### ISSUE TITLE
PossiblyUndefinedVariable

### ISSUE THREAD

**Issue by janhanacek1** [vimeo/psalm#10017]
Dear psalm dev team,
following correct code ends with error, but same variable cannot have different value. 

Could you solve it, please? 

```

$condition = \random_int( 1, 5 ) > 2;
if( $condition ) {
	$foo = 1;
}

if( $condition ) {
	$bar = $foo + 8;
}

```

ERROR: PossiblyUndefinedVariable
Possibly undefined variable $foo, first seen on line xx (see https://psalm.dev/018)
$bar = $foo + 8;

**Comment by ygottschalk** [comment]
possibliy the same as #10020
