### ISSUE TITLE
static with `!isset` intialization block

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1001]
Currently psalm doesn't understand this pattern

```
static $data;
if (!isset($data)) {
    $data = 42;
}

// no type information for $data here
```

**Comment by muglug** [comment]
This is a hard problem - the issue is that `$data` can have all sorts of values set all over the place, and Psalm doesn't currently have the means to restrict those values.

**Comment by fesor** [comment]
In global context - yes. But usually this pattern is applied inside function's local context. So type of this variable could be inferred.

**Comment by muglug** [comment]
Closing, dupe of https://github.com/vimeo/psalm/issues/678
