### ISSUE TITLE
TaintedEval on mysqli_result::fetch_assoc

### ISSUE THREAD

**Issue by cgocast** [vimeo/psalm#10011]
I wish to declare `mysqli_fetch_assoc` and `mysqli_result::fetch_assoc` as sources for TaintedEval. Therefore, I wrote this little stub file:
```
<?php

/**
 * @psalm-taint-source eval
 */
function mysqli_fetch_assoc(mysqli_result $result): array|null|false {}


class mysqli_result
{
    /*
     * @psalm-taint-source eval
     */
    public function fetch_assoc(): array|null|false {}
}
```

When I test it on this source code:
```
function eval_fetched_code_procedural(mysqli_result $result) : void {
    $row = mysqli_fetch_assoc($result);
    $code = $row["code"];
    eval($code);
}

function eval_fetched_code_object(mysqli_result $result) : void {
    $row = $result->fetch_assoc();
    $code = $row["code"];
    eval($code);
}
```
I only get the error on `mysqli_fetch_assoc` and no error on `mysqli_result::fetch_assoc`:
```
ERROR: TaintedEval - tests/checkmarx/stored_code_injection.php:6:10 - Detected tainted code passed to eval or similar (see https://psalm.dev/252)
  mysqli_fetch_assoc - tests/checkmarx/stored_code_injection.php:4:12
    $row = mysqli_fetch_assoc($result);

  $row - tests/checkmarx/stored_code_injection.php:4:5
    $row = mysqli_fetch_assoc($result);

  $row['code'] - tests/checkmarx/stored_code_injection.php:5:13
    $code = $row["code"];

  $code - tests/checkmarx/stored_code_injection.php:5:5
    $code = $row["code"];


------------------------------
1 errors found
------------------------------
```

I tried several variants of my little stub file without any result. Please, can you tell me what should I fix in order to get a TaintedEval on `mysqli_result::fetch_assoc` ?

**Comment by ygottschalk** [comment]
Can you provide a reproducer? Some small repo containing the analyzed file, the psal config, your stub, etc...

**Comment by cgocast** [comment]
Thank you @ygottschalk for you answer.

You can find all you asked for in this repository: https://github.com/cgocast/psalm-10011

**Comment by cgocast** [comment]
Hi @ygottschalk, were you able to reproduce with the repository I provided ?

**Comment by ygottschalk** [comment]
Sry I havent had the time to look into it... Maybe I got some time spare next weekend...

**Comment by cgocast** [comment]
I found the issue. I used a regular comment block /* instead of a DocComment block /**.

@ygottschalk I am sorry for taking your time for such a stupid mistake.

**Comment by ygottschalk** [comment]
@cgocast no worries, we've all been there =D
