### ISSUE TITLE
`RedundantCondition` for `BackedEnum` once checked all enum cases

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#10054]
Hey there,

I do have a function which should provide me some data based on enum values.
To avoid having unhandled enum values or even invalid handling, I add dedicated `if` statements for every enum case.

Once I reach the very last, psalm tells me that the condition is always true and thus redundant even tho, an enum can be extended at some point in time. It feels like psalm recommends to remove the always true condition, but for me, that might lead to issues once the enum is being extended.

For example:

https://psalm.dev/r/c285b1d9a1

----

If I follow the current "suggestion", I have to remove the last condition and the `RuntimeException`. Once I did that, psalm does not complain anymore. 

https://psalm.dev/r/5bd09be4f3

But psalm does also not complain once I add an additional ENUM case, i.e. `ARCHIVE`:

https://psalm.dev/r/cfaa29bccd

The problem is, that there is no feedback at all and I do potentially have a bug since all archive actions are actually delete actions.
With the previous implementation (i.e. redundant condition), that was not possible.

I am aware that I can add suppressions to avoid this, but we do have developers who are not that familiar with all these suppressions and thus, I wonder if there is a way to avoid the `RedundantCondition` for enums.

---- 

Another bug I see with the first example is that the `$fileAction->value` backend enum value is inferred as `mixed` even tho, the `BackedEnum` type is explicitly set to `string`.

**Comment by ygottschalk** [comment]
I was bothered a long while ago with a smilar thing. I wanted to have 'safety' default cases which would be, in theory, never executed and were tagged by psalm with `ParadoxicalCondition`.

If you really want to go without supression, this could be your way: https://psalm.dev/r/9aca5238d0

> Another bug I see with the first example is that the $fileAction->value backend enum value is inferred as mixed even tho, the BackedEnum type is explicitly set to string.

In that case (after eliminating all possible enum cases), the type of `$fileAction` is `never`, therefore all property accesses will result in `mixed`. It's not a bug, it's a feature :D

**Comment by boesing** [comment]
@weirdan Yah, I just created a simpler use-case. I do have an object passed to the factory having data depending on the enum value and thus I can't just use `match` as I do have to handle dedicated properties based on the action :-/

@ygottschalk TIL, wasn't ware of the `psalm-check-type-exact`. However, this feels a bit too specific IMHO. So yah, it works, but not sure if I do want to implement it this way :-/

**Comment by weirdan** [comment]
In that case I would split complex match arms in private methods

**Comment by boesing** [comment]
I actually switched my code to `match` and added a method for the more complex match case. works as expected and properly reports `UnhandledMatch` (or whatever the issues name is) for new enum entries.

Thanks for the feedback and for helping me improving our codebase.
