### ISSUE TITLE
Regression: ArgumentTypeCoercion non-empty-string despite checks

### ISSUE THREAD

**Issue by ivoba** [vimeo/psalm#10056]
After upgrading psalm from "5.4.0" to "5.13.1" i get this error:

> Argument 1 of explode expects non-empty-string, but parent type string provided 

This used to work before and the code seems correct to me:

https://psalm.dev/r/4eb9f52b40

**Comment by colinodell** [comment]
I'm also experiencing this regression with the following simplified examples:

 - https://psalm.dev/r/4465ae002f: a function returning a hard-coded string
 - https://psalm.dev/r/a3767bdf39: a hard-coded string set on a class property

The regression seems to have been introduced sometime after version 5.12.0.

**Comment by orklah** [comment]
This is an evolution rather than a regression. PHP will emit a warning when passing an empty string to explode: https://3v4l.org/7eJkA or preg_match: https://3v4l.org/euMBO

So Psalm now requires that you explicitly declares your input as non-empty

**Comment by colinodell** [comment]
Ah, thanks for explaining that Psalm now checks for non-empty strings where appropriate.  That's really helpful!

Unfortunately, the issue we're having is that **Psalm is failing to detect when a string is non-empty**, which means this new feature is creating false positives.  Here are six examples showing this issue: https://psalm.dev/r/928c4467c6 It would be nice if Psalm could automatically detect those as non-empty for me so I don't need to litter my codebase with `/** @psalm-var non-empty-string */` hints :-/

It would be especially helpful if Psalm could auto-detect these two scenarios:

1. String variables guarded by `if (strlen($str)) { ... }` checks ([PHPStan supports this](https://phpstan.org/r/3c6f0e2c-3991-41cd-9ef7-86e02ae54202))
2. `non-empty-string` types returned from a function

This would avoid most (perhaps all) of the false-positives I'm seeing in the libraries I maintain.

**Comment by orklah** [comment]
Indeed, strlen could be supported, you can create an issue for that :)

About function calls, that's not how SA tools work, you should document your function inputs and outputs as fine as you could so that tools like Psalm and PHPStan can take those metadata and work with it: https://psalm.dev/r/bba89100c3

So yeah, basically, strlen is left
