### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by siganushka** [vimeo/psalm#10078]
How to fix this error?

![image](https://github.com/vimeo/psalm/assets/45844370/7043547d-36d1-4e30-ac5d-bd10b4bf7231)

https://github.com/siganushka/generic-bundle/actions/runs/5715546923/job/15485110795#step:11:29

This indicates that the class or interface does not exist, but the ``AbstractObjectNormalizer`` class exists in the source repository.

https://github.com/symfony/serializer/blob/6.3/Normalizer/AbstractObjectNormalizer.php

**Comment by siganushka** [comment]
I understand what you mean, when PHP 8.2 version, dependency `symfony/serializer` will install 6.3 version, class or interface `AbstractObjectNormalizer` still exists.

PHP 7.4
https://github.com/symfony/serializer/blob/5.4/Normalizer/AbstractObjectNormalizer.php

PHP 8.2
https://github.com/symfony/serializer/blob/6.3/Normalizer/AbstractObjectNormalizer.php

**Comment by weirdan** [comment]
When you have 6.3 being analyzed with PHP 7.4 `AbstractObjectNormalizer` contains syntax errors (`readonly` properties weren't a thing in PHP 7.4). So it's as good as being absent. Use `--php-version`.

**Comment by siganushka** [comment]
Ok thanks, I think so!
