### ISSUE TITLE
Strlen as guard for non-empty-string

### ISSUE THREAD

**Issue by ivoba** [vimeo/psalm#10072]
Followup ticket for https://github.com/vimeo/psalm/issues/10056 :

A condition with a `Strlen` check should be regarded as valid guard for `non-empty-string` warning.

See: https://psalm.dev/r/bba89100c3

**Comment by orklah** [comment]
Thanks for creating the issue!

If you're interested for looking into it, we basically did the same thing for count on arrays here: https://github.com/vimeo/psalm/blob/fa644cbb3487a7e79d614c32857d95728cefabae/src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php#L850
