### ISSUE TITLE
PropertyNotSetInConstructor cannot be ignored on a constructor

### ISSUE THREAD

**Issue by duskwuff** [vimeo/psalm#1008]
Classes which initialize properties in ways that Psalm doesn't recognize will trigger a `PropertyNotSetInConstructor` issue. Ideally it would be possible to suppress this issue on the initializer, but this doesn't seem to work:

```
class IndirectPropertyInitializer {
    /** @var int */
    public $foo;

    function __construct() {
        /** @psalm-suppress PropertyNotSetInConstructor */
        foreach (["foo"] as $prop) {
            $this->$prop = 123;
        }
    }
}
```

Suppressing the issue on the property declaration does work, but this is awkward for classes which have many properties, all of which are initialized indirectly.

**Comment by weirdan** [comment]
You can suppress it in the class docblock though: https://getpsalm.org/r/f134c80355

**Comment by duskwuff** [comment]
Aha! Perfect, thanks.
