### ISSUE TITLE
UnexpectedValueException: Expecting a version number in the format x.y

### ISSUE THREAD

**Issue by AndreyMZ** [vimeo/psalm#10084]
### Steps to reproduce
1. Set [`phpVersion`](https://psalm.dev/docs/running_psalm/configuration/#phpversion) to `"5.1"` in the configuration file.
2. Run Psalm.

#### Actual result
~~~
Uncaught UnexpectedValueException: Expecting a version number in the format x.y in /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php:1174
Stack trace:
#0 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/CliUtils.php(500): Psalm\Internal\Analyzer\ProjectAnalyzer->setPhpVersion('5.1', 'config')
#1 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(349): Psalm\Internal\CliUtils::initPhpVersion(Array, Object(Psalm\Config), Object(Psalm\Internal\Analyzer\ProjectAnalyzer))
#2 /opt/psalm/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
#3 /opt/psalm/vendor/bin/psalm(119): include('/opt/psalm/vend...')
#4 {main}
(Psalm 5.11.0@c9b192ab8400fdaf04b2b13d110575adc879aa90 crashed due to an uncaught Throwable)
~~~

#### Expected result
1. No uncaught exception, no stack trace.
2. Correct error message telling that PHP 5.1 specified in the configuration file "<filepath>.xml" is not supported by Psalm, and only PHP 5.4-5.6, 7.0-7.4, 8.0-8.2 are supported.

### Root cause
https://github.com/vimeo/psalm/blob/dc8163011d4afb3b8eb638a4990b1c8e62a08f2f/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php#L1182-L1184

### Additional information
The error message is also wrong because actually version numbers in the formats x.y.z (e.g. "8.2.8") are also expected.

**Comment by weirdan** [comment]
Feel free to PR.
