### ISSUE TITLE
Remove "test" ExecuteCommandOption

### ISSUE THREAD

**Issue by limarkxx** [vimeo/psalm#10094]
At https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/LanguageServer/LanguageServer.php#L422
there is `$serverCapabilities->executeCommandProvider = new ExecuteCommandOptions(['test']);`, what appears to be a test-call of the workspace/executeCommand LSP feature.
This doesn't affect the first LSP in VSCode, but if you have multiple instances the subsequent LSP clients fail during initialization with 
```
[Error - 9:23:14 PM] Server initialization failed.
Error: command 'test' already exists
	at a.registerCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:76383)
	at Object.registerCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:120:20180)
```

**Comment by limarkxx** [comment]
> Hey @limarkxx, can you reproduce the issue on https://psalm.dev ?

It's not possible to instantiate multiple LSP instances there.

**Comment by tm1000** [comment]
@limarkxx I think we can just remove that. Perhaps it was left by me? 

If that line is removed does it fail in another place?

**Comment by limarkxx** [comment]
Maybe https://github.com/vimeo/psalm/commit/427ff3a018e1d57feb30de9ce6e4cb4da69e4b69#diff-cbb599c443d206c9d474890996dd092fada08e9190b9a2c90e7eb24325825ee5R457 is related?

**Comment by weirdan** [comment]
I don't think `Fix all` ever worked in LSP context.

**Comment by tm1000** [comment]
It did not that was me trying to figure out how to get it to work though it shouldnt even show up. Regardless it should be removed along with the test command
