### ISSUE TITLE
False positive InvalidArrayOffset with Enum name

### ISSUE THREAD

**Issue by blackwolf12333** [vimeo/psalm#10090]
When you use the name of an enum value as check in an `isset` in an array you get an error that an option in the enum that is not defined in the array that's indexed exists. However that's what the `isset` check is there for, so this shouldn't report an error.

The reproducer below shows the issue clearly

https://psalm.dev/r/50c582c00b

**Comment by weirdan** [comment]
It's actually because we think `$val->name` can only be `BOAT`: https://psalm.dev/r/fb7b222271
