### ISSUE TITLE
class-string-map is not working as documented

### ISSUE THREAD

**Issue by stof** [vimeo/psalm#10095]
The documentation shows `class-string-map<T of Foo, SomethingBasedOn<T>>` while the working syntax is `class-string-map<T as Foo, SomethingBasedOn<T>>`. It looks like `of` does not work there, only `as` (unlike in `@template`).

**Comment by stof** [comment]
see https://psalm.dev/r/6f7e81fe99 for a reproducer, which is literally a copy-paste of the example in the documentation of `class-string-map`

**Comment by weirdan** [comment]
Fixed in #10326
