### ISSUE TITLE
Add pass by reference variable constraints

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#101]
When variables are passed by reference, Psalm cannot do much about them. It assumes, optimistically, that if a function parameter is passed by reference, that function parameter's type does not change in the body of the function e.g.

```php
function changeInt(int &$a) {
  $a = "hello";
}

$a = 5;
changeInt($a);
// Psalm assumes $a is still an int
```

Obviously optimism isn't sufficient for decent type analysis. Instead, we should register type constraints in the current `Context` and emit an issue if that constraint is violated e.g.:

```php
class A {
  /** @var int */
  private $foo;

  public function __construct(int &$foo) { // $foo is constrained to an int
    $this->foo = &$foo;
    $foo = "hello"; // ReferenceConstraintViolation issue emitted
  }
}

$bar = 5;
$a = new A($bar); // $bar is constrained to an int
$bar = null; // ReferenceConstraintViolation issue emitted
```

A special case arises if we have a variable constrained in different branches of an `if` statement:

```php
class A {
  /** @var int */
  private $foo;

  public function __construct(int &$foo) { // $foo is constrained to an int
    $this->foo = &$foo;
  }
}

class B {
  /** @var string */
  private $bar;

  public function __construct(string &$bar) { // $bar is constrained to a string
    $this->bar = &$bar;
  }
}

if (rand(0, 1)) {
  $v = 5;
  $c = (new A($v)); // $v is constrained to an int
} else {
  $v = "hello";
  $c =  (new B($v)); // $v is constrained to a string
}

$v = 8; // ContradictoryReferenceConstraints issue emitted
```

**Comment by Fleshgrinder** [comment]
This looks good to me. Are all reference assigned values tracked as well, e.g. what happens in this example:

```
class A {
  /** @var int */
  private $foo;

  public function __construct(int &$foo) { // $foo is constrained to an int
    $this->foo = &$foo;
    $this->foo = "hello"; // ReferenceConstraintViolation issue emitted?
  }
}

$bar = 5;
$a = new A($bar); // $bar is constrained to an int
$bar = null; // ReferenceConstraintViolation issue emitted
```

**Comment by muglug** [comment]
@fleshgrinder reference assigned values are not currently tracked - so `$this->foo` would still be treated as an `int`, even after the pointer has its value changed. Psalm should support locking types together, but it doesn't yet. I've created #103 to track.
