### ISSUE TITLE
override array<never, never>

### ISSUE THREAD

**Issue by chou666** [vimeo/psalm#10118]
See sample: https://psalm.dev/r/f2796a7ced

I cannot resolve the error, even if I add 

`@psalm-suppress  InvalidClassConstantType `

An idea ?

**Comment by weirdan** [comment]
You can use `@var` to specify the expected type: https://psalm.dev/r/dd55d7af6e

**Comment by chou666** [comment]
Thanks for the tip but the abstract class is an external file I cannot add the annotation

**Comment by chou666** [comment]
Merge request proposed in Symfony project
