### ISSUE TITLE
Feature: Immutable object via getters

### ISSUE THREAD

**Issue by Legion112** [vimeo/psalm#10113]
# Issue name: "Immutable object via getters"

## Problem
Developer write much code to create an immutable object which contains many lines
```php
class StatusEvent
{
    public function __construct(
        private readonly string $newValue,
    ) {
    }

    public function getNewValue(): string
    {
        return $this->newValue;
    }
}
```
### Details
If the object is an **immutable** class that accepts the parameter and **only exposes** The state via getters might be wise to suggest using a public read-only property

By only expose I mean it does not do anything else except return value from "getter" methods

## Solution
```php
class StatusEvent
{
    public function __construct(
        public readonly string $newValue,
    ) {
    }
}
```

Define property as public, readonly gives you the same guarantee object will never chain state. 

You save about 5 lines per property - that is a lot 

To access property

```php
/** @var StatusEvent $a */
$a->newValue;
```

### Alternative
Maybe this has to be implemented as code code-style rule in phpcs or another alternative.

**Comment by weirdan** [comment]
I believe this is completely a style issue, and this is out of scope for Psalm. IMHO Transformations like this are best handled via Rector (phpcs API is too low level).
