### ISSUE TITLE
UnusedFunctionCall with openssl_pkey_export_to_file & openssl_x509_export_to_file

### ISSUE THREAD

**Issue by LauraTaylorUK** [vimeo/psalm#10119]
Hey everyone,

When I generate a self-signed certificate, the two calls to save the key and the certificate generate UnusedFunctionCall errors:

https://psalm.dev/r/864a429ed9

This is perfectly fine PHP code which calls both functions without problems, the error seems wrong.

Thank you.

**Comment by robchett** [comment]
@LauraTaylorUK this issue is resolved and the snippet is returning "No issues!"
