### ISSUE TITLE
Psalm producing Error on good code

### ISSUE THREAD

**Issue by rotexdegba** [vimeo/psalm#10124]
I am getting the error below when I run psalm on https://github.com/rotexsoft/versatile-acl . Could you guys please try running it to let me know what I need to fix this or is this a bug with psalm?

![image](https://github.com/vimeo/psalm/assets/1242622/3e865889-2571-4ba7-998c-03dadc0d6b95)

**Comment by rotexdegba** [comment]
> Hey @rotexdegba, can you reproduce the issue on https://psalm.dev ?

https://psalm.dev/r/47feb2cc74

**Comment by weirdan** [comment]
`IteratorAggregate` is a generic interface, so you must specify its generic parameters:

https://psalm.dev/r/b4bd96ded6

It's likely your `CollectionInterface` could benefit from being generic as well, so you may want to read up on templating: https://psalm.dev/docs/annotating_code/templated_annotations/
