### ISSUE TITLE
Recent commit breaks psalm

### ISSUE THREAD

**Issue by vlakarados** [vimeo/psalm#10132]
Recently psalm stopped working, throwing 

    Uncaught Exception: InvalidArgumentException Could not get class storage for spaze\phpstan\rules\disallowed\allowed\allowdirectivesconfig
     Emitted in /.../vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45 
    .......

    (Psalm dev-master@a4de6d9dc092d77871b6097af42498a192362e9a crashed due to an uncaught Throwable)

It is thrown on dozens of different repositories which have typehints or classes that are not present. In example above PHPAT surely has a problem, but it should not kill psalm, especially as psalm configuration has `<ignoreFiles><directory name="../vendor"/>`.

More so it's thrown on libraries that have optional dependencies, in my case psalm throws the same error on Monolog for the ElasticSearch code (I don't have elastic search as I don't use it, but it's supported by Monolog):

    Uncaught Exception: InvalidArgumentException Could not get class storage for elastic\elasticsearch\response\elasticsearch
    Emitted in /home/stelshevsky/work/projects/jefe/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45

After requiring different psalm versions (`./composer.phar require --dev vimeo/psalm:dev-master#a4de6d9dc092d77871b6097af42498a192362e9a --with-d
ependencies`), seems this commit causes this:
https://github.com/vimeo/psalm/commit/a4de6d9dc092d77871b6097af42498a192362e9a

Any older version does not have this issue.

**Comment by weirdan** [comment]
> seems this commit causes this: https://github.com/vimeo/psalm/commit/a4de6d9dc092d77871b6097af42498a192362e9a

I don't see anything in that commit that would change the behaviour you describe. Would you mind to create a reproducer in a separate repo (and ideally do a proper bisect)?

**Comment by spaze** [comment]
Hi, I'm the author of spaze/phpstan-disallowed-calls package mentioned in the first error message.

The class specified at
https://github.com/spaze/phpstan-disallowed-calls/blob/c7a80cc9747e6307bfa6f5ea88ed3f9b1804790c/src/Allowed/Allowed.php#L179
indeed doesn't exist but `AllowDirectivesConfig` is a [global type alias](https://phpstan.org/writing-php-code/phpdoc-types#global-type-aliases) defined here https://github.com/spaze/phpstan-disallowed-calls/blob/c7a80cc9747e6307bfa6f5ea88ed3f9b1804790c/phpstan.neon#L12

I don't know whether Psalm supports type aliases but it may explain this particular problem if not.

**Comment by vlakarados** [comment]
I will try reproducing it during the week, it's not directly related to the missing class as psalm is configured to ignore errors in the vendor directory.

**Comment by vlakarados** [comment]
Actually took much less time:
https://github.com/vlakarados/psalmtest

Composer update/install and

    ./vendor/bin/psalm --config=psalm.xml .

    Uncaught Exception: InvalidArgumentException Could not get class storage for elastic\elasticsearch\response\elasticsearch
    Emitted in /home/stelshevsky/work/sandbox/psalmtest/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45


![image](https://github.com/vimeo/psalm/assets/386678/437b5296-39a3-4e70-80f3-70a531b70644)

**Comment by weirdan** [comment]
One immediate observation: you _don't_ need to pass `.` as an argument (`--config=psalm.xml` is also redundant, as `psalm.xml` is picked by default). Passing `.` makes Psalm analyze all files in the current folder, including the `vendor` folder. When you don't do that, Psalm both runs faster and doesn't crash:

![image](https://github.com/vimeo/psalm/assets/57403/ea4a0ac8-2f6b-493b-aa0f-9c4374803bcf)

**Comment by vlakarados** [comment]
Thank you for the tips, but does it still scan folder in case it's not in analysis scope?
Besides running faster, I see no errors this way as well, but still the commits linked in the first comment are causing errors if run on the vendor directory

**Comment by weirdan** [comment]
> does it still scan vendor folder for type hints in case it's not in analysis scope?

Yes, but we don't look into method bodies in this case. And the crash happens when we analyze these lines (in a method body):
https://github.com/Seldaek/monolog/blob/9546d94bdc212214e23aa7ea5a3734417e33e5e1/src/Monolog/Handler/ElasticsearchHandler.php#L180-L183

I managed to reproduce the crash without having to analyze `vendor` (and without any external dependencies), so the report is valid and we will be looking into this.

```php
<?php

namespace Psalmtest\Psalmtest;

use SomeMissingClass;

class Test
{
  public function f(): void {
    /** @var SomeMissingClass */
    $result = null;

    if ($result['errors'] === true) {}
  }
}
```

Bisect indeed points at a4de6d9dc092d77871b6097af42498a192362e9a

**Comment by weirdan** [comment]
> I don't see anything in that commit that would change the behaviour you describe.

Ah, now I see. There was a call to `classExtendsOrImplements()` added without checking the symbol existence first.

/cc: @ygottschalk

**Comment by weirdan** [comment]
There's no crash with latest `master` anymore. And, to reiterate, don't run `psalm .`, you're forcing it to do way more than it is necessary:

![image](https://github.com/vimeo/psalm/assets/57403/fa7c57a9-5a0a-430d-a38c-4dceec60fb18)

**Comment by vlakarados** [comment]
Thank you, can no longer reproduce and big thanks for the tip on omitting the target folder

**Comment by vlakarados** [comment]
Interestingly enough, without the dot, psalm found A LOT of unused properties

**Comment by weirdan** [comment]
> Interestingly enough, without the dot, psalm found A LOT of unused properties

That's expected. When you specify any paths (including `.`) Psalm assumes it isn't going to check the entire project and unused code detection only works when checking the entire project. There's also a warning telling you exactly this (you can see it on the screenshot above):

![image](https://github.com/vimeo/psalm/assets/57403/2ec9a306-6f46-4259-8bb1-45cd14445263)

**Comment by vlakarados** [comment]
Thank you, clear. Despite being offtopic, but I struggle to find any information on if it's possible to suppress unused* errors for inherited classes or implementing an interface? In my case I now have almost 200 errors popped up due to having entities/value objects with public properties that are used by hydration/dehydration processes, and never explicitly referenced. As I plan to have them for a pretty big database (450 tables) as well as for transferring queue messages, explicitly suppressing error in each of the classes seems like a PITA and boilerplate-ish. Maybe any other solution to their suppression?

**Comment by weirdan** [comment]
If they are under the same namespace, `referencedClass` (https://psalm.dev/docs/running_psalm/dealing_with_code_issues/#config-suppression) supports primitive regexps. Something like this should work:
```xml
<issueHandlers>
  <UnusedClass>
    <errorLevel type="suppress">
       <referencedClass name="Applications\Dto\*"/>
    </errorLevel>
  </UnusedClass>
</issueHandlers>
```

**Comment by vlakarados** [comment]
Too bad, but they are not.

I tried going the plugin way:

```php
class PsalmSuppressor implements AfterClassLikeVisitInterface
{
        public static function afterClassLikeVisit(AfterClassLikeVisitEvent $event)
    {
        $storage = $event->getStorage();
        if ($storage->user_defined && !$storage->is_interface && \class_exists($storage->name)) {
            $c = new ReflectionClass($storage->name);
            if ($c->getParentClass() && $c->getParentClass()->getName() === Entity::class) {
                $storage->suppressed_issues[] = 'PossiblyUnusedProperty';
            }
            if ($c->implementsInterface(MessageHandler::class)) {
                $storage->suppressed_issues[] = 'UnusedParam';
            }
        }
    }
}
```

It works for the PossiblyUnusedProperty, but does not work for UnusedParam  - the `if` statement works, but it doesn't get suppressed, probably because it's not class related, but method related. I'm failing to understand how can I suppress the error for other events as they don't have the same `->getStorage()` method, or is there something I'm doing wrong fundamentally?

**Comment by weirdan** [comment]
> Too bad, but they are not.

`UnusedClass` definitely does; I've just tested it to make sure it does. Property issues may not support regexp suppressions. It shouldn't be hard to add, though, see
https://github.com/vimeo/psalm/blob/948dd1a89ee361e9c235996425b4d8f46a40d588/src/Psalm/Config/FileFilter.php#L610-L613
and
https://github.com/vimeo/psalm/blob/948dd1a89ee361e9c235996425b4d8f46a40d588/src/Psalm/Config/FileFilter.php#L355-L360

You'd want to handle them similarly to `referencedMethod`. Feel free to send a PR.
