### ISSUE TITLE
Analysis stops processing after UndefinedClass error

### ISSUE THREAD

**Issue by jorgsowa** [vimeo/psalm#10140]
I have the following code and after the line with the `UndefinedClass` error psalm doesn't detect the next errors.

https://psalm.dev/r/9825d8ce93

**Comment by weirdan** [comment]
Pretty much anything could have happened in that `Manager::autoload()` call. If Psalm can't see it, it basically cannot continue the analysis.

Either fix the issue that prevents Psalm from finding that class, or provide a stub for that class (https://psalm.dev/docs/running_psalm/configuration/#stubs)
