### ISSUE TITLE
Could not get class storage for stdClass 

### ISSUE THREAD

**Issue by mxr576** [vimeo/psalm#1016]
After upgraded to 2.0.14 from 2.0.13 I keep getting this error.

```
> psalm --config=psalm.xml.dist --show-info=false --stats
Scanning files...
Analyzing files...
[11-Oct-2018 09:03:56 Europe/Budapest] PHP Fatal error:  Uncaught InvalidArgumentException: Could not get class storage for stdClass in /var/www/html/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:35
```

https://travis-ci.org/mxr576/apigee-client-php/jobs/439992829#L814

**Comment by muglug** [comment]
Sorry about this - I wanted to eliminate any unnecessary rescanning happening in the analysis phase, and this was a casualty of that. The fix makes sure to add `stdClass` to the set of classes Psalm knows about in the scanning step.

**Comment by mxr576** [comment]
Thanks for the quick fix!
