### ISSUE TITLE
`@psalm-inheritors` does not catch error at class declaration

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#10167]
Took an example from the [documentation](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-inheritors): https://psalm.dev/r/0d2892f51f

No issues are reported

**Comment by weirdan** [comment]
Looks like it's only processed when the class is instantiated (all tests for this issue are like that).

https://psalm.dev/r/06e1310c0b

**Comment by weirdan** [comment]
> Looks like it [inheritor violation] is only processed when the class is instantiated (all tests for this issue are like that).

@robchett is this how it was intended to be?

**Comment by someniatko** [comment]
> Looks like it's only processed when the class is instantiated

Hmm, I see, this shifts responsibility to the class clients rather to class declaration though. For example, if it is a library which defines a class, IMO it's library maintainer's responsibility to make sure his hierarchy is properly defined, not library user's (if a user is the party who creates the class instance). Anyways, even if it's the intended behavior, then the docs should be updated to be more accurate about where the actual error occurs.

**Comment by weirdan** [comment]
This doesn't look very useful to me either, thus the question above.

**Comment by robchett** [comment]
No, I would say this is not the intention of the annotation. 

I'll try and find some time to debug this, but at a quick glance I can see the violation is thrown in the same place that MissingDependency and InvalidClass are, which do work as expected. Leave it with me

**Comment by someniatko** [comment]
@robchett Thank you for the fast reaction :D
