### ISSUE TITLE
uksort false positive

### ISSUE THREAD

**Issue by MoonE** [vimeo/psalm#10174]
`strnatcasecmp` only accepts string arguments, but PHP runs this code without error. The `uksort` function passes all keys as strings even if they are numeric.
https://psalm.dev/r/1494673480

**Comment by weirdan** [comment]
Generally speaking, Psalm flags type mismatches for calls from `strict_types=0` code, even though they won't cause runtime errors: https://psalm.dev/r/d6d2a9aee2, https://3v4l.org/dqj5u. All calls from inside the engine (think callbacks provided to `array_map()`, `uksort()` and so on) are done in `strict_types=0` mode. So I'd say it's working consistently and as expected.
