### ISSUE TITLE
DoS by sleep

### ISSUE THREAD

**Issue by cgocast** [vimeo/psalm#10178]
The following piece of code is vulnerable to Denial of Service attacks
```
<?php

sleep($_GET["seconds"]);
```

Psalm returns no issue when run with --taint-analysis.

I'll write a PR in 6.x that raises a new issue named TaintedSleep

**Comment by cgocast** [comment]
I am not sure to understand you. Do you mean that if we pass $_GET to [max](https://www.php.net/manual/en/function.max), then psalm should raise an error ?

**Comment by weirdan** [comment]
https://psalm.dev/r/fd07c5e482

Fixed in #10183
