### ISSUE TITLE
SIGTERM must be sent before pcntl_waitpid when ending forked processes in Sublime Text

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#1022]
Have encountered this when Psalm is spawned from a Sublime `plugin_container` process. 

This line:
https://github.com/vimeo/psalm/blob/13cc3b47519bba1a28f873ff51dec6c9170a2222/src/Psalm/Fork/Pool.php#L262 hangs indefinitely.

The child process has already called `exit`, but it somehow still exists.

The only (Unix-specific) workaround I've found is to add a specific `posix_kill($child_pid, SIGTERM);` beforehand.

@TysonAndre have you seen something similar with Phan's language server?

**Comment by TysonAndre** [comment]
https://github.com/phan/phan/pull/2054 may be related. I recently discovered a bug in the language server

If they're zombie processes, you may want to ensure pcntl_signal is called to add a signal handler, and pcntl_signal_dispatch to handle the SIGCHILD from the child process.

- I'm not sure if not handling SIGCHILD from the child process will help or not. It may do nothing.
- I think that the Fork pool should **also** handle sigchild from child processes

My approach was to discourage using fork pools and the language server simultaneously

**Comment by muglug** [comment]
Thanks - all this is very new to me. I've ended up going for a `SIGALRM` message instead of `SIGTERM`. It seems like an ok hack.

I still don't understand what the process is doing after `exit` is called. :/

**Comment by muglug** [comment]
If you're up for it, would you mind emailing me at `github@muglug.com`? I'd like to have a line of discussion that's less formal than GitHub tickets, especially when discussing Language Server things where you have a lot more experience.

**Comment by TysonAndre** [comment]
I sent an email - Having a record of the discussion might help other people understand the code in the future, or help others writing language servers in PHP.

**Comment by muglug** [comment]
Huh - that didn’t seem to make its way through. My main interest is to discuss things that would count as noise to most observers.

Anyway, this ticket seems to have solved itself - at least I haven’t seen this issue when running the language server recently.
