### ISSUE TITLE
EmptyArrayAccess after checking if key exists

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#10229]
https://psalm.dev/r/9b6ace575a

**Comment by robchett** [comment]
I'm not aware of a way that `Foo::BAR` could have any keys as it is declared as `const`. 
Do you have an example setup where Psalm is wrong and `array_key_exists` isn't always going to return false.

**Comment by sanmai** [comment]
Great point! I changed it from `self::` to `static::` and the problem went away.
