### ISSUE TITLE
Missing TaintedSql for tainted integers

### ISSUE THREAD

**Issue by cgocast** [vimeo/psalm#10238]
This code snippet https://psalm.dev/r/0d4f65473b is a slight modification of the snippet given in the TaintedSql documentation https://psalm.dev/docs/running_psalm/issues/TaintedSql/ The cast to string has been changed to a cast to int.

An attacker could delete thousands of users from the table by doing multiple GET requests with a range of "user_id". Therefore I would expect that Psalm raises a TaintedSql, even if this code snippet is not vulnerable to classical SQL injection.

I'll write a PR to fix this issue.

**Comment by orklah** [comment]
You may want to look at https://github.com/vimeo/psalm/pull/6993/files

I assumed back then that some types could not transmit taints, the rule may be more complex than that then

**Comment by cgocast** [comment]
Thank you @orklah for the interesting link.

In my opinion, which type transmit taints or not depends on the issue. For instance, numerics shoud transmit taints TaintedSql, but they should not for TaintedHtml.

Of course there will be some specific SQL queries where integers are safe. But I prefer those case to be handled with a `@psalm-taint-escape sql` annotation
