### ISSUE TITLE
stream_socket_shutdown & socket_shutdown call is not used

### ISSUE THREAD

**Issue by LauraTaylorUK** [vimeo/psalm#10235]
Hello!

An error is reported for the following two functions:
- stream_socket_shutdown
- socket_shutdown

The error is:
UnusedFunctionCall - The call to socket_shutdown is not used (see https://psalm.dev/206)
UnusedFunctionCall - The call to stream_socket_shutdown is not used (see https://psalm.dev/206)

This is wrong, since both functions can be used without doing anything with the returned result.

Thank you.

**Comment by orklah** [comment]
This can be fixed by adding those here:
https://github.com/vimeo/psalm/blob/db07b05156d3a5f65e09000999acb6ae47f05634/dictionaries/ImpureFunctionsList.php
