### ISSUE TITLE
Psalm shows minimal output when run via GitHub Actions

### ISSUE THREAD

**Issue by mmcev106** [vimeo/psalm#10250]
@ro0NL, version 5.14.0 included commit #8ed4f94 which changed the output format when Psalm is run via GitHub Actions.  This broke our unit tests until I tracked it down and unset `GITHUB_ACTIONS` prior to running our Psalm related tests.

Was this change intended to affect all downstream projects that run Psalm via GitHub Actions?  If it was only intended to affect Psalm itself's tests, then I wonder if we should set a new environment variable to control this instead (in Psalm's Github Action configuration).

**Comment by mmcev106** [comment]
Nope

**Comment by ro0NL** [comment]
yes, intended https://github.com/vimeo/psalm/pull/9982

you can specify the output format explicitly: https://github.com/vimeo/psalm/blob/69d5881d56341de735a2fcf1e579ccafa79f29af/tests/EndToEnd/PsalmRunnerTrait.php#L27-L30

i didnt expext downstream would assert it :joy_cat: excusi

(i do think current default behavior is the right one)

**Comment by mmcev106** [comment]
Thanks for the quick response!  Understood, closing...
