### ISSUE TITLE
Incorrect parsing of variable-length argument list

### ISSUE THREAD

**Issue by danherd** [vimeo/psalm#1027]
Given the following function:

```
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  string[]  ...$guards
     * @return mixed
     *
     * @throws \Illuminate\Auth\AuthenticationException
     */
    public function handle($request, Closure $next, ...$guards)
    {
        $this->authenticate($request, $guards);

        return $next($request);
    }
```

The following call to it should be fine, should it not?

`return $this->authenticate->handle($request, $next, 'api');`

But psalm claims:

```
ERROR: InvalidArgument - app/Http/Middleware/AccessTokenChecker.php:37:65 - Argument 3 of Illuminate\Auth\Middleware\Authenticate::handle expects array<mixed, string>, string(api) provided
            return $this->authenticate->handle($request, $next, 'api');
```

**Comment by muglug** [comment]
Ah no, the correct docblock there is `@param  string  ...$guards` (`@param  string[]  $guards` is also acceptable)

**Comment by danherd** [comment]
but if `@param string[] $guards` is also acceptable, shouldn't psalm not be throwing that error?

**Comment by muglug** [comment]
At least when this has come up before, people have opted to copy exactly how you'd write this in PHP 7. That means writing `@param string ...$guards`. If Laravel complains, that's on them.
