### ISSUE TITLE
Requiring nikic/php-parser:dev-master

### ISSUE THREAD

**Issue by sserbin** [vimeo/psalm#1028]
@muglug  was requiring nikic/php-parser:dev-master intentional (https://github.com/vimeo/psalm/commit/54fdda651b9af7a796436134610cfca814ea2bf2) or was that just by mistake?

It kinda breaks things for those that don't have `minimum-stability: dev` (which I'd imagine is a lot)

**Comment by muglug** [comment]
Definitely a mistake, sorry - it dates from a time when there was a fix for an issue in PHP Parser's master that wasn't yet released, and it affected real-time updates inside classes.
