### ISSUE TITLE
base64_decode - string does not contain false

### ISSUE THREAD

**Issue by LauraTaylorUK** [vimeo/psalm#10285]
Hello!

As per [PHP documentation](https://www.php.net/base64_decode), the function ` base64_decode(string $string, bool $strict = false): string|false` may return false in case of an error.

But when checking for false, psalm complains about DocblockTypeContradiction:
https://psalm.dev/r/83642709a2

Thank you.

**Comment by orklah** [comment]
The official doc explains it:
> If the strict parameter is set to true then the base64_decode() function will return false if the input contains character from outside the base64 alphabet. Otherwise invalid characters will be silently discarded.

Indeed, base64_decode will never return false unless its second param is true (and your exemple default it to false), the stub is correct:
https://github.com/vimeo/psalm/blob/5.x/stubs/CoreGenericFunctions.phpstub#L1589
