### ISSUE TITLE
Argument 1 of get_class_methods expects class-string|object

### ISSUE THREAD

**Issue by LauraTaylorUK** [vimeo/psalm#10284]
Hello!

As per [PHP documentation](https://www.php.net/get_class_methods), the function ` get_class_methods(object|string $object_or_class): array` can take as an argument an object or a string.

But when given a string, psalm returns an error:
https://psalm.dev/r/c5147c3e87

Thank you.

**Comment by robchett** [comment]
Psalm expects this to be a `class-string`, e.g. a string generated by `Awesome::class`, or a string that has passed a `class_exists` check.
