### ISSUE TITLE
null union return types on callable incorrectly errors  

### ISSUE THREAD

**Issue by MarkBird1992** [vimeo/psalm#10283]
these error
https://psalm.dev/r/f77cf5b2c5
https://psalm.dev/r/ad3157434a

these do not 
https://psalm.dev/r/cefce0f389
https://psalm.dev/r/9f528af4e7

**Comment by orklah** [comment]
That's a parser choice, otherwise, there's no way of knowing what you mean with that | at the end. Adding parenthesis is the way to go

**Comment by MarkBird1992** [comment]
what do you mean?

Union type can be used in psalm in other context without parenthesis, why would a callable be any different.

**Comment by orklah** [comment]
Exactly :)
