### ISSUE TITLE
Unable to suppress MissingConstructor

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#10317]
https://psalm.dev/r/8c4c57c5f5

**Comment by mathe42** [comment]
https://psalm.dev/r/649b9cf18a

**Comment by ro0NL** [comment]
it's per property AFAIK

**Comment by ro0NL** [comment]
hmm https://psalm.dev/r/c08ffcb937 :eyes:

**Comment by ro0NL** [comment]
funny, we already had `PropertyNotSetInConstructor` in psalm.xml with a `referencedProperty` node.

After that we only got `MissingConstructor` issues

Moving it to inline `@psalm-suppress PropertyNotSetInConstructor` solves the `MissingConstructor` as well :confused:
