### ISSUE TITLE
Incorrect stub for RecursiveIterator, return value of getChildren() should be nullable

### ISSUE THREAD

**Issue by sad-spirit** [vimeo/psalm#10327]
The [docs for RecursiveIterator](https://www.php.net/manual/en/class.recursiveiterator.php) and [stubs in PHP source](https://github.com/php/php-src/blob/b6bf7a0faf3f26711d7bd4c192b9aa0e679ad948/ext/spl/spl_iterators.stub.php#L51) specify the return value of `getChildren()` as `?RecursiveIterator`, while psalm complains in case of `null` return value:

https://psalm.dev/r/602a63575d

**Comment by weirdan** [comment]
Appears to be fixed in #10340
