### ISSUE TITLE
Uncaught RuntimeException: Failed to infer case value for...

### ISSUE THREAD

**Issue by JoshuaEstes** [vimeo/psalm#10334]
Using the following enum, I get the error `Uncaught RuntimeException: Failed to infer case value for OK in psalm/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php:1457`
```php
enum UploadedFileError: int
{
     case OK = \UPLOAD_ERR_OK;
}
```

**Note**: If I comment out that line, everything works as expected. I'm not too familiar with psalm, but this might be an easy fix.

<img width="1023" alt="Screenshot 2023-10-31 at 2 12 54 AM" src="https://github.com/vimeo/psalm/assets/447419/a668e29c-a272-4efb-8682-608ca64de19e">

**Comment by JoshuaEstes** [comment]
yes

**Comment by rela589n** [comment]
The same issue happens when using interface constant as a enum value:

Here's a enum from carbon library:

```php
enum Month: int
{
    case January = CarbonInterface::JANUARY;
    case February = CarbonInterface::FEBRUARY;
    case March = CarbonInterface::MARCH;
    case April = CarbonInterface::APRIL;
    case May = CarbonInterface::MAY;
    case June = CarbonInterface::JUNE;
    case July = CarbonInterface::JULY;
    case August = CarbonInterface::AUGUST;
    case September = CarbonInterface::SEPTEMBER;
    case October = CarbonInterface::OCTOBER;
    case November = CarbonInterface::NOVEMBER;
    case December = CarbonInterface::DECEMBER;
}
```

What I currently face is following issue:

```
Uncaught Exception: RuntimeException Failed to infer case value for January
Emitted in /app/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php:1447
```

**Comment by weirdan** [comment]
> The same issue happens when using interface constant as a enum value

Technically it's quite different because classes/interfaces/enums/traits can be autoloaded (thus we need to delay the type inference until all of the codebase is loaded) and constants cannot.
