### ISSUE TITLE
UnexpectedValueException with \Swoole\Http\Response

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1035]
I get the following message

> PHP Fatal error:  Uncaught UnexpectedValueException: Storage for Swoole\Http\Response::status is not user-defined

when analysing the line 

```
$this->response->status((string) $code, $line);
```

How can I avoid a fatal error here?

**Comment by vasily-kartashov** [comment]
Both `2.0.13` and `1.1.8` are also affected. The extension is not installed on the instance that runs the `psalm`. Can this be the reason?

**Comment by muglug** [comment]
Partially - that would cause an `UndefinedClass` issue but shouldn’t be a fatal error.

**Comment by muglug** [comment]
In answer to your direct question, you can stub out those classes in a stubs directory.

**Comment by muglug** [comment]
Thanks - turns out this had already been fixed for static methods, but not for instance ones.
