### ISSUE TITLE
False `NoValue` while using switch with condition

### ISSUE THREAD

**Issue by grzybu** [vimeo/psalm#10358]
I'm getting false `NoValue` error in given sample - https://psalm.dev/r/3af858bcfc

**Comment by orklah** [comment]
Arguably, the code is pretty funky.

You're making a switch on an int value and then your cases are booleans values.

So yeah, the switch will match for 0 and false or 1 and true but is this really what you want here?

Here's the same issue without switch: https://psalm.dev/r/a7f79ca0a6
And simplified even more: https://psalm.dev/r/917ae2279b

**Comment by grzybu** [comment]
@orklah   - indeed the code is indeed funky, found it refactoring old code base. it's definitely does not work as intended - since 

`a(0) => object(Partner)#1 (1) {
  ["id"]=>
  int(0)
}`

**Comment by orklah** [comment]
I don't see a lot of improvements to be made here then. Psalm helped catch a weird piece of code so it counts as a win in my book :)

If we wanted to have something perfect here, we would have to implement the loose comparison matrixes and it would make Psalm blind to this kind of errors
