### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#10372]
Hi,

Im a bit curious ..., does psalm releases every quarter, or is it a bit of random affair?

Releasing patch-releases often shouldnt hurt too much right :sweat_smile:

**Comment by ro0NL** [comment]
cc @orklah

**Comment by orklah** [comment]
Hey! I talked about it here a little: https://github.com/vimeo/psalm/discussions/10363

There's a phar issue that will need to be resolved before release

**Comment by danog** [comment]
Took a quick look earlier, super weird, the built phar seems to work fine, maybe switching to GHA will solve the issue...
