### ISSUE TITLE
Failed to infer case value for GET

### ISSUE THREAD

**Issue by psprokofiev** [vimeo/psalm#10374]
PHP 8.2.12
PSALM 5.15.0

Enum is like:
```
use Symfony\Component\HttpFoundation\Request;

enum ApiRequestMethod: string
{
    case GET = Request::METHOD_GET;
    case POST = Request::METHOD_POST;
}
```
Constants return strings: 
https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpFoundation/Request.php#L55

Here is error:
> Uncaught RuntimeException: Failed to infer case value for GET in /app/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php:1457

**Comment by psprokofiev** [comment]
> Hey @psprokofiev, can you reproduce the issue on https://psalm.dev ?

Sure, here you are
https://psalm.dev/r/2bbe1c6fa0

**Comment by Arkemlar** [comment]
Same here but with int backed enum
https://psalm.dev/r/767842b5c9

**Comment by GhostlyIT** [comment]
I've got the same problem. Can you fix it please?

**Comment by carmenbarrancoconvelio** [comment]
Hello, I have the same issue. Could you fix it please ? Thanks

**Comment by aurimasrim** [comment]
Similar issue but the enum references another enum
https://psalm.dev/r/d4e839fc63
