### ISSUE TITLE
Meta - change text of bot

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#10376]
>can you reproduce the issue on https://psalm.dev/ ?

Change to:

>can you reproduce the issue on https://psalm.dev/ ? These will be used as phpunit tests when implementing the feature or fixing the bug.

As people are more likely to comply and provide good examples, when they know why.

**Comment by weirdan** [comment]
You can do a pull request on the bot repo to update it, the greeting message is here: https://github.com/psalm/psalm-github-bot/blob/master/src/Responder/index.ts#L6

**Comment by weirdan** [comment]
https://psalm.dev/r/a915915af4

**Comment by weirdan** [comment]
It does respond to comments, so at least it's not completely down. Checking.

**Comment by weirdan** [comment]
Ah, I see. When it decides whether to respond to a created issue, it looks at the issue description for 'psalm.dev' substring, to avoid responding to issues stating something like 'Cannot be reproduced on psalm.dev'. And you happened to mention 'psalm.dev' in your issue :man_shrugging:
