### ISSUE TITLE
InvalidArrayOffset reported for array_keys() keys

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#10382]
https://psalm.dev/r/6c6ea1b229

OG issue at https://github.com/doctrine/DoctrineBundle/pull/1728/files#diff-afe5f060789287a8ad428a4b5df1ad844184f496ece0297e421f6b1fc442b5a4

**Comment by weirdan** [comment]
You need to validate that you pass an array to the `array_keys()`: https://psalm.dev/r/409ee9c8ec
