### ISSUE TITLE
No error when passing an user-controlled array into an `extract` call

### ISSUE THREAD

**Issue by cgocast** [vimeo/psalm#10394]
Psalm raises no error when analysis this sample : https://psalm.dev/r/5738c5401d

[Documentation about extract function](https://www.php.net/manual/en/function.extract.php) warns : "Do not use extract() on untrusted data, like user input (e.g. $_GET, $_FILES)."

I'll write a PR to fix this issue.

**Comment by weirdan** [comment]
Fixed in #10417
