### ISSUE TITLE
Breaking changes for v3

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#1040]
- [x] Rename `*Checker` to `*Analyzer`
- [x] Config: change `allowStringToStandInForClass` default to `false`
- [x] Config: remove `allowCoercionFromStringToClassConst`
- [x] Plugin refactor cc @weirdan

**Comment by weirdan** [comment]
@muglug #855 as it stands does not have any breaking changes. `PluginApi` namespace which it introduces is an extension, old plugins would still continue to work with `LegacyPlugin` wrapper.

Remaining todo items are not strictly required, the PR can be merged as is . `PluginApi` interfaces can (and should, as currently you can only add stub files through them) be extended during v3 lifecycle.

There's couple of finishing touches I want to do before it's merged though: namespacing the `extra` key in `package.json` and renaming the `PluginFacade`.

**Comment by muglug** [comment]
Removed `CamelCase vars and properties?` bc actually I think `snake_case` is more legible, and it's backed up by some science.

**Comment by weirdan** [comment]
> bc actually I think snake_case is more legible, and it's backed up by some science.

What about snake_casing the `inferredType` then? Also, can coding standards be documented somewhere, as it deviates from commonly used style in PHP ecosystem (camelCasing everything)?

Sadly, neither php-cs-fixer nor codesniffer seem to have an option for snake_case vars/props.

**Comment by TysonAndre** [comment]
> Sadly, neither php-cs-fixer nor codesniffer seem to have an option for snake_case vars/props.

I have a custom sniffer based on another sniffer which will warn about variables/properties that seem to be camelCase, to enforce this consistency. See https://github.com/phan/phan/blob/master/internal/PHP_CodeSniffer/Sniffs/ValidUnderscoreVariableNameSniff.php and https://github.com/phan/phan/blob/9a1e89cd615ca44ffa4ccb5db69674bd9213217d/phpcs.xml#L56-L59

**Comment by ktomk** [comment]
- 7fd4cab1f7be484ce7d51c7f81993cac20543091 - Changelog (mention: allowCoercionFromStringToClassConst)
- dc834fdb01490d5774a1a1f41889fe59414c7765 - allow_coercion_from_string_to_class_const removal / upgrade away from it
