### ISSUE TITLE
psalm lsp implementation uses Amp\ByteStream\ResourceInputStream

### ISSUE THREAD

**Issue by hexmode** [vimeo/psalm#10411]
But this was renamed [two years ago](https://github.com/amphp/byte-stream/commit/b7f5920f16b4d0b69ee74a0e16f1b3a7ef0e1a90).

**Comment by hexmode** [comment]
Ulp.  I was using a [fork to test a bugfix ](https://github.com/tm1000/psalm/commit/461ff956c5d3023c25a39c3179bb7a0144b46336) and [ended up with this code](https://github.com/tm1000/psalm/blob/2e8d575543c73bae8f9fd3ac46957699c0b90903/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php#L8).

**Comment by hexmode** [comment]
I was [informed](https://github.com/vimeo/psalm/issues/10397#issuecomment-1826847231) that master isn't used for development, 5.x is.  This exists on 5.x.

**Comment by danog** [comment]
ReadableResourceStream is an amp v3 class, 5.x is still using amp v2, so the existing code is correct.
Psalm v6 will use amp v3, and migration was already done there.
