### ISSUE TITLE
Allow templates to be used in psalm-assert

### ISSUE THREAD

**Issue by DaveLiddament** [vimeo/psalm#1044]
I'm trying to write a stub for an assertion library's assertInstanceOf method. 

It seems that a template is not allowed in `@psalm-assert`

My attempt at what would go in the stub:
```
/** 
 * @param mixed $value 
 * @param class-string $type 
 * @template T 
 * @template-typeof T $type 
 * @psalm-assert T $value 
 */ 
function assertInstanceOf($value, string $type): void { 
 // some code
} 
```
I get this error (See: https://getpsalm.org/r/bfe32f9d85): 

```
Psalm runner output

Internal Psalm error on line 40 - Could not get class storage for T
```

**Comment by muglug** [comment]
Thanks! I definitely should have foreseen this use case. Anyhow, fixed now.
