### ISSUE TITLE
Invalid `DocblockTypeContradiction` issue when checking result of `base64_decode()`

### ISSUE THREAD

**Issue by stekostas** [vimeo/psalm#10471]
There's an invalid `DocblockTypeContradiction` issue reported when comparing the result of `base64_decode()` against `false`. The issue reports that "string does not contain false", however, the [function return type is `string|false`](https://www.php.net/manual/en/function.base64-decode).

Notably, the issue is reported when using an "identical" comparison operator, but not when using an "equal" operator.

Example Snippet: https://psalm.dev/r/78e968d225

**Comment by jack-worman** [comment]
https://www.php.net/manual/en/function.base64-decode.php
`base64_decode()` will always return a string if you don't set the param `strict: true`

https://psalm.dev/r/af5bd6fed2

**Comment by stekostas** [comment]
Thanks for the clarification @jack-worman. I was unaware of that behaviour.
