### ISSUE TITLE
Feature: Add option to sort output by error type (instead of file)

### ISSUE THREAD

**Issue by ThomasLandauer** [vimeo/psalm#10482]
Motivation: When seeing hundreds of errors, it's easier to deal with the same error in 20 files (rather than fixing 10 different errors in the first file, then move to the next file).

So I'm suggesting something like a command line option:
```bash
---sort=error|file
```

**Comment by weirdan** [comment]
I believe we already have this:
https://github.com/vimeo/psalm/blob/ca9a12dddaabb9caf8dd622d558696de0dabb9e8/src/Psalm/Report/ByIssueLevelAndTypeReport.php#L28-L40

To use this output format, invoke Psalm with `--output-format=by-issue-level` switch.
