### ISSUE TITLE
Psalm not allowing for inline comments in type definition

### ISSUE THREAD

**Issue by juacala** [vimeo/psalm#10492]
This page says you can have one-line comments for array shapes:
https://psalm.dev/docs/annotating_code/type_syntax/array_types/

But it appears not to work:  https://psalm.dev/r/6a9ab1188c
Removing the comment does work: https://psalm.dev/r/005b7c90a2

This would be very useful to comment array shapes, especially for larger ones.

**Comment by juacala** [comment]
If someone can help point me to the right place in the code to look at this, I'd be happy to work on a pull request for it.

**Comment by ging-dev** [comment]
> If someone can help point me to the right place in the code to look at this, I'd be happy to work on a pull request for it.

you can start debug from https://github.com/vimeo/psalm/blob/b113f3ed0259fd6e212d87c3df80eec95a6abf19/src/Psalm/Internal/Analyzer/CommentAnalyzer.php#L335

**Comment by juacala** [comment]
@ging-dev Although the same error is thrown, I can't get that line to hit in the debugger (I've verified the debugger is running and breaks on the initial PHP file). Is there a cache I need to disable to get it to appropriately reanalyze files during development?

**Comment by ging-dev** [comment]
> @ging-dev Although the same error is thrown, I can't get that line to hit in the debugger (I've verified the debugger is running and breaks on the initial PHP file). Is there a cache I need to disable to get it to appropriately reanalyze files during development?

For xdebug to work with Psalm, you need to set the environment variable `PSALM_ALLOW_XDEBUG=1` when run psalm:

```bash
PSALM_ALLOW_XDEBUG=1 path/to/psalm --no-cache
```
For more information, see xdebug section at https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/

**Comment by weirdan** [comment]
My understanding is that the parser (`CommentAnalyzer::splitDocLine()`) skips from `//` until `\n'. But specifically for type aliases, before calling the parser, we remove all newlines:

https://github.com/vimeo/psalm/blob/e87fd867108308d516747bd5066455726c1adafb/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php#L1940-L1945
