### ISSUE TITLE
Imported types cannot be used as array keys in 5.18.0

### ISSUE THREAD

**Issue by TJ09** [vimeo/psalm#10496]
```php
<?php

/**
 * @psalm-type ArrayKeyType array-key
 */
class Bar {}

/**
 * @psalm-import-type ArrayKeyType from Bar
 * @psalm-type UsesArrayKeyType array<ArrayKeyType, bool>
 */
class Foo {}
```

Link: https://psalm.dev/r/72f05104ae

Note that there are no errors in psalm.dev at the time of writing (but it's also running a week-old commit: [a75d26a](https://github.com/vimeo/psalm/commit/a75d26a)).

Psalm 5.17 reports no errors, while Psalm 5.18 reports:

```
ERROR: InvalidDocblock - lib/Foo.php:12:1 - Invalid array key type ArrayKeyType (see https://psalm.dev/008)
/**
 * @psalm-import-type ArrayKeyType from Bar
 * @psalm-type UsesArrayKeyType array<ArrayKeyType, bool>
 */
class Foo {}
```

As far as I can tell `ArrayKeyType` as `array-key` is definitely an okay array key type.

**Comment by ging-dev** [comment]
Maybe rated https://github.com/vimeo/psalm/commit/82ff58228092cb15f6bd17adfba5aa607179a4a9
