### ISSUE TITLE
Constructor arguments are not being reported as unused

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#10509]
When having a class with `__construct` where arguments are required but not used at all, I'd expect `PossiblyUnusedParam` or something which tells me that there is dead code.

https://psalm.dev/r/2da05c10af

**Comment by boesing** [comment]
Even tho that `findUnusedVariablesAndParams="true"` is enabled, it is implicitly disabled due to `findUnusedCode="false"`.

Maybe that should be reported at least as some kind of `warning` that due to the default value of `findUnusedCode` the `findUnusedVariablesAndParams` is disabled as well.

**Comment by weirdan** [comment]
The issue, as originally reported, seems to be invalid: https://psalm.dev/r/41a3621f5e

**Comment by weirdan** [comment]
> Maybe that should be reported at least as some kind of warning [...]

Agree, that would be useful. Mind filing a separate issue for this enhancement?
