### ISSUE TITLE
Using partial stub causes MissingConstructor

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#1050]
I'm trying to override couple of signatures for `Doctrine\ORM\EntityRepository` with a stub like this:
```php
<?php
namespace Doctrine\ORM;

use Doctrine\Common\Persistence\ObjectRepository;
use Doctrine\Common\Collections\Selectable;

class EntityRepository implements ObjectRepository, Selectable
{
    /** @return object[] */
    public function findAll() {}
    /**
     * @return object[]
     * @param ?int $limit
     * @param ?int $offset
     */
    public function findBy(array $criteria, ?array $orderBy = null, $limit = null, $offset = null) {}
}
```
However when Psalm uses this stub, it starts to complain about `MissingConstructor` for descendant classes, even though original `Doctrine\ORM\EntityRepository` does have the constructor, and properly initializes instance properties there.

**Comment by muglug** [comment]
If that doesn't fix, please reopen - I'm sort of flying blind, but you might be able to play some more.
