### ISSUE TITLE
Unpexpected parameter names for SessionUpdateTimestampHandlerInterface

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#10512]
https://psalm.dev/r/37d0b51da1

https://www.php.net/manual/en/class.sessionupdatetimestamphandlerinterface.php

**Comment by ging-dev** [comment]
Hi @zerkms, do you want open pull request? 

https://github.com/vimeo/psalm/blob/5.x/dictionaries/CallMap_historical.php#L6586-L6587
