### ISSUE TITLE
get a notice at the very start

### ISSUE THREAD

**Issue by marcelloh** [vimeo/psalm#1052]
Notice: Uninitialized string offset: 0 in C:\Data\git\QualityReport\vendor\vimeo\psalm\src\Psalm\Config\FileFilter.php on line 92

Perhaps it has something to do that I also notice that more directories are scanned/used than my source dir.
Which I configured like this:
    <projectFiles>
        <directory name="src" />
    </projectFiles>

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/5eca4a8b2781d81d815def598565780cd91e4051
