### ISSUE TITLE
Add SimpleXMLElement::__set() method handling

### ISSUE THREAD

**Issue by kthaler** [vimeo/psalm#10535]
## Description
As of https://github.com/vimeo/psalm/pull/10049, we are unable to dynamically set properties in a `SimpleXMLElement`. So code like `$xmlElement->newProp = $newVal` causes psalm to flag the line with a `InvalidPropertyAssignment` error. 

## Potential Solution
We suggest updating [the Psalm stubs](https://github.com/vimeo/psalm/blob/5.x/stubs/extensions/simplexml.phpstub#L68) for SimpleXMLElement to include handling of the __set() method.

**Comment by orklah** [comment]
Seems fine, could you push a PR?
