### ISSUE TITLE
Code with attributes causes missing class error on method return type

### ISSUE THREAD

**Issue by jimbo2150** [vimeo/psalm#10563]
I have a Symfony entity class with various attributes attached to the class and properties. When using a template generic, psalm appears to recognize the template on the class property, but not on the return value of a class method. It says it is an undefined class.

Here is the example code: https://psalm.dev/r/6cb02178be
_In the above example you can ignore all other errors except for the docblocks and specifically the `@return` value on the `getValue()` method. The other errors are just because of the referenced classes do not exist within the test environment._

However, when I remove the attributes, the error disappears. It seems to recognize the template generic variable and no longer has an issue with it.

Here is the same code with attributes removed: https://psalm.dev/r/ba05c5fb24
_The above example has all the attributes removed and it now seems to recognize the `@template` generic on the method return type._

**Comment by weirdan** [comment]
Minimal reproducer: https://psalm.dev/r/b85c3cd814

**Comment by weirdan** [comment]
The issue is with the underlying parser library we use: nikic/PHP-Parser#762. Nothing can be done here unless that issue is fixed first.
