### ISSUE TITLE
NullableReturnStatement after assertNotNull in unittest

### ISSUE THREAD

**Issue by marcelloh** [vimeo/psalm#1058]
In my test, I have a lot of this:
```
$this->assertNotNull($result);
return $result;
```
and I still get this message:
```
[0;31mERROR[0m: NullableReturnStatement - tests\Unit\Common\Base\BaseModelTest.php:387:3 - The declared return type 'AllUnited\Smart\DataLayer\Models\CountryModel' for Tests\Unit\Common\Base\BaseModelTest::getFilledCountryModel is not nullable, but the function returns 'AllUnited\Smart\DataLayer\Models\CountryModel|null'
		[97;41mreturn $result;[0m
```
I expect no error, since I'm pretty sure its not null when I return the value

**Comment by marcelloh** [comment]
About the same happends with:
```
$this->assertNotNull($model);
$this->assertEquals($model->id, $insertedId);
```
which tells me:
```
[0;31mERROR[0m: PossiblyNullPropertyFetch - tests\Unit\Common\Base\BaseRepositoryTest.php:113:23 - Cannot get property on possibly null variable $model of type AllUnited\Smart\DataLayer\Models\CountryModel|null
		$this->assertEquals([97;41m$model->id[0m, $insertedId);
```
and here also I know for sure the model is not null

**Comment by muglug** [comment]
Could you follow the instructions here: https://github.com/vimeo/psalm/issues/1053#issuecomment-435468312 and let me know if they work? Short answer is that Psalm doesn't support PHPUnit assertions natively, but a plugin is coming soon.

**Comment by marcelloh** [comment]
I will wait for the plugins then, no rush. Keep up the good work, since your work is making me a better programmer :-)
