### ISSUE TITLE
numeric-string status lost via rtrim

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#10595]
https://psalm.dev/r/78d23c0ac0

`rtrim('0.50', '0')` and `rtrim('0.0', '0')` should both remain numeric-string

**Comment by weirdan** [comment]
Some numeric strings would be invalidated by `rtrim(..., '0')` (e.g. '0'). So we can't assume the trimmed string is always numeric.

See https://3v4l.org/aGqrN

**Comment by SignpostMarv** [comment]
ext-bcmath with a precision parameter greater than zero will always result in a decimal string.

See https://3v4l.org/W7BPM

**Comment by weirdan** [comment]
I don't see how it's relevant to `rtrim()` though.

**Comment by SignpostMarv** [comment]
> I don't see how it's relevant to `rtrim()` though.

`bcdiv('27', '60', 3)` is `'0.450'` and flagged as a numeric string. `rtrim(bcdiv('27', '60', 3), '0')` is `'0.45'` and is not flagged as a numeric string.

**Comment by weirdan** [comment]
`bcdiv()` returns a `numeric-string` (not a literal numeric string), and as we established above not every `numeric-string` passed through `rtrim(..., '0')` remains a `numeric-string`. So not much can be done here.

**Comment by SignpostMarv** [comment]
@weirdan how much scope would there be for a `decimal-string` type?

**Comment by weirdan** [comment]
I'd say it's infinitely more complex than consistently using a custom function to trim trailing zeroes: https://psalm.dev/r/2941c00f3a
