### ISSUE TITLE
Unexpected result: InvalidScalarArgument

### ISSUE THREAD

**Issue by paragonie-scott** [vimeo/psalm#106]
> Argument 2 of apcu_store expects int, string provided

That's actually not true. Optional argument 3 is an int, but argument 2 is mixed.

> Argument 2 of PDOStatement::fetchall expects string, int provided

That actually depends on which constant goes in the first argument.

Offending snippet: `return $stmt->fetchAll(\PDO::FETCH_COLUMN, $offset);`

-----

I'm sure there are other PHP functions that behave weird like this, especially with optional extensions. These are just the two I've found thus far.

**Comment by paragonie-scott** [comment]
Additionally:

> Too few arguments for method sodium\memzero

I suspect something is breaking in reflection?

**Comment by muglug** [comment]
Would you mind breaking the second one out into another issue?

**Comment by paragonie-scott** [comment]
Sure, no problem. Also, wow, that was fast! :+1:
