### ISSUE TITLE
Support PHP 8.3 Override attribute

### ISSUE THREAD

**Issue by edsrzf** [vimeo/psalm#10626]
Psalm should support PHP 8.3's new `Override` attribute in two ways:

* [x] When a method has an `Override` attribute but does not override a parent method, raise an issue. (Any method with an `Override` attribute that would cause a fatal runtime error should also be detected statically by Psalm.) Call it `InvalidOverride`. (Implemented in #10644.)
* [ ] When a method of a child class overrides that of a parent class and there is no `Override` attribute, raise an issue. Call it `MissingOverrideAttribute`.

Both of these would apply only when the PHP version is >= 8.3, and the second one should probably have its own configuration option.

I'm happy to work on the implementation and use this issue to track progress, discuss the ideas, and hash out any details, like the error names or configuration.

**Comment by weirdan** [comment]
Don't we have that already? See #10493

**Comment by weirdan** [comment]
> Maybe call it `InvalidOverrideAttribute`?

Just `InvalidOverride` would seem more fitting - as there's nothing wrong with the attribute itself.

> Maybe call it `MissingOverrideAttribute`?

Sounds good to me.

**Comment by weirdan** [comment]
> Don't we have that already? See https://github.com/vimeo/psalm/pull/10493

That PR just adds the attribute stub.
