### ISSUE TITLE
Invalid type hint for properties when using `psalm --alter`

### ISSUE THREAD

**Issue by BenjaminHoegh** [vimeo/psalm#10650]
```
./vendor/bin/psalm -v                                              
Psalm 5.21.1@8c473e2437be8b6a8fd8f630f0f11a16b114c494

./vendor/bin/psalm --alter --php-version=7.4 --issues=all --dry-run
Target PHP version: 7.4 (set by CLI argument).
Scanning files...
Analyzing files...

Altering files...
@@ -38,7 +38,7 @@
-    private $createAnchorIDCallback = null;
+    private ?callable $createAnchorIDCallback = null;
```

**Comment by BenjaminHoegh** [comment]
> https://psalm.dev

Yes, but I believe psalm.dev is using a newer PHP version where this is valid

**Comment by weirdan** [comment]
I believe the callable type hint for properties is invalid for all existing PHP versions: https://3v4l.org/bXWo2 (also https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.base.function) so this is clearly a bug.
