### ISSUE TITLE
Inline type of generics

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1068]
Could we add inline type for generics to have a better definition for `callable`s?

```
/**
 * @var callable(callable(mysqli):$T):$T
 */
private $executor;
```

Currently `@template` doesn't seem to apply on `@var` level, and moving it to the class level would be incorrect.

**Comment by muglug** [comment]
Not quite sure I understand the use case - there's support for templates at the class property level: https://github.com/vimeo/psalm/blob/2065e0129ecd496dccf7220f3acc415fd181bf76/tests/TemplateTest.php#L197-L202

**Comment by vasily-kartashov** [comment]
Here's my use case. Handling transactions in a database is a generic functionality. In a very simplified form this looks something like this:

```
$executor = function(callable $procedure) {
    try {
        $this->startTransaction();
        $result = ($procedure)($this->connection)
        $this->commit();
        return $result;
    } catch (Exception $e) {
        $this->rollback();
        throw $e;
    }
}
```

The type of executor is `callable<S>(callable(T):S):S`, where `T` is a class type parameter (i.e. `mysqli`, `SQLite3`, `PDO`, whatever), but `S` can be really anything. In other words `S` states the relationship between the return types of the inner and outer closures.

**Comment by muglug** [comment]
Ah ok, I think I get it.

So the second function call here should fail? https://getpsalm.org/r/131fb5ac06

**Comment by weirdan** [comment]
> So the second function call here should fail?

If that's so, it would be the same as #742 (that one looks more complex though).

**Comment by muglug** [comment]
Thanks for the comments here!
