### ISSUE TITLE
Modulo in PHP is always int, Psalm infers int|float

### ISSUE THREAD

**Issue by dkarlovi** [vimeo/psalm#1069]
https://getpsalm.org/r/95ff7fa464

/cc @ostrolucky

**Comment by SignpostMarv** [comment]
more test cases:

- https://3v4l.org/J906T
- https://3v4l.org/RbIE7
- https://3v4l.org/k8So4
- https://3v4l.org/bFUkt

3v4l passes fine whether or not strict_types is enabled.

**Comment by muglug** [comment]
Thanks! Not sure how that got through.
