### ISSUE TITLE
Issue with PHP extension functions

### ISSUE THREAD

**Issue by paragonie-scott** [vimeo/psalm#107]
First, install the libsodium extension from PECL. Then, inspect this script with Psalm:

```php
$foo = random_bytes(32);
\Sodium\memzero($foo);
```

This will produce the following failure:

> Too few arguments for method sodium\memzero

I suspect there's a bug with reflection and figuring out which PHP extensions' function arguments are optional.

**Comment by muglug** [comment]
Hmm when I `var_dump` the `Sodium\memzero` reflection parameters I get

```
array(2) {
  [0]=>
  object(ReflectionParameter)#528 (1) {
    ["name"]=>
    string(9) "reference"
  }
  [1]=>
  object(ReflectionParameter)#99 (1) {
    ["name"]=>
    string(6) "length"
  }
}
```

Both, according to Reflection, are non-optional

**Comment by paragonie-scott** [comment]
Oh, interestingly enough, https://github.com/jedisct1/libsodium-php/blob/7222f79d663830637edf979aa29eea9417515d28/libsodium.c#L228

I'll be sure to fix that before it lands in core. X_x

**Comment by muglug** [comment]
Yes 2 required params: https://github.com/jedisct1/libsodium-php/blob/cb60317b16f93b6bf652db96802a879b0d751fdb/libsodium.c#L21

**Comment by muglug** [comment]
Good to close?

**Comment by paragonie-scott** [comment]
Yep. :)

**Comment by muglug** [comment]
Rarely is reflection trustworthy, but this is one of those times ;)
