### ISSUE TITLE
Trigger update for dev-master on packagist 

### ISSUE THREAD

**Issue by sserbin** [vimeo/psalm#1070]
@muglug can you please manually "update" psalm's version on packagist? 

Composer's version seems to be stuck on 8354b6e055b10d329d5c6c0c47de3200f7aaa93c which is a broken commit(that was fixed in 6cf6d2cfda34da038e5cb9015a9f77221cb1a2ed)

Thanks!

**Comment by muglug** [comment]
Have just updated
