### ISSUE TITLE
UnexpectedValueException: Storage for mysqli::get_server_info is not user-defined

### ISSUE THREAD

**Issue by morozov** [vimeo/psalm#1073]
This is similar to https://github.com/vimeo/psalm/issues/884 and https://github.com/vimeo/psalm/issues/963:
```
↪ git remote -v
upstream	git@github.com:doctrine/dbal.git (fetch)
upstream	git@github.com:doctrine/dbal.git (push)

↪ git rev-parse HEAD # develop
e5a586eaba90ff5df55c6c65369e8fdf000b6804

↪ vendor/bin/psalm --version
Psalm 2.0.14@792144def40d678b7fa7c8a52da6cdbd34dd415a

↪ vendor/bin/psalm --debug-by-line
...
lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php:107

Fatal error: Uncaught UnexpectedValueException: Storage for mysqli::get_server_info is not user-defined in vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php:551
Stack trace:
#0 vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/Call/MethodCallChecker.php(681): Psalm\Codebase\Methods->getUserMethodStorage('mysqli::get_ser...')
#1 vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(105): Psalm\Checker\Statements\Expression\Call\MethodCallChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#2 vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/AssignmentChecker.php(144): Psalm\Checker\Statements\ExpressionChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#3 vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChe in vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php on line 551
```
The [line in question](https://github.com/doctrine/dbal/blob/e5a586eaba90ff5df55c6c65369e8fdf000b6804/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php#L107) contains:
```php
$serverInfos = $this->conn->get_server_info();
```
Where `$this->conn` is of type `mysqli`.

**Comment by muglug** [comment]
Do you get this with the [latest version of Psalm](https://github.com/vimeo/psalm/releases/tag/2.0.17)?

**Comment by muglug** [comment]
I'm unable to reproduce with latest Psalm: https://getpsalm.org/r/a9642fa085

**Comment by muglug** [comment]
Reproduced here: https://getpsalm.org/r/ec734cc03c

**Comment by morozov** [comment]
@muglug thank you for a quick turnaround. I can install `dev-master#fe25530` via composer thanks to relaxed constraints but I'm seeing a new issue:
```
Parsing lib/Doctrine/DBAL/Sharding/PoolingShardConnection.php

Fatal error: Psalm\Checker\StatementsChecker::analyze(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "_HumbugBoxd9c486c39807\PhpParser\Node\Stmt\Namespace_" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in vendor/vimeo/psalm/src/Psalm/Checker/StatementsChecker.php on line 178
```
I can consistently reproduce it with different PHP versions and different way of installing psalm (as a dependency of doctrine/dbal and as a separate project).

A quick bisect points to https://github.com/vimeo/psalm/commit/f9cca5e59726347dbfe3f23881cdcfdd09e5b51e and https://github.com/vimeo/psalm/commit/addaea2c1c637caa9203eea02fc887cb3fb74c1f.

Should I file a new issue and is there a way to temporarily disable those optimizations?

**Comment by muglug** [comment]
Clearing cache should fix

**Comment by morozov** [comment]
@muglug it did. Please see the above.

**Comment by morozov** [comment]
Thank you for support. I was able to run it initially on the codebase.
