### ISSUE TITLE
Psalm crashes after switching between phar and composer-installed versions

### ISSUE THREAD

**Issue by morozov** [vimeo/psalm#1074]
Please see the beginning in https://github.com/vimeo/psalm/issues/1073#issuecomment-437639062.

Debugging shows that `ParserCacheProvider` doesn't take into account the origin of the cache: whether it was generated by a phar-packaged application or by one managed by composer. In both cases, the class names of the cached objects are different and therefore cannot be unserialized by another version leading to incomplete php objects.

**Comment by muglug** [comment]
Thanks - should be good now
