### ISSUE TITLE
Feature request: Require #[Override]

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#10751]
I'm suggesting it because I believe it falls into the type safety category.

Details: if a class implements a method that is defined in the interface, or is overriden from one of its base classes - then the function declaration *MUST* contain `#[Override]`.

It would fall into the same category of things like:

```
INFO: [UnusedVariable](https://psalm.dev/077) - 3:1 - $a is never referenced or the value is not used
```

because if the function was ever overriden or implemented as a part of interface, and then function is removed from the base declaration, then it would be most likely an unused dangling function forever, unless it's spotted by accident.

Thoughts?

**Comment by zerkms** [comment]
This would be an error: https://psalm.dev/r/8b1bef08a6

This would be not an error: https://psalm.dev/r/ee0216f465

**Comment by weirdan** [comment]
It's already available with a feature flag: https://psalm.dev/docs/running_psalm/configuration/#ensureoverrideattribute

Perhaps we need to add some more toggles to psalm.dev sandbox though.

**Comment by zerkms** [comment]
Oh, now that's truly awesome, thank you!

**Comment by weirdan** [comment]
It'll be available on psalm.dev once this PR is merged: https://github.com/psalm/psalm.dev/pull/104
