### ISSUE TITLE
RiskyTruthyFalsyComparison false positive

### ISSUE THREAD

**Issue by MelechMizrachi** [vimeo/psalm#10754]
https://psalm.dev/r/8671eefd97

It seems like a straight boolean comparison like `empty()` or `!empty()` triggers `RiskyTruthyFalsyComparison` which seems to be incorrect.

**Comment by weirdan** [comment]
Mind elaborating on this? The comments in the snippet explain precisely why the issue _should_ be triggered here.

**Comment by MelechMizrachi** [comment]
Closing this. It's a non-issue. I misunderstood the crux issue, because the original example did not have the empty method (I noticed this issue popping up all over for us internally due to empty method usages and was a bit perplexed). We'll work on getting our instances of empty split out into different conditions. Thanks for taking a look at this @weirdan !!
