### ISSUE TITLE
Feature request: emit a warning if it's a bogus @psalm-suppress

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#10763]
In cases like https://psalm.dev/r/01bba3c905

```php
<?php

/** @psalm-suppress MixedAssignment */
$a = 1;
```

it would be ideal if it was an extra warning for the line 3 about the `@psalm-suppress` not suppressing anything.

That way you know some suppressions are dangling and only create noise.

**Comment by weirdan** [comment]
Don't we have it already?

See https://psalm.dev/docs/running_psalm/configuration/#findunusedpsalmsuppress

**Comment by weirdan** [comment]
Or is it another case of 

>  I probably need to re-run through all the configuration parameters once again :-)

😁

**Comment by zerkms** [comment]
Oh my god, feeling so stupid now :facepalm:

**Comment by weirdan** [comment]
Sorry, I just couldn't resist 😁 

Seriously though, don't let it discourage you from requesting useful features to be added to Psalm.
