### ISSUE TITLE
WeakMap mixed - works on psalm.dev?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#10773]
https://psalm.dev/r/e14ff7b1b3

No error and trace shows `Throwable`

However, when I run exactly the same code locally in 5.x, 5.22.0 and 5.21.0, I get trace mixed and lots of "mixed" errors.

Running PHP 8.3 with phpVersion="8.3"

**Comment by weirdan** [comment]
psalm.dev runs `master`, so you may try that.

**Comment by weirdan** [comment]
I'm updating master now to have all the changes from 5.x, and then it should be possible to dig deeper.
