### ISSUE TITLE
ParamNameMismatch not reported for __construct

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#10784]
https://psalm.dev/r/f49829b72e

Besides named argument calls, this is also an issue with promoted properties: https://psalm.dev/r/3f6f25190f
which is the reason this should report an error

**Comment by weirdan** [comment]
Constructors generally don't have to be compatible. However we should report name mismatches if the constructor is declared consistent by using `@psalm-consistent-constructor`: https://psalm.dev/r/db66d21cb2

**Comment by weirdan** [comment]
No, it should be like the following:

* when neither of `@psalm-consistent-constructor` / `@no-named-arguments` are present, no consistency (neither names nor types) is enforced
* when `@psalm-consistent-constructor` is present without `@no-named-arguments`, both names and types have to match
* when both are present, only types have to match (much like the current behaviour of `@psalm-consistent-constructor`)
