### ISSUE TITLE
First type in an intersection type, used as a type parameter for a class-string, in a union of class-strings, gets dropped from the union.

### ISSUE THREAD

**Issue by rzvc** [vimeo/psalm#10799]
Sorry for the title. It's slightly incorrect, but didn't want to make it longer. The code below exemplifies the issue quite well:
https://psalm.dev/r/69a0df463f

**Comment by weirdan** [comment]
The linked PR changes the interpretation of `class-string<IBar>|class-string<IFoo>|class-string<IBar & IFoo>` to `class-string<IBar>|class-string<IFoo>` (regardless of the order of the intersection).
