### ISSUE TITLE
PDO prepare method return type

### ISSUE THREAD

**Issue by marvin255** [vimeo/psalm#1081]
Hello. I have code like below:

```php
protected function getStatement(string $sql): PDOStatement
{
    $newPrepared = $this->pdoConnection->prepare($sql);
    if (!($newPrepared instanceof PDOStatement)) {
        throw new Exception("Can't prepare statement for {$sql}");
    }
    return $newPrepared;
}
```

Psalm throws a notice while checking `Found a redundant condition when evaluating $newPrepared and trying to reconcile type 'PDOStatement' to PDOStatement`. But I'm pretty sure that `prepare` method can returns a bool value depends on [error handling mode](http://php.net/manual/en/pdo.error-handling.php).

Looks like related to https://github.com/vimeo/psalm/issues/669.

Anyway i don't actually need this condition but other checker in my project wants to see it. I just want to understand which way is correct and which way i should use.

Psalm version is `Psalm 2.0.17@ead7d62d489d58edb4fa03b21e4f0bc87a476211`.

**Comment by muglug** [comment]
Thanks, simple fix
