### ISSUE TITLE
Null-coalesced variable within arrow function not recognized

### ISSUE THREAD

**Issue by muzcb** [vimeo/psalm#10811]
https://psalm.dev/r/6534f57638

```
if (rand() % 2 === 0) {
    $foo = true;
}
$f = fn(): bool => $foo ?? false;
$f();
```

Works, but leads to these issues:

* ERROR: [UndefinedVariable](https://psalm.dev/024) - 4:20 - Cannot find referenced variable $foo
* INFO: [MixedReturnStatement](https://psalm.dev/138) - 4:20 - Possibly-mixed return value
* INFO: [MixedReturnStatement](https://psalm.dev/138) - 4:20 - Could not infer a return type
* INFO: [UnusedVariable](https://psalm.dev/077) - 2:5 - $foo is never referenced or the value is not used

**Comment by weirdan** [comment]
Support for uninitialized variables currently is (and probably always will be) out of scope for Psalm.

Initialize the variable and the error goes away: https://psalm.dev/r/52168c1e0b
