### ISSUE TITLE
Weird ReservedWord  "Parameter cannot be never" when using Laravel collections

### ISSUE THREAD

**Issue by paali** [vimeo/psalm#10844]
I'm having a bit of problems understanding some issue after upgrading psalm. In our (private) project Illuminate/Collections seem to be giving lots of new errors. This started happening from 5.16 release.

https://psalm.dev/r/1245f7d7f6

I tried to copy only small part of the collection code for the reproducer.

This kind of simpe collection usage started giving errors I cannot follow:
```php
$suffixHeaders = ['foo', 'bar'];
(new Collection())
    ->merge($suffixHeaders)
    ->map(fn (string $header) => ucfirst($header));
``` 

ERROR: [ReservedWord](https://psalm.dev/095) - 108:15 - Parameter cannot be never - for the string $header parameter.
ERROR: [InvalidArgument](https://psalm.dev/004) - 107:13 - Argument 1 of Collection::merge expects Arrayable<never, never>|iterable<never, never>, but list{'foo', 'bar'} provided

Maybe there's something wrong in how Laravel Collections are templated. Is this possibly an issue in psalm? Or maybe there's a workaround? I updated to latest illuminate/collections and tested on master version of psalm.

Changing the collection creation to something like this seems to work but is this mandtory now? There are a couple of them...
```php
/** @var Collection<int, string> $col */
$col = new Collection();
```

**Comment by weirdan** [comment]
> but is this mandtory now?

It basically always was. Perhaps a new release got a bit more strict (like not allowing to pass `never` as argument), but Psalm always required a docblock override for generics with constructor parameters.

**Comment by paali** [comment]
Yes. And also there seems to be a bit of a recurring antipattern in our codebase.
`collect()->merge($wellDefinedArray)` cannot work but `collect($wellDefinedArray)` is just fine.

I'll just close this and hammer the issues out.
