### ISSUE TITLE
UndefinedClass when aliasing imports

### ISSUE THREAD

**Issue by keradus** [vimeo/psalm#10840]
reproduce: https://psalm.dev/r/ab628dd25f

```php
<?php

use Foo\Exception as FooException;

class Connection
{
    public function __construct()
    {
        throw new FooException("foo");
    }
}
```

produces
```
ERROR: [UndefinedClass](https://psalm.dev/019) - 9:19 - Class, interface or enum named Foo\Exception does not exist
```

original issue: https://github.com/symfony/symfony/actions/runs/8332242829/job/22800953251?pr=53244#step:7:33

link https://github.com/symfony/symfony/pull/53244/commits/98e7ecd7fd6645df6202626a9338559fcae77ffb

**Comment by weirdan** [comment]
Does `Foo\Exception` actually exist?

**Comment by keradus** [comment]
In case I faced, it's about class from php-extention, ref https://github.com/symfony/symfony/pull/53244#discussion_r1529123313

**Comment by weirdan** [comment]
So the error you get on psalm.dev is valid. Now let me put it another way - does Symfony CI have this extension installed?

**Comment by keradus** [comment]
Unfortunately I'm not aware of Symfony CI specifics

**Comment by weirdan** [comment]
So let's assume it's not. As such, there's no problem with Psalm: it reported what it was designed to report - `UndefinedClass`.
