### ISSUE TITLE
RFC: New issue for implicit implementation of Stringable on PHP 8.0+

### ISSUE THREAD

**Issue by edsrzf** [vimeo/psalm#10863]
[Stringable](https://www.php.net/manual/en/class.stringable.php) is the only interface in PHP that may be implemented implicitly, when there is a `__toString` method on a class. It was introduced in PHP 8.0. From [the RFC](https://wiki.php.net/rfc/stringable), this decision was made to support code that's compatible with earlier PHP versions, where `__toString` was still a magic method with special behavior.

For code bases that only support PHP 8.0+, this interface should be implemented explicitly, and Psalm should raise an issue when it's implicitly implemented.

I propose a new Psalm issue, `ImplicitStringable`, at error level 2. When a class is analyzed and it has a `__toString` method, a parent class or implemented interface must also have that method. This allows for cases where a code base extends a library class and the library supports older versions of PHP that don't have `Stringable`.

I thought about this when fixing #10846. I also noticed that there isn't a way within `ClassLikeStorage` to figure out whether `Stringable` is implemented explicitly or not, so there are still some cases not covered by that fix.

**Comment by weirdan** [comment]
I was under impression that PHP recently started moving away from interfaces to magic methods (see, e.g. deprecation of `Serializable`).

**Comment by edsrzf** [comment]
The [justification on the custom serialization RFC](https://wiki.php.net/rfc/custom_object_serialization#magic_methods_vs_interface) seems specific to serialization. All PHP objects are serializable; the magic methods just provide a way to customize. `Stringable` is different in that it actually provides a new capability. Objects that don't implement `Stringable` can't be converted to a string at all.

There were also interoperability concerns, similar to `Stringable`, and it's interesting that they were solved in a different way.

**Comment by weirdan** [comment]
Were plans to require explicit `Stringable` for `__toString()` to work ever discussed? As it stands now it looks very much like a coding style issue, even if it's hard to detect in a tool like phpcs.

**Comment by edsrzf** [comment]
I think it's fair to consider this a style issue. It was just an idea.
