### ISSUE TITLE
non-empty-literal-string|literal-string is inferred as string

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#10925]
https://psalm.dev/r/21adcbe806

**Comment by VincentLanglet** [comment]
Hi @orklah @weirdan,

I assume this could be an easy fix but I have no idea where such type resolution is done in the psalm codebase.
Any idea which method does such job ?

**Comment by orklah** [comment]
Yeah, it should be around https://github.com/vimeo/psalm/blob/c6311028647126fa760ff54b580bcde7ca9a0f92/src/Psalm/Internal/Type/TypeCombiner.php#L987

The TypeCombiner is the class that makes `true|false` become `bool` or `non-empty-string|non-falsy-string` becomes `non-empty-string` for example.

specifically, `scrapeStringProperties` handles strings of different shapes, you can see things like `$has_only_numeric_strings` or `$has_only_non_empty_strings` that are flags to check that every string match the property you want to conserve at the end
