### ISSUE TITLE
`@psalm-suppress` don't work for `MissingClassConstType` issue

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#10933]

**Comment by ThomasLandauer** [comment]
I suggested to suppress `MissingClassConstType` for `final` classes: https://github.com/vimeo/psalm/issues/10951

**Comment by jack-worman** [comment]
I don't understand why you would add `@psalm-suppress` instead of just adding the type.
Using `@var` should also work if you cannot use native PHP for some reason.

**Comment by vjik** [comment]
> I don't understand why you would add `@psalm-suppress` instead of just adding the type.

We use psalm for library that support previous PHP versions (8.1, 8.2).

**Comment by weirdan** [comment]
> We use psalm for library that support previous PHP versions (8.1, 8.2).

what @jack-worman was alluding to is that since you're adding a docblock anyway you could have added, e.g., `/** @var int */` instead and get better type inference, even before 8.3. 

Nevertheless, `@psalm-suppress` should work anyway.
