### ISSUE TITLE
Suggestion: Allow empty `<errorLevel>` in `psalm.xml` (i.e. suppress everywhere)

### ISSUE THREAD

**Issue by ThomasLandauer** [vimeo/psalm#10952]
Am I missing something here or is there indeed no way to suppress an error **globally**? At least this is not working for me:

```xml
<SomeError>
    <errorLevel type="suppress" />
</SomeError>
```
Reference: https://psalm.dev/docs/running_psalm/dealing_with_code_issues/#suppressing-issues

**Comment by weirdan** [comment]
It's actually shown in the first example on that page:
```xml
  <MissingPropertyType errorLevel="suppress" />
```

**Comment by ThomasLandauer** [comment]
I was so convinced that `errorLevel` is an element (not attribute) that I didn't look for anything else ;-) I now added a comment in https://github.com/vimeo/psalm/pull/10954
