### ISSUE TITLE
 PHP 8.2 has PHP Error: Creation of dynamic property PhpParser\Node\Stmt\...

### ISSUE THREAD

**Issue by winstrand** [vimeo/psalm#10956]
Still present in v3.4.3
Deprecated: Creation of dynamic property PhpParser\Node\Stmt\PropertyProperty::$fqsen
Deprecated: Creation of dynamic property PhpParser\Node\Stmt\ClassMethod::$fqsen
Deprecated: Creation of dynamic property PhpParser\Node\Stmt\Namespace_::$fqsen
Deprecated: Creation of dynamic property PhpParser\Node\Stmt\Class_::$fqsen

Same as #7007

**Comment by zonuexe** [comment]
Is it really [`3.4.3`](https://github.com/vimeo/psalm/releases/tag/3.4.3)? The [`3.x` branch](https://github.com/vimeo/psalm/tree/3.x) has also not been committed since 2020.

**Comment by winstrand** [comment]
# phpdoc --version
phpDocumentor vv3.4.3

Enviroment:
# php -v
PHP 8.2.12 (cli) (built: Oct 24 2023 21:15:15) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies

OS: Windows 11 (22H2)

**Comment by winstrand** [comment]
Sorry wrong lib
