### ISSUE TITLE
Ignoring extra params in callback

### ISSUE THREAD

**Issue by sserbin** [vimeo/psalm#1101]
In the following example psalm forces callback to be defined with exactly two parameters. However it's quite often the case that some of those parameters can be omitted (think of some util/collection-like functions, like `group()`, `reindex()`, `reduce()`(passing in `key`) etc which would regularly pass to callback everything available to them while not really being requested/used by callers)
```php
<?php

/**
 * @param callable(int,string):int $fn
 */
function foo(callable $fn): int
{
    return $fn(1, 'one');
}

foo(function (int $i) {
    return $i++;
});
// Argument 1 of foo expects callable(int, string):int, parent type Closure(int):int provided
```

I don't remeber this being enforced before and it's hard to tell whether it's intentional change or not. I can certainly see the point though, but at the same time this shouldn't be a big problem for the caller (that is, the fact caller doesn't care about anything else), isn't it? 
(well unless you are being passed a reference which you are expected to modify in callback, but you'd then have bigger problems anyway I'd imagine). 

Fwiw, say native `array_walk()` does *not force you to have a callback with both params (value and key), the following is totally fine with psalm:
```php
$arr = [1,2,3];
array_walk($arr, function (int $value) {
    print $value . PHP_EOL;
});
```

**Comment by muglug** [comment]
This is by design - I'm not really persuaded that it's bad.
