### ISSUE TITLE
incorrect UndefinedMethod error with traits

### ISSUE THREAD

**Issue by ylixir** [vimeo/psalm#1104]
when remapping the name of a trait function more than once, Psalm incorrectly throws an UndefinedMethod error for all but the last name mapping.

https://getpsalm.org/r/e815a86fbf

**Comment by muglug** [comment]
Did not know you could do this, also why?

**Comment by ylixir** [comment]
I made a trait to allow me to define enums easily and it does this. it's pretty gross if i'm honest, but it's typesafe without me having to maintain bunch of copy pasted `'a'|'b'|'c'` annotations to get psalm to typecheck it.

**Comment by ylixir** [comment]
here is the use case. it's terrible i know, i'd be happy to be educated on a simpler way of doing this as long as it doesn't involve a lot of copy paste boilerplate, or lots of places for me to forget to change string values or other bookkeeping for human error to creep in

https://getpsalm.org/r/e2ccb3be0d

**Comment by weirdan** [comment]
> it's terrible i know

I actually think it's very creative. Could use some minor improvements (e.g. https://3v4l.org/QfNqB), but impressive nevertheless. Is this your invention?

**Comment by ylixir** [comment]
Yes, that is my invention.

Although it didn't work at first because `__FUNCTION__` just gives the original trait function name. Thanks to stack exchange for the backtrace trick to get the correct function name.

I didn't know you could typehint `self`, that's cool.

**Comment by muglug** [comment]
Thanks!
