### ISSUE TITLE
Destructuring with possibly undefined element leads to confusing errors later

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#1107]
https://getpsalm.org/r/4db13bd33e
```php
<?php
  /** @var array{0?:string} */
  $entry = ["a"];

  [$elt] = $entry;
  strlen($elt);
```
This results in the following output:
```
Psalm output (using commit f84224b): 

ERROR: InvalidScalarArgument - 6:10 - Argument 1 of strlen expects string, string provided
```

The culprit, it appears, is that `$entry[0]` is possibly undefined, but Psalm fails to report it where it's accessed.

**Comment by weirdan** [comment]
Another variant of getting similarly confusing message is:
```php
<?php
  /** @var array{0?:string} */
  $entry = ["a"];

  /** @psalm-suppress PossiblyUndefinedArrayOffset */
  strlen($entry[0]);
```
https://getpsalm.org/r/aaa24f48dd

Should I report it as a separate issue?

**Comment by muglug** [comment]
Nah, the fix just wasn't comprehensive enough
