### ISSUE TITLE
Variadic argument in definition assumed to be array

### ISSUE THREAD

**Issue by Rarst** [vimeo/psalm#1110]
The following code:
```php
function variadic_arguments( $foo, ...$bars ) {}

variadic_arguments($baz, $qux);
```
Produces the following error:
```
MixedArgument - 5:26 - Argument 2 of variadic_arguments cannot be mixed, expecting array<int, mixed>
```
https://getpsalm.org/r/f406e5f761

There is no implication that second argument should be `array<int, mixed>` here.

I suspect it might be confusing `...` when _calling_ a function (which does expect arguments supplied as array) with its use when _defining_ a function (which means a variable amount of standalone arguments of the type).

**Comment by weirdan** [comment]
If you clear up the undefined vars errors this error also goes away: https://getpsalm.org/r/0d2047e515

**Comment by Rarst** [comment]
In my actual code there is still this error if the input is valid, but its type cannot be determined.

This specific message just seems to be misleading in nature. It doesn't say "you need to figure out which type argument is" it says "argument should be **numeric array**", which is not true.

**Comment by weirdan** [comment]
Oh, it would be even more confusing if it reported the type 'properly': "cannot be mixed, expecting mixed". Which kind of seem quite similar to #1107

**Comment by Rarst** [comment]
True, but I think just omitting expectation that cannot be determined would be better than claim _wrong_ expectation.

Primary purpose of `MixedArgument` is “cannot determine the type of an argument”, so `cannot be mixed` would satisfy that even in lack of `expecting` part.

**Comment by muglug** [comment]
I don't exactly understand the problem here - is your use-case different to the following?

```php
function variadic_arguments(...$bars) : void {}

/**
 * @param mixed $baz
 * @param mixed $qux
 */
function foo($baz, $qux) : void {
	variadic_arguments($baz, $qux);
}
```

https://getpsalm.org/r/427b0ea09d

**Comment by Rarst** [comment]
The problem is that if second argument `$qux` is of unknown type then error message claims it should be `array<int, mixed>`, which is wrong. It just pulls this array type out of thin air, probably because it's confused by variadic function definition?

As long as you don't have error "upstream" it doesn't matter. The problem is that if you _do_ have problem it causes error message to be incorrect and confusing.

**Comment by muglug** [comment]
Ah ok, then a potential fix might just stop analysis of args after an undefined variable
