### ISSUE TITLE
Broken error output without type/location/explanation

### ISSUE THREAD

**Issue by Rarst** [vimeo/psalm#1112]
Running Psalm on this file [`Load_Order_Manager.php`](https://github.com/Rarst/laps/blob/4013046e4f634f2bb28937534562f2952302b454/src/Manager/Load_Order_Manager.php), I get this error (verbatim) in console that is missing issue type, detected location, and explanation:

```
ERROR@return array
         */
        public function pre_update_option_active_plugins( array $plugins ): array {

                $plugin = plugin_basename( \dirname( __DIR__, 2 ) . '/laps.php' );
```

Copy/pasting file into online sandbox doesn't seem to replicate.

**Comment by muglug** [comment]
That looks like it comes from somewhere in your codebase. What happens when you run with `--debug-by-line`

**Comment by Rarst** [comment]
Nothing unusual. After some poking the details are there, but output to console specifically is broken. I am on Win7 with ansicon for color support.

Combing through source, the problem goes away if I delete fancy apostrophe [at the end of `plugins’`](https://github.com/Rarst/laps/blob/4013046e4f634f2bb28937534562f2952302b454/src/Manager/Load_Order_Manager.php#L23). Maybe it interacts in some strange way with color codes or something?..

**Comment by muglug** [comment]
If you run with `--monochrome` does it also go away?

**Comment by Rarst** [comment]
With monochrome the error part of the output disappears completely:
```
Scanning files...
Analyzing files...

------------------------------
1 errors found
------------------------------

Checks took 0.67 seconds and used 57.797MB of memory
Psalm was able to infer types for 98.495% of analyzed code (27 files)
```

**Comment by Rarst** [comment]
This is what I get if I run in Git Bash instead of cmd:

```
Scanning files...
Analyzing files...

[0;31mERROR[0m: MixedInferredReturnType - src\Manager\Load_Order_Manager.php:2
5:5 - Could not verify return type 'array<mixed, mixed>' for Rarst\Laps\Manager\
Load_Order_Manager::pre_update_option_active_plugins
        /**
         * Reorder active plugins so Laps is first and starts timing load early.

         *
         * @param array $plugins Filtered array of active plugins’ basenames.
         *
         * [97;41m@return array[0m
         */
        public function pre_update_option_active_plugins( array $plugins ): arra
y {

                $plugin = plugin_basename( \dirname( __DIR__, 2 ) . '/laps.php'
);


------------------------------
[0;31m1 errors[0m found
------------------------------

Checks took 0.62 seconds and used 54.110MB of memory
Psalm was able to infer types for 98.495% of analyzed code (27 files)
```
Honestly this seems like some strange console quirk rather than issue on your end, so feel free to close if you don't think this is worth looking into.

**Comment by muglug** [comment]
do you have a branch with Psalm analysis that I could test on? Curious to see if problem exists in unix-land too. 

It occurs to me that I don't escape output for the command line, but I should.

**Comment by Rarst** [comment]
It's pushed to master https://github.com/Rarst/laps , just config is tucked away in `config/psalm.xml`

**Comment by muglug** [comment]
Yeah, I'm unable to repro on Mac or Windows (regular command line) - I'm going to close, but feel free to ping if you can narrow it down.
