### ISSUE TITLE
Cannot access value on variable using a int<-2, 2> offset, expecting int<0, 2> if using % inside function

### ISSUE THREAD

**Issue by gleb-shchavlev** [vimeo/psalm#11160]
Outside function works fine:
https://psalm.dev/r/ceec7650a1

First bug:
https://psalm.dev/r/2e40c98518

```
Psalm output (using commit [03ee02c](https://github.com/vimeo/psalm/commit/03ee02c)): 

ERROR: [InvalidArrayOffset](https://psalm.dev/115) - 5:10 - Cannot access value on variable  using a int<-2, 2> offset, expecting int<0, 2>

INFO: [MixedReturnStatement](https://psalm.dev/138) - 5:10 - Could not infer a return type
```

Second bug:
https://psalm.dev/r/20a6400c5d

```
Psalm output (using commit [03ee02c](https://github.com/vimeo/psalm/commit/03ee02c)): 

ERROR: [InvalidArrayOffset](https://psalm.dev/115) - 5:8 - Cannot access value on variable  using a int<-2, 2> offset, expecting int<0, 2>

INFO: [MixedArgument](https://psalm.dev/030) - 5:8 - Argument 1 of echo cannot be mixed, expecting string
```

**Comment by MoonE** [comment]
In the first example psalm knows that index is always 2, so there is no error.

In the second and third example the function parameter is int. Meaning it could be possibly be negative. Psalm does not infer the param type as `2` from the call to it.
As this function only accepts ints >= 0, it should be annotated accordingly, to remove the warning.
https://psalm.dev/r/148ec04253

**Comment by gleb-shchavlev** [comment]
@MoonE Good explanation, thanks!
Will this behavior be fixed or do you suggest using annotations?

**Comment by MoonE** [comment]
It's good practice to annotate functions with precise parameters.
My understanding is that it is working as intended.
