### ISSUE TITLE
Issue with templates and intersection types

### ISSUE THREAD

**Issue by aidantwoods** [vimeo/psalm#1119]
I've tried to trim down most of the implementation details from the actual scenario here, hence there are a few nonsense looking empty structures.

A bit of motivation for the current setup:
I have a few classes that implement `Foo`, and some that almost implement `Foo` but require some `State` object that will be provided later in order to produce the final `Foo` result—these implement `AlmostFoo` which requires a `makeFoo(State $State): Foo` method.

In some cases I want to place the eventual result of an `AlmostFoo` inside an object that implements `Foo`, to do this in-place I use a `callable(State):Foo` closure to delay evaluating the `Foo` upfront. I wanted to create a templated class `AlmostFooMap` to wrap this closure so that this wrapper could too implement `AlmostFoo` via this callable (i.e. so that when I compose a `Foo` in terms of an `AlmostFoo` I can pass around a summary `AlmostFoo` that can produce a `Foo` given the later `State`).

I wanted to constrain the templated `T` so that the acceptable closures used to construct `AlmostFooMap` are `callable(State):(T&Foo)`, although when trying to implement the `makeFoo(State $State):Foo` Psalm complains that the returned `T` is more general then `Foo` (when in-fact it is both a `T` and a `Foo`).

I wasn't sure if this might be an issue with support for covariance of the declared return type, although when dropping the generic `T` type information from the implemented `makeFoo` in `AlmostFooMap` (i.e. change the return type on line 36 of the example to just `Foo`) I still run into some `MixedTypeCoercion` warnings, 
```
INFO: MixedTypeCoercion - 40:9 - The type 'T' is more general than the declared return type 'Foo' for AlmostFooMap::makeFoo

INFO: MixedTypeCoercion - 36:16 - The declared return type 'Foo' for AlmostFooMap::makeFoo is more specific than the inferred return type 'T'
```
so I'm thinking the problem here might be in retaining the intersection type within the typed closure `callable(State):(T&Foo)` and that Psalm may have just internalised this as `callable(State):T`?

---
Example:

https://getpsalm.org/r/9b16b5294b

```php
<?php

final class State
{}

interface Foo
{}

interface AlmostFoo
{
    /**
     * @param State $State
     * @return Foo
     */
    public function makeFoo(State $State);
}

/**
 * @template T
 */
final class AlmostFooMap implements AlmostFoo
{
    /** @var callable(State):(T&Foo) */
    private $closure;

    /**
     * @param callable(State):(T&Foo) $closure
     */
    public function __construct(callable $closure)
    {
        $this->closure = $closure;
    }

    /**
     * @param State $State
     * @return T&Foo
     */
    public function makeFoo(State $State)
    {
        return ($this->closure)($State);
    }
}
```
Psalm output (using commit 5f34f6c): 
```
ERROR: LessSpecificImplementedReturnType - 36:16 - The return type 'Foo' for AlmostFoo::makeFoo is more specific than the implemented return type for AlmostFooMap::makefoo 'T'
```

**Comment by weirdan** [comment]
> so I'm thinking the problem here might be in retaining the intersection type within the typed closure `callable(State):(T&Foo)` and that Psalm may have just internalised this as `callable(State):T`

Indeed: https://getpsalm.org/r/9cdd0d37b3
```
ERROR: InvalidArgument - 40:12 - Argument 1 of type expects void, callable(State):T provided
```

**Comment by aidantwoods** [comment]
Good call on defining that `type` function to get Psalm to print the type in the error message—didn't think of doing that.

Interestingly if `AlmostFooMap` doesn't implement `AlmostFoo` then Psalm reports no issues (looks like the intersection type is lost from both the closure return and the `makeFoo` return in this case, and Psalm just sees `T` for both—hence no issues), so looks like this issue isn't just restricted to closure returns.

"No issues": https://getpsalm.org/r/f6e0d696cb

Same code, but printing the type of closure reveals it is different to both return types (should be `callable(State):(T&Foo)`): https://getpsalm.org/r/56954f1dfc
```
ERROR: InvalidArgument - 40:14 - Argument 1 of type expects void, callable(State):T provided
```

**Comment by muglug** [comment]
as an aside, `void` is never a valid param type

**Comment by muglug** [comment]
One cosmetic issue: `callable:A&B` was only appearing as `callable:A` in error output (but Psalm still treated it as an intersection).

**Comment by muglug** [comment]
ok so after all the fixes improving error messages, we still have (for https://getpsalm.org/r/9b16b5294b) the following error message

```
ERROR: LessSpecificImplementedReturnType - 36:16 - The return type 'Foo' for AlmostFoo::makeFoo is more specific than the implemented return type for AlmostFooMap::makefoo 'T&Foo'
```

`Foo` is actually less specific than `T&Foo` so, as you suggested, it's a problem of return type covariance not working with templates (it works fine for standard interfaces: https://getpsalm.org/r/dd9373aac0)

**Comment by aidantwoods** [comment]
Awesome work, thanks for fixing that! :)

A couple of minor nits (sorry! 😃):
It seems that the intersection type prevents Psalm from doing type deduction to properly specify the templated type, and that Psalm then "upcasts" to `mixed`: https://getpsalm.org/r/6bbd19a07e

```
INFO: MixedTypeCoercion - 49:5 - The type 'AlmostFooMap<mixed>' is more general than the declared return type 'AlmostFooMap<FooImplementer>' for bar

INFO: MixedTypeCoercion - 46:13 - The declared return type 'AlmostFooMap<FooImplementer>' for bar is more specific than the inferred return type 'AlmostFooMap<mixed>'
```

I think that if Psalm knows the concrete type for any intersection expression involving (any number of) templated types then they should all get assigned to that concrete type

e.g. with `T`, `U` templated and `Foo` an already known type: if Psalm needs to check that a specified `someClass` is a `T&U&Foo` when instantiating a templated object, then it must check that `someClass` is a `Foo`, and then it can set `T` is a `someClass` and `U` is a `someClass` (it's possible that `T` and `U` could be allowed to be more general than `someClass`, but they cannot be more specific).

Maybe this is a feature request as I'm not sure this was technically expected to be supported?

---

I think this shouldn't be allowed: https://getpsalm.org/r/9872014b22, the constructor accepts a closure that returns just `T`, and then assigns it to an instance variable which is a closure that returns `T&Foo`. Then permits an actual usage of a non `Foo` as `T`.

I can open these as separate issues if you prefer?

**Comment by muglug** [comment]
> Maybe this is a feature request as I'm not sure this was technically expected to be supported?

Yeah, definitely a feature request. I feel like what's really desired is something like this (but without the error): https://getpsalm.org/r/69bf15cac2

That would be much simpler to implement.

> I think this shouldn't be allowed: https://getpsalm.org/r/9872014b22

Yeah, feel free to file both as separate issues
