### ISSUE TITLE
psalm --init fails with missing xml files

### ISSUE THREAD

**Issue by phodge** [vimeo/psalm#1127]
Hi, I'm trying to get started with psalm but `psalm --init` is failing due to missing xml files:

    $ cd /my/project
    $ composer require vimeo/psalm
    ...
    $ vendor/bin/psalm --init
    Could not open config template /my/project/vendor/vimeo/psalm/assets/config_levels/3.xml

I got this error using the latest `3.0.3`, but also when I tried `2.0.16` as well. I suspect there is something weird with my composer setup, but I have no idea what it might be.

**Comment by muglug** [comment]
Hey! Do those files exist in the folder? They really really should...

**Comment by phodge** [comment]
@muglug: I did some more digging and found that this legacy project I've inherited also has a dependency on the horrific train wreck that is https://github.com/dg/composer-cleaner which was deleting all of the psalm assets post-installation. Sorry for wasting your time!

**Comment by muglug** [comment]
No worries!
