### ISSUE TITLE
False positive UnusedVariable in try/catch/finally, potentially false negative too

### ISSUE THREAD

**Issue by tomtomau** [vimeo/psalm#1128]
Version: dev-master#

This is code we have written: https://getpsalm.org/r/855b47e04c

In this case, $stream is referenced in the finally block - false positive?

If we remove `$stream = null`, then Psalm does not report an issue with that use of $stream in the finally block, however $stream is an undefined variable - false negative then?

Psalm: [https://getpsalm.org/r/80dd67be7d](https://getpsalm.org/r/80dd67be7d)
3v4l: [https://3v4l.org/lFEK1](https://3v4l.org/lFEK1)

I would have thought that this would have been reported as an issue by Psalm, it's as if anything that is declared in the try block is risky to be using outside that scope unless it has been defined earlier? Not sure exactly.

**Comment by muglug** [comment]
Try/catch blocks are hard to reason about, but I agree this is a little problematic
