### ISSUE TITLE
Using new operator on specific class-string doesn't check __construct requirements

### ISSUE THREAD

**Issue by aidantwoods** [vimeo/psalm#1143]
The following is currently allowed by Psalm, even though it would fail in practice:

https://getpsalm.org/r/ef21737d26

```php
<?php

class Foo
{
    public function __construct(int $_)
    {
    }
}

/**
 * @return Foo
 */
function makeFoo()
{
    $fooClass = Foo::class;
    return new $fooClass;
}
```

Psalm output (using commit d70f853): 
```
No issues!
```

---

IMO if `$classString` is just known to be a `class-string` then the expression `new $classString` shouldn't be allowed: since the constructor might have requirements (as above), be `private`, or even might be throwing. `class-string` without any more specificity is the `mixed` of metatypes, and you shouldn't really be able to do much with it without running into analysis errors.

I think a better pattern to enable constructing metatypes might be something like (using the `@template T as ...` notation):
```php
<?php
  
interface DefaultConstructable
{
    public function __construct();
}

/**
 * @template T as DefaultConstructable
 * @template-typeof T $defaultConstructableClass
 * @param T::class $defaultConstructableClass
 * @return T
 */
function make($defaultConstructableClass)
{
    return new $defaultConstructableClass;
}
```

but this could be generalised to allow other static behaviour too if #1142 is fixed.

**Comment by muglug** [comment]
Thanks - I've fixed this for the case where there's only one possible class.

> IMO if `$classString` is just known to be a `class-string` then the expression `new $classString` shouldn't be allowed

I agree - this now triggers a `MixedMethodCall` issue (which in turn forced me to [improve Psalm's internal annotations](https://github.com/vimeo/psalm/commit/901596281c1522135ca2e27f97140730f059576a#diff-20a62f59764c9aa89c920a98d1b6ec16) to avoid this issue)

**Comment by aidantwoods** [comment]
Thanks! :D

> which in turn forced me to [improve Psalm's internal annotations](https://github.com/vimeo/psalm/commit/901596281c1522135ca2e27f97140730f059576a#diff-20a62f59764c9aa89c920a98d1b6ec16) to avoid this issue

This is really cool!
