### ISSUE TITLE
Invalid `RawObjectIteration` error when iterating an object implementing ArrayAccess

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#1145]
https://getpsalm.org/r/3c2a05352a

```php
<?php
/**
 * @param array|\ArrayAccess $options
 */
function foo($options): void {
    foreach ($options as $f) {
    }
}
```

```
ERROR: RawObjectIteration - 6:14 - Possibly undesired iteration over regular object ArrayAccess
```

**Comment by ADmad** [comment]
Can you please provide an example of instance of class which implements `ArrayAccess` but trying to iterate it generates an error? For e.g. this runs fine https://3v4l.org/HKe9J.

**Comment by weirdan** [comment]
`ArrayObject` that you've used implements `IteratorAggregate`

> but trying to iterate it generates an error

Iterating over any object is always 'valid' in PHP (meaning, it would not generate any error). It's, however, often quite pointless thing to do, and that's what Psalm telling you.

**Comment by muglug** [comment]
Yeah, this is by design (though easy to suppress as any other issue, obviously)
