### ISSUE TITLE
Invalid "RedundantCondition" error when checking return value of IntlDateFormatter::format()

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#1147]
As per the docs [IntlDateFormatter::format()](http://php.net/manual/en/intldateformatter.format.php) can return `false` on failure, yet the following code throws error.

https://getpsalm.org/r/51f37e06a7

**Comment by weirdan** [comment]
The link you posted does not illustrate the issue. Psalm complains that you can't pass `null` to `datefmt_create`.
