### ISSUE TITLE
Unexpected "RedundantCondition" reported when doing empty() check for iterable.

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#1149]
Since an argument type hinted as `iterable` can be an array, doing a `empty()` check for that variable should not generate `RedundantCondition` error.

**Comment by weirdan** [comment]
Got a sample code? I can imagine this error to be quite handy to remind me generators/iterators shouldn't be checked with `empty()`. And `is_array($iterable) && empty($iterable)` does not produce any issues.

**Comment by muglug** [comment]
Reproduced with https://getpsalm.org/r/9f78de4b04

```php
function foo(iterable $i) : void {
    if (empty($i)) {}
}
```

**Comment by muglug** [comment]
@weirdan  Yeah, that may be, but it's still a bug in Psalm

**Comment by ADmad** [comment]
@weirdan How is the above example muglug showed error prone? Since argument is non nullable it's not like someone can any other non empty value besides array to it.

**Comment by weirdan** [comment]
@ADmad I can easily see how someone may assume `empty($iterable)` to be something that would produce zero iterations when looped over.

**Comment by ADmad** [comment]
My understanding is that the purpose of pslam or similar static analyzer find potential errors in code, not prevent someone from misunderstanding the code.
