### ISSUE TITLE
Add @return no-return to denote a function that never returns

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#1155]
Hack has `noreturn`, Psalm could have something similar

**Comment by aidantwoods** [comment]
See also: [`Never`, from Swift](https://github.com/apple/swift-evolution/blob/master/proposals/0102-noreturn-bottom-type.md).

It's [possible](https://github.com/paragonie/airship/pull/203) to create the main feature of this type in pure PHP, although having things like `exit` also "return" this type would of-course require some understanding by Pslam. And having a standardised way to declare this would definitely be nice!

Is there any scope to make this a [bottom-type](https://github.com/apple/swift-evolution/blob/master/proposals/0102-noreturn-bottom-type.md#never-as-a-universal-bottom-subtype) too? :)

**Comment by muglug** [comment]
> Is there any scope to make this a bottom-type too?

Absolutely - it is in Hack: https://github.com/facebook/hhvm/commit/8eabac5c83c82fabd7334c02dbfa9a4d49c9f9c4 cc @manzyuk

**Comment by muglug** [comment]
Also in Hack, any function with `no-return` _must_ have an explicit `exit`/`throws` call - it's not enough that it just call a function that throws or exits.

**Comment by aidantwoods** [comment]
> Also in Hack, any function with `no-return` must have an explicit `exit`/`throws` call - it's not enough that it just call a function that throws or exits, and the same will apply in Psalm.

I assume that calling a function that returns `no-return` would be sufficient though?

**Comment by muglug** [comment]
> I assume that calling a function that returns no-return would be sufficient though?

Not in Hack, and it wasn't sufficient in Psalm, but now it is: cca0070

**Comment by muglug** [comment]
For the record, `@return no-return`, `@return never-return` and `@return never-returns` all result in the same return type.
