### ISSUE TITLE
MissingDependency false positive on UNIX

### ISSUE THREAD

**Issue by josephzidell** [vimeo/psalm#1156]
Similar to one of the original bugs in #1135, I am now running into a `MissingDependency` issue only on UNIX (my dev machine is windows 🙄), and it works fine there.

```
ERROR: MissingDependency - app/.../File.php:282:35 - ...\Model\AppModel depends on class or interface model that does not exist
```

Now, the parent class in question is `Model` (notice the capitalization), and throws no error on Windows, which is case-insensitive.

Let me know what else you need to solve this one.

**Comment by josephzidell** [comment]
There's no alias here. Also, this class is not namespaced, so I require it
in the psalm init file.

This is in Gitlab CI, which is run within a docker container.

**Comment by muglug** [comment]
> There's no alias here.

Oh! That's strange and interesting. How do you require it?

**Comment by muglug** [comment]
And does `Using reflection to locate file` appear when you run with `--debug`?

**Comment by muglug** [comment]
It's a bit of a shot-in-the-dark, but is it still broken after df9ea9e?

**Comment by josephzidell** [comment]
Let me try

**Comment by josephzidell** [comment]
Now it breaks on Windows also.

> How do you require it?

a `require_once`

> And does `Using reflection to locate file` appear when you run with `--debug`?

Yes, it does. `Using reflection to locate file for Model`

**Comment by muglug** [comment]
Sorry, lost track of this one.

Would you mind including the path (redacted where necessary) that you use in the `require_once` call?

**Comment by josephzidell** [comment]
```php
require_once "{$root}/vendors/cakephp/cakephp/lib/Cake/Model/Model.php";
```

**Comment by muglug** [comment]
Closing – feel free to reopen if you get a reproducer
