### ISSUE TITLE
PSALM hangs while trying to locate file with reflection

### ISSUE THREAD

**Issue by npoepperl** [vimeo/psalm#1162]
When analysing my code psalm hangs with this line as last output (while performing a deep scan on my php file):

`Using reflection to locate file for RobRichards\XMLSecLibs\DOMElement`

XMLSecLibs does not contain a class DOMElement. It's just using this class with `use DOMElement;`.

The XMLSecLibs are required by a package I'm depending on. So I don't directly use it. Is there a way to ignore the namespace (`XMLSecLibs`)?

**Comment by muglug** [comment]
What sort of autoloader are you using?

**Comment by weirdan** [comment]
I might be mistaken, but their autoloader seem to be prone to infinite recursion here: https://github.com/simplesamlphp/simplesamlphp/blob/2d3504f577aa59114287dda22ce27434c3d53c07/lib/_autoload_modules.php#L24

**Comment by weirdan** [comment]
Yep, that must be it: https://github.com/weirdan/simplesaml-autoloader-recursion

**Comment by muglug** [comment]
Thanks @weirdan!

**Comment by npoepperl** [comment]
😮 
You are awesome! Thank you very much for the great support! 🥇
