### ISSUE TITLE
Feature request: add Like<_> type.

### ISSUE THREAD

**Issue by aidantwoods** [vimeo/psalm#1166]
In https://github.com/vimeo/psalm/issues/1143#issue-393718578 I suggested that

```php
<?php
  
interface DefaultConstructable
{
    public function __construct();
}

/**
 * @template T as DefaultConstructable
 * @template-typeof T $defaultConstructableClass
 * @param T::class $defaultConstructableClass
 * @return T
 */
function make($defaultConstructableClass)
{
    return new $defaultConstructableClass;
}
```

might be a candidate pattern for replacing `new $classString` when the exact `$classString` type isn't known, but we want to enforce that the type that is passed is constructable. This has the downside that the types we pass in must explicitly be defined to implement `DefaultConstructable`, and won't work very well when trying to combine types that we do not have direct definitional control over.

There are a few approaches taken to try to solve this problem by languages e.g.

* In Go, any type which has the correct methods and properties to implement an interface is considered to implement it with no need to declare it explicitly in the definition
* In Swift, types can have "extension"(s) written (not a subtype) that increases the surface area of the original type's interface: so that the original type can be extended with new methods or (computed) properties (if necessary) to implement interfaces ("protocols" in Swift).

I don't think either approach would work here though, since we can't ever make PHP's runtime happy that an interface has been implemented unless it was explicitly defined that way.

So I would propose a new annotation/type could be added to Pslam, so as to restrict acceptable types to types that are "like" an interface (have the necessary interface, but don't explicitly have a subtyping relation).

I originally thought it would be a good idea to write something like `@template T like DefaultConstructable` to mean that `T` has the same interface  as `DefaultConstructable`, but doesn't necessarily implement it.
This would already be a powerful feature, since it would allow all cases that previously used `new $classString` (without knowing what `$classString` was) to simply define an interface, and use this new notation in the function that accepts the class string without needing to redefine any other types to be aware of `DefaultConstructable`.
What might be one step better, though. Is to have Psalm support a new type `Like<T>` where Psalm can check that if `Foo` has a compatible interface with `T`, then `Foo` is a subtype of `Like<T>`. Clearly `Foo` is a `Like<Foo>` but not necessarily the converse[1]. We could then write `@template T as Like<DefaultConstructable>`, but would also be able to use this annotation with non-generic types: i.e. write `@param Like<DefaultConstructable> $something` which should let us use the interface of `DefaultConstructable` when using `$something`, but we don't know whether `$something` is a `DefaultConstructable` (or anything else about it) within the function body.

---

Some rambling that might help with type deduction and simplifying type expressions:

`Like<_>` is also a monad: Suppose that `T` has a method `foo(Bar $Bar): Baz` (w.l.o.g. due to properties only caring about covariance, which is covered by considering a method). Then any `Like<T>` has a method `foo(_Bar $Bar): Baz_` where `Bar` is a `_Bar` and `Baz_` is a `Baz`. Any `Like<Like<T>>` then has a method `foo(__Bar $Bar): Baz__` where `_Bar` is a `__Bar` and `Baz__` is a `Baz_`. Since any `Like<Like<T>>` has a compatible interface with `T`, then `Like<Like<T>>`  is a `Like<T>`. But also any `Like<T>` is a `Like<Like<T>>` (by [1]) and so `Like<Like<T>> = Like<T>`.

We can also note that `mixed` has no interface requirements, and so trivially any type is a `Like<mixed>`, and since any type is a `mixed`, `Like<mixed>` is a `mixed` so `Like<mixed> = mixed`.

There are also some nice properties with union and intersection types:
Any `Like<T>|Like<U>` is a `Like<T>` or a `Like<U>`, so has a compatible interface with `T` or `U`, i.e. `Like<T>|Like<U>` is a `Like<T|U>` (similarly `Like<T|U>` is a `Like<T>|Like<U>`). Any `Like<T>&Like<U>` has a compatible interface with `T` and with `U`, so `Like<T>&Like<U>` is a `Like<T&U>` (similarly `Like<T&U>` is a `Like<T>&Like<U>`). i.e.  `Like<T|U> = Like<T>|Like<U>` and `Like<T&U> = Like<T>&Like<U>`.

---

I do keep meaning to have a proper read through the source, so that I can help out a bit more than just requesting features and reporting bugs ;-) Please let me know if I made any mistakes in the above!

**Comment by muglug** [comment]
This is interesting. The obvious issue is about reserved words - in docblock annotations the simplest way to avoid reserved words is with a `-`, e.g. `like-object<Foo>`.

Psalm has a method that compare methods: https://github.com/vimeo/psalm/blob/ca6149ed172585063bd13adfbddd3d34a46d220b/src/Psalm/Internal/Analyzer/MethodAnalyzer.php#L422 which you could use to do _some_ of the initial work, if you're interested.

**Comment by aidantwoods** [comment]
> The obvious issue is about reserved words - in docblock annotations the simplest way to avoid reserved words is with a `-`, e.g. `like-object<Foo>`.

This seems reasonable, wrt `like-object`, I wonder whether `like-type` could be preferable? It's slightly shorter, and also leaves open the possibility of considering what the "interface" of certain scalars might be in the future. E.g. in particular, if a type implements the magic 🧙‍♂️ `__toString` then it *could* be regarded to be *like a string*, or perhaps `like-type<string>`. (Funnily enough this behaves way more like a string than I might have expected: https://3v4l.org/YmJsI). Scalars are probably best approached more carefully and with some restraint though, objects are the primary goal here.

> Psalm has a method that compare methods: [...] which you could use to do some of the initial work, if you're interested.

I'll venture into taking a look :)

**Comment by muglug** [comment]
Decided not to do this, too complicated
