### ISSUE TITLE
false positives on filesystem-related funcs

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#117]
On both 0.3.31 and dev-master 30e8e18, the following snippet resulted in these errors:
1) "Cannot resolve types for $freeSpace - float does not contain false"
2) "Cannot resolve types for $sourceResource"
3) "Cannot resolve types for $destinationResource"
4) "Cannot resolve types for $copySucceeded - int does not contain false"

```php
$freeSpace = disk_free_space($this->rootPath);
if ($freeSpace === false) { // error #1
    throw new RuntimeException(
        'Cannot determine disk free space!'
    );
}

// some other stuff

$sourceResource = fopen($file->getRealPath(), 'r');
if (!is_resource($sourceResource)) { // error #2
    // implementation-specific exception gets thrown here
}

$destinationResource = fopen($destination, 'w');
if (!is_resource($destinationResource)) { // error #3
    // implementation-specific exception gets thrown here
}

$copySucceeded = stream_copy_to_stream($sourceResource, $destinationResource);
$closeSourceSucceeded = fclose($sourceResource);
$closeDestinationSucceeded = fclose($destinationResource);

if ($copySucceeded === false) { // error #4
    // implementation-specific exception gets thrown here  
}
```

Just wondering if there's a config thing I'm missing for psalm to know the correct return types ?

p.s.:

```bash
$ php -v
PHP 7.1.1 (cli) (built: Jan 18 2017 18:51:14) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by muglug** [comment]
Thanks for this v. concise issue!

**Comment by SignpostMarv** [comment]
You're welcome :)

My tests pass now, thanks :D

**Comment by muglug** [comment]
And (if it wasn't obvious from the commit) the return & param types of builtin functions are stored in [`src/Psalm/CallMap.php`](https://github.com/vimeo/psalm/blob/master/src/Psalm/CallMap.php), which is synced semi-regularly to its [source of truth](https://github.com/etsy/phan/blob/master/src/Phan/Language/Internal/FunctionSignatureMap.php) in a similar project.
