### ISSUE TITLE
Add inspection for incorrect casing in function/method-calls

### ISSUE THREAD

**Issue by mindplay-dk** [vimeo/psalm#1174]
Inspections for the following are missing:

```php
<?php
  
function myFunc(): void {}

myfunc(); // wrong case

abstract class MyClass {
  public static function myMethod(): void {}
}

MyClass::mymethod(); // wrong case

class MyOtherClass {
  public function myMethod(): void {}
}

(new MyOtherClass())->mymethod(); // wrong case
```

**Comment by SignpostMarv** [comment]
tools like php-cs-fixer identify this, i'm thinking this should only be an issue if it's referring to magic methods, i.e.

```php
class Foo {
    public function __call(string $method, array $args) {
        switch (mb_strtolower($method)) {
            case 'mymethod':
                return var_export($args, true);
        }
    }
}
```

followed up with plugin magic to determine what the methods are?

**Comment by muglug** [comment]
This shouldn't be an issue at any level - PHP is currently case-agnostic w/r/t functions. It's slightly different for classes, where autoloaders can be case-sensitive (hence `InvalidClass`).

I've created an example plugin that should meet your needs, though: https://github.com/vimeo/psalm/blob/8ab5fae4842cb4e74f0ed88af8bb728e59280c14/examples/plugins/FunctionCasingChecker.php

**Comment by SignpostMarv** [comment]
@muglug I was thinking of something like intervention/image that has the methods defined off on classes, only without all the `@method` docblocks on the class to say what the methods were- namely, a magic method processor that triggered case-sensitive autoloading.

**Comment by mindplay-dk** [comment]
> tools like php-cs-fixer identify this

There's already a ton of overlap with php-cs, php-md, php-stan and probably others - I was hoping this would become the one tool to replace them all... (not least of all PHP Storm, where I'd love to be able to finally turn off their inspections entirely and rely on *one* tool that can also run on the CI server.)

> This shouldn't be an issue at any level - PHP is currently case-agnostic w/r/t functions

Plenty of things currently caught by this tool aren't strictly an issue.

Plenty of things are just coding standards and preferences, not strictly bugs, and (especially) not provable bugs in PHP code. (Am I wrong?)

If you really don't want this feature, I'd love it if someone could clarify, what exactly is the goal and scope of this tool?

I'd hate to have "just another tool" - we have far too many tools as it is, all of them have overlapping features, inconsistencies, different limitations, wildly different configuration file-formats and so on... it's already a mess - if I'm going to introduce another tool, it's going to be because I can use it to kill off at least one of these other tools.

Ideally, all of them. Because it seems like this tool already has the best, most versatile architecture - and love to help contribute any missing features so we can finally have a clean CI configuration with all our code-standards verifiable from one place, with IDE support.

**Comment by muglug** [comment]
Thanks for that!

Here are the goals as they exist today:

Goal 1: provide a programme that allows you to discover potential bugs and logical flaws in your code, and to make it easy to fix them

Goal 2: provide a plugin system that allows you to piggyback off Psalm’s type inference engine to perform tasks that may or may not relate to finding bugs

Pretty much all issues Psalm finds relate to the first goal. For example, the warning about missing param types is *really* Psalm complaining that you’re not giving it enough information for it to do its job properly. The `totallyTyped` mode is a natural extension of that.

There are a few other things it does because it’s well-placed to - checking `@internal`, `@deprecated` and `@throws`, and dead code detection. I could have made these into plugins, but I decided that they’re all something that most people would like available, so I added them.

There are a number of things Psalm is definitely not designed for, e.g. formatting checks (the AST strips white space). Others (like cyclomatic complexity checks) could be bolted-on, but I’m a little wary of bloat (especially when running as a language server).

There are still many things that PHPStorm does that Psalm could do in its core (e.g. renaming methods). I’ve not much interest in adding those features at the moment, but would welcome thoughts, issues and PRs.

**Comment by mindplay-dk** [comment]
@muglug thanks for the clarification :-)

I definitely don't expect code quality metrics or source formatting checks from a tool like this.

The inspection in question isn't about formatting though, it's about consistency. I know inconsistent formatting is allowed in PHP, but it isn't popular - pretty much every coding standard mandates consistent case.

You don't want this in the tool though, that's fine - plugins don't look too complex, I'm sure we can build our own package to enforce all of our coding standards.

Still don't completely understand why this would be out of scope, but, oh well :-)

**Comment by muglug** [comment]
> Still don't completely understand why this would be out of scope, but, oh well :-)

Out of scope because, AFAIK, this can never cause a bug in the execution of PHP code (unless someone's subverting PHP's case insensitivity with `__call`)

**Comment by mindplay-dk** [comment]
> AFAIK, this can never cause a bug in the execution of PHP code

Nor can things like doc-blocks?

The problem as I see it, is that PHP is inconsistent on this point - with method-names being case-insensitive, and property-names being case-sensitive, it's easy for someone to make a mistake that introduces bugs to the code.

For example, changing a method-name from `getUuid()` to `getUUID()` is strictly not a breaking change (though I would certainly frown upon this assumption in a code-review) but renaming a property from `$userName` to `$username` is breaking.

I expect that's why most other tools warn about this issue by default?

**Comment by muglug** [comment]
> > AFAIK, this can never cause a bug in the execution of PHP code

> Nor can things like doc-blocks?

Yeah, but docblocks are nevertheless contracts that allow Psalm to verify your code is free of bugs that could cause fatal errors. Here, for example, calling `foo` doesn't cause a fatal error, but code that depends on that documentation being correct will fail:

```php
/** @return int */
function foo() {
  return new stdClass;
}

echo foo();
```

> PHP being _partially_ case-sensitive, it's safer to just assume it is.

If Psalm flags things that are not bugs, and the user knows they're not bugs, it will cause that user to ignore other issues that maybe _are_ bugs, which is unsafe.

> I expect that's why most other tools warn about this issue by default?

Not static type-inferring static analysis tools - Phan doesn't at all, and PHPStan only does it via a plugin.

I think  "psalm-style" plugin is the best approach for this (and related) functionality. I've just enabled the above-referenced plugin in Psalm's own codebase: https://github.com/vimeo/psalm/commit/b43a6a31f1c6d8490849337c8e4a9c0114c42627

Obviously this is subject to change if, as Hack has done, PHP announces plans to become case sensitive for user-defined function names in a future version (a change I'd welcome)

**Comment by mindplay-dk** [comment]
> I think a "psalm-style" plugin is the best approach for this (and related) functionality.

Okay, sold :-)

I was hoping to sell my team on the idea of replacing code-sniffer and mess-detector (both of which have been giving us headaches) but I understand now why that's not appropriate.

I'm still going to push for us to integrate Psalm in our CI stack though - we'll see how that goes, and then I'll probably push for us to build a plugin for style-checks... we'll see.

Thank you for your patience and clarifications :-)

**Comment by muglug** [comment]
You’re welcome!
