### ISSUE TITLE
issue with var_export in ternary with is_numeric

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1178]
somewhere between 3.0.8 & 3.0.9 (edit: 9d8c2792e2f8503e6d0272b41e4a53404871fd6c), psalm seems to think scalar does not contain numeric:

https://getpsalm.org/r/686b84fb97

```php
<?php
declare(strict_types=1);

/**
* @var array<string, scalar>
*/
$props = [];

foreach ($props as $val) {
  echo is_numeric($val) ? (string) $val : var_export($val, true);
}
```

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/a2ee2f12a4e75a512fb30b27174ea1c9454ad79d.

It's been broken for much longer - at least, the testcase

```php
/** @param scalar $val */
function foo($val) : void {
    if (!is_numeric($val)) {}
}
```
has been broken forever

**Comment by muglug** [comment]
But thanks for ticketing!
