### ISSUE TITLE
MixedTypeCoercion for new array-key property type when combining array functions

### ISSUE THREAD

**Issue by tomtomau** [vimeo/psalm#1179]
[Example](https://getpsalm.org/r/ab11d57eda)

As a user, I do not expect to get a warning here.

I can do a gross work around like [this](https://getpsalm.org/r/123cdf5277) but I don't feel like I should have to do this with a `string[]` type the assumption is that the key is an integer

**Comment by tomtomau** [comment]
Additionally, I think this is possibly related:
[additional example](https://getpsalm.org/r/32afae1b6e)

**Comment by muglug** [comment]
This is by design! You're doing something *slightly* risky, so Psalm should warn you about it.

**Comment by tomtomau** [comment]
Ah okay. So we should be explicitly typing the value of the keys then? Like I did in the work around?

**Comment by muglug** [comment]
Yeah, if you want to avoid this issue.
