### ISSUE TITLE
Too many arguments for method array_keys

### ISSUE THREAD

**Issue by MetalArend** [vimeo/psalm#118]
The [array_keys](http://php.net/manual/en/function.array-keys.php) method has the ability to add a third strict parameter, but psalm tells me I have `Too many arguments for method array_keys` when using the third parameter.

**Comment by muglug** [comment]
Fixed in 7800d34b5925e4e976a1697b3aa130709a274336

**Comment by MetalArend** [comment]
Wow, sweet, that was fast. And now that I know how to fix, I will do it myself next time 👍

**Comment by muglug** [comment]
Awesome! Most function definitions are kept in [CallMap.php](https://github.com/vimeo/psalm/blob/master/src/Psalm/CallMap.php), but some `array_` are templated so their return type can be dependent on their input types.
