### ISSUE TITLE
Question: how to implement plugin with restriction to count public methods in class

### ISSUE THREAD

**Issue by andrew-demb** [vimeo/psalm#1183]
I want to implement plugin, that will restrict to have only 1 public method in my controller classes.

I know, that `AfterClassLikeVisitInterface` is cover my issue, but it works only with `--no-reflection-cache` or on first call (on empty cache). Also, it will trigger the hook on non-project classes.

Are planned to implement hook on class check (on `ClassAnalyzer::analyze()` method) or include to `afterStatementAnalysis` class method check event?

**Comment by muglug** [comment]
Added a `AfterClassLikeAnalysisInterface` hook for this!
