### ISSUE TITLE
`password_hash` should return `string|false`, not `string|null`

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#1188]
https://github.com/vimeo/psalm/commit/2f30132d9488bfd7e4aee6688f36d3cefeef7919#diff-4355ecf0bcc89fe8c145b64be0e02ddfL8647 — this commit replaced proper signature with the broken one.

**Comment by weirdan** [comment]
Additionally:
- `SQLiteUnbuffered::column` is mixed, not void
- `spliti` is removed in 7.0

**Comment by iluuu1994** [comment]
This issue seems to have regressed.

https://github.com/vimeo/psalm/blob/dc78e9c57ba58e21e7970451ca52314b398fc811/src/Psalm/Internal/CallMap_74_delta.php#L18

According to the PHP docs nothing has changed.

**Comment by weirdan** [comment]
> This issue seems to have regressed.

Almost a [year ago](https://github.com/vimeo/psalm/commit/8edb1174512c5f42ed0a733f088081f63b992ab7#diff-44478d770bbfc81347d61bd7a95c1b40) in fact. 
/cc @bugreportuser

**Comment by bugreportuser** [comment]
I believe this is correct. In 7.4, [there is no false return](https://github.com/php/php-src/blob/PHP-7.4/ext/standard/password.c#L727-L756).

This change was not documented, which is why [this bug](https://bugs.php.net/bug.php?id=77218) exists.

**Comment by weirdan** [comment]
Oh, I totally forgot we already discussed it back then.

**Comment by bugreportuser** [comment]
That's fine. It's good this was revisited after the 7.4 release.

**Comment by iluuu1994** [comment]
Thanks guys! Bummer this takes so long to fix in the docs.

**Comment by muglug** [comment]
Sorry, would one of you mind PRing again with the correct signatures? And also leave a comment this time so someone well-meaning doesn’t undo them (here's where they were changed: https://github.com/vimeo/psalm/pull/2396/files#diff-4355ecf0bcc89fe8c145b64be0e02ddf)

**Comment by weirdan** [comment]
@muglug the delta is fine, as it's changed in 7.4. Does CallMap represent the latest stable PHP version (7.4 now)?

**Comment by bugreportuser** [comment]
@muglug The signatures are already correct. The return type changed in 7.4. The documentation is wrong.

A PR with a comment is a good idea. Do you want that [here](https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/CallMap_74_delta.php#L18) or [in the callmap](https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/CallMap.php)?

**Comment by iluuu1994** [comment]
Is it correct through that this issue was triggered when running on PHP 7.3?

**Comment by bugreportuser** [comment]
@iluuu1994 Now I understand. [This PR](https://github.com/vimeo/psalm/pull/2396) is new. It made a change in the callmap that was already in the 7.4 delta. I'll create a PR to fix that.

**Comment by muglug** [comment]
The callmap should have the latest PHP version’s changes, with the deltas providing backwards-compatibility

**Comment by bugreportuser** [comment]
@muglug Ok, then maybe the delta isn't being correctly applied for PHP 7.3. I'm getting the same signature as @iluuu1994.

Example on master:

*php73.php*:

```php
<?php
echo password_hash("password", PASSWORD_DEFAULT) === false;
```

```
$ psalm --php-version=7.3 php73.php

ERROR: TypeDoesNotContainType - php73.php:2:6 - null|string does not contain false
