### ISSUE TITLE
possible path normalisation issue with baseline files

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1192]
developing on a windows machine, running tests again with scrutinizer on linux: 
* [scrutinizer run](https://scrutinizer-ci.com/g/SignpostMarv/daft-object/inspections/77ba6245-5093-498b-af93-beaec78234d2)
* [github diff containing baseline](https://github.com/SignpostMarv/daft-object/compare/e0fb4705610291d1b43142ab3b9545ad0630d581...635be688dd0470f25cbcf43aa7cfb25ba0c91c55)

tests fail because of psalm errors not being suppressed by the baseline file, will be running a little experiment shortly.

**Comment by SignpostMarv** [comment]
scrutinizer run succeeds with the above-mentioned theory test, but `composer run tests` fails locally because the paths don't match. definitely looks like a path normalisation issue: https://scrutinizer-ci.com/g/SignpostMarv/daft-object/inspections/223c17d1-e687-44ab-bc13-25c2a7f87541

**Comment by muglug** [comment]
Thanks for identifying that! Try with latest master - hopefully should worl

**Comment by SignpostMarv** [comment]
sorted :D
