### ISSUE TITLE
Assignments in by-ref arguments are ignored

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#1195]
https://getpsalm.org/r/a5a892b16c.

Either of the first three params of `stream_select()` can be null.
From php manual:
```
You do not need to pass every array to stream_select(). You can leave it out and use an empty array or NULL instead. 
```

**Comment by weirdan** [comment]
On a related note, it appears side-effects in `stream_select`s arguments are not evaluated (but they should): https://getpsalm.org/r/cc72102f5f

**Comment by weirdan** [comment]
@ADmad however your code is invalid, and Psalm properly tells you it is: https://3v4l.org/5JsSd

**Comment by weirdan** [comment]
To expand on that, yes, arguments could be null, but they must be variables nevertheless.

**Comment by ADmad** [comment]
Such usage is present in CakePHP.

https://github.com/cakephp/cakephp/blob/8c2ccf1b8c0617fc0c5273664975a9ca6a3698d9/src/Console/ConsoleInput.php#L80.

But given such usage generates error it seems that method is never used :stuck_out_tongue:.

**Comment by muglug** [comment]
Works for regular functions, broken for byref args: https://getpsalm.org/r/f1001b2ed0
