### ISSUE TITLE
Add support for parameterised variable checks

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#12]
This code passes (if `$a` is an `array<mixed>` and `Foo::bar()` is a method)

```php
if ($a['b'] instanceof Foo) {
  $a['b']->bar();
}
```

but this code (assuming `$b` is defined) emits a `MixedMethodCall` issue:

```php
if ($a[$b] instanceof Foo) {
  $a[$b]->bar();
}
```

It currently fails because Psalm does not allow array fetches with variable-key-offsets to be considered scoped variables. But we should adapt Psalm to allow variable-key array offsets, and then remove those variables from `Context::$vars_in_scope` when either the array is modified or the key variable is modified.

Related (slightly) to https://github.com/vimeo/psalm/issues/11

**Comment by weirdan** [comment]
@muglug This seems to have been fixed already.

**Comment by muglug** [comment]
Yes!
