### ISSUE TITLE
Document `falsy` (e.g. in psalm-assert)

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#1203]
It isn't mentioned in CHANGELOG.md or docs/

Also document that it works on conditions, not just variables

I noticed an example in the tests:

```php
                    /**
                     * @param mixed $_b
                     * @psalm-assert !falsy $_b
                     */
                    function myAssert($_b) : void {
```

**Comment by muglug** [comment]
Yeah, [I added a block](https://github.com/vimeo/psalm/commit/f5378bdc#diff-7f1b4a6294505ffc7937ee5c92f02fb7R2199) to handle `@psalm-assert !falsy $var` calls so it could mimic `assert($expr)` without needing a variable/property (a fairly common use-case), but I don't have a general solution to that problem

**Comment by TysonAndre** [comment]
I went with something similar instead of a general solution - phan-assert-true-condition and phan-assert-false-condition are mostly equivalent to `!falsy` and `falsy`

**Comment by ruudk** [comment]
Maybe good to also document `!false` and `!true`, since it's nowhere to be found, but does work, see: https://psalm.dev/r/dfa38a60dc

**Comment by muglug** [comment]
@ruudk would you mind adding the documentation? The file is here: https://github.com/vimeo/psalm/edit/master/docs/annotating_code/assertion_syntax.md

**Comment by ruudk** [comment]
@muglug Done, https://github.com/vimeo/psalm/pull/2528
