### ISSUE TITLE
Missing implied inheritdoc for properties

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#1210]
```php
class x {
  /**
   * @var string|null
   */
  protected $a;
  
  /**
   * @var string|null
   */
  protected static $b;
}

class y extends x {
  protected $a = 'foo';
  protected static $b = 'foo';
}
```

https://getpsalm.org/r/c977f20499
Expected: no issues

**Comment by ro0NL** [comment]
Same for methods: https://getpsalm.org/r/98af582a23

**Comment by muglug** [comment]
Second issue ticketed in #1213

**Comment by muglug** [comment]
Your example for methods was different, because there's a type given, and the Liskov Substitution Principle allows functions to take wider param types than their parent.
