### ISSUE TITLE
False-Positive InvalidStringClass when string is passed and used for class

### ISSUE THREAD

**Issue by andreasschroth** [vimeo/psalm#1222]
Please see this code example:

https://getpsalm.org/r/abae86f87f

It reports that the string cannot be used as a class although the string is just used for instantiating the new class.

**Comment by andreasschroth** [comment]
Alright, thank you for clarifying @weirdan . I'm closing this.

**Comment by andreasschroth** [comment]
Reopening, because it does not work with `allowStringToStandInForClass="true"` in config when the parameter is passed to the method and the declared type is string.

Please see this updated example: https://getpsalm.org/r/955f251906

**Comment by muglug** [comment]
Hey @andreasschroth, did @andrew-demb’s fix work?

**Comment by andreasschroth** [comment]
@muglug Yep, thanks a lot, works with this fix. 👍
