### ISSUE TITLE
Suppression of MissingClosureParamType impossible if Closure inside a function call

### ISSUE THREAD

**Issue by andreasschroth** [vimeo/psalm#1223]
Please see this code:

https://getpsalm.org/r/f3529162d2

I can't suppress the `MissingClosureParamType` info, no matter if I place it directly in the line before or even before the whole function.

**Comment by andreasschroth** [comment]
Ah alright, thank you @weirdan 👍 

But isn't it also supposed to work in the docblock of the main function as well?

**Comment by weirdan** [comment]
Yeah, that would be useful.

**Comment by muglug** [comment]
Yeah, you’d typically add line breaks to make the code prettier.

But it’s not unreasonable to want issue suppressions to cascade down through closure boundaries, so I’ll fix that.

You know that you can suppress these issues at the config level too?

**Comment by muglug** [comment]
Turned out the issue was just limited to `MissingClosureParamType` - everything should be good now.
