### ISSUE TITLE
request for plugin hook to allow plugins to preempt PropertyFetchAnalyzer & PropertyAssignmentAnalyzer

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1228]
following on from the [twitter thread](https://mobile.twitter.com/psalmphp/status/1087938219054903299), I'm requesting psalm be modified to allow plugins to preemptively populate class storage to allow them to assert that an interface has magic properties.

While phpdoc's `@property`, `@property-read`, & `@property-write` could be used to imply that properties exist, the approach I'm taking explicitly requires a type implement `__get()` & `__set()` which wraps the property to a predictably formatted method (which allows for types to be explicit as well). I've got a [phpstan plugin in my project implementing this](https://github.com/SignpostMarv/daft-object/blob/c91fcc3d96aeeb2943d38200173838bf041c5db6/PHPStan/ClassReflectionExtension.php#L41) with fewer assumptions than the exhaustive phpunit checks, but as mentioned in the twitter thread I've extracted the code and made it more generic so it could be reused by others that don't necessarily follow the same method naming scheme.

Additionally, I was taking a peek at `Psalm\Storage\PropertyStorage` and I'm not sure how to clarify that a given property is read-only or write-only; real-world use-cases for this are anything that implements a read-only `length` property that wraps to `Countable::count()` or other value not directly changeable, or a write-only `password` paired with a readable `password_hash` property that internally wraps to `password_hash()`. This might come in handy for stubs, given that `DOMNodeList::$length` is stubbed out, but not explicitly declared as readable leading to [no issues in psalm](https://getpsalm.org/r/8a3d234680) but [issues at runtime](https://3v4l.org/cpdDk)

**Comment by muglug** [comment]
I've allowed some behaviour for interfaces with magic get and set when suppressing `NoInterfaceProperties` (which can now be narrowed down by `<referencedClass="YourInterfaceName" />`):

```php
/**
 * @property-read string $foo
 * @psalm-seal-properties
 */
interface GetterSetter {
    /** @return mixed */
    public function __get(string $key);
    /** @param mixed $value */
    public function __set(string $key, $value) : void;
}

/** @psalm-suppress NoInterfaceProperties */
function getFoo(GetterSetter $o) : string {
    return $o->foo;
}

/** @psalm-suppress NoInterfaceProperties */
function getBar(GetterSetter $o) : string {
  return $o->bar;
}
```

you can use a plugin that updates the storage (so you don't need the `@property-read/@property-write/@psalm-seal-properties` annotations

```php
class SpecialPropertyChecker implements Hook\AfterClassLikeVisitInterface
{
    /**
     * @param  FileManipulation[] $file_replacements
     *
     * @return void
     */
    public static function afterClassLikeVisit(
        PhpParser\Node\Stmt\ClassLike $stmt,
        ClassLikeStorage $storage,
        FileSource $statements_source,
        Codebase $codebase,
        array &$file_replacements = []
    ) {
        if ($stmt instanceof PhpParser\Node\Stmt\Class_ &&
            !$storage->abstract &&
            ($fq_class_name = $storage->name) &&
            in_array(strtolower(GetterSetter::class), $storage->class_implements)
        ) {
            foreach ($some_property_provider as $property_name => list($read_type, $write_type)) {
                if ($read_type) {
                    $storage->pseudo_property_get_types['$' . $property_name] = $read_type;
                }

                if ($write_type) {
                    $storage->pseudo_property_set_types['$' . $property_name] = $write_type;
                }
            }
              
            $storage->sealed_properties = true;
        }
    }
}
```

**Comment by muglug** [comment]
The alternative requires a much bigger change - turn these properties on objects (`ClassLikeStorage::$properties/$pseudo_property_get_types` etc) into methods, and allow you to extend `ClassLikeStorage` with your own implementation.

That would probably have a sizeable performance impact, but if it enabled a broader landscape of plugins I might be up for it.

OTOH I'm really interested in more powerful docblock annotations so people don't have to write plugins.

**Comment by SignpostMarv** [comment]
bit of a config issue going on here: https://gist.github.com/SignpostMarv/9a92ea1e53bed6f5d762f3cc60800e39

**Comment by muglug** [comment]
Crap, sorry - fixed in fb28362fb9b17a833631d19c3f745b30bbcce3e8

**Comment by SignpostMarv** [comment]
it doesn't seem to be visiting ?, i.e. running `./vendor/bin/psalm ./quick-checks/` & `var_dump($stmt->name->name)` doesn't show up any of the fixtures.

**Comment by muglug** [comment]
Might be a cache issue - run with `--no-reflection-cache` and if that works, clear your cache and run without

**Comment by SignpostMarv** [comment]
nope, no joy.

**Comment by muglug** [comment]
You were comparing `$stmt->name->name` (the un-namespaced class name) to a fully-qualified string. `$storage->name` has the value you want.

**Comment by SignpostMarv** [comment]
this is a little odd; if I call `./vendor/bin/psalm` i hit some of the debug code, but if I `./vendor/bin/psalm ./quick-checks/` I don't o_O

**Comment by SignpostMarv** [comment]
does psalm have something like phpstan's `TypehintHelper::decideTypeFromReflection()`, where I can pass a psalm method a `ReflectionParameter` type or `ReflectionMethod` return type & get a pre-populated Union ?

**Comment by muglug** [comment]
No, but you can make a method - add it here: https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Codebase/Reflection.php - you’ll see something similar in that file - and add a proxy in Codebase.php

**Comment by muglug** [comment]
Or wait a few days and I’ll do it

**Comment by SignpostMarv** [comment]
I'm happy waiting- currently several levels down the rabbit hole of feature implementation with this idea to write a plugin that handles both phpstan (done) & psalm (todo) :P

**Comment by SignpostMarv** [comment]
will have a tinker with it tomorrow :)

**Comment by SignpostMarv** [comment]
have updated the psalm branch, doesn't seem to be triggering anything now :(

**Comment by SignpostMarv** [comment]
> I'm wondering if instead of trying to make psalm aware of interface properties with a plugin if I should instead modify daft-object to enforce `@property`, `@property-read`, and `@property-write` in docblocks ?

currently working on this, shall I mark this issue as closed when I'm done ?

**Comment by muglug** [comment]
Please!

**Comment by muglug** [comment]
Have a look at what I did with FunctionReturnTypeProvider - might want to do something similar

**Comment by weirdan** [comment]
> Have a look at what I did with FunctionReturnTypeProvider

:clap: That's totally great! And .phpstorm.meta support looks very interesting as well - are you going to announce it?

**Comment by muglug** [comment]
Yeah, once I've got https://github.com/psalm/laravel-psalm-plugin (which uses it) working properly
