### ISSUE TITLE
Implement hover for LSP server 

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#1239]
Psalm internally has a lot of knowledge of expression / variable / property types than most tools out there (provided the code base is thoroughly typed). However it's rather hard to get insights into that, even though this may be beneficial for programmers.

[LSP Hover](https://microsoft.github.io/language-server-protocol/specification#textDocument_hover) request provides a way for editors to notify language server that user is curious about some code part (for this use case that would be variable / expression / property *in certain position*). To respond to this Psalm could re-process containing scope, and emit the type it thinks the element has when it reaches that element. It's important to return the type as Psalm sees it *at that point*, as it could change subsequently.

**Comment by muglug** [comment]
Uhhh this already works? It even has some tests: https://github.com/vimeo/psalm/blob/master/tests/LanguageServer/SymbolLookupTest.php

**Comment by weirdan** [comment]
It does indeed!

Apparently [Psalm LSP docs](https://github.com/vimeo/psalm/blob/master/docs/language_server.md) are somewhat out of date.

**Comment by muglug** [comment]
Thanks, updated
