### ISSUE TITLE
Issue with array_filter, ARRAY_FILTER_USE_KEY & $variables for array keys

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#124]
Cut-down working example of a problem with vimeo/psalm:dev-master @ b20ddfec94f0be73a9da7f2c7c5855fae86b2cd2

Compare:
```php
$foo = [
    'bar' => function () : string {
        return 'baz';
    },
];

$foo = array_filter(
    $foo,
    function (string $key) : bool {
        return $key === 'bar';
    },
    ARRAY_FILTER_USE_KEY
);
```

With

```php
$bar = 'bar';

$foo = [
    $bar => function () : string {
        return 'baz';
    },
];

$foo = array_filter(
    $foo,
    function (string $key) : bool {
        return $key === 'bar';
    },
    ARRAY_FILTER_USE_KEY
);
```

The former passes, the latter results in an InvalidArgument error
>  First parameter of closure passed to function array_filter expects string, Closure provided

**Comment by muglug** [comment]
Thanks for showing both edgecases!

The first example shouldn't have passed either (for unrelated reasons) and I've fixed that bug too.
