### ISSUE TITLE
@return, @param and @var annotations allow violation of generic constraints

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#1245]
https://getpsalm.org/r/3abde19f34
```php
<?php
  /** @template T as object */
  class Generic {}

  /**
   * @template T
   * @param T $_p
   * @return Generic<T>
   * @psalm-suppress InvalidReturnType
   */
  function violate($_p) {}

  // is Generic<string(constraints)>, but that shouldn't be possible
  $violated = violate("constraints");

  /** 
   * @var Generic<int> $directViolation
   * @psalm-suppress UnusedVariable doesn't seem to work, but that's clearly a separate issue
   */
  $directViolation = $violated;

  /** @param Generic<array> $_p */
  function f($_p): void {}
```
**Expected**: all `Generic` specializations are invalid here
**Actual**: no issues (apart from unrelated UnusedVariable)

**Comment by weirdan** [comment]
Follow up to #1244

**Comment by muglug** [comment]
Big diff to solve this. I removed a bunch of hacks that I had added initially to get generics working (things like using the last generic type param for the value parameter).

Now it uses CoreGenericClasses.php to figure what the `Traversable<TKey, TValue>` refers to for the given class/interface: https://github.com/vimeo/psalm/blob/22ee72808a45d6b244a1639e353601a29c1d4678/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php#L769-L785

**Comment by muglug** [comment]
Opened https://github.com/vimeo/psalm/issues/1246 to track `@var` annotations (which aren't currently checked at all)

**Comment by weirdan** [comment]
:+1:
