### ISSUE TITLE
Class implementing IteratorAggregate is not considered Traversable by iterator_to_array

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#1247]
https://getpsalm.org/r/9f8e3f9199
```php
<?php
  /** @template-extends IteratorAggregate<int,string> */
  class C extends IteratorAggregate {
    public function getIterator() { yield 1 => "1"; }
  }

  iterator_to_array(new C);
```
**Expected**: no issues, result is `array<int,string>`
**Actual**:
```
Psalm output (using commit 16c2a0f): 

ERROR: InvalidArgument - 7:21 - Argument 1 of iterator_to_array expects Traversable, C provided
```

I guess custom handling of `iterator_aggregate` needs to be updated. Unfortunately it cannot be simply dropped, as its signature requires overloading.

**Comment by muglug** [comment]
Huh, weird. No custom handling should be kicking in here.

**Comment by weirdan** [comment]
Oh, this is embarassing. One cannot *extend interface with a class*.
