### ISSUE TITLE
Unimplemented methods defined in interfaces on abstract classes

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#125]
With b20ddfec94f0be73a9da7f2c7c5855fae86b2cd2 I'm getting `UndefinedMethod` cropping up with
> ERROR: UndefinedMethod - src\foo.php:17 - Method AbstractFoo::Bar does not exist

Minimum reproduceable code: 
```php
<?php
interface Foo
{
    public function Bar() : string
    {
        return 'Bar';
    }
}

abstract class AbstractFoo
    implements
        Foo
{

    public function Baz() : string
    {
        return $this->Bar();
    }
}
```

Am I missing something that I should be doing, or am I correct in thinking that psalm isn't looking up interface method signatures on abstract classes ?

p.s. since I'm running phpstan at the same time & misread my console output I made an ass of myself over on phpstan/phpstan#229 :s

**Comment by muglug** [comment]
Thanks! I made a slight tweak to your example so that it passes PHP's linter, but this was a great edgecase :)
