### ISSUE TITLE
class-string param (inheritance??) & return types

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1250]
* method A returns `Exception`, with return type indicated by a `class-string<Exception>` parameter.
* method B returns `InvalidArgumentException`, with a return type indicated by a `class-string<InvalidArgumentException>` parameter which is passed to the `class-string<Exception>` parameter of method A

Ideally, psalm would identify that the return type of method A is controlled by the `class-string` parameter, so when method B passes along a `class-string` that is a sub-class of `class-string<Exception>`, the errors would be automagically suppressed.

example: https://getpsalm.org/r/ff1da168e9 from https://github.com/SignpostMarv/sprintf-exception-factory/blob/35e2e6d5fe0a03c65e90f866cbe5f7808998d28d/src/SprintfExceptionFactory.php

**Comment by weirdan** [comment]
> Ideally, psalm would identify that the return type of method A is controlled by the class-string parameter, 

That implies generics, and you're not using them.

Here's a simplified generic version of what you're describing (https://getpsalm.org/r/77dc286950):
```php
<?php
class C {
  /**
   * @template T as Exception
   * @param T::class $type
   * @return T
   */
  public static function a(string $type): Exception {
    return new $type;
  }
  /**
   * @template T as InvalidArgumentException
   * @param T::class $type
   * @return T
   */
  public static function b(string $type): InvalidArgumentException {
    return self::a($type);
  }
}
```
@muglug it doesn't work either, but I think it should. Fails with:
```
Psalm output (using commit 16c2a0f): 

INFO: MixedReturnStatement - 17:5 - Could not infer a return type

INFO: MixedInferredReturnType - 14:6 - Could not verify return type 'T' for C::b
```

**Comment by SignpostMarv** [comment]
@weirdan I take it `T::class` resolves to class-string<T>, depending on what T is ?

**Comment by weirdan** [comment]
Yep, and `T as Exception` constraints it to `Exception` or its descendants.

**Comment by muglug** [comment]
When `T` is templated, `T::class` and `class-string<T>` result in identical types (in Psalm). `Foo::class` and `class-string<Foo>` are different though (the former is literal, the latter

**Comment by muglug** [comment]
Turns out it was super-simple :)

**Comment by SignpostMarv** [comment]
am I overlooking something? psalm seems to think the return type is mixed in the tests:

* [test file](https://github.com/SignpostMarv/sprintf-exception-factory/blob/a302d741232b4873fd2d30f1463eb75485d7a64a/Tests/SprintfExceptionFactoryTest.php)
* [new errors that get thrown up](https://github.com/SignpostMarv/sprintf-exception-factory/commit/9d4112117ce45444fdcae336e51487b494301358)
* using psalm a8019235024698bdef49d4840330211789f1314b
