### ISSUE TITLE
Feature request: stub-specific annotation to keep stubs in sync with stubbed classes

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#1252]
I came upon the problem where stub classes were in the wrong namespace. Thus they failed to override what they should have been overriding, and (I suppose) made Psalm think there were classes that wouldn't be there on execution time.

This can also happen when upstream changes the API (moves/renames classes, removes methods, etc).

So I would like to request an annotation that would mark a interface/trait/class/function/method as an explicit override, and then complain if the interface/trait/class/function/method marked as overridden does not have it's upstream available. I think it makes sense to abort Psalm run immediately when this happens, since users are obviously using an incompatible plugin. Also it could be made a no-op outside of stubs.

**Comment by muglug** [comment]
Do you have a suggestion?

**Comment by weirdan** [comment]
What about `@psalm-stub-override`?

**Comment by mr-feek** [comment]
I'd be interested in this -- any implementation pointers? Maybe I'll take a stab later this week
