### ISSUE TITLE
Could not get class storage for self

### ISSUE THREAD

**Issue by kirich74** [vimeo/psalm#1257]
Fatal error: Uncaught InvalidArgumentException: Could not get class storage for self in /Users/k.pilipenko/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:43
Stack trace:
#0 /Users/k.pilipenko/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php(85): Psalm\Internal\Provider\ClassLikeStorageProvider->get('self')
#1 /Users/k.pilipenko/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(556): Psalm\Internal\Codebase\Methods->methodExists('self::getvalue')
#2 /Users/k.pilipenko/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(199): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyzeAtomicCall(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Codebase), Object(Psalm\Context), Object(Psalm\Type\Atomic\TNamedObject), NULL, NULL, false, false, true, false, Array, Array, Array, Array)
#3 /Users/k.pilip in /Users/k.pilipenko/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php on line 43

**Comment by kirich74** [comment]
When I launch psalm on my big project, i see this error, but if i launch it two times: first time on the first half of my project and the second time on the second half of my project - it works.

**Comment by muglug** [comment]
Would you be able to run with `vendor/bin/psalm --debug-by-line` to figure out which file/line Psalm crashes on? And then, if possible, paste the offending code?

**Comment by kirich74** [comment]
The result of launching vendor/bin/psalm --debug-by-line :
`/Users/k.pilipenko/taxiserv/classes/order.php:3755
/Users/k.pilipenko/taxiserv/classes/order.php:3756
/Users/k.pilipenko/taxiserv/classes/order.php:3757
/Users/k.pilipenko/taxiserv/classes/order.php:3758

Fatal error: Uncaught InvalidArgumentException: Could not get class storage for self in /Users/k.pilipenko/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:43
Stack trace:
#0 /Users/k.pilipenko/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php(85): Psalm\Internal\Provider\ClassLikeStorageProvider->get('self')
#1 /Users/k.pilipenko/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(556): Psalm\Internal\Codebase\Methods->methodExists('self::getvalue')
#2 /Users/k.pilipenko/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(199): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyzeAtomicCall(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Codebase), Object(Psalm\Context), Object(Psalm\Type\Atomic\TNamedObject), NULL, NULL, false, false, true, false, Array, Array, Array, Array)
#3 /Users/k.pilip in /Users/k.pilipenko/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php on line 43
`
order.php on 3757, 3758, 3759 lines is
`if (self::isCanHoldOnRequest($request)) {
        $update['hold_status'] = HoldStatus::needHold()->getValue();
}`

As I sayed, my project is very big and I think that the problem is here. As we can see analyze failed on order.php But if I launch analyzer on all directories, connected with orders, it works. Also if I ignore order.php file, the analyzer failed on another file (Service.php) on line `return new LevelPromotion(`

**Comment by muglug** [comment]
What does `HoldStatus::needHold` return?

**Comment by muglug** [comment]
And is the call done inside `HoldStatus`, or a child class?

It'd be incredibly useful if you could isolate this to something on https://getpsalm.org

**Comment by kirich74** [comment]
wow, looks interesting. I don't understand, what this method returns, but here it is: 

HoldStatus.php:
```
<?php

namespace App\Models\Order;

use App\Libraries\Enumeration\Enumeration;

/**
 * @method bool isNoNeedHold()
 * @method bool isNeedHold()
 * @method bool isHoldSuccess()
 * @method bool isHoldCanceling()
 * @method bool isHoldCancel()
 * @method bool isErrorOnHoldRequest()
 * @method bool isErrorOnHoldResponse()
 * @method bool isErrorOnHoldChargeResponse()
 * @method bool isErrorOnPayResponse()
 * @method static self noNeedHold()
 * @method static self needHold()
 * @method static self holdSuccess()
 * @method static self holdCanceling()
 * @method static self holdCancel()
 * @method static self errorOnHoldRequest()
 * @method static self errorOnHoldResponse()
 * @method static self errorOnHoldChargeResponse()
 * @method static self errorOnPayResponse()
 */
final class HoldStatus extends Enumeration
{
    public const NO_NEED_HOLD = 0;

    public const NEED_HOLD = 1;

    public const HOLD_SUCCESS = 5;

    public const HOLD_CANCELING = 6;

    public const HOLD_CANCEL = 7;

    public const ERROR_ON_HOLD_REQUEST = 2;

    public const ERROR_ON_HOLD_RESPONSE = 3;

    public const ERROR_ON_HOLD_CHARGE_RESPONSE = 8;

    public const ERROR_ON_PAY_RESPONSE = 9;
......
}
```

Enumeration.php: 

```<?php

namespace App\Libraries\Enumeration;

use BadMethodCallException;
use App\Libraries\Enumeration\Exception\EnumerationClassNotFound;
use App\Libraries\Enumeration\Exception\NotSameEnumerationClass;
use App\Libraries\Enumeration\Exception\NotValidEnumerationName;
use App\Libraries\Enumeration\Exception\NotValidEnumerationValue;

abstract class Enumeration
{
    /**
     * @var string[]
     */
    private static $caseConvertCache = [];

    /**
     * @var int|string
     */
    protected $value;

    /**
     * @param int|string $value
     * @throws EnumerationClassNotFound
     * @throws NotValidEnumerationValue
     */
    final public function __construct($value)
    {
        if (!static::contains($value)) {
            throw new NotValidEnumerationValue(
                strtr(
                    "'{value}' is not a valid value for enumeration '{name}'",
                    [
                        '{value}' => $value,
                        '{name}' => static::class
                    ]
                )
            );
        }

        $this->value = $value;
    }

    /**
     * @param int|string $value
     * @return static
     * @throws EnumerationClassNotFound
     * @throws NotValidEnumerationValue
     */
    final public static function createByValue($value): Enumeration
    {
        return new static($value);
    }

    /**
     * @param string $name
     * @param array $arguments
     * @return static
     * @throws EnumerationClassNotFound
     * @throws NotValidEnumerationValue
     * @throws NotValidEnumerationName
     */
    final public static function __callStatic($name, $arguments): Enumeration
    {
        return self::createByName($name);
    }

    /**
     * @param $name
     * @return static
     * @throws EnumerationClassNotFound
     * @throws NotValidEnumerationValue
     * @throws NotValidEnumerationName
     */
    final public static function createByName($name): Enumeration
    {
        return self::createByValue(self::getValueByName($name));
    }

    /**
     * @param string $name
     * @return string|int
     * @throws NotValidEnumerationName
     */
    private static function getValueByName(string $name)
    {
        $value = null;
        try {
            $reflectionClass = new \ReflectionClass(static::class);
            $snakeCaseConstant = self::convertMethodNameToConstant($name);
            if ($reflectionClass->hasConstant($snakeCaseConstant)) {
                $value = \constant(static::class . '::' . $snakeCaseConstant);
            } elseif ($reflectionClass->hasConstant($name)) {
                $value = \constant(static::class . '::' . $name);
            }
        } catch (\ReflectionException $e) {
            $value = null;
        }
        if (NULL === $value) {
            throw new NotValidEnumerationName(
                strtr(
                    "'{name}' is not a valid name for enumeration '{class}'",
                    [
                        '{name}' => $name,
                        '{class}' => static::class
                    ]
                )
            );
        }

        return $value;
    }

    /**
     * @return int|string
     */
    final public function getValue()
    {
        return $this->value;
    }
.....
}```

**Comment by muglug** [comment]
Thanks, I deleted your code -  I was able to reproduce with

```
/**
 * @method static self getSelf()
 */
class C {
  public static function __callStatic(string $c, array $args) {}
  
  public function bar() : void {}
}

C::getSelf()->bar();
```

**Comment by weirdan** [comment]
What about `@method static getSomething()`? Generally, `static` is a valid type name (at least under PSR-5), so I think it's ambiguous what this is supposed to mean if you accept `static` as a modifier.

**Comment by weirdan** [comment]
See phpDocumentor/phpDocumentor2#822 - it seems to be referenced by Phan as well. The approach phpdoc appear to have taken is to treat `static foo()` as a method returning `static`, and for static void to require it spelled explicitly as `static void`

**Comment by muglug** [comment]
This rule (requiring that the `@method` must be called statically) only kicks in with
`@method static <someReturnType> methodName()`

**Comment by weirdan** [comment]
Is it? I'm getting `InvalidDocblock` for `@method static foo()`: https://getpsalm.org/r/cf5737c771
Not sure if it worked previously though.

**Comment by muglug** [comment]
Ah ok, well that should probably still work

**Comment by kirich74** [comment]
I downloaded your last commit and now all works fine. Thank you!

**Comment by muglug** [comment]
You're welcome!

**Comment by weirdan** [comment]
@muglug So what's your take on this `@return static foo()` issue? It appears you've reopened and closed the ticket without any further actions.

**Comment by muglug** [comment]
@weirdan I reopened by mistake. I've ticketed this separately in https://github.com/vimeo/psalm/issues/1258

**Comment by kirich74** [comment]
Hello once again. Today i've got the same error. Now it fails on the line 
```
\App\Models\Acquiring\Invoice::$current->setUsedStatus($order);
```
setUsedStatus function is 
```
<?php

namespace App\Models\Acquiring;

class Invoice {

    const PAID_STATUS = 1;
    const USED_STATUS = 2;

    public function setUsedStatus($order){
        return $this->updateStatus(self::USED_STATUS, ['order' => $order]);
    }
...
}

**Comment by muglug** [comment]
How is `\App\Models\Acquiring\Invoice::$current` defined?

**Comment by kirich74** [comment]
```
/**
* @var self
*/
public static $current;```

**Comment by muglug** [comment]
Thanks, sorry - ticketed as https://github.com/vimeo/psalm/issues/1267

**Comment by muglug** [comment]
And that should now be fixed in master.
