### ISSUE TITLE
Too many template params

### ISSUE THREAD

**Issue by mmasiukevich** [vimeo/psalm#1259]
Greetings,

After the latest updates, [this code](https://getpsalm.org/r/fef0e30bb5) leads to an error TooManyTemplateParams. Can you please tell how to describe the type correctly now?

**Comment by weirdan** [comment]
Right now, just `\SplObjectStorage`. Psalm by default is only aware about generics defined here: https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Stubs/CoreGenericClasses.php

You can also propose a pull request, or define the stub yourself and add it to your project with `psalm.xml` config.

**Comment by weirdan** [comment]
Yeah. It's got peculiar signature though, as it's used both as Set and Map. So it could be both `SplObjectStorage<T>` and `SplObjectStorage<T,V>`, and users may be interested in either type signature.
Also it's counter-intuitively `@template-extends Traversable<int,T>`. It's not (!) `Traversable<T,V>` as one might expect.

**Comment by muglug** [comment]
Thanks @weirdan  - I've added support the slightly icky signature `SplObjectStorage<TObject, TArrayValue>` to support `ArrayAccess` returning a separate value type: https://3v4l.org/K9QKq

I might support shortcuts for templates at some later date - make a type param optional, with some sort of precedence (they're currently optional for `Generator`, but that's an exception to the rule)

**Comment by weirdan** [comment]
Shouldn't `TArrayValue` also be used on `attach()`, `getInfo()`, `setInfo()`, `offsetSet()` and `offsetGet()` though?

**Comment by weirdan** [comment]
@muglug it appears `@param mixed` overridden the inherited `ArrayAccess` signatures: https://getpsalm.org/r/919dfcaae5

**Comment by muglug** [comment]
@weirdan fixed those signatures in https://github.com/vimeo/psalm/commit/d52fd70fd6485236e154af3fe88f9c0048f85d9f, but the `ArrayAccess` `mixed` offset is a bigger issue that currently applies to anything implementing `ArrayAccess`.

**Comment by mmasiukevich** [comment]
thx
