### ISSUE TITLE
possibly incorrect MixedMethodCall: "Cannot call method on an unknown class" when using templated class-string param & return types

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1263]
This templated scenario seems to trigger an error for two different reasons:
* in the example the class is known, it being `class-string<DateTimeImmutable>`
* `is_a()` returns false if either of the first two `class-string` arguments are unknown, thus the return statement will never be reached: https://3v4l.org/Pd7BJ

* https://getpsalm.org/r/07abe707ba
* using e384fb0

```php
<?php
declare(strict_types=1);

/**
* @template T
*
* @param class-string $maybe
* @param class-string<T> $shouldBe
*
* @return class-string<T>
*
* @throws InvalidArgumentException if $maybe is not an implementation of $shouldBe
*/
function Foo(string $maybe, string $shouldBe) : string {
  if ( ! is_a($maybe, $shouldBe, true)) {
    throw new InvalidArgumentException('nope');
  }
  
  return $maybe;
}

Foo(DateTimeImmutable::class, DateTimeImmutable::class)::getFromMutable(new DateTime());
```

**Comment by weirdan** [comment]
I think it could be simplified further (https://getpsalm.org/r/94b619a6ac):
```php
<?php
/**
* @template T
*
* @param class-string<T> $shouldBe
* @return class-string<T>
*/
function identity(string $shouldBe) : string {  return $shouldBe; }

identity(DateTimeImmutable::class)::getFromMutable(new DateTime());
```

**Comment by SignpostMarv** [comment]
@weirdan does psalm internals make a distinction between `class-string` for a known class and `class-string` for an unknown class ?

**Comment by weirdan** [comment]
Depends on what you mean by that, I suppose. `class-string<Exception>` and just `class-string` do result in different behavior in some places.

However in this case the return type is inferred to be `class-string<>` (https://getpsalm.org/r/ecaf471209), which is certainly not something I'd expect to see.

**Comment by SignpostMarv** [comment]
@weirdan I was using `class-string<void>` for known unknown class testing, but it's detected as a reserved word now :p

**Comment by muglug** [comment]
`class-string` is equivalent to `class-string<object>`
