### ISSUE TITLE
@template & return object

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1268]
just wanted to double-check i wasn't planning on doing signpostmarv/daft-object#6 wrong; 

`php:>=7.2` supports `object` as a return type hint, which seems to conflict with psalm's templated return type system:

* https://getpsalm.org/r/91308fe42c
* https://3v4l.org/SHnqX
* with 509709d

```php
/**
* @template T
*
* @param class-string<T> $foo
*
* @return T
*/
function Foo(string $foo) : object {
  return new $foo;
}

echo Foo('DateTime')->format('c');
```

the key complaint from psalm is that the return type docblock should be 'object'- is there additional syntax I'm missing to ensure psalm knows that `@return T` refers to a specific type of object?

**Comment by muglug** [comment]
> is there additional syntax I'm missing to ensure psalm knows that @return T refers to a specific type of object?

Yes - `@template T of object` (`@template T as object` also works)

**Comment by muglug** [comment]
I've improved the error message in https://github.com/vimeo/psalm/commit/8b65acf15bf6828d9a145c6e9ce042974a2fb570 to make things more clear

**Comment by SignpostMarv** [comment]
/me has been under the mistaken assumption that `T` defaults to `object` :P
