### ISSUE TITLE
@immutable annotation

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1272]
What do you think of adding an `@immutable` annotation to classes to mark immutable classes? 

https://getpsalm.org/r/aeccdca86c

At the moment the only way to avoid a warning is to capture the "value at rsk" in an additional variable, which pollutes the code quite a bit.

**Comment by vasily-kartashov** [comment]
> Does @immutable just apply to class properties?

Good question, I'd say yes. We're talking about immutable _objects_ after all. Also static factory methods can be conveniently placed in the same immutable class, and such factory methods may need to mutate the state. 

> Should they be only privately settable or settable by subclasses?

One can easily enforce `private $*` on all properties, by forcing subclasses to call `protected|public parent::__construct` to set properties, and `protected|public get*` to get properties.

> Is @immutable inheritable?

No, based on a simple consideration that the person extending the class doesn't need to respect immutability contract by default.

> Also can @immutable be set at the property level?

I guess so, but maybe I should explain some more where my question comes from. In our application there are plenty of data objects (alexa request, generally parsed json, IoT shadow, db rows etc.) which we treat as immutable. We wrap them in data object that only have accessors.

```
class AlexaRequest {
    private $payload;
    ...
    public function locale(): ?string {
        return $this->payload['request']['locale'] ?? 'en-US';
    }
}
```
It would convenient to just add an annotation on top of the class and let static analyser see `AlexaRequest::locale()` as a constant of type `?string`.

**Comment by weirdan** [comment]
To provide some more examples of immutable objects in the wild take a look at [PSR-7 HTTP Messages](https://www.php-fig.org/psr/psr-7/).
[Zend Diactoros](https://github.com/zendframework/zend-diactoros) is the implementation I'm familiar with.

**Comment by TysonAndre** [comment]
A class's properties itself could be immutable, but the methods could access global state (e.g. `global $counter`, `mt_rand()`, etc), so I don't think that's sufficient to infer method results don't change. (Maybe `@pure` or something)

- Also, it can be subclassed.

Phan implements `@phan-read-only`/`@phan-write-only`, and read-only is similar to the `@immutable` suggestion: https://github.com/phan/phan/blob/master/NEWS.md#05-nov-2018-phan-112
Write-only is useful less commonly (e.g. when writing to an object to be serialized or json encoded but not used within the library/application)

- The implementation shares a lot with analysis of properly using `@property-read` and `@property-write`

**Comment by weirdan** [comment]
Even just being able to *assert* immutability is a huge value in itself. *Verification* of immutability is a separate, quite interesting topic, but if that proves to be infeasible it shouldn't mean assertion option is ruled out.

**Comment by joshdifabio** [comment]
I'm not sure about this. Very often, objects which are observably immutable are mutable internally due to having computed, memoized properties.

I think some kind of _readonly_ annotation for properties (like in TypeScript) might be simpler and more flexible.

**Comment by bdsl** [comment]
> Is @immutable inheritable?

I would say that if you inherit from an immutable class then the immutability should be inherited, but it probably only needs to apply to those fields defined in the parent class. This would help to enforce the history rule of the [Liskov Substitution Principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle#Principle).

**Comment by muglug** [comment]
Current status:

Psalm supports the `@readonly` on object properties, and I've also added support for `@psalm-pure` on functions. `@psalm-pure` says: this function only operates on its input (it keeps no internal state, and any other functions it calls must also be pure).

I'm also considering a `@psalm-pure-instance` annotation for classes. That annotation would tell Psalm that the class never modifies state external to the class instance, so that any instances of it can be thrown away if the attached variable is not used, for example here:

```php
/** @psalm-pure-instance */
class A {
  public ?string $hello = null;
  public function getHello() : string {
    if (!$this->hello) {
      $this->hello = "hello";
    }
    return $this->hello;
  }
}

function foo() : void {
  $a = (new A)->getHello(); // this entire line can be removed
}
```

**Comment by TysonAndre** [comment]
> That annotation would tell Psalm **that the class never modifies state external to the class instance, so that any instances of it can be thrown away if the attached variable is not used,** for example here:

It sounds like there would be some edge cases in where the code can actually be treated as a no-op for this definition of "pure" (this definition is != immutable and != "effectively immutable" ("effectively immutable" being similar to C++ const methods)), e.g.

- If the element was tracked elsewhere (e.g. passed in as a parameter, added to an array, etc.)
- Setting properties of the instance to `microtime()` and other expressions that vary based on time/global state, for use later on

```php
/** @psalm-pure-instance - this doesn't modify any state *external* to the instance */
class ArrayBuilder {
    public array $values = [];
    public function addNext(int $next) {
        $this->values[] = $next;
        return $this;
    }
}

function foo(ArrayBuilder $builder) : void {
  $a = $builder->generateNext(rand(0,10)); // this entire line cannot be removed
}
$builder = new ArrayBuilder();
foo($builder);
var_export($builder);
```

**Comment by muglug** [comment]
> // this entire line cannot be removed

Yeah, I'd treat this similar to how I currently treat pure functions - a `pure_instance` flag would be set on the node during the constructor call, then propagated appropriately.

**Comment by TysonAndre** [comment]
> I'm **also** considering a `@psalm-pure-instance` annotation for classes. That annotation would tell Psalm that the class never modifies state external to the class instance, so that any instances of it can be thrown away if the attached variable is not used, for example here:

Oh. I was confused earlier - I'm assuming that meant that `@psalm-pure-instance` can be implemented in the short term, and `@immutable` or something similar can be implemented alongside that in the longer term.

- Can't warn about `$this->addNext($int)` being unused or `$this->getHello()` being unused from within the class
- `@psalm-pure` functions cannot call methods of `@psalm-pure-instance` because they can modify that instance

-----

I'm guessing it'd be useful to mark some internal classes (such as `SplObjectStorage` (and other spl data structures) and `ArrayObject`) as being equivalent to `@psalm-pure-instance` (but not immutable)

- low priority, I'd guess they're not used very frequently

**Comment by muglug** [comment]
> I'm guessing it'd be useful to mark some internal classes (such as SplObjectStorage (and other spl data structures) and ArrayObject) as being equivalent to @psalm-pure-instance (but not immutable)

Yeah, I think most of them - including `DateTime`. I think any `@immutable`-annotated class like `DateTimeImmutable` would always be treated as `@psalm-pure-instance`, whether or not it was instantiated.

**Comment by muglug** [comment]
For a C `const` method equivalent there could be something like `@psalm-mutation-free`.

There could be a more general thing like `@psalm-external-mutation-free` that could be used both at the class level (replacing the proposed `@psalm-pure-instance`) and the method level.

We could also say `@psalm-mutation-free` at the class level has the same effect as an `@immutable` annotation there - all methods are assumed `@psalm-mutation-free` and all properties are assumed `@readonly`.
