### ISSUE TITLE
Request to allow Generator send type to be strictly type-hinted to warn end-user.

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1286]
I'm not sure that generators can both yield and receive values, since all the examples I'm coming up with on 3v4l result in an uncaught exception about rewinding the generator.

this suggests that `void` be an acceptable type for `T0` & `T1` rather than the default `int` and `null` (since `foo(null)` is different from `foo()`).

If a `Generator` function does not support `Generator::send()`, i.e. no assign-from-field (`$foo = yield;`), then `T2` should be required to be `void`.

If a `Generator` function does support `Generator::send()`, then `T2` should support type-hinting other than mixed [without triggering MixedTypeCoercion](https://getpsalm.org/r/0eb120fa6e) (although it does currently correctly trigger `InvalidScalarArgument`).

Also, interesting things happen if you type-hint T0-T3 as `void`: https://getpsalm.org/r/c325c1a397

```
Psalm output (using commit c83afc1): 

ERROR: InvalidReturnStatement - 10:3 - Empty return statement is not expected in Foo

ERROR: AssignmentToVoid - 15:24 - Cannot assign $v to type void

ERROR: InvalidArgument - 16:8 - Argument 1 of echo expects string, void provided

INFO: UnusedVariable - 15:24 - Variable $v is never referenced
```

**Comment by SignpostMarv** [comment]
p.s. psalm provides a solution for phpstan/phpdoc-parser#13

**Comment by muglug** [comment]
> should a request for having all un-hinted `Generator`s be flagged for being `Generator<mixed, mixed, mixed, mixed>` ?

Nope

**Comment by muglug** [comment]
I believe this is fixed now
