### ISSUE TITLE
InvalidFunctionCall on Closure|null used by reference

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#129]
```php
<?php
/**
* @var Closure|null $foo
*/
$foo = null;

$foo = function ($bar) use (& $foo) : string
{
    if (is_array($bar)) {
        return $foo($bar);
    }

    return $bar;
};
```
> ERROR: InvalidFunctionCall - src\foo.php:10 - Cannot treat $foo of type null as function

At runtime, the side effect of `$foo = function(){}` and `use (& $foo)` is that the imported `$foo` will be $foo, which is at that point is a Closure, especially as $foo isn't later reassigned back to null.

**Comment by muglug** [comment]
I realise this isn’t a true fix, but I feel the above code is sufficiently tricksy to warrant it (because pass by reference is a little awful to reason about)

**Comment by SignpostMarv** [comment]
It's close enough, and gives me something slightly more preferable to set from error to info :)
