### ISSUE TITLE
How do I reuse doc blocks on classes inheriting a well documented interface?

### ISSUE THREAD

**Issue by Neppord** [vimeo/psalm#1294]
Hi!

I wonder if there is a way to remove the need to sync and update type annotations between the interface and all the implementing classes.

It would be nice if Psalm could just reuse the docblock from the class that first defined the method.

Thanks!

**Comment by SignpostMarv** [comment]
Might not be related, but in some circumstances I've had to use `{@inheritdoc}`, to allow me to selectively override the method signature.

**Comment by Neppord** [comment]
Thanks @SignpostMarv I'll try it out tonight. It might be what I'm looking for.

**Comment by muglug** [comment]
@Neppord if you have an example where Psalm isn't inheriting I could provide more context or fix a bug, if there is one

**Comment by Neppord** [comment]
'{@inheritdoc}' fixed it, there is no bug.

**Comment by SignpostMarv** [comment]
@muglug here's an example where it's not inheriting: https://getpsalm.org/r/3cfca3d276
