### ISSUE TITLE
array_filter expects `callable(mixed, mixed=):bool`

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1296]
short story is sometimes I take the lazy option of filtering out empty strings by just calling `array_filter($arr, 'trim');`, sometimes with the combination `array_map('trim', array_filter($arr, 'trim'));` to strip empty strings while trimming values.

* https://getpsalm.org/r/9a029bb29d
* using 69d4407
* https://3v4l.org/9ZnaL

```php
<?php
$foo = array_filter(['', '', ''], 'trim');

echo count($foo);
```

I've tried tinkering with a stub definition for `trim`, i.e. to decorate it as being `callable(string):string`, but that didn't appear to take effect. This might be a general issue of the falsey `''` not being considered sufficiently booleanish enough to allow `callable(string):string` to be accepted for `callable(mixed):bool`, or a general "is there a dict of native functions usable as callables?" question.

**Comment by weirdan** [comment]
> This might be a general issue of the falsey `''` not being considered sufficiently booleanish enough to allow `callable(string):string` to be accepted for `callable(mixed):bool`

This. However I'm not sure this should be considered an issue.

**Comment by SignpostMarv** [comment]
@weirdan I suppose it's then a question of should `array_filter` be tagged as accepting `callable(mixed, mixed=):(truthy|falsey)` instead of `callable(mixed, mixed=):bool` ?

* https://getpsalm.org/r/55ac1e6c11
* https://3v4l.org/3eRQj

```php
<?php
$foo = array_filter(['', '', '', '0'], 'trim');

$bar = array_filter(['', '', '', '0'], function (string $e) : string {
  return trim($e);
});

$baz = array_filter(['', '', '', '0'], function (string $e) : bool {
  return (bool) trim($e);
});

$bat = array_filter(['', '', '', '0'], function (string $e) : bool {
  return '' !== trim($e);
});

$falsey = array_filter(['', '', '', '0'], function (string $e) : int {
  return (int) $e;
});

echo count($foo), count($bar), count($baz), count($bat), count($falsey);
```

**Comment by SignpostMarv** [comment]
@weirdan oh btw; see also this terrible idea:
* https://getpsalm.org/r/a8947a4257
* https://3v4l.org/LaAhS

```php
/**
* @var callable(mixed, mixed=):bool
*/
$closure = Closure::fromCallable('trim');

$terrible_idea = array_filter(['', '', '', '0'], $closure);
```

**Comment by muglug** [comment]
I decided to allow `callable():scalar`. Anyone passing in `callable():?stdClass` is probably just a terrible person and should be justifiably sanctioned.
