### ISSUE TITLE
[Question] LessSpecificImplementedReturnType on empty phpdoc for implemented interface method

### ISSUE THREAD

**Issue by andrew-demb** [vimeo/psalm#1298]
Is it expected behavior, when I don't specify `inheritdoc` or not duplicate implemented interface phpdoc for method return types and got `LessSpecificImplementedReturnType`?
Thanks.

```php
<?php

interface TypesProvider
{
    /**
     * @return string[]
     */
    public static function getTypes();
}

class EnvTypesProvider implements TypesProvider
{
    public static function getTypes(): array
    {
    	return [
          'env' => 'env'
        ];
    }
}
```

> using commit 88b4f82

> ERROR: LessSpecificImplementedReturnType - 13:37 - The return type 'array<array-key, string>' for TypesProvider::getTypes is more specific than the implemented return type for EnvTypesProvider::gettypes 'array<array-key, mixed>'

https://getpsalm.org/r/10025b06d2

**Comment by muglug** [comment]
This is slightly weird, but it goes away if the interface method has an explicit `: array` return type;

**Comment by weirdan** [comment]
Or if implementer doesn't have explicit `: array` return type hint.

**Comment by andrew-demb** [comment]
Okay
