### ISSUE TITLE
psalm not able to correctly identify yield types when calling `yield from` on an array.

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1307]
* https://getpsalm.org/r/be11faca2d
* using 574a553

```php
<?php
/**
* @return Generator<int, int, mixed, void>
*/
function Foo() : Generator {
  yield 1;
}

/**
* @return Generator<int, int, mixed, void>
*/
function Bar() : Generator {
  yield from [1];
}

/**
* @return Generator<int, int, mixed, void>
*/
function Baz() : Generator {
  yield from Foo();
}
```
> INFO: MixedTypeCoercion - 10:3 - The declared return type 'Generator<int, int, mixed, void>' for Bar is more specific than the inferred return type 'Generator<mixed, mixed, mixed, void>'

one would expect Bar to behave as Baz.

**Comment by muglug** [comment]
Thanks for finding!
