### ISSUE TITLE
Old-style constructor confusion ?

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#131]
Running psalm 32efdfd0f7 on code that uses [cocur/slugify e8167e9a3](https://github.com/cocur/slugify/blob/e8167e9a3236044afebd6e8ab13ebeb3ec9ca145/src/Slugify.php), I get the following error:
> ERROR: TooFewArguments - src\path\to\file.php:{line number} - Too few arguments for method Cocur\Slugify\Slugify::slugify
>                             $slugify = new Slugify();

psalm seems to be confusing Slugify::__construct() with Slugify::slugify(), possibly due to some parser confusion with old-style constructors ?

**Comment by muglug** [comment]
Yup, can be reproduced on https://getpsalm.org with
```php
<?php
class A {
    public function __construct(string $s) { }
    public function a(int $i) { }
}
new A("hello");
```

**Comment by muglug** [comment]
Thanks for finding!
