### ISSUE TITLE
Init documentation unclear

### ISSUE THREAD

**Issue by Sarke** [vimeo/psalm#1312]
The current documentation show this:

> Add a psalm.xml config:
> `./vendor/bin/psalm --init [source_directory=src] [config_level=3]`

https://getpsalm.org/docs/installation/

Executing the above command will result in an error.  The correct syntax is:

`./vendor/bin/psalm --init src 3`

**Comment by muglug** [comment]
Sorry, I'm confused - isn't that what the documentation suggests?

**Comment by weirdan** [comment]
I guess @Sarke expected to be able to just run that line verbatim.

**Comment by Sarke** [comment]
Yes, that's what I mean was not clear.  It's in a code block, so I can't be the only one who copy and pasted it.

There's no explanation that the square brackets are informative only.

**Comment by muglug** [comment]
@Sarke @weirdan oh right, makes sense - do you have a suggestion for making it more clear?

**Comment by muglug** [comment]
Closing now - thanks @weirdan!
