### ISSUE TITLE
Cannot assign mixed value in foreach even if explicitly written

### ISSUE THREAD

**Issue by Girgias** [vimeo/psalm#1318]
Seems like Psalm has some problems when dealing with mixed.
I have a situation where I'm totally fine with mixed values in an array but it still gives me a warning.
Example: https://getpsalm.org/r/f8facc6047

(Or am I doing something totally wrong in my type declaration ?)

**Comment by muglug** [comment]
You aren't doing anything wrong. When it comes to the `MixedAssignment` warning, Psalm doesn't discriminate between hand-written `mixed` declarations and inferred ones.

**Comment by muglug** [comment]
So the best way around this is to put `@psalm-suppress MixedAssignment` either above the `foreach`, in the function docblock, or in the Psalm config for the file (the last is not advised).
