### ISSUE TITLE
Psalm as a global referenced dependency

### ISSUE THREAD

**Issue by MetalArend** [vimeo/psalm#132]
Is there a way to install Psalm as a global referenced dependency?

If I run the following code snippet on a PHP 7.1 docker image, it keeps telling me that "class or interface <xxx> does not exist":
```
composer global require vimeo/psalm
~/.composer/vendor/bin/psalm
```

Might it be that psalm is using the composer instance it is installed to to autoload classes? Or am I missing something else?

**Comment by MetalArend** [comment]
It seems Psalm expects a certain directory structure to find an autoload file: https://github.com/vimeo/psalm/blob/master/bin/psalm#L4 

Is there a way to overwrite this autodetected location? Or could it be added?

**Comment by muglug** [comment]
Yes, Psalm is designed only to be used on a project-by-project basis – I'll investigate what's necessary to change that.

**Comment by MetalArend** [comment]
Thanks, that would be awesome!

**Comment by TysonAndre** [comment]
> Yes, Psalm is designed only to be used on a project-by-project basis – I'll investigate what's necessary to change that.

One way to make it generic would be to have a parse phase like Phan (To get all of the classes, methods, interfaces, functions, etc.), and a separate analysis phase (With or without keeping around the parsed AST)
(some projects don't use the composer autoloader, some may use `require_once` everywhere, and composer dump-autoload may be inconvenient to run before psalm)

- Probably slower
- Would also be acceptable to have scripts/instructions to dump an autoload file from a list of files before running psalm
 
Also, I haven't used this before. Does the way that Psalm run mean that it won't pick up some functions, if the file containing a function is processed after the file declaring a function?

**Comment by muglug** [comment]
@TysonAndre 
Unlike Phan (which only needs reflection non-user-defined classes & functions), Psalm relies on reflection to figure out file locations of classes.

Psalm has a visit phase and an analysis phase, but the visit phase is responsible for collecting all the information that the analysis phase will use. Inherited class methods, for instance, are computed and stored during that visit phase.

That could be altered to be more like Phan (or add it as alternative loading method). One advantage of the current approach is that it allows us to analyse individual files relatively quickly.

As to function declarations, Psalm will emit an issue if a function is (globally) defined in a file A.php if it is referenced in B.php without an explicit `include` statement. You can also specify a custom autoloader in the config (that can itself define globally-available functions).

**Comment by MetalArend** [comment]
What if we could overwrite `__DIR__ . '/../vendor/autoload.php'` in the [psalm file](https://github.com/vimeo/psalm/blob/master/bin/psalm#L4) with a cli option?

**Comment by muglug** [comment]
Thanks @MetalArend – I've done that in #154

**Comment by MetalArend** [comment]
Awesome! Big thanks, @muglug, looking forward to trying it out!
