### ISSUE TITLE
@psalm-suppress not working for MissingThrowsDocblock

### ISSUE THREAD

**Issue by p810** [vimeo/psalm#1325]
I'm not sure if this is due to my own misunderstanding of how Psalm works, but I figured this was the best place to report/ask this question.

|                         |                                          |
| --------------|-------------------------|
| **Expected** | Psalm reports no errors |
| **Actual**      | Psalm reports a `MissingThrowsDocblock` error |

I set the `checkForThrowsDocblock` attribute to true in `psalm.xml` and ran the tool. It reported a few missing `@throws` annotations which I fixed. One of the methods that Psalm reports an error for doesn't throw an exception on its own, rather a method it calls throws one which then bubbles up through the call stack.

I added `@psalm-suppress MissingThrowsDocblock` annotation above the method declaration and later inline, immediately above the call that would throw an exception.

Here's the output from my command line:

```
./vendor/bin/psalm --show-info=false
Scanning files...
Analyzing files...

ERROR: MissingThrowsDocblock - src/Http/Message/Response.php:15:5 - UnexpectedValueException is thrown but not caught - please either catch or add a @throws annotation
    /**
     * @psalm-suppress MissingThrowsDocblock 
     */
    protected function build(): string {


------------------------------
1 errors found
------------------------------

Checks took 0.24 seconds and used 27.327MB of memory
Psalm was able to infer types for 95.939% of analyzed code (22 files)
```

And here's the method if that helps any:

**Response.php**
```php
/**
 * $container->getStatusMessage() may throw an UnexpectedValueException, and it has the annotation.
 * @psalm-suppress MissingThrowsDocblock
 */
protected function build(): string {
    $compiled = sprintf("%s %s %s\n",
        $this->container->getVersion(),
        $this->container->getStatusCode(),
        $this->container->getStatusMessage()
    );

    $headers = iterator_to_array($this->container->getHeaders());

    if ($headers) {
        array_walk($headers, function ($v, $k) use (&$compiled) {
            $compiled .= "{$k}: {$v}\n";
        });
    }

    $body = $this->container->getBody();

    if ($body) {
        $compiled .= "\n{$body}";
    }

    return $compiled;
}
```

**psalm.xml**
```xml
<?xml version="1.0"?>
<psalm
    totallyTyped="false"
    checkForThrowsDocblock="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config file:///Users/pbice/dev/9933-consulting/vendor/vimeo/psalm/config.xsd"
>
```

What am I doing wrong? Or is this an issue with Psalm?

**Comment by weirdan** [comment]
> One of the methods that Psalm reports an error for doesn't throw an exception on its own, rather a method it calls throws one which then bubbles up through the call stack.

So effectively it throws.The main goal of `checkForThrowsDocblock` it to find unhandled exceptions - and  psalm tells you you may get exception running this method, because you don't handle it there. `@throws` is supposed to be specified for all methods up to the point where it's handled.

**Comment by p810** [comment]
You're right, but still I'm not sure why the `@psalm-suppress` annotation isn't working here.

**Comment by weirdan** [comment]
Can you elaborate on why you want to suppress it? Does psalm identify exception as thrown where it really isn't, or does it fail to see you actually handle that exception? Or is there any other reason?

**Comment by p810** [comment]
I added a `@throws` annotation to the method earlier, but from my understanding of how `@psalm-suppress` is supposed to work, this could potentially be a bug. I'm not interested in getting this instance to work so much as I am curious why the annotation didn't in the first place.

**Comment by weirdan** [comment]
If this was made to work, it would be great to be able to ignore specific exceptions in specific methods.

**Comment by SignpostMarv** [comment]
@weirdan `@psalm-suppress MissingThrowsDocblock Throwable` turns off all the things?

**Comment by weirdan** [comment]
Yeah, but I was thinking about suppressing more specific kinds of exceptions.

**Comment by SignpostMarv** [comment]
Would support for `@template T as Throwable` + `@psalm-suppress MissingThrowsDocblock T` be overkill ?

**Comment by SignpostMarv** [comment]
p.s. I can see `@psalm-suppress MissingThrowsDocblock TypeError` being useful for libraries that support environments where `TypeError` doesn't exist :)

**Comment by weirdan** [comment]
> Would support for `@template T as Throwable` + `@psalm-suppress MissingThrowsDocblock T` be overkill ?

I don't see a practical application for that, so I would say yes.

**Comment by SignpostMarv** [comment]
@weirdan the only practical example I can foresee is phpunit, but `TestCase::expectException()` implies `@psalm-suppress MissingThrowsDocblock T` if it were stubbed out in psalm/phpunit-psalm-plugin as:

```php
/**
* @template T as Throwable
*
* @param class-string<T> $throwable
*/
public function expectException(string $throwable) { }
```

**Comment by weirdan** [comment]
@SignpostMarv but that would mean function call affects outer (callee) scope. Generally, all of the test methods should be treated as if all exceptions are suppressed - because PHPUnit would catch and handle everything that's thrown.
