### ISSUE TITLE
PhpStorm generics stopped working

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#1333]
Getting "Cannot determine the type of the object" for this method:

```php
    /**
     * @return \Traversable|HasErrorCode[]
     */
    public function getMessages();
```
Example: https://getpsalm.org/r/ef4492f426

```
$ php vendor/bin/psalm -v
Psalm 3.0.15@c310a2dd86660944b3f15fb8486ab73d45066618
$ grep Gene psalm.xml 
    allowPhpStormGenerics="true"
```

([Were they working before?](https://github.com/vimeo/psalm/blob/master/docs/configuration.md#allowphpstormgenerics) I don't know.)

Workaround is to use `@return \Traversable|HasErrorCode[]|\Traversable<HasErrorCode>`, but shouldn't it be working as it is? [Demo with this workaround.](https://getpsalm.org/r/d9baa714c6)

**Comment by andrew-demb** [comment]
+1, same isuue for me

**Comment by muglug** [comment]
It was definitely working before - Psalm is collapsing `Traversable|array` into `iterable`, but it shouldn't _if_ the config flag is on and the `Traversable` is also in the return param hint

**Comment by muglug** [comment]
I'll release a build with this

**Comment by muglug** [comment]
https://github.com/vimeo/psalm/releases/tag/3.0.16
