### ISSUE TITLE
calls to `list()` treated differently than manually-declared assign-from-array-offset

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1334]
# repro

* https://getpsalm.org/r/cabc44b573
* https://3v4l.org/qQorf
* using 27c99ae

```php
$foo = [];

list($a) = $foo;

echo $a;

$bar = [1,2,3];

if (count($bar) >= 3) {
	list($a, $b, $c, $d) = $bar; 
  
	echo $a, ',', $b, ',', $c, ',', $d;
}
```
> INFO: MixedArgument - 13:34 - Argument 7 of echo cannot be mixed, expecting string

# issue
* psalm does not identify that `list($a) = $foo;` will fail due to undefined index with the array being empty.
* psalm does not identify that `list($a, $b, $c, $d) = $bar;` will fail because `list()` is not being called inside a condition that suggests there's a 4th entry in `$bar`, only that there's at least 3 entries.
* psalm unexpectedly flags `$d` as being mixed.

# expected/desired
* psalm throws up an `EmptyArrayAccess` issue if list() is called on a known-empty array
* psalm treats list calls as if they were manually-declared assignments & throws up the appropriate `InvalidArrayOffset` issue as per:
```php
$bar = [1, 2, 3];

$a = $bar[0];
$b = $bar[1];
$c = $bar[2];
$d = $bar[3];

echo $a, "\n", $b, "\n", $c, "\n", $d, "\n";
```
> ERROR: InvalidArrayOffset - 7:6 - Cannot access value on variable $bar using offset value of 3, expecting '0', '1' or '2'
>
> INFO: MixedAssignment - 7:1 - Cannot assign $d to a mixed type
>
> INFO: MixedArgument - 9:36 - Argument 7 of echo cannot be mixed, expecting string

**Comment by muglug** [comment]
Psalm now checks a bunch of this stuff
