### ISSUE TITLE
Coalesce to empty array makes input mixed

### ISSUE THREAD

**Issue by ErikBooij** [vimeo/psalm#1335]
Given [the following code](https://getpsalm.org/r/bbf4881e60):

```php
<?php

class Session
{
    /** @var array */
    private $sessionData;

    /**
     * @param array $sessionData
     */
    private function __construct(array $sessionData)
    {
        $this->sessionData = $sessionData;
    }

    /**
     * @param array $data
     *
     * @return Session
     */
    public static function fromData(array  $data): self
    {
        return new static($data);
    }
}  

class SessionProvider
{
    /** @var Session|null */
    private static $session = null;

    /**
     * @return Session
     */
    public function getSession(): Session
    {
        // This line generates the issue
        return self::$session ?? self::$session = Session::fromData($_SESSION ?? []);
    }
}
```

```
MixedArgument - 36:69 - Argument 1 of Session::fromData cannot be mixed, expecting array<array-key, mixed>
```

Strange thing here is that both `$_SESSION` and `[]` as arguments don't generate the same issue.

I've tried finding the issue myself, but couldn't in a reasonable amount of time. If it's fixed, I'll try to learn something from that commit.

Thanks in advance!

**Comment by muglug** [comment]
is `$_SESSION` ever null?

**Comment by muglug** [comment]
`$_SESSION ?: []` works fine - I think Psalm struggles with a possibly null `$_SESSION`

**Comment by ErikBooij** [comment]
`$_SESSION` could theoretically be `null` if `session_start()` wasn't called.

But how would that explain that `Session::fromData($_SESSION)` doesn't generate this issue? That type apparently matches the expected signature, and so does `[]`, so the confusing this for me is that either of them is valid, but either of them *determined at runtime* isn't.

**Comment by ErikBooij** [comment]
`$_SESSION ?: []` works according to the analyzer, but doesn't actually work at runtime, that will generate an `Undefined variable: _SESSION` when `session_start()` has not been called.
