### ISSUE TITLE
Allow running without a psalm.xml configuration file

### ISSUE THREAD

**Issue by jdufresne** [vimeo/psalm#1336]
When integrating the default configuration in a project, this is my experience:

```
$ ./vendor/bin/psalm
Could not locate a config XML file in path /home/jdufresne/myproject/. Have you run 'psalm --init' ?
$ ./vendor/bin/psalm --init
Config file created successfully. Please re-run psalm.
$ ./vendor/bin/psalm
...
```

I made no edits to `psalm.xml`.

It would be nice if psalm could run without an XML configuration file. If one is not found, just use the default configuration (the same configuration generated by `--init`). It would remove this step and allow me to avoid adding yet another top level file to my project. Other CLI tools often take this approach.

**Comment by muglug** [comment]
I'm not going to add this, mainly because I think it'll open up a bunch annoying edge-cases when analysing individual files.

One exception is taint analysis, where _if composer is present_ you can run Psalm without a config (taint analysis always runs on the entire project anyway).

**Comment by abdounikarim** [comment]
Hello,

How can i do to run psalm without a configuration file ? I'm using a phar executable which doesn't read configuration files.

Cheers
