### ISSUE TITLE
types with transposed var type hints not being reported?

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#134]
This snippet cropped up earlier, because I typed it wrong :P

```php
/**
* @var $out int
*/
$out = 1;

return $out;
```
An unrelated error (i.e. was caused by something elsewhere in the code) reported that the return type of the method the code resembling the snippet was int|array<empty, empty>|$out- I'm thinking that if psalm detects a phpdoc hint with the arguments accidentally transposed, it could perhaps trigger an error of some sort?

**Comment by muglug** [comment]
Yes, there should be an `InvalidDocblock` error if the first part contains a `$` and isn't `$this`.
