### ISSUE TITLE
Documentation request: conditions for triggering UnusedMethod

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#1343]
When I try the code from [UnusedMethod documentation](https://github.com/vimeo/psalm/blob/master/docs/issues.md#unusedmethod) on getpsalm.org I don't get any issues (https://getpsalm.org/r/7cf15559f8). I was able to get `UnusedParam`, so dead code detection is on there.

Similarly I can't seem to get UnusedMethod in my tests (for psalm/phpunit-psalm-plugin) which leads me to believe there are some preconditions to get this working, but I have yet to identify them. Can you clarify them?

**Comment by muglug** [comment]
Was tracked here: https://github.com/psalm/getpsalm.org/issues/5, now fixed.

The key is to call `$project_analyzer->checkClassReferences()`

**Comment by muglug** [comment]
Example: https://getpsalm.org/r/ba412190d6
