### ISSUE TITLE
Error generated in TypeCombination

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#1350]
Running psalm on CakePHP's 4.x branch results in following error (though the process does seem to finish fine)

```
Analyzing /srv/cakephp/src/ORM/Entity.php

Notice: Undefined index: Traversable in phar:///home/admad/.phive/phars/psalm.phar/src/Psalm/Internal/Type/TypeCombination.php on line 301

Warning: Invalid argument supplied for foreach() in phar:///home/admad/.phive/phars/psalm.phar/src/Psalm/Internal/Type/TypeCombination.php on line 301
```

The file in question is [this](https://github.com/cakephp/cakephp/blob/4.x/src/ORM/Entity.php).

**Comment by muglug** [comment]
Thanks - sorry about that

**Comment by ADmad** [comment]
Thank you for your quick responses and fixes.
