### ISSUE TITLE
Missing tests?

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#1354]
Psaml test sute used to report over 18k tests (https://travis-ci.org/vimeo/psalm/jobs/489749181#L231) but now it shows only 2.9k (https://travis-ci.org/vimeo/psalm/jobs/494684508#L229)
![image](https://user-images.githubusercontent.com/57403/52954794-bae09400-3393-11e9-842a-6b39ffb0c556.png)
![image](https://user-images.githubusercontent.com/57403/52954868-eb283280-3393-11e9-98cf-8aa0f94dd2f4.png)

**Comment by muglug** [comment]
There was a data provider that used the CallMap as input to TypeParseTest. I simplified that to a single test so as not to spam the phpunit output

**Comment by weirdan** [comment]
Ah, great. Got me worried :rofl:
