### ISSUE TITLE
Ways to check subtypes from plugin

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#1357]
I'm working on checking data providers for PHPUnit tests, and facing the following issue:
Given a data provider method return type, I need to check if it's a subtype of `iterable<int|string,array>`.

As far as I understand, `TypeAnalyzer::isContainedBy()` is precisely what I need, but that class is internal. Are there any other ways to achieve this?

**Comment by muglug** [comment]
> but that class is internal

Feel free to make a method in `Psalm\Codebase` that calls that internal method!

**Comment by weirdan** [comment]
Yeah, will do, but I'd like to support users of older Psalm versions too. That's why I'm interested in workarounds.

**Comment by muglug** [comment]
The workaround is to use the internal method. The first three args of the signature won't change before v4, I think
