### ISSUE TITLE
Psalm not able to correctly identify return type of array_map() when callback is method of another class that returns "self"

### ISSUE THREAD

**Issue by jdreesen** [vimeo/psalm#1361]
https://getpsalm.org/r/a79ca62482

```php
<?php
  
class Foo {
  function __construct(int $param) {}
  
  static function self(int $param): self {
    return new self($param);
  }
  
  static function foo(int $param): Foo {
    return new self($param);
  }
}

class Bar {
  /**
   * @return Generator<int, Foo, mixed, void>
   */
  function fooSelf(): iterator {
    yield from array_map([Foo::class, 'self'], [1,2,3]);
  }
  
  /**
   * @return Generator<int, Foo, mixed, void>
   */
  function fooFoo(): iterator {
    yield from array_map([Foo::class, 'foo'], [1,2,3]);
  }
}
```

The return type of `Bar::fooSelf()` emits an error: 

> ERROR: InvalidReturnType - 17:6 - The declared return type 'Generator<int, Foo, mixed, void>' for Bar::fooSelf is incorrect, got 'Generator<int, Bar, mixed, void>'

Psalm seems to infer a wrong type when the callable has the return type `self`.

**Comment by weirdan** [comment]
Also reproducible without generators: https://getpsalm.org/r/0712ca9290

**Comment by jdreesen** [comment]
Interesting, thx for the investigation! I corrected the title.
