### ISSUE TITLE
Make @psalm-type defined inside a class accesible from outside

### ISSUE THREAD

**Issue by juanfernandoe** [vimeo/psalm#1363]
Please allow to access type alias from outside class

```php
class Test1
{

    /**
     * @psalm-type _BB=array{code:int,name:string}
     */
}


/**
 * @psalm-param Test1::_BB $p
 */
function func1(array $p): void {
    echo $p['code'];
}
```

output error:
Parameter $p has wrong type 'scalar-class-constant', should be 'array<array-key, mixe
d>'

**Comment by muglug** [comment]
Constants aren't scoped to the class - they're available throughout the file:

https://psalm.dev/r/414a8c16fb

**Comment by juanfernandoe** [comment]
Hi, 

I appreciate you taking the time to answer my question.

I have another doubt, how access class scoped psalm-type from another file?

**Comment by muglug** [comment]
It's not possible, unfortunately - it would introduce a level of indirection that would make the first scanning step much slower.

**Comment by juanfernandoe** [comment]
I understand

Have you any advise to workaround this situation?, because I'm planning to add psalm to an existent project.

I'm very influenced by the Hacklang shapes, so I have array structure across multiples classes.

**Comment by muglug** [comment]
No workaround that I can think of - Psalm itself copies types in a number of places: https://github.com/vimeo/psalm/search?q=IssueData&unscoped_q=IssueData

**Comment by muglug** [comment]
If they ever become a language feature (as they are with Hack) it may be possible to use other means to make this performative.

**Comment by juanfernandoe** [comment]
maybe you consider something like Phan Stubs in order to define global psalm-type in a special place, so you can parse global types at the beginning.

https://github.com/phan/phan/wiki/How-To-Use-Stubs

**Comment by muglug** [comment]
Ah yes, Psalm already supports stubs so that should be relatively easy. Created #1386 to track that.
