### ISSUE TITLE
mysql_* not typed for `resource|false`

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1372]
note to self to PR some stubs for `ext-mysql`

should I PR into main project or package it up as a stubby plugin that requires `php:<7.0` given that `ext-mysql` was removed in php 7.0 & the various `mysql_*` shims will have different return types ?

**Comment by weirdan** [comment]
> & the various `mysql_*` shims will have different return types ?

Got examples for that?

> should I PR into main project

There hasn't been any PHP 5.x compatible releases lately, so I think that branch is dead.

> package it up as a stubby plugin

Plugin packages is Psalm 3.x feature. Of course you can put out a composer package and add a README on how to add the required stub.

**Comment by SignpostMarv** [comment]
> Got examples for that?
* https://getpsalm.org/r/80e6d50395

> There hasn't been any PHP 5.x compatible releases lately, so I think that branch is dead.
the legacy environments I work with in the day job use so much psalm 1.x I think i've been that used to it :P

> Plugin packages is Psalm 3.x feature. Of course you can put out a composer package and add a README on how to add the required stub.
I'll see what happens when I pull in the mysql shim tomorrow- i'd imagine psalm would pick the types up from the shim'd functions.

**Comment by weirdan** [comment]
> https://getpsalm.org/r/80e6d50395

As long as those functions are in the CallMap it makes sense to PR to the main project repo.

**Comment by SignpostMarv** [comment]
Got one of the userland ext-mysql shims installed, looks like psalm sticks
to the callmap for return types?

**Comment by SignpostMarv** [comment]
> As long as those functions are in the CallMap it makes sense to PR to the main project repo.

I'm getting the feeling I should do something to the CallMap such as `if ( ! extension_loaded('mysql') && function_exists('mysql_connect')) { /* append to call map */ }`, so that if one loaded up a userland shim for the mysql extension, psalm would automatically go sniff from wherever the function was defined?

**Comment by muglug** [comment]
That wouldn’t be _terrible_, but why not just create a plugin with the stubs?

**Comment by SignpostMarv** [comment]
@muglug Do you think it's preferable to shift any deprecated/removed extension out of the main psalm repo ?

**Comment by muglug** [comment]
Certainly the removed ones, yeah

**Comment by SignpostMarv** [comment]
* [7.0](http://php.net/manual/en/migration70.removed-exts-sapis.php)
  * ext-ereg
  * ext-mssql
  * ext-mysql
  * ext-sybase_ct
* [7.2](http://php.net/manual/en/migration72.other-changes.php)
  * ext-mcrypt

**Comment by muglug** [comment]
Closing as not maintained
