### ISSUE TITLE
array<empty, empty> does not play nice with others

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1377]
# issue
* while specifying a types-only (`array<string, T>`) array one can default to `array<empty, empty>`: https://getpsalm.org/r/fc338f48b7, but when specifying the key/value types of an array, one cannot.
* one can also not union `array{id:string}` type with `array<empty, empty>` without it being converted to optional members (`array{id?:string}`)

# repro

* https://getpsalm.org/r/025b10de5c
* using b7a0950

```php
<?php

/**
* @template T as scalar
*
* @param array{id:T} $arr
*/
function foo(array $arr = []) : array {
  return $arr;
}

/**
* @template T as scalar
*
* @param array{id:T}|array<empty,empty> $arr
*/
function bar(array $arr = []) : array {
  return $arr;
}

/**
* @template T as scalar
*/
class BarBar {
  /**
  * @param array{id:T}|array<empty,empty> $arr
  */
  public function bar(array $arr = []) : array {
    return bar($arr);
  }
}

interface BarBarInterface {
  /**
  * @param array<string, scalar|array|object|null> $arr
  */
  public function bar(array $arr = []) : array;
}

class Baz implements BarBarInterface {
  /**
  * @param array{id:T}|array<empty,empty> $arr
  */
  public function bar(array $arr = []) : array {
    return bar($arr);
  }
}

class Bat implements BarBarInterface {
  /**
  * @param array{id:T} $arr
  */
  public function bar(array $arr = []) : array {
    return bar($arr);
  }
}
```
> ERROR: InvalidParamDefault - 6:10 - Default value type array<empty, empty> for argument 1 of method foo does not match the given type array{id:T}
> 
> ERROR: MoreSpecificImplementedParamType - 44:29 - Argument 1 of Baz::bar has wrong type 'array{id?:T}', expecting 'array<string, array<array-key, mixed>|scalar|object|null>' as defined by BarBarInterface::bar
> 
> ERROR: InvalidArgument - 45:16 - Argument 1 of bar expects array{id?:scalar}, array{id?:T} provided
> 
> ERROR: MoreSpecificImplementedParamType - 53:29 - Argument 1 of Bat::bar has wrong type 'array{id:T}', expecting 'array<string, array<array-key, mixed>|scalar|object|null>' as defined by BarBarInterface::bar
> 
> ERROR: InvalidParamDefault - 51:12 - Default value type array<empty, empty> for argument 1 of method Bat::bar does not match the given type array{id:T}
> 
> ERROR: InvalidArgument - 54:16 - Argument 1 of bar expects array{id?:scalar}, array{id:T} provided

**Comment by weirdan** [comment]
Works as expected, as far as I can see.

**Comment by muglug** [comment]
Yeah - `array{key: T}|array<empty, empty>` will be collapsed - I think you want `array{key?: T}`. Also you're missing some `@template` tags

**Comment by SignpostMarv** [comment]
@weirdan @muglug point being if I don't specify a union with `array<empty, empty>`, it complains of:

> MoreSpecificImplementedParamType - Tests\DefinesOwnIdPropertiesInterface\Fixtures\DefinesOwnScalarIdProperties.php:34:39 - Argument 1 of SignpostMarv\DaftObject\Tests\DefinesOwnIdPropertiesInterface\Fixtures\DefinesOwnScalarIdProperties::__construct has wrong type  'array{id:T as scalar}', expecting 'array\|scalar\|object\|null>' as defined by SignpostMarv\DaftObject\DaftObjectCreatedByArray::__construct

**Comment by weirdan** [comment]
Conceptually, are you trying to make constraints on implementer parameters more strict than interface requires? That would break LSP (Liskov Substitution Principle), and so it's rightfully flagged.

Maybe you actually need generic interface.

**Comment by SignpostMarv** [comment]
Flagging up a fixture for "must be given an array with key id of type T",
not for end-user consumption.
