### ISSUE TITLE
request for a more user-friendly error message

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1378]
# issue
Digging through one of the legacy environment projects at the day job; Discovered that a switch statement containing redundant cases triggers a `ParadoxicalCondition` issue, with a message that complains of `($i==!=int(0)) and ($i==!=int(0))`.

Is it possible for psalm to say something more user-friendly in the context of switch statements such as so that the following:
> ERROR: ParadoxicalCondition - 9:8 - Encountered a paradox when evaluating the conditionals ($i==!=int(0)) and ($i==!=int(0))

becomes something a little more friendly like:
> ERROR: ParadoxicalCondition - 9:8 - Encountered a paradox when evaluating the conditionals ($i==!=int(0)) in ***somefile.php:9:8*** and ($i==!=int(0)) in ***somefile.php:4:8***

# repro
* https://getpsalm.org/r/41b58e6e73
* using 6420a56

```php
<?php
$i = random_int(0, 2);
switch ($i) {
  case 0:
  case 1:
  case 2:
    echo $i;
    break;
  case 0:
    break;
  case 1:
    break;
  case 2:
    break;
}
```

> ERROR: ParadoxicalCondition - 9:8 - Encountered a paradox when evaluating the conditionals ($i==!=int(0)) and ($i==!=int(0))
> 
> ERROR: ParadoxicalCondition - 11:8 - Encountered a paradox when evaluating the conditionals ($i==!=int(1)) and ($i==!=int(1))
> 
> ERROR: ParadoxicalCondition - 13:8 - Encountered a paradox when evaluating the conditionals ($i==!=int(2)) and ($i==!=int(2))

**Comment by dkarlovi** [comment]
Same here: https://psalm.dev/r/1035490c06

Maybe the message tries to describe the exact failure it found? In my case:

```
file:9 `$s === 'two` is impossible here, it was matched in file:6
```

**Comment by muglug** [comment]
This is done!
