### ISSUE TITLE
Codebase::classExtends() with unpopulated ClassLikeStorage instance

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#1387]
It's possible to call `Codebase::classExtends()` during `afterClassLikeVisit()`, but it appears it would only work with immediate parent, probably because classlikes have not been crosslinked during this phase yet. Works fine during later stages (like in `AfterClassLikeAnalysisInterface::afterStatementAnalysis()`).

Am I supposed to check ClassLikeStorage::$populated before calling the method? It seems to be false when `classExtends()` produces false negatives. If so, I'd like to propose PR integrating this check into `classExtends()` itself, to save plugin authors a lot of confusion).

**Comment by muglug** [comment]
Yeah, please PR that - it's a good and necessary check
