### ISSUE TITLE
Psalm being unaware of __constructor() on built-in classes causes runner issues on psalm.dev

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1389]
# issue
Psalm being unaware of `__constructor()` method on built-in classes leads to psalm.dev runner being unable to get method params

# repro
## ReflectionClass
* expected (with workarounds): https://psalm.dev/r/2d23c927af
* actual: https://psalm.dev/r/2b5bba0f7b

**Comment by muglug** [comment]
Can't transfer to psalm.dev (different base org)

**Comment by SignpostMarv** [comment]
need to re-open

**Comment by SignpostMarv** [comment]
related to #1402

**Comment by muglug** [comment]
Fixed in https://github.com/psalm/psalm.dev/commit/f87393fc81b893a409014d052117d800310de4a2
