### ISSUE TITLE
possibly erroneous PossiblyUndefinedVariable ?

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#139]
Where:
```php
<?php
$foo = ['a', 'b', 'c'];
foreach ($foo as $bar) {
}
unset($foo, $bar);
```
> $ ./vendor/vimeo/psalm/bin/psalm ./src/foo.php
ERROR: PossiblyUndefinedVariable - src\foo.php:6 - Possibly undefined variable $bar, first seen on line 3
unset($foo, $bar);

Where:
```php
<?php
$foo = ['a', 'b', 'c'];
foreach ($foo as & $bar) {
    $bar = strtoupper($bar);
}
unset($foo, $bar);
```
> $ ./vendor/vimeo/psalm/bin/psalm ./src/foo.php
ERROR: PossiblyUndefinedVariable - src\foo.php:6 - Possibly undefined variable $bar, first seen on line 3
unset($foo, $bar);

Where:
```php
<?php
function baz() : array {
    return [];
};
$foo = baz();
foreach ($foo as & $bar) {
    $bar = strtoupper($bar);
}
unset($foo, $bar);
```
> $ ./vendor/vimeo/psalm/bin/psalm ./src/foo.php
ERROR: PossiblyUndefinedVariable - src\foo.php:9 - Possibly undefined variable $bar, first seen on line 6
unset($foo, $bar);

I'm thinking that  PossiblyUndefinedVariable should only occur in the third case, i.e. when the value of $foo is determined to be the result of a function/method that returns an array with no guarantee that the  the array is not empty since [if the foreach loop doesn't execute, $bar is not defined](https://3v4l.org/VV8Vo)

**Comment by SignpostMarv** [comment]
p.s. thought of a fourth case/second case where it should crop up:

```php
$foo = [];
if ($someCondition) {
    $foo = $baz();
}
```

In this case, $foo is both initialised as empty and conditionally empty.

**Comment by muglug** [comment]
Happy to remove `PossiblyUndefinedVariable` issues when calling `unset`. I agree it's extraneous. However, Psalm cannot reasonably figure out whether a given array is empty or not:

```php
function bat(array $foo) {
    foreach ($foo as $bar) {}
    echo $bar;
}
```

The above example emits an `E_NOTICE` for `bat([])`, but not `bat(["hello"])`
