### ISSUE TITLE
psalm incorrectly thinks DOMNode::$parentNode is never null

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1401]
* Correct behaviour: https://psalm.dev/r/868f2917e0 https://3v4l.org/OhJXF
* Incorrect behaviour: https://psalm.dev/r/38006b5afe

# repro

```php
<?php
function foo(DOMNode $node) : string {
  return get_class($node);
}

class BecauseRunnerBug extends DOMElement
{
  /**
  * @psalm-suppress UndefinedMethod
  */
  public function __construct(string $name, string $value = null, string $namespaceURI = null) {
    parent::__construct($name, $value, $namespaceUri);
  }
}

$node = new BecauseRunnerBug('foo');

echo foo($node->parentNode);
```

## expected
* ~related issue to file later~ see @weirdan comment on #1402 
* invalid type coercion maybe? i.e. `DOMNode::$parentNode` is `DOMNode|null`, unless context indicates otherwise- i.e. when looping over a node's children, `DOMNode::$parentNode` is only going to be null if the dom tree was manipulated mid-loop.

## actual
> Psalm output (using commit 815bf84): 
>
> No issues!

**Comment by muglug** [comment]
Nah, it's a problem where Psalm didn't know that `DOMElement::__construct` existed.
