### ISSUE TITLE
psalm does not find UnusedVariable errors if method or function body triggers or suppresses UndefinedMethod/UndefinedFunction

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1402]
# actual
* https://psalm.dev/r/868f2917e0
> Psalm output (using commit 815bf84): 
> 
> No issues!

# expected
* https://3v4l.org/OhJXF
~something similar to the notice 3v4l bubbles up- i.e. undefined variable "$foo" (psalm does internal case-insensitive check), did you mean "$Foo"?~
> Psalm output (using commit 815bf84): 
> 
> ERROR: UndefinedVariable - 12:39 - Cannot find referenced variable $namespaceUri, did you mean $namespaceURI

# repro
* using 815bf84
```php
<?php
function foo(? DOMNode $node) : bool {
  return ! is_null($node);
}

class BecauseRunnerBug extends DOMElement
{
  /**
  * @psalm-suppress UndefinedMethod
  */
  public function __construct(string $name, string $value = null, string $namespaceURI = null) {
    parent::__construct($name, $value, $namespaceUri);
  }
}

$node = new BecauseRunnerBug('foo');

echo foo($node->parentNode) ? 'yep' : 'nope';
```

**Comment by weirdan** [comment]
I think it's limited to undefined methods, see https://psalm.dev/r/26386e97dd

**Comment by SignpostMarv** [comment]
yup, definitely seems that way: https://psalm.dev/r/8512a30fc8

**Comment by weirdan** [comment]
@muglug what about undefined functions, like here https://psalm.dev/r/772af0ec5e ?
