### ISSUE TITLE
Class template params conflict with static method template params

### ISSUE THREAD

**Issue by joshdifabio** [vimeo/psalm#1403]
When a class has a template parameter, for example `T`, static methods on that class can define a template parameter with the same name `T` without any explicit error from Psalm. However, the template parameter on the static method(s) will not work as expected.

https://psalm.dev/r/0b86a1cfb4
https://psalm.dev/r/5fda436c35

I think it would make sense for static method templates param names not to conflict with class template param names, given that the templates apply to different scopes. However, if they must continue to conflict, an explicit error from Psalm would be good imo.

**Comment by muglug** [comment]
Yeah, Psalm should flag duplicate template parameters
