### ISSUE TITLE
TypeCoercion: Closure passed in to templated function unexpectedly rejected

### ISSUE THREAD

**Issue by joshdifabio** [vimeo/psalm#1408]
I'm not sure exactly how to describe this issue, but I'm pretty sure it's a bug.

https://psalm.dev/r/72860a47a8

**Comment by muglug** [comment]
Yeah, it's happening because Psalm thinks the templated param is the literal string `'foo'`

**Comment by muglug** [comment]
Actually not a bug, and I don't think this is real-world code. If you want to not have the error you need to type your templated thing more generally e.g. https://psalm.dev/r/830c77c9b2

I've fixed how Psalm reports callable types so the fix is a bit more obvious.

**Comment by joshdifabio** [comment]
Yeah, this was just me checking whether templated types were being inferred correctly. The previous error message was throwing me off. Thanks.
