### ISSUE TITLE
Support templated union types

### ISSUE THREAD

**Issue by bugreportuser** [vimeo/psalm#1418]
Union types for callable template params only infer the first type.

Template `T` should be inferred as `int|false`, but it's inferred as `int`.

Example (https://psalm.dev/r/b94061e018):
```php
<?php
/**
 * @template T
 * @param callable(T) $x
 * @param array<T> $y
 */
function example($x, $y): void {}

example(/** @param int|false $x */ function($x): void {}, [strpos('str', 'str')]);
```

Example output:
```
Psalm output (using commit 8ec188a):

ERROR: InvalidScalarArgument - 9:36 - Argument 1 of example expects callable(int), Closure(int|false):void provided

ERROR: InvalidScalarArgument - 9:59 - Argument 2 of example expects array<array-key, int>, array{0:int|false} provided
```

**Comment by muglug** [comment]
Templated unions are not supported atm - you can work around this for the moment with `@param scalar $x`

**Comment by bugreportuser** [comment]
Good to know, and thanks for the hint about `scalar`. Some more complex types still require `mixed`, but it's a good idea for the example.

**Comment by muglug** [comment]
Promoting to a bug, because I now think it was a bad design choice on my part

**Comment by weirdan** [comment]
What made you change your mind?

**Comment by muglug** [comment]
Realising that it prevented `ArrayObject<?int, string>` (which is necessary to allow `$a[] = "hello"`)

**Comment by bugreportuser** [comment]
Thanks! Great to see this fixed.
