### ISSUE TITLE
Object like notation should work for objects that implement ArrayAccess

### ISSUE THREAD

**Issue by nickyr** [vimeo/psalm#142]
A full example would be a little long, but

```php
<?php

class Foo implements ArrayAccess 
{
    // full class would be defined here
}

/**
 * @param Foo{key: int} $foo
 * @return int
 */
function bar($foo) 
{
    return $foo['key']; 
}
```

This actually will give a fatal error:

```
PHP Fatal error:  Uncaught exception 'Psalm\Exception\TypeParseTreeException' with message 'Object-like type must be array' in <file>
```

**Comment by TysonAndre** [comment]
This suggestion has conflicts with enhancements discussed in from https://github.com/vimeo/psalm/issues/390 

ArrayObject (the class) could work out, ArrayAccess (the interface) would potentially lead to different meanings

I can't think of a good syntax right now. Foo|ArrayAccess{key:int}, maybe.

**Comment by nickyr** [comment]
What sorts of different meanings do you foresee with ArrayAccess @TysonAndre?

**Comment by muglug** [comment]
I'm not sure this is helpful, and it's hard to implement
