### ISSUE TITLE
Fix complex undefined constant errors with define

### ISSUE THREAD

**Issue by bugreportuser** [vimeo/psalm#1428]
`define` doesn't always allow constants to be defined correctly.

This can be fixed with #1423 but that fails test `constantDefinedInFunctionButNotCalled`. This issue waits for a solution that does the same without failing the test.

Example (https://psalm.dev/r/307ec4b8e7):
```php
<?php
namespace ns;
function func(): void {}
define(__NAMESPACE__.'\\cons', 0);

namespace ns;
cons;
```

Example (https://psalm.dev/r/2a8155192c):
```php
<?php
namespace ns1;
function func(): void {}
define('ns3\\cons', 0);

namespace ns2;
\ns3\cons;
```

**Comment by muglug** [comment]
These both appear to work

**Comment by bugreportuser** [comment]
This is great. Thanks!
