### ISSUE TITLE
Psalm thinks types are mixed when you cast to arrays

### ISSUE THREAD

**Issue by nickyr** [vimeo/psalm#143]
Casting a string to an array returns an array containing the string. But paste this in getpsalm.org:

```php
<?php

/**
 * @param string|array<string> $bar
 * @return array<string>
 */
function foo($bar)
{
    foreach ((array) $bar as $baz) {
        // do stuff 
    }
    return (array) $bar;
}
```

You'll see errors where Psalm has decided the type of `(array) $baz` is `array<mixed>` instead of `array<string>`

**Comment by muglug** [comment]
> Casting a string to an array returns an array containing the string

Ah, I did not know that. Will fix.
