### ISSUE TITLE
Unable to suppress "InvalidReturnType" error using @psalm-suppress

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#1434]
https://psalm.dev/r/795aec48df

**Comment by muglug** [comment]
Thanks! There are also a bunch of other ways to suppress that:

```php
function first(string $foo): int {
  switch ($foo) {
    case 'a':
      return 0;
    case 'b':
      return 0;
  }
  
  throw new \Exception('bad');
}

/**
 * @psalm-param 'a'|'b' $foo 
 */
function second(string $foo): int {
  switch ($foo) {
    case 'a':
      return 0;
    case 'b':
      return 0;
  }
}
```

 https://psalm.dev/r/d287734ebf

**Comment by ADmad** [comment]
Thanks, how to deal with the error for this method.

https://github.com/cakephp/cakephp/blob/86cac2930946f886e335dbf26e1496ba3921c46c/src/View/View.php#L598-L620

**Comment by muglug** [comment]
Uh that looks a little strange? Do you want a `TypeError` to be thrown at the end?

**Comment by ADmad** [comment]
Actually adding a `return ''` at the end of method is what was needed :slightly_smiling_face:.

**Comment by ADmad** [comment]
I hope I am not being annoying but I have another case

https://github.com/cakephp/cakephp/blob/86cac2930946f886e335dbf26e1496ba3921c46c/src/Shell/SchemaCacheShell.php#L80-L90

The `abort()` method does throw and exception.

**Comment by muglug** [comment]
Add `@psalm-return never-return` here: https://github.com/cakephp/cakephp/blob/86cac2930946f886e335dbf26e1496ba3921c46c/src/Console/Shell.php#L789, and Psalm will understand the meaning of that call

**Comment by ADmad** [comment]
Sweet, thank you very much.

**Comment by ADmad** [comment]
The level of control psalm provides for dealing with issues is what sets it apart from the competition :slightly_smiling_face:.
