### ISSUE TITLE
Multiline function declaration reports problem in incorrect position

### ISSUE THREAD

**Issue by Nacoma** [vimeo/psalm#1437]
I've verified that this is the behavior in both VSCode and PhpStorm.

The provided error message is: `Not all code paths of test_function end in a return statement, return type string expected`.

For single line declarations the error range highlights the return type.
![selection_009](https://user-images.githubusercontent.com/1852424/53986168-107ea580-40e3-11e9-9526-160a14aacccd.png)

For multi line declarations it highlights the first line of the declaration using the character range of the return type.
![selection_008](https://user-images.githubusercontent.com/1852424/53986075-d0b7be00-40e2-11e9-8b70-954bdfe6f75b.png)

**Comment by muglug** [comment]
Thanks!
