### ISSUE TITLE
Warn about unused suppressions

### ISSUE THREAD

**Issue by bugreportuser** [vimeo/psalm#1444]
Unused suppressions can be confusing and clutter code.

Example (https://psalm.dev/r/b11fba8c87):
```php
<?php
$str = rand(0, 1) ? 'str' : 'st';
$x = strpos($str, 'str');
/** @psalm-suppress RedundantCondition */
assert($x !== false, 'never happens');
```

Example output:
```
Psalm output (using commit 57a4522):

No issues!
```

I would expect some warning about `RedundantCondition` not being suppressed.

**Comment by weirdan** [comment]
Related: #681

**Comment by bugreportuser** [comment]
Thanks! This is great.
