### ISSUE TITLE
Add implicitInheritdoc=true

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#1447]
Currently we can inherit psalm annotations using explicit `@inheritdoc`: https://psalm.dev/r/9a3c16f65f

But per http://docs.phpdoc.org/guides/inheritance.html, this is implied by default.

>  inheritance is automatic; you do not need to define a special tag for it.

To comply, i suggest adding `implicitInheritdoc="true"` in psalm.xml

**Comment by ro0NL** [comment]
Another case https://psalm.dev/r/63186e75ae

**Comment by weirdan** [comment]
> Another case https://psalm.dev/r/63186e75ae

This looks like a legitimate issue reported by Psalm. `class y` violates trait-required interface by narrowing down the type parameters for that method.
