### ISSUE TITLE
PHP function getmypid() can return false

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#1448]
According to the [manual](http://php.net/manual/en/function.getmypid.php), getmypid() returns false on error. Psalm thinks it always returns an int.

https://psalm.dev/r/cc505018a0

**Comment by still-dreaming-1** [comment]
Also, in my config, I have `ignoreInternalFunctionFalseReturn="false"`

**Comment by weirdan** [comment]
`man 2 getpid` (the underlying function `getmypid` uses) says:
> These functions [getpid, getppid] are always successful.

But, surprisingly, php can actually return `false` for this call: https://github.com/php/php-src/blob/623911f993f39ebbe75abe2771fc89faf6b15b9b/ext/standard/pageinfo.c#L141-L143

**Comment by still-dreaming-1** [comment]
@weirdan that is interesting. You may not have been implying this, but let's pretend for a moment that we believe it is completely impossible for PHP to actually hit that line of code where it would return false for getmypid(). Even if that were presently true, since the manual says it could return false, I would expect that a future version of PHP might have a scenario where it does return false. Therefore, until they change the manual and their own code to not have a case for it to return false, my opinion is that Psalm should conform to the expectations presented by the PHP manual, at least for this return value. In other words, I would not feel comfortable writing PHP code that does not handle this potentially false return value, therefore I feel Psalm should error on the side of caution by accommodate this.

**Comment by still-dreaming-1** [comment]
@weirdan That is interesting. Regardless I feel that since the manual and the PHP code say it could return false, I would rather write code that handles that return value, and I feel that Psalm should encourage this.

**Comment by weirdan** [comment]
>  I feel that since the PHP manual and code say it could return false [...]

Yep, specifically because of the 'code' part.

**Comment by muglug** [comment]
Would you mind PRing this (against CallMap.php)?

**Comment by still-dreaming-1** [comment]
@muglug  Thanks. That change looks simple enough. The next time I have a similar issue I will try making a PR.
