### ISSUE TITLE
Negative character positions

### ISSUE THREAD

**Issue by Nacoma** [vimeo/psalm#1449]
> In `LanguageServer/LanguageServer::emitIssues` the value of `$end_column - 1` is -1 with the following code snippet:
> 
> ```
> function test(): int {
>     return (new Something())
>         ->any();
> }
> ```

This was being discussed in [this issue](https://github.com/gtache/intellij-lsp/issues/68) on intellij-lsp. Let me know if there's any additional information that would be helpful.

**Comment by muglug** [comment]
Would you be able to reproduce on https://psalm.dev? The provided example doesn't result in negative offsets AFAICT: https://psalm.dev/r/e86812197b

**Comment by Nacoma** [comment]
https://psalm.dev/r/d9d6cd0f46 is the exact contents of `test.php` which is generating the following in PhpStorm:

```
[11-Mar-2019 16:16:13 America/Chicago] LanguageServerProtocol\Diagnostic::__set_state(array(
   'range' => 
  LanguageServerProtocol\Range::__set_state(array(
     'start' => 
    LanguageServerProtocol\Position::__set_state(array(
       'line' => 15,
       'character' => 4,
    )),
     'end' => 
    LanguageServerProtocol\Position::__set_state(array(
       'line' => 18,
       'character' => -1,
    )),
  )),
   'severity' => 1,
   'code' => NULL,
   'source' => 'Psalm',
   'message' => 'The type \'TestClass\' does not match the declared return type \'int\' for test2',
))
[11-Mar-2019 16:16:13 America/Chicago] LanguageServerProtocol\Diagnostic::__set_state(array(
   'range' => 
  LanguageServerProtocol\Range::__set_state(array(
     'start' => 
    LanguageServerProtocol\Position::__set_state(array(
       'line' => 14,
       'character' => 18,
    )),
     'end' => 
    LanguageServerProtocol\Position::__set_state(array(
       'line' => 14,
       'character' => 21,
    )),
  )),
   'severity' => 1,
   'code' => NULL,
   'source' => 'Psalm',
   'message' => 'The declared return type \'int\' for test2 is incorrect, got \'TestClass\'',
))
```

Because this works as expected on https://psalm.dev/ it seems safe for me to assume the problem has to do with the LSP server and not Psalm. If this is likely the case then feel free to close this.

**Comment by muglug** [comment]
I think the error is/was with Psalm. What version of Psalm do you have locally? And does the problem persist after `--clear-global-cache`?

**Comment by Nacoma** [comment]
I've tried clearing the global cache with 3.1.2 and still see the same `'line' => 18, 'character' => -1` diagnostic.

**Comment by Nacoma** [comment]
This may have been resolved. I can no longer reproduce the problem.

**Comment by muglug** [comment]
Closing as not reproducable
