### ISSUE TITLE
SimpleXMLElement::asXML is not typed correctly

### ISSUE THREAD

**Issue by nickyr** [vimeo/psalm#145]
Paste the following into getpsalm.org:

```php
<?php
  
$foo = new SimpleXMLElement('<hi />');
$bar = $foo->asXML();
if ($bar === false) {
	echo "Oh no!"; 
}
```

You'll get this error on the if statment:
![image](https://cloud.githubusercontent.com/assets/1389687/25294000/412d1738-26ab-11e7-8136-3ed48f116abf.png)

However, the documentation says that asXML can return a string or boolean: http://php.net/manual/en/simplexmlelement.asxml.php

**Comment by erunion** [comment]
Fix PR: https://github.com/vimeo/psalm/pull/146

**Comment by erunion** [comment]
@muglug You want to tag a new release for this CallMap fix?

**Comment by muglug** [comment]
Sure – have tagged 0.2.x and 0.3.x releases
