### ISSUE TITLE
Ignores ImplicitToStringCast when parameter allows null

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#1451]
Here is some code that shows Psalm will ignore an implicit `(string)` cast on an object whose class implements `__toString()` if the function it is being passed to expects a `?string`

https://psalm.dev/r/cca9157aa1

When `declare(strict_types=1);` is enabled, this can even lead to a runtime error because the implicit cast never happens.

**Comment by muglug** [comment]
This was fixed in c22cdb07959e4d4364dc51fb2adf00337d308070
