### ISSUE TITLE
Does declare(strict_types=1) affect Psalm?

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#1455]
I hope this is an acceptable place to ask this question, please let me know if it is not. This might also be considered a request to change Psalms behavior depending on how the question is answered.

I'm wondering if using PHP's `declare(strict_types=1)` affects the issues Psalm reports. I am wanting to configure Psalm such that not using `strict_types` does not prevent Psalm from reporting all the issues. Perhaps it already works that way, I'm not sure. In my opinion this would be a good option. The following explains why I want to do this.

I have been gradually adding types to the codebase I work on for some time now. We have also been using PHP's `declare(strict_types=1)` feature in the parts of our code that are more up to date with our coding standards. However, now I'm beginning to question the value of using both `strict_types` and Psalm together. Theoretically, Psalm should be capable of providing us with all the "type errors" we want to see, but at "compile time" instead of run time. However, Psalm's typing is more flexible than `strict_types`, it is able to be strict where we want it to be, and ignore type issues in other places.

It is starting to seem like PHP's `strict_types` is getting in the way of progress because I am afraid to add types to certain parts of the code where I would like to because we may not yet be able to remove all the type issues Psalm discovers as a result, and therefore this could result in runtime errors that would not occur if implicit casting were allowed because of not enabling `strict_types`. Of course adding types still needs to be done carefully if you are not going to remove all type errors right away, but in the context of parameter type declarations, the ability to implicitly cast does give us enough wiggle room to add more types sooner.

**Comment by muglug** [comment]
To your first question: `declare(strict_types=1)` changes the issue Psalm reports in the affected files - `InvalidScalarArgument` becomes `InvalidArgument` for arguments passed to those functions. It sounds like your config may be suppressing `InvalidScalarArgument`.

You can simulate the effects of `declare(strict_types=1)` without actually adding the `declare` using a per-directory config flag:

```
<projectFiles>
        <directory name="src" useStrictTypes="true"/>
</projectFiles>
```

That tells Psalm to pretend `declare(strict_types=1)` is at the top of every file in `src`.

**Comment by weirdan** [comment]
> `useStrictTypes="true"`

BTW, this flag is not in the docs.

**Comment by still-dreaming-1** [comment]
@muglug That's what I was looking for, thanks!
