### ISSUE TITLE
Undefined index endFilePos in PartialParserVisitor.php on line 72

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#1456]
Psalm reported some internal undefined index PHP notice. This is not an ongoing problem for me, so if you don't find the report helpful, go ahead and close it, I'm just reporting it to be helpful. I experienced this when running Psalm version 3.1.2. Here is what happened:

```
psalm --threads=3 --diff --diff-methods --show-info=false
Scanning files...

Notice: Undefined index: endFilePos in /home/jesse/acs/build_dependencies/psalm-isolated/vendor/vimeo/psalm/src/Psalm/Internal/Visitor/PartialParserVisitor.php on line 72
PHP Notice:  Undefined index: endFilePos in /home/jesse/acs/build_dependencies/psalm-isolated/vendor/vimeo/psalm/src/Psalm/Internal/Visitor/PartialParserVisitor.php on line 72
Analyzing files...
```
I don't know how to reproduce it. What happened is I rapidly ran a Vim macro hundreds of times that deleted all my `declare(strict_types=1);` lines. Then I ran the above command and got that output. I could not reproduce it by running the command again or by just running `psalm`. Despite the undefined index notice, Psalm continued running and accurately reported no errors found.

**Comment by still-dreaming-1** [comment]
I just realized, it is theoretically possible that, in addition to running that command manually, nvim was running Psalm commands automatically in the background at the same time, due to the Neomake plugin's integration with Psalm. So this might not so much be a bug as it is me abusing Psalm by running it multiple times before letting it finish?

**Comment by muglug** [comment]
> So this might not so much be a bug as it is me abusing Psalm by running it multiple times before letting it finish?

Yes, almost definitelt

**Comment by weirdan** [comment]
> Yes, almost definitely

@muglug If Psalm doesn't tolerate parallel runs shouldn't we provide some locking to prevent them, or at least mention it in the docs?

**Comment by muglug** [comment]
> If Psalm doesn't tolerate parallel runs shouldn't we provide some locking to prevent them, or at least mention it in the docs?

I don't think that's really necessary – though I suppose Psalm could exit with an exception if it detects a file has changed between scanning and analysis.

@still-dreaming-1 Psalm's language server support (via ALE or similar) should do what you want here, and much more performantly, without the risk of invoking this error.
