### ISSUE TITLE
Reflection

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1457]
What would be the best way to enable type inference for `ReflectionClass`, `ReflectionMethod` to help out with the following inference: https://psalm.dev/r/73bb4a110f

```php
/**
 * @template T
 * @param class-string<T> $className
 * @return ReflectionClass<T>
 */
function getTypeOf(string $className) {
    return new ReflectionClass($className);
}

/**
  * @template T
  * @param class-string<T> $className
  * @return T
  */
function getInstance(string $className) {
    return getTypeOf($className)->newInstanceWithoutConstructor();
}
```

**Comment by muglug** [comment]
The second function works (thanks to @SignpostMarv's work templating `ReflectionClass`) but the first function doesn't, due to a bug (I think).

**Comment by SignpostMarv** [comment]
workaround: https://psalm.dev/r/2430c5da80

```php
/**
 * @template T as object
 * @param class-string<T> $className
 * @return ReflectionClass<T>
 */
function getTypeOf(string $className) {
  /**
  * @var ReflectionClass<T>
  */
  $out = new ReflectionClass($className);
  
  return $out;
}
```

**Comment by SignpostMarv** [comment]
tl:dr; `* @param class-string<T> $className` doesn't automagically let psalm know that T is a class ?
