### ISSUE TITLE
Losing array type information after `empty` check

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1460]
Checking that an array is empty corrupts element type information: https://psalm.dev/r/83e77b4600

```
<?php
  
/**
 * @param array<int> $a
 */
function process(array $a): void {
    assert(!empty($a));
    foreach ($a as $i) {
    	assert(is_int($i));
    }
}

ERROR: DocblockTypeContradiction - 9:13 - 
Found a contradiction with a docblock-defined type when evaluating $i 
and trying to reconcile type 'int' to int
```

Without `empty` check everything works fine

**Comment by weirdan** [comment]
> corrupts element type information

Actually it shows that Psalm is aware of element type. Of course it shouldn't emit TypeContradiction (as there's no contradiction), but something like RedundantCondition would make sense here.

**Comment by vasily-kartashov** [comment]
OK, so this is pretty much `RedundantConditionGivenDocblockType` masquerading as `DockblockTypeContradition`.

**Comment by weirdan** [comment]
It appears so. However I wonder why Psalm does not emit the same issue when there's no '!empty' check - clearly you're asserting the same thing you've already declared with the docblock.

**Comment by muglug** [comment]
Crap sorry, this was bug was added in https://github.com/vimeo/psalm/commit/8650f9eb1ab29da822206369c054e8b34e01c389
