### ISSUE TITLE
Magento module usage?

### ISSUE THREAD

**Issue by paul-gene** [vimeo/psalm#1465]
How can i use Psalm to check my Magento 2 module?

After installing and trying to run `--init` I got this error:

`PHP Fatal error:  Uncaught Error: Class 'Magento\Framework\Component\ComponentRegistrar' not found in /Users/me/Projects/demo/magento2/app/code/MyVendor/MyModule/registration.php`

**Comment by weirdan** [comment]
Psalm requires either composer autoloader (preferred way) or specifying custom autoloader in config file with [autoloader attribute](https://github.com/vimeo/psalm/blob/master/docs/configuration.md#autoloader).
