### ISSUE TITLE
Should report issue when expanding variable in string that would produce issue with string casting

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#1471]
When a class does not implement __toString(), casting a variable of that type to a string will cause Psalm to report an issue, which is all good. When you embed that same variable into a double quoted string for expansion, Psalm should report a similar issue.

https://psalm.dev/r/01014d790f

**Comment by still-dreaming-1** [comment]
Hold up, I posted the wrong reproduce.

**Comment by still-dreaming-1** [comment]
Fixed it.

**Comment by SignpostMarv** [comment]
tweaked for completeness: https://psalm.dev/r/49c642e53d

**Comment by still-dreaming-1** [comment]
@muglug This is great! It found a bug in our code that I was completely unaware of. Also, that turned out to be dead code, so I was able to just delete the entire implementation (it was supposed to be a default implementation of an abstract method, but turned out to be overridden in all cases).
