### ISSUE TITLE
Maybe use relative file path for xsi:schemaLocation in psalm.xml

### ISSUE THREAD

**Issue by demetris** [vimeo/psalm#1472]
My psalm.xml created with `psalm --init` has this line:

```xml
xsi:schemaLocation="https://getpsalm.org/schema/config file:///mnt/c/Users/my-windows-username/path/to/my/project-dir/vendor/vimeo/psalm/config.xsd"
```

Would it be possible to make `psalm --init` use a relative file path there, to avoid revealing possibly sensitive information when psalm.xml leaves your machine?

I changed the above to:

```xml
xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
```

... and psalm seems to be OK with it.

ENVIRONMENT INFORMATION

In case it’s relevant:

Windows Subsystem for Linux running Debian on the latest official release of Windows 10.
Psalm was installed via Composer.

Thanks to anyone reading this ticket and to all people contributing to Psalm!

EDITED to add Composer bit to Environment Information.

**Comment by bugreportuser** [comment]
This would be fixed by #1392. The only difference is I'm guessing you're using Composer.

**Comment by demetris** [comment]
To add another maybe relevant bit to my Environment Information:

I installed Psalm with Composer

**Comment by bugreportuser** [comment]
Whoops, not a regression. It looks intentional for Composer installs. The PHAR still uses the relative path.

https://github.com/vimeo/psalm/blob/ab832207a4d23651b79a5625dd8198a883af48ea/src/psalm.php#L371-L377

**Comment by SignpostMarv** [comment]
this one bugs the crap outta me too :s
