### ISSUE TITLE
Rename `LogicException` stub?

### ISSUE THREAD

**Issue by gharlan** [vimeo/psalm#1477]
My code:

```php
<?php

namespace Foo;

class InvalidArgumentException extends \InvalidArgumentException
{
    public function __construct(string $message, ?\Exception $previous = null)
    {
        parent::__construct($message, 0, $previous);
    }
}
```

PhpStorm is showing me two warnings here:

![Screenshot 2019-03-17 17 28 10](https://user-images.githubusercontent.com/330436/54494413-4d644c80-48da-11e9-82c0-f1b8bbb9875c.png)

![Screenshot 2019-03-17 17 28 30](https://user-images.githubusercontent.com/330436/54494416-52290080-48da-11e9-82a2-7787a293c139.png)

The reason is this `LogicException` stub in psalm tests:
https://github.com/vimeo/psalm/blob/ca765cba589598ea9b7fcdca4c6128060f5fa684/tests/stubs/logicexception.php

`\InvalidArgumentException` extends `\LogicException`, and PhpStorm uses the stub from psalm instead of its own stub.

I don't know how this stub is used in psalm tests. Maybe it is possible, to rename it? Or is it required for the test, that it is named `LogicException` in root namespace?

**Comment by muglug** [comment]
I need a test for that, but it doesn't have to be as common as `LogicException`. I've changed to `DomainException`.

From googling it looks like one can exclude files from PHPStorm in the settings, btw. `vendor/vimeo/psalm/tests` would be an obvious candidate

**Comment by weirdan** [comment]
> vendor/vimeo/psalm/tests 
That shouldn't be in the dist archive though. Is Psalm missing .gitattributes file?

**Comment by muglug** [comment]
Yes, what is that?

**Comment by weirdan** [comment]
In short, it's a file where you can list files/dirs to not be included in git export (among other things). See https://madewithlove.be/gitattributes/ for more details.

**Comment by muglug** [comment]
Thanks, added in 6e88ddc
