### ISSUE TITLE
Variadic parameter

### ISSUE THREAD

**Issue by Isinlor** [vimeo/psalm#148]
Hello,

I have an issue with variadic parameter:
```
ERROR: InvalidDocblock - src/Constraint/BlockedRelationshipsConstraint.php:56 - Parameter $relationshipsBlockers has wrong type 'array<mixed, KUL\BioMed\Distribution\Contract\RelationshipsBlocker>', should be 'array<int, KUL\BioMed\Distribution\Contract\RelationshipsBlocker>'
    /**
     * BlockedRelationshipsConstraint constructor.
     *
     * @psalm-suppress InvalidDocblock
     *
     * @param string[]               $groupedByElementTypes
     * @param string[]               $blockedElementTypes
     * @param RelationshipsBlocker[] $relationshipsBlockers
     *
     * @throws \InvalidArgumentException
     */
    public function __construct(
```

```php
    /**
     * BlockedRelationshipsConstraint constructor.
     *
     * @psalm-suppress InvalidDocblock
     *
     * @param string[]               $groupedByElementTypes
     * @param string[]               $blockedElementTypes
     * @param RelationshipsBlocker[] $relationshipsBlockers
     *
     * @throws \InvalidArgumentException
     */
    public function __construct(
        array $groupedByElementTypes,
        array $blockedElementTypes,
        RelationshipsBlocker ...$relationshipsBlockers
    ) {
        // ...
    }
```

There is many things at hand.

1. `@psalm-suppress InvalidDocblock` does not work.
2. I feel like I should be able to ignore this error (mismatch between mixed and int from variadic) globaly for old style `RelationshipsBlocker[]`.
3. The version currently used by me is correctly interpreted by PHPStorm. However, `array<int, KUL\BioMed\Distribution\Contract\DistributionAwareConstraint>` is not, so I can not replace it.
4. I was thinking about something similar to `@psalm-return array<mixed, string>`, like `@psalm-param array<int, KUL\BioMed\Distribution\Contract\RelationshipsBlocker>`, but `@psalm-param` does not exists.

Any suggestions how to solve this error?

Thanks for your help.

**Comment by muglug** [comment]
Sorry, this is a poor error message.

The simplest way to fix it to change that line to

```
  @param RelationshipsBlocker ...$relationshipsBlockers
```

I'll keep this open so that `@psalm-suppress InvalidDocblock does actually suppress the error.
