### ISSUE TITLE
Intersection types must all be objects

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1481]
What's the particular reason not to allow intersection types on non-object types?

The following function indexes the list of array based on a property's value. https://psalm.dev/r/e996aadef0

```
/**
 * @template K as array-key
 * @template T
 *
 * @param array<array<K, T>> $a
 * @param string $key
 *
 * @return array<T & array-key, array<K, T>>
 */
function indexArray(array $a, string $keyField): array {
    $result = [];
    foreach ($a as $v) {
      	$key = $v[$keyField] ?? null;
      	if (is_string($key) || is_int($key)) {
            $result[$key] = $v;
        }
    }
    return $result;
}
```

With intersection types it should be able to detect that type of `indexArray(array<array<int,int>>)` is `array<int,array<int,int>>`

**Comment by weirdan** [comment]
Wouldn't promoting `array-key` to be template constraint (https://psalm.dev/r/61d0a97f09) solve this? Or do you expect T to be wider than that (e.g. `int|string|null` or similar)?

**Comment by vasily-kartashov** [comment]
I expect `T` to be anything. Sometimes the type T is the outcome of multiple conversion steps and can by itself be a complex type. 

For example, according to implementation above the function should accept `indexArray(array<array<int,DateTime>>)` and return an empty array.

**Comment by muglug** [comment]
Sorry, I'm not going to support this I don't think. It's basically too difficult to engineer well.

**Comment by vasily-kartashov** [comment]
`@var` it is :)
