### ISSUE TITLE
Fork Pool model uses `ps` to check process is running

### ISSUE THREAD

**Issue by neanton** [vimeo/psalm#1485]
Seems like this commit https://github.com/vimeo/psalm/commit/47e987ccf8b1dd227e77a20973a380103946c78c introduced an issue with Alpine-based images of PHP from Docker Hub, as Alpine is using busybox and has no such params for `ps` invocation (https://busybox.net/downloads/BusyBox.html).

Maybe this line:
https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Fork/Pool.php#L268

Can be replaced with sending a `kill -0` signal to PID to check if it's alive?

`$process_lookup = posix_kill($child_pid, 0);`

**Comment by muglug** [comment]
Sure - would you be able to PR a fix?

**Comment by neanton** [comment]
@muglug done, check please
