### ISSUE TITLE
Psalm expects array keys can have impossible types

### ISSUE THREAD

**Issue by jnvsor** [vimeo/psalm#1487]
Psalm doesn't perform the same type casts when creating arrays that PHP does:

https://psalm.dev/r/888b70685f

When using a key `null` in an array, you can't call `array_merge` on it because `null` isn't an `array-key` like it expects. Psalm should be able to detect `null` being cast to `''`

**Comment by jnvsor** [comment]
Sorry @muglug, could you reopen this? I should have been more explicit in my example: https://psalm.dev/r/bc23f331d6

Floats and bools are also examples of automatically cast array keys. Both are cast to int, with true becoming 1, false becoming 0, and floats being trunced. At least it's not version dependent behavior: https://3v4l.org/Zbdug

**Comment by bugreportuser** [comment]
This sounds dangerous. Can Psalm give an error if the type needs to be converted? I would expect that using non-`array-key` as a key is almost always a bug. It can be a different error but still an error.

**Comment by jnvsor** [comment]
That would work too, though I would presume that PHP doing these casts without so much as a notice implies it's intended. Either way the way it works currently isn't correct.

**Comment by bugreportuser** [comment]
I agree it's weird, but that could change eventually: https://externals.io/message/100180
