### ISSUE TITLE
Templated subclasses do not inherit templated return types from templated superclasses

### ISSUE THREAD

**Issue by joshdifabio** [vimeo/psalm#1488]
It looks like templated subclasses do not inherit templated return types from templated superclasses.

https://psalm.dev/r/2cd6e98f06

`IntCollection1` and `IntCollection2` should both error.

**Comment by muglug** [comment]
Thanks, this was hard to figure out (but I think [the fix](https://github.com/vimeo/psalm/commit/cc568422d8a6b53384095cd800b33607fd995dca?w=1) is robust?)
