### ISSUE TITLE
Else branch for literal value not equal can restrict type

### ISSUE THREAD

**Issue by bugreportuser** [vimeo/psalm#1491]
In this example, Psalm can restrict the type of `$x` in the else branch. It should be equal to `$y`.

Example (https://psalm.dev/r/183fa0d23f):
```php
<?php
/** @var 0|string */
$x = 0;
$y = rand(0, 1);
if ($x !== $y) {
} else {
    chr($x);
}

/** @var int|string */
$x = 0;
if ($x !== $y) {
} else {
    chr($x);
}
```

Example output:
```
Psalm output (using commit 9f7f707):

ERROR: DocblockTypeContradiction - 5:5 - int can never contain int|string

ERROR: InvalidScalarArgument - 7:6 - Argument 1 of chr expects int, int(0)|string provided

ERROR: InvalidScalarArgument - 14:6 - Argument 1 of chr expects int, int|string provided
```

Could be related to #1490.

**Comment by muglug** [comment]
Slight change here - Psalm isn't smart enough to realise that there's an intersection of types, so I added a `!is_string` check before the `chr`, but the other issue (`DocblockTypeContradiction`) is fixed

**Comment by bugreportuser** [comment]
Thanks! The workaround should be fine for my uses.
