### ISSUE TITLE
query: re RedundantThrownCatch ?

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1494]
Given that psalm has the ability to detect redundant conditions, what about redundant try-catch blocks ? i.e. a try-catch block where an exception is always thrown and handled entirely within the try-catch block (i.e. to replace `throw new Foo()` + `bar($e);` with `bar(new Foo());`.

Example:
* https://psalm.dev/r/6d267fe022
* https://3v4l.org/QJoqo
```php
<?php
use Throwable as 💩;

try {
    throw new Exception('foo');
} catch (💩 $e) {
    echo $e->getMessage();
}
```

above example *could* be re-written as: `echo (new Exception('foo'))->getMessage();`

p.s. while this snippet of code did initially get written as a bit of a giggle to see what PHP does with the poop emoji, the redundant try-catch block query is a serious one.

**Comment by muglug** [comment]
Not sure this is massively useful, as there are a lot of functions whose exceptions are not documented (but still throw)

**Comment by muglug** [comment]
Yeah, gonna close
