### ISSUE TITLE
Psalm doesn't correctly detect the number of arguments allowed for PDOStatement::setFetchMode

### ISSUE THREAD

**Issue by lord2800** [vimeo/psalm#1496]
(Sorry for the crazy title, I couldn't think of anything more succinct and still accurate)

[According to the docs](http://php.net/pdostatement.setfetchmode), `PDOStatement::setFetchMode` can optionally take up to 3 arguments, depending on the mode passed in. While trying to use the `PDO::FETCH_CLASS` mode, psalm reports a `TooManyArguments` error.

Example:
```php
<?php

class A { public $a; }

$db = new PDO('sqlite::memory:');
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$stmt = $db->prepare('select "a" as a');
$stmt->setFetchMode(PDO::FETCH_CLASS, A::class);
$stmt->execute();
$a = $stmt->fetch();
var_dump($a);
```

**Comment by lord2800** [comment]
Apologies--this is my bad. I somehow had an older version globally installed that got picked up instead.

**Comment by lord2800** [comment]
Nope I take that back--it definitely happens in the latest version too!

**Comment by muglug** [comment]
Yup, I added this suppression to Vimeo's own codebase last year. Good catch.

```
/** @psalm-suppress TooManyArguments due to Psalm not yet understanding callmap method options */
$this->getStatement()->setFetchMode(PDO::FETCH_CLASS, $class);
```

**Comment by lord2800** [comment]
Apparently there's another scenario this happens in as well (passing two values, i.e. `PDO::FETCH_CLASS | PDO::FETCH_PROPS_LATE`)--would you prefer me to create a new ticket for it or reopen this one?
