### ISSUE TITLE
Stub constants not recognized

### ISSUE THREAD

**Issue by tvdijen** [vimeo/psalm#1497]
Hi!

I have a project that uses the PHP radius library and in an attempt to silence Psalm on all kinds of missing/undefined stuff, I added the proper [PhpStorm stub file](https://github.com/JetBrains/phpstorm-stubs) to my [project](https://github.com/simplesamlphp/simplesamlphp-module-radius).
It does fix some of the issues, but it seems that constants defined in the stub-file are not [recognized](https://travis-ci.com/simplesamlphp/simplesamlphp-module-radius/jobs/187201936#L600).

Is this a bug? Am I doing something wrong here? Or have I just misinterpreted the way stubs are supposed to work?

**Comment by bugreportuser** [comment]
The problem is that those constants are defined with `define`. It looks like Psalm doesn't recognize those in stub files.

If you enable the radius extension before running Psalm, it shouldn't need that file.

**Comment by tvdijen** [comment]
Unfortunately installing the radius-library in Travis is sheer impossible... `pecl install` fails horribly and `apt-get install php-radius` appears to not deploy a .so file in the extensions-directory... This stub-file would make my life so much easier

**Comment by bugreportuser** [comment]
Not a problem. I checked, and none of those constants need `define`, so you can just change e.g., `define('RADIUS_MPPE_KEY_LEN', 16)` to `const RADIUS_MPPE_KEY_LEN = 16` while this is still an issue.

**Comment by muglug** [comment]
Thanks all for input!
