### ISSUE TITLE
Unable to suppress MethodSignatureMismatch

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#1499]
See https://psalm.dev/r/def9f6ff15 (vs. https://3v4l.org/gsA5L)

**Comment by weirdan** [comment]
I wonder why PHP ignores the trait signature altogether: https://3v4l.org/lFEgv

**Comment by muglug** [comment]
> no rationale is provided

Maybe it was just an omission?

I'm uncomfortable with allowing `MethodSignatureMismatch` to be suppressed locally, but I'll could create a `TraitMethodSignatureMismatch` issue that could (for this unique it-works-in-php-but-it-shouldn't situation)

**Comment by weirdan** [comment]
Note that when a trait declaring an abstract method is used in an abstract class, descendants of that class are forced to follow the signature (unlike concrete classes using the same trait): https://3v4l.org/PDFm7

**Comment by ro0NL** [comment]
i think we should not think of traits as real types, they are copy-pasted into a real type. As such IMHO the user is responsible for a valid type system in this case.
