### ISSUE TITLE
phar file missing for v3.2.3

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#1506]
https://github.com/vimeo/psalm/releases/tag/3.2.3

**Comment by weirdan** [comment]
https://travis-ci.org/vimeo/psalm/jobs/511048891

**Comment by muglug** [comment]
Yeah, I'm going to tag a new release if this build passes. Sorry about that.

**Comment by muglug** [comment]
Fixed in latest. Also you might be interested in https://github.com/psalm/phar, which now has an corresponding Phar for every Psalm release.
