### ISSUE TITLE
Class cannot be found with find-references-to option

### ISSUE THREAD

**Issue by leilaes** [vimeo/psalm#1509]
Hi there,

I am trying to use psalm library to find all the references to a class or method in a codebase (with find-references-to option). 
For some repositories, I get a message that the class I am looking for cannot be found. 
Example: 
repository: guzzle/guzzle, command: ./vendor/bin/psalm  --find-references-to=Client
Output: 
Scanning files...
Analyzing files...
Class Client cannot be found

Further, I was wondering if it is possible to find the references to only the classes defined in the main namespace without having to install the dependencies.

**Comment by muglug** [comment]
For `guzzle/guzzle`, the [`Client` class is namespaced](https://github.com/guzzle/guzzle/blob/master/src/Client.php) - so you'd want to run

```
vendor/bin/psalm --find-references-to=GuzzleHttp\Client
```

**Comment by leilaes** [comment]
Thank you for your reply.
I had tried that and had no luck. For the code below:
```
<?php
namespace TestInterface;
class TestClass{
    public function TestFunc(){

    }
}
```
and command  `vendor/bin/psalm --find-references-to=TestInterface\TestClass` I get this output:
```
Scanning files...
Analyzing files...
Class TestInterfaceTestClass cannot be found
```

**Comment by muglug** [comment]
Oh, sorry - try with quotes

```
vendor/bin/psalm --find-references-to="TestInterface\TestClass"
```

**Comment by leilaes** [comment]
Thanks for that :)
Another question, do we need to install all the dependencies before trying to find all the references? That would be a great help :)

**Comment by muglug** [comment]
Yeah, Psalm requires a composer installation before running.

**Comment by leilaes** [comment]
Thank you, our use-case is analysing third party code and while we are able to install all the dependencies it is very expensive. Would there be any workarounds?

**Comment by muglug** [comment]
No, sorry. You might have more luck with a phpcs plugin, but you'd have to write that yourself.
