### ISSUE TITLE
False UnusedVariable when used as array index on a variable of unknown type

### ISSUE THREAD

**Issue by mpesari** [vimeo/psalm#1510]
Sorry about the title.. here it is: https://psalm.dev/r/0263d3c10c

Yes it's stupid - but because toggling comments on line 23 gets rid of the error I smell something funny.

**Comment by mpesari** [comment]
This seems related: https://psalm.dev/r/02c5464c58

**Comment by mpesari** [comment]
OK so it boils down to this: https://psalm.dev/r/e4d3df9cb1

**Comment by muglug** [comment]
This is actually a deeper problem – Psalm doesn't check the offsets of `mixed` types (but it should)
