### ISSUE TITLE
psr0 namespace problem ??

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [vimeo/psalm#1511]
Hi - working on a Sanitized WordPress fork that does things better (e.g. argon2id etc.) including moving all the classes to autoloading mostly w/ PSR-4 namespacing but some w/ PSR-0 no-namespace (usually when it is stand-alone class also in PEAR)

Anyway - thank you for this tool, tempted to add vimeo/psalm to authors in docblock because it's really helping me clean stuff up ;)

But right now there is an issue - when I run

    vendor/bin/psalm psr0/Requests/Cookie

I get errors about `UndefinedClass` specifying that `Requests_Cookie` is not a valid class but the file for that class is there (and psalm finds no errors) so I suspect it might be a configuration error on my end in telling psalm where the classes are?

I'm using PEAR style directory structure for PSR-0 style classes.

Here is the project and I probably won't push again until I figure this out:

https://gitlab.com/Pipfrosch/swpress

Here is how I tell composer where the classes are, which I presume how I also tell psalm where the classes are:

        "autoload": {
            "psr-4": {
                "PHPMailer\\PHPMailer\\": "psr4/PHPMailer/PHPMailer/",
                "SWPress\\Block\\": "psr4/SWPress/Block/",
                "SWPress\\Core\\": "psr4/SWPress/Core/",
                "SWPress\\Error\\": "psr4/SWPress/Error/",
                "SWPress\\Exceptions\\": "psr4/SWPress/Exceptions/",
                "SWPress\\Groovytar\\": "psr4/SWPress/Groovytar/",
                "SWPress\\HTTP\\": "psr4/SWPress/HTTP/",
                "SWPress\\Plugins\\": "psr4/SWPress/Plugins/",
                "SWPress\\Themes\\TwentyNineteen\\": "psr4/SWPress/Themes/TwentyNineteen/",
                "SWPress\\Walker\\": "psr4/SWPress/Walker/",
                "SWPress\\Walker\\Admin\\": "psr4/SWPress/Walker/Admin/"
            },
            "psr-0": {
                "Requests": "psr0/",
                "SWP": "psr0/"
            }
        }

I tried modifying that specifically to add "Requests_Cookie" with the basedir of "psr0/Requests" and deleted my vendor directory to fresh install dev deps but that didn't seem to help.

The other psalm errors I'm working through, but how to tell it where the find the class it can't seem to find I think is configuration error, not code error.

**Comment by AliceWonderMiscreations** [comment]
gah - I mean psr0 directory structure problem, not namespace problem ;)

**Comment by weirdan** [comment]
`psr-0` entry maps *prefixes to paths*. So `"Vendor_Namespace_": "src/"` will make composer look for `Vendor_Namespace_Classname` in `src/Classname.php` file.
Given your configuration, I suppose it looks for `Requests_Cookie` class in `psr0//Cookie.php` file (which is obviously not there).

It appears empty prefix might work for your directory structure: `"" : "src/'` (so that class loader will resolve `Requests` -> `src/Requests.php`, `Requests_Cookie` -> `src/Requests/Cookie.php` and so on).

**Comment by AliceWonderMiscreations** [comment]
Didn't work for me but I solved it by using classpath - tedious but OTOH I am only using composer for debug and I'm not going to be putting very many things in the psr0 directory, mostly just stuff where the user can choose to use PEAR version instead if they want.
