### ISSUE TITLE
UndefinedInterfaceMethod on extended system interfaces

### ISSUE THREAD

**Issue by bernhard-efler** [vimeo/psalm#1515]
When extending from an system interfaces the inheritance is not checked.

```
interface ContainerInterface extends \RecursiveIterator
{
    /**
     * @param string|callable $filter
     * @return ContainerInterface
     */
    public function filter($filter, array $params = []): self;
}
```
the RecursiveIterator extends the Iterator interface which has current, key, next, ... methods

```
class Item implements ContainerInterface
{
    /**
     * @var ContainerInterface
     */
    private $container;

    /**
     * @return Item
     */
    public function current()
    {
        return $this->container->current();
    }
}
```

results in an 

> ERROR: UndefinedInterfaceMethod - Item.php - Method ContainerInterface::current does not exist
        return $this->container->current();

**Comment by muglug** [comment]
I'm not sure what the bug is here?

**Comment by bernhard-efler** [comment]
ContainerInterface extends \RecursiveIterator which extends the \Iterator interface
ContainerInterface contains also the methods from Iterator interface for example current()

But plsam give an error that ContainerInterface::current is not defined!

**Comment by muglug** [comment]
The code you've given doesn't run: https://3v4l.org/1booS

**Comment by weirdan** [comment]
@muglug see https://psalm.dev/r/298d878a38

**Comment by bernhard-efler** [comment]
@weirdan thx for the example!

**Comment by muglug** [comment]
Thanks all! That was a bad bug, I'm sorry.
