### ISSUE TITLE
Add a way to escape/unescape array keys of object-like arrays

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#1518]
(aka. array shapes)

1. Escape the key if it contains characters that aren't in a whitelist (e.g. use similar escaping to string())

```
<?php
$value = ["a\nb" => 'bar'];
echo strlen($value);
```

Note that the error output contains a literal newline, which may be a problem for some machine-readable formats

```
ERROR: InvalidArgument - src/what.php:3:13 - Argument 1 of strlen expects string, array{a
b:string(bar)} provided
echo strlen($value);
```

---

Also, any ideas on how to represent this?

I'd be in favor of `array{foo\\bar\nbaz:'literal'}` for the expression `["foo\\bar\nbaz" => "literal"]` (escape non-whitelisted characters)

Alternately, forcing those to be quoted (`array{'foo\\bar\nbaz':'literal'}`) may also work and allow using commas and `:` inside the key without escaping them, if the parser allowed it)

**Comment by SignpostMarv** [comment]
problem case: https://psalm.dev/r/e09b875b7c

```php
<?php
$foo = ["a\nb" => 'bar'];

$bar = ['a\nb' => 'bar'];

echo strlen($foo), strlen($bar);
```

> Psalm output (using commit ef8292c): 
> 
> ERROR: InvalidArgument - 6:13 - Argument 1 of strlen expects string, array{a
b:string(bar)} provided
> 
> ERROR: InvalidArgument - 6:27 - Argument 1 of strlen expects string, array{a\nb:string(bar)} provided

stupid suggestion: add support for concat, splitting escape-optional & escape-required characters, i.e:

> ERROR: InvalidArgument - 6:13 - Argument 1 of strlen expects string, array{concat(a,\n,b):string(bar)} provided

**Comment by SignpostMarv** [comment]
additional problem case: array shape keys should be able to have dots in them https://www.php.net/manual/en/function.imap-mail-compose.php https://psalm.dev/r/ffbd70ba44
