### ISSUE TITLE
False positive PossiblyFalseArgument when instantiating DateTime

### ISSUE THREAD

**Issue by pfazzi** [vimeo/psalm#1523]
Consider the following code:
```php
[$tprec, $codpro, $coddoc, $dtdoc, $codfor, $nomefor, $numbolla, $codcau, $dtcar] = $header;

if ($dtdoc === false) {
	throw new \InvalidArgumentException('Malformed CSV row.');
}

$instance = new Header(
	UniqueDocumentCode::create($coddoc),
	\DateTimeImmutable::createFromFormat('Y-m-d', $dtdoc),
	SupplierCode::create($codfor)
);
```
Even if i check that $dtdoc is not false i still get the PossiblyFalseArgument when instantiating the DateTimeImmutable. Is it possible to avoid it?

**Comment by weirdan** [comment]
I couldn't reproduce PossiblyFalse* issue, but latest Psalm reports no issues when `$header` is fully typed: https://psalm.dev/r/ba39ea7abb

**Comment by pfazzi** [comment]
In my code header is not fully typed, i'll add types ;)
