### ISSUE TITLE
Anonymous function

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [vimeo/psalm#1529]
I can probably silence these with PHPdoc parameters but I wonder if they exist because I'm not doing it right?

Anonymous function used in a callback

    /**
     * Use regular expressions to replace unsafe characters with percent encoded.
     *
     * @param array  $array  Characters in addition to always encode.
     * @param string $string The string to encode.
     *
     * @return string The encoded string.
     */
    protected static function makeSafe($array, $string): string
    {
        mb_internal_encoding('UTF-8');
        $string = rawurldecode($string);
        $dirty = array_merge(self::$encodeMe, $array);
        $s = array();
        $r = array();
        foreach ($dirty as $key => $value) {
            $s[] = "/" . $key . "/";
            $r[] = $value;
        }
        $return = preg_replace($s, $r, $string);
        if (! mb_detect_encoding($return, 'ASCII', true)) {
            //now non-ascii characters
            $return = preg_replace_callback(
                '/[^\x00-\x7F]/',
                function ($m) {
                    return rawurlencode($m[0]);
                },
                $return
            );
        }
        return $return;
    }//end makeSafe()

It's the defined function for the callback where I get these warnings from psalm:

    INFO: MissingClosureReturnType - psr4/Pipfrosch/NetCom/UrlEncode.php:75:17 - Closure does not have a return type, expecting string
                    function ($m) {

    INFO: MissingClosureParamType - psr4/Pipfrosch/NetCom/UrlEncode.php:75:27 - Parameter $m has no provided type
                    function ($m) {

From the context they obviously will always be strings, but I am not indicating they will always be string hence why psalm is complaining, is there a proper way to indicate the type for `$m` and the return type?

**Comment by weirdan** [comment]
As with any other function, you either use type hints or docblocks (or both):
```php
<?php
  $return = ""; // some string
  preg_replace_callback(
    '/[^\x00-\x7F]/',
    /** @param string[] $m */
    function (array $m): string {
      return rawurlencode($m[0]);
    },
    $return
  );
```
(https://psalm.dev/r/6816c1f115)
> they obviously will always be strings

Callback argument is gonna be array actually, and Psalm is able to tell you that if you specify any other type for the callback arg.

**Comment by AliceWonderMiscreations** [comment]
Thank you, I don't understand why it didn't work when I tried it before (the type hinting way), must have been a typo I didn't see. Working now.
