### ISSUE TITLE
Support generative type providers

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#153]
Given code (with functionality defined elsewhere) I want to be able to fully type check this:

```php
class Dog extends DBEntity {
  /** @var string **/
  public $name;

  /** @var int **/
  public $age;
}

$dogs = Dog::getDatasource();

$age_field = $dogs->getField('age');
$name_field = $dogs->getField('name');

$puppies = $dogs->where(new DsLessThan($age_field, 2))->select($name_field)->fetchAll();

foreach ($puppies as $puppy_row) {
  echo $puppy_row['name'];
  echo $puppy_row['age']; // this would throw an error
}
```

Conceptually an extension of https://github.com/vimeo/psalm/issues/89, where we say that some functions/methods have the ability to return a projection of their input.

**Comment by TysonAndre** [comment]
If the goal is to type check a specific ORM, this should also be possible to do via a plugin or an example plugin for DBEntity after https://github.com/vimeo/psalm/issues/459 ? (May have to loop over all subclasses of DBEntity)

(And could be published as an example plugin for a simple mock ORM or a real ORM)

E.g. plugins could be much more specific about what to do for an absent field, or generating a filtered list of public properties)

**Comment by muglug** [comment]
@TysonAndre yeah, I think a plugin would to it. I'm also thinking of a system that could introduce its own meta type constraints, and check them. For example, I can create a `LazyComparison` object that takes arguments of `LazyString` and `LazyString` but not `LazyString` and `LazyInt`

**Comment by muglug** [comment]
Closing as too complicated
