### ISSUE TITLE
How to annotate empty array

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1533]
How do I annotate this return type:

```
function f(bool $empty): array {
    if ($empty) {
        return [];
    } else {
        return ['a' => 1, 'b' => 2, 'c' => 3];
    }
}
```

Preferably I'd like something like `empty-array|array{a:int,b:int,c:int}`. At the moment the best I seem to be able to do is `array{a?:int,b?:int,c?:int}` which is "wider" than the actual return type.

**Comment by muglug** [comment]
Not possible - arrays are always unified. I’d recommend using `null` if possible.
