### ISSUE TITLE
SoapFault constructor signature mismatch

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#1535]
Psalm seems to detect incorrectly the constructor of SoapFault. It looks like it tries to match thesignature of SoapFault to the one of \Exception.

https://psalm.dev/r/2cc662a08b

```php
<?php
  
new SoapFault('1', 'faultstring', 'faultactor');
```

Output:
```
ERROR: InvalidScalarArgument - 3:20 - Argument 2 of __construct expects int, string(faultstring) provided
ERROR: InvalidArgument - 3:35 - Argument 3 of __construct expects null|Throwable, string(faultactor) provided
```

Expected:
```
No issues!
```

**Comment by muglug** [comment]
Just fixed this - `SoapFault`'s reflection is wrong, confusing Psalm.
