### ISSUE TITLE
Fatal error: Cannot construct a union with empty type

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#1536]
Hello,

With our codebase, psalm (since 375f3917b2699ae360e99742fac0f5f860dd1618) crashes with this error:
```php
Fatal error: Uncaught UnexpectedValueException: Cannot construct a union with empty types in src/Psalm/Type/Union.php:135
```

The issue can be reproduced with this code snippet:
https://psalm.dev/r/e79db3633e
```php
<?php

function funcError()
{
    return array_filter(
        array_map(
            static function ($arg) {
                return;
            },
            []
        )
    );
}
```

**Comment by muglug** [comment]
Thanks - the snippet should always produce an empty array, and I've updated to match

**Comment by LeSuisse** [comment]
Thanks for the quick fix! :+1:
