### ISSUE TITLE
Cannot access array value on non-array variable $array['key'] of type void

### ISSUE THREAD

**Issue by jaydiablo** [vimeo/psalm#1539]
This was encountered on some code that uses the Zend Framework Zend\Config class (https://github.com/zendframework/zend-config/blob/master/src/Config.php#L22).

I was able to get a working example on psalm.dev and also on 3v4l.org.

Here's the example on psalm.dev:  https://psalm.dev/r/4fff6e8d29  The `Config` class there is mostly a direct copy of Zend's Config class, but I removed a couple of methods (`merge` and `clone`) to reduce how much code is there, as psalm.dev appears to have a limit on how much code it'll process.

Here's the exact same code on 3v4l.org: https://3v4l.org/ajpbM

The specific error that I'm concerned about here is the one in the subject of this issue:

>ERROR: InvalidArrayAssignment - 219:1 - Cannot access array value on non-array variable $array['key'] of type void

The rest are all internal to the `Zend\Config` class, which is only there so I can reproduce this issue.

The `Zend\Config` class has a `__set` magic method defined (https://github.com/zendframework/zend-config/blob/master/src/Config.php#L106) that has this in it:

```
if (is_array($value)) {
    $value = new static($value, true);
}
```

I believe this is probably the source of the issue because psalm sees that this method is called when setting `$array['key']` to an empty array, so is applying the `void` return type (which is the return type of `__set`) to `$array['key']` rather than the array value itself (technically it becomes another `Zend\Config` object).

I'm not sure this is something that's easily resolvable in psalm, but thought I'd bring it up.

**Comment by muglug** [comment]
Fixed in 8f1dbc072df6930898de4b9d9323916f4d1a4bc3
