### ISSUE TITLE
managing to confuse type resolver re: mixed > throw if not valid

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1545]
* using 34ebf5c
* https://psalm.dev/r/23eab0e6c3

```php
<?php
  
/**
* @param mixed $width
* @param mixed $height
*
* @throws RuntimeException
*/
function Foo($width, $height) : void {
  if ( ! (is_int($width) || is_float($width)) || ! (is_int($height) || is_float($height))) {
    throw new RuntimeException('Width & Height were not numeric!');
  }
  
  echo sprintf('padding-top:%s%%;', 100 * ($height/$width));
}
```

> Psalm output (using commit 34ebf5c): 
> 
> INFO: MixedOperand - 14:44 - Left operand cannot be mixed
> 
> INFO: MixedArgument - 14:37 - Argument 2 of sprintf cannot be mixed, expecting string|int|float

The exception is thrown only if width or height are not either an int or a float, therefore in any subsequent code the types should be `int|float`

**Comment by SignpostMarv** [comment]
p.s. this issue also occurs with is_numeric.

**Comment by muglug** [comment]
`is_numeric` issue fixed in cadee4d

**Comment by muglug** [comment]
This works: https://psalm.dev/r/0d11d03290

**Comment by muglug** [comment]
Improved handling slightly in 8751bf2 to work around a problem this fix introduced
