### ISSUE TITLE
Return type of array_merge isn't appropriately specific

### ISSUE THREAD

**Issue by nickyr** [vimeo/psalm#156]
Paste this into getpsalm.org:

```php
<?php
/**
 * @param array<string, int> $a
 * @return array<string, int>
 */
function foo($a)
{
  return $a; 
}
  
$a1 = ['hi' => 3];
$a2 = ['bye' => 5];
$a3 = array_merge($a1, $a2);

foo($a3);
```

and you'll get

![image](https://cloud.githubusercontent.com/assets/1389687/25751825/49d1c83c-3184-11e7-913e-aba9d4f2019e.png)

array_merge's return type depends on the type of the parameters, but psalm doesn't acknowledge this.

**Comment by muglug** [comment]
changing the arrays to
```php
$t1 = 't1';
$t2 = 't2';
$a1 = [$t1 => 3];
$a2 = [$t2 => 5];
```
so it's an issue with object-like arrays. Will fix!

**Comment by nickyr** [comment]
Cool, thanks!
