### ISSUE TITLE
query re: MoreSpecificReturnType & template-extends

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1560]
if class A has a template tag for T as Foo on class Bar, and class Baz extends Bar but also has a template tag for T as Foo and flags `template-extends<T>`, is it meant to cause a `MoreSpecificReturnType` ? I've recently been seeing `"The decalred return type 'class-string<Foo>' for Baz::someMethod() is more specific than the inferred return type 'class-string'`

**Comment by muglug** [comment]
Sorry, could you provide an example?

**Comment by SignpostMarv** [comment]
* https://github.com/SignpostMarv/daft-object/commit/5a14c1d2a6afdc1cdec56703e9bdd25c345a9a1f
* https://github.com/SignpostMarv/daft-object/blob/3926a32e909ab35e7b5c3fca89e385e46959f7e7/Tests/DefinitionAssistant/DefinitionAssistant.php#L46
* https://github.com/SignpostMarv/daft-object/blob/3926a32e909ab35e7b5c3fca89e385e46959f7e7/src/DefinitionAssistant.php#L162

**Comment by SignpostMarv** [comment]
https://github.com/SignpostMarv/daft-db-object/blob/3f232c014ad214be1f7414a5b0012a55e35098bb/Tests/AbstractDaftObjectEasyDBRepository/AbstractDaftObjectEasyDBRepositoryTest.php#L81 gets `TypeCoercion` from https://github.com/SignpostMarv/daft-object-repository/blob/56f32f57674a4afd4115c91f5f357784dd8b3d39/Tests/DaftObjectMemoryRepository/DaftObjectMemoryRepositoryTest.php#L192

**Comment by muglug** [comment]
Thanks - could you provide an example on psalm.dev? Something that I could test against?

**Comment by SignpostMarv** [comment]
this one is a little difficult to express on psalm.dev, as I'm not 100% certain of the cause?
