### ISSUE TITLE
PHP Notice: Uninitialized string offset 

### ISSUE THREAD

**Issue by Alexander882** [vimeo/psalm#1563]
When running Psalm on my project I get the following notice:
```
PHP Notice: Uninitialized string offset: 0 in ...\vendor\vimeo\psalm\src\Psalm\Type.php on line 498
```

As far as I can tell from looking at the source of the error, it seems that it's missing a check for empty strings:
```
if ($parse_tree->value[0] === '"' || $parse_tree->value[0] === '\'') {
```

**Comment by muglug** [comment]
Would you mind running with `--debug-by-line` to figure out where the empty type is coming from? That string should never be empty.

**Comment by Alexander882** [comment]
Hi again, sorry for the long wait, it was for some reason very difficult to get the error to happen consistently.
I've finally managed to narrow it down to the following horrible code someone has written in my codebase
```
/**
     * @return \?string
     */
    public function getSendDateTime(): ?string
    {
        return $this->sendDateTime;
    }
```
Removing the `\` alone was enough to make the error go away

**Comment by muglug** [comment]
Reproduced with

```
/**
 * @return \?string
 */
function foo() {
  return rand(0, 1) ? "hello" : null;
}
```
