### ISSUE TITLE
CallMap for stream_get_meta_data

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1567]
CallMap for https://www.php.net/manual/en/function.stream-get-meta-data.php now says: `array{timed_out:bool,blocked:bool,eof:bool,unread_bytes:int,stream_type:string,wrapper_type:string,wrapper_data:mixed,mode:string,seekable:bool,uri:string}|array<string,mixed>`

I think the union type leads to this: https://www.php.net/manual/en/function.stream-get-meta-data.php

Additionally, isn't `array<string,mixed>` a super type of `array{timed_out:bool,blocked:bool,eof:bool,unread_bytes:int,stream_type:string,wrapper_type:string,wrapper_data:mixed,mode:string,seekable:bool,uri:string}` and as such redundant?

**Comment by muglug** [comment]
Thanks!
