### ISSUE TITLE
Intersection types and object like arrays

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1571]
Why doesn't this example work (https://psalm.dev/r/85152e01af)? 

```
/**
 * @template T as array{id:int}
 * @param T $a
 * @return T & array{name:string}
 */
function f(array $a) {
    $a['name'] = (string) $a['id'];
    return $a;
}

$a = ['id' => 1, 'active' => false];
$c = f($a);

echo $c['name'];
```

I expect the type of `$c` to be `array{id:int(1),active:bool(false),name:string}`?

The motivation for this is to get some coverage for PHP code that uses this pattern: accept an object like array, add (drop as well, but let's ignore it for now) few fields, return the modified input.

Maybe this would be a more direct way of expressing the same idea:

```
/**
 * @template T as array{userId:int}
 * @param T $user
 * @return T + location as array{latitude: float, longitude: float}
 */
function addLocation(array $a): array {
     ...
}
```

**Comment by muglug** [comment]
Intersections cannot be done on arrays at the moment, and I don't plan on implementing that feature.
