### ISSUE TITLE
substr' third parameter

### ISSUE THREAD

**Issue by swiffer** [vimeo/psalm#1572]
According to the php docs, the third parameter of strpos can be **false**:

> If length is given and is 0, FALSE or NULL, an empty string will be returned. 

```php
$eEmail = substr($abfrage[1], 0, strpos($abfrage[1], "@@"));
```

https://www.php.net/manual/en/function.substr.php

**Comment by muglug** [comment]
I’m tempted to close this. While it’s currently valid code, and Psalm generally aims to allow valid code, it also conceals a possible error scenario (where `strpos` returns `false`).

Would be interested in @TysonAndre’s opinion here.

**Comment by TysonAndre** [comment]
I'm also in favor of closing this.

I wasn't aware of that edge case - I'd prefer code to explicitly spell out what the index for null strpos (etc.) is.

- People reading that snippet might not know if $eEmail was going to be an empty string, null, or something else
- Phan changes similar code to `(int)strpos(...)` to pass type checking

Also, if the type was changed to `?int|?false`, then code such as `substr($x, 0, false)` and `substr($x, 0, some_bool())` would be unintentionally accepted in type checkers casting rules (without special casing). This would allow more bugs through.

- And `SomeClass|false` is then treated as **potentially** valid without special casing (strict type checks will still warn about SomeClass)

**Comment by muglug** [comment]
Thanks!
