### ISSUE TITLE
Probelm parsing psalm.xml ParseError is not expected

### ISSUE THREAD

**Issue by widoz** [vimeo/psalm#1583]
Getting this error by running `./vendor/bin/psalm`

```
Problem parsing <path>/psalm.xml:
  Error on line 84:
    Element '{https://getpsalm.org/schema/config}ParseError': This element is not expected.
```

I see in the doc [Issue.md](https://github.com/vimeo/psalm/blob/master/docs/issues.md#parseerror) that a `ParseError` element exists.

**Comment by muglug** [comment]
This is by design - you shouldn’t be able to suppress `ParseError`, because it implies you’ve done a bad thing.

**Comment by widoz** [comment]
@muglug Thanks for the info, may be the doc should be updated in that case. 
Btw I get another similar issue:

```
Problem parsing <path>/psalm.xml:
  Error on line 110:
    Element '{https://getpsalm.org/schema/config}MixedArrayTypeCoercion': This element is not expected.
```

For all *Coercion rules

**Comment by muglug** [comment]
Are you on latest master? That issue should only be emitted on latest master (and you should only be able to suppress in in latest master, too). It's not yet in any release (though it's in the docs because they're synced to master).

**Comment by widoz** [comment]
Ah thank you for informing me. 

Sorry I know this isn't for support but I haven't found enough information online.
Thank you again.

**Comment by dshafik** [comment]
@muglug I'd like to raise this issue again, as I have a legitimate case for ignoring a parse error. Forward compatibility polyfills.

My project (ultimately) depends on symfony/polyfill-mbstring, which has a polyfill for PHP 8.0 that uses `??=`. My project is running PHP 7.4, which is what is in my `composer.json`, and while I can specify `--php-version=8.0` that means it wouldn't detect usage of PHP 8.0-specific features as incorrect in files I _do_ care about.

Simply ignoring the file doesn't work.

**Comment by weirdan** [comment]
@dshafik the case of polyfills including files base on PHP version (as is the case with `symfony/polyfill-mbstring`) is going to be solved in a different way, see https://github.com/vimeo/psalm/issues/4961#issuecomment-757082605
