### ISSUE TITLE
Is there a Difference Between Unused and Dead Code?

### ISSUE THREAD

**Issue by astorm** [vimeo/psalm#1586]
The `psalter` and `psalm` commands (appear to?) use _different_ option names for the same functionality

    ./vendor/bin/psalter --help
    //...
    --find-unused-code
        Include unused code as a candidate for removal    
    //...
    
    ./vendor/bin/psalm --help
    //...    
    --find-dead-code[=auto]
        Look for dead code. Options are 'auto' or 'always'. If no value is specified, default is 'auto'    
    //...    
    
This created a bit of confusion for me when I was first using psalm.  It's a small thing, but it would be great if option flags with identical/near identical functionality were the same across project.

**Comment by muglug** [comment]
No, they do the same things, but `--find-unused-code` is the preferred way now - a less dramatic name.

I've just added `--find-unused-code` as an alternative formulation when running Psalm.
