### ISSUE TITLE
Add a class-string-like metatype which supports non-objects

### ISSUE THREAD

**Issue by joshdifabio** [vimeo/psalm#1589]
When utilising `@template` to create generic data structures, I often have the need for something like `class-string` which supports all types, not just object types. For example:

```php
/**
 * @template E
 */
class Collection
{
    /**
     * @param type-string<E>
     */
    function __construct(string $type): self {}
}
```

Perhaps there is already a way of doing this? Or we could have something like `type-string`? 

Otherwise I can create something like a `TypeDescriptor` seen in other languages, but I'd rather not:

```php
/**
 * @template T
 */
class TypeDescriptor
{
    /**
     * @param class-string<T1>
     * @return TypeDescriptor<T1>
     */
    static function ofClass(string $class) { ... }

    /**
     * @return TypeDescriptor<string>
     */
    static function string() { ... }

    /**
     * @return TypeDescriptor<int>
     */
    static function int() { ... }
}

/**
 * @template E
 */
class Collection
{
    /**
     * @param TypeDescriptor<E>
     */
    function __construct(TypeDescriptor $type): self {}
}
```

**Comment by muglug** [comment]
Would `type-string` just allow the values of `gettype`?

**Comment by joshdifabio** [comment]
It's probably more complex than I realise, but I was thinking it would also permit class names. So I could pass `SomeClass` or `int` as a `type-string`.

**Comment by muglug** [comment]
I think you can just use `/** @var Collection<string> */` above the assignment, right?

If/when PHP gets generics, there'd presumably a constructor like `new Collection<string>()`

**Comment by joshdifabio** [comment]
@muglug I was trying to avoid an intermediate assignment, but you're right, it would be better to do it that way. Thanks for your help, I'm gonna close.
