### ISSUE TITLE
Behavior of multiple errorLevels for one rule should not depend on order

### ISSUE THREAD

**Issue by nickyr** [vimeo/psalm#159]
Putting this in your psalm.xml will suppress all MissingPropertyType errors in src except for those in src/Foo:

```xml
<MissingPropertyType errorLevel="info">
  <errorLevel type="error">
    <directory name="src/Foo" />
  </errorLevel>
  <errorLevel type="suppress">
    <directory name="src/" />
  </errorLevel>
</MissingPropertyType>
```

However, if you switch the order of the errorLevels, it will just suppress them all: 

```xml
<MissingPropertyType errorLevel="info">
  <errorLevel type="suppress">
    <directory name="src/" />
  </errorLevel>
  <errorLevel type="error">
    <directory name="src/Foo" />
  </errorLevel>
</MissingPropertyType>
```

I think a more natural behavior would be to always use the most specific rule. If two rules are equally specific, an error should be thrown. You don't want to think something is getting checked that actually isn't.

**Comment by muglug** [comment]
I think this edge-casey enough that it's not worth implementing, sorry.
