### ISSUE TITLE
Class property accepts generic instance with unmatching template types

### ISSUE THREAD

**Issue by arnaud-lb** [vimeo/psalm#1590]
In the code at https://psalm.dev/r/764a5d7b48, a value that is inferred to be an `Collection<empty,empty>` is assigned without warnings to a property accepting a `Collection<int,DateTime>`. During the executing of the constructor, the property is also inferred to be a `Collection<empty,empty>`, as shown by the error.

What may be expected instead:
 - The assignment of a `Collection<empty,empty>` to a property of type `Collection<int,DateTime>` shouldn't be allowed
- Ideally, `new ArrayCollection()` should be inferred to be a `Collection<int,DateTime>` in this case. It's currently inferred as a `Collection<empty,empty>` because the constructor argument has a default value; however this value is an empty array

**Comment by muglug** [comment]
The original need for empty arrays comes from here:

```php
class A {
  /** @var array<int, int> */
  public $foo = [1, 2, 3];

  public function empty() {
    $this->foo = []; // this should be allowed
  }
}
```

but I agree that generic objects probably shouldn't have the same behaviour

**Comment by arnaud-lb** [comment]
Thanks !

**Comment by jaikdean** [comment]
What should we be doing instead in these cases? We have a very similar situation, and are now getting `InvalidPropertyAssignmentValue` errors with the latest version of Psalm.

What's the best way to stop this example throwing an error? https://psalm.dev/r/fadb9a2e76

**Comment by arnaud-lb** [comment]
Something like this would work: https://psalm.dev/r/f24763a004

However, it would be awesome if psalm could infer the types, in the presence of an empty array :)

**Comment by muglug** [comment]
@jaikdean you should just put a `@var` docblock about the assignment being complained about.

This is a current weakness of PHP, given it lacks support for generics at the language level (in other languages you might write `new ArrayCollection<int, DateTime>()`

**Comment by jaikdean** [comment]
Thanks. I can add a docblock like `/** @var ArrayCollection<int, DateTime> $this->c */` and it resolves Psalm's issues. However, PHP-CS-Fixer doesn't recognise this as a valid docblock (I think because it contains `$this->`?) and "fixes" it to `/* @var ArrayCollection<int, DateTime> $this->c */`, which Psalm then ignores.

Is this purely a problem with PHP-CS-Fixer?

**Comment by andrew-demb** [comment]
@jaikdean, I emitted the same behavior for php-cs-fixer. It's fixer issue.

**Comment by muglug** [comment]
@arnaud-lb @jaikdean this was fixed in https://github.com/vimeo/psalm/pull/1662

**Comment by muglug** [comment]
btw @jaikdean Psalm doesn't require `$this->c` in the `@var` docblock above assignments - it assumes the expression to the left of the `=` is the one getting assigned a value.

**Comment by muglug** [comment]
The behaviour is now much-improved – no `@var` docblock is necessary, as Psalm now steals a property's generic params if none could be inferred: https://psalm.dev/r/3426fdf676
