### ISSUE TITLE
possibly erroneous PropertyTypeCoercion in loop that excludes unacceptable values

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1591]
Looping over `array<int, string>` to toggle only named values on `array{from:bool, to:bool}` now results in a `PropertyTypeCoercion`, even if only valid values are available at the time the property is modified.

* using dcfe9bf
* https://psalm.dev/r/904c3b243c

```php
<?php declare(strict_types=1);

class Foo {
  /**
  * @var array{from:bool, to:bool}
  */
  protected $things = ['from' => false, 'to' => false];
  
  public function ToggleWithoutWorkaround(string ...$things) : void {
    foreach ($things as $thing) {
      if ('from' !== $thing && 'to' !== $thing) {
        continue;
      }
      
      $this->things[$thing] = !$this->things[$thing];
    }
  }
  
  public function ToggleWithWorkaround(string ...$things) : void {
    foreach ($things as $thing) {
      if ('from' !== $thing && 'to' !== $thing) {
        continue;
      }
      
      /**
      * @var 'from'|'to'
      */
      $thing = $thing;
      
      $this->things[$thing] = !$this->things[$thing];
    }
  }
}
```

> Psalm output (using commit dcfe9bf): 
> 
> ERROR: PropertyTypeCoercion - 15:7 - $this->things expects 'array{from:bool, to:bool}', parent type 'non-empty-array<string, bool>' provided

**Comment by muglug** [comment]
So this works: https://psalm.dev/r/796e496be9

seems `'from' !== $thing` and `$thing !== 'from'` are treated differently
