### ISSUE TITLE
InvalidReturnType in terminating function

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#1592]
This results in an error:

```php
<?php

interface Foo
{
    public function doFoo(): int;
}

class Bar implements Foo
{
    public function doFoo(): int
    {
        print "Error\n";
        exit(1);
    }
}
```

> InvalidReturnType - 10:27 - No return statements were found for method Bar::doFoo but return type 'int' was expected

https://psalm.dev/r/889ef4b380

While this does not:

```php
<?php

interface Foo
{
    public function doFoo(): int;
}

class Bar implements Foo
{
    public function doFoo(): int
    {
        throw new \Exception('Error');
    }
}
```

https://psalm.dev/r/ed5b75ad71

**Comment by muglug** [comment]
Yeah, this is inconsistent - both should have `/** @return no-return */`

**Comment by iluuu1994** [comment]
Thanks 👍
