### ISSUE TITLE
[PropertyNotSetInConstructor] Working with frameworks

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#1594]
This is a rather common pattern in frameworks:

```php
<?php

// --- Symfony

interface Container {}

abstract class AbstractController
{
  /** @var Container */
  protected $container;

  public function setContainer(ContainerInterface $container)
  {
    $this->container = $container;
  }
}

// --- Application

class UserController extends AbstractController
{
  public function __construct()
  {
  }
}
```

> ERROR: PropertyNotSetInConstructor - 15:7 - Property AbstractController::$container is not defined in constructor of UserController or in any methods called in the constructor

https://psalm.dev/r/587733a07e

So instead of injecting the dependency in the constructor the DI framework calls the setter. This makes it easier to extend the class and inject your own dependencies.

Now, I totally get why this error is thrown and it's pretty cool that Psalm catches this. But since this is such a common pattern I'd have to ignore this all over the place. I can't think of a concrete solution though, any suggestions?

**Comment by iluuu1994** [comment]
Actually, this can be ignored pretty easily:

```xml
<PropertyNotSetInConstructor>
  <errorLevel type="suppress">
    <referencedProperty name="Symfony\Bundle\FrameworkBundle\Controller\AbstractController::$container"/>
  </errorLevel>
</PropertyNotSetInConstructor>
```

I'd still like to hear any suggestions 🙂

**Comment by iluuu1994** [comment]
Actually, the ignoring worked pretty well so I don't think anything is necessary here.

**Comment by Arkemlar** [comment]
Worth mentioning that the xml code snippet above must be placed under xml path `psalm > issueHandlers > PropertyNotSetInConstructor`
