### ISSUE TITLE
issue with getters & setters backed by template-annotated array, and `@property` inference

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1607]
* using ecb7a6c
* https://psalm.dev/r/92f2a9d77e

```php
<?php

/**
* @template DATA as array<string, scalar|array|object|null>
*/
abstract class Foo {
  /**
  * @var DATA
  */
  protected $data;
  
  /**
  * @param DATA $data
  */
  public function __construct(array $data) {
    $this->data = $data;
  }
  
  /**
  * @return scalar|array|object|null
  */
  public function __get(string $property) {
    return $this->data[$property] ?? null;
  }
  
  /**
  * @param scalar|array|object|null $value
  */
  public function __set(string $property, $value) {
    $this->data[$property] = $value;
  }
}

/**
* @template-extends Foo<array{a:int, b:float, c:null, d:DateTimeInterface}>
*/
class Bar extends Foo {
  
}

$baz = new Bar(['a' => 1]); // expected because Baz<DATA> has non-optional keys
$baz = new Bar(['a' => 1, 'b' => 2.3, 'c' => null, 'd' => new DateTime()]);

echo number_format($baz->b, 2);
```
> Psalm output (using commit ecb7a6c): 
> 
> ERROR: InvalidArgument - 41:16 - Argument 1 of Bar::__construct expects `array{a:int, b:float, c:null, d:DateTimeInterface}`, `array{a:int(1)}` provided

Working as expected, as `Baz<DATA>` template describes non-optional keys.

> 
> INFO: MixedArgument - 44:20 - Argument 1 of number_format cannot be `mixed`, expecting `float|int`

related to the "p.s." of `@property` inference if `__get()` and `__set()` are backed by an array docblock such as `array{a:int, b:float, c:null, d:DateTimeInterface}`

> 
> INFO: UnusedVariable - 41:1 - Variable `$baz` is never referenced

Working as expected, outside the scope of this issue.

> 
> INFO: MixedReturnStatement - 23:12 - Could not infer a return type

Even if `@param 'a'|'b'|'c'|'d' $property` is included, this error still bubbles up; That `Foo::$data` and `Baz::$data` have known types that fail into a null coalescing operator.

> 
> INFO: MixedInferredReturnType - 20:13 - Could not verify return type` 'array<array-key, mixed>|scalar|object|null'` for `Foo::__get`

Direct consequence of the above `MixedReturnStatement` issue.

> 
> ERROR: MixedArrayAssignment - 30:5 - Cannot access array value on mixed variable `$this->data[$property]`

`$property` should be known as string here, so I'm only guessing that the `@template DATA as array<string, scalar|array|object|null>` template is failing to apply?

**Comment by muglug** [comment]
There's no `@property` in your example

**Comment by SignpostMarv** [comment]
> There's no `@property` in your example

That's intentional- the *inference* of `@property` is secondary to the initial issue; That a null coalescence of array value retrieval results in an unknown type when the type of the array is specified via a template tag.

**Comment by SignpostMarv** [comment]
> That a null coalescence of array value retrieval results in an unknown type when the type of the array is specified via a template tag

If the array isn't templated, the getter behaves as expected but the setter falls over: https://psalm.dev/r/f04c98d29a

**Comment by muglug** [comment]
I think this is fixed? Now the only errors are valid ones, as far as I can see.
