### ISSUE TITLE
Unable to suppress issue for TooManyArguments by referencedFunction

### ISSUE THREAD

**Issue by andrew-demb** [vimeo/psalm#1608]
I tried to use suppress by config, but psalm isn't suppressing any issues.

Version: 3.2.10

```xml
<psalm>
<!-- ... -->
    <issueHandlers>
        <TooManyArguments>
            <errorLevel type="suppress">
                <referencedFunction name="ReferencedClass::referencedMethod"/>
            </errorLevel> 
        </TooManyArguments>
    </issueHandlers>
<!-- ... -->
</psalm>

```

**Comment by andrew-demb** [comment]
After some investigating I found, that psalm do not respect any config error level customization except "info"

https://github.com/vimeo/psalm/blob/b9bece4cbcb3f342c8412618f73ca02db98064e8/src/Psalm/IssueBuffer.php#L222

**Comment by muglug** [comment]
Is this still broken on master? I revamped this on Friday

**Comment by andrew-demb** [comment]
Looks like in master working correctly.
