### ISSUE TITLE
Declaring dynamic object-like-array as a return type

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1611]
Is there a reason for the return type to be generalized to `non-empty-array<K as string, V as mixed>` here?
https://psalm.dev/r/421578e4cf

```
/**
 * @template K as string
 * @template V
 * @param K $a
 * @param V $b
 * @return array{K:V}
 */
function f(string $a, $b): array {
    return [$a => $b];
}
```

In other words, is there a way to return an object-like-array with a dynamic structure without losing information about this structure?

**Comment by muglug** [comment]
`ObjectLike` currently just stores an associative array of offset => type. The offsets are just ints or strings, so cannot be templated.

The workaround is to store both property type and value type, but it'll inevitably use more memory.

**Comment by muglug** [comment]
Actually I'm not going to fix this - it doesn't work in Hack, and I think it's very edge-casey.

**Comment by vasily-kartashov** [comment]
@muglug Please reconsider. At the moment this is the only place when generation of new types from simpler types breaks down. Here's an example of how it could look like

https://github.com/hamlet-framework/type

```
assert(_union(_int(), _null())->matches($x));
// here psalm will know that $x is int|null, 
// and there will be an assertion if the actual type doesn't match at runtime
```

compare it to the "standard" solution at the moment
```
/** @var int|null $a */
// no runtime check here
``` 
where there's no runtime check and a potential type error can propagate further.

Up until this point, the template language of psalm has been sufficient for me to combine types to produce other types, with an exception of object-like-array. I can imagine that object-like-array isn't a particularly nice type to deal with but it's everywhere, including `mysql_fetch`, GraphQL params, or PSR7 `getQueryParams` / `getParsedBody` to name the few.

**Comment by muglug** [comment]
Very happy to accept a PR - you’d need to slightly change `ObjectLike` to suit, but from the small sketch of the idea I wrote earlier, I don’t think there’s much that’d need to change. Template stuff would be slightly challenging, maybe, but it’d also help understand how Psalm handles it under the hood (and I’m happy to make changes if you see things that look horrendous).

**Comment by vasily-kartashov** [comment]
There's one aspect of this I wasn't quite aware of before: this signature is only valid for bound values of `K`. In other words:

```
f('a', 1); // valid signature, indeed returns array{a:1}
f('a', $y); // valid signature, the method returns array{a:V}
f($x, 22); // invalid signature, the method actually returns array<K,V>
```

Does it sound to hairy for your liking?
