### ISSUE TITLE
Invalid MethodSignatureMismatch with Serializable interface

### ISSUE THREAD

**Issue by ajgarlag** [vimeo/psalm#1612]
If I write a valid Serializable implementation, psalm throws a `MethodSignatureMismatch`:

- Psalm output with errors: https://psalm.dev/r/62b34c2a9d
- 3v4l.org output without errors: https://3v4l.org/kniqU

To avoid the psalm error, I must write invalid PHP code:

- Psalm output without errors: https://psalm.dev/r/aff7557ea4
- 3v4l.org output with errors: https://3v4l.org/OE2TF

**Comment by weirdan** [comment]
You can get around this with a docblock: https://psalm.dev/r/690051948e

**Comment by ajgarlag** [comment]
Thanks!
