### ISSUE TITLE
Is it possible to add attributes like ‘allowFileIncludes=`false`, totallyTyped=`true`’ to be effective only on a specific folder in the project? If so, can you share an example?

### ISSUE THREAD

**Issue by sharan1** [vimeo/psalm#1613]

**Comment by andrew-demb** [comment]
No, you can't for now.

You can try to use separated configs: base (with `totallyTyped: false, allowFileIncludes: true`), and specific (with `totallyTyped: true, allowFileIncludes: false`).

**Comment by sharan1** [comment]
Can we use multiple psalm config files for different folders in a single repo?

**Comment by muglug** [comment]
Yeah, you'd just have to specify the config with `--config=...`. It means running Psalm will be slower (as you'll have to run it once for each config).

I'd happily accept a PR for turning on `totallyTyped` on a per-folder basis in `<projectFiles>`. At Vimeo we have `totallyTyped` turned on globally, but suppress the various issues it generates in _most_ of the codebase.

`allowFileIncludes` was added to avoid potential code execution on https://psalm.dev, but I'd also welcome a PR to make it a per-folder thing.

**Comment by sharan1** [comment]
is there a developer's guide for psalm somewhere?

Also, is there a PR I can follow related to this change? I would be happy to make a PR for this.

**Comment by muglug** [comment]
There’s https://github.com/vimeo/psalm/blob/master/docs/how_psalm_works.md, but it’s not too helpful for config changes. If I were you I’d start by grepping `totallyTyped`, and following that thread. `Psalm\Config` handles parsing of things, and delegates to a few other classes. Let me know if you have more questions!
