### ISSUE TITLE
Allow generating output in checkstyle format with only issues of severity "errors"

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#1617]
The `--show-info` option only controls output to STDOUT. Currently it's not possible to generate a checkstyle XML file with only errors.

As suggested in https://github.com/vimeo/psalm/issues/1616#issuecomment-490659278, it would be nice to have an option like `--report-level=error` to achieve the above.

**Comment by muglug** [comment]
It's going to work with `--report-show-info=false`
