### ISSUE TITLE
Suspicious unused variable in src/Psalm/Internal/Codebase/Methods.php

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#1625]
In https://github.com/vimeo/psalm/blob/d4f1a4a75f82c52792f65a79012671fac890b9f4/src/Psalm/Internal/Codebase/Methods.php#L462-L469 (master)

```
                foreach ($atomic_type->type_params as $type_param) {
                    $type_param = self::localizeParamType(
                        $codebase,
                        $type_param,
                        $appearing_fq_class_name,
                        $base_fq_class_name
                    );
                }
```

This should instead be one of the following:

1. `as &$type_param` if the intent was to modify the array by reference
2. `$i => $type_param` and `$atomic_type->type_params[$i] = self::localizeParamType...` if the intent was to reassign to an index of atomic_type->type_params (equivalent but doesn't leave a reference around)

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/a3a208a7c919d2b60708f24923f8a89b72ec83bf, with the underlying cause fixed in https://github.com/vimeo/psalm/commit/7c2fe5344699ed1a67674f580908eca178804177
