### ISSUE TITLE
Checkstyle XML reports character encoding issue

### ISSUE THREAD

**Issue by ArtemGoutsoul** [vimeo/psalm#1639]
Seems like current escaping generates some entities that are not acceptable for XML, e.g. \&ldquo;, \&rdquo;, \&auml;,\&ouml;, possibly others.

Maybe this helps somewhat?
https://stackoverflow.com/questions/2822774/php-is-htmlentities-sufficient-for-creating-xml-safe-values

**Comment by muglug** [comment]
Thanks - you're also welcome to open a PR next time!
