### ISSUE TITLE
Documentation is not easily google-able

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1642]
A google search such as https://www.google.com/search?q=%22Psalm+uses+an+XML+config+file%22 only gives me one result, namely https://github.com/vimeo/psalm/blob/master/docs/configuration.md

It does not give the result I would like, which is https://psalm.dev/docs/configuration/

I think this might be because that page has a tag **`<link rel="canonical" href="https://getpsalm.org/configuration/">`**, and https://getpsalm.org/configuration/ returns a 302 redirect to https://psalm.dev/configuration/, which returns a 404.

**Comment by muglug** [comment]
Ah, thanks for the heads-up - I had no idea. Fixed in https://github.com/psalm/psalm.dev

**Comment by bdsl** [comment]
@muglug The linked google search result page still only has the github.com entry. I don't know why it isn't showing the psalm.dev entry. You might want to take a look in Google Search Console.

**Comment by muglug** [comment]
Thanks - it'll take a few days for me to figure out what's up

**Comment by bdsl** [comment]
Actually that page is in Google's cache from 14 may, i.e. before [your fix ](https://github.com/vimeo/psalm/issues/1642#issuecomment-492868497) made on 16 may. So maybe we just need to wait a few more days for google to index psalm.dev
