### ISSUE TITLE
I don't think psalm understands the elvis operator

### ISSUE THREAD

**Issue by hexmode** [vimeo/psalm#1643]
From https://psalm.dev/r/fb37411946

```
ERROR: PossiblyInvalidPropertyAssignmentValue - 7:32 - $this->branchedExtensions with declared type 'array<array-key, mixed>' cannot be assigned possibly different type 'array<empty, empty>|true'
```

**Comment by muglug** [comment]
On the contrary, I'm not sure you do.

Try this in 3v4l.org, in `git-php-7.4`:

```php
class test {
    public array $branchedExtensions;
	function __construct( array $branchLists ) {
	  $this->branchedExtensions = isset( $branchLists['extensions'] ) ?: [];
	}
}

new test(['extensions' => 1]);
```

It produces output

```
Fatal error: Uncaught TypeError: Typed property test::$branchedExtensions must be array, bool used
```

**Comment by muglug** [comment]
I think you mean to write 

```php
$this->branchedExtensions = $branchLists['extensions'] ?? [];
```

**Comment by muglug** [comment]
Sorry, I've edited my response because it was a little cheeky.

**Comment by hexmode** [comment]
I'm pretty sure that I meant `?:` but you may be right.  (I'm too exhausted to look right now.  I've been waiting 3 hours for a delayed flight and just found it was delayed AGAIN.)

**Comment by muglug** [comment]
`$a ?: $b` is just short for `$a ? $a : $b`

so `isset(...) ?: []`

is the same as `($a = isset(...)) ? $a : []`

which boils down to `isset(...) ? true : []`

Sorry about the delayed flight. Flying sucks.

**Comment by hexmode** [comment]
After some sleep, I realized that isset() was wrong here.  I wanted:
```
$this->branchedExtensions = $branchLists['extensions'] ?: [];
```
But this can result in an E_NOTICE which I was trying to use the `isset()` to avoid.  For example:
```
$ php -r 'var_dump( $x ?: true );'
PHP Notice:  Undefined variable: x in Command line code on line 1
bool(true)
```

I think I can avoid the undef notice in my code, but this seems like another bit of [PHP Sadness]
(http://phpsadness.com/).

**Comment by muglug** [comment]
I think you want the `??` operator, which was added for this explicit purpose.

**Comment by hexmode** [comment]
> I think you want the `??` operator, which was added for this explicit purpose.

Sorry, you're right, I just re-reviewed [the docs](https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce).  I'm just a little dense.
