### ISSUE TITLE
Cacheing issue with 3.2.12

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1646]
Affects the latest version only. When I modify files, everything works as intended the first time. On consecutive runs it seems that psalm forgets about functions located outside of classes.

**Comment by muglug** [comment]
Sorry about that - are you able to reproduce in a self-contained repo?

**Comment by vasily-kartashov** [comment]
master @ https://github.com/hamlet-framework/type

**Comment by muglug** [comment]
Thanks!
