### ISSUE TITLE
On the homepage please name the filename of the XML config

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#1648]
The doc says:

> Psalm uses an XML config file. A barebones example looks like this:

Please change to

> Psalm uses an XML config file called `psalm.xml`. A barebones example looks like this:

Link: https://psalm.dev/docs/configuration/

**Comment by iluuu1994** [comment]
Technically doesn't have to, you can specify any file you want using `psalm --config=xyz.xml`

**Comment by olleharstedt** [comment]
OK. Well, then say that? My `--init` failed, and I didn't know what XML file Psalm was looking for.

**Comment by muglug** [comment]
How did your `--init` fail?

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/e75ee779384bf139f1d996a47fb86861de7e1c75

**Comment by olleharstedt** [comment]
Many thanks!

> How did your --init fail?

I'm not sure, my shell was broken and I couldn't event copy the error message. Starting a new terminal solved it.
