### ISSUE TITLE
Drop support of PHP 7.0?

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#1650]
Hi,

I was preparing a PR to update phpmyadmin/sql-parser to the latest version (5.0.0) because it includes the fix for #1542.

phpmyadmin/sql-parser now requires to use at least PHP 7.1. Psalm still supports PHP 7.0.

PHP 7.0 being no longer supported since January, is there a reason for Psalm to keep supporting it or can I go ahead and propose a PR to drop it?

**Comment by muglug** [comment]
I have a branch with the change: https://github.com/vimeo/psalm/compare/php-71 (it also updates PHPUnit).

Dropping PHP 7.0 would be a backwards-incompatible change, but one that would presumably be handled by Composer, so I think I could just tag with `3.3` and call it a day.

**Comment by LeSuisse** [comment]
Nice!

Yep Composer handles that just fine (if `--ignore-platform-reqs` is not used of course). Bumping the minimal requirement to 7.1 [is a conservative choice](https://github.com/Ocramius/ProxyManager/issues/455) so I'm guessing it's not going to bother a lot of users.
