### ISSUE TITLE
LSP Completion: Error when encountering variable whose types is a templatised class

### ISSUE THREAD

**Issue by joshdifabio** [vimeo/psalm#1654]
During LSP completion requests, when the type of a variable is inferred to be some templatised class, this results in a class storage error. E.g. 

`Could not get class storage for Optional\Optional<Some\Other\Class>`

This is happening because `Psalm\Codebase::getCompletionDataAtPosition()` is returning a type like `Optional\Optional<Some\Other\Class>` which `Psalm\Internal\LanguageServer\Server\TextDocument` [is then passing to `ClassLikeStorageProvider::get()`](https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/LanguageServer/Server/TextDocument.php#L271).

I guess something should be stripping out the template types but I don't know how or where this should happen.

**Comment by muglug** [comment]
Thanks!
