### ISSUE TITLE
LSP Completion: Completion fails for chained method calls 

### ISSUE THREAD

**Issue by joshdifabio** [vimeo/psalm#1656]
Completion requests do not work for chained function calls due to `Psalm\Internal\Codebase\Analyzer` returning incorrect offsets for function calls.

For example:

```
$foo->bar()->
             ^ LSP client sends a completion request to Psalm at this offset (13)
```

In this scenario, `Codebase::getCompletionDataAtPosition()` calls `Analyzer::getMapsForFile()` which returns a `type_map` for the file being edited. This `type_map` includes the return type of the `$foo->bar()` call, but the type has start offset 6 and end offset 9, while the completion is looking for a type at offset 11. It seems like the offset of the type in the `type_map` should be defined by the offset of the closing paren of the function call, which is 11, rather than the end of the function name as it is currently.

**Comment by muglug** [comment]
Would you be able to reproduce in https://github.com/vimeo/psalm/blob/master/tests/LanguageServer/CompletionTest.php?

**Comment by joshdifabio** [comment]
I'll have a go :)

**Comment by joshdifabio** [comment]
Here you go.

https://github.com/joshdifabio/psalm/commit/2107698f262087973d2aa8478e7441272f09925e

**Comment by muglug** [comment]
Thanks!

**Comment by joshdifabio** [comment]
Thanks, Matt. Completion is working seriously well in VS Code now!
