### ISSUE TITLE
Interface support for class-string type

### ISSUE THREAD

**Issue by thiagorb** [vimeo/psalm#1657]
It is currently possible to use `class-string` as a type, and the assertion with the function call `class_exists` works like a charm.

Using it with interfaces is not so straightforward though. The `ReflectionClass` constructor accepts a `class-string`, but it is also possible to pass an interface name to it.

Consider the following code:
```
<?php

/**
 * @psalm-param class-string $className
 */
function funA(string $className): ReflectionClass
{
    return new ReflectionClass($className);
}

function funB(string $className)
{
    if (class_exists($className)) {
        return funA($className);
    }

    if (interface_exists($className)) {
        return funA($className);
    }
}
```

In this case, psalm will raise an error saying that I'm passing a `string` where a `class-string` was expected, after the `interface_exists` check.

If I add the `class-string` type to `$className` of `funB` psalm will say `class_exists($className)` is a redundant condition.

I believe that making all interfaces to be considered valid `class-string` values would end up being too generic, but it would be nice to have a sort of hierarchy then, like `type-string`, `interface-string` and `class-string`, where both `interface-string` and `class-string` values could be assigned to a `type-string` variable/parameter/return.

**Comment by bdsl** [comment]
I think it would be more useful to say that the concept of 'class' for the purposes of `class-string` includes interfaces as well as classes.

The [docs say](https://psalm.dev/docs/docblock_type_syntax/) that class-string is used "_to tell Psalm make sure that the function is always called with a ::class constant in that position_". `:class` is valid for interfaces in PHP just as it is for classes, and \ReflectionClass has an [isInterface](https://www.php.net/manual/en/reflectionclass.isinterface.php) function.

I think a solution to prevent the error in the code shown, is to create a `hasInterfaceExistsCheck` function, and change `elseif (self::hasClassExistsCheck($expr))` to `elseif (self::hasClassExistsCheck($expr) || self::hasInterfaceExistsCheck($expr))` in the [AssertionFinder](https://github.com/vimeo/psalm/blob/ae531506de5eba8beb8afbbd3a5b379faadcec85/src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php#L1667).

**Comment by thiagorb** [comment]
Hey @bdsl! I thought about this at first, but I was afraid that information could be lost by using this approach. Making `class-type` accept interfaces would make it impossible to point out errors using `new $interfaceString` for example.

**Comment by bdsl** [comment]
Hey @thiagorb . It's true that `new $interfaceString`, will fail, but so will `new $abstractClass`, `new $classWithConstructorWithRequiredParam`, and `new $classWithNonPublicConstructor`.

I'm not sure there's much value in something that can prevent the first failure but not the others. What sort of mistakes would it typically catch?

**Comment by muglug** [comment]
Yeah, I don't think there's an easy answer for this - `class-string<SomeAbstractClass>` allows `SomeAbstractClass::class` and any classes that extend `SomeAbstractClass` - hard to detect problems.

The documentation should be updated to make clear that `class-string` can represent an interface, and `interface_exists` should also result in a `class-string`-making assertion.

**Comment by orklah** [comment]
Related to https://github.com/vimeo/psalm/pull/6106
