### ISSUE TITLE
Cant access https://psalm.dev/ website

### ISSUE THREAD

**Issue by funivan** [vimeo/psalm#1659]
Browser:  Chromium 73
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu 
Chromium/73.0.3683.86 Chrome/73.0.3683.86 Safari/537.36
```
```
Attackers might be trying to steal your information from psalm.dev
(for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
```
![07:29:05](https://user-images.githubusercontent.com/425208/58068475-26f0b500-7b9a-11e9-9205-2536799202e4.png)

**Comment by muglug** [comment]
You very likely have some software on your computer or local network that redirects `*.dev` domains.

Does https://google.dev load for you?

**Comment by funivan** [comment]
Thanks @muglug  
This is probably a bug on my side. I also can't access google.dev
