### ISSUE TITLE
Psalm doesn't process require_once once

### ISSUE THREAD

**Issue by jdwx** [vimeo/psalm#166]
Given two files, One.php:

```
require_once __DIR__ . '/Two.php';
```

and Two.php:

```
require_once __DIR__ . '/One.php';
```

Psalm bounces between the two files in an infinite loop and eventually dies:

```
$ psalm One.php

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in /data/phplib/vendor/vimeo/psalm/src/Psalm/Provider/CacheProvider.php on line 53
```

The same issue occurs if require_once is changed to include_once.

It seems like it's the ```__DIR__``` special variable that's throwing it off.  Changing these to './One.php' or even './' . 'One.php' allows psalm to run without issue.  (But the . has a different meaning than ```__DIR__```.)

Thanks!

**Comment by muglug** [comment]
I'm able to reproduce in a test https://github.com/vimeo/psalm/blob/b79b9e9b8cef4ee337db527c1b215c8238897801/tests/IncludeTest.php#L137

Will have a fix tonight, hopefully

**Comment by jdwx** [comment]
Alas I don't think this issue is completely resolved.  Although the provided test now seems OK, our actual codebase generates the same error with the latest code, albeit moved by one line:

```
$ psalm

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in /data/build/phpcf/vendor/vimeo/psalm/src/Psalm/Provider/CacheProvider.php on line 54
```

Here's a slight tweak to the example that re-exhibits the problem:

One.php:
```
<?php
require_once './Two.php';
require_once __DIR__ . '/Three.php';
```

Two.php:
```
<?php
require_once './Three.php';
```

Three.php:
```
<?php
require_once './One.php';
```

Unlike our production code, this produces a lot of output, but it does appear to be stuck in an infinite loop and eventually runs out of memory.

```
$ psalm One.php
Warning: file_get_contents(/tmp/psalmo/./././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././ in /data/phplib/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php on line 1119
(... repeated lots of times ...)
Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 262144 bytes) in /data/phplib/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php on line 164
```

(It looks like the actual warning is getting truncated.)

The key features of this example are:
1) As before, there's a loop of require_once files.
2) Three.php is referred to by two different paths.

Thanks!
