### ISSUE TITLE
query re: array-key

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1660]
Since the introduction of the pseudo-type in #1144, I've only really come across it in logging output, so I'm wondering if there's utility in stating (via templates) that a given parameter is the array-key of a given array, without having to manually flesh out the list of keys

* https://psalm.dev/r/6157df36c6

```php
<?php
/**
* @template T as array
*/
abstract class Foo {
  /**
  * @var T
  */
  protected $data;
  
  /**
  * @param T $data
  */
  public function __construct(array $data) {
    $this->data = $data;
  }
  
  /**
  * @param array-key<T> $k
  */
  public function __get(string $k) {
    return $this->data[$k];
  }
  
  /**
  * @param array-key<T> $k
  */
  public function __isset(string $k) {
    return true;
  }
}

/**
* @template-extends Foo<array{x:float, y:float, z:float}>
*/
class Bar extends Foo {
}
```

**Comment by SignpostMarv** [comment]
p.s. I'm also wondering if it makes sense to have `array-value`, i.e.

```php
    /**
    * @param array-key<T> $k
    * @param array-value<$k> $v
    */
    function __set(string $k, $v) {
    }
```

in order to ensure that $v only accepts types that are accepted on key $k of the templated array.

**Comment by weirdan** [comment]
There's some value in type operators like `key-of` or `value-of`, but your case is already (mostly) possible to cover with two-param template: https://psalm.dev/r/b3389aa929

**Comment by muglug** [comment]
Yeah I think this would be covered by https://github.com/vimeo/psalm/issues/762
