### ISSUE TITLE
array<empty, empty> not picked up in a class-string/templated edge-case

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1667]
* https://psalm.dev/r/a5a74d7cf0
* using 7601921

```php
<?php
/**
* @param array<empty, empty> $bar
*/
function foo(array $bar) : string { return (string) count($bar); }

foo(['a' => 1]); // errors as expected

/**
* @template T as array<string, scalar|array|object|null>
*/
abstract class Bar {
  /**
  * @param T $bar
  */
  function foo(array $bar) : string { return (string) count($bar); }
  
  /**
  * @return class-string<Bar<T>>
  */
  final public static function Factory() : string
  {    
    return Baz::class;
  }
}

/**
* @template-extends Bar<array<empty, empty>>
*/
class Baz extends Bar{}

$type= Bar::Factory();

$a = new $type();
$a->foo(['a' => 1]);

$b = new Baz();
$b->foo(['b' => 2]);
```
> Psalm output (using commit 7601921): 
>
> ERROR: InvalidScalarArgument - 7:5 - Argument 1 of foo expects array<empty, empty>, array{a:int(1)} provided
>
> ERROR: InvalidScalarArgument - 38:9 - Argument 1 of Baz::foo expects array<empty, empty>, array{b:int(2)} provided

both `foo(['a' => 1]);` and `$b->foo(['b' => 2]);` trigger errors as expected, but `$a->foo(['a' => 1]);` does not unless the variable is docblocked with the appropriate type- which is impractical to know at coding time if the result of `Bar::Factory()` refers to classes built with nikic/php-parser, i.e. 

```php
$class = $this->factory->class('BakedChangeProxy_' . hash('sha256', $T1));
```

**Comment by muglug** [comment]
I don't know what the bug is here, sorry - Psalm only infers templated types when it's possible so to do. It's impossible in the example you've given.

**Comment by SignpostMarv** [comment]
since I can't use templates on anonymous classes, I'm trying to create a means of generating classes that are pre-baked with the appropriate templates already in place.

The issue seems to be at the moment that even when one assigns & `@var` hints `Baz::class` as `Bar<array<empty, empty>>` that the return hint of `Bar::Factory()` takes precedence & psalm just sees the unrestricted default `array<string, scalar|array|object|null>`.

The idea I'm looking at is the php 7.4 feature set makes large swathes of overly-paranoid type checking code kinda moot if one can just typehint properties directly & splash a bit of `@property-read` in there for readonly properties, but the lack of __get() wrapping makes it harder to automatically determine what properties have been changed for an optimised `UPDATE` sql statement (i.e. if no properties have actually changed despite being written to several times, one can avoid a db hit altogether).

so for the example interface

```php
/**
* @property int $id
* @property string $public_id
* @property bool $require_password_reset
* @property bool $allow_login
* @property string $two_factor_auth_secret
* @property string $username
* @property string $password
*
* @template-extends Type<array{id:int, public_id:string, require_password_reset:bool, allow_login:bool, two_factor_auth_secret:string, username:string, password:string}>
*/
interface AdminUser extends Type
{
}
```

one ends up with a class generated w/ php-parser:

```php
/**
* @template-extends ChangeProxy<Type, array{id?:int, public_id?:string, require_password_reset?:bool, allow_login?:bool, two_factor_auth_secret?:string, username?:string, password?:string}, array<empty, empty>, array{id:int, public_id:string, require_password_reset:bool, allow_login:bool, two_factor_auth_secret:string, username:string, password:string}>
*/
class BakedChangeProxy_8a45d816ec6809ded01e791d1d970d828b5910f61511fafdaeeb358bfd7bda44 extends ChangeProxy
{
}
```

but when returning `BakedChangeProxy_8a45d816ec6809ded01e791d1d970d828b5910f61511fafdaeeb358bfd7bda44::class` (either statically via typhinted switch statement or a dynamically concatenated string), psalm only appears to see the generic `array<string, scalar|array|object|null>` and not something specific to the input type like `array<empty, empty>` (which one gets in my generator if none of the properties are `@property-read`)
