### ISSUE TITLE
Recoverable fatal error: Method Psalm\Type\Union::__toString() must return a string value

### ISSUE THREAD

**Issue by jdwx** [vimeo/psalm#167]
With our codebase, psalm (from commit 1745518c2c6245b4a3f96ae3862e7396dbff974f ) crashes with the following message:

```
Recoverable fatal error: Method Psalm\Type\Union::__toString() must return a string value in /data/phplib/vendor/vimeo/psalm/src/Psalm/Context.php on line 218
```

It's easy enough to work around this:

```
$ git diff Union.php
diff --git a/src/Psalm/Type/Union.php b/src/Psalm/Type/Union.php
index bbdbe5e..069dce2 100644
--- a/src/Psalm/Type/Union.php
+++ b/src/Psalm/Type/Union.php
@@ -74,6 +74,8 @@ class Union
             $s .= $type . '|';
         }

+        if ( ! $s )
+            return '';
         return substr($s, 0, -1);
     }

```

However, it seems likely that this does not fix the issue, it merely hides it.

substr() is defined by PHP to return false if $s is an empty string.  In this case, $this->types is empty when this happens, leading to an empty $s.  An expression with no type at all seems like a deeper-rooted problem.

Unfortunately, I was not able to determine was what in our code was causing this behavior.

Is there some way to poke at this (perhaps from Context::getRedefinedVars(), where the error is getting detected) to get the relevant source file and line number to figure out what's going on and try to come up with a self-contained reproduction?

The $var variable appears to contain the variable name, but in this case it's a very generic name ("$match") that's used in many places in our code and in third-party libraries.  At least it's not $x.

Running psalm with --debug only generates two lines of "Visiting (path).php" before the error, neither of which refer to a file containing a $match variable.

Thanks!

**Comment by muglug** [comment]
I've just pushed https://github.com/vimeo/psalm/commit/90d0d12f6c686e7cdeeb0150a0c724906efe6d58 which prevents XDebug from being disabled, as long as you run with `--debug`. That should give you a call stack – would you be able to enable XDebug and paste that here?

**Comment by morozov** [comment]
@muglug here's how it's reproduced for me with psalm 0.3.46 (a made up example extracted from 10-year-old code):
```php
<?php

function foo($a, $b)
{
    return "$a/$b";
}

function bar()
{
    $array = array();
    foo('a', 'b');

    $x = $array['x'];

    if (isset($array['y']) && $array['y'] != '') {
        foo('c', $array['y']);
    }
}
```
Configuration:
```xml
<?xml version="1.0"?>
<psalm stopOnFirstError="false"/>
```
Output:
```$ psalm --debug test.php
Checking test.php
Visiting test.php
Analyzing test.php
ERROR: MissingReturnType - test.php:3 - Method foo does not have a return type, expecting string
function foo($a, $b)



Catchable fatal error: Method Psalm\Type\Union::__toString() must return a string value in vendor/vimeo/psalm/src/Psalm/Context.php on line 223

Call Stack:
    0.0035     456224   1. {main}() vendor/vimeo/psalm/bin/psalm:0
    0.0856    2202592   2. Psalm\Checker\ProjectChecker->checkFile(???, ???) vendor/vimeo/psalm/bin/psalm:332
    0.1154    4443808   3. Psalm\Checker\FileChecker->analyze(???, ???) vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php:699
    0.1179    4808416   4. Psalm\Checker\FunctionChecker->analyze(???, ???, ???) vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php:277
    0.1179    4808584   5. Psalm\Checker\StatementsChecker->analyze(???, ???, ???, ???) vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php:409
    0.1427   11959328   6. Psalm\Checker\Statements\Block\IfChecker::analyze(???, ???, ???, ???) vendor/vimeo/psalm/src/Psalm/Checker/StatementsChecker.php:123
    0.1458   12154008   7. Psalm\Checker\Statements\Block\IfChecker::analyzeIfBlock(???, ???, ???, ???, ???, ???, ???) vendor/vimeo/psalm/src/Psalm/Checker/Statements/Block/IfChecker.php:183
    0.1467   12196520   8. Psalm\Context->getRedefinedVars(???) vendor/vimeo/psalm/src/Psalm/Checker/Statements/Block/IfChecker.php:341
```

**Comment by muglug** [comment]
Thanks @morozov!

Shorter testcase:

```php
$arr = [];
$x = $arr['x'];
if (isset($arr['x']) && $arr['x'] !== '') { }
```
