### ISSUE TITLE
How do I pass in strictness level when running psalm on the console?

### ISSUE THREAD

**Issue by prondubuisi** [vimeo/psalm#1678]
I am trying to pass in strictness level when working with Psalm on the console, how can I achieve this?

`coolife@coolife:~/git-repos/gsoc$ ./vendor/bin/psalm api 1`
`Cannot locate 1`
`coolife@coolife:~/git-repos/gsoc$ ^C`
`coolife@coolife:~/git-repos/gsoc$ ./vendor/bin/psalm api level=1`
`Cannot locate level=1`
`coolife@coolife:~/git-repos/gsoc$ ./vendor/bin/psalm api `
`Scanning files...`

**Comment by Ocramius** [comment]
@prondubuisi as far as I know, there is no such thing as "strictness level", but rather a level of reporting for issue types (see `psalm.xml` docs)

**Comment by prondubuisi** [comment]
> @prondubuisi as far as I know, there is no such thing as "strictness level", but rather a level of reporting for issue types (see `psalm.xml` docs)

Do you have any links I could go through?

**Comment by Ocramius** [comment]
https://psalm.dev/ has just a few pages: give them a read 👍

**Comment by prondubuisi** [comment]
Running the command below solved this
`./vendor/bin/psalm --init api 1`
where `api` is the name of the directory and `1` is the strictness level
adjust as necessary but remember to delete the `psalm.xml` each time
strictness level ranges from `1 - 8` 1 for most strict and 8 for least strict

**Comment by muglug** [comment]
I may add this as a feature soon - I came from a place where everything wants to be super-custom, but `--init` isn’t necessary for simple projects.

**Comment by prondubuisi** [comment]
> I may add this as a feature soon - I came from a place where everything wants to be super-custom, but `--init` isn’t necessary for simple projects.

Hello @muglug thanks for this. Maybe if you are too busy to implement this future, you can guide me on how to implement this feature. I will be very glad to contribute. I am working with Psalm all summer here https://summerofcode.withgoogle.com/projects/#6100626637848576
