### ISSUE TITLE
Type issues not emitted on function call inside condition

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1684]
Psalm emits `RedundantCondition` at the if condition below, as expected:

```php
<?php

function returnsInt(): int
{
  return 3;
}

$value = returnsInt();

if (is_int($value)){
  echo 'I was always going to echo';
}
```

However if the variable is inlined, Psalm reports no issues:

```php
<?php

function returnsInt(): int
{
  return 3;
}

if (is_int(returnsInt())){
  echo 'I was always going to echo';
}
```

The same thing applies to other code for which psalm would emit issues such as `TypeDoesNotContainType`, `DocblockTypeContradiction`, `RedundantConditionGivenDocblockType` etc if a variable is used.

**Comment by SignpostMarv** [comment]
> However if the variable is inlined, Psalm reports no issues:

neither does this (for completeness):

```php
<?php
if (is_int((function (): int
{
  return 3;
})())){
  echo 'I was always going to echo';
}
```
