### ISSUE TITLE
Traits are not considered in templated types

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#1691]
This is possibly invalid, since traits don't really "mean" anything at runtime, yet it is worth asking:

```php
<?php
  
trait HelloWorldTrait
{
    public function sayHello() : string
    {
        return 'hello world!';
    }
}

/**
 * @psalm-template TraitType of object
 * @psalm-param class-string<TraitType> $className
 * @psalm-return TraitType
 */
function makeConcrete(string $className) : object
{
   return new class() {
     use HelloWorldTrait;
   };
}

echo makeConcrete(HelloWorldTrait::class)->sayHello();
```

https://3v4l.org/28OVj
https://psalm.dev/r/49f665f17a :

```
Psalm output (using commit d51ee03):

INFO: UnusedParam - 16:30 - Param $className is never referenced in this method

ERROR: UndefinedDocblockClass - 23:6 - Docblock-defined class or interface HelloWorldTrait does not exist
```

This is mostly relevant for `PHPUnit\Framework\TestCase#getMockForTrait()`

**Comment by muglug** [comment]
I think this would require a separate `trait-string` type

**Comment by muglug** [comment]
This would also require a reasonably heavy refactoring of how classes are dealt with/methods recognised as valid. I'm gonna say it's probably not worth doing.
