### ISSUE TITLE
PropertyNotSetInConstructor when assigning via parameter object's method directing back to setter

### ISSUE THREAD

**Issue by andrewmy** [vimeo/psalm#1694]
```php
<?php

class Task
{
  /** @var SubTask[] */
  private $subTasks = [];
  
  public function addSubTask(SubTask $subTask): void
  {
    $this->subTasks[] = $subTask;
    $subTask->linkTask($this);
  }
}

class SubTask
{
  /** @var Task */
  private $task;
  
  public function __construct(Task $task)
  {
    $task->addSubTask($this);
  }
  
  public function linkTask(Task $task): void
  {
    $this->task = $task;
  }
}
```

> Psalm output (using commit 442c307): 
> ERROR: PropertyNotSetInConstructor - 18:11 - Property SubTask::$task is not defined in constructor of SubTask or in any methods called in the constructor

See https://psalm.dev/r/6f7912cd53

**Comment by muglug** [comment]
Not going to fix this, as it's way beyond the scope of Psalm's current checks. I'd just suppress it, if I were you.
