### ISSUE TITLE
Memory usage increase between 3.2.12 and 3.3.0

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#1696]
On the same codebase I observe a noticeable memory usage increase and I'm guessing it was not an expected change.

Same command has been used between the 2 versions:
```
$ ~/Workspace/psalm/psalm -c=tests/psalm/psalm.xml --show-info=false --no-cache plugins/tracker/include/Workflow/
```

Profile with Psalm 3.12.0 (peak memory usage 145MB): https://blackfire.io/profiles/b4977a42-4285-4b0f-84a7-b4cf1a57d17f/graph
Profile with Psalm dev-master 9a93525d33a0f2d540fcd8e7af5c70195f6b2127 (peak memory usage 578MB): https://blackfire.io/profiles/fc7f16a2-2b47-43db-8d18-f9c736a0319b/graph

Comparison between the two profiles: https://blackfire.io/profiles/compare/c77a7a37-56bc-42dd-ae1b-12b9f474070e/graph

Issue seems to have been introduced by 0bd4dbcbc48ed6ba06dc35367bfd57c2406f8781.

**Comment by muglug** [comment]
Ah thanks, that commit picked up the remnants of some abandoned work to identify a potential memory leak in tests.
