### ISSUE TITLE
Errouneous InvalidArgument with templated key-of

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1699]
I think the following code is correct, but psalm reports:

 `ERROR: InvalidArgument - 34:16 - Argument 1 of Day::__construct expects string('monday')|string('tuesday')|string('wednesday')|string('thursday')|string('friday'), string(monday) provided`

Note the lack of quotes in `string(monday)`

```php
<?php

/**
 * @template TData as array
 */
abstract class Enum {
  
  /** 
   * @template K as key-of<TData>
   * @param K $value 
   */
  protected $value;
  
  /** 
   * @template K as key-of<TData>
   * @param K $value 
   */
  public function __construct(string $value){
    $this->value = $value;
  }
}

/** 
  * @extends Enum<array{
  *  'monday':null, 
  *  'tuesday':null, 
  *  'wednesday':null, 
  *  'thursday':null, 
  *  'friday':null
  * }> 
  */
class Day extends Enum {}

$foo = new Day('monday');
 ```
https://psalm.dev/r/f7d2a43db9

**Comment by SignpostMarv** [comment]
doesn't appear to be erroneous: string keys don't require quoting: https://psalm.dev/r/3cde15b57c

```php
/** 
  * @extends Enum<array{
  *  monday:null, 
  *  tuesday:null, 
  *  wednesday:null, 
  *  thursday:null, 
  *  friday:null
  * }> 
  */
class Day extends Enum {}

$foo = new Day('monday');
$bar = new Day('yadnom');
```

**Comment by bdsl** [comment]
@SignpostMarv You're quite right, thanks. Perhaps Psalm should have thrown a DocBlockParsingExcedption on my code, but that's a much less serious issue.

**Comment by SignpostMarv** [comment]
@bdsl `'\'monday\''` is a valid string, so it may be preferable to have a psalm plugin that checks for quotes in `array-key`, so the stricter false positives can be added to a baseline file, rather than complicating the config of the core parser ?
