### ISSUE TITLE
EmptyArrayAccess when values has been set through an "indirect" reference

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#1702]
Expected: No EmptyArrayAccess after the conditional isset()

```php
<?php
  
/**
 * @param array{param1: array} $params
 */
function dispatch(array $params) : void {
    $params['param1']['foo'] = 'bar';
}

$ar = [];
dispatch(['param1' => &$ar]);
$value = 'foo';
if (isset($ar[$value])) {
    echo (string) $ar[$value];
}
```
https://psalm.dev/r/dbaf6223d1

**Comment by muglug** [comment]
Why is this bad?

**Comment by weirdan** [comment]
Shouldn't it rather be reported as impossible condition on the `if` line?

**Comment by LeSuisse** [comment]
Yep in this isolated code snippet the `if` line is an impossible condition. My real case is a bit more complex and looks more like this:
```php
<?php
/**
 * @param array{param1: array} $params
 */
function dispatch(array $params) : void {
    $params['param1']['foo'] = 'bar';
}

$ar = [];
dispatch(['param1' => &$ar]);
$value = 'v';
if (isset($ar[$value])) {
    echo (string) $ar[$value];
}
```
https://psalm.dev/r/a693501765

Also, even in the simple test case I think it's a bit strange that annotating the array removes the issue.
```php
<?php

/** @var array */
$ar = [];
$value = 'v';
if (isset($ar[$value])) {
    echo (string) $ar[$value];
}
```
https://psalm.dev/r/640915c412


Both issues might be distinct.

**Comment by muglug** [comment]
Oh your “special case” looks like buggy behaviour on Psalm’s part - I haven’t seen that pattern before, and didn’t know it was possible. Mind updating the ticket?
