### ISSUE TITLE
Erroneous type coercion warning when one intersection type matches

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#1704]
```php
interface I1 {}
interface I2 {}
class A implements I1 {}

/** @param A|I2 $i */
function foo($i) : void {}

/** @param I1&I2 $i */
function bar($i) : void {
  foo($i);
}
```

Expected: no issue
Actual: https://psalm.dev/r/ccfaa9d6d5

**Comment by muglug** [comment]
Not actually a bug

**Comment by weirdan** [comment]
> Not actually a bug

Why? `I1&I2` is `I2` (and `I1`, but that's irrelevant), and `foo()` should accept `I2` (even if it accepts something else as well). Or am I missing something?

**Comment by muglug** [comment]
You’re not, I’m just a little sleep-deprived. I’m in the process of fixing it at the moment
