### ISSUE TITLE
Fatal error when running psalm.phar in project that has vimeo/psalm as a composer dependency

### ISSUE THREAD

**Issue by gjuric** [vimeo/psalm#1705]
PHP Fatal error:  Declaration of _HumbugBoxefd23dc1fea4\Psalm\Internal\Provider\ReturnTypeProvider\ArrayColumnReturnTypeProvider::getFunctionReturnType(_HumbugBoxefd23dc1fea4\Psalm\StatementsSource $statements_source, string $function_id, array $call_args, _HumbugBoxefd23dc1fea4\Psalm\Context $context, _HumbugBoxefd23dc1fea4\Psalm\CodeLocation $code_location): _HumbugBoxefd23dc1fea4\Psalm\Type\Union must be compatible with Psalm\Plugin\Hook\FunctionReturnTypeProviderInterface::getFunctionReturnType(Psalm\StatementsSource $statements_source, string $function_id, array $call_args, Psalm\Context $context, Psalm\CodeLocation $code_location) in phar:///Users/gog/Downloads/psalm(1).phar/src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayColumnReturnTypeProvider.php on line 11

    Fatal error: Declaration of _HumbugBoxefd23dc1fea4\Psalm\Internal\Provider\ReturnTypeProvider\ArrayColumnReturnTypeProvider::getFunctionReturnType(_HumbugBoxefd23dc1fea4\Psalm\StatementsSource $statements_source, string $function_id, array $call_args, _HumbugBoxefd23dc1fea4\Psalm\Context $context, _HumbugBoxefd23dc1fea4\Psalm\CodeLocation $code_location): _HumbugBoxefd23dc1fea4\Psalm\Type\Union must be compatible with Psalm\Plugin\Hook\FunctionReturnTypeProviderInterface::getFunctionReturnType(Psalm\StatementsSource $statements_source, string $function_id, array $call_args, Psalm\Context $context, Psalm\CodeLocation $code_location) in phar:///Users/gog/Downloads/psalm(1).phar/src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayColumnReturnTypeProvider.php on line 11```

I am using the latest phar from the releases page (Psalm 3.3.2@201030928de5001941a59eddce77b9d326bc1880) on PHP 7.2.11 installed by Homebrew on MacOs.

**Comment by muglug** [comment]
I was able to reproduce this on a project that already had `vimeo/psalm` as a composer dependency, so I've updated the ticket.

I'm not sure how to class this - the Phar should probably check that Psalm isn't already installed before running in a given directory, as things are very likely to break.

**Comment by muglug** [comment]
In the meantime you should just run `vendor/bin/psalm` (i.e. use the composer-installed version, which you can update if necessary)

**Comment by gjuric** [comment]
Ah, sorry, my bad for not mentioning that. I was trying to run psalm from the vendor folder first, but because I am using a phpstan-shim there were some issues with psalm not recognizing how nikic/php-parser was installed so I tried running the phar without removing it from the vendor folder first.

If you ask me this issue can be closed.

**Comment by muglug** [comment]
Yeah that issue (with `phpstan-shim`, not with Psalm) is tracked at https://github.com/vimeo/psalm/issues/1630
