### ISSUE TITLE
Support for finding plugins when using composer-bin-plugin

### ISSUE THREAD

**Issue by gjuric** [vimeo/psalm#1710]
I am using https://github.com/bamarni/composer-bin-plugin to install psalm to get around an unrelated issues.

When psalm is installed in a separate **bin**  and a plugin is installed in the same **bin** it looks like the psalm_plugin can not find the plugins.

To reproduce:

    composer require --dev bamarni/composer-bin-plugin
    composer bin psalm require vimeo/psalm weirdan/doctrine-psalm-plugin
    mkdir src
    vendor/bin/psalm --init src
    vendor/bin/psalm-plugin

Got output:

```Enabled
-------

 ! [NOTE] No plugins enabled

Available
---------

 ! [NOTE] No plugins available
```

Expected output:

```
Enabled
-------

 ! [NOTE] No plugins enabled

Available
---------

 ------------------------------- ------------------------------------
  Package                         Class
 ------------------------------- ------------------------------------
  weirdan/doctrine-psalm-plugin   Weirdan\DoctrinePsalmPlugin\Plugin
 ------------------------------- ------------------------------------
```

**Comment by weirdan** [comment]
If you enable the plugin manually (by editing the `psalm.xml` file), does plugin work? In other words, is it limited to just `psalm-plugin`, or plugins are fully unusable in this setup?

**Comment by gjuric** [comment]
It looks like it can't be found:

```
Scanning files...
PHP Fatal error:  Uncaught UnexpectedValueException: Weirdan\DoctrinePsalmPlugin\Plugin is not a known class in {removed}/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Config.php:985
Stack trace:
#0 {removed}/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(458): Psalm\Config->initializePlugins(Object(Psalm\Internal\Analyzer\ProjectAnalyzer))
#1 {removed}/vendor-bin/psalm/vendor/vimeo/psalm/src/psalm.php(563): Psalm\Internal\Analyzer\ProjectAnalyzer->check('{removed}...', false)
#2 {removed}/vendor-bin/psalm/vendor/vimeo/psalm/psalm(2): require_once('{removed}...')
#3 {main}

Next Psalm\Exception\ConfigException: Failed to load plugin Weirdan\DoctrinePsalmPlugin\Plugin in {removed}/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Config.php:1003
Stack trace:
#0 {removed}/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analy in {removed}/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Config.php on line 1003
```

**Comment by weirdan** [comment]
Thanks, I'll take a look at this tonight. It's a bit surprising that Psalm cannot load the plugin when configured manually, it's ought to be using the same autoloader Psalm uses.

**Comment by weirdan** [comment]
So plugins not being loaded by Psalm is apparently caused by 8eca864e98abd6d1b418874de76d732c0a675fea . @muglug do you recall why you introduced this change?

**Comment by muglug** [comment]
> do you recall why you introduced this change?

At work and at home I have a folder with the latest version of Psalm. That folder also has a Psalm plugin installed (for PHPUnit).

I often run that Psalm installation on other projects, and this prevents Psalm's autoloader from using the plugin version local to Psalm when scanning those other projects. I think.

If it's a problem feel free to create a PR reverting it - my use case is probably incredibly niche.

**Comment by weirdan** [comment]
> and this prevents Psalm's autoloader from using the plugin version local to Psalm when scanning those other projects. 

If that was the the goal, it appears to be only partially achieved, because plugin still uses autoloader internally to load hooks - and thus, I think, it will load stubs local to the project, but hooks will be loaded from that other folder.

Installing both Psalm and plugins using `composer global` probably will result in a similar issue (I assume loading global plugin was causing issues for you). Maybe it could be solved with alternative, configurable, autoloader, but I need to give it some more thought.
