### ISSUE TITLE
Reference with null coalesce operator ignored

### ISSUE THREAD

**Issue by Isinlor** [vimeo/psalm#172]
Following code:
```php
<?php
$variable = 0;
$reference =& $variable ?? null;

if ($reference === null) {
}
```

Triggers: `Cannot find referenced variable $reference` while it's a valid code.

**Comment by muglug** [comment]
Thanks! I can reproduce with https://github.com/vimeo/psalm/commit/f0141cab4e2d1c623551d142d13f64fbff1739b7, and I think it's a parser error. Will let you know more as the linked issue is updated.

**Comment by muglug** [comment]
In the meantime, changing the above to

```php
<?php
$variable = 0;
if (isset($variable)) {
    $reference =& $variable;
} else {
    $reference = null;
}

if ($reference === null) { }
```

passes Psalm checks (and is arguably more clear).

**Comment by muglug** [comment]
`=&` binds stronger than `??`, so your code doesn't do what you think it does (and what I thought it did).

Thanks @nikic for clearing it up.
