### ISSUE TITLE
CallMap.php is incorrect for mcrypt_get_cipher_name

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#1725]
The param name doesn't match php's regex for a valid identifier. Also, this should be cipher => int|string

https://php.net/mcrypt_get_cipher_name

```
src/Psalm/Internal/CallMap.php
7217:'mcrypt_get_cipher_name' => ['string|false', 'int|cipher'=>'string'],
```

Consider adding a unit test that asserts that parameters and union types are parseable and normalized (and sorted) - [something along the lines of this](https://github.com/phan/phan/blob/master/tests/Phan/Language/Internal/FunctionSignatureMapTest.php)

**Comment by muglug** [comment]
Callmap union types are checked in a test, but the param names aren’t used by Psalm anywhere, so go uncovered. Happy to add a test, though.
