### ISSUE TITLE
@template-extends expects multi-line input

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1728]
It appears that the docblock parser expects template-extends to be a multi-line annotation entry if the line following the declaration consists solely of a single "*".

There's a php-cs-fixer rule (`phpdoc_separation`) that requires annotations of differing types be separated by a "blank" line.

If one declares the template annotations first, followed by property annotations, then the issue occurs.
The workaround is to declare `@template-extends` last, as the docblock parser likely interprets `*/` as "there's no more annotations, go home".

Unless the docblock is parsed backwards, I suspect non-workaround solution to this may be impacted by/benefit from #1518 as docblock annotations *may* be valid at the start of a line in a multi-line annotation (e.g. a multi-line version of `array{@property:string}`).

* expects-multiline: https://psalm.dev/r/0077af5d32
* doesn't expect: https://psalm.dev/r/315044f3c9

```php
<?php
/**
* @template DATA as array<string, scalar|array|object|null>
*/
abstract class Foo {}

/**
* @template-extends Foo<array{id:int}>
*
* @property int $id
*/
class Bar extends Foo {}
```
> Psalm output (using commit 624c7bc): 
>
> ERROR: InvalidDocblock - 12:1 - Invalid type '
> *' in docblock for Bar

**Comment by muglug** [comment]
This was broken (in `dev-master`) by https://github.com/vimeo/psalm/commit/c569f3932c7149ffec4e7defbf6ea0d264ea5255
