### ISSUE TITLE
Introduce top type

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1729]
Psalm has a bottom type, `no-return`, and the dynamic type `mixed`, but I think it might be useful to also have a top type. Taking a lead from typescript, `mixed` is comparable to Typescript's `any`, `no-return` is comparable to Typescript's `never`, and we could adopt the[ name `unknown` for the top type](https://github.com/Microsoft/TypeScript/pull/24439).

To illustrate the difference, psalm emits `MixedMethodCall` on the call to `bar()` below:

```
<?php

/** @return mixed */
function foo() {
    return "bar";
}

function usesFoo(): void {
  foo()->bar();
}
```

`MixedMethodCall` is (with default Psalm settings) an `INFO`, not an `ERROR`.

However if the return statement was changed to `/** @return unknown */` then instead of `MixedMethodCall` psalm would emit some form of error.

The top type should be treated as a supertype of all other types, so that the following code should cause no issues:

````
<?php
/** @param unknown $value */
function is_valid_array_key($value): bool {
    return is_string($value) || is_int($value);
}
````

`unknown` would be roughly equivilent to `object|scalar|mixed|array|null`, except currently psalm seems to treat `object` as a form of mixed, rather than as a supertype of all other object types.

**Comment by muglug** [comment]
Flow handles this with [a `mixed` type](https://flow.org/en/docs/types/mixed/) that's equivalent to TypeScript's `unknown`.

I think it's an interesting idea, but I wonder whether it would be useful in that many places.

**Comment by bdsl** [comment]
Right, Hack [does the same thing](https://stackoverflow.com/a/23052550/2526181). But I think for PHP `mixed` probably has to retain its current meaning as used in existing docblocks.

If you don't have something like `any` / `mixed` then I think the language stops being gradually typed and becomes statically typed, which we probably don't want.

**Comment by ondrejmirtes** [comment]
PHPStan's `mixed` is effectively a top type.

**Comment by muglug** [comment]
> PHPStan's mixed is effectively a top type.

The only deliberate difference I'm aware of is that a union of `mixed|string` in Psalm is still `mixed|string`.

The benefit of that is in finding bugs - `PossiblyInvalidMethodCall` can be emitted for https://psalm.dev/r/80910f8ebf where previously it would just be a `MixedMethodCall` issue.

**Comment by ondrejmirtes** [comment]
Yes, I want to tackle this by adding this as a property to `MixedType` - "it's still mixed, but sometimes I'm sure it's a string".

**Comment by muglug** [comment]
Closing as not really relevant
