### ISSUE TITLE
Psalm V4 breaking changes

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#1732]
Coming late this year, probably to coincide with 7.4 release

- [x] class constants should live in their own storage object
- [x] remove issues `MisplacedRequiredParam`, `TypeCoercion`, `MixedTypeCoercion`
- [x] remove support for `@template-typeof`
- [x] rename `TFn` to `TClosure`, `ObjectLike` to `TKeyedArray`
- [x] Remove return type manipulation from `AfterFunctionCallAnalysisInterface`
- [x] default to not disabling checks with `UnresolvableInclude` (#2818)
- [x] Added return and param types to plugin hooks
- [x] Remove `requireVoidReturnType`, `useAssertForType` config flags
- [x] Change default on `resolveFromConfigFile` to `"true"`

**Comment by weirdan** [comment]
@muglug it seems v4 just never happened. Is the list still up to date?

**Comment by muglug** [comment]
I'll probably do it with PHP 8 release, which seems like an even better reason
