### ISSUE TITLE
Problem inferring type when type is checked by another method

### ISSUE THREAD

**Issue by jaikdean** [vimeo/psalm#1734]
I would expect these two examples to be equivalent:

https://psalm.dev/r/8d84086c1a
https://psalm.dev/r/9f38b46cda

Is there any way to get that working?

Further to this, I'm getting odd behaviour in a private code base that I've been unable to reproduce. The situation is basically outlined [here](https://psalm.dev/r/77be4f2066), but what I'm seeing is the equivalent of `ERROR: PossiblyUndefinedMethod - foo.php:11:20 - Method BazInterface::bar does not exist`. Effectively rather than being unable to determine the type of `$object`, Psalm is seeing it as an interface the type we're checking for implements.

As I say, I've not been able to reproduce that, but it seemed to appear in 3.2.11 or 3.2.12. Are there any options I can pass to Psalm to help debug or create a reproducer for this?

**Comment by iluuu1994** [comment]
Although it's not exactly equivalent, this sounds similar to TypeScript's [type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards).

**Comment by weirdan** [comment]
> Is there any way to get that working?

Just a couple more annotations is all you need: https://psalm.dev/r/f7dc5dc400

**Comment by iluuu1994** [comment]
That's awesome! Forgot about `@psalm-assert`.

**Comment by jaikdean** [comment]
@weirdan That is beautiful, I didn't know `@psalm-assert` existed. Thank you!

**Comment by weirdan** [comment]
There are also `psalm-assert-if-*` variants should you need them ([doc link](https://github.com/vimeo/psalm/blob/master/docs/supported_annotations.md#psalm-assert-psalm-assert-if-true-and-psalm-assert-if-false)).
