### ISSUE TITLE
query re: templating array-empty onto array<string, scalar>

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1735]
~~if a template is `T as array{a:string, b:float, c:int}`, would `@return array<key-of<T>, string>` be interpreted as `array{a:string, b:string, c:string}` ?~~

~~i.e. for the laziness of `return array_map('strval', $this->data);`~~

type shuffling appears to work as expected: https://psalm.dev/r/aa150efc53

```php
<?php
/**
* @template T as array<string, scalar>
*/
interface Foo {
  /**
  * @return array<key-of<T>, string>
  */
  public static function AsStrings() : array;
  
  /**
  * @return T
  */
  public static function AsScalars() : array;
}

/**
* @template-implements Foo<array<empty, empty>>
*/
class IsEmpty implements Foo {
  public static function AsStrings() : array {
    return [];
  }
  
  public static function AsScalars() : array {
    return [];
  }
}

/**
* @template-implements Foo<array{foo:'bar'}|array<empty, empty>>
*/
class NotEmpty implements Foo {
  public static function AsStrings() : array {
    return random_int(0, 1) ? ['foo' => 'bar'] : [];
  }
  
  public static function AsScalars() : array {
    return random_int(0, 1) ? ['foo' => 'bar'] : [];
  }
}

/**
* @template T as array{foo:'bar', baz:int, bat:float}
*
* @template-implements Foo<T>
*/
class WorksAsExpected implements Foo {
  public static function AsStrings() : array {
    /**
    * Should not be needed, because:
    * value-of<array<string, scalar>> for array_map('strval', $arr)
    * is array<string, string>, since no scalar is not string-castable
    *
    * @var array<string, string>
    */
    $out = array_map('strval', static::AsScalars());
    
    return $out;
  }
  
  public static function AsScalars() : array {
    return ['foo' => 'bar', 'baz' => 1, 'bat' => 2.3];
  }
}
```

However,

> Psalm output (using commit c7f35c2): 
>
> ERROR: ImplementedReturnTypeMismatch - 25:40 - The return type 'array<empty, empty>' for Foo::AsScalars is different to the implemented return type for IsEmpty::asscalars 'T as array<string, scalar>'
>
> ERROR: LessSpecificImplementedReturnType - 38:40 - The return type 'array{foo?:string(bar)}' for Foo::AsScalars is more specific than the implemented return type for NotEmpty::asscalars 'T as array<string, scalar>'

* For `IsEmpty::AsScalars()` `array<string, scalar>` on an array of length 0 is `array<empty, empty>`
* For `NotEmpty::AsScalars()`, the return value is either `array{foo:'bar'}` or `array<empty, empty>`, both of which are equivalent to `array<string, scalar>`.

**Comment by muglug** [comment]
I think this is fixed now?

**Comment by SignpostMarv** [comment]
not quite: https://github.com/SignpostMarv/daft-router/blob/87fc4efb588d7cc9327a23ed3d63896baaa92861/src/DaftRouterZeroArgumentsTrait.php#L35

```php

    /**
    * @param array<empty, empty> $args
    *
    * @return EmptyArgs
    */
    public static function DaftRouterHttpRouteArgsTyped(array $args, string $method) : TypedArgs
    {
        return new EmptyArgs();
    }
```

> INFO: MoreSpecificImplementedParamType - src\DaftRouterZeroArgumentsTrait.php:35:63 - Argument 1 of SignpostMarv\DaftRouter\DaftRouterZeroArgumentsTrait::DaftRouterHttpRouteArgsTyped has the more specific type 'array<empty, empty>', expecting 'array<K as key-of<T1>, string>' as defined by SignpostMarv\DaftRouter\DaftRoute::DaftRouterHttpRouteArgsTyped
>    public static function DaftRouterHttpRouteArgsTyped(array $args, string $method) : TypedArgs
