### ISSUE TITLE
@psalm-assert crashes on "no hyphens allowed"

### ISSUE THREAD

**Issue by JanVoracek** [vimeo/psalm#1736]
Following code (https://psalm.dev/r/8e56964b7e):
```php
<?php

/**
 * @psalm-assert 'foo'|'bar'|'foo-bar' $s
 */
function assertFooBar(string $s) : void {
}

$a = '';
assertFooBar($a);
```
crashes on
```
PHP Fatal error:  Uncaught Psalm\Exception\TypeParseTreeException: no hyphens allowed in .../vendor/vimeo/psalm/src/Psalm/Type/Atomic.php:187
```

My local environment:
- PHP version: 7.2.12
- psalm version: master (778b95d)

**Comment by muglug** [comment]
Union types aren't intended to work in `@psalm-assert` (though I can see why that could be a useful future addition).

The code now results in an `InvalidDocblock` issue.
