### ISSUE TITLE
Psalm can not be installed in Symfony 4.3 project

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1739]
Unless I'm misreading this, the composer.json line below will prevent installation of psalm in any project which has symfony/console 4.3, which is any project built with the current version of the symfony framework. https://github.com/vimeo/psalm/blob/99a2d866611c6478490bfba1377a30d527e6b874/composer.json#L23

Perhaps a good way to resolve this would be to change the installation instructions, replacing `composer require --dev vimeo/psalm` with `composer require --dev psalm/phar`. Other changes would need to be made, either to documentation or to the build of the `psalm/phar` repository, since currently the phar has to be called as `vendor/bin/psalm.phar`, and `vendor/bin/psalm`, `vendor/bin/psalter`, etc are not available in the phar distribution.

**Comment by muglug** [comment]
The Phar's the reason it can't be installed - it currently [generates a warning](https://github.com/vimeo/psalm/issues/1733) which I haven't yet had time to probe

**Comment by bdsl** [comment]
I'm not sure I follow - if it's the phar that shouldn't be installed in a 4.3 project shouldn't that be restricted in as a [conflict](https://getcomposer.org/doc/04-schema.md#conflict) in https://github.com/psalm/phar/blob/master/composer.json rather than the composer.json of this repo?

**Comment by muglug** [comment]
`symfony/console:4.3` requires `symfony/polyfill-php73` which provides a stub for `JsonException` that breaks in actual PHP 7.3 when prefixed by `humbug/php-scoper` (and calling `class_alias`). I'll spend some more time investigating tonight, but it's likely easily-fixable.

**Comment by bdsl** [comment]
Ah right. But presumably that wouldn't mean the phar shouldn't installed in a Symphony 4.3 project - it's just an issue about what version of symfony/console exists **inside** the phar. So updating the docs to recommend the phar would be a viable fix.

Hopefully I'll have upgrade something to 4.3 soon, so I can try it out then.

**Comment by jaikdean** [comment]
Any chance of a release so we can use this? :)

**Comment by muglug** [comment]
Done!
