### ISSUE TITLE
`scalar` cannot be used as type hint

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#1744]
`scalar` doesn't seem to be allowed as a possible docblock type:

```php
<?php

/**
 * @psalm-assert scalar $actual
 */
function assertIsScalar($actual) : void
{
}

/**
 * @param mixed $value
 *
 * @psalm-return scalar
 */
function consume($value) : string
{
    assertIsScalar($value);

    return $value;
}
```

https://psalm.dev/r/923a5cc1a3 :

```
Psalm output (using commit ddd287f):

INFO: MissingParamType - 6:25 - Parameter $actual has no provided type

ERROR: MismatchingDocblockReturnType - 13:18 - Docblock has incorrect return type 'scalar', should be 'string'

INFO: MixedInferredReturnType - 13:18 - Could not verify return type 'scalar' for consume
```

**Comment by weirdan** [comment]
Your return type hint (which is authoritative) is narrower than docblock return type, so Psalm tells you that. When you drop it, Psalm emits no issues: https://psalm.dev/r/9a9e03d2c0

When you drop docblock return type, Psalm properly complains that you return scalar where only string should be returned: https://psalm.dev/r/91b6781b2a

**Comment by Ocramius** [comment]
Grmbl: I need some more beer when doing these. Thanks @weirdan!
