### ISSUE TITLE
Filter DeprecatedInterface issues by the deprecated interface 

### ISSUE THREAD

**Issue by pamil** [vimeo/psalm#1746]
Having the following code:

```php
<?php
  
/** @deprecated */
interface DeprecatedInterface {}

class ClassUsingDeprecatedInterface implements DeprecatedInterface {}
```

I'm getting the following error:

```
ERROR: DeprecatedInterface - 6:7 - DeprecatedInterface is marked deprecated
```

I'd like to configure and suppress this error the following way:

```xml
<DeprecatedInterface errorLevel="info">
    <errorLevel type="suppress">
        <referencedInterface name="DeprecatedInterface" />
    </errorLevel>
</DeprecatedInterface>
```

It is currently possible to do the same with `DeprecatedClass` with the following config:

```xml
<DeprecatedClass errorLevel="info">
    <errorLevel type="suppress">
        <referencedClass name="DeprecatedClass" />
    </errorLevel>
</DeprecatedClass>
```

I'm willing to create a PR for that (as I have a few similar issues incoming) but I'd need some guidance to start.

**Comment by muglug** [comment]
I've just done an audit - a bunch of other issues are now also filterable the same way.

You could also use the baseline feature to discourage future use of deprecated classes/interfaces.

Feel free to open more issues - if fixes are easy enough I'll point you in the right direction!

**Comment by pamil** [comment]
Thanks a lot! 🎉
