### ISSUE TITLE
Windows: --update-baseline cleans file on call

### ISSUE THREAD

**Issue by serhioli** [vimeo/psalm#1747]
#### Environment
Dir: [ps.zip](https://github.com/vimeo/psalm/files/3263232/ps.zip)
PHP: `PHP 7.3.5 (cli) (built: May  1 2019 13:17:17) ( ZTS MSVC15 (Visual C++ 2017) x64 )`
Installed from scoop on Windows 10. No specific configurations.

Psalm: `Psalm 3.4.2@f327d75116a15e88431668c36b9613f1e3dd62a4`
Installed in project. `--init . 8`

##### Var.1
- `./vendor/bin/psalm --set-baseline=baseline.xml`
- You'll see the `baseline.xml` with existing errors
- `./vendor/bin/psalm --update-baseline`
- Now `baseline.xml` contains only xml header and self version
##### Var.2
- `./vendor/bin/psalm --set-baseline=baseline.xml`
- You'll see the `baseline.xml` with existing errors
- You're trying to fix one of two found issues
- `./vendor/bin/psalm --update-baseline`
- Now `baseline.xml` contains only xml header and self version

P.S.: Console output looks totally weird:
![image](https://user-images.githubusercontent.com/1549136/59061756-7f1afd00-88a4-11e9-8d8f-819cb39bf794.png)

**Comment by muglug** [comment]
Ah this is definitely a Windows issue

**Comment by SignpostMarv** [comment]
yeah, I've had this for a while but just thought I was using it wrong- give a shout if a fix needs testing?

**Comment by muglug** [comment]
If you’re on Windows atm you’re better placed to fix than I am

**Comment by SignpostMarv** [comment]
any ideas of the root cause ?

**Comment by SignpostMarv** [comment]
I think found it; `countIssueTypesByFile` returns non-normalised file paths, therefore file is not in entry, therefore it gets removed from the list?

**Comment by muglug** [comment]
Thanks @SignpostMarv - I think it should be good now

**Comment by SignpostMarv** [comment]
@muglug yup, seems that way :)

**Comment by serhioli** [comment]
Wow! @SignpostMarv thank you so much!
