### ISSUE TITLE
Problem with Symfony contracts event dispatcher interface

### ISSUE THREAD

**Issue by loic425** [vimeo/psalm#1752]
On symfony/event-dispatcher 4.3, the event dispatcher implements PsrEventDispatherInterface only if this interface exists.
https://github.com/symfony/contracts/blob/master/EventDispatcher/EventDispatcherInterface.php

When you parse an EventListener, this throws an error.
`MissingDependency - src/EventListener/UserRegistrationListener.php:38:13 - Symfony\Component\EventDispatcher\EventDispatcherInterface depends on class or interface psr\eventdispatcher\eventdispatcherinterface that does not exist`

What do you purpose to prevent throwing this kind of error without exluding all your EventListeners in a Symfony project.

**Comment by muglug** [comment]
Oof ok.

So add that as a dependency to `require-dev` in composer and Psalm should be happy.

**Comment by loic425** [comment]
@muglug It works, thanks.

**Comment by tvdijen** [comment]
I ran into the same issue today, but adding it to `require-dev` doesn't feel like an actual solution?

**Comment by muglug** [comment]
OK I don't think the code is _that_ valid - two different definitions of an interface depending on a fairly arbitrary switch. It's not something you'd find in pretty much any other language.

But I'll think about how this could be worked around.

**Comment by tvdijen** [comment]
Yeah, they're not gonna win a beauty contest with this, but I've seen it before an it won't be the last one either.. Thanks for reconsidering.
