### ISSUE TITLE
Psalm doesn't inherit parent method phpdoc for constructor arguments

### ISSUE THREAD

**Issue by andrew-demb** [vimeo/psalm#1753]
I have an abstract class, that implements interface template params and introduce own new template param.
Own template param used for type hint constructor dependency, but when I extend this class and override constructor without specified phpdoc, psalm doesn't import it automatically.

This requires from me duplicate parent definition (and add new template param) or explicit specify generic param value.

Sorry for the large example.

https://psalm.dev/r/30ed05a0cb

Expected: "InvalidArgument" issue on `new StdClassProvider($intIndexator)` line.
Actual: No issue.

P. S. Psalm warns about "LessSpecificImplementedReturnType", I cannot find out, why.

**Comment by weirdan** [comment]
> P. S. Psalm warns about "LessSpecificImplementedReturnType", I cannot find out, why.

More succinct reproducer for that: https://psalm.dev/r/4443f0eb7b
```php
<?php
/** @template T as mixed */
interface I {
    /**
     * @param  T $v
     * @return array<string,T>
     */
    public function indexById($v): array;
}

/** @template-implements I<int> */
class C implements I {
    public function indexById($v): array {
      return [(string)$v => $v]; 
    }
}
```

**Comment by muglug** [comment]
Reproduced main bug as https://psalm.dev/r/d994825774

```php
/**
 * @template TValue as mixed
 */
interface Producer {}

/**
 * @template TValue as mixed
 */
abstract class Container
{
    /**
     * @param Producer<TValue> $producer
     */
    abstract public function __construct(Producer $producer);
}

/**
 * @template-extends Container<\stdClass>
 */
class StdClassContainer extends Container
{
    public function __construct(Producer $producer) {}
}

/**
 * @param Producer<int> $i
 */
function takesIntProducer(Producer $i) : void {
  new StdClassContainer($i); // should be error
}
```

**Comment by muglug** [comment]
OH this is not a bug - constructor docblocks aren't inherited, because constructor of class `A` bears no relation to the constructor of `AChild` (they can have different params, in different orders).

**Comment by muglug** [comment]
If you leave out the child class's constructor entirely your example works fine.

**Comment by muglug** [comment]
Fixed the LessSpecificImplementedReturnType in 2fa0f27

**Comment by bdsl** [comment]
Of course there's always a way to break it at run time as with most things in PHP. You can call a child constructor on an object that's staticly typed as the parent like so:

```php
<?php
class Foo 
{
  public function __construct()
  {
  }
}

function takesAFoo(Foo $foo) :void
{
  $foo->__construct();
}
```

But I think the answer is just don't do that.
