### ISSUE TITLE
Don't output colours by default if output is not a terminal

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1754]
I use psalm with less, and to workaround this issue I need to run `./bin/psalm | less -R` rather than `./bin/psalm | less` . If I don't include the `-R` I get hard to read output including all the colour codes.

I think the fix would be to add --color and --no-color options, with the default depending on the value returned by [`stream_isatty(STDOUT)`](http://docs.php.net/manual/en/function.stream-isatty.php).

**Comment by muglug** [comment]
Would you mind PRing this? You’ll find similar checks around whether or not to show the progress bar in src/psalm.php

**Comment by bdsl** [comment]
I can't right now, but I will try to in the next few days if no-one else does, should be pretty trivial. I know I still also promised to do the directory resolution thing.

**Comment by muglug** [comment]
Oh I think you just want the `-m` or `--monochrome` flag. I thought about it, and I want to keep colourful output in CI where possible.

**Comment by bdsl** [comment]
Ok, that should work. @muglug , while you're here can you take a look at #1758 ? Thank you.
