### ISSUE TITLE
UndefinedFunction - function not included in file but in parent

### ISSUE THREAD

**Issue by hlscalon** [vimeo/psalm#1755]
I don't know if this is a design decision, a configurable parameter or a bug (I've searched for this, and couldn't find anything, so forgive me if it's a duplicate).

I'm working in a very big (and old) codebase and I'm trying to use Psalm (which I really liked). Consider the following code (silly example, just made very simple to reproduce the issue):

> utils.php:

```
<?php

function uRounder($x) {
	return round($x, 4);
}
```

> Rounder.php:

```
<?php

class Rounder {

	private $number;

	public function __construct($_number = 0) {
		$this->number = $_number;
	}

	public function format() {
		return uRounder($this->number);
	}

}
```
> service.php
```
<?php

require_once("utils.php");
require_once("Rounder.php");

$x = new Rounder(53.134443123);
echo $x->format();
```
Psalm gives me the following error (I am supressing all type checks):

> /.../Rounder.php:12:10:error - UndefinedFunction: Function uRounder does not exist

This kind of problem happens everywhere in the codebase (constants also). Is there a solution for this situation ?

Thanks

**Comment by muglug** [comment]
> Is there a solution for this situation ?

Yup! Don't have Psalm analyse `utils.php` or `Rounder.php`  directly - instead it should just analyse `service.php`. It'll discover the other files and  complain about any bugs it finds therein.
