### ISSUE TITLE
issue with implicitly vs. explicitly type-hinting `yield from $x;` via interface-defined `IteratatorAggregate::getIterator():Generator<int, int, mixed, void>`

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1756]
* implicit: https://psalm.dev/r/5179c1e9cc
  * return type not inherited from interface
  * `yield from Foo` resolves to mixed, rather than int
* explicit: https://psalm.dev/r/fed16a81b1
  * `yield from Foo` resolve to int correctly
  * but type is inferred as `Generator<mixed, mixed, mixed, void>`

**Comment by weirdan** [comment]
You've posted the same link twice.

**Comment by SignpostMarv** [comment]
whoops.

**Comment by muglug** [comment]
The problem seems to be with `getIterator` not inheriting the parent's docblock. It works for differently-named methods: https://psalm.dev/r/afa913f049

**Comment by muglug** [comment]
The reason this is happening is because `Bar` implements two interfaces - `IteratorAggregate` and `Foo` - that both define a `getIterator` method, so it doesn't know which one's docblock to use. This is still probably a bug, but not one that I'm going to bother to fix, as it would be hard.

**Comment by SignpostMarv** [comment]
@muglug do one of thesesolve the method definition issue? 

https://psalm.dev/r/3106230c24
```php
/**
* @template-extends IteratorAggregate<Generator<int, int, mixed, void>>
*/
interface Foo extends IteratorAggregate {
}
```
https://psalm.dev/r/82c22fbb27
```php
/**
* @template-extends IteratorAggregate<int, int>
*/
interface Foo extends IteratorAggregate {
}
```

**Comment by muglug** [comment]
`Baz` still inherits `IteratorAggregate` and `Foo`

**Comment by SignpostMarv** [comment]
@muglug except now `Foo` doesn't redefine `IteratorAggregate::getIterator()`, it just passes the the template params over?

**Comment by muglug** [comment]
I've ticketed that here: https://github.com/vimeo/psalm/issues/1766

**Comment by muglug** [comment]
I fixed that an a related problem that doesn't quite apply here - 9c4599a
