### ISSUE TITLE
Psalter incorretcly replaces method

### ISSUE THREAD

**Issue by oscargala** [vimeo/psalm#1757]
I'm running Psalter on a Symfony 3.4 project and I have a Command file where Psalter replaces this method:

```php
    /**
     * @param array $companyId
     */
    private function test(array $companyId)
    {
    }
```

with 

```php
   ompanyId): void
    {
    }
```

I have used ./vendor/bin/psalter --issues=all --safe-types
and ./vendor/bin/psalter --issues=all --php-version=7.1
Got the same result with both commands.

Any ideas?

**Comment by muglug** [comment]
Would you be able to reproduce in a separate repo?

**Comment by oscargala** [comment]
I'll try that over the weekend!

**Comment by muglug** [comment]
thanks!

**Comment by muglug** [comment]
Also check if it's still broken on latest master (made some improvements in last few days)

**Comment by muglug** [comment]
were you able to reproduce?

**Comment by oscargala** [comment]
Sorry, this took me too long.
I have been able to reproduce with this Symfony 3.4 project:
https://github.com/oscargala/psaltertest

If I run vendor/bin/psalter --issues=all --php-version=7.2  then the AppBundle/Entity/Category.php file gets messed up. It's due to the addProduct and removeProduct methods.
