### ISSUE TITLE
Is there a way for psalm to support beberlei/assert?

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#1762]
I get error 

> PossiblyInvalidArgument - file.php:n:n - Argument 1 of Safe\json_decode expects string, possibly different type string|resource provided

```php
$jsonContent = $request->getContent();
Assertion::string($jsonContent);
$content = json_decode($jsonContent, true);
```

`getContent()` is typed as `* @return string|resource` but [Assertion](https://github.com/beberlei/assert) ensures it's `string`

Is there a way https://github.com/beberlei/assert is supported?

**Comment by muglug** [comment]
I know @Ocramius was asking about it - while not all methods are easily assertable, `Assertion::string` could have a `@psalm-assert string $value` assertion added easily: https://github.com/beberlei/assert/blob/f6ca7546e11102db2feed8e76a61a9ed1962e8cd/lib/Assert/Assertion.php#L661

**Comment by muglug** [comment]
I've added some obvious ones here: https://github.com/muglug/assert/compare/master...add-psalm-assertions

**Comment by simPod** [comment]
@muglug I see 👍 . Are you planning to open PR with that?

**Comment by muglug** [comment]
Yeah, I'll do it today

**Comment by Ocramius** [comment]
@simPod the complex part is type-checking stuff like:

```php
Assert::that($value)
 ->all()
 ->integer()
 ->greaterThan(0);
```

Besides that, I suggest you to pick it up from @muglug after he gave us pointers/ideas: there's enough to already be done from his end in this repo :-P

**Comment by muglug** [comment]
The simple stuff was tackled in https://github.com/beberlei/assert/pull/282

**Comment by muglug** [comment]
Closing
