### ISSUE TITLE
False Positive UndefinedInterfaceMethod

### ISSUE THREAD

**Issue by basz** [vimeo/psalm#1764]
Why would calling an interface method called in a constructor be marked as `ERROR: UndefinedInterfaceMethod - 37:23 - Method ShapeInterface::something does not exist`

https://psalm.dev/r/d51e65c43a

Calling the same interface method from a method does not error.

**Comment by muglug** [comment]
Short answer: it's a bug. Slightly longer answer: Psalm calls the parent constructor when checking that `$this->shape` is set before it's used, and it seems to forget the type of the passed-in interface, using instead the parent param type.

**Comment by basz** [comment]
We all forget stuff sometimes... cheers

**Comment by muglug** [comment]
The solution was just to suppress the error during the property initialisation checks (it'd still be caught on the first run).
