### ISSUE TITLE
Allow psalm-refactor to manipulate whole namespaces, not just classes

### ISSUE THREAD

**Issue by bendavies** [vimeo/psalm#1771]
Use case.

Moving all test classes from `src` to `tests` when you have a composer setup like:
```
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
```

**Comment by muglug** [comment]
`--rename "Foo\Bar\*" --to "Baz\*"` should now work.

**Comment by bendavies** [comment]
@muglug thanks, i'll give it a go!

**Comment by bendavies** [comment]
hey @muglug 
this works, but does not move the files to respect the new folder structure, in the case that the new namespace is in a different directory, as in my description above.
