### ISSUE TITLE
InvalidReturnStatement occurs when a more specific type is returned

### ISSUE THREAD

**Issue by rickogden** [vimeo/psalm#1775]
When a method Type-hints for an interface and it only returns a more specific implementation, it comes up with the `InvalidReturnStatement` error. This is a particularly problematic issue when it comes to stub classes where you want to simply return an item.

Example available here: https://psalm.dev/r/c9f3ba913d

**Comment by weirdan** [comment]
This seems to be limited to bool literals only.
```php
return new TestPromise("a"); // works when return type is declared as PromisInterface<string>
return new TestPromise(1); // works when return type is declared as PromiseInterface<int>
return new TestPromise(rand(0,1) === 1);; // works with PromiseInterface<bool>
return new TestPromise(true); // or false, fails with PromiseInterface<bool>
```

**Comment by muglug** [comment]
Thanks, both!
