### ISSUE TITLE
Return non-zero exit code if XML configuration file is not found

### ISSUE THREAD

**Issue by foobar1643** [vimeo/psalm#1779]
Right now running psalm without configuration file present, will execute this code:

https://github.com/vimeo/psalm/blob/c21e9917fa05ba4d97da464725471f53ab4fe0d8/src/Psalm/Config.php#L435-L441

This terminates the script with an exit code 0, which means that the program was executed successfully, however the message it outputs does not indicate success, it's an error which can impact CI jobs that are relying on exit codes to indicate success or failures in the pipeline.

My proposal is to change this behavior by simply adding non-zero exit code to the code above. Will you accept a PR with this change?

Also, seeing issue #1336 was labeled as enhancement, I think it would be nice to have a CLI option to allow psalm to run with built-in configuration, something like this:

```
$ psalm --use-default-configuration
```

**Comment by muglug** [comment]
No need for a PR, it's an easy fix. Thanks!
