### ISSUE TITLE
Sort of cache problem on property definition ?

### ISSUE THREAD

**Issue by Taluu** [vimeo/psalm#1780]
I'm currently using psalm-language-server with vim (and w0rp/ale) ; I had an error that I was trying to set an int value on a boolean property.

I switched the boolean property to int (as it was actually an int), but I still have the error message that I shouldn't use `0` as a default value.

Can't reproduce on the playground though, as I think it's a cache error. More over, it keeps pointing on a wrong line.

```php
<?php
//...
     /** 
      * @var int
      * 
      * @ORM\Column....
      */
     private $isVip = 0;
```

For some reasons, as I changed the typehint from `bool` to `int` and added the "blank" line between `@var` and `@ORM`, the error points onto the closing `*/` and still states that `0` is incompatible with `bool` (or something along those lines)...

**Comment by muglug** [comment]
I added a test for this in 4adebec80f16d553028817fbbeede7b4ec321865 and wasn't able to reproduce - was there anything that may have affected things?

**Comment by Taluu** [comment]
(Just to have a marker : We discussed on it on symfony's slack, and @muglug reproduced the error)
