### ISSUE TITLE
possible issue with nested template/orm-style getters

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1782]
Actual example has a lot more uses of the repeating pattern- templates are being used to avoid duplicating the pattern of acceptable values for `DATA[day]`.

I'm not sure if this is a misuse of templates, as I've ran into issues previously that caused issues by having templates referencing each other.

https://psalm.dev/r/21f819229b
```php
<?php

/**
 * @psalm-type DAYOFWEEK = 'MON'|'TUE'|'WED'|'THU'|'FRI'|'SAT'|'SUN'
 * @template DATA as array{day:DAYOFWEEK}
 *
 * @property-read DAYOFWEEK $day
 */
class Foo {
  /**
  * @var DATA
  */
  protected $data;

  /**
  * @param DATA $data
  */
  public function __construct(array $data) {
    $this->data = $data;
  }
  
  /**
   * @template K as key-of<DATA>
   *
   * @return DATA[K]
   */
  public function __get(string $k) {
    return $this->data[$k];
  }
}
```
> Psalm output (using commit c42269e): 
>
> ERROR: InvalidReturnStatement - 28:12 - The type 'string(MON)|string(TUE)|string(WED)|string(THU)|string(FRI)|string(SAT)|string(SUN)' does not match the declared return type 'DATA[K]' for Foo::__get
>
> ERROR: InvalidReturnType - 25:14 - The declared return type 'DATA[K]' for Foo::__get is incorrect, got 'string'

**Comment by muglug** [comment]
I've updated your example to something a little more Psalm-friendly, but I still don't get its purpose.

**Comment by SignpostMarv** [comment]
@muglug psalm doesn't like `@property-*` having `'a'|'b'|'c'` as a type, so template tags are being used as a workaround, but this then causes other issues with the orm-style `@template K as key-of<DATA>` stuff.

snippet from day-job project https://psalm.dev/r/99d22df208:

```php
<?php
/**
* @template DATA as array<string, scalar|array|object|null>
*/
abstract class Base {
  /**
  * @param DATA $data
  */
  public function __construct(array $data) {
    foreach ($data as $k => $v) {
      $this->$k = $v;
    }
  }
  
  /**
  * @template K as key-of<DATA>
  *
  * @return DATA[K]
  */
  public function __get(string $k) {
    /**
    * @var DATA[K]
    */
    $out = $this->$k;
    
    return $out;
  }
  
  /**
  * @return Proxy<static, DATA>
  */
  public function ObtainProxy() : Proxy {
    return new Proxy($this);
  }
}

/**
* @template T1 as Base
* @template T2 as DATA
*/
class Proxy {
  /**
  * @var T1
  */
  protected $initial;
  
  /**
  * @param T1 $initial
  */
  public function __construct(Base $initial) {
    $this->initial = $initial;
  }
}
  
/**
* @template MONTHSOFYEAR as '01'|'02'|'03'|'04'|'05'|'06'|'07'|'08'|'09'|'10'|'11'|'12'
* @template DAYSOFWEEK as 'Monday'|'Tuesday'|'Wednesday'|'Thursday'|'Friday'|'Saturday'|'Sunday'
*
* @template DATA as array{startson:DAYSOFWEEK, q1:MONTHSOFYEAR, q2:MONTHSOFYEAR, q3:MONTHSOFYEAR, q4:MONTHSOFYEAR}
*
* @property-read MONTHSOFYEAR $q1
* @property-read MONTHSOFYEAR $q2
* @property-read MONTHSOFYEAR $q3
* @property-read MONTHSOFYEAR $q4
* @property-read DAYSOFWEEK $startson
*
* @template-extends Base <DATA>
*/
class Foo extends Base {
  /**
  * @var MONTHSOFYEAR
  */
  protected $q1;
  
  /**
  * @var MONTHSOFYEAR
  */
  protected $q2;
  
  /**
  * @var MONTHSOFYEAR
  */
  protected $q3;
  
  /**
  * @var MONTHSOFYEAR
  */
  protected $q4;
}
```

**Comment by SignpostMarv** [comment]
> I've updated your example to something a little more Psalm-friendly, but I still don't get its purpose.

did not know `@psalm-type` was a thing :D

**Comment by SignpostMarv** [comment]
> did not know `@psalm-type` was a thing :D

I guess this boils it down to "`@property-*` does not allow union types" ?

**Comment by SignpostMarv** [comment]
> did not know `@psalm-type` was a thing :D

incidentally, if I don't `@var MONTHSOFYEAR` all the assignments, psalm lists out the options in reverse (when I cause an error).

**Comment by muglug** [comment]
as of 7a63954, `@property-*` now accepts all the types `@var`/`@param`/`@return` do.

**Comment by SignpostMarv** [comment]
> ```php
>   /**
>   * @return Proxy<static, DATA>
>   */
>   public function ObtainProxy() : Proxy {
>     return new Proxy($this);
>   }
> ```

this is what #1695 was for avoiding btw.
