### ISSUE TITLE
query: re correct way to docblock that a method returns a subset of a templated type?

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1783]
The method I've been trying doesn't work:

* https://psalm.dev/r/3588c444d3
* using 7a63954

```php
<?php
 
/**
* @template T as array{foo:'foo', bar:'bar'}
*/
class Foo {
  /**
  * @template K as key-of<T>
  *
  * return array{K?:T[K]}
  */
  public function A() : array {
    return [
      'foo' => 'foo',
      'bar' => 'bar',
    ];
  }
  
  /**
  * @template K as key-of<T>
  *
  * return array{K?:T[K]}
  */
  public function B() : array {
    return [
      'foo' => 'foo',
    ];
  }
  
  /**
  * @template K as key-of<T>
  *
  * return array{K?:T[K]}
  */
  public function C() : array {
    return [
      'bar' => 'bar',
    ];
  }
}
```
> Psalm output (using commit 7a63954): 
>
> ERROR: InvalidDocblock - 12:3 - Template K has invalid as type - Unrecognised template param K
> 
> ERROR: InvalidDocblock - 24:3 - Template K has invalid as type - Unrecognised template param K
>
> ERROR: InvalidDocblock - 35:3 - Template K has invalid as type - Unrecognised template param K

**Comment by SignpostMarv** [comment]
context here is I have `protected $patch = [];` where `$patch` is a subset of `T`, set in `public function __set(string $k, $v) : void;`

**Comment by muglug** [comment]
You mean `@return`: https://psalm.dev/r/89368f97df

**Comment by SignpostMarv** [comment]
> You mean `@return`: https://psalm.dev/r/89368f97df

better example, `array{K?:T[K]}` only works on `@return`, not `@var`? : https://psalm.dev/r/cc153ec346

```php
<?php
 
/**
* @template T as array<string, scalar|array|object|null>
*/
class Foo {
  /**
  * @template K as key-of<T>
  *
  * @var array{K?:T[K]}
  */
  protected $patch = [];
  
  /**
  * @var T
  */
  protected $data;  
  
  /**
  * @param T $data
  */
  public function __construct(array $data) {
    $this->data = $data;
  }
  
  /**
  * @template K as key-of<T>
  *
  * @param K $k
  * @param T[K] $v
  */
  public function __set(string $k, $v) : void {
    $this->patch[$k] = $v;
  }
  
  /**
  * @template K as key-of<T>
  *
  * @param K $k
  *
  * @return T[K]
  */
  public function __get(string $k) {
    /**
    * @var T[K]
    */
  	$out = array_key_exists($k, $this->patch) ? $this->patch[$k] : $this->data[$k];
    
    return $out;
  }
  
  public function count() : int {
    return count($this->patch);
  }
  
  /**
  * @template K as key-of<T>
  *
  * @return array{K?:T[K]}
  */
  public function Difference() : array {
    /**
    * @var array{K?:T[K]}
    */
    $out = [];
    
    foreach ($this->patch as $k => $v) {
      if ($this->initial[$k] !== $v) {        
        $out[$k] = $v;
      }
    }
    
    return $out;
  }
}
```

> Psalm output (using commit 7a63954): 
> 
> ERROR: InvalidDocblock - 12:3 - array{K?:T[K]} is not a valid type (from /var/www/vhosts/psalm.dev/httpdocs/src/somefile.php:7)
> 
> INFO: MixedArgument - 47:32 - Argument 2 of array_key_exists cannot be mixed, expecting array<array-key, mixed>
> 
> INFO: MixedArgument - 53:18 - Argument 1 of count cannot be mixed, expecting array<array-key, mixed>|Countable|SimpleXMLElement|ResourceBundle
> 
> INFO: MixedAssignment - 67:36 - Cannot assign $v to a mixed type
> 
> INFO: MixedArrayAccess - 68:11 - Cannot access array value on mixed variable $this->initial
> 
> INFO: MixedArrayOffset - 68:11 - Cannot access value on variable $this->initial using mixed offset
> 
> INFO: MixedAssignment - 69:9 - Cannot assign to a mixed type
> 
> INFO: MixedArrayOffset - 69:9 - Cannot access value on variable $out[$k] using mixed offset
> 
> INFO: MixedReturnTypeCoercion - 73:12 - The type 'non-empty-array<mixed|string, mixed|T[K]>' is more general than the declared return type 'array{K?:T[K]}' for Foo::Difference
> 
> INFO: MixedReturnTypeCoercion - 59:13 - The declared return type 'array{K?:T[K]}' for Foo::Difference is more specific than the inferred return type 'non-empty-array<mixed|string, mixed|T[K]>'

**Comment by SignpostMarv** [comment]
the *actual* implementation is more akin to this one: https://github.com/vimeo/psalm/issues/1782#issuecomment-502109381

where this example's `Foo<T>` gets passed from that example's `public function ObtainProxy()`.

let me know if you need something more accurate and I'll try and get it signed off from supervisors etc. :D

**Comment by muglug** [comment]
```
/**
  * @template K as key-of<T>
  *
  * @var array{K?:T[K]}
  */
  protected $patch = [];
```

This is not good - `K` is a string literal `"K"` here

**Comment by muglug** [comment]
This is as much as Psalm can manage: https://psalm.dev/r/54cfe7d6a6
