### ISSUE TITLE
array_merge() with splat doesn't chew through complex template

### ISSUE THREAD

**Issue by Rarst** [vimeo/psalm#1786]
I am trying to template a rather convoluted WordPress data structure:

```php
  class Formatter {
	/**
	 * @template Callback as string|object|array
	 * @template AcceptedArgs as int
	 * @template Hook as array{function: Callback, accepted_args: AcceptedArgs}
	 * @template Priority as array-key
	 * @template Hooks as array<Priority, array<Hook>>
	 *
	 * @param \WP_Hook|array $hook Hook instance.
	 * @psalm-param \WP_Hook|Hooks $hook
     * 
     * @psalm-suppress UndefinedClass
	 */
	public function format( $hook ) {
      
      if ( $hook instanceof \WP_Hook ) {
        /** @psalm-var Hooks $hook->callbacks */
        $hook = $hook->callbacks;
      }

      $functions = array_merge( ...$hook );

      foreach ( $functions as $function ) {

      }
    }
}
```
And at that array_merge Psalm gives up:
```
ERROR: InvalidArgument - 23:36 - 
Argument 1 of array_merge expects array, Hooks as array<Priority as array-key, array<array-key, Hook as array{function:Callback as array<array-key, mixed>|string|object, accepted_args:AcceptedArgs as int}>> provided
```
https://psalm.dev/r/8cd575e16e

From what I see it _should_ understand that, since it sees the outer array (`Hooks`) which is structured like `Priority => Hook[]` so splat should turn it into multiple `Hook[]` and merge should stitch them together.

But for some reason it doesn't seem good enough to be considered a valid argument there.

**Comment by weirdan** [comment]
Are you using templates as a substitute for `@psalm-type` (a kind of `typedef`)? It's not documented, but you can find some examples in Psalm's source code: https://github.com/vimeo/psalm/search?q=psalm-type&unscoped_q=psalm-type

**Comment by Rarst** [comment]
Well, since it's not documented I didn't know it exists. :)

I am mostly just looking to document it as comprehensively and robustly as possible. With upstream mess like this keeping it all neat in Psalm is very tiresome.

Open to suggestions how to do it best!

**Comment by Rarst** [comment]
Think this might be something with splat in general, my type mayhem aside.

Here is a simpler case elsewhere:

```php
/** @var array{0:string} $data */
$this->add_event( ...$data );
```

```
ERROR: MixedArgument - src\Record\Collector\Hook_Collector.php:83:26 - 
Argument 1
of Rarst\Laps\Record\Collector\Hook_Collector::add_event cannot be mixed, expecting string
```

I am _telling_ it its string in the array before splat. Since I have the comment from before this might have worked and regressed at some point, not sure.

**Comment by muglug** [comment]
```php
/** @var array{0:string} $data */
$this->add_event( ...$data );
```

won't work as `/** @var ... */` docblocks only work above direct assignments and `foreach` loops

**Comment by muglug** [comment]
I think this is what you meant: https://psalm.dev/r/95d52a2a08
