### ISSUE TITLE
InvalidGlobal for no clear reason

### ISSUE THREAD

**Issue by Rarst** [vimeo/psalm#1789]
```
ERROR: InvalidGlobal - src\Record\Collector\Hook_Collector.php:133:6 - Cannot use
global scope here
                                        global $wp_filter;
```

https://github.com/Rarst/laps/blob/1e9a6000965579b2842d4c20c5a66a3f02fe14a9/src/Record/Collector/Hook_Collector.php#L133

Seems like a pretty vanilla global within closure.

**Comment by muglug** [comment]
It's a bug, but there's an easy workaround: you can solve by moving the `global $wp_filter` up to the top of the function: https://psalm.dev/r/cf7a7b7d85

Since use of globals is an anti-pattern I'm gonna let this be.
