### ISSUE TITLE
Use of undefined class constant is not reported when using static::

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#1791]
https://psalm.dev/r/4c99e2883e

I would expect an error to be reported for line 11.

**Comment by weirdan** [comment]
There should be an error, but only if the class is `final`. Otherwise that constant may be defined in descendant classes.

**Comment by ADmad** [comment]
Why are constants treated differently than variables?

For e.g. an error is thrown for `static::$nonExistent`. https://psalm.dev/r/a19c1bd23f

**Comment by muglug** [comment]
I think this is a bug - ideally Psalm should both require a present constant, and verify that descendants don’t change that constant’s type (same with static properties).

**Comment by muglug** [comment]
I've ensured that the missing class constant is now reported.
