### ISSUE TITLE
A sub class of templated T causes issues

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#1794]
See https://psalm.dev/r/6c82aff665

**Comment by muglug** [comment]
You don’t have any parameters telling Psalm what T is

**Comment by ro0NL** [comment]
I'm trying to describe a generic contract for `T::class => function (T $) {}` where `T` can be any sub class, using `template T of <type>`.

Now it starts working, i think simply by referencing `T` itself instead of the sub class in a yielded closure: https://psalm.dev/r/b85920cb0c vs. https://psalm.dev/r/33a0b3e4fb But this is a violation actually.

**Comment by muglug** [comment]
Again, neither of those have a template param defined as input to the containing function call that returns the templated type, so it cannot determine the type T. Seems like I need to make this a proper error to avoid this sort of confusion.

**Comment by ro0NL** [comment]
I understand now :sweat: 

this is what i was looking for https://psalm.dev/r/ccdcce34fe

eventually it comes down to listing all the expected types i figure, i was trying to avoid that.
