### ISSUE TITLE
Monitor mutation coverage score of test suite

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1797]
Broken out from  #1788.

As discussed, this isn't a priority, but my unsuccessful attempt at doing this using [Infection](https://infection.github.io/) is now merged in. It isn't doing any harm beyond taking up a few minutes of build time for each commit, but obviously having a useless build step is not ideal.

This is the command used to run Infection in the current master: https://github.com/vimeo/psalm/blob/a553adb232cc58925bc09f6cb85653acf75187c4/.circleci/config.yml#L75 . The `|| echo` is there to suppress the non-zero return code.

The output is visible at https://circleci.com/gh/vimeo/psalm/39 and looks like:
```

#!/bin/bash -eo pipefail
php -d memory_limit=4G ~/.composer/vendor/bin/infection --coverage=build/phpunit --only-covered --threads=2 || echo 'Temporarily ignoring unexplained infection failure'

     ____      ____          __  _
    /  _/___  / __/__  _____/ /_(_)___  ____
    / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
  _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
 /___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Running initial test suite...

PHPUnit version: 8.2.2

Generate mutants...

Processing source code files: 543
/bin/bash: line 1:   184 Killed                  php -d memory_limit=4G ~/.composer/vendor/bin/infection --coverage=build/phpunit --only-covered --threads=2
Temporarily ignoring unexplained infection failure
```

I never managed to work out why Infection is apparently crashing after three minutes.

**Comment by maks-rafalko** [comment]
For reference https://github.com/infection/infection/issues/705

**Comment by mundia521** [comment]
Still working out

**Comment by bdsl** [comment]
It may be possible to resolve this following the next release of Infection - I've been testing infection's master branch on Psalm. See latest comments on infection/infection#705 .

**Comment by muglug** [comment]
I think this is not worth pursuing
