### ISSUE TITLE
query re: ctrl-c

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1800]
Just wondering if psalm is interruptible under linux via ctrl-c?

on windows, I occasionally forget to include `--find-dead-code` when setting the baseline file, but I can't interupt the execution of psalm from gitbash with the usual ctrl-c key combo.

**Comment by weirdan** [comment]
It is:
```console
$ ./psalm
Scanning files...
^C
$ ./psalm
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░^C
```

**Comment by iluuu1994** [comment]
It is, even with multiple threads...

**Comment by SignpostMarv** [comment]
have just checked, this doesn't occur on windows from cmd, just gitbash ? o_O

**Comment by SignpostMarv** [comment]
oh ffs.

under gitbash on windows, psalm only gets the signal if one `ctrl+break`s instead of `ctrl+c`s ¬_¬
