### ISSUE TITLE
psalm-refactor should move classes if applicable

### ISSUE THREAD

**Issue by bendavies** [vimeo/psalm#1802]
REF:
https://github.com/vimeo/psalm/issues/1771

Given a composer setup like this:
```
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
```

`vendor/bin/psalm-refactor --rename "App\Foo\Tests\*" --to "App\Tests\Foo\*" should move the classes to the `tests` folder.

**Comment by muglug** [comment]
So I think this is now fixed (it would have caused a warning before). Please verify! Tested locally.
