### ISSUE TITLE
issue with array shape using class-string as key

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1809]
It appears that one presently cannot use a class-string as the array-key of an array shape.

~~https://psalm.dev/r/c4df16e8d5~~ https://psalm.dev/r/37eec4e269

```php
<?php
<?php
/**
* @var array{DateTimeInterface::class:array<int, class-string<DateTimeInterface>>}
*/
$foo = [
  DateTimeInterface::class => [
    DateTimeImmutable::class,
    DateTime::class,
  ],
];

foreach ($foo[DateTimeInterface::class] as $bar) {
  echo (new $bar())->format('Y-m-d'), "\n";
}
```
> Psalm output (using commit 22ae114): 
> 
> ERROR: InvalidArrayOffset - 12:10 - Cannot access value on variable $foo using offset value of 'DateTimeInterface', expecting 'DateTimeInterface::class'
> 
> INFO: MixedAssignment - 12:44 - Cannot assign $bar to a mixed type
> 
> INFO: MixedMethodCall - 13:9 - Cannot call constructor on an unknown class
> 
> INFO: MixedMethodCall - 13:22 - Cannot determine the type of the object on the left hand side of this expression
> 
> INFO: MixedArgument - 13:8 - Argument 1 of echo cannot be mixed, expecting string

***edited to use `foo::class` instead of `class-string<foo>`***

**Comment by weirdan** [comment]
Works fine without docblock though.

**Comment by bdsl** [comment]
@SignpostMarv I think you want this:

```
<?php
/**
* @var array<class-string<DateTimeInterface>, array<int, class-string<DateTimeInterface>>>
*/
$foo = [
  DateTimeInterface::class => [
    DateTimeImmutable::class,
    DateTime::class,
  ],
];

foreach ($foo[DateTimeInterface::class] as $bar) {
  echo (new $bar())->format('Y-m-d'), "\n";
}
```

With which psalm finds [no issues](https://psalm.dev/r/3ca776c993).

You used the notation for object-like arrays, not key-value arrays.

**Comment by SignpostMarv** [comment]
> @SignpostMarv I think you want this:

actual code is still dayjob secret sauce, but this is closer to what I want:

https://psalm.dev/r/37eec4e269
```php
/**
* @var array{DateTimeInterface::class:array<int, class-string<DateTimeInterface>>}
*/
$foo = [
  DateTimeInterface::class => [
    DateTimeImmutable::class,
    DateTime::class,
  ],
];
```

`class-string<DateTimeInterface>` would accept *any* class string as key, `DateTimeInterface::class` should accept *only* `DateTimeInterface::class` as key.

**Comment by SignpostMarv** [comment]
> `class-string<DateTimeInterface>` would accept _any_ class string as key, `DateTimeInterface::class` should accept _only_ `DateTimeInterface::class` as key.

being able to specify an array shape with a specific class-string as a key would mean being able to skip `isset()` & `array_key_exists()` checks.

**Comment by muglug** [comment]
Array shape docblocks really shouldn't capture anything but strings & ints for key types. Under the hood they're a little more powerful (and will be refactored slightly for Psalm 4 to be stored more intelligently).

**Comment by SignpostMarv** [comment]
@muglug so for now I should be specifying the literal fqcn instead of `class-string` or `::class` magic ?

**Comment by muglug** [comment]
Yup!
