### ISSUE TITLE
Type restrictions on asserted object properties are retained even after property mutations

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#1812]
Given a type restricted by an assertion for `$object->property`, when `$object->anyMethod()` is called, `$object->property` assumptions should be cleared:

```php
<?php

class A
{
    /** @var mixed */
    public $field;
  
    public function mutate() : void 
    {
        $this->field = 'mutated';
    }
}

$a = new A;

assert(is_null($a->field));

$a->mutate();

assert(is_null($a->field));
```

https://psalm.dev/r/8fc357f3d4 :

```
Psalm output (using commit d0e84f1):

ERROR: RedundantConditionGivenDocblockType - 20:8 - Found a redundant condition when evaluating docblock-defined type $a->field and trying to reconcile type 'null' to null
```

I'm not sure if the scope of this should be expanded to any method calls, such as in this case:

```php
assert($foo->bar === null);

$somethingUnrelated->aMethodCall();

// the following shouldn't be redundant, because `$somethingUnrelated`
// may have a reference to `$foo`, and mutate it as a side-effect.
assert($foo->bar === null);
```

**Comment by muglug** [comment]
You can disable this with `rememberPropertyAssignmentsAfterCall="false"` in your config.

**Comment by muglug** [comment]
Same code, but with that flag turned off (in the settings panel): https://psalm.dev/r/e57eb56096

**Comment by Ocramius** [comment]
Thanks!

**Comment by Ocramius** [comment]
Just a note: this should probably be the default behavior in a new major, heh...

**Comment by muglug** [comment]
Before I make it the default I’d want to fix the 444 errors in the Psalm codebase when this flag is turned on, which is to say it’s not going to happen any time soon.

**Comment by Ocramius** [comment]
Works for me :D

**Comment by muglug** [comment]
The first example now doesn't give any errors either.
