### ISSUE TITLE
Generic type inference is too specific

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#1815]
I'm not even sure if this is bad. But I thought it was a little surprising so I thought I'd share:

https://psalm.dev/r/7bfa5d6184

```php
<?php
 
/**
 * @template T
 */
class Box {
  /**
   * @param T $value
   */
  public function __construct($value) {}
  
  /**
   * @param T $value
   */
  public function set($value): void {} 
}

$box = new Box(42);
$box->set(43); // ERROR: InvalidArgument - Argument 1 of Box::set expects int(42), int(43) provided
```

It's probably hard to come up with a general rule on how much to generalize the type. Feel free to close this if you think it's fine.

**Comment by muglug** [comment]
Yeah, this is a known issue (insofar as I have thought about it). In practice you're rarely instantiating templates with specific strings where you don't want this behaviour.

**Comment by iluuu1994** [comment]
Fair enough 🙂

**Comment by bdsl** [comment]
You can probably work around this by adding an @var Box<int> annotation to widen the type.

If you did come up with a general rule for widening the type it might be similar to the the [literal type widening](https://mariusschulz.com/blog/typescript-2-1-literal-type-widening) that Typescript does for mutable primitives declared with literal values.

**Comment by muglug** [comment]
Reopening as the basis for a more practical solution

**Comment by muglug** [comment]
Closing again - I don't think it's worth fixing this (though a potential fix is mentioned here: https://github.com/vimeo/psalm/issues/1886#issuecomment-509746129)

**Comment by iluuu1994** [comment]
@muglug Yeah, I think this one is fine.
