### ISSUE TITLE
Allow array_filter callable strings to be interpreted as closures

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1816]
Bringing up the issue of strings being passed as argument 2 to `array_filter()`, psalm at present doesn't parse `array_filter(array<T as array-key, object|null>, 'is_object')` to resolve to `array<T, object>`:

* https://psalm.dev/r/db27600d90
```php
<?php
/**
* @var array<int, DateTimeImmutable|null>
*/
$a = [];

for ($i=0;$i<=10;$i+=1) {
  $a[] = (random_int(0, 1) === 1 ? new DateTimeImmutable() : null);
}

$b = array_filter($a, 'is_object');

/**
* @var array<int, int>
*/
$c = array_map(
  function(DateTimeImmutable $d) : int {
    return $d->getTimestamp();
  },
  $b
);

echo var_export($c, true);
```
> Psalm output (using commit f06cd85): 
> 
> ERROR: PossiblyInvalidArgument - 17:3 - First parameter of closure passed to function array_map expects DateTimeImmutable, possibly different type null|DateTimeImmutable provided

**Comment by muglug** [comment]
Smaller reproduction:

```php
/**
 * @param array<int, DateTimeImmutable|null> $a
 * @return array<int, DateTimeImmutable>
 */
function foo(array $a) : array {
	return array_filter($a, 'is_object');
}
```

https://psalm.dev/r/8a614bdb08

**Comment by muglug** [comment]
This works fine:

```php
/**
 * @param array<int, DateTimeImmutable|null> $a
 * @return array<int, DateTimeImmutable>
 */
function foo(array $a) : array {
	return array_filter($a, function ($f) { return is_object($f); });
}
```

So it should be a relatively simple fix.
