### ISSUE TITLE
By-ref bound closure scope variable type is inferred as `mixed` even if variable is unused

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#1817]
In following example, `$counter` is never mutated, but in the scope of the closure, it is inferred as `mixed`. This is obviously tricky, since by-ref is a mine-field, but I think `mixed` should only be inferred if `$counter` is passed to something other than the closure.

```
<?php
  
(function () : void {
    function useCounter(int $counter) : void
    {
      echo $counter;
    }

    $counter = 0;

    (function () use (& $counter) : void {
        $counter += 1;

        useCounter($counter);
    })();
})();
```

https://psalm.dev/r/45578f4f02 :

```
Psalm output (using commit 4823e35):

INFO: MixedOperand - 12:9 - Left operand cannot be mixed

INFO: MixedArgument - 14:20 - Argument 1 of useCounter cannot be mixed, expecting int
```

**Comment by muglug** [comment]
Yeah this is a big ol’ wontfix from me. While this particular case is semi-reasonable, the semantics of by-ref assignment is reasonably impossible to reason about safely. There’s a good reason Facebook has pretty much completely removed it from their fork.

**Comment by Ocramius** [comment]
Works for me :+1:
