### ISSUE TITLE
query re: issue with max

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1820]
This is possibly a little more complicated than I thought, because `max()` accepts & processes a lot more than numerics o_O

I've got an issue whereby I'm treating `max()` as `max(T, ...T):T`, with what I would be hoping would be detected for `T as int`.

https://psalm.dev/r/a181337b14

```php
<?php
$files = [
  __FILE__,
  __FILE__,
  __FILE__,
  __FILE__,
];

$a = array_map('filemtime', $files);
$b = array_map(
  function (string $file) : int {
    return filemtime($file);
  },
  $files
);

$A = max(filemtime(__FILE__), ...$a);
$B = max(filemtime(__FILE__), ...$b);

echo date('c', $A), "\n", date('c', $B);
```
> Psalm output (using commit 5bb28cc): 
> 
> INFO: MixedAssignment - 17:1 - Cannot assign $A to a mixed type
> 
> INFO: MixedAssignment - 18:1 - Cannot assign $B to a mixed type
> 
> INFO: MixedArgument - 20:16 - Argument 2 of date cannot be mixed, expecting int
> 
> INFO: MixedArgument - 20:37 - Argument 2 of date cannot be mixed, expecting int

**Comment by weirdan** [comment]
`max(...T):T` is fine though:
```php
$b[] = filemtime(__FILE__);
$B = max( ...$b); // produces no errors
```

**Comment by SignpostMarv** [comment]
I'm having a poke around a solution for this, and it looks like `...$a` gets parsed with a php-parser index of `['unpack' => true]` and a psalm object-like of `array{0:int|false, 1:int|false,... n:int|false}`

Is there a sufficient utility to other psalm issues/to-dos for me to PR in a "from_variadic" property  on `Type\ObjectLike` ?

**Comment by SignpostMarv** [comment]
@orklah the error message changed a little since originally posted, it's still more in line with the 2020 comment: https://psalm.dev/r/a181337b14

**Comment by orklah** [comment]
Seems correct to me. What would you expect here?

**Comment by SignpostMarv** [comment]
That `$b` being arraymapped with `function (string $file) : int {` have it detected as `list<int>`, or `non-empty-list<int>` if it notices that `$files` has an unchanged size.

**Comment by SignpostMarv** [comment]
> $b is currently `array{int, int, int, int}<int>`: https://psalm.dev/r/b1c491bdd5 so it's even more precise than a list

except it's coming up as `array{int, int, int, int}<int>|false|int`

**Comment by SignpostMarv** [comment]
oh hang on a sec, confused by the context;

so here, `$b` has a known size of `array{int, int, int, int}`, but `$B` has `|false|int` tacked on the end; shouldn't it be `int|false` ?

**Comment by orklah** [comment]
oh, I think I see. Psalm did not destructure the array internally, so it thinks you will either get the array, int or false.

This should be pretty simple to fix in MinMaxReturnTypeProvider looking to `$arg->unpack` to know if there must be a destructuration somewhere
