### ISSUE TITLE
Error when trying to concatenate a string with a possibly null value

### ISSUE THREAD

**Issue by ste93cry** [vimeo/psalm#1823]
The given example throws an error saying `Cannot concatenate with a null`. According to [PHP documentation](https://php.net/manual/en/language.types.string.php#language.types.string.casting) a `null` value is always converted to an empty `string`, so it should not lead to any error. This may be something that the user wants to check of course, but should be valid behavior out-of-the-box

```php
$foo = null;

echo 'foo' . $foo;
```

https://psalm.dev/r/22093c9f0c

**Comment by muglug** [comment]
PHP allows a lot of things that Psalm prohibits, e.g.

```php
function foo(array $arr) : array {
  $ar["b"] = 5;
  return $arr;
}
```

It does so because (I decided) the behaviour might be undesirable. If you disagree it's very easy to suppress that issue via the config.

**Comment by ShiraNai7** [comment]
@muglug Which option did you mean? Or was it @psalm-suppress?

I find it a bit inconsistent that `$x = null; $x[] = 'item';` is allowed but `$x = null; $x .= 'string';` is not.

https://psalm.dev/r/0f611294ec

**Comment by muglug** [comment]
> I find it a bit inconsistent that `$x = null; $x[] = 'item';` is allowed

you're right, that probably shouldn't be allowed.

> Suppressing PossiblyNullOperand seems to work. A possible caveat is that it affects other operators as well.

I _think_ all other operators implicitly work with `null`, too (but don't quote me on that)

**Comment by ShiraNai7** [comment]
I've done a few quick tests with `null`. All operators seem to be ok, except for:

- `~` emits a warning with `null`, Psalm raises `PossiblyInvalidOperand`
- `+` throws an exception when trying to union an array with `null`, Psalm raises `PossiblyNullOperand`

So there are some edge cases where suppressing `PossiblyNullOperand` might hide potential crashes, not just silent fallbacks to blank values (`""`, `0`).
