### ISSUE TITLE
Closure docblocks get corrupted when re-analysing

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#1824]
https://psalm.dev/r/5cf354ad0b

```php
class Event {}
class Breadcrumb {}

class C {
  /** @var string */
  public $i;
  
  public function __construct() {
    [
      'before_send' => function (Event $event): Event {
        return $event;
      },
      'before_breadcrumb' => function (Breadcrumb $breadcrumb): Breadcrumb {
        return $breadcrumb;
      },
    ];
    
    $this->i = "hello";
  }
}
```

Expected: no issue
Actual: MismatchingDocblockParamType

cc @ste93cry, code seen in `sentry-php`

**Comment by muglug** [comment]
Fixed in db38270a6aed9e838b92a92bb0ab78c07e5f5c5b

**Comment by ste93cry** [comment]
Wow, so fast at fixing the bug! Thank you for the hard work

**Comment by muglug** [comment]
> Wow, so fast at fixing the bug

I wish! It took about 30 minutes - bugs around references to objects are a _pain_ to debug (but very satisfying to fix).
