### ISSUE TITLE
ArgumentTypeCoercion infers parent rather than child type

### ISSUE THREAD

**Issue by andrewmy** [vimeo/psalm#1828]
When a parent class returns `new static`, the return type is actually the child type, and PHP agrees: https://3v4l.org/S1jQe

However Psalm does not: https://psalm.dev/r/8f8cc7dd77

**Comment by andrewmy** [comment]
Added a `@return static` docblock, the issue disappears. Not sure if this is the designed behaviour.

**Comment by muglug** [comment]
Yup, this is by design - when calling the method Psalm sees only the declared return type, not the contents of the method (which would tell it the return type is more specific). Hack even has a special return type `: this` for this use-case.
