### ISSUE TITLE
LSP: Jump to definition for docBlock types

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#1832]
Currently jump to definition doesn't work for type hints in docBlocks. Since many types are currently only expressible in docBlocks it would be nice if jump to definition would work for those too.

**Comment by muglug** [comment]
This requires the retention of offset positions when parsing types. Getting it working on types that contain newlines would be an additional challenge.

**Comment by iluuu1994** [comment]
This doesn't seem to work for me just yet. I cleared the cache but no luck. Can I provide any debugging information?

**Comment by muglug** [comment]
Fixed to add reference rather than type.

This doesn’t work in Sublime because the plugin doesn’t recognise docblocks as symbols, but does in VS Code.

**Comment by muglug** [comment]
766b1b0 had the fix

**Comment by iluuu1994** [comment]
Works! Thanks man!
