### ISSUE TITLE
LSP: Jump to definition doesn't work when method call contains an error

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#1835]
<img width="469" alt="Screen Shot 2019-06-23 at 13 07 10" src="https://user-images.githubusercontent.com/1752683/59975371-e11f7600-95b7-11e9-8c52-4f5e98c17844.png">

In this case a parameter is missing. Only when the parameter is added does "Jump to definition" work as expected. The same goes for the hover popover.

**Comment by iluuu1994** [comment]
Fantastic! Thanks @muglug!

**Comment by muglug** [comment]
Fixed to add reference rather than type.

This doesn’t work in Sublime because the plugin doesn’t recognise docblocks as symbols, but does in VS Code.
