### ISSUE TITLE
Add support for marking variable as const

### ISSUE THREAD

**Issue by bustbr** [vimeo/psalm#1840]
Hi,

this is a feature request.

I think it would be useful to be able to mark any local variable as final (or const). PHP itself does not support this and as far as I know there are no plans to change it in the foreseeable future (no RFC).

A simple example:
```php
function waitFor(int $timeInMilliseconds): void;

function doSomethingPeriodically(): void {
    /** const */ $oneMinute = 60000;
    while (true) {
        doSomething();
        waitFor(5 * $oneMinute);
    }
}
```

I never want the value of `$oneMinute` to change, its only purpose here is to improve readability. If some code was added that changed the value of that variable it would be by accident and it would be very useful for this to pop up as an error.

**Comment by muglug** [comment]
why not just use a `private CONST ONE_MINUTE = 60000`?

**Comment by bustbr** [comment]
> why not just use a `private CONST ONE_MINUTE = 60000`?

that would only work for functions in a class context, not plain old functions, and would also make the const more visible than it needs to be – to all methods of that class and not only the one that uses it.

**Comment by muglug** [comment]
I understand, but given that most behaviour takes place in methods (vs. flat files), and constants do exist in the language already (albeit in some slightly less ergonomic ways) I’m going to close this.

**Comment by bustbr** [comment]
> given that most behaviour takes place in methods (vs. flat files)

We have some projects where this is not true at all, because the attached team tries to go towards a more functional approach with leaner classes without any internal state. To avoid classes that only consist of static functions we instead use classes simply as data structs and have plain functions operate on this data.

> I’m going to close this.

Is it that you don't see the use in this at all, or do you think the work required to implement this in Psalm is not worth it?
I haven't looked at the implementation of Psalm yet, but if you think the feature could eventually be included I'd be glad to give it a go.

As for the notation I'd suggest `@const` where ever `@var` is allowed right now.
As an extension we could also add `@final`, but I'd leave that out for now, because it seems more complicated to me.

### aside on `const` vs. `final`
`const` would mean that when a symbol is declared it would also have to be assigned a value and any further assignment to that symbol would be an offense; `final` could mean the symbol may be declared only (which in PHP I would translate to mean initialized with a value of `null`) and then assigned a value exactly once.

### code example
```php
/** @const int $foo */
$foo = 23; // ok
$foo = 32; // error
$foo *= 2; // error
$foo = 23; // error

/** @const ?int $bar */
$bar = null; // ok
$bar = 23; // error
$bar = null; // error

/** @final int $baz */
$baz = 23; // ok
$baz = 32; // error

/** @final ?int $qoo */
$qoo = null; // ok
$qoo = 23; // ok
$qoo = 32; // error
$qoo = null; // error
```

**Comment by muglug** [comment]
> We have some projects where this is not true at all, because the attached team tries to go towards a more functional approach with leaner classes without any internal state. To avoid classes that only consist of static functions we instead use classes simply as data structs and have plain functions operate on this data.

I'm happy that works for you, and I don't want to discourage you from using the language however you want. Nevertheless, the vast majority of PHP is written with classes (vs files) as the dominant way of organising similar functionality, and Psalm is heavily tailored to that use-case.

> Is it that you don't see the use in this at all, or do you think the work required to implement this in Psalm is not worth it?

I definitely don't see the value for the PHP codebases I spend every day looking at, but I understand how it might have value to you.

If you want to add this functionality to Psalm, I'd encourage you think about a `@psalm-immutable` annotation above an assignment which would have the same basic effect, but couldn't be confused with actual constants. That `@psalm-immutable` annotation could eventually be expanded to work with class properties too.
