### ISSUE TITLE
LSP: Signature Help

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#1841]
I've been investigating on how to implement the `SignatureHelp` API. Can you give me a few pointers? It's pretty similar to `Hover`. The main challenge is that `Codebase::getReferenceAtPosition` can't be used because it only records the position of the identifier (excluding the parentheses). Furthermore we need to not only know which method is being called but also at what parameter the cursor is at.

**Comment by muglug** [comment]
What do you want exactly? Something like `Codebase::getFunctionArgumentAtPosition` that returns the method id and arg offset? Or do you also need the arg name?

**Comment by iluuu1994** [comment]
Yeah something like that. So I should probably extend `Analyzer` to store the parameters in a `$parameter_map`, right?

**Comment by muglug** [comment]
Yeah, the general idea being that all these maps are cached, and only updated/invalidated when individual methods are changed. Which is to say I think this would only work for methods, not functions (at the moment at least)

**Comment by iluuu1994** [comment]
Cool, I'll give that a shot.

**Comment by iluuu1994** [comment]
This is not quite as easy to implement as I thought. The main issue is that the whitespace and `,` argument separator tokens are just thrown away by the parser. Currently I'm looking for the next `,` after the arguments `getEndFilePos`. This can be quite easily fooled with a comment:

<img width="1010" alt="Screen Shot 2019-06-25 at 23 41 27" src="https://user-images.githubusercontent.com/1752683/60135794-c9f0ac00-97a2-11e9-9576-76db1c3cb3eb.png">

We could use `token_get_all` here but I wanted to avoid tokenizing again.

There are other issues too. The parser is not as fault tolerant as I'd like. For example, more than one trailing comma results in the entire method call missing in the AST:

```php
$this->foo($foo,,); // Poof!
```

Thus the argument positions won't be recorded and you'll get no signature help.

Kind of a bummer, those are likely not easily fixable.

**Comment by muglug** [comment]
> This can be quite easily fooled with a comment

Yeah, it's not the best, but it wouldn't be too hard to add some functionality that detects comments - I have [this code block](https://github.com/vimeo/psalm/blob/904267638f59c798cfd2d1a75987681b12bd7276/src/Psalm/Internal/FileManipulation/FunctionDocblockManipulator.php#L137-L218) that could probably be extracted and reused.

> For example, more than one trailing comma results in the entire method call missing from the AST

I've ticketed that here: https://github.com/nikic/PHP-Parser/issues/616, but I'm not sure it's a blocker - I think the usability benefit of this massively outweighs the edge-case annoyance.

**Comment by iluuu1994** [comment]
In that case I think I'll just use `token_get_all` after all. The only thing that needs to be tokenized is the source code from the `getEndFilePos` of the previous argument to the `getStartFilePos` of the next argument.

> I've ticketed that here

Thanks!
