### ISSUE TITLE
Fatal error if comment has asterisk

### ISSUE THREAD

**Issue by bgpastukh** [vimeo/psalm#1844]
Hello, required swagger-php and now psalm fails because of this line https://github.com/zircote/swagger-php/blob/2.x/src/Annotations/Swagger.php#L184
Who should fix this problem? Or can i skip this file during analyze?

**Comment by muglug** [comment]
Sorry - I'll just fix and release tonight

**Comment by muglug** [comment]
Actually this is a dupe of https://github.com/vimeo/psalm/issues/1730, and should be fixed in the two most recent releases
