### ISSUE TITLE
No report invalid return type if use template

### ISSUE THREAD

**Issue by vadim2991** [vimeo/psalm#1845]
```php
<?php
 
/**
 * @template T
 * @psalm-param T $t
 * @return T
 */
function mirror($t) {
    return 'string';
}

$a = 5;
$b = mirror(5);
$c = "foo";
$d = mirror($c);
```
Expected: InvalidReturnStatement and InvalidReturnType errors
Actual : No issues
https://psalm.dev/r/84363ebfd4

**Comment by muglug** [comment]
Yeah, this check is currently suppressed for non-objects to allow default values for template params.
