### ISSUE TITLE
"no hyphens allowed in docblock" in array shape declaration

### ISSUE THREAD

**Issue by ste93cry** [vimeo/psalm#1852]
The following code produces an error saying `InvalidDocblock - 8:1 - no hyphens allowed in docblock for foo`

```php
/**
 * @psalm-return array{
 *     foo: non-empty-string
 * }
 */
function foo(): array
{
    return [
        'foo' => Exception::class
    ];
}
```

The problem is the `non-empty-string` word. However, `class-string` (which contains a dot too) for some reason works

https://psalm.dev/r/4e7a2f3447 vs https://psalm.dev/r/c6b8f43569

**Comment by SignpostMarv** [comment]
one gets slightly different results if `non-empty-string` is applied to a psalm type first, although the original bug is still there:

https://psalm.dev/r/d305e387c5
```php
<?php

/**
 * @psalm-type T = non-empty-string
 * @psalm-return array{foo: T}
 */
function foo(): array
{
  return [
  	'foo' => Exception::class
  ];
}
```
> ERROR: InvalidDocblock - 7:1 - no hyphens allowed
> 
> ERROR: InvalidReturnStatement - 9:10 - The type 'array{foo: Exception::class}' does not match the declared return type 'array{foo: T}' for foo
> 
> ERROR: InvalidReturnType - 5:18 - The declared return type 'array{foo: T}' for foo is incorrect, got 'array{foo: class-string}'

**Comment by muglug** [comment]
`non-empty-string` isn’t a type that Psalm recognises - but I agree the message is confusing

**Comment by SignpostMarv** [comment]
@muglug how would you feel about `non-empty<string>`, `non-empty<array>`, `non-empty<object>`, mostly just so one could `non-empty<T>`?

**Comment by muglug** [comment]
> how would you feel about `non-empty<string>`, `non-empty<array>`, `non-empty<object>`, mostly just so one could `non-empty<T>`?

Not great - I don't want to make that general if I can help it.
