### ISSUE TITLE
 LSP coc.nvim failing

### ISSUE THREAD

**Issue by gitbugr** [vimeo/psalm#1855]
I'm trying to set up psalm with [coc.nvim](https://github.com/neoclide/coc.nvim), but the language server is closing for some reason on initialisation:

I've installed psalm globally with composer, and this is my config:

```
call coc#config('languageserver', {
\  'psalm-language-server': {
\     'command': '~/.composer/vendor/bin/psalm-language-server',
\     'trace.server': 'verbose',
\     'filetypes': ['php']
\   }
\ }:
```

Here is the trace log:
https://gist.github.com/gitbugr/aed261322d40d7a930736e645b326eb0

**Comment by muglug** [comment]
What happens when you run `~/.composer/vendor/bin/psalm-language-server` on its own (outside of `vim`)

**Comment by gitbugr** [comment]
@muglug nothing (providing `psalm --init` was run in the cwd). The process stays open until I kill it with `^C`. I get nothing back if I fire random input at it

**Comment by muglug** [comment]
And to state the obvious, Psalm runs fine on the codebase?

**Comment by muglug** [comment]
Oh! What if you run `psalm --threads=8`?

**Comment by gitbugr** [comment]
psalm does run fine on the codebase, yes.

Awesome! `psalm --threads=8` returned this:
```
Scanning files...
Mac users: pcre.jit is set to 1 in your PHP config.
The pcre jit is known to cause segfaults in PHP 7.3 on Macs, and Psalm
will not execute in threaded mode to avoid indecipherable errors.
Consider adding pcre.jit=0 to your PHP config.
Relevant info: https://bugs.php.net/bug.php?id=77260
```

and updating my php.ini located at `/usr/local/etc/php/7.3/php.ini` to the suggested fixed the issue!

Thanks @muglug !

**Comment by gitbugr** [comment]
I would suggest adding that to the readme / installation docs. Would've saved everyone a bit of time. :)

**Comment by muglug** [comment]
> I would suggest adding that to the readme / installation docs

I've added it as a message every time you run Psalm!
