### ISSUE TITLE
Psalm doesn't realize that null > 0 will return false

### ISSUE THREAD

**Issue by nickyr** [vimeo/psalm#186]
Paste this into getpsalm.org:

```php
<?php
/**
 * @return int|null
 */
function foo() {
    return mt_rand(0, 1) ? 3 : null; 
}

$bar = foo();
if ($bar > 0) {
 echo $bar + 3; 
}
```

and you get

![image](https://user-images.githubusercontent.com/1389687/28127014-3613dee8-66f9-11e7-8528-50a8c07c063c.png)

Psalm does not realize that `(null > 0)` is false so it doesn't actually need to evaluate `echo $bar + 3;` in that case.

**Comment by muglug** [comment]
Hack doesn't do this, so I'm too lazy to implement it. But you can!

We find all an expression's assertions in [AssertionFinder::getAssertions](https://github.com/vimeo/psalm/blob/17205bc093ef73948b24a9d6d442184ad1bce00f/src/Psalm/Checker/Statements/Expression/AssertionFinder.php#L30)

**Comment by muglug** [comment]
I got less lazy.

The check is only reliable for `$bar > 0` and `0 < $bar`. Otherwise you get funny results:
```php
var_dump(1 > null); // true
var_dump(0 > null); // false
var_dump(-1 > null); // true

var_dump(1 < null); // false
var_dump(0 < null); // false
var_dump(-1 < null); // false

var_dump(null > 1); // false
var_dump(null > 0); // false
var_dump(null > -1); // false

var_dump(null < 1); // true
var_dump(null < 0); // false
var_dump(null < -1); // true
```

**Comment by nickyr** [comment]
Yesss I love the do nothing and wait for matt to fix it strategy
