### ISSUE TITLE
False positive when passing mixed types into methods in 3.4.6

### ISSUE THREAD

**Issue by jaikdean** [vimeo/psalm#1861]
In 3.4.5 [this example](https://psalm.dev/r/2ed6c33f4f) raised no errors. I understand from the info messages that the template annotations are wrong/incomplete, so the type of `$foo` is `mixed`. However, the error this results in is misleading at best.

**Comment by jaikdean** [comment]
This is fixed [with additional template tags on the implementation](https://psalm.dev/r/a2e516a7f7), though requiring those feels like a bug to me. I'm happy to be told otherwise :)

**Comment by muglug** [comment]
Psalm was correct to complain, this should be fine: https://psalm.dev/r/988e4f483a
