### ISSUE TITLE
Constant's array-key as class-string with interfaces

### ISSUE THREAD

**Issue by rickogden** [vimeo/psalm#1864]
An interesting scenario. If you have a constant which is an array that uses a class-string as an array key. When you use \get_class() on a variable type-hinted as "object" to retrieve the value from the constant array, it it works fine: https://psalm.dev/r/8aa39b9382

However, if you type-hint an object as an interface and use \get_class() on that, it gets flagged as:
> InvalidArrayOffset - 19:6 - Cannot access value on variable using a class-string offset, expecting `class list`

https://psalm.dev/r/02fef440e4

I assume psalm is being too clever as it already knows what classes to expect, but the behaviour seems inconsistent.

**Comment by muglug** [comment]
So first-off the `@var` on the `const` declaration has no effect, so you're really comparing 
 https://psalm.dev/r/3c46368407 with https://psalm.dev/r/9cfa4c9f2f

This is really the error that's happening: https://psalm.dev/r/060bf5a5aa, and it's correct behaviour by Psalm - other classes might implement `I`, too.

**Comment by muglug** [comment]
Your particular example can be fixed with a more specific docblock on `getObject()`: https://psalm.dev/r/c889884bc5
