### ISSUE TITLE
Psalm doesn't tolerate punctuation immediately after property name in comment

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#1868]
Expected: Should parse the part of the property name that's a valid identifier. Possibly warn about unexpected punctuation that was ignored.
Observed: Fails to infer the existence of $bar because of the semicolon

I forget if there are similar open issues - I didn't find any

```php
<?php

/**
 * @property-read int $foo has no semicolon
 * @property-read int $bar; has semicolon
 * @psalm-seal-properties
 */
class Magic {
    public function __get(string $x) {
        return strlen($x);
    }
}
$m = new Magic();
var_export($m->foo + $m->bar);
```

**Comment by muglug** [comment]
Fixed in 83fe3a2
