### ISSUE TITLE
Return type when using abs()

### ISSUE THREAD

**Issue by ssnepenthe** [vimeo/psalm#187]
I'm not really sure what to make of this one...

Given the following functions:

```
function abs_int(int $value) : int
{
  return abs($value);
}

function abs_float(float $value) : float
{
  return abs($value);
}
```

Psalm reports the following:

```
ERROR: InvalidReturnType - test.php:3 - The declared return type 'int' for abs_int is incorrect, got 'int|float'
```

According to the docs, `abs()` returns float when given a float, otherwise it returns int, so technically I believe both functions have the correct return type.

It would make sense if psalm expected a return type of `int|float` for both functions. I guess the inconsistency between the two functions is what is throwing me. Maybe I am missing something?

**Comment by muglug** [comment]
Thanks for the testcase!

**Comment by ssnepenthe** [comment]
No problem. Thanks for the quick responses - you rock!
