### ISSUE TITLE
Update 3.4.4 has broken splat usage in constructors

### ISSUE THREAD

**Issue by 2e3s** [vimeo/psalm#1873]
It thinks that `EntityTags::$tags` has a type `Tag` instead or `array<Tag>`
```php
final class EntityTags
{
    private $tags;

    public function __construct(Tag ...$tags)
    {
        $this->tags = $tags;
    }

    /**
     * @return Tag[]
     */
    public function getTags(): array
    {
        return $this->tags;
    }
}
```
```
ERROR: InvalidReturnType - EntityTags.php:31:16 - The declared return type 'array<array-key, Tag>' for EntityTags::getTags is incorrect, got 'Tag'
     * @return Tag[]

ERROR: InvalidReturnStatement - EntityTags.php:35:16 - The type 'Tag' does not match the declared return type 'array<array-key, Tag>' for EntityTags::getTags
        return $this->tags;
```
PHPStorm infers the type correctly.
I have to use version 3.4.3 to keep this working. There is supposedly `inferPropertyTypesFromConstructor` but this seems to be absent in the XML scheme?

**Comment by muglug** [comment]
Sorry, will fix momentarily - in the meantime you can work around the problem by adding a `/** @var Tag[] */` docblock to the property

**Comment by 2e3s** [comment]
It's a part of our code style: omit docblocks which can be inferred in the constructors :smile:

**Comment by muglug** [comment]
Code now works as expected: https://psalm.dev/r/b4e5f23e6d
