### ISSUE TITLE
query re: badly-formed return

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1877]
A blank return tag is not considered badly-formatted, one would expect it to be.

https://psalm.dev/r/83e59b6d75
```php
<?php
/**
* @return
*/
function foo() : void {}

/**
* @param
*/
function bar(string $bar) : void {
  echo $bar;
}
```
> Psalm output (using commit 791b30a): 
> 
> ERROR: InvalidDocblock - 10:1 - Badly-formatted @param in docblock for bar

**Comment by muglug** [comment]
Psalm just ignores it - happy to continue that behaviour (but would accept a PR to update)
