### ISSUE TITLE
MissingReturnType when checking entire codebase, not when checking single file

### ISSUE THREAD

**Issue by ssnepenthe** [vimeo/psalm#188]
The project is here: https://github.com/ssnepenthe/color-utils

When I run `./vendor/bin/psalm` I get the following:

```
INFO: MissingReturnType - inc/helpers.php:63 - Method _color_args_probably_contain_extra_arg does not have a return type, expecting bool
```

When I run `./vendor/bin/psalm inc/helpers.php` there is nothing.

**Comment by muglug** [comment]
Oh are you on latest master? That sounds a bit like https://github.com/vimeo/psalm/issues/182

**Comment by ssnepenthe** [comment]
Nope - was on latest tag, switching to master seems to fix it - sorry about that.

**Comment by muglug** [comment]
No worries!
