### ISSUE TITLE
Sort the use statements for functions/constants in Psalm?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#1880]
e.g. in src/Psalm/Type/Reconciler.php

```
use function strpos;
use function array_shift;
use function ksort;
use function substr;
use function implode;
use function array_map;
use function is_string;
use function array_filter;
```

The slevomat/coding-standard can be used with `phpcbf` to sort function uses automatically. An example config section that could be used is https://github.com/phan/phan/blob/master/phpcs.xml#L15-L19

Motivation: Merge conflicts (e.g. duplicate uses) are more likely when function/constant uses are unordered

**Comment by TysonAndre** [comment]
https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#3-declare-statements-namespace-and-import-statements (the draft extended coding style guide) was more of what I had in mind, and looked cleaner to me, but sorting everything alphabetically still meets the goal of avoiding merge conflicts

> - One or more class-based use import statements.
> - One or more function-based use import statements.
> - One or more constant-based use import statements.

**Comment by muglug** [comment]
For whatever reason the fixer didn’t arrange them that way :shrug:
