### ISSUE TITLE
After 50 entries in a constant, `@param key-of<Some::CONST_NAME>` is ignored

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#1881]
While testing https://github.com/Ocramius/PackageVersions/issues/90, I found out that psalm would not kick in at all while verifying key existence in larger arrays.

Specifically, https://psalm.dev/r/2c763f4202 passes, while https://psalm.dev/r/dd67416f3c seems to fail.

The limit of 50 entries was probably introduced to avoid proliferation of extremely long union type operations, but in this case it prevents usage of `key-of` on the component, since the check will effectively be completely skipped.

**Comment by muglug** [comment]
One solution is an annotation like `@psalm-preserve-keys` for class constant arrays where Psalm should ignore the limit

**Comment by Ocramius** [comment]
Are the keys removed in initial steps? If so, then yes, that would help

**Comment by muglug** [comment]
yeah the limit happens here: https://github.com/vimeo/psalm/blob/220fa31404ccc46a934a5a328388b3d7f19bc383/src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php#L149-L168

**Comment by Ocramius** [comment]
What's the side-effect of completely removing that `count()` limit?

This acts on hardcoded maps anyway, no?

**Comment by muglug** [comment]
Psalm has a few very large arrays e.g. https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/CallMap.php, and I imagine other codebases have similar arrays in places. No need to bloat memory with mostly-unnecessary data.

**Comment by Ocramius** [comment]
I see, so we'd indeed need to whitelist the cases where the keys are necessary. I think 50 as a limit is very low though: wouldn't generated data always have thousands of keys?

**Comment by muglug** [comment]
The `keys-of<...>` annotation was not designed for generated data (I didn’t have this use case in mind when adding) - it’s intended for small enum-like constant arrays, or arrays specified in a template.

That’s why an annotation that tells Psalm to store the keys anyway would come in handy.

**Comment by Ocramius** [comment]
Yep, I nay indeed be misusing this...

**Comment by muglug** [comment]
Well, it’s just a use-case I hadn’t thought of. But I think an annotation to specifically preserve keys is still necessary.

In terms of annotations there are a couple of options - `@psalm-preserve-array-data` could preserve, key types, value types AND associativity, `@psalm-preserve-array-keys` would preserve array keys, ditching associativity, and `@psalm-preserve-array-values` would preserve values, ditching associativity.

**Comment by Ocramius** [comment]
@muglug is the code location mentioned above (https://github.com/vimeo/psalm/issues/1881#issuecomment-507046505) all that's needed to be touched? I can give it a try once I free myself a bit :)

**Comment by muglug** [comment]
It's also this: https://github.com/vimeo/psalm/blob/96ba4ad7d38af2ab05e4818d82283c42c9215a43/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php#L1358-L1393, which is a little more relevant for the reflection stage.
