### ISSUE TITLE
expects string, int provided

### ISSUE THREAD

**Issue by thomasbley** [vimeo/psalm#1882]
Since PHP can handle int to string conversion implicitly, is there any option to disable errors for this specific case?

test.php
```
<?php
urlencode(42);
```
gives for psalm 3.4.7:
```
ERROR: InvalidScalarArgument - test.php:2:11 - Argument 1 of urlencode expects string, int(42) provided
urlencode(42);
```

**Comment by weirdan** [comment]
You can suppress it for the specific line with docblock (https://psalm.dev/r/c81626c258) or for entire project with [psalm.xml config options](https://github.com/vimeo/psalm/blob/7a1a728cee205457aba841023ce1259368bb920b/docs/running_psalm/dealing_with_code_issues.md#config-suppression).

**Comment by muglug** [comment]
Future versions of PHP will probably behave differently, as well - this is intended behaviour (though you can suppress as @weirdan notes)
