### ISSUE TITLE
query re: mismatched parent method call

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1889]
Have just had a chunk of code commit an infinite loop that passed phpunit, psalm, & php-cs-fixer without issue.

I'm wondering if it's possible for psalm to have a mismatched parent method call error for circumstances when you have `parent::Foo();` in the method body of `Bar::Baz()` ?

Personally, there are a few times when I've deliberately called a different parent method, but I'm going to hazard a guess that throwing up an error would've helped me catch this earlier :D

example:
https://psalm.dev/r/3da74ad93a
```php
<?php
class Foo {
  public function Bar() : void {
    echo __METHOD__, "\n";
    
    $this->Baz();
  }
  
  protected function Baz() : void {
    echo __METHOD__, "\n";
  }
}

class Foo2 extends Foo {
  protected function Baz() : void {
    parent::Bar(); // requesting this call to raise a mismatched parent method call error
  }
}
```

***edited to add example***

**Comment by muglug** [comment]
Basically not possible to catch - you could develop a simple heuristic for obvious cases like this, but otherwise this gets into the realm of the undecidable.
