### ISSUE TITLE
Recursive array type not validated

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1892]
Code:
```php
<?php

/**
* @psalm-type recursiveData array<string, string|recursiveData> 
*
* @return recursiveData
*/
function foo(): array {
    return ['id' => 'bar', 'key' => ['baz' => 'fred']];
}
```

Actual output at https://psalm.dev/r/d19ae42a39
```
Psalm output (using commit 5c76b3c):

ERROR: InvalidReturnStatement - 8:12 - The type 'array{id: string(bar), key: array{baz: string(fred)}}' does not match the declared return type 'array<string, string|recursiveData>' for foo

ERROR: InvalidReturnType - 5:13 - The declared return type 'array<string, string|recursiveData>' for foo is incorrect, got 'array{id: string, key: array{baz: string}}'
```

Expected output:
```
No issues!
```

**Comment by muglug** [comment]
Recursive types aren’t supported by Psalm (and probably won’t ever be tbh)

**Comment by SignpostMarv** [comment]
slap it on hacktoberfest for giggles ?

**Comment by sukei** [comment]
> Recursive types aren’t supported by Psalm (and probably won’t ever be tbh)

Is there any reason not to allows it? (design, philosophy, etc.)

**Comment by orklah** [comment]
> > Recursive types aren’t supported by Psalm (and probably won’t ever be tbh)
> 
> Is there any reason not to allows it? (design, philosophy, etc.)

Implementation would be pretty complex, that's about it I think
