### ISSUE TITLE
Allow dynamic checking of docblock types

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1893]
This may not be something Psalm should do, but perhaps could be a separate tool that could use part of Psalm code.

Since many codebases are not [TotallyTyped](https://psalm.dev/docs/running_psalm/configuration/), and libraries that are developed using psalm may be depended on by code that is not checked with Psalm, there are cases where it's useful to do a check at runtime to ensure passed params match a type declared in a docblock.

So it might be useful to have a function that can use the runtime values of parameters, and perhaps also a variable to be returned, and read the declared types from the docblock and check if they match.

Not sure how realistic this is.

**Comment by andrew-demb** [comment]
https://github.com/Roave/you-are-using-it-wrong

**Comment by bdsl** [comment]
@andrew-demb you-are-using-it-wrong is probably a good alternative to this in many cases, but it I don't think it makes this entirely obsolete, particularly as seven of the eight [psalm config levels](https://github.com/vimeo/psalm/tree/master/assets/config_levels) have `totallyTyped="false"`

Even with a totally typed codebase I can imagine wanting to use this, for instance when something is typed as an enum using with `key-of` or `value-of` an array, persisted to a db, and then pulled out again.

**Comment by muglug** [comment]
This is basically what assertion libraries are for, and `@psalm-assert` annotations can help you understand those. Feel free to create a special assertion library that does something like `assertType('array<int, string>')` - I'd be happy to build a compatible annotation for it.
