### ISSUE TITLE
possible issue with traited/templated return types

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1902]
* reduced example: https://psalm.dev/r/d936482598
* verbose example: https://psalm.dev/r/51ad5ec95b

```php
<?php
/**
* @template HTTP_METHOD as 'GET'|'POST'|'CONNECT'|'DELETE'|'HEAD'|'OPTIONS'|'PATCH'|'PURGE'|'PUT'|'TRACE'
*/
interface Foo {
  /**
  * @return HTTP_METHOD
  */
  public static function DefaultHttpMethod() : string;
}

trait WithoutDocs {
  public static function DefaultHttpMethod() : string {
    return 'GET';
  }
}

/**
* @template-implements Foo<'GET'>
*/
class Bar implements Foo {
  use WithoutDocs;
}

/**
* @template-implements Foo<'GET'>
*/
class Baz implements Foo {
  public static function DefaultHttpMethod() : string {
    return 'GET';
  }
}

/**
* @template-implements Foo<'POST'>
*/
class Bat implements Foo {
  public static function DefaultHttpMethod() : string {
    return 'POST';
  }
}
```
> Psalm output (using commit 6dd549b): 
> 
> ERROR: LessSpecificImplementedReturnType - 13:48 - The return type 'HTTP_METHOD as string(GET)|string(POST)|string(CONNECT)|string(DELETE)|string(HEAD)|string(OPTIONS)|string(PATCH)|string(PURGE)|string(PUT)|string(TRACE)' for Foo::DefaultHttpMethod is more specific than the implemented return type for WithoutDocs::defaulthttpmethod 'string'

**Comment by SignpostMarv** [comment]
this is still erroring out on psalm.dev?

**Comment by muglug** [comment]
Yeah, my example didn't have return typehints, sorry - reproduced more succinctly here: https://psalm.dev/r/f03f0f154c

**Comment by muglug** [comment]
The fix for your use-case is just to remove the `: string` typehints. I'm not going to fix this in a more robust manner, as it's a very edge-case and would require a lot of work.

**Comment by SignpostMarv** [comment]
I should mention that a workaround that sort of works is to pass in a template of `'GET'|'GET'` but then it gets confused for other reasons.

**Comment by muglug** [comment]
without the typehints: https://psalm.dev/r/03872e2811

**Comment by SignpostMarv** [comment]
with the workaround: https://psalm.dev/r/3fe28f074d
> Psalm output (using commit 422d994): 
> 
> ERROR: ImplementedReturnTypeMismatch - 14:13 - The return type 'HTTP_METHOD as string(GET)|string(POST)|string(CONNECT)|string(DELETE)|string(HEAD)|string(OPTIONS)|string(PATCH)|string(PURGE)|string(PUT)|string(TRACE)' for Foo::DefaultHttpMethod is different to the implemented return type for WithoutDocs::defaulthttpmethod 'string(GET)'
