### ISSUE TITLE
Metadata from @method disappears in the children interfaces

### ISSUE THREAD

**Issue by 2e3s** [vimeo/psalm#1903]
### Description

Children lose parent's structural metadata which is given by `@method`. I think this isn't a logical behaviour if we allow extending interfaces with `@method` at all.
```php
interface ClassMetadata {}
interface ORMClassMetadata extends ClassMetadata {}

interface EntityManagerInterface {
    public function getClassMetadata() : ClassMetadata;
}
/**
 * @method ORMClassMetadata getClassMetadata()
 * @method int getOtherMetadata()
 */
interface ORMEntityManagerInterface extends EntityManagerInterface{}
interface ConcreteEntityManagerInterface extends ORMEntityManagerInterface {}

function em(): ORMEntityManagerInterface {}
function concreteEm(): ConcreteEntityManagerInterface {}

function test(ORMClassMetadata $metadata): void {}
function test2(int $metadata): void {}

test(em()->getClassMetadata());
test(concreteEm()->getClassMetadata()); // error 1, LSP violation

test2(em()->getOtherMetadata());
test2(concreteEm()->getOtherMetadata()); // error 2, method doesn't exist
```
```
ERROR: ArgumentTypeCoercion - 42:6 - Argument 1 of test expects ORMClassMetadata, parent type ClassMetadata provided
ERROR: UndefinedInterfaceMethod - 45:21 - Method ConcreteEntityManagerInterface::getothermetadata does not exist
```
https://psalm.dev/r/f38ce27a6b
Setting `usePhpDocMethodsWithoutMagicCall` to `true` and `false` changes nothing.
Replacing interfaces with `class` fixes the issue (but I can't apply such a fix).

What would be the expected behaviour here? Is it a valid bug?

### Use case

The current problem is with Doctrine's usage https://github.com/doctrine/orm/commit/45e733eb607032374e1519cb7d9437456d2d077c
We override `Doctrine\ORM\EntityManagerInterface` and it gets the returned value from `Doctrine\Common\Persistence\ObjectManager` (the parent interface).

I feel like it may be related to my failed attempt to stub this method of `EntityManagerInterface` at  https://github.com/2e3s/doctrine-psalm-plugin/pull/1 - I didn't use any inheritance there but neither could I overwrite the definition of `@method getClassMetadata()` from `EntityManagerInterface`.

**Comment by muglug** [comment]
It was a bug, now fixed!
