### ISSUE TITLE
Climb directory tree to find config file

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1905]
Once #1524 is resolved, so that psalm can be run from any working directory as long as the appropriate `--config` options is provided, it might be a good convenience feature to allow running psalm from any sub-directory of the location of psalm.xml without having to explicitly specify the config location.

This is similar to how git works, when run from any subdirectory of the repository.

Possibly in the case where psalm.xml is found by directory climbing and has no explicit setting for resolving files from the psalm.xml location instead of working directory that behaviour should be switched on by default.

**Comment by weirdan** [comment]
@bdsl isn't it done already?

**Comment by weirdan** [comment]
It is.
