### ISSUE TITLE
Crash with PHP Fatal Error on invalid/broken composer.json

### ISSUE THREAD

**Issue by theseer** [vimeo/psalm#1907]
When syntactically breaking `composer.json`, for instance by removing a closing `}` or `,` on a list, `psalm` crashes:

```
theseer@nyda ~/storage/php/phar.io/manifest master $ ./tools/psalm 
PHP Fatal error:  Uncaught UnexpectedValueException: Invalid composer.json at /home/theseer/storage/php/phar.io/manifest//composer.json in phar:///home/theseer/.phive/phars/psalm.phar/src/command_functions.php:98
```

While the error obviously is detected and the shown error message is quite clear, it's an Uncaught Exception never the less..

**Comment by muglug** [comment]
Thanks!
