### ISSUE TITLE
Inline "conditional" @var annoation gets ignored

### ISSUE THREAD

**Issue by theseer** [vimeo/psalm#1908]
When using an inline `/** @var Type $name` conditionally as follows, `psalm` seems to ignore the annotation:

```php
//...

class FooType extends Type { ... }

// ...

case $type->isFoo(): 
    /** @var FooType $type */

    // ...

    $other->someMethod($type->methodOnlyExistingInFooType());

// ...
```

Psalm complains that the method `methodonlyexistinginfootype` would not exist (why ever it's all lower case?). Given it doesn't know about the method, the return type is - I assume - implicitly considered mixed, leading to a secondary complaint about wrong type for argument 1 of `$other->someMethod`.

**Comment by muglug** [comment]
At the moment Psalm only processes `@var` annotations above assignments, `foreach` blocks and `return` statements. I suppose, since this has come up multiple times, that I should extend `@var` annotations to more places.

**Comment by theseer** [comment]
Oh, didn't see that in the docs.

Yes, it would be very much appreciated. I consider the pattern of `isFoo()` a very nice way to avoid `instanceOf` - or other classname based implementations and would assume I'm far from being the only one doing that. Since the IDE (=PHPStorm) has no means of seeing that this is an (implicit?) type check, the `@var` annotation needs to be used. Alternatively, one could invent an annotation that signals to psalm/IDE that `isFoo()` ensures an annoted type.

Would be nice but is probably a lot harder to implement ;)

**Comment by muglug** [comment]
> Alternatively, one could invent an annotation that signals to psalm/IDE that isFoo() ensures an annoted type. Would be nice but is probably a lot harder to implement ;)

Psalm already has the scaffolding for that with `@psalm-assert-if-true`, and I've just added support for asserting on `$this` in 5c4ac97.

See it in practice here: https://psalm.dev/r/88ba06b5cf

**Comment by theseer** [comment]
Very nice! Any ETA when this will be in a release phar?

**Comment by muglug** [comment]
By EOD tomorrow (US Eastern Time), all things being equal.

**Comment by muglug** [comment]
Closing this in favour of https://github.com/vimeo/psalm/issues/1916
