### ISSUE TITLE
Annotation doesn't work on throw-statements

### ISSUE THREAD

**Issue by tvdijen** [vimeo/psalm#1909]
Consider the variable `$lastException` of type `\Exception|null`..
I'm sure that the variable at a certain point can only contain an `\Exception`, so I want to use annotation:

``/** @var \Exception $lastException */``
``throw $lastException;``

This appears to be doing nothing at all (tested on versions 1.1.9 & 3.4.7):
> ERROR: InvalidThrow - modules/saml/lib/Message.php:419:9 - Cannot throw null as it does not extend Exception or implement Throwable
>         /** @var \Exception $lastException */
>         throw $lastException;

The only way around this I could think of was to either use `/** @psalm-suppress InvalidThrow */` to suppress the false-positive or to insert another assignment like this:

``/** @var \Exception $lastException */``
``$lastException = $lastException;``
``throw $lastException;``

Both do the trick, but neither is really a solution if you ask me..

**Comment by muglug** [comment]
Can you reproduce on psalm.dev?

**Comment by tvdijen** [comment]
If by 'psalm.dev' you mean `master`, then yes it has got the same issue.
If you need a bigger picture you can look at the actual code [here](https://github.com/simplesamlphp/simplesamlphp/blob/2c6d1de15c9f2e3ce208d8a84a37b0c515cf7cba/modules/saml/lib/Message.php#L406-L419)

**Comment by muglug** [comment]
At the moment `@var` annotations are just supported above foreach, assignments and return statements.

The best bet here, I think, is to tell Psalm that `$keys` always has at least one element - either with an `assert(count($keys))` or a `@psalm-return non-empty-array` return type on the function that produces them.

Psalm doesn’t know for sure that `$keys` is non-empty

**Comment by tvdijen** [comment]
Ah right, I just figured out that you meant https://psalm.dev, so I was able to come up with a snippet for what it's worth:  https://psalm.dev/r/e029799d59
I will consider your suggestions, thanks very much for that!

What do you want with this issue? Is it a wontfix or should I keep it open?

**Comment by muglug** [comment]
Thanks for reproducing - either the assert or the `non-empty-array` should be sufficient, so it's definitely a bug, reproduced more succinctly here: https://psalm.dev/r/88b20040ae

**Comment by tvdijen** [comment]
What does this change mean in practice? Does this enable your suggested assert() / psalm-return workarounds? Does this enable @var annotations on throws? Backports?
Thanks much for you time and for addressing this..

**Comment by muglug** [comment]
> Does this enable your suggested assert() / psalm-return workarounds

Yes, either will now work. I always prefer assertions that can be verified by Psalm over those that cannot, so `@psalm-return non-empty-array<T>` would be my preference.

I'm going to also support `@var` in more places, but didn't feel that this ticket _depended_ on that behaviour being there.
