### ISSUE TITLE
ReflectionProperty<class-string<T1>, T2 as string>()::getValue(T1) does not inherit property type

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1912]
Expected: if psalm knows the type of a property value directly, it should know the type of the reflected value
Actual: psalm assumes reflected value type is mixed

https://psalm.dev/r/f49a459172

```php
<?php
class Foo {
  /**
  * @var int
  */
  protected $bar = 1;
  
  public static function Baz(int $value) : void {
    echo (string) $value;
  }
}

$foo = new Foo();

$reflector = new ReflectionProperty(Foo::class, 'bar');

Foo::Baz($reflector->getValue($foo));
```
> Psalm output (using commit 5f8d4ed): 
> 
> INFO: MixedArgument - 17:10 - Argument 1 of Foo::baz cannot be mixed, expecting int

**Comment by muglug** [comment]
I'm not going to fix this, given it's so much of an edge-case.
