### ISSUE TITLE
Test for plugin with absolute filename fails on Windows / Appveyor

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1913]
Error message from [AppVeyor console](https://ci.appveyor.com/project/muglug/psalm/builds/25801733/job/f83i0rhj1xl5d6e2):
```

1) Psalm\Tests\Config\PluginTest::testPluginFilenameCanBeAbsolute
InvalidArgumentException: Cannot find plugin file C:\projects\php-project-workspace\C:\projects\php-project-workspace\tests\Config/../../examples/plugins/StringChecker.php
C:\projects\php-project-workspace\src\Psalm\Config.php:974
C:\projects\php-project-workspace\src\Psalm\Config.php:839
C:\projects\php-project-workspace\src\Psalm\Config.php:582
C:\projects\php-project-workspace\tests\Config\PluginTest.php:835

```

I don't have a windows machine myself, so I'm not sure if this is specific to the AppVeyor set up or would affect all windows environments. Also not sure whether it's a problem with the test or if this is a bug in Psalm.

**Comment by bdsl** [comment]
I've submitted PR https://github.com/vimeo/psalm/pull/1914  to stop this failing the build and link to this issue from the test output.

**Comment by muglug** [comment]
These tests also fail on my mac at home, but not (for whatever mysterious reason) on my mac at work.

**Comment by weirdan** [comment]
I think `isAbolutePath` just fails on paths containing the drive letter.

**Comment by muglug** [comment]
It was a bug in Psalm, fixed with https://github.com/vimeo/psalm/commit/3d4adee6b332aa3408a934e4c2c7871364e20fcd
