### ISSUE TITLE
Enable CircleCI Github checks

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1920]
This might make it a bit easier for people to see what's going on with each PR. I made a PR to my own repo so you can see how it looks: https://github.com/bdsl/psalm/pull/1/checks

![Screenshot from 2019-07-08 00-59-55](https://user-images.githubusercontent.com/159481/60775500-ca326500-a11b-11e9-8af1-59eebbb7cb7d.png)

This is a settings change that would need to be done by someone with admin rights to the `vimeo/psalm` repo. Instructions at https://circleci.com/docs/2.0/enable-checks/

**Comment by muglug** [comment]
I don't think this is is necessary - the GH UI on the main PR page does a decent job
