### ISSUE TITLE
Bad error message when accessing offset Psalm doesn't think exists

### ISSUE THREAD

**Issue by aidantwoods** [vimeo/psalm#1933]
The error message I got which eventually led to finding #1932 and #1931 incorrectly claims that the array is mixed when it believes an offset not to exist: https://psalm.dev/r/f6d9f200a6. While in this case it probably makes sense to warn, IMO when the same thing is the result of a closure then no warning should be given since the implementation of the closure may change: https://psalm.dev/r/2e2f6f9d63.

**Comment by muglug** [comment]
This isn't really a bug - rewriting with a function call fixes: https://psalm.dev/r/ae8aea9ba1 (closures have their internals investigated by Psalm).

**Comment by aidantwoods** [comment]
Okay, good catch about writing as a function—that seems fair.

The error message is still wrong though :)

It says:

> MixedArrayAccess - 5:40 - Cannot access array value on mixed variable $array

But `$array` is not `mixed`.

**Comment by aidantwoods** [comment]
I think if anything, there should be some impossible condition / unreachable code warning for the situation that causes this—but the current error isn't correct.
