### ISSUE TITLE
Psalm error when trying to replicate psalm remote config locally

### ISSUE THREAD

**Issue by prondubuisi** [vimeo/psalm#1939]
Hello  I am trying to use my `psalm.xml` file from a remote server locally I am running into this error

`Problem parsing /home/coolife/git-repos/gsoc/core/psalm.xml:
  Error on line 9:
    Element '{https://getpsalm.org/schema/config}psalm', attribute 'resolveFromConfigFile': The attribute 'resolveFromConfigFile' is not allowed.
`
Everything works well remotely though any fix for this? here is what my `psalm.xml` looks like 
https://pastebin.com/MejWbQq7

**Comment by weirdan** [comment]
The psalm version you're running locally does not support `resolveFromConfigFile` (you need Psalm 3.4.8+).

**Comment by prondubuisi** [comment]
Yes, I can Confirm that thanks @weirdan
