### ISSUE TITLE
Included constants not recognised

### ISSUE THREAD

**Issue by maxarvidsson** [vimeo/psalm#194]
Including a file that defines a constant and using that constant gives an `UndefinedConstant` error, this happens on latest dev-master and does not happen on a version from a few days ago. Example:

src/constant.php
```
<?php

define('FOO', 1);
```
src/test.php
```
<?php

require_once 'constant.php';

$foo = FOO;
```
Running psalm gives:
```
ERROR: UndefinedConstant - src/test.php:5:8 - Const FOO is not defined
$foo = FOO;
```

**Comment by muglug** [comment]
Sorry about this - was caused by https://github.com/vimeo/psalm/pull/191, which dramatically refactored how files were analysed. I've added tests so this shouldn't crop up again.

**Comment by maxarvidsson** [comment]
Thanks for the quick fix, and wow, psalm is running about 10 times faster now on an old codebase I'm working on. Twice that when using --threads=2.

Good job! :)
