### ISSUE TITLE
Support @var T $var in a templated method

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#1941]
Given https://psalm.dev/r/9b57703528

Considering the method is templated, I managed to get it to work using both `/** @var object $o */` for assigning, as well as `/** @var T */` for returning.

I was wondering if it could be combined into one, e.g. `/** @var T $o */` which is currently failing: https://psalm.dev/r/02e14c77f7

Related/Question; is there any difference in using `T` vs `T of object` in this case?

**Comment by vasily-kartashov** [comment]
That interests me as well: what are the rules of inheritance wrt docblocks? In https://psalm.dev/r/9b57703528 is it at all allowed to use `T` inside of `y::boo`? 

What if I introduce another template parameter `@template T` for the whole class `y`:
```
interface x {
  /**
   * @template T of object
   * @param class-string<T> $c
   * @return T
   */
  public function boo(string $c): object;
}

/**
 * @template T
 */
class y implements x {
  public function boo(string $c): object
  {
    /** @var object $o */
    $o = mixish();

    /** @var T */
    return $o;
  }
}
```

which `T` will it be at the `return $o`?

**Comment by muglug** [comment]
That fails because `T` is only live in the method it’s declared in.

**Comment by muglug** [comment]
@vasily-kartashov templates are scoped to only work inside classes and functions they’re declared on - there’s no implicit inheritance. Any inheritance has to be done explicitly via `@extends Foo<TValue>`, `@implements MyInterface<T>` etc.

**Comment by vasily-kartashov** [comment]
@muglug Do I understand it correctly, in this case we'd have to copy the complete declaration from `x::boo` to `y::boo` to make `T` available inside of `y::boo`?

```
class y implements x 
{
    /**
     * @template T of object
     * @param class-string<T> $c
     * @return T
     */
    public function boo(string $c): object { ... }
}
```

**Comment by weirdan** [comment]
> Any inheritance has to be done explicitly via `@extends Foo<TValue>`, `@implements MyInterface<T>` etc.

But there's no way to explicitly inherit *a method* (like `@extends x::boo<T>`), short of repeating all the generic boilerplate. On the other hand, languages like Java and C# do require that as well (albeit more succinctly), I suppose.

**Comment by muglug** [comment]
Yeah, I’m not going to offer anything over and above what C#/Hack offers

**Comment by gharlan** [comment]
> Given https://psalm.dev/r/9b57703528
> 
> Considering the method is templated, I managed to get it to work using both `/** @var object $o */` for assigning, as well as `/** @var T */` for returning.

This does not seem to work anymore (open the link). What is the current way to fix this?
