### ISSUE TITLE
Memory error.

### ISSUE THREAD

**Issue by omatamix** [vimeo/psalm#1943]
10.76s$ ./vendor/bin/psalm
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes) in /home/travis/build/phoenix-zero-ai/tic-tac-toe/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php on line 593

You can view the repository here <https://github.com/phoenix-zero-ai/tic-tac-toe>.

I do not even have that much code and the loops are not that big.

**Comment by weirdan** [comment]
Apparently Psalm cannot handle the condition here:
https://github.com/phoenix-zero-ai/tic-tac-toe/blob/master/src/Status.php#L27

**Comment by muglug** [comment]
Hahaha. Ok, yes. Definitely bad behaviour on Psalm’s part.

But, and I pretty much never say this, that verification code should probably just be rewritten to use for loops instead.

**Comment by omatamix** [comment]
I'll do some adjusting and I'll comment later.

**Comment by omatamix** [comment]
I just used loops instead and the error went away. Since this was bad behavior from psalm should i keep this issue open?

**Comment by muglug** [comment]
The OOM can be triggered on psalm.dev easily: https://psalm.dev/r/b4f7e58f9e

The bottom line is Psalm shouldn’t crash here - it should have _some_ mechanism to detect a conditional that'll likely expand to something massive (i.e combinatorial explosion)

**Comment by weirdan** [comment]
Or, alternatively, track memory usage and abort type inference for the particular expression if mem delta grows too big.
