### ISSUE TITLE
strings can be incremented

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1944]
Was running psalm on [nikic/fast-route](https://github.com/nikic/FastRoute/blob/e4001344506393b63e9373446e38eb8db228ef63/src/DataGenerator/MarkBased.php#L31), got an error;

> ERROR: PossiblyInvalidOperand - src\DataGenerator\MarkBased.php:35:15 - Cannot perform a numeric operation with a non-numeric type string
>            ++$markName;

it turns out one *can* perform increment operations on strings:
```php
<?php
function bar(string $bar, string $expected) : bool {
  return $expected === $bar;
}

foreach (
  [
    'a' => 'b',
    'foo' => 'fop',
  ] as $to_increment => $expected
) {
  echo $to_increment, ',', $expected, ',';
  
  ++$to_increment;
  
  echo bar($to_increment, $expected) ? 'yup' : 'nope', "\n";
}
```
* https://psalm.dev/r/d483ae3149
> Psalm output (using commit 7f0dcae): 
> 
> ERROR: InvalidOperand - 14:5 - Cannot perform a numeric operation with a non-numeric type string

* https://3v4l.org/OMidv
> Output for 7.1.25 - 7.4.0alpha2
> a,b,yup
> foo,fop,yup

**Comment by weirdan** [comment]
To quote nikic himself (https://externals.io/message/106054#106203):

> String increment seems like a pretty niche use case, and I believe that 
> many people find the overflow behavior quite surprising. I think it may be 
> better to forbid string increment under strict_operators.

**Comment by muglug** [comment]
Yeah Psalm doesn’t allow this, because it is dumb and weird behaviour that is more likely to be a bug than something intended by the user

**Comment by kelunik** [comment]
We use these quite often within Amp, is there any simple configuration option to disable these `InvalidOperand` errors without ignoring every `InvalidOperand` error?

**Comment by muglug** [comment]
There isn’t, but there could easily be.

**Comment by kelunik** [comment]
@muglug Should we reopen this issue or should I open a new one?

**Comment by muglug** [comment]
Please create a new one!

**Comment by kelunik** [comment]
See #2061.
