### ISSUE TITLE
Negated type expressions

### ISSUE THREAD

**Issue by aidantwoods** [vimeo/psalm#1953]
Feature request (since afaik this isn't currently possible).

I think it would be useful to allow negated type expressions (i.e. `!T` where `T` is a valid Psalm type).

A specific use case is to use this in combination with intersection types to convey specifically disallowed small value-type subsets of a certain type (e.g. non empty strings: `string&!""`), but this is of course more generic in practice to allow excluding of whole types (e.g. `scalar&!string`).

IMO negated type expressions are sort of a missing counterpart to being able to construct [negated assertions](https://github.com/vimeo/psalm/blob/master/docs/annotating_code/assertion_syntax.md#negated-assertions), in-that: after asserting this, it isn't currently possible to then pass this type information across scope boundaries or store this information as the type of a class' property.

E.g. ignoring the errors about the unsupported syntax, it would be nice if https://psalm.dev/r/8f63e341cb could give the same `ParadoxicalCondition` error as https://psalm.dev/r/7beed46aa3 (via the type information included in the param).

**Comment by aidantwoods** [comment]
@muglug I think that might have been meant to close #1952?

**Comment by muglug** [comment]
Yup sorry!

**Comment by muglug** [comment]
I think there the way forward would be to add a `non-empty-string` type, the same way there's a `non-empty-array` type

**Comment by muglug** [comment]
But I'm not going to add a negated type expression

**Comment by aidantwoods** [comment]
Is this due to complexity?

**Comment by muglug** [comment]
Yeah, and general ugliness

**Comment by aidantwoods** [comment]
For a potential `non-empty-string` I would expect that it is best to depart from PHP's idea from the `empty` function on strings where falsey strings are also somehow "empty" (e.g. `empty('0') === true` and just have that `non-empty-string $string` implies that `$string
!== ''`.
