### ISSUE TITLE
not working PHP 7.2.4

### ISSUE THREAD

**Issue by EliuFlorez** [vimeo/psalm#1959]
**Run**
./vendor/bin/psalm --init application 3
./vendor/bin/psalm

**nothing**
```
$ ./vendor/bin/psalm
Scanning files...
Analyzing files...

E░EE░EEE
```

version
PHP 7.2.4 (cli) (built: Mar 28 2018 04:46:46) ( ZTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by muglug** [comment]
Sorry, what's not working?
