### ISSUE TITLE
Support for Amp\Promise

### ISSUE THREAD

**Issue by prolic** [vimeo/psalm#1960]
For example I have this error here:

`$this->connection with declared type 'null|Amp\Socket\ClientSocket' cannot be assigned type 'Amp\Promise<Amp\Socket\ClientSocket>'`

with this code:

`$this->connection = yield connect($uri, $context);`

It would be super nice, if psalm could detect Amp\Promise resolution via `yield` calls and not complain anymore.

**Comment by muglug** [comment]
Closing in favour of #1961.

Also please consider spending some time away from the internet. Your Twitter account is a mass of hate-filled bile. You stand in opposition pretty much everything I hold dear.
