### ISSUE TITLE
Consider an annotation that makes clear what yielding a promise does

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#1961]
Carried on from https://github.com/vimeo/psalm/issues/1960

Calling `$a = yield $foo` where $foo has type `Amp\Promise<Bar>` should assign the type `Bar` to `$a`.

I'm thinking of an annotation like this:

```php
namespace Amp;
/**
 * @template T
 * @yields T
 */
interface Promise {...}
```

cc @kelunik

**Comment by prolic** [comment]
https://github.com/vimeo/psalm/issues/1960#issuecomment-513588166

very professional

**Comment by trowski** [comment]
What happens if `$foo` has type `Amp\Promise`? Some older annotations only declare that a promise is returned but omitted the resolution type. In that case `$a` should probably be assigned mixed.

**Comment by bzikarsky** [comment]
This would be an awesome feature for a huge amp based project of ours. I just tried to hack some "hard" support for "yield Promise<T> into T" into psalm via plugins, but I guess this will just not work.

Is there a chance this will show up on a (near) future roadmap? Can we support this implementation? Would a PR with a new `@yields` annotation be considered? 

Also partially related (but may warrant a new/separate issue) - Do we have any chance to raise an error, if a Promise is neither yielded nor assigned nor returned?

**Comment by muglug** [comment]
This is now supported with `@psalm-yield`
