### ISSUE TITLE
Feature request: "verify if costs estimated are optimal"

### ISSUE THREAD

**Issue by voku** [vimeo/psalm#1964]
This was a idea for phpstan: "In this pull-request (https://github.com/phpstan/phpstan/pull/1694) I applied suggestions from "Php Inspections (EA Ultimate)" (PhpStorm), but the idea is that we have a similar functionality for phpstan itself."

e.g.:
```php
if (
        isset($x[uniqid()])
		&&
        $x // This condition execution costs less than the previous one.
    ) {}
```

links:
- "NotOptimalIfConditionsInspection.java" https://github.com/kalessil/phpinspectionsea/blob/master/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/ifs/NotOptimalIfConditionsInspection.java#L462
- "ExpressionCostEstimateUtil.java" https://github.com/kalessil/phpinspectionsea/blob/master/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/ifs/utils/ExpressionCostEstimateUtil.java#L36
- tests: https://github.com/kalessil/phpinspectionsea/tree/master/testData/fixtures/ifs

**Comment by muglug** [comment]
Would you mind first running these inspections on Psalm's source code, as you did in that closed PR? I want to get a sense of what things it would flag.

**Comment by voku** [comment]
run & fix some phpstorm + ea ultimate inspection stuff: e.g.: https://github.com/vimeo/psalm/compare/master...voku:phpstorm-inspections#diff-be02ba260907ea8b964e4347c8bf7b69R473

**Comment by muglug** [comment]
there's nothing in that diff (and I don't use PHPStorm)

**Comment by voku** [comment]
Maybe only I can see this diff?! So I create a pull request as example for "verify if costs estimated are optimal" -> e.g. https://github.com/vimeo/psalm/pull/1971/files#diff-56d65dabd9dc187cef055b49937a4839R824

**Comment by weirdan** [comment]
> there's nothing in that diff (and I don't use PHPStorm)

That was a broken link. Here's a good one:
https://github.com/vimeo/psalm/compare/master...voku:phpstorm-inspections

**Comment by muglug** [comment]
I don't _think_ this is something that Psalm should do - happy to leave it up to a paid product to mangle code that much.
