### ISSUE TITLE
Feature request: class-string-map<T> type

### ISSUE THREAD

**Issue by aidantwoods** [vimeo/psalm#1969]
At the moment there isn't a very good way to retrieve objects from an array indexed by their class string and have Psalm track this relationship.

I'd like to tell Psalm that I have an array of type `array<class-string<Foo>, Foo>` where the class string in the key refers to ***the same*** `Foo` that will be returned. This is roughly equivalent to having a method of the following format as the array-accessor of an array:

```php
/**
 * @template T as Foo
 * @template-typeof T $fooClass
 * @param class-string<T> $fooClass
 * @return T|null
 */
public function get($fooClass);
```

At the moment when I write something like:

```php
interface Foo {}

final class FooStorage
{
    /** @var array<class-string<Foo>, Foo> */
    private $storage = [];
  
    /** @param Foo[] $Foos */
    public function __construct($Foos)
    {
     	foreach ($Foos as $Foo) {
            $this->storage[\get_class($Foo)] = $Foo;
        }
    }
  
    /**
     * @template T as Foo
     * @template-typeof T $fooClass
     * @param class-string<T> $fooClass
     * @return T|null
     */
    public function get($fooClass)
    {
        return $this->storage[$fooClass] ?? null;
    }
}
```

Psalm correctly flags an error since the array accessor on `$this->storage` is only guaranteed to return `Foo` and is not itself generic on the input. If possible, I'd like to tell Psalm that I will assign class strings to map to their objects using some special type (e.g. `class-string-map<T>`) so that something like:

```php
interface Foo {}

final class FooStorage
{
    /** @var class-string-map<Foo> */
    private $storage = [];
  
    /** @param Foo[] $Foos */
    public function __construct($Foos)
    {
     	foreach ($Foos as $Foo) {
            $this->storage[\get_class($Foo)] = $Foo;
        }
    }
  
    /**
     * @template T as Foo
     * @template-typeof T $fooClass
     * @param class-string<T> $fooClass
     * @return T|null
     */
    public function get($fooClass)
    {
        return $this->storage[$fooClass] ?? null;
    }
}
```
would succeed.

**Comment by muglug** [comment]
Small nit: here the `@template-typeof` is redundant:

```
     * @template-typeof T $fooClass
     * @param class-string<T> $fooClass
```

**Comment by muglug** [comment]
Although this is identical to something we do at Vimeo, I don't think it's a common-enough use-case to warrant a separate type, sorry.

**Comment by aidantwoods** [comment]
> Small nit: here the `@template-typeof` is redundant

Hmm yeah, I thought this too (I was updating some code to Psalm 3.4) so I removed it and got +60 errors :) I just tried my code in `master` and same thing happens so I'll have to track down a minimal example of what's causing that.

**Comment by aidantwoods** [comment]
> Although this is identical to something we do at Vimeo[...]

I'd be curious to see how Vimeo has implemented it, do you just have some `@psalm-suppress` annotations to ignore the error? The trouble is, I can't think of a way of using existing annotations to tell Psalm what I'm doing with the array (and I kind of need the array to perform lookups) :)

Best way I can think of without suppressing the error is to utilise an `_ instanceof $fooClass` check (as in #1970). But apart from being unnecessary code in theory, it also then forces the case that that check fails to be dealt with as an additional code path.

Would be curious to see if Vimeo did anything different to one of these two?

**Comment by muglug** [comment]
The actual returning of stored values just happens in a templated function, with a `@var` docblock on the return.

```
        if (isset(self::$storage[$class_name])) {
            /** @var T */
            return self::$storage[$class_name];
        }
```

**Comment by muglug** [comment]
This turns out to be a fairly common ask. Reopening.

**Comment by muglug** [comment]
I think specifying the template at the property level might be the simplest to understand, conceptually e.g.

```
/**
 * @template T of Foo
 * @var array<class-string<T>, T>
 */
private array $map;

/**
 * @template T of Foo
 * @var array<class-string<T>, callable():T>
 */
private array $factories;
```

**Comment by aidantwoods** [comment]
Naming this type elsewhere (e.g. in a return type) could be problematic if the only way to notate this relationship is as a property accessor template?

**Comment by muglug** [comment]
Yeah - maybe it should be `class-string-map<T of Foo, T>`

**Comment by aidantwoods** [comment]
> Yeah - maybe it should be `class-string-map<T of Foo, T>`

I think that's a good idea. Looking at the other threads it seems that wanting a class-string to map to a callable which returns that class is also a use case, which I hadn't considered.

I think the syntax you suggested here does a good job to accommodate arbitrary placement of the class-string type within the value position. This would definitely be a *new* syntax behaviour, where there's sort of an unspecialised generic passed through the type arguments, which doesn't really become specialised until call time (where the generic serves to preserve the type relationship until then).

It's almost as if we want `class-string-map` to here actually accept a type (say `T`) which forms the upper constraint, and a [type constructor (kind `* -> *`)](https://en.wikipedia.org/wiki/Kind_(type_theory)) called `U<_>` say, which is then passed down to the array accessor which is itself a generic of the signature:

```php
/**
 * @template V as T
 * @param class-string<V> $tClass
 * @return U<V>|null
 */
public function get($tClass);
```

So something like the following if written as a class (of course in practice this would be a subtype of an array):

```php
/**
 * @template T
 * @template U<_>
 */
class class-string-map
{
    /**
     * @template V as T
     * @param class-string<V> $tClass
     * @return U<V>|null
     */
    public function get($tClass);
}
```

You'd then need some way of specifying this type constructor inline, perhaps using `_` again, e.g.: if you wanted to return a callable: `callable():_`. Full declaration: `class-string-map<Foo, callable():_>` would mean that a variable of this type accepts `class-string`'s which are `Foo` or a subtype, and returns a callable which maps to the corresponding `class-string`. Similarly, `class-string-map<Foo, _>` would mean that a variable of this type accepts `class-string`'s which are `Foo` or a subtype (as before), but returns an instance of the type corresponding to the given class-string.

Maybe this type of thing has been done elsewhere in another language, in which case it might be a good idea to lean on existing conventions?

**Comment by muglug** [comment]
I'm not sure there are similar constructs in other languages – I don't think Hack has one, for example (though @fredemmott may correct me).

The syntax I'm using [in my current working branch](https://github.com/vimeo/psalm/compare/class-string-map) is

`class-string-map<T as ClassOrInterface, U>` where `U` is a type parameterised on `T`
e.g. `class-string-map<T, T>`, `class-string-map<T as Bar, Closure():T>`

I think it's the most obvious solution given how templated parameters are referenced today.

cc @TysonAndre @ondrejmirtes if they have other thoughts/opinions

**Comment by TysonAndre** [comment]
Even if it occurs in various projects, it'd probably only occur in a few places within projects. Suppressing the issues or switching to a helper method or `MyFactory<class-string<T as Bar>, Closure(): T>` would be other options.

This might add additional work for conditionals, inferring types for access/foreach, plugins, etc., so those would continue to work properly, for a much less common use case than list/generic arrays/etc.

**Comment by muglug** [comment]
I've added a very basic implementation, but it's an obscure-enough use case that I don't think I'll do anymore work on it – anyone who wants to use it is responsible for fixing any bugs they find :)

**Comment by aidantwoods** [comment]
Seems fair 😂
