### ISSUE TITLE
Callmap delta not taken into account?

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#1972]
Hi,

It seems the callmap delta is not taken into account even if I set `php-version` to the targeted PHP version.
For example, the signatures of setcookie/setrawcookie functions have been updated in #1924 but I get an InvalidArgument if I try to use to new signature in a PHP 7.3 environment.
```php
<?php
 
// InvalidArgument - 6:2 - Argument 3 of setcookie expects int, array{path: string(/), expires: int(0), httponly: true, secure: true, samesite: string(Lax)} provided
setcookie(
	'name',
	'value',
	[
		'path'     => '/',
		'expires'  => 0,
		'httponly' => true,
		'secure'   => true,
		'samesite' => 'Lax'
	]
);
```

(I cannot generate a link on psalm.dev, I get a "Connection to database failed" error)

**Comment by muglug** [comment]
Thanks - the main callmap should be up-to-date one with the most recent version of PHP (the deltas apply to old versions). In this case the callmap wasn't up-to-date.
