### ISSUE TITLE
Incorrect work language server with PHPstorm?

### ISSUE THREAD

**Issue by EvgeniiR** [vimeo/psalm#1973]
I'm just trying to use language server with phpstorm. Immediately encounter some errors:
1. Duplicate language server inspections (See screenshot)
2. "Property is not defined in constructor" error, but it isn`t correct, I initialize all properties in constructor(also on screenshot). This error is not present if you run psalm from the console.
<details>
<summary>Images</summary>

![image](https://user-images.githubusercontent.com/19509035/61997278-ec2e6000-b0a7-11e9-914b-83a089634ecf.png)

Server definition: 

![image](https://user-images.githubusercontent.com/19509035/61997687-1551ef00-b0ae-11e9-98bb-9c99168093fb.png)

</details>

This file: https://github.com/EvgeniiR/ws-chat/blob/dev/src/MigrationsComponent/Internal/SchemaUpdater.php

PhpStorm 2019.1.3
Build #PS-191.7479.51, built on June 18, 2019
Licensed to Evgeniy Romashkan
Subscription is active until August 24, 2019
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-55-generic

Psalm 3.4.10

**Comment by muglug** [comment]
Yup, I can reproduce in Sublime.
