### ISSUE TITLE
Unexpected result when using array key value annotation

### ISSUE THREAD

**Issue by torranced** [vimeo/psalm#1974]
Not getting expected error when trying to use the syntax borrowed from Java as described in documentation.

See code here:
https://psalm.dev/r/67151262d6

I'd expect an error when setting the default value of the property.

**Comment by muglug** [comment]
Constant docblocks are currently ignored by Psalm, but I fixed the issue for static properties.

**Comment by torranced** [comment]
@muglug - Thank you!

I'm presuming there is a reason why constant docblocks are ignored. Is there any one particular issue you could point me to for more info on why that is so?

**Comment by muglug** [comment]
> I'm presuming there is a reason why constant docblocks are ignored. Is there any one particular issue you could point me to for more info on why that is so?

In 99% of situations Psalm can infer them. For the rest, there's an open issue about this: https://github.com/vimeo/psalm/issues/942
