### ISSUE TITLE
Feature request: exhaustive type narrowing

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#198]
In some cases it's possible to determine variable type by looking at negative type assertions. One notable example is DateTimeInterface + it's descendants, where base interface cannot be implemented by user classes, so anything that is DateTimeInterface is either DateTime or DateTimeImmutable. Taking this into account the following code could be type checked successfully:
```php
<?php

function ensureImmutable(DateTimeInterface $dt): DateTimeImmutable
{
    return $dt instanceof DateTimeImmutable ? $dt
        : DateTimeImmutable::createFromMutable($dt);
}
```

Currently, however, it complains that `$dt` in `DateTimeImmutable::createFromMutable($dt)` call could be something other than `DateTime`.

**Comment by muglug** [comment]
Ah right. Well, I could make an exception for this, but it doesn't seem like a terribly common occurrence.

**Comment by weirdan** [comment]
Ah, it could be overridden with assert, so no big deal.
```php
function ensureImmutable(DateTimeInterface $dt): DateTimeImmutable
{
    assert($dt instanceof DateTimeImmutable || $dt instanceof DateTime, 'unknown datetime type');
    return $dt instanceof DateTimeImmutable ? $dt
        : DateTimeImmutable::createFromMutable($dt);
}
```

**Comment by muglug** [comment]
Absolutely, as long as you turn on `useAssertForType`

**Comment by muglug** [comment]
Gonna close this
