### ISSUE TITLE
Not inferring types when destructuring type hinted array

### ISSUE THREAD

**Issue by sspat** [vimeo/psalm#1981]
There seems to be a problem with destructuring type-hinted arrays.
As far as my understanding goes, it must be possible to infer the types of the variables the array is destructured to, if the array itself is type hinted in the docblock.

Using php 7.4.0beta1 and psalm@dev-latest

https://psalm.dev/r/805618addb

```php
/** @var string[] $arrayOfStrings */
$arrayOfStrings = ["test", "test2"];

// We know at this point that $arrayOfStrings contains only strings
foreach ($arrayOfStrings as ['test' => $test, 'test2' => $test2]) {
  // Psalm complains, that $test is mixed
  printString($test);
  // Psalm complains, that $test2 is mixed
  printString($test2);
}

function printString(string $string) : void
{
  echo $string;
}
```

**Comment by muglug** [comment]
You're missing an extra `[]` in the hinted docblock: https://psalm.dev/r/9b3646288a

**Comment by muglug** [comment]
Alternative without the docblock: https://psalm.dev/r/6e9941c193
