### ISSUE TITLE
isset on nested array should imply array access on n-1 level

### ISSUE THREAD

**Issue by aidantwoods** [vimeo/psalm#1986]
If an `isset` check succeeds on something of the form `$array['foo']['bar']` where `$array` is known to be an array then I think this can safely imply that `$array['foo']` is an array or array accessible with key `bar`.

```php
<?php
  
interface Foo {
    function getArray(): array;
}

function getBar(Foo $Foo): ?string {
    $array = $Foo->getArray();

    if (!isset($array['foo']['bar']) || !is_string($array['foo']['bar'])) {
        return null;
    }
  
    return $array['foo']['bar'];
}
```
Psalm output (using commit b2c0993): 
```
INFO: MixedArrayAccess - 10:52 - Cannot access array value on mixed variable $array['foo']
```

https://psalm.dev/r/3b2a04a4de

**Comment by muglug** [comment]
Yeah, you're right, Psalm should refine the type to `array|ArrayAccess`

**Comment by muglug** [comment]
Hmm that was not the right solution. Back to the drawing board.

**Comment by weirdan** [comment]
This shouldn't affect strings though, which also could be accessed as arrays. And now it does (I think due to these changes):

https://psalm.dev/r/5a87b3ae84 cf. https://3v4l.org/ukiRA

**Comment by muglug** [comment]
Thanks @weirdan, fixed in https://github.com/vimeo/psalm/commit/63974212157f1bd81ff5e2079c4cd078c5b11ca6
