### ISSUE TITLE
setlocale second parameter can be 0

### ISSUE THREAD

**Issue by BackEndTea** [vimeo/psalm#1988]
I get the following error in my code: 
```
ERROR: InvalidScalarArgument - src/Assert.php:1101:40 - Argument 2 of setlocale expects string, int(0) provided
        $locale = \setlocale(LC_CTYPE, 0);
```

But 0, or `null` is allowed for this function.

From the documentation(https://www.php.net/manual/en/function.setlocale.php): 
* If locale is NULL or the empty string "", the locale names will be set from the values of environment variables with the same names as the above categories, or from "LANG".

* If locale is "0", the locale setting is not affected, only the current setting is returned.

* If locale is an array or followed by additional parameters then each array element or parameter is tried to be set as new locale until success. This is useful if a locale is known under different names on different systems or for providing a fallback for a possibly not available locale.

**Comment by HenkPoley** [comment]
You can fix this by patching https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/CallMap.php

```
'setlocale' => ['string|false', 'category'=>'int', 'locale'=>'string', '...args='=>'string'],
```

to:

```
'setlocale' => ['string|false', 'category'=>'int', 'locale'=>'string:null', '...args='=>'string'],
```

**Comment by muglug** [comment]
yeah, feel free to send a PR!

**Comment by HenkPoley** [comment]
@BackEndTea this one is up to you, since you can verify that it resolved your problem. (I'm just passing by, dropping random advice)

**Comment by BackEndTea** [comment]
I'll open up a PR later today.

**Comment by BackEndTea** [comment]
Thanks for the help @muglug & @HenkPoley
