### ISSUE TITLE
Fully-qualified @method param types aren’t respected

### ISSUE THREAD

**Issue by HenkPoley** [vimeo/psalm#1989]
```
`INFO: InvalidArgument - <*.php:*:*> - Argument 1 of transaction expects Illuminate\Support\Facades\Closure, Closure():mixed provided`
            DB::transaction(function () {
```

DB refers to one of Laravel's facades: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Support/Facades/DB.php#L20

Specifically the line: `@method static mixed transaction(\Closure $callback, int $attempts = 1)`

I'm not sure \Closure should be interpreted as Illuminate\Support\Facades\Closure (which does not exist), but more like PHP's internal Closure class. 

I can work around the error by adding `use Closure;` at the top. But it's strictly not needed for PHP, even if the class had method explicitly defined using \Closure as a type in the arguments.

Example workaround pull-request for Laravel: https://github.com/laravel/framework/compare/5.8...HenkPoley:patch-1

**Comment by muglug** [comment]
Reproduced with

```
namespace Foo {
  /**
   * @method  void setInteger(\Closure $c)
   */
  class Child {
    public function __call(string $s, array $args) {}
  }
}

namespace {
	$child = new Foo\Child();
	$child->setInteger(function() : void {});
}
```

**Comment by HenkPoley** [comment]
I've checked with `"vimeo/psalm": "dev-master"` (resulting in the even newer dec612a being installed) in my composer.json, and it also seems to have fixed the issue on my end 👍

Thanks for the quick fix 🎉🙂
