### ISSUE TITLE
Psalter incorretcly replaces method in Doctrine Entity

### ISSUE THREAD

**Issue by oscargala** [vimeo/psalm#1991]
Creating this issue again, previous one was closed because I took too long in recreting it in a separate repo.

I'm running Psalter on a Symfony 3.4 project and I have a Command file where Psalter replaces this method:

```php
    /**
     * @param array $companyId
     */
    private function test(array $companyId)
    {
    }
```

with 

```php
   ompanyId): void
    {
    }
```

I have used ./vendor/bin/psalter --issues=all --safe-types
and ./vendor/bin/psalter --issues=all --php-version=7.1
Got the same result with both commands.

I have been able to reproduce with this Symfony 3.4 project:
https://github.com/oscargala/psaltertest

If I run vendor/bin/psalter --issues=all --php-version=7.2 then the AppBundle/Entity/Category.php file gets messed up. It's due to the addProduct and removeProduct methods.

**Comment by muglug** [comment]
Reproduced with `--issues=PossiblyUnusedMethod,MissingReturnType --dry-run`

**Comment by muglug** [comment]
Thanks!
