### ISSUE TITLE
MixedPropertyTypeCoercion for array of objects

### ISSUE THREAD

**Issue by rtyshyk** [vimeo/psalm#1992]
Hi there,

Code example: https://psalm.dev/r/f7997b79b7

Not sure if it is a bug, but I really have no idea how to write it better to avoid MixedPropertyTypeCoercion issue.

There only one fix is possible is add property type annotation inside a constructor, e.g. https://psalm.dev/r/85c2f05901 , but it looks very verbose to me.

Is it expected behaviour?

Did I miss something how to document it better? 

Thanks!

**Comment by muglug** [comment]
The docblock `@param` is lacking the param name!
