### ISSUE TITLE
@psalm-assert-if-true doesn’t work for $this properties

### ISSUE THREAD

**Issue by Erwyn** [vimeo/psalm#1994]
Hello there,

In the documentation about assertions it is mentioned that  "Psalm has three docblock annotations that allow you to specify that a function verifies facts about variables and **properties**:"(https://psalm.dev/docs/annotating_code/adding_assertions/)

I tried to make it work and look for it in psalm's codebase but couldn't find how to do so with properties. Here is an example: https://psalm.dev/r/3c3a6cedfe

Am I doing something wrong ?

**Comment by muglug** [comment]
It's a bug (it works with `@psalm-assert`)
