### ISSUE TITLE
phar not generated for 3.4.11

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#1995]

**Comment by ADmad** [comment]
It just appeared :)

**Comment by muglug** [comment]
![5022825D-A463-47D2-98D2-94B9E8C51EF0](https://user-images.githubusercontent.com/2292638/62793257-21bb4c00-ba9f-11e9-9daa-5113c7628af9.jpeg)

It just takes a few minutes :)

**Comment by ADmad** [comment]
Yes I figured, I'll me be more patient next time I get notification of a new release :smile:.
