### ISSUE TITLE
@psalm-assert with $this results in TypeDoesNotContainType error

### ISSUE THREAD

**Issue by vzz3** [vimeo/psalm#1998]
```php
<?php
  
class A {
	
  /**
   * @var array<string>|null
   */
  private $list = null;
  
  /**
   * @psalm-assert !null $this->list
   */
  private function init(): void {
  	$this->list = [];
  }
  
  public function doSomething(): void {
    if($this->list === null) {
    	$this->init(); // ERROR: TypeDoesNotContainType - 19:13 - Found a contradiction when evaluating $this->list and trying to reconcile type 'null' to !null
    }
    foreach($this->list as $item) {
    	echo $item;
    }
  }
}
```
https://psalm.dev/r/c709f845fd

Expected: no issue

**Comment by muglug** [comment]
You're using assertions wrong - they don't describe effects of calling functions. Rather, they describe assertions made within the function.

**Comment by vzz3** [comment]
Thank you for your quick answer! Could you pleas tell me what would be the best way to prevent the PossiblyNullIterator error in such a situation?

https://psalm.dev/r/5158930fa5

**Comment by weirdan** [comment]
To me it looks like Psalm just refuses to refine out the only type left (in the `if` block). Rewriting it like this: https://psalm.dev/r/f502c55707 (properly) yields no errors, even though it's still can be said to 'describe the effect of calling the function'.

**Comment by vzz3** [comment]
Thank you for pointing me into the right direction.
