### ISSUE TITLE
Psalm cannot infer return types of higher level functions

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#1999]
Given following example:

```php
<?php

class HelloWorld
{
    public function sayHello() : void
    {
        echo 'Hello World!';
    }
}

/**
 * @psalm-template InstanceType as object
 * @psalm-param class-string<InstanceType> $className
 * @psalm-return InstanceType
 */
function factory(string $className) : object
{
    return new $className;
}

/**
 * @psalm-template InputType of string
 * @psalm-template OutputType
 * @psalm-param callable(InputType) : OutputType $factory
 * @psalm-param InputType $input
 * @psalm-return OutputType
 */
function makeThroughFactory(callable $factory, string $input)
{
    return $factory($input);
}

makeThroughFactory('factory', HelloWorld::class)->sayHello();
```

Psalm reports (https://psalm.dev/r/411d7d36b9):

```
Psalm output (using commit e32b92b):

INFO: MixedMethodCall - 33:51 - Cannot determine the type of the object on the left hand side of this expression
```

I realise that this is extremely complex, but ideally I'd expect the return type of `makeThroughFactory()` (at the call site) to be inferred from the return type of `factory` (`InstanceType`), which is coupled to the input (`InputType of string`).

In practice, this allows chaining functions through pipe-alike structures. In following example, assumping `compose()` to be the function composition operation:

```php
$a = function (T1 $v) : T2 {}
$b = function (T2 $v) : T3 {}
$b = function (T3 $v) : T4 {}

$composed = compose($a, compose($b, compose($c)));
```

Then `$composed` should be inferred as `function (T1 $v) : T4 {}`

**Comment by muglug** [comment]
This shouldn't be too hard to do (TypeScript [has a similar construct](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-inference-in-conditional-types)).

**Comment by muglug** [comment]
Hmm actually the general case (for `compose`) is doable, but I'm not sure about your above example.

Unless I made some fairly substantial changes to its inference algorithm, Psalm would nfer the type of `InputType` and `OutputType` as being `class-string` and `object` respectively, so the `sayHello` method would still not be understood.

**Comment by muglug** [comment]
Similar behaviour can be got like this: https://psalm.dev/r/327187bbae - I'm minded to close this, as I don't see myself ever adding the changes to make this work.

**Comment by muglug** [comment]
Using a closure there also fixes the irksome issue of using strings which, I think we can all agree, are a pox upon the language.

**Comment by Ocramius** [comment]
@muglug to be clear on how this was discovered: I was trying to declare types for a DIC similar to Pimple

**Comment by Ocramius** [comment]
It seems like psalm correctly infers the function composition example:

```php
<?php

/**
 * @psalm-template A
 * @psalm-template B
 * @psalm-template C
 * @psalm-param callable(A) : B $f1
 * @psalm-param callable(B) : C $f2
 * @psalm-return callable(A) : C
 */
function compose($f1, $f2)
{
    // note: following suppressions aren't really valid if A, B and C are correctly allowing "of mixed"
    /** 
     * @psalm-suppress MissingClosureParamType
     * @psalm-suppress MissingClosureReturnType
     */
    return function ($v) use ($f1, $f2) {
        /** @psalm-suppress MixedArgument */
        return $f2($f1($v));
    };
}

$a = function (int $i) : string {
    return 'Hello ' . $i;
};

$b = function (string $i) : bool {
    return strlen($i) > 0;
};

$c = function (bool $i) : float {
    return $i ? 0.1 : 0.2;
};

$composed = compose($a, compose($b, $c));

echo $composed(10) > 0;
echo $composed;
```

Produces https://psalm.dev/r/8147d79698:

```
Psalm output (using commit fac7df2):

ERROR: InvalidArgument - 39:6 - Argument 1 of echo expects string, callable(int):(float(0.1)|float(0.2)) provided
```

This indeed indicates that the functional composition worked with non-generic types. 

Currently working on a simpler example (not involving class-string) that uses generic types.

**Comment by Ocramius** [comment]
Here's a better example that doesn't involve the dreaded `class-string` mumbo-jumbo:

```php
<?php

/**
 * @psalm-template A
 * @psalm-template B
 * @psalm-template C
 * @psalm-param callable(A) : B $f1
 * @psalm-param callable(B) : C $f2
 * @psalm-return callable(A) : C
 */
function compose($f1, $f2)
{
    // note: following suppressions aren't really valid if A, B and C are correctly allowing "of mixed"
    /** 
     * @psalm-suppress MissingClosureParamType
     * @psalm-suppress MissingClosureReturnType
     */
    return function ($v) use ($f1, $f2) {
        /** @psalm-suppress MixedArgument */
        return $f2($f1($v));
    };
}

/**
 * @psalm-template A
 * @psalm-param A $a
 * @psalm-return array{0: A}
 * @psalm-suppress MissingClosureParamType closure has no parameter type (by design)
 */
$wrap = function ($a) : array {
    return [$a];
};

/**
 * @psalm-template A
 * @psalm-param array{0: A} $a
 * @psalm-return A
 * @psalm-suppress MissingClosureReturnType closure has no return type (by design)
 */
$unwrap = function (array $a) {
    return $a[0];
};

$composed = compose($wrap, compose($wrap, $unwrap));

/** @psalm-suppress ForbiddenCode yes, we are having a dump */
var_dump($composed(123));

echo $composed; // inferred as callable(mixed):mixed - psalm gave up here

compose($unwrap, $unwrap); // here psalm did indeed infer that something is wrong

echo (compose($wrap, $wrap)[123])[0][0]; // also here, psalm gave up
```

Psalm gets some stuff right (https://psalm.dev/r/058ad10d6e):

```
Psalm output (using commit 6397421):

ERROR: InvalidArgument - 49:6 - Argument 1 of echo expects string, callable(mixed):mixed provided

INFO: MixedArgumentTypeCoercion - 51:9 - Argument 1 of compose expects callable(array<array-key, mixed>):array<array-key, mixed>, parent type Closure(array<array-key, mixed>):mixed provided

ERROR: InvalidArrayAccess - 53:7 - Cannot access array value on non-array variable of type callable(mixed):array{0: mixed}

INFO: MixedArrayAccess - 53:6 - Cannot access array value on mixed variable

INFO: MixedArgument - 53:6 - Argument 1 of echo cannot be mixed, expecting string
```

**Comment by muglug** [comment]
Here's a version of that with docblocks in the right place (though I'm not sure whether Psalm supports templates on closures): https://psalm.dev/r/33517c26e0

**Comment by muglug** [comment]
But my same original issue applies - for this to work, Psalm has to resolve not just the immediate template params but also the template params on the nested call. That's beyond the scope of what I'm prepared to do (it's a very knotty problem).

**Comment by muglug** [comment]
Addendum: here's the `compose` function inferring stuff properly: https://psalm.dev/r/5930311ff5

**Comment by Ocramius** [comment]
Update on this: seems like this is working with OP examples now (tried with psalm 3.9.3)

**Comment by muglug** [comment]
Also the suppressions in the first example won’t be required once https://github.com/vimeo/psalm/issues/2896 is fixed (cc @ragboyjr)

**Comment by drupol** [comment]
Sorry to dig up old topics, but I'm wondering what is the best way to type a kind of `compose` function (just like in https://psalm.dev/r/5930311ff5) but with **variadic** arguments.

**Comment by weirdan** [comment]
@drupol I'm afraid it can only be done with a custom plugin.

**Comment by drupol** [comment]
> @drupol I'm afraid it can only be done with a custom plugin.

Is there some documentation on how I could achieve that? I'm really willing to get through this :)

**Comment by weirdan** [comment]
There's a chapter on plugin authoring here: https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/

I imagine you will need to implement `(Method|Function)ParamsProviderInterface` (where you will check the number of parameters and generate their types like `callable(A):B, callable(B):C, etc`) and `(Method|Function)ReturnTypeProviderInterface` that will take the first / last parameter and use its return type as `compose()` return type. 

Be sure to also check https://psalm.dev/docs/running_psalm/plugins/plugins_type_system/

**Comment by weirdan** [comment]
You may also find valuable inspecting the code of other open source plugins (the list is here: https://psalm.dev/plugins) and internal providers (see https://github.com/vimeo/psalm/tree/master/src/Psalm/Internal/Provider/ReturnTypeProvider).

**Comment by thomasvargiu** [comment]
I was trying this solution, simulating a function overloading, but psalm seems to sum all possibile types:

https://psalm.dev/r/067cdff6d0
