### ISSUE TITLE
Templated lambdas

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#2000]
Spin off from #1999 ([comment](https://github.com/vimeo/psalm/issues/1999#issuecomment-520232476)), just to make sure it's not lost in the closed discussion

@muglug wrote
> I'm not sure whether Psalm supports templates on closures

```php
$wrap =
/**
 * @template A
 * @param A $a
 * @return array{0: A}
 */  
function ($a) : array {
    return [$a];
};

/**
 * @template A
 * @param A $a
 * @return array{0: A}
 */  
function wrap($a) : array {
    return [$a];
}

/** @var int */
$q = 1;
atan($wrap($q)[0]);
atan(wrap($q)[0]);
```
**Expected**: no issues
**Actual**: 
```
Psalm output (using commit 6397421): 

ERROR: InvalidArgument - 23:12 - Argument 1 expects A as mixed, int provided

INFO: MixedArgumentTypeCoercion - 23:6 - Argument 1 of atan expects float, parent type A as mixed provided
```

**Comment by muglug** [comment]
I'm not entirely sure if this would ever be useful, but Psalm should support it.

**Comment by muglug** [comment]
Actually changed my mind, I don't think this is worth it (code for there are a few too many things I'd have to change, and I don't think the utility is worth it).
