### ISSUE TITLE
Possibly dead code `unset(self::$parser->errorHander)`

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#2004]
Seen in src/Psalm/Internal/Provider/StatementsProvider.php when checking for typos

1. Hander seems to be a typo, it should be Handler. There's a local variable $error_handler
2. I can't tell what would set either of those properties

```php
        /** @psalm-suppress NoInterfaceProperties */
        unset(self::$parser->errorHander);
```

**Comment by muglug** [comment]
Thanks, this was added when trying to hunt down memory leaks. Fixing the typo breaks tests, so I just removed the line.
