### ISSUE TITLE
Return type depending on parameter string

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#2009]
We define methods in which the return type is identified/can be mapped based on a string given to the methods, see e.g. https://github.com/redaxo/redaxo/blob/18b5ebf48b9b0ac06dd7e0dff9c57e128fb69fbf/redaxo/src/addons/metainfo/lib/input.php#L126

Is there any way to make this type-information available to psalm?
We cannot change to fqcn references for BC reasons

Using phpstorm project stubs we defined it with e.g. https://github.com/redaxo/redaxo/blob/18b5ebf48b9b0ac06dd7e0dff9c57e128fb69fbf/redaxo/src/core/.phpstorm.meta.php#L106-L114

**Comment by staabm** [comment]
Maybe we could turn this arround and add a mechanism which allows to register a phpstorm stub with psalm?

**Comment by muglug** [comment]
This can be done with a return type provider like [this one](https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Provider/ReturnTypeProvider/DomNodeAppendChild.php).

You would do something like this:
```php
    public static function getClassLikeNames() : array
    {
        return ['rex_input'];
    }

    /**
     * @param  array<PhpParser\Node\Arg>    $call_args
     *
     * @return ?Type\Union
     */
    public static function getMethodReturnType(
        StatementsSource $source,
        string $fq_classlike_name,
        string $method_name_lowercase,
        array $call_args,
        Context $context,
        CodeLocation $code_location,
        array $template_type_parameters = null,
        string $called_fq_classlike_name = null,
        string $called_method_name_lowercase = null
    ) {
        if ($method_name_lowercase === 'factory'
            && isset($call_args[0]->value->inferredType)
            && $call_args[0]->value->inferredType->hasSingleStringLiteral()
        ) {
            switch ($inputType) {
                case 'text':
                case 'textarea':
                case 'select':
                case 'categoryselect':
                case 'mediacategoryselect':
                case 'radio':
                case 'checkbox':
                case 'date':
                case 'time':
                case 'datetime':
                case 'mediabutton':
                case 'medialistbutton':
                case 'linkbutton':
                case 'linklistbutton':
                    return Type::parseString('rex_input_' . $inputType);
            }
            return Type::getNull();
        }
    }
```

Follow the guide here: https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/

**Comment by muglug** [comment]
An alternative (that's be more Psalm-friendly) is to change `rex_input::factory` to instead accept class strings (e.g. `rex_input::factory(\rex_input_text::class)`). That would allow you to dispense with the plugin, and just use template annotations on the method (but it would presumably entail something of a refactor, too).

**Comment by muglug** [comment]
You can also specify the PhpStorm meta file in Psalm’s `<stubs>` config option and it should work - if it doesn’t, that’s a probably a feature I can add quickly.
