### ISSUE TITLE
psalter doesn't seem to understand @inheritdoc

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#2013]
Running `psalm --alter --issues=LessSpecificReturnType` it added `@return` tags even for methods with docblocks like
```
    /**
     * @inheritDoc 
     */
```

I would expect it to leave such docblocks unchanged.

**Comment by ADmad** [comment]
Issue lies in psalm too https://psalm.dev/r/bdbc36c292

**Comment by muglug** [comment]
Constructors are the only methods that cannot inherit their types from the parent (because they can have wholly different types).

**Comment by ADmad** [comment]
Yup constructors can have different signatures but if child class does have same signature and `@inheritDoc` is specified shouldn't psalm understand the types are same?

**Comment by muglug** [comment]
I think `@inheritdoc` should only apply where PHP assumes inheritance

**Comment by ADmad** [comment]
Okay, guess I can live with duplicating the params for the few classes with this issue.

**Comment by ADmad** [comment]
Sorry to bug you about this again but wouldn't it be feasible to compare signature with parent and not throw any error if the signatures are identical?

If implementing such a check would be too much effort then it's okay if it's not done.
