### ISSUE TITLE
Check @throws for valid exception

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#2015]
Pslam doesn't seem to check `@throws` tag in docblock. phpstan throws an error if you specify an invalid class for it while psalm doesn't.

**Comment by ADmad** [comment]
Thanks!

**Comment by muglug** [comment]
You're welcome - it doesn't yet target the exact location (https://psalm.dev/r/63e00385cf), but it should be otherwise good.

**Comment by ADmad** [comment]
Just for reference this is what phpstan's message looks like:

```
PHPDoc tag @throws with type Foo\Bar is not subtype of Throwable
```

**Comment by muglug** [comment]
I've changed Psalm's message from

```
Cannot throw Foo\Bar as it does not implement Throwable
```

to

```
Class supplied for @throws Foo\Bar does not implement Throwable
```
