### ISSUE TITLE
Unexpected ParadoxicalCondition

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#2027]
I dont expect the error which gets reported regarding $setter

https://psalm.dev/r/ae34064cf5

**Comment by muglug** [comment]
Reduced to

```php
function foo(string $key) : void {
  $setter = 'a' . $key;
  if (is_callable($setter)) {
    return;
  }
  $setter = 'b' . $key;
  if (is_callable($setter)) {}
}
```

https://psalm.dev/r/a2da7fef18

**Comment by staabm** [comment]
Fix confirmed, work with latest master version in our project. ❤️
