### ISSUE TITLE
PHP warning on PHP 7.2

### ISSUE THREAD

**Issue by paragonie-scott** [vimeo/psalm#203]
```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/travis/build/paragonie/halite/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php on line 1290
```

From https://travis-ci.org/paragonie/halite/jobs/266322358

https://github.com/vimeo/psalm/blob/d6e2e786db086877dd1b4308b39ad227097b4456/src/Psalm/Checker/ProjectChecker.php#L1290

**Comment by muglug** [comment]
Thanks! Fixed dumb and prevented it from reoccurring.
