### ISSUE TITLE
Constants within complex expressions cannot be type inferred

### ISSUE THREAD

**Issue by lhchavez** [vimeo/psalm#2031]
I haven't fully identified what the minimal reproduction case is, but there are cases where a class constant's type cannot be inferred when inside a complex expression (example https://psalm.dev/r/51c2ee1d7e):

```php
<?php
  
class A {
  private const STRING = 'x';

  public static function foo() : bool {
    return strpos('x', self::STRING) === 0;  // this works.
  }

  public static function bar() : bool {
    return !defined('FOO') && strpos('x', self::STRING) === 0;  // this does not.
  }
}
```

```text
Psalm output (using commit c98c160):

INFO: MixedArgument - 11:43 - Argument 2 of strpos cannot be mixed, expecting string|int
```

**Comment by lhchavez** [comment]
a-ha! found it. There is some amount of manipulation of `$context` within `FunctionCallAnalyzer.php` that is not reset when an expression is done being processed. i'll try to introduce something like Chromium's [`ScopedClosureRunner`](https://codesearch.chromium.org/chromium/src/base/callback_helpers.h?q=symbol:base::ScopedClosureRunner) or [`AutoReset`](https://codesearch.chromium.org/chromium/src/base/auto_reset.h?q=symbol:base::AutoReset) in order to simplify the state management of the context.

**Comment by lhchavez** [comment]
before that, also took a stab at Context's `$parent_context` to avoid re-inventing the wheel and neatly isolating all changes, but it seems like the function call context needs to propagate _some_ things (e.g. if something is `define`d).

**Comment by muglug** [comment]
so I don't even think that's necessary. When I first created Psalm I was also super cautious about `function_exists` and `class_exists` - after they were called, subsequent calls of _existing_ functions and usage of _existing_, reflectable classes was mangled. Now they work mostly as expected - I just need to extend that to `defined` too.

**Comment by muglug** [comment]
Basically, this check should be moved further inside: https://github.com/vimeo/psalm/blob/c98c16090749aac83f8398409d86a0c22948c2b5/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ConstFetchAnalyzer.php#L99

**Comment by lhchavez** [comment]
oh that was fast! thanks so much for fixing it!

**Comment by muglug** [comment]
You're welcome - things that are obviously wrong tend to get fixed quickly
