### ISSUE TITLE
Suppress with short-open tags in a single line

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#2032]
I expected this psalm-suppres to work for the following statement after it

https://psalm.dev/r/4b5a49a863

**Comment by muglug** [comment]
I think a better solution here would be a Psalm annotation like

```
<?php
/** @psalm-scope-this Foo\Bar\Baz */
?>
```

**Comment by staabm** [comment]
Sounds perfect to me

**Comment by muglug** [comment]
Closing now that `@psalm-scope-this` works
