### ISSUE TITLE
Add a --bootstrap-file= option

### ISSUE THREAD

**Issue by williamdes** [vimeo/psalm#2037]
I did not find any option to inject a bootstrap file, I really need that because at @phpmyadmin we have `__('translate me')` functions calls everywhere (https://github.com/phpmyadmin/motranslator), they are loaded before all the code.

For phpstan we use the https://github.com/phpstan/phpstan#bootstrap-file option and it works great !
https://github.com/phpmyadmin/phpmyadmin/blob/master/test/bootstrap-phpstan.php

Please help me find the option or implement it if possible ! :)

Thanks

**Comment by muglug** [comment]
Check out https://psalm.dev/docs/running_psalm/configuration/#running-psalm - the `autoloader` param is what you want, I think (akwardly-named, as it was originally intended to specify a custom autoloader we used at Vimeo)
