### ISSUE TITLE
apcu_add(), apcu_inc(), umask(),  gives UnusedFunctionCall

### ISSUE THREAD

**Issue by thomasbley** [vimeo/psalm#2038]
https://psalm.dev/r/ce6cf42869

version: 3.4.12
actual: The call to apcu_add is not used
expected: no error

**Comment by muglug** [comment]
Would you mind adding them (and anything else you find) to this list? https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Codebase/Functions.php#L300

**Comment by thomasbley** [comment]
sure will do it tonight and open a PR for it
