### ISSUE TITLE
Crash with @deprecated annotation on a variable

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#2041]
```php
<?php
  
/** @deprecated */
$a = 'A';
// Fatal error: Uncaught Error: Call to a member function queueClassLikesForScanning() on null in src/Psalm/Internal/Visitor/ReflectorVisitor.php:462
```
https://psalm.dev/r/992c674c3f

The crash seems to have been introduced by a change between 3.4.11 and 3.4.12.

**Comment by muglug** [comment]
Thanks, this was because Psalm's own config suppressed `MissingConstructor` for the file with a bad type definition.
