### ISSUE TITLE
ucfirst should be fine in function call by name

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2047]
```php
function fooBar(): void {}

$foo = 'foo';
$bar = 'bar';

($foo . ucfirst($bar))();
```

> ERROR: UnusedFunctionCall - 8:9 - The call to ucfirst is not used

https://psalm.dev/r/e38bd0ea66

IMO this should be fine, don't you think? I know technically it doesn't matter to PHP if the casing of the called method is ok but I'd like to think that someday PHP might become case sensitive (you may say I'm a dreamer).

**Comment by weirdan** [comment]
`ucfirst` result should be considered as used here, regardless of the function case match or mismatch, as it's used in concatenation.

**Comment by muglug** [comment]
yeah, [this check should be expanded] to include something like `$context->in_function_name`

**Comment by iluuu1994** [comment]
Thank you!
