### ISSUE TITLE
Call to session_name is unused

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2050]
```php
session_name('SVSESSID');
@session_start();
```

> UnusedFunctionCall - 3:1 - The call to session_name is not used

https://psalm.dev/r/a71f956ab5

This shouldn't error.

**EDIT**: 

Same thing with:

*  `session_id`
* `ldap_set_option`

**Comment by muglug** [comment]
Mind PRing an update to this list? https://github.com/vimeo/psalm/blob/738ba81185abbdd25d5e99940080c2f713ec1da1/src/Psalm/Internal/Codebase/Functions.php#L269

**Comment by iluuu1994** [comment]
Not at all, just wasn't aware of this 🙂

**Comment by muglug** [comment]
It's a very new list!
