### ISSUE TITLE
Catch block type not used for type inference

### ISSUE THREAD

**Issue by kelunik** [vimeo/psalm#2060]
**Example**

```php
<?php
  
function test() {
  try {
    
  } catch (\Throwable $e) {
    // fall through
  }
  
  throw new Exception('', 0, $e ?? null);
}
```

**Output**

```
INFO: MixedArgument - 10:30 - Argument 3 of Exception::__construct cannot be mixed, expecting null|Throwable|Exception
```

https://psalm.dev/r/79e8eefda3

**Expectation**

There shouldn't be an error, because `$e` is always `Throwable|null`

**Comment by muglug** [comment]
You can work around this by initialising `$e` to null before the try/catch: https://psalm.dev/r/8c3528e39e

Those this is a false-positive, I’m not going to fix as it would mean making a large number of changes to how Psalm handles variables.
