### ISSUE TITLE
Is the incomplete phpdoc @var documented anywhere?

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#2065]
In my desperate attempts to type a line with `$data` assignment in the following code https://psalm.dev/r/c73a7e3d1c

```php
<?php
  
/** @var mixed $data */
$data = 42;

$arr = [];
/** @var array{k: mixed} */
$arr['k'] = $data;

echo count($arr);
```

I accidentally found that an "incomplete" (not sure it's a thing, I could not find any references to it) `@var` notation works for that code.

While a "complete" version does not: `/** @var array{k: mixed} $arr */`

I believe the "complete" notation should work in this case.

And should the "short" one even be valid?

**Comment by muglug** [comment]
The short one should be valid - at least, it’s used a lot in the wild (though some linters prevent it). But the long version should also work, and that’s a bug.

**Comment by muglug** [comment]
This also works (no spaces): https://psalm.dev/r/69ce009611

**Comment by muglug** [comment]
This appears to work now
