### ISSUE TITLE
RedundantCondition for config constants

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2076]
Many of our applications look like this:

```php
class Config {
  const DB_DRIVER = 'pdo_sqlsrv'; // Yes, we use sqlsrv :'(
}

if (Config::DB_DRIVER === 'pdo_sqlsrv') {
  // ...
}
```

> ERROR: RedundantCondition - 7:5 - Found a redundant condition when evaluating Config::DB_DRIVER and trying to reconcile type 'string(pdo_sqlsrv)' to string(pdo_sqlsrv)

https://psalm.dev/r/3ed817ceba

I'm aware this isn't great. Constant shouldn't contain variable values. Either way, PHPStan allows defining constants as "dynamic": https://github.com/phpstan/phpstan/pull/1083

Do you see any value in this?

**Comment by iluuu1994** [comment]
@muglug Yeah that would probably be better but unfortunately this is something I just can't change. Anyway, I'll just close this. Psalm shouldn't have to deal with badly designed codebases.

**Comment by bugreportuser** [comment]
I'd also like to see this. I think it's a pretty common thing to do:
- https://stackoverflow.com/questions/11427681/how-to-define-a-php-config-file-that-define-constant-and-use-it-any-where-in-pro
- https://github.com/WordPress/WordPress/blob/363cfc4301c84d1fb388b6defded9db415ffe1ab/wp-config-sample.php
- https://github.com/cakephp/cakephp/blob/master/tests/bootstrap.php

**Comment by iluuu1994** [comment]
Truth is this is horrible for testability and reusability. I'd much rather it weren't this way in our application but it's not something I can change easily.

Your config values should probably be coming from a separate file and be distributed through dependency injection or something like similar.

**Comment by bugreportuser** [comment]
I don't even see this being useful just for config constants. Most times, the value of a constant doesn't matter. So, if your application breaks when the value of a constant changes to a different value of the same type, that can be a problem.
