### ISSUE TITLE
Better support for compact

### ISSUE THREAD

**Issue by bugreportuser** [vimeo/psalm#2084]
Psalm [gives an error](https://github.com/vimeo/psalm/commit/5770a6c904c33be736d952c31a6d596b8e1c3299) when `compact()` is used on an undefined variable. However, it still infers the type as `array<array-key, mixed>`.

Example (https://psalm.dev/r/bfab55228d):
```php
<?php
$x = 'str';
$y = 0;
$example = compact('x', 'y');
echo ord($example['x']);
echo chr($example['y']);
```

Example output:
```
Psalm output (using commit 1f0aca0):

INFO: MixedArgument - 5:10 - Argument 1 of ord cannot be mixed, expecting string

INFO: MixedArgument - 6:10 - Argument 1 of chr cannot be mixed, expecting int
```

It should be able to treat that example as:
```php
<?php
$x = 'str';
$y = 0;
$example = ['x' => $x, 'y' => $y];
echo ord($example['x']);
echo chr($example['y']);
```

**Comment by muglug** [comment]
Do people use `compact`? I'd rather not support this IMO bad function.

**Comment by bugreportuser** [comment]
It's debatable. I think `extract` is actually the problem, but they're usually grouped together.

`compact` is basically syntactic sugar. A parser can transform `compact('x', 'y')` into `['x' => $x, 'y' => $y]` as easily as `$x ?? 10` into `isset($x) ? $x : 10`. If you pass variable strings to `compact`, that's when it becomes a bad function.

**Comment by muglug** [comment]
yeah, but it's not particularly sugary because it comes in the form of a function that takes a bunch of strings.

**Comment by bugreportuser** [comment]
That's pretty common in PHP:

```php
constant('constant');
array_map('function', []);
get_parent_class('class');
```

**Comment by muglug** [comment]
🙈

**Comment by still-dreaming-1** [comment]
Psalm would have slightly better support for compact if it at least understood the returned array key type was a string instead of array-key, although that would not exactly fix the issues of the OP.

**Comment by still-dreaming-1** [comment]
Actually I was interested in making that change myself (improving key type), but I couldn't find anywhere in Psalm's code where return type of compact was specified. It seemed likely to me this would be hard coded somewhere, but I couldn't find it. I did look through the contributions guide, but I still couldn't figure it out.. There is another similar contribution I would like to attempt as well.

**Comment by bugreportuser** [comment]
@still-dreaming-1 It's in [the callmap](https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/CallMap.php).

```php
'compact' => ['array', 'var_name'=>'string|array', '...var_names='=>'string|array'],
```

The first element is the return type, which can be replaced with `array<string,mixed>`.

**Comment by muglug** [comment]
This is fixed

**Comment by bugreportuser** [comment]
Thanks!
