### ISSUE TITLE
Setting @readonly properties for new instance in static constructor 

### ISSUE THREAD

**Issue by EvgeniiR** [vimeo/psalm#2085]
I like to do named constructors like this: https://psalm.dev/r/b8fb7dfc55
And i thought that it didn`t contradict with "Psalm will complain when trying to manipulate a property with that annotation from outside the class.", but get InaccessibleProperty error.

Is it expected behavior, and i should do only like this - https://psalm.dev/r/479a810a8f ?

**Comment by muglug** [comment]
It's expected behaviour. I could _maybe_ allow it on classes that don’t have a constructor, but I wonder if that's too accommodating.

**Comment by EvgeniiR** [comment]
@muglug In my case, i use such technique for creating Data Transfer Objects, cause sometimes they have many properties, constructor presents, but it`s empty and private ( https://psalm.dev/r/ab8457c297 )

**Comment by muglug** [comment]
I'm not going to allow this (following example set by other constructor checks).
