### ISSUE TITLE
Override type information for library functions

### ISSUE THREAD

**Issue by joehoyle** [vimeo/psalm#2088]
Is it possible to override the type information for functions / classes when you don't want to edit the library source code, kinda of like how Typescript lets you provide types for untyped modules.

I think I _could_ use stubs, but then I'd need to provide stubs for _all_ library functions, but I want to just override some.

**Comment by muglug** [comment]
You don’t need to provide stubs for all functions! Psalm just substitutes the ones you provide.

**Comment by joehoyle** [comment]
From what I'm seeing, when this is done, the types are merged, rather than replaced. E.g. this is in my stubs file: 

```php
/**
 * Apply a filter
 *
 * @template TFilterValue
 * @param string $a
 * @psalm-param TFilterValue $value
 * @return TFilterValue
 */
function apply_filters( string $a, $value ) {
	return $value;
}
```

(this is a function that returns the same type of what you passed in `$value`. It is defined elsewhere in the codebase with `@return mixed`. The types then for:


```php
$value = apply_filters( 'awd', '' );
```
Are shown as `@var mixed|TFilterValue $value`, where I'd expect it to be `TFilterValue`.

**Comment by muglug** [comment]
would you be able to reproduce in a test? Maybe in `StubsTest.php`?
