### ISSUE TITLE
standalone annotations parser

### ISSUE THREAD

**Issue by DerManoMann** [vimeo/psalm#2094]
Hi there,

Just came across this very nice looking project while looking for something that can parse PHPDoc collections anotations.
Is there any way of just using the annotation parser part as a kind of replacement for phpDocumentor?

**Comment by muglug** [comment]
What exactly do you want to do?

**Comment by DerManoMann** [comment]
I have a library to de-serialize JSON into nested object structures [json-object-mapper](https://github.com/DerManoMann/json-object-mapper).

Right now I am using the Symfony property-info component which, in turn, uses phpDocumentor.

There are currently 2 shortcomings:
* No support for collections, in particular I am looking for spport for something like `@var \ArrayObject[string]` / `\ArrayObject<string>`
* symfony doesn't support using multiple extractors at the same time, its either phpdoc or type hints or whatever else there is. (this is not really related to this question, tho)

**Comment by muglug** [comment]
Hey!

So the annotation flow is a few different things:

1. [ReflectorVisitor](https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Visitor/ReflectorVisitor.php) that iterates over the PHP AST, among other things finding docblocks to parse.

2. [DocComment](https://github.com/vimeo/psalm/blob/master/src/Psalm/DocComment.php) which parses docblock text, preserving offset information so Psalm can identify errors more specifically.

3. The [type tokenizer](https://github.com/vimeo/psalm/blob/071fae98b2b89bb58cbf3a90b15b655f00d8629d/src/Psalm/Type.php#L760) that breaks apart types into tokens.

4. The [type parser](https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Type/ParseTree.php) that turns the type tokens into an type AST.

5. The [Psalm type creator](https://github.com/vimeo/psalm/blob/071fae98b2b89bb58cbf3a90b15b655f00d8629d/src/Psalm/Type.php#L223) that takes a type AST and returns a Psalm type.

Steps 2-4 could reasonably be moved into a separate package without disrupting how Psalm works.

**Comment by DerManoMann** [comment]
Cool, thanks for the details. I'll have a look see if the code might fit for me.

Might be a bit more work that asked for to split the code off, but we'll see - hard for me to judge if there is motivation to actually accept such a change, tho...

Anyway, will add updates as I go :)

**Comment by muglug** [comment]
I'll close this for now, feel free to reopen with concrete steps!
