### ISSUE TITLE
Callables incorrect for set_error_handler

### ISSUE THREAD

**Issue by auroraeosrose** [vimeo/psalm#2097]
https://psalm.dev/r/73174c4096

The "use our current object instance and a method name" format of a callable appears to not be properly accepted for set_error_handler

**Comment by muglug** [comment]
So this is bad on Psalm's part, messaging-wise, but that callable expects a boolean return: https://psalm.dev/r/ca2e4a92d5

**Comment by muglug** [comment]
I've opened https://github.com/vimeo/psalm/issues/2098 to track that

**Comment by auroraeosrose** [comment]
Thanks!
