### ISSUE TITLE
Allow different errorLevels on different files

### ISSUE THREAD

**Issue by nickyr** [vimeo/psalm#21]
In the psalm.xml, you can currently set an error level for all files except a few, where it will be suppressed:

```xml
        <MissingReturnType errorLevel="info">
            <excludeFiles>
                <directory name="tests" />
            </excludeFiles>
        </MissingReturnType>
```

And you can set an error level for specific files, and suppress it everywhere else:

```xml
        <MissingReturnType errorLevel="info">
            <includeFiles>
                <directory name="src" />
            </includeFiles>
        </MissingReturnType>
```

But there's no way to have some files set to info, and some set to error. One possible syntax could be:

```xml
        <MissingReturnType errorLevel="info" />

        <!-- overrides the previous errorLevel for these files -->
        <MissingReturnType errorLevel="error">
            <includeFiles>
                <directory name="src" />
            </includeFiles>
        </MissingReturnType>
```

A big plus of this syntax is that it's backwards compatible with the current syntax. Downside is you now have rules for one error in two different blocks. 

You could also add a tag like this, to avoid having two blocks and still be backwards compatible:

```xml
        <MissingReturnType errorLevel="info">
            <levelOverride errorLevel="error">
                <directory name="src" />
            </levelOverride>
        </MissingReturnType>
```

In this example, everything would get level 'info' except things in `src` would get level 'error'.

Open to any other suggestions too.

**Comment by muglug** [comment]
How about

```xml
<MissingReturnType errorLevel="info">
  <includeFiles>
    <directory name="src" errorLevel="error" />
  </includeFiles>
</MissingReturnType>
```

**Comment by nickyr** [comment]
@muglug the problem with that is it changes the behavior of `includeFiles` in a way that's not clear.

This means that you *only* apply the error level 'info' to the included files and suppress everything else:

```xml
<MissingReturnType errorLevel="info">
  <includeFiles>
    <directory name="src" />
  </includeFiles>
</MissingReturnType>
```

Saying that the error will no longer be suppressed on all other files when you add `errorLevel="error"` to the directory in the `includeFiles` block is counterintuitive.

**Comment by muglug** [comment]
oh right. How about, similar to your `levelOverride`, 
```xml
<InvalidReturnType errorLevel="info" />

<MissingReturnType>
  <errorLevel name="suppress">
    <directory name="tests" />
  </errorLevel>
  <errorLevel name="info">
    <directory name="src" />
  </errorLevel>
</MissingReturnType>
```
which could replace `includeFiles` and `excludeFiles` entirely

**Comment by nickyr** [comment]
that looks nice! maybe it should include the default error level still though? so you could do

```xml
<MissingReturnType defaultErrorLevel="info">
  <errorLevel name="suppress">
    <directory name="tests" />
  </errorLevel>
  <errorLevel name="error">
    <directory name="src/Critical" />
  </errorLevel>
</MissingReturnType>
```

Because otherwise if you have a lot of directories you'd have to specify each one individually. `defaultErrorLevel` could be an alias of the current `errorLevel`. Just adding the default on here because I think it reads better.

**Comment by muglug** [comment]
yeah, I would definitely support having `errorLevel` at the root too – but maybe without the `default` – fewer keywords to worry about

**Comment by nickyr** [comment]
Sounds good!

**Comment by olleharstedt** [comment]
Hm, what's current status of this?

**Comment by orklah** [comment]
This issue is closed and the feature was implemented for a while. See https://github.com/vimeo/psalm/blob/4.x/psalm.xml.dist#L67

**Comment by orklah** [comment]
you can have a --config=your-file.xml too with psalm

**Comment by ThomasLandauer** [comment]
Thanks, see https://github.com/vimeo/psalm/pull/11332 :-)
