### ISSUE TITLE
Too many arguments false positive for method print_r with invalid arg

### ISSUE THREAD

**Issue by ArtemGoutsoul** [vimeo/psalm#2101]
`TooManyArguments: Too many arguments for method print_r - expecting 1 but saw 2`

print_r can actually have two arguments: 
`print_r ( mixed $expression [, bool $return = FALSE ] ) : mixed`
https://www.php.net/manual/en/function.print-r.php

**Comment by muglug** [comment]
Can you reproduce on https://psalm.dev? I'm unable to

**Comment by weirdan** [comment]
https://psalm.dev/r/9457fbb751 - reproducible with invalid type for the second argument.
