### ISSUE TITLE
Erroneous return type matched when using multiple interfaces using `self` as return type

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2102]
See https://psalm.dev/r/8170d89c39:

```php
<?php

interface Id {}
interface Foo
{
    public function id() : Id;
}

class ImplementsFoo implements Foo, Id
{
     public function id() : self
     {
          return $this;
     }
}
```

Reports:

```
Psalm output (using commit ae2c671):

ERROR: MethodSignatureMismatch - 9:7 - Method ImplementsFoo::id with return type 'ImplementsFoo' is different to return type 'Id' of inherited method Foo::id
```

Even simpler in https://psalm.dev/r/494e02869f:

```php
Psalm output (using commit ae2c671):

ERROR: MethodSignatureMismatch - 8:7 - Method ImplementsFoo::id with return type 'ImplementsFoo' is different to return type 'Foo' of inherited method Foo::id
```

Reports:

```
<?php

interface Foo
{
    public function id() : self;
}

class ImplementsFoo implements Foo
{
     public function id() : self
     {
          return $this;
     }
}
```

Related: https://github.com/sebastianbergmann/phpunit/issues/3120

**Comment by Ocramius** [comment]
Ah... this is a PHP 7.4 thing, my bad.

Working on bleeding edge spoiled me.

**Comment by muglug** [comment]
Yeah I'll disable this when Psalm detects it's running on 7.4

**Comment by muglug** [comment]
I have other features (e.g. arrow functions) ready to ship, but I don't want to bump the upstream dependency (`nikic/php-parser`) version until necessary, once 7.4 is publicly available

**Comment by zmitic** [comment]
@muglug Can you put arrow functions support in master or fork? I would really like to get rid of errors like this: 

![image](https://user-images.githubusercontent.com/1964158/67329617-66da1080-f51b-11e9-8abc-ab3dd773485c.png)

**Comment by Ocramius** [comment]
@zmitic a bit of patience: PHP 7.4 isn't even out yet :-)

**Comment by zmitic** [comment]
@Ocramius I know, I know... but I love it :smile: 

Above example is just one small thing. More complex are coming tomorrow when I put entity accessors: https://github.com/hitechcoding/strict-form-mapper-bundle/blob/master/docs/accessors.md

Arrow functions really makes these things easier.

**Comment by muglug** [comment]
@zmitic the branch (`arrow-functions`) already exists, I've just rebased it on top of latest master.

I'll add Psalm compatibility about a week before PHP's 7.4 release date.

**Comment by zmitic** [comment]
@muglug Thank you, a lot! My errors are gone now.
