### ISSUE TITLE
Allow intersection types on arrays?

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2105]
While working on a lot of existing code that is very `array_merge()`-intensive, I found out that psalm can't annotate intersections of arrays.

I think it would be interesting to add it, for example in cases like following (https://psalm.dev/r/e6fe3afebb):

```php
<?php

/**
 * @psalm-template T of array
 * @psalm-param T $map
 * @return T&array{potato: string}
 */
function addPotato(array $map) : array
{
    $map['potato'] = 'the potato';

    return $map;
}
```

```
Psalm output (using commit ae2c671):

ERROR: InvalidDocblock - 8:1 - Intersection types must all be objects, Psalm\Type\Atomic\ObjectLike provided in docblock for addPotato
```

Or also simpler (without generic type - https://psalm.dev/r/a610a70b23):

```php
<?php

/**
 * @psalm-param array<string, string> $map
 * @psalm-return array<string, string>&array{potato: string}
 */
function addPotato(array $map) : array
{
    $map['potato'] = 'the potato';

    return $map;
}
```

```
Psalm output (using commit ae2c671):

ERROR: InvalidDocblock - 7:1 - Intersection types must all be objects, Psalm\Type\Atomic\TArray provided in docblock for addPotato
```

Examples of intersections could be something like:

 * `array{a: int}&array{b: int}` => `{a: int, b: int}`
 * `array{a: int}&array{a: string}` => type error
 * `array<string, string>&array<string, int>` => type error
 * `array<string, string>&array{a: int}` => type error
 * `array<string, string>&array{a: string}` => `array<string, string>&array{a: string}` (not merged)

**Comment by muglug** [comment]
This is a no from me, sorry - the rules governing how arrays are created and modified are already complicated enough, without adding this additional wrinkle.

**Comment by Ocramius** [comment]
Works for me 👍

**Comment by orklah** [comment]
For anyone subscribed here or that ends up here after a search, this was implemented here: https://github.com/vimeo/psalm/pull/3064
