### ISSUE TITLE
erroneous InvalidPropertyAssignmentValue when assigning values between identically templated properties

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2107]
https://psalm.dev/r/50554fc591
```
<?php
/**
* @template T as array<string, scalar|array<int, scalar>>
*/
class Foo {
  /**
  * @var T
  */
  public $a = [];
}

/**
* @template T as array<string, scalar|array<int, scalar>>
*/
class Bar
{
  /**
  * @var T
  */
  public $a = [];
  
  public function Foo() : Foo
  {
    $foo = new Foo();
    $foo->a = $this->a;
    
    return $foo;
  }
}
```
> Psalm output (using commit b61d0c6):
>
> ERROR: InvalidPropertyAssignmentValue - 25:15 - $foo->a with declared type 'T as array<string, array<int, scalar>|scalar>' cannot be assigned type 'T as array<string, array<int, scalar>|scalar>'
> 
> INFO: UnusedClass - 15:7 - Class Bar is never used

**Comment by muglug** [comment]
Closing because you're trying to assign one templated param to another (feel free to suppress the issue)

**Comment by SignpostMarv** [comment]
the templated types are identical/compatible though? The error message/type is a little confusing.

**Comment by weirdan** [comment]
> the templated types are identical/compatible though?

Not necessarily. Template type constraint (the part after `as`) gives the upper boundary of a type, and you can narrow it down when instantiating the templated instance. Here, the types are incompatible, even though they share the same upper boundary, much like `string` and `int` are incompatible even though they share the same top type (`mixed`). Meaning you could have `Bar<T as array<string, int>>` and `Foo<T as array<string, array<int, bool>>>`. These are valid instances of the generic types you defined, but their type parameters are obviously not the same (and obviously incompatible).

**Comment by SignpostMarv** [comment]
Have tinkered with it further- it appears to work so long as at least one side is `psalm-type`d rather than templated.
