### ISSUE TITLE
Impure method call in a static factory

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#2109]
https://psalm.dev/r/b339171524

Hi! Testing new great functionality.  I think, static methods should not be taken into account when checking dynamic part of class for immutability, should it?

**Comment by muglug** [comment]
Static methods can still be called on the instance e.g. `$foo->someStaticMethod()`. In that example I just think you can use `/** @psalm-suppress ImpureMethodCall */

**Comment by vudaltsov** [comment]
@muglug , static methods can be called on the instance, that's true, but within a static method you cannot mutate the state because you don't have access to `$this`.

**Comment by vudaltsov** [comment]
this is also mentioned in the initial proposal you referenced in the release.
https://github.com/vimeo/psalm/issues/1272#issuecomment-459952600

> We're talking about immutable objects after all. Also static factory methods can be conveniently placed in the same immutable class, and such factory methods may need to mutate the state.

**Comment by muglug** [comment]
Good points, I'll revert static methods to being impure, and clean up the documentation
