### ISSUE TITLE
Handling immutable objects with cloning factory methods

### ISSUE THREAD

**Issue by jaikdean** [vimeo/psalm#2111]
We have a couple of examples where we have public methods in a class that create a copy of the object with a single value changed: https://psalm.dev/r/c68a9534ba

It's the same kind of behaviour as `DateTimeImmutable::add()`, for example. Is `@psalm-immutable` not the right thing to use in this context, or is this a bug?

**Comment by muglug** [comment]
That is absolutely a bug, I forgot about `clone`

**Comment by snapshotpl** [comment]
@muglug what about case https://psalm.dev/r/e8927989fd ?
