### ISSUE TITLE
array_map() and array_filter() considered impure?

### ISSUE THREAD

**Issue by jaikdean** [vimeo/psalm#2112]
Example: https://psalm.dev/r/81b5127c15

We call `array_map()` and `array_filter()` in a method in what we consider to be an immutable object. Psalm is complaining about this, I assume because an impure callable _can_ be passed into these functions? Is there any way to annotate this example correctly for Psalm to understand?

**Comment by muglug** [comment]
Yup, this will be fixed by tomorrow. Psalm just needs to introspect on the callables.

**Comment by jaikdean** [comment]
Awesome, thanks @muglug

**Comment by BenMorel** [comment]
Is this really fixed? I'm having the same issue: https://psalm.dev/r/aa2b6f809d

**Comment by weirdan** [comment]
It is. Purity of `array_map()/array_filter()` now depends on whether the callable they receive is pure. You may want to declare that you only accept pure callables by prefixing `Closure` with `pure-`: https://psalm.dev/r/4f237c3360

**Comment by BenMorel** [comment]
Thanks a lot, @weirdan! Makes sense.

**Comment by yevsid** [comment]
Seems this issue is still present when using array syntax for callables https://psalm.dev/r/db993dc30e
