### ISSUE TITLE
Psalter should suggest candidates for @psalm-pure, @psalm-mutation-free etc

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2117]
re: [twitter](https://twitter.com/SignpostMarv/status/1171406901881581569), requesting that psalm/psalter suggest candidates for new docblock tags.

**Comment by SignpostMarv** [comment]
thought: with verbose option for listing *why* a method isn't a candidate for pure/mutation-free, etc.

**Comment by muglug** [comment]
Psalm now does this!

**Comment by HenkPoley** [comment]
This was already added in August?

E.g. MissingPureAnnotation: https://github.com/vimeo/psalm/commit/94cec1559891ef32bf6d443f9e796a674994b6af
