### ISSUE TITLE
query re: xdebug filter

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2118]
I'm thinking that the xdebug filter (e571c182993b055fef190dfa0607a4271f1059b4) explains why psalm thinks `XDEBUG_FILTER_CODE_COVERAGE` etc. are undefined?

If this is the case, is it possible for psalm to ship with a stub that's only loaded if xdebug was loaded before check is called?

**Comment by muglug** [comment]
Mind creating a stub?

**Comment by SignpostMarv** [comment]
sure :)

just having a tinker here- it's hypothetically possible to get the xdebug constants/functions at runtime, although I'm not sure how that'd impact startup performance of psalm (as it'd be doing runtime reflection while xdebug is active).

**Comment by SignpostMarv** [comment]
explored using source code parsing last night (i.e. automating stub generation), but one tool wasn't running on windows & couldn't make head nor tails of the other; I'll give the docs a look & do it manually.

**Comment by SignpostMarv** [comment]
closed as per #2133
