### ISSUE TITLE
Impossible to use @psalm-immutable or @psalm-readonly for static properties

### ISSUE THREAD

**Issue by dbalabka** [vimeo/psalm#2120]
I'm tried to use read-only static properties (similar to Java final) to implement PHP enumeration classes and control class immutability with Psalm (see https://github.com/dbalabka/php-enumeration). Unfortunately, it is impossible to use `@psalm-immutible` or `@psalm-readonly` for static properties

Code example: https://psalm.dev/r/4d44c9de62

**Comment by muglug** [comment]
Problem with static properties is that there might not be a constructor, so there's no place to verify that it's only assigned to once.

**Comment by dbalabka** [comment]
@muglug how the public properties w/o constructor usage are handled then? Or I misunderstand the reason or technical limitation?

**Comment by muglug** [comment]
immutable properties are only allowed to be mutated in a constructor.
