### ISSUE TITLE
Assertion on `mixed[]` leads to internal error

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#2121]
https://psalm.dev/r/44f60db67a

```php
<?php
  
/**
 * @param mixed[] $a
 */
function one(array $a): void {
  isInts($a);
}

/**
 * @psalm-assert int[] $value
 * @param mixed $value
 */
function isInts($value): void {}
```

Expected: it should be fine
Actual: it's not fine

```
Internal Psalm error on line 208 - /var/www/vhosts/psalm.dev/httpdocs/vendor/vimeo/psalm/src/Psalm/Type/Atomic.php: Unrecognized type array<array-key, int>
```

**Comment by zerkms** [comment]
Actually, it happens on any array type: https://psalm.dev/r/1c55f1fd97

**Comment by zerkms** [comment]
And it looks like another case that hits the same problem https://psalm.dev/r/aad07c80e3

**Comment by muglug** [comment]
It's not a valid assertion, but now Psalm will complain properly

**Comment by zerkms** [comment]
> It's not a valid assertio

hm, why is it not?

**Comment by muglug** [comment]
Because I haven't written that code... valid assertions can be found here: https://psalm.dev/docs/annotating_code/assertion_syntax/
