### ISSUE TITLE
Tell if a division results in an int

### ISSUE THREAD

**Issue by ntzm** [vimeo/psalm#2132]
https://psalm.dev/r/d451f2d5f2

If we know the value of two constants, we should be able to infer int or not

**Comment by SignpostMarv** [comment]
> I'm slightly hesitant to add this mainly just because it's rare we know the value of both sides of a division operation, but I suppose I guess it makes sense when evaluating class constants

```php
bcdiv('500', '3'); // string(166) or numeric(166)
bcdiv('500', '3', 1); // string(166.6) or numeric(166.6)
```

see also ridiculous context:
```php
json_decode(bcdiv('500', '3')); // int(166)
```

**Comment by SignpostMarv** [comment]
@muglug if a `TInt` is multiplied by a `TLiteralInt`, then the resulting `TInt` can be divided by any of the `TLiteralInt`'s factors ?
