### ISSUE TITLE
query re: getVendorDir()

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2137]
It looks like the `getVendorDir()` isn't used with `psalm --init`- how much of a pita would it be to add that in?

**Comment by muglug** [comment]
not sure I follow

**Comment by SignpostMarv** [comment]
the default config for psalm (`psalm --init`) includes the vendor directory in the `<ignoreFiles>` section; if `composer.json` has the vendor directory set elsewhere, then the vendor files won't be ignored.

**Comment by SignpostMarv** [comment]
see https://github.com/SignpostMarv/psalm-issue-2137/blob/b04eaf74574bfb84748def7ea04970fc7d8303f5/composer.json#L8 and https://github.com/SignpostMarv/psalm-issue-2137/blob/b04eaf74574bfb84748def7ea04970fc7d8303f5/psalm.xml#L12
