### ISSUE TITLE
Immutability/purity is not enforced in inheritance/contracts

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2138]
Following example (https://psalm.dev/r/e5b578def2) is a clear violation of purity rules:

```php
<?php

/** @psalm-immutable */
interface SomethingImmutable {
    public function someInteger() : int;
}

class MutableImplementation implements SomethingImmutable {
    private int $counter = 0;
    public function someInteger() : int {
        return ++$this->counter;
    }
}

/** @psalm-pure */
function useSomething(SomethingImmutable $something) : int
{
    return $something->someInteger();
}

$instance = new MutableImplementation;

echo useSomething($instance);
echo useSomething($instance);
```

Psalm does not find errors, but it should probably implicitly propagate `@psalm-immutable` to `MutableImplementation`, and flag it as an error.

**Comment by Ocramius** [comment]
Note: same rule for inheritance, interfaces and traits (if traits ever apply at all)

**Comment by weirdan** [comment]
> but it should probably implicitly propagate `@psalm-immutable` to `MutableImplementation`

Probably it should be limited to methods covered by `SomethingImmutable` only.

**Comment by Ocramius** [comment]
@weirdan interesting view on it. Can you elaborate on a scenario where two interfaces are involved, and mutability would be an advantage? I'd expect any state touched by `SomethingImmutable` implementations (even if just the methods) to require immutability/read-only.

**Comment by weirdan** [comment]
I think Java's `StringBuilder` which implements read-only `CharacterSequence` interface could be a good example (in a single-threaded environment, as long as you don't hold references to it).

**Comment by Ocramius** [comment]
Thinking more about this, I think it is much safer to treat `@immutable` as a meta-interface that applies to everything, without restrictions. Applying `@immutable` to an interface should propagate `@immutable` at class level to all implementations.

As an example:

```php
/** @psalm-immutable */
interface Money
{
     public function gimme() : int;
}

final class MyMoney implements SomeInteger
{
    private int $amount = 0;
    public function gimme() : int
    {
        return $this->number;
    }
    public function increment() : void
    {
        $this->number += 1;
    }
}

/** @psalm-immutable */
class MyBankAccount
{
     private Money $money; // problem: my bank account is now mutable
}
```

**Comment by Ocramius** [comment]
🤘🤘🤘

**Comment by iluuu1994** [comment]
IMO this implementation is incorrect.

https://psalm.dev/r/ea9bd56925

```php
/** @psalm-immutable */
interface ImmutableCollection {
  /** @return mixed */
  public function get(string $key);
}

interface MutableCollection extends ImmutableCollection {
  /** @param mixed $value */
  public function set(string $key, $value): void;
}

class Collection implements MutableCollection {
  /** @return mixed */
  public function get(string $key) {
    return null;
  }  
  
  /** @param mixed $value */
  public function set(string $key, $value): void {}
}
```

> ERROR: MissingImmutableAnnotation - 14:7 - ImmutableCollection is marked immutable, but Collection is not marked immutable

As @weirdan mentioned, Psalm should make sure that all the methods contained in the interface don't mutate the objects state. The class as a whole doesn't necessarily need to be immutable.

**Comment by Ocramius** [comment]
Heya, have you seen the example above? Passing around something expected to be immutable (while it is not) is seriously problematic

**Comment by muglug** [comment]
Yeah, for example here: https://psalm.dev/r/5c66c3b907

```php
/** @psalm-pure */
function thinksItsPure(ImmutableCollection $c) : int {
  return $c->get("hello");
}

echo thinksItsPure(new Collection());
```

**Comment by muglug** [comment]
But on the other hand if it was just enforced at the method level I _think_ it'd be OK, too.

**Comment by muglug** [comment]
Definitely willing to reconsider

**Comment by muglug** [comment]
For now I've changed it so that immutability is only enforced on interface methods:

```php
/** @psalm-immutable */
interface Money {
     public function gimme() : int;
}

final class MyMoney implements Money {
    private int $amount = 0;
    public function gimme() : int
    {
        return $this->amount;
    }
    public function increment() : void
    {
        $this->amount += 1;
    }
}

/** @psalm-immutable */
class MyBankAccount {
	private Money $money; // problem: my bank account is now mutable
    public function __construct(Money $money) {
     	$this->money = $money;
       
       	if ($money instanceof MyMoney) {
       	  	$money->increment(); // this is an error
       	}
    }
}
```

https://psalm.dev/r/88b6284c0f

@Ocramius if you can poke holes in that, happy to go back to the more strict version

**Comment by iluuu1994** [comment]
> Passing around something expected to be immutable (while it is not) is seriously problematic

Why do you think so? I assume it's because something outside of `MyBankAccount` could mutate the `MyMoney` instance?

```php
$myMoney = new MyMoney();
$myBankAccount = new MyBankAccount($myMoney);
$myMoney->increment(); // $myBankAccount has implicitely changed
```

That's a valid point. This is a hard issue to solve with reference types. Swift for example only tracks mutability for structs which are value types. Although `@immutable` doesn't mean pure so Psalm shouldn't assume that `increment()` always returns the same value either way.

**Comment by Ocramius** [comment]
@muglug the idea of immutability on objects is to avoid any by-ref mutation of state: having mutators on anything that is expected to be immutable is pretty much defeating the use of this annotation on supertypes.

@iluuu1994 yes, spooky action at a distance is very common, and effectively to be avoided.

I think folks in the thread are confusing immutability with API purity: the API declared on an interface may well be pure, but immutability is something that affects all state of an instance.

In practice, `@immutable` should be enforced on all API and state even on an interface without any method.

**Comment by Ocramius** [comment]
Misconception probably comes from how this was documented: `@immutable` in psalm is "all method are `@pure`", but then I'd propose:

 * `@immutable` at class/interface means immutable and pure
 * `@pure` at class/interface means that the API of that class (and any subtype) is `@pure`

That would probably be less confusing.

**Comment by muglug** [comment]
> Further on, having this pseudo-immutability means that any less experienced developer can subclass an immutable type and add mutators (seen it happen many times), therefore breaking simple invariants of running systems. This is neither good nore helpful

Yeah, I agree, and I think the default should go back to what it was when I first resolved the issue (where anything implementing an immutable interface must also be immutable). If someone wants to turn an immutable interface mutable, they can suppress the issue themselves, or request the upstream interface not be immutable.

Sorry for the back and forth. Changed in 56d2507.
