### ISSUE TITLE
Class constants using other constants in ternaries are mixed

### ISSUE THREAD

**Issue by bugreportuser** [vimeo/psalm#2139]
Psalm is much better at inferring class constant types from other constants. The problem is that ternaries still give a mixed type.

Example (https://psalm.dev/r/abf2071ee8):
```php
<?php
const cons1 = true;

class Clazz {
    const cons2 = (cons1) ? 1 : 0;
}

echo Clazz::cons2;
```

Example output:
```
Psalm output (using commit 4a2822e):

INFO: MixedArgument - 8:6 - Argument 1 of echo cannot be mixed, expecting string
```

`Clazz::cons2` can be inferred as `int(1)` but `int(1)|int(0)` would be good too.

**Comment by muglug** [comment]
Did not know that ternaries were legal there, that's just silly

**Comment by bugreportuser** [comment]
It can be useful sometimes.

**Comment by muglug** [comment]
This is something you could definitely add yourself - if you look at the last PR, things should be *reasonably* obvious

**Comment by bugreportuser** [comment]
Thanks! I thought about that but have been too busy to try it.
