### ISSUE TITLE
Idea: Track real type set separately from the phpdoc type set?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#2144]
`Union->is_from_phpdoc` is not sufficient for all use cases, e.g. it causes false positives in redundant condition detection in #2143 

- trim() would have a phpdoc type of `string`, but a real return type of `?string` in php 7, because it will return null if the argument type was invalid.
- See https://github.com/phan/phan/blob/master/src/Phan/Language/Internal/FunctionSignatureMapReal_php73.php and https://github.com/phan/phan/blob/master/src/Phan/Language/Internal/FunctionSignatureMapReal.php for a source of real types for php's internal global functions in php 7/8.

Note that changing this will likely involve a lot of work and follow-up work (e.g. the way adding or removing or merging types is done would have to change in callers) 

An example of how this could be represented is https://github.com/phan/phan/blob/2.2.12/src/Phan/Language/UnionType.php#L101-L109

**Comment by muglug** [comment]
> Note that changing this will likely involve a lot of work

Yeah, not going to do this I think
