### ISSUE TITLE
Referenced variables modified in closures are not type-checked

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#2145]
I understand that closures is a temporal aspect of runtime not spatial, yet I'm not sure it should be totally silent about it.

https://psalm.dev/r/56ac6fff68

```php
<?php

function i(int $_): void {}
  
function assertInt(int $int): void {
  i($int);
  
  $s = static function() use(&$int): void {
    $int = '42';
  };
  $s();

  i($int);
}
```

**Comment by muglug** [comment]
You're right, it should type that `$int` as mixed afterwards

**Comment by zerkms** [comment]
that's unbelievable quick, thanks a lot!

**Comment by muglug** [comment]
Soundness is important!
