### ISSUE TITLE
Class constants using bitwise operations are mixed

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2149]
possibly related to #2139 and #1551 

bitwise const: https://psalm.dev/r/222baddf7b
```php
<?php
class Foo {
  const BAR = ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML5;
  
  public int $flags;
  
  public function __construct() {
    $this->flags = self::BAR;
  }
}
```
> Psalm output (using commit e9cd791): 
> 
> INFO: MixedAssignment - 8:5 - Cannot assign $this->flags to a mixed type

bitwise literal: https://psalm.dev/r/f6b76e4d2f
```php
<?php
class Foo {
  const BAR = 1 | 2;
  
  public int $flags;
  
  public function __construct() {
    $this->flags = self::BAR;
  }
}
```
> Psalm output (using commit e9cd791): 
>
> INFO: MixedAssignment - 8:5 - Cannot assign $this->flags to a mixed type

p.s. `1 | "nope"` = `1`, with a warning.

**Comment by SignpostMarv** [comment]
@muglug - I'm digging around in the code, and it appears that psalm [does track the binary or operation](https://github.com/vimeo/psalm/blob/55aceb2b6d52d1bee97ae8f71d9f0521102dcf5f/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php#L330), leaving `Psalm\Type\Atomic\TInt` as the sole member of a union, but the class const fetch comes back as mixed (with and without hoist consts)

**Comment by weirdan** [comment]
Can't reproduce anymore.
