### ISSUE TITLE
Uncaught InvalidArgumentException

### ISSUE THREAD

**Issue by RashmicaG** [vimeo/psalm#215]
Hi I'm new to running psalm. I'm getting this error when running psalm on my project:

`
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get class storage for Exception in /home/rashmica/workspace/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:21
Stack trace:
#0 /home/rashmica/workspace/vendor/vimeo/psalm/src/Psalm/Checker/MethodChecker.php(161): Psalm\Provider\ClassLikeStorageProvider->get('Exception')
#1 /home/rashmica/workspace/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php(1282): Psalm\Checker\MethodChecker::extractReflectionMethodInfo(Object(ReflectionMethod), Object(Psalm\Checker\ProjectChecker))
#2 /home/rashmica/workspace/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(483): Psalm\Checker\ClassLikeChecker::registerReflectedClass('InvalidArgument...', Object(ReflectionClass), Object(Psalm\Checker\ProjectChecker))
#3 /home/rashmica/workspace/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(363): Psalm\Checker\ProjectChecker->scanFiles()
#4 /home/rashmica/workspace/vendor/vimeo/ in /home/rashmica/workspace/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php on line 21
`

and when I run psalm with the debug option the file it was going through before this error was '/usr/share/php/Zend/Ldap/Filter/Not.php'.

Any ideas on what could be causing this error?

**Comment by muglug** [comment]
Thanks – try with dev-master now, and see if the fix I just pushed works for you. I remember encountering this same bug a week or so ago – not sure what exactly is causing it.

**Comment by RashmicaG** [comment]
That got rid of that error! Got another error, but looks like its from analysing my code rather than just scanning it.

`PHP Fatal error:  Uncaught UnexpectedValueException: $declaring_method_id should be a string in /home/rashmica/workspace/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php:155   `

**Comment by muglug** [comment]
I've just added slightly more descriptive exception messages that'll let you know what class method it's failing on.

**Comment by muglug** [comment]
It goes without saying that this is another bug, but depending on the callsite I may be able to narrow it down without seeing all of your code.
