### ISSUE TITLE
Feature request: Redundant @var annotation

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2150]
We have lots of `@var` annotations littered in our legacy codebase. It could be cool if Psalm could recognize redundant `@var` annotations:

```php
/** @var string $string */
$string = 'foo';
// ERROR: The type of `$string` is already inferred as `string`
```

**Comment by muglug** [comment]
yeah, considered this before, an easy addition - the only issue is that sometimes people keep these in for PHPStorm's autocompletion to work (because its inference isn't as good).

**Comment by muglug** [comment]
Should it be a command-line/config flag, or should it be a type of issue reported with `--find-unused-code`? It's not strictly unused, but it's _unnecessary_

**Comment by iluuu1994** [comment]
You're a legend man, thanks so much! 🤘

**Comment by iluuu1994** [comment]
Works great! Our codebase is free of unnecessary `@var` annotations now 🙂

**Comment by ADmad** [comment]
Would be nice if `psalter` could auto remove these unneeded `@var`.

**Comment by muglug** [comment]
Mind ticketing it?
