### ISSUE TITLE
PHPStorm generics issue

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2151]
https://psalm.dev/r/52d4af8c41

```php
/**
 * @psalm-template TKey of array-key
 * @psalm-template T
 * @template-extends IteratorAggregate<TKey, T>
 * @template-extends ArrayAccess<TKey|null, T>
 */
interface Collection extends Countable, IteratorAggregate, ArrayAccess {}

class Foo {
    /** @var Collection|string[] */
    private $bars;

    /**
     * @param Collection|string[] $bars
     */
    public function __construct($bars)
    {
        $this->bars = $bars;
    }
}
```

> ERROR: InvalidPropertyAssignmentValue - 20:23 - $this->bars with declared type 'Collection<array-key, string>' cannot be assigned type 'array<array-key, string>|Collection'

Apparently `Collection|string[]` doesn't have the same meaning when it's added to a parameter compared to when it is added to a property.

**Comment by iluuu1994** [comment]
Interestingly, adding a native `Collection` type hint fixes the issue:

https://psalm.dev/r/26d249d13d

```php
public function __construct(Collection $bars)
```

**Comment by muglug** [comment]
> Interestingly, adding a native Collection type hint fixes the issue

Yeah, that's by design - PHPStorm generics are only allowed when there's a native hint on param/return types. They're allowed on property types, because those couldn't be native _until recently_.

**Comment by iluuu1994** [comment]
I see, thanks!
