### ISSUE TITLE
UnusedMethod false positive

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2154]
![image](https://user-images.githubusercontent.com/1752683/65313439-a5835080-db94-11e9-9539-6101a23bf9d3.png)

> ERROR: UnusedMethod - lib/command/TestCommand.php:134:22 - Cannot find any calls to private method sv\command\TestCommand::runProcess

Unfortunately, this only happens on our CI server even though I run Psalm in the exact same way.

The code loosely translates to this:

```php
class Foo {
  public function bar(): void {
    $projectDir = __DIR__;
    $checks = [];

    if (file_exists($projectDir . '/vendor/friendsofphp/php-cs-fixer/php-cs-fixer')) {
      $checks['php-cs-fixer'] = ['php', '-d', 'memory_limit=-1', $projectDir . '/vendor/friendsofphp/php-cs-fixer/php-cs-fixer', 'fix', '--dry-run', '--ansi'];
    }

    if (file_exists($projectDir . '/vendor/phpstan/phpstan/bin/phpstan')) {
      $checks['phpstan'] = ['php', '-d', 'memory_limit=-1', $projectDir . '/vendor/phpstan/phpstan/bin/phpstan', 'analyze', '-c', 'phpstan.neon', '--ansi'];
    }

    if (file_exists($projectDir . '/vendor/vimeo/psalm/psalm')) {
      $checks['psalm'] = ['php', '-d', 'memory_limit=-1', $projectDir . '/vendor/vimeo/psalm/psalm', '--show-info=false'];
    }

    if (file_exists($projectDir . '/vendor/phpunit/phpunit/phpunit')) {
      $checks['phpunit'] = ['php', '-d', 'memory_limit=-1', $projectDir . '/vendor/phpunit/phpunit/phpunit', '--configuration', 'phpunit.xml.dist'];
    }

    foreach ($checks as $checkName => $checkArguments) {
      $this->baz($checkName, $checkArguments);
    }
  }

  private function baz(string $name, array $parts): void {
    echo $name . "\n";
    exec(join(" ", $parts));
  }
}

(new Foo())->bar();
```

https://psalm.dev/r/4a8a27c2c9

Can I provide more helpful information?

Both CI and local run with the newest master (f6b0de0).

**Comment by muglug** [comment]
Very weird. Does Psalm run with `--threads=X` and, if so, does the message remain when running in a single process?

**Comment by iluuu1994** [comment]
CI always runs on a single thread.

**Comment by muglug** [comment]
Can you isolate Psalm to just run on the file in question? I usually do this via the Psalm config.

**Comment by iluuu1994** [comment]
You mean by just doing this?

```xml
<projectFiles>
    <file name="lib/command/TestCommand.php" />
</projectFiles>
```

**Comment by iluuu1994** [comment]
It's super annoying to debug this in the CI environment. I'll try tonight by using the Docker image locally.

**Comment by muglug** [comment]
Ok, sorry!

**Comment by iluuu1994** [comment]
It's no problem, I've suppressed the issue and our build is green. I'll see if I can figure out what's going on here.

**Comment by iluuu1994** [comment]
Unfortunately it's not reproducible in the Docker container either. 🙃 It only fails on the actual CI that then runs the Docker container.

**Comment by muglug** [comment]
If you have control over the CI (and it won't block other people) you could narrow down to just that file as above. We've had issues at Vimeo in the past where things would break because dockerised environments running on Apple machines were case-insensitive, whereas dockerised envs running on Linux machines are very much case-sensitive.

**Comment by muglug** [comment]
I'm going to close in the meantime.
