### ISSUE TITLE
false array key is converted to integer

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2155]
https://psalm.dev/r/f2a590f6e4

```php
function foo(): array {
  $array = [];
  $array[false] = '';
  return $array;
}
```

> ERROR: InvalidReturnStatement - 6:10 - The type 'non-empty-array<false, string()>' does not match the declared return type 'array<array-key, mixed>' for foo

> ERROR: InvalidReturnType - 3:17 - The declared return type 'array<array-key, mixed>' for foo is incorrect, got 'non-empty-array<false, string>'

In reality, `false` is just converted to `int` so the returned type is actually just `array<int, string>`:

https://3v4l.org/Y0iQf

**Comment by iluuu1994** [comment]
By definition, an array can only contain `array-key`s as keys.

No matter what you feed it PHP will always either convert it to `int` or `string`:
https://3v4l.org/ijDIF

**Comment by muglug** [comment]
> By definition, an array can only contain array-keys as keys.

Yeah I know (and it was a painful thing to discover the silent casting behaviour)

**Comment by iluuu1994** [comment]
Thanks @muglug!
