### ISSUE TITLE
Psalm cannot infer an object-like array type, when nesting is more than two.

### ISSUE THREAD

**Issue by Akhristenko** [vimeo/psalm#2156]
When i check shape of object-like array via isset/is_array/is_int and nesting is less or equal to two all works correct
But when i try to do this for array with nesting more than two, psalm cannot infer correct type.
Example : [https://psalm.dev/r/6863b56299](https://psalm.dev/r/6863b56299)

**Comment by muglug** [comment]
I think the issue is somewhere in `Psalm\Type\Reconciler::adjustObjectLikeType`, which doesn't properly account for nested types.
