### ISSUE TITLE
InvalidArgumentException constructor considered impure

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#2160]
I don't see how constructing an InvalidArgumentException could violate the purity of the calling function.

https://psalm.dev/r/138ea33e28
```php
<?php
  /** @psalm-pure */
  function f(): void {
     throw new InvalidArgumentException('oops');
  }
```
**Expected**: no issues
**Actual**:
```
Psalm output (using commit fdbea45):

ERROR: ImpureMethodCall - 4:12 - Cannot call an impure constructor from a pure context
```

**Comment by muglug** [comment]
I don't know - @Ocramius do you have thoughts?

**Comment by Ocramius** [comment]
The ctor of an exception relies on `debug_backtrace()`, which is probably the most impure thing you can get.

**Comment by weirdan** [comment]
> The ctor of an exception relies on debug_backtrace(), which is probably the most impure thing you can get.

That is true, but the actual question was different: is purity of the function violated when it throws exceptions? It is if exceptions are considered to be just another kind of return values, and it likely isn't if you're only concerned about actual return values.

**Comment by muglug** [comment]
Yeah I don't think return type purity is violated, but certainly anything that catches the exception would be impure.

**Comment by muglug** [comment]
This is no longer impure

**Comment by Ocramius** [comment]
The thrown value is always different (in terms of equality): purity is most certainly being violated here.

This would be pure
```php
function f(AnException $e) {
    throw $e;
}
```

Calling the ctor is not viable from pure scope.

**Comment by muglug** [comment]
Yeah, but I don't count thrown values as function output.

**Comment by Ocramius** [comment]
Ah, that makes sense.
