### ISSUE TITLE
How to enable shepherd for repository?

### ISSUE THREAD

**Issue by kubawerlos** [vimeo/psalm#2161]
I see some repositories already benefit from type coverage report at https://shepherd.dev and I'm trying [here](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/pull/96) to enable for my repo, but cannot make the report to be shown at the website.

Is there something more I need do?

**Comment by muglug** [comment]
Yup, add `--shepherd` to your CI build. It's not enabled by default, and not even fully public, because there are still kinks to work out.

**Comment by kubawerlos** [comment]
@muglug that's what I did in https://github.com/kubawerlos/php-cs-fixer-custom-fixers/pull/96/files and Travis passed, but there is nothing at https://shepherd.dev/github/kubawerlos/php-cs-fixer-custom-fixers

**Comment by muglug** [comment]
It also has to be running on the master branch.

**Comment by kubawerlos** [comment]
That made the trick. Thanks!

**Comment by leocavalcante** [comment]
I added the flag: https://github.com/leocavalcante/siler/blob/master/composer.json#L84
Its runs on GitHub's Actions CI: https://github.com/leocavalcante/siler/blob/master/.github/workflows/ci.yml#L23
But I can't see my project in Shepherd: https://shepherd.dev/github/leocavalcante/siler

Am I missing something?

**Comment by muglug** [comment]
> Its runs on GitHub's Actions CI
> But I can't see my project in Shepherd
> Am I missing something?

No! It didn't work in Github Actions. Now (in latest master) it should.

**Comment by muglug** [comment]
@leocavalcante latest release should work!

**Comment by leocavalcante** [comment]
Awesome! Thank you.
