### ISSUE TITLE
Error message - conflicting with ZRay?

### ISSUE THREAD

**Issue by bogal** [vimeo/psalm#2162]
Using Psalm 3.5, when i run the command $ vendor\bin\psalter --issues=InvalidReturnType i get the following message:

> Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 4096 bytes) in C:\Program Files (x86)\Zend\ZendServer\data\plugins\composer\zray\zray.php on line 40

(I am running Zend Server on my local machine).

**Comment by muglug** [comment]
Never used ZRay, but I imagine you'd want to disable it when using Psalm (just as Xdebug is disabled).

**Comment by bogal** [comment]
It was disabled, although digging through the advanced options there is an option to monitor cli requests, which was set to enabled (and seemed to be interefering despite zray being disabled?). Anyway, i'm still getting a memory limit error but from a slightly different location:

> Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in C:\workspace\project-dir\vendor\vimeo\psalm\src\Psalm\Config.php on line 1069

I have tried setting my memory_limit to 1024M, and -1, still getting this message.

**Comment by weirdan** [comment]
> memory size of 2097152 bytes 

That's a bit too low for Psalm. Make sure you're editing the right php.ini file, check the output of `php --ini` cli command - it'll show you what ini files are loaded.

**Comment by muglug** [comment]
> memory size of 2097152 bytes

Yeah that's 2MB. Insanely low, and not Psalm-related.

**Comment by bogal** [comment]
> 
> 
> > memory size of 2097152 bytes
> 
> That's a bit too low for Psalm. Make sure you're editing the right php.ini file, check the output of `php --ini` cli command - it'll show you what ini files are loaded.

Thanks for the tip. It's all a bit strange really

- Via Zend Server, i've set the memory_limit to 1024M
- From the cli, php -r "echo ini_get('memory_limit');" outputs 1024M
- php --ini outputs 

> Configuration File (php.ini) Path: C:\WINDOWS
Loaded Configuration File:         C:\Program Files (x86)\Zend\ZendServer\etc\php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

- There is no php.ini in C:\Windows, but the ini file in the Zend Server directory also has 1024M as it's memory limit.

...yet i'm still getting the above message. Zend Server and Apache have been restarted many times, different command prompts opened as user and admin. At a loss!

**Comment by weirdan** [comment]
2MB is the minimum memory limit that can be set for PHP, and it often happens people get it set to that value when they spell the postfix wrong and PHP can't recognize it, e.g. `MB` instead of `M`, or using a similarly looking multibyte character like Cyrillic М. You can try using the actual byte value such as `1073741824` just to rule out this potential issue.

```console
$ php -dmemory_limit=1GB -r '$q = str_repeat("a", 1024*1024*2);' # wrong, should be 1G, or better yet 1073741824
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 2097184 bytes) in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. str_repeat() Command line code:1
```

**Comment by bogal** [comment]
> 
> 
> 2MB is the minimum memory limit that can be set for PHP, and it often happens people get it set to that value when they spell the postfix wrong and PHP can't recognize it, e.g. `MB` instead of `M`, or using a similarly looking multibyte character like Cyrillic М. You can try using the actual byte value such as `1073741824` just to rule out this potential issue.

Thanks again, yes i tried changing it to 1073741824 but same issues persists. I agree this is not a Psalm issue and will close this, but appreciate the advice regardless :)
