### ISSUE TITLE
checks against constant strings

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#2168]
code like
```php
<?php declare(strict_types = 1);

class HelloWorld
{
	public function sayHello(): void
	{
		if ('false' == stripos('abc', 'def')) {
			echo 'this will never happen';
		}
	}
}
```

should error because a constant string `false` can never be coerced to something which matches the `int|false` return value of `stripos`.

I am aware that this logic can not be used in case of comparing a variable containing a string at runtime, but it might be worth to do those checks when the string in question is known at "analysis-time"

**Comment by muglug** [comment]
This is one of those things where it's a lot of effort to handle correctly, and far simpler for people just to use `===`. Sorry!
