### ISSUE TITLE
Unexpected MissingImmutableAnnotation error

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#2170]
After the upgrade got this error:

![image](https://user-images.githubusercontent.com/2552865/65640782-d085fe00-dff3-11e9-8752-e0ce38b144ef.png)

```php
<?php

declare(strict_types=1);

namespace HappyJob\Infrastructure\HttpFlow\ExceptionHandler;

use Elao\Enum\SimpleChoiceEnum;
use Symfony\Component\HttpFoundation\Response;

/**
 * @method static self OK()
 * @method static self BAD_REQUEST()
 * @method static self NOT_FOUND()
 * @method static self INTERNAL_SERVER_ERROR()
 * @method int    getValue()
 */
final class StatusCode extends SimpleChoiceEnum
{
    public const OK = Response::HTTP_OK;
    public const BAD_REQUEST = Response::HTTP_BAD_REQUEST;
    public const NOT_FOUND = Response::HTTP_NOT_FOUND;
    public const INTERNAL_SERVER_ERROR = Response::HTTP_INTERNAL_SERVER_ERROR;
}
```

I was surprised, because this [`Enum`](https://github.com/Elao/PhpEnums/blob/master/src/Enum.php) is not marked as immutable. 

Is this an expected behavior?

**Comment by muglug** [comment]
Definitely not expected. Do you think I should cut a new release with the fix? I think it only affects people using `@method`, so should be of limited scope.

**Comment by vudaltsov** [comment]
Just this does not deserve a release. But I just turned on all the new features and it feels like I have a couple of other strange errors. Let me double check them.

**Comment by iluuu1994** [comment]
I actually had the same issue but couldn't reproduce it. It's fixed now 👍
