### ISSUE TITLE
PHP Fatal error:  Uncaught UnexpectedValueException in Version 3.5.2

### ISSUE THREAD

**Issue by mitelg** [vimeo/psalm#2175]
hey,
I updated to version 3.5.2 today and got this exception while executing psalm. 
```
PHP Fatal error:  Uncaught UnexpectedValueException: There should be types here in /vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeCombination.php:461
Stack trace:
#0 /vendor/vimeo/psalm/src/Psalm/Type.php(1438): Psalm\Internal\Type\TypeCombination::combineTypes(Array, NULL, false, true, 500)
#1 /vendor/vimeo/psalm/src/Psalm/Type/Atomic/ObjectLike.php(224): Psalm\Type::combineUnionTypes(Object(Psalm\Type\Union), Object(Psalm\Type\Union))
#2 /vendor/vimeo/psalm/src/Psalm/Type/Atomic/GenericTrait.php(184): Psalm\Type\Atomic\ObjectLike->getGenericValueType()
#3 /vendor/vimeo/psalm/src/Psalm/Type/Union.php(1388): Psalm\Type\Atomic\TArray->replaceTemplateTypesWithStandins(Array, Array, Object(Psalm\Codebase), Object(Psalm\Type\Atomic\ObjectLike), true, in /vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeCombination.php on line 461

```
Unfortunately I could not find out, on which file the operations fails. If you could give me a hint, I could investigate further

**Comment by weirdan** [comment]
Have you tried `--debug-by-line` cli switch? It'll output every line Psalm looks at, and it's usually something towards the end of that output that is the source of the problem.

**Comment by muglug** [comment]
Hi - try running with `--debug-by-line`, which should help you locate the code that triggers the exception

**Comment by muglug** [comment]
do you use any `@psalm-assert` calls?

**Comment by mitelg** [comment]
no, we don't use this annotation.

I already tried the debug-by-line option, but I guess I need to reduce the tested code 🙈 
way too much output 😁
will try it tomorrow. thanks so far

**Comment by muglug** [comment]
you can run `--debug` first to figure out what file causes the crash, then `--debug-by-line` to narrow down to the line (which will be the last line output before the crash).

**Comment by mitelg** [comment]
the thing is, psalm does not stop the execution when the error occurs. seems it throws the exception, skips the broken file and goes on with the rest.
is there a stop-on-error option or something like that?

**Comment by muglug** [comment]
@mitelg are you running with `--threads=X`? Make sure that's turned off.

**Comment by mitelg** [comment]
oh yes, running it with 4 threads.
will test without it 👍

**Comment by mitelg** [comment]
Should have written the execution line in my initial post :see_no_evil: 
Now we have a result: the exception is thrown on this line: https://github.com/shopware/platform/blob/master/src/Core/Content/Media/TypeDetector/ImageTypeDetector.php#L26

**Comment by ddebin** [comment]
Same issue here. `Fatal error: Uncaught UnexpectedValueException: There should be types here in /vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeCombination.php:461`

Line triggering error in my source code is: `$countrySpec = Config::COUNTRIES_SPECS[$this->getCountry()];`

**Comment by muglug** [comment]
Thanks both - I’ll have a patch release in a few hours

**Comment by muglug** [comment]
Please check with latest master - if it works I'll create a release

**Comment by muglug** [comment]
I've verified that Shopware passes

**Comment by muglug** [comment]
I've gone ahead and released: https://github.com/vimeo/psalm/releases/tag/3.5.3

**Comment by ddebin** [comment]
It's good for me! 👍🏻

**Comment by mitelg** [comment]
thanks a lot! 🤩 I will check the update on Monday

**Comment by mitelg** [comment]
works like a charm :blush: :+1: 
thanks again for the quick fix!
