### ISSUE TITLE
`PossiblyUndefinedVariable` in try/catch context

### ISSUE THREAD

**Issue by Wirone** [vimeo/psalm#2177]
Hi @muglug, we think we found issue with Psalm, which didn't found error in our code and caused production error. Thanks to Sentry we know the cause so I reproduced it here: https://psalm.dev/r/0144b46cf6 

Basically if `try/catch` is used, Psalm doesn't report `PossiblyUndefinedVariable` for variables used in `catch` that in some scenarios might be undefined (are declared after statement that could throw an exception in `try` block.

Would be great if Psalm could determine such wrong usage.

**Comment by muglug** [comment]
To do this properly Psalm will need to understand the difference between

```php
try {
  $a = someFunctionThatMaybeThrows();
} catch (Exception $e) {
  echo $a;
}
```

and

```php
try {
  $a = null;
  someFunctionThatMaybeThrows();
} catch (Exception $e) {
  echo $a;
}
```

Which should never throw a PossiblyUndefinedVariable issue.
