### ISSUE TITLE
DateTime::format() return type

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#218]
Currently DateTime::format() return type is considered to be ['string|false'](https://github.com/vimeo/psalm/blob/1012c23ff55470699903c795f091473d205ef723/src/Psalm/CallMap.php#L1125), based on PHP documentation saying this function may return `false`. However, inspecting php source code shows that `false` may only ever be returned when [parameter parsing has failed](https://github.com/php/php-src/blob/fd8ebdbadb0554260447568e1a1081f5c809e325/ext/date/php_date.c#L3165-L3167) (meaning parameter types are not what they expected to be).

Given that the whole point of running Psalm is to prevent errors, type errors in particular, doesn't it make sense to change the signature, as far as Psalm concerned, to return strings only?

This is further supported by the fact that `DateTime::setTimestamp()` (and, I bet, many other methods too) is documented as possibly-returning-false, but defined, for Psalm purposes, as returning `DateTime` [only](https://github.com/vimeo/psalm/blob/1012c23ff55470699903c795f091473d205ef723/src/Psalm/CallMap.php#L1159), despite having virtually the same implementation in php source ([returning false on argument type errors](https://github.com/php/php-src/blob/fd8ebdbadb0554260447568e1a1081f5c809e325/ext/date/php_date.c#L3702-L3704)).

**Comment by muglug** [comment]
Good point, well made. Fixed.
