### ISSUE TITLE
Class storage failure for old namespace style classes

### ISSUE THREAD

**Issue by dbalabka** [vimeo/psalm#2186]
```
Fatal error: Uncaught InvalidArgumentException: Could not get class storage for Braintree_Transaction in phar:///.../psalm.phar/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:42
Stack trace:
#0 phar:///.../psalm.phar/src/Psalm/Internal/Codebase/Properties.php(72): _HumbugBoxaf7094e20827\Psalm\Internal\Provider\ClassLikeStorageProvider->get('Braintree_Trans...')
#1 phar:///.../psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/PropertyFetchAnalyzer.php(309): _HumbugBoxaf7094e20827\Psalm\Internal\Codebase\Properties->propertyExists('Braintree_Trans...', false, Object(_HumbugBoxaf7094e20827\Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBoxaf7094e20827\Psalm\Context), NULL)
#2 phar:///.../psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(181): _HumbugBoxaf7094e20827\Psalm\Internal\Analyzer\Statements\Expression\ in phar:///.../psalm.phar/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php on line 42
```

Reproduction steps:
1. Install vendors using following  composer.json:
```
{
    "name": "dmitry.balabka/psalm-test",
    "authors": [
        {
            "name": "Dmitry Balabka",
            "email": "dmitry.balabka@ecentria.com"
        }
    ],
    "require": {
        "braintree/braintree_php": "^3.16.0"
    }
}
```
2. Create file `src/test.php`
```
<?php

$some = Braintree_Transaction::class;
```
3. Install Psalm PHAR with default configuration (`--init`)
4. Run:
```
php ./psalm.phar
```

**Comment by weirdan** [comment]
Reproduced (I suppose it's the same issue) with https://psalm.dev/r/fa51a8779a:
```php
<?php
  class A { }
  class_alias('A', 'A_A');
  
  echo A_A::class;
```
**Expected**: no exceptions
**Actual**:
```
Psalm runner output:

Internal Psalm error on line 47 - /var/www/vhosts/psalm.dev/httpdocs/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php: Could not get class storage for A_A
```

**Comment by weirdan** [comment]
The culprit appears to be here: https://github.com/vimeo/psalm/blob/0f7925e769a25cb8e800a92aa67fa964795752ef/src/Psalm/Internal/Codebase/Scanner.php#L716-L724

Psalm considers any resolvable class-like to be existing (which is not always true), and later refuses to override "existing" name with an alias.

**Comment by muglug** [comment]
Psalm has an (internal) method that can be called to get the unaliased class name, like so: https://github.com/vimeo/psalm/commit/f8a2eae0e2603d2816ddd0e2c1973eb7bbee9fb9#diff-bd57be1f44c66ece7b22b87f914c1c51R104

**Comment by weirdan** [comment]
@muglug this may have fixed the simpler case with class alias in the same file, but the original issue still persists. 

It's because that snippet above results in adding `braintree_transaction` into `Psalm\Internal\Codebase\ClassLikes::$existing_classlikes_lc`, so subsequent call to `ClassLikes::addClassAlias('braintree_transaction')` has no useful effect (`ClassLikes::getUnAliasedName()` checks `ClassLikes::$existing_classlikes_lc` first).
