### ISSUE TITLE
Cannot handle static when $static_class is empty

### ISSUE THREAD

**Issue by afbarbaro** [vimeo/psalm#2192]
I'm having an issue analyzing a class on this line (got this from the --debug-by-line analysis)

`$this->add($this->getRelatedModel()->newInstance($modelData));`

The issue seems to be related to the fact that inside the `newInstance` method there is a call to `static`:

```
    /**
     * Create a new instance of the given model.
     *
     * @param  array $attributes
     */
    public function newInstance($attributes = array())
    {
        // This method just provides a convenient way for us to generate fresh model
        // instances of this current model.
        $model = new static((array) $attributes);

        return $model;
    }
```

This code is in a library (not our own code), so how can I get pass this exception which prevents the code from being analyzed (psalm stops)?

Thank you!

**Comment by muglug** [comment]
Hey - what’s Psalm’s exception?

**Comment by afbarbaro** [comment]
> Hey - what’s Psalm’s exception?

Sorry, forgot to include that.  Here it is:
```
/Users/andres/git/app/app/tailwind/Core/Collection/EntityCollection.php:433

Fatal error: Uncaught UnexpectedValueException: Cannot handle static when $static_class is empty in phar:///Users/andres/git/app/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php:758
Stack trace:
#0 phar:///Users/andres/git/app/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(712): _HumbugBox74ec554d87c6\Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::fleshOutAtomicType(Object(_HumbugBox74ec554d87c6\Psalm\Codebase), Object(_HumbugBox74ec554d87c6\Psalm\Type\Atomic\TNamedObject), 'Illuminate\\Data...', NULL, NULL, true)
#1 phar:///Users/andres/git/app/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(598): _HumbugBox74ec554d87c6\Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::fleshOutType(Object(_HumbugBox74ec554d87c6\Psalm\Codebase), Object(_HumbugBox74ec554d87c6\Psalm\Type\Union), 'Illuminate\\Data...', NULL, NULL)
#2 phar:///Users/andres/git/app/vendor/psalm/phar/psalm. in phar:///Users/andres/git/app/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php on line 758
```

**Comment by muglug** [comment]
I'll need a _bit_ more info, sorry.

I'm trying to reproduce the issue online, and I'm coming up short: https://psalm.dev/r/b12383fbba

Would you be able to flesh out the return type of `getRelatedModel` there to see if the error emerges?

**Comment by afbarbaro** [comment]
> I'll need a _bit_ more info, sorry.
> 
> I'm trying to reproduce the issue online, and I'm coming up short: https://psalm.dev/r/b12383fbba
> 
> Would you be able to flesh out the return type of `getRelatedModel` there to see if the error emerges?

Thanks for working on this.  I implemented the `getRelatedModel` on your snippet referenced above, but the issue does not reproduce.  In our codebase, I was able to get past the problem by changing:

` $model = new static((array) $attributes);`

to 

`$class_name = get_called_class();`
`$model = new $class_name((array) $attributes);`

If you'd like to, we can close this issue as "can't reproduce", although the issue still exists.

**Comment by muglug** [comment]
I don't want to close as it's very likely a Psalm bug, and I especially hate bugs that crash Psalm.

Is the `new static` line contained in third-party code, or in your own code? I saw that pattern in [the Laravel codebase](https://github.com/illuminate/database/blob/fba945616f6f80cf91ea3bf73c55f43ffe3cc6ba/Eloquent/Model.php#L380-L403) and assumed you were just relying on that dependency.

How is `$this->add($this->getRelatedModel()->newInstance($modelData));` called?

Also it would help a lot if you could change your PHP ini `log_errors_max_len` to something higher like `log_errors_max_len = 2048`, which would mean I could see the full trace. That's probably going to be the quickest way for me to fix this.

**Comment by afbarbaro** [comment]
Hey @muglug - good news! I was able to reproduce the issue with this simple example:
https://psalm.dev/r/4382948908

Hopefully, it'd be easy to resolve.  Thanks for all your help!

**Comment by muglug** [comment]
Thanks for taking the time on this!
