### ISSUE TITLE
Bidirectional type inference for functions and methods

### ISSUE THREAD

**Issue by dbalabka** [vimeo/psalm#2193]
Not sure was this discussed or not. It would be great to make Psalm less to report `...cannot be mixed` or `...has no provided type`.

In the following example, Psalm will report multiple info messages about missing type:
https://psalm.dev/r/01e39c763b
```php
function foo($s) {
    return "foo" . $s;
}

$s = foo(1);
$s + 1;
```
```
INFO: MixedOperand - 4:20 - Right operand cannot be mixed
INFO: MissingParamType - 3:14 - Parameter $s has no provided type
INFO: MissingReturnType - 3:10 - Method foo does not have a return type, expecting string
INFO: MixedAssignment - 7:1 - Cannot assign $s to a mixed type
INFO: MixedOperand - 8:1 - Left operand cannot be mixed
```
If we will add required annotations for functions we will get proper error messages:
https://psalm.dev/r/3cdc864aed
```php
/** 
 * @psalm-param string $s 
 * @psalm-return string
 */
function foo($s) {
    return "foo" . $s;
}

$s = foo(1);
$s + 1;
```
```
ERROR: InvalidScalarArgument - 11:10 - Argument 1 of foo expects string, int(1) provided
ERROR: InvalidOperand - 12:1 - Cannot perform a numeric operation with a non-numeric type string
```

Psalm already do [types inference](https://medium.com/vimeo-engineering-blog/automated-type-inference-for-dynamically-typed-programs-6e79197e5420).Probably, it might be possible to infer types for functions signatures.

In some particular cases, the [type templates can be inferred](http://cruxlang.org/inference/) which are already supported by Psalm:
1. without types https://psalm.dev/r/cfef863ba4
2. with types https://psalm.dev/r/aa024b4141

[Dart's type system](https://dart.dev/guides/language/sound-dart) is a great example. I can guess that such type inference system might be very complex. For example, Python's mypy  [does not support types inference for dynamically typed functions](https://mypy.readthedocs.io/en/latest/common_issues.html#no-errors-reported-for-obviously-wrong-code) and there might be some a reason for this.

**Comment by muglug** [comment]
Hey!

Psalm doesn't do this for three reasons:

1. when writing code at scale — code that will be seen and edited by others — we generally want to be explicit about expected types (whether in docblocks or in function signatures)
2. the analysis is somewhat slower than the current analysis that Psalm does, and cannot so easily be parallelised
3. I'm probably not smart enough to do a good job of it, what with Psalm's existing complexity.

If you want a tool that does this, I recommend [Phan](https://tysonandre.github.io/phan-demo/?code=%3C%3Fphp%0Aclass+A+%7B%0A++++public+function+foo%28%24a%29+%7B%0A++++++++echo+%24a+.+%22who%22%3B%0A++++%7D%0A%7D%0A%0Aclass+B+%7B%0A++++public+function+bar%28%24b%29+%7B%0A++++++++%28new+A%29-%3Efoo%28%24b%29%3B%0A++++%7D%0A%7D%0A%0A%28new+B%29-%3Ebar%28new+stdClass%29%3B) which has always had it, I think? cc @TysonAndre on that.

If you have a solution that's not obviously slower (or which could be hidden behind an opt-in flag) I would welcome a PR. I'm happy to also provide pointers on how you might go about things. But I'm not going to add this myself.

**Comment by TysonAndre** [comment]
It's not quite bidirectional - The parameter types aren't inferred from the method body. Instead, types are inferred from usage, with a limit on how deeply Phan would recurse. (This was easier to implement)

- Phan recursively analyzes by default (where it makes sense to do so). That can be turned off with `--quick`, which makes it only analyze method bodies once, non-recursively. (similar to Psalm)
- Instead of inferring parameters from the method body, the parameter types are inferred from the argument types if parameter types aren't specified. Literals and array shapes get normalized to non-literals and generic arrays (e.g. `array{0:'string literal'}` becomes `array<int,string>`
- Additionally, if no return type is specified (either in the signature or as `@return`), the types from `return` statements within the method body get added to the return type of the method. (So the return type you get currently depends on the order in which uses get analyzed, which is a situation that could probably get improved on)

**Comment by dbalabka** [comment]
@muglug another much simpler example of type inference of return type that would be useful:
https://psalm.dev/r/2d72825662
All current static analyzer Psalm, Phan, Phpstan reports about a not existing method:
```
Psalm output (using commit 19faa31):

ERROR: UndefinedMethod - 37:34 - Method ParentClassTranslation::setextrafield does not exist
```
Surprisingly, PHPStorm can infer the type correctly and recognize the method properly.

**Comment by muglug** [comment]
You can achieve decent results with templates here: https://psalm.dev/r/e16fcbab0a

**Comment by dbalabka** [comment]
@muglug I agree that it is not a problem to cover code with types. Unfortunately, these cases are mostly related to third-party libraries. A much simpler workaround can be done with simple `assert(... instanceof ChildClassTranslation )`, but I just use `@psalm-suppress` to avoid additional variable creation.
