### ISSUE TITLE
Use native or phpDoc type, depending on which is more specific

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2196]
https://psalm.dev/r/fcf4b78b88

```php
interface FooInterface {}
class Foo implements FooInterface {
  public function notDefinedInInterface(): void {}
}

/**
 * @return FooInterface
 */
function getFoo(): Foo {
  return new Foo();
}

$foo = getFoo();
$foo->notDefinedInInterface();
```

> ERROR: MismatchingDocblockReturnType - 9:12 - Docblock has incorrect return type 'FooInterface', should be 'Foo'
> 
> INFO: MixedInferredReturnType - 9:12 - Could not verify return type 'FooInterface' for getFoo
>
> ERROR: UndefinedInterfaceMethod - 16:7 - Method FooInterface::notdefinedininterface does not exist

Error 1 is ok. Not sure what the info is about.

It would be nice though if Psalm would use native return type here as it more specific. It could also take an intersection of the two types, so `Foo&FooInterface` which could just be simplified to `Foo` in this case.

The reason I'm suggesting this is because this is often wrong in open source libraries.

Thanks!

**Comment by muglug** [comment]
This is hard to do (determining which is more precise before everything's been analysed).

If this is a problem, use stubs & also patch those 3rd-party libraries.

**Comment by iluuu1994** [comment]
Ok 👍
