### ISSUE TITLE
UndefinedThisPropertyAssignment false positives with Exceptions

### ISSUE THREAD

**Issue by Fleshgrinder** [vimeo/psalm#220]
## Minimal Example
```php
abstract class A extends \Exception {
    private $p;

    final public function __construct($p) {
        $this->p = $p;
    }
}

final class B extends A {}
```

## Actual
> Instance property B::$p is not defined

## Expected
All should be fine. It seems as if this affects exceptions only.

**Comment by weirdan** [comment]
>  It seems as if this affects exceptions only.

Not only, the following code seems to be affected as well:
```php
<?php
namespace Q;

abstract class Base
{
    /**
     * @var string
     */
    private $aString;

    public function __construct()
    {
        $this->aString = 'aa';
    }
}

class Descendant extends Base
{
    /**
     * @var bool
     */
    private $aBool;

    public function __construct()
    {
        parent::__construct();
        $this->aBool = true;
    }
}
```
A couple of observations:
* if I remove `$aBool` from `Descendant` (both assignment and the var itself) the error goes away.
* if I turn `private $aString` into `protected $aString` the error goes away.

**Comment by muglug** [comment]
Very likely coming from the `PropertyNotSetInConstructor` checks, which check parent constructor calls with the context of the child.

If you suppress that issue (and not `UndefinedThisPropertyAssignment`) you’ll likely see the problem go away. I’ll have a fix, but maybe not for a week (currently on holiday with limited computer access, sorry).

**Comment by weirdan** [comment]
Confirmed, adding:
```xml
	<issueHandlers>
		<PropertyNotSetInConstructor errorLevel="suppress" />
	</issueHandlers>
```
to `psalm.xml` does indeed make the problem go away, for both my my case and @Fleshgrinder's

**Comment by muglug** [comment]
Intermediate fix done on my smartphone while on a train. If this doesn’t solve your (likely more complicated) use case, feel free to reopen and I’ll address in a more robust fashion a week or so hence.
