### ISSUE TITLE
Mysqli real_connect signature issues

### ISSUE THREAD

**Issue by jaydiablo** [vimeo/psalm#2202]
If `null` is passed to the first or third parameter of the `mysqli` `real_connect` method (https://www.php.net/manual/en/mysqli.real-connect.php), Psalm complains that `null` cannot be passed:

>Argument 1 of mysqli::real_connect cannot be null, possibly null value provided
>Argument 3 of mysqli::real_connect cannot be null, possibly null value provided

According to the docs, both parameters can accept `null`:

> host
>    Can be either a host name or an IP address. Passing the NULL value or the string "localhost" to this parameter, the local host is assumed. When possible, pipes will be used instead of the TCP/IP protocol.

> passwd
>    If provided or NULL, the MySQL server will attempt to authenticate the user against those user records which have no password only. This allows one username to be used with different permissions (depending on if a password as provided or not).

(I believe for the `passwd` argument the docs mean "If **not** provided or NULL" but that's not important here)

**Comment by muglug** [comment]
Create a PR against `CallMap.php` then - I have no strong feelings about it...
