### ISSUE TITLE
Can't @psalm-suppress UnusedVariable errors

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2205]
https://psalm.dev/r/7ad29536fe

```php
function foo(): void {
  /** @psalm-suppress UnusedVariable */
  $bar = null;
}
```

> INFO: UnusedVariable - 5:3 - Variable $bar is never referenced

Excuse me if this is a known issue.

**Comment by muglug** [comment]
You have to [suppress them on the function itself](https://psalm.dev/r/b2942b600c), sorry - there's no easy way to change that behaviour to be more accommodating
