### ISSUE TITLE
Unused variable in list

### ISSUE THREAD

**Issue by mitelg** [vimeo/psalm#2207]
Hey,

I'm trying to fix unused variables and parameters. I came to code, which looks similar to this: https://psalm.dev/r/0e056957cd

How could I fix it? If I would remove `$foo` as first list parameter, the output would be wrong.

**Comment by muglug** [comment]
Like this: https://psalm.dev/r/a48dcd242e

**Comment by mitelg** [comment]
thanks! :blush:
