### ISSUE TITLE
Template inheritance not allowing valid cases

### ISSUE THREAD

**Issue by afbarbaro** [vimeo/psalm#2208]
I've run into this on our codebase and created a small example that reproduces the issues.  I basically have a Collection class with a single generic variable `T` and the collection accepts only generic bindings of a given interface.   Psalm is yielding two errors that I think are invalid.

Here's the example
https://psalm.dev/r/44fc9e203a

Here's the errors
>Psalm output (using commit d85fbae): 
>
>ERROR: InvalidPropertyAssignmentValue - 63:31 - $this->related_model with declared type 'T as ModelInterface' cannot be assigned type 'TestEntity'
>
>ERROR: InvalidPropertyAssignmentValue - 34:13 - $this->items with declared type 'array<string, T as ModelInterface>' cannot be assigned type 'non-empty-array<string, T as ModelInterface|TestEntity>'

In this example, `TestEntity` does implement `ModelInterface`, so the errors (in my opinion) are invalid.

By the way, Psalm is awesome.  My background is in Java and having generics at least for Collection classes is a must-have.  So thanks for creating this life-saving awesome tool for PHP.

**Comment by muglug** [comment]
The first reported error — setting a property of an extended templated type — is reproduced more succinctly here: https://psalm.dev/r/293078567e.

The second error is likely caused by the same bug as the first, reproduced more succinctly here: https://psalm.dev/r/a7085421f6

**Comment by afbarbaro** [comment]
> The first reported error — setting a property of an extended templated type — is reproduced more succinctly here: https://psalm.dev/r/293078567e.
> 
> The second error is likely caused by the same bug as the first, reproduced more succinctly here: https://psalm.dev/r/a7085421f6

Wow! Thank you!
