### ISSUE TITLE
Allow to specify method calls as early termination/exit functions

### ISSUE THREAD

**Issue by b1rdex** [vimeo/psalm#2213]
This is a followup for #806.

https://github.com/vimeo/psalm/issues/806#issuecomment-404715027:
> @muglug: For performance reasons this was limited to functions and static methods - identifying dynamic ones is too costly, unfortunately.

This restriction should be removed and there should be a possibility to specify method calls as early termination functions. This is common practice for PHP frameworks and is widely used.

Also, this is implemented in phpstan. I guess it's not a huge performance deal overall. Please see https://github.com/phpstan/phpstan/blob/6a595c388e75d211b9ae0257e87bb52eb76c0334/src/Analyser/NodeScopeResolver.php#L1164 for implementation details.

Also, if you need to speed things up, it's possible to check if the method name is in the configured list of early termination methods first, to remove unnecessary variable class derivation check.

**Comment by weirdan** [comment]
There is a way to mark a method as never returning one: `/** @return no-return */`
https://psalm.dev/r/336aefdad7

**Comment by weirdan** [comment]
>  Also, this isn't a correct PhpDoc type hint and I suppose it'll produce warnings in all IDEs…

You can also spell it as `/** @psalm-return no-return */` for compatibility with other tools.

> Also, framework users have no way to add @return no-return to framework source code if the maintainer wouldn't accept it

They can, by adding a [stub](https://github.com/vimeo/psalm/blob/master/docs/running_psalm/configuration.md#stubs) with this additional phpdoc tag.

**Comment by muglug** [comment]
Yeah, I'm going to be deprecating the exit functions config in favour of `@psalm-return no-return` types at some point.

**Comment by muglug** [comment]
Having `@psalm-return no-return` return types is a more comprehensive solution, and if this feature ever makes it into PHP itself, it'll likely be in the form of a return type (as it exists in Hack).
