### ISSUE TITLE
TypeDoesNotContainType false positive

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2214]
https://psalm.dev/r/d97586a0ef

```php
function foo(array $options): void {
  if (!isset($options['tmp_name'])) {
    throw new \Exception();
  }

  if (!isset($options['error'])) {
    $options['error'] = UPLOAD_ERR_OK;
  }

  switch ($options['error']) {
    case UPLOAD_ERR_INI_SIZE:
      break;
  }
}
```

> ERROR: TypeDoesNotContainType - 13:10 - int(1) cannot be identical to int(0)

This error goes away when the `if (!isset($options['tmp_name'])) {` statement is removed.

**Comment by muglug** [comment]
Is this in the latest release, or just latest master?

**Comment by iluuu1994** [comment]
Only tested on `master`.

**Comment by muglug** [comment]
It's useful for the release notes once I fix it - master contains a bunch of changes relating to array offset checks, I want to make sure this is a bugfix.

**Comment by iluuu1994** [comment]
Thanks @muglug!
