### ISSUE TITLE
Generic with an intermediate function gives an error

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#2224]
this does not work: https://psalm.dev/r/5a273cac14
while without `value()` it does: https://psalm.dev/r/783811c522

**Comment by muglug** [comment]
Yeah this also works: https://psalm.dev/r/1448f0da75

**Comment by vudaltsov** [comment]
Excuse me, cannot understand what's wrong with https://psalm.dev/r/1448f0da75?

**Comment by muglug** [comment]
Sorry, I meant to paste https://psalm.dev/r/76bf7c53c0
