### ISSUE TITLE
Proposal: associative-array<KeyT, ValueT>, as a counterpart of list<T>

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#2230]
This would be useful for analyzing the code that uses params/returns/properties of type `list<T>`, for detecting bugs.

- there should be a way to represent (in the type system) that it's probably a mistake to pass an array to a function expecting `list<bool>` or to invoke `foo(...$x)`. Similarly, it's probably an array to pass `list<T>` where an `associative-array` is provided.

`associative-array` could be inferred in examples such as the following, when the exact array fields are unknown:

- phpdoc such as `@param associative-array`, `associative-array<value>`, and `associative-array<key, value>`
- Expressions such as `[$uid1 => $value, $uid2 => $value2]` with unknown keys
- Unsetting an array key of a variable.
- Adding an unknown array key to an empty array.
- Return values of certain built-in functions, such as `array_filter` or `array_unique`,
  which don't preserve all keys and don't renumber array keys.

Also see https://github.com/phan/phan/issues/3357

**Comment by vudaltsov** [comment]
Could be called `map` instead of `associative-array`.

**Comment by muglug** [comment]
`map` isn't a reserved word in PHP though. Adding the `-` means it cannot be confused for a real class

**Comment by TysonAndre** [comment]
Yeah, I'd like a short name, but I didn't like any other ideas I had

- `-map` or `a-map` (i.e. a special prefix) or would be easy to type but unintuitive and hard to remember
- `__map` would be for **internal use for php itself,** not for docblocks, making it a bad idea
- `array-map` sounds too much like `array_map()`
- `hash-map` is possible to confuse with SplObjectHash.

Some special symbol in the template parameters might work for this, but they also seem hard to remember and lack meaning. It also doesn't reflect the type system as well.

- `array<$, [KeyT,] ValueT>`

**Comment by TysonAndre** [comment]
`@param [=>]` and `@param [string=>stdClass]` or `@param [=>stdClass]` was another idea.

Annoyingly, it would interfere with heuristics used to parse template params (match up < and >)

`@param [:]` and `@param [string:stdClass]` might work as alternatives to `associative-array` and `associative-array<string,stdClass>`

That has the drawback of making `array{stdClass,T2,T3}` harder to change to `[stdClass,T2,T3]` in the future.

**Comment by TysonAndre** [comment]
Or `@param array{[string]:stdClass}`, `array{[mixed]:}`, etc. (This would not work if `[]` are allowed in array shape keys unescaped)

Typescript has something similar with `{[key:string]:ValueT}`

**Comment by AndrolGenhald** [comment]
I think this is mostly completed now, but it's hard for me to tell without code examples. If part of this still isn't working I'm guessing it will be solved if we add an index-signature-like feature in #5299.
