### ISSUE TITLE
Class properties are not inferred when the constructor has a behavior

### ISSUE THREAD

**Issue by smelesh** [vimeo/psalm#2231]
When class property is calculated in the constructor, Psalm doesn't infer **all** properties.

https://psalm.dev/r/97bfeff75c
https://psalm.dev/r/5620c9f064

1. Does it make sense [to not reset already inferred types](https://github.com/vimeo/psalm/blob/03c39cbe7c7096ec89cfef7a9790b54e46a28bf2/src/Psalm/Internal/Visitor/ReflectorVisitor.php#L2523) when the constructor contains any operation except the assignment?
2. Is it possible to infer types from simple expressions (assign scalars, `new` object)? Or it's complicated and better to wait for PHP 7.4?

**Comment by muglug** [comment]
The optimisation only works for dirt-simple objects where all property types can be inferred without doing any deep analysis — when all types are passed via the constructor.

In all other cases you’ll want to provide types, sorry.
