### ISSUE TITLE
countable type should include SimpleXmlelment and ResourceBase

### ISSUE THREAD

**Issue by BackEndTea** [vimeo/psalm#2232]
See also: https://github.com/symfony/polyfill-php73/blob/2ceb49eaccb9352bff54d22570276bb75ba4a188/bootstrap.php#L16

Those 2 classes don't imlement countable, but can be counted.

**Comment by muglug** [comment]
They will, in PHP 7.4. Unless this is breaking some code, it's a wontfix.

**Comment by BackEndTea** [comment]
Cheers, didn't know that
