### ISSUE TITLE
Typing mixed variable used as a `while` condition

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#2233]
In the following pretty standard pattern to fetch all the rows from the result set https://psalm.dev/r/cbfd72ecbd:

```php
<?php
  
$db = new \PDO('');

$stmt = $db->prepare('');

/** @var mixed $row */
while ($row = $stmt->fetch()) {}
```

it looks like there is no way to type `$row` variable (without rewriting it to an infinite loop with `break`).

**Comment by muglug** [comment]
The solution is to inline the `@var` next to the assignment: https://psalm.dev/r/3c3771ae92. It's not particularly pretty, but it parallels how the statements are actually interpreted

**Comment by zerkms** [comment]
Oh, indeed. Thanks!
