### ISSUE TITLE
List and array_merge

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#2235]
https://psalm.dev/r/01e095bf24

**Comment by vudaltsov** [comment]
So, basically we should teach Psalm that array_merging two lists gives a new list.

**Comment by TysonAndre** [comment]
It's more general than that - array_merge()ing one or more lists with only integer keys gives a new list

```
php > var_export(array_merge([0 => 2, 2 => 3]));
array (
  0 => 2,
  1 => 3,
)
php > var_export(array_merge([0 => 2, 2 => 3], [-4 => 'x']));
array (
  0 => 2,
  1 => 3,
  2 => 'x',
)
```
