### ISSUE TITLE
InvalidArrayOffset expects integer key on associative sub-array

### ISSUE THREAD

**Issue by Rarst** [vimeo/psalm#2243]
I have an associative array property that stores either strings or nested associative arrays of strings.

I am trying to type it as following and Psalm keeps insisting that second level key should be an `int`:

```php
class Config
{
    /** @var array<string, string|array<string,string>> */
    private $config = [
        'title'      => '',
        'baseURL'    => '',
        'params'     => [
            'description' => '',
        ],
    ];

    public function handle(): void
    {
      $this->config['params']['description'] = 'foo';
    }
}
```

> Psalm output (using commit 216f991):
> ERROR: InvalidArrayOffset - 16:7 - Cannot access value on variable $this->config['params']['description'] using offset value of 'description', expecting int

https://psalm.dev/r/77926238e5

Am I setting up the type in a wrong way or something?..

PS truncated example, describing all of the keys individually in type would be unwieldy.

**Comment by weirdan** [comment]
That's because you could have tried to set `$this->config['title']['description']`, and you can only use int offsets with strings.

**Comment by Rarst** [comment]
Yeah, I can see that, but also... I am not doing _that_. :)

So what's "correct" here? Describing the whole config array key by key after all?

**Comment by weirdan** [comment]
You can fix it with `assert`: https://psalm.dev/r/8b8f0da3af
This way you're telling Psalm that even though the array element could theoretically be string or array, you're dealing with the array case here (and not string).

**Comment by Rarst** [comment]
Hm hm, that feels like adding dead code to me (in this case, since nothing else can mess with it).

I've tried just documenting key in question and it seems to be passable for now `/** @var array{params: array<string,string>} */`

Thank you for your time! :)
