### ISSUE TITLE
Trying psalm for the first time, got multiple errors

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#2247]
I used these commands:

```
composer require --dev vimeo/psalm
vendor/bin/psalm --init src 1
vendor/bin/psalm
```

Output of the last command:

```
Scanning files...
Analyzing files...

PHP Notice:  Undefined offset: 1 in /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php on line 1001

Notice: Undefined offset: 1 in /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php on line 1001
PHP Notice:  Undefined offset: 1 in /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php on line 1001

Notice: Undefined offset: 1 in /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php on line 1001
PHP Notice:  Undefined offset: 1 in /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php on line 242
PHP Fatal error:  Uncaught Error: __clone method called on non-object in /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php:257
Stack trace:
#0 /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php(133): Psalm\Internal\Analyzer\FunctionLike\ReturnTypeCollector::getReturnTypes(Array, Array, false, false, true)
#1 /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1752): Psalm\Internal\Analyzer\FunctionLike\ReturnTypeAnalyzer::verifyReturnType(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Internal\Analyzer\MethodAnalyzer), Object(Psalm\Type\Union), 'App\\Library\\Ds\\...', Object(Psalm\CodeLocation), Array)
#2 /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1644): Psalm\Internal\Analyzer\ClassAnalyzer::analyzeClassMethodReturnType(Object(PhpP in /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php on line 257

Notice: Undefined offset: 1 in /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php on line 242

Fatal error: Uncaught Error: __clone method called on non-object in /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php:257
Stack trace:
#0 /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php(133): Psalm\Internal\Analyzer\FunctionLike\ReturnTypeCollector::getReturnTypes(Array, Array, false, false, true)
#1 /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1752): Psalm\Internal\Analyzer\FunctionLike\ReturnTypeAnalyzer::verifyReturnType(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Internal\Analyzer\MethodAnalyzer), Object(Psalm\Type\Union), 'App\\Library\\Ds\\...', Object(Psalm\CodeLocation), Array)
#2 /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1644): Psalm\Internal\Analyzer\ClassAnalyzer::analyzeClassMethodReturnType(Object(PhpP in /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php on line 257
```

This seems to be an internal error of Psalm. Can you fix this just from this report?

Also it's worth mentioning that each error seems to be printed twice to the output. You might want to review your error handling logic and only print them once.

**Comment by muglug** [comment]
Would you mind running with `--debug-by-line` to track down the code that Psalm failed on?

**Comment by enumag** [comment]
It seems to have failed on a `yield from`:

```
	public function getIterator(): Iterator
	{
		yield from $this->vector;
	}
```

**Comment by muglug** [comment]
Oh awesome, thanks - what’s the type of `$this->vector`?

**Comment by enumag** [comment]
`$this->vector` is `\Ds\Vector` from [ext-ds](https://github.com/php-ds/ext-ds).

**Comment by enumag** [comment]
I'm not sure if it's related but `Vector` is one of the bit strange classes that implement `Traversable` without implementing neither `Iterator` nor `IteratorAggregate` which is not possible by user-land code but is possible my internal classes.

```php
<?php

$vector = new \Ds\Vector();

var_dump($vector instanceof Traversable);
var_dump($vector instanceof Iterator);
var_dump($vector instanceof IteratorAggregate);
```

```
bool(true)
bool(false)
bool(false)
```

**Comment by muglug** [comment]
I can reproduce this issue by installing `ext-ds` and running Psalm on

```
class A {
    /**
     * @var Ds\Vector<string>
     */
    public Ds\Vector $vector;

    /**
     * @param Ds\Vector<string> $v
     */
    public function __construct(Ds\Vector $v) {
        $this->vector = $v;
    }

    public function getIterator(): Iterator
    {
        yield from $this->vector;
    }
}
```

**Comment by muglug** [comment]
That fixes the crash, I've ticketed https://github.com/vimeo/psalm/issues/2248 so that you can write `Ds\Vector<string>` without Psalm complaining about `TooManyTemplateParams`

**Comment by enumag** [comment]
Thanks for solving both this and Ds support so quickly @muglug! I'll try the 3.6.2 release.

**Comment by enumag** [comment]
Ok unfortunately the fix is incomplete. There is no fatal error anymore but I'm still getting a lot of these notices:

```
PHP Notice:  Undefined offset: 1 in /home/tousek/Projects/Parkers/ifm24-api/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php on line 1001
```

**Comment by enumag** [comment]
It seems it happens when I use

```
/**
 * @return Iterator<Something>
 */
function test(): Iterator {}
```

I do that when the keys are not important and I only care about the value type.

**Comment by muglug** [comment]
Thanks - I've fixed the notice in 233977a. But Psalm wants you to supply all the params of iterator — both a key and a value type — and that won't change.

**Comment by enumag** [comment]
Thanks for fixing the notice though I'd like to ask you to consider to reconsider or add some different syntax for no-key iterators.

With `@return Iterator<X, Y>` I'm saying the type of both keys and values where as with `@return Iterator<X>` I not only say just the type of the values but more importantly also **convey the fact that keys have no meaning** for this iterator and whoever traverses the iterator should avoid using he keys. Knowing this fact is very important thing for anyone using such method so I really really want to have it documented in the return type and feel heavily inclined to avoid using tools that force me otherwise.

As an author of Psalm I'm sure you do realize the importance of this since psalm supports `array<X, Y>` and `list<X>` syntax for exactly this purpose.

It's the same thing for iterators except infinitely more important because I avoid using arrays in my code as much as possible, replacing them with Iterators, Generators and ext-ds data structures as much as possible.

On a side note since this is kinda related, how many type arguments can I specify for `\Generator<...>` in Psalm? Because I might want to specify anywhere between 1 up to 6 type arguments but there is no way I would specify all of them for every Generator annotation.

**Comment by muglug** [comment]
> With `@return Iterator<X, Y>` I'm saying the type of both keys and values where as with `@return Iterator<X>` I not only say just the type of the values but more importantly also convey the fact that keys have no meaning for this iterator and whoever traverses the iterator should avoid using he keys.

A type cannot convey that iterator keys have no meaning (that should be specified somewhere in the documentation). The nearest a type can come is with the `mixed` type - and you can specify that with `Iterator<mixed, X>`.

Psalm supports a few shortcuts - writing `iterable<X>` is interpreted as `iterable<mixed, X>`, and `Generator<X>` is interpreted as `Generator<mixed, X, mixed, mixed>`. but that’s pretty much where Psalm stops.

If Psalm were to support `Iterator<X>`, it would only be as a shortcut for `Iterator<mixed, X>`. But I think it’s important for people to get used to writing out the full annotation - it’s what Psalm uses under the hood, and it doesn’t make much sense (to me) for users to omit key types of templated objects.

**Comment by enumag** [comment]
Wait, if `Generator<X>`, why `Iterator<X>` isn't? That makes no sense at all and is not intuitive. Usually the fact that it is a Generator is useless for the consumer so my usual return type for yielding function is `Iterator`.

**Comment by muglug** [comment]
I suppose if you feel very strongly, you just need to update this line - I'd accept a PR: https://github.com/vimeo/psalm/blob/dc0dd08a6778386af38fb6b5f353f1782ef3051e/src/Psalm/Type.php#L254-L257

**Comment by enumag** [comment]
See #2285.
