### ISSUE TITLE
`@var self` weirdness

### ISSUE THREAD

**Issue by erunion** [vimeo/psalm#225]
```
/**
 * With an array of data that was output from an Annotation, via `toArray()`, hydrate a new Annotation object.
 *
 * @param array $data
 * @param Version|null $version
 * @return self
 */
public static function hydrate(array $data = [], Version $version = null): self
{
    /** @var self $annotation */
    $annotation = parent::hydrate($data, $version);
    $annotation->setDescription($data['description']);
    $annotation->setField($data['field']);
    $annotation->setType($data['type']);
    $annotation->setUri($data['uri']);
    $annotation->setValues($data['values']);

    return $annotation;
}
```

With this code, Psalm fails with the following:

> ERROR: UndefinedClass - src/Parser/Annotations/UriSegmentAnnotation.php:127:9 - Class or interface self does not exist
>         $annotation->setDescription($data['description']);
> 
> 
> ERROR: UndefinedClass - src/Parser/Annotations/UriSegmentAnnotation.php:128:9 - Class or interface self does not exist
>         $annotation->setField($data['field']);
> 
> 
> ERROR: UndefinedClass - src/Parser/Annotations/UriSegmentAnnotation.php:129:9 - Class or interface self does not exist
>         $annotation->setType($data['type']);
> 
> 
> ERROR: UndefinedClass - src/Parser/Annotations/UriSegmentAnnotation.php:130:9 - Class or interface self does not exist
>         $annotation->setUri($data['uri']);
> 
> 
> ERROR: UndefinedClass - src/Parser/Annotations/UriSegmentAnnotation.php:131:9 - Class or interface self does not exist
>         $annotation->setValues($data['values']);

Changing `@var self` to `@var UriSegmentAnnotation` works, but it'd be nice to support `self`.

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/6b4bd47ddb7cf53d8ec0cb453b590135611cac27

**Comment by muglug** [comment]
Thanks for raising this!
