### ISSUE TITLE
Callable array not interpreted correctly when using 'parent'

### ISSUE THREAD

**Issue by bkdotcom** [vimeo/psalm#2256]
Along the same lines of #2055 

```
 Argument 1 of call_user_func_array expects callable, array{0: string(parent), 1: string(bindColumn)} provided
        return \call_user_func_array(array('parent', 'bindColumn'), $args)
```

**Comment by muglug** [comment]
Can't you use `parent::class`?

**Comment by bkdotcom** [comment]
It's a project that still supports php 5.4. :| (`::class` is 5.5+)
    


-------- Original message --------

**Comment by muglug** [comment]
Then I'd just suppress this issue.

Even though I'm sympathetic to projects that support 5.4 (Vimeo only moved off 5.4 two years ago), 5.4 EOL was over four years ago.
