### ISSUE TITLE
CallMap type issues

### ISSUE THREAD

**Issue by bkdotcom** [vimeo/psalm#2257]
**unregister_tick_function -> accept callable**

currently:
`'unregister_tick_function' => ['void', 'function_name'=>'string'],`

I believe it should be 
`'unregister_tick_function' => ['void', 'function_name'=>'string|callable'],`

https://www.php.net/manual/en/function.unregister-tick-function.php

-----
I believe the following return types should be `'class-string[]'` :

`'ReflectionClass::getInterfaceNames' => ['string[]'],`
`'ReflectionObject::getInterfaceNames' => ['string[]'],`

```PHP
$interfaces = $reflector->getInterfaceNames();
foreach ($interfaces as $className) {
    // Argument 1 of ReflectionClass::__construct expects class-string|object, parent type string provided
    $reflectionClass = new ReflectionClass($className);
}
```

**Comment by muglug** [comment]
`callable` includes `string`, so that can be simplified - but otherwise these changes look great! Would you mind creating a PR?
