### ISSUE TITLE
Call to undefined function json_decode()

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#2260]
Call to undefined function json_decode()
File: vendor/vimeo/psalm/src/command_functions.php on line 127

I already googled, but the issue I am having is different, bc I have json installed.

Also json_decode is working for all php-fpm (web) as well as CLI things, EXCEPT psalm.

```
php -m | grep json
json

php -i | grep json
/etc/php.d/20-json.ini,
json
json support => enabled
json version => 1.7.0
proto_binary_fetched_json => 0
```

I am using psalm 3.6.1

```
php -v
PHP 7.3.8 (cli) (built: Jul 30 2019 09:26:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.8, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
```

Any suggestions on how I could further debug this? Is there perhaps some special way psalm calls php which could cause this problem?

**Comment by weirdan** [comment]
Does it work if you run it as `PSALM_ALLOW_XDEBUG=1 psalm` ?

**Comment by kkmuffme** [comment]
Thanks, that solved the problem EXCEPT for psalter, I still get this exact error even with the flag:

`PSALM_ALLOW_XDEBUG=1 ./vendor/bin/psalter`

Could it be that it isn't implemented for psalter?

(using --alter flag is not an option, since it doesn't support --issues and --php-version)

**Comment by andrew-demb** [comment]
For psalter you can use `PSALTER_ALLOW_XDEBUG=1 psalter`

**Comment by kkmuffme** [comment]
Thanks!

**Comment by weirdan** [comment]
@kkmuffme Psalm uses [composer/xdebug-handler](https://github.com/composer/xdebug-handler) package to disable Xdebug for performance reasons (like many other tools do), and it appears it can't find the ini file where `json.so` is loaded or can't use temporary ini file. Is there anything special about your PHP setup? Ini path suggests CentOS / RedHat distro, do you have selinux enabled in enforcing mode?

**Comment by kkmuffme** [comment]
@weirdan I am using the remi package (which is the most common for centos7 I guess).

My json.ini is normal, just extension=json, so I don't think it has issues there.

No selinux isn't enabled.

Temporary ini file: in which directory does it create it? Perhaps it doesn't have permissions to create it there so it fails? (but just guessing)

**Comment by weirdan** [comment]
You may try to run Psalm with `XDEBUG_HANDLER_DEBUG` env variable set to 2. It'll print additional information during the restart process, including what php command it used and will keep temporary ini for you to examine:

```console
$ XDEBUG_HANDLER_DEBUG=2 ./psalm
xdebug-handler[28533] Checking PSALM_ALLOW_XDEBUG
xdebug-handler[28533] The xdebug extension is loaded (2.7.2)
xdebug-handler[28533] Process restarting (PSALM_ALLOW_XDEBUG=internal|2.7.2|1|*|*)
xdebug-handler[28533] Running '/home/weirdan/.phpenv/shims/php' '-n' '-c' '/tmp/qtRAk3' './psalm'
xdebug-handler[28602] Checking PSALM_ALLOW_XDEBUG
xdebug-handler[28602] Restarted (153 ms). The xdebug extension is not loaded
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  60 / 723 (8%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 120 / 723 (17%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 180 / 723 (25%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 240 / 723 (33%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 300 / 723 (41%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 360 / 723 (50%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 420 / 723 (58%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 480 / 723 (66%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 540 / 723 (75%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 600 / 723 (83%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 660 / 723 (91%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 720 / 723 (100%)
░░░

------------------------------
No errors found!
------------------------------

Checks took 26.31 seconds and used 404.307MB of memory
Psalm was able to infer types for 99.8270% of the codebase
xdebug-handler[28533] Restarted process exited 0
xdebug-handler[28533] Temp ini saved: /tmp/qtRAk3
$ less  /tmp/qtRAk3 # here you can inspect generated ini file
```

**Comment by kkmuffme** [comment]
Looks normal to me?

```
XDEBUG_HANDLER_DEBUG=2 ./vendor/bin/psalm --no-cache --config=my-folder/psalm.xml my-folder/my-file.php >> local.log
xdebug-handler[29293] Checking PSALM_ALLOW_XDEBUG
xdebug-handler[29293] The xdebug extension is loaded (2.7.2)
xdebug-handler[29293] Process restarting (PSALM_ALLOW_XDEBUG=internal|2.7.2|1|*|*)
xdebug-handler[29293] Running '/usr/bin/php' '-n' '-c' '/tmp/gSbHb3' './vendor/bin/psalm' '--no-cache' '--config=my-folder/psalm.xml' 'my-folder/my-file.php'
xdebug-handler[29293] Restarted process exited 0
xdebug-handler[29293] Temp ini saved: /tmp/gSbHb3
```

**Comment by weirdan** [comment]
Next step would be to inspect that temp ini for `extension=json.so` and try to find out why the extension is not loaded in this case.

**Comment by kkmuffme** [comment]
Oh ok, actually the json extension is normally loaded from /etc/php.d (from 20-json.ini)

I cannot check /tmp/gSbHb3, since this is not the "real" tmp directory, but a tmp directory php itself manages (this is a security feature of php), so not really sure how I would be able to see the .ini, especially since I guess the .ini is removed once the command finishes running.

**Comment by weirdan** [comment]
```
xdebug-handler[29293] Temp ini saved: /tmp/gSbHb3
```
This line indicates that the ini file was kept.

> I cannot check /tmp/gSbHb3, since this is not the "real" tmp directory, but a tmp directory php itself manages (this is a security feature of php)

I'm not aware of such feature in PHP, did you mean systemd's PrivateTmp unit option? It shouldn't apply to cli commands started from interactive shell I guess. 

But if your distro actually creates separate tmp folder for every process that could very well be the cause of the problem, since xdebug-handler creates a temporary ini file and restarts the process using this temporary ini (so spawned process needs to be able to access the temporary file generated by the parent process).

**Comment by kkmuffme** [comment]
Yes I meant PrivateTmp

No this directory doesn't exist (checked as user I run the psalm command and also as root):

```
cd: /tmp/gSbHb3: Not a directory
```

So I cannot find a .ini file either.

**Comment by weirdan** [comment]
`Not a directory` indicates that it *does* exist, but is not a directory (as it's a file, as it should be). If it didn't exist it would say `cd: no such file or directory`.

Just open it with whatever editor / viewer you use for text files.

**Comment by kkmuffme** [comment]
Sorry.

Yes in this file it has:

```
; Enable json extension module
extension=json
```

**Comment by weirdan** [comment]
Does psalm work if you run it as `'/usr/bin/php' '-n' '-c' '/tmp/gSbHb3' './vendor/bin/psalm' '--no-cache' '--config=my-folder/psalm.xml' 'my-folder/my-file.php'`? If it doesn't I would suggest comparing output of `php -i` vs `php -n -c /tmp/gSbHb3 -i` (original configuration vs what xdebug-handler generated).

**Comment by kkmuffme** [comment]
Thanks.

Checked, and they are completely different. The one composer creates is complete crap, bc it loads the absolute barebones, so all common extensions that are normally placed in /etc/php.d are completely missing: redis, imagick,...

Since this isn't really an issue with psalm, but composer, I think this can be closed, and I will just keep using the XDEBUG flag.

**Comment by weirdan** [comment]
Keep in mind that Psalm is not the only tool using that lib, it's quite popular. So you may face this issue again.

Did I get it right, `extension=json` is in that file, but extension is not loaded and there are no startup errors like `Unable to load dynamic library 'json.so'...`? It may indicate php failed to find or read the generated file. It would manifest in the phpinfo (`-i` switch) output as `Loaded Configuration File => (none)`. If the file was read, you would get something like `Loaded Configuration File => /tmp/qtRAk3` instead.
