### ISSUE TITLE
PossiblyNullReference: Cannot call method getId on possibly null value

### ISSUE THREAD

**Issue by ruudk** [vimeo/psalm#2269]
This is my code. I early return when something is null. 
```php
return array_filter($this->data, function (PayoutReversal $payoutReversal) use ($ids) {
            if ($payoutReversal->getPaidBackPayment() === null) {
                return false; // When it's null, then early return
            }

            // at this point, we now 100% that $payoutReversal->getPaidBackPayment() is not null
            return in_array($payoutReversal->getPaidBackPayment()->getId(), $ids, false);
        });
```

But still Psalm still complains

```
ERROR: PossiblyNullReference - src/Repo.php:135:68 - Cannot call method getId on possibly null value
            return in_array($payoutReversal->getPaidBackPayment()->getId(), $ids, false);
```

It does not understand that I already early return.

**Comment by ruudk** [comment]
When I change the code to this, it works:
```php
return array_filter($this->data, function (PayoutReversal $payoutReversal) use ($ids) {
            if ($var === null) {
                return false; // When it's null, then early return
            }

            // at this point, we now 100% that $payoutReversal->getPaidBackPayment() is not null
            return in_array($payoutReversal->getPaidBackPayment()->getId(), $ids, false);
        });
```

**Comment by ruudk** [comment]
I guess this is the same problem:
```
ERROR: PossiblyNullReference - src/File.php:75:99 - Cannot call method equals on possibly null value
                return $payout->getId() !== null && $payout->getId()->equals($somethingElse);
```

**Comment by muglug** [comment]
> at this point, we now 100% that $payoutReversal->getPaidBackPayment() is not null

You might, but Psalm doesn't - in theory `getPaidBackPayment` may return different values on subsequent calls.

> But that's not pretty.

Well, I wouldn't use the variable name `$var` - instead, `$paidBackPayment` or similar, but otherwise it's _much_ prettier to me, and it's also more performant - PHP isn't calling a method twice.

But if you want this pattern anyway, there's a config flag for you: [memoizeMethodCallResults](https://psalm.dev/docs/running_psalm/configuration/#memoizeMethodCallResults)

**Comment by ruudk** [comment]
You're right. I'll try it with `memoizeMethodCallResults` first, and maybe later optimize that :)
