### ISSUE TITLE
MixedPropertyFetch when skipping iteration in a foreach loop.

### ISSUE THREAD

**Issue by JensArctiq** [vimeo/psalm#2272]
Hi,

First of all, thanks for creating this package, I've been trying and testing this package in my own projects and I noticed some behavior I didn't expect. The situation is as follows:

When using the native "json_decode" function in PHP, you'll get a (nested) object which can contain several types. When I use the results in a foreach loop, I use a function to check whether one of the nested properties in the object is an actual object too, so I'm sure I can call another property on it.

However, the situation above still throws an "MixedPropertyFetch" exception. Am I doing something wrong here?

Link to snippet: https://psalm.dev/r/00ffcfd2c3

Many thanks!

**Comment by weirdan** [comment]
You can let Psalm know what your function is checking with `@psalm-assert-*`: https://psalm.dev/r/a36d5568e6

**Comment by muglug** [comment]
Yup, please use @weirdan's  suggestion!

**Comment by JensArctiq** [comment]
Thanks @weirdan and @muglug !
