### ISSUE TITLE
query re: get_magic_quotes_gpc & similar

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2276]
I'm wondering if it's out-of-scope for psalm to raise `RedundantCondition` when `get_magic_quotes_gpc()` is used in a condition, given that no version of psalm has supported a version of php that would ever `true`.

Same goes for any function/method currently (or subsequently, going forward) that returns a boolean hardcoded to `true` or `false` in php >= 5.4

**Comment by weirdan** [comment]
If Psalm does this for user-defined functions there's no reason it shouldn't do it for internal functions. Speaking of which, @muglug, is there a way to mark internal functions as deprecated in Psalm?

**Comment by SignpostMarv** [comment]
@weirdan would adding a deprecated tag to a stub work?

**Comment by weirdan** [comment]
It probably would, but functions are mostly described in the callmap, so creating stubs for them just to mark them deprecated sounds like an overkill to me. An attribute in the callmap would be more manageable IMO.

**Comment by SignpostMarv** [comment]
> An attribute in the callmap would be more manageable IMO.

would be it be necessary to specify the php semver that the class/method was deprecated in ?

**Comment by weirdan** [comment]
CallMap is versioned itself, so I don't think there's a need for that.

**Comment by SignpostMarv** [comment]
re: versioned callmaps, I was tinkering with this the other night & was wondering if I should be adding `CallMap_53_delta.php` (for `int|false`) & `CallMap_54_delta.php` (for `false`) ?
