### ISSUE TITLE
Different results yielded on slightly different envs

### ISSUE THREAD

**Issue by Taluu** [vimeo/psalm#2282]
I have 2 environments, one local with PP 7.2.24 and another one through docker (stretch+fpm) on 7.2.18. I tried with the docker image updated to 7.2.24, but no dice, I have the same problem...

Looks like 2 runs for psalm on these two envs yields different errors (which makes establishing a baseline difficult) ; even though there *may* be some differences on extensions (such as xdebug installed on one part, blackfire on the dockerized env), the errors doesn't seem to be dependant on those.

It's errors such as `PossibilyNullReference`, `TypeDoesNotContainType`, `PossiblyNullPropertyAssignmentValue`, `InvalidOperand`, ... and so on. So it doesn't really seem to be env related errors, does it ?

Thanks.

**Comment by Taluu** [comment]
Something new ; if I update my baseline from the dockerized env, and run it on the non-dockerized env, looks like it works (got no errors, as expected).

So basically, something looks wrong with the baseline generation on two different envs ?

**Comment by muglug** [comment]
Do you see this when running with `--no-cache`?

**Comment by Taluu** [comment]
I'm always running with `--no-cache`. What seems strange too, is that if I run with `--set-baseline` then `--update-baseline` on the same runtime, the baseline file seems to be edited (some things are removed)...

**Comment by Taluu** [comment]
Something new : using the same docker image on two different servers (one on local, one through a kubernetes pod) also seems to yield different results and making one crash (as it reports a `TypeDoesNotContainType` error).

The same (distant) image from amazon is used on both envs though, so I guess it's not something env related... right ?

**Comment by muglug** [comment]
Could it be related to file name casing? When this happens, it's almost always a *nix case-based issue.

**Comment by Taluu** [comment]
Hum, both env are on a docker image, and both images are run on a unix env...

Here is the code that makes a difference between the two envs :

```php
<?php

// $object is an object with some properties

$arr = [
   'key1' => ['foo', 'enabled'],
   'key2' => ['bar', 'enabled'],
   'key3' => ['baz', 'option'],
];

$result = [];

foreach ($arr as $key => $values) {
    $result[$key] = $value[1] === 'option' ? $this->getOption($value[0]) : $this->isEnabled($value[1]);
}
```

This is not the actual code, but this is what it looks like. On my dockerimage env, it doesn't complain, but on the remote env, it complains that the condition `$value[1] === 'option'` will never be true as `$value[1]` should always be equal to `enabled`.

Adding this manually to the baseline make the error go away.

**Comment by Taluu** [comment]
Bumping, as I think it's the same error reported in phpstan : https://github.com/phpstan/phpstan/issues/3827

Could it be because of parallelism ?

**Comment by muglug** [comment]
Closing, if you can reproduce in a repo feel free to reopen
