### ISSUE TITLE
Typecasting inside a conditional.

### ISSUE THREAD

**Issue by kaan-atakan** [vimeo/psalm#2287]
Consider the following situation:

```
function fun(ParentClass $instance) {
  if($instance instanceof SubClass) {
    $instance->subClassMethod();
  }
}
```
Where the ParentClass definition does not contain the method subClassMethod but SubClass does. Psalm throws an error here complaining that $instance does not have this method. Is there a way to tell psalm via a comment that we know now that $instance is an instance of SubClass without addding redundant code like:

```
function fun(ParentClass $instance) {
  if($instance instanceof SubClass) {
    /** @var SubClass */
    $instance=$instance
    $instance->subClassMethod();
  }
}
```

Which does resolve the issue but is long and adds extra code that doesn't serve any purpose but to satisfy psalm. Ideally we wouldn't even have to annotate the code and psalm would just get that we're dealing with the sub class when it sees the instanceof operator.

**Comment by muglug** [comment]
Hey - can you try to reproduce this issue on https://psalm.dev? The `@var` docblock should not be necessary.

**Comment by kaan-atakan** [comment]
Ok so I wrote the following test code:

```
<?php

Class BaseClass {
}

Class SubClass extends BaseClass {
  public function subClassFunc():void {
    echo "I exist";
  }
}

$inst = new SubClass();
fun($inst);

function fun(BaseClass $arg):void {
    if($arg instanceof SubClass) {
        $arg->subClassFunc();
    }
}
```

Which actually validated fine in a clean environment as well as on [psalm.dev](https://psalm.dev/r/c1fdebae7d).

**Comment by kaan-atakan** [comment]
I had the issue in a laravel installation. Inside the exception handler. I have the laravel plugin installed so maybe thats causing the issue, or I might not have set up a situation with adequate complexity. I think it might have had an extra condition as well as some code between the if statement and the function call. I'll have to check back tomorrow at work.

**Comment by kaan-atakan** [comment]
Okay so I was able to replicate the issue. It turns out that I was assigning the value of the instanceof comparison to a variable and then using that in the conditional like so:

```
function fun(BaseClass $arg):void {
    $isSubClass = $arg instanceof SubClass;
    if($isSubClass) {
        $arg->subClassFunc();
    }
}
```
Which results in psalm throwing the error:

`ERROR: UndefinedMethod - 18:15 - Method BaseClass::subclassfunc does not exist`

I don't know how feasible it is for psalm to track the contents of a boolean when it was assigned the result of an instanceof operation. In an ideal world it would even track when something like this happens: `$isSubClass = get_class($arg) == 'SubClass`' 

You can consider this a feature request,  But maybe I aught to just refactor my code. Also I figgured out that I can suppress the error with: `/** @psalm-suppress UndefinedMethod */`, see https://psalm.dev/r/3b335819bc

**Comment by muglug** [comment]
> You can consider this a feature request, But maybe I aught to just refactor my code.

Yeah. Psalm doesn't work properly with variables that are contingent on another's value, as that pattern could be broken by something like so:

```php
function fun(BaseClass $arg):void {
    $isSubClass = $arg instanceof SubClass;
    $arg = null;
    if($isSubClass) {
        $arg->subClassFunc();
    }
    $arg->subClassFunc();
}
```
