### ISSUE TITLE
Add `composer dump-autoload --optimize --classmap-authoritative` to recommended settings for project?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#229]
This helps with an issue (PHP fatal error) noticed in a project depending on php-activerecord/php-activerecord

- Relationship.php contained various classes, but no class called Relationship
- PHPdoc of another file contained a phpdoc mention of `@param Relationship $paramname`
- This resulted in Relationship.php being loaded twice by the composer autoloader, due to the classmap not being authoritative (composer would look for it in Relationship.php). (Psalm would die silently without --debug enabled)
- Using composer with an authoritative class map works around this.

**Comment by muglug** [comment]
Not going to add this - I think the improvements to autoloading should have made this easier to debug, and I haven't heard of someone encountering this elsewhere
