### ISSUE TITLE
Cannot figure out how to use nested template parameters

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#2291]
I try to use the following construction:

```php
/** 
  * @psalm-template TView as object
  * @psalm-param list<Viewable<TView>> $viewables
  * @psalm-return list<TView>
  */
function getViews(array $viewables): array
// ...
```

As you see, here I use nested `TView` template parameter. The intent is to map list of Viewable objects to their Views, and correctly typehint this. However, psalm gives me an error when trying to use this function. Am I doing something wrong?

see https://psalm.dev/r/d3dfbb95ce

BTW, this works in TypeScript: https://codesandbox.io/s/uwpqw

**Comment by someniatko** [comment]
I suspect that the problem lies in inability of TypeAnalyzer#isAtomicContainedBy() to check TNamedObject against TGenericObject

**Comment by someniatko** [comment]
Yeah! Based on the assumption above I have narrowed down the issue:

https://psalm.dev/r/d3dfbb95ce

It isn't related to nested templates now.

**Comment by muglug** [comment]
Adding `-covariant` to the template should fix the issue, but template covariance isn't currently inherited.

Here's an adapted version of an existing test that _should_ work, but doesn't: https://psalm.dev/r/e46d450967

**Comment by someniatko** [comment]
@muglug Thank you! Is this `-covariant` suffix documented anywhere? Also, shouldn't the covariance be the default behaviour?

**Comment by muglug** [comment]
It's currently undocumented, though it should be. It was added to fix #1603.

Covariance shouldn't be the default behaviour, as covariance comes with its own limitations - namely that covariant generic params can't then be used as input: https://github.com/vimeo/psalm/issues/1609

**Comment by someniatko** [comment]
Thank you for the explanation! 

> It's currently undocumented

I think there should be an issue dedicated to documenting the `template-covariant` behavior. If you don't mind, I can create one.

**Comment by muglug** [comment]
> If you don't mind, I can create one.

Yes please! Even better, you could write it! The reason I've resisted is that it's a fairly non-trivial thing to explain.

**Comment by someniatko** [comment]
@muglug Sorry to bother you, after the fix, the original code snippet does still not work https://psalm.dev/r/d3dfbb95ce (even if I add `-covariant` to the `@psalm-template` annotation). What did I do wrong in that case?

**Comment by muglug** [comment]
You didn’t add it in the right place: https://psalm.dev/r/716f4d7159
