### ISSUE TITLE
array_shift($arr) does not take type of $arr[0]

### ISSUE THREAD

**Issue by duskwuff** [vimeo/psalm#2295]
This seems unexpected. Surely `$arr[0]` and `array_shift($arr)` should have the same type? (Or am I missing something?)

```
<?php declare(strict_types=1);

function expects_int(int $x) : void { }

function type_of_array_shift(array $arr) : void {
  if (\is_int($arr[0])) {
    expects_int($arr[0]); // OK
    expects_int(\array_shift($arr)); // MixedArgument
  }
}
```

**Comment by TysonAndre** [comment]
That'd make sense for a `list`, and possibly to array shapes (from literals) with known keys, but doesn't apply to all `array`s

```
php > $x = [-1 => 'x', 0 => 'y'];
php > var_export($x[0]);
'y'
php > var_export(array_unshift($x));
2
```

**Comment by duskwuff** [comment]
Hinting the function as `/** @param list $arr */` still generates an error, though.

Interestingly, though, hinting it as `@param list<int> $arr` _doesn't_ raise an error.
