### ISSUE TITLE
Uncaught UnexpectedValueException: closure to have storage

### ISSUE THREAD

**Issue by NonnEmilia** [vimeo/psalm#2296]
Like in issue #2250, but running psalm 3.6.2@05ace258176795e87ef07b4262b5ceba3fd27de3 with PHP 7.2.4 (on Windows... with a network drive mounted on Q:... dammit!).

The command
```
.\vendor\bin\psalm -r Q:\project_dir --debug-by-line --no-cache
```
gives me:
```
Fatal error: Uncaught UnexpectedValueException: Expecting Q:\project_dir\script\class\ProjectVars.php:129:3053:-:closure to have storage in Q:\project_dir\script\class\ProjectVars.php in C:\Users\xxxxxxx\vendor\vimeo\psalm\src\Psalm\Codebase.php:647
Stack trace:
#0 C:\Users\xxxxxxx\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ClosureAnalyzer.php(18): Psalm\Codebase->getClosureStorage('Q:\\project_dir...', 'Q:\\project_dir...')
#1 C:\Users\xxxxxxx\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer.php(433): Psalm\Internal\Analyzer\ClosureAnalyzer->__construct(Object(PhpParser\Node\Expr\Closure), Object(Psalm\Internal\Analyzer\StatementsAnalyzer))
#2 C:\Users\xxxxxxx\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer.php(521): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object in C:\Users\xxxxxxx\vendor\vimeo\psalm\src\Psalm\Codebase.php on line 647
```

The closure is a simple callback for an `usort()`, commenting that closure it give the same error for every closure in the project.

**Comment by muglug** [comment]
Hmm, that may well be a windows-specific issue.

**Comment by NonnEmilia** [comment]
Nothing easier...

Feel free to tell me anything I can do to investigate further.

**Comment by muglug** [comment]
The storage should be created here: https://github.com/vimeo/psalm/blob/e7330afe8b316b730e9de0c2aa3c87cf9491fd12/src/Psalm/Internal/Visitor/ReflectorVisitor.php#L1704-L1706

You could add an `echo $function_id;` to see if the path there is different.

**Comment by NonnEmilia** [comment]
I debugged step by step and I found the issue: the function above return an id (in my case `Q:\project_dir\script\class\projectVars.php:129:3053:-:closure`) using the real file path as first argument; while in https://github.com/vimeo/psalm/blob/e7330afe8b316b730e9de0c2aa3c87cf9491fd12/src/Psalm/Codebase.php#L638 the variable `$file_path` is created with the classname (I guess) and results in `Q:\project_dir\script\class\ProjectVars.php:129:3053:-:closure` with an upper "P"!

Windows is case insensitive so the scripts are working well, but the PHP array keys getter is case sensitive so it fails and return the `UnexpectedValueException`.

I'll try to rename the file, it won't so easy for the same reason: even changing the file name and committing with git when I'll do a git pull in other places Windows won't change it...

**Comment by muglug** [comment]
Latest master should fix the issue!

**Comment by NonnEmilia** [comment]
It works like a charm!
Thank you very much.
