### ISSUE TITLE
"This element is not expected" when using `referencedClass` or `referencedMethod`

### ISSUE THREAD

**Issue by ruudk** [vimeo/psalm#2297]
After reading the docs https://psalm.dev/docs/running_psalm/dealing_with_code_issues/#config-suppression I tried to add this:
```xml
// ...
<issueHandlers>
        <RedundantConditionGivenDocblockType errorLevel="info">
            <errorLevel type="suppress">
                <referencedClass name="Stripe\Card" />
            </errorLevel>
        </RedundantConditionGivenDocblockType>
```

But I get this error:
```
Problem parsing /Volumes/CS/www/psalm.xml:
  Error on line 51:
    Element '{https://getpsalm.org/schema/config}referencedClass': This element is not expected.

exit status 1
```

**Comment by weirdan** [comment]
Not every issue type supports `referencedClass` (only those extending [`ClassIssue`](https://github.com/vimeo/psalm/blob/master/src/Psalm/Issue/ClassIssue.php) do). [`RedundantConditionGivenDocblockType`](https://github.com/vimeo/psalm/blob/master/src/Psalm/Issue/RedundantConditionGivenDocblockType.php) is not one of those.

**Comment by muglug** [comment]
Yeah, you want to be suppressing those particular ones line by line. Alternatively you could stub out the proper return types, if the stripe-given ones are incorrect.
