### ISSUE TITLE
[InvalidArrayOffset] Cannot access value using a string offset, expecting int

### ISSUE THREAD

**Issue by ruudk** [vimeo/psalm#2298]
I'm getting this error and I don't know how to resolve it. 
```
ERROR: InvalidArrayOffset - 20:34 - Cannot access value on variable Test::MAP using a string offset, expecting int(123)
```
https://psalm.dev/r/e805b6e381

**Comment by weirdan** [comment]
When you create an array key with a numeric string offset PHP silently casts it to int (https://3v4l.org/ZYlqW), and Psalm tells you that.

**Comment by muglug** [comment]
Yeah, not a bug
