### ISSUE TITLE
Document template-covariant behavior

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#2299]
As a fix for https://github.com/vimeo/psalm/issues/1603, a concept of "covariant templates" was born. However, as stated in https://github.com/vimeo/psalm/issues/2291#issuecomment-549525513, it was never documented.

Therefore, to fill this gap, covariant templates should be explained on this page: https://psalm.dev/docs/annotating_code/templated_annotations/

**Comment by muglug** [comment]
This was fixed in 7b6061efe3fb6535082990071668949ea0fe4400
