### ISSUE TITLE
RedundantConditionGivenDocblockType false positive and template type not detected

### ISSUE THREAD

**Issue by nicolopignatelli** [vimeo/psalm#2301]
https://psalm.dev/r/0ddbe71742

When a Maybe<int> object is returned from the `repository()` function, psalm is not able to narrow down the type to Some<int> inside the if block.

Is this an expected behaviour or am I setting up annotations the wrong way?

**Comment by muglug** [comment]
This is _unexpected_ behaviour - looks like refining generic types via `instanceof` is broken.
