### ISSUE TITLE
Hardcoded memory limit of 4096M in psalter makes it difficult to use more memory

### ISSUE THREAD

**Issue by ftzdomino** [vimeo/psalm#2302]
My application is very large and I need more than 4096M.  psalter.php has a line that overrides the CLI's default memory_limit setting with ini_set('memory_limit', '4096M');, making it impossible to provide more without manually commenting out this line.

It would be nice if psalter.php only set the memory_limit to 4096M if it was currently less than 4096M.

**Comment by muglug** [comment]
> It would be nice if psalter.php only set the memory_limit to 4096M if it was currently less than 4096M.

I like this idea, will use the same for Psalm

**Comment by iluuu1994** [comment]
Don't forget `-1` for unlimited memory. 🙂
