### ISSUE TITLE
Crash on invalid code

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#2304]
https://psalm.dev/r/a540ed53af
```php
<?php
  class C {
    public function execute(): parent {}
  }
```
**Expected**: Something along the lines of 'Cannot access parent:: when current class scope has no parent' (https://3v4l.org/4mVnJ)
**Actual**: 
```
Psalm runner output:

Internal Psalm error on line 1173 - /var/www/vhosts/psalm.dev/httpdocs/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php: Cannot handle parent when $parent_class is empty
```

**Comment by muglug** [comment]
Would you mind fixing this? You could introduce an issue called `InvalidParent`.

**Comment by weirdan** [comment]
Yeah, I'll take a look at this over the weekend.
