### ISSUE TITLE
The possibility that template parameter can be instantiated with type, narrower than its constraint, is not taken into account

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#2308]
Look at this snippet: https://psalm.dev/r/6d99f50803

here function `usesCollection<T>(Collection<T> $col)` is allowed to add arbitrary value to the collection, even though it's type T is not known. To demonstrate the possibility of bugs, i've created a collection of strings, and via this function added an integer to it. Psalm noticed no errors.

Such behavior is disallowed in TypeScript:

```ts
class Collection<T> {
    constructor(private col: T[]) {}

    add(element: T): void {
        this.col.push(element);
    }
}

function usesCollection<T>(col: Collection<T>) {
    col.add(123);
}
```

**Comment by someniatko** [comment]
BTW, i noticed that in this snippet it is also possible to instantiate the `$collection` as follows:
`$collection = new Collection([ 1, 2, 3 ]);` even though i stated it's collection of strings in `@var` annotation. I don't know whether `@var` annotation must take precendence over actual type inferred from code, so I do not call it a bug.

**Comment by muglug** [comment]
> I don't know whether @var annotation must take precendence over actual type inferred from code, so I do not call it a bug.

Yeah, `@var` always takes precedence. But the first is a bug.

**Comment by someniatko** [comment]
@muglug You are likely the fastest issue resolver in the open source world :)

Your fix indeed works, but somehow if i change `456` to an empty array, psalm does no longer notice the error:

See https://psalm.dev/r/f3e26879c7

**Comment by muglug** [comment]
Empty array case is now fixed, thanks
