### ISSUE TITLE
InvalidReturnType on templates since 3.6.3

### ISSUE THREAD

**Issue by Taluu** [vimeo/psalm#2309]
Just updated to 2.6.3, and using doctrine collection I now have the following error :

```
ERROR: InvalidReturnType - (file:line:col) - The declared return type 'Doctrine\Common\Collections\Collection<int, (my class)>' for (method) is incorrect, got 'Doctrine\Common\Collections\Collection<TKey, (my class)|Doctrine\Common\Collections\Collection<int, (my class)>'

     * @psalm-return Collection<int, (my class)>
```

(I replaced "sensible" information in there). Has something changed, or is it a bug of some sort ?

poke @Ocramius

**Comment by muglug** [comment]
Most likely a bug (I did a template handling refactor, thought I caught all the issues).

There should be a more specific issue at the site where `Collection<TKey, ...>` Is returned - what’s the code there?

**Comment by Ocramius** [comment]
Can you make an example on psalm.dev please?

**Comment by Taluu** [comment]
I kinda patched up the thing, but here it goes, and it looks like it's my error : https://psalm.dev/r/33a2ef1840

It was working on 3.6.2 but not anymore on 3.6.3.

**Comment by muglug** [comment]
No that looks like a Psalm bug, will hopefully have a patch in a sec

**Comment by muglug** [comment]
I've just created a release (3.6.4) - I don't want anyone else getting caught up in this.
