### ISSUE TITLE
is_array is ignored and error "Cannot access array value on mixed variable $decodedResponse" is returned

### ISSUE THREAD

**Issue by Aerendir** [vimeo/psalm#2323]
```console
ERROR: MixedArrayAccess - src/MyApp/Manager/MyManager.php:108:18 - Cannot access array value on mixed variable $decodedResponse
        $icons = $decodedResponse['icons'];
```

The code is this:

```php
    /**
     * @param string $url
     *
     * @throws JsonException
     * @throws \RuntimeException
     *
     * @return array
     */
    public function getFaviconUrlsList(string $url): array
    {
        $response = $this->getClient()->get($url)->getBody();
        // THIS IS THE LINE THAT CAUSES THE ERROR
        $decodedResponse = json_decode((string) $response, true);
        if (is_array($decodedResponse) && !isset($decodedResponse['icons'])) {
            throw new \RuntimeException('Impossible to get the list of favicons as the key "icons" doesn\'t exist: maybe the API response changed and the app needs to be updated.');
        }

        // THIS IS THE LINE THAT CAUSES THE ERROR
        $icons = $decodedResponse['icons'];

        if (false === is_array($icons)) {
            throw new \RuntimeException('The "icons" key is not an array: maybe the API response changed and the app needs to be updated.');
        }

        return $icons;
    }
```

As you can see from the provided code, I check that the content of `$decodedResponse['icons']` is actually an `array`.

If I use something like this:

```php
        /** @var array $decodedResponse */
        $decodedResponse = json_decode((string) $response, true);
```

The error disappears, but I like to avoid adding the comment.

Is this error on my side or is something Psalm should take into account?

**Comment by muglug** [comment]
I think it's maybe an issue on your side:

```php
if (is_array($decodedResponse) && !isset($decodedResponse['icons'])) {
```

should be

```php
if (!is_array($decodedResponse) || !isset($decodedResponse['icons'])) {
```

and then Psalm will understand the code

**Comment by Aerendir** [comment]
@muglug , please, reopen this issue: it is not solved!

This is the code:

```php
    public function getFaviconUrlsList(string $url): array
    {
        $response = $this->getClient()->get($url)->getBody();
120     $decodedResponse = json_decode((string) $response, true);
        if (false === is_array($decodedResponse) || false === isset($decodedResponse['icons'])) {
            throw new RuntimeException('Impossible to get the list of favicons as the key "icons" doesn\'t exist: maybe the API response changed and the app needs to be updated.');
        }

125     $icons = $decodedResponse['icons'];

        if (false === is_array($icons)) {
            throw new RuntimeException('The "icons" key is not an array: maybe the API response changed and the app needs to be updated.');
        }

        return $icons;
    }
```

Those are the errors:

```console
ERROR: MixedAssignment - src/Hub/Coommercio/Manager/FaviconManager.php:120:9 - Cannot assign $decodedResponse to a mixed type
        $decodedResponse = json_decode((string) $response, true);


ERROR: MixedAssignment - src/Hub/Coommercio/Manager/FaviconManager.php:125:9 - Cannot assign $icons to a mixed type
        $icons = $decodedResponse['icons'];


ERROR: MixedArrayAccess - src/Hub/Coommercio/Manager/FaviconManager.php:125:18 - Cannot access array value on mixed variable $decodedResponse
        $icons = $decodedResponse['icons'];
```

It continues to ignore the `is_array()` call to check that the `mixed` value retruned by `json_decode()` is actually an `array` and to check that `$decodedResponse['icons']` is an `array`, too.

There is also the `MixedArrayAccess` error.

I have no idea about how to solve those issues.

**Comment by muglug** [comment]
Yeah, you're right, there's a bug lurking.

You can work around it by separating out the `is_array($decodedResponse)` check:

```php
function getIconsBroken(string $response): array {
  $decoded = json_decode((string) $response, true);

  if (!is_array($decoded)
      || !isset($decoded['icons'])
      || !is_array($decoded['icons'])
  ) {
    throw new RuntimeException('Bad.');
  }
  
  $icons = $decoded['icons'];

  return $icons;
}

function getIconsFixed(string $response): array {
  $decoded = json_decode((string) $response, true);

  if (!is_array($decoded)) {
    throw new RuntimeException('Bad.');
  }
  
  if(!isset($decoded['icons'])
      || !is_array($decoded['icons'])
  ) {
    throw new RuntimeException('Bad.');
  }
  
  $icons = $decoded['icons'];

  return $icons;
}
```

https://psalm.dev/r/76b407403d

_By the way_ `if (false === is_array(...))` is identical to `if (!\is_array(...))`, but slower to execute.

**Comment by Aerendir** [comment]
This solution continues to raise errors:

> MixedAssignment - 19:3 - Cannot assign $decoded to a mixed type

Anyway, thank you for the hint about using `!` instead of `false === ...`!

**Comment by muglug** [comment]
> This solution continues to raise errors

That error is valid - Psalm doesn’t know the type that’s returned by `json_encode`

**Comment by muglug** [comment]
Fixed in 7f5af74

**Comment by Aerendir** [comment]
> That error is valid - Psalm doesn’t know the type that’s returned by `json_encode`

Ok, but I then check it is an `array`, so I want an `array`: nothing mixed.
`json_decode` returns `mixed`, but I then explicitly check for only one kind of variable: `array`.

This behavior is confusing me...

**Comment by muglug** [comment]
Now the fix is in place, it shouldn't be confusing:

There's only one issue here, when assigning the (unknown) output of `json_decode` to a variable: https://psalm.dev/r/a6df0888e1

Everything else now works

**Comment by Aerendir** [comment]
@muglug , ok, I've understood that this is an intended behavior.

What I don't understand is why Psalm behaves this way and I also don't understand how should I fix the issue?

**Comment by muglug** [comment]
> What I don't understand is why Psalm behaves this way and I also don't understand how should I fix the issue?

Psalm behaves that way to warn you that it cannot infer a type, and therefore that using that value is potentially dangerous.

Psalm's own codebase [has a few of these warnings suppressed](https://github.com/search?utf8=%E2%9C%93&q=MixedAssignment+repo%3Avimeo%2Fpsalm+path%3Asrc%2FPsalm%2FInternal+language%3APHP+language%3APHP&type=Code&ref=advsearch&l=PHP&l=PHP) when unserialising data strings – it's fine to suppress them, given PHP currently doesn't provide the ability to cast via syntax.

**Comment by Aerendir** [comment]
So I should necessarily use something like `/** psalm-suppress MixedAssignment */`?

**Comment by muglug** [comment]
Yes!
