### ISSUE TITLE
Error: `Could not get class storage for static`

### ISSUE THREAD

**Issue by andyg0808** [vimeo/psalm#2324]
I'm currently running into an issue where Psalm is throwing an `InvalidArgumentException` with `Could not get class storage for static`.

I've been able to duplicate on psalm.dev: https://psalm.dev/r/32b598075a
Changing `self`to `static` also fails, but if it's changed to the class name, it doesn't, for whatever that's worth.
Using `uasort`, it breaks in a way like it thinks I'm passing an array of strings: https://psalm.dev/r/ad786185a1

Possibly related to #2278.

**Comment by weirdan** [comment]
Shouldn't throw that, but you can replace `'self'` with `self::class` as a workaround.

**Comment by muglug** [comment]
Sorry about that - @weirdan is right, changing to `self::class` will fix it more immediately.
