### ISSUE TITLE
Unused variables in foreach

### ISSUE THREAD

**Issue by mitelg** [vimeo/psalm#2325]
hey guys,

according to this issue https://github.com/vimeo/psalm/issues/540 there should be a possibility to name variables in a certain way, so that Psalm does not complain about them. It seems, that this feature was removed https://psalm.dev/r/44f857c752
Was this intended? Is there any other way to fix issues like this?

thanks and best regards :wave:

**Comment by iluuu1994** [comment]
Seems like it's broken for everything except for `$_`.

https://psalm.dev/r/88bfb0bab8

**Comment by muglug** [comment]
The fix in #540 was just for unused _params_, but this is an easy change

**Comment by mitelg** [comment]
thanks a lot @muglug :+1:
