### ISSUE TITLE
Psalm doesn't use inferred return type of function.

### ISSUE THREAD

**Issue by Akhristenko** [vimeo/psalm#2329]
Example: https://psalm.dev/r/d92ae55d0b

Psalm can infer return type of function. But if function doesn't have explicit return type declaration in signature or phpdoc, psalm take mixed for return type. And when we use this value in inappropriate context later, psalm show to us INFO: MixedArgument instead of ERROR: InvalidArgument.

I suggest use this inferred type when function doesn't have explicit type, by default or via some flag in setting.

It make psalm more usefull when it start used in legacy project.

**Comment by muglug** [comment]
You can add return types for those functions missing them with Psalter: https://psalm.dev/docs/manipulating_code/fixing/#missingreturntype. Psalm can then use those return types the next time it runs.

**Comment by Akhristenko** [comment]
This solution does not work if return types are omitted in third-party libraries.
Also, several argument for this issue:
- type inference can help find and show as error more real error without do any job on some legacy project
- with return type inference you can write less in trivial situations
- typescript have this feature

Some statical-typed languages(for example scala/haskell) considered type inference as an advantage. If you think this is a bad idea, can you say why?

**Comment by muglug** [comment]
> This solution does not work if return types are omitted in third-party libraries

Yes, but Psalm doesn't analyse the bodies of third-party libraries (for performance reasons), so there's nothing to be gained there.

> typescript have this feature

Does it have this feature across file boundaries? I recall that Flow limited its inference that way, to prevent pathalogical situations.

> Some statical-typed languages(for example scala/haskell) considered type inference as an advantage. If you think this is a bad idea, can you say why?

I agree that type inference would find more errors _without_ having to alter the codebase, but the feature is also decidedly non-trivial to implement in a performant manner and, in my rather limited experience, languages that lean heavily on type inference (e.g. Haskell, StandardML) tend to encourage codebases that are hard for less-smart people like me to read. Explicit types are like signposts — they can help you orient yourself as you examine new code.

If you'd like to contribute this feature, I'd be more than happy to look at a proposal and help guide the execution, but it's not something that I want to spend a lot of my own time on, given the issues above.
