### ISSUE TITLE
Null coalescing assignment operator generates PossiblyNullArgument

### ISSUE THREAD

**Issue by Girgias** [vimeo/psalm#2339]
Example: https://psalm.dev/r/b42d636ea7

It seems to me that maybe Psalm does not recognize this PHP 7.4 feature only.

**Comment by muglug** [comment]
Yeah, full PHP 7.4 support will land closer to the release date.

**Comment by Girgias** [comment]
> 
> 
> Yeah, full PHP 7.4 support will land closer to the release date.

Any ETA on PHP 7.4 support? Release is on Thursday (has been tagged for QA process)

**Comment by muglug** [comment]
> Any ETA on PHP 7.4 support?

I've just closed all the 7.4 tickets - there's probably more to do, but the big-ticket items — property types, arrow functions, return type covariance and null coalescing assignment — are now done.
