### ISSUE TITLE
Conditional logic to infer variable type dynamically implemented half-way?

### ISSUE THREAD

**Issue by afbarbaro** [vimeo/psalm#2341]
Psalm can do a great job of figuring out the type of a variable dynamically.  In this [example](https://psalm.dev/r/9d9d843621) I show how it can figure out that `$foo` is effectively of type `A`:

```
class A { 
  public function go() : int { return 1;}
}

/** @var bool|A $foo */
$foo = new A();
$v = is_bool($foo) ? -1 : $foo->go();  // Psalm is awesome for this! It knows we can safely call $foo->go() :D
```

However, it can't figure out the same thing on these other equivalent alternatives (both of them safe):
$v = is_boolean($foo) ? -1 : $foo->go(); // is_boolean yields false (see example)
$v = $foo->go(); 

Thanks for providing such an awesome life-saver tool!  We rely on it every day.

**Comment by muglug** [comment]
Search for `'is_bool'` in the source code and create a PR that supports `is_boolean` too!

**Comment by afbarbaro** [comment]
> Search for `'is_bool'` in the source code and create a PR that supports `is_boolean` too!

I think I was looking for a global fix that can infer that at a given point the variable is not a `bool` but I looked a the code and yes, it's got some direct checks to `is_bool`.  I'm hesitant to attempt to change it because it wouldn't be a general to hard-code other functions.

**Comment by muglug** [comment]
ah right, sorry I assumed it was a PHP function.
