### ISSUE TITLE
Inline DocBlock requires two asterisks, perhaps one will suffice?

### ISSUE THREAD

**Issue by localheinz** [vimeo/psalm#2344]
When using `friendsofphp/php-cs-fixer` with the `phpdoc_to_comment` fixer enabled, the following diff will be applied

```diff
 foreach ($this->subscribers[$eventClassName] as $subscriber) {
-    /** @noinspection PhpParamsInspection */
+    /* @noinspection PhpParamsInspection */
-    /** @psalm-suppress UndefinedInterfaceMethod */
+    /* @psalm-suppress UndefinedInterfaceMethod */
     $subscriber->notify($event);
 }
```

This, however, results in `vimeo/psalm` ignoring (i.e., not understanding) the annotations.

Not sure, do we need to disable the `phpdoc_to_comment` fixer, or would it be possible to make adjustments so these inline DocBlocks/comments are understood by `vimeo/psalm`?

**Comment by andrew-demb** [comment]
AFAIK psalm especially support parsing phpdoc only started with `/**`.

phpdoc docs says, that all valid structured comment should starts with `/**` https://docs.phpdoc.org/getting-started/your-first-set-of-documentation.html#what-does-a-docblock-look-like

Also in draft PSR for phpdoc they required the same starting symbols
https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#3-definitions

**Comment by muglug** [comment]
Yeah, only `/**` is valid phpdoc

**Comment by localheinz** [comment]
Thank you for the clarification, @andrew-demb and @muglug!

**Comment by localheinz** [comment]
For reference, also see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3611.
