### ISSUE TITLE
MismatchingDocblockReturnType behaves weirdly with covariant return types and docblocks

### ISSUE THREAD

**Issue by pamil** [vimeo/psalm#2345]
```php
<?php
  
class A {
  /**
   * @return string|null
   */
  public function foo(): ?string
  {
    return null;
  }
}

class B extends A {
  public function foo(): string
  {
    return 'B';
  }
}
```

The following snippet generates these errors:
```
Psalm output (using commit 00be4c2):

ERROR: MismatchingDocblockReturnType - 14:26 - Docblock has incorrect return type 'null|string', should be 'string'

INFO: MixedInferredReturnType - 14:26 - Could not verify return type 'null|string' for B::foo
```

If you remove the docblock for `A::foo` or add one with `@return string` for `B::foo`, theses issues are solved.

https://psalm.dev/r/e40ab8146b

**Comment by muglug** [comment]
I think this particular case can be solved by ignoring inherited docblocks where nullability changes between types, but it's slightly intrinsic to automatic docblock inheritance.

**Comment by weirdan** [comment]
No longer reproducible: https://psalm.dev/r/e40ab8146b
