### ISSUE TITLE
Suppression fails on class properties

### ISSUE THREAD

**Issue by tvdijen** [vimeo/psalm#2347]
https://psalm.dev/r/f3b0e5dab3

I would expect the suppression to work though..

**Comment by tvdijen** [comment]
In this case I missed a dev-dependency.. I would expect the suppression to work though

**Comment by SignpostMarv** [comment]
ditto w/typed https://psalm.dev/r/78b334c298

**Comment by weirdan** [comment]
These are now properly suppressed.
