### ISSUE TITLE
Add option to use alternate serializers (igbinary, maybe msgpack) if available?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#235]
On a large project, caching /tmp/psalm/php-parser with igbinary_serialize and igbinary_unserialize took up 60MB of space, and with serialize()/unserialize() took up 240MB of space. (4x savings, even without a compression algorithm such as gzcompress)

- igbinary_serialize() has less header overhead for representing strings, arrays, etc.
  It also de-duplicates strings (class names, property keys, property values, etc., which serialize() doesn't.
- Not as familiar with msgpack's implementation.
- May add memory savings, due to string deduplication when unserializing.

The amount of disk space used would be larger if a user decided to analyze everything in `vendor`.

Of course, depending on the CFLAGS used, igbinary may end up being slower than serialize(), which is why making this the user's choice would make sense.

- Noticed this when testing, see https://github.com/igbinary/igbinary/ PR 145  (`CFLAGS=-O3 pecl install igbinary`, for example, should be as fast or faster).

**Comment by muglug** [comment]
On a large project (e.g. Vimeo's PHP codebase) using `igbinary` results in a 30% increase in speed, so it's worth it for that reason alone.

**Comment by muglug** [comment]
While using `igbinary_serialize` cuts the disk usage of a large project by a similar amount, it more than doubles the amount of time taken to run Psalm (that's with string compacting turned on).

Do you see a similar impact on speed? I'm not too happy with that trade off (even on a project that uses far in excess of 240MB).

It's faster to turn off caching entirely (or, more accurately, clear the folder after Psalm finishes execution) than it is to use igbinary on my machine (a late-2016 Macbook Pro)

**Comment by TysonAndre** [comment]
Again, I had to install with `CFLAGS=-O3`, I normally build igbinary from source instead of via pecl.

The performance is better with the override `CFLAGS=-O3`, but worse without it. 2.0.5 should have CFLAGS=-O2 as a default:

```
CFLAGS=-O3 pecl install igbinary                                                                                                                  WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update                                                                                    downloading igbinary-2.0.4.tgz ...                                                                                                                                                             Starting to download igbinary-2.0.4.tgz (68,294 bytes)                                                                                                                                         
.................done: 68,294 bytes                                                                                                                                                            
22 source files, building                               
```

```
» time ./bin/psalm; time ./bin/psalm
Checks took 3.9887239933014 and used 65.589MB
./bin/psalm  3.95s user 0.06s system 99% cpu 4.018 total
Checks took 2.9521949291229 and used 59.851MB
./bin/psalm  2.95s user 0.02s system 99% cpu 2.977 total
```

After `pecl uninstall igbinary` and removing extension=igbinary.so from php.ini, then clearing cache:

```
» time ./bin/psalm; time ./bin/psalm
Checks took 4.2273609638214 and used 63.495MB
./bin/psalm  4.16s user 0.09s system 99% cpu 4.257 total
Checks took 3.4594209194183 and used 57.910MB
./bin/psalm  3.44s user 0.04s system 99% cpu 3.484 total
```

The first time (3.0 seconds) had this patch:

```
--- a/src/Psalm/Provider/CacheProvider.php
+++ b/src/Psalm/Provider/CacheProvider.php
@@ -52,7 +52,7 @@ class CacheProvider
             filemtime($cache_location) > $file_modified_time
         ) {
             /** @var array<int, \PhpParser\Node\Stmt> */
-            return igbinary_unserialize((string)file_get_contents($cache_location)) ?: null;
+            return unserialize((string)file_get_contents($cache_location)) ?: null;
         }
     }
 
@@ -103,7 +103,7 @@ class CacheProvider
                 mkdir($parser_cache_directory, 0777, true);
             }
 
-            file_put_contents($cache_location, igbinary_serialize($stmts));
+            file_put_contents($cache_location, serialize($stmts));
```

**Comment by muglug** [comment]
Interesting. I'll investigate more tomorrow, but looks good.

**Comment by TysonAndre** [comment]
Hopefully, 2.0.5 should improve the performance a bit more. Also, if optimization flags aren't provided for gcc, it now uses -O2 (It was failing to detect gcc under some circumstances). And 2.0.5 finally has working Windows DLLs again.

- https://github.com/igbinary/igbinary/blob/master/NEWS

In all igbinary versions, disabling compact_strings speeds up serialization noticeably, but would use more space on disk and slow down unserialization (and use more memory after unserializing).
