### ISSUE TITLE
Excluding directories/globbing

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#2351]
Great tool, but the directory globbing is beyond me.

My file structure I want to exclude is:
/start/my/example/test-library/some-file.php
/start/my/example/some-library/some-file.php
/start/my/example/another/xyz-file.php
/start/my/example/testing/xyz-abc.php
/start/my/test/hello/world.php

How can this be achieved? These files are loaded/required by a.php which is the file I am analysing with psalm.
I need to be able to glob it as the structure is variable and there is not a specific number of directories.
I tried like:
```
**/*library/
**/xyz-*
**/hello/
```

but none is working

**Comment by muglug** [comment]
Would you be able to create a sample repo with the folder structure?

**Comment by muglug** [comment]
Closing - if you're able to reproduce in a sample repo, happy to reopen.
