### ISSUE TITLE
Feature Request: Statically prove a numeric variable can only be an integer

### ISSUE THREAD

**Issue by Girgias** [vimeo/psalm#2352]
This is probably a long shot, but would it be possible to prove that the result from a certain function can only be an integer and not a float?
Current example I have is available here: https://psalm.dev/r/af48f9b428
In this example the ``$integerRepresentation`` is assured to be within a certain range which can be represented by a 32bit unsigned integer.

I know that the easy solution here is to explicitly type cast to integer using ``(int)`` but just wanted to know how feasible of a feature this is.

**Comment by weirdan** [comment]
> In this example the $integerRepresentation is assured to be within a certain range which can be represented by a 32bit unsigned integer.

But it's not assured to be integer though. `π` is in that range as well, yet it's most certainly not an integer.

I think in this case adding `\is_int()` check makes most sense: https://psalm.dev/r/4e84825ea7
If you're worried about performance impact (which should be negligible as it's compiled into a specialized opcode: https://3v4l.org/tVlNW/vld#output) you can put it into an `assert()` and have zero run-time penalty (when php is configured with production settings): https://psalm.dev/r/cba8a01028

**Comment by muglug** [comment]
No, I won’t add that, but it looks like `hexdec` is a good candidate for having an `int` return type with a `from_calculation` flag, which is the same type given to `$some_int + $other_int` (allowing the result to be checked to see if it has overflowed into a float). Try PRing that - you’ll want to create a function return type provider. Feel free to ping me for help!

**Comment by Girgias** [comment]
> 
> 
> > In this example the $integerRepresentation is assured to be within a certain range which can be represented by a 32bit unsigned integer.
> 
> But it's not assured to be integer though. `π` is in that range as well, yet it's most certainly not an integer.
> 
> I think in this case adding `\is_int()` check makes most sense: https://psalm.dev/r/4e84825ea7
> If you're worried about performance impact (which should be negligible as it's compiled into a specialized opcode: https://3v4l.org/tVlNW/vld#output) you can put it into an `assert()` and have zero run-time penalty (when php is configured with production settings): https://psalm.dev/r/cba8a01028

I'm not sure I understand what you are going for? I know that there are floats within that range but my use case is insuring that the value returned by ``hexdec`` hasn't overflown which is assured because the hexvalue is representable in less than 31 bits. (and ``hexdec`` returns an integer when it can).
I'm not really worried about the performance, but if I can prevent an, IMHO, unnecessary condition then I'm personally all for it.



> 
> 
> No, I won’t add that, but it looks like `hexdec` is a good candidate for having an `int` return type with a `from_calculation` flag, which is the same type given to `$some_int + $other_int` (allowing the result to be checked to see if it has overflowed into a float). Try PRing that - you’ll want to create a function return type provider. Feel free to ping me for help!

It is indeed the same :) I didn't know that there was already some similar feature done, also I didn't know how to express what I wanted. I'll try to work on that ASAP :)

**Comment by weirdan** [comment]
@Girgias IMO the feature as requested ("prove a numeric variable can only be an integer") is probably not doable at all. At least I don't see what kind of operations may prove that for *arbitrary* numeric value.

Now if we're talking about some kind of `int|overflown-int` type then range check may suffice.

**Comment by Girgias** [comment]
> 
> 
> Now if we're talking about some kind of `int|overflown-int` type then range check may suffice.

This is mostly what I want, just expressed myself very badly.
