### ISSUE TITLE
`instanceof` does not narrow type (at all)

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#2356]
It's a follow-up for the https://github.com/vimeo/psalm/issues/2234

https://psalm.dev/r/bdb4a135d4

```php
<?php
  
interface One {
  function callme(string $data): void;
}

interface Two {
  function callme(int $data): void;
}

/** @var One|Two $value */
$value = null;

if ($value instanceof One) {
    $value->callme('1');
    $value->callme(1);
}

$value->callme('1');
$value->callme(1);
```

Looking at the discussion at the very bottom - does it mean that psalm would never be able to handle this valid php code?

**Comment by muglug** [comment]
> Looking at the discussion at the very bottom - does it mean that psalm would never be able to handle this valid php code?

Yes, basically. Interfaces with different param types for same-named functions is a weird and bad edge-case that I don't want to support.
