### ISSUE TITLE
It looks like `non-empty-list<string>` narrowing to `array{string, string}` was broken

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#2357]
https://psalm.dev/r/d477552109

```php
<?php
  
/**
 * @psalm-assert array{string,string} $value
 * @param mixed $value
 */
function isStringTuple2($value): void {}

$s = '';

$parts = explode(':', $s, 2);

isStringTuple2($parts);
```
```
Psalm output (using commit e76beff):

INFO: UnusedParam - 7:25 - Param $value is never referenced in this method

ERROR: TypeDoesNotContainType - 13:1 - Cannot resolve types for $parts - non-empty-list<string> does not contain array{0: string, 1: string}
```

**Comment by muglug** [comment]
So this isn't entirely  wrong, insofar as `array{string,string}` is the same as `array{0: string, 1: string}` which accepts both `["hello", "goodbye"]` and `[1 => "goodbye", 0 => "hello"]`.

But I agree there should be some way to annotate this.

I think https://psalm.dev/r/4284edcd12 would be best

**Comment by zerkms** [comment]
> So this isn't entirely wrong

`non-empty-list<string> does not contain array{0: string, 1: string}`

`non-empty-list<string>` definitely contains the `array{string,string}` type, it is its direct supertype.

**Comment by muglug** [comment]
> `non-empty-list<string>` definitely contains the `array{string,string}` type

Not quite, for the same reason given above - there are types that match `array{0: string, 1: string}` that would not match `non-empty-list<string>` (for example `[1 => "a", 0 => "b"]`)

But I realise that your initial example should still work (for the same reason that this does: https://psalm.dev/r/adad59f3a6) - that is, the assertion type can filter the given one without replacing it.

So after the assertion the new type would be represented internally as `array{0: string, 1: string}<int, string>` with the `is_list` flag set to `true`.

**Comment by zerkms** [comment]
Right, I totally did not consider you can reorder numeric indexes in php, you're surely right, my apologies.

**Comment by muglug** [comment]
This now has the desired output on psalm.dev: https://psalm.dev/r/4c673d6dd3
