### ISSUE TITLE
Falsy UnusedVariable error

### ISSUE THREAD

**Issue by mitelg** [vimeo/psalm#2358]
Hello,
currently I'm trying to introduce the `findUnusedVariablesAndParams` feature to the [Shopware platform](https://github.com/shopware/platform).
Unfortunately I get and error  in some of our tests files which I cannot comprehend. They do all the same as the [CartAmountRuleTest](https://github.com/shopware/platform/blob/master/src/Core/Checkout/Test/Rule/Rule/Cart/CartAmountRuleTest.php#L42-L47)
the error:
```
	ERROR: UnusedVariable - platform/src/Core/Checkout/Test/Rule/Rule/Cart/CartAmountRuleTest.php:18:9 - Variable $cart is never referenced
	        $cart = Generator::createCart();
	
	
	ERROR: UnusedVariable - platform/src/Core/Checkout/Test/Rule/Rule/Cart/CartAmountRuleTest.php:19:9 - Variable $context is never referenced
	        $context = $this->createMock(SalesChannelContext::class);

```
But obviously the variables are used.
 
I also wasn't able to reproduce this on https://psalm.dev/ so you guys could check it better. :disappointed: 
Hope you could help nevertheless :blush: :+1: 

best regards from Schöppingen :wave:

**Comment by weirdan** [comment]
It seems Psalm does not mark variables as used when they are used in a call to methods on mixed var (`$rule` is mixed there, as you omitted the return type in `AssignArrayTrait`). This is easily fixed with the following patch:
```patch
diff --git a/src/Core/Framework/Struct/AssignArrayTrait.php b/src/Core/Framework/Struct/AssignArrayTrait.php
index c4a0d1e0b2..e9de27c1b6 100644
--- a/src/Core/Framework/Struct/AssignArrayTrait.php
+++ b/src/Core/Framework/Struct/AssignArrayTrait.php
@@ -4,6 +4,7 @@
 
 trait AssignArrayTrait
 {
+    /** @return $this */
     public function assign(array $options)
     {
         foreach ($options as $key => $value) {
```

**Comment by muglug** [comment]
Reproduced here:

```php
/**
 * @psalm-suppress MixedAssignment
 * @psalm-suppress MixedMethodCall
 * @psalm-suppress MissingParamType
 */
function foo($a): void {
    $m = $_GET["m"] ?? null;
    $a->foo(new Exception($m));
}
```

**Comment by mitelg** [comment]
@muglug thanks a lot for the incredible fast fix :+1: :blue_heart: 
you guys do an amazing job :blush:

**Comment by mitelg** [comment]
@weirdan also thanks a lot to you. you solution works, too :+1:
