### ISSUE TITLE
InvalidArgument Argument 2 of imagepng expects null|string, false|resource provided

### ISSUE THREAD

**Issue by k2rn** [vimeo/psalm#2365]
When I ran psalm on my project, I encountered this message.

```
InvalidArgument - src/xxxxx/xxxxx - Argument 2 of imagepng expects null|string, false|resource provided
        if (!imagepng($img, $handle)) {
```

the code is below.
```
        $handle = tmpfile();
        if (!imagepng($img, $handle)) {
            throw new Exception('Failed to create png.');
        }
        imagedestroy($img);
```

I think the argument 2 of imagepng can accept resource.
https://www.php.net/manual/en/function.imagepng.php

Is this an issue? or how do I run psalm correctly?

**Comment by muglug** [comment]
@k2rn you could fix this with a PR to `CallMap.php`

**Comment by k2rn** [comment]
@muglug I created PR for fix this issue.

https://github.com/vimeo/psalm/pull/2373
