### ISSUE TITLE
Handle "Could not get class storage.." error more gracefully.

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#2368]
A file used inline annotation like `@var \Cake\Console\Command`. The file for `Command` class did not have any class definition but just a `class_alias()` call since this the class moved under a different namespace.

This caused psalm to crash with following error:
```
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get class storage for cake\console\command in phar:///home/admad/.phive/phars/psalm-3.6.6.phar/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:42
````

One would expect pslam to handle this case more gracefully and show some error message instead of crashing.

**Comment by muglug** [comment]
I realise it’s a while back, but would you be able to recreate this error in a repo?

**Comment by ADmad** [comment]
Change this line 
https://github.com/cakephp/cakephp/blob/a524ad808e2b4e96c788d396485a67807b649a21/src/Console/CommandScanner.php#L143 
to 
`/** @var \Cake\Console\Command $class */` and then run psalm on the full code base and you should get the error.

**Comment by ADmad** [comment]
Thanks.
