### ISSUE TITLE
Error when error suppresions are configured which dont suppres a actual error

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#2369]
Similar to https://github.com/vimeo/psalm/issues/2033 but for the psalm.xml when handlers are defined like e.g. `<PossiblyInvalidOperand errorLevel="info" />` but the codebase-scan does not contain a PossiblyInvalidOperand error psalm should report that one can/should remove the suppression rule (like phpstan does)

**Comment by weirdan** [comment]
Fixed in #10341
