### ISSUE TITLE
wrongly infered return type

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#2371]
IMO the return type inferred is wrong.
I cannot see a path thru the code which would lead to a `string` type into the return value.

https://psalm.dev/r/ad993518a1

**Comment by muglug** [comment]
Psalm cannot understand foreach loops which wholly change the type of an array (it’s a very hard thing to reason about, and there are other similar closed issues). Either suppress the issue, or change your code to create a new array in the foreach loop.
