### ISSUE TITLE
Undefined class PHPUnit\Framework\Constraint\LogicalOr

### ISSUE THREAD

**Issue by ndench** [vimeo/psalm#2375]
Full disclosure, I don't know how to reproduce this in a small testable case but I also don't know how to fix it in our codebase so I'm looking for pointers on where to look or what to do next.

We have a PHPUnit test containing the following:

```php
// Escape the same way twig does with \twig_escape_filter
$htmlEncoded = \htmlspecialchars($expected, ENT_QUOTES | ENT_SUBSTITUTE);

// Twig won't escape strings that are hard-coded into the twig file, only the variables.
// So we need to check for either or.
TestCase::assertThat(
    $this->getHtml(),
    TestCase::logicalOr(
        TestCase::stringContains($expected, false),
        TestCase::stringContains($htmlEncoded, false)
    )
);
```
Psalm reports the `LogicOr` class returned by `TestCase::logicalOr` as undefined. This is the only Psalm error we have so it's not reporting any other issues with our PHPUnit usage, but this is the only place we use `TestCase::logicalOr`.

We also use `symfony/phpunit-bridge` which means that `phpunit/phpunit` is installed at `vendor/bin/.phpunit/phpunit-8.3.5-0` and that we have the following in `psalm.xml`:

```xml
<psalm
        ...
        autoloader="vendor/bin/.phpunit/phpunit-8.3.5-0/vendor/autoload.php"
>
```

This has been working perfectly for over a year, however one of the testing bundles we're using ([LiipFunctionalTestBundle](https://github.com/liip/LiipFunctionalTestBundle)) recently made `phpunit/phpunit` a dependency, so we also have that installed in `/vendor` where we didn't have that before. My gut feel says this is some sort of problem with the autoloader and having phpunit installed twice, but I'm not sure.

**What I've tried**
1. Changing the `autoloader=` line `psalm.xml` so that it's not loading the `phpunit-bridge` version of phpunit and only the regular one, but the issue is still reported:

```xml
<psalm
        ...
        autoloader="vendor/autoload.php"
>
```

2. Removing `TestCase::logicalOr` and just using `TestCase:stringContains` (this returns a PHPUnit\Framework\Constraint\StringContains), now psalm does not report any errors:

```php
TestCase::assertThat(
    $this->getHtml(),
    TestCase::stringContains($expected, false)
);
```

3. Changing the `TestCase::logicalOr` to `TestCase::logicalAnd`, now it reports that `LogicalAnd` is undefined:

```php
TestCase::assertThat(
    $this->getHtml(),
    TestCase::logicalAnd(
        TestCase::stringContains($expected, false),
        TestCase::stringContains($htmlEncoded, false)
    )
);
```

It seems weird that `StringContains` is defined but `LogicalOr` and `LogicalAnd` are not.

**Comment by weirdan** [comment]
Have you tried dropping `autoloader` attribute completely? Psalm uses composer to locate classes automatically, and without triggering autoloader at all.

**Comment by ndench** [comment]
Good idea @weirdan, I gave it a shot but unfortunately the error is still reported.

**Comment by weirdan** [comment]
Does it help if you (temporarily) comment out [those four `class_alias` calls](https://github.com/symfony/phpunit-bridge/blob/master/bootstrap.php#L99-L102)?

**Comment by ndench** [comment]
Yep, that stops the error being reported. I'm not sure why that solves it though, is psalm reading and executing the `class_alias` calls?

**Comment by weirdan** [comment]
Reads and analyzes, yes. @muglug I'm not 100% sure, but to me it seems that `$this->skip_if_descendants` in `ReflectorVisitor` should be set at that point in code, but for some reason isn't. Shouldn't it be non-null for any complex `if` condition?

**Comment by muglug** [comment]
@weirdan @ndench I agree there's more it can do – I think my fix should be enough, I'll reopen if stuff is still broken.
