### ISSUE TITLE
Handling 'Cannot use uninitialized property' with PDO::FETCH_CLASS

### ISSUE THREAD

**Issue by theffernan-mphn** [vimeo/psalm#2382]
Hello,

I want to highlight a case where we are using the PDO to fetch database entries that have their properties injected by PDO outside of a constructor using PDO::FETCH_CLASS.

Example psalm INFO record: 
`Model\Area.php:84:13 - Cannot use uninitialized property $this->CreatedDate`

Issue being that as far as psalm can tell, the variable has not been initialized yet, but it actually has been from PDO setting up the class.

In the future is there a better way this should be handled or a way to inform psalm using docblocks of this?

**Comment by muglug** [comment]
Hey! Would you mind pasting the code that generates the issue?

**Comment by theffernan-mphn** [comment]
Hello, am currently using many layers of abstraction so it is slightly difficult to paste out for you, but here is a larger explanation:

```php
class Area
{
    /** @var int */
    public $ID;

    function __construct()
    {
        if ($this->ID !== null)
            settype($this->ID, "int");
    }
}

...
$connection = new \PDO(...);
$stmt = $connection->prepare($sql);
$stmt->setFetchMode(\PDO::FETCH_CLASS, Area::class);
$area = ($result = $stmt->fetch()) ? $result : null;
```

I am doing a check in my constructor for properties that have been injected by PDO and if i want to cast their type or not.

If there is a better way i should be doing this, id love to find out.

**Comment by weirdan** [comment]
I think you should be able to suppress this error with `@psalm-suppress` in the property docblock (but it doesn't work yet):
```php
class Area
{
    /** 
     * @var int
     * @psalm-suppress UninitializedProperty
     */
    public $ID;

    function __construct()
    {
        if ($this->ID !== null)
            settype($this->ID, "int");
    }
}
```

**Comment by muglug** [comment]
Instead I'd use `if (isset($this->ID))`, which now (as of 4052e6dfac18e6dbb052401b9e5dcc477e4d6215) suppresses that issue, both in the [docblock version](https://psalm.dev/r/746e5bac52) and the [typed property equivalent](https://psalm.dev/r/1a0599d50a).
