### ISSUE TITLE
Covariant type variable should not be allowed in non-covariant positions

### ISSUE THREAD

**Issue by arnaud-lb** [vimeo/psalm#2387]
### Snippet

https://psalm.dev/r/b2e620621f (generates a runtime error: https://3v4l.org/vdiqX)

### Expected output

```
ERROR: InvalidTemplateParam - 36 - Template param T of C is marked covariant and cannot be used as in invariant position in Reference<T>
ERROR: InvalidTemplateParam - 42 - Template param T of C is marked covariant and cannot be used as in invariant position in Reference<T>
```

### Actual output

No error

**Comment by muglug** [comment]
Yeah I think you’d model the same structure this way to catch the error in the call? https://psalm.dev/r/4b248ccb67
