### ISSUE TITLE
[3.7.0] InvalidArgument - Calling empty on a boolean value is almost certainly unintended

### ISSUE THREAD

**Issue by Jeckerson** [vimeo/psalm#2390]
Since version `3.7.0` appeared error, that in under question if it is really error.

Code:
```
if (!empty($arguments[$paramName]['have-option']) && $param == '') {
    throw new CommandsException("The parameter '$paramName' requires an option");
}
```

Error message:
> ERROR: InvalidArgument - src/Commands/Command.php:288:28 - Calling empty on a boolean value is almost certainly unintended

**Comment by muglug** [comment]
Would you mind pasting the preceding code? Or try to reproduce it on psalm.dev?

**Comment by muglug** [comment]
Closing because it's old
