### ISSUE TITLE
Check types of operators

### ISSUE THREAD

**Issue by nickyr** [vimeo/psalm#24]
Languages like Java don't allow mismatched types on either side of an operator. After discussing offline with @muglug, we think that to keep Psalm from being too obnoxious, there may need to be two different levels of this check.

**Looser level:**  
`'the number is ' + 12` is illegal
`'the number is ' . 12` is LEGAL
`1.5 + 2` is LEGAL

**Stricter level:**
`'the number is ' + 12` is illegal
`'the number is ' . 12` is illegal
`1.5 + 2` is illegal
`1.0 + 2.0` is LEGAL

The looser level could be in the default config.

An example of where the stricter level can catch a bug: Say you were adding money and you had `$price1 = 3.5` and `$price2_cents = 50`. Throwing an error if you did `$price1 + $price2_cents` would actually catch the bug since you shouldn’t be adding dollars and cents.

Psalm does not currently support varying levels of the same check, so the syntax for that in the XML will need to be determined.

**Comment by muglug** [comment]
@nickyr what about

```php
$a = '5';

if (is_numeric($a)) {
  return $a + 4;
}
```

I *think* that should be LEGAL in the looser level, and illegal in the stricter.

**Comment by nickyr** [comment]
I agree!
