### ISSUE TITLE
3.7 - Cannot use string as callable for call_user_func_array

### ISSUE THREAD

**Issue by othercorey** [vimeo/psalm#2401]
https://psalm.dev/r/b0875ce98c

We get this error now when using a string to build the callable:
> Argument 1 of call_user_func_array expects callable, string provided

```
     * @param string $name Method name.
     * @param array $arguments Method argument.
     * @return mixed
     */
    public static function __callStatic($name, $arguments)
    {
        return call_user_func_array('\Cake\Mailer\Mailer::' . $name, $arguments);
    }
```

I think this was changed with https://github.com/vimeo/psalm/issues/2380. I see the type for callable changed from string to literal.

**Comment by othercorey** [comment]
We can resolve this with:

```
call_user_func_array([Mailer::class, $name]
```

**Comment by muglug** [comment]
While I did mean to remove the ability to pass a `string` to a function that expects a `callable`, I should have allowed a `callable-string` (which previously worked, as it's a subtype of `string`). In  latest master you can also now use an `is_callable` check and then it'll work: https://psalm.dev/r/98b7ead847

But mostly I recommend `[Mailer::class, $name]` as a preferable alternative.
