### ISSUE TITLE
Cannot recognize type in Doctrine ArrayCollection

### ISSUE THREAD

**Issue by snapshotpl** [vimeo/psalm#2403]
https://psalm.dev/r/537b4435f3

I would expects that default array in collection is typed as declared in property.

**Comment by muglug** [comment]
This is not a bug - you have to use a `@var` docblock annotation: https://psalm.dev/r/fbfbd21fdd

If this were supported by the language you'd write something like

```php
$this->variantItems = new ListCollection<string>();
```

(I changed the name of the collection to match the `add` method behaviour)

**Comment by snapshotpl** [comment]
Right! Works like charm, thanks!

**Comment by snapshotpl** [comment]
However this `@var` format is not correct. I needed to make:
```
/** @var ArrayCollection<int, Item> $item */
$items = new ArrayCollection();
```

**Comment by muglug** [comment]
yeah, the example I gave was specific to the amended code I used
