### ISSUE TITLE
False positive with PHP 7.4 / PropertyNotSetInConstructor and MissingConstructor 

### ISSUE THREAD

**Issue by CodeDuck42** [vimeo/psalm#2405]
Both cases should be identical:

~~~php
class Foo
{
    /** @var int|null */
    public $bar;
}
~~~

~~~php
class Foo
{
    public ?int $bar;
}
~~~

The later produces the following error:
ERROR: MissingConstructor - src/Foo.php:5:17 - Test has an uninitialized variable $this->bar, but no constructor
    public ?int $bar;

**Comment by muglug** [comment]
No, PHP treats them differently! In the latter case, not assigning to null (either as a property default or in the constructor) will result in a fatal error if you access the property. In the former case it’s fine.
