### ISSUE TITLE
template-covariant doesn't work for return types anymore

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#2411]
https://psalm.dev/r/863d97518c

```php
<?php  

/**
 * @template-covariant T
 */
interface I
{
    /** @psalm-return T[] */
    public function foo(): array;
}
```

**Expected:** no issues
**Actual:** ERROR: InvalidTemplateParam - 8:23 - Template param T of I is marked covariant and cannot be used here

**Comment by muglug** [comment]
This was added for object collections, but should work on arrays as they're copy-on-write.

**Comment by someniatko** [comment]
@muglug same with iterable
https://psalm.dev/r/5e1a37c2ec

**Comment by muglug** [comment]
`iterable` is slightly different, I think, as it can represent typed collections. See https://psalm.dev/r/b2e620621f for an example.

**Comment by someniatko** [comment]
@muglug i think you are not right.

iterable = `Traversable|array`

For `array` you allow this behavior, for `Traversable` as well, however for `Traversable|array` suddenly not.

**Comment by someniatko** [comment]
BTW, in C# lang there is `IEnumerable<T>` interface, which is covariant, and it is something like iterable in PHP (because arrays are also IEnumerable).
There is also `IList<T> extends IEnumerable<T>`, and IList is NOT covariant. No contradiction here.

**Comment by someniatko** [comment]
both array and Traversable (and therefore, iterable) only RETURN some values, not operate on them.

Of course, if we extend/implement Traversable interface and also add some functionality like `add(T $item)`, this extending interface or implementing class must not be covariant anymore. However if we USE it as iterable, we CAN use it as covariant, because we have no possibility of accessing add() method (it's will be prohibited by psalm)

**Comment by someniatko** [comment]
@muglug should I open another issue for iterable, regarding notes above?
