### ISSUE TITLE
Support for "banned" calls in Psalm?

### ISSUE THREAD

**Issue by afbarbaro** [vimeo/psalm#2414]
Hi, we've recently implemented Psalm on our CI pipeline and came across a use case where we could use a feature that detects of unallowed/banned/forbidden methods.  Something similar to what PHPStan has with this [extension:](https://github.com/ekino/phpstan-banned-code).

Is this something valuable for Psalm? Could it be easily introduced?

Thanks!

**Comment by muglug** [comment]
Psalm currently forbids `shell_exec` and `var_dump` by default.

You can also use a `<forbiddenFunctions>` config to list things Psalm shouldn’t allow: https://github.com/vimeo/psalm/blob/c97ba8f7135aa23cfe5800f216c9a11c4d7e2c29/tests/Config/ConfigTest.php#L1006-L1008

Should it forbid more functions by default?

**Comment by afbarbaro** [comment]
Ah!

> Psalm currently forbids `shell_exec` and `var_dump` by default.
> 
> You can also use a `<forbiddenFunctions>` config to list things Psalm shouldn’t allow:
> 
> https://github.com/vimeo/psalm/blob/c97ba8f7135aa23cfe5800f216c9a11c4d7e2c29/tests/Config/ConfigTest.php#L1006-L1008
> 
> Should it forbid more functions by default?

Awesome, this `forbiddenFunctions` the exact functionality we would need.  We want to block some invocations of our own code 😬or at least force implementors to add a `@psalm-suppress` block justifying the call.  Is `@psalm-suppress supported` for overriding this error?

**Comment by muglug** [comment]
Yes!
