### ISSUE TITLE
Uncaught UnexpectedValueException: Cannot get method params for DOMDocument

### ISSUE THREAD

**Issue by chrisgraham** [vimeo/psalm#2421]
I got this on Symfony, and also a use of `DOMDocument` in my own project. However, I do not get it when analyzing standalone files, or even the whole of Symfony as a project.

```
Analyzing /var/www/html/composr/vendor/symfony/console/Descriptor/XmlDescriptor.php

Fatal error: Uncaught UnexpectedValueException: Cannot get method params for DOMDocument::__construct in /var/www/html/composr/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php:433
Stack trace:
#0 /var/www/html/composr/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php(260): Psalm\Internal\Codebase\Methods->getMethodParams('DOMDocument::__...', Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Object(Psalm\Context))
#1 /var/www/html/composr/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php(391): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkMethodArgs('DOMDocument::__...', Array, Object(Psalm\Internal\Type\TemplateResult), Object(Psalm\Context), Object(Psalm\CodeLocation), Object(Psalm\Internal\Analyzer\StatementsAnalyzer))
#2 /var/www/html/composr/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(417): Psalm\Internal\Analyzer\Statements\Expression\Call\NewAnalyzer::analyze(Object( in /var/www/html/composr/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php on line 433
```

**Comment by muglug** [comment]
Hey! First, thanks for using Vimeo APIs back in the day!

Why are you analysing files in `vendor`? That’s not something I'd recommend.

**Comment by muglug** [comment]
Is there any chance of me reproducing the issue?

**Comment by chrisgraham** [comment]
I tried to create a reproduction case by copying my repository and deleting some completely unrelated files to see if I could whittle it down - but the error went away.

Looking at the stack trace doesn't help me much. My guess is your doing something non-linear that is breaking normal exception flow. But you'd know better than me, and I can't afford to plow hours into this.

**Comment by chrisgraham** [comment]
> Hey! First, thanks for using Vimeo APIs back in the day!
> 
> Why are you analysing files in `vendor`? That’s not something I'd recommend.

I'm just trying out your tool, not doing anything serious. But remember I got the error on one of my own files too.
