### ISSUE TITLE
EmptyArrayAccess on global array

### ISSUE THREAD

**Issue by xPaw** [vimeo/psalm#2424]
https://psalm.dev/r/055aa13a11

Running the example code correctly produces `first\nsecond`. Looks like psalm is unable to track modifications to a global array. As a result it is also unable to determine the return type.

Not to mention the error appears on a line inside of an `isset` check.

---
Changing it to a class and removing global, it looks like it is still unable to determine the return type: https://psalm.dev/r/beea63ceeb

**Comment by muglug** [comment]
> Changing it to a class and removing global, it looks like it is still unable to determine the return type: https://psalm.dev/r/beea63ceeb

You can fix that by adding a property type: https://psalm.dev/r/ec40ea3409

**Comment by weirdan** [comment]
> You can fix that by adding a property type: https://psalm.dev/r/ec40ea3409

That works for global too: https://psalm.dev/r/cfd303b24e

**Comment by weirdan** [comment]
The case with untyped global probably cannot be inferred, as global may be modified outside that function - say by including that file, changing the global value and then calling that function.

**Comment by muglug** [comment]
Yeah, going to close this
