### ISSUE TITLE
Assignment in expressions not fully supported

### ISSUE THREAD

**Issue by ShiraNai7** [vimeo/psalm#2426]
https://psalm.dev/r/10f4f6860b

While not pretty, the code runs fine and doesn't crash. Are assignments in expressions supported only partially?

Changing `$value` from `mixed` to a `string` produces different errors: 
- https://psalm.dev/r/908a3073f2

Using a new variable name instead of overwriting `$value` prevents most errors, but not all:
- https://psalm.dev/r/b4c5673df4
- https://psalm.dev/r/67ec477a21

**Comment by muglug** [comment]
Yeah, the nested equivalent also works: https://psalm.dev/r/c4c7903340

**Comment by muglug** [comment]
Current work: https://github.com/vimeo/psalm/compare/fix-binaryop-handling

**Comment by muglug** [comment]
OK, so I realise I haven't solved most of this, but having spent a good chunk of time on this over the last three days, I've gone as far as I'm able (for now).

I hope to do a bit more tomorrow to get rid of the mixed var issues, though.

**Comment by muglug** [comment]
Mixed var issues for the `and` examples are now fixed.

**Comment by muglug** [comment]
I've made a couple more improvements so that most examples now work.

**Comment by ShiraNai7** [comment]
Thanks!

**Comment by muglug** [comment]
All examples here now work
