### ISSUE TITLE
goto is not supported

### ISSUE THREAD

**Issue by xPaw** [vimeo/psalm#2428]
I don't know if `goto` can be supported, but I don't see anything about in the documentation or any issues about it.

Example: https://psalm.dev/r/5db8b74528
Running the code outputs `beforeGoto` but psalm thinks the variable is `string(afterGoto)`

**Comment by muglug** [comment]
Yeah, not going to support this, sorry.

**Comment by xPaw** [comment]
Perhaps this warrants a documentation update?
