### ISSUE TITLE
Fix the documentation for spread operator in callables

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#2429]
https://psalm.dev/r/bbb6cbb5c5

**Comment by vudaltsov** [comment]
Why is it an enhancement? This feature is mentioned in the documentation: https://psalm.dev/docs/annotating_code/type_syntax/callable_types/

**Comment by muglug** [comment]
Ah crap, the documentation is wrong – the syntax as discussed in the original issue had `...` as a suffix, not prefix.

**Comment by vudaltsov** [comment]
It works this way, thanx! https://psalm.dev/r/9d40ba643b

**Comment by muglug** [comment]
I've also now just supported that syntax (but your docs change is still good)
