### ISSUE TITLE
Invalid return type `BaseType` for templated class with `T of BaseType`

### ISSUE THREAD

**Issue by tux-rampage** [vimeo/psalm#2433]
I'm not sure if this is really a bug or I'm missing something. 

The following code sample errors: https://psalm.dev/r/601d0d3a8c
It says that `The type 'Bar' does not match the declared return type 'T:Foo as Bar'`. To me this reads like `Bar` does not match `Bar` which looks like an analysis error to me.

Maybe you can shed some light.

**Comment by muglug** [comment]
Not a bug (but also not something that’s easily solvable). You’re declaring the function to return `T as Bar` but you’re only returning `Bar` (so a less-specific version). You could add `@return static` to the method in Bar, but that creates a different, more subtle issue.

**Comment by tux-rampage** [comment]
But how is `Bar` less specific than `Bar`?
Maybe I'm too spoiled by TypeScript (where this is fully valid), but I don't get it.

**Comment by weirdan** [comment]
> But how is `Bar` less specific than `Bar`?

Not `Bar`, but `T as Bar`. Suppose there's a `class C extends Bar {}`. When you instantiate `new Foo(C::class)` the resulting object's `barFromUpstreamValue()` has to return `C` (because of `@return T`). But there's no guarantee `C::fromString()` will return `C`. Its contract allows it to return any other descendant of `Bar`.

**Comment by tux-rampage** [comment]
Ah I see. Thanks for taking the time to explain this.

I totally ignored that covariant return types did not exist before 7.4 and the following was not possible:

```php

class A
{
    public static function factory(): self
    {
        return new A();
    }
}

class B extends A
{
    public static function factory(): self
    {
        return new B();
    }
}
```

In theory the analysis could ensure that the Generic is only used with compatible types, like this (please correct me if I'm wrong):

```php
// Given classes A and B from the example above

class C extends A
{
    public static  function factory(): A
    {
        return new C();
    }
}

/** 
 * @template T of A
 */
class Test
{
    /** @var class-string<T> */
    private string $t;

    /** @psalm-param class-string<T> $t */
    public function __construct(string $t)
    {
        $this->t = $t;
    }

    /** @psalm-return T */
    public function someMethod(): A
    {
        return ($this->class)::factory();
    }
}

new Test(A::class); // ok
new Test(B::class); // ok
new Test(C::class); // type error
```

But this is indeed not trivial to implement (might even be impossible). Would you potentially accept a feature PR in this direction or do you think it's not worth to invest any time into that? At the moment this is an edge case for me that I can get around with, but I'm not sure if there are other use cases affected.

Thanks again for your valuable feedback and if course for this great tool.

**Comment by weirdan** [comment]
I think in practice you want to just add `/** @return static */` on `A::factory()`, which will make this implementation of `C` invalid in its own right. I think Psalm should also be able to use (but currently cant, gonna file a separate issue for that) that return type when typechecking generics.
