### ISSUE TITLE
Return value of get_class() should be treated as class-string instead of string

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#2438]
https://psalm.dev/r/f9eb5dc177

**Comment by weirdan** [comment]
It is treated as `class-string`: https://psalm.dev/r/8c6995bde3
But it should be reported as a constructor call on unknown class.

**Comment by ShiraNai7** [comment]
There are more issues with `get_class()` when called without an argument or used in static calls: https://psalm.dev/r/83af0a5540

**Comment by muglug** [comment]
So what's actually happening here is that there are two types: `TClassString` (which is the type created for `class-string` docblocks) and `GetClassT`, which is a dependent type created from the use of `get_class($foo)`, useful when analysing switch statements.

Thanks @ShiraNai7 for the exhaustive tests!
