### ISSUE TITLE
loosing types after uasort

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2440]
Hi,

It seems that calling uasort on an array is making it loose some details on its type.

For this code:
https://psalm.dev/r/0f9f06ebd6

I get errors on the following foreach() saying that the content of the array is mixed but when I delete the uasort block:
https://psalm.dev/r/b105428308

Everything is fine.

Contrary to usort, uasort do not mess with array keys and using it shouldn't change the type of a variable.

Thanks for your amazing work!

**Comment by orklah** [comment]
Thanks!

**Comment by weirdan** [comment]
@muglug should it still complain about `$a['time']` being possibly undefined in the closure? I think `array_map()` doesn't require explicit annotations on closure params, so I was under impression it would be the same. Or does getting rid of that require more than just a stub definition?
