### ISSUE TITLE
`mixed` assignment: allow it when immediately followed by an assertion?

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2442]
Taking https://psalm.dev/r/d2fb7dd6cc as an example:

```
<?php

/** @var int $foo */
$foo = eval('nobody cares');
$bar = eval('nobody cares');
assert(is_int($bar));
```

This code produces following output:

```
Psalm output (using commit 517aaac):

INFO: MixedAssignment - 5:1 - Cannot assign $bar to a mixed type
```

That's fine under current psalm constraints, but I'm wondering if this could be relaxed to allow `$bar` to be in `mixed` state if followed by a type assertion **before** it is used in any expression.

Specifically, I'm moving all my existing code from relying on `/** @var Type $var */` to `assert($var instanceof Type);`, and obviously the tooling refuses to accept that.

For reference: https://github.com/doctrine/coding-standard/pull/47

**Comment by muglug** [comment]
> That's fine under current psalm constraints, but I'm wondering if this could be relaxed to allow $bar to be in mixed state if followed by a type assertion before it is used in any expression.

I think you're basically just asking to suppress all `MixedAssignment` warnings, right? That can be done via the config.

Otherwise, this is a wontfix – it would require far too much extra work.

**Comment by Ocramius** [comment]
The idea is to have the same rules of `/** @var Foo $foo */` apply also to `assert($foo instanceof Foo);` when the assertion is immediately following the first declaration of the variable.

Alternatively, the rule could be "variable never used before assertion".

This would make the strictly typed mode of psalm usable with layers such as json decoding (and upcasting), which are currently in direct conflict with assertions and `/* @var */` (the consider each other redundant):

```php
/** @var list<int> $a */ // can't remove this due to mixed assignment rule
$a = json_decode($b);

Assert::isList($a); // detected as redundant, but strictly required by runtime invariants
```

In the code above, the correct modus operandi is to only have the assertion, since removing that is leading to a Security issue.

**Comment by weirdan** [comment]
I think the code above should rather use `@var mixed`: https://psalm.dev/r/1d472201d1

**Comment by Ocramius** [comment]
Yeah, I'm saying that's redundant/skippable, since `mixed` is the inferred type
