### ISSUE TITLE
InvalidScope cannot be suppressed with config

### ISSUE THREAD

**Issue by mishfish** [vimeo/psalm#2444]
Try 
`    <issueHandlers>
        <InvalidScope errorLevel="suppress" />
`

or

`
    <issueHandlers>
        < InvalidScope >
            <errorLevel type="suppress">
                <directory name="src"/>
            </errorLevel>
        < InvalidScope >
`

and have 

> ERROR: InvalidScope - Invalid reference to $this in a non-class context

For another issues types all work fine.

Psalm 3.6.6@5e17a9af104de39321c47f73b253cece9df1cf2c

**Comment by mishfish** [comment]
Look like 
https://github.com/vimeo/psalm/issues/2032
must work for me

**Comment by muglug** [comment]
@mishfish are you able to reproduce this in a separate repo?

**Comment by mishfish** [comment]
@muglug I've try to reproduce this separately and didn't get this trouble.
This is probably trouble with my code.
Solve my problem with 
`<?php
/** @psalm-scope-this Foo\Bar\Baz */
?>`
Sorry, close the issue.
