### ISSUE TITLE
Error with classes extending doctrine/collections ArrayCollection since psalm 3.6.6

### ISSUE THREAD

**Issue by sspat** [vimeo/psalm#2445]
Since the changes introduced in Psalm in this commit, released in 3.6.6: https://github.com/vimeo/psalm/commit/7012bedf4e2d2cad676ce9191ab31408a82619c2

When I extend the `ArrayCollection` class of doctrine/collections and use the `filter` method of the extended class, I get the following error:
```
ERROR: TooManyTemplateParams - src\class.php - Class has too many template params, expecting 0
```

More than that, I could not reproduce it in the psalm sandbox on psalm.dev, as it seems to be happening only when the classes are in different namespaces.

I created a minimal reproduction in a separate repository.
https://github.com/sspat/psalm-doctrine-collections-test
Also posted this issue to doctrine/collections:
https://github.com/doctrine/collections/issues/223

**Comment by muglug** [comment]
I'm unable to reproduce it here in a different namespace: https://psalm.dev/r/24632d0755

**Comment by sspat** [comment]
Yes, I tried that too. Only way I can reproduce is by including the actual collections package. Maybe the code needs to be in separate files also.

**Comment by muglug** [comment]
Ok, sorry, will try to reproduce more properly

**Comment by muglug** [comment]
As to why it doesn’t fail on psalm.dev, it's due to this code: https://github.com/vimeo/psalm/commit/864d242f1#diff-277ec424419f1cefc295033a518a7397R319-R323
