### ISSUE TITLE
query re: redundant condition / unreachable code

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2446]
https://psalm.dev/r/cf37b71a1f
```php
<?php

function foo() : string {
  if (true) {
    return 'foo';
  } elseif (true) {
    return 'bar';
  }
  
  return 'baz';
}
```

The `return 'bar';` and `return 'baz';` branches are unreachable, because the first condition is always true, so both the `elseif` and final return statements might need flagging?

**Comment by muglug** [comment]
I think `if (true)`/`if (false)` is rare _enough_ that I'm not going to add support for it – when that construct is used, it's normally on purpose (and it's very easy to search your codebase for `if (true)`)

**Comment by SignpostMarv** [comment]
@muglug this was a more general thing of conditions being repeated in different branches of a set of conditions- where it's either hardcoded true/false values left in for debugging, identical truthy functions, or consts.

i.e.

```php
if (preg_match('/foo/', $_SERVER['REQUEST_URI'])) {
// stuff
} elseif (preg_match('/foo/', $_SERVER['REQUEST_URI'])) {
// different stuff
}
```

regardless of what the function arguments are, for a built-in function like this, the truthiness should always be identical, so either both branches would never be reached or only the first one would be reached.
