### ISSUE TITLE
Allow typing things as `scalar&!empty`?

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2449]
While trying to refine type annotations for `webmozart/assert`, I noticed that it is not currently possible to use intersection types together with the `empty` construct.

My attempt was to add `@psalm-assert string&!empty` (as an example), as well as other combinations of `empty` and `!empty`, but the `empty` and `!empty` types seem to only be parsed when in a standalone context, and not in union/intersection types.

**Comment by muglug** [comment]
Intersections of assertions should just be represented as separate `@psalm-assert` annotations:

```php
/**
 * @param mixed $value
 * @psalm-assert scalar $value
 * @psalm-assert !empty $value
 */
function assertScalarNotEmpty($value) : void {}
```

That doesn't _quite_ work in the current Psalm release, but I've just fixed things so it should:

https://psalm.dev/r/4892c18ffb

**Comment by Ocramius** [comment]
> That doesn't *quite8 work in the current Psalm release, but I've just fixed things so it should:

I missed this detail: will do another iteration on `webmozart/assert` after these are through in a release :+1:
