### ISSUE TITLE
Unable to run --init

### ISSUE THREAD

**Issue by ErikBooij** [vimeo/psalm#245]
I was following the documentation in README.md and ran `./vendor/bin/psalm --init`, it yielded the following error:

```
The given path "/path/to/my/project/--ansi" does not appear to be a directory
```

Then I viewed the help and saw I needed to pass a directory, so I tried:

`./vendor/bin/psalm --init src`

But I still got an error:

```
Config strictness must be a number between 1 and 5 inclusive
```

So I tried:

`./vendor/bin/psalm --init src  3`
`./vendor/bin/psalm --init src --level 3`
`./vendor/bin/psalm --init src --level=3`

But all gave me the error:

```
Too many arguments provided for psalm --init
```

Now I have no idea anymore how to initialize it. I'm probably just interpreting the help wrong, but in that case, maybe it (and README.md) needs a little improvement.

**Comment by weirdan** [comment]
It should be fixed in #244
Meanwhile you can disable xdebug (by commenting out `zend_extension=xdebug.so` line in php.ini or included files) to work around this problem.

**Comment by muglug** [comment]
Yup, fixed in `dev-master`.

**Comment by muglug** [comment]
I've tagged a new release (0.3.58) that should be available in composer momentarily.

**Comment by ErikBooij** [comment]
Damn, that was quick, awesome guys! :+1:
