### ISSUE TITLE
`non-empty-list` type assertions are incorrectly considered redundant when `list` is encountered

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2450]
While refining type declarations for `webmozart/assert`, I found that psalm considers `non-empty-list` to be a redundant condition on top of `list` or `array`: https://psalm.dev/r/e8ec0750f5

```php
<?php

/** 
 * @psalm-assert non-empty-list $v
 * @psalm-param mixed $v
 */
function assertNonEmptyList($v):void {}

/** @psalm-param array<int> $v */
function firstElement($v) : int
{
    assertNonEmptyList($v);
    return $v[0];
}
```

```
Psalm output (using commit 74de32f):

INFO: UnusedParam - 7:29 - Param $v is never referenced in this method

ERROR: RedundantConditionGivenDocblockType - 12:5 - Found a redundant condition when evaluating docblock-defined type $v and trying to reconcile type 'array<array-key, int>' to non-empty-list<mixed>

INFO: PossiblyUndefinedIntArrayOffset - 13:12 - Possibly undefined array offset 'int(0)' is risky given expected type 'array-key'. Consider using isset beforehand.
```

Also seems that `non-empty-list` doesn't implicitly have key `0`.

**Comment by muglug** [comment]
As with #2449, the best option here is for separate `@psalm-assert` calls:

https://psalm.dev/r/4228415ada

**Comment by Ocramius** [comment]
Hmm, I think I'm hitting a different bug with `webmozart/assert` then. If I **add** `@psalm-assert !empty` to `Assert::stringNotEmpty()`, then type inference fails to restrict the type to `string`.

I can't seem to isolate through `psalm.dev` though.

This happens if I use the suggested approach from #2449 in following code location:

https://github.com/Ocramius/assert-1/blob/ea5e87e60c1a4e643d063c29a570daa7f5f8a022/src/Assert.php#L221-L233

This static analysis verification file will no longer pass:

https://github.com/Ocramius/assert-1/blob/ea5e87e60c1a4e643d063c29a570daa7f5f8a022/tests/static-analysis/assert-stringNotEmpty.php#L7-L15

**Comment by Ocramius** [comment]
Note: comment above may be due to https://github.com/vimeo/psalm/issues/2449#issuecomment-563481384

**Comment by muglug** [comment]
Yeah part of the fix was to allow multiple `@psalm-assert` for a given variable.
