### ISSUE TITLE
`@psalm-assert` type assertions seem to ignore `callable():T` types

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2451]
While refining type assertions for `webmozart/assert`, I noticed that type assertions around callables/closure signatures seem to get ignored.

https://psalm.dev/r/900c79479b

```php
<?php

/** @psalm-assert callable(): object $v */
function assertFactory(callable $v) : void {}

function useFactory(callable $factory):object
{
    assertFactory($factory);
    return $factory();
}
```

```
Psalm output (using commit c8d8244):

INFO: UnusedParam - 4:33 - Param $v is never referenced in this method

ERROR: RedundantCondition - 8:5 - Found a redundant condition when evaluating $factory and trying to reconcile type 'callable' to callable():object

INFO: MixedReturnStatement - 9:12 - Could not infer a return type

INFO: MixedInferredReturnType - 6:40 - Could not verify return type 'object' for useFactory
```

Note: similar behavior happens with `@psalm-assert something<T>`, where `T` may be a complex array structure - the `array` structure is ignored, and `T` is inferred as `mixed[]`.

**Comment by Ocramius** [comment]
I'm adding them myself, hence why I'm discovering all these crazy scenarios.

Specifically, I tried to add assertions so that `Assert::throws($closure)` verifies that `@psalm-assert callable(): never-return $clousure` (or something similar).

The `@psalm-assert` works, but it ignores the return type.

**Comment by muglug** [comment]
How can you assert that a closure always throws without using static analysis?

**Comment by Ocramius** [comment]
TBH, I didn't quite think that through: I was mostly documenting existing behavior:

https://github.com/webmozart/assert/blob/a74981fecc0337dabe75461d9b33bac38a77f2f2/src/Assert.php#L1777-L1809

**Comment by muglug** [comment]
But that’s dodgy - it only asserts that the closure throws when called without arguments.

Which is to say, that this is essentially unknowable so I won’t be adding support for those assertions.
