### ISSUE TITLE
Type-assertions seem to be ignoring union types

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2452]
Rationale behind this issue:

 * `filter_var()` works with both `object`s implementing `#__toString()` and `string`.
 * In the discussion at https://github.com/webmozart/assert/pull/160#discussion_r355964035 and https://github.com/webmozart/assert/pull/160#discussion_r355965110, we identified that assertions performing `filter_var()` or `ctype_*` checks do work with mixed/union types (because dammit, PHP!).
 * The closest type declarations for assertions with `filter_var()` and `ctype_*()` I could use so far are `string|object` or `string|int`.

In https://psalm.dev/r/57e37c2c68:

```php
<?php
  
/** 
 * @param mixed $v
 * @psalm-assert string|object $v
 */
function assertStringOrObject($v) : void {
  assert(is_string($v) || is_object($v));
}

function gimmeAString(?string $v): string {
  assertStringOrObject($v);
  
  return $v;
}

function gimmeAnObject(?object $v): object {
  assertStringOrObject($v);
  
  return $v;
}
```
```
Psalm output (using commit 8494f02):

ERROR: TypeDoesNotContainType - 12:3 - Found a contradiction when evaluating $v and trying to reconcile type 'null|string' to object

INFO: MixedReturnStatement - 14:10 - Could not infer a return type

INFO: MixedInferredReturnType - 11:36 - Could not verify return type 'string' for gimmeAString
```

It seems like psalm bails out when trying to constrain a type assertion to a union type. Note that this is also true for `int|string` (https://psalm.dev/r/ce839325be).

**Comment by muglug** [comment]
It's problematic because Psalm handles the assert annotations like it would the equivalent code: https://psalm.dev/r/e27d09a815

It's also pretty trivial for me to change this behaviour, I think.

**Comment by muglug** [comment]
Yeah, as a far as I'm concerned this behaviour is internally consistent (with replacing the assert-function calls with the actual assertions) so I'm not going to fix.

**Comment by muglug** [comment]
Small update: assertions will still generate a Psalm error, but after 750d4b4f4f79fdd8441dbcc2101aab4f8347a743 Psalm is now smarter about the resultant type (so the mixed errors in your example have disappeared).

**Comment by Ocramius** [comment]
So, if I understand this correctly, psalm (as an implementation detail), inlines:

```php
/** @psalm-assert foo|bar $v */
function assertSomething($v):void{}
```

as

```php
assert($v instanceof foo || $v instanceof $bar);
```

The problem with this is that the implementation detail will indeed lead to a redundant expression detection, and that's unavoidable. Isn't there a way to render the inline replacement opaque to the engine, so that the operation is atomic enough to not be considered redundant?

**Comment by muglug** [comment]
> Isn't there a way to render the inline replacement opaque to the engine, so that the operation is atomic enough to not be considered redundant?

There's always _a way_, but I'm not sure it's worth implementing for the inconsistency I think it brings.

But also for your examples above, any `Assert::ip` example on an object assumes the `__toString` method is pure, and that's not particularly sound either.

**Comment by Ocramius** [comment]
> But also for your examples above, any `Assert::ip` example on an object assumes the `__toString` method is pure, and that's not particularly sound either.

Anything calling `__toString()` has been removed the `@psalm-pure` tag there.

**Comment by muglug** [comment]
I could support `@psalm-assert stringable`, but it wouldn’t be backwards-compatible.

**Comment by Ocramius** [comment]
> but it wouldn’t be backwards-compatible.

Adding `@psalm-assert stringable` could work, if you think it is a sensible type to have. The issue still stands for `@psalm-assert int|string` though, so I think it's fixing a symptom there.

I'm also OK with *not* adding type assertions for some of the discovered stuff: as I mentioned on slack, I'm mostly pushing the boundaries.
