### ISSUE TITLE
Unexpected InvalidDocblock if use default array value for array parameter in magic method docblock

### ISSUE THREAD

**Issue by vadim2991** [vimeo/psalm#2455]
```php
<?php

/**
 * @method array randomElements(array $array = array(1,2,3))
 */
class Foo
{
    /**
     * @param string $method
     * @param array $attributes
     *
     * @return mixed
     */
    public function __call($method, $attributes)
    {
        return [];
    }
}
```
https://psalm.dev/r/3a9834b40d
Expected: No issues
Actual:
ERROR: InvalidDocblock - 6:7 - randomElements(array $array=array(1,2,3) is not a valid method in docblock for Foo

This docblock is used in Faker https://github.com/fzaninotto/Faker/blob/master/src/Faker/Generator.php#L147

**Comment by Ocramius** [comment]
@vadim2991 seems like the parsing stops inside the declared array as default parameter:

https://psalm.dev/r/a22229878b

```php
<?php

/**
 * @method foo($a = [])
 * @method bar($a = [1, 2])
 */
class A
{
}
```

```
Psalm output (using commit af52590):

ERROR: InvalidDocblock - 7:7 - bar($a=[1,2]) is not a valid method in docblock for A
```
