### ISSUE TITLE
`@psalm-pure`, `: void` methods (assertions) and exceptions

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2456]
Further follow-up from work being done to improve `webmozart/assert` @ https://github.com/webmozart/assert/pull/160#issuecomment-564491986

`@psalm-pure` doesn't seem to play well with `:void` expressions. There are a few things weird about the following code (https://psalm.dev/r/e34695a167): 

```php
<?php

/** @psalm-pure */
function stopOn1(int $v):void
{
  if ($v === 1) {
    throw new \RuntimeException();
  }
}

stopOn1(1);
stopOn1(2);
stopOn1(3);
```

```
Psalm output (using commit af52590):

ERROR: UnusedFunctionCall - 11:1 - The call to stopon1 is not used

ERROR: UnusedFunctionCall - 12:1 - The call to stopon1 is not used

ERROR: UnusedFunctionCall - 13:1 - The call to stopon1 is not used
```

Specifically:

 * the `new \RuntimeException()` constructor is not `@psalm-pure`: I think this was discussed before with @weirdan (#2160)
 * the function return value is expected to be used, but this function's only purpose is to throw

I think this is connected with https://github.com/vimeo/psalm/issues/2160#issuecomment-533843789: thrown values are not considered function output.

Few possible resolutions:

 * ignore `UnusedFunctionCall` if that result is `void`
 * consider exceptions as return signature in all callers (this sounds like a mess, as it changes basic assumptions about the type system)

**Comment by muglug** [comment]
What if we ignore `UnusedFunctionCall` when the function has `@psalm-assert`?

**Comment by weirdan** [comment]
To me, `:void` indicates the return value should not be used, so why should Psalm complain about unused return? Or am I misunderstanding the nature of `UnusedFunctionCall`?

**Comment by weirdan** [comment]
Oh, I think I get it now: pure functions should return values that are used, otherwise calls to them are deemed useless.

**Comment by Ocramius** [comment]
> What if we ignore `UnusedFunctionCall` when the function has `@psalm-assert`?

Seems reasonable.

**Comment by Ocramius** [comment]
Thanks @muglug! :tada:
