### ISSUE TITLE
Narrow immutable types if already asserted to be more narrow in current scope

### ISSUE THREAD

**Issue by dkarlovi** [vimeo/psalm#2460]
Basically this should IMO work: https://psalm.dev/r/51021a10bb

/cc @Ocramius @ostrolucky

**Comment by Ocramius** [comment]
To be specific, `@psalm-immutable` should lead to memoized method calls

**Comment by weirdan** [comment]
@Ocramius IMO `@psalm-immutable` does not preclude one from returning, say, random values. Perhaps you meant `@psalm-pure` - that should be memoizable.

**Comment by Ocramius** [comment]
@weirdan ah, correct: had to dig it up, but we discussed this in https://github.com/vimeo/psalm/issues/2138#issuecomment-533916958

**Comment by muglug** [comment]
I'm not sure about this. On the one hand, a dinky little feature. On the other, It leads to slightly slower code (method calls are slower than local variable lookups).

**Comment by muglug** [comment]
And `@psalm-immutable` _does_ preclude returning random values - it ensures that all instance methods are free of mutations: https://psalm.dev/r/3dd94738e5

**Comment by dkarlovi** [comment]
I agree it leads to slightly worse code, see discussion on Symfony's Slack.

But on the other hand, the current behaviour does seem like a false positive.
