### ISSUE TITLE
Cannot template object in ArrayCollection

### ISSUE THREAD

**Issue by snapshotpl** [vimeo/psalm#2463]
https://psalm.dev/r/5c340f7497

I get:
```
ERROR: InvalidArgument - 225:18 - Argument 1 of test::match expects ArrayCollection<array-key, object>, ArrayCollection<array-key, MyClass> provided
```

When change `ArrayCollection` to `IteratorAggregate` in `test` class then everything works smooth. Any idea?

**Comment by weirdan** [comment]
Trimmed down version: https://psalm.dev/r/36d52ca28f
```php
<?php
/**
 * @template TKey of array-key
 * @template T
 */
class ArrayCollection {}

class MyClass {}

class test { 
  /** @param ArrayCollection<array-key, MyClass> $col */
  public function __construct($col) {
    $this->match($col);
  }
  /**
   * @template T of object
   * @param ArrayCollection<array-key, T> $data
   */
  public function match($data): void {}
}
```
**Expected**: no issue, as `MyClass` is most definitely an object
**Actual**:
```
Psalm output (using commit 6ff312f):

ERROR: InvalidArgument - 13:18 - Argument 1 of test::match expects ArrayCollection<array-key, object>, ArrayCollection<array-key, MyClass> provided
```

**Comment by weirdan** [comment]
Actually `T` needs to be covariant for it to work: https://psalm.dev/r/2e7ec74e77 and there's no issue when it's defined as such.

**Comment by weirdan** [comment]
@snapshotpl see https://github.com/vimeo/psalm/blob/f36766bf99afe8ade8a3dc3b74aa6c721eba985d/src/Psalm/Internal/Stubs/CoreGenericClasses.php#L17 for why it worked with `IteratorAggregate`.

**Comment by snapshotpl** [comment]
@weirdan it's impossible to set `T` as covariant because this https://psalm.dev/r/b54d8120d2
