### ISSUE TITLE
Null coallesce operator supresses UndefinedVariable error

### ISSUE THREAD

**Issue by codyhatch** [vimeo/psalm#2464]
Example: https://psalm.dev/r/5e4835c5e9

Line 5 generates a `UndefinedVariable` error, but line 13 does not. It does generate a `MixedAssignment`, but that's only INFO level, is supressed if `totallyTyped` is set to false, and is fairly cryptic.

I just hit an issue where there was a method that looked like:

```
    public function __construct(string $url, array $config = [])
    {
        $use_proxy = $config['use_proxy'] ?? false;
        /* bunch of stuff */
    }
```

This got copy and pasted into a fairly similar class, but it had different parameters:

```
    public function __construct(string $wsdl, array $options = [])
    {
        $use_proxy = $config['use_proxy'] ?? false;
        /* bunch of stuff */
    }
```

The intended usage was to pass in a URL and an optional array of extra options, including an optional `use_proxy` flag which should default to false if not otherwise set.

And the error is pretty clear here - the second param was renamed from `$config` to `$options`, but the bit where we tried to retrieve the `use_proxy` flag was never updated.  Unfortunately, with `totallyTyped` false, Psalm is totally silent about this, and even with `totallyTyped` true it doesn't treat it with the seriousness I would have expected.

Is this a bug? Design decision? An option I haven't correctly set is Psalm?

FWIW, Phan [seems to catch this](https://phan.github.io/demo/?code=%3C%3Fphp%0A%0Afunction+foo%28%29%3A+void%0A%7B%0A++++%24do_baz+%3D+%24config%5B%27do_it%27%5D%3B%0A++++if+%28%24do_baz%29+%7B%0A++++++++baz%28%29%3B%0A++++%7D%0A%7D%0A%0Afunction+bar%28%29%3A+void%0A%7B%0A++++%24do_baz+%3D+%24config%5B%27do_it%27%5D+%3F%3F+false%3B%0A++++if+%28%24do_baz%29+%7B%0A++++++++baz%28%29%3B%0A++++%7D%0A%7D%0A%0Afunction+baz%28%29%3A+void%0A%7B%0A%7D).

**Comment by muglug** [comment]
It's a bug - the alternate version with `isset` is caught correctly: https://psalm.dev/r/c5a49fe2d9
