### ISSUE TITLE
Assertions on properties does not work when method called from another class

### ISSUE THREAD

**Issue by gmazzap** [vimeo/psalm#2466]
Consider the following code:

```php
class Foo
{
    private $arrayObject;

    public function __construct(?\ArrayObject $arrayObject)
    {
        $this->arrayObject = $arrayObject;
    }

    /**
     * @psalm-assert-if-true \ArrayObject $this->arrayObject
     */
    public function hasArray(): bool
    {
        return $this->arrayObject instanceof \ArrayObject;
    }

    public function toMaybeArray(): ?array
    {
        if ($this->hasArray()) {
            return $this->arrayObject->getArrayCopy();
        }

        return null;
    }
}

class Bar {

    private $foo;

    public function __construct(Foo $foo)
    {
        $this->foo = $foo;
    }

    public function toArray(): array
    {
        if ($this->foo->hasArray()) {
            return $this->foo->toMaybeArray();
        }

        return [];
    }
}
```

Psalm will raise an `InvalidNullableReturnType` and a `NullableReturnStatement` problems for the `Bar::toArray` method.

The reason is that `Foo::toMaybeArray()` has a nullable return type, whereas the `Bar::toArray` has not.

I thought that asserting that when `Foo::hasArray()`  returns `true`  then `Foo::$arrayObject` is not null, would have made Psalm understand that `Bar::toArray` can never return true, but I was wrong.

It worth noting how the assertion correctly works for `Foo::toMaybeArray()`, in fact, Psalm does not complain that `getArrayCopy()` is called on a possibly null value, however, it has no effect when `Foo::hasArray` is called from another class.

Is this something achievable?

**Comment by weirdan** [comment]
Yes, but the assertion has to change the type of the `Bar` itself, similar to this: https://psalm.dev/r/51a794d8e5

**Comment by weirdan** [comment]
I thinks this should work: https://psalm.dev/r/717c38af30 (but doesn't, as Psalm has issue with nullable templates).

@muglug is nullable template (`@template T as someType|null`) supposed to work?

**Comment by muglug** [comment]
> @muglug is nullable template (@template T as someType|null) supposed to work?

Yes, and now it does!

**Comment by muglug** [comment]
I think @weirdan's solution is great - will close this

**Comment by gmazzap** [comment]
Thanks
