### ISSUE TITLE
Socket/file functions not detected as possibly returning false

### ISSUE THREAD

**Issue by xPaw** [vimeo/psalm#2469]
https://psalm.dev/r/fec14f87c5

Both `stream_socket_client` and `fread` can return false, but psalm doesn't detect that. Most likely happens to other file/stream functions.

I'm not sure where Psalm gets the return types from.

**Comment by weirdan** [comment]
On psalm.dev you can turn on `Use strict internal function results` flag in snippet settings to show those issues: https://psalm.dev/r/b8a7120220
 
This flag corresponds to [`ignoreInternalFunctionNullReturn` and `ignoreInternalFunctionFalseReturn`](https://github.com/vimeo/psalm/blob/master/docs/running_psalm/configuration.md#ignoreinternalfunctionfalsereturn) attributes in `psalm.xml` which you probably want to turn off.

**Comment by muglug** [comment]
Oh, and if you think it’s a common-enough thing that those functions return false then I can add back checks in those cases. Some built in functions (like `strpos`) where a false return is common always have checks enforced, but others like `preg_replace` (where `false` return values are rare) do not.

**Comment by xPaw** [comment]
That would probably make sense for stream/file functions, yeah.

**Comment by muglug** [comment]
Mind making a PR to expand this list? https://github.com/vimeo/psalm/blob/1a92e98dd3e66af9ab638e65925705b6616a18be/src/Psalm/Internal/Analyzer/FunctionAnalyzer.php#L376-L388

**Comment by xPaw** [comment]
The list may get slightly big:
https://www.php.net/manual/en/ref.filesystem.php
https://www.php.net/manual/en/ref.stream.php
https://www.php.net/manual/en/ref.sockets.php

**Comment by muglug** [comment]
Big is fine. As long as it’s very common to check a given function’s return type for `false`, Psalm should require those checks. If `false` is only returned in situations where other languages would throw an exception (e.g. bad input, missing files) then I don’t think Psalm should enforce checks by default.
