### ISSUE TITLE
array_map should preserve non-emptiness

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#2472]
https://psalm.dev/r/c3ab0a2910
same as [this](https://github.com/vimeo/psalm/commit/441d3c4693de532fc4f2d1941c4797396d1441d9), I guess

**Comment by muglug** [comment]
Patched the fix in https://github.com/vimeo/psalm/commit/7cb021a26834630cfd21e7000c5ddd41761aff66
