### ISSUE TITLE
template-covariant return type doesn't work for array|Traversable or iterable

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#2475]
https://psalm.dev/r/95578e7d6b

**Expected:** Psalm finds no issues
**Actual:** `Traversable<T>` and `array<T>` return types are allowed, `array<T>|Traversable<T>` and `iterable<T>` are not.

@nikic I think this is very important question for future of PHP generics, era of which is for now preceded by psalm, is it valid to allow `iterable` (or `array|Traversable`) generic return type to be covariant?

**Comment by muglug** [comment]
I don't think we need to drag @nikic into something that's clearly just a bug on Psalm's part...

**Comment by someniatko** [comment]
@muglug oh, sorry, last time you had disagreed with me. https://github.com/vimeo/psalm/issues/2411

**Comment by muglug** [comment]
Yes I was wrong, and the example code you give in this ticket proves it. But still, not much use tagging someone who’s not involved in the project - generic param covariance is not a new concept, and if PHP implements it they likely will look to languages like Hack and C# with robust implementations in similar domains.
