### ISSUE TITLE
Assertions are not inherited

### ISSUE THREAD

**Issue by ShiraNai7** [vimeo/psalm#2477]
`@psalm-assert` is not resolved when used with `@implements` or `@extends`, but works fine with the original interface or abstract class.

- implements: https://psalm.dev/r/60b94827f0
- extends: https://psalm.dev/r/413ec5bbd0

Same thing happens with other assertion annotations, such as `@psalm-assert-if-true`: https://psalm.dev/r/12b8540f5d

**Comment by muglug** [comment]
Currently there's no logic for inheriting assertions e.g. https://psalm.dev/r/8d78a43a13

I don't think I'm going to support this, as 1) I'm lazy and 2) inheriting assertions from parent methods might lead to some weird situations that I haven't fully thought out.

For the moment I'm happy just to force everyone to redeclare assertions – if you want to create a PR for assertion inheritance I could readdress this down the line.
