### ISSUE TITLE
Psalm scans the whole project dir even if we specify some files

### ISSUE THREAD

**Issue by Taluu** [vimeo/psalm#2480]
Currently, it seems that if you have a `projectDir` config in your xml config, and if you want to run psalm only on a few files, all the files in the projectDir are scanned anyway.

If we specify files to scan (e.g through a git hook), then shouldn't psalm ignore / be smart on which files to scan in the project dir ? We currently have to make two configs, one with a project dir (when run with the "classic" `psalm`) and on without it (when run with a git hook, which does a `psalm file1 file2 file3`)... this isn't really practical.

**Comment by Taluu** [comment]
Pinging @Wharren who debugged that

**Comment by muglug** [comment]
> if you have a `projectDir` config in your xml config

That's not a config Psalm has...

**Comment by muglug** [comment]
I think the functionality you're looking for is just to run Psalm with the `--diff` flag. That will just check files that have changed, and those that depend on them.

**Comment by Taluu** [comment]
Even with the `--diff` flag it seems to scan the whole project. I meant the `projectFiles` config.

(Ping @Wharenn)

**Comment by muglug** [comment]
The whole project is scanned the first time, but then only the changes are analysed

**Comment by muglug** [comment]
That way is more reliable than just checking the individual changed files, as altering a function/method signature may have changed.

**Comment by weirdan** [comment]
@muglug so there must be some state persisted somewhere - is the location documented / configurable? It would have to be cached by CI server for `--diff` to work.

**Comment by Taluu** [comment]
@muglug Then how about when scanning individual files, it just scans its direct dependencies ? Wouldn't this be faster (and appropriate for a git hook, so it doesn't take ages, even on the "first" scan) ? 

We have some perfs that with a "huge" basefile (~15k errors last I checked), even with a cache controlled to a directory (thourgh `cacheFile` or something ? Can't remember), that on a macos + docker, it takes ~4min to scan (on a linux and linux + docker, or even mac native, it takes something like 3 minutes) with or without cache, it still the same... so it will kinda halt the adoption. :/

**Comment by muglug** [comment]
> on a macos + docker

I never run Psalm in docker + macOS, on account of it's much slower and using `--threads=X` doesn't work half as well.

When you say "it scans the full project" when running `psalm file1.php file2.php` what do you mean exactly?

There are two things Psalm does when checking a project – scanning, and analysis.

The scanning is necessary to gather up all the data that it may use in the analysis step, and if you're just analysing a single file in a big project the scanning can sometimes take much longer than analysis (but it still should be much quicker than analysis when checking the whole project).

**Comment by muglug** [comment]
> so there must be some state persisted somewhere - is the location documented / configurable? It would have to be cached by CI server for --diff to work.

I think he was talking about running this locally, but our CI server persists state to make runs shorter.

**Comment by Taluu** [comment]
Yep I guess it scans the whole project and then analyse only the passed files. So for our hooks (which runs psalm only on the changed files), we have to duplicate the config just to remove the `projectFiles` config...

We can't ask our devs to run psalm a first time to be able to commit something :/

Maybe we could have an option from psalm that allows it just to _scan_ (without any analysis) just to prepare the cache ?

And how do you persist the state, just making an artifact out of the cache directory ?

**Comment by michabbb** [comment]
hello, i don´t know if my problem is the same. i have a very large legacy project here. scanning a singl files takes 2,5 minutes 😕 
my options: `--diff --threads=50` . it takes 2 minutes before psalm says "Scanning files..." the output:

```
Checks took 19.29 seconds and used 826.768MB of memory
Psalm was able to infer types for 76.4230% of the codebase
```

is there anything i can do to speed up the whole process ???

**Comment by orklah** [comment]
Please open a new issue instead. Can you also try with --no-cache to see if it's not the cache restoration that's taking time?

**Comment by weirdan** [comment]
and `--debug` to see if cache is actually used.
