### ISSUE TITLE
Add error when unpacking an array of arguments with string keys

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#2481]
Could psalm detect such cases?

https://psalm.dev/r/5a1bf51bb9
https://3v4l.org/NNsi8

Note that arrays with integer keys (not lists) can be unpacked https://3v4l.org/ddAYG.

**Comment by AndrolGenhald** [comment]
This shows an error now, but the error is a bit misleading: https://psalm.dev/r/72849382c2

**Comment by orklah** [comment]
It doesn't show an error anymore

**Comment by AndrolGenhald** [comment]
Note that there are two issues here now:

 1. We don't currently disallow unpacking string keyed arrays in PHP < 8.0 (https://psalm.dev/r/72849382c2?php=7.4)
 2. `array_merge` is unlike most variadic functions in that it [disallows named arguments](https://3v4l.org/5hgJE), and we should show an issue for that when unpacking an array with possibly-`string` keys
