### ISSUE TITLE
Array type support with @psalm-assert-if-true

### ISSUE THREAD

**Issue by ndench** [vimeo/psalm#2484]
[Psalm assertions](https://psalm.dev/docs/annotating_code/adding_assertions/) don't seem to support [array types](https://psalm.dev/docs/annotating_code/type_syntax/array_types). It generates a `MissingDocBlockType` error, which I assume is because it reads the docblock as invalid because if I change `@psalm-assert-if-true array{type: string} $data` to `@psalm-assert-if-true array $data` the `MissingDocBlockType` error goes away.

https://psalm.dev/r/754114d12f

```php
/**
 * @param mixed $data
 * @return bool
 * @psalm-assert-if-true array{type: string} $data
 */
function isBar($data)
{
  return isset($data['type']);
}

/**
 * @param mixed $data
 * @return string
 */
function doBar($data)
{
  if (isBar($data)) {
    return $data['type'];
  }
  
  throw new \Exception();
}
```

**Comment by weirdan** [comment]
It works if you omit the spaces: `https://psalm.dev/r/63cd7a8b6c

**Comment by ndench** [comment]
Ah that makes perfect sense, thanks @weirdan!
