### ISSUE TITLE
Templates and callable argument in function parameters

### ISSUE THREAD

**Issue by paxal** [vimeo/psalm#2486]
Hi, I don't know if it's a bug, a feature, or psalm misusage.
I want to reuse the template passed in the first param in the type of the second param, but the type of my callable param seems unaware of my template, like : 
```php
/**
 * @template T
 * @template U
 * @param T[] $values
 * @param callable(T):U $callback <= maybe infer T(callable-param)&T($values) ?
 * @return U[]
 */
function map(array $values, callable $callback): array 
{
    return array_map($callback, $values);
}
```

I would expect this snippet to report no issues : https://psalm.dev/r/80019ad782

**Comment by muglug** [comment]
Psalm has some special logic to make `array_map` and `array_filter` work without needing extra type information, but custom functions need more help.

You can add a docblock param type like so:  https://psalm.dev/r/6053afaabb

**Comment by muglug** [comment]
The crux of this is that Psalm knows the closures in array_map/array_filter take as their first argument the value param of the given array, so Psalm evaluated the array arg first before evaluating the closure with that inferred first arg.

It’s not safe to assume this in general.

**Comment by paxal** [comment]
> You can add a docblock param type like so: https://psalm.dev/r/6053afaabb

Yes that's what I usually do, I was just wondering if there were some way to achieve that without extra annotations / plugin.

Thanks for your answer !

**Comment by weirdan** [comment]
The problem, as I see it, is that Psalm, given the docblock:
```php
/**
 * @param iterable<T> $a
 * @param callable(T):U $c
 * @return iterable<U>
 */
```
doesn't know if it needs to constrain the callable by type T or to use the callable's type to infer T.
@muglug what if there was some kind of construct to opt out specific mention of type from being used for inference - something like `constrain-type<T>`, so the above would become
```php
/**
 * @param iterable<T> $a
 * @param callable(constrain-type<T>):U $c
 * @return iterable<U>
 */
```
making the inference of T unambiguous?
