### ISSUE TITLE
Support @phpstan- prefixed annotatins

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#2488]
@ondrejmirtes is there a list of those you support somewhere?

**Comment by ondrejmirtes** [comment]
You can look up the supported tags in this class: https://github.com/phpstan/phpstan-src/blob/master/src/PhpDoc/PhpDocNodeResolver.php

I've compiled the list for you:

* `@phpstan-var`
* `@phpstan-extends`
* `@phpstan-implements`
* `@phpstan-use'
* `'@phpstan-template'`
* `'@phpstan-template-covariant'`
* `@phpstan-param`
* `@phpstan-return`
