### ISSUE TITLE
Request to make Psalm's Laravel plugin compatible with Laravel Lumen

### ISSUE THREAD

**Issue by HenkPoley** [vimeo/psalm#2489]
_Old title: Is there a preferred way to give --find-unused-code some guidance on seemingly but-not-quite unused code?_

For example Laravel's router is a stringly-type concoction, that magically understands how to parse those strings and instantiate the Controllers.

Psalm of course doesn't know any of that. Is there a `@psalm-this-function-is-honestly-in-use-trust-me` or something?

Or is there a place to put 'in use' classes / methods ?

**Comment by muglug** [comment]
`@psalm-suppress PossiblyUnusedMethod */` should work, but maybe more importantly: how are  those strings expressed? Are they something Psalm's Laravel plugin could evaluate?

**Comment by HenkPoley** [comment]
>  how are those strings expressed? 

See here:
* https://laravel.com/docs/6.x/routing
* https://lumen.laravel.com/docs/6.x/routing

AFAIK internally it uses `nikic/fast-route` (or at least Lumen does).

> Are they something Psalm's Laravel plugin could evaluate?

Maybe it already does 🤷‍♂️. But that plugin is incompatible with Laravel Lumen (deep down it requires `laravel/framework`).

**Comment by muglug** [comment]
That's still very easy for Psalm to parse – have a look at https://github.com/vimeo/psalm/blob/master/examples/plugins/PreventFloatAssignmentChecker.php and see whether you could create something similar for checking those static methods.

Calling `$codebase->methodExists($method_id, $code_location)` will tell Psalm that the method is in fact used – and you can also use the return value of that to complain if it doesn't exist.

**Comment by HenkPoley** [comment]
For future reference, this needs to be done for:

* Commands->handle()
* Middleware->handle()
* Controllers->get()/->index()/->update() etc. (as described in the router), maybe __construct()
* Provider->boot()
* Exceptions->render()
* Maybe: Events->__construct()

**Comment by muglug** [comment]
Closing in favour of other issues

**Comment by HenkPoley** [comment]
btw, this sort of belonged to https://github.com/psalm/psalm-plugin-laravel/issues
