### ISSUE TITLE
Overriding trait method exception

### ISSUE THREAD

**Issue by corsal** [vimeo/psalm#2490]
Hi, when running on code that overrides a method from a trait, like this:

`
class InventoryController
{  
    use CrudTrait {
        getNewItem as crud_getNewItem;
    }
}
`

I get the following exception:

`
Fatal error: Uncaught Error: Unsupported operand types in vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Populator.php:278
`

**Comment by muglug** [comment]
Sorry about that!

Would you mind trying to reproduce on psalm.dev?

**Comment by corsal** [comment]
https://psalm.dev/r/76cade6d92

**Comment by muglug** [comment]
Thanks!
