### ISSUE TITLE
Support ordered arrays

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2497]
Hi,

I have a project where I have this structure:
https://psalm.dev/r/c4efcf6b99

The first function compute and format a lot of fields (my real case is something like "array{0: int, 1: int, 2: array<string, array{name: string, column: string}>, 3: array<string>, 4: array<string>}".

The second function is my Controller, which calls a third function. This way the code in my controller is minimal.

This particular feature was discussed here already:
https://github.com/vimeo/psalm/issues/764
Where it was flagged as "wontfix" because there is currently no order supported in arrays in psalm.

However, now we have the special "list" array, could it be possible to have another specific array which would support order to cover such use cases?

Thanks

**Comment by muglug** [comment]
Again, I won't fix this.

I'd strongly suggest you [use a data transfer object](https://psalm.dev/r/445065964e) for sharing this information. I know you want to minimise your controller code but I promise you this is a much more sane solution.
