### ISSUE TITLE
switch(bool) to assert nullability/non-nullability

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#250]
Currently, `switch(get_class($var)) {` can be used to assert `$var` class. It would be useful if psalm could understand the following as well:
```php
class A {
   /**
    * @var ?string
    */
   public $a = null;
   /**
    * @var ?string
    */
   public $b = null;
}
function f(A $obj): string {
  switch (true) {
    case $obj->a !== null:
      return $obj->a; // definitely not null
    case !is_null($obj->b):
      return $obj->b; // definitely not null
    default:
      throw new \InvalidArgumentException('$obj->a or $obj->b must be set');
  }
}
```

**Comment by muglug** [comment]
Ah, I haven't encountered that pattern before – I'll make sure that there's a less specific treatment of switch statement case assertions.

**Comment by muglug** [comment]
The equivalent function in if-statement form also fails in Psalm:

```php
function f(A $obj): string {
  if (($obj->a !== null) == true) {
    return $obj->a; // definitely not null
  } elseif (!is_null($obj->b) == true) {
    return $obj->b;
  } else {
    throw new \InvalidArgumentException('$obj->a or $obj->b must be set');
  }
}
```

But it works when simplified:

```php
function f(A $obj): string {
  if ($obj->a !== null) {
    return $obj->a; // definitely not null
  } elseif (!is_null($obj->b)) {
    return $obj->b;
  } else {
    throw new \InvalidArgumentException('$obj->a or $obj->b must be set');
  }
}
```

and in the spirit of not forcing Psalm to understand arbitrarily convoluted algebra, I'm going to close this, while opening one to address more basic switch statement logic.

**Comment by muglug** [comment]
OTOH PHPStan [supports this](https://github.com/phpstan/phpstan/blob/bc51719d160ca50243dd36476f9178e2dd03fbea/src/Analyser/NodeScopeResolver.php#L477-L479)
so maybe Psalm should as well

**Comment by muglug** [comment]
Thanks for this – I've done a bunch of work to improve Psalm's assertion finding, and it now treats switch statements identically to their comparable if statements.
