### ISSUE TITLE
error handle callable registration shouldn't error

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#2501]
`set_error_handler([self::class, 'handleError']);` should be allowed but errors

https://psalm.dev/r/1a5af2ff08

**Comment by weirdan** [comment]
Error handler should return `bool` and Psalm tells you that (in a cryptic way): https://psalm.dev/r/707d29c13c

**Comment by staabm** [comment]
> in a cryptic way

ohh wow.. there were so much types involved in this error message that I was not able to tell which ones I got right and which one actually report a error..

**Comment by staabm** [comment]
is there already a issue regarding improving this message for better DX?

**Comment by weirdan** [comment]
You mean like Typescript does: [set_error_handler in Typescript](https://www.typescriptlang.org/play/?ssl=8&ssc=94&pln=8&pc=52#code/JYOwLgpgTgZghgYwgAgKJSgeygYTgG3wCNEBrZAbwChlbkAKaKETALmRAFcBbI6AGiYBnMFHYiooAOb9kTGMHwQA-ONHTZTfKBXsuvAcgSZwEAB5hVyTEQBWEBGACU7IpkxK4IKgF8qxkBFkIQgwAH0mbDCACy8AEyUoZABeZBhOEEdgEwZYkATodnQsXAJiMhdkADdMYDjKGjo8gqh6AEZZACImTq6FJQA6WyFe5DaAJlkKHycAbl8qKhDwyKgY+MT6dMywbJB6CIwWdi8AT1lDqAkTkHPkS-6IG7vL7RAn5DPKmrrKGaA) ?

**Comment by muglug** [comment]
Yeah, it's ticketed here: https://github.com/vimeo/psalm/issues/2098
