### ISSUE TITLE
bug: array_unshift transforms list<T> to array<int, T>

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2504]
prepending `T` to `list<T>` sourced from variadic should result in `list<T>`, rather than being modified to `array<int, T>`

* https://psalm.dev/r/57268ef804
* https://3v4l.org/J9M7S

```php
<?php
class Foo {}

/**
* @return list<Foo>
*/
function bar(Foo $foo, Foo ...$foos) : array {
  array_unshift($foos, $foo);
  
  return $foos;
}

/**
* @return list<Foo>
*/
function baz(Foo ...$foos) : array {  
  return $foos;
}
```
> Psalm output (using commit ee35db5):
> 
> INFO: LessSpecificReturnStatement - 10:10 - The type 'array<int, Foo>' is more general than the declared return type 'list<Foo>' for bar
> 
> INFO: MoreSpecificReturnType - 5:11 - The declared return type 'list<Foo>' for bar is more specific than the inferred return type 'array<int, Foo>'

**Comment by muglug** [comment]
this was fixed in https://github.com/vimeo/psalm/commit/26876b9a1393f08364007901a1ef0f8d05f23167
