### ISSUE TITLE
Update to 3.7.2 causes UnusedClass errors

### ISSUE THREAD

**Issue by mitelg** [vimeo/psalm#2506]
I tried the update from 3.7.1 to 3.7.2 and suddenly I got 3k errors about `UnusedClass`
Here you could find our current [configuration](https://github.com/shopware/platform/blob/6.1/psalm.xml)

**Comment by muglug** [comment]
Sorry about that!

**Comment by mitelg** [comment]
thanks again for the real quick fix 👍🎉 love your work 💙
