### ISSUE TITLE
Serializable interface methods not marked as used when calling w/ serialize function

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2511]
* https://psalm.dev/r/77f77efa4f
```php
<?php
class Foo implements Serializable {
  function serialize() : string {
    return '';
  }
  
  function unserialize($_serialized) : void {}
}

$a = new Foo();

var_dump(serialize($a));
```
> Psalm output (using commit 6b81f8c):
> 
> ERROR: ForbiddenCode - 12:1 - Unsafe var_dump
> 
> INFO: PossiblyUnusedMethod - 3:12 - Cannot find any calls to method Foo::serialize
> 
> INFO: PossiblyUnusedMethod - 7:12 - Cannot find any calls to method Foo::unserialize

**Comment by muglug** [comment]
I think those two methods should just be ignored for `PossiblyUnusedMethod` when the class implements `Serializable` - could you make a PR?

**Comment by SignpostMarv** [comment]
@muglug would `Serializable::unserialize()` be flagged as unused, because there isn't a `serialized-string<T>` type for `unserialize()` to hook in to ?

i.e.
```php
/**
* @template T
*
* @param T $mixed
*
* @return serialized-string<T>
*/
function serialize($mixed) : string {}

/**
* @template T
*
* @param serialized-string<T> $str
*
* @return T|false
*/
function unserialize(string $str) : mixed {}

/**
* @template T
*/
interface Serializable {
    /**
    * @param T $mixed
    *
    * @return serialized-string<T>
    */
    function serialize($mixed) : string {}

    /**
    * @param serialized-string<T> $str
    *
    * @return T|false
    */
    function unserialize(string $str) : mixed {}
}

serialize(1); // 'i:1;' aka serialized-string<int> or serialized-string<int(1)>
serialize($a); // 'C:3:"Foo":0:{}' aka serialized-string<Foo>
```

**Comment by SignpostMarv** [comment]
(forgot to click comment)

**Comment by muglug** [comment]
The logic that triggers those `PossiblyUnusedMethod` issues should just skip if the method name is either `serialize` or `unserialize` and the class implements `Serializable`, as there's basically no way to detect that serialisation has occurred.

**Comment by SignpostMarv** [comment]
presently having issues with `preventImplementingSerializableWithType`, and `preventImplementingSerializableWithWrongDocblockType`- getting the tests to pass seems to be problematic;
```php


interface Serializable
{
    /**
     * @return string
     */
    public function serialize();

    /**
     * @return void
     */
    public function unserialize($str);
}
```

`public function unserialize(string $str);` seems to mess with `preventImplementingSerializableWithType` entirely- whether it's typed inline or via `@param`.
