### ISSUE TITLE
"uninitialized variable" with use \php_user_filter class

### ISSUE THREAD

**Issue by Ne-Lexa** [vimeo/psalm#2513]
How to reproduce: https://psalm.dev/r/6f8098b9ef

Error: 'XXXXX has an uninitialized variable $this->xxxxx, but no constructor'

When implementing the [`\php_user_filter`](https://www.php.net/php-user-filter) class, php does not call the constructor; all variables must be initialized in the [`onCreate()`](https://www.php.net/php-user-filter.oncreate) method.

**Comment by muglug** [comment]
Feel free to suppress this issue, but I think this is too much of an edge-case.
