### ISSUE TITLE
[?] Except constructor from purity checks

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#2517]
https://psalm.dev/r/7aa1afd57c
```php
<?php
  /** @psalm-immutable */
  class Assessment {
     private ?string $root;
     public function __construct() {
       $this->root = rand(0, 1) ? 'root' : null;
     }
     public function getAttributeRoot(): ?string {
       return $this->root;
     }
  }
```
**Expected**: no issues
**Actual**: 
```
Psalm output (using commit 9a04d93):

ERROR: ImpureFunctionCall - 6:22 - Cannot call an impure function from a mutation-free context
```

As far as I understand, constructors should not be considered mutation-free context, as constructor purpose is specifically to mutate the object being created.

/cc: @Ocramius

**Comment by Ocramius** [comment]
They can mutate state, but they shouldn't produce side-effects: for that, use a factory that can do IO.

The problem with ctors is that they are both static and instance methods (nothing prevents calling `$this->__construct()`)

**Comment by muglug** [comment]
`rand` is still very impure - the idea is that it mutates _external_ state (mutating instance state inside the constructor is fine).

**Comment by weirdan** [comment]
> nothing prevents calling `$this->__construct()`

Psalm could be that thing :smile: if that solves any problems.

> `rand` is still very impure - the idea is that it mutates external state (mutating instance state inside the constructor is fine).

Ok, but if we reformulated that initialization as `$this->root = time() > 1 ? 'root' : null;` there would be no external state mutated, but Psalm still complains about that:  https://psalm.dev/r/3c4f16bbd2

**Comment by muglug** [comment]
ok I guess my description wasn't complete – the constructor is not allowed to depend on externally-mutated state either. This means that you can create immutable objects in the context of a pure function, and that purity is guaranteed.

**Comment by weirdan** [comment]
Ok, that makes sense. Basically one may think the constructor of a `@psalm-immutable` is a pure function that has `$this` as its return value (and thus is allowed to mutate it).
