### ISSUE TITLE
How to correctly extend a class

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#2519]
How does psalm expect classes to be extended? I checked the docs & also the docs on the phpdoc.org site, but couldn't find any solution.

For the following code, I always get this error:
ERROR: InvalidDocblock - 12:1 - @template-extends has invalid class ParentClass

```php
/**
 * @class ParentClass
 */
class ParentClass {}

/**
 * @class ChildClass
 * @extends ParentClass
 */
class ChildClass extends ParentClass {}
```

See: https://psalm.dev/r/871761f45c

**Comment by weirdan** [comment]
You only need template-extends if the parent class is a template (generic). So in your case you need no doc blocks at all: https://psalm.dev/r/4b58c95118

**Comment by tdtm** [comment]
For anyone else stumbling on this: my issue was that I was doing

```php
/**
 * @psalm-type TKey=string
 * @template TValue of FooInterface
 * @template-extends Map
 */
```

but I should have been doing:


```php
/**
 * @psalm-type TKey=string
 * @template TValue of FooInterface
 * @template-extends Map<TKey, TValue>
 */
```

Passing the template types to the extended class is what I had missed.
