### ISSUE TITLE
Psalm doesn't support vendor directories that are not vendor

### ISSUE THREAD

**Issue by AshleyPinner** [vimeo/psalm#252]
It is perfectly possible to have your composer vendor directory be a custom name:

```JSON
{
    "config": {
        "vendor-dir": "vendors",
    },
    "require": {...}
}
```

However, Psalm is unmoving on the name of this directory:

```PHP
$vendor_autoload_file = $autoload_root . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';
```

It would be nice if you could specify the name of the vendor dir (Defaulting to vendor) for situations like this.

**Comment by muglug** [comment]
Thanks, finally fixed.
