### ISSUE TITLE
InvalidPropertyAssignmentValue With trait

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#2521]
Didnt expect this code will emit an error

https://psalm.dev/r/868bd13646

Tried fixing it with https://github.com/redaxo/redaxo/pull/3061/files but the same error still applies

Tested on 3.8.0

**Comment by muglug** [comment]
It's basically this: https://psalm.dev/r/ea1870c98b

**Comment by staabm** [comment]
thx for the fast feedback. the reduced test-case you mentioned works now. the initally reported one still emits an error.

is this expected?

**Comment by staabm** [comment]
ahh I guess this means that my fix mentioned initially could now work:
https://github.com/redaxo/redaxo/pull/3061

will test it..

**Comment by muglug** [comment]
Well, you also should fix your docblocks.

This only has a single `MixedAssignment` issue: https://psalm.dev/r/d1cd4e0a4c

The one functional change I made was changing `call_user_func_array($createCallback, $args)` into `$createCallback(...$args)` which Psalm has a slightly better time with.

**Comment by muglug** [comment]
Now supported in latest master with `call_user_func_array` too: https://psalm.dev/r/4267615844
