### ISSUE TITLE
Can't make inferences about PDOStatement->fetch?

### ISSUE THREAD

**Issue by duskwuff** [vimeo/psalm#2529]
Psalm seems to have trouble dealing with the return value of `PDOStatement::fetch()`, even with a fetch mode specified.

```
$p = new \PDO("sqlite:::memory:");
$sth = $p->prepare("SELECT 1");
$sth->execute();
while (($row = $sth->fetch(\PDO::FETCH_ASSOC)) !== false) {
  //    ^-- MixedAssignment: Cannot assign $row to a mixed type
}
```

The only thing that seems to help is adding a `/** @var array|false $row */` _directly before_ `$row`, inside the condition of the while loop -- but this seems pretty awkward.

**Comment by muglug** [comment]
I've fixed it for your one use-case, but would you mind opening a PR for [all the other values](https://www.php.net/manual/en/pdostatement.fetch.php) of `PDOStatement::fetch`?
