### ISSUE TITLE
[?] Marking an implementation with an anonymous class as immutable

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#2543]
Hi,

Is there a way to mark as immutable the implementation with an anonymous class of an interface marked as immutable?

https://psalm.dev/r/f093f15ec3

**Comment by LeSuisse** [comment]
Just to clarify: it's just out of curiosity since `@psalm-mutation-free` can be used on each methods of the interface.

https://psalm.dev/r/cd20191753

**Comment by weirdan** [comment]
It works when docblock directly precedes the `class` keyword: https://psalm.dev/r/9d49354b28
