### ISSUE TITLE
InaccessibleProperty and UnusedMethodCall in constructor method call

### ISSUE THREAD

**Issue by snapshotpl** [vimeo/psalm#2545]
https://psalm.dev/r/74ba73afc4

**Comment by muglug** [comment]
Why make the class immutable?

**Comment by snapshotpl** [comment]
It's just simplified version of my more complex class. I just want to be marked as immutable, because it is ;)

**Comment by muglug** [comment]
what does the `test` method do?

**Comment by snapshotpl** [comment]
This is my real case https://psalm.dev/r/6c80d506de

I have event with interface and additional use trait to reduce duplication

**Comment by muglug** [comment]
@snapshotpl I've simplified that down to something I think should definitely always work: https://psalm.dev/r/bab5cb47ae

**Comment by snapshotpl** [comment]
More simplified https://psalm.dev/r/2860dccd79

**Comment by snapshotpl** [comment]
@muglug awesome work! I'm waiting for release with all my reported bugs now

**Comment by muglug** [comment]
Sadly not so fast – I've fixed a bug that was causing the `InaccessibleProperty` issue in your first posted example, but there's no way to allow your more complex use-case without breaking checks that catch code that does violate immutability. Feel free to suppress those issues.

**Comment by snapshotpl** [comment]
@muglug you are talking about `UnusedMethodCall` ?
