### ISSUE TITLE
Only recognise class definition in shims if !class_exists

### ISSUE THREAD

**Issue by asgrim** [vimeo/psalm#2547]
I'm writing a library that I'm trying to make compatible across multiple major versions of a third party library, so I've written a shim.

Basically, in the 3rd party library, a class was essentially renamed with the following technique:

 - 1.0.x `class B {}`
 - 1.1x `class A extends B {}` and `B` is marked as "deprecated" - consumers are encouraged to depend on `A` from now on
 - 2.x `class A {}` only - `B` has been removed

However, I'm getting the following:

```
ERROR: DuplicateClass - 12:11 - Class ThirdPartyLibrary\A has already been defined in /var/www/vhosts/psalm.dev/httpdocs/src/../src/somefile.php
```

In my example: https://psalm.dev/r/d6ea3719ab ... it seems `!class_exists(A::class)` is not being recognised here (or maybe the complication of the `class_exists(B::class)` is breaking something ?). 

I did see #2505 which has a VERY similar example (and I note that was fixed recently in `dev-master`). I wonder if the "order of loading" has something to do with this in autoloader? In my "real" code, I actually get an additional error:

```
ERROR: MissingDependency - src/C.php:11:27 - ThirdPartyLibrary\A depends on class or interface thirdpartylibrary\b that does not exist
    public function thing(A $a) : void {}
```

For that full example, you can also see a test repo I made (since I can't seem to reproduce it in the psalm.dev editor): https://github.com/asgrim/psalm-shim-example

**Comment by muglug** [comment]
I had to rename `third-party-library` to `lib` to get it to work – for some reason Composer was having a hard time autoloading that folder 🤷‍♂
