### ISSUE TITLE
Passing template type in method

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2551]
I don't know if this is possible and I'm doing something wrong or if Psalm is simply not design for this.

It's hard to eplain with words, here's an example

https://psalm.dev/r/b0eeecbe47

I named my templates Entity and Entity2 for this exemple because I wanted to be sure there was no side-effect due to being in the same scope, but they have the same name in my code.

The error is a little cryptic but what I understand is that Psalm doesn't seem to consider that EQB has a template of its own

I believe this specific error message (with fn-...) appeared last version but I think it just replaced an previous error.

**Comment by muglug** [comment]
It's a good question, but that's not how Psalm is designed - any generic types have to be set in the constructor (e.g. https://psalm.dev/r/1814563e3f) otherwise Psalm templates the object as just `EQB<mixed>` (which is equivalent to `EQB`).

**Comment by orklah** [comment]
Thanks for the reply! So I completely refactored and I just have a detail different from your example that make Psalm raise an error:
https://psalm.dev/r/18c32a91b2

the class_exists() is messing with the templates and Psalm seems to believe EQB<Entity> is not compatible with EQB<object>

I tried to give the "object" type to psalm with the "of object" notation but it doesn't seem to change anything
