### ISSUE TITLE
Psalm does not reject arrays literals with empty elements

### ISSUE THREAD

**Issue by chloekek** [vimeo/psalm#2552]
All the following statements are accepted by Psalm 3.8.1:

```php
[1,,2];
['a' => 1,,'b' => 2];
array(1,,2);
array('a' => 1,,'b' => 2);
```

But executing this script with PHP gives an error:

> Fatal error: Cannot use empty array elements in arrays

Should be nice if Psalm could catch this.

**Comment by muglug** [comment]
Generally I advise that people run `php -l` on every file in their codebase, because occasionally the parser that Psalm uses will allow things that aren't valid PHP.

But this particular case is something that Psalm can trivially check for.
