### ISSUE TITLE
Type coverage report

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#2555]
Wouldnt it be helpful to be able to generate some kind of coverage report with psalm, which shows which exact lines of code psalm was able to identify the types and in which areas types are not known ?

It could be visualized like a phpunit test coverage report..?
See e.g. 
https://www.google.de/search?q=phpunit+test+coverage+report

http://www.inanzzz.com/index.php/post/8023/creating-code-coverage-report-with-phpunit

I am only aware of the totallyTyped option.. are there any other means which can be used to increase type coverage?

**Comment by weirdan** [comment]
There's a (mostly undocumented) cli switch that may provide what you're looking for: `--generate-json-map`:
```
    --generate-json-map=PATH
        Generate a map of node references and types in JSON format, saved to the given path.
```

**Comment by muglug** [comment]
Yeah, I'd see if that works first.

**Comment by staabm** [comment]
Lets try this differently: is there a supported/known-way on how to tackle type coverage, so how to get higher type coverage without just added phpdocs everywhere?

**Comment by HenkPoley** [comment]
PhpDoc typehints is the way to add types in older PHP.

Since 7.4 you can also annotate class properties directly: https://www.php.net/manual/en/language.oop5.properties.php

Since PHP 8.0 you should be able add union types.

A way for Psalm to add as much as it knows (for example for PHP 7.4); while keeping true only to what PHP knows ('safe types'):

```shell
vendor/bin/psalter --php-version=7.4 --safe-types --issues=InvalidFalsableReturnType,InvalidNullableReturnType,InvalidReturnType,LessSpecificReturnType,MismatchingDocblockParamType,MismatchingDocblockReturnType,MissingClosureReturnType,MissingParamType,MissingPropertyType,MissingReturnType,ParamNameMismatch,PossiblyUndefinedGlobalVariable,PossiblyUndefinedVariable,UnnecessaryVarAnnotation,MissingPureAnnotation,MissingImmutableAnnotation
```
