### ISSUE TITLE
Irreproducible PossiblyFalseArgument error

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2557]
![image](https://user-images.githubusercontent.com/1752683/71816966-97ded180-3084-11ea-9e8e-ac0f5ef666eb.png)

> ERROR: PossiblyFalseArgument - ???.php:233:50 - Argument 2 of substr cannot be false, possibly false value provided

I couldn't reproduce this one on https://psalm.dev (yet). The surrounding method is quite long.

**Comment by iluuu1994** [comment]
Here we go: https://psalm.dev/r/a063da61fc

**Comment by muglug** [comment]
Fixed in 4888ae6

**Comment by iluuu1994** [comment]
Thanks @muglug! Happy new year 🙂
