### ISSUE TITLE
query: re differences between 3.7 * 3.8

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2558]
I've got some dayjob code that makes extensive use of a set of `ELEMENT`, `ATTRIBUTES`, & `CONTENT` `@template` & `@psalm-type` tags, and somewhere between 3.7 and 3.8, psalm is not able to find them (resulting in `UndefinedDocblockClass`, rather than psalm pulling the array shapes/strings from the class docblock).

Where might I be best off looking for the relevant change in psalm to determine the cause of the problem?

**Comment by SignpostMarv** [comment]
> Hey @SignpostMarv, can you reproduce the issue on https://psalm.dev ?

nope.

**Comment by SignpostMarv** [comment]
for public reference, I've just checked the public code & [`@template T1 as string`](https://github.com/SignpostMarv/daft-markup/blob/44f892e1adc85db2ddb8ddfff77ffb46dc2f7f4a/src/AbstractHtmlElement.php#L10) isn't getting picked up as a template tag under 3.8.1

**Comment by muglug** [comment]
Is the template tag being used in a static method?

**Comment by SignpostMarv** [comment]
```php

	/**
	* @return T1
	*/
	abstract public static function MarkupElementName() : string;
```
> ERROR: UndefinedDocblockClass - src\Html\AbstractHtmlDocument.php:260:47 - Docblock-defined class or interface SignpostMarv\DaftMarkup\T1 does not exist

currently trying to get a psalm.dev mini example working.

**Comment by muglug** [comment]
static methods can no longer use class template params (as they were easy to misuse)

**Comment by SignpostMarv** [comment]
I'm going to hope I can get away with doing:
```php
/**
* @var T1
*
* @readonly
*/
public string $element;
```

**Comment by SignpostMarv** [comment]
> static methods can no longer use class template params (as they were easy to misuse)

re: misuse, is that the frequent liskov principle violation my code tends to trample all over ?

**Comment by muglug** [comment]
No, mainly due to this: https://github.com/phpstan/phpstan/issues/2731#issuecomment-565724794
