### ISSUE TITLE
Consider `array_filter()` over an `array{0: T}` to be a `list<T>`?

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2560]
Probably a bit of an edge case, but interesting nice-to-have: an `array_filter()` over an array of length `0` or `1` will always generate a `list`:

```php
<?php

/** @psalm-return list<int> */
function makeAList(int $ofThisInteger): array
{
    return array_filter([$ofThisInteger]);
}
```
```
Psalm output (using commit cd0d118):

INFO: LessSpecificReturnStatement - 6:12 - The type 'array<int(0), int>' is more general than the declared return type 'list<int>' for makeAList

INFO: MoreSpecificReturnType - 3:19 - The declared return type 'list<int>' for makeAList is more specific than the inferred return type 'array<int(0), int>'
```

https://psalm.dev/r/659b6172a3

It could be interesting to consider `array{}` and `array{0: T}` to be implicitly a `list<T>`.

Not sure if psalm has information about an array being of a specific length.

**Comment by orklah** [comment]
Why not documenting array<int(0), int> in this case? It's even detailed than list in this case.

It seems weird to handle a special case to loose information about the variable type. Maybe what's missing is a notation to describe the length of the list? Something like list(1)<T>?

**Comment by Ocramius** [comment]
The example I made is simplistic, to show that `list<T>` is not recognised.

Consumers of this code (that I happened to encounter) expect a `list<T>`, I didn't annotate it 😅

**Comment by orklah** [comment]
Still, there's a loss of information. If someone try to perform a $list[1] on the array afterwards, Psalm won't be able to warn about the issue if `array<int(0), int>` is transformed to `list<int>`

However, I misread the Psalm warning, I expected `array<int(0), int>` to be more precise than `list<int>`, not less

**Comment by Ocramius** [comment]
💪
