### ISSUE TITLE
Support modulo operator

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#2562]
Both cases should error https://psalm.dev/r/5912c6fcaa because they can never be true

**Comment by muglug** [comment]
Was there a bug that this check would have prevented?

**Comment by staabm** [comment]
I am not aware of a psalm or php-src bug you might refering to?

**Comment by muglug** [comment]
As in did you run into a bug during your own development that having this check would have prevented? I'm wary of adding specific arithmetic checks as I think they're not terribly useful in real-world situations.

**Comment by bdsl** [comment]
I suppose if it was worth adding support for `%`, `+`, `-`, `*` and `/` would be higher priorities. Psalm [currently](https://psalm.dev/r/8c6afa51ae) types the result of `0+0` as `int`, not `int(0)`.

**Comment by staabm** [comment]
> As in did you run into a bug during your own development that having this check would have prevented? I'm wary of adding specific arithmetic checks as I think they're not terribly useful in real-world situations.

In the past I was experiencing bugs e.g. in $i % 2 == 0 expressions when trying to implement alternating colors for Html-table-rows

**Comment by SignpostMarv** [comment]
@muglug if both sides of a modulo are the same, does psalm set the type to a literal int 0 ?

**Comment by bdsl** [comment]
@SignpostMarv No, it returns `int`, not `int(0)`. You can see by the error message given for https://psalm.dev/r/3e8bf4f1ba - "string() cannot be identical to int"

**Comment by SignpostMarv** [comment]
@bdsl: having a poke around at this particular case.

**Comment by SignpostMarv** [comment]
@bdsl fixed both, tinkering for others.

**Comment by muglug** [comment]
Going to close this as not worth it.
