### ISSUE TITLE
parent type array-key provided after array_keys

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#2572]
https://psalm.dev/r/139ec1fbb0

MixedArgumentTypeCoercion - 6:51 - Argument 2 of preg_match expects string, parent type array-key provided

Why does it complain here? the array keys are either empty or strings so I don't get what it has an issue with here

**Comment by weirdan** [comment]
> the array keys are either empty or strings

Psalm doesn't know this because you declared that your `my_func` returns arbitrary `array` - thus it potentially may include integer keys.

If it will never return integer keys you may want to add more specific `@return` docblock: https://psalm.dev/r/746e67ff22
