### ISSUE TITLE
Type declarations for third party packages.

### ISSUE THREAD

**Issue by andres-valdes** [vimeo/psalm#2575]
Hi, is there a way that I can make a psalm.d file or something of the sort where I can add stronger psalm types for third party packages and the sort?

I am mainly interested in adding templates to Laravel's collections.

Edit: it is now my suspicion that this would be accomplished through a plugin. Is this correct?

**Comment by muglug** [comment]
You can make stubs, then add them to Psalm’s Laravel plugin so everyone else can use them too.

Stubs are basically a slimmed down version of the class without any method bodies, and only need the specific methods whose signatures you want to improve.

**Comment by weirdan** [comment]
Laravel plugin lives here: https://github.com/psalm/laravel-psalm-plugin

**Comment by muglug** [comment]
The Doctrine plugin does something similar: https://github.com/weirdan/doctrine-psalm-plugin/blob/master/Plugin.php#L23
