### ISSUE TITLE
array filter on list<int> drops values but not keys.

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2576]
https://psalm.dev/r/8de1a7d011

expecting `parent type array<int(0)|int(1)|int(3)|int(4), int(2)|int(3)|int(4)|int(5)>`

**Comment by someniatko** [comment]
@SignpostMarv there is no bug here:

after `array_filter()` the array has the following structure:

```
)array (
  0 => 2,
  1 => 3,
  3 => 4,
  4 => 5,
)
```

as you see, key `2` is missing. `list` type implies that all keys are consecutive. You should use `array_values(array_filter($arr))` and then you get `list` type.
