### ISSUE TITLE
TooManyArguments is triggered if the variadic function declared at the autoloader file

### ISSUE THREAD

**Issue by incrize** [vimeo/psalm#2579]

**Comment by incrize** [comment]
I have an autoloader file that declares global functions. Some of the declared functions are variadic.
There is a part of code that uses these global functions. When psalm analyzes that code, I get TooManyArguments errors.

Unit test was implemented as follows: https://github.com/incrize/psalm/commit/6576d1dcefc9393b703e46bc1d89f5ad75835222#diff-f5429097d608f3340a97154a2745842aR38.

Issue can't be reproduced at https://psalm.dev, because it doesn't allow to configure the autoloder file.

**Comment by incrize** [comment]
Maybe i misuse a psalm. In the near future I will prepare a more detailed example.

**Comment by muglug** [comment]
Possibly, or possibly not – haven't had time to examine this in detail yet.

**Comment by incrize** [comment]
Changes in PR do not completely solve my problem, global functions which are includes in autoloader, alse are part of coda base  that will be analized.

**Comment by incrize** [comment]
I figured it out. Some of global functions were included through the dynamic include expression which has resulted functions were not declared as stabbed (https://github.com/vimeo/psalm/blob/7482b9e56fba9003948e0c679ff756acae4f96db/src/Psalm/Internal/Codebase/Functions.php#L33). So PR changes are completely solve my problem.

**Comment by muglug** [comment]
Great! Closing.
