### ISSUE TITLE
UndefinedMagicMethod: Magic method boolean does not exist

### ISSUE THREAD

**Issue by ElisDN** [vimeo/psalm#2583]
I have fixtures with this code:

```php
$post = new Post(
    $date,
    $faker->slug,
    $faker->sentence(4)
);

if ($faker->boolean(60)) {
    $post->publish($date);
}
```

And in 3.8.2 only I get errors for every usage of method `boolean()`:

```
ERROR: UndefinedMagicMethod - BlogFixture.php:42:25 - Magic method Faker\Generator::boolean does not exist
if ($faker->boolean(60)) {
```

but other magic methods like `sentence()` above work correctly.

All methods are [specified](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Generator.php) in Faker's PHPDoc.

**Comment by ElisDN** [comment]
It cause error with `namespace Faker` https://psalm.dev/r/56d69a8eda
But it passes without namespace https://psalm.dev/r/a4bfb87446

**Comment by SignpostMarv** [comment]
namespaceless one shouldn't be passing as Generator already exists in global namespace.

**Comment by muglug** [comment]
@ElisDN check the docks. Faker defines a magic property for `boolean`, not a magic method. It just so happens that it still works with `boolean()`

**Comment by ElisDN** [comment]
@muglug, check the snippets too. Faker defines property and method both:

```php
/**
 * @property boolean $boolean
 * @method boolean boolean($chanceOfGettingTrue = 50)
 */
```

**Comment by muglug** [comment]
Sorry, this is Psalm replacing `boolean` with `bool` in docblocks. Very embarrassing...

**Comment by muglug** [comment]
And sorry to have closed your issue without properly investigating

**Comment by muglug** [comment]
This should work now. My premature closing was due to the fact that some Faker properties like `->uuid` also work as methods `->uuid()`

**Comment by ElisDN** [comment]
Yes, it works. Thanks!
