### ISSUE TITLE
query: re vimeo/psalm.dev#11

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2585]
It occurs to me I could possibly pr this into psalm myself (i.e as `psalm-matches <value> <php-source>), but I'm not sure:

`Psalm\Type::parseString()` would be used to parse the type that a value is expected to match, but I'm not sure how to proceed with regards to parsing the type.

* if `<php-source>` is a string, then one would assume I'd dig around how psalm invokes php-parser
* if `<php-source>` is a file path, the assumption could be "this file must return a value", but again, then not sure how to obtain the returned value.

which bit of psalm would I be looking at for seeing if union B satisfies the definition of union A ?

**Comment by muglug** [comment]
Psalm has [this method that you can use](https://github.com/vimeo/psalm/blob/2ae85f7c8bb4436ed0edc1263f93a0f0bc62c69a/src/Psalm/Codebase.php#L1566-L1583), but you can also test it out online by submitting your type as an argument to a type that expects the supertype as a parameter, and see if the code works.
