### ISSUE TITLE
Integrate 'php-assumptions'-like behaviour ?

### ISSUE THREAD

**Issue by HenkPoley** [vimeo/psalm#2586]
There is a small tool that looks over your code to see if you are testing assumptions that don't necessarily cover all the future uses of that variable. E.g. you only check if a variable is 'not unset', and then assume it is a particular object.

https://github.com/rskuipers/php-assumptions

It appears that psalm (in default configuration) does not show INFO messages about assumptions. It could be nice to add such messages.

**Comment by muglug** [comment]
This seems like Psalm already covers implicitly:

```php
function foo($foo) {
  if ($foo !== null) {
    $foo->bar(); // MixedMethodCall issue emitted
  }
}
```

vs

```php
function foo(?User $user) {
  if ($user !== null) {
    $user->bar(); // this is fine, $user *must* be an object of type User
  }
}
```

Checking for explicit instances is, for me, a stylistic difference (and unnecessarily verbose IMO).
