### ISSUE TITLE
Support seal-methods/seal-properties as shorthand for psalm-seal-methods

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#2587]
Having a syntax that wasn't specific to Psalm would be a better indication that the user wants the comment to be interpreted that way in other IDEs or analyzers.

src/Psalm/Internal/Analyzer/CommentAnalyzer.php would need to be changed.

Phan's latest releases support `@seal-methods`/`@seal-properties`.

**Comment by muglug** [comment]
The behaviour changed in the most recent version so that any time `@property` or `@mixin` is given, `@psalm-seal-properties` is assumed (ditto for `@method`), but I'm happy to also support `@seal-properties`/`@seal-methods`.

**Comment by TysonAndre** [comment]
I know - that makes it less important.

This may help if a class defines __get() to throw if it gets called but doesn't define magic properties, but this is relatively uncommon.

**Comment by weirdan** [comment]
Assumed fixed in #10344
