### ISSUE TITLE
[Question] Using Psalm in tests

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2592]
Hi,

I was not sure where to search for this functionnality, if it even exists at all.

I'm creating a library where static analysis will have a big role.

I have template annotations in my classes and I'm expecting Psalm to understand what type I want to output. I'd want to include that behaviour in my tests so if I break my annotations or if something changes in Psalm, I can be warned.

Is there a tool that would allow me to do something like that?

Ideally, I'd expect something like that:
`self::assertEquals('array<string, int>', Psalm::getType($var));`

Is this even remotely possible?

Thanks!

**Comment by weirdan** [comment]
> Ideally, I'd expect something like that:
> ```php
> self::assertEquals('array<string, int>', Psalm::getType($var));
> ```
> Is this even remotely possible?

I think it depends on what `$var` is. Psalm can analyze some code and check assertions on the global (?) variables after the analysis is finished. It's actually how many Psalm's own tests are structured, e.g.:  https://github.com/vimeo/psalm/blob/df8e3845e580aba4fc03b289c697fe83a0baa38f/tests/ClassTest.php#L146-L155

**Comment by orklah** [comment]
@weirdan thanks for answering

The $var would be the result of the script above with instantiations and returns of my library.

This format could fit as well. In fact, as long as I can check the result in a PHPUnit test, I'm okay with it.

However, I'm not sure it would be a good idea to try to create my own Psalm\Internal\Analyzer\ProjectAnalyzer to try to emulate the way Psalm does its internal tests

**Comment by HenkPoley** [comment]
While I have no idea how this package works: https://github.com/Roave/you-are-using-it-wrong

It uses elements of psalm to check if some code complies. Might be useful to inspect how it does its things.

**Comment by orklah** [comment]
I'll close this. #3080 should solve my issue nicely
