### ISSUE TITLE
False positive:  ReflectionClass::__construct expects class-string|object, parent type string provided

### ISSUE THREAD

**Issue by cmahnke** [vimeo/psalm#2596]
This is raised by `new \ReflectionClass($instance);`, when `$instance` is a `string`.

Not sure if this is a false positive on the language level, but from a usability point of view it 
definitely is, since `new \ReflectionClass((class-string) $instance);` isn't valid PHP.

**Comment by cmahnke** [comment]
`<?php`
`$instance = "InvalidArgumentException";`
`new \ReflectionClass($instance);`

It's reproducible...

**Comment by andrew-demb** [comment]
See here mention about class-string

https://psalm.dev/docs/annotating_code/type_syntax/scalar_types/#class-string

**Comment by muglug** [comment]
`class-string` isn’t a PHP-supported class - it just represents a string that is also a valid class name.

Psalm has a bunch of ways to allow you to verify that the class name is valid:
- you could use a `::class` constant: https://psalm.dev/r/f15a48e9f6
- if the string is arbitrary you can wrap the call in a `class_exists` check: https://psalm.dev/r/eed39d8ded

If you really don’t like this, there’s a config flag `allowCoercionFromStringToClassConst="true"` that you can use.
