### ISSUE TITLE
Suppressing errors for file from comment

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#2606]
When putting a @psalm-suppress in the file doc (at top of the file) it doesn't actually suppress the error for the whole file.

Is there any way to get errors suppressed for a whole file (which does not involve modifying the psalm.xml)?

Use case:
I have an auto_prepend_file. When I check this file with psalm, it reports "DuplicateFunction" for all functions in this file, and I'd prefer to suppress them all together in this file instead of having to put 72 @psalm-suppress in the file.

**Comment by muglug** [comment]
You can suppress the issue for that file in your Psalm config: https://psalm.dev/docs/running_psalm/dealing_with_code_issues/#config-suppression

**Comment by kkmuffme** [comment]
I know, that's why I wrote:
>which does not involve modifying the psalm.xml

Bc this will just lead to additional conflict resolving on large projects when suddenly all people start modifying the same file in their branch, which could be easily avoided if we could suppress within a file (like phpcs:disable)

**Comment by muglug** [comment]
oh sorry – the answer is no – you'll have to add those suppressions individually

**Comment by XedinUnknown** [comment]
I'd like this.
