### ISSUE TITLE
psalm-suppress not working for function defaults

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#2608]
`ERROR: InvalidParamDefault - 5:11 - Default value type string() for argument 2 of method get_function_arg_names does not match the given type class-string`

Is not suppressed despite @psalm-suppress & it's showing in documentation like that too:
https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-suppress-someissuename
I also tried putting it before the @param but same problem

https://psalm.dev/r/6fe34dee75

```php
<?php
/**
 * get a function's arg variable names, e.g. function test( $hello, $world )
 * @param string $function_name name of the function
 * @param class-string $class_name if its a method instead of a function, you need to pass the class name of the method as second arg
 *
 * @return bool
 *
 * @psalm-suppress InvalidParamDefault
 */
function get_function_arg_names( $function_name, $class_name = '' ) {
  // if its a class/method
  if ( !empty( $class_name ) ) {
    if ( !method_exists( $class_name, $function_name ) ) {
      return false;
    }
  }

  // truncated code for visualization
  return true;
}
```

**Comment by muglug** [comment]
The error is valid, and you shouldn't suppress it – instead make it nullable: https://psalm.dev/r/dc9d13ac6d

**Comment by kkmuffme** [comment]
I can't, the code is for WP which requires support back to PHP 5.6 an nullable is a feature of PHP7.1+

So what is the suggested way to handle this then if suppressing doesn't work?

**Comment by andrew-demb** [comment]
You can specify type as `class-string|''` or use default value `null` instead empty string (`= null`, type `class-string|null`).

**Comment by muglug** [comment]
Great suggestion @andrew-demb - here's an example: https://psalm.dev/r/d4cdd5510c

But also @kkmuffme you can use null defaults in PHP 5.6, as long as you remove the `?string`:  https://psalm.dev/r/9bd867a099

**Comment by kkmuffme** [comment]
ok, thank you
