### ISSUE TITLE
Checking against unexpected type

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2610]
Hi,

I'd be surprised if this issue was never discussed but I couldn't find it.

For libraries, it's very common to check against unexpected types. The user may send wrong types and it's the responsability of the library to output errors or handle this nicely.

I had this issue while working in https://github.com/Roave/BetterReflection/issues/525 (the goal is to have 100% type coverage in Psalm).

The issue here is that libraries documented for types that they want, but will try to deal with what they don't expect.

It's not possible to add Unwanted types to the documentation at the risk of confusing users

The concrete example I had look like that:
https://psalm.dev/r/a97bc83bdc

The only solution I see here is to add every type to "foo" doc, but it would not make sense.

It would be nice to have a way to handle that. Maybe an "UnexpectedType", or a tag to tell Psalm that a method is exposed as an API and that "RedundantConditionGivenDocblockType, TypeDoesNotContainType, DocblockTypeContradiction" should not complain?

**Comment by muglug** [comment]
This is by design – Psalm differentiates between contradictions of docblock types (where `DocblockTypeContradiction` and `RedundantConditionGivenDocblockType` issues are emitted) and signature type contradictions (where `TypeDoesNotContainType` and `RedundantCondition` are emitted).

Feel free to suppress issues that don't make sense given your codebase!

**Comment by muglug** [comment]
(notice how the second error is different: https://psalm.dev/r/6b66a2adfa)

**Comment by orklah** [comment]
@muglug Thanks for your answer.

Does a suppressed error about Mixed Type have an impact in the % of inferred type at the end?
