### ISSUE TITLE
get_defined_constants types

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2616]
[get_defined_constants](https://www.php.net/manual/fr/function.get-defined-constants.php) has an optional parameter, which, if set to true, will change the output by adding an array level with the category.

The current type in callmap is `array<string,int|string|float|bool|null|array|resource>`. I guess we could change the type to `array<string,int|string|float|bool|null|array|resource>|array<string, array<string,int|string|float|bool|null|array|resource>>` But maybe there's a better way to do that which use the value of the parameter?

**Comment by muglug** [comment]
That's something you could add a PR for with a ReturnTypeProvider, but I'm not going to lose sleep over it.
