### ISSUE TITLE
query: re str_replace

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2617]
so I'm noticing that `str_replace()` doesn't quite behave as expected under psalm:

* if `$subject` is `array<empty, empty>`, the return value is `array<empty, empty>` https://3v4l.org/nDsfR https://psalm.dev/r/1e3345aa46
* if `$subject` is `list<scalar|null>`, the return value is `list<string>`
* if `$subject` is `list<scalar|null|T1|T2|...|Tn>` where `Tx` is known but not scalar or null (have not checked resource), then return value is `list<string|T1|T2|...|Tn>`
* if `$subject` is `array<string, T1>`, then the return value is `array<string, T2>` (where `T2` is `T1` mutated by other rules) https://3v4l.org/ereTU
* * similarly, if `$subject` is `array{foobar:T1, 1:T1, 2:T1}` where `T1` is `scalar|null`, then the return value is `array{foobar:string, 1:string, 2:string}` https://3v4l.org/7bh1C

is an array `$subject` sufficiently known in common usage to warrant PRing?

**Comment by muglug** [comment]
I don't think this is really ever much of an issue, but if you want feel free to create a `ReturnTypeProvider` with these rules.
