### ISSUE TITLE
simplexml_import_dom can return false

### ISSUE THREAD

**Issue by eclipxe13** [vimeo/psalm#262]
According to http://php.net/manual/en/function.simplexml-import-dom.php#refsect1-function.simplexml-import-dom-returnvalues the function `simplexml_import_dom` can return `false`.

The following code throws:

```
ERROR: TypeDoesNotContainType
Cannot resolve types for $simpleXmlElement - SimpleXMLElement does not contain false
```

```php
<?php
// ...
/** @var \DOMElement $element */
$simpleXmlElement = simplexml_import_dom($element);
if (false === $simpleXmlElement) {
    // ...
}
```

I think this should recognize that `simplexml_import_dom` can return `false`.

Thanks for your amazing project!

**Comment by muglug** [comment]
Fixed. Glad you're finding it useful!
