### ISSUE TITLE
array_filter inference broken for arrow functions

### ISSUE THREAD

**Issue by slepic** [vimeo/psalm#2627]
I have this piece of code that filters an array<A|B> based on value type effectively restricting the return type of the array_filter call to array<X>. Psalm is not able to infer this type reduction and so I have to introduce a variable and add comment informing psalm (and anyone else) that array<X> is the actualy type returned by array_filter
```
interface X {}
class A {}
class B implements X {}
class P {
  private X $x;
  function __construct(X $x) {$this->x = $x;}
}

\array_map(
  fn($x) => new P($x),
  /** @var array<string, X> $dummy psalm would scream on the above line */
  $dummy = \array_filter(['a' => new A(), 'b' => new B()], fn($x) => $x instanceof X)
);
```
It would be nice if psalm could infer the type, but I have no idea if that's even possible...

PS: PHP 7.4 arrow functions are used in the snippet but that is not necesary to reproduce the problem I believe

**Comment by slepic** [comment]
Yes, if the comment is there, no issues. But if the dummy is removed I get this:
```
Psalm output (using commit 389af1b):

ERROR: PossiblyInvalidArgument - 11:19 - Argument 1 of P::__construct expects X, possibly different type A|B provided
```

**Comment by muglug** [comment]
This is a simple bug –  there's different behaviour for arrow functions: https://psalm.dev/r/2cb63c9069

**Comment by slepic** [comment]
@muglug Aha nice, when I dont use arrow function, it is ok without the dummy comment.
