### ISSUE TITLE
`resource` is a reserved word in return context

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2629]
* https://psalm.dev/r/002bc5ac12 https://3v4l.org/dUYZO
* https://psalm.dev/r/60a9ad51ed https://3v4l.org/XvTPh

**Comment by muglug** [comment]
If you actually call `foo()` you'll see the fatal errors.

**Comment by weirdan** [comment]
> If you actually call `foo()` you'll see the fatal errors.

You can declare a class named resource, and there won't be fatal errors (see above).

**Comment by muglug** [comment]
> You can declare a class named resource, and there won't be fatal errors (see above).

Yeah, but that's really not great – you can declare it in a namespace and Psalm won't complain.

**Comment by SignpostMarv** [comment]
> If you actually call `foo()` you'll see the fatal errors.

my bad, I suspected I already checked this earlier & that's why- didn't check return ¬_¬

**Comment by muglug** [comment]
@SignpostMarv I know it's tempting but (in order to avoid overwhelming me) it'd be great if you could avoid _searching_ for potential Psalm bugs (or potential failures to infer code in certain situations). Obviously if you run into bugs in the course of writing your own code, please still ticket.

I'm focussed on issues that may prevent people from using Psalm, and issues where it fails to detect bugs in commonly-occurring code.

**Comment by SignpostMarv** [comment]
> @SignpostMarv I know it's tempting but (in order to avoid overwhelming me) it'd be great if you could avoid _searching_ for potential Psalm bugs

filing bugs discovered in the course of writing code at the dayjob under the personal account in the event I'm able to fix them on my own time.

**Comment by SignpostMarv** [comment]
> I'm filing bugs discovered in the course of writing code at the dayjob under the personal account in the event I'm able to fix them on my own time.

i.e. bugs/queries filed mon-fri, 9-5 are found in the course of doing work at the dayjob, bugs/queries filed outside those hours are stuff I've discovered in the course of working on my personal projects.

**Comment by muglug** [comment]
You've filed plenty of bugs that have helped make the project better for everyone.

I guess it'd be great if you sent a few more PRs, especially ones that fix [things I've marked as bugs](https://github.com/vimeo/psalm/issues?q=is%3Aopen+is%3Aissue+label%3Abug), so as to lighten my load a little.
