### ISSUE TITLE
Additional annotations @psalm-return, @psalm-param, @psalm-var

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#263]
Would it be possible to use an additional annotation, similar to `@return` to annotate types in Psalm syntax and that would take precedence over standard PHPDoc annotations? At the moment I am forced to pick wether to support Psalm or PhpStorm, and it's not a good choice to make.

Something like
```
/**
 * @param int[] $userIds
 * @return User[]
 * @psalm-param array<int,int> $userIds
 * @psalm-return array<int,User>
 */
public function findUsersByUserIds(array $userIds): array {
   ...
}
```

**Comment by muglug** [comment]
`@psalm-return` is supported, but not `@psalm-param` yet - will add that

**Comment by vasily-kartashov** [comment]
Great! Would it be possible to add `@pslam-var` as well?

**Comment by muglug** [comment]
Yup, added them all. Thanks for the suggestion!
