### ISSUE TITLE
sort functions considered impure?

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#2631]
Hi,

In 690209d8e5d432938e2099c8b118872404e15ff1 usort() and uasort() have lost the `@psalm-pure` annotations.

Was it an expected change?

https://psalm.dev/r/fca3adb346

**Comment by weirdan** [comment]
I guess it's expected, since the callback is not guaranteed to be pure.

**Comment by LeSuisse** [comment]
`array_filter()` and `array_map()` also use a callback but can be used in a pure function (#2112).

https://psalm.dev/r/6a8f54342d
