### ISSUE TITLE
LSP crashing in PhpStorm with UnanalyzedFileException

### ISSUE THREAD

**Issue by derekhamilton** [vimeo/psalm#2633]
I'm running into what looks like is described in #1621 but with an up-to-date version of psalm. Configuring psalm to run using LSP in PhpStorm following the [documentation](https://psalm.dev/docs/running_psalm/language_server/#phpstorm), if I start typing, the language server will crash with the message

```
LanguageServer for definition exe : path /usr/bin/php args : /var/www/testing/vendor/vimeo/psalm/psalm-language-server, project Project (name=testing, containerState=ACTIVE, componentStore=/var/www/testing)  keeps crashing due to 
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Psalm\Exception\UnanalyzedFileException: /var/www/testing/app/Http/Controllers/IndexController.php is not open in /var/www/testing/vendor/vimeo/psalm/src/Psalm/Codebase.php:1277
```

Output of `psalm --version`

`Psalm 3.8.2@90d6b73fd8062432030ef39b7b6694b3902daa31`

**Comment by muglug** [comment]
Do you run Psalm on the project outside of PHPStorm?

**Comment by derekhamilton** [comment]
Yes, I'm able to run it directly on the project, as well as have it fully working in neovim with ale without issue.

**Comment by muglug** [comment]
Mind running `--clear-gobal-cache` and restarting PHPStorm? I’ve no idea why the behaviour’s different between PHPStorm and neovim

**Comment by derekhamilton** [comment]
I do get the same result after running `--clear-global-cache`. Threw in a plugin reinstall and a PhpStorm reinstall for good measure. I'll have to try it on another machine, too, that I haven't done yet.

**Comment by derekhamilton** [comment]
Using a different computer, same OS, install PhpStorm, install psalm, configure and it works, no issues. Still no idea what's going on with it crashing. I've tried multiple projects so it's not catching on one specific thing.

**Comment by HenkPoley** [comment]
I ran into this same exception, but with a codebase that should make psalm cry in a corner. So I didn't report it.

**Comment by muglug** [comment]
So I think it's very likely that the plugin is sending incorrect commands to Psalm, but I've made sure no exception is thrown because of it.
