### ISSUE TITLE
Allow calling isset() to check if properties are initialized

### ISSUE THREAD

**Issue by jaikdean** [vimeo/psalm#2650]
With typed properties in PHP 7.4, we might need to check if they are initialized before accessing them via `isset()` or `??`; for example to set a value on first access. Currently this throws a `TypeDoesNotContainType`.

I'm using the current latest release version 3.8.3.

https://psalm.dev/r/a684c62bc4

**Comment by muglug** [comment]
If it _can_ be null after construction, it should be marked as `?int`: https://psalm.dev/r/5b274d5262

**Comment by jaikdean** [comment]
That's a slight logical change as it disallows `null` as an explicit value of the property, but will work in this case.
