### ISSUE TITLE
Psalm ignores arithmetic precedence

### ISSUE THREAD

**Issue by l-x** [vimeo/psalm#2651]
When `strictBinaryOperands` is set to `true` in the psalm config file, psalm fails to respect the precedence in arithmetic expressions:

```php
$foo = 1 / 2 + 0.5;
```
leads to
```
InvalidOperand - [...] - Cannot add ints to floats
```

**Comment by jaikdean** [comment]
This works fine in the latest release version of Psalm.

https://psalm.dev/r/c014241c90

**Comment by l-x** [comment]
@jaikdean No, it does NOT work in 3.8.3. psalm.dev does not set `strictBinaryOperands="true"`

**Comment by jaikdean** [comment]
Ah sorry, my mistake!

**Comment by muglug** [comment]
@l-x it's not ignoring arithmetic precedence – the issue is that Psalm doesn't know the value of `int / int` – it could be a `float` or an `int`. You can fix by casting the numerator to `float`:

```php
$x = (float) 1/2 + 0.5;
```
