### ISSUE TITLE
@psalm-var use inside a function never triggers an INFO

### ISSUE THREAD

**Issue by HenkPoley** [vimeo/psalm#2655]
```php
/** @return false|string */
function foo() {
  /** @psalm-var int $a */
  $a = ['obviously' => 'not an int'];
  
  return json_encode($a);
}
```

I'm not sure, but shouldn't that @psalm-var emit some kind of problem?

psalm.dev repoduction: https://psalm.dev/r/93d3d707eb

Psalm 3.8.3@389af1bfc739bfdff3f9e3dc7bd6499aee51a831

**Comment by HenkPoley** [comment]
I tripped onto this when trying to nail down the syntax of some arrays that get returned as JSON.

**Comment by weirdan** [comment]
Docblocks override inferred types. Psalm doesn't have a notion of statically defined type for variables.

**Comment by HenkPoley** [comment]
So there is no way to assert anything about that $a ?

E.g., that it has an 'id' that is an int or something.

**Comment by weirdan** [comment]
Basically there's no way to typecheck assignments to variables (unlike, say, properties).

**Comment by HenkPoley** [comment]
E.g. put the part that builds the array into a function, and then you can use psalm to check validity of the array?

**Comment by weirdan** [comment]
Yeah, that's one way to do it. Or you can probably drop the docblock and let psalm figure types out.
