### ISSUE TITLE
Are there ways to annotate (serialized data) caches?

### ISSUE THREAD

**Issue by HenkPoley** [vimeo/psalm#2656]
E.g. that the type of the cache writer 'teleports' to the cache reader function ?

Psalm won't be able to prove anything. But it would be nice for checking correctness elsewhere.

**Comment by muglug** [comment]
Do you have an example? I don't know what you're talking about.

**Comment by HenkPoley** [comment]
```php
<?php

use Illuminate\Support\Facades\Cache;

/** @param SomeObject $a */
function writeToCache($a): void {
    Cache::forever('KeyToStoreThisCache', $a);
}

/** @psalm-return teleport from writeToCache() */
function readFromCache() {
    return Cache::get('KeyToStoreThisCache');
}
```

I guess the new undocumented @psalm-type could do some of that.

**Comment by muglug** [comment]
Yeah, beyond that I won't support this annotation, at least for the forseeable future.

**Comment by HenkPoley** [comment]
Are there ways to make @psalm-type not do a 'type alias', but that it has to be an exact match (e.g. 'NewType')?

https://psalm.dev/r/a2bd6f3b93

Psalm will not warn if you mix Apple and Banana in the linked example.

It would be nice to protect my code from mixing different IDs from database tables. All ints, all different meanings.

**Comment by muglug** [comment]
This is essentially nominal typing, something that Psalm will likely never properly support because it’s not supported by the language. 

You can hack around it by creating container classes like `class UserId {}`.

**Comment by HenkPoley** [comment]
Thanks for the reply. I've seen those workarounds using classes. Kinda cool from an academic view, but not very practical.
