### ISSUE TITLE
Inconsistent warnings on object properties vs method parameters

### ISSUE THREAD

**Issue by hexmode** [vimeo/psalm#2659]
Compare (a)[type provided on property](https://psalm.dev/r/2b64be0cf8) vs (b)[type not provided on property](https://psalm.dev/r/2c920b6a2c) while still being provided in a docblock and compare both with (c)[a type provided on the method parameter but not the property](https://psalm.dev/r/5325f75a64)

The code works identically, but for (a) and (c) Psalm complains that "Property Test\Tmp::$user does not have a declared type".  Putting the type on the property declaration itself seems to mitigate this.

Meanwhile, despite the types being provided for method parameters in (c), Psalm complains that it "Could not infer return type" even though it is clearly a string.

Expected result:

* If a type is provided for a property in a docblock, it should work the same as if it is declared in the code. There should be no "Property ... does not have a declared type" when it is provided by the docblock.
* If you want to keep the current behavior,  then there should be a similar complaint about method parameters without types declared in the code.
* Psalm should infer that return type in (c) is a string since the code is clearly typed that way in the method parameters.

**Comment by weirdan** [comment]
`@param` is invalid on properties. You want `@var` there.

**Comment by weirdan** [comment]
See https://psalm.dev/r/110bbe906f

**Comment by hexmode** [comment]
Thanks. This leaves my third item: "Psalm should infer that return type in (c) is a string since the code is clearly typed that way in the method parameters."

**Comment by weirdan** [comment]
Psalm complains you're returning mixed where you declared you want to return string. And it's mixed because Tmp::$user has no type specified. So it really works as expected.

**Comment by hexmode** [comment]
Maybe there is some way that a variable's type could be changed between the assignment and the return.  I don't know of one, but maybe there is.

So, despite the property itself not being typed, it is clear that the method is returning a string.

But this isn't a hill I'm willing to die on, so feel free to close this.

**Comment by weirdan** [comment]
Currently inferences do not transcend function boundaries. Changing that would increase both the analysis complexity and a chance of incorrect inferences, not to mention that you still have to stop at some depth.
