### ISSUE TITLE
SoapClient not found

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2664]
Hi,

There are some skipped tests in CI because of SoapClient not being found
https://ci.appveyor.com/project/muglug/psalm/builds/30216882#L24894

I had the same issue at work but I thought it was because of our whacky codebase. Now that I see the same thing here, I wonder what's going on. I checked and SoapClient is indeed in the ClassMap.

Can I do something to fix it?

**Comment by LeSuisse** [comment]
Do you have ext-soap enabled in the environment running Psalm?

**Comment by orklah** [comment]
> Do you have ext-soap enabled in the environment running Psalm?

That could be it, I will check that tomorrow

**Comment by orklah** [comment]
ext-soap was indeed disabled. I forgot Psalm was using native extensions and not only stubs. There are tests being skipped on appveyor because of missing extension but I'm not sure it's an issue because the tests will pass on other CI tools. I'm closing this issue.
