### ISSUE TITLE
Strange LessSpecificImplementedReturnType

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#2667]
https://psalm.dev/r/eca60d7782

I am almost sure there is no issue on my side and it's a bug in psalm.

Expected: No issues

**Comment by someniatko** [comment]
I have found out, that if i add
```
  /** @return TView */
```
annotation to the `AbstractViewer#view()`, the issue is gone. However, i see no reason for doing this, as long as AbstractViewer's TView is exactly equal to ViewerInterface's T

**Comment by muglug** [comment]
Removing the PHP return types fixes the issue: https://psalm.dev/r/22a80a4ecf

**Comment by someniatko** [comment]
@muglug I see. So, it means the native return type declaration takes precedence over inherited PHPDoc's one?

**Comment by muglug** [comment]
Yeah, but it shouldn't.
