### ISSUE TITLE
Erroneous type detection with argument unpacking

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#2668]
The following code, while admittedly very ugly (it's from our test-suite using a @dataProvider - so it's somewhat excusable), is correct:

```php
$a = [new DateTime(), 1, 2];
function f(DateTime $d, int $a, int $b): void
{
  printf('%s %d, %d', $d->format('Y'), $a, $b);
}

f(...$a);
```

but psalm warns: 

```
ERROR: PossiblyInvalidArgument - 9:6 - Argument 1 of f expects DateTime, possibly different type DateTime|int(1)|int(2) provided
```

It looks like it's not seeing the argument unpacking.

https://psalm.dev/r/59b818b053

**Comment by muglug** [comment]
The specific issue in the example is fixed in 36f5c51.
