### ISSUE TITLE
Update baseline doesn't work

### ISSUE THREAD

**Issue by snapshotpl** [vimeo/psalm#2674]
```
psalm --update-baseline
```
returns standard output, like after analyse. And my `baseline.xml` doesn't change. After remove current baseline and init new file is fine.

**Comment by muglug** [comment]
`--update-baseline` just prunes entries. `--set-baseline=your-file.xml` will also create them.

**Comment by JoppeDC** [comment]
I agree that this is strange behaviour, I expect an `--update-baseline` to update the baseline file, including new entries.
