### ISSUE TITLE
GitHub Actions formatter

### ISSUE THREAD

**Issue by alexeyshockov** [vimeo/psalm#2678]
What do you think about implementing a formatter for GitHub Actions, to highlight errors directly in the pull requests "Changes" tab? Using [GitHub-specific `::error` and `::warning` format](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-error-message-error).

It could be a separate package (like https://github.com/mheap/phpunit-github-actions-printer for PHPUnit) or bundled with Psalm directly... I'm not sure what's better.

**Comment by muglug** [comment]
Add `--output-format=github` to get this working!

**Comment by alexeyshockov** [comment]
Thanks a lot for the quick fix :)
