### ISSUE TITLE
Inconsistent type inference for iterators with and without templates

### ISSUE THREAD

**Issue by tux-rampage** [vimeo/psalm#2682]
A templated function or class seem to infer types through many `new` instanciations of templated classes while functions without templating don't.

See: https://psalm.dev/r/2ec1d65e4f

**Comment by weirdan** [comment]
The inference is consistent when probles with the snippet are fixed: https://psalm.dev/r/20b9fd46a1
The cause seems to be that Psalm doesn't have a template definition for `IteratorIterator` (you can try adding this to `src/Psalm/Internal/Stubs/CoreGenericClasses.php`).

**Comment by tux-rampage** [comment]
That explains the issue, but I found another one with Traversable (Which has a template definition):

https://psalm.dev/r/aa681dc42c

**Comment by muglug** [comment]
I've fixed the main issue (added generic forms of IteratorIterator) and it now works: https://psalm.dev/r/ca4e17776a
