### ISSUE TITLE
variable misdetected as unused

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#2685]
https://psalm.dev/r/5cfcd5e9fd

interestingly enough, if you rewrite the sample to remove the indirection via `function a()` it doesn't complain.

Granted, the assignment isn't *really* needed, but I wouldn't say that `$c` is *never referenced*

**Comment by pilif** [comment]
the reported also seems to be not suppressible via `@psalm-suppress`

https://psalm.dev/r/c56c3547d9

**Comment by muglug** [comment]
Yeah it's not properly counting the arguments to a callable: https://psalm.dev/r/7536adce3e

**Comment by muglug** [comment]
worse example: https://psalm.dev/r/bac59b0e54
