### ISSUE TITLE
psalm doesn't know about $GLOBALS

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#2686]
https://psalm.dev/r/816ca70058

I'm not sure this needs fixing because who in their right mind uses global variables and $GLOBALS, but this is correct code and yet it causes 3 warnings.

(I'm so sorry for reporting all of these issues in what's obviously horrendous code - psalm is *so good* I let it run on some pretty bad legacy that nobody should ever speak about)

**Comment by orklah** [comment]
Partial support (probably not perfect, especially on global namespace) could probably be achieved pretty easily, Psalm carry around a $context variable with a `vars_in_scope` property that's just an array with all the known variables and their type. All that would be needed is a special case on ArrayFetchAnalyzer when the variable name is $GLOBALS.

Feel free to work on it. I'll close this in the meantime, it's probably not worth keeping in mind it exist
