### ISSUE TITLE
vprintf and printf are treated differently

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#2687]
https://psalm.dev/r/89a13d8115

both `vprintf` and `printf` return `int`, but only in case of `vprintf` psalm warns about the unused return value via "the call to vprintf is not used".

I would argue that the behavior with `printf` is more correct I don't think anybody really cares or should care about how many characters were just printed to stdout.

**Comment by pilif** [comment]
(also, shouldn't it complain about using %d with a string argument? - I just noticed that - was an oversight when creating the snippet)

**Comment by erunion** [comment]
There appears to be some discrepancies in how `vsprintf` is documented and how it actually functions. Psalm is reporting it as not being used because it's documented as only returning a value, not actually printing something out.
