### ISSUE TITLE
Don't emit LoopInvalidation if loop terminates after modification?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#2688]
e.g. https://psalm.dev/r/a2c6431c67

If there's always a return/break/throw, then the loop condition being invalidated shouldn't matter, unless I'm overlooking something.

> Emitted when logic inside a loop invalidates one of the conditionals of the loop

**Comment by muglug** [comment]
This stems from me not totally understanding how `foreach` worked when I first added this in late 2017. I'll make sure `foreach` iterables are not taken into consideration
