### ISSUE TITLE
InvalidPropertyAssignmentValue $this->conn with declared type 'null|resource' cannot be assigned type 'closed-resource'

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#2689]
See https://psalm.dev/r/3f8265f7fb

It succeeds for just `@var resource`, but not `@var resource|int`, `@var resource|null`, etc.

**Comment by muglug** [comment]
Not a bug – Psalm now supports `closed-resource`: https://psalm.dev/r/5d60d73ff5
