### ISSUE TITLE
PhpStorm generic annotations aren't resolved for objects

### ISSUE THREAD

**Issue by derekhamilton** [vimeo/psalm#2692]
```
/**
 * @return Collection|Foo[]
 */
 function foo()
```

When used `foo()->toArray()` with a method call results in an error `Cannot call method on possible array<array-key, Foo>` instead of interpreting it as a Collection object.

https://psalm.dev/r/e58e32c74f

**Comment by muglug** [comment]
For the PHPStorm substitution to kick in, the class has to implement `Traversable`: https://psalm.dev/r/c1133b430e

**Comment by muglug** [comment]
Alternatively, use `@psalm-return Collection<int, Foo>`
