### ISSUE TITLE
Feature Request: Add check for placeholder count vs arguments count mismatch for sprintf()

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#2694]
psalm currently doesn't report any error for such cases: https://phpstan.org/r/d0c449de-5105-48ca-ab18-e6a192ecd527

**Comment by ADmad** [comment]
@psalm-github-bot  There you go dumb bot :slightly_smiling_face: https://psalm.dev/r/1aa31eadbc

**Comment by weirdan** [comment]
It seems there's a plugin by @boesing for that: https://github.com/boesing/psalm-plugin-stringf

**Comment by ostrolucky** [comment]
Looks like this feature has been added meanwhile https://psalm.dev/r/1aa31eadbc

**Comment by orklah** [comment]
It was :)
