### ISSUE TITLE
Static variable breaks pure function (while static property does not)

### ISSUE THREAD

**Issue by alexeyshockov** [vimeo/psalm#2696]
I'm not really sure what's the correct behaviour, so...

https://psalm.dev/r/a956b1d865 — this is an example, with two cases (both identical, but implemented slightly different). In the first case (`Number1::zero()`) a static property is used. Psalm doesn't show any errors here.

The second case (`Number2::zero()`) uses a static variable, and here Psalm raises "Cannot use a static variable in a mutation-free context" error.

IMO Psalm should be consistent in both solution and raise two errors respectively or be silent.

**Comment by muglug** [comment]
Accessing static properties should also be prohibited!

**Comment by alexeyshockov** [comment]
OK, good, thanks :)

The another question, not directly related to the bug. Do you see a way to use `@psalm-pure` on method like above? They are not strictly pure by definition, but they pure by behaviour, because the static properties/variables are used only for cache. I mean, I can simply suppress the error, but maybe there is a proper way to handle this?

**Comment by muglug** [comment]
I'd just suppress the error. Hack has a `<<memoize>>` annotation to achieve the same effect (which is presumably reasonably pure), but that's a language-level thing.

**Comment by alexeyshockov** [comment]
Thanks a lot!
