### ISSUE TITLE
Psalm's templating annotation conflicts with PHPStan Generics

### ISSUE THREAD

**Issue by zonuexe** [vimeo/psalm#2698]
PHPStan 0.12 introduced Generics notation for Iterator/Generator.
([Generics in PHP using PHPDocs - Ondřej Mirtes - Medium](https://medium.com/@ondrejmirtes/generics-in-php-using-phpdocs-14e7301953))

It has the following notation:

```
@phpstan-return Generator<TKey, TValue, TSend, TReturn>
```

It conflicts with [Psalm's Templated annotation](https://psalm.dev/docs/annotating_code/templated_annotations/).

`Psalm 3.8.3@389af1bfc739bfdff3f9e3dc7bd6499aee51a831` outputs the following in [my project](https://github.com/phppg/playground/commit/40fc2ab598e849da8d057de9709c28d54ef2c6a9):

```
ERROR: TooManyTemplateParams - src/Invoker.php:17:24 - Symfony\Component\Process\Process<string, string> has too many template params, expecting 0
     * @phpstan-return Process<string,string>


ERROR: TooManyTemplateParams - src/Invoker/ProcessInvoker.php:43:24 - Symfony\Component\Process\Process<string, string> has too many template params, expecting 0
     * @phpstan-return Process<string,string>


ERROR: TooManyTemplateParams - src/Invoker/ProcessInvoker.php:53:62 - Symfony\Component\Process\Process<string, string> has too many template params, expecting 0
    public function invoke(Code $code, Input $input = null): Process


ERROR: TooManyTemplateParams - src/Invoker/ProcessInvoker.php:59:9 - Symfony\Component\Process\Process<string, string> has too many template params, expecting 0
        $proc->mustRun();


ERROR: TooManyTemplateParams - src/Process/SymfonyProcessFactory.php:15:24 - Symfony\Component\Process\Process<string, string> has too many template params, expecting 0
     * @phpstan-return Process<string,string>
```

This issue is partially pointed out in #2567, but not only `@implements`, other tags have the same problem.

**Comment by zonuexe** [comment]
Reproduced this issue in psalm.dev: https://psalm.dev/r/ae7acf2db9

**Comment by ondrejmirtes** [comment]
What PHPStan does is that it has backwards compatibility for `Foo<Bar, Baz>` from pre-generics days, where it means `Foo&iterable<Bar, Baz>`. So even if `Foo` isn't generic, `Foo<Bar, Baz>` might be valid.

@zonuexe Your code isn't technically correct, this has the same meaning:

```php
/**
 * @phpstan-return Iter
 */
```

as `Iter<string, string>`, because there's already `@implements IteratorAggregate<string,string>` above `Iter`.

**Comment by muglug** [comment]
So not a bug on Psalm’s end, I think?

**Comment by ondrejmirtes** [comment]
What I think OP is asking for is compatibility with PHPStan's interpretation - for `Foo<Bar>` and `Foo<Bar, Baz>`, when Foo isn't generic, do `iterable<Bar>&Foo` and iterable<Bar, Baz>&Foo` intersection.

**Comment by muglug** [comment]
> What I think OP is asking for is compatibility with PHPStan's interpretation - for `Foo<Bar>` and `Foo<Bar, Baz>`, when Foo isn't generic, do `iterable<Bar>&Foo` and `iterable<Bar, Baz>&Foo` intersection.

Yeah that feels sort of bad IMO. Better to make the issue clear up-front.

**Comment by ondrejmirtes** [comment]
PhpStorm also kind-of interprets it like that: https://blog.jetbrains.com/phpstorm/2018/09/phpstorm-2018-3-eap-183-2635-12/ (headline "PHPDoc PSR-5 <generic> collection type hints")

**Comment by zonuexe** [comment]
@ondrejmirtes 
Thank you for response. No problem with fixing as you say.
https://psalm.dev/r/0f2140326c

**Comment by zonuexe** [comment]
Close to the real case (Symfony\Process module not annotated for PHPStan) is code like this:

https://psalm.dev/r/aff71ec4be

**Comment by muglug** [comment]
@zonuexe you can always stub out those classes (and I'd recommend it) until Symfony supports the template annotations natively.

**Comment by zonuexe** [comment]
@ondrejmirtes @muglug Thank you!

**Comment by ThomasLandauer** [comment]
In case somebody is getting this error on Doctrine Repository's: Just install [weirdan/doctrine-psalm-plugin](https://github.com/weirdan/doctrine-psalm-plugin) :-)
