### ISSUE TITLE
By-reference $variable with default null value like preg_match

### ISSUE THREAD

**Issue by iquito** [vimeo/psalm#2701]
I am trying to properly adjust the type hints in an open source library I am using (to make a pull request and have better static analyzer support) which as one part of it wraps the PHP internal `preg_` functions to throw exceptions instead of returning false. When wrapping `preg_match` I have encountered some problems as seen in this heavily simplified example (https://psalm.dev/r/0bfc425c9e):

```php
class preg
{
    public static function match(string $pattern, string $subject, array &$matches = null): int
    {
        return preg_match($pattern, $subject, $matches);
    }
}

preg::match('pattern', 'subject', $matches);

foreach ($matches as $match) {
}
```

Psalm complains about two things here:

```
ERROR: PossiblyNullIterator - 13:10 - Cannot iterate over nullable var array<array-key, mixed>|null

ERROR: PossiblyNullArgument - 7:47 - Argument 3 of preg_match cannot be null, possibly null value provided
```

With the first error Psalm thinks $matches might be null, which is a reasonable assumption usually yet is never the case in this example. How can Psalm be told that $matches will always be an array? Because otherwise people replacing `preg_match` with `preg::match` will get a lot of PossiblyNullIterator and PossiblyNullArrayAccess errors. As far as I can tell Psalm does handle this in a special way for the internal `preg_match` function, as these PossiblyNull errors do not show up when using preg_match directly, can this be type hinted in regular code too?

The second error is less impactful, as users of the library would not encounter it, yet as far as I can tell it is incorrect, as $matches can be null, preg_match will overwrite it anyway.

**Comment by muglug** [comment]
I think you want something like this: https://psalm.dev/r/7c54e11c8e

**Comment by iquito** [comment]
`@param-out` was exactly what I was looking for, thanks!
