### ISSUE TITLE
psalm (current master) gets entirely confused around ReflectionMehtod::getParameters()

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#2702]
https://psalm.dev/r/07d8a8476b

this is the simplest example I could make.  The confusion starts around the `getParameters()` call. When I use any other method on `ReflectionMethod`, everything works as expected.

Also note that line 20 references an undefined variable which psalm doesn't see in addition to all the bogus errors reported.

If I change lines 11 to 14 to not use `ReflectionMethod::getParameters()`, then that undefined variable is seen and all other issues go away.

Trying to understand what's going on there is way beyond my current skills related to the codebase, so all I can do is report this here.

**Comment by muglug** [comment]
Fixed in dec274a1fe1ff268e0aec00a9215a0064d003e8a, surfaced (but not introduced) by https://github.com/vimeo/psalm/pull/2675

**Comment by pilif** [comment]
holy hell - you're faster than lightning 😊
