### ISSUE TITLE
[InaccessibleProperty] Accessing protected property using Closure

### ISSUE THREAD

**Issue by shyim** [vimeo/psalm#2706]
I am accessing a protected property using a Closure. https://psalm.dev/r/92008a39ee
But psalm throws InaccessibleProperty. Maybe this special case is not implemented?

**Comment by muglug** [comment]
Yeah, I'm hesitant to mark this as a bug because it's rarely-seen (at least by me) in PHP code.

**Comment by ShiraNai7** [comment]
`@psalm-scope-this` can be used in this case (looks like it isn't mentioned in the docs):

https://psalm.dev/r/ec2c2dca0e

But I agree that this isn't very common (or clean) use-case. I've only used it for temporary hacks.

**Comment by orklah** [comment]
@psalm-scope-this sound enough for the use-case. I'm closing this.
