### ISSUE TITLE
Execution crashes when Couchbase SDK is loaded

### ISSUE THREAD

**Issue by tlieschenfon** [vimeo/psalm#2711]
Hi,

we're using php7.3.14 on Ubuntu from Ondrej Sury's repository and installed the couchbase extension using pecl. When enabling this extension, vimeo crashes everytime it encounters this line of code

`$query = CouchbaseN1qlQuery::fromString($n1ql);`

where $n1ql is just a string representation of the query command. CouchbaseN1qlQuery is an extension internal alias for Couchbase\\N1qlQuery.

`Uncaught InvalidArgumentException: Could not get class storage for couchbasen1qlquery in /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:47
Stack trace:
#0 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php(319): Psalm\Internal\Provider\ClassLikeStorageProvider->get('couchbasen1qlqu...')
#1 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php(156): Psalm\Internal\Analyzer\ClassLikeAnalyzer::checkFullyQualifiedClassLikeName(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), 'CouchbaseN1qlQu...', Object(Psalm\CodeLocation), Array, false, false, false)
#2 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(139): Psalm\Internal\Analyzer\Statements\Expression\Call\StaticCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\StaticCall), Object(Psalm\Context))
#3 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(234): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\StaticCall), Object(Psalm\Context))
#4 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(120): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Variable), Object(PhpParser\Node\Expr\StaticCall), NULL, Object(Psalm\Context), NULL)
#5 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(683): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Assign), Object(Psalm\Context), false, Object(Psalm\Context), true)
#6 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(526): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#7 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1650): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#8 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(813): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#9 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(201): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#10 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(335): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#11 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(567): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(91, '/host_mnt/c/Use...')
#12 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(258): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#13 /home/tliesche/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(528): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false)
#14 /home/tliesche/.composer/vendor/vimeo/psalm/src/psalm.php(553): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/host_mnt/c/Use...', false)
#15 /home/tliesche/.composer/vendor/vimeo/psalm/psalm(2): require_once('/home/tliesche/...')
#16 {main}
(Psalm 3.8.3@389af1bfc739bfdff3f9e3dc7bd6499aee51a831 crashed due to an uncaught Throwable)`

Any ideas on how to solve this problem? When not loading the Couchbase extension we run into endless UndefinedDocblockClass and UndefinedClass warnings.

**Comment by muglug** [comment]
Unless you can provide a docker image or similar with that extension, I won't be able to reproduce – it doesn't look like that class is part of the most recent release of that SDK maintained here: https://github.com/couchbase/php-couchbase

Neverthelsss, you should be able to use stubs from that old source code I found here: https://github.com/brett19/php-couchbase/tree/master/stub

You can include the stubs in your Psalm config: https://psalm.dev/docs/running_psalm/configuration/#ltstubsgt
