### ISSUE TITLE
Missing inference when using `[ClassName::class, 'method']` callables together with templated types?

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2719]
Found a relatively ugly one:

https://psalm.dev/r/3a73db700f
https://psalm.dev/r/daf61f63b6

In the examples above, psalm reports an issue when using `array_map([ClassName::class, 'method'], ...)`, and even infers `mixed` when the callable is used directly.

Potentially an edge case caused by the templated type, since removing it makes the issue go away:

https://psalm.dev/r/c79b52a659

Note that the callable type inference still doesn't work here, but I mostly added it to complete the example, and to see if it was somehow related.

**Comment by muglug** [comment]
Definitely feels like a bug, narrowed to https://psalm.dev/r/fc8a90b42d
The equivalent arrow function works fine: https://psalm.dev/r/37bdb54baa (and it's so much nicer to behold)
