### ISSUE TITLE
MixedArgumentTypeCoercion if argument name is different

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#2722]
https://psalm.dev/r/d46df351b7

**Comment by muglug** [comment]
I don't _think_ this is a bug. The implicit inherited documentation refers only to a param named `$argument` – it says nothing about `$changedArgument`.

**Comment by vudaltsov** [comment]
well, PHP itself inherits the signature regardless of the argument name

**Comment by muglug** [comment]
> PHP itself inherits the signature regardless of the argument name

It doesn't though – this is perfectly valid:

```php
class A {
  public function takesInput(array $array) : void {}
}

class AChild extends A {
  public function takesInput($mixed) : void {}
}

(new AChild())->takesInput("hello");
```

**Comment by muglug** [comment]
And by that logic I'd argue that PHPStan's behaviour here (newly-added) is incorrect: https://phpstan.org/r/552e0cc2-66dd-48bd-a6d4-cfbe9bdbf8f6

**Comment by zerkms** [comment]
> this is perfectly valid:

it's valid not because of changed argument name, but because of type widening: `(mixed $a): void` is compatible with `(array $a): void`.

**Comment by vudaltsov** [comment]
@muglug , based on your example, Psalm then should be enable to infer types for `X` either, because `$argument` has no type hint/declaration at all.

**Comment by vudaltsov** [comment]
@muglug , a counter-argument to my issue could be the following: in pure PHP when you change the argument name, but leave the type the same, code breaks. But that's wrong.

**Comment by weirdan** [comment]
@muglug guys are right here, parameter *names* have always been local to the function in PHP. It's the order that matters.

**Comment by muglug** [comment]
> parameter names have always been local to the function in PHP. It's the order that matters.

Yes, but I'm asking about the intent of documenting those parent type parameters – is it to apply to all arguments in that position, or just to apply to things with that name in that position?

**Comment by vudaltsov** [comment]
@muglug , to all arguments in that position, unless overridden by position in subclasses. Same as in PHP.

**Comment by weirdan** [comment]
> Yes, but I'm asking about the intent of documenting those parent type parameters – is it to apply to all arguments in that position, or just to apply to things with that name in that position?

To put it another way - if I'm free to choose the parameter names for my implementation when extending/implementing non-generic class/interface, extending generic one should behave the same.

**Comment by zerkms** [comment]
And while we're all here, could you please have a look at my report https://github.com/vimeo/psalm/issues/2721 which was shaded by this one :-D

**Comment by muglug** [comment]
Fixed after I spent 20 minutes debugging an issue caused by this
