### ISSUE TITLE
Confusion regarding PossiblyUndefinedArrayOffset

### ISSUE THREAD

**Issue by glen-84** [vimeo/psalm#2724]
https://psalm.dev/r/8569119e5b

I know that the type for `$tokens` needs to be improved, but I don't understand why there is an error on L19.

L16 asserts that `$tokens[$i]['orig_content']` is set, but that doesn't imply that the whole of `$tokens[$i]` is unset in the else branch?

Surely `$tokens[$i]['orig_content']` should be seen as unset in the else branch, and not the whole of `$tokens[$i]`?

It's accessed on L22 without errors. Uncommenting L14 also removes the error for some reason.

**Comment by muglug** [comment]
Move the `if (isset($tokens[$i]))` check into the `while` condition (where I think it belongs) and the errors go away: https://psalm.dev/r/4442e26dcd

**Comment by glen-84** [comment]
@muglug,

I wasn't suggesting that a workaround wasn't possible, but that the current behaviour for this code (which actually comes from the [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer/blob/dceec07328401de6211037abbb18bda423677e26/src/Standards/Squiz/Sniffs/Strings/DoubleQuoteUsageSniff.php#L57) project), appears to be wrong. Is it not a bug?

Here is a shorter version: https://psalm.dev/r/e3d0c6b658

Why is L11 an error, but not L14?

**Comment by muglug** [comment]
Yeah sorry, looking at this again there's a clear difference in how these two things are handled: https://psalm.dev/r/a1885833a4, and there shouldn't be

**Comment by muglug** [comment]
Having thought about this a bit more, Psalm will no longer treat this pattern as an error.

**Comment by glen-84** [comment]
@muglug Thanks a lot for looking into this, and for all the work that you do. It is much appreciated.
