### ISSUE TITLE
Support @psalm-private-mutate annotation

### ISSUE THREAD

**Issue by christian-kolb** [vimeo/psalm#2729]
With PHP 7.4 using public properties in a type safe way is finally possible. In some languages you have the concept of marking a property to be able to be read from outside the class, but not modified. Basically public get, but private set. 
Psalm already supports `@psalm-readonly` which prevents the property by being modified anywhere. It would be awesome to have a similar annotation which allows to modify the property with class methods. With this the public get, private set paradigm would be available to PHP users 🙂 
Please let me know when there is already concept within psalm with which I could get the same result, I haven't found one yet.

**Comment by muglug** [comment]
Have you read https://psalm.dev/articles/immutability-and-beyond?

**Comment by christian-kolb** [comment]
@muglug Yes, but thanks for the reminder (was a while ago). This might be a good example to help me explain what I want.

```
<?php

class Counter {
  /** @psalm-new-annotation */
  public int $count = 0;
  
  public function increment() : void {
    $this->count++;
  }
}

function makeCounter() : Counter {
  $a = new Counter();
  $a->increment(); // this is fine
  return $a;
}

function canNotUpdateDirectly(Counter $a) : Counter {
  $a->count = 10; // This is not allowed
}
```

So basically I can use a public property as getter, not as setter, but modify it through its class methods.

As far as I'm aware this behaviour can only made available with getter methods but not with psalm annotations. Basically I want to get rid of getters, because I have many instances where I only have them to get this result. And at the moment this means I have "clean" classes without getters and ones cluttered with them. It would be amazing if I could solve this issue with psalm 🙂

**Comment by muglug** [comment]
I think you're asking for `/** @psalm-external-mutation-free */` – does its use in the article line up with what you want?

**Comment by christian-kolb** [comment]
@muglug Kind of, but this only applies to methods, doesn't it? I would need it to be applied for classes and properties. I tried with psalm.dev, but it doesn't raise any issues: 

https://psalm.dev/r/69691fb410

It would describe the behaviour I want 🙂

**Comment by muglug** [comment]
OK, I understand now – if you contribute an implementation and/or documentation, I'll do the rest.

I suggest an annotation of `@psalm-private-set`

**Comment by christian-kolb** [comment]
Awesome, I have no idea how I would start an implementation for it. But I'm sure I can write documentation for it. `@psalm-private-set` sounds great. I'll start working on it tomorrow  🙂
