### ISSUE TITLE
LogicException: $this->classlike_storages should not be empty

### ISSUE THREAD

**Issue by cklm** [vimeo/psalm#2731]
Hi, I want to use psalm 3.8.3 on a symfony 3.4 project. I started with `psalm --init src 1` to create a config and run psalm. Soon, I get the following exception:

    Uncaught LogicException: $this->classlike_storages should not be empty in C:\path\vendor\vimeo\psalm\src\Psalm\Internal\Visitor\ReflectorVisitor.php:353
    Stack trace:
    #0 C:\path\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(200): Psalm\Internal\Visitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\TraitUse))
    #1 C:\path\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
    #2 C:\path\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
    #3 C:\path\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
    #4 C:\path\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Else_))
    #5 C:\path\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
    #6 C:\path\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
    #7 C:\path\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
    #8 C:\path\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
    #9 C:\path\vendor\vimeo\psalm\src\Psalm\Internal\Scanner\FileScanner.php(96): PhpParser\NodeTraverser->traverse(Array)
    #10 C:\path\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Scanner.php(606): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DebugProgress))
    #11 C:\path\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Scanner.php(389): Psalm\Internal\Codebase\Scanner->scanFile('C:\\projekte\\reg...', Array, false)
    #12 C:\path\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Scanner.php(497): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(8, 'C:\\path\\...')
    #13 C:\path\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Scanner.php(347): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
    #14 C:\path\vendor\vimeo\psalm\src\Psalm\Config.php(1719): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes))
    #15 C:\path\vendor\vimeo\psalm\src\psalm.php(512): Psalm\Config->visitComposerAutoloadFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), Object(Psalm\Progress\DebugProgress))
    #16 C:\path\vendor\vimeo\psalm\psalm(2): require_once('C:\\path\\...')
    #17 {main}
    (Psalm 3.8.3@389af1bfc739bfdff3f9e3dc7bd6499aee51a831 crashed due to an uncaught Throwable)

I assume, there some error in one of the files which psalm cannot handle, but I don't have a clue where to start.

Running psalm with `--debug` shows the following:

    $ vendor/bin/psalm --debug --no-cache
    Registering autoloaded files
    [truncated 600 lines]
    Parsing C:\path\vendor\symfony\symfony\src\Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface.php
    Scanning C:\path\vendor\symfony\symfony\src\Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface.php
    Parsing C:\path\vendor\symfony\symfony\src\Symfony\Component\Security\Core\Authentication\Token\TokenInterface.php
    Scanning C:\path\vendor\symfony\symfony\src\Symfony\Component\Security\Core\Authentication\Token\TokenInterface.php
    Parsing C:\path\vendor\symfony\symfony\src\Symfony\Bridge\Doctrine\ManagerRegistry.php
    Scanning C:\path\vendor\symfony\symfony\src\Symfony\Bridge\Doctrine\ManagerRegistry.php
    Uncaught LogicException: $this->classlike_storages should not be empty in C:\projekte\regw-konsole\vendor\vimeo\psalm\src\Psalm\Internal\Visitor\ReflectorVisitor.php:353

Any ideas?

**Comment by muglug** [comment]
Are you able to reproduce this in a new project? I think you might have a particular set of dependencies that leads to the error.

**Comment by cklm** [comment]
I'm sure now, that the problem is somewhere in parsing/scanning this file:
https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bridge/Doctrine/ManagerRegistry.php
It is reproducable in a fresh symfony 3.4-project (`composer create-project symfony/framework-standard-edition test "3.4.*"`, you need to switch to a newer php-version in config.platform.php in composer.json).

**Comment by muglug** [comment]
would you mind providing a test repo I can check out to reproduce this?

**Comment by cklm** [comment]
sure - please see here:
https://github.com/cklm/psalm-2731

Just `composer install` and `vendor/bin/psalm --debug` to reproduce it.

**Comment by muglug** [comment]
awesome, thanks!

**Comment by muglug** [comment]
I think this error is fixed with latest `dev-master`, though.

**Comment by cklm** [comment]
you are right - error does not occure in dev-master - thank you!

**Comment by muglug** [comment]
Fixed in b582c49, for the record

**Comment by edditor** [comment]
We have the same issue with some of our symfony 3.4 projects, thankfully I found this issue here.
Thanks a lot for the quick fixing of this issue! :)

**Comment by muglug** [comment]
I’ll release today
