### ISSUE TITLE
Specify enum by shared prefix

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#2739]
Given the class example at https://psalm.dev/docs/annotating_code/typing_in_psalm/#specifying-stringint-options-aka-enums

it's common to have a list of enum values, that belong together. Usually a list of possible statuses, e.g.

```php
class Subject {
  const STATUS_OK = 0;
  const STATUS_KO = 1;
}
```

Listing all possible statuses would be boring, as such i suggest

```
@param Subject::STATUS_* $status
```

Additionally it could allow any const using `Subject::* $status`, but it looks less like a known const type :/ so it could be confusing to reason about.

**Comment by muglug** [comment]
Create a PR for the documentation and I'll add the implementation

**Comment by ro0NL** [comment]
`@param A::SOME_*|A::SOME_X` should be marked redundant btw. Nice to have i guess :)

**Comment by muglug** [comment]
> @param A::SOME_*|A::SOME_X should be marked redundant

I won't bother with that, I don't think

**Comment by weirdan** [comment]
I had a perfect use-case for `*` today:
```php
/**
 * @psalm-type _LogLevel=LogLevel::EMERGENCY|LogLevel::ALERT|LogLevel::CRITICAL|LogLevel::ERROR|LogLevel::WARNING|LogLevel::NOTICE|LogLevel::INFO|LogLevel::DEBUG
 */
```
