### ISSUE TITLE
PDOStatement::fetchColumn() cannot return null

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#2741]
For some reason, Psalm pretends that [`PDOStatement::fetchColumn()`](https://www.php.net/manual/en/pdostatement.fetchcolumn.php) can return `false|null|string`:

https://psalm.dev/r/068bf355c9

This is weird, as:

- the [docs](https://www.php.net/manual/en/pdostatement.fetchcolumn.php) do not mark it as nullable,
- the [PHPStorm stubs](https://github.com/JetBrains/phpstorm-stubs/blob/e3b13456b9ca5ecb166925adeec574cefc270d9a/PDO/PDO.php#L1347) do not mark it as nullable,
- reflection gives no info about the return value,
- the [source code](https://github.com/php/php-src/blob/afdaa91170a1f7b0387cf577d957d4d6c015c136/ext/pdo/pdo_stmt.c#L1267-L1285) does not have any `RETURN_NULL` statement.

So how come `fetchColumn()` is considered nullable?

**Comment by muglug** [comment]
> So how come fetchColumn() is considered nullable?

Because it can return `null` (see https://github.com/phpstan/phpstan/pull/1886)

**Comment by BenMorel** [comment]
Oops. Of course.

**Comment by BenMorel** [comment]
Actually `fetchColumn()` can return more than `false|null|string`, see #2743.
