### ISSUE TITLE
!empty assertion on a shape is ignored

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#2742]
https://psalm.dev/r/d699b45899
**Expected**: no issues (or `assert()` call marked as redundant)

**Comment by muglug** [comment]
> or `assert()` call marked as redundant

That's the one I went with, because it was much easier...

**Comment by weirdan** [comment]
Well, this is still wrong:
https://psalm.dev/r/9787b31a7d

**Comment by muglug** [comment]
Yeah, I think that’s too much of an edge-case to fix (though if you want to try, knock yourself out)
