### ISSUE TITLE
PDOStatement::fetchColumn() can return int

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#2743]
Can't provide a `3v4l` link, as it does not have a MySQL server running. But when running the following code, one can see that `fetchColumn()` can return `int` as well, with the `mysql` driver and `PDO::ATTR_EMULATE_PREPARES` set to `false`.

```php
$pdo = new PDO('mysql:host=localhost', 'root', '');
$pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);

var_dump($pdo->query('SELECT 1')->fetchColumn()); // int(1)
```

As for `float`s, these seem to be always returned as strings by the `mysql` driver. However, the return type may be entirely up to the driver, and could be the reason why it's documented as `mixed`. The [doc](https://www.php.net/manual/en/pdostatement.fetchcolumn.php) actually says:

> `PDOStatement::fetchColumn()` should not be used to retrieve boolean columns, as it is impossible to distinguish a value of `FALSE` from there being no more rows to retrieve. Use `PDOStatement::fetch()` instead.

So it looks like some drivers may even return `bool`.

As such, I would suggest to document this method with every possible **scalar** type (`PDO::FETCH_CLASS` does not make sense in this context, and I don't *think*  a driver could return an array or a resource):

```php
fetchColumn() : string|int|float|bool|null
```

Thoughts?

**Comment by muglug** [comment]
Please PR an update to `CallMap.php` for this entry!
