### ISSUE TITLE
Psalm does not pull through templated type information to the child class method parameters

### ISSUE THREAD

**Issue by DaveLiddament** [vimeo/psalm#2744]
I think that Psalm should know that the parameter `$dog` is of type `Dog` in `DogProcessor::process`

```
class Dog {
  public function bark(): void {}
}

/** @template T */
interface AnimalProcessor
{
    /** @param T $animal */
    public function process($animal): void;
}

/** @implements AnimalProcessor<Dog> */
class DogProcessor implements AnimalProcessor
{
    public function process($dog): void
    {
        $dog->bark(); // I think Psalm should know this is a dog
    }
}
```
See full code here: https://psalm.dev/r/3cc6f2b730 
PHPStan does appear to know the type of `$dog`: https://phpstan.org/r/45dd07aa-212c-4e49-bd92-fb11ba456c42

The counter cases that I would expect issue are here (both tools correctly report issues):
- Psalm: https://psalm.dev/r/b376c60387
- PHPStan: https://phpstan.org/r/0447b4d4-5819-4fdf-849d-b26a49d2234e

**Comment by andrew-demb** [comment]
See discussion in  https://github.com/vimeo/psalm/issues/2722

If you will use the same name for argument, as in interface, you will get expected behaviour.

**Comment by DaveLiddament** [comment]
@andrew-demb Thanks for that. Yes managed to recreate as not an issue: https://psalm.dev/r/2f2cb159a7

I had a feeling that I was missing something as I was pretty sure that I'd used this kind of notation before.
