### ISSUE TITLE
Feature request - Suppress `UndefinedMagicMethod` with wild card in referenced method name

### ISSUE THREAD

**Issue by robguy21** [vimeo/psalm#2745]
With the following config:

```
                <?xml version="1.0"?>
                <psalm>
                    <projectFiles>
                        <directory name="src" />
                    </projectFiles>

                    <issueHandlers>
                        <UndefinedMagicMethod>
                            <errorLevel type="suppress">
                                <referencedMethod name="A::*" />
                            </errorLevel>
                        </UndefinedMagicMethod>
                    </issueHandlers>
                </psalm>
```

I would expect the `UndefinedMagicMethod` error to be suppressed in this example file:

```php
                <?php
                /**
                 * @method bar():string
                 */
                class A {
                    public function __call(string $name, array $args) {
                        return "cool";
                    }
                }
                (new A)->foo();

```

But with the following test fails:

```php
        $this->assertSame(
            'suppress',
            $config->getReportingLevelForFile(
                'UndefinedMagicMethod',
                realpath($file_path)
            )
        );

# PHPUnit

1) Psalm\Tests\Config\ConfigTest::testUndefinedMagicMethodNamesCanHaveWildCards()

Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'suppress'
+'error'
```

**Use case:**

I'd like to allow all method calls off of Laravel's Builder object, it doesn't seem like psalm is too happy with a call like `Model::get()->someRelationship()` even though this is correct in laravel-land.

My ideal end-result is to have a config which allows allows all magic method calls as per ` Illuminate\Database\Eloquent\Builder::*`

I'd be keen to make this PR myself but I'm struggling to find exactly what file is handling these comparisons.

**Comment by muglug** [comment]
If it's laravel-specific then https://github.com/psalm/laravel-psalm-plugin may be a better home for this. Psalm has a plugin hook [MethodExistenceProviderInterface](https://github.com/vimeo/psalm/blob/master/src/Psalm/Plugin/Hook/MethodExistenceProviderInterface.php) that you can use to override this particular check.

**Comment by robguy21** [comment]
My use case is laravel specific and I don't mind moving it to it's own plugin/improving laravel-psalm.

I think that this base library might find the below useful when ignoring methods:

```
                                <referencedMethod name="A::*" />
```

If you don't think this is necessary I'll for sure look at applying a fix in laravel-psalm, let me know what you think!

great job by the way!

**Comment by weirdan** [comment]
`referencedMethod` now supports PCRE regular expressions:
```
			    <referencedMethod name="/A::.*/" />
```
