### ISSUE TITLE
Consider property null check in block condition when determining type of property getter result

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#2749]
Since `Foo::hasBar()` checks `Foo::$bar` in the following snippet, I would expect Psalm to derive that `$bar` cannot be `null` in the block.

## Snippet

(https://psalm.dev/r/e583671af1)

```php
class Foo {
  /**
    * @var string|null
    */
  private $bar;
  
  public function __construct(?string $bar = null) {
    $this->bar = $bar;
  }
  
  public function hasBar(): bool
  {
    return !is_null($this->bar);
  }
  
  public function getBar(): ?string
  {
    return $this->bar;
  }
}

$foo = new Foo("nullable");

if ($foo->hasBar()) {
  $bar = $foo->getBar();
  echo strlen($bar);
}
```

## Output

```
Psalm output (using commit bbdb125):

ERROR: PossiblyNullArgument - 28:15 - Argument 1 of strlen cannot be null, possibly null value provided
```

**Comment by muglug** [comment]
In Psalm, with some notable exceptions, what happens in functions stays in functions.

I think you can achieve what you want with a `@readonly` property: https://psalm.dev/r/626f190105

**Comment by weirdan** [comment]
Or with some generic magic: https://psalm.dev/r/1dc90247a2
