### ISSUE TITLE
@template with static functions

### ISSUE THREAD

**Issue by GDXbsv** [vimeo/psalm#2751]
@template annotation does not work with static functions

This works: https://psalm.dev/r/cf7c2247e4
This does not work: https://psalm.dev/r/c47280851d

**Comment by muglug** [comment]
Yeah, I agree it's not great – I purposefully disabled the functionality because it was easy to get confused, but on reflection I think it's ok to re-enable it if there are other ways to let people know they've constructed templating in error.
