### ISSUE TITLE
call to __toString may return Exception

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2752]
Hi,

I'm not sure it will be worth fixing but I'll report it anyway.

While working on https://github.com/phpDocumentor/phpDocumentor/pull/2263

I noticed Psalm suggested to delete a cast to string that seemed not useful: https://github.com/phpDocumentor/phpDocumentor/pull/2263/files#diff-5844ff81b5eb5ff658aabe38d06279fdL70

I reproduced something similar in psalm.dev:
https://psalm.dev/r/d50c69dac0

We have an exception that could be thrown in __toString (note that this is valid from PHP 7.4 only).

The cast to (string) on a class that implements __toString can actually be valid code that may throw and that could be catched and handled.

**Comment by muglug** [comment]
> I'm not sure it will be worth fixing but I'll report it anyway.

Anything that deletes working code is a bug that's worth fixing!
