### ISSUE TITLE
How to find where psalm finds the type declaration for property?

### ISSUE THREAD

**Issue by robguy21** [vimeo/psalm#2753]
Given the following error (from a laravel application)

```
ERROR: InvalidPropertyAssignmentValue - path/To/File.php:86:49 - $this->object->property with declared type 'int|null' cannot be assigned type 'string(contact)'
            $this->object->property = 'some string';
```

I have searched everywhere to try and find out where psalm has found a declaration for `int|null` on `property` when it is clearly used as a string everywhere in the project.

Is there a way to see where psalm gets the type declaration for a property?

**Comment by muglug** [comment]
Is this in Laravel?

**Comment by robguy21** [comment]
It is 😅

I'm thinking I should probably just stick to `psalm/laravel-psalm-plugin` for these issues, but this might be a useful feature in psalm as well? I'll close this issue up, if you feel like this can be implemented in psalm feel free to reopen and I'll provide more info 👍
