### ISSUE TITLE
ext-ds subs from PHPStan

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#2754]
Recently I have made some big improvements to PHPStan's stubs for ext-ds. I won't attempt to port these to Psalm since I'm not using it at the moment, but your users might benefit from these improvements too.

https://github.com/phpstan/phpstan-src/blob/master/stubs/ext-ds.stub

Note that PHPStan's stubs don't contain all methods that actually exist on these classes but only those that are using `@template` types. So methods like `count()`, `isEmpty()` etc. are missing in these stubs - not sure if Psalm needs them to be there or not.

Also note that part of the `ext-ds` support is [this](https://github.com/phpstan/phpstan-src/blob/master/src/Type/Php/DsMapDynamicReturnTypeExtension.php) DynamicMethodReturnTypeExtension which lets PHPStan correctly interpret the different behavior of `\Ds\Map::get()` based on the number of given arguments. Currently Psalm doesn't interpret this correctly, I tried.

**Comment by muglug** [comment]
Thanks! Do you have an example, reproducible on psalm.dev, of expected behaviour of `Ds\Map::get()`?

**Comment by enumag** [comment]
@muglug psalm.dev says that class `\Ds\Map` doesn't exist so obviously I can't reproduce anything there.

**Comment by muglug** [comment]
Thanks, I've fixed this so those stubs are always loaded for the online checker: https://psalm.dev/r/122db42116
