### ISSUE TITLE
Work better with ReflectionClass 

### ISSUE THREAD

**Issue by vladyslavstartsev** [vimeo/psalm#2766]
I have code that looks like this

```php
    private function getRealTimeFacadesNamespace(): string
    {
        if ($this->realTimeFacadesNamespace !== null) {
            return $this->realTimeFacadesNamespace;
        }
        $aliasLoaderInstance = AliasLoader::getInstance();
        $facadeNamespaceReflectionProperty = (new \ReflectionClass($aliasLoaderInstance))->getProperty('facadeNamespace');
        $facadeNamespaceReflectionProperty->setAccessible(true);
        $this->realTimeFacadesNamespace = $facadeNamespaceReflectionProperty->getValue($aliasLoaderInstance);

        return $this->realTimeFacadesNamespace;
    }
```
you can find original code here https://github.com/vladyslavstartsev/laravel-strict-coding-standard/blob/master/LaravelStrictCodingStandard/Sniffs/Laravel/DisallowUseOfFacadesSniff.php#L120-L130

------

In this code you can  actually infer that `facadeNamespace` property of `AliasLoader` is string by looking at `AliasLoader` and not just getting info from `ReflectionProperty::getValue()`

**Comment by vladyslavstartsev** [comment]
@psalm-github-bot no

I know that it's bot, maybey it will get smarter:)

**Comment by muglug** [comment]
It would take a bit of work for Psalm to do this inference, and I don't think it's worth my time (reflection is a big edge-case).

But if you want to add this, feel free. You'd want to add a method to the generic `ReflectionClass` definition: https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Stubs/CoreGenericClasses.php#L1427

something like

```php
    /**
     * @template TPropertyName as string
     * @param TPropertyName $name
     * @return ReflectionProperty<T, TPropertyName>
     */
    public function getProperty($name) {}
```

And then you'd want to add a `MethodReturnTypeProvider` hook for `ReflectionProperty` that inferred the correct type.

Feel free to tag me on a draft PR if you decide to implement!
