### ISSUE TITLE
ArgumentTypeCoercion with version_compare()

### ISSUE THREAD

**Issue by sebastianbergmann** [vimeo/psalm#2769]
I just upgraded to Psalm 3.8.5 for PHPUnit and now get 8 errors where I did get 0 with Psalm 3.8.3.

One of these errors is

```
ERROR: ArgumentTypeCoercion - src/Util/Test.php:189:85 - Argument 3 of version_compare expects string(!=)|string(<)|string(<=)|string(<>)|string(=)|string(==)|string(>)|string(>=)|string(eq)|string(ge)|string(gt)|string(le)|string(lt)|string(ne), parent type string provided
            if (!\version_compare($phpunitVersion, $required['PHPUnit']['version'], $operator)) {
```

This is what the code looks like:

```
187    self::ensureOperatorIsValid($operator);
188
189    if (!\version_compare($phpunitVersion, $required['PHPUnit']['version'], $operator)) {
190    // ...
904    private static function ensureOperatorIsValid(string $operator): void
905    {
906        if (!\in_array($operator, ['<', 'lt', '<=', 'le', '>', 'gt', '>=', 'ge', '==', '=', 'eq', '!=', '<>', 'ne'])) {
907            throw new Exception(
908                \sprintf(
909                    '"%s" is not a valid version_compare() operator',
910                    $operator
911                )
912            );
913        }
914    }
```

Before, Psalm was able to infer that when `ensureOperatorIsValid()` does not throw an exception `$operator` contains a string that can be used as the third argument to `version_compare()`.

**Comment by sebastianbergmann** [comment]
`https://psalm.dev` just gives me `Internal Psalm error on line undefined - undefined` when I paste the contents of `src/Util/Test.php`.

**Comment by muglug** [comment]
> Before, Psalm was able to infer that when ensureOperatorIsValid() does not throw an exception

It wasn't doing that – it only attempt to infer assertions from functions whose names begin with `assert...`

What happened is `version_compare` got a more precise function definition. Accordingly, you need to add an assertion to that method (note the `/*` is changed to `/**`):

```php
    /**
     * @throws Exception
     *
     * @psalm-assert '<'|'lt'|'<='|'le'|'>'|'gt'|'>='|'ge'|'=='|'='|'eq'|'!='|'<>'|'ne' $operator
     */
    private static function ensureOperatorIsValid(string $operator): void
```
