### ISSUE TITLE
Message for TypeDoesNotContainType seems to be incomplete

### ISSUE THREAD

**Issue by sebastianbergmann** [vimeo/psalm#2770]
I just upgraded to Psalm 3.8.5 for PHPUnit and now get 8 errors where I did get 0 with Psalm 3.8.3.

One of these errors is

```
ERROR: TypeDoesNotContainType - src/Util/Test.php:167:30 - Cannot resolve types for  on null var
                $hint      = $hint ?? 'PHP';
```

The message `Cannot resolve types for  on null var` looks incomplete to me. The extra whitespace between `for` and `on` suggests that something is missing.

**Comment by sebastianbergmann** [comment]
`https://psalm.dev` just gives me `Internal Psalm error on line undefined - undefined` when I paste the contents of `src/Util/Test.php`.

**Comment by muglug** [comment]
In that example, `$hint` is always `null` – the check is unnecessary.
