### ISSUE TITLE
Collection expects empty, something provided

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2771]
Hi,

For this example:
https://psalm.dev/r/05f878620a

Psalm tells me that it doesn't understand the type of the Collection's generic but I can't understant why or what I should do to fix it.

If I mess with the content of __construct, the error disappear. If I drop the foreach in setArguments, it disappear. I don't know what causes it...

Thanks

**Comment by weirdan** [comment]
It's no-args collection construction that causes it. Override the type where it constructed, and it clears up all issues: https://psalm.dev/r/569506a8dc

**Comment by orklah** [comment]
Arg, I did try to do that between constructor and setArguments. Didn't thought of this one.

Thanks!

**Comment by muglug** [comment]
I'm going to reopen this – having thought about this pattern, and about what @enumag said in #2755, the solution is pretty unintuitive.

This should not be an error: https://psalm.dev/r/d95eff4c56

I think that when assigning to a property with a known generic type, any template params with the inferred `empty` type should instead receive the property params.

**Comment by muglug** [comment]
Examples all now work without the need for an additional `@var` docblock

**Comment by enumag** [comment]
Great improvement! Thanks.
