### ISSUE TITLE
`array_map((a, b) => c), a, b)` fails to infer the type of `b` in the closure

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2772]
Typically, `array_map()` is used with two parameters, one is the closure mapping the values, and one is the foldable passed to that closure.

When `array_map(function ($a, $b) { return $c; }, $as, $bs)` is used, then the type of `$b` fails to be inferred as the type of `$bs` items: https://psalm.dev/r/cdabfb49ce

When declaring the type of `$b` explicitly, the errors obviously go away: https://psalm.dev/r/c5f1c38c50

The code is obviously over-simplified: the reason why this issue exists, is because `$b` is often a complex nested structure.

**Comment by Ocramius** [comment]
Actual example from the code in the downstream project: https://psalm.dev/r/f5715acb09

**Comment by muglug** [comment]
For whatever reason the `@psalm-suppress` confuses things, when it's removed everything works: https://psalm.dev/r/3ca580553f

**Comment by Ocramius** [comment]
Uhh, something else happened too: if you see the [comment above (about the real-world use-case)](https://github.com/vimeo/psalm/issues/2772#issuecomment-583754562), @psalm-github-bot found:

```
Psalm output (using commit b439a57):

ERROR: InvalidReturnStatement - 52:12 - The type 'non-empty-array<string(C::changed1)|string(orderChanged), array{0: BetterReflectionFunctionAbstract, 1: BetterReflectionFunctionAbstract, 2: non-empty-array<array-key, mixed>}>' does not match the declared return type 'array<string, array{0: BetterReflectionFunctionAbstract, 1: BetterReflectionFunctionAbstract, 2: list<string>}>' for functionsToBeTested

ERROR: InvalidReturnType - 32:18 - The declared return type 'array<string, array{0: BetterReflectionFunctionAbstract, 1: BetterReflectionFunctionAbstract, 2: list<string>}>' for functionsToBeTested is incorrect, got 'non-empty-array<string, array{0: BetterReflectionFunctionAbstract, 1: BetterReflectionFunctionAbstract, 2: non-empty-array<array-key, mixed>}>'
```

Now it no longer reports anything

**Comment by muglug** [comment]
> Now it no longer reports anything

Yeah, because now it's inferring the types properly, right? Or is the code incorrect?

**Comment by Ocramius** [comment]
No, the code is correct, I'm just wondering what changed on this side meanwhile (the snippet wasn't changed)

**Comment by muglug** [comment]
That's due to this commit: https://github.com/vimeo/psalm/commit/9115ffd2

Psalm now has a better idea the array type than it did before, so it uses that instead of the `array` param type.

**Comment by Ocramius** [comment]
\o/ thanks!
