### ISSUE TITLE
PHP time() function flagged as impure

### ISSUE THREAD

**Issue by afbarbaro** [vimeo/psalm#2774]
Running into this issue, reproduced [here](https://psalm.dev/r/bf1cc0375f).  Why is `time()` considered impure? It doesn't take any arguments and it does not belong to a class so how can it be impure?

**Comment by someniatko** [comment]
@afbarbaro 
From Wikipedia:
In computer programming, a pure function is a function that has the following properties:
    1. **Its return value is the same for the same arguments** (no variation with local static variables, non-local variables, mutable reference arguments or input streams from I/O devices).
    2. Its evaluation has no side effects (no mutation of local static variables, non-local variables, mutable reference arguments or I/O streams).

However, `time()` may output different result when calling it with the same arguments (actually, without any argument). Therefore, it violates p.1. and is not a pure one. Actually, you can consider system clock as an I/O device.

**Comment by muglug** [comment]
Yeah, methods in immutable classes must be pure-ish - their output is solely a function of both the arguments passed to the constructor (and set as readonly properties on the object) and arguments passed to the method itself.

That allows Psalm to make all sorts of other guarantees about those classes when used inside other pure functions.
