### ISSUE TITLE
Return type with multiple inherited interfaces leading to type confusion

### ISSUE THREAD

**Issue by iquito** [vimeo/psalm#2775]
When having multiple levels of "inheritance" Psalm seems to incorrectly apply the type hints - this is [a simple example](https://psalm.dev/r/6056b59870):

```php
interface NumberInterface
{
    public function getStatus(): string;
}

interface NumberInternalInterface extends NumberInterface
{
    /**
     * @psalm-return "free"|"assigned"|"locked"|"ported"|"parent"|"fragmented"|"external"
     */
    public function getStatus(): string;
}

class NumberInternal implements NumberInternalInterface
{
    public function getStatus(): string
    {
        return 'free';
    }
}
```

Psalm gives the following error in this case:

    ERROR: LessSpecificImplementedReturnType - 18:34 - The inherited return type 'string(assigned)|string(external)|string(fragmented)|string(free)|string(locked)|string(parent)|string(ported)' for NumberInternalInterface::getStatus is more specific than the implemented return type for NumberInternal::getstatus 'string'

If you move the `@psalm-return` to the `NumberInterface` instead of the `NumberInternalInterface`, the error still stays the same, so the problem seems to be that there are multiple levels of inheritance.

When only one interface in the example is used, it works without an error, as seen [in this example](https://psalm.dev/r/cea10b07c6):

```php
interface NumberInternalInterface
{
    /**
     * @psalm-return "free"|"assigned"|"locked"|"ported"|"parent"|"fragmented"|"external"
     */
    public function getStatus(): string;
}

class NumberInternal implements NumberInternalInterface
{
    public function getStatus(): string
    {
        return 'free';
    }
}
```

This reports no issues, as expected.

**Comment by muglug** [comment]
Slightly simpler-to-parse example:

```php
class A {}
class AChild extends A {}

interface IParent {
    public function get(): A;
}

interface IChild extends IParent {
    /**
     * @psalm-return AChild
     */
    public function get(): A;
}

class Concrete implements IChild
{
    public function get(): A {
        return new A;
    }
}
```

**Comment by iquito** [comment]
The return type of Concrete in your example is probably wrong though, should be:

```php
class Concrete implements IChild {
    public function get(): A {
        return new AChild;
    }
}
```

Otherwise psalm will probably complain about it not being the advertised AChild as specified in IChild when this bug is fixed :-)
