### ISSUE TITLE
Suppress errors about using bad class

### ISSUE THREAD

**Issue by vladyslavstartsev** [vimeo/psalm#2776]
I would like to have option to disable issues when using magic class. What I mean is I have really old class that I need to use (I will refactor to new one in future, but not now) and I need to use it in new code. I would like to have option to suppress issues about this class in client code, just ignore them.

**Comment by someniatko** [comment]
https://psalm.dev/docs/running_psalm/dealing_with_code_issues/#using-a-baseline-file

**Comment by vladyslavstartsev** [comment]
@someniatko I do use baseline for old code. But I'm talking about new code

**Comment by muglug** [comment]
What sort of errors do you want to suppress?

**Comment by vladyslavstartsev** [comment]
mostly it's `MixedArgument` or `MixedArrayAccess`

**Comment by muglug** [comment]
I'm not entirely sure what you want to be able to do, but I think you can solve it either by adding more issues to the baseline, or ignoring those issues in the given files.
