### ISSUE TITLE
[Question] How to express a recursive type?

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#2777]
Hello there!

I try to type a `flatten()` function from the `nikic\iter` package. I have no ideas how to do this using current psalm. I would appreciate any help. I have copied the function definition below:

<details>
    <summary>source:</summary>

```php
/**
 * Takes an iterable containing any amount of nested iterables and returns
 * a flat iterable with just the values.
 *
 * The $level argument allows to limit flattening to a certain number of levels.
 *
 * Examples:
 *
 *      iter\flatten([1, [2, [3, 4]], [5]])
 *      => iter(1, 2, 3, 4, 5)
 *      iter\flatten([1, [2, [3, 4]], [5]], 1)
 *      => iter(1, 2, [3, 4], 5)
 *
 * @param iterable $iterable Iterable to flatten
 * @param int $levels Number of levels to flatten
 *
 * @return \Iterator
 */
function flatten(iterable $iterable, $levels = INF): \Iterator {
    if ($levels < 0) {
        throw new \InvalidArgumentException(
            'Number of levels must be non-negative'
        );
    }

    if ($levels === 0) {
        // Flatten zero levels == do nothing
        yield from $iterable;
    } else if ($levels === 1) {
        // Optimized implementation for flattening one level
        foreach ($iterable as $key => $value) {
            if (isIterable($value)) {
                yield from $value;
            } else {
                yield $key => $value;
            }
        }
    } else {
        // Otherwise flatten recursively
        foreach ($iterable as $key => $value) {
            if (isIterable($value)) {
                yield from flatten($value, $levels - 1);
            } else {
                yield $key => $value;
            }
        }
    }
}
```
</details>

This is what I did so far:

<details>
    <summary>First attempt:</summary>

```php
/**
 * FIXME: probably not solvable without recursive types like in TypeScript.
 * Types are only describen for given nesting level of 1.
 *
 * @template T
 *
 * @param iterable<T|iterable<T>> $iterable
 * @param int $levels
 * @return \Iterator<T>
 */
function flatten(iterable $iterable, $levels = INF): \Iterator {}
```
</details>

**Comment by someniatko** [comment]
I think there is no way to type this correctly, because the return type depends on the $levels variable.

`@param` should be sth like this:

`@param iterable<T|iterable<T>|iterable<iterable<T>>|...>`

and return type for `$levels = INF` is exactly `\Iterator<T>`, however, for any other level it is
`\Iterator<T|iterable<T>|iterable<iterable<T>>|...>`

**Comment by weirdan** [comment]
Psalm doesn't have a notion of recursive types as far as I know.

**Comment by muglug** [comment]
Yeah, you can't - if you search issues you'll see a few requests for recursive types that have come up (and I've dismissed).

The reason being; they're pretty complicated. Unless someone smarter than me wants to sink serious time into this, I don't think they'll ever be available in Psalm.

FWIW support in TypeScript was only added properly 6 months ago: https://github.com/microsoft/TypeScript/pull/33050
