### ISSUE TITLE
Split up (Possibly)UnusedVariable into UnusedMethodParameter, UnusedFunctionParameter

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#278]
Unused method parameters have a higher false positive rate than local variables, etc due to OOP. Some base classes or subclasses have no need to use certain parameters.

E.g. if a global function has an unused argument, it's more likely to be a bug.

Could also subdivide methods into categories by whether they are private, protected, final, or not overrides/overridden (one or more of those - private/protected seems more reliable)

**Comment by muglug** [comment]
This was fixed in https://github.com/vimeo/psalm/commit/875bb8c072ce1228c8f12518f3bf38dc365da5fd with `PossiblyUnusedParameter` (for public/protected methods) and `UnusedParameter` (for private methods and functions)
