### ISSUE TITLE
Error for fgetcsv + array_combine

### ISSUE THREAD

**Issue by thomasbley** [vimeo/psalm#2782]
https://psalm.dev/r/fd51bd0974

Psalm 3.8.3 reported no error, 3.8.5 reports ERROR: InvalidArgument - 9:26 - Argument 1 of array_combine expects array<mixed, array-key>, non-empty-list<null|string> provided

**Comment by muglug** [comment]
An empty line in a CSV is represented as `[null]`, so it's not really wrong. Instead, use `array_filter` to weed out that possibility: https://psalm.dev/r/9b9904f70a

**Comment by muglug** [comment]
If you feel strongly about this, I could make it so the `null` value was ignored.

**Comment by thomasbley** [comment]
maybe better to ignore null since array_combine works for null keys?

```
var_export(array_combine([null], [null]));

array (
  '' => NULL,
)
```

**Comment by thomasbley** [comment]
but I admit array_combine is a bit strange with nulls:

```
var_export(array_combine([null, 2], [null, null]));

array (
  '' => NULL,
  2 => NULL,
)
```
