### ISSUE TITLE
Could not get class storage for object when calling method in a trait

### ISSUE THREAD

**Issue by SiebeVE** [vimeo/psalm#2784]
When parsing following code: https://psalm.dev/r/dc517e18aa, you get an invalid argument exception.
The code is an abstract of a Laravel model and their way of call forwarding, but I have simplified it.
The HasTrait is in fact a class in the vendor directory from a package (not Laravel)

As soon as you add a docblock to the $model, it gets properly parsed (line 25)
https://psalm.dev/r/7eafcb3167

Why is psalm crashing when it doesn't have the doc block, shouldn't it be giving a proper error?

**Comment by SiebeVE** [comment]
The issue was fixed when you use the commit you fixed it in, but lately it is still throwing the error.
When I use your code from your test and remove the typehint, I still get the same issue.
https://psalm.dev/r/d876c4742a

**Comment by muglug** [comment]
Thanks – I've patched that in eeb2858

**Comment by SiebeVE** [comment]
Thank you!
