### ISSUE TITLE
ensureArrayStringOffsetsExist doesn't work with shapes

### ISSUE THREAD

**Issue by ShiraNai7** [vimeo/psalm#2787]
https://psalm.dev/r/0d19ceaee9

**Comment by weirdan** [comment]
`@param array{a: string, b: int} $context` requires all parameters to conform to the defined shape (https://psalm.dev/r/7109b2e8b0), so it's safe to access offsets without additional checks.

**Comment by ShiraNai7** [comment]
`a` and `b` shouldn't require checks, but `undefined` should, no?

https://psalm.dev/r/9b7b51cae6

**Comment by weirdan** [comment]
I think it should.
