### ISSUE TITLE
Invalid PossiblyUnusedVariable from boolean OR

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#279]
The message is misleading, it should say something like "is never referenced in some execution paths of this method" (not sure what to call that)

Observed:`PossiblyUnusedVariable - src/params.php:3:52 - Variable $location is never referenced in this method`
Expected: `PossiblyUnusedVariable - src/params.php:3:52 - Variable $location is never referenced in some execution paths of this method`

E.g. for the below:

```
<?php
class params {
    public static function isCity(float $distance, stdClass $location): bool {
        return ($distance == 0 || $location->type == 'city');
    }
}
```

**Comment by muglug** [comment]
Oh that's just a bug, sorry – the idea being that there could be classes that extend `params` that do use `$location`.
