### ISSUE TITLE
Feature Request: Statistic of all issues by level

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#2790]
Is there a way to produce the following statistics for a code basis:

```
# level 3
23 DeprecatedMethod
20 DeprecatedProperty
10 DeprecatedClass
...

# level 9
...
20 UndefinedDocblockClass
10 ParadoxicalCondition
5 InvalidThrow
```

This would be a great way to get an overview over which issues (with few occurrences) can be easily fixed and set to "error" afterwards.

**Comment by weirdan** [comment]
There's (undocumented) output format called `json-summary` that produces something similar:
![image](https://user-images.githubusercontent.com/57403/74280624-9197e100-4d25-11ea-8859-2885e2f16c00.png)

**Comment by muglug** [comment]
Ideally Psalm would do this for you – running `--init` would pick the best level for your project

**Comment by muglug** [comment]
Psalm now does this for you magically
