### ISSUE TITLE
ImplementedReturnTypeMismatch when implementation returns a Generator instead of a generic array.

### ISSUE THREAD

**Issue by yivi** [vimeo/psalm#2797]
The interface I'm implementing (from a `vendor` package, so I can't change it) goes like this:
```php
/**
 * @return Envelope[]
 */
public function get(): iterable;
```

My implementation returns a `Generator` that yields `Envelope`s.
```php
/**
 * @psalm-return Generator<array-key, Envelope>
 */
public function get(): Generator
{
   yield new Envelope(new stdClass());
}
```
But I'm getting:

> Receiver.php:52:22:error - ImplementedReturnTypeMismatch: The inherited return type 'array<array-key, Envelope>' for ReceiverInterface::get is different to the implemented return type for Receiver::get 'Generator<array-key, Envelope, mixed, mixed>'

Obviously changing the docblock to say that I'm actually returning `array<array-key, Envelope>` will get me a `MismatchingDocblockReturnType`...

How can I document this to better explain psalm what I'm trying to do? I feel like something very obvious is getting past me, but I can't see it.

**Comment by yivi** [comment]
https://psalm.dev/r/29aebd5bb7

**Comment by andrew-demb** [comment]
Adding `|iterable` on interface method solves issue.
https://psalm.dev/r/15a934bcd

But I don't know, is psalm should get it automatically.

**Comment by yivi** [comment]
@andrew-demb The psalm.dev link you posted does not seem to be related to this issue, is it?

**Comment by andrew-demb** [comment]
Seems like link broken.
Generated again: https://psalm.dev/r/15a934bcdc

**Comment by andrew-demb** [comment]
As workaround to fix vendor signature, you can use stubs for now.
https://psalm.dev/docs/running_psalm/configuration/#ltstubsgt

**Comment by yivi** [comment]
Ok, I'll investigate the use of stubs. Thanks.

But should this be the expected behaviour?

**Comment by weirdan** [comment]
I think it's expected. The interface (wrongly?) requires `array<Envelope>` return, so implementation must comply. Otherwise it would be an LSP break.

**Comment by yivi** [comment]
Yes @weirdan , I think you are right.

I imagine the interface should say `@return iterable<array-key, Envelope>`, which would cover for all these different implementations (returning arrays, generators, etc).

Not sure how extended is that notation, so I'm not sure if they'd be tractable for a PR.
 
Thanks for your help everyone.

**Comment by muglug** [comment]
Yes, I think you can just ignore the error from the implementer? Or use stubs for the `iterable` return type.
