### ISSUE TITLE
is_null(DOMNode::$parentNode) causes TypeDoesNotContainNull error

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#2799]
The `TypeDoesNotContainNull` error in the following example surprises me:

https://psalm.dev/r/713d990318

Interestingly, changing the `while` condition to `$node->parentNode instanceof DOMNode` causes a `RedundantCondition` locally (`Found a redundant condition when evaluating $node->parentNode and trying to reconcile type 'DOMNode' to DOMNode`), but not on https://psalm.dev/.

**Comment by weirdan** [comment]
Also it's interesting that `!== null` does not produce any issues here: https://psalm.dev/r/bf5dd1f946

**Comment by caugner** [comment]
Oh, it looks like a bug in the `PropertyMap` definitions:

https://github.com/vimeo/psalm/blob/ecf85aef129149abcb87512a7ac961c864d84e83/src/Psalm/Internal/PropertyMap.php#L319-L323
