### ISSUE TITLE
AfterFunctionCallAnalysisInterface::afterFunctionCallAnalysis is not called for every function call

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#2804]
When writing a plugin for our project that was using `AfterFunctionCallAnalysisInterface`, I noticed that the plugin method wasn't called for even close to all function calls in the body of analysis.

One condition for the plugin to not be called is if the function call in question is calling a function for which psalm knows it has issues.

Another condition is that the plugin is not called for some internal php library function (but not others).

I've created a demo project in an empty branch of my clone here:

https://github.com/pilif/psalm/tree/after-function

The project contains a pslam plugin that `var_dump()`s all `$function_id`s it gets called with.

In the initial commit in the demo project, I miss calls to 

* `fopen()`
* `feof()`
* `fgets()`
* `generateTemplateStrings` (see later)
* `array_map`
*  the anonymous functoin

https://github.com/pilif/psalm/blob/1661b330fd6aa3b22af2df97808bff412f34430c/src/demo.php#L10-L18

`generateTemplateStrings()` is a function included in the project via demo2.php. Psalm has an issue with it because it's missing a return type declaration.

Even after [base-lining the errors](https://github.com/pilif/psalm/commit/97de7dd1f6ac360f22057785203c21b89951071e), the logged output is still the same.

However, after [fixing the function](https://github.com/pilif/psalm/commit/de2c98bc6c1a76677c0bae9fb9986f07af413dcd), now `afterFunctionCallAnalysis` is called for `generateTemplateStrings`.

This lead me to the conclusion that `afterFunctionCallAnalysis` is not called for functions plsam has issues with.

However, that doesn't explain why `afterFunctionCallAnalysis` isn't called for most of the php standard library. 

Is this a documentation issue? Is there a hook to be called for *any* function call, not just a few specific ones from the standard library and those that don't have issues?

**Comment by pilif** [comment]
@psalm-github-bot no. I can't bevause psalm.dev doesn't allow custom plugins.

**Comment by pilif** [comment]
ha! A quick check of the source codes shows me that `afterFunctionCallAnalysis` is only called when the function's return type is known:

https://github.com/vimeo/psalm/blob/89a0b101e451f9d4a1ba057e3518c15151bf2087/src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php#L558

that certainly explains the issue partially - I'm still not clear as to why some php internals are missing.

**Comment by pilif** [comment]
while this explains the issue of why that function with the missing return type wasn't seen, it doesn't explain the missing php internals. In that case, that if is not hit

**Comment by pilif** [comment]
ok. here's the places where a function call happens but the `afterFunctionCallAnalysis` plugin method is not called:

in case of `array_map()` in the demo project, `$stmt_type` here is always set, so the `if` is never entered.

https://github.com/vimeo/psalm/blob/89a0b101e451f9d4a1ba057e3518c15151bf2087/src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php#L538

in case of `fopen` or `fgets` in the demo project, `$in_call_map` is true in this if

https://github.com/vimeo/psalm/blob/89a0b101e451f9d4a1ba057e3518c15151bf2087/src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php#L539

and thus the return type is read from the callMap and the plugins is not called

https://github.com/vimeo/psalm/blob/89a0b101e451f9d4a1ba057e3518c15151bf2087/src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php#L617-L622

As the plugin method gets some of the arguments as a reference and is allowed to change them, I don't think it's safe to move the plugin call all the way outside of the outermost if. Instead, I think the correct fix for the problem would be to add another hook interface which gets called for *every* function call but which cannot influence the `$return_type` argument.

Do you agree? If so: What would you name the Interface? I can provide the implementation of the required changes if you'd like me to.

**Comment by muglug** [comment]
Thanks! I've updated https://github.com/vimeo/psalm/issues/1732, as I think they can be combined in the next major version
