### ISSUE TITLE
Associated mutable in immutable class breaks immutability

### ISSUE THREAD

**Issue by snapshotpl** [vimeo/psalm#2805]
https://psalm.dev/r/a6ac151a01

IMO psalm should report mutable error when not immutable class is injected.

**Comment by weirdan** [comment]
@muglug The fix looks a bit too radical. IMO this should not fail: https://psalm.dev/r/8b58a212bc.

**Comment by muglug** [comment]
Yup, it doesn't anymore

**Comment by muglug** [comment]
In retrospect I think this was the wrong fix. The error here is allowing the assignment `$this->item = $item`. That's the risky thing – instead the code should be `$this->item = clone $item` to prevent the reference leaking

**Comment by muglug** [comment]
cc @sebastianbergmann and @ADmad who were caught up in this, among others. Upon further reflection the only issue is when an immutable class stores a reference to a mutable one.

**Comment by ADmad** [comment]
@muglug The issue I had reported about was a much simpler case https://github.com/vimeo/psalm/issues/2930. There's no assignment there, just new object creation.

**Comment by muglug** [comment]
yeah, that's the point – whether or not the object created was immutable, that should not have been reported as an issue

**Comment by muglug** [comment]
I've actually gone back totally on this: I don't believe it was a bug in the first instance. Issue was raised here: https://github.com/vimeo/psalm/issues/4126

Basically there's no way for any immutable/pure promises to be broken.
