### ISSUE TITLE
LessSpecificImplementedReturnType when implementing \IteratorAggregate

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#2806]
https://psalm.dev/r/e95ecc81f1

**Comment by andrew-demb** [comment]
See https://github.com/vimeo/psalm/issues/2093

**Comment by someniatko** [comment]
okay, I will close it as duplicate. Anyway IMO this should be fixed somehow.

**Comment by someniatko** [comment]
it looks like it's fixed now, yay
