### ISSUE TITLE
Cannot override variable type with phpdoc

### ISSUE THREAD

**Issue by andrew-demb** [vimeo/psalm#2807]
https://psalm.dev/r/0f31b34d81

Expected: no issues
Actual: UndefinedInterfaceMethod - 16:23 - Method BaseInterface::getsome does not exist

**Comment by muglug** [comment]
Sort-of dupe of #1916

**Comment by andrew-demb** [comment]
I don't think it's related.
`echo` added only for example.

https://psalm.dev/r/6d0482f6c1 with `if`, same problem

**Comment by muglug** [comment]
Yes, more statements where `@var` docblocks currently have no effect

**Comment by andrew-demb** [comment]
Now I get it. Thank you.
