### ISSUE TITLE
Psalm does not infer template type of interfaces extending \IteratorAggregate

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#2808]
https://psalm.dev/r/f5727e8c01

**Comment by someniatko** [comment]
bot ping https://psalm.dev/r/f5727e8c01

**Comment by someniatko** [comment]
@muglug by the way, it seems you've fixed the "won't fix" https://github.com/vimeo/psalm/issues/1756

**Comment by muglug** [comment]
Ha indeed
