### ISSUE TITLE
list with for loop

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#2811]
got no error, but expected that psalm would error because of the loop starting on a invalid index

https://psalm.dev/r/3a506100f3

**Comment by staabm** [comment]
would also expect errors in https://psalm.dev/r/9809284588

**Comment by staabm** [comment]
or also https://psalm.dev/r/ec39399572

**Comment by muglug** [comment]
These are, in principle, incredibly difficult things to catch with static analysis – a good reason for you to have unit tests!
