### ISSUE TITLE
Pure context, impure `callable` being produced

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2812]
Welcome back to the corner of @Ocramius' tricky issues!

I'm currently designing a system to declare DB mutations in a pure way, and execute them (at runtime) in an impure way. It looks kinda like this:

```php
/** @psalm-pure */
interface MutationDefinition
{
    /** @psalm-return list<callable (Machine) : void> */
    public function effects():array;
}

/** @psalm-pure */
final class StepsToMakeCoffee implements MutationDefinition
{
    /** @psalm-return list<callable (Machine) : void> */
    public function effects():array
    {
        return [
            function (Machine $m) : void { $m->addBeans(); },
            function (Machine $m) : void { $m->grindBeans(); },
            function (Machine $m) : void { $m->addWater(); },
            function (Machine $m) : void { $m->boilWater(); },
            // ... well, you get the point
        ];
    }
}
```

Stripping down everything, we get following meta-code:

```php
/** @psalm-pure */
function makeSomeStuff() : callable
{
    return static function (object $dependency) {
        \var_dump($dependency, 'impure, pure `makeSomeStuff`');
    };
}
```

Psalm rejects this, because, while the method is pure, it does indeed produce closures that have side-effects when run: https://psalm.dev/r/e9a48220fc

 > ERROR: ImpureFunctionCall - 6:9 - Cannot call an impure function from a mutation-free context

In FP langs, this is something like `makeSomeStuff :: [(IO a -> IO ())]` (notice that `makeSomeStuff` is still pure).

This calls for a few things to be tweaked:

 * [ ] the idea of "pure context" should not expand to results of pure contexts. If a function is pure, the produced data structure is immutable, but not necessarily pure (`function (Machine $m) : void { $m->addBeans(); }` is an immutable `Closure`, but `Machine` is not immutable nor pure)
 * [ ] Immutability and purity are not necessarily overlapping: the `Closure` type is `immutable` if no `use ()` nor `global` nor `static` variables are present
 * [ ] Executing logic on the result (`object|callable`) of a `@psalm-pure` context is not to be considered pure (https://psalm.dev/r/a1852660f6):
    ```php
    /**
     * @psalm-pure
     * @psalm-return callable() : void
     */
    function makeSomeStuff() : callable
    {
        return static function () {
            \var_dump('this closure is not pure');
        };
    }

    // expecting an error from this one - currently detects nothing
    /** @psalm-pure */
    function notReallyPure() : void
        makeSomeStuff()();
    }
    ```
 * [ ] Later, we probably need a way to document parameter and return types as `@psalm-pure`, sort of like a meta-interface that needs to be part of the type (https://psalm.dev/r/a2d34a695d - parse error):
    ```php
    /**
     * @psalm-pure
     * @psalm-return @psalm-pure callable() : int
     */
    function makeSomeStuff() : callable
    {
        return static function () {
            return 1;
        };
    }

    // no error expected 
    /** @psalm-pure */
    function notReallyPure() : int
    {
        return makeSomeStuff()();
    }
    ```

**Comment by muglug** [comment]
Can you think up a way of documenting that a `callable` is pure? maybe `pure-callable`?

**Comment by Ocramius** [comment]
I think it isn't limited to callables: would need to also be able to declare purity on objects.

For instance:

```php
/** @psalm-return immutable object */
function makePure() : object {
    // not relevant
}
```

Psalm has been using dashed names for special types such as `non-empty-list`: maybe we can use `immutable-object` and `pure-callable` or such? Only a bit concerned about the alias explosion 🤔

**Comment by still-dreaming-1** [comment]
> Immutability and purity are not necessarily overlapping
Yeah I don't think annotating a class with `@psalm-immutable` should require anything about it to be pure, and likewise annotating a method as @psalm-mutation-free should not require the method to be pure. I believe it is supposed to be the other way around. If a class or method is pure, then it must be immutable, but something immutable doesn't need to be pure. Think of how strings are immutable, and this just means they can't be changed.

**Comment by weirdan** [comment]
@Ocramius I think all of the cases now pass and fail as they should. You can now annotate a callable as pure with `pure-callable` type: https://psalm.dev/r/2f9967f144

Refs #4077 and #4066

**Comment by Ocramius** [comment]
Fantastic, thank you @weirdan!

**Comment by weirdan** [comment]
Thanks go to @muglug and @azjezz, I'm just playing janitor here, cleaning up old issues.
