### ISSUE TITLE
Error while reading baseline: Baseline file does not contain <files>

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#2815]
Using psalm 3.8.5

- Generate baseline file using `./vendor/bin/psalm --set-baseline=baseline.xml`
- Run `./vendor/bin/psalm`

Expected:
No errors

Actual:
`Error while reading baseline: Baseline file does not contain <files>`

Can be fixed by removing a significant number of the `<file>` nodes.
The generated file is ~5M, 140000 lines.

**Comment by SignpostMarv** [comment]
I've seen this a lot after a rebase where merging a baseline went a bit funky.

**Comment by muglug** [comment]
@leighman are you able to narrow down to a particular chunk of files where it starts failing?

**Comment by SignpostMarv** [comment]
@muglug I can't be 100% certain, but I *think* one of my odd rebase cases was when the same file was listed twice?

**Comment by leighman** [comment]
So it seems like the problem line is `<code>normalise_text_for_xml("some string containing ^Y character")</code>`
The character renders as `^Y` in vim which apparently is the `END OF MEDIUM (EM)` 🤷‍♂
Removing that line makes the file work. Presumably not a valid character in xml?
Amusing that the undefined function is `normalise_text_for_xml`

**Comment by muglug** [comment]
😱

**Comment by SignpostMarv** [comment]
@muglug just had this during a rebase at the dayjob where `ö` somehow got replaced with `<F6>`

**Comment by emmanuelGuiton** [comment]
I came across the same issue. Here is what triggers it in my case (the accentuated letters) :
```
<?xml version="1.0" encoding="UTF-8"?>
<files psalm-version="4.1.1@16bfbd9224698bd738c665f33039fade2a1a3977">
  <file src="sources/ferie.inc.php">
    <MixedArrayAssignment occurrences="11">
      <code>$ferie["Fête du travail "][5]</code>
      <code>$ferie["Fête nationale"][7]</code>
      <code>$ferie["Noël"][12]</code>
    </MixedArrayAssignment>
</files>
```

**Comment by akademic** [comment]
I have the same issue with psalm 4.4.1
I have big old projects with lots of non-UTF8 strings, so some of it I have in baseline.xml file.
I can't fix all this code and honestly don't want to do that.

So I solved this issue by patching `Psalm/ErrorBaseline.php`.

```
- $xmlSource = $fileProvider->getContents($baselineFile);
+ $xmlSource = utf8_encode($fileProvider->getContents($baselineFile));
```

**Comment by robchett** [comment]
I believe these issues are resolved as <![CDATA[ is now used?

```
  <file src="test.php">
    <InvalidOperand>
      <code><![CDATA['<XML></XML>']]></code>
    </InvalidOperand>
    <MixedArrayAccess>
      <code><![CDATA[$ferie["Fête du travail "]]]></code>
      <code><![CDATA[$ferie["Fête du travail "][5]]]></code>
    </MixedArrayAccess>
    <MixedAssignment>
      <code>$v</code>
    </MixedAssignment>
    <UndefinedGlobalVariable>
      <code>$ferie</code>
    </UndefinedGlobalVariable>
    <UnusedVariable>
      <code>$out</code>
      <code>$v</code>
    </UnusedVariable>
  </file>
```

**Comment by weirdan** [comment]
Yep, should be fixed.
