### ISSUE TITLE
Unexpected left operand cannot be mixed

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#2816]
https://psalm.dev/r/9f94b65fff

**Comment by muglug** [comment]
This isn't a bug – the type of `$i` is unknowable is many situations  (Psalm's behaviour is different from PHPStan's: https://github.com/phpstan/phpstan/issues/2630).

The only proper way to address this would be to have an annotation like `@psalm-closure-use int $i` that would act as a constraint on `$i`'s input and output types.

**Comment by leighman** [comment]
> The only proper way to address this would be to have an annotation like `@psalm-closure-use int $i` that would act as a constraint on `$i`'s input and output types.

Yes please!

**Comment by muglug** [comment]
@leighman @vudaltsov if someone writes the documentation in a PR I'll do the rest
