### ISSUE TITLE
Don't emit TooManyArguments if the function body contains func_get_args(), func_num_args(), etc.

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#282]
or func_get_arg

This helps reduce false positives when analyzing old PHP 4/5 code/libraries.

E.g. the below has no issues
```
<?php
error_reporting(E_ALL);
function test() {
    return func_get_args();
}
var_export(test(2));
```

**Comment by muglug** [comment]
Yes, this should be analysed up front in `DependencyFinderVisitor`
