### ISSUE TITLE
Generic Iterable Parameter with Splat Loses inner Type

### ISSUE THREAD

**Issue by ragboyjr** [vimeo/psalm#2824]
https://psalm.dev/r/b83276837c

Here is an example showing two different join methods one that takes an a variadic number of args via the splat syntax, and the other just accepting an array. The join method simply takes an iterable of iterables and joins them together into one iterable, very similar to array_merge.

e.g.
```
join([1,2,3], [4,5,6]) == [1,2,3,4,5,6]
```

It seems as though, when I typehint with the splat syntax for the varargs, the resulting iterable from join doesn't maintain the inner type of T, and defaults to mixed as shown in the MixedAssignment warning.

However, when I don't use the varargs and just accept an array, the inner type is maintained.

I've read the docs a few times and didn't see any examples that could guide me through and already have checked the open/closed Github issues and didn't seem to find anyone else stumbling on my specific issue.

I apologize in advance if this is just me not understanding the proper docblock syntax :(.

**Comment by ragboyjr** [comment]
whoa, awesome!!! Thanks for the quick turn around!

**Comment by ragboyjr** [comment]
Btw, I've been playing around with psalm over the weekend, and I'm absolutely blown away at how well this works. I feel like I'm coding in php 9 with psalm, some very very neat stuff.

**Comment by muglug** [comment]
From one Brooklynite to another, thanks!
