### ISSUE TITLE
No error when accessing unknown property of object-like array

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#2828]
https://psalm.dev/r/cf5fc7c957

I would expect `$row['foo']` to error since the 'foo' property is not specified in `Row`.

**Comment by muglug** [comment]
Yeah I think that's a reasonable expectation. Currently Psalm will error if the array keys are explicitly defined: https://psalm.dev/r/ce71468132

**Comment by muglug** [comment]
Now this is an error

**Comment by leighman** [comment]
Legend
