### ISSUE TITLE
Explosion of Mixed* info issues

### ISSUE THREAD

**Issue by iquito** [vimeo/psalm#2829]
With the new 3.9 version the number of "other issues" reported by Psalm exploded (in one project there were 960 new ones, in the other 6000), and when looking through them, these seem to be all issues with "Mixed" at the beginning:

- MixedAssignment
- MixedOperand
- MixedArgumentTypeCoercion
- MixedInferredReturnType
- MixedReturnStatement
- ... and many more

Many or most of them are wrong (although I only manage to scan through them) - they occur even though psalm knows or is being told the specific types. This error message might show this:

INFO: MixedReturnTypeCoercion - src/Portal/Entity/CustomerRepositoryReadOnly.php:119:20 - The declared return type 'array<array-key, Portal\Entity\Customer>' for Squirrel\Entities\Action\PortalEntityCustomer\SelectEntries::getAllEntries is more specific than the inferred return type 'array<array-key, mixed>'
         * @return [30;47m\Portal\Entity\Customer[][0m

It seems that psalm assumes everything to be mixed somehow (or it infers mixed), and then issues INFO messages about that, even though the types are clearly specified and used accordingly. There are also many of these:

INFO: MixedReturnStatement - src/Portal/Entity/EventRepositoryReadOnly.php:165:20 - Could not infer a return type
            return [30;47m$this->iteratorInstance->current()[0m;

The context here is that the return type is specified through a PHPDoc block, and the Iterator is a generic implementation. Some of the Mixed INFO messages might actually be valid, but many are definitely not.

I did not try to recreate a minimal example yet, but running it on any real project should show this problem clearly, as even on a new greenfield project where psalm can infer types for 96% of the codebase I got 960 new issues - there are only INFO issues at least.

**Comment by muglug** [comment]
Psalm has always had these issues in the background, but it now surfaces them _if_ you use `--show-info=true`.

> even though the types are clearly specified and used accordingly. 

Do you have an example where Psalm should be able to infer a type beyond `mixed`?

> I got 960 new issues - there are only INFO issues at least.

As long as there are no new _errors_, I don't think this is a bug.

`--show-info` now defaults to `false`, so users won't see these issues by default. My aim with that was to hide the noise of info issues, while making it clear that there's extra stuff Psalm has problems with.

**Comment by iquito** [comment]
I will see what examples I can come up with. For me this generates a lot of noise, as before I had 41 other issues (errors which were set to INFO via a baseline file), now I have 999 other issues. While I can see that some are actually helpful, many, especially the "could not infer" messages seem not helpful. Here an example:

```php
public function create(CustomerChangeAction $changeData): int
{
    return $this->transaction->run(function (CustomerChangeAction $changeData): int {
        $locationAddressId = $this->addressService->create($changeData->locationAddress, 'customers');

        if ($changeData->invoiceAddressSpecified === true) {
            $invoiceAddressId = $this->addressService->create($changeData->invoiceAddress, 'customers');
        }

        $customerId = $this->customerService->create($changeData->name, $changeData->resellerCustomerId, $locationAddressId, $invoiceAddressId ?? 0);

        $customerId = \intval($customerId);

        if ($changeData->isReseller === true) {
            $this->customerService->setReseller($customerId, $changeData->isReseller);
        }

        if ($changeData->resellerResponsibleForInvoice === true) {
            $this->customerService->setResellerResponsibleForInvoice($customerId, $changeData->resellerResponsibleForInvoice);
        }

        return $customerId;
    }, $changeData);
}
```

Here Psalm says:

INFO: MixedInferredReturnType - src/wwcom/Portal/ChangeHandler/CustomerChangeHandler.php:40:63 - Could not verify return type 'int' for wwcom\Portal\ChangeHandler\CustomerChangeHandler::create
    public function create(CustomerChangeAction $changeData): [30;47mint[0m

I don't get that message - the type is clearly int, and the return value is even cast with `intval`.

**Comment by muglug** [comment]
> I don't get that message - the type is clearly int, and the return value is even cast with intval.

You're looking at the wrong line – if you look at `CustomerChangeHandler.php:40:63` you'll see it lines up with the `int` return type for the parent function.

I imagine `$this->transaction->run(...)` doesn't have a return type on it.

It looks like it should be templated along the lines of

```php
/**
 * @template TReturn
 * @param callable(mixed):TReturn
 * @return TReturn
 */
function run(callable $c, $arg) {
  return $c($arg);
}
```

Adding that (if it's code under your control) would allow Psalm (and other tools including PHPStan) to understand what's being returned.

The _danger_ of `Mixed*` issues is that a failure to infer types can often hide bugs – I give some examples in [this article](bugs-creep-in-when-types-cant-be-inferred).

**Comment by iquito** [comment]
Ah okay, now I get it. Although the call to `$this->transaction->run` does go to a class in my vendor directory, so usually there would be nothing I could do about this issue.

While I do see how many of these issues can be helpful, the sheer amount makes it hard to actually go through them:

- Issues coming from the vendor directory are in there
- Some are confusingly worded, like `Cannot assign $variable to a mixed type`, which seems to come up when an array is iterated over which is not defined in detail (only `array` as type hint), but the wording and where it is reported does not make this very clear
- It is hard to go through so many of these issues (and I have a small greenfield application which has been using static analyzers from the start, this will be much worse for large codebases). Some of them might be important, but going over dozens and dozens of them I found only one which was something I could easily change. Some sort of triage could make this a lot more useful
- As far as I could tell, there is no way easy way of turning off these new issues globally - or is there a way? (I went through the documentation and as far as I could tell every type of Mixed* error type would have to be suppressed separately) This could be useful to enable them one by one if they should be tackled, but also to see the other issues which could be more important (like issues from a baseline file, where the number of issues can be an important metric).

**Comment by orklah** [comment]
There is a config totallyTyped in psalm.xml that can be set to false to disable those rules.

And you should also be able to disable them manually with errorHandlers

**Comment by muglug** [comment]
> There is a config totallyTyped in psalm.xml that can be set to false to disable those rules.

Now setting `totallyTyped="false"` doesn't suppress those rules completely – it just stops them from being treated as errors. If you want to suppress them you can use:

```
<MixedArgument errorLevel="suppress" />
<MixedArrayAccess errorLevel="suppress" />
...
```

**Comment by orklah** [comment]
> Now setting `totallyTyped="false"` doesn't suppress those rules completely – it just stops them from being treated as errors.

Good to know. Thanks!

**Comment by muglug** [comment]
@iquito I've added a config flag you can use in 520b646

**Comment by muglug** [comment]
And after further thought I've further reverted this to use the pre-3.9 behaviour in https://github.com/vimeo/psalm/releases/tag/3.9.3 when a `totallyTyped` config flag is used.

**Comment by iquito** [comment]
Thanks! Having ways to customize this easily (or also prioritize issues) will help to focus on the most pressing issues depending on the project. Also, many libraries and frameworks are still missing some or most of the necessary type hints, which might be why these issues are so plentiful.

A small question about the necessary annotations for `$transaction->run` - is this the correct annotation?

```php
interface TransactionInterface
{
    /**
     * Process $func within a transaction. Any additional arguments after
     * $func are passed to $func as arguments
     *
     * @template TReturn
     * @param callable(...$arguments): TReturn $func
     * @param mixed ...$arguments
     * @return TReturn
     */
    public function run(callable $func, ...$arguments);
}
```

I am unsure if `@param callable(...$arguments): TReturn $func` is the right way of telling psalm that the passed arguments are passed on in the same way to $func, or if psalm even cares/checks this in any way.
