### ISSUE TITLE
Emit PossiblyUndefinedMethod if there are other types in the union type which define the method

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#283]
The below example is simplified. Real use cases might be unanalyzable (e.g. domain assumptions about given subclasses, etc.)

Possible implementation: Check if at least one of the types in the union type is a class type, and defined the method name or magic getter. If at least one did, emit `PossiblyUndefinedMethod` instead of `UndefinedMethod` (error message could mention that other classes exist with the method)

Another implementation would be to suppress the entire group of UndefinedMethod if at least one method was found for any type, but this seems to go against psalm's design.

```
ERROR: UndefinedMethod - src/possible.php:20:9 - Method B22::foo does not exist
        $a->foo();
```

```
<?php

class A22 {
    public function foo() : void {}
}
class B22 {
    public function other() : void {}
}

function a(bool $cond) : void {
    if ($cond) {
        $a = new A22();
    } else {
        $a = new B22();
    }

    // ... Other code or function calls go here.

    if ($cond) {
        $a->foo();  // Observed: UndefinedMethod. Desired: PossiblyUndefinedMethod, because it might be A22 or B22
    }
}
```

**Comment by muglug** [comment]
Yeah, absolutes were great initially, but I like the `Possibly*` messages more now (to allow people to level-up their type checking).

**Comment by TysonAndre** [comment]
Thanks!
