### ISSUE TITLE
allowPhpStormGenerics doesn't seem to be effective

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2830]
I can't reproduce on psalm.dev, but on https://github.com/Roave/BetterReflection when launching psalm, we get a certain type coverage. if we add allowPhpStormGenerics and clean cache, the coverage doesn't change. if we add 
```php
    'phpparser\\node\\stmt\\class_' => [
        'stmts' => 'array<int, PhpParser\Node\Stmt>',
    ],
    'phpparser\\node\\stmt\\trait_' => [
        'stmts' => 'array<int, PhpParser\Node\Stmt>',
    ],
    'phpparser\\node\\stmt\\interface_' => [
        'stmts' => 'array<int, PhpParser\Node\Stmt>',
    ],
```
in propertymap.php and clean cache, the type coverage increases

**Comment by muglug** [comment]
I don't understand. `allowPhpStormGenerics` only applies to docblocks of the form `string[]|SomeIterator`. `BetterReflection` doesn't have many of those, but Psalm complains when that config is disabled (there are a couple more errors).

Type coverage (the % of expressions with types) doesn't change, but I wouldn't expect it to.

**Comment by orklah** [comment]
> I don't understand. `allowPhpStormGenerics` only applies to docblocks of the form `string[]|SomeIterator`. `BetterReflection` doesn't have many of those, but Psalm complains when that config is disabled (there are a couple more errors).
> 
> Type coverage (the % of expressions with types) doesn't change, but I wouldn't expect it to.

Sorry, went too fast. I was talking about usePhpDocPropertiesWithoutMagicCall
