### ISSUE TITLE
--find-unused-psalm-suppress returns "This suppression is never used" that are actually used

### ISSUE THREAD

**Issue by HenkPoley** [vimeo/psalm#2834]
Psalm 3.8.5@e6ec5fa22a7b9e61670a24d07b3119aff80dcd89

I have a function foo() that takes a CarbonImmutable from composer [`nesbot/carbon`](https://github.com/briannesbitt/Carbon) package:

```php
<?php
use Carbon\CarbonImmutable;

function foo(DateTimeInterface $s) : bool {
    return true;
}

/** @psalm-suppress PossiblyFalseArgument */
foo(CarbonImmutable::createFromFormat('!Y-m-d', '2019-12-30'));
```

CarbonImmutable::createFromFormat() might return a false (e.g. `@return false|CarbonImmutable`). But in their normal mode it will not return false, only CarbonImmutable or an Exception. So I suppress the INFO message.

If I run `vendor/bin/psalm --find-unused-psalm-suppress` it will say this suppress is unused, but if I remove it, I get the INFO message.

**Comment by HenkPoley** [comment]
No bot, I can't since don't import (use) Carbon on there.

**Comment by HenkPoley** [comment]
Same with Psalm 3.9.0@9866b292a40bc0258b1483428ea2f19baa7aed51

**Comment by orklah** [comment]
Closing as stale. Feel free to ping me to reopen
