### ISSUE TITLE
Optional property error

### ISSUE THREAD

**Issue by snapshotpl** [vimeo/psalm#2835]
https://psalm.dev/r/c9ea0f8b5d

**Comment by weirdan** [comment]
AFAIK Psalm does not let you leave property uninitialized. You may want to give the property a default null value: https://psalm.dev/r/6d4631b38f

**Comment by muglug** [comment]
This just mirrors PHP's own (slightly confusing) behaviour – properties with explicitly nullable types must still be initialised somehow to `null` before use.

**Comment by snapshotpl** [comment]
Good to know. Thanks
