### ISSUE TITLE
Constants annotations do not work.

### ISSUE THREAD

**Issue by GDXbsv** [vimeo/psalm#2836]
https://psalm.dev/r/d7e2009c63

**Comment by muglug** [comment]
Only string keys work in that context: https://psalm.dev/r/a960775fb7

**Comment by Chrico** [comment]
Howdy,

we saw that issue being closed without any feedback. Is there any reason why this is closed? 

As far as i can see, in `list<>` class constants are working as array-value. But in `array{}` they are not working as array-key. Is there any reason why this is not supported?

Test cases: https://psalm.dev/r/88415c73fd

**Comment by gmazzap** [comment]
I find myself often using constants as array key because that's the only way to have IDE auto-complete and avoid typo. Having to resort to hardcoded strings in annotations completely defeats that purpose.

**Comment by muglug** [comment]
The point of `array{...}` annotations is conciseness. If instead Psalm has to worry about all the indirection that class constants provide, a lot of the ergonomics of object-like types disappear from an internal perspective.

**Comment by muglug** [comment]
I've now made the error more explicit

**Comment by awd-studio** [comment]
Hey! 

It would be cool to use constants ins such way: https://psalm.dev/r/dd8e04a375

**Comment by orklah** [comment]
Please create a new issue for that
