### ISSUE TITLE
totallyTyped="false" is ignored in Config::reportIssueInFile(), versions 3.9.0/3.9.1

### ISSUE THREAD

**Issue by thomasbley** [vimeo/psalm#2841]
Psalm 3.9.1/3.9.0 gives for my code base many mixed-typed errors:

```
1048 other issues found.
You can display them with --show-info=true
```

Psalm 3.8.5 gave no other issues.

my config:

```
<?xml version="1.0"?>
<psalm
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config config.xsd"
    autoloader="src/psalm-autoload.conf"
    ignoreInternalFunctionFalseReturn="true"
    ignoreInternalFunctionNullReturn="false"
    findUnusedCode="true"
    totallyTyped="false"
>
    <projectFiles>
        <directory name="src" />
        <directory name="tests" />
        <ignoreFiles>
            <directory name="src/vendor" />
        </ignoreFiles>
    </projectFiles>

    <issueHandlers>
        <InternalMethod errorLevel="suppress" />
        <MissingPropertyType errorLevel="suppress" />
        <PropertyNotSetInConstructor errorLevel="suppress" />
        <UnusedClass errorLevel="info" />
        <MissingConstructor />
    </issueHandlers>
</psalm>
```

Changing Psalm/Config.php gives the old behavior:

```
    public function reportIssueInFile($issue_type, $file_path)
    {
+        if ($this->level !== 1 && in_array($issue_type, self::MIXED_ISSUES, true)) {
+            return false;
+        }
```

**Comment by thomasbley** [comment]
Seems const MIXED_ISSUES is defined but unused in latest master:

```
grep -rn "MIXED_ISSUES" .
./src/Psalm/Config.php:101:    const MIXED_ISSUES = [
```

**Comment by muglug** [comment]
Yeah, this is a change from 3.8 to 3.9.

If you want to properly suppress them (so they never show up anywhere) you can do it in your config file.

The aim with `INFO` messages (which are now hidden by default) is to say "hey, there may be bugs here, I'm not sure", and `Mixed*` issues are part of that.

**Comment by thomasbley** [comment]
If I configure totallTyped="false", I expected Mixed issues to be no issues.
e.g. https://psalm.dev/r/2b2d67e9da is typical code that's not fully typed and did not produce "other issues" in 3.8.5. Maybe it would be good to have this change documented in more detail?

**Comment by thomasbley** [comment]
> If you want to properly suppress them (so they never show up anywhere) you can do it in your config file.

When having suddenly thousands of new INFO issues, it's easy to overlook other INFO issues.
It would be great to have an easier way to avoid adding 18 extra rules to the configuration for each project.

**Comment by muglug** [comment]
> It would be great to have an easier way to avoid adding 18 extra rules to the configuration for each project.

I agree – I've added a config flag you can use in 520b646

**Comment by muglug** [comment]
After further thought I've further reverted this to pre-3.9 behaviour in https://github.com/vimeo/psalm/releases/tag/3.9.3, and have also deprecated `totallyTyped`.
