### ISSUE TITLE
call to __invoke should behave consistently with ()

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2842]
https://psalm.dev/r/3357465620

Direct call to $c->__invoke() should have the same effect as $c()

(Note: I added callable and closure to the example as I could reproduce with both, but I'm not actually sure if both can have an __invoke method)

**Comment by muglug** [comment]
Is this new with 3.9.*?

**Comment by orklah** [comment]
I'm pretty sure it's not. I'll try that right away

**Comment by orklah** [comment]
I reproduce it with 3.8.0

**Comment by muglug** [comment]
Great – just making sure it wasn't introduced

**Comment by weirdan** [comment]
> Direct call to $c->__invoke() should have the same effect as $c()

For invokable classes (including closures) only. Callables might be strings, and so I'd expect `->__invoke()` call on those to be flagged.

**Comment by muglug** [comment]
Yeah, actually I don't consider this a bug

**Comment by orklah** [comment]
How should I document a call to invoke then? My goal is for psalm to realise that it returns the callable return without complaining. Thanks!
