### ISSUE TITLE
Need a good way for a plugin to mark a class or method as "used"

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#2843]
In frameworks it's a common pattern to either use dependency injection to automatically call constructors and to use some kind of annotation to mark controller methods as routable and then call them through the framework.

Both of these cases would seen as "unused" by psalm.

The recommendation back in 2018 with #1105 was to just suppress the "unused*" warnings, but I feel like this isn't fine grained enough, *especially* in case of annotation based routing. I don't want to ignore *all* public methods of a controller and, as it's annotation based, I don't want to have to specifically list all controller methods in the config file (or manually add yet another suppression).

Ideally, a plugin should be able to mark a method as used.

Right now I *think* I can hack something using a `AfterClassLikeAnalysisInterface` and add suppressions as needed, but suppressing the error feels less correct than being able to mark a method as used.

Ideally, there would be an interface similar to the existing `*ProviderInterface` interfaces that gets called to mark a method or class as used respectively.

For now, I think this is beyond my skills to create a PR for, so I'll leave this as an issue.

**Comment by muglug** [comment]
There's a way! It's not a great way, but it's a way nonetheless – see here: https://github.com/psalm/phpunit-psalm-plugin/blob/496c08f088d9e34e1947bca1de52b32b6571bad3/hooks/TestCaseHandler.php#L178-L183

**Comment by pilif** [comment]
haha - thank you for the pointer. I'll make a PR to update the docs.

btw: after posting this issue, I tried something via `AfterClassLikeAnalysisInterface` and adding to `$classlike_storage->methods[..]->suppressed_issues`, but unfortunately that doesn't fly because the $classlike_storage reference passed into the plugin is different from the storage `ClassLikes::checkMethodReferences()` is acting on.
