### ISSUE TITLE
Incorrect InvalidPropertyAssignmentValue for array<string, string> on class properties

### ISSUE THREAD

**Issue by tux-rampage** [vimeo/psalm#2846]
Assigning a static string hash map (inline or via const) that contains a string-key with a number to a class property defined as `array<string, string>` raises an `InvalidPropertyAssignmentValue`.
When the numbers starting with a `0` are not reported.

Doing the same with a variable does not raise such an issue.

https://psalm.dev/r/1be5577335

**Comment by andrew-demb** [comment]
PHP doesn't allow to use numeric string as array key and psalm report this correctly.

See https://3v4l.org/go7El

**Comment by tux-rampage** [comment]
Oh PHP, why ... 🤦🏻‍♂️
