### ISSUE TITLE
Invalid ImplementedReturnTypeMismatch

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#2849]
related to #2581 and #2556 

snippet : https://psalm.dev/r/0bc59b077a

**Comment by azjezz** [comment]
more context if needed : https://github.com/azjezz/psl/pull/10/files

**Comment by azjezz** [comment]
This is the same as #2556, the fix for #2556 caused #2569, and the fix for #2569 caused #2581, and the fix for #2581 caused this apparently :)

**Comment by muglug** [comment]
Looks like it's specific to object-like arrays: https://psalm.dev/r/d204b75ee3
