### ISSUE TITLE
tidyNode properties’ types are inaccurate

### ISSUE THREAD

**Issue by chloekek** [vimeo/psalm#2855]
The tidyNode class has two properties _attribute_ and _child_. In Psalm these are both given the type _array_.

First of all, both properties could have a NULL value. See the example below. Secondly, the types could be more strict, by telling about the array element types.

#### Proposal

 - [ ] Make the _attribute_ property of type `?array<string,string>`.
 - [ ] Make the _child_ property of type `?array<tidyNode>`.

#### Example

```php
$tidy = new tidy();
$tidy->parseString('hello');

// $text is of type tidyNode
$text = $tidy->body()->child[0];

assert($text->attribute === NULL);
assert($text->child === NULL);
```

**Comment by chloekek** [comment]
I should add: the nullabilities and exact types are unfortunately not documented in the PHP manual for the Tidy extension. I will look into contributing a documentation f ix.

**Comment by othercorey** [comment]
@orklah The current property map looks correct https://github.com/vimeo/psalm/blob/2d9e3f42f65a1fb2b6e25e7d228be61aa42695d2/dictionaries/PropertyMap.php#L578

**Comment by orklah** [comment]
yeah, null was added by https://github.com/vimeo/psalm/pull/8000.

I'll close this, if someone wants to make the extra mile and precise the type inside the array, they're welcome!
