### ISSUE TITLE
Add option to ignore `@param null $x` when null is only type?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#286]
This is probably inaccurate boilerplate when it is included (e.g. in third party composer library)
Currently, I see `InvalidArgument: ... expects null, string provided.`

**Comment by muglug** [comment]
I think it should just be the default – and same for `@param false`, right?

**Comment by TysonAndre** [comment]
Default sounds reasonable and what I would do, not sure when it would ever be turned off

**Comment by TysonAndre** [comment]
A same for `@param true`
