### ISSUE TITLE
Too many arguments or could not verify return type 'T'

### ISSUE THREAD

**Issue by leocavalcante** [vimeo/psalm#2860]
If I left the annotation as `callable(): T` it throws `TooManyArgument`:
https://psalm.dev/r/123627be23

And if I set it as `callable: T` it throws `Could not verify return type 'T'` for a dependent function:
https://psalm.dev/r/3c655385f7

How can I make it work? There is some way to set a callable as receiving arbitrary number of arguments?

**Comment by muglug** [comment]
use `callable(...mixed)`: https://psalm.dev/r/3d1a91b5e0

**Comment by leocavalcante** [comment]
Thank you!
