### ISSUE TITLE
Nested Closures Lose Generic Typing

### ISSUE THREAD

**Issue by ragboyjr** [vimeo/psalm#2863]
https://psalm.dev/r/31ea15b421

In the above example, I get the error:

```
ERROR: InvalidArgument - 32:4 - Argument 1 expects iterable<empty, int>, array{0: int(1), 1: int(2), 2: int(3), 3: int(4)} provided
```

The issue is related to me using the `@template K` and trying to specify that key type of the input iterable will match the output iterable. If I just remove the K template and don't specify the key type for the iterables, everything works fine.

I'm not entirely sure psalm expects that the key would be empty vs array-key or int.

**Side Note**

`@return callable(iterable<K, T>): iterable<K, U>` I feel like this declaration is redundant considering the inner callable is typed, but psalm won't work without it.

**Comment by weirdan** [comment]
There's no way to infer `K` in your example as it's not mentioned in any paramenter. What you're trying to do here is to return generic closure from map, with K still unbound. I don't think Psalm supports this at the moment, @muglug correct me if I'm wrong.

**Comment by ragboyjr** [comment]
@weirdan do you know if this is something reasonable to achieve with your current understanding of the architecture?

**Comment by muglug** [comment]
It's not possible – this is the only way for template types to be inferred: https://psalm.dev/r/ae9719b25d
