### ISSUE TITLE
Psalm Plugin: Can't seem to autoload Psalm/Test namespace

### ISSUE THREAD

**Issue by jarstelfox** [vimeo/psalm#2869]
While writing a plugin, I wanted to allow the plugin to be tested similar to your existing psalm tests: I want to get an [analyzed codebase from a string](https://github.com/vimeo/psalm/blob/master/tests/ArrayAccessTest.php#L21-L32). This would allow my plugin to be tested without needing to checkout multiple codebase's / running psalm on them.

I was looking at pulling in your [Test namespace](https://github.com/vimeo/psalm/blob/master/composer.json#L77-L80) however, [autoload-dev is root-only](https://getcomposer.org/doc/04-schema.md#autoload-dev) which does not allow my project to easily pull in this test namespace.

My current composer.json does not work:

```php
{
  "name": "jarstelfox/psalmdocumentor",
  "description": "Outputs docblocks as markdown documentation with psalm's types",
  "type": "psalm-plugin",
  "require": {
      "phpunit/phpunit": "^8.0",
      "vimeo/psalm": "dev-master"
  },
  "autoload": {
      "psr-4": {
         "PsalmDocumentor\\": "src/"
      }
   }
  "autoload-dev": {
      "psr-4": {
         "Psalm\\Tests\\": "vendor/vimeo/psalm/tests/"
      }
   }
}
```

However, I can load your classes one by one with `require_once __DIR__ . '/../vendor/vimeo/psalm/tests/TestCase.php'`

Do you have any insight into how to easily autoload your test namespace when writing a plugin?

**Comment by weirdan** [comment]
Seems to be working for me: https://github.com/weirdan/psalm-tests-autoload (clone, `composer install`, then run `php main.php`).

**Comment by jarstelfox** [comment]
Whoops! I forgot `require 'vendor/autoload.php';`

However, now I am seeing:

```
phpunit ./tests 
PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 103 ms, Memory: 14.00 MB

There was 1 error:

1) Test::testCaseOne
Psalm\Exception\ConfigException: Could not resolve config path to /Users/Jarred/Documents/Coding/psalmdocumentor//src/Psalm/Internal/Stubs
```
given

```php
<?php
require 'vendor/autoload.php';

use Psalm\Tests\TestCase;

class Test extends TestCase
{
   public function testCaseOne(): void {}
}
```
