### ISSUE TITLE
FInd where a type requirement originated

### ISSUE THREAD

**Issue by alecwcp** [vimeo/psalm#2871]
Given a variable `$query` that is of type `\Cake\Database\Query` (from https://github.com/cakephp/database), when passing an array with 2 elements into the `select` or `order` functions, I get the error below
```
ERROR: UndefinedClass - /path/To/File.php:65:23 - Class or interface ASC does not exist
$query->order([
    'instance_date' => 'ASC',
    'start_time' => 'ASC',
]);
```

However, stepping into the class in use there, I'm unable to find anywhere that would cause (either through usage or annotations) that would indicate that the first value in that array should be a class/interface.

Is there any way to get out more info about where that expectation has come from? I've tried `--debug` and `--debug-by-line` but those didn't give me any more info and I don't see any other options that would do that when looking at the output of `--help`.

I've attempted to reproduce this with the online demo at https://psalm.dev/ but have been unsuccessful.

**Comment by weirdan** [comment]
Looks the first param was defined as callable somewhere: https://psalm.dev/r/453d2db92b

**Comment by muglug** [comment]
ah yes, that's definitely a bug – Psalm shouldn't bother verifying classes on clearly non-callable arrays

**Comment by muglug** [comment]
Although it could also be prevented upstream: https://psalm.dev/r/f0bdf4046d

**Comment by weirdan** [comment]
@alecwcp are you sure the issue was triggered by the call to `Query::order()`? Looking at upstream's docblocks it shouldn't have triggered it, but a call to `select()` might.

**Comment by muglug** [comment]
@weirdan order has that docblock I think? Either way, it should be fixed in latest master

**Comment by alecwcp** [comment]
@weirdan it was triggered by both `Query::order()` and `Query::select()`, they have similar doc blocks
```
/**
 * @param array|\Cake\Database\ExpressionInterface|callable|string $fields fields to be added to the list
 * @param bool $overwrite whether to reset order with field list or not
 * @return $this
 */
public function order($fields, $overwrite = false)
```
and
```
/**
 * @param array|\Cake\Database\ExpressionInterface|string|callable $fields fields to be added to the list.
 * @param bool $overwrite whether to reset fields with passed list or not
 * @return $this
 */
public function select($fields = [], $overwrite = false)
```
@muglug the example you give of using `@psalm-param array|callable-string|callable-object $_fields` in a stub worked :+1:  - although doesn't that then imply that it cannot take a direct callable (i.e. passing in an anonymous function?), that's allowed by the code (actually one of the examples in the full doc block).

**Comment by alecwcp** [comment]
Ah, ignore my previous comment - I now see in the fixes for this (https://github.com/vimeo/psalm/commit/ff7fbcda993752fe009187df05b3eba1e155ad77 and https://github.com/vimeo/psalm/commit/234a6ba4b4c11cb86d6524b190ac2d67ed1f817a) mean that in this situation it isn't necessary to add `callable-string` to suppress this (if I've understood correctly).

**Comment by weirdan** [comment]
> @weirdan it was triggered by both Query::order() and Query::select(), they have similar doc blocks

Ah, now I see, that's how it was in older (pre 4.x) Cake.

> in this situation it isn't necessary to add callable-string to suppress this (if I've understood correctly).

Correct.
