### ISSUE TITLE
Unable to suppress error about duplicate core function

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#2872]
https://github.com/vimeo/psalm/pull/2825

I would expect this test to pass but it fails.
Duplicate core function raises DuplicateFunction but it doesn't seem possible to suppress it

**Comment by TysonAndre** [comment]
I'm seeing a similar issue with two user-defined classes

https://psalm.dev/r/df2625c721

**Comment by alfredbez** [comment]
I ran into the same error: https://psalm.dev/r/aa89d6f59e

**Comment by ricardoboss** [comment]
Any update on this? I'm having the same issue

**Comment by masonmcelvain** [comment]
I'm also having this issue. While a proper solution is in the works, is there a recommended way for users to handle in the short term? The only option I can see is baselining occurrences of `DuplicateFunction`.
