### ISSUE TITLE
LessSpecificReturnStatement + MoreSpecificReturnType reported together

### ISSUE THREAD

**Issue by bendavies** [vimeo/psalm#2875]
See: https://psalm.dev/r/4c0bab583c

If we change line 28 to
`@return (T&Baz)|null`
(switching Baz and T), then there are no errors.

**Comment by weirdan** [comment]
Order-dependence is unexpected, but wouldn't it make more sense to declare the types like this: https://psalm.dev/r/462ae2c353

**Comment by bendavies** [comment]
i wasn't aware of that syntax. thanks

**Comment by muglug** [comment]
Yes, order-dependence is still a bug

**Comment by bendavies** [comment]
seems phpstan doesn't like `@template T of Foo` unfortunately. (i run both)

**Comment by weirdan** [comment]
Works for me: https://phpstan.org/r/c5b43fd7-f415-43fa-aacf-159a2a3123c8

**Comment by muglug** [comment]
distilled down, these should both be errors: https://psalm.dev/r/7c42967494

**Comment by bendavies** [comment]
> Works for me: [phpstan.org/r/c5b43fd7-f415-43fa-aacf-159a2a3123c8](https://phpstan.org/r/c5b43fd7-f415-43fa-aacf-159a2a3123c8)

huh, thanks. i got an error. i'll look into it another time.
