### ISSUE TITLE
Array by reference incorrectly hinted by auto fixer

### ISSUE THREAD

**Issue by AJenbo** [vimeo/psalm#2878]
This issue produces invalid PHP when calling `psalm --alter --issues=MissingParamType`

input
```
/**
 * @param array $var
 */
function callMe(&$var): void
{}
```
result:
```
/**
 * @param array $var
 */
function callMe(&array $var): void
{}
```
expceted:
```
/**
 * @param array $var
 */
function callMe(array &$var): void
{}
```

**Comment by AJenbo** [comment]
@psalm-github-bot I don't belive that allows me to run the fixers.

**Comment by muglug** [comment]
Dupe of #2857, fixed in master (but not yet released)
