### ISSUE TITLE
PHAR - rename file extensions of PhpStorm stubs

### ISSUE THREAD

**Issue by voku** [vimeo/psalm#2879]
PhpStorm will index all phar files, but if the phar file use "stubs" we will have problems with the autocompletion. 

Autocompletion problem from PhpStorm: https://twitter.com/suckup_de/status/1232431473006759937/photo/1

Example implementation from PHPStan: https://github.com/phpstan/phpstan-src/commit/e18b3b47c8e1b91f1844dd3c91d961e912476d86

**Comment by alexeyshockov** [comment]
@muglug, should all plugins do the same? I see a lot of issues like this with @weirdan's doctrine-psalm-plugin...
