### ISSUE TITLE
InvalidReturnType while using instantiator with switch statement

### ISSUE THREAD

**Issue by adrianpanicek** [vimeo/psalm#2885]
I've typehinted code based on `instantiator` example but instead of using `$class::method()` construct, we want to use switch statement like [this](https://psalm.dev/r/b6cc0939f3).

```php
<?php

class A {}
class B extends A {}

/**
 * @template T as A
 * @psalm-param class-string<T> $class
 * @psalm-return T
 * @return A
 */
function instantiator(string $class): A {
    switch ($class) {
      case B::class:
    	return new B();
    }
}

instantiator(B::class);
```

Yet psalm says that `B` is not correct return type for this call.

**Comment by muglug** [comment]
I know it feels like Psalm should understand this, but it's not simple to determine that returning `B` is a logical result of your class string check.

This formulation works, but may not do what you want:

```
/**
 * @template T as A
 * @psalm-param class-string<T> $class
 * @psalm-return T
 * @return T
 */
function instantiator(string $class): A {
  return new $class;
}
```
