### ISSUE TITLE
Struggling to type mixed for anonymous callable

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#2886]
I tried to search issues but did not find answer. How can I type `mixed` type for arguments and return type of anonymous callable? Tried `/** @var callable(mixed):mixed $fcn */` but psalm seems to ignore it.

> Closure does not have a return type, expecting mixed

https://psalm.dev/r/34ac45b249

**Comment by muglug** [comment]
You have to do it here: https://psalm.dev/r/f38ed2c769
