### ISSUE TITLE
--no-cache returns a different result than cached

### ISSUE THREAD

**Issue by jarstelfox** [vimeo/psalm#2891]
This sounds exactly like #1051.

Unfortunately, I can't reproduce it easily in simple codebases.

We are getting 4 errors on our code base if we use `--no-cache` and none if we omit the option.

If it helps the offending issues were:

* TraitMethodSignatureMismatch
* InvalidDocblock x 3

Version: Psalm 3.9.3@2e4154d76e24d1b4e59e6cc2bebef7790cb9e550

**Comment by muglug** [comment]
What sort of errors were the invalid docblocks?

**Comment by jarstelfox** [comment]
> What sort of errors were the invalid docblocks?

All of them were `Badly-formatted @param in docblock for <method_name>`

**Comment by jarstelfox** [comment]
> What sort of errors were the invalid docblocks?

All of them were `Badly-formatted @param in docblock for <method_name>`

Exs:

```php
/**
 * Function: something<br>
 * Purpose:  Blah blah blah
 *           Blah Blah blah.
 * @author   Its Mario <mario at nintendo dot com>
 * @param string
 * @return string
 */
```

```php
/**
 * Blah Blah Blah. Blah
 * example 1 => 1k, 2333 => 2.3k, 999999 => 999.9k.
 *
 * @author Author One, Author Two
 * @param string
 * @return string
 */
```

```php
/**
 * Blah blah blah
 *
 * Type:     modifier<br>
 * Name:     something<br>
 * Purpose:  Blah blah blah/Blah
 * @link https://www.php.net/manual/en/function.array-map.php
 *          Blah blah blah (Blah blah blah)
 * @author   Its Mario <mario at nintendo dot com>
 * @param string
 * @param string|array
 * @param string|array
 * @return string
 */
```

**Comment by muglug** [comment]
Is this still broken after ff9d774?

**Comment by jarstelfox** [comment]
> Is this still broken after [ff9d774](https://github.com/vimeo/psalm/commit/ff9d77430457aca044aec7a189735742871d4cb3)?

Looks like it. I checked out, dev-master@f44c3488ebbe4063819e24cd5f2c3c4c8e339e68.

I tried setting 2 baselines, 1 with cache, one without. The 4 psalm issues were the only difference.

**Comment by jarstelfox** [comment]
Hey, @muglug I think we got to the bottom of this on our end. We looked at the difference between

* `psalm --debug (FILE) > cache.out 2>&1`
* `psalm --debug --no-cache (FILE) > nocache.out 2>&1`

To us, it looks like our autoload file does not run unless we use `--no-cache`:

![Screen Shot 2020-08-04 at 3 22 53 PM](https://user-images.githubusercontent.com/857362/89351201-618f2200-d666-11ea-9eb1-e5e435c55e46.jpg)

Our autoload looks something like:
```php
<?
declare(strict_types = 1);

require 'IncludePathSetup.php';
IncludePathSetup::run();
```

**Comment by jarstelfox** [comment]
Oh hey @muglug, we solved this, but it is still a bug.

Steps to reproduce:

* Set `Tests/psalm-load.php`
```php
if (!defined('CODE_DIR')) {
   $codeDir = self::getCodeDir();
   define('CODE_DIR', $codeDir);
}
```

* Set the conf to:

```xml
<?xml version="1.0"?>
<psalm
    totallyTyped="false"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    errorBaseline="psalm-baseline.xml"
    autoloader="Tests/psalm-load.php"
    resolveFromConfigFile="true"
>
   <fileExtensions>
      <extension name=".php" />
   </fileExtensions>
   <projectFiles>
         <directory name="./"/>
        <ignoreFiles>
           <directory name="Tests"/>
        </ignoreFiles>
    </projectFiles>
</psalm>
```
* Notice: `psalm-load.php` is our autoloader and under the ignored `Tests` directory
* Run `psalm` twice (to ensure reading from cache)
* Notice psalm complains like:

```php
ERROR: UndefinedConstant - SomeFile.php:65:14 - Const CODE_DIR is not defined (see https://psalm.dev/020)
      return \CODE_DIR . '/tmp';
```
* Running `psalm --no-cache` the psalm complaint disappears

### Workaround

* Include this line in the conf
```
   <projectFiles>
         <file name="Tests/psalm-load.php"/>
   </projectFiles>
```

**Comment by jarstelfox** [comment]
@muglug thanks! I tested this out. This fixed the original issue: the UndefinedConstant / InvalidDocblocks are no longer an issue.

Note: `psalm --no-cache` is returning 457 issues vs while `psalm` is returning 418 issues.

I will leave it for now since I was testing an unreleased version. If the issue still persists I'll try and get you more info next release.
