### ISSUE TITLE
Psalm understood only primitive types in brackets

### ISSUE THREAD

**Issue by EvgeniiR** [vimeo/psalm#2892]
With primitive types(```@param (string|int)[] $x```) - found errors:
https://psalm.dev/r/669c0b478b

With classes(```@param (A|B)[] x```) - nope:
https://psalm.dev/r/b1388ba698

Also without [] - https://psalm.dev/r/17d9c1d795

Is it a bug, or we should use generics? 

Came here from - https://github.com/symfony/symfony/issues/35896

**Comment by muglug** [comment]
You’re missing a `$` sign in the docblock

**Comment by EvgeniiR** [comment]
@muglug Sorry for inappropriate example, here is complete example(copy-paste from symfony serializer) - https://psalm.dev/r/b072f752d7
