### ISSUE TITLE
--set-baseline in a git directory should only use tracked files

### ISSUE THREAD

**Issue by jarstelfox** [vimeo/psalm#2894]
@muglug I am curious if you agree with this.

With Psalm 3.9.3@2e4154d76e24d1b4e59e6cc2bebef7790cb9e550,

* Create a new git repo
* init psalm
* Create 2 php files with psalm errors
* Add one file to git, leave one untracked
* Commit the one file
* Run `psalm --set-baseline=psalm-baseline.xml`

Notice: psalm picked up the errors from changes that were uncommited

**Comment by muglug** [comment]
Yeah, Psalm doesn't care what's in the git repo, just the files covered by the Psalm config.
