### ISSUE TITLE
`Psalm\Config#$totally_typed` property removed in 3.9.x?

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2899]
While working on upgrades in downstream projects, I noticed some BC breaks in protected state. Specifically, `Psalm\Config#$totally_typed` is no longer visible (property seems to have been removed completely).

I know this was probably not intended to be maintained as a BC boundary in first place, but I suggest some more care when changing exposed (observable) API in general.

If I understand it correctly, when calling `Psalm\Config::__construct()`, `Psalm\Config#$level` is `1` by default, so `totally_typed` is not needed at all anymore?

**Comment by muglug** [comment]
Yeah, sorry this wasn’t great of me. With 3.9 that went away. Use `$this->show_mixed_issues !== false && $this->level === 1` instead to determine whether or not the user is likely to see the mixed issues reported as errors.
