### ISSUE TITLE
Analyzing Legacy Templates

### ISSUE THREAD

**Issue by psren** [vimeo/psalm#2902]
## The Problem

Some frameworks used to use PHP-Templates which used `echo` everywhere.
The Template-File is beeing loaded from a class and inherits the context of a given method.

I want to "describe" what variables/typed are beeing passed to the template,
so they can be statically analyzed.

## Examples

Then the output is being read from

```php
ob_start();
$data = $this->data();
extract($data, EXTR_OVERWRITE);

include __DIR__.'/../templates/magic.php';

return ob_get_clean();
```

Since this are 2 files I had problems recreating this on psalm.dev
Here's a try: https://psalm.dev/r/86a67e5e7b

If this is misleading I made a minimal [example repo](https://github.com/psren/static-analyzed-templats) including a [baseline file](https://github.com/psren/static-analyzed-templats/blob/master/psalm-baseline.xml).
(This shows what I try to catch)

In my original code (closed source repo) I want to analyze [Views & Presenter](https://github.com/fuelphp/display/blob/master/src/Presenter.php) from [FuelPHP](https://fuelphp.com/).

### Performing checks in the template

https://psalm.dev/r/629fd4b8be

👎 Shitload of work in 100+ Templates.
I'll definitely need to refactor them, but at the moment I'm looking for some sort of low hanging fruit.

### Using fancy annotations

https://psalm.dev/r/44a5698b6d

👎 Doesn't work.
In the real example it is also a bit more complex since most of the items beeing passed to the template are magic properties (🥇) from the `Presenter`.

```php
class Presenter_Index extends Presenter
{

    public function view()
    {
        $this->title = 'Testing this Presenter thing';

        $this->articles = Model_Articles::find('all');
    }
}
```

### Creating a custom `TemplateAnalyzer`

I tried this one: https://psalm.dev/docs/running_psalm/checking_non_php_files/
The docs seem to be out of date (`FileAnalyzer` is `@internal`) and I don't understand the `StatementsSource`-Interface.

```php
final class TemplateAnalyzer extends Psalm\Internal\Analyzer\FileAnalyzer {}
```

### Conclusion

I'm too stupid :-(
Can you help me to improve the docs, or point me in the right direction?

**Comment by weirdan** [comment]
> Creating a custom TemplateAnalyzer

Do you have a publicly available repo with your implementation of template analyzer?

**Comment by psren** [comment]
Not at the moment, but if this isn't a stupid way of triing it, i'll clean it up and come back to you in a few days.

**Comment by psren** [comment]
Oh, I just saw your hint, thank you very much
