### ISSUE TITLE
Detection of Exceptions can be improved

### ISSUE THREAD

**Issue by alfredbez** [vimeo/psalm#2908]
1. If a method throws an exception and the `@throws` declaration is wrong, it is not reported.
2. Uncatched exceptions are not reported.
3. Trying to catch an exception that is not thrown could be reported, but I'm not sure about this one. 

Example:

https://psalm.dev/r/147527b739

**Comment by weirdan** [comment]
You need to enable 'Check for `@throws` annotation` in snippet settings: https://psalm.dev/r/d58fa8d0db

**Comment by weirdan** [comment]
Also make sure you have [`checkForThrowsInGlobalScope`](https://github.com/vimeo/psalm/blob/master/docs/running_psalm/configuration.md#checkforthrowsinglobalscope) and [`checkForThrowsDocblock`](https://github.com/vimeo/psalm/blob/master/docs/running_psalm/configuration.md#checkforthrowsdocblock) options in `psalm.xml`. They both default to `false`.
