### ISSUE TITLE
Method calls on `mixed` seem to disable some checks

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#2909]
given

https://psalm.dev/r/785a5a9ad7

I would expect psalm to complain about `$param` not being defined.

**Comment by muglug** [comment]
This is not quite a bug - `$p` may be passed by reference

**Comment by pilif** [comment]
oh - yes. of course. I guess you're right.

**Comment by weirdan** [comment]
I'd think it's sensible to assume it's a non-reference parameter in this case - references are fairly rare nowadays.

**Comment by muglug** [comment]
Yeah, but so are undefined variables. I know that when I played with the default on Vimeo’s codebase about 3 years ago most of the things were by-ref args

**Comment by pilif** [comment]
I have a refined example like this:

https://psalm.dev/r/076608f041

this is broken code either way: Either the unknown method b() takes a reference at which point this expression isn't allowed to be passed as a parameter, or it doesn't, at which point, $a is undefined and can't be defined by b()

**Comment by muglug** [comment]
Yeah actually I’ve changed my mind - I’ll make sure those are all treated as bugs

**Comment by muglug** [comment]
The previous fix treated them as `UndefinedVariable`, but I ran the updated analysis on the Vimeo codebase and felt `PossiblyUndefinedVariable` was more appropriate.
