### ISSUE TITLE
Unexpected unused variable

### ISSUE THREAD

**Issue by balland** [vimeo/psalm#2910]
I would have expected `$a` to be considered as used. I can reproduce the bug only when the variable is used in a more complex expression. If I pass directly `$a` then it is considered as used.

https://psalm.dev/r/3dfb1d17df

**Comment by balland** [comment]
This was related to our attempt to reproduce https://github.com/vimeo/psalm/issues/2909

**Comment by pilif** [comment]
also, *very* much related to #2909, *this* instance of using an undefined variable should *definitely* be complained about: 

https://psalm.dev/r/076608f041

this is broken code either way: Either the unknown method b() takes a reference at which point this expression isn't allowed to be passed as a parameter, or it doesn't, at which point, $a is undefined and can't be defined by b()
