### ISSUE TITLE
`true` and `false` types don't seem to be matched as redundant when combined with `assert()`

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2915]
In following snippet (and any usage of `@psalm-return true` or `@psalm-return false`), the assertion and conditional should probably be detected as redundant:

```php
/** @psalm-return false */
function alwaysFalse()
{
    return false;
}

assert(! alwaysFalse());

if (alwaysFalse()) {
    echo "impossible";
}
```

https://psalm.dev/r/d466b99dbc

**Comment by weirdan** [comment]
But the message needs to be worded carefully, to not give the user impression that **the call itself** is redundant.

**Comment by muglug** [comment]
Yeah, I'm just not sure about this.

I sometimes see things like

```
if (true) {
```

in scripts and crons, and I don't want Psalm to flag this pretty obvious issue.

**Comment by Ocramius** [comment]
That stuff should be commented out, no?

**Comment by muglug** [comment]
I don't think so – they often just act as _really_ crude feature flags.

**Comment by Ocramius** [comment]
Probably should be `if ($_GET[...]) {` (or `if (getenv(...)) {` or actual feature flags) in most cases. Most certainly not for code that goes under static analysis scrutiny, but rather is stashed away in procedural blocks that are not critical.

**Comment by Ocramius** [comment]
In the grand majority of cases (empirical personal experience) a conditional that is always redundant is not intentional, and flagging it is probably better (can always suppress for single statements, no?)

**Comment by Ocramius** [comment]
\o/ thanks for the fix!
