### ISSUE TITLE
DocblockTypeContradiction with template as object

### ISSUE THREAD

**Issue by dbrekelmans** [vimeo/psalm#2918]
This might be a duplicate of https://github.com/vimeo/psalm/issues/2916, but I'm not quite sure if this is a different case due to the `@template` used.

```
ERROR: DocblockTypeContradiction - 41:17 - Found a contradiction with a docblock-defined type when evaluating $element and trying to reconcile type 'E:Sequence as object' to !object
```

See snippet for full example: https://psalm.dev/r/63a52b780d

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/5d49605f18
