### ISSUE TITLE
confusion around closures use()ing themselves

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#2922]
I admit that this is really, really, really bad code - but hey - if it's a bad pattern, it's probably in the code-base I'm working with ATM

https://psalm.dev/r/b3302fdaab

All `INFO`s reported by this snippet are false-positives. `$foo` used by the closure is totally fully defined.

I'm somewhat afraid that this one is very hard to fix because psalm can't know the type of the `use()`d `$foo` before finishing evaulating the assignment which also requires knowing the type of `$foo`.

I'm leaving this issue here for reference - if you think it's not worth fixing, I'm happy too.

**Comment by muglug** [comment]
yeah, sorry but I'm going to close this
