### ISSUE TITLE
Is it possible to auto-annotate thrown throwables?

### ISSUE THREAD

**Issue by Aerendir** [vimeo/psalm#2926]
As per the title, I'm trying to figure out if it is possible to automatically annotate thrown throwables, either using `psalm --fix` or using `psalter`.

I'm playing with two plugins: one that implements `AfterAnalysisInterface` and one that implements `AfterClassLikeAnalysis`.

Now, from a plugin that implements `AfterClassLikeAnalysis` it is possible to modify the code, but I haven't access to the list of found issues;
From a plugin that implements `AfterAnalysisInterface` it is possible to access to the found thrown and not annotated throwables, but it is not possible to modify the code.

Am I right or am I missing some pieces of the puzzle?

**Comment by muglug** [comment]
I wouldn't create a plugin for this – I'd add this directly to the Psalm codebase. Have a look at how `InvalidReturnType` issues are fixed in Psalter.
