### ISSUE TITLE
3.9.4: Exception can not be used in a pure context

### ISSUE THREAD

**Issue by jarstelfox** [vimeo/psalm#2927]
https://psalm.dev/r/a123ef2aa1

I might be crazy, but I think this is a bug.

It does seem like exception should be allowed to be created in pure contexts

**Comment by weirdan** [comment]
Exception is allowed to be created in impure context when it's thrown: https://psalm.dev/r/d25209b735
Function returning the exception cannot be pure, because its return value (the exception) contains a backtrace which depends on where it was called from (among other things): https://3v4l.org/pG4kF

**Comment by jarstelfox** [comment]
Yea that does make sense. For clarity, I have a box with data or an exception:

https://psalm.dev/r/237d413eab

My idea was to be able to map over the data and catch any errors, put them in the box.

I understand if that does not make the methods pure - however, the functions do only depend on the input of the functions.

**Comment by jarstelfox** [comment]
I don't mind marking these methods as impure. Just a surprising behaviour in my opinion!

* Would you consider allowing exception creation as pure? 

If not, feel free to close.

I know a few ways to handle this - just wanted to get clarity from you guys.

**Comment by weirdan** [comment]
It's been discussed in #2160, and Psalm adopted a middle ground - you can throw exceptions from pure functions as a thrown exception is not considered a proper function output, but you can't return them.

**Comment by jarstelfox** [comment]
Fair enough! Sorry I was having trouble finding where this was discussed.
