### ISSUE TITLE
Psalm unable to infer generic type when templated class implements a templated interface

### ISSUE THREAD

**Issue by ocrampete16** [vimeo/psalm#2928]
I've created a snippet to illustrate the issue: https://psalm.dev/r/557d8b895c

The first `foreach` block:
```
/** @var Collection<int, string> $foo */
$foo = new FooCollection(['foo']);
foreach ($foo as $bar) {
  $bar + 1;
}
```
results in `Cannot perform a numeric operation with a non-numeric type string`. So Psalm knows that `$bar` is a string. So far so good.

When I use the concrete class in the type hint (or leave the docblock out completely), Psalm is unable to infer that `$bar` is a string instead of `mixed`, even though it knows that it is of type `FooCollection<int, string>`:
```
/** @var FooCollection<int, string> $foo */
$foo = new FooCollection(['foo']);
foreach ($foo as $bar) {
  $bar + 1;
}
```
Running Psalm with the second `foreach` block gives me:
```
INFO: MixedAssignment - 45:18 - Cannot assign $bar to a mixed type

INFO: MixedOperand - 46:3 - Left operand cannot be mixed
```

**Comment by muglug** [comment]
You can fix this by adding  a return type  to `getIterator`: https://psalm.dev/r/3f8b934c61

Still not sure if this is a bug, though

**Comment by ocrampete16** [comment]
Awesome, thanks for the swift fix!
