### ISSUE TITLE
Crash when parsing MadelineProto

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#2932]
psalm seems to crash when parsing my main project, MadelineProto.
I would love to help localizing the exact source of the issue, but I can't quite understand what file is causing it.
Here are the single-threaded [debug](https://hastebin.com/vomoloqala.sql) and [debug-line](https://gist.github.com/danog/f4e77ceb3c352a5dd156d118b847a3f5) outputs of psalm with the thrown exception.

**Comment by danog** [comment]
Hi there friendly bot, would love to, but I can't quite figure out what is causing it.
When trying to parse `src/danog/MadelineProto/MTProto.php`, psalm.dev crashes with an `Internal Psalm error on line undefined - undefined`.

**Comment by weirdan** [comment]
https://psalm.dev/r/aadbf06ed9 - this reproduces the crash indicated by the debug-by-line link in the ticket description

**Comment by danog** [comment]
Great, you found the issue! ❤️
I guess I don't need that legacy condition after all, since is_callable works with array class callables anyway. 

P. S. 
BTW, Sorry for the ugly lack of parenthesis, recently did a mass refactor with php-parser that removed some unnecessary brackets.
