### ISSUE TITLE
Detect mutable in immutable class on definition level

### ISSUE THREAD

**Issue by snapshotpl** [vimeo/psalm#2933]
Fixes introduced here https://github.com/vimeo/psalm/issues/2805 works on class usage. But IMO it should be detected on class definitions.
https://psalm.dev/r/74b7779d86

**Comment by muglug** [comment]
I don’t see the problem here - can you provide an example where purity/immutability promises are broken?

**Comment by weirdan** [comment]
If Foo is only used externally (is a part of library API) and your tests are not type-checked Psalm wouldn't highlight the issue above.

**Comment by muglug** [comment]
Yeah, but the same goes for a lot of Psalm's issues.
