### ISSUE TITLE
3.9.4 release produces analysis errors that previously did not exist

### ISSUE THREAD

**Issue by ramsey** [vimeo/psalm#2934]
Perhaps this was purposefully done, but it was unexpected for me to have builds start failing because `composer install` grabbed version 3.9.4 of Psalm instead of 3.9.3.

You can see the failing build here: https://travis-ci.org/ramsey/uuid/builds/659625125

All of the errors are `MutableDependency` and `ImpureArgument` errors.

An additional `RedundantCondition` error occurred on 32-bit PHP (see https://travis-ci.org/ramsey/uuid/jobs/659625128).

These are obviously issues with the ramsey/uuid code, and I have committed changes to fix them ([1](https://github.com/ramsey/uuid/commit/57e3ce9dd7f06c9448341bb78ca15307e310b81e), [2](https://github.com/ramsey/uuid/commit/5ed0ba442d2b60bc279d7be473451b224b24480a)).

I am reporting this because these changes broke backward compatibility in Psalm, even though they may be considered "bug fixes," and because of the versioning scheme used (patch-level version increase), downstream projects are affected. Others may be experiencing similar broken builds.

**Comment by muglug** [comment]
In the main this is an issue endemic to static analysis tools: semver for us (PHPstan, Phan and Psalm) means that our APIs don’t change between minor releases.

It cannot mean “keep the tool’s output between major version changes the same”, because that would require that almost every release would have to be a major version. Even when no new issue types are added, fixing false negatives means that users would see new issues where there their builds had previously been green.

**Comment by ramsey** [comment]
Honestly, I don't know how to feel about it. One one hand, I see your point, and you're right, but on the other hand, it's jarring to have builds passing for weeks and then, suddenly, to see them failing, with no change whatsoever on my end.

I don't know the solution. I'm just raising it as an issue and pointing it out, in case others have similar issues.

Thanks!

**Comment by muglug** [comment]
If it bothers you the solution is to pin your composer dependency for Psalm so there’s no worry the rug will be pulled from underneath you.

**Comment by ramsey** [comment]
I know. 😄

**Comment by weirdan** [comment]
And you can combine it with automatic dependency upgrade system like Dependabot so instead of getting failures on cron builds (or worse - on unrelated pull requests) you would get dependency update pull requests you can merge at your convenience.

**Comment by ramsey** [comment]
Thanks for the tip! Added Dependabot to my repos.
