### ISSUE TITLE
Idea: @psalm-signature annotation

### ISSUE THREAD

**Issue by ragboyjr** [vimeo/psalm#2936]
```php
// convert this
/**
 * @template T
 * @template U
 * @template V
 * @param callable(U): V $f
 * @param callable(T): U $g
 * @return callable(T): V
 */
function compose(callable $f, callable $g): callable {
    return function($v) use ($f, $g) { 
        return $f($g($v));
    };
}
// into this
/** @psalm-signature <T, U, V>((U): V, (T): U): (T): V */
function compose(callable $f, callable $g): callable {
    return function($v) use ($f, $g) { 
        return $f($g($v));
    };
}
```

In an effort to reduce some of the boilerplate associated with psalm typings across more complex definitions, I'd like to see what we think about adding a new signature annotation that would allow us to parse out a terse signature as shown above.

**Comment by muglug** [comment]
This seems useful only for annotating higher-order functions, which is a pretty niche area of the language, and I think it only really makes sense if you’re familiar with Ocaml or the like.

BUT I think a tool that could translate between an OCaml function signature and Psalm template annotations would be pretty cool

**Comment by ragboyjr** [comment]
Interesting, how would you suggest this tool would work or be integrated?

Separately, I'd imagine psalm-signature would be translated basically into the current set of annotations.

I think defining higher order functions in application is definitely a bit more rare, but I do think defining higher order functions in library code is a lot more common.

Do you know if a plugin would be able to register and handle annotations?

**Comment by muglug** [comment]
I was thinking of just a simple command-line tool to split out generated code - like

```
vendor/bin/hof-to-php “compose((U): V, (T): U): (T): V”
```

Which would spit out

```php
/**
 * @template T
 * @template U
 * @template V
 * @param callable(U): V $f
 * @param callable(T): U $g
 * @return callable(T): V
 */
function compose(callable $f, callable $g): callable {
    return function($v) use ($f, $g) { 
        return $f($g($v));
    };
}
```

I appreciate this is the exact opposite of what you’re asking for, but I think Psalm’s annotation is still relatively clear to people used to using PHP docblocks, and I’d like to keep it that way.

**Comment by weirdan** [comment]
>  I think it only really makes sense if you’re familiar with Ocaml or the like.

Or Typescript, which is much more mainstream:
```typescript

function compose<T,U,V>(f: (v: U) => V, g: (v: T) => U): (v: T) => V {
    return function(v) { 
        return f(g(v));
    };
}

```

[Playground Link](https://www.typescriptlang.org/play/index.html#code/FAMwrgdgxgLglgewgAiggtgBwQZwKYA8AKgDQCqJAagHwAUIAXMrQG5NkCUyAvNcpSWQBzJqyZEuvZJ1FtkEnn0rIA3sGQbkAJzwwwWlOGjwkrLiuTrN1nXoPIQtIWY4BuKxoC+7z8CA)

**Comment by muglug** [comment]
Ok, that's fair, but parsing that signature still requires, in my mind, an amount of cognitive overhead that's not common in developers in general.

Even though I've been taught lambda calculus it still takes me a second to understand what's going on, and I don't really want to make that harder.

**Comment by weirdan** [comment]
Yeah, I'm not advocating in favor of that.

**Comment by ragboyjr** [comment]
Ya, the typescript syntax takes me a bit to understand what's going on as well, but I think the main reason I prefer this syntax is because it allows for one line signatures and cut down on the documentation noise that would take 3-4 lines to implement properly.

```php
/** @psalm-signature (int, string, array{key1?: int, key2?: string}): void */
public function execute($arg1, $arg2, array $options = []) {}

// vs
/**
 * @param int $arg1
 * @param string $arg2
 * @param array{key1?: int, key2?: string} $options
 * @return void
 */
public function execute($arg1, $arg2, array $options = []) {}
```
