### ISSUE TITLE
class_exists && method_exists is not parsed properly

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#2939]
https://psalm.dev/r/f8851e801d

**Comment by weirdan** [comment]
Switching to `Thread::class` instead of a bare string helps: https://psalm.dev/r/c402c23071
Enabling [`allowStringToStandInForClass`](https://github.com/vimeo/psalm/blob/master/docs/running_psalm/configuration.md#allowstringtostandinforclass) might help as well (not available on psalm.dev).

**Comment by muglug** [comment]
Yeah, just use class constants here
