### ISSUE TITLE
UndefinedClass: Class or interface Boolean does not exist

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#294]
It seems odd that Boolean is case sensitive (and possibly unintentional), other class names are case insensitive.

This isn't reserved/soft reserved: http://php.net/manual/en/reserved.other-reserved-words.php

Same for integer, double, etc.

```
ERROR: UndefinedClass - src/bool.php:7:1 - Class or interface Boolean does not exist
/**
 * @param Boolean $x
 * @param boolean $y
 */
function foo($x, $y) : bool {
```

**Comment by muglug** [comment]
Hmm I don't actually think this is wrong, given the general convention that CamelCased names refer to classes.

**Comment by weirdan** [comment]
[PHPDoc reference](http://docs.phpdoc.org/references/phpdoc/types.html#keyword) specifically mentions that type keywords (like `boolean`) must be in lowercase:

> Note: Most of these keywords are allowed as class names in PHP and as such are hard to distinguish from real classes. As such the keywords MUST be lowercase, as most class names start with an uppercase first character, and you SHOULD NOT use classes with these names in your code.

**Comment by muglug** [comment]
Yeah I'm gonna say this is by design
