### ISSUE TITLE
Uncaught Exception: Could not locate trait statement

### ISSUE THREAD

**Issue by kelunik** [vimeo/psalm#2951]
```
git clone https://github.com/amphp/amp
cd amp
./vendor/bin/psalm.phar --init
```

```
Psalm 3.9.4@352bd3f5c5789db04e4010856c2f4e01ed354f4e
```

Running `--init` on Amp currently isn't possible. This is due to the conditional definition of our [`CallableMaker` trait](https://github.com/amphp/amp/blob/34bcf727dcc8d99184d1dc32c16d1f220288b119/lib/CallableMaker.php). Can I work around this or could Psalm be extended to evaluate `PHP_VERSION_ID` and pick the right version?

**Comment by kelunik** [comment]
Not really, it says `ERROR: DuplicateClass - 56:11 - Class Amp\CallableMaker has already been defined` there. https://psalm.dev/r/a6601ab157

**Comment by weirdan** [comment]
Similar bug reported on phpunit plugin: https://github.com/psalm/phpunit-psalm-plugin/issues/56, also involving conditionally defined trait: https://github.com/symfony/symfony/blob/14b825b24fece6a4853d7bf537b86df88d3bfcc1/src/Symfony/Component/Validator/Test/ForwardCompatTestTrait.php

**Comment by muglug** [comment]
I'll release a fix today for this that uses reflection to determine the winner when there's more than one trait defined in a given file.

**Comment by kelunik** [comment]
@muglug Thanks for the quick fix. Now I get the `DuplicateClass` as on psalm.dev. I guess this error needs to be suppressed by me now?

```
ERROR: DuplicateClass - lib/CallableMaker.php:56:11 - Class Amp\CallableMaker has already been defined in /home/kelunik/GitHub/amphp/amp/lib/CallableMaker.php
    trait CallableMaker
```

**Comment by kelunik** [comment]
Adding `@psalm-suppress DuplicateClass` to both definitions doesn't seem to help.

**Comment by muglug** [comment]
You can suppress that in your `psalm.xml`:

```
    <issueHandlers>
        <DuplicateClass>
            <errorLevel type="suppress">
                <file name="lib/CallableMaker.php" />
            </errorLevel>
        </DuplicateClass>
    </issueHandlers>
```

**Comment by kelunik** [comment]
Thanks!
