### ISSUE TITLE
Psalm breaks horribly if line breaks are CRLF

### ISSUE THREAD

**Issue by ArSn** [vimeo/psalm#2953]
### Scenario
I am currently fiddling around a bit with [ubuntu for windows](https://ubuntu.com/tutorials/tutorial-ubuntu-on-windows#1-overview) and I thought psalm would be a great project to work on with this. I installed all composer packages and required PHP extensions and even the suggested `ext-igbinary`.

It took me a few days to realize that this was not the issue, but the fact that I checked out psalm with PHPStorm on windows and was using it in the ubuntu command line. This lead to the line breaks in the code being CRLF (aka `\r\n`) instead of only LF (aka `\n`).

To help debug this I created some examples ( ⚠️ careful, they only break if your linebreaks are CRLF, which is obviously not shown in the code below):

### How to reproduce
code:
```php
<?php

namespace Some\Weird\Space;


class A {
    /**
     * @param string|null $bla
     * @return array{
     *          0: \Some\Weird\Space\A|null,
     *          1: null
     *          }
     */
    public function doSomething($bla): array
    {
        echo '1' . (string)$bla;
        return [null, null];
    }
}

$bla = new A();
$bla->doSomething('2');
```

output:
```
Scanning files...
Analyzing files...

E

' in docblock for Some\Weird\Space\A::doSomething type 'Some\Weird\Space\null
    /**
     * @param string|null $bla
     * @return array{
     *          0: \Some\Weird\Space\A|null,
     *          1: null
     *          }
     */
    public function doSomething($bla): array


------------------------------
1 errors found
------------------------------

Checks took 1.40 seconds and used 117.811MB of memory
Psalm was able to infer types for 100% of the codebase
```

### Expected output
just leaving this here as a reference for the full bug report, and it works fine if the linebreaks are LF only:
```
Scanning files...
Analyzing files...

░

------------------------------
No errors found!
------------------------------

Checks took 1.41 seconds and used 117.818MB of memory
Psalm was able to infer types for 100% of the codebase
```

### Remarks
My guess is that this has something to do with the tokenization going wrong and I have it in the back of my mind that there was some piece of code that I stumbled upon during debugging that was just searching for `\n` and nothing else, which sounds like it could have to do with it, but I could not find it again yet.

That being said, my debugging efforts only led to this guess so far and I can not really put my finger on it as you can probably tell.

Given that nobody else seems to have stumbled upon this so far I wonder if it is even relevant, but if so, I would be happy to dig deeper and find a solution - just let me know! Thanks!

**P.S.:** I almost forgot to add. I was not looking for that problem but when I run `./psalm` on master in this configuration, it throws over 400 errors because of this problem.

**Comment by weirdan** [comment]
Similar: #2859

**Comment by muglug** [comment]
Can this be replicated in any sort of test? Maybe one that uses `str_replace` to replace line endings before sending to Psalm?

**Comment by weirdan** [comment]
Could be reproduced on Psalm's codebase (probably any sufficiently large and complex codebase would do): just convert all PHP files to DOS line endings:
```console
$ find src -type f -exec sed -i 's/$/\r/g' {} \;
```

**Comment by muglug** [comment]
Yeah but I <3 tests

**Comment by Rarst** [comment]
I tried to running current unit tests on Windows for starters.

With CRLF line endings (which is how git checks out by default on Windows):

```
ERRORS!
Tests: 4531, Assertions: 9824, Errors: 15, Failures: 191, Skipped: 29.
```

With LF line endings (search/replace on *.php):

```
ERRORS!
Tests: 4531, Assertions: 9931, Errors: 2, Failures: 1, Skipped: 29.
```

So line endings of Psalm source do seem to make a significant impact on operation...

Might make sense to add Windows to CI, if possible?

**Comment by Rarst** [comment]
As a git level fix, it seems `.gitattributes` can be configured to normalize to specific line endings, which would prevent source from ending up with CRLF line endings on Win:

```
*.php	text eol=lf
```
https://www.git-scm.com/docs/gitattributes#_code_eol_code

**Comment by weirdan** [comment]
> Might make sense to add Windows to CI, if possible?

There are Windows CI jobs running on AppVeyor: e.g.https://ci.appveyor.com/project/muglug/psalm/builds/31356395

**Comment by Rarst** [comment]
Ah, missed it, sorry! :) Any idea what its git settings are in regards to CRLF?

**Comment by weirdan** [comment]
It's `core.autocrlf=input`, according to their KB: https://www.appveyor.com/docs/windows-images-software/#version-control-systems

**Comment by Rarst** [comment]
Yeah, `input` would not cause CRLF check out (only enforce `LF` on commit), while it's commonly `true` on Windows because that's git installer default/recommended.

**Comment by ArSn** [comment]
I want to point out that this is an issue when checking code that has CRLF breaks in it - not only for psalm checking itself. None the less thanks for all your input!

I agree with @muglug that we should add an test for this and from your feedback on the issue I gather that it is a relevant point, so I will look deeper into it and try to provide a fix.

**Comment by muglug** [comment]
AppVeyor builds will now run with CRLF breaks after 9484231 which should prevent this, once fixed, from reoccurring

**Comment by ArSn** [comment]
I can confirm this works like a charm now - thanks for the quick fix!
