### ISSUE TITLE
Error and Exception class methods seems to be mutation free

### ISSUE THREAD

**Issue by Daeroni** [vimeo/psalm#2956]
The built in Error and Exception classes seem to have only final methods that are mutation free, and thus should be able to be called from a pure context.

https://psalm.dev/r/f405c53d93

**Comment by muglug** [comment]
But it's trivial to craft an exception with an impure `getMessage` call: https://psalm.dev/r/1931963daa

**Comment by weirdan** [comment]
@muglug exception methods have become final in 7.4: https://3v4l.org/T3es5 , so I think it's a valid request.

**Comment by weirdan** [comment]
@muglug your snippet causes fatal error (that Psalm doesn't notice): https://3v4l.org/O4tHG
```
Fatal error: Cannot override final method Exception::getMessage() in /in/O4tHG on line 11

Process exited with code 255.
```

**Comment by Daeroni** [comment]
The methods of Error and Exception classes are final, and cannot be overriden, and no other classes can implement the Throwable interface. Thus your example is wrong, and wont compile:

```
php > class MutatingException extends Exception {
php {     public function getMessage() : string {
php {         return "hello" . date('s');
php {     }
php { }
PHP Fatal error:  Cannot override final method Exception::getMessage() in php shell code on line 2
```

**Comment by muglug** [comment]
well damn, I guess we all learned something today (that I should check code on 3v4l.org more often)
