### ISSUE TITLE
All methods of DateTimeInterface seem to be mutation free

### ISSUE THREAD

**Issue by Daeroni** [vimeo/psalm#2957]
All methods defined by the DateTimeInterface seem to be mutation free, and thus should be able to be called from a pure context.

https://psalm.dev/r/3514312f8e

**Comment by Daeroni** [comment]
It seems that DateTime and DateTimeImmutable does not define these methods as final, and they can be overriden to be not mutation-free so this bug might be invalid

**Comment by muglug** [comment]
Yeah ok, closing
