### ISSUE TITLE
Possible bug in template handling

### ISSUE THREAD

**Issue by andyg0808** [vimeo/psalm#2959]
I think there's a type error in this code in the call of `idx`:
https://psalm.dev/r/0c513d0612
The `$key` parameter has type `string` while the array has `int` keys, and those are supposed to have the same template type. I'd expect that I get a type error in that case?

There also should be a type error in this case, when passed a variable in place of the literal:
https://psalm.dev/r/8fb363edba

**Comment by muglug** [comment]
> The $key parameter has type string while the array has int keys, and those are supposed to have the same template type. I'd expect that I get a type error in that case?

That's not how Psalm's (and Hack's) templating model behaves. Instead the template `K` is resolved to the union of all inputs. Here's a better example of the behaviour: https://psalm.dev/r/c99d0b9f85
