### ISSUE TITLE
Make plugin config available in hooks

### ISSUE THREAD

**Issue by seferov** [vimeo/psalm#2964]
Hello 👋 

When developing a plugin using `PluginEntryPointInterface`, plugin config is available in `__invoke` method. It is useful. In the same method, `RegistrationInterface` register hooks by only accepting the hook class name. I think it would be very really useful if custom object(s) can be passed to register and make it available for the hook class as well.

By the way, I know in hook classes, there is `$codebase->config` and config xml can be accessed like this which does not look good:

```php
$simpleXmlConfig = null;
if (count($codebase->config->getPluginClasses())) {
    foreach ($codebase->config->getPluginClasses() as $pluginClass) {
         if ($pluginClass['class'] === str_replace('Handler', 'Plugin', __NAMESPACE__)) {
             $simpleXmlConfig = (string) $pluginClass['config'];
         }
    }
}

// do some calculations based on $simpleXmlConfig
```

After that if it involves some same calculations based on the config in **each** hook, it affects performance badly. I would love do these calculations before registration of hooks and pass the result to hooks.

**Comment by weirdan** [comment]
Ideally hooks would just be proper objects that could have their dependencies passed to their constructors. Meanwhile you can have something like this:
```php
class EntryPoint implements PluginEntryPointInterface {
   public function __invoke(..., ?SimpleXmlElement $config): void {
         $processedConfig = $this->processConfig();
         HookClass::init($processedConfig);
   }
}

class HookClass implements ... {
   private static $config = null;
   public static function init($config): void {
       self::$config = $config;
   }
  // ........
}
```

**Comment by seferov** [comment]
Right, it would be best if hooks were objects.
Thank you, your workaround seems legit.

**Comment by muglug** [comment]
@weirdan / @seferov could you show what that would look like? I'm happy to add support for that model somehow

**Comment by weirdan** [comment]
@muglug 
The end goal would be for Psalm to accept object instances instead of classes:

```php
       /** @var Psalm\Plugin\RegistrationInterface $psalm */
        $psalm->registerHooksFromClass(HookClass::class);
        // will become
        $psalm->registerHooks(new HookClass(...));
```
This will require new versions of all hook interfaces because currently they mandate static method that can't access object data (`$this` is unavailable in static methods).
