### ISSUE TITLE
Uncaught DocBlockParseException for invalid inline var comment

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#297]
This has an invalid union type in an inline doc comment.
Observed: the inline doc comment results in an uncaught DocBlockParseException.
Expected: An INFO level notice about the doc block.

A fix is in progress.

```php
<?php

/**
 * @return array(string) This is invalid PHPdoc, and is properly warned about by psalm,
 */
function returns_strings() {
    /** @var array(string) $result also invalid, but crashes DependencyFinderVisitor*/
    $result = ['example'];
    return $result;
}
```

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/b2ae9a2892a62ebfe56b2478f20e23b5cf7e12ed
