### ISSUE TITLE
Object from static template not compatible with Object expected by class template

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2973]
Hi,

In this example, I expected everything to go well.

It tells me that my static template extending Subject is not compatible with the class template extending Subject but I don't see why.

Replacing `@template S of Subject` by `@template S of U` doesn't change anything

https://psalm.dev/r/7d3136c23f

**Comment by muglug** [comment]
Yeah it goes away with an explicit constructor: https://psalm.dev/r/66fd5849b7

**Comment by orklah** [comment]
> Yeah it goes away with an explicit constructor: https://psalm.dev/r/66fd5849b7

Oh, thanks the tip. I have quite a lot of child of EventAbstract though. If you intend to fix it, I'll wait for next release ;)

Thanks
