### ISSUE TITLE
Consider failing analysis with an error when baseline contains non-applicable exclusion

### ISSUE THREAD

**Issue by localheinz** [vimeo/psalm#2979]
Thanks to the baseline feature of `vimeo/psalm`, we can currently suppress errors that we can not or do not want to fix at the moment.

Now, after removing said code, running `vimeo/psalm` does not result in an error, which is not a problem.

However, when regenerating the baseline at a later time, for example, when making changes to other code, inspecting the diff reveals that the baseline contains unrelated changes (the removal of the errors related to the previously removed code).

How do you feel about failing the run when the baseline contains non-applicable errors, similar to `phpstan/phpstan`?

**Comment by localheinz** [comment]
Thanks for asking, 🤖, but since https://psalm.dev does not allow specifying a baseline, I believe that is not possible at the moment.

🤓

**Comment by muglug** [comment]
> How do you feel about failing the run when the baseline contains non-applicable errors

It could be something that's triggered when running with `--find-unused-psalm-suppress`, but I don't want to make it the default.

If you just want to remove items from the baseline, `--update-baseline` with remove them without adding new ones (use `--set-baseline` for that)

**Comment by VincentLanglet** [comment]
> If you just want to remove items from the baseline, `--update-baseline` with remove them without adding new ones (use `--set-baseline` for that)

When we're adding some comment to explain why the error is ignored, we're loosing the comment with `--update-baseline`. Having the same feature than phpstan which report unused baseline would be great indeed, it'll help to reduce the baseline file size.

**Comment by boesing** [comment]
>It could be something that's triggered when running with `--find-unused-psalm-suppress`, but I don't want to make it the default.

I would be +1 on this aswell. Maybe another `--fail-on-updatable-baseline` (which probably enables `--find-unused-psalm-suppress` inside of psalm aswell) may work?

**Comment by VincentLanglet** [comment]
To be consistent with `--find-unused-psalm-suppress` it could be `--find-unused-baseline` ?

**Comment by weirdan** [comment]
Implemented in #9130 

You can enable it with [the config attribute `findUnusedBaselineEntry="true"`](https://psalm.dev/docs/running_psalm/configuration/#findunusedbaselineentry).

**Comment by localheinz** [comment]
Thanks a ton, @weirdan!
