### ISSUE TITLE
Documentation: Generator<array-key, mixed, mixed, void>?

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#2984]
Psalm infers Generator return types like `Generator<array-key, mixed, mixed, void>`.

The first two parameters probably refer to the `yield` key and value, but what are the third and fourth parameter for?

(Unfortunately the Psalm documentation doesn't explain this.)

**Comment by andrew-demb** [comment]
Types for `send()` and `throw()`

**Comment by caugner** [comment]
Thanks @andrew-demb!

Would be great to document this here:
https://github.com/vimeo/psalm/blob/master/docs/annotating_code/type_syntax/atomic_types.md

**Comment by caugner** [comment]
https://psalm.dev/r/31e1f15a77

**Comment by caugner** [comment]
@andrew-demb It looks like psalm does not support a `send()` type other than `mixed`:
https://psalm.dev/r/b6bedecbb9

**Comment by andrew-demb** [comment]
Sorry, I was wrong in my suggestion about `throws`.
https://github.com/vimeo/psalm/blob/474b9dc01b2024ed6288b506f9487358b7813bf4/src/Psalm/Internal/Stubs/CoreGenericClasses.phpstub#L190-L198

Why `send` template is not working, I don't know yet :)

**Comment by caugner** [comment]
Thanks for the update, I have updated #2984 accordingly. 👍 

Didn't think of looking it up int he stubs code myself, will do that in the future! 😃
