### ISSUE TITLE
Annotation of "callbacks" makes psalm throw an error

### ISSUE THREAD

**Issue by Fredrik82** [vimeo/psalm#2985]
### Issue
Psalm trows an error if you try to pass a `callable` to a method that is (PHP doc) annotated with `callback`. There is no way in PHP to cast an object from `callback` to `callable` (at least that I know of 🤷‍♂). Test will fail unless this is added to the baseline.

### Reference

Consider
https://psalm.dev/r/afac6ade05

According to [php.net](https://www.php.net/manual/en/language.types.callable.php) `callback` can be denoted as `callable` as of PHP 5.4.

### Proposal
Consider `callable` === `callback`

**Comment by weirdan** [comment]
`callback` was never a valid type in phpdoc. It was used exclusively by PHP doc website and wasn't intended to be used elsewhere.

**Comment by muglug** [comment]
Yeah, not a bug

**Comment by Fredrik82** [comment]
Not a bug, just a suggestion for improvement 🙂
