### ISSUE TITLE
Markdown: Unordered list after ordered list displayed as (continuing) ordered list

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#2988]
Just noticed that my changes from #2986 don't show up [on the site](https://psalm.dev/docs/annotating_code/type_syntax/object_types/) as expected.

## Source

```md
#### Generators

Generator types support up to four parameters, e.g. `Generator<int, string, mixed, void>`:

1. `TKey`, the type of the `yield` key - default: `mixed`
2. `TValue`, the type of the `yield` value - default: `mixed`
3. `TSend`, the type of the `send()` method's parameter - default: `mixed`
4. `TReturn`, the return type of the `getReturn()` method - default: `void`

- `Generator<int>` is a shorthand for `Generator<mixed, int, mixed, void>`
- `Generator<int, string>` is a shorthand for `Generator<int, string, mixed, void>`
```

## GitHub

![grafik](https://user-images.githubusercontent.com/495429/76966299-0b734980-6926-11ea-89be-115acd7fa505.png)

## psalm.dev

![grafik](https://user-images.githubusercontent.com/495429/76966318-129a5780-6926-11ea-85f9-b2198e7dedc5.png)

**Comment by muglug** [comment]
At the mercy of the python markdown package here. I've converted those into paragraphs.
