### ISSUE TITLE
Derive type of array element after explicit type check with null-coalescing operator

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#2990]
It would be great if Psalm could infer that (1.) `is_bool($array['foo'] ?? null)`  is equivalent to (2.) `isset($array['foo']) && is_bool($array['foo'])` w.r.t. `$array['foo']` being `bool` in the following block.

1. https://psalm.dev/r/b9ea8bbb2f
2. https://psalm.dev/r/82286d1579

**Comment by muglug** [comment]
I could write code for this specific pattern, but I think it would complicate some some already-pretty-complicated machinery.
