### ISSUE TITLE
Heavy memory usage on cache populate

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2992]
at work, when running Psalm for the second time, I get the error:
`PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 20480 bytes) in C:\[path]\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Populator.php on line 1143`

What's strange is that the first run is ok and if I launch with --no-cache after the first run, it can run without issues.

Somehow, retrieving the cache needs more memory than running the program itself.

I don't know if anything can be done here. Maybe detect memory related crash and disable cache in this case?

**Comment by dereuromark** [comment]
Same here
```
vendor/bin/psalm --init
Calculating best config level based on project files
Calculating best config level based on project files
Scanning files...
PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted 
(tried to allocate 80909248 bytes) in project/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php on line 331

Fatal error: Allowed memory size of 8589934592 bytes exhausted 
(tried to allocate 80909248 bytes) in project/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php on line 331
```

**Comment by orklah** [comment]
Not sure it's really related. You try to --init, which seems to imply it's your first run.

In my case, the first run is fine but on the second one, the memory needed to load the cache is way higher than the memory needed to run psalm in the first place.

I believe in my case it's because we have a lot of classes related to each other and it's heavy to load.

In your case, if it's only the --init that fails, I'd advice giving psalm a level (for example `vendor\bin\psalm --init src 6`) to try to see if it's better once the init is done.

**Comment by dereuromark** [comment]
It was the first run, and even after setting the init file, an actual 2nd like in your case yields the same fatal memory errors.
So yeah, those are probably related as in "not able to work with a larger" codebase" or alike.

**Comment by muglug** [comment]
Please run in debug mode to see where Psalm is failing - it’s normally some sort of pathological code in a single file

**Comment by muglug** [comment]
> So yeah, those are probably related as in "not able to work with a larger" codebase" or alike.

For reference, Vimeo’s codebase has just shy of 1M LOC, and Psalm runs fine there - unless you’re codebase is much larger I’m not sure any natural limits are getting hit.

**Comment by dereuromark** [comment]
1.5 (src) + 3.0 (vendor) = 4.5 mio LOC

**Comment by weirdan** [comment]
> (tried to allocate 80909248 bytes) in project/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php on line 331

This line is where Psalm reads the output from it's children processes, so running with `--threads=1` (to avoid forking) may help as well. Apparently children output a lot of data.
