### ISSUE TITLE
stream_select issue when threads > 2

### ISSUE THREAD

**Issue by m0003r** [vimeo/psalm#2994]
After processing ~70% (sometimes ~60%, sometimes ~90%) of codebase following message appears:

```
PHP Warning:  stream_select(): unable to select [4]: Interrupted system call (max_fd=21) in 
vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php on line 312

Warning: stream_select(): unable to select [4]: Interrupted system call (max_fd=21) 
in vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php on line 312
unable to select on read stream
```

and `ps` shows some processes remaining.

**Comment by muglug** [comment]
What OS are you running on?

**Comment by m0003r** [comment]
CentOS 7 (kernel 3.10.0)
PHP 7.3.16

I have inserted something like to `vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php`
```
$num = @stream_select($needs_read, $needs_write, $needs_except, null /* no timeout */); // inserted @ here
if ($num === false) {
    error_log('unable to select on read stream');
    // sleep and continue instead of exiting
    usleep(50000);
    continue;    
}
```

and it seems to be working now.
But error count is slightly different comparing to single-threaded mode

single-threaded: 4127 errors found, 5651 other issues found.
16 threads with that fix: 4129 errors, 5651 other issues
32 threads with fix: 4131 errors, 5651 other issues
64 threads with fix: 4134 errors, 5651 other issues

that numbers are the same across different runs with same threads count.

**Comment by m0003r** [comment]
Seems that symphony/process uses the same idea of solution: https://github.com/symfony/symfony/pull/6540/commits/fa6fb6fa807f06ee2587cda56f1052d616668ea9

**Comment by muglug** [comment]
Could you use a tool like diffchecker.com to figure out what the extra errors are?

**Comment by m0003r** [comment]
I have updated Psalm to 3.10.1 and now 64 threads works without any errors (however 32 does throw the same error as earlier).

Difference in error count is still there, so I suppose it is not related to interrupted `stream_select`, but to multithreading itself.

I also did reproduce it between 63 and 64 threads. Issue count is the same, but the issues is slightly different (filenames wiped out, highlighted marked as bold):

<pre>
-ERROR: PossiblyFalseOperand - Cannot concatenate with a possibly false false|string (see https://psalm.dev/162)
-            $values[] = '(' . <b>$pdo->quote($bik)</b> . ', ' . $pdo->quote($name) . ', ' . ($crsa ? $pdo->quote($crsa) : 'NULL') . ')';
-
-
-ERROR: PossiblyFalseOperand - Cannot concatenate with a possibly false false|string (see https://psalm.dev/162)
-            $values[] = '(' . $pdo->quote($bik) . ', ' . <b>$pdo->quote($name)</b> . ', ' . ($crsa ? $pdo->quote($crsa) : 'NULL') . ')';
-
-
-ERROR: PossiblyFalseOperand - Cannot concatenate with a possibly false false|string (see https://psalm.dev/162)
-            $values[] = '(' . $pdo->quote($bik) . ', ' . $pdo->quote($name) . ', ' . <b>($crsa ? $pdo->quote($crsa) : 'NULL')</b> . ')';
-
-

+ERROR: PossiblyFalseOperand - Cannot concatenate with a possibly false false|int (see https://psalm.dev/162)
+        $log->write("Update rows: " . <b>$updated</b>);


+ERROR: PossiblyFalseOperand - Cannot concatenate with a possibly false false|string (see https://psalm.dev/162)
+    $values[] = '(' . <b>$pdo->quote($str[0])</b> . ', ' . $pdo->quote($str[1]) . ')';
+
+
 ERROR: PossiblyNullArrayAccess - Cannot access array value on possibly null variable $str of type false|list<null|string>|null (see https://psalm.dev/079)
     $values[] = '(' . $pdo->quote(<b>$str[0]</b>) . ', ' . $pdo->quote($str[1]) . ')';


+ERROR: PossiblyFalseOperand - Cannot concatenate with a possibly false false|string (see https://psalm.dev/162)
+    $values[] = '(' . $pdo->quote($str[0]) . ', ' . <b>$pdo->quote($str[1])</b> . ')';
+
+
 ERROR: PossiblyNullArrayAccess - Cannot access array value on possibly null variable $str of type false|list<null|string>|null (see https://psalm.dev/079)
     $values[] = '(' . $pdo->quote($str[0]) . ', ' . $pdo->quote(<b>$str[1]</b>) . ')';
</pre>

I can't see any pattern.

There also is the same error in trait code detected in different classes which uses that trait.

Unfortunately I can not provide more code. However ~0,1% difference is definitely not significant.
