### ISSUE TITLE
Failed on PHP-7.4 version

### ISSUE THREAD

**Issue by peter279k** [vimeo/psalm#2995]
When using the `psalm` command on `php-7.4` version, it should present following syntax error message:

```
PHP Parse error:  syntax error, unexpected 'Fn' (T_FN), expecting identifier (T_STRING) in /path/to/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php on line 301
```

Is it possible to fix?

**Comment by muglug** [comment]
What version of Psalm are you running?

**Comment by peter279k** [comment]
Both latest `1.x` and ``2.x` version are used. And issue is happened on these two versions.

**Comment by muglug** [comment]
Use 3.4 and over, which supports 7.4

**Comment by XedinUnknown** [comment]
Can't use 3.4 and over, because it requires PHP 7.1, which is above our minimal requirements.

**Comment by weirdan** [comment]
@XedinUnknown then you obviously don't suffer from this issue and can just use older versions.

**Comment by XedinUnknown** [comment]
What? No! 😂 I definitely do suffer from this issue. Just because 7.0 is the minimal requirement, doesn't mean it's also the maximal requirement. Builds on 7.4 fail because if this issue.

**Comment by weirdan** [comment]
Why don't you use 3.4+ on 7.4 builds though?
