### ISSUE TITLE
False positive: UninitializedProperty on by-ref pass inside constructor

### ISSUE THREAD

**Issue by kelunik** [vimeo/psalm#3000]
This is pretty weird code, but valid: https://psalm.dev/r/0533500984

**Comment by muglug** [comment]
The equivalent code with property types produces a fatal error in PHP 7.4: https://3v4l.org/EcUc7

Postponing the assignment is sufficient to fix the issue: https://psalm.dev/r/a48a49fec7

**Comment by kelunik** [comment]
Making the typed property nullable works fine, but still yields Psalm errors: https://3v4l.org/HUMT5 / https://psalm.dev/r/99a27865de

**Comment by muglug** [comment]
Fixed in c986cdf

**Comment by kelunik** [comment]
Thanks!
