### ISSUE TITLE
False positive UnitializedProperty when nullable typed property passed by reference

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#3003]
https://psalm.dev/r/19df87d185

This works fine at runtime

cc @kelunik

**Comment by muglug** [comment]
@nikic I'm curious whether this behaviour is intended. It seems this is a special case – passing a nullable property by reference before it's initialised

**Comment by kelunik** [comment]
Relates to #3000. The error message if it's not nullable explicitly says `Cannot access uninitialized non-nullable property`, so I guess this is by design.

**Comment by nikic** [comment]
@muglug Passing by reference (or acquiring a reference in any other way) performs an implicit null initialization. Same reason why you can write `preg_match(..., $matches)` without initializing `$matches` first.

**Comment by muglug** [comment]
Thanks, that's really useful to know
