### ISSUE TITLE
Optional return for callable types / void in union return ignored

### ISSUE THREAD

**Issue by kelunik** [vimeo/psalm#3006]
Seems like `|void` is currently ignored as return type, it needs a full repetition of the callable signature with an exclusive `: void`.

 - https://psalm.dev/r/36be2d4c01
 - https://psalm.dev/r/72c3b2644d

**Comment by weirdan** [comment]
Perhaps what you're trying to express is actually a union of callables? Union of callables is not the same as callable returning a union, the difference can be demonstrated as follows: https://psalm.dev/r/a8da1e3a82

**Comment by kelunik** [comment]
@weirdan While there is a difference, for the callable caller the resulting type is exactly the same as long as the parameter types are equal, it's always the union for the caller.

**Comment by muglug** [comment]
Actually, sorry, this is not a bug – the second example you've given is the appropriate way to describe that type. `null|void` is, to Psalm at least, the same as `null`.
