### ISSUE TITLE
Problem with type inference when returning lists of templated types

### ISSUE THREAD

**Issue by jaikdean** [vimeo/psalm#3008]
I'm not sure exactly where the problem lies here, but there are a couple of what I believe to be false-positives flagged up in this example: https://psalm.dev/r/ffe0384957

If nothing else, there's scope to improve the message output by `InvalidReturnType`:

> The declared return type 'list' for Foo::getBarsThatAreInstancesOf is incorrect, got 'list'

**Comment by muglug** [comment]
> If nothing else, there's scope to improve the message output by InvalidReturnType

This was actually just a bug in psalm.dev, which has been hiding anything between `<` and `>` for a week :(
