### ISSUE TITLE
False negative when checking for array key existence

### ISSUE THREAD

**Issue by rybakit** [vimeo/psalm#3010]
See https://psalm.dev/r/4b84be093e.

**Comment by weirdan** [comment]
You need to tell Psalm that your function never returns: https://psalm.dev/r/be421b32a4

**Comment by rybakit** [comment]
> You need to tell Psalm that your function never returns: https://psalm.dev/r/be421b32a4

Thanks for the tip. However, I found that removing `$parsed['scheme']` from the `isset()` arguments also eliminates the error. Isn't it strange that it works with one argument even without annotating the function, and doesn't work with two arguments?

https://psalm.dev/r/34134a373c.

**Comment by muglug** [comment]
Yeah that's weird

**Comment by muglug** [comment]
The bug only affects core functions that return `array|false`, basically:

https://psalm.dev/r/50c1f9df06

**Comment by rybakit** [comment]
@muglug I re-checked my initial [snippet](https://psalm.dev/r/4b84be093e.) on Psalm f94ab22a5f73c45052111dd9610b7a79e543b47d and it still reports `PossiblyUndefinedArrayOffset` error. Even worse, now it's started complaining about the previously valid second snippet (the one with one `isset` argument): https://psalm.dev/r/34134a373c.

**Comment by weirdan** [comment]
@rybakit 
> Even worse, now it's started complaining about the previously valid second snippet

I don't think it was valid, and I do think `never-returns` should be necessary. Now Psalm behaves consistently, and `never-returns` consistently helps with both cases.

**Comment by muglug** [comment]
Yup, I labelled this a _false negative_, not false positive. Psalm is correct in labelling those as potentially problematic, and it can be fixed with `@return never-return` annotation on that function

**Comment by rybakit** [comment]
Thanks for the clarifications, guys!
