### ISSUE TITLE
Extremely high CPU usage across all cores leads to computer freezes

### ISSUE THREAD

**Issue by nd9600** [vimeo/psalm#3015]
Hi,
I'm not sure if anything can be done about this, but frequently when my team runs Psalm on our ~160k line codebase (Ubuntu 18.04, Intel i7-8550U CPUs), our CPU usage will spike to 100% on all of our cores, and the computer freezes - earlier today mine froze so badly I had to restart.

Is there any way to limit the CPU usage/number of cores that're used? Even if it ran 2 or 3 times as long, but used only 50% of the CPU, that'd be great.

Thanks,
Nathan

**Comment by muglug** [comment]
How many cores do you have available?

You can run with `--threads=X` where `X` is whatever number your computer is comfortable with. I'd be interested to know what number that's failing at for you.

**Comment by mitelg** [comment]
I have the same issue. (Ubuntu 19.10, Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8)

we use following command: `php vendor/bin/psalm --threads=max --diff --diff-methods --show-info=false` or `php vendor/bin/psalm --threads=$(nproc) --diff --diff-methods --show-info=false`

for me the "start-up" of Psalm is freezing the computer, while the scanning itself runs quite ok

**Comment by nd9600** [comment]
We have [4 cores, 8 threads](https://ark.intel.com/content/www/us/en/ark/products/122589/intel-core-i7-8550u-processor-8m-cache-up-to-4-00-ghz.html).

It does work quite a bit better with `--threads=2`, thanks, though occasionally the computer still freezes, but not as badly.
