### ISSUE TITLE
Inherited method failing with UndefinedMethod

### ISSUE THREAD

**Issue by beaucollins** [vimeo/psalm#3018]
### Context

- I have a project that is using WordPress APIs.
- I am using stubs from [giacocorsiglia/wordpress-stubs](https://packagist.org/packages/giacocorsiglia/wordpress-stubs).
- I have a class that extends `\WP_REST_Response` named `\Collins\CustomResponse`
- `\WP_REST_Response` extends from `\WP_HTTP_Response`

### The Problem

Psalm does not think any of the methods defined in `\WP_REST_Response` or `\WP_HTTP_Response` are available in `\Collins\CustomResponse`.

Definition of [`CustomResponse`](https://github.com/beaucollins/psalm-failure/blob/93edcac9386f0692e9dfc1fa20f51514fbdb66fa/src/CustomResponse.php) (note that Psalm also [fails to find the obvious failures of `custom_method`](https://github.com/beaucollins/psalm-failure/runs/534150577)):

```php
<?php declare( strict_types = 1 );
namespace Collins;

use WP_REST_Response;

final class CustomResponse extends WP_REST_Response {

	/**
	 * @param boolean $arg
	 * @return string
	 */
	public function custom_method() {
		return 1;
	}
}
```

[The project `beaucollins/psalm-failure` reproduces the problem](https://github.com/beaucollins/psalm-failure/blob/master/src/Failure.php#L6-L31).

```php
	public static function failureExample(): void {
		$response = new CustomResponse();
		$response_rest = new \WP_REST_Response();
		$response_base = new \WP_HTTP_Response();
		/**
		 * ::get_status() is defined by WP_HTTP_Response
		 *
		 * Psalm error is UndefinedMethod
		 */
		$status = $response->get_status();

		/**
		 * Custom_Response extends WP_REST_Response
		 */
		$response_rest = $response_rest->get_status();

		/**
		 * WP_REST_Response extends WP_HTTP_Response
		 */
		$other_status = $response_base->get_status();

		/**
		 * Sanity check
		 */
		$custom = $response->custom_method();
	}

```

The failure can be seen in [this Github check run](https://github.com/beaucollins/psalm-failure/runs/534150577).

<img width="618" alt="image" src="https://user-images.githubusercontent.com/19795/77567737-d49cb680-6e84-11ea-9b9c-4ccc4e8353fd.png">

**Comment by beaucollins** [comment]
> can you reproduce the issue on https://psalm.dev ?

I am unable to reproduce this problem on https://psalm.dev.

**Comment by muglug** [comment]
Looks like you currently can't inherit from a class that only exists as defined in a stub file (a pretty glaring hole). The temporary workaround is to autoload the stub files in Psalm's config.

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/39f729667089bf704baba53075ce8399e772151e

**Comment by beaucollins** [comment]
Thanks @muglug! We've been able to workaround by changing anything that returns the `CustomResponse` to use its parent class as the return type instead.

**Comment by AndrolGenhald** [comment]
@antonioeatgoat I believe I fixed inheritance from stubs in the past couple of months, have you tried this on the 5.0 beta or on the latest development version (composer `dev-master`)?

**Comment by muglug** [comment]
@antonioeatgoat could you create a branch that adds a should-pass-but-actually-breaks test to `tests/StubTest.PHP` please?

**Comment by antonioeatgoat** [comment]
@muglug you can see the failing test here https://github.com/vimeo/psalm/commit/52e9ecec40451273114694bf8379f97f21f2f27c
