### ISSUE TITLE
Add a way to indicate that the list of `@property`/`@method` annotations is comprehensive?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#302]
E.g. by adding `/** @psalm-forbid-undeclared-magic-properties */`, `/** @psalm-forbid-undeclared-magic-methods */` to the class's docblock.

Code may have __get() and __set() defined, but intended for use to implement only a few magic properties.
So, if a property that isn't in that list is fetched/set, it'd be nice to warn about that.

Something similar was done in Phan

Example:

```php
<?php

/**
 * @property \array $x
 * @psalm-forbid-undeclared-magic-properties
 */
class A {
    private $instances = ['x' => 'value']; 
    /** @return mixed */
    public function __get($key) {
        return $this->instances[$key];
    }   

    public static function test() {
        $x = new self();
        echo intdiv($x->x, 2); // Expected: warn because x is a string
        echo intdiv($x->y, 2);  // Expected: warn because the property y doesn't exist.
    }   
}
```

**Comment by muglug** [comment]
This is a great idea, spent a bunch of time writing a plugin to do the exact same thing.

**Comment by muglug** [comment]
I went with `@psalm-seal-properties` – possibly less clear, but also concise
