### ISSUE TITLE
False negative when checking for non-nullabe return type

### ISSUE THREAD

**Issue by rybakit** [vimeo/psalm#3021]
https://psalm.dev/r/f940cf8684

In that snippet, Psalm complains that `getString()` can return `string` or `null`, however, given the way the code is written, it can only return `string`. I don't know if Psalm can detect such cases, I looked through the documentation, but the closest I could find was the `@psalm-ignore-nullable-return` annotation, which I understand is irrelevant to my case.

**Comment by muglug** [comment]
I am not sure what you're trying to achieve here

**Comment by weirdan** [comment]
There's an implied dependency between those properties, but Psalm considers every property in isolation. Give it a hint with `assert()` and you'll be good: https://psalm.dev/r/2989fb219d

**Comment by rybakit** [comment]
> There's an implied dependency between those properties, but Psalm considers every property in isolation.

Clear, I suspected that, but I wasn't entirely sure. Thank you for confirming my guess.
