### ISSUE TITLE
self return type mismatch

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#3023]
In this snippet https://psalm.dev/r/1223a7e538 the return type of `State::map` should be `self`, but if I declare it in an annotation (using only the return type works fine) I receive an `ImplementedReturnTypeMismatch` error

**Comment by weirdan** [comment]
You have duplicate `@return` annotations on `State::map()`, and the first one takes precedence. If you leave just `@return self<B, S>` or rename the latter to `@psalm-return self<B,S>` (to make other tools ignore it) it all checks fine: https://psalm.dev/r/1880ee7432

**Comment by marcosh** [comment]
ouch, thanks! sorry for this

**Comment by weirdan** [comment]
@marcosh ditto for `State::state()`
