### ISSUE TITLE
Last run caching doesn't work when there were errors

### ISSUE THREAD

**Issue by bendavies** [vimeo/psalm#3024]
REF: https://github.com/vimeo/psalm/commit/68c95c622a5c91c387929a01a48a667cb5428ffd

Expected: 
1. do a full uncached run that generates an error
1. run again, no files are scanned(?), errors as per 1 are shown.

Actual
1. do a full uncached run that generates an error
1. run again, no files are scanned, no errors found.

**Comment by muglug** [comment]
Note this is still behind the `--diff --diff-method` flags
