### ISSUE TITLE
Add Stringable type

### ISSUE THREAD

**Issue by jaikdean** [vimeo/psalm#3028]
PHP's source now contains the `Stringable` type. The latest versions of Symfony have started to add this type to their docblocks, which Psalm complains about as an undefined class/interface.

See https://github.com/php/php-src/pull/5083

https://psalm.dev/r/70d9510fe2

**Comment by vadim2991** [comment]
For fix issue in your project add polyfill php8 https://github.com/symfony/polyfill-php80 .

**Comment by muglug** [comment]
Yeah, Psalm doesn’t yet support PHP 8, on account of it’s not released. When PHP 8 is released, I imagine Stringable will automatically work - if it doesn’t, feel free to reopen.

**Comment by weirdan** [comment]
@muglug I don't think it'll work automatically, as it's an *implicit* interface: any class that has `__toString()` method is an instance of `Stringable`, even if it doesn't have it in its `implements` declaration.

Anyway, it would be a part of PHP8 support effort.

**Comment by zerkms** [comment]
It's possible to create a stub for that. Would anybody do that, if not I can release one.

**Comment by zerkms** [comment]
Wait a second - given it's an interface no stubs needed - one may just use one of the polyfills available, eg https://github.com/symfony/polyfill/blob/master/src/Php80/Resources/stubs/Stringable.php

**Comment by weirdan** [comment]
I imagine stub would be pointless too: if you're targeting PHP7 you still need a polyfill (for runtime support), and if you're targeting PHP8 the interface would be discovered via reflection. 

Cross-checking from older to newer version (e.g. Psalm running on PHP7 checking PHP8 code) wasn't a supported scenario for Psalm last time I checked.

**Comment by zerkms** [comment]
> I imagine stub would be pointless too: if you're targeting PHP7 you still need a polyfill (for runtime support), and if you're targeting PHP8 the interface would be discovered via reflection.

```php
interface Stringable
{
    /**
     * @return string
     */
    public function __toString();
}
```

this is the complete declaration shipped by that package which is compliant with the standardised one.
