### ISSUE TITLE
Write Contributing guidelines/Developing guidelines?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#304]
E.g. something similar to [this wiki page](https://github.com/phan/phan/wiki/Developer%27s-Guide-To-Phan) for Psalm.

Things that might be included:

- Where parts of Psalm are implemented, core concepts/design goals
- Instructions for writing unit tests.
- Instructions for fixing common bugs (e.g. how to add a completely different issue type to config.xsd, emit it in psalm's output, etc.)
- Syntax guidelines for the project (I notice phpcs.xml exists)
- Link to CONTRIBUTING.md

**Comment by muglug** [comment]
I'll add this, hopefully in the next week.

> Where parts of Psalm are implemented, core concepts/design goals

I avoided this for a long time just because the code changed so much, but the basic architecture is pretty settled now.

**Comment by muglug** [comment]
I've added contributing/CoC guidelines

**Comment by muglug** [comment]
> Where parts of Psalm are implemented

And I've added https://github.com/vimeo/psalm/blob/master/docs/how_psalm_works.md
