### ISSUE TITLE
Generate psalm xml output to html overview

### ISSUE THREAD

**Issue by StephanKrauss** [vimeo/psalm#3041]
Hello,

I'm a beginner in testing with psalm.
I have a simple question.

In my first test i have generate a test.xml file.
For example:

```php
<?xml version="1.0" encoding="UTF-8"?>
<files psalm-version="3.10.1@eeed5ecccc10131397f0eb7ee6da810c0be3a7fc">
  <file src="src/App/Commands/MigrateCustomersCommand.php">
    <UndefinedDocblockClass occurrences="1">
      <code>$this-&gt;logger-&gt;error($log)</code>
    </UndefinedDocblockClass>
  </file>
  ...
```

Now i will generate from this file a html overview file.
Is there a way to do this ?

Your sincerly

Stephan

**Comment by muglug** [comment]
Hey!

What do you want to get an overview of?

**Comment by weirdan** [comment]
Closing as inactive.
