### ISSUE TITLE
UndefinedVariable when it is defined in complex condition as side-effect

### ISSUE THREAD

**Issue by m0003r** [vimeo/psalm#3043]
https://psalm.dev/r/d100fc8b5f

both functions are equivalent (even considering short-circuit evaluation), but the first one triggers `MixedArgument - 7:13 - Argument 1 of echo cannot be mixed, expecting string`

**Comment by muglug** [comment]
Just initialise `$b` to `null` beforehand, code is more readable anyway. https://psalm.dev/r/6967085d0e
