### ISSUE TITLE
TypeDoesNotContainType

### ISSUE THREAD

**Issue by martinssipenko** [vimeo/psalm#3044]
Ignore the `MissingConstructor` error.

https://psalm.dev/r/d91fb7af1f

**Comment by muglug** [comment]
> Ignore the MissingConstructor error.

Ah, so that's the entire point. Psalm believes that all non-nullable properties should be initialised in the constructor.

You can make the issue go away by making your property nullable: https://psalm.dev/r/ee8be420ab
