### ISSUE TITLE
array_multisort and InvalidPassByReference

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#3047]
array_multisort is super bad documented in PHP itself, but it can actually be used to sort arrays by multiple columns, where the finally sorted array (by reference) is the LAST element (even though the docs say the first arg is passed by ref which isn't true e.g. in my example), causing a InvalidPassByReference in my test case.

https://psalm.dev/r/9d7e5978bf

(Note: in reality I sort multiple columns, at once, so it looks like:

```
array_multisort(
	array_column( $test, 'sort_this' ),
	SORT_DESC,
	array_column( $test, 'id' ),
	SORT_ASC,
        ...,
	$test
);
```

**Comment by weirdan** [comment]
> the finally sorted array (by reference) is the LAST element (even though the docs say the first arg is passed by ref which isn't true e.g. in my example)

It's worse than that: all array arguments are (optionally!) accepted by reference and all of them are sorted, see https://3v4l.org/iZLaY
