### ISSUE TITLE
Template default value

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#3048]
Is it possible to use template with default value, if undeclared?

Example:

```php
/**
 * @template T
 * @template O=[]
 */
interface FormTypeInterface
```

and class

```php
/**
 * @implements FormTypeInterface<User>
 */
class MyForm implements FormTypeInterface
{
 
}
```

Reason;
I am making stub [for this file](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Form/FormTypeInterface.php) and in lots of cases, ``$options`` will not be used (other things are already covered).

---
If not possible, no big problem. Is it then possible some sort of merging where interface would set ``array{required: bool}``, MyForm would add ``array{label: string}`` and resulting ``O`` would be a merge of them?

Sorry if too confusing or complex, I don't have experience with other languages.

**Comment by andrew-demb** [comment]
AFAIK yes, you can.
You need to use ` as some-default-type`.

https://psalm.dev/docs/annotating_code/templated_annotations/

**Comment by zmitic** [comment]
@andrew-demb I did, it creates an error: https://psalm.dev/r/5feea3d0d1

**Comment by muglug** [comment]
Sorry, this isn't possible

**Comment by orklah** [comment]
@MidnightDesign please create a new issue, but don't get your hopes up, development resources are pretty scarce...

**Comment by muglug** [comment]
No worries! It’s just highly unlikely to be added unless someone really wants this feature and also has enough background in generics implementations to be able to implement it.

**Comment by kkmuffme** [comment]
`@psalm-this-out self<Foo>` on the `__construct(` method can be used to set the default value of the template
(obviously doesn't work on interfaces)
