### ISSUE TITLE
Array of arrays modification in foreach by reference

### ISSUE THREAD

**Issue by m0003r** [vimeo/psalm#3049]
https://psalm.dev/r/b3133fe9cb
https://psalm.dev/r/c45e07da42

both code snippets are equivalent

`PossiblyUndefinedArrayOffset` in the second case is feasible (because usually there is some `if`s inside the loop)

**Comment by muglug** [comment]
My inclination would just be for you to rewrite it like this: https://psalm.dev/r/30a4737959 – if you want to get rid of any errors you could instead use a duplicate array: https://psalm.dev/r/7ec955d029

As you say, there are normally some ifs inside the loop, so it's hard to reason about generally. By-reference assignment makes this much harder, and "solving" that, which is non-trivial, would still have the `PossiblyUndefinedArrayOffset` as above.
