### ISSUE TITLE
Template with template :)

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#3050]
Can I do smth like this?
https://psalm.dev/r/f0a3bcb972

**Comment by muglug** [comment]
No, sorry

**Comment by vudaltsov** [comment]
@muglug , so there are no plans to add it as a feature? Is it only Psalm's limitation or it is not supported in other languages as well?

**Comment by muglug** [comment]
If it’s supported in Hack I would add it, but I doubt it’s supported there

**Comment by vudaltsov** [comment]
It works after https://github.com/vimeo/psalm/commit/5ef82b53f6732beb66a94482e1fbea48d10b50e7!
Thank you, @muglug.
