### ISSUE TITLE
Let psalm know about static constructors

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#3053]
https://psalm.dev/r/de3195dc51

see also https://github.com/vimeo/psalm/issues/2755#issuecomment-583159843

I tend to believe this "false positive" could be solved by letting psalm know about static constructors, as i proposed in the snippet using a special `@constructor` annotation.

Or perhaps we can just detect/assume static constructors by validating all properties are set for any static method that returns its own type (e..g ensure the return value is "initialized").

Though, given the language doesnt specify "static constructors", im not sure psalm should get involved (then again, it also doesnt specify generics :grin:)

Do you think that's a good feature?

**Comment by ro0NL** [comment]
so IF `x::init()` returns an uninitialized object, the error could be of type `PropertyNotSetInStaticConstructor` :thinking:

**Comment by muglug** [comment]
Why not just do https://psalm.dev/r/88721c89b3?

**Comment by ro0NL** [comment]
Because it works in practice? :sweat_smile:

i agree relying on __construct is the most pure approach, and perhaps for the better as well.

However, im not sure about cases in the wild. I've seen a lot of VOs with many named/static constructors (`fromCase, fromOtherCase, etc.`). Im not sure it's practical to channel all cases thru __construct.

**Comment by ro0NL** [comment]
> I've seen a lot of VOs with many named/static constructors
> I dont think it's practical to channel all cases thru __construct.

on second thought, i have no example currently why that's impracticable actually. Especially, since the goal is to have no uninitialized state at all.

Closing for now :)
