### ISSUE TITLE
Max execution time reached on Psalter

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#3054]
This is a copy/paste of https://github.com/vimeo/psalm/issues/2728#issuecomment-607775117

@muglug Would you mind looking at this profiling?
https://blackfire.io/profiles/d6859c36-fdbd-4c3f-a580-3af0293f85a4/graph?settings%5Bdimension%5D=io&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main()
(EDIT: I tried after clearing cache, it may provide a better view: https://blackfire.io/profiles/f1ff27fb-5881-4fd1-9ae6-60f86e415614/graph?settings%5Bdimension%5D=io&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main() )

It was launched using the command `blackfire run vendor\bin\psalm --config=psalm5.xml --alter --issues=MissingReturnType --safe-types` on something around 300 files.

Psalter crashes after a minute with a time limit of 60 reached. It spend the entire time reading and writing files in cache. Unfortunately, I cannot disable the cache on psalter because there is no such option. I think this is pretty much the same issue I had in #2992 but at least, I could disable the cache as a workaround.

Do you have any solution for any of these issues:
- Timeout limited to 60 (ignore my php.ini configuration and set_time_limit in my autoloader)
- Underlying issue that could explain the time consumption
- a way to disable cache on psalter
Any of those could solve my issue :)

Thanks a lot!

**Comment by muglug** [comment]
Are you running Psalm inside of a VM?

**Comment by muglug** [comment]
You should be able to PR the disable cache thing reasonably quickly if you just follow how psalm.php does it

**Comment by orklah** [comment]
No, I'm running it on Windows.

Ok, I'll submit the PR, it's not very complicated on Psalm

**Comment by orklah** [comment]
I created the PR. I tested it today at work. It helped a lot, I could run Psalter multiple times. I still had one case of time limit reached but it's still a big improvement
