### ISSUE TITLE
UnusedVariable when isset check

### ISSUE THREAD

**Issue by snapshotpl** [vimeo/psalm#3055]
Code looks type safe, but throw info. In my code throw error because `findUnusedVariablesAndParams` is `true`.

https://psalm.dev/r/04debf3226

**Comment by weirdan** [comment]
Initialize `$command` at the top of your function and all errors are gone (apart from legitimate MissingParamType). I'd say the code becomes easier to read as well:
https://psalm.dev/r/a8e6ab60d4

**Comment by muglug** [comment]
Agree with @weirdan
