### ISSUE TITLE
TSend in generator is always inferred as mixed

### ISSUE THREAD

**Issue by kelunik** [vimeo/psalm#3058]
https://psalm.dev/r/86d80c3d13

The verification that only the given `TSend` is passed should be on the caller of `$generator->send(...)`, not in the generator itself.

**Comment by weirdan** [comment]
It looks almost like `TSend` is incorrectly assigned to `TValue`. Note that it's inferred as Generator<int,**int**,...>, while clearly it's a string being yielded.

**Comment by vudaltsov** [comment]
The given snippet still produces an error: https://psalm.dev/r/86d80c3d13
Also consider this case https://psalm.dev/r/e6d40b7667
The issue should be reopened.

**Comment by muglug** [comment]
I think the `TSend` just says what you _can_ send in, but it doesn't mean that it's always sent in for _every_ yield, right?

**Comment by kelunik** [comment]
Depends on the user running the generator, e.g. Amp's coroutines always send, others might not. Generally I'd say it's mostly always send or never send.
