### ISSUE TITLE
Add better typing for generator function return statements

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#306]
And support a `@psalm-generator-return` annotation:

```php
function takesInt(int $i) : void {
    echo $i;
}

function takesString(string $s) : void {
    echo $s;
}

/**
 * @psalm-generator-return int
 * @return Generator<int, string>
 */
function other_generator() : Generator {
    yield "traffic";
    return 1;
}

/**
 * @return Generator<int, string>
 */
function foo() : Generator {
    takesInt(yield from other_generator());
}

foreach (foo() as $s) {
    takesString($s);
}
```

**Comment by TysonAndre** [comment]
You'd also want `@phan-generator-send SomeType` for `$val = yield (optional expr);`, which is less common. (Using the value returned by `yield` might be done when imitating coroutines)

An alternate approach would be `Generator<key, value, sendT, finalReturnType>` 
https://docs.hhvm.com/hack/async/generators#sending-and-raising uses sendT as a third argument

Before PHP allowed getReturnType() to be called on the generator, it allowed these three:

- Type of value
- Type of key
- Type of send() value that the caller passes in to `$x = yield;`

So supporting all 4 of `Generator<value> implements Traversable<value>, Generator<key, value> implements Traversable<key, value>, Generator<key, value, sendT> implements Traversable<key, value>, Generator<key, value, sendT, finalReturnType>` would be another way to do that (An implementation could assume mixed if a template is left out, unless it can be inferred from the AST)

Unfortunately, there's no spec for that. And I'm not aware of anything using syntax for a Generator with 4 template parameters.

**Comment by muglug** [comment]
@TysonAndre I like `Generator<TKey, TValue, TSend, TReturn>` the most. I think you'd want to disallow just three parameters, due to the ambiguity as to whether you meant `TSend` or `TReturn` for the third, but two params is fine.

**Comment by muglug** [comment]
OTOH, anyone using this would probably understand the annotation
