### ISSUE TITLE
Heterogeneous arrays with types depending on previous entries

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#3060]
Consider this use case. I have an array of functions of the form `a -> F b`, where `a` and `b` are templates and `F` is a class with one type parameter. But every entry could have different `a` and `b`, with the constraint that the `a` of every entry should be equal to the `b` of the previous one.

For example, this would be a correct sequence:

```
a -> F b
b -> F c
c -> F d
...
```

This would allow to express and type check something along the lines of [do notation](https://en.wikibooks.org/wiki/Haskell/do_notation) in PHP
It would be super nice to be able to express such a constraint in Psalm.

**Comment by muglug** [comment]
Sorry, I'm not going to implement this.

**Comment by marcosh** [comment]
no problem, thanks for the reply
