### ISSUE TITLE
Feature request: provide suggested fixes via LSP

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#3062]
In LSP, its possible for a language server to provide suggested fixes in addition to the diagnostics it emits. Below is an example of missing import from typescript server, with 'Add import' suggestion:
![image](https://user-images.githubusercontent.com/57403/78367715-38348b80-75cb-11ea-97d9-dd555700edbd.png)

It would be very handy if Psalm also provided suggested fixes to the LSP client. For example, where it reports 'does not have a return type, expecting F\Q\C\N' it could also offer a quick fix to actually add it. Probably all issues fixable with psalter could be added.

LSP Reference: https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction

**Comment by muglug** [comment]
I'm not going to add this, but if someone wants to take a crack at it, they should feel free.
