### ISSUE TITLE
Disable reading @phpstan annotations

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#3066]
`Symfony\Component\Form\FormInterface` implements `Traversable` and PHPStan requires me to specify its inner type. So I gladly do this:

`* @phpstan-param FormInterface<FormInterface> $form`

However, psalm complains:

> Symfony\Component\Form\FormInterface<Symfony\Component\Form\FormInterface> has too many template params, expecting 0 (see https://psalm.dev/184)

Not sure if it's psalm's feature or bug but in case of feature I was thinking to specify custom type hints for phpstan to satisfy it and disable reading of those annotations in psalm. 

Or I can do this but it seems redundant to me as method signature has native type hint identical to psalm's

```php
* @phpstan-param FormInterface<FormInterface> $form
* @psalm-param FormInterface $form
```

What would be a correct solution to this? Thanks

**Comment by muglug** [comment]
I believe this is a bug in PHPStan, which I've ticketed here: https://github.com/phpstan/phpstan/issues/3149

**Comment by ondrejmirtes** [comment]
Hi, if you install phpstan-symfony, this won't be a problem for you - PHPStan won't require you to do the `FormInterface<FormInterface>` thing anymore. See https://github.com/phpstan/phpstan-symfony/blob/master/stubs/FormInterface.stub

**Comment by ondrejmirtes** [comment]
There's a lengthy explanation of the problem: https://github.com/phpstan/phpstan/issues/3149#issuecomment-609438139

**Comment by simPod** [comment]
@ondrejmirtes I have same issue with other libraries as well. Eg.  https://github.com/consistence/consistence/blob/master/docs/Enum/multi-enums.md Though have to admit I prefer psalm's way as I don't intend to do any traversing of those classes anyway so I'm not bothered.
