### ISSUE TITLE
Q: coveralls disabled since last summer?

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#3077]
@muglug I've just noticed that coveralls uploads were disabled. Since coverage is still gathered on CircleCI, wouldn't it make sense to upload it to coveralls.io?

**Comment by muglug** [comment]
Yes it was taking too long, vaguely curious what the coverage is now. What do you/I need to do to get it working in CircleCI?

**Comment by weirdan** [comment]
I'll make a PR, you will need to configure the COVERALLS_REPO_TOKEN on CircleCI
