### ISSUE TITLE
Concatenating yield from leads to invalid return type deduction

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#3083]
Concatenation of two yielded values leads to invalid return type deduction: https://psalm.dev/r/5f2073aaef

**Comment by muglug** [comment]
This actually isn't a bug. 

The type of a `yield from $some_generator` is the _return_ value of that generator.

In your example, you specify `Generator<string>`.

This is equivalent to `Generator<int, string, mixed, mixed>` – a reference for that type is [here](https://psalm.dev/docs/annotating_code/type_syntax/object_types/#generators).

If you specify the full type, `Generator<int, string, void, string>` the code works as expected: https://psalm.dev/r/01c6eb8f5a

**Comment by danog** [comment]
Understood, thanks for the clarification!
