### ISSUE TITLE
`foreach`ing `mixed` values

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#3086]
Is it expected that values that are mixed are allowed to be `foreach`ed without any warning?

It looks inconsistent that you cannot pass them as an argument if the function expects an `array`, but is allowed to be `foreach`ed just fine.

```php
<?php

function getArray(array $a): void {}

/** @var mixed $v */
$v = 42;

foreach ($v as $q) {}

getArray($v);
```
```
Psalm output (using commit 9954987): 

INFO: UnusedParam - 3:25 - Param $a is never referenced in this method

INFO: MixedAssignment - 8:16 - Unable to determine the type that $q is being assigned to

INFO: MixedArgument - 10:10 - Argument 1 of getArray cannot be mixed, expecting array<array-key, mixed>

INFO: UnusedVariable - 8:16 - Variable $q is never referenced
```

**Comment by zerkms** [comment]
Oops, sorry bot: https://psalm.dev/r/3527076be2

**Comment by muglug** [comment]
You’ll always get that MixedAssignment issue, so it’s not too much of an issue for me.

**Comment by zerkms** [comment]
> You’ll always get that MixedAssignment issue

Always, including when it's a correctly typed as `array`.

Imagine - you have a code like:

```
/** @var mixed $v */
foreach ($arr as $v) {
    // deal with $v
}
```

Then `$arr` type has suddenly changed from `array` to `mixed`.

Nothing would be reported, but code will possibly break in runtime.

**Comment by muglug** [comment]
Yeah, but that’s sort of your prerogative then

**Comment by zerkms** [comment]
@muglug it could be a 3rd party dependency that has changed their signature:

```php
/** @var mixed $v */
foreach ($lib->getArr() as $v) {
    // deal with $v
}
```
