### ISSUE TITLE
False positive on Psalter safe-types with empty array

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#3087]
Hi,

For the following code:

```php
function test(array $array){
    $a_res = [];

    Foreach($array as $arr){
        $a_res[] = $arr === 'Y';
    }
    
    if(count($a_res) > 1) {
        throw new Exception();
    }

    return $a_res[0];
}
```

And the following command:
`vendor\bin\psalm --alter --issues=MissingReturnType --safe-types`

Psalter will transform the code into:

```php
function test(array $array): bool{
    $a_res = [];

    Foreach($array as $arr){
        $a_res[] = $arr === 'Y';
    }
    
    if(count($a_res) > 1) {
        throw new Exception();
    }

    return $a_res[0];
}
```

However, when the array `$array` is empty, the $a_res[0] will return null and it will produce a Type Error. The return type should have been ?bool

Thanks

**Comment by muglug** [comment]
You can add `ensureArrayIntOffsetsExist="true"` to have Psalm detect this class of errors, but this is beyond the scope of Psalter.
