### ISSUE TITLE
UnnecessaryVarAnnotation & PHPStan incompatibility

### ISSUE THREAD

**Issue by patrickkusebauch** [vimeo/psalm#3088]
Not really sure whether a Psalm problem or PHP/Stan problem, but it might be the case, that PHPStan needs an inline `@var` annotation, but Psalm does not. In that case, it is not possible to comment the code in a way that neither tool will complain. Example: 
```php
            $flow = $flowFactory($providerName);
            /** @var FacebookProvider|GoogleProvider $provider */
            $provider = $flow->getProvider();
            $provider->setRedirectUri($this->link('//oauthAuthorize', ['backlink' => null]));
            /** @var \League\OAuth2\Client\Token\AccessToken $accessToken */
            $accessToken = $flow->getAccessToken($this->getHttpRequest()->getQuery());
            /** @var FacebookUser|GoogleUser $owner */
            $owner = $provider->getResourceOwner($accessToken);
```
Psalm complaint:
```
 UnnecessaryVarAnnotation - app/Saas/Presenters/UI/LogInPresenter.php:114:22 - The @var Contributte\OAuth2Client\Flow\Facebook\FacebookProvider|Contributte\OAuth2Client\Flow\Google\GoogleProvider annotation for $provider is unnecessary (see https://psalm.dev/212)
            /** @var FacebookProvider|GoogleProvider $provider */
```
if I remove the annotation PHPStan will complain:
```
 115    Call to an undefined method                                        
         League\OAuth2\Client\Provider\AbstractProvider::setRedirectUri().  
```

The only way to write the `@psalm-supress` annotation to make it work:
```php
            /** @var FacebookProvider|GoogleProvider $provider */
            /** @psalm-suppress UnnecessaryVarAnnotation */
            $provider = $flow->getProvider();
```
But in that case the PHPStan problem persists.

**Comment by weirdan** [comment]
Why don't you just ignore the issue in `psalm.xml`? See https://psalm.dev/docs/running_psalm/dealing_with_code_issues/#config-suppression

**Comment by patrickkusebauch** [comment]
@weirdan That is what I had to do in the end, but it is hard to maintain ignoring one specific piece of code outside of that piece of code. That is why I would like for the `@psalm-suppress` annotation to work.

**Comment by weirdan** [comment]
`@psalm-suppress` should work as well (but doesn't), but you will need to put both annotation into a single docblock like this: https://psalm.dev/r/2ac19136f8

**Comment by weirdan** [comment]
@muglug I think the snippet above should not emit any issues.

**Comment by patrickkusebauch** [comment]
@weirdan Agree, this will resolve withing PHPStan as expected. Would be great if this syntax would work within Psalm too.

**Comment by muglug** [comment]
@patrickkusebauch this is almost certainly a bug in PHPStan, which generally isn't as good at doing type inference as Psalm. I'm not sure I want to allow people to locally suppress `UnnecessaryVarAnnotation`, as that's just Psalm doing its job.

**Comment by eclipxe13** [comment]
Could you please reconsider this issue? It is also related to #2270

Psalm does not always recognize the types that PHP can return (as in `DOMDocument::$documentElement`) and there is no way to instruct Psalm about this behavior.

> *I'm not sure I want to allow people to locally suppress `UnnecessaryVarAnnotation`, as that's just Psalm doing its job.*

I agree with you, except that Psalm is doing its job overriding some PHP types.
