### ISSUE TITLE
Unexpected PossiblyFalseReference with elseif chain, but not with else if

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#3091]
https://psalm.dev/r/836f9ed515

Here, after `if .. elseif .. elseif` both vars are guaranteed to be not false. However Psalm marks one of them (depending on the order of `elseif`s) as possibly false.

Replacing `elseif`s with `else if` (they are equivalent) fixes the issue, which is also rather surprising.

**Comment by weirdan** [comment]
`else if` variant: https://psalm.dev/r/e17c8369bb

**Comment by muglug** [comment]
Reduced to https://psalm.dev/r/15fba40aa9 – the last is redundant, that's the bug I should fix

**Comment by weirdan** [comment]
I don't think the reduced case is about the same issue as original - the original had all conditions negated, not just one in the `if()`.

psalm.dev output for the original snippet also hasn't changed: https://psalm.dev/r/836f9ed515

**Comment by muglug** [comment]
Yeah, sorry – I can't see how to fix that. If you could figure out how to prove that the `!$dateTo` is redundant, I could probably implement that in Psalm.

Currently, going into the second `elseif` condition Psalm sees:

```
($dateTo || $dateFrom) && ($dateFrom)
```
which it simplifies to
```
$dateFrom
```
but maybe it shouldn't?

**Comment by weirdan** [comment]
> If you could figure out how to prove that the !$dateTo is redundant, 

Why do you think it's redundant? On function enter there are 4 possible cases:

* `$from` and `$to` are both `null`
* `$from` is `DateTime` and `$to` is null
* `$from` is `null` and `$to` is `DateTime`
* `$from` and `$to` are both `DateTime`

`if .. elseif .. elseif` inspect and correct cases 1 through 3. Eliminating cases 1-2 does not leave case 3 as the only possible. The cases are independent, and the only reason they are not handled in separate `if`s is because vars are also changed (corrected) inside.

Looking at the added test cases though it appears you came to this conclusion yourself.
