### ISSUE TITLE
False positive: MixedPropertyTypeCoercion with \Ds\Map

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#3098]
Ref #2755

https://psalm.dev/r/9c5fa1bbdd

**Comment by weirdan** [comment]
I think it would work if we changed default value for `Ds\Map` constructor parameter from `null` to empty array.
@enumag do you know if passing `null` to constructor has any special meaning for `Ds\Map`?

**Comment by enumag** [comment]
@muglug Actually passing null explicitly even causes an error. So yeah, changing it to an empty array is fine.
