### ISSUE TITLE
Psalter: Incomplete array detection on unitialized array

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#3104]
Hi,

For the following code:

```php
function test(){
    $array['a'] = 'a';
    $array['b'] = 'b';
    return $array;
}
```

And the following command:
`vendor\bin\psalm --alter --issues=MissingReturnType`

Psalter will transform the code into:

```php
/**
 * @return (mixed|string)[]
 *
 * @psalm-return array{b: string}
 */
function test(): array{
    $array['a'] = 'a';
    $array['b'] = 'b';
    return $array;
}
```

There's something weird here, the @psalm-return don't see the 'a' key, but the @return was able to detect something but it considers it's mixed instead of a string.

Adding $array = []; on the first line of the function solves the issue.

Thanks

**Comment by muglug** [comment]
I don't count this as a bug – Psalm will tell you about a `PossiblyUndefinedVariable`, and I think that's sufficient to know that something's wrong: https://psalm.dev/r/089c2868b3
