### ISSUE TITLE
Undefined offset: 0 at vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/CommentAnalyzer.php

### ISSUE THREAD

**Issue by pristinesource** [vimeo/psalm#3107]
There is an issue when a `@method` tag has an invalid function name for example:
`* @method ClientInterface exchange-connect(array $options = [])`
That method name has a dash, which is invalid for a function name.

The fix to this would be to add a check for `empty($statements)` at https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Analyzer/CommentAnalyzer.php#L1064 so it looks like so:
```
if (empty($statements) || !$statements[0] instanceof \PhpParser\Node\Stmt\Class_
```

**Comment by pristinesource** [comment]
See https://psalm.dev/r/3bfe2b8edb for an example.  In that example when a `-` is present in the method name, all parsing stops (assuming it is crashing in the background), but if you replace it with an underscore `_`, then everything works as expected.  The expected behavior should be that it attempts to parse it and gives an error that says something like: "Badly-formatted @method string "

**Comment by pristinesource** [comment]
🤣 Lol!!! The bot can parse it properly, but when you actually go to the page, the parsing does not work, and running it from the command line gives an error.

**Comment by weirdan** [comment]
Bot must be using more tolerant JSON parser. The output they get is the same (they use the same enpoints on psalm.dev), but JSON is malformed, as there's a PHP warning:

![image](https://user-images.githubusercontent.com/57403/78838496-fb1f2d80-79fe-11ea-8bce-f3d446c57d21.png)

**Comment by weirdan** [comment]
Actually, I was wrong, and the bot is using a different endpoint. So no, it wasn't fixed. And psalm.dev is  using a master branch.

**Comment by pristinesource** [comment]
Oh ok, so it has to do with php error reporting levels?  Since my PHP setup considers undefined indexes an error, I see the error.  But, psalm.dev must have it to only show a notice, and the bot must have its php settings to not have any type of error/notice for undefined indexes. Makes sense 👍 🤔.
