### ISSUE TITLE
Add PossiblyInvalidArrayOffset when only some types cannot have given offset type

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#311]
#285 followup

May become a larger issue after fixing https://github.com/vimeo/psalm/issues/309

Less common, but may still happen, e.g. if fetching a configuration value that can be an array or string depending on the key.

```php
<?php
/**
 * @return array<int,array<string,float>>|string
 * @return string
 */
function return_array() {
    return rand() % 5 > 3 ? [['key' => 3.5]] : 'key:3.5';
}
$result = return_array();
$v = $result[0]['key'];  // Saw InvalidArrayOffset, want PossiblyInvalidArrayOffset
```

**Comment by muglug** [comment]
Changed title after https://github.com/vimeo/psalm/commit/6c9cdd896bac759dcc335877624a3d6ff7e87eac
