### ISSUE TITLE
Psalm gives no output when everything is ok??

### ISSUE THREAD

**Issue by flip111** [vimeo/psalm#3119]
I have a project, when i remove autoload of a file, psalm detects many missing functions. When i include this file and rerun psalm i get no output at all. Is it normal that when everything is ok there is no output? I was expecting some success message.

**Comment by muglug** [comment]
no output indicates that something in an autoloaded file called `exit()`. You can run with `--debug` to get a bit more information.

**Comment by flip111** [comment]
@muglug  please explain ..

> A static analysis tool for finding errors in PHP applications https://psalm.dev

> Static program analysis is the analysis of computer software that is performed without actually executing programs, in contrast with dynamic analysis, which is analysis performed on programs while they are executing.

Why does it matter that the code contains `exit`?

I included `wp-load.php` from wordpress, the php files there are full of `exit`.

`--debug` didn't give any further info by the way.

**Comment by muglug** [comment]
> I included wp-load.php from wordpress

You should you [WordPress stubs](https://packagist.org/packages/giacocorsiglia/wordpress-stubs) instead

> Why does it matter that the code contains exit?

I'm assuming that you referenced some files in the `bootstrap` config option. In that scenario Psalm runs the code in those files, which means that logic in those files can crash Psalm.

Other than calling the code in `bootstrap`, Psalm's analysis is completely static.

**Comment by flip111** [comment]
> You should you [WordPress stubs](https://packagist.org/packages/giacocorsiglia/wordpress-stubs) instead

Thank you @muglug  by the way there is also now https://github.com/php-stubs/wordpress-stubs which seems more up to date than the package you linked.
