### ISSUE TITLE
Reserved word mixed, in function argument type 

### ISSUE THREAD

**Issue by sparcbr** [vimeo/psalm#3121]
Why is this? 

`function debug(mixed $val, bool $printBackTrace = true, int $l = 5): void`

ERROR: ReservedWord - debug.utils.php:2:16 - mixed is a reserved word (see https://psalm.dev/095)

**Comment by andrew-demb** [comment]
Because you can not use 'mixed' as explicit typehint in php.

Try to run this example in any playground.
