### ISSUE TITLE
infer numeric-string type from BC Math and GMP

### ISSUE THREAD

**Issue by vladyslavstartsev** [vimeo/psalm#3123]
All functions of BC Math except of `bccomp` and `bcscale` return numeric-string.
Also GMP's `gmp_strval` function also returns numeric-string type

see
https://psalm.dev/r/d1a036f1f4

that would be awesome to infer them.

**Comment by muglug** [comment]
This should be trivial to PR in CallMap.php!

**Comment by vladyslavstartsev** [comment]
Let me make a PR
