### ISSUE TITLE
Uninitialized, typed, static properties not caught

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#3124]
I'm not sure if this is on oversight or just a limitation of Psalm, but I noticed uninitialized, typed, static properties are not caught by Psalm. This can be particularly unexpected when the type could be null because PHP used to automatically set uninitialized properties to null by default. But after they added typed properties, typed properties must be explicitly set to null or else PHP will consider them uninitialized and trigger an error when the property is accessed.

[Here is an example](https://psalm.dev/r/a545514004) that illustrates how Psalm correctly identifies uninitialized non-static properties, but fails to do so for static ones. This is also a good example of where a potentially unexpected runtime error would occur when accessing the uninitialized, static $b property. In this example the correct way for the programmer to fix the runtime error is probably to explicitly set the $b property to null where it is declared the same way that $d is, but Psalm is not helping them notice this oversight.

However the problem is not limited to static, typed properties that can be null, any static, typed property is not noticed as being uninitialized. This is also true for static properties that are typed in the DocBlock instead of in the PHP code such as property $e in the example. In that case it is implicitly set to null instead of string, but Psalm does not help the programmer notice this type error.

**Comment by muglug** [comment]
This isn't something that I think Psalm can meaningfully help with.

**Comment by still-dreaming-1** [comment]
What if it required you to initialize them where they are declared? That is how I have always thought of static properties, the initialized value is whatever you set it to where it is declared. So it would just be enforcing that the initial value is compatible with the specified type. I mean, that would require you to declare many types as possibly null, and initially set them to null. But then at least it is forcing you to deal with the reality of the limitations of PHP and the types you declared.

Or perhaps it could offer you specify a static function that effectively serves as a static initializer/constructor?
