### ISSUE TITLE
'cannot reconcile upper and lower bound for template' message usability

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#3126]
The fix for #3084 introduced new error message which I'm afraid will be **extremely** confusing for even the average Psalm user.

Consider this (simple) example: https://psalm.dev/r/8a21c26e0a

Even here one could have a head scratching moment figuring out where do A and B come from. Now imagine that parameters come from one library, getting passed to another library, and types for both provided by independent plugins and it all starts looking like a support hell. 

I would suggest to:
1. spell out the inference sources
2. get rid of 'uppper/lower bound' terminology and use 'subtype/supertype' instead

Example of adjusted message: 
```
InvalidArgument: template type T inferred from argument 1 (class-string<T>) should be a subtype of type T inferred from argument 2 (callable(T):void)
```

**Comment by vudaltsov** [comment]
Got this issue after updating to 3.11. The case is similar to what @weirdan mentioned: a callable was passed as a fully qualified function name. Am I right that to fix it I shoud use a Closure instead?

Also "see https://psalm.dev/194" does not really help as it is about arrays and iterables.

**Comment by weirdan** [comment]
Message has been changed since.
