### ISSUE TITLE
ArgumentTypeCoercion for static in 3.11.0

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#3127]
https://psalm.dev/r/cc4ea0abe5
I think this is the correct behavior of Psalm, just want to make sure I understand the edge case.

If I have `abstract class AbstractId extends Id` and then `Ids<AbstractId>`, the `Ids<AbstractId>::contains` method will not work correctly, right?

**Comment by weirdan** [comment]
> I think this is the correct behavior of Psalm,

Why do you think it's correct?

**Comment by vudaltsov** [comment]
@weirdan , as I said, if I have `abstract class AbstractId extends Id` and then `Ids<AbstractId>`, the `Ids<AbstractId>::contains` method will not be able to check that `Id::equals` is called against `static`.

**Comment by vudaltsov** [comment]
Okay, maybe I am overthinking this and it's just a bug :)
