### ISSUE TITLE
Throwing a returned exception should not make a function impure

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#3130]
I'm have no idea how practical of a distinction this would be in terms of the implementation, performance implications, and maintainability, but it would be ideal.

Since Psalm does not consider throwing exceptions to make a function impure, calling a function that returns an exception in order to throw this return value should not cause the outer function to be considered impure even though the other function being called to get the exception is and should be considered impure. So I agree that the function returning the exception should be considered impure, but calling it in this context should not be.

Here is an [example](https://psalm.dev/r/299ea587d7). Alternatively, I could just create the exception by calling the constructor directly, but using static factory methods to construct things is a common pattern that can have some benefits in certain situations.

**Comment by muglug** [comment]
Fixed in edb0795
