### ISSUE TITLE
impure callable not caught

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#3131]
https://psalm.dev/r/d772d5607a

I'm not sure if the upHigh() function should be considered impure or if Psalm can be smart enough to allow it be pure, and then complain that you are passing an impure callable to the pure function.

**Comment by weirdan** [comment]
Either way this also should be caught: https://psalm.dev/r/df0ee3d782

**Comment by weirdan** [comment]
This is now reported (purity not inferred).

**Comment by weirdan** [comment]
https://psalm.dev/r/df0ee3d782
