### ISSUE TITLE
Downcasting by class name results in InvalidReturnStatement

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#3136]
https://psalm.dev/r/4c3380e758

**Comment by vudaltsov** [comment]
Creating instance dynamically does not work either.
https://psalm.dev/r/112f7b9e6f

**Comment by muglug** [comment]
Just suppress it – working out the semantics of this is, unfortunately, non-trivial.

**Comment by vudaltsov** [comment]
OK, thanks!
