### ISSUE TITLE
Templated types as type params to subsequent templated type declarations.

### ISSUE THREAD

**Issue by pristinesource** [vimeo/psalm#3137]
Lets say I have a class that takes a templated type (via the template tag) and that type has templated type. for example:
```
* @template-covariant TViewData BaseViewDataInterface
* @template-covariant TModel BaseModel<TViewData>
```
☝️ this does not work because it says "Class or interface TViewData does not exist".  

Example at: https://psalm.dev/r/cbdf3e7312 (see the bottom class for the example and remarks), but it won't give errors there because when Psalm analyzes a single file it does not know about other class names, thus will not give errors about it.

What I am trying to accomplish is to be able to use BaseObject<> as a templated type and be able to get (and use) its type parameter as a templated type here.  TViewData would both be a constraint on the TModel templated type and a templated type to use throughout the class.  This is something I use a lot with C# generics and it would be awesome to have it here also.

I am using v3.11.2.

**Comment by muglug** [comment]
Can you express the idea in C# generics? Sorry, I'm a little lost.

**Comment by andrew-demb** [comment]
Ref https://github.com/vimeo/psalm/issues/3050

**Comment by pristinesource** [comment]
@muglug  Here is an example I made in C# showing how it is done: https://dotnetfiddle.net/F9Rj6G

**Comment by muglug** [comment]
Ah ok, sorry, that's not something I care enough to add to Psalm. You can use the (simple, unverifiable) version of that here: https://psalm.dev/r/f13d507a0e.

If you want to dig into Psalm's template handling and implement this yourself, you're more than welcome.

**Comment by pristinesource** [comment]
@muglug  I see, and thanks for the update, I understand since this is most likely more of an edge case.  Also, thanks for the more generalized example, I will use that for now.

If I get bored, I may make that update and submit a PR for it 👍.

Thanks!!! 😄

**Comment by muglug** [comment]
On second thoughts it wasn't too hard to get this working

**Comment by pristinesource** [comment]
@muglug That is awesome! Thank you!!!
