### ISSUE TITLE
Question: How to annotate property that is no longer nullable in child classes?

### ISSUE THREAD

**Issue by kboduch** [vimeo/psalm#3138]
```
<?php

class A {
    /* @var string|null  */
    public $key;

    /**
     * @param string|null $key
     */
    public function __construct(string $key = null)
    {
        $this->key = $key;
    }
}

class B extends A {
    /** @var string|null  */
    public $foo;

    /**
     * @param string $key
     * @param string|null $foo
     */
    public function __construct(string $key, string $foo = null)
    {
        parent::__construct($key);
        $this->foo = $foo;
    }
}

function test (string $bar): string { return $bar; }

$obj = new B('a', 'b');

test($obj->key);
//ERROR: PossiblyNullArgument - 39:6 - Argument 1 of test cannot be null, possibly null value provided

```

Class B construct method ensures $key is a string. How do I convince Psalm?
Overriding $key property in B class worked but that's a poor argument to override it (changing annotation to `@var string`). I was unable to figure it out. Is there a different way?

**Comment by muglug** [comment]
This should work: https://psalm.dev/r/f5f7db53fd

But it doesn't

**Comment by andrew-demb** [comment]
Extra `*` missed.
After fix there are new issue.
https://psalm.dev/r/f944d4ce5d

**Comment by kboduch** [comment]
Seems like Psalm might be ignoring 
```
    /**
     * @param TKey $key
     */
```
Modifying  code to this

```
    /**
     * @param TKey $key
     */
    public function __construct(?string $key = null)
    {
        /** @var TKey */
        $this->key = $key;
    }
```

Solves the issue. But is it really solved?

https://psalm.dev/r/eee303c152

**Comment by kboduch** [comment]
https://psalm.dev/r/2f610b4852
I have expanded my example to mirror the codebase I'm working on. 
I'm new to Psalm. Did I overdo Foo class? Having `Foo::itMightFloat2()` "return" `float(6.66)` or `null` is great but I think `float(6.66)|null` should suffice and dropping PHP return type might not be a good idea.  What do you think?
Also, I'm still struggling with the A::$value type which always returns `mixed`. Do I need to annotate this differently? Or is this a bug?
```
$test = new B('null value', $foo->itMightFloat()); //retrun type is null
$test->value; //value is type of mixed :(
```

**Comment by muglug** [comment]
Boils down to this: https://psalm.dev/r/cf4b22e112
