### ISSUE TITLE
Binding two template parameters leads to `empty`

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#3139]
https://psalm.dev/r/817237475b

```
/**
 * @template I
 * @return callable(I):array<I>
 */
function f() {
    return 
        /**
         * @template I
         * @param I $a
         * @return array<I>
         */
         function ($a) {
             return [$a];
         };
}

/** @psalm-trace $a */
$a = f();
```

produces this:

```
INFO: Trace - 19:1 - $a: callable(empty):array<array-key, empty>

ERROR: InvalidScalarArgument - 21:13 - Argument 1 expects empty, int(22) provided
```

**Comment by muglug** [comment]
Yeah, Psalm treats unbound template params as empty.

The code you've written isn't analysable by Psalm or similar (TypeScript, for example, [binds those templates](https://www.typescriptlang.org/v2/en/play#code/LAKAZgrgdgxgLgSwPZQARgDwEkB8AKASlQC5U88BDAJwHNSsiBeHVAQSqooE9sciBvUKmGoqAUzgQqaSLEQoy1OqgYk2Hbr1SCQIkeMnTUAbSUBdANxCRAXysgboJyAA2E1BVSN0he27ioAEZeHngArAT2gRZAA) to the `unknown type`).

Psalm could start warning about unbound templated types, though `empty` is often preferable.

**Comment by vasily-kartashov** [comment]
Does setting both template types to `as mixed` count as binging? The error is the same.

https://psalm.dev/r/2080be4800

```
/**
 * @template I as mixed
 * @return callable(I):array<I>
 */
function f() {
    return 
        /**
         * @template I as mixed
         * @param I $a
         * @return array<I>
         */
        function ($a) {
            return [$a];
        };
}

/** @psalm-trace $a */
$a = f();
```

Generally speaking, is it correct to assume that `@template T` and `@template T as mixed` are equivalent?

**Comment by muglug** [comment]
> Does setting both template types to as mixed count as binding?

No, it doesn't

**Comment by muglug** [comment]
Here's why Psalm has this behaviour:

https://psalm.dev/r/6ecaba774d (added to fix https://github.com/vimeo/psalm/issues/2273)

I'm not sure there's a better solution, frankly.

**Comment by vasily-kartashov** [comment]
Not sure I follow.

```
/**
 * @template I
 * @param I $a
 * @return array<I>
 */
function f0($a) {
    return [$a];
}
```

is the same function as the lambda in my initial example. I don't expect Psalm to think the type of the `f0` is `callable(empty):array<array-key, empty>`? What makes the difference here?

**Comment by muglug** [comment]
In both instances Psalm has nothing to tell it the value of a template parameter. In the first, to make the code work, Psalm infers `empty`. I'm not sure if there's a way to make both examples work.

**Comment by muglug** [comment]
Closing as Psalm now explicitly does not support templated closures
