### ISSUE TITLE
count() ignores array_unique() to determine count

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#3142]
https://psalm.dev/r/5c7875e791

https://3v4l.org/2MVEi

When `array_unique()` is used within `count()` with array where count is known in advance, psalm does not take into account that the array count may get changed by `array_unique()` fcn.

**Comment by simPod** [comment]
@muglug hi, I tried with 3.11.5 but the issue still persists https://psalm.dev/r/d198aefc94

**Comment by weirdan** [comment]
No longer reproducible: https://psalm.dev/r/d198aefc94
