### ISSUE TITLE
Phpstorm issue with phpunit, any suggestion? 

### ISSUE THREAD

**Issue by gianiaz** [vimeo/psalm#3147]
Hi, in phpstorm I see this error in tests appearing discontinuously.

![Schermata del 2020-04-14 17-05-27](https://user-images.githubusercontent.com/603458/79318645-891b7c80-7f07-11ea-8b82-b8b9bcb5ac15.png)

(BaseUnitTestCase extends TestCase of phpunit)

It seems that the root of the problem is the vendor/psalm/plugin-phpunit/stubs/TestCase.php that declares the same namespace of phpunit TestCase.

Vendor dir is excluded in the project by default. 

Does anyone have a solution to this? 

Thank you

**Comment by Jean85** [comment]
This seems already fixed (but not released yet) with https://github.com/psalm/psalm-plugin-phpunit/pull/64
