### ISSUE TITLE
psalm thinks Iterator::current() can't return null, but it toally can

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#3148]
https://psalm.dev/r/b4aa40ee22

I would not expect the NullableReturnStatement error: According to the PHP docs, Iterator::current() can return `mixed` which IMHO includes `null` - especially considering the sample code where `parent::current()` of `ArrayIterator` would definitely return `null` in this sample snippet.

**Comment by orklah** [comment]
IIRC, current() will return null too when next() is called but valid() returns false (for example, when the iterator don't have anymore elements)

**Comment by pilif** [comment]
yes. and that's actually a bit of an issue in case of iterators which you know cannot possibly return a `null` value when used correctly, e.g. via `foreach`.

so making `Iterator::current()` nullable in general is bad too because then every call-site (including the ones using `foreach`) would need to check for a bogus `null` value.

I wonder whether it's better in the context of psalm to just throw a `LogicException` when the iterator is used incorrectly at least in the cases where you intend to always return a non-null value.

But in cases like the sample I posted, psalm should totally not assume `current()` to never return null. The parent `ArrayIteratror::current()` also naturally returns `null` when it goes over the 0th element of the array.

**Comment by orklah** [comment]
@pilif Couldn't that be solved by generics naturally? Either you have null in your generics type (like this should be for the author and mixed), either you don't have null in your generics and the only null case should be removed after a valid() call?

**Comment by pilif** [comment]
not necessarily because in the case of the `ArrayIterator` from my example, you can totally pass an array containing `null` into the array iterator.

in my saple code, without the condition, just passing through `parent::current()`, psalm wouldn't list an error, even though the function *totally* can still return null by virtue of `parent::current()` returning null when the wrapped array contains null elements.

The error in this case is still bogus regardless of the `valid()` issue.

**Comment by jenshaase** [comment]
Hi,

just found this issue after searching for a similar problem. I implemented the `ArrayAccess` Interface. The method `offsetGet` has the return type `mixed` which also includes `null`:

```php
<?php
// Example from https://www.php.net/manual/de/class.arrayaccess.php
class Obj implements ArrayAccess {
    private $container = array();

    // ...

    public function offsetGet($offset) {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }
}
```

Psalm prints the error:
```
The declared return type 'mixed' for Obj::offsetGet is not nullable, but the function returns 'mixed|null'
```

Best regards,
Jens Haase

**Comment by pilif** [comment]
as a workaround, I've added

```
/** @return null|mixed */
```

to `current()` (and `offsetGet` in your case)

but IMHO, that doesn't make sense. mixed should contain null and even if it doesn't, `ArrayAccess::offsetGet` and `Iterator::current` should be declared as being able to return null by default.

**Comment by weirdan** [comment]
Does this still happen?

**Comment by jenshaase** [comment]
Looks like the problem is resolved (at least in the case of `offsetGet`):
https://psalm.dev/r/8cf0892b98

**Comment by weirdan** [comment]
Original example also works as expected, if annotated with specific `@extends` (https://psalm.dev/r/89269f9b25) or with the `MixedReturnStatement` suppressed (https://psalm.dev/r/094eea66f7).
