### ISSUE TITLE
Detecting existence of __toString method to allow casting to string

### ISSUE THREAD

**Issue by alecwcp** [vimeo/psalm#3149]
Currently code like
```
<?php

interface EmptyInterface {}

class StringCastable implements EmptyInterface
{
    public function __toString()
    {
        return 'I am castable';
    }
}

function factory(): EmptyInterface
{
    return new StringCastable();
}

$object = factory();
if (method_exists($object, '__toString')) {
    $a = (string) $object;
    echo $a;
}
```

results in the error
`ERROR: InvalidCast - 20:19 - EmptyInterface&object{__toString()} cannot be cast to string`

(see https://psalm.dev/r/c2464d2f09)

But since we've checked that the method `__toString` exists on the object, it is castable. Psalm appears to know that the method `__toString` exists on the object (based on the error message) so I wondered if it was possible for psalm to use that to know that the object is therefore safe to cast to a string?

**Comment by alecwcp** [comment]
I don't know enough about the internals of psalm to begin making a patch for this - but if someone is able/willing to point me in the right direction I'd be up for giving it a shot.

**Comment by muglug** [comment]
Thanks for the offer @alecwcp! The fix was _slightly_ non-trivial, though.
