### ISSUE TITLE
Concrete implementations of template parameters not covariant with their abstract types

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#3150]
Looking at following snippet (https://psalm.dev/r/75f9d49fb7):

```php
<?php

interface Entity
{
    /** @psalm-return Id<static> */
    function id(): Id;
}

/** @psalm-template EntityType Of Entity */
interface Id {}

/** @implements Id<User> */
final class UserId implements Id {}

final class User implements Entity
{
    function id(): UserId {
        throw new \BadMethodCallException('implementation irrelevant');
    }
}
```

`UserId` is a valid `Id<static>` in this scenario, and should be usable as return type of `User#id()`, but it is recognized as a mismatch.

**Comment by weirdan** [comment]
It works if you drop return types: https://psalm.dev/r/30cee3cbc5
But you shouldn't have to.

**Comment by Ocramius** [comment]
@weirdan yeah, that was only part of the issue: raised a second bit in #3151, which is strictly related.
