### ISSUE TITLE
Concrete type of method is replaced by parent templated type

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#3151]
Strictly related to #3150, if a templated type is used as return type on an interface, any concrete implementation concrete return type seems to be completely shadowed (https://psalm.dev/r/5d360166ab)

```php
<?php

interface Entity
{
    /** @psalm-return Id<static> */
    function id(): Id;
}

/** @psalm-template EntityType Of Entity */
interface Id {}

/** @implements Id<User> */
final class UserId implements Id {
    function username(): string {
        throw new \BadMethodCallException('implementation irrelevant');
    }
}

final class User implements Entity
{
    function id(): UserId {
        throw new \BadMethodCallException('implementation irrelevant');
    }
}

function getUser(): User
{
    throw new \BadMethodCallException('implementation irrelevant');
}

echo getUser()->id()->username();
```

Specifically, regardless of the `MismatchingDocblockReturnType`, method `UserId#username()` should be available when a concrete `User` is fetched.

**Comment by muglug** [comment]
Adding a docblock return _as well_ fixes it: https://psalm.dev/r/2866602044

**Comment by Ocramius** [comment]
Oh, interesting: I didn't try it because such a docblock would conflict with my CS rules...

**Comment by muglug** [comment]
Now fixed!

**Comment by Ocramius** [comment]
\o/ thank you, will try it out this week! :partying_face:
