### ISSUE TITLE
Annotation @property works weird

### ISSUE THREAD

**Issue by SCIF** [vimeo/psalm#3156]
Hi there,

We are using Eloquent having magic `__get/__set()`. I tried to annotate properties for Psalm and met next weird issue: https://psalm.dev/r/b425c44bf6

I tried different versions like `@property-read/-write` and `@psalm-` prefixed version. No luck for any of them.

**Comment by muglug** [comment]
When you add actual `__get`/`__set` methods (as exist in Eloquent models) the errors go away: https://psalm.dev/r/d8918bd835

**Comment by SCIF** [comment]
But why `@property-read` doesn't require `__get()`? It's inconsistency.

**Comment by muglug** [comment]
it does: https://psalm.dev/r/d168183001

**Comment by SCIF** [comment]
Hi @muglug , sorry, don't follow you.

I mean this case: https://psalm.dev/r/b425c44bf6

**Comment by muglug** [comment]
Yeah, you're right, it's inconsistent. Both should be errors in your first case.

`usePhpDocPropertiesWithoutMagicCall="true"` will also disable these checks completely.
