### ISSUE TITLE
Object structures are not type checked properly

### ISSUE THREAD

**Issue by tux-rampage** [vimeo/psalm#3158]
When defining an object structure with `@param`, the type checker just seems to check for object.

### Example

https://psalm.dev/r/1e6f27cd81

### Expected

Argument 1 of consume expects object{id:string, name:string, parent?:null|string}, object{group: object{id:string, name: string}} provided.

### Actual

No issues

**Comment by muglug** [comment]
Would you be able to create a PR for this? The necessary code is in TypeAnalyzer.php

**Comment by tux-rampage** [comment]
I'm not sure, yet. I could check out and if I'm able and find the time to fix it I'll open a PR.

**Comment by tux-rampage** [comment]
The code was refactored to `AtomicTypeComparator`/`KeyedArrayComparator` in the meantime. This solved this issue and Psalm is now reporting the type mismatch correctly.
