### ISSUE TITLE
false positive InvalidPropertyAssignmentValue for templated arrays with named keys

### ISSUE THREAD

**Issue by GrandLTU** [vimeo/psalm#3163]
https://psalm.dev/r/6325c38df8

**Comment by SCIF** [comment]
@GrandLTU , 
Not sure if I correct or not but I noticed you are using union types in incorrect manner. Check if it makes sense: https://psalm.dev/r/fbe1f7665b

**Comment by GrandLTU** [comment]
> @GrandLTU ,
> Not sure if I correct or not but I noticed you are using union types in incorrect manner. Check if it makes sense: https://psalm.dev/r/fbe1f7665b
why is it incorrect?
