### ISSUE TITLE
Non-existent arguments should probably give an error

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#3166]
Over the time I find a lot of useless `@param` phpdocs in my project. They are for arguments that no longer exist. It would be nice if psalm could point them out.

https://psalm.dev/r/ca86c581f6

**Comment by muglug** [comment]
I've always thought of this as more of a code style issue – if someone created a PR, and made it something that only appeared with `--find-unused-code` I'd happily accept it

**Comment by weirdan** [comment]
Original snippet now reports a couple of `UnusedDocblockParam`s: https://psalm.dev/r/ca86c581f6
