### ISSUE TITLE
Mark more methods from Throwable as mutation-free

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#3170]
[There are much more methods in exception that are final than just `getMessage()`](https://www.php.net/manual/en/language.exceptions.extending.php)

[Only `getMessage()` is marked as such now probably because that was what the original bug repot was about](https://github.com/vimeo/psalm/commit/d1fcbf38ae591e25d9578b44e9a6e0d675d6d884)

Here is what kind of issue this would fix: https://psalm.dev/r/33893fb34b

**Comment by muglug** [comment]
Make a PR please!

**Comment by greg0ire** [comment]
On it :)
