### ISSUE TITLE
Question: How to proxy to another method in a FunctionReturnTypeProviderInterface extension

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3173]
Hello!

I am struggling to implement a `FunctionReturnTypeProviderInterface` in the laravel plugin, however I think this can be a broader question for how to proxy return types in general.

```php
/**
     * @param  array<\PhpParser\Node\Arg> $call_args
     */
    public static function getFunctionReturnType(StatementsSource $statements_source, string $function_id, array $call_args, Context $context, CodeLocation $code_location): ?Union
    {
        if (!$statements_source instanceof \Psalm\Internal\Analyzer\StatementsAnalyzer) {
            return Type::getMixed();
        }

        // proxy to \Illuminate\Foundation\Application::make
        $methodId = new MethodIdentifier(\Illuminate\Foundation\Application::class, 'make');
        $self_class = 'self';
        return $statements_source->getCodebase()->methods->getMethodReturnType($methodId, $self_class, $statements_source, $call_args);
    }
```

In this specific case, I also have a templated stub for `\Illuminate\Foundation\Application::class`, which I think is the part breaking this proxy.

When I execute some code that invokes this function return type, I get 

```
The declared return type 'Illuminate\Routing\Redirector' for Foo::appHelperResolvesTypes is more specific than the inferred return type 'T:fn-illuminate\foundation\application::make as object'
```

**Shouldn't the templated return type be resolved from the `$call_args`?**

Is this a bug, or am I misunderstanding how this should work? Are we not able to say "This function X should return whatever function Y does"?

Thanks!

Here was my PR for more context: https://github.com/psalm/psalm-plugin-laravel/pull/39

**Comment by muglug** [comment]
The ArrayMapReturnTypeProvider gives a good example: https://github.com/vimeo/psalm/blob/5c511ad95d4153c604660eb6ce05b55b99b5b478/src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMapReturnTypeProvider.php#L230-L266

It's not wonderful (it should probably be extracted into an API method) but it works!
