### ISSUE TITLE
Array item type becomes mixed when array is defined as template

### ISSUE THREAD

**Issue by dsech** [vimeo/psalm#3178]
https://psalm.dev/r/1c3a2a372e
Actual:
> INFO: MixedArgument - 13:51 - Argument 1 of strlen cannot be mixed, expecting string

Expected:
> No issues!

This seems to happen only when typehinting `$data` as `T`. If `$data` is directly typehinted as array then there are no issues reported, as expected: https://psalm.dev/r/77dacdbae5

**Comment by muglug** [comment]
I don't think I'll fix this – it's too niche, sorry.
