### ISSUE TITLE
Ignores docblock return type contradicts signature return type when should be a union type to include null

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#3181]
[Here is a simple example](https://psalm.dev/r/9d6e3c535d). A more real world example would be if you were returning an array, where the array type you specify in the docblock is more specific than the type you specify in the function signature return type. That would be a scenario where there could be value in having both a docblock return type and a function signature return type, but the simple example from the link reproduces the bug in a simpler way.

**Comment by muglug** [comment]
Psalm will always add null if the funtion return type (or param type) signature has it, but you can use `@psalm-ignore-nullable-return`: https://psalm.dev/r/c9c462798f

**Comment by still-dreaming-1** [comment]
What I mean is, I don't want it to be ignored. I want Psalm to report the contradiction as an issue. This could be very confusing for someone who only looks at the docblock return type, assuming it is more accurate and precise, not less accurate. I don't want to have to examine both return types just to know what type a function returns.

**Comment by still-dreaming-1** [comment]
I renamed this to emphasize that I think this should be considered a bug. The main point of Psalm is to report type issues. In my example, the return type in the docblock is incompatible with the types returned in the code and contradicts the return type in the signature.
