### ISSUE TITLE
Template params, string callable functions, and namespaces

### ISSUE THREAD

**Issue by beaucollins** [vimeo/psalm#3182]
I'm attempting to use `@template` with `callable` like this:

```php
/**
 * @template T
 * @param callable(): (T|Throwable) $get_resource
 * @param callable(T): Result $action
 * @return callable(): Result
 */
function runner($get_resource, $action) {
    return function() use ($get_resource, $action) {
        $resource = $get_resource();
        if ( $resource instanceof Throwable ) {
            throw $resource;
        }
        return $action( $resource );
    };
}
```

In use, I expect that if the `$get_resource`'s `T` does not match `$action`s `T` then a type error will be raised.

**If no `namespace` is used**, then an `InvalidArgument` is [correctly raised](https://psalm.dev/r/640d53013d):

```
/**
 * @param OtherThing $thing
 * @return Result
 */
function execute( $thing ) {
    return new class() implements Result {};
}

runner(
    fn() => new Thing(),
    'execute'
);
```

The error as I expect:

```
ERROR: InvalidArgument - 30:1 - Type OtherThing should be a subtype of Thing
```

### The Problem

If a `namespace` is used, [the error disappears](https://psalm.dev/r/bcbd96e22f).

I would expect the same error:

```
ERROR: InvalidArgument - 32:1 - Type Hello\OtherThing should be a subtype of Hello\Thing
```

But there is no error.

**Comment by weirdan** [comment]
In your second example, you refer to the function as `Hello\execute` **from within** `Hello` namespace - so you're actually calling `Hello\Hello\execute` which does not exist: https://3v4l.org/9WQE8

When this is fixed, Psalm correctly reports the issue: https://psalm.dev/r/fd7e115eaa

**Comment by weirdan** [comment]
Actually string callables need to be fully qualified (I was wrong above): [works](https://3v4l.org/9VC66), [fails](https://3v4l.org/mC0Fm1).

**So the bug on Psalm's part is that it qualifies string callables, but it should not.**

**Comment by weirdan** [comment]
Also the failure is limited to functions from the calling namespace, functions from other namespaces are resolved properly: https://psalm.dev/r/26c638224c

**Comment by beaucollins** [comment]
So to recap:

1) If `Hello\execute` is a function that doesn’t exist, I would expect Psalm to fail it it’s used as a callable.
2) Using `\Hello\execute` should fail with `InvalidArgument` but doesn’t, it behaves the same way: https://psalm.dev/r/de3c0df2f1

**Comment by beaucollins** [comment]
Here's a sample that shows the same problem even when the function is in a different namespace as the string callable:

https://psalm.dev/r/44f133751c

**Comment by beaucollins** [comment]
Is there a way to test the changes?

I attempted to install `psalm/phar=dev-master` but it fails to find the failing scenario still. From what I can tell it _does_ include the fix from a3ae2a7.

Step 0) `composer require --dev psalm/phar=dev-master`
Step 1) create non-namespace code:

```php
<?php

/**
 * @template T
 * @param callable():T $get_resource
 * @param callable(T):void $action
 * @return callable():void
 */
function execute( $get_resource, $action ) {
	return function() use ( $get_resource, $action ) {
		$resource = $get_resource();
		$action( $resource );
	};
}

class ThingA {}
class ThingB {}

execute(
	fn() => new ThingA(),
	'execute_thingb'
);

/**
 * @param ThingB $thing
 * @return void
 */
function execute_thingb( $thing) {

}
```

Note that it successfully detects that the return value for `T` does not match the `@param` type of `execute_thingb` because `ThingA` and `ThingB` are not compatible types for `T`.

```
 ./vendor/bin/psalm.phar src
Scanning files...
Analyzing files...

░E░

ERROR: InvalidArgument - src/other.php:19:1 - Type ThingB should be a subtype of ThingA (see https://psalm.dev/004)
execute(
	fn() => new ThingA(),
	'execute_thingb'
);


------------------------------
1 errors found
------------------------------
```

Step 2) change the file to use a namespace:

```diff
diff --git a/src/other.php b/src/other.php
index 76b4a3b..468dae7 100644
--- a/src/other.php
+++ b/src/other.php
@@ -1,4 +1,5 @@
 <?php
+namespace Foo;
 
 /**
  * @template T
@@ -18,7 +19,7 @@ class ThingB {}
 
 execute(
 	fn() => new ThingA(),
-	'execute_thingb'
+	'\Foo\execute_thingb'
 );
 
 /**
```

Step 3) Run psalm again:

```
./vendor/bin/psalm.phar src
Scanning files...
Analyzing files...

░░░

------------------------------
No errors found!
------------------------------
```

The same error is present, but Psalm failed to find it.

To make sure I'm using the correct `psalm` binary, if I keep the namespace but remove the fully qualified string callable name, Psalm correctly reports the `UndefinedFunction` error as introduced by a3ae2a7.

```
./vendor/bin/psalm.phar src
Scanning files...
Analyzing files...

░E░

ERROR: UndefinedFunction - src/other.php:22:2 - Function execute_thingb does not exist (see https://psalm.dev/021)
	'execute_thingb'


------------------------------
1 errors found
------------------------------

```

**Comment by beaucollins** [comment]
Same problem when there are two different namespaces:

```diff
diff --git a/src/other.php b/src/other.php
index 76b4a3b..1f8e8a3 100644
--- a/src/other.php
+++ b/src/other.php
@@ -1,4 +1,5 @@
 <?php
+namespace Foo;
 
 /**
  * @template T
@@ -13,12 +14,14 @@ function execute( $get_resource, $action ) {
 	};
 }
 
+namespace Bar;
+
 class ThingA {}
 class ThingB {}
 
-execute(
+\Foo\execute(
 	fn() => new ThingA(),
-	'execute_thingb'
+	'\Bar\execute_thingb'
 );
 
 /**
```

**Comment by weirdan** [comment]
>  composer require --dev psalm/phar=dev-master

`composer require --dev vimeo/psalm:dev-master` should be the actual latest, without any potential phar issues.
