### ISSUE TITLE
add allowUnusedParametersBeforeUsed option

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#3186]
if a function has multiple arguments and e.g. the first arg is unused but the second arg is used, I would like to be able to NOT get an UnusedParam error.
As in most of these cases, the reason there is an unused arg is bc this function is filtered from some place where the ordering/number of args is pre-given and I cannot change this.

https://psalm.dev/r/6e123c2317

phpcs has this available as a plugin https://github.com/sirbrillig/phpcs-variable-analysis

**Comment by muglug** [comment]
Just prepend `_` to the name: https://psalm.dev/r/12485b0b38
