### ISSUE TITLE
Allow unusedVariable for $value in foreach when $key is used

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#3187]
In a foreach loop the only option to use the $key, is to also assign the $value.
In that case you will get an UnusedVariable error though:
https://psalm.dev/r/d9bd03cc4e

Change rule UnusedVariable: 
>Allow unusedVariable for $value in foreach when $key is used

I know I can just do array_keys, but this is slower & not benefitting the code.

**Comment by weirdan** [comment]
Did you know that Psalm ignores UnusedVariable on variables starting with `$_`: https://psalm.dev/r/08012bd7e6

It works for parameters as well: https://psalm.dev/r/69532a684b

**Comment by muglug** [comment]
Yeah, just change the name to `$_`
