### ISSUE TITLE
Inconsustency in GMP

### ISSUE THREAD

**Issue by vladyslavstartsev** [vimeo/psalm#3190]
While working on https://github.com/vimeo/psalm/pull/3189 I've found that `GMP` it self is not so consistent with language. 
The best way to understand it is to show the example
https://3v4l.org/BE8MW
The inconsistency is, that `hexdec` function supports hex numbers with OR without leading `0x`/`0X`, but `gmp_*` functions (in this example `gmp_init` support only numbers with leading `0x`/`0X`).
Psalm it self doesn't detect any issues.
https://psalm.dev/r/fb278eed35

I would be nice, if it can detect that.

**Comment by muglug** [comment]
I don't think this is possible in practice, sadly
