### ISSUE TITLE
Subtracted/negative types

### ISSUE THREAD

**Issue by BackEndTea** [vimeo/psalm#3192]
# Feature request

What i would like are subtractable/negative types, my use case is an assertion lib, in order to allow 'negative' validations.

Is this something that could be added into phpstan, or would it bring too much complexity for little gain? If this is something that is wanted within stan i'd be happy to work on a PR.

Here are some examples of how this could work.

```php
   /**
     * @param mixed $input
     *
     * @return ~null
     * Or maybe:
     * @return (mixed&~null)
     * or even
     * @return (mixed~null)
     */
    public function notNull($input)
    {
        if ($input === null) {
            throw new LogicException();
        }

        return $input;
    }
```

Or with templates:

```php
    /**
     * @template T
     * @template TNot
     * @param callable(mixed): TNot $not
     *
     * @return callable(T): (T~TNot)
     */
    public function not(callable $not);
```

Related: https://github.com/phpstan/phpstan/issues/3182

**Comment by andrew-demb** [comment]
`s/phpstan/psalm/` 🙂

**Comment by weirdan** [comment]
That's already possible with Psalm templates: https://psalm.dev/r/daf7f25805

**Comment by weirdan** [comment]
And in the form of assertions (different, but working to the same effect): https://psalm.dev/r/c7ef651fd1

**Comment by BackEndTea** [comment]
> `s/phpstan/psalm/` 🙂

@andrew-demb 
Woops, i copy pasted this from that repo, so i forgot to update it 😅 

> That's already possible with Psalm templates: https://psalm.dev/r/daf7f25805

@weirdan 
Thats almost the same, but i dont' think i can apply that to more 'generic' applications like my second example? e.g. subtract one templated type from the other? Or maybe i'm missing something.

**Comment by weirdan** [comment]
> i dont' think i can apply that to more 'generic' applications like my second example?

Can you show the implementation for that `not()` function? I'm not sure I completely understand how it's supposed to work.

**Comment by BackEndTea** [comment]
```php

class Assert
{
/**
     * @param callable(mixed): TNot $callable
     *
     * @return callable(T): T~TNot
     *
     * @template T
     * @template TNot
     */
    public function not(callable $callable): callable
    {
        return static function ($input) use ($callable) {
            try {
                $callable($input);
            } catch (InvalidArgumentException $e) {
                return $input;
            }

            throw new InvalidArgumentException();
        };
    }
}

class Type
{
    /**
     * @return callable(mixed): null
     */
    public static function null(): callable
    {
        return static function ($input) {
            if ($input !== null) {
                throw new InvalidArgumentException();
            }

            return $input;
        };
    }
}
```

So here i could do someting like:
```php

function(?string $input) {
    $input = Assert::not(Type::null())($input);
    //input would be certain of type string after this
}
```
