### ISSUE TITLE
$_SERVER['REQUEST_TIME_FLOAT']

### ISSUE THREAD

**Issue by sebastianbergmann** [vimeo/psalm#3194]
Psalm does not know that `$_SERVER['REQUEST_TIME_FLOAT']` is `float`. At least if it does not get overwritten in userland.

When I explicitly cast it to float then Psalm is happy but PhpStorm complains about a superfluous cast.

Code in question: https://github.com/sebastianbergmann/php-timer/blob/master/src/Timer.php#L119

**Comment by muglug** [comment]
Oh, upon reflection PHPStorm is in the wrong here, as it's generally unsafe to assume anything about `$_SERVER`. Does it still complain if you use an `is_float` check: https://psalm.dev/r/48a8fb9874?

**Comment by weirdan** [comment]
Note: it's possible to declare the shape of a superglobal in `psalm.xml` with [`<globals>`](https://psalm.dev/docs/running_psalm/configuration/#globals). So this can be achieved by:
```xml
<globals>
   <var name="_SERVER" type="array{REQUEST_TIME_FLOAT:float}"/>
</globals>
```
