### ISSUE TITLE
Should complain about private typed property initialized in public/protected non-final method

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#3201]
I think Psalm should still complain about potentially uninitialized property, because public, non-final method may be overridden in descendants: https://psalm.dev/r/4f967f6930, https://3v4l.org/juGjD

_Originally posted by @weirdan in https://github.com/vimeo/psalm/issues/3200#issuecomment-616707251_

**Comment by weirdan** [comment]
Simplified: https://3v4l.org/HmtAZ, https://psalm.dev/r/63168feb83

**Comment by muglug** [comment]
So I think the thing to do here is to ignore any non-final methods when analysing initilisation of one or more private methods.

**Comment by muglug** [comment]
This imposes an additional constraint that will break some currently-working Psalm builds

**Comment by weirdan** [comment]
> This imposes an additional constraint 

I thought Psalm already had that constraint (see #358). Was it relaxed at some point?

**Comment by muglug** [comment]
Yeah, I didn’t have any tests with this edge-case (a private property set in an overrideable method), so blanket allowed setting properties in public methods.
