### ISSUE TITLE
Psalm with @template in namespace function fails to find error

### ISSUE THREAD

**Issue by beaucollins** [vimeo/psalm#3204]
The original problem from #3182 is still not resolved.

When no `namespace` is used, Psalm correctly finds mismatched `@template` types:

https://psalm.dev/r/6d185cca5b

When a `namespace` _is_ used, Psalm **fails to find** mismatched `@template` types:

https://psalm.dev/r/83cc97962c

Note that this seems to be only when using `string` callable types. From what I can tell all other callable scenarios work as expected:

https://psalm.dev/r/e2cd506b36

**Comment by beaucollins** [comment]
From testing it appears as the `namespace`d scenario gives the `TemplateResult` an empty `lower_bounds`

https://github.com/vimeo/psalm/blob/e7b8983b7ea811ae95131134e0c4c40d6777e856/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php#L3838

```
[lower_bounds] => Array
        (
        )
```

Where the non-`namespace`ed version has a non-empty `lower_bounds`:

```
    [lower_bounds] => Array
        (
            [T] => Array
                (
                    [fn-execute] => Array
                        (
                            [0] => Psalm\Type\Union Object
                                (
                                    [types:Psalm\Type\Union:private] => Array
                                        (
                                            [B] => Psalm\Type\Atomic\TNamedObject Object
```

Tests being used:

```diff
diff --git a/tests/CallableTest.php b/tests/CallableTest.php
index 4523ee310..522fd1569 100644
--- a/tests/CallableTest.php
+++ b/tests/CallableTest.php
@@ -1098,13 +1098,13 @@ class CallableTest extends TestCase
                         $action($item);
                     }
 
-                    class A {}
-                    class B {}
+                    class C {}
+                    class D {}
 
-                    function action_b( B $item ): void {
+                    function action_d( \NS\D $item ): void {
                     }
 
-                    execute( new A(), "\NS\action_b" );
+                    execute( new \NS\C(), "\NS\action_d" );
                     ',
                 'error_message' => 'InvalidArgument',
             ],
```

**Comment by beaucollins** [comment]
For namespaced functions when calling `Psalm\Internal\TypeAnalyzer::getCallableFromAtomic` it calls `Psalm\Internal\Codebase\Functions::getStorage` with the function name with the namespace defined in the source code _with_ the prefixed `\` root namespace backslash.

So `\NS\action_d` is used an the `$function_id`, but the function is known as `ns\action_d` in the storage containers.

https://github.com/vimeo/psalm/blob/e7b8983b7ea811ae95131134e0c4c40d6777e856/src/Psalm/Internal/Codebase/Functions.php#L80-L91

**Comment by muglug** [comment]
ahh, this is a casing bug! PHP & its &%#*ing case-insensitive symbols...

**Comment by beaucollins** [comment]
> this is a casing bug!

Similar sentiments here.

Worth noting it was _also_ because of a preceding slash `ns\fn_name` vs `\ns\fn_name`.

**Comment by muglug** [comment]
Sorry! Didn’t see your solution until it was too late, but thanks for providing one

**Comment by beaucollins** [comment]
Not to worry, the harder part was finding the problem to begin with.
