### ISSUE TITLE
Invalid variable type assumption on list assignment.

### ISSUE THREAD

**Issue by kapitancho** [vimeo/psalm#3206]
The following snippet:
	[$a, $b] = explode('-', $whatever);
	$c = $b ?? '';
Emits an error incorrectly. The value of $b could be either string or null depending on the value inside $whatever.

ERROR: TypeDoesNotContainType - src\todo.php:4:7 - string is always defined and non-null

**Comment by kapitancho** [comment]
Yes, it is reproducible on psalm.dev

**Comment by weirdan** [comment]
https://psalm.dev/r/763868f89d

**Comment by muglug** [comment]
Any code that would emit a notice/warning in PHP (as this code does) is not something I consider buggy.

Instead use this formulation: https://psalm.dev/r/7a00f4a5c6
