### ISSUE TITLE
Ability to restrict templates

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#3207]
Currently it is possible to use the `@template A of B` syntax to restrict the family of types where `A` can actually vary. This currently needs to happen when the template `A` is declared.

It could be interesting to provide a mechanism (the `of` syntax could be good for this, but maybe there's a better syntax) to allow restrictions on templates at a later point in the code. Consider the following snippet of code (https://psalm.dev/r/730b1b48dc), which currently fails

```php
/**
 * @template A
 */
class Foo
{
    /** @var A */
    private $a;
    
    /**
     * @psalm-param A $a
     */
    public function __construct($a)
    {
    	$this->a = $a;
    }
    
    /**
     * @template A of string
     * @psalm-return A
     */
    public function print()
    {
        return $this->a;
    }
}
```

The class `Foo` can be built with `A` being any type. But I would like to be sure that the method `print` is actually called only when `A` is a string.

This is a silly example, but I guess it gives the idea.

**Comment by muglug** [comment]
Do it with a subclass: https://psalm.dev/r/ce8a587dce

**Comment by marcosh** [comment]
thanks @muglug for the suggestion. That's not a viable solution in my case though, because the class is final and I can't inherit from it

**Comment by marcosh** [comment]
I realised there is another reason why inheritance is not a good solution here. Consider the case where you already have a class `Bar<A>` inheriting from a class `Foo<A>`. If you create clasees `StringBar<A>` and `StringFoo<A>` to implement your suggestion, then you get a multiple inheritance issue, since `StringBar<A>` should inherit both from `Bar<A>` and `StringFoo<A>`

**Comment by muglug** [comment]
You can sort of do this with a conditional return type now:

https://psalm.dev/r/edcb6282af

**Comment by marcosh** [comment]
thank you!

still, I think it is not enough for what I have in mind. Consider for example this snippet (https://psalm.dev/r/c11482f00b)

```php
/**
 * @template T
 */
class Foo
{
    /**
     * @constraint T of string
     */
    public function bar(): void {}
}

/** @var Foo<int> $foo */
$foo = new Foo();

$foo->bar();
```

I would like it to fail because the method `bar` should be callable only if the template `T` is a string

**Comment by weirdan** [comment]
Something like this, paired with ability to alter type params as a result of a method call could allow to mimic typestates recently mentioned in another thread. /cc: @olleharstedt 

The big question, I suppose, is how it should interact with inheritance.

**Comment by olleharstedt** [comment]
> I would like it to fail because the method bar should be callable only if the template T is a string

I'm working on a patch for this. My solution is a new annotation called `@self-out` (alternative to `@param-out`) which changes the type of `$this` on method call. To be really useful, it needs some kind of alias tracking (typestate always does), but even so, it wouldn't interact well with exceptions. Still could be useful. Anyway, with e.g. `@self-out <interface>`, you could shift which methods are available while keeping the same object. Example:

```php
/**
 * @self-out ClosedFile
 */
public function close() {
  // close the file here
}
```

`@self-out` should probably also have some type restrictions, so it's not possible to change a DatabaseConnection class into a string. ^^

Some notes about alias tracking here: https://old.reddit.com/r/types/comments/hc4xnw/a_simple_alias_tracking_system_for_variables_with/

A forum would be a better place to discuss things like this, though. ;)

**Comment by marcosh** [comment]
@olleharstedt if I understand correctly your proposal, `@self-out` would modify the type of the class when a method is called.

What I need is to actually prevent a method from being called if a template does not satisfy a constraint.

I don't necessarily see the two things as one containing the other. Am I missing something? How would my example above (https://github.com/vimeo/psalm/issues/3207#issuecomment-646734940) work with your proposed syntax?

**Comment by olleharstedt** [comment]
> What I need is to actually prevent a method from being called if a template does not satisfy a constraint.

By using `@self-out T of string`.

**Comment by olleharstedt** [comment]
@marcosh Ah yeah, they don't overlap (as I can see). But if you have control over how Foo is created, why not create an interface without bar() and cast it to that?

```php
/** @var FooWithoutBarInterface<int> $foo */
$foo = new Foo();
```

**Comment by weirdan** [comment]
My idea was that:
* if it's possible to change the type, say from `File<Closed>` to `File<Open>`
* and there's a way to restrict some methods to be available only on `File<Closed>` and some other to be available on `File<Open>` exclusively

then the following would behave just like typestates mentioned in that other ticket

```php
/** @template TState */
interface File {
   /** @template-mutate TState is Closed */
   public function __construct(string $filename);

   /**
    * @template-require TState is Closed
    * @template-mutate TState is Open
    */
   public function open();

   /**
    * @template-require TState is Open
    */
   public function read(): string;

   /**
    * @template-require TState is Open
    * @template-mutate TState is Closed
    */
   public function close(): void;
}

$file = new File('/dev/null'); // $file is File<Closed>
$file->read(); // error, read() is only available on File<Open>
$file->open(); // $file is File<Open>
$file->open(); // error, open() is only available on File<Closed>
$file->read(); // ok
$file->close(); // ok
$file->close(); // error, close() is only available on File<Open>
```

**Comment by muglug** [comment]
For the original question,

`@psalm-param string T` seems like it might be sufficient - it wouldn’t require new syntax, and it sort of makes sense

**Comment by muglug** [comment]
I think a `@psalm-assert File<Open> $this` annotation would work fine here

**Comment by weirdan** [comment]
> I think a `@psalm-assert File<Open> $this` annotation would work fine here

Would that be a substtiution for `-mutate` or `-require`?

Wouldn't that change how assert's are working now though (read: BC break)? As far as I understand, currently asserts can only narrow the type (e.g. with assert you can go from `Class<mixed>` to `Class<int>`, but not vice versa), and Psalm complains about contradiction when that results in empty intersection.

**Comment by muglug** [comment]
Ohh yes, very good point

**Comment by muglug** [comment]
So yeah, `@self-out` or `@psalm-self-out` probably makes the most sense

**Comment by marcosh** [comment]
> @marcosh Ah yeah, they don't overlap (as I can see). But if you have control over how Foo is created, why not create an interface without bar() and cast it to that?
> 
> ```
> /** @var FooWithoutBarInterface<int> $foo */
> $foo = new Foo();
> ```

I don't have control over who creates `Foo`, so this is not viable

**Comment by marcosh** [comment]
> For the original question,
> 
> `@psalm-param string T` seems like it might be sufficient - it wouldn’t require new syntax, and it sort of makes sense

do you mean something like

```php
<?php

/**
 * @template T
 */
class Foo
{
    /**
     * @psalm-param string T
     */
    public function bar(): void {}
}
```

and `psalm-param` works on the template `T` instead of an actual parameter? That could work for me

**Comment by muglug** [comment]
Yup, that’s what I was thinking

**Comment by marcosh** [comment]
> Yup, that’s what I was thinking

Great, I could have some time to contribute to an implementation, you you can provide some pointers

**Comment by olleharstedt** [comment]
> and psalm-param works on the template T instead of an actual parameter? That could work for me

Does not really communicate intent clearly, if same notation is used for different purpose.

**Comment by marcosh** [comment]
sorry to bother you all again, could you just provide some pointers on how to go to implement such a feature? I have some time I'd like to dedicate to this

**Comment by olleharstedt** [comment]
Well, I'm already against usting `param` for anything else than function arguments. :) You'd have to start reading the code, I guess.

**Comment by olleharstedt** [comment]
My suggested solution: https://github.com/vimeo/psalm/issues/3740
