### ISSUE TITLE
[Intended Behavior?] Stubs can remove interfaces from classes

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3208]
Hello!

Forgive me if I'misunderstanding the intended power of stubs, but I come from phpstan where stubs are just used for changing docblocks 😃. We've run into this over at https://github.com/psalm/psalm-plugin-laravel/issues/21

```php
interface UserContract  {}

class User implements UserContract {}
```

And then a stubfile for user like the following, which was intended to add documentation to the `User` class:

```php
/**
* @property string $name
*/
class User {}
```

Since the stub file doesn't have the interface listed, psalm thinks the `User` class no longer satisfies the `UserContract`. Is this intentional behavior? I found https://github.com/vimeo/psalm/issues/482, which makes me thing that this might be a bug

**Comment by muglug** [comment]
It's intentional – classes should still give all their interfaces, but they don't to give all the class's methods or properties.
