### ISSUE TITLE
psalm does not consider null on list('key' => $assignement) = func()

### ISSUE THREAD

**Issue by ygottschalk** [vimeo/psalm#3210]
### TL;DR
https://psalm.dev/r/6c9100f2dc

### how to reproduce
consider having a function `func()` with `@return null|array{'key': int}` (or simply any value with that type)
using `['key' => $a] = func();` to assign `$a` should leave it with type `null|int`, but `int` is assumed

### additional stuff
see also https://3v4l.org/3DbO5

somehow related #1334

if you need more info please let me know

**Comment by muglug** [comment]
I generally don't treat the by-product of any operation that generates a notice or warning in PHP as a bug in Psalm, but the array destructuring should prompt a warning
