### ISSUE TITLE
Analysis cache in CI

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#3212]
Like phpstan supports it, I tried adding the /tmp/psalm directory in our GithubAction to a actions/cache@v1

https://github.com/redaxo/redaxo/pull/3552/files

The output of the GithubActions after merging this change looks like that psalm still scans the whole application, instead of only changes.

See https://github.com/redaxo/redaxo/runs/607688837?check_suite_focus=true

![A25FE947-D571-45C8-95BF-96EED153DC66](https://user-images.githubusercontent.com/120441/79952262-6f83b300-847a-11ea-8444-7c93ef01fa54.png)

Did I do something wrong, or is the feature not supported?

**Comment by weirdan** [comment]
As far as I understand, the output should be the same (seen commits mentioning 'replaying issues'), but it should run faster.

**Comment by staabm** [comment]
I wondered because I dont see speed improvements compared to bevore caching /tmp/psalm

See e.g. https://github.com/redaxo/redaxo/pull/3548/checks?check_run_id=597937809

**Comment by muglug** [comment]
You're not running Psalm with `--diff`, so there's no reuse of cache happening. I plan to make that the default in two or three minor versions, but for now you need the flag.

**Comment by staabm** [comment]
thx for the hints.. just added `--diff` (with https://github.com/redaxo/redaxo/pull/3564) and it did not get any faster 

https://github.com/redaxo/redaxo/runs/611336632

![grafik](https://user-images.githubusercontent.com/120441/80076336-5814fa80-854c-11ea-8a12-fe8eaa9af002.png)
