### ISSUE TITLE
Late static binding values used as template params require declaration of `&static` in method return types

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3213]
👋I ran into this while templating Eloquent. Is it intentional that we are required to declare an intersection type of the actual subclass type &static? 
https://psalm.dev/r/c5cba4ead9

This only seems to be an issue for me when templates are involved, as I tried minimizing the steps to reproduce and normal late static binding typehinting seem to work fine.

https://psalm.dev/r/7eadb6a3f4

Am I missing something?

Thanks!

**Comment by muglug** [comment]
Yes, because the templates are not declared [covariant](https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance). If you change to `@template-covariant`, things work: https://psalm.dev/r/a8ded03e27

**Comment by muglug** [comment]
Sorry, ignore my last comments, this is a bug I think.

**Comment by mr-feek** [comment]
you the man @muglug , thanks!
