### ISSUE TITLE
Static functions have issues resolving `static` return type

### ISSUE THREAD

**Issue by SCIF** [vimeo/psalm#3219]
https://psalm.dev/r/08359d1906 L23

**Comment by muglug** [comment]
`static` can only refer to the class a function is declared in, and its descendants, so I believe the treatment is essentially correct. Do you have a real-world example?

**Comment by zerkms** [comment]
`static` should be the same as the class the static function was invoked on: https://3v4l.org/JINUl

So `$a` should be typed as `B2<C2>&C2`

https://www.php.net/manual/en/language.oop5.late-static-bindings.php

**Comment by muglug** [comment]
Yeah, and the intersection of two classes is impossible in PHP.

**Comment by SCIF** [comment]
Hey @muglug , real worlds example is Laravel's Eloquent ORM. It uses a lot of magic under the hood of Model class (highly coupled with Builder)

**Comment by zerkms** [comment]
> Yeah, and the intersection of two classes is impossible in PHP.

Is it?

```php
<?php

class A {}
class B extends A {}

/** @var A&B $b */
$b = new B();
```

In the provided case indeed, the value of the _expected_ intersection type cannot exist in php's type system. But _actually_ inferred type is invalid as well.

**Comment by SCIF** [comment]
Here is a code implementing damn magic I mentioned above — https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Model.php#L1658-L1664

**Comment by mr-feek** [comment]
Hey @SCIF , I'm in the process of stubbing out Eloquent myself! https://github.com/psalm/psalm-plugin-laravel/pull/52

would love to have you help contribute

**Comment by SCIF** [comment]
Hi @mr-feek , I'm actually quite new to psalm and I'm doing stubbing in unofficial laravel adapter because official laravel adapter is quite heavy and overwhelmed for me/my company. I would consider `Collection`, `Model` and `Enumerable` pretty much done. You can [grab](https://github.com/macroactive-io/laravel-psalm/tree/master/stubs) whatever you want or I can do a PR providing my files to your project. But these days I'm struggling for stubbing `Builder` because of scopes, `where*` methods having intersection with `Builder` even «implemented» in Model.

**Comment by SCIF** [comment]
Oh, my bad, `Model` is not ready yet. :(

**Comment by SCIF** [comment]
Hi @muglug , could you advise the state of this ticket?

**Comment by muglug** [comment]
@SCIF you'll have to do a better job with some real-world code – the example you've given (the intersections with `static` don't make sense

**Comment by SCIF** [comment]
Hi @muglug , it was not a good idea to share a link to branch. Here is [a proper link](https://github.com/laravel/framework/blob/v7.12.0/src/Illuminate/Database/Eloquent/Model.php#L1722-L1741) using tag

**Comment by SCIF** [comment]
Hi @muglug , is this example is clear enough?

**Comment by muglug** [comment]
Yup – check out the Psalm Laravel plugin, where @mr-feek has added a lot of that functionality since this ticket was opened. I know you're already aware of it, but he has done a lot of great work and I've pushed updates to Psalm to ensure compatibility.

**Comment by SCIF** [comment]
Hi @muglug , I don't really understand why this ticket is treated as not a bug. There is an inconsistency between behavior of static and not static calls. So at least `bug` label should be applied, IMHO.  And optionally `mattwontfix`, if you want.

**Comment by muglug** [comment]
@SCIF the code in the example you posted doesn’t make sense, as it implies the union of two classes, which is impossible. There’s no difference (as far as I’m aware) in the handling of valid code.

**Comment by muglug** [comment]
Laravel does some quirky things, but @mr-feek is doing an awesome job of helping Psalm make sense of them. If you’re using Psalm and Laravel, the official plugin is the officially-supported method.
