### ISSUE TITLE
Psalm not understanding generics on method signature

### ISSUE THREAD

**Issue by afbarbaro** [vimeo/psalm#3220]
Reproduced [here](https://psalm.dev/r/3b80d43323)

Getting `ERROR: MethodSignatureMismatch - 13:32 - Argument 1 of B::foo has wrong type 'string', expecting '' as defined by A::foo`

```
/** @template T **/
abstract class A {
    /** 
     * @psalm-param T $bar
     */
    protected function foo($bar) : void {}
}

/** @template-extends A<string> **/
class B extends A {
    public function foo(string $bar) : void {}
}
```

**Comment by afbarbaro** [comment]
Additionally, the error suppression does not work either, so it's a blocking/critical bug for us.

` /** @psalm-suppress MethodSignatureMismatch this is a Psalm bug */`

This does not take effect.

**Comment by andrew-demb** [comment]
Are you need to change method visibility (protected to public) and make argument type closer (mixed to string)?
AFAIK PHP not allow to change argument type in child

**Comment by muglug** [comment]
Psalm is right – this is a bug: https://3v4l.org/aLtmj

**Comment by afbarbaro** [comment]
> Psalm is right – this is a bug: https://3v4l.org/aLtmj

Thank you both @andrew-demb and @muglug.  You are correct.  Psalm is right!

Just for clarity, the issue is due to the child method having the argument typehint.  The increase visibility is not a problem.

Thanks again.
