### ISSUE TITLE
Documentation: document `lowercase-string`

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#3223]
I'm not sure I can find `lowercase-string` description anywhere in the documentation.

**Comment by muglug** [comment]
It's sort of intended as a type that only gets used in Psalm itself – I'm not sure I want it to be considered part of Psalm's type system.

**Comment by zerkms** [comment]
Right, it's used in the webmozart/assert though: https://github.com/webmozart/assert/blob/e692710ce783cf3d42e7e157e7bb18c12b2107ec/src/Assert.php#L1446

**Comment by Ocramius** [comment]
Using it in the wild as well: it is very interesting for templating logic too :+1:

**Comment by staabm** [comment]
We also use it - pretty usefull

**Comment by weirdan** [comment]
It's been documented: https://psalm.dev/docs/annotating_code/type_syntax/scalar_types/#lowercase-string-non-empty-string-non-empty-lowercase-string

**Comment by uuf6429** [comment]
Hi! Unfortunately that documentation is not enough.

This PHPDoc type "leaked" out of psalm and is used elsewhere, notably PHPStan (and PHPDocumentor), which also lacks documentation on this type.

From the [code here](https://github.com/vimeo/psalm/pull/10722/files#diff-4f029c4356416f8c892d88d24cc3e7a2d389e74a3fadc739ad0970ffedae233dR1149) it seems this has been implemented with strtolower(), which explains why Ü (capital umlaut) is allowed: https://psalm.dev/r/3e2c6d9d0a (multibyte variant would have worked differently though: https://3v4l.org/1FXE3)

Why am I mentioning this? I'm working on something that require validating `lowercase-string` values, and I thought about using a negated unicode category, which would normally make sense: `/^[^\p{Lu}]*$/` However in this case a simpler `/^[^A-Z]*$/` would fit better.

**Comment by Ocramius** [comment]
@uuf6429 please open a nee issue 😁
