### ISSUE TITLE
str_replace does not allow a null replacement

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#3224]
Working php code Psalm is not happy with: https://psalm.dev/r/89bd6bab25
I would fix it but I could not find where Psalm gets its info from.

**Comment by weirdan** [comment]
Looks like a sufficiently bad code that should be fixed rather than allowed.

**Comment by greg0ire** [comment]
I don't know… this looks like something that phpcs would forbid, but not Psalm. Psalm is here to find bugs, and this works perfectly, doesn't it?

**Comment by weirdan** [comment]
That's debatable. On one hand 'Psalm is not PhpCS' is established position, I had the issues reported by me closed with that justification. On the other hand Psalm rejects a lot perfectly working code (see all those Mixed* issues), so it's not here to only prevent bugs. It's here to make you write better code, and does this mainly by enforcing type correctness. And you're passing `null` (which is distinct type in PHP) where `string[]|string` is expected.

Besides, it's easy to fix: https://psalm.dev/r/1d16bdfe2a

**Comment by greg0ire** [comment]
> And you're passing null (which is distinct type in PHP) where string[]|string is expected.

Again, I did not write this :P , but if I had to fix it, I would use `echo str_replace('a', '', 'abc');`

I'm afraid that if I change this, people are going to go pedantic and tell me that nothing in the docs says that replacement as to be `string[]|string`

> On the other hand Psalm rejects a lot of perfectly working code (see all those Mixed* issues), so it's not here to only prevent bugs. 

I didn't know that was the case, closing, then, thank you.

**Comment by weirdan** [comment]
> I'm afraid that if I change this, people are going to go pedantic and tell me that nothing in the docs says that replacement as to be string[]|string

Apart from the function description which reads 'Replace all occurrences of the search *string* with the replacement *string*' (https://www.php.net/str_replace). 

If that doesn't work to convince them, invoke @Ocramius :rofl:

**Comment by greg0ire** [comment]
Well the repo at hand is doctrine/dbal, so … should work I guess :P

**Comment by Ocramius** [comment]
should be fixed: use a `(string)` cast on that `null`, and pretend to never have seen that `null` also ever worked.

**Comment by greg0ire** [comment]
It's fixed, see the linked commit above ;)
