### ISSUE TITLE
Template constraints do not support value

### ISSUE THREAD

**Issue by gmazzap** [vimeo/psalm#3226]
When using nullable types in template constraints, trying to assign to a property the exact value of the constraint produce an error.

See https://psalm.dev/r/50fef3f077

**Comment by weirdan** [comment]
Not limited to nullable constraints, neither to unions: https://psalm.dev/r/a6c96d4275

**Comment by muglug** [comment]
You're just missing param types: https://psalm.dev/r/10275d7ef6

**Comment by muglug** [comment]
It should be an error to assign the property to a non-templated value

**Comment by weirdan** [comment]
:facepalm:

**Comment by gmazzap** [comment]
The problem is that I have ` useDocblockTypes="false"` in `psalm.xml` so relying on doc block don't work for me.

(I'm dealing with 3rd party code with complete bonker doc block so I need to avoid parsing them)

Would be possible that Psalm recognizes that the type of the template and the type of the variable from type declaration match? 

Btw, I've solved adding `@var` before assigning the variable https://psalm.dev/r/3eb607cac9

**Comment by weirdan** [comment]
@gmazzap that's not really a solution, as templates are not properly narrowed without `@param` docblocks on constructors: https://psalm.dev/r/a4815cbb9c - this should output `Foo<null>`.

**Comment by gmazzap** [comment]
@weirdan so that means that  `useDocblockTypes="false"` and templates with constraints can't be used together?

Is there a way to tell Psalm to don't parse doc-bloc of external code (things in vendor or other folders) but parse for _my_ code?

**Comment by weirdan** [comment]
Templates just don't work without using docblock types.

I don't think Psalm can be configured to ignore docblocks in third-party code right now. I'd suggest to describe this feature request in a separate issue.
