### ISSUE TITLE
Return by parameter and type checks on a null initialized variable

### ISSUE THREAD

**Issue by ktomk** [vimeo/psalm#3227]
As good coding practice for functions that return by ~~reference~~ parameter, I initialize such variables with NULL.

Psalm somewhat rightfully complains about these. Just initializing the variable in the function call that returns by parameter does _not_ make psalm complain about such variables.

So this is not a request for feature creep, only if this is compatible on a general level with the utility without affecting it's run-time performance to a neglectable degree:

```php
<?php declare(strict_types=1);

$status = null;

$result = exec(':', $ouput, $status);
```
* https://psalm.dev/r/bc44abcd30

The example might appear borderline somewhat, why initialize $status when not initializing $output? The answer is trivial, in a larger code/with more context, $status is evaluated after the  exec() call while $output is not.
 
So the feature request in this issue is to support variables for parameters by reference that are earlier defined with a NULL value. A simple `$status = 0` works around the issue, but then I don't feel so well about the fact, that I can't differentiate the type (e.g. strict comparison) afterwards for the status (here w/ exec $status === 0 is OK by posix convention).

The rationale is, that effectively $output is passed (effectively) as null as well - at least for me who is merely in PHP user-space - so it could/should be acceptable for $status pre-initialized as NULL to make the actual code more explicit (read: readability) and psalm should not mark it as an error (false-positive).

Maybe this is easily possible (and makes sense first of all)?

**Comment by weirdan** [comment]
@psalm-github-bot, you missed this: https://psalm.dev/r/bc44abcd30

**Comment by weirdan** [comment]
So what you're asking for is to treat `exec()` as if it was defined as follows?
https://psalm.dev/r/72d3f07218

**Comment by weirdan** [comment]
@muglug doesn't `&w_` prefix in callmap mean the input type should be ignored? The following line in the file header hints it should be:

>  '&w_<arg_name>' indicates that a parameter is expected to be passed in, and the value will be ignored, and may be overwritten.

**Comment by ktomk** [comment]
@weirdan as an example probably, but I have to read about `@

> @psalm-github-bot, you missed this: https://psalm.dev/r/bc44abcd30

I edited it in later.

**Comment by weirdan** [comment]
> I edited it in later.

It should have picked that as well (it monitors edits to comments it replied to), so I suspect there's a bug I need to fix.

**Comment by ktomk** [comment]
@weirdan 

> So what you're asking for is to treat `exec()` as if it was defined as follows?
> https://psalm.dev/r/72d3f07218

sort-of as an example probably, but I have to read about `@param-out` first, it's new to me.

nevertheless I'm less concerned about `exec()` itself but I'm more on the impression that with NULL initialization it's always acceptable in PHP for referenced parameters as it would be for "undefined" variables (used for pass-by-reference parameters) - am I too far off here?

**Comment by ktomk** [comment]
> > I edited it in later.
> 
> It should have picked that as well (it monitors edits to comments it replied to), so I suspect there's a bug I need to fix.

The bot seems to pick it all over again as well, each quoted mention for example. The bot first reminded me to put in, albeit I wanted to edit it in anyway (okay that the bot could have never known), and then the original comment went away (nice!) and then it reported about detecting it (again).

**Comment by weirdan** [comment]
> am I too far off here?

It really depends on how the function in question uses that parameter, as it's not necessarily used as output-only.

**Comment by ktomk** [comment]
> > am I too far off here?
> 
> It really depends on how the function in question uses that parameter, as it's not necessarily used as output-only.

but in any case var defined NULL earlier equals undefined var passed in invocation.

**Comment by ktomk** [comment]
> @muglug doesn't `&w_` prefix in callmap mean the input type should be ignored? The following line in the file header hints it should be:
> 
> > '&w_<arg_name>' indicates that a parameter is expected to be passed in, and the value will be ignored, and may be overwritten.

Maybe NULL is not a value but  a type in the system that has no value?

**Comment by weirdan** [comment]
> but in any case var defined NULL earlier equals undefined var passed in invocation.

And it could either be a problem (for functions using it as in/out parameter, like `array_multisort`) or it could be just fine (when it's used for output only, like `exec` uses it). 

> Maybe NULL is not a value but a type in the system that has no value?

Nope, it's a distinct type as far as Psalm concerned. PHP also treats it as a separate type internally.

PS: the bot has it's own repo (https://github.com/weirdan/psalm-github-bot/issues) where it can be discussed. Let's not clutter @muglug's inbox with off-topic messages.

**Comment by ktomk** [comment]
> > but in any case var defined NULL earlier equals undefined var passed in invocation.
> 
> And it could either be a problem (for functions using it as in/out parameter, like `array_multisort`) or it could be just fine (when it's used for output only, like `exec` uses it).

yes, this is exactly the part I'm too far of, just didn't consider such. very nice.

> 
> > Maybe NULL is not a value but a type in the system that has no value?
> 
> Nope, it's a distinct type as far as Psalm concerned. PHP also treats it as a separate type internally.

Yes, this is it it. For PHP it's not even a [scalar](https://www.php.net/manual/en/function.is-scalar.php), so as far as it's possible to say that PHP has types (PHP has strict types for sure), it needs to treat NULL specifically internally.

So could it be this is just an issue for not having psalm being aware for exec() about `@param-out` (or whatever the internal part of that is ) like in your example?

For exec it is exactly where I ran over it in my project. 

And I'm completely new to psalm, so please excuse that I ask that many questions.

> 
> PS: the bot has it's own repo (https://github.com/weirdan/psalm-github-bot/issues) where it can be discussed. Let's not clutter \@muglug's inbox with off-topic messages.

Now you distracted me a bit.  Filed https://github.com/weirdan/psalm-github-bot/issues/128 and was able to reproduce.

**Comment by weirdan** [comment]
I think Psalm should take callmap prefixes into account, and allow any type on `&$w_`-prefixed parameters.

**Comment by muglug** [comment]
This no longer errors
