### ISSUE TITLE
Psalter: structured array with space in index

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#3232]
Hi,

For the following code:

```php
/**
 * @return int[]
 */
function a(): array{
    return ['a b'=>0];
}
```

If we run the command  `vendor\bin\psalm --alter --issues=all`

Psalter will transform the docblock into:
```php
/**
 * @return int[]
 *
 * @psalm-return array{a b: int}
 */
```

However, this kind of notation is not allowed, and psalm will then flag an error:
`
ERROR: InvalidReturnStatement - test.php:15:12 - The inferred type 'array{a b: int(0)}' does not match the declared return type 'array{ab: int}' for a (see https://psalm.dev/128)
    return ['a b'=>0];
`

I guess Psalter could skip the detailed "@psalm-return" when this happens

Thanks

**Comment by muglug** [comment]
Yeah, Psalm should format this with quotes.

**Comment by muglug** [comment]
Should be fixed now!
