### ISSUE TITLE
Custom Iterator causes mixed key in foreach loop

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#3234]
Here is an [example](https://psalm.dev/r/e355f22569) with a `MixedArgument` that should be understood to be an int. Initially I tried this without the `@implements` annotation above the class with the same results, then I tried adding that annotation to see if it would help. Either way the result are the same, so I'm not sure if this example is better with or without that annotation. I guess it would be ideal if Psalm knew the key was an int based on my custom return type for the `key()` method, but if the only way Psalm can know this is based on the `@implements` iterator key type that would also be good.

**Comment by muglug** [comment]
The link you pasted doesn’t work

**Comment by still-dreaming-1** [comment]
Oops. Updated it.
