### ISSUE TITLE
Checks for missing return types of magic methods, as well as my own methods prefixed with a double underscore

### ISSUE THREAD

**Issue by mkamranpk** [vimeo/psalm#3236]
https://psalm.dev/r/9bb946286a

I expect Psalms to check and report missing return types of magic methods, as well as my own methods prefixed with a double underscore (e.g. `__my_cool_method()`). I saw at https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php#L110 and noticed code which skips everything that starts with a double underscore. I locally changed it so it checks all the magic methods that actually return a value or my custom methods that begin with a double underscore.

My question is, is there a conscious design decision behind that logic or is this something that can be qualified as a bug? If it is a bug, I can submit my changes as a PR.

Thanks.

**Comment by muglug** [comment]
I think double underscores are pretty much only used for magic methods in the vast majority of PHP code, and magic methods are deliberately omitted from method usage checks by Psalm, so I don't consider this a bug.

**Comment by mkamranpk** [comment]
Thanks for the reply Matt. Sounds good, but why does Psalm deliberately
ignores the magic methods? May I know the reasoning behind this? Thanks.

**Comment by mkamranpk** [comment]
@muglug would be awesome if you can please respond to my question above: why does Psalm deliberately ignores the magic methods? May I know the reasoning behind this? Thanks.

**Comment by muglug** [comment]
Having thought about it a bit, there's no great reason (except for `__destruct` and `__clone` which are basically impossible to catch

**Comment by mkamranpk** [comment]
You are awesome @muglug - Thanks!
