### ISSUE TITLE
PossiblyUndefinedGlobalVariable

### ISSUE THREAD

**Issue by m4p1e** [vimeo/psalm#3245]
i have a  code snippet like that
```php
<?php
/**@var mixed*/
$a=I();
/**@var mixed*/
$b=I();
$where['post_type']=array($b=>$a,array('exp','IS NULL'),'OR');
```
its will show error  **Possibly undefined global variable $where, first seen on line 6**
i think php allow does it that way. and i tracked the type inference in psalm, when it finished analysis, `the context->var_in_scope` show that :
```
array(
"$argv"=>Psalm\Type\Union,
"$argc"=>Psalm\Type\Union,
"$a"=>Psalm\Type\Union,
"$b"=>Psalm\Type\Union,
"$where"=>Psalm\Type\Union,
)
```

why there is not "$where['post_type']" in the context scope?

**Comment by m4p1e** [comment]
https://psalm.dev/r/ed3124e0b3

**Comment by m4p1e** [comment]
https://psalm.dev/r/2641e794f7

**Comment by muglug** [comment]
PHP allows it, but it's an anti-pattern that no other language permits.

Please instead do

```php
<?php
$a = 1;
$b = 2;
$where = ['post_type' => [$a => $b]];
```
