### ISSUE TITLE
Errors in overwritten stub reported for function that overwrites

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#3249]
When I have stub:

```
/**
 * @param string $arg hello
 */
function some_test( $arg ) {
}
```

but then declare this function in my real code (e.g. bc in original code the stubbed function is wrapped in function_exists or whatever) like:
```
/**
 * @param string $arg hello
 *
 * @return string
 */
function some_test( $arg ) {
    echo $arg;
}
```

Then psalm tells me:
MissingReturnType

bc in the stub there is no return type specified

Since the return type is specified in the "real" function, this is incorrect.

**Comment by kkmuffme** [comment]
no, bc this requires setting a stub in the config file which isn't possible on psalm.dev

**Comment by muglug** [comment]
@kkmuffme could you reproduce in a separate repo?

**Comment by kkmuffme** [comment]
@muglug you can literally just copy the code I posted in OP in a test.php and stubs.php then you will get the issue.

If you still want it, I can create a zip for it though

**Comment by muglug** [comment]
Even better: create a PR with a test that reproduces the bug (there are a bunch of stub tests in `StubTests.php`
