### ISSUE TITLE
TypeDoesNotContainType for globals

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#3252]
$var does contain true (actually: is always true in this example), so TypeDoesNotContainType is incorrect.

https://psalm.dev/r/deede8edb1

If you don't want to fully fix this, could you perhaps completely disable "TypeDoesNotContainType" for globals, as most cases reported are wrong atm.

**Comment by muglug** [comment]
Add a `@global` docblock there to fix: https://psalm.dev/r/58778c8162
