### ISSUE TITLE
What is the default errorLevel?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#3253]
https://psalm.dev/docs/running_psalm/error_levels/

What's the default value if we don't specify this in xml? Couldn't find it anywhere in docs

**Comment by orklah** [comment]
Since version 3.9.0, Psalm will determine what is the optimal level for you:
https://github.com/vimeo/psalm/releases/tag/3.9.0

> When you run --init in the latest version it will scan your project to figure out the most appropriate starting level (here's an exhaustive list of all the error levels, and what they mean: https://psalm.dev/docs/running_psalm/error_levels/).

**Comment by muglug** [comment]
Yup, as above!

**Comment by kkmuffme** [comment]
@muglug sorry, but this isn't correct. when I set errorLevel="1" in my psalm.xml I get a lot more errors reported than when I leave out errorLevel from the .xml alltogether.

So what value is it using if I do not specifc an errorLevel in my psalm.xml? (= my initial question)
