### ISSUE TITLE
Suggest to remove unmatched issueHandlers

### ISSUE THREAD

**Issue by williamdes** [vimeo/psalm#3262]
`<LessSpecificReturnType errorLevel="info" />` I had added some ignore errors and they got unused.

I would suggest that like phpstan has you add something to report the unmatched issueHandlers
Like I did on https://github.com/phpmyadmin/phpmyadmin/pull/16100/commits/29bbf03c22cf3d0a8dbf198b8115f93710993bd8

And 2nd possible feature: suggest to the user to make the rule file specific if it hits only x files
So the user can stop propagating error y on more files than x without knowing it

Thank you for the tool, I am adding it to phpMyAdmin dev tools !
https://github.com/phpmyadmin/phpmyadmin/pull/16100

**Comment by williamdes** [comment]
Hi @muglug 
Do you think this feature would be usefull ?

**Comment by robchett** [comment]
Unused issue handler PR added in https://github.com/vimeo/psalm/pull/10341.

It won't suggest narrowing the list of files/directories but I think it could fairly easily be expanded to do so by breaking up the issue handler into multiple when parsing them from the XM.

**Comment by weirdan** [comment]
Fixed, as per above.
