### ISSUE TITLE
@mixin doesn't recognise @property on mixed in class

### ISSUE THREAD

**Issue by brendt** [vimeo/psalm#3263]
Laravel has a concept op "model resources" which wrap around model classes. These classes implement `__get` and `__call` to proxy property and method calls to the underlying model. To goal of these classes is to transform a model to eg. a JSON representation for API calls.

In general, you'd add an `@mixin` docblock on all these resources, eg:

```php
/** @mixin \App\Context\Product\Types\Event\Models\Event */
class EventGeneralCardResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'name' => $this->name,
        ];
    }
}
```

This allows PhpStorm to know that `$this->name` actually refers to the property `$name` on the `Event` model.

Psalm however seems to not recognise this:

```
ERROR: UndefinedThisPropertyFetch - app/Http/Staff/Resources/Product/EventGeneralCardResource.php:13:23 - Instance property App\Http\Staff\Resources\Product\EventGeneralCardResource::$name is not defined (see https://psalm.dev/041)
            'name' => $this->name,
```

**Comment by brendt** [comment]
https://psalm.dev/r/970d1bd2e9

**Comment by brendt** [comment]
It turns out that the issue only happens when the mixed in class uses `@property`. It does work when the property is defined on the class itself.

The model definition is generated with the ide helper though, so you cannot change that.

**Comment by muglug** [comment]
Yeah, `@property` tags should also be inherited with `@mixin`

**Comment by mr-feek** [comment]
@brendt would love a PR to the laravel plugin for resource support!

**Comment by brendt** [comment]
I'm new to this, but I'm happy to dive into this. Any pointers where to start?
