### ISSUE TITLE
Return type inference for generators

### ISSUE THREAD

**Issue by kelunik** [vimeo/psalm#3268]
https://psalm.dev/r/f6160f23ad

Follow-up for https://github.com/vimeo/psalm/issues/3257#issuecomment-621002517.

**Comment by weirdan** [comment]
Psalm doesn't infer return types for functions, so why would generators need to be special-cased?

The only exception I'm aware of is closure type inference, and Psalm does have problems with generator closures: https://psalm.dev/r/bdde9a61fb

I think both of the cases (with and without the return type) should be accepted, but return type inference for functions would be inconsistent.

**Comment by kelunik** [comment]
I only care about closures, so that's entirely fine with me.

Your example works fine with #3269.

**Comment by kelunik** [comment]
@muglug Thanks! <3

I had to add two suppressions for `Amp\coroutine`, but tests show it's working fine.

https://github.com/amphp/amp/commit/17e2c2344c42c39c6e834c3d50cc2416a9cfc202
