### ISSUE TITLE
Uncaught "this is a bad place" analyzing nested array assignment

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#327]
This seems related to `$current[1][] = $value` in foreach, as well as $current being null to begin with.

Expected: An issue type is emitted, or this is analyzed without issues.
Observed: Uncaught InvalidArgumentException 

```php
<?php
/**
 * Stripped down version of a function to partition an array based on a callback.
 */
function partition(array $arr) : array {
    $partition = [];
    $empty = true;
    $current = null;
    foreach ($arr as $a) {
        // The if branch can be removed, but then the code wouldn't make sense
        if ($empty) {
            $empty = false;
            $current = array(0, array($a));
        } else {
            $current[1][] = $a;  // <-- This line seems to cause the exception.
        }
    }
    return $partition;
}
```

**Comment by TysonAndre** [comment]
Replacing the `throw` with `return Type::getMixed();` is a potential workaround.

**Comment by muglug** [comment]
Simpler example:

```php
$a = null;
$a[0][] = 1;
```

I'll fix momentarily

**Comment by muglug** [comment]
I've also introduced a `PossiblyNullArrayAssignment` issue that'll come in handy if you have some sort of object that implements `ArrayAccess`, and you don't want to be assigning array keys on its `null` alternate
