### ISSUE TITLE
Extra space before @template breaks parsing

### ISSUE THREAD

**Issue by githoober** [vimeo/psalm#3270]
I have the following hierarchy of interfaces and classes:

```
<?php
interface I {}

class A implements I {}

/** @template T of I */
interface IFactory {
    
    /** @return T */
    public function create(): I;
}

/** @template T of I */
abstract class Factory implements IFactory {}

/** @extends Factory<A> */
class AFactory extends Factory {
    public function create(): I
    {
        return new A();
    }
}

class AService {
    public function use(A $a): void {}
}

$factory = new AFactory();
$service = new AService();

$a = $factory->create();

$service->use($a);
```

[Here](https://psalm.dev/r/fba490675a)
[Another version](https://psalm.dev/r/bb8a8bdf0f)
[One  more](https://psalm.dev/r/ae4842e0db)

The errors are:
```
Psalm output (using commit 21f4dee): 

ERROR: ArgumentTypeCoercion - 33:15 - Argument 1 of AService::use expects A, parent type I provided
```

No matter what I try I cannot make this setup work. I have a feeling that's impossible. The question is whether it's a design choice, a technical limitation, or a bug.  

Not being able to use psalm for such a hierarchy would be a showstopper for me.

**Comment by andrew-demb** [comment]
You should duplicate template doc and explicit use `@implements`
https://psalm.dev/r/2deb4d5f6a

**Comment by githoober** [comment]
@andrew-demb check this link, it's still now working

https://psalm.dev/r/ae4842e0db

**Comment by andrew-demb** [comment]
@githoober here is fixed snippet https://psalm.dev/r/6233fbb659

**Comment by githoober** [comment]
@andrew-demb I see my mistake. Thanks.

**Comment by weirdan** [comment]
> I see my mistake

Docblock parsing should be space-insensitive, so that's a bug.

@muglug, see this: https://psalm.dev/r/79a9a112b6
There's a double space between `*` and `@template` that causes template to be ignored.
