### ISSUE TITLE
Links to source code

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#3271]
When solving PHPStan issues it's very useful for me to have the ability to open the source code directly from the console output with a click. I achieved that using this [Formatter](https://github.com/grifart/phpstan-oneline/blob/master/src/CompactErrorFormatter.php) with the following configuration:

```
	errorFormatter.compact:
		class: Grifart\PhpstanOneLine\CompactErrorFormatter
		arguments:
			format: "]8;;phpstorm://open/?file={absolutePath}&line={line}\\{path}:{line}]8;;\\\n ↳ {error}\n"
```

Is there any way I could configure psalm similarly?

**Comment by enumag** [comment]
ping @muglug

**Comment by andrew-demb** [comment]
I think we can put logic to report formatters (they inherits from https://github.com/vimeo/psalm/blob/master/src/Psalm/Report.php).

For example - console formatter - https://github.com/vimeo/psalm/blob/d8cd30b34a438e5e980533922fc18bea49bc7402/src/Psalm/Report/ConsoleReport.php#L37-L39

**Comment by enumag** [comment]
Can I configure Psalm to use my custom Report implementation?

**Comment by andrew-demb** [comment]
AFAIK, no you can't.

But we can introduce new option to current report formatter to show file links in IDE-compatible way.

Where formatters instantiated:
https://github.com/vimeo/psalm/blob/4bfdda597efc724e44d89a75dc71adc849140c55/src/Psalm/IssueBuffer.php#L631-L704

**Comment by enumag** [comment]
@andrew-demb One issue is that the link needs to contain an absolute path to the file. `IssueData::$file_name` is relative. How can I get the absolute path in `ConsoleReport`?

**Comment by andrew-demb** [comment]
I don't know codebase so much, but I think we can add argument in `getOutput()` - `string $base_dir` and put to it value from config - `$project_analyzer->getConfig()->base_dir`

**Comment by ostrolucky** [comment]
Here is how to setup iterm2 to do this, although limitation here is that because of hardcoded path, this is viable for single project only:

Preferences -> Profiles - {profileName} -> Advanced -> Triggers (Edit) -> Add:
Regular Expression: `ERROR: \w+ - ([a-zA-Z\/.\d]+):(\d+)`
Action: Make Hyprelink
Parameters: `phpstorm://open?file=/Users/gabriel.ostrolucky/Documents/enrola/project/\1&line=\2`

Done

![Screenshot 2020-05-24 at 14 08 47](https://user-images.githubusercontent.com/496233/82753756-7464bb00-9dc8-11ea-9042-d1b2efdf27c9.png)

**Comment by the-toster** [comment]
Hi everyone, I have published little wrapper for psalm, to provide this functionallity - https://github.com/the-toster/psalm-fmt

**Comment by Rarst** [comment]
I noticed this is source and I am tad confused what the `phpstorm` format accomplishes, is `at...` line supposed to be picked up automatically by it (that doesn't happen for me)? Is it meant to be additionally configured with storm somehow?

**Comment by Rarst** [comment]
Ok, from a lot of going in circles it seems it needs to be an _absolute_ path to get recognized by storm, see https://youtrack.jetbrains.com/issue/IDEA-154439

**Comment by the-toster** [comment]
For me it works with relative path, but, maybe this related to psr-4 configuration (`lounge-eloquent-connector` is a namespace root):
![изображение](https://user-images.githubusercontent.com/22966096/92582463-a9265080-f299-11ea-8d55-8f9ccad86cfe.png)

**Comment by Rarst** [comment]
I couldn't make it work with relative no matter what (output a bunch of paths in every way possible) and same complaints on YouTrack issue. Absolute is probably most foolproof here between projects/OSes.

**Comment by enumag** [comment]
This isn't solved. Even when using `vendor/bin/psalm --output-format=phpstorm`, there is no link to source code to be clicked in the output.

**Comment by Rarst** [comment]
@enumag do you see the format change from default? To double check, are you running it in _PhpStorm_'s own terminal?

The format doesn't output _actual link_ (those aren't commonly clickable in terminals anyway), but the way it's structured triggers Storm's recognition of code location and it linkifies it.

Here is how it should work:
![psalm-phpstorm-clickable-link](https://user-images.githubusercontent.com/737584/93494609-e2a03100-f915-11ea-8610-b7c620be0efd.png)

**Comment by enumag** [comment]
Yes, I'm usin PhpStorm terminal.

PhpStorm terminal does support clickable links now (though they're only clickable while holding ctrl). I personally did some lobbying to have them implement it.

I was never interested in having the terminal recognize location. First that requires absolute paths which is useless. Also it doesn't work reliability at all. It seems it works for you on windows but for me on Ubuntu it does not.

See #4204. I implemented actual links there.

**Comment by ostrolucky** [comment]
Yeah absolute links without having a way to remap it is not very useful, this stuff is nowadays running in some sort of VM, so phpstorm will not recognize it

**Comment by Rarst** [comment]
> PhpStorm terminal does support clickable links now

Though does not seem to support `phpstorm://` ones for me when I tried...

> I was never interested in having the terminal recognize location. First that requires absolute paths which is useless. Also it doesn't work reliability at all. It seems it works for you on windows but for me on Ubuntu it does not.

Gotcha! Your PR seems to use absolute path as well though?

**Comment by enumag** [comment]
> Though does not seem to support `phpstorm://` ones for me when I tried...

Interesting. Can you try `idea://`?

> Gotcha! Your PR seems to use absolute path as well though?

You need absolute path int the link itself. But the text of the link can be anything - personally I'd use path relative to `composer.json` but couldn't find such path in the `IssueData` object. If you have an idea how to get that path, please let me know.

**Comment by Rarst** [comment]
> Interesting. Can you try idea://?

Nope, doesn't work either. Regular `http://` does (doesn't require ctrl for me btw, just a clickable link). Cross-platform implementation differences maybe...

**Comment by hgraca** [comment]
Any idea how to map the paths from inside the container to outside the container?
