### ISSUE TITLE
How to annotate @return type depending on argument count [func_num_args()]

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#3273]
Laravel has a [`response()` helper function](https://github.com/laravel/framework/blob/100dc5efc21f920e44bccc2e58366d60e882986d/src/Illuminate/Foundation/helpers.php#L737-L754):

* `response()` returns a `ResponseFactory` object
* `response('Hello world')` returns a `Response` object

Does Psalm currently support annotating this `@return` type depending on the argument count? [Conditional types](https://psalm.dev/docs/annotating_code/type_syntax/conditional_types/) don't seem to support this.

Here's a derived example:
https://psalm.dev/r/927336a62d

**Comment by caugner** [comment]
Here's a closer example:

https://psalm.dev/r/bd04a5ea2a

**Comment by weirdan** [comment]
You don't need argument count as return type here depends on the parameter type (literal empty string in this case): https://psalm.dev/r/306cc1e212

**Comment by caugner** [comment]
> You don't need argument count if you can ignore the case of `return('')` not returning the factory as return type then may depend on the parameter type (literal empty string in this case): https://psalm.dev/r/306cc1e212

Good idea, but unfortunately that workaround only works for explicit strings, not for string parameters:
https://psalm.dev/r/cd6d14ee01

**Comment by mr-feek** [comment]
@caugner I assume this is in a stub file then yeah? I think you might be able to get away with declaring the parameter string|null, and then checking if it's a string. 

I did something similar for laravel factories https://github.com/mr-feek/psalm-plugin-laravel/pull/1/files

Would love to have you PR whatever you have so far against the laravel plugin and we can get it over the finish line!

**Comment by muglug** [comment]
HMMMMMM

What if conditional return types supported

`($argc > 1 ? string : int)`

That wouldn't be too hard to add to the parser, I don't think

**Comment by caugner** [comment]
> HMMMMMM
> 
> What if conditional return types supported
> 
> `($argc > 1 ? string : int)`
> 
> That wouldn't be too hard to add to the parser, I don't think

Sounds like a good solution to me!

**Comment by muglug** [comment]
I made the solution a little more conservative – `$argc` already has a meaning, so I used `func_num_args()` instead:

`(func_num_args() is 0 ? int : string)`

**Comment by caugner** [comment]
@muglug Thank you for this great feature and the rapid implementation!

**Comment by mr-feek** [comment]
Awesome, this will be helpful for me too! Thanks @muglug
