### ISSUE TITLE
[bug] asserted type on property ignored in function call

### ISSUE THREAD

**Issue by ygottschalk** [vimeo/psalm#3275]
https://psalm.dev/r/f099f3f912

**Comment by ygottschalk** [comment]
as seen, type is correctly narrowed, still there is a `PossiblyNullArgument` emitted

**Comment by weirdan** [comment]
Use `@psalm-assert-if…`: https://psalm.dev/r/eb2b246c08
Usually, `@psalm-` is just a prefix that you can omit, but not for `@psalm-assert`.
