### ISSUE TITLE
[Enhancement] Support for "static mixins"

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3278]
👋 I have come across the following proxying code pattern in Laravel quite a bit. I have been struggling to inform Psalm of it.

https://psalm.dev/r/a2d6eb819f

Are there any solutions right now out of the box besides using `@mixin` for the main methods, and then manually adding `@method static ...` annotation for the rest? 

-------

Here are two ideas to solve this  in psalm that have come to mind:

- new class level annotation ala `@mixin static Mixin`

```php
/**
* @mixin MyMixin
* @mixin static MyMixin
*/
class Foo {}
```

- allow `@mixin Mixin` scope annotation over `__callStatic` method implementation

```php
/**
* @mixin MyMixin
*/
class Foo {
    /**
    * @mixin MyMixin
    */
    public function __callStatic {}
}
```
Proxying in `MethodReturnTypeProviders` is another solution, however that gets quite complex

**Comment by muglug** [comment]
How does Laravel annotate this, if at all?

**Comment by mr-feek** [comment]
Solved via a plugin described here https://github.com/vimeo/psalm/issues/3336
