### ISSUE TITLE
Strange behavior when string callable is used as a fallback

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#3285]
Without a type hint works fine: https://psalm.dev/r/d6df24af07

With a type hint produces an error: https://psalm.dev/r/9bbc5109cc

**Comment by vudaltsov** [comment]
The code itself works fine: https://3v4l.org/lqsL8

**Comment by weirdan** [comment]
Observations: 
* it's not caused by function being named `void()`
* trying to work this around with assignment and assert causes another issue: https://psalm.dev/r/af89844686

**Comment by orklah** [comment]
This was fixed.

There is still an error in the snippet but it's legit, as Psalm can't know the callable in $handler will return void

**Comment by vudaltsov** [comment]
Cool, thank you!
