### ISSUE TITLE
Ignore subclasses of <ignoreExceptions>

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#3286]
I added `Error`, `LogicException` and `RuntimeException` to the `<ignoreExceptions>` because they are unchecked. I assumed that `InvalidArgumentException`, `OutOfBoundsException` and many others will also be ignored, since they are subclasses. Instead Psalm doesn't take inheritance into account, so I had to list 41 exception instead of 3 and the my list grows along with the project.

**Comment by mr-feek** [comment]
Isn't this what `classAndDescendants` is for?

**Comment by vudaltsov** [comment]
@mr-feek , thank you so much! I didn't know about this tag.

**Comment by mr-feek** [comment]
I just stumbled across it. Doesn't look like it's documented!
