### ISSUE TITLE
What is the default errorLevel?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#3288]
Followup to https://github.com/vimeo/psalm/issues/3253 bc both comments dont seem to be right:

when I set errorLevel="1" in my psalm.xml I get a lot more errors reported than when I leave out errorLevel from the .xml alltogether.

What value is it using if I do not specify an errorLevel in my psalm.xml?

**Comment by orklah** [comment]
Do you mind posting what values you have in 
https://psalm.dev/docs/running_psalm/configuration/#totallytyped
and
https://psalm.dev/docs/running_psalm/configuration/#reportmixedissues
if any?

**Comment by kkmuffme** [comment]
I have neither in my psalm.xml

**Comment by orklah** [comment]
Hum, weird.

Does every new issue you have when you delete errorLevel begins by "Mixed"?

Do you have anything specific in issueHandlers tag?

**Comment by kkmuffme** [comment]
>Does every new issue you have when you delete errorLevel begins by "Mixed"?

Yes, seems like it.

>Do you have anything specific in issueHandlers tag?

Here's my full psalm.xml:

```
<?xml version="1.0"?>
<!-- https://psalm.dev/docs/running_psalm/configuration/#coding-style -->
<psalm
	totallyTyped="false"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="https://getpsalm.org/schema/config"
	xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
	resolveFromConfigFile="false"
>
	<projectFiles>
		<file name="error-handler.php" />
		<directory name="source" />
		<directory name="assets" />
	</projectFiles>

	<issueHandlers>
		<ForbiddenCode errorLevel="suppress" />
		<ForbiddenEcho errorLevel="suppress" />
		<InvalidGlobal errorLevel="suppress" />
		<MissingDependency errorLevel="suppress" />
		<PossiblyUndefinedVariable errorLevel="suppress" />
		<UndefinedVariable errorLevel="suppress" />
		<UndefinedClass errorLevel="suppress" />
		<UndefinedConstant errorLevel="suppress" />
		<UndefinedFunction errorLevel="suppress" />
		<UndefinedGlobalVariable errorLevel="suppress" />
		<UnresolvableInclude errorLevel="suppress" />
		<RedundantConditionGivenDocblockType errorLevel="suppress" />
		<MissingClosureParamType errorLevel="suppress" />
		<MissingClosureReturnType errorLevel="suppress" />
		<UnusedParam errorLevel="suppress" />
	</issueHandlers>
</psalm>
```

**Comment by orklah** [comment]
The first flag in your file is `totallyTyped="false"` which is a deprecated flag who means "Don't show Mixed issues".

When `errorLevel` is explicitly mentionned, it seems it has a higher priority than `totallyTyped` and it displays these errors anyway.

Can you try to drop this flag (and replace it by reportMixedIssues if needed)?

**Comment by kkmuffme** [comment]
Ah thanks so much.

Changed now from `totallyTyped="false"` without error level specified to `reportMixedIssues="false"` with `errorLevel="1"` and I get the same errors as before.
