### ISSUE TITLE
Loss of a generic type when iterating over an IteratorAggregate instance

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#3289]
https://psalm.dev/r/899267c919

**Comment by weirdan** [comment]
Looks fairly edge-casey to me. In practice I would expect `handle()` to be generic function, as it handles generic objects: https://psalm.dev/r/09d623f767

**Comment by muglug** [comment]
It comes down to the difference between https://psalm.dev/r/1b8723c305 and https://psalm.dev/r/f1cd0114c1 – they should both be treated the same
