### ISSUE TITLE
Detect code used in PHPDocs (annotations)

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#3291]
In Symfony, one can create custom annotations that get injected automatically into Request; very useful feature to avoid boilerplate code like in this example: https://github.com/strictify/coding-challenge/blob/symfony-4/src/Controller/Product/CreateAction.php#L17

It's usability goes way above this but I put the simplest example. Here the ``__invoke`` will receive submitted form, exact form class is defined via annotations and I have static analysis via stub of ``FormInterface``.

---

The trouble is that such code is reported as unused: https://psalm.dev/r/ba40c18e2d (controller is irrelevant and ignored via psalm.xml)

Is it possible to have it detected as used, like other classes? I guess that with native attributes in PHP8 it would be simpler but December is still far away.

**Comment by weirdan** [comment]
Possible, with a plugin. PHPUnit plugin does something similar, where it marks methods and classes as used (all test classes and test methods are marked as used, and all referenced data providers are marked as well).

* https://github.com/psalm/psalm-plugin-phpunit/blob/master/src/Hooks/TestCaseHandler.php#L122
* https://github.com/psalm/psalm-plugin-phpunit/blob/master/src/Hooks/TestCaseHandler.php#L154
* https://github.com/psalm/psalm-plugin-phpunit/blob/master/src/Hooks/TestCaseHandler.php#L199

**Comment by muglug** [comment]
Yeah, this is a candidate for https://github.com/psalm/psalm-plugin-symfony

**Comment by zmitic** [comment]
Isn't this something that should be in psalm itself? doctrine/annotations is not Symfony specific.

**Comment by weirdan** [comment]
Considering current votes on [Attributes RFC](https://wiki.php.net/rfc/attributes_v2) we may soon have no need for `doctrine/annotations`.

**Comment by zmitic** [comment]
@weirdan I agree but as I mentioned, December is still far away. And it will take some time for libs to catch up and support/require PHP8.

But I still think this should go in the core; plugin is not that useful in S4 and above.

**Comment by weirdan** [comment]
> But I still think this should go in the core

Doctrine annotations (DA for short) are not a part of PHP. An argument can be made that PHPDoc docblocks aren't either, but pretty much everyone in PHP world uses them, unlike DA. 

This alone makes me think support for DA does not belong to Psalm core and should rather be handled in a plugin of some sort, but there are technical obstacles as well. When I looked into supporting DA last time for doctrine plugin, there were no static-analysis-friendly parsers available.
`doctrine/annotations` is based on Reflection, which means you need to *actually execute* the inspected code to use that parser - and it causes all kinds of pain in SA context. 

@Ocramius once vaguely [mentioned on Twitter](https://twitter.com/Ocramius/status/1224668519524130816) he might be looking into creating a better parser one day, but I don't know if it progressed past the idea phase.

>  plugin is not that useful in S4 and above

I think PRs making it more useful for modern Symfony would not meet much resistance :smile:
