### ISSUE TITLE
Feature request: classes used  through their interface should not be marked as unused

### ISSUE THREAD

**Issue by githoober** [vimeo/psalm#3293]
```<?php
interface I {};

class C implements I {};

class A {
    public function useI(I $i): void {
        $name = get_class($i);
        echo "HERE is $name\n";
    }
}

$a = new A();
```

The dead code detection produces the following errors:
```
ERROR: UnusedClass - src/index.php:4:7 - Class C is never used (see https://psalm.dev/075)
class C implements I {};


ERROR: UnusedClass - src/index.php:6:7 - Class A is never used (see https://psalm.dev/075)
class A {
```

The class C in this example is used through its interface I. This approach is widely utilized in applications based on abstractions/contracts, i.g. onion architectures, domain-driven design, etc.

It would be very helpful to detect classes usages through their interfaces and thus not to report them as not used.

**Comment by muglug** [comment]
> The class C in this example is used through its interface I

It still has to be initialised _somewhere_ though – where is that happening?

**Comment by githoober** [comment]
Yes, it is, and IMO is irrelevant.

**Comment by mr-feek** [comment]
I am 👎🏼on this feature request. Just because a class implements an interface does not mean it is used.

**Comment by githoober** [comment]
I think I did a poor job explaining myself.

* The class A has a reference to the interface I. 
* The class A is instantiated for example by a DI container. 
* With the request feature enabled via an extra option --ignore-contract-implementations, psalm would not mark any implementations of the interface I as not used because they are used through the class A.

**Comment by weirdan** [comment]
> The implementations of I are also instantiated by the same DI container (This is IMO irrelevant as it cannot fix our issue). There are no any references to these classes in the code!

There's a decision made by DI container to use specific implementation of `I`, and Psalm needs to know that. There could be a factory instantiating `A`, or a configuration mentioning `A` or some convention telling DIC to prefer `A implements I` over `B implements I`. How to supply this data to Psalm heavily depends on how that decision is made. So this is actually most relevant.

**Comment by muglug** [comment]
Yes – there has to be information somewhere that specifies what classes are actually to be instantiated – maybe it's in XML configuration, maybe it's in code – but that data needs to be sent to Psalm somehow (presumably via a plugin), otherwise it won't be able to connect the dots.

**Comment by githoober** [comment]
@muglug our use case is creating libraries that become part of applications. These libraries do not have a DIC or anything else that creates class instances. 

IMO, psalm can support a mode where it calculates usage purely based on relations between classes.

**Comment by muglug** [comment]
In your example code you had `class C implements I {}`. For that code to be useful, `C` has to be instatiated _somewhere_.

Where is it instantiated, and what decides how that instantiation happens?

**Comment by zmitic** [comment]
I just noticed this as well. In my case, I am using Symfony DIC to inject iterable of ``ViewFactoryInterface`` into ``ViewFactory`` service.

All of them can be seen in this screenshot:

![image](https://user-images.githubusercontent.com/1964158/87927900-39a79800-ca84-11ea-8c5a-ae0b28b3b1d4.png)


Main class (ViewFactory) is used everywhere and it is not a problem. What is does is strategy pattern i.e. delegate the job of doing something to some of other classes.

But all of them are reported as unused, even though their interface is used in 

```php
    /**
     * @param iterable<ViewFactoryInterface> $factories
     */
    public function __construct(iterable $factories)
    {
        $this->factories = $factories;
    }
```

If of any information, unused constructors are not a problem:

```xml
        <PossiblyUnusedMethod>
            <errorLevel type="suppress">
                <referencedMethod name="*::__construct"/>
                <directory name="src/Service"/>

```

**Comment by dbalabka** [comment]
@githoober  IMO any class must be used somewhere if we are building an application. In the case of libraries, you should suppress this issue case-by-case (see [@psalm-suppress](https://psalm.dev/docs/annotating_code/supported_annotations/#:~:text=non%2Dprefixed%20counterpart.-,%40psalm%2Dsuppress%20SomeIssueName,applying%20to%20the%20following%20statement.&text=%40psalm%2Dsuppress%20all%20can%20be,instead%20of%20listing%20them%20individually.))

Or you should disable this check-in project configuration of your library.
