### ISSUE TITLE
[Bug] Parent generic mixins aren't propagated down to children

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3294]
Following up on https://github.com/vimeo/psalm/pull/3280#issuecomment-622296063

Generic mixins declared on parent classes are not inherited by children.
https://psalm.dev/r/b46088c1bf

Normal mixins that aren't generic seem to be inherited without problem. From the digging I did, this seems to possibly be an issue with storing generic mixins in classlike storage.

**Comment by mr-feek** [comment]
Doing some digging. When a mixin is generic, the parent classlike storage doesn't seem to have a `mixin_fqlcn` set in `Populator`

**Comment by muglug** [comment]
Fixed in 28349c6

**Comment by mr-feek** [comment]
Thanks @muglug !! I was struggling with implementing this
