### ISSUE TITLE
[Bug] Generic Mixins type is lost

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3295]
Clearly I'm having a lot of fun with mixins :) Dang laravel.

https://psalm.dev/r/6852b0cc06

When a mixin tries to denote that it returns an instance of itself, the type specifics are lost. I'm not  sure  if the bug is that `$this` isn't correctly bound to the  mixin instance, or if it is that `self` doesn't include the template params.

**Comment by muglug** [comment]
You can fix with `@return self<T>`: https://psalm.dev/r/519891248d
