### ISSUE TITLE
[Bug] Static does not seem to be correctly bound when a parent class declares a method with generic type

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3296]
https://psalm.dev/r/f9b863e567

**Comment by muglug** [comment]
This can be solved by making the template covariant: https://psalm.dev/r/1d0cc7d224

But the example should still work if `Cheese` is declared final: https://psalm.dev/r/1ffe32a900

**Comment by mr-feek** [comment]
Thanks @muglug !
