### ISSUE TITLE
MissingClosureReturnType issues with @return on container element

### ISSUE THREAD

**Issue by erunion** [vimeo/psalm#33]
I have the following closure, and can't seem to get Psalm to recognize it having a return type:

```php
$container['filesystem'] = function (Container $c) {
    $adapter = new Local('/');

    return new \League\Flysystem\Filesystem($adapter);
};
```

I've tried adding a `/** @return \League\Flysystem\Filesystem */` above it, but it's still throwing an error.

```
ERROR: MissingReturnType - src/Provider/Filesystem.php:18 - Method  does not have a return type
        $container['filesystem'] = function (Container $c) {
```

**Comment by muglug** [comment]
Keeping this open as it's a common use-case, but you can solve it with

```php
$container['filesystem'] =
    /** @return \League\Flysystem\Filesystem */
    function (Container $c) {
        $adapter = new Local('/');

        return new \League\Flysystem\Filesystem($adapter);
    };
```

, the issue being that the assignment docblock is not checked *as well*.

**Comment by muglug** [comment]
Unfortunately it'd be too disruptive to the assignment evaluation system to change this. Closing out.

**Comment by shadowhand** [comment]
This is insanely awkward:

```php
return
/** @return object */
function () {
    return new \stdClass();
};
```

Is there really no better way to define a closure return type?

**Comment by muglug** [comment]
@shadowhand well obviously you could use the `object` typehint in PHP 7.2, but there's also the maybe-slightly-less-awkward

```php
return /** @return object */ function () {
    return new \stdClass();
};
```

Also I think that Psalm should be able to infer the majority of these return types automatically, and that this is generally not a useful message.

**Comment by shadowhand** [comment]
@muglug that's slightly better. Hurts the "line length limit" in some cases though. I would greatly prefer to be able to do:

```php
/** @return object */
return function () { ... };
```
