### ISSUE TITLE
"PHPStan / Psalm / Generics" => "The reference cache must be an array"

### ISSUE THREAD

**Issue by voku** [vimeo/psalm#3300]
I am trying to use the "PHPStan / Psalm / Generics"-Plugin for PhpStorm but I see some error in my local error log. 

unserialize(): Error at offset 552956 of 552960 bytes

⇉ If I look for the file on the filesystem, this file is already deleted, so maybe the plugin is using psalm in a non-optimal way (or it's related to a Java Exception from the Plugin?!), or why do we try to fetch non-existing cache files?

```
UnexpectedValueException: The reference cache must be an array
#5 phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Provider/FileReferenceCacheProvider.php(154): getCachedMethodMemberReferences
#4 phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Provider/FileReferenceProvider.php(402): loadReferenceCache
#3 phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(770): checkPaths
#2 phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/psalm.php(398): require_once
#1 phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/psalm(5): require
#0 Framework/thirdparty/psalm.phar(14): null
```

**Comment by muglug** [comment]
I'm going to close this – Psalm [already has support for PHPStorm via the Language Server Protocol](https://psalm.dev/docs/running_psalm/language_server/#phpstorm), and I'm not going to support third-party solutions (though you're welcome to debug it yourself)
