### ISSUE TITLE
PossiblyUndefinedStringArrayOffset with isset inside a foreach loop and access to the index from outside it

### ISSUE THREAD

**Issue by ste93cry** [vimeo/psalm#3302]
As can be seen in the example below, even though we check that the key is present before using it Psalm is not able to recognize it. Moving the `isset` statement outside of the loop does indeed gets considered. Would it be possible to enhance the analyser to take into account this use-case?

https://psalm.dev/r/1bf136b9ad

**Comment by muglug** [comment]
Sadly I don't think this is something Psalm will be able to detect easily – assertions in loops are hard to depend on in the general case.

This is an alternative version of the same: https://psalm.dev/r/962fefb413

**Comment by muglug** [comment]
The explicit version works though: https://psalm.dev/r/6564540681

**Comment by ste93cry** [comment]
>The explicit version works though

Indeed it works, but it would be nicer if the formal worked too because if you need to check a lot of keys writing a `if` statement for any of them is a lot of code to maintain
