### ISSUE TITLE
@psalm-assert(-*) fails on static property fetch

### ISSUE THREAD

**Issue by Lctrs** [vimeo/psalm#3307]
https://psalm.dev/r/beaaafabe7

Notice that it does work on non-static property fetch.

**Comment by muglug** [comment]
It's not currently documented to work there – adding would be some sort of addition to the syntax.

**Comment by weirdan** [comment]
@muglug any hints on the implementation? Psalm seems to know how to narrow types of class variables in the context of a method, so would it be as easy as just attaching assertions to variables in scope?
