### ISSUE TITLE
Emit FailedTypeResolution in more scenarios

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#331]
General idea: It should be emitted if a later condition is implied by a previous condition. Invalidation logic and assertion tracking from PsalmParadoxicalCondition can probably be reused.

Example conditions:

```php
$a = rand(0, 10) > 5;
$b = rand(0, 10) > 5;
if ($a && $b && $a) {}

$c = rand(0, 10) > 5 ? "hello" : 3;
if (is_int($c) && is_numeric($c)) {}

$x = rand(0, 10) > 5 ? new stdClass : null;
if ($x instanceof stdClass && $x) {}
```

**Comment by muglug** [comment]
I removed the last one

```php
// The combination of the two assertions on $str:
if (!is_string($str)) { throw new RuntimeException("fail"); }
if (is_string($str)) { ...}
```

because Psalm already catches it as `FailedTypeResolution`. Indeed, all of these _should_ be `FailedTypeResolution`. It's not as specific, but does the job.

**Comment by muglug** [comment]
I guess `RedundantCondition` makes far more sense than `FailedTypeResolution`

**Comment by muglug** [comment]
Oops: https://github.com/vimeo/psalm/blob/fd3de443b2e732ab55026017d9156baacb4494a4/src/Psalm/Checker/Statements/Expression/FetchChecker.php#L942

**Comment by muglug** [comment]
Thanks. I won't create a release until I'm confident that related bugs have also been fixed, as this is likely to expose a whole ton of them.
