### ISSUE TITLE
mysqli_stmt::__construct defined wrong in Callmap

### ISSUE THREAD

**Issue by bkdotcom** [vimeo/psalm#3310]
https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/CallMap.php

`'mysqli_stmt::__construct' => ['void', 'query='=>'string'],`

should be something like 
`'mysqli_stmt::__construct' => ['void', 'link'=>''mysqli',  'query'=>'string'],`

ie 2 params... the first param is not a string

I'm getting two errors
> Too many arguments for mysqli_stmt::__construct - expecting 1 but saw 2
> Argument 1 of mysqli_stmt::__construct expects string MyExtendedMysqliClass provided

https://www.php.net/manual/en/mysqli-stmt.construct.php

**Comment by bkdotcom** [comment]
> Hey @bkdotcom, can you reproduce the issue on https://psalm.dev ?

I see the issue in the codebase

**Comment by weirdan** [comment]
https://psalm.dev/r/a86e23e82c

**Comment by weirdan** [comment]
@bkdotcom would you mind to PR that change?

**Comment by bkdotcom** [comment]
https://github.com/vimeo/psalm/pull/3315
