### ISSUE TITLE
Allow type&otherType[]

### ISSUE THREAD

**Issue by dereuromark** [vimeo/psalm#3316]
I would like to propose allowing the special semantic structure of e.g.

    \Generator&\DateTimeInterface[]

> InvalidDocblock - src/Core/PluginCollection.php:331:5 - Intersection types must be all objects or all object-like arrays

Similar issues with the `\Generator|\DateTimeInterface[]` syntax, where here we could indeed argue that this could mean either Generator or array collection of this interface.

What both however mean usually is the collection of a class/interface inside this specific object.
So an array isn't even returned in either case (or valid return value for that matter).

The reason for the `X&Y[]` syntax:
Most IDEs (even latest phpstorm 2020.1.1) do not understand the newer generic typehints:

    \Generator<\FQCN>
    iterable<\FQCN>

They do not work on the iteration of the return value, and inline annotations are necessary everywhere.

We would like to not have to use inline annotations while still allowing the static anal. and the IDE to understand the collection object X of iterable type Y.
As the first example using `&` would not make sense anyway, maybe it could be used to express this semantic construct - and allow us to use the benefits without having to silence either the tooling (psalm) or find other workarounds.

What do you think?

**Comment by dereuromark** [comment]
https://psalm.dev/r/c266b6e215 some examples

**Comment by dereuromark** [comment]
See (not working)

![iterator_1](https://user-images.githubusercontent.com/39854/81324052-b1c20c80-9096-11ea-8799-dfda79ff1223.png)

And (working)

![iterator_2](https://user-images.githubusercontent.com/39854/81324057-b38bd000-9096-11ea-828f-4681975f12a3.png)

**Comment by weirdan** [comment]
You can use correct types in `@psalm-param`, `@psalm-return`, etc (PHPStan reads those tags too), and feed those broken types to PHPStorm via `@param`, `@return` and so on: https://psalm.dev/r/8bec242657
