### ISSUE TITLE
Weird issue with templates (cannot think out a better issue name)

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#3317]
https://psalm.dev/r/ee84fa161a

**Comment by mr-feek** [comment]
How does `$var` become a list? I think psalm might be operating as intended here -- `$var` is never turned into a list therefore the inferred type is an int. Though  I do not know the order of operations around what takes precedence -- the actual code vs docblocks

**Comment by someniatko** [comment]
@mr-feek it does not matter how `$var` is used. It is only used for automatic type inference, such that I don't have to type `/** @var */` annotation in the `B` class. You can change my example such that `$this->var = [ $var ];` and see no difference.

**Comment by someniatko** [comment]
Here I did it for you :) https://psalm.dev/r/46b67f810f

**Comment by muglug** [comment]
You can solve this a couple of ways: firstly by adding `@template-covariant` [to the original interface](https://psalm.dev/r/32678b2128), or by using a more general type than `1` (which is a subtype of `int`) when initialising: https://psalm.dev/r/7990805692

**Comment by weirdan** [comment]
As far as I understand, generics as implemented by Psalm are invariant, unless when they are covariant :smiling_imp: : https://psalm.dev/r/32678b2128

**Comment by someniatko** [comment]
@muglug I see. But this means the error message is incorrect though.

**Comment by someniatko** [comment]
@muglug I found variation of this bug, which does not relate to covariance:

https://psalm.dev/r/ee84fa161a

This is closer to what hit me in real code.

**Comment by someniatko** [comment]
I think the issue here is that `/** @template-implements */` annotation does not correctly pass nested template params (i.e. `list<T>`) to the parent, therefore 

IC<T> should become I<list<T>>, however due to the bug psalm treats it as I<T>
