### ISSUE TITLE
ArgumentTypeCoercion class-string vs string?

### ISSUE THREAD

**Issue by bkdotcom** [vimeo/psalm#3318]
ERROR: ArgumentTypeCoercion - .... - Argument 1 of ReflectionClass::__construct expects class-string|object, parent type string(PDO) provided (see https://psalm.dev/193)
            `$ref = new \ReflectionClass('PDO');`

https://psalm.dev/r/a34f8c9dbd

**Comment by andrew-demb** [comment]
Check docs for class-string
https://psalm.dev/docs/annotating_code/type_syntax/scalar_types/#class-string

**Comment by andrew-demb** [comment]
> takesClassName("A"); would trigger a TypeCoercion issue (or a PossiblyInvalidArgument issue if allowCoercionFromStringToClassConst was set to false in your config), whereas takesClassName(A::class) is fine.

**Comment by weirdan** [comment]
Use `PDO::class`: https://psalm.dev/r/a9734cec24 (preferable) or enable `allowCoercionFromStringToClassConst` in your `psalm.xml`

**Comment by bkdotcom** [comment]
@andrew-demb & @weirdan 
Thanks!
