### ISSUE TITLE
Use reference annotations from CallMap.php to determine psalm's treatment of references?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#332]
CallMap.php prefixes parameter names with `rw_` to indicate that the union types of reference parameters are unchanged by a given function.

The upstream source of CallMap.php has the following documentation:

```php
/**
 * Currently, the only prefixes with meaning are 'rw_' (read-write) and 'w_' (write).
 * Those prefixes don't mean anything for non-references.
 * Code using these signatures should remove those prefixes from messages rendered to the user.
 * 1. '&rw_<arg_name>' indicates that a parameter with a value is expected to be passed in, and may be modified.
 *    Phan will warn if the variable has an incompatible type, or is undefined.
 * 2. '&w_<arg_name>' indicates that a parameter is expected to be passed in, and the value will be ignored, and may be overwritten.
 * 3. The absence of a prefix is treated by Phan the same way as having the prefix 'w_' (Some may be changed to 'rw_name'). These will have prefixes added later.
 * ...
 */
'array_push' => ['int', '&rw_stack'=>'array', 'var'=> '', '...vars='=>''],
'socket_select' => ['int', '&rw_read_fds'=>'resource[]|null', '&rw_write_fds'=>'resource[]|null', '&rw_except_fds'=>'resource[]|null', 'tv_sec'=>'int', 'tv_usec='=>'int'],
```

This will avoid the need for multiple special cases such as https://github.com/vimeo/psalm/commit/60c9f1ca96f7c9f5b0009bc6b7f6809836e02d5d (Covered by `rw_`) and possibly `preg_match` (w_)

array_push is more complicated, but ksort/asort probably isn't. This should also help with less frequently used extensions (Collator::asort)

**Comment by muglug** [comment]
Ahh! That makes a lot of sense. But there are few enough of them that I'm happy to just use the overrides I have in place.

**Comment by TysonAndre** [comment]
This isn't exactly
