### ISSUE TITLE
LessSpecificImplementedReturnType when child class overrides static return type through @method

### ISSUE THREAD

**Issue by AegirLeet** [vimeo/psalm#3320]
Sorry for the weird title, not sure how to express this in a title-appropriate amount of characters.

https://psalm.dev/r/2873089463

As you can see, psalm flags `B::foo`'s return type as less specific, even though `B` is final and `B` should therefore be just as specific as the parent's `static`. In `C`, psalm seems to handle this correctly, not complaining about the return type.

So it seems like the `@method` tag in `B`'s DocBlock is handled differently from the actual method in `C`.

**Comment by weirdan** [comment]
Workaround: https://psalm.dev/r/2114576447
