### ISSUE TITLE
type of __DIR__ is not inferred in a class constant

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#3322]
I have a peeeen... https://psalm.dev/r/b73e668896
I have an apple... https://psalm.dev/r/f133ab4d64
Uh https://psalm.dev/r/ce4be3b3b9

**Comment by the-toster** [comment]
Looks like now it fixed, last example produce "No issues!" - https://psalm.dev/r/ce4be3b3b9

**Comment by weirdan** [comment]
I believe it's fixed in #3602

**Comment by someniatko** [comment]
Thank you, guys!
