### ISSUE TITLE
Unable to suppress missing constructor

### ISSUE THREAD

**Issue by SharkMachine** [vimeo/psalm#3331]
![image](https://user-images.githubusercontent.com/7488694/81485507-42931680-9256-11ea-8ada-fbc9c73b0444.png)

Having that @psalm-suppress will not help :<

**Comment by orklah** [comment]
Closing this as not reproduced

**Comment by cseufert** [comment]
I have a simple reproduction here:
https://psalm.dev/r/8ee1efc9c8

**Comment by orklah** [comment]
The suppression should be located above the class: https://psalm.dev/r/c58b371682
