### ISSUE TITLE
False InvalidArrayOffset in latest master

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#3335]
Psalm reports ``InvalidArrayOffset`` error here i.e. doesn't recognize null coalescing operator:

https://psalm.dev/r/0d4e325a34

which is valid code: https://3v4l.org/A2Adh

**Comment by muglug** [comment]
Do you have an example on slightly more realistic code? The code above is clearly a bug.

**Comment by zmitic** [comment]
I double checked my stubs and the problem was in ``@var`` I had to put before to solve some other problem (something about not reading typed property).

That was fixed long ago, I forgot to remove it. My bad, sorry.
