### ISSUE TITLE
[Question] How to proxy a method return type to a generic object?

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3336]
Following on from https://github.com/psalm/psalm-plugin-laravel/pull/52#discussion_r416831998 and https://github.com/vimeo/psalm/issues/3173

Given the following code:

```php
/**
* @template T of Model
*/
class Builder {
    public function where(): array {}
}

class User extends Model {
    public function __call($method, $parameters) {
         return $this->forwardCallTo($this->newQuery(), $method, $parameters);
    }

    public function __callStatic($method, $parameters) {
          return (new static)->$method(...$parameters);
    }
}
```

I am trying to inform Psalm that `User::where()` should return whatever `Builder<User>::where` returns

This is very easy to accomplish for instance methods via `@mixin Builder<User>`, however I am running into trouble documenting this functionality for static calls too.

I've turned to making a plugin since this is getting quite complex, and it is not valid in php to have a method declared as both an instance method and a static method. Here is a chunk of code in the plugin I have so far:

```php
final class EloquentBuilderReturnTypeProvider implements MethodReturnTypeProviderInterface
{

    public static function getClassLikeNames(): array
    {
        return [Model::class];
    }

    public static function getMethodReturnType(StatementsSource $source, string $fq_classlike_name, string $method_name_lowercase, array $call_args, Context $context, CodeLocation $code_location, array $template_type_parameters = null, string $called_fq_classlike_name = null, string $called_method_name_lowercase = null)
    {
        if ($method_name_lowercase === '__callstatic') {
            if (!$source instanceof \Psalm\Internal\Analyzer\StatementsAnalyzer) {
                return Type::getMixed();
            }
            $methodId = new MethodIdentifier($called_fq_classlike_name, $called_method_name_lowercase);

            $fake_method_call = new StaticCall(
                new Name(Builder::class),
                $methodId->method_name,
                $call_args
            );

            $fakeCallReturnType = self::executeFakeCall($source, $fake_method_call, $context);
            return $fakeCallReturnType;
    }

   // this is directly copy pasted from https://github.com/vimeo/psalm/blob/5c511ad95d4153c604660eb6ce05b55b99b5b478/src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMapReturnTypeProvider.php#L230 for now
    private static function executeFakeCall(
        \Psalm\Internal\Analyzer\StatementsAnalyzer $statements_analyzer,
        \PhpParser\Node\Expr\StaticCall $fake_method_call,
        Context $context
    ) : ?Union {
        $old_data_provider = $statements_analyzer->node_data;

        $statements_analyzer->node_data = clone $statements_analyzer->node_data;

        $suppressed_issues = $statements_analyzer->getSuppressedIssues();

        if (!in_array('PossiblyInvalidMethodCall', $suppressed_issues, true)) {
            $statements_analyzer->addSuppressedIssues(['PossiblyInvalidMethodCall']);
        }

        $was_inside_call = $context->inside_call;

        $context->inside_call = true;

        \Psalm\Internal\Analyzer\Statements\Expression\Call\StaticCallAnalyzer::analyze(
            $statements_analyzer,
            $fake_method_call,
            $context
        );

        $context->inside_call = $was_inside_call;

        if (!in_array('PossiblyInvalidMethodCall', $suppressed_issues, true)) {
            $statements_analyzer->removeSuppressedIssues(['PossiblyInvalidMethodCall']);
        }

        $return_type = $statements_analyzer->node_data->getType($fake_method_call) ?: null;

        $statements_analyzer->node_data = $old_data_provider;

        return $return_type;
    }
```

How do I pass the template parameter `T` to the `Builder` fake method call? Is it something to do with `UnionType::replaceTemplateTypesWithArgTypes`?

**Comment by mr-feek** [comment]
friendly ping @muglug if you could give some thoughts here when you have a chance! I'm very close to done the bulk of the support for eloquent, just running into this scenario 🙌

**Comment by mr-feek** [comment]
another bump @muglug ! I'm eager to get this plugin finished so i can reap the full benefits of  psalm!

**Comment by muglug** [comment]
Sorry!

This should be a `PhpParser\Node\Expr\MethodCall`, not a `StaticCall`, and the value of `$context->vars_in_scope['$this']` passed to the fake method call should be a union of type `Builder<User>` – you could just use the `Type::parseString` method to create that union, but it might be better to build it explicitly. Also `$context->self` should be set to `Builder::class`.

Also you'll want to execute `$context = clone $context` before you modify the context for the fake method call so you don't spoil it for later users.

**Comment by muglug** [comment]
BUT I also think Psalm should understand this particular forwarding pattern for `__callStatic`` natively – I'll add something tomorrow (hopefully) that treats this method as a redirect:

```
    public function __callStatic($method, $parameters) {
          return (new static)->$method(...$parameters);
    }
```

**Comment by mr-feek** [comment]
@muglug I'm getting super close, but I must be missing something. After analyzing my fake method call I seem to lose the context of the `User` param value. 

I spent quite some time tracing everything, and `$class_template_params`  seems  to be null, instead of the  value  of `User`. That jumps  out at me as incorrect, any idea?

https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php#L516

This is the area where I seem to lose the context of the template param value. As a result, the return type for my fake method call seems to always be the generic `Model` value, instead of `User`.

Perhaps this has something  to do with the `@return self<TModel>`  docblock, and the `TModel` actual value isn't being used?

Would appreciate any insight you may have! I believe It's a  bit too far into the psalm internals for me to debug any more effectively.

Here's  my  failing test case:
https://github.com/psalm/psalm-plugin-laravel/pull/52/files#diff-d6d4a1c1105a48f07ff520cd5ee460b8R80-R110

**Comment by muglug** [comment]
You're almost there. Change references on `'this'` and `'$this'` to `'builder'` and `'$builder'` respectively and the test passes (you can also remove `$context->self = Builder::class;`).

**Comment by mr-feek** [comment]
wow, i think I actually understand what's going on now. Thanks a lot @muglug , you the man. If you can point me to a way for me to buy you a beer, I will totally do so 😄
