### ISSUE TITLE
Raise an issue if exception is created and not thrown

### ISSUE THREAD

**Issue by DaveLiddament** [vimeo/psalm#3338]
Feature request for a new issue that warns you if you don't throw an instantiated Exception. 

Just wrote some code like this:

```
if (... some check fails ...) {
  new MyException(); // Forgot to throw it!
}
```

Example code with comments on where I think issue should be raised:

https://psalm.dev/r/cf94aa5993

**Comment by weirdan** [comment]
Looks like a source of false positives to me, with a dubious benefits. Let's see what others think.

**Comment by mr-feek** [comment]
I think this might fall more into the category of unused variable detection / dead code ?

**Comment by weirdan** [comment]
The case of named constructor could probably be handled by annotating it with `@psalm-pure` (which doesn't seem to be working): https://psalm.dev/r/d5456ccb2f

**Comment by muglug** [comment]
Yeah, I don't think this is particularly valuable, sorry
