### ISSUE TITLE
Conditional return type not excluded in if block

### ISSUE THREAD

**Issue by joehoyle** [vimeo/psalm#3344]
Using the conditional types mentioned at https://psalm.dev/articles/conditional-love, I am trying to annotate a an `is_error()` function. This is intended to take 1 argument, and will return true or false ultimately based on the type. Therefor, it seems this is an ideal case to use `@psalm-return` conditionals.

However, it seems that conditional is not followed / understood in an `if` block. Whereas Psalm can understand `if ( $obj instanceof Error )` means anything in the block can narrow the `$obj` type to `Error`, it can't seem to link a conditional return with this.

This is best explained by https://psalm.dev/r/008bd5f780

**Comment by mr-feek** [comment]
@joehoyle 

Have a look at the [documentation](https://psalm.dev/docs/annotating_code/type_syntax/conditional_types/) pertaining conditional types, it's a bit more in-depth than the launch article.

> Conditional types are dependent on template parameters, so you can only use them in a function where template parameters are defined.

I believe your example will work if `$error` is templated

**Comment by mr-feek** [comment]
That being said, i would expect this to work: https://psalm.dev/r/8f0b564577

**Comment by joehoyle** [comment]
Ah nice, thanks for the correction @mr-feek. Based off your example, it seems maybe something is awry with the value detection, as the error `ERROR: DocblockTypeContradiction - 27:6 - if (false) is impossible` also seems to be wrong. It seems to thing `$object` _must_ be false, so is showing a warning that the `if` statement is operating on a must-be-false value.

**Comment by weirdan** [comment]
Conditional return types do not act as assertions (e.g. function mapping the `Error` to true being used in `if` does not imply `$obj` is `Error`). You would have to use actual assertions for that: https://psalm.dev/r/d172731fda

**Comment by joehoyle** [comment]
Ah great, thanks @weirdan!
