### ISSUE TITLE
InvalidCast - object cannot be cast to string

### ISSUE THREAD

**Issue by bkdotcom** [vimeo/psalm#3345]
despite having a check before doing so
ie either `methoc_exists($obj, '__toString')` or `isCallable(array($obj, '__toString'))`

https://psalm.dev/r/a1cafa9d3e

```php
if (is_object($val)) {
    if (!\is_callable(array($val, '__toString'))) {
        throw new \RuntimeException(__METHOD__ . ': ' . \get_class($val) . 'is not stringable');
}
    echo (string) $val;   // yes, this can be cast to string
}
```

**Comment by weirdan** [comment]
`method_exists()` seems to be working: https://psalm.dev/r/c0bca5d469

**Comment by muglug** [comment]
OK, what's required here is a simple check in `AssertionFinder` that generates the same assertion for `is_callable([$a, 'someMethod'])` as it would for `method_exists($a, 'someMethod')`
