### ISSUE TITLE
InvalidScalarArgument when getting value from array

### ISSUE THREAD

**Issue by bkdotcom** [vimeo/psalm#3346]
Not sure how to put into words.... but

https://psalm.dev/r/bc24f17936

if I use `$values['key']`..    psalm seems to think 'key' is a variable and `$values['key']` could be any of the values within $values

leading to `MixedArgument`  & `InvalidScalarArgument` errors  
even `PossiblyUndefinedStringArrayOffset`  when the array with 'key` is "clearly" defined

**Comment by orklah** [comment]
The output changed a lot since the issue creation. There is now only mixed errors. Is your issue solved now?

**Comment by weirdan** [comment]
Certainly fixed. `$setting` is now inferred as `array{filter: int(258)|mixed, msg: mixed|string(), name: mixed|string(), operator: mixed|string(==), val: mixed|true}` which gets rid of `PossiblyUndefinedStringArrayOffset` and `InvalidScalarArgument`. 

`MixedArgument` is legit, as any of the keys may get overwritten by the parameter, which has no clearly specified type.
