### ISSUE TITLE
[Question] Anaylzing comments / docblock in plugin

### ISSUE THREAD

**Issue by joehoyle** [vimeo/psalm#3348]
I'm currently writing a plugin to analyize special comments than precede function calls. Using `AfterEveryFunctionCallAnalysisInterface` I am able to identify the specific function calls, however the PHP comment is not "attached" the instance of the `PhpParser\Node\Expr\FuncCall` Expr. I think this is expected, as function calls don't inherently get linked to a preceding comment.

However, I also can't find any way in the Psalm plugin API to analyze comments, so I can't find a way to link a comment (which I think might bet attached to `Stmt_Nop` in PHPParser.

**Comment by muglug** [comment]
What does the code you're trying to analyse look like?

**Comment by joehoyle** [comment]
I'm trying to write a parser to collection all WordPress filters, which follow the WordPress hooks standard that is:

```php
/**
 * Filters the attached file based on the given ID.
 *
 * @since 2.1.0
 *
 * @param string $file          Path to attached file.
 * @param int    $attachment_id Attachment ID.
 */
return apply_filters( 'get_attached_file', $file, $attachment_id );
```

So, I'm currently adding a `AfterEveryFunctionCallAnalysisInterface` to look at each `apply_filters` call, and get the type, desc etc annotations from the comment before.

**Comment by muglug** [comment]
I think in that case you'd need to use the `AfterStatementAnalysisInterface` as the comment is attached to the `Return_` statement.
