### ISSUE TITLE
ImplementedReturnTypeMismatch how to fix

### ISSUE THREAD

**Issue by bkdotcom** [vimeo/psalm#3352]
The fix described in
https://psalm.dev/docs/running_psalm/issues/ImplementedReturnTypeMismatch/

Just leads to a InvalidReturnType error on the parent method

https://psalm.dev/r/a89d87bbbf

how can A::foo return void   and B::foo return string  ?

Is this  the same error as
https://github.com/vimeo/psalm/issues/3283
?

**Comment by muglug** [comment]
return `null` explicitly: https://psalm.dev/r/dd8de53475
