### ISSUE TITLE
Issues @template inheriting from IteratorIterator

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#3353]
after updating to psalm 3.11.4, a custom Iterator inheriting from IteratorIterator whose @template annotations I have lifted off psalm's internals now causes a `MissingTemplateParam` error to be thrown even though it totally looks correct to me.

The following snippet is a copy & paste of psalm's own `FilterIterator` stub and yet, when told to analyze this exact stub, the `MissingTemplateParam` error is back:

https://psalm.dev/r/391754eb4e

I don't see what the third parameter would be. There's only TKey and TValue. 

Also, having a bit more details in the error message would help diagnose the issue.

**Comment by andrew-demb** [comment]
Here third parameter: https://github.com/vimeo/psalm/blob/ebcb0b8cc48da269b19a470219e4d28ff9521c49/src/Psalm/Internal/Stubs/CoreGenericClasses.phpstub#L115

**Comment by pilif** [comment]
doesn't help though

https://psalm.dev/r/02546c281e
