### ISSUE TITLE
Allow class-level @psalm-suppress

### ISSUE THREAD

**Issue by AegirLeet** [vimeo/psalm#3357]
I recently deprecated a number of related classes. This causes a `DeprecatedClass` error every time one deprecated class references another deprecated class. I'd like to suppress those and adding `@psalm-suppress DeprecatedClass` to every class's class-level DocBlock seemed like the most straightforward approach. Unfortunately, that doesn't seem to have any effect.

There are alternative approaches (`<errorLevel> + <file>` in config, `@psalm-suppress` for every method etc., baseline), but a class-level suppression would be way simpler.

[Example](https://psalm.dev/r/443e68eb21)

Ideally, a `DeprecatedClass` would be generated for `C`, but not for `B`.

**Comment by eithed** [comment]
> I found these snippets:
> 
> https://psalm.dev/r/443e68eb21

This doesn't seem to work
