### ISSUE TITLE
Wrong return type for \parse_url with two arguments

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#3359]
[\parse_url](https://www.php.net/manual/en/function.parse-url.php) returns `false` for 'seriously malformed urls'. [This is true](https://3v4l.org/9Mepj) whether called with one param or two.

However in the latter case, psalm thinks the return type is `null|string`. It should be `null|string|false`.

https://psalm.dev/r/3234b76fb6

**Comment by weirdan** [comment]
Should be easy to fix the inference in `src/Psalm/Internal/Provider/ReturnTypeProvider/ParseUrlReturnTypeProvider.php`

**Comment by bdsl** [comment]
Thanks @orklah and @muglug!
