### ISSUE TITLE
Use JSON_PRETTY_PRINT by default

### ISSUE THREAD

**Issue by dereuromark** [vimeo/psalm#3360]
When generating a report.json using `--report=PATH` the file generated is not using JSON_PRETTY_PRINT, being one huge blob that is not readable by default without IDE level extensions or alike.

Since this is a dev only tool, I propose that the default here should be with pretty print, to allow this also be read/searched by humans more easily.
After all, the few more bytes here on the disk probably don't matter. And tooling doesn't care either way.
It is also harder to read diff when committing those files or alike.

**Comment by muglug** [comment]
Mind creating a PR?
