### ISSUE TITLE
cannot implicitly use if to make sure a string is actually a non-empty-string

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#3365]
I recently discovered that Psalm has the non-empty-string and non-empty-array types. It is so great that Psalm has these! Most type systems are missing these, which is terrible, because conceptually an empty string doesn't make any sense, because conceptually an empty string is not actually a string, it is conceptually the same as null. I mean if you have a string that is empty, what is it a string of? It is not  a string of characters or bytes, it is just nothing. You could make a similar argument about an empty array. Therefore, in my opinion, using arrays or strings instead of non-empty-array or non-empty-string is a code smell. Let's say a function returns a string. You can't tell from the method signature what the API/contract of that function really is. Can it return an empty string or not? You have no idea without examining further. You could clarify this with a docblock by specifying the return type as either `non-empty-string` or as `null|non-empty-string` depending on which one represents the contract of that method. Then if it needs to return an empty string, it would return null instead, since empty strings make no sense.

Anyway, that is just my way of thanking you for this, and my way of letting you know why I am planning to start using both non-empty-string and non-empty-array extensively.

The issue I'm report is in regards to the non-empty-string, checking `if ($something === '')` does not help Psalm understand if $something is an empty string or not. Here is an [example](https://psalm.dev/r/e71974d387). As a point of comparison, you could check `if ($something === null)` , and this does help Psalm understand if $something is null or not.

**Comment by muglug** [comment]
Thanks for the praise!

**Comment by still-dreaming-1** [comment]
Your welcome. I couldn't resist editing my original post to throw in a point about TOP.
