### ISSUE TITLE
PossiblyFalseReference is not reported when UndefinedGlobalVariable occurs beforehand 

### ISSUE THREAD

**Issue by nobuf** [vimeo/psalm#3366]
Link: https://psalm.dev/r/7d3e0a9f01

I'd expect psalm reports both UndefinedGlobalVariable and PossiblyFalseReference in the above code.

It looks like the order matters as https://psalm.dev/r/21f44d1936 reports both issue types.

**Comment by muglug** [comment]
Yeah at the moment `UndefinedGlobalVariable` is a show-stopper for Psalm, but I agree it needn't be.
