### ISSUE TITLE
[Question] Template with array-keys

### ISSUE THREAD

**Issue by joehoyle** [vimeo/psalm#3368]
I have this code: https://psalm.dev/r/d6bb5762c6, and I'm trying to see if there is a way to have Psalm follow this pattern, without explicitly defining the return type based off a huge conditional return docblock.

Ideally I'm looking to do _something_ like this:

```
<?php

/**
 * @psalm-type OptionsArray = array{foo: string, bar: int}
/**
 * @return OptionsArray
 */
function getOptions() {
    return ['foo' => 'baz', 'bar' => 1 ];
}

/**
 * @template T
 * @param T $key
 * @return OptionsArray[T]
 */
function getOption( string $key ) {
    return getOptions()[ $key ];
}

$value = getOption('foo');
```

However, this isn't valid syntax -- with the Templates, is it possible to specify an array key (or am I approaching this completely wrong?)

**Comment by weirdan** [comment]
Basically, you're looking for index types, as they call it in TS. Would also be useful in cases like #3141

**Comment by muglug** [comment]
Psalm has index types for templates: https://psalm.dev/r/e2d1e612d5

**Comment by weirdan** [comment]
Indeed. Combined with `key-of<T>` it works *almost* perfectly: https://psalm.dev/r/0eb2af5a2a

Should I close this then?

**Comment by muglug** [comment]
Yeah, otherwise this issue is basically just asking for Psalm to support redirecting to a constant fetch, which isn’t terribly useful in general, I think
