### ISSUE TITLE
Complains about LSP violations in SPL

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#337]
This code:
```php
<?php
class SomeIterator extends IteratorIterator
{

}
```
results in the following problem report:
```
ERROR: MoreSpecificReturnType - qqqqq.php:2:1 - The return type 'Iterator' for OuterIterator::getInnerIterator is more specific than the implemented return type for IteratorIterator::getinneriterator 'Traversable'
class SomeIterator extends IteratorIterator
```
However there's nothing user could do about this as both reported classes/interfaces are in PHP SPL/core, and those signatures are unlikely to change anytime soon.

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/8b0d99e28b8e32c3afd7345cff2f5f386594a3cc
