### ISSUE TITLE
Infer numeric-string from (string)$numeric

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#3370]
https://psalm.dev/r/24d8f97f54
Here I'd expect Psalm to understand that strings produced from numbers are always numeric.

**Comment by SignpostMarv** [comment]
additional example with bcadd, only line 5 should really be failing: https://psalm.dev/r/67dc2926c8

**Comment by muglug** [comment]
This is a very easy thing to solve in the `ExpressionAnalyzer::castStringAttempt` method

**Comment by SignpostMarv** [comment]
will have a PR for this shortly.

**Comment by SignpostMarv** [comment]
44e01e7 should fail on purpose, 6f94afc should pass where 44e01e7 fails.

**Comment by SignpostMarv** [comment]
PR build is passing now, 6f94afc failed due to formatting issues & existing tests now returning `numeric-string[]` instead of `string[]`.

**Comment by SignpostMarv** [comment]
would it be overkill to add checks to fixed strings to see if they're numeric?

currently picking up a bunch of these errors: https://psalm.dev/r/c9b66a30c6

where line 5 errors because `$foo = '0.0';`, whereas line 11 presumably doesn't error because literal `0.0` is typecast with string?

**Comment by weirdan** [comment]
> would it be overkill to add checks to fixed strings to see if they're numeric?

Looks sensible to me.
