### ISSUE TITLE
Inconsistent type errors on arrow functions

### ISSUE THREAD

**Issue by jwdunne** [vimeo/psalm#3376]
New to using Psalm and it's awesome!

Noticed that return type checking doesn't seem to handle arrow functions as well as the non-arrow counterparts e.g:

https://psalm.dev/r/2b701d86b9

Because I'm new, I'm not sure if I'm doing something wrong but it doesn't look like the return type is considered when returning an arrow function.

**Comment by muglug** [comment]
Oh @ragboyjr I think your earlier solution just needs a slight adaptation to arrow functions - want to make it, or should I?

**Comment by ragboyjr** [comment]
@muglug ah, ok, will give this a look!

**Comment by ragboyjr** [comment]
OK, i was able to fix the patch for arrow functions, but it looks like there's another bug that tries to infer his example as `Closure(empty):bool`. Will try to address that in a separate PR.

**Comment by muglug** [comment]
Thanks!
