### ISSUE TITLE
Generic type "does not contain an empty array"

### ISSUE THREAD

**Issue by EvgeniiR** [vimeo/psalm#3380]
Hello, here is code sample - https://psalm.dev/r/9d76cdb17f

As far as I know, generic type here can be empty array, but psalm says it can't, although it allows to call the function by passing an empty array as an argument

**Comment by EvgeniiR** [comment]
@muglug If you haven't done this yet, can I try fixing this problem myself and make PR?

I have already managed to achieve the desired code behavior, now need to may be make some cosmetic code fixes, add more tests, and as I understand, we should now differentiate "InvalidClone" and "PossibleInvalidClone" types, so I need to add PossibleInvalidClone type, and page in documentation for it

**Comment by muglug** [comment]
It was a very simple fix, but

> we should now differentiate "InvalidClone" and "PossibleInvalidClone" types, so I need to add PossibleInvalidClone type, and page in documentation for it

Please do that!

**Comment by EvgeniiR** [comment]
@muglug Sorry, messed up with topics a bit, i certainly mean https://github.com/vimeo/psalm/issues/3329 , that why I mentioned cloning.

After that I'll try to fix this one too
