### ISSUE TITLE
Key wrongly detected as non-empty-mixed

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#3381]
This method could very well be called with `["isOwningSide" => true]`, in which case `joinColumns` is and stays empty.

https://psalm.dev/r/d66f9d79c3

**Comment by orklah** [comment]
This seems to resolve itself when we document that the array could contains the `joinColumns` key:
https://psalm.dev/r/51208503d1

**Comment by greg0ire** [comment]
Ok I think I can close it, the issue is my misunderstanding of the annotation I was using. To express that this is an array that must contain `isOwningSide` and might contain other keys, I should have used the following: https://psalm.dev/r/c61b1e8199

**Comment by orklah** [comment]
> Ok I think I can close it, the issue is my misunderstanding of the annotation I was using. To express that this is an array that must contain `isOwningSide` and might contain other keys, I should have used the following: https://psalm.dev/r/c61b1e8199

Not really your fault, this is a blurry zone in Psalm. Please read this answer in the issue, that should help you understand: https://github.com/vimeo/psalm/issues/5299#issuecomment-788070132

**Comment by greg0ire** [comment]
Indeed, good to know :slightly_smiling_face:
