### ISSUE TITLE
?int lte num check does not subtract null

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#3389]
Having `?int $val`  and checking for `$val < 0` should IMO tell psalm, that `$val` is int and cannot be null after successfully passing such check. However, psalm thinks the value can be null.

https://3v4l.org/Tfaiv `var_dump(null < 0); => bool(false)`

https://psalm.dev/r/86b0c0c2ee

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/21798efed21503ff481084d4839cd6a7a688bfbd
