### ISSUE TITLE
assigning numeric-string / query re: literal-numeric-string

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#3396]
re: #3370 and https://psalm.dev/r/c9b66a30c6, I'm wondering if `$foo = '0.0';` should resolve to numeric-string, or if a TLiteralNumericString should be implemented?

had a poke around trying to implement assignment as numeric-string, but had a bit of an issue trying to figure out where to put it.

**Comment by weirdan** [comment]
I suppose `TLiteralNumericString` makes sense (or `TNumericString&TLiteralString`, but, IIRC intersections are only supported for shapes and objects). Otherwise you'd have to chose whether to infer a type as literal or numeric, where it could be both.

**Comment by SignpostMarv** [comment]
this is vaguely related to #3408 because of how union types with stringables resolve to a single string type rather than a combination of literals a non-literals.

**Comment by muglug** [comment]
There's no real point – I fixed merging of numeric-string and literal strings that look numeric in https://github.com/vimeo/psalm/commit/2312523318154890b0bc628e92da5ece644f6df9
