### ISSUE TITLE
Issue with reference argument and subclasses

### ISSUE THREAD

**Issue by afbarbaro** [vimeo/psalm#3397]
This seems to be an erroneous check.   Am I missing something?  It seems the return of `bar` is correct as `B`.

https://psalm.dev/r/949e386523

```
<?php

class A { /** @var int */ public $x = 0;}

class B extends A{}

function foo(A &$obj): void { $obj->x = 1;}

function bar(): B {
	$b = new B();
	foo($b);
	return $b;
}
```

```
INFO: LessSpecificReturnStatement - 12:12 - The type 'A' is more general than the declared return type 'B' for bar

INFO: MoreSpecificReturnType - 9:17 - The declared return type 'B' for bar is more specific than the inferred return type 'A'
```

Note:  If the reference in the argument to `foo` is removed no warnings are issued.

**Comment by weirdan** [comment]
This is to prevent situations like this: https://3v4l.org/fHSIl
Psalm generally performs checks at function boundaries, so at the call site (`foo($b);`) it cannot guarantee the type of `$b` won't change.

You should be able to get around this by declaring `foo()` a generic function:
https://psalm.dev/r/13b9aaa1e9
but it doesn't seem to work, which looks like a bug to me.

**Comment by afbarbaro** [comment]
@weirdan yes, I can see the use of `generics` to resolve this but I bumped into that issue that now `Psalm` doesn't understand that `T` is of type that `extends A`.  So we still need a way to get pass this issue.

**Comment by weirdan** [comment]
I think I fixed it in the linked PR. There are issues with master branch right now, so it can't be merged yet.

**Comment by afbarbaro** [comment]
> I think I fixed it in the linked PR. There are issues with master branch right now, so it can't be merged yet.

Awesome! Thanks so much 🥇

**Comment by muglug** [comment]
Above example now works
