### ISSUE TITLE
Analysis fails upon nested array with initialized value

### ISSUE THREAD

**Issue by viktorasp** [vimeo/psalm#340]
As of some recent update psalm checks started crashing with a message 'This is a bad place' (FetchChecker.php:1182). 

I've reduced the code that causes psalm to crash down to:
```
class A
{
    public function getResults()
    {
        $hydrated = [
            'totals' => [],
        ];
        $hydrated['totals']['foobar'] = 0;

        foreach ([2017, 2018] as $date) {
            $hydrated['totals']['total'] += $hydrated['totals'][$date];
        }

        return $hydrated;
    }
}
```

By the way, if `$date` is replaced with a static value - all goes well.

**Comment by muglug** [comment]
Thanks – do you get notices in PHP from this code? The above simplifies to

```php
$a = [
    'b' => [],
];

$a['b']['c'] = 0;

foreach ([1, 2, 3] as $i) {
    $a['b']['d'] += $a['b'][$i];
}
```

which gives an `Undefined offset` notice (this is still a Psalm bug, obviously)

**Comment by muglug** [comment]
This commit should have a fix.

**Comment by viktorasp** [comment]
In a proper code those sub-nodes get populated before `$a['b']['d'] += $a['b'][$i];` part. However, in this reduced example yes, it would emit a notice.

Thank you for a quick fix!
