### ISSUE TITLE
PossiblyUndefinedStringArrayOffset is not thrown

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#3402]
https://psalm.dev/r/a7d812940a

I expect a `PossiblyUndefinedStringArrayOffset` error on line 41

**Comment by weirdan** [comment]
To be able to catch that, `Evaluation` type should store the type of it's constructor parameter, i.e. it should be generic: https://psalm.dev/r/b6a6db9f70

**Comment by vudaltsov** [comment]
@weirdan , it seems I changed `InvalidArrayOffset` to `PossiblyUndefinedStringArrayOffset` in the description too late. 

I didn't mean that I want the exact offset missing, just a generic error that I try to access a key that might not be there. Like in this simple case: https://psalm.dev/r/23af1eeec7.

Correct me if I'm wrong or, please, reopen.

**Comment by weirdan** [comment]
Literal string offsets trigger `PossiblyUndefinedStringArrayOffset`, but `string` offsets don't:
 https://psalm.dev/r/cf51fd3b98

I suppose changing that may cause a lot of false positives (especially in case of `unknownArray[unknownString()]`), but the issue seems to be valid as described.

**Comment by vudaltsov** [comment]
Well... Maybe I rely on Psalm too much, but I would be happy if in strict mode I could detect such errors before deploying.

**Comment by muglug** [comment]
I don't think this is a bug – it quickly gets into the realm of undecidable problems
