### ISSUE TITLE
Dynamic return type for Ds\Map

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#3405]
Is there some equivalent for PHPStan's `DynamicMethodReturnTypeExtension`? I need a psalm equivalent for [this](https://github.com/phpstan/phpstan-src/blob/master/src/Type/Php/DsMapDynamicReturnTypeExtension.php). Currently Psalm is unaware that `Ds\Map::get()` called with only one argument can't return `TDefault`.

**Comment by muglug** [comment]
@enumag yes there is (see the [plugin authoring section](https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/) of the docs) but it would be easier for you to add a conditional return type e.g. https://github.com/vimeo/psalm/blob/dc82243edc3b01b912b7bec1700a5dc889234ea6/src/Psalm/Internal/Stubs/CoreGenericFunctions.phpstub#L417-L424
