### ISSUE TITLE
Invalid read from CallMap when methods are in inheritance

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#3406]
```php
<?php

use RdKafka\Producer;
use const RD_KAFKA_PARTITION_UA;

final class A
{
    public function fcn() : void
    {
        $producer = new Producer();
        $topic = $producer->newTopic('topic');
        $topic->produce(RD_KAFKA_PARTITION_UA, 0, 'payload', 'key');
    }
}
```
Psalm reports

> UndefinedMethod - Method RdKafka\Topic::produce does not exist (see https://psalm.dev/022)
>        $topic->produce(RD_KAFKA_PARTITION_UA, 0, 'payload', 'key');

[`RdKafka\Producer`](https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/class.rdkafka-producer.html) extends [`RdKafka`](https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/class.rdkafka.html).

```php
<?php

class Producer extends \RdKafka
{
    /**
     * @param string    $topic_name
     * @param TopicConf $topic_conf
     *
     * @return ProducerTopic
     */
    public function newTopic($topic_name, TopicConf $topic_conf = null)
    {
    }
```

```php
<?php

abstract class RdKafka
{
    /**
     * @param string    $topic_name
     * @param TopicConf $topic_conf
     *
     * @return Topic
     */
    public function newTopic($topic_name, TopicConf $topic_conf = null)
    {
    }
```

This is correctly defined in CallMap:

```
'RdKafka::newTopic' => ['RdKafka\Topic', 'topic_name'=>'string', 'topic_conf='=>'?RdKafka\TopicConf'],
'RdKafka\Producer::newTopic' => ['RdKafka\ProducerTopic', 'topic_name'=>'string', 'topic_conf='=>'?RdKafka\TopicConf'],
```

However, psalm assigns `RdKafka::newTopic` definition to `RdKafka\Producer::newTopic` and thinks it returns `RdKafka\Topic` while it returns `RdKafka\ProducerTopic`.

https://github.com/simPod/psalm-kafka-broken/commit/58962588fc16d046cdc69ddbd16e77b9d34f4914#diff-3e3f7392d7da765a65d0ece9729444aaR14

**Comment by weirdan** [comment]
I don't think Psalm is mistaken here. Both [documentation](https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka.newtopic.html) and [extension source code](https://github.com/arnaud-lb/php-rdkafka/blob/cc11637e4530caca730f8a32a8d36fc1998eee8e/rdkafka.c#L465) says there's no method `newTopic` on `RdKafka\Producer` class. Psalm sees that (via reflection) and uses correct callmap entry. 

Basically `RdKafka::newTopic` has a conditional return type based on LSB, but I'm not sure if it's possible to express that condition given the features we have right now. @muglug, can you advise if it's possible to use type of $this/static as a condition in a conditional return type (I tried `static is Type` and `$this is Type` but none of that worked for me)?
