### ISSUE TITLE
issue with casted nulls, false, & unions with numeric-string

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#3408]
https://psalm.dev/r/054aa5988d

* `(string) null` should be `TLiteralString("");`
* `(string) false` should be `TLitertalString("");`
* string cast of `false|numeric-string` or `null|numeric-string` should resolve as `''|numeric-string`, not `string`

**Comment by SignpostMarv** [comment]
I've been poking around the codebase, and it seems to fall apart around `TypeCombination::combineTypes()`.

**Comment by SignpostMarv** [comment]
relevancy of nulls casted to literal strings, various `ext-bcmath` functions return either `null` or `false` when given bad inputs. these both string-typecast to `''`, which seems to be interpreted by bcmath as `0`.

not all `ext-bcmath` exhibit the behaviour of null on bad inputs, at least one returns `false`, others return variations of `'0'` or `'0.0'` depending on how the `$scale` parameter is interpreted, and at least one of them returns a variation of `'1'`.

**Comment by muglug** [comment]
Fixed in b38d945

**Comment by SignpostMarv** [comment]
`null|numeric-string` doesn't typecast to `''|numeric-string`

**Comment by muglug** [comment]
it typecasts to `string`, which is all that Psalm can currently do (and I think a sane option)

**Comment by SignpostMarv** [comment]
is this re: avoiding resolving unions more accurately due to potential negative performance impact of more complex unions?

**Comment by SignpostMarv** [comment]
point being https://psalm.dev/r/5d42b4bcbc where `(string) numeric-string` wraps back around to `numeric-string`.

**Comment by muglug** [comment]
It's that the type combination logic is already complex, and making it _more_ complex (allowing unions of literal strings and `numeric-string`) would be stupid, from a future-maintenance perspective.
