### ISSUE TITLE
Case condition side-effects

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#342]
```php
switch (true) {
    case preg_match('/(d)ata/', 'some data in subject string', $matches):
        return $matches[1]; // return 'd'
    default:
        throw new RuntimeException('none found');
}
```
results in the following problem report:
```
ERROR: UndefinedVariable - q.php:4:16 - Cannot find referenced variable $matches
        return $matches[1]; // return 'd'
```
But `$matches` are supposed to be defined, by the virtue of being the out parameter of evaluated `preg_match` call.
What's interesting, while `$matches` is considered undefined in that `case` body, accessing it *after* the switch works just fine.

There's similar problem with assignments in the case condition, but Psalm reports nothing at all for the case body here:
```php
function f(string $p) : void { }
switch (true) {
    case $q = (bool) rand(0,1):
        f($q); // this type problem is not detected
        break;
}
f($q); // but this is correctly reported
```

**Comment by muglug** [comment]
Thanks for this!
