### ISSUE TITLE
Psalm "forgets" about declared `@psalm-type` when it is used in other `@psalm-type` recursive expressions

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#3422]
See https://psalm.dev/r/78e9f0bdcd

In this example, I have a recursively nested array structure that I'm trying to document both for type-safety and sanity reasons:

```php
<?php

namespace Audience\Infrastructure\FilterRule\Serializer;

/**
 * @psalm-type TermArray            = array{irrelevant: string}
 * @psalm-type LogicalAndArray      = array{and: list<LogicExpressionArray>}
 * @psalm-type LogicExpressionArray = LogicalAndArray | TermArray
 */
final class JsonLogicExpressionSerializer
{
    /** @psalm-return LogicExpressionArray */
    private function logicExpressionToArray($expression): array
    {
        throw new \BadMethodCallException('not implemented');
    }
}
```

Psalm seems to be confused about `LogicExpressionArray` (and only `LogicExpressionArray`: other types work fine!):

```
Psalm output (using commit 952216f): 

ERROR: UndefinedDocblockClass - 14:23 - Docblock-defined class or interface Audience\Infrastructure\FilterRule\Serializer\LogicExpressionArray does not exist
```

Interestingly, pulling the code out of the namespace leads to a crash: https://psalm.dev/r/93cc816e1b
I tried making a more minimal example: similar crash (or forgotten type) behavior depending on namespace or not: https://psalm.dev/r/0131b39270

**Comment by muglug** [comment]
Recursively-defined types are not supported, sorry.

**Comment by Ocramius** [comment]
Hmm, how would one go about defining a basic JSON type?

Thinking:

```php
type JSON = 
    Null
    | Number
    | Text
    | Map JSON
    | List JSON
```

Seems like a basic scenario: is it really not possible to have cross-referencing types, like we already have classes?

**Comment by Ocramius** [comment]
Note: not *expecting* it to work right now, just wondering if it can be done with effort, or if it's cut off from possibilities :-)
