### ISSUE TITLE
psalm-template T of not understood correctly when class-string flow is not inherent

### ISSUE THREAD

**Issue by JoshuaBehrens** [vimeo/psalm#3429]
When using the psalm template notation the type of the returned instance is marked as incorrect although it is not. When you use the parameter that claims to be of that template type as class name to invoke the constructor it works out correctly but if you choose your own implementation which still matches every condition and pass the parameter that should be used to detect the return type phpstan states that it does not match.

https://psalm.dev/r/19fa9b7bf7

**Comment by muglug** [comment]
This isn't a bug, in my opinion (and Ondrej's, and the Hack typecchecker).

**Comment by weirdan** [comment]
You can also provide Psalm with a `@var` hint: https://psalm.dev/r/a4670dde38
