### ISSUE TITLE
Cannot call function on T:fn-foo as Closure

### ISSUE THREAD

**Issue by EvgeniiR** [vimeo/psalm#3432]
Here's an example: https://psalm.dev/r/9fb0f7a28a

**Comment by EvgeniiR** [comment]
UPD: My mistake: must be `Closure()` instad of `Closure` in docblock ( https://psalm.dev/r/0bc209bbc2 )

**Comment by weirdan** [comment]
`Closure` is a valid class name, so it should be usable as a template constraint without parenthesis.

**Comment by orklah** [comment]
@weirdan this is no longer reproducible, you can close
