### ISSUE TITLE
Not recognizing that class of template collection implements given interface when returning?

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3433]
https://psalm.dev/r/7d4517670c

Foo implements FooInterface, so why is psalm complaining during returning that it returns `<Foo>` instead of `<FooInterface>`?

**Comment by muglug** [comment]
The template param `T` on `Collection` needs to be declared covariant: https://psalm.dev/r/15b8696de5

**Comment by ostrolucky** [comment]
Is this safe to do in common library like Doctrine Collections? And why is this not default behaviour? Because I've run into this issue exactly with doctrine collections.

**Comment by weirdan** [comment]
It's safe for read-only contexts, or immutable objects (so, not for Doctrine Collections, which are mutable).

For why it's not a default behavior see this: https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance

**Comment by ostrolucky** [comment]
Problem that is explained https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance at is when returning Dog/Cat instead of Animal. I have opposite problem, I'm returning Animal instead of Dog/Cat, this should be perfectly LSP safe.

Since I cannot use `@psalm-template-covariant` because it's Doctrine Collection, what's the proper solution here then?

**Comment by weirdan** [comment]
The code, as written, allows the class consumer to put other implementations of `FooInterface` to that collection, while the class (still holding a reference to it) expects it to only contain `Foo`s. So it's not actually type-safe.

> Since I cannot use @psalm-template-covariant because it's Doctrine Collection, what's the proper solution here then?

One way I can think of is to make FooInterface generic: https://psalm.dev/r/f8ce27c766
