### ISSUE TITLE
ERROR: ArgumentTypeCoercion - Argument 1 of foo expects callable(object):void, parent type Closure(Foo):void provided

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3435]
https://psalm.dev/r/41f620d927

Why is `Foo` class not considered `object` or/nor `Closure` not considered `callable`?

**Comment by weirdan** [comment]
When you declare you accept `callable(object)` it means you should be able to call it inside your function with **any** object. However you're passing the value that cannot fulfill this contract.

The rules governing this are similar to those used during the inheritance - if you think of callable signature in `@param` docblock as an interface and the passed value as implementation. 
Parameters of the passed callable must be contravariant - same or wider than those declared by the 'interface'. Return type must be covariant - same or narrower than declared by 'interface'.

It's more obvious when callable/closures are replaced with actual interfaces / classes with `__invoke()`: https://3v4l.org/tRLWs
