### ISSUE TITLE
Doctrine ArrayCollection::set is broken

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3436]
Reproducer: https://psalm.dev/r/be559962d4

**Comment by weirdan** [comment]
You're not giving Psalm enough information to infer the type for `$coll`. In a language with native generics you'd do something like `$coll = new ArrayCollection<int,string>()`, but in PHP/Psalm you have to resort to docblock: https://psalm.dev/r/017a26e6b3

**Comment by ostrolucky** [comment]
Then Psalm should say so, not giving bogus message that it expects empty, what does that even mean. Let's reopen and rename title.

**Comment by weirdan** [comment]
I'll let @muglug to decide this.

**Comment by ostrolucky** [comment]
I didn't see answers from @muglug in recent issues for a while, so I don't want to rely on that he will come back to this issue soon. Let's reopen this issue and let him decide if he wants to close it, not reverse.

**Comment by orklah** [comment]
I can confirm that "expects empty" kind of error on missing phpdoc is really disturbing. Once you saw it a few times, this is easy to fix/pinpoint, but it's really not user friendly.

**Comment by weirdan** [comment]
> for a while 

It's been 12 hours: https://github.com/vimeo/psalm/issues/3430#issuecomment-633041722

> Let's reopen this issue

No need to do that, as you now have created a better version of it (#3441)

**Comment by muglug** [comment]
hey @ostrolucky,

@weirdan has been contributing valuably to Psalm for almost two years, and definitely has the authority to close issues.

Since my personal time is finite I have to prioritise what I spend time working on. Currently that involves working on taint analysis, a feature that hopefully a lot of people will find useful.

If you want to help, there are a ton of "easy" fixes in Psalm's issue backlog.

**Comment by ostrolucky** [comment]
Yeah I'm not saying @weirdan doesn't have authority to close issues, he sure does. I'm saying if it's not decided if issue is valid, it should stay open, because open/closed issue state is a marker if issue is still valid and not doing action immediately after getting notification will cause such issue to be lost among other done issues. Anyways I've opened new issue because I didn't see this one getting reopened, so yeah nothing needs to be done here now.

As for helping out, I sure will do that sometime, but you know how it is in OSS, lot of work and few people. This also applies for me and my projects I maintain or contribute to. In another words, I'm flooded with work in other repositories already.
