### ISSUE TITLE
psalm should be smarter about recognizing if bcdiv can return null (if divisor is non-0)

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3438]
https://psalm.dev/r/41cf16dc2d

**Comment by weirdan** [comment]
Once the linked ticket is fixed, it'll be possible to express `bcdiv` type as:
```php
/**
 * @psalm-pure
 *
 * @template T of numeric-string
 * @param numeric-string $left_operand
 * @param T $right_operand
 * @return (T is "0" ? null : numeric-string)
 */
function bcdiv(string $left_operand, string $right_operand, int $scale = 0): ?string {}
```

**Comment by orklah** [comment]
@weirdan you should even be able to remove the @template in this case and just use the conditional with the param name:
https://psalm.dev/r/80f91a4817

The issue is still the same, but the @template is not needed here.

**Comment by weirdan** [comment]
> you should even be able to remove the @template in this case

No, it doesn't seem to work with variables: https://psalm.dev/r/11f0b87b16

**Comment by orklah** [comment]
> > you should even be able to remove the @template in this case
> 
> No, it doesn't seem to work with variables: https://psalm.dev/r/11f0b87b16

https://psalm.dev/r/47f571287c
I fixed the variable name :)
