### ISSUE TITLE
Psalm doesn't understand that prefixing int with '-' makes it numeric-string

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3439]
https://psalm.dev/r/9d1850e0dd

**Comment by weirdan** [comment]
That's only true for positive numbers: https://3v4l.org/MK2Zq
To me it would make more sense if it was written as https://psalm.dev/r/5dd235bca2

**Comment by ostrolucky** [comment]
What about this? Psalm should know this is positive number thanks to guard clause. https://psalm.dev/r/5a670f1de1

**Comment by weirdan** [comment]
Psalm doesn't have a `non-negative-number` type. There's was a rejected feature request to add that (see #3199), but as it stands now it's not something Psalm can do.

**Comment by ostrolucky** [comment]
If it doesn't have non-negative-number, how can Psalm not return error in your link https://psalm.dev/r/5dd235bca2? I think this proves it has something for this internally.

**Comment by weirdan** [comment]
`-int` is still `int`, `(string)` cast makes that `numeric-string`. No non-negative types had to be involved.

**Comment by ostrolucky** [comment]
Yes I know `-int` is still int. `int` is also `int`. My point is Psalm understands difference between them, because it reports error for
```php
/**
 * @return numeric-string
 */
function getMonthlyFeeForUsers(int $val): string
{
    return '-' . $val;
}
```
but not for
```php
/** @return numeric-string */
function getMonthlyFeeForUsers(int $val): string
{
    return (string) -$val;
}
```

So how does it understand that difference?

**Comment by weirdan** [comment]
>  `int` is also `int`.

True, but you probably had something else in mind.

Looking at your version:
* `'-'` is a `string`
* Concatenating `string` with an `int` results in `string` (not necessarily numeric, as was shown above).

So Psalm reports the issue.
