### ISSUE TITLE
Support negation in @psalm-assert

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#3443]
While implementing https://github.com/webmozart/assert/pull/126 I have found a few edge cases with `@psalm-assert` when the parser cannot parse the valid type declaration (which contains negation):

https://psalm.dev/r/466053ccd4

I'm providing all the 9 cases that "affect" my implementation.

**Comment by weirdan** [comment]
Parse error is a bug, while negated types look more like an enhancement.

**Comment by muglug** [comment]
Fixed the uncaught exception, but I'm not going to allow `Foo|!Bar` (`!Foo|Bar` is already caught).
