### ISSUE TITLE
Feature request/question: empty and union types

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#3444]
This is partially related to the https://github.com/vimeo/psalm/issues/3443 but mostly is a feature request/suggestion/question of its own.

At the moment to express "not empty string" type one would use the following annotations

```php
    /**
     * @psalm-pure
     * @psalm-assert string $value
     * @psalm-assert !empty $value
     *
     * @param mixed  $value
     * @param string $message
     *
     * @throws InvalidArgumentException
     */
    public static function stringNotEmpty($value, $message = '')
    {
        static::string($value, $message);
        static::notEq($value, '', $message);
    }
```

Now if we want to make this assertion nullable so that it expressed as "null or not empty string" then we realise it's not really possible to encode it in type.

If I'm not wrong in everything I wrote above, then the question would be: how feasible instead of using 2 `@psalm-assert` - to support a `string & !empty` type annotation?

Then the desired nullable option for it would be `null | (string & !empty)`.

Also relevant:

```php
    /**
     * @psalm-pure
     * @psalm-template UnexpectedType of object
     * @psalm-param class-string<UnexpectedType> $class
     * @psalm-assert !UnexpectedType $value
     * @psalm-assert !class-string<UnexpectedType> $value
     *
     * @param object|string $value
     * @param string        $class
     * @param string        $message
     *
     * @throws InvalidArgumentException
     */
    public static function isNotA($value, $class, $message = '') {}
```

**Comment by weirdan** [comment]
Your specific case is possible with `non-empty-string` type: https://psalm.dev/r/f1537fc1b1 though

> Also relevant:

That works: https://psalm.dev/r/b8afb83865

**Comment by zerkms** [comment]
@weirdan 

> That works

when I said "relevant" I meant - that is another case that I need to `null | X`

**Comment by weirdan** [comment]
Ah, I see.

**Comment by muglug** [comment]
I don't ever see Psalm supporting this, sorry

**Comment by Ocramius** [comment]
This seems to already work with more "traditional" assertions: is there an architectural reasoning why union types cannot be expanded to `||` expressions?

See https://psalm.dev/r/890b8abfff for reference

**Comment by muglug** [comment]
It’s mainly about the complexity of type parsing.

Types and assertions have a different syntax, but some types are valid assertions. Many valid assertions are not, on the other hand, valid types.

In order to not make life too difficult for me or anyone else updating the type parsing logic, I have to add some limits on what’s allowable.

**Comment by Ocramius** [comment]
Makes sense, thank you!

**Comment by zerkms** [comment]
> Types and assertions have a different syntax, but some types are valid assertions.
That's what I always wondered. What would be a trivial example of a valid assertion that is an invalid type otherwise?

**Comment by muglug** [comment]
> What would be a trivial example of a valid assertion that is an invalid type otherwise?

`!null`, `falsy` are two examples
