### ISSUE TITLE
Psalm doesn't support @template in combination with traits

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3446]
https://psalm.dev/r/0f50b31337 What's the solution when functionality in templated class is split into traits? If this is hard to implement, can we make Psalm at least complain about such annotations in Traits, since they seem ignored?

**Comment by weirdan** [comment]
Use `@use Crud<T>` to pass the template parameter to the trait: https://psalm.dev/r/beb1be393f
