### ISSUE TITLE
Message "Type Foo should be a subtype of object" that happens when class doesn't specify @extends is wrong, should be fixed. 

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3447]
https://psalm.dev/r/a844944e60

Specifically I'm confused about this error

> ERROR: ArgumentTypeCoercion - 42:16 - Type Foo should be a subtype of object

I know how to fix it, as I shown in that snippet with ExtendedManager2, but this message doesn't make sense. Any subclass is a subtype of object.

**Comment by muglug** [comment]
The error is correct, but the error message is wrong, it should be the other way around

**Comment by muglug** [comment]
Error message fixed in ff5c17c

**Comment by muglug** [comment]
@ostrolucky as to why, here's code that blows up at runtime: https://psalm.dev/r/19256f37a2

**Comment by ostrolucky** [comment]
Yeah one another thing I didn't realize when I was changing these docblocks was that Psalm by default considers 
```
/**
 * @psalm-template T of object
 **/
class CommonManager 
```
as `CommonManager<object>`. It would be nice if Psalm tipped me off on this, but not sure what would be a good message. I was thinking something in Symfony style, such as `Type object should be a subtype of Foo. Have you specified @extends annotation in ExtendedManager?`
