### ISSUE TITLE
[False Positive] Argument 3 of preg_match can be nullable

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3451]
Some conversation here https://github.com/vimeo/psalm/pull/3450

https://psalm.dev/r/2cf31156ee

**Comment by muglug** [comment]
Psalm should treat any `&$w_` param as `mixed` for input with an appropriate `@param-out` type inferred. This will require one or two modifications, but shouldn't be too difficult.

**Comment by weirdan** [comment]
No longer reproducible: https://psalm.dev/r/2cf31156ee
