### ISSUE TITLE
password_hash algo param can be string

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#3454]
I get an error on PHP 74 due to this line:

https://github.com/vimeo/psalm/blob/3416e333486e1202035a6620137e1c1c06730144/src/Psalm/Internal/CallMap_74_delta.php#L24

When I add `string` to the `algo` param it goes away. Not sure if this should be necessary, I do not fully understand what the `'new'` and `'old'` sections are for.

**Comment by iluuu1994** [comment]
> can you reproduce the issue on https://psalm.dev?

Nope, the `PASSWORD_ARGON2ID` constant isn't recognized, but this would be the code:
https://psalm.dev/r/8cf9e2fdbc

**Comment by weirdan** [comment]
Does the error go away if you run Psalm with `--php-version=7.4` switch on?

**Comment by iluuu1994** [comment]
> Does the error go away if you run Psalm with --php-version=7.4 switch on?

Yes, that seems to fix it. Since `PASSWORD_ARGON2ID` will return a string or int depending on the PHP version that shouldn't matter though, right?

**Comment by weirdan** [comment]
What is likely happening here:
* Psalm uses constant type from current runtime (string)
* But figures out the minimum supported PHP version from you composer.json, and uses that to access the callmap

**Comment by muglug** [comment]
This appears fixed
