### ISSUE TITLE
Array shape not recognized without key (Unexpected :: in array key)

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#3456]
https://psalm.dev/r/1cba140274

Not sure if this is a bug but if I return shape with ``MyEnum::*`` syntax, psalm is not happy.

Setting a key fixed it but the weird thing is that problem doesn't show when ``string`` is used.

**Comment by andrew-demb** [comment]
AFAIK syntax `array{...}` used to describe some map structure, like this `array{one: int, two: string}`

Instead `array{MyEnum::*}` did you mean `array<MyEnum::*>` ?

**Comment by muglug** [comment]
Yup, this is not valid syntax

**Comment by muglug** [comment]
Valid syntax: https://psalm.dev/r/4da67b2800

**Comment by weirdan** [comment]
I don't think `array<MyEnum::*>` was what @zmitic was after (please confirm), it sound more like `array{0: MyEnum::*}` was desired (but as a tuple). It's still possible to get that form of tuple by using a typedef (https://psalm.dev/r/dad767de1b), so I think this syntax should actually be supported.

**Comment by zmitic** [comment]
>I don't think array<MyEnum::*> was what @zmitic was after (please confirm),

You are right, the issue is that shape requires key **only** when ``MyEnum::*`` is used. It doesn't require key if I use string or anything else. Keep in mind this happens in latest master, wasn't a problem before.

Example:

![image](https://user-images.githubusercontent.com/1964158/82887972-0693cd00-9f49-11ea-9d9f-ac0f0628d0a5.png)

---

The only difference here is the missing key (0) in ``generate_4`` function. But array key is **not** required for strings:

![image](https://user-images.githubusercontent.com/1964158/82888564-c254fc80-9f49-11ea-95d7-9b0501fadb15.png)

https://psalm.dev/r/fd75a45689

That is why I am not sure if this is a bug or unfinished feature that will always require keys for array shapes and not assume indexed values if undeclared (like before).

I.e. if psalm will always require

```@var array{0: string, 1: float}```

and not allow this:

```@var array{string, float}```

**Comment by zmitic** [comment]
@weirdan I created simpler snippet: https://psalm.dev/r/f42096e8f2

Notice that the only difference is the usage of array keys; values are identical and psalm has no problems in detecting ``MyEnum::*`` [wild card syntax (bottom of page)](https://psalm.dev/docs/annotating_code/typing_in_psalm/#specifying-stringint-options-aka-enums) if array has key.

As soon as key is gone, error is reported. Other types (string, int...) don't create errors.

**Comment by alfredbez** [comment]
Stumbled upon the same today, see these examples:
* https://psalm.dev/r/d150ae0c1b (valid)
* https://psalm.dev/r/3a4b488204 (invalid)

**Comment by alfredbez** [comment]
The only change:
```diff
@@ -6,7 +6,7 @@ class Order
     private const STATUS_INVALID = 1;

     /**
-     * @param array{0: self::STATUS_*, string} $status
+     * @param array{self::STATUS_*, string} $status
```
