### ISSUE TITLE
Psalm-internal and direct usage of method from internal class

### ISSUE THREAD

**Issue by skolman** [vimeo/psalm#3457]
https://psalm.dev/r/17f080d422
```
<?php
namespace App\A {
    /**
     * @internal
     * @psalm-internal App\A
     */
    class Foo {
        public static function abc(): int { return 1; }
    }
}

namespace App\B {
    class Bat {
        
        /**
        * @var \App\A\Foo
        */
        public $a;
        
        public function __construct(\App\A\Foo $a)
        {
            $this->a = $a;
        }
        
        public function batBat() :void {
            $a = $this->a->abc();
            $b = \App\A\Foo::abc();
            $c = new \App\A\Foo();
        }
    }
}
```

Psalm returns

```
ERROR: InternalClass - 27:18 - App\A\Foo is marked internal to App\A
ERROR: InternalClass - 28:18 - App\A\Foo is marked internal to App\A
```
and this is fine, but what about the line `$a = $this->a->abc();`? Psalm did not find any issue. Why?

It works fine when I use `@internal` (but namespaces are not completely different)
https://psalm.dev/r/6add224dce

```
<?php
  namespace A {
    /**
     * @internal
     */
    class Foo {
        public static function abc(): int { return 1; }
    }
}

namespace B {
    class Bat {
        
        /**
        * @var \A\Foo
        */
        public $a;
        
        public function __construct(\A\Foo $a)
        {
            $this->a = $a;
        }
        
        public function batBat(): void
        {
            $a = $this->a->abc();
            $b = \A\Foo::abc();
            $c = new \A\Foo();
        }
    }
}
```

Output:

```
ERROR: InternalMethod - 25:28 - The method A\Foo::abc has been marked as internal
ERROR: InternalClass - 26:18 - A\Foo is marked internal to A
ERROR: InternalMethod - 26:18 - The method A\Foo::abc has been marked as internal
ERROR: InternalClass - 27:18 - A\Foo is marked internal to A
```

**Comment by weirdan** [comment]
This: https://psalm.dev/r/a4f18d346f should be marked as error. I think it doesn't matter where the error is generated, could as well be reported at `@var \A\Foo` line and/or constructor.

**Comment by bdsl** [comment]
Hi @skolman - I'll try and take a look at this soon. I'm the original author of the `@psalm-internal` feature. I didn't know until now whether anyone outside my company was using it. As @weirdan pointed out the type annotation at line 16 in the above snippet should also be an error, but as [noted](https://github.com/vimeo/psalm/pull/1623#issuecomment-491529583) in the PR that introduced the feature that isn't currently checked.

As a workaround for now, if you're willing to do extra work in `App\A` to prevent possible mistakes in `App\B` you can change your code to https://psalm.dev/r/969d26e1ac

**Comment by bdsl** [comment]
I just reported several similar issues in report at #3706 .

**Comment by bdsl** [comment]
@muglug I think this can be closed. The original snippet https://psalm.dev/r/17f080d422 now produces four errors.
