### ISSUE TITLE
File based plugins don't get the PluginEntryPointInterface invoked

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#3459]
I'm not sure if this is a bug, or if I'm doing something wrong. I have a file based plugin that is definitely running for some hooks, but not for the PluginEntryPointInterface. Being a file based plugin, the path to my plugin file is specified in my psalm.xml file, which is apparently setup correctly and working as my plugin hooks are running. Here is an example of a plugin that doesn't get invoked in this way. I am using the latest code from Psalm's master branch.

```
namespace Dreamy\PsalmTestsPlugin;

use Psalm\Plugin\PluginEntryPointInterface;
use Psalm\Plugin\Hook\AfterFunctionLikeAnalysisInterface;
use Psalm\Codebase;

class Plugin implements PluginEntryPointInterface, AfterFunctionLikeAnalysisInterface
{
    public function __invoke(\Psalm\Plugin\RegistrationInterface $api, ?\SimpleXMLElement $config = null) {
        throw new \Exception('invoked file plugin wrath');
    }

    public static function afterStatementAnalysis(
        \PhpParser\Node\FunctionLike $stmt,
        \Psalm\Storage\FunctionLikeStorage $classlikeStorage,
        \Psalm\StatementsSource $statementsSource,
        Codebase $codebase,
        array &$file_replacements = []
    ) {
        echo "\nfunction got analyzed\n";
    }
}
```

**Comment by weirdan** [comment]
Yeah, file-based plugins are v2 feature, and dynamic registration was introduced in v3. It's easy to upgrade though. In your case it should be as easy as just replacing the `<plugin>` entry in your `psalm.xml` with `<pluginClass class="Dreamy\PsalmTestsPlugin\Plugin"/>` (assuming the class is autoloadable) and then registering the hooks from that class:
```php
    public function __invoke(\Psalm\Plugin\RegistrationInterface $api, ?\SimpleXMLElement $config = null) {
        $api->registerHooksFromClass(self::class);
    }
```

**Comment by still-dreaming-1** [comment]
@weirdan that worked perfectly and was an easy upgrade for me. Thanks! The documentation seemed to only mention composer plugins and file based plugins. I didn't want to make a composer plugin because at least for now I want it to be in the same project as the code it is analyzing.
