### ISSUE TITLE
Strange RedundantCondition analyzing reference variable

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#346]
I'd expect RedundantCondition to be emitted for `!is_int`, not for `if ($min < $other)`. Simplified case reproducing this:

Edit: Oops, !is_int isn't redundant unless it was placed **before** is_null. I had the same minimum default in the original code.

```php
<?php

/**
 * @param int $min ref
 * @param int $other
 */
function testmin(&$min, int $other) : void {
    if (is_null($min)) {
        $min = 3;
    } elseif (!is_int($min)) {
        $min = 5;
    } else if ($min < $other) {  // Strange RedundantCondition warning here instead of for !is_int
        $min = $other;
    }
}
```

**Comment by weirdan** [comment]
`is_null($min)` is probably redundant as well, as `$min` declared non-nullable here

**Comment by muglug** [comment]
@weirdan yes, but `$min` is only typed in a docblock, and `RedundantCondition` checks ignore docblock-asserted types. The following pattern is very common:

```php
/**
 * @param int $i
 */
function somePublicFunction($i) : void {
  if (!is_int($i)) {
    throw new Exception("bad input");
  }
}
```

**Comment by weirdan** [comment]
So `$min` is `mixed` then? Then why any of those conditions would be redundant?

**Comment by muglug** [comment]
No, it's not `mixed` – it's just that I annotate the type with a `from_docblock` property.

**Comment by muglug** [comment]
Thanks for this!
