### ISSUE TITLE
const not considered non-empty-string if value set concatenating __DIR__

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#3464]
The `__DIR__` throws it off. I tried concatenating a custom const set to either an empty string or a string with characters in it, and those were both fine, but for some reason this example with concatenating __DIR__ throws it off.
https://psalm.dev/r/678b71f78c

**Comment by muglug** [comment]
You can fix this in `MagicConstAnalyzer`

**Comment by still-dreaming-1** [comment]
I guess in my haste, I forgot to actually test this. The example I provided seems to still not work.

**Comment by still-dreaming-1** [comment]
I think the original PR did help to get __DIR__ typed better, but apparently this is a separate issue that has to do with using type inference to type a newly defined const.

**Comment by still-dreaming-1** [comment]
@muglug can you re-open this? I'm guessing you don't normally see these messages for closed issues?

**Comment by weirdan** [comment]
I do see them.

**Comment by still-dreaming-1** [comment]
This issue was mentioned in the latest release, but I just wanted to point out again, I despite improving the types, didn't actually fix this issue. The original example still results in an ArgumentTypeCoercion error. https://psalm.dev/r/678b71f78c

**Comment by weirdan** [comment]
The reason for this is that the types for const initializers are inferred in `SimpleTypeInferer`. PR incoming.
