### ISSUE TITLE
Looks like Psalm doesn't recognize class aliases 

### ISSUE THREAD

**Issue by runtothefather** [vimeo/psalm#3465]
Faced with the issue with fatal error while psalm processing the project, it is failed on the `psalm --init` command when processing the line with class alias definition
the exact example was
```
try {
  //some code
} catch (\Doctrine\Common\Persistence\Mapping\MappingException $e) { -- fatal on this line
}
```

looks like due to class been moved into another namespace, psalm doesn't parse this
tried to simulate situation in the sandbox https://psalm.dev/r/c63cf9ad4b

**Comment by weirdan** [comment]
Also,  this: https://psalm.dev/r/15b31a80cf crashes.

**Comment by BenjaminHoegh** [comment]
Seems like you can trigger the issue if you do this


```
class_alias(class_exists('SomeClassExtra') ? 'SomeClassExtra' : 'SomeClass', 'SomeClassParentAlias');

class SomeClassExtended extends SomeClassParentAlias
{
```
