### ISSUE TITLE
TooManyTemplateParams when extending ArrayObject

### ISSUE THREAD

**Issue by Gladhon** [vimeo/psalm#3466]
If i extend ArrayObject, i geht a TooManyTemplateParams error, while using ArrayObject it self works great.

https://psalm.dev/r/63b9a7736a

```
class A extends ArrayObject{}

/**
 * @return A<int, string>
 */
function a() {
    return new A(['a']);
}

/**
 * @return ArrayObject<int, string>
 */
function a2() {
    return new ArrayObject(['a']);
}


foreach(a() as $b){
    echo $b;
}
foreach(a2() as $b){
    echo $b;
}

**Comment by weirdan** [comment]
To use A as a generic class you need to declare template parameters and pass them to the class being extended (note the A's docblock): https://psalm.dev/r/b5cb6cef68
