### ISSUE TITLE
[False Positive] Unnecessary &static required in typehint

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3470]
I believe this was just a regression introduced in 3.11.5, as one of my tests over @ the laravel plugin just started failing.

https://psalm.dev/r/64c4862e7e

I don't believe the additional `&static` is necessary, since `User` is `final`.

Marking the template as covariant is a workaround

**Comment by muglug** [comment]
The fix is easy, can you figure it out? Hint: it involves the newly-added call to `TypeExpander::expandUnion`

**Comment by mr-feek** [comment]
oooo boy i love a challenge 😉 Yeah ill pr shortly
