### ISSUE TITLE
Ds\Map is unable to infer Key and Value types

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#3472]
```php
use Ds\Map;
use Ds\Vector;

$map = new Map();

foreach ([] as $row) {
    $a = $row['a'];
    $entry = $map->get($a, null);
    if ($entry === null) {
        $entry = new Vector();
        $map->put($a, $entry);
    }

    $entry->push(rand(0, 1));
}
```

For `if ($entry === null) {` psalm thinks
> Found a redundant condition when evaluating docblock-defined type $entry and trying to reconcile type 'null' to null (see https://psalm.dev/156)

However, the return type here is `Vector<int>|null`. Is it possible for psalm to infer it?

------------------

Also similar issue I just found while enabling other IssueHandlers

```php
$map = new Map();
foreach ([] as $_) {
    $map->put('', 1);
}
```

> Argument 1 of Ds\Map::put expects empty, string() provided
> Argument 2 of Ds\Map::put expects empty, int(1) provided

Most of Map methods have such issue.

**Comment by simPod** [comment]
Maybe we need something like https://github.com/phpstan/phpstan-src/blob/master/src/Type/Php/DsMapDynamicReturnTypeExtension.php?

**Comment by simPod** [comment]
Yes, it seems that before it always expected `T|null` instead of `T`.

**Comment by enumag** [comment]
Which version of Psalm are you using? There were some fixes related to `Ds\Map::get()` recently:

https://github.com/vimeo/psalm/pull/3412
https://github.com/vimeo/psalm/issues/3423
https://github.com/vimeo/psalm/issues/3453

They should all be in `v3.11.5` though.

**Comment by simPod** [comment]
I bumped from 3.11.2 to 3.11.5 and the issue from initial snippet is present there.

**Comment by weirdan** [comment]
> Argument 1 of Ds\Map::put expects empty, string() provided
> Argument 2 of Ds\Map::put expects empty, int(1) provided

This is indicative of general issue with types inferred from empty array, which is also present with other collection generics (like Doctrine Collections). This is usually worked around by adding explicitly typed `@var` docblock to collection initialization: https://psalm.dev/r/57299077c6

**Comment by simPod** [comment]
@weirdan I wanted to avoid typing each data structure in my app explicitly. I thought psalm could know what types are contained in the structure from types of values going in.

**Comment by enumag** [comment]
@simPod That can't work of course. And it doesn't make sense either. The type inference works only when initializing the collection using the initial values. Of course when you create an empty collection then the type is unknown. If it could add any type later then you could call Map::put() with different types each time by accident and instead of getting an error you would only grow the internal type of the Map.

**Comment by muglug** [comment]
Yeah, the only thing I could think of would be to use the first assignment to set the type, but even that’s tricky - what if it happens in a conditional, for instance?

Until PHP adds native support for generics this will continue to be a grey area that can only be overcome with docblocks.

**Comment by simPod** [comment]
Makes sense, thanks!
