### ISSUE TITLE
Allow int[] for str_replace

### ISSUE THREAD

**Issue by thomasbley** [vimeo/psalm#3475]
After upgrade from 3.11.4 to 3.11.5 I get errors for str_replace using int[] array.

Checking the docs https://www.php.net/str_replace I'm not sure we should force arrays to be string?

I'm proposing to allow using int[] in str_replace.

example: https://psalm.dev/r/c9c73429c8

**Comment by thomasbley** [comment]
maybe this definition of str_replace is better:

```
/**
 * @param string|array $search
 * @param string|array $replace
 * @param string|array $subject
 * @param int $count
 * @return ($subject is array ? array : string)
 */
function str_replace($search, $replace, $subject, &$count = null) {}
```

**Comment by muglug** [comment]
Hmmm I'm actually very surprised that none of this results in a type error:

```php
<?php declare(strict_types=1);

$result = str_replace([1, 3], ['one', 'three'], [1, 3]);
var_dump($result);
$result = str_replace(1, 2, [1, 3])
var_dump($result);
```
