### ISSUE TITLE
Nested templated inferenced return type wrongly compares against internal type representation

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#3479]
https://psalm.dev/r/01089383cc

I know you love template-related bugs.
Reproduces on each 3.11.x version, didn't try lower ones though.

**Comment by weirdan** [comment]
Everybody loves them. However I'm not exactly sure it's a bug. `Foo` is invariant over `T`, so returning `Foo<Params<1>>` where `Foo<Params<int>>` was promised looks like a violation. Unless we ignore literal types for template inference purposes - but templates based on literal types look useful.

Declaring T for Foo to be covariant (`@template-covariant T`) silences the error, if you can allow Foo to be covariant. 

@muglug what do you think?

**Comment by someniatko** [comment]
@weirdan now look where the hands go https://psalm.dev/r/405cda9520

**Comment by someniatko** [comment]
So the issue here is that cases like `int <-> int literal` are made "auto-covariant", but case with `Params<int> <-> Params<int literal>` was not considered.

**Comment by weirdan** [comment]
One of those looks like a bug to me. Not sure which one exactly, though.

**Comment by orklah** [comment]
First two examples doesn't emit an issue anymore so I'll close this. Feel free to reopen with the last example if it's still an issue for you
