### ISSUE TITLE
Linux: memory isn't shared across processes when forking

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#3486]
Not sure how widespread this is, but [received a report](https://twitter.com/Majkl578/status/1266404101262200833) (reproduced by a colleague) that Psalm's forked processes don't share memory on Gentoo Linux and Ubuntu.

When running Psalm on a mac (on its own source-code) memory is shared effectively.

**Comment by muglug** [comment]
@Majkl578 check out https://github.com/vimeo/psalm/tree/debug-forking and tell me what you see when you run Psalm.

**Comment by Majkl578** [comment]
Here you go, Psalm analysing itself: <details>
<summary>Result</summary>

```
$ ./psalm
Scanning files...
Analyzing files...

366.875 of 451.941
366.879 of 451.942
366.875 of 451.941
366.883 of 451.942
366.879 of 451.942
366.89 of 451.943
366.896 of 451.943
366.883 of 451.942
366.89 of 451.942
366.896 of 451.942
366.906 of 451.943
366.913 of 451.943
366.906 of 451.943
366.913 of 451.943
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  60 / 864 (6%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 120 / 864 (13%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 180 / 864 (20%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 240 / 864 (27%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 300 / 864 (34%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░E░░░░░░░░░░░░░░░░░░░░░░░ 360 / 864 (41%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 420 / 864 (48%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 480 / 864 (55%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 540 / 864 (62%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 600 / 864 (69%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 660 / 864 (76%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 720 / 864 (83%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 780 / 864 (90%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 840 / 864 (97%)
░░░░░░░░░░░░░░░░░░░░░░░░

ERROR: ForbiddenCode - src/Psalm/Internal/Fork/Pool.php:430:36 - Unsafe shell_exec (see https://psalm.dev/002)
        $totes_aux = explode("\n", \shell_exec('ps ax -o pid,rss | grep ' . \posix_getpid()) ?: '');


------------------------------
1 errors found
------------------------------
37 other issues found.
You can display them with --show-info=true
------------------------------

Checks took 13.55 seconds and used 570.017MB of memory
Psalm was able to infer types for 99.8576% of the codebase

```

</details>

**Comment by muglug** [comment]
so that does look like a problem with the underlying language/system. @TysonAndre have you seen anything similar in Phan?

**Comment by TysonAndre** [comment]
I haven't seen anything like that reported, but it's possible it's affected. Does psalm fork after everything is parsed or before it's parsed? What's the memory usage when using a single process?

**Comment by weirdan** [comment]
> When running Psalm on a mac (on its own source-code) memory is shared effectively.

What's the expected output of those echos, i.e. what do you see on mac?

**Comment by muglug** [comment]
> What's the expected output of those echos, i.e. what do you see on mac?

When running on a Mac (and on CentOS running in Docker on a Mac) you see the first number being a fraction of the second.

On some linux installations the numbers are essentially equivalent the whole time.

**Comment by TysonAndre** [comment]
Also, psalm stores the union types in files it analyzes on the PhpParser\Node instances, which might lose some of the benefits of copy-on-write for analysis.

Phan also adds a lot to `ast\Node`.

----

> When running on a Mac (and on CentOS running in Docker on a Mac) you see the first number being a fraction of the second.


Maybe it depends on the number of bytes in the pages being shared between processes?

**Comment by muglug** [comment]
> Does psalm fork after everything is parsed or before it's parsed?

It forks after everything is parsed, but the parsed sources aren't kept in memory.

> What's the memory usage when using a single process?

About 500MB

**Comment by TysonAndre** [comment]
Still seeing more memory usage per-process than shared if I'm reading this right - not an expert on this.

https://en.wikipedia.org/wiki/Page_(computer_memory)#Determining_page_size
![Screenshot_2020-05-29_16-19-39](https://user-images.githubusercontent.com/1904430/83302277-07d32d00-a1c9-11ea-80c3-1382b2e394d9.png)

**Comment by muglug** [comment]
It looks like Phan has the same issue (if that's on Linux)

Running Psalm with the latest (less buggy) version of `debug-forking`

On Linux running in 5 forks:
```
479 of 456.844
479 of 456.845
479 of 456.845
479 of 456.845
479 of 456.845
```

on Mac running on the same:

```
8.703 of 544.104
8.691 of 544.105
8.691 of 544.103
8.711 of 544.104
8.68 of 544.105
```

**Comment by TysonAndre** [comment]
https://stackoverflow.com/a/7734509 and the above response suggest that **the way Mac OS reports resident set size might just be more intuitive** at a glance. Proportionate set size might be more useful, but not readily available

**Comment by muglug** [comment]
I'm running Psalm in a Linux docker container and seeing this large chunk of dirty shared memory when calling `echo shell_exec('cat /proc/' . posix_getpid() . '/smaps');` immediately after forking:

Reproduced more simply with

```
<?php
ini_set('memory_limit','1024M');
$a = [];

for ($i = 0; $i < 1000000; $i++) {
    $a[] = "$i";
}

$pid = pcntl_fork();
if ($pid == -1) {
     die('could not fork');
} else if ($pid) {
     // we are the parent
     pcntl_wait($status); //Protect against Zombie children
} else {
    if (PHP_OS === 'Linux') {
        // extra debugging for Linux
        echo shell_exec('cat /proc/' . posix_getpid() . '/smaps');
    }
    sleep(200);
}
```

Here

**Comment by muglug** [comment]
Filed here: https://bugs.php.net/bug.php?id=79660, will close because it's something that I can't fix.

**Comment by TysonAndre** [comment]
I'm confused by the example. Is this *caused* by the use of shell_exec? Does the same issue occur if you use file_get_contents() and to read the contents of /proc/posix_getpid()/smaps?

**Comment by muglug** [comment]
> Does the same issue occur if you use file_get_contents() and to read the contents of /proc/posix_getpid()/smaps?

Yeah, I just checked and the same regions of memory are listed as dirty

**Comment by Majkl578** [comment]
@muglug Do you plan to implement some workaround for this? E.g. PHPStan has no problems on Linux and works quite well in parallel mode. The PHP issue you created seems to not interest anyone as it's quite OS-/system-specific and even when fixed it won't solve the issues for people on older PHP versions (luckily not me). :S

**Comment by muglug** [comment]
I've closed the PHP bug report because I was just confused about Linux memory differences to MacOS.

I've added some better logging to the `debug-forking` branch that should show all `_Dirty` memory both prior to forking, after forking for analysis, and right before the forked process reports back to the parent.

`Private_Dirty` memory in the parent should transition to `Shared_Dirty` in the child.

**Comment by muglug** [comment]
The plot thickens: could not reproduce locally on Docker locally on a Mac, but _can_ reproduce a Psalm-specific failure in GitHub Actions: https://github.com/vimeo/psalm/runs/751766554

**Comment by muglug** [comment]
I'm pretty sure this is caused by GitHub Actions itself. I can't reproduce the behaviour (shared memory becoming private after forking) on any Linux box outside of GitHub Actions.

**Comment by muglug** [comment]
If anyone else on Linux wants to try, this is the expected output from that fork:

```
 ./psalm --threads=2
Scanning files...
Before:

Priv: 96444 kB  Shared: 0 kB

Analyzing files...

Before:

Priv: 550032 kB  Shared: 0 kB

Priv: 0 kB  Shared: 549928 kB
Priv: 0 kB  Shared: 549928 kB
Priv: 0 kB  Shared: 548688 kB
Priv: 0 kB  Shared: 549872 kB
░Priv: 0 kB  Shared: 548672 kB
Priv: 0 kB  Shared: 548660 kB
░Priv: 0 kB  Shared: 548392 kB
░Priv: 0 kB  Shared: 548324 kB
░Priv: 0 kB  Shared: 548324 kB
...
```

**Comment by muglug** [comment]
And actual output: 

```
Analyzing files...

Before:

Priv: 628736 kB  Shared: 0 kB



Priv: 28672 kB  Shared: 600064 kB
Priv: 26624 kB  Shared: 602112 kB
Priv: 83968 kB  Shared: 544768 kB
Priv: 83968 kB  Shared: 544768 kB
Priv: 81920 kB  Shared: 546816 kB
Priv: 86016 kB  Shared: 542720 kB
Priv: 126976 kB  Shared: 501760 kB
```

**Comment by weirdan** [comment]
For me, it's `Priv: 0` for the most of the run, but it reverses at about 80-90%:
```
░Priv: 0 kB  Shared: 597900 kB
░Priv: 0 kB  Shared: 597900 kB
░Priv: 0 kB  Shared: 597900 kB
░Priv: 0 kB  Shared: 597900 kB
░Priv: 0 kB  Shared: 597900 kB
░Priv: 34948 kB  Shared: 572260 kB
░Priv: 53396 kB  Shared: 553564 kB
░ 720 / 864 (83%)
Priv: 70576 kB  Shared: 536324 kB
░Priv: 87704 kB  Shared: 519196 kB
░Priv: 96404 kB  Shared: 501112 kB
░Priv: 125108 kB  Shared: 481244 kB
░Priv: 272012 kB  Shared: 326208 kB
░Priv: 409236 kB  Shared: 198936 kB
░Priv: 608172 kB  Shared: 0 kB
░Priv: 608172 kB  Shared: 0 kB
░Priv: 608172 kB  Shared: 0 kB
░Priv: 608172 kB  Shared: 0 kB
```

**Comment by weirdan** [comment]
It depends on number of subprocesses Psalm starts - with 4 it's `Priv: 0` till the end, and with anything above that `Shared` drops to zero soon after the start.

**Comment by muglug** [comment]
> For me, it's Priv: 0 for the most of the run, but it reverses at about 80-90%:

I think that was just down to a bug in the debugging – I moved it into the file analysis loop, and it now looks the way I'd expect (previously it was executing after the job had returned and as the processes were wrapping up, I think.

**Comment by muglug** [comment]
My hunch is that, in terms of physical memory, GitHub Actions is severely resource-constrained and penalises programs that attempt to share memory (as Psalm does when running in multiple processes).

If anyone can reproduce outside GHA I'll take a second look.

**Comment by muglug** [comment]
Also @bendavies, Github Actions VMs currently only have [2 CPUs allotted](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources), and Psalm will not fork there by default. I recommend not using `--threads` option in GitHub Actions.

**Comment by bendavies** [comment]
Quite. We use 1 thread and it's fine now
