### ISSUE TITLE
Template on abstract class and interface

### ISSUE THREAD

**Issue by matiux** [vimeo/psalm#3488]
I'm in this situation:
`Interface  -> abstract class  -> concrete class`
`EntityId      -> BasicEntityId   -> TestId`

```
/**
 * @template T
 */
interface EntityId
{
    /**
     * @psalm-return T
     */
    public static function create();

    public function id(): string;
}

/**
 * @template T of BasicEntityId
 * @template-implements EntityId<T>
 */
abstract class BasicEntityId implements EntityId
{
    private $uuid;

    public function __construct(string $uuid)
    {
        $this->uuid = $uuid;
    }

    public static function create()
    {
        return new static(Uuid::uuid4()->toString());
    }

    public function id(): string
    {
        return $this->uuid;
    }
}

/**
 * @template-extends BasicEntityId<TestId>
 */
class TestId extends BasicEntityId
{
}
```

Then let's say I have an Entity that accepts a TestId:

```
class Entity
{
    private $entityId;

    public function __construct(TestId $entityId)
    {
        $this->entityId = $entityId;
    }

    public static function create(TestId $entityId): self
    {
        return new static($entityId);
    }
}
```

And finally I create an entity:

`Entity::create(TestId::create());`

In this point psalm logs only one error:

```
ERROR: InvalidReturnStatement
The inferred type 'BasicEntityId<BasicEntityId>' does not match the declared return type 'T:BasicEntityId as BasicEntityId' for BasicEntityId::create (see https://psalm.dev/128)

return new static(Uuid::uuid4()->toString());
``` 

I'm struggling to figure out how to solve and I don't understand if the problem is `new static` or the template annotation. I have try to implement interface directly in concrete `TestId` in this way:

```
/**
 * @template-implements EntityId<TestId>
 */
class TestId implements EntityId
{
    private $uuid;

    public function __construct(string $uuid)
    {
        $this->uuid = $uuid;
    }

    public static function create()
    {
        return new static(Uuid::uuid4()->toString());
    }

    public function id(): string
    {
        return $this->uuid;
    }
}

```

and creating the Entity in the same way works fine

`Entity::create(TestId::create());`

no problem

This makes me think that the problem is not `new static` but the way I implemented the template annotation in the abstract class. 
What do you think about this?

I have reproduced the problem here: https://psalm.dev/r/1867083f1f

**Comment by weirdan** [comment]
Hey @psalm-github-bot, you missed this:
  https://psalm.dev/r/1867083f1f

**Comment by weirdan** [comment]
`BasicEntityId` appears to be a recursive type, and Psalm does not support recursive types. 

What you're trying to achieve though?

**Comment by matiux** [comment]
@weirdan I have an `EntityId` intended as a concept (the interface). Then I have an abstract class to have some basic behaviors (BasicEntityId class) since that what changes in the concrete Id (TestId class) is only the name (the type)

**Comment by weirdan** [comment]
Recursive type is a type that refers to itself, e.g. `BasicEntityId<T of BasicEntityId>`

I wonder why do you need generics here, and what problem you are solving by introducing generics.

**Comment by matiux** [comment]
I'm trying to use generics to solve this problem https://psalm.dev/r/8a357f83f5

How you can see, before to use psalm, I was strict return type in my interface.

Although the runtime code worked, the ArgumentTypeCoercion error occurred

**Comment by matiux** [comment]
@weirdan how you can see, with generics works fine https://psalm.dev/r/795ef4295b

But I'd like to have an abstract class in the middle

**Comment by weirdan** [comment]
That specific problem is solved with a single docblock: https://psalm.dev/r/759ccf3315
You probably want `@return static` on `Entity::create()` as well. 
In PHP8 you will be able to use `static` as a native return type.

**Comment by matiux** [comment]
Amazing! only one line to solve my problem. I struggled with it for days...

I know the new feature of php 8 but this code is part of a library that needs to work with php >= 7.2

Thank you so much.
I think that I will write again for other "problems" :)
