### ISSUE TITLE
replace composer/composer dependency with composer/xdebug-handler

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#349]
Now that composer/composer#6802 is implemented Psalm could drop `composer/composer` (huge dependency) and replace it with `composer/xdebug-handler`

I'll do PR soon enough.

**Comment by johnstevenson** [comment]
I'd wait until we have cut the first release if I were you. It has only just been decoupled from Composer, so there will be breaking changes.

**Comment by weirdan** [comment]
Of course, that's why PR is marked [wip] (and mentions "don't merge, wait for release" in its message).
