### ISSUE TITLE
Discussion: extending base (primitive) types

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#3490]
Now as types importing was implemented in the v3.11.5 I think it opens opportunity to implement even more expressive type system if a new concept of extending primitive types was introduced.

An example of how it could be useful:

```php
<?php

/**
 * @psalm-type email=extends string
 */
 
/**
 * @psalm-assert email $value
 * @param mixed $value
 */
function isEmail($value): void {}
 
/**
 * @param email $address
 * @param string $message
 */
sendMessage(string $address, string $message): void {}
```

So in this example `email` type would be assignable to both `email` and `string`.

Another example

```php
<?php

/**
 * @psalm-immutable
 * @psalm-type id=extends int
 */
class User
{
    /** @var id */
    public int $id;
}

/**
 * @psalm-immutable
 * @psalm-type id=extends int
 */
class Article
{
    /** @var id */
    public int $id;
}

$article->id = $user->id; // type check violation
```

Because `User::id` and `Article::id` are of different types (incompatible by default, but assertable if necessary) - the last line won't pass a type check.

It could also generalise special cases like `lowercase-string`.

Thoughts?

**Comment by Ocramius** [comment]
Very interesting! in Haskell, this is called a `newtype`

**Comment by orklah** [comment]
It could be interesting to document legacy code that can't be refactored easily. But at the same time, it seems to share the same use case as a value object. Not sure if the PHP ecosystem will improve in the long term if we replace immutable value objects by checks in static analysis

**Comment by zerkms** [comment]
> if the PHP ecosystem will improve in the long term if we replace immutable value objects by checks in static analysis

If those are just wrappers over scalar types - they only exist there because there was no other mechanism to implement it safely.

**Comment by marcosh** [comment]
@Ocramius these are a bit different than Haskell `newtype`s, since there you don't have to care about inheritance.

Newtypes are actually more similar to a simpler composition like

```
class Foo
{
    /** @var int */
    private $int;

    public function __construct(int $int)
    {
        $this->int = $int
    }

    public function int()
    {
        return $this->int;
    }
}
```

regarding the proposal, it could be interesting, but I think it could lead to issues (you'll need to refactor) as soon as you want to add behaviour to an inherited type

**Comment by BruceGitHub** [comment]
> Very interesting! in Haskell, this is called a `newtype`
Also in c# extension method

**Comment by muglug** [comment]
This is very similar to https://github.com/Microsoft/Typescript/issues/202 but, unlike TypeScript, Psalm cannot support add support at the PHP language level, so I don't think this is very practical. For example, you'll never be able to do

```php
if ($foo is email) {}
```

Instead you'd have to do something like 

```php
if (isEmail($foo)) {}
```

with

```php
/** @psalm-assert email-string */
function isEmail(string $s) : void {}
```

But I also think this pattern is going a bit too far in the Haskelly direction. Though I can see the benefit from a typing perspective – turning logic errors into type errors – I'm wary of developing features for a select few that increase the overall maintenance burden (computing unions of strings is already complex, this would make it much more so).

**Comment by muglug** [comment]
I said more or less the same thing here: https://github.com/vimeo/psalm/issues/2656#issuecomment-575686091

**Comment by leighman** [comment]
Would it be possible to allow intersection on primitive types instead which would allow something like TS brands?
```
/**
 * @psalm-type Email string & EmailBrand
 */
class EmailBrand {}
```

**Comment by muglug** [comment]
No - intersections are only possible on objects

**Comment by githoober** [comment]
I cannot find @psalm-type in the documentation.

**Comment by XedinUnknown** [comment]
Is this idea completely abandoned? It sounds very useful!
