### ISSUE TITLE
Add prevention of dynamic type reassignment

### ISSUE THREAD

**Issue by githoober** [vimeo/psalm#3498]
It would be nice to have a check that prevents a dynamic type reassignment, something PHP will probably never do. See the following snippet:

https://psalm.dev/r/b9db3b1006

Psalm would make reassignments in the example above  from a string value to an int value and from object A value to object B value illegal.

kalessil/phpinspectionsea already does that: https://github.com/kalessil/phpinspectionsea/blob/master/docs/architecture.md#callable-parameter-usage-violates-definition

**Comment by muglug** [comment]
This goes strongly against PHP's dynamic nature – not sure how on board people would be with this.

**Comment by githoober** [comment]
PHP 7.4 has added typed properties. Don't they go against PHP's dynamic nature?

**Comment by muglug** [comment]
Not really, because properties have a well-known precedent (in existing PHP code) that they store things of a single type. Variables have no such precedent.

BUT Psalm also does have this functionality for pass-by-reference variables – this is an error:

```php
/**
 * @return void
 */
function test(string &$string) {
    $string  = 6;
}
```

https://psalm.dev/r/7743d3176d

**Comment by githoober** [comment]
Are you referring to locally declared variables or function or method parameters? I would argue that typed parameters also have a precedent of holding a value of only one type.

It would have been nice to have more people commenting on this proposal.

**Comment by muglug** [comment]
Sorry, but this is just one of those things where four years of working on Psalm has given me a pretty firm idea of the directions it should and shouldn’t progress.

Psalm is designed to identify bugs in PHP code. Where it checks things (like functional purity) which aren’t necessarily directly related to catching bugs, they can all be tied back to that aim. This request, as far as I can tell, would not allow Psalm to catch any bugs it cannot already detect.

**Comment by githoober** [comment]
@muglug it's your prerogative of course.

Below is a somewhat contrived example where two unrelated class variables are swapped inside the function body. This causes an improper answer captured. Psalm, as currently designed, cannot detect such invalid type bugs as there is no any call in the method body to any other methods that can help Psalm verify the class variable type. 
 
https://psalm.dev/r/556a766367
