### ISSUE TITLE
How to annotate array MixedArgument

### ISSUE THREAD

**Issue by matiux** [vimeo/psalm#3500]
I'm in a situation like this:

https://psalm.dev/r/4d04a0cb80

I have a function that returns a multidimensional array, where each child array has is like this: array<array-key, mixed>. 

Specifically, I'm running a unit test:

```
function read(): array {
    return [
                [
                'name' => 'Mat',
                'age' => 34
            ]
    ];
}


$data = read();

self::assertCount(1, $data);
self::assertArrayHasKey('name', $data[0]);
```

So I have tried to annotatefunction the function in this way:

```
@psalm-return list<array<string,mixed>>
@psalm-return array<int, array<string,mixed>>
@psalm-return list<ArrayAccess|array<array-key, mixed>>
```

But I get still the MixedArgument error or MixedArrayAccess error

**Comment by orklah** [comment]
You can use
https://psalm.dev/r/6b1efdd467

If you want, Psalter with Issue LessSpecificReturnType should fill those for you, it should help understanding the full panel of notations :)

**Comment by matiux** [comment]
@orklah the array doesn't contain always the same keys. I would need of a generic annotation

**Comment by orklah** [comment]
Then you can use something like that:
https://psalm.dev/r/7291a0086b

But you will be reminded that you have to check for "name" offset existence

**Comment by matiux** [comment]
@orklah nothing to do.
If you want this is my code https://pastebin.com/vDht5CEJ

and this is the errors:

```
ERROR: MixedArrayAccess - Cannot access array value on mixed variable $transformed (see https://psalm.dev/051)
        self::assertArrayHasKey('name', $transformed[0]);


ERROR: MixedArgument - Argument 2 of assertArrayHasKey cannot be mixed, expecting ArrayAccess|array<array-key, mixed> (see https://psalm.dev/030)
        self::assertArrayHasKey('name', $transformed[0]);


ERROR: ImplementedReturnTypeMismatch - The inherited return type 'R:collectiondatatransformer::read as mixed' for CollectionDataTransformer::read is different to the implemented return type for PeopleDataTransformer::read 'list<array<array-key, mixed>>' (see https://psalm.dev/123)
    /** @psalm-return list<array<array-key, mixed>> */
```

**Comment by orklah** [comment]
Well, basically, your issue is that you keep "mixed" in the annotation.

As long as you have a mixed value and you try to access it, you will get a Mixed error.

If there is no way you can be more precise about the type in your array, then you'll always have a Mixed error here. It's okay however, Mixed issues must be the strictest rules Psalm will check and you have to design your system very carefully from the start to be sure there are none...

**Comment by matiux** [comment]
So, in this specific case, the only thing that I can do is to suppress the error, right?

**Comment by weirdan** [comment]
Assuming your version of PHPUnit includes `@psalm-assert` tags, or you're using [PHPUnit Psalm plugin](https://packagist.org/packages/psalm/plugin-phpunit) you should be able to use assertions like this: https://psalm.dev/r/2fc5e72d26
