### ISSUE TITLE
Don't emit UnresolvableInclude after a file_exists check

### ISSUE THREAD

**Issue by koriym** [vimeo/psalm#3502]
```php
require foo('a.php');

function foo(string $s) : string
{
    assert(file_exists($s));
    return $s;
}
```
Expected: No issue
Actual: UnresolvableInclude

Related: #908

**Comment by koriym** [comment]
I can't reproduce the issue on https://psalm.dev .

https://psalm.dev/r/c375852247

```
Psalm runner output: 

Internal Psalm error on line 3730 - /vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php: File includes are not allowed per your Psalm config - check the allowFileIncludes flag.
```

**Comment by muglug** [comment]
This error says that Psalm can’t figure out what file is being included. It’s not really a bug, just Psalm saying “I want to know what’s happening in this file, but I can’t figure out what’s in it.
