### ISSUE TITLE
Implementing interfaces with @return static

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#3504]
What should be the type of `@return` for methods implementing `@return static` from interfaces? (https://psalm.dev/r/f87cbc4bed)

```
interface I {
    /**
     * @return static
     */
    public function f();
}

class C implements I {
    /**
     * @return ?
     */
    public function f() {
        return new self;
    }
}
```

For `@return static`:

> INFO: LessSpecificReturnStatement - 15:16 - The type 'C' is more general than the declared return type 'C&static' for C::f
> INFO: MoreSpecificReturnType - 12:16 - The declared return type 'C&static' for C::f is more specific than the inferred return type 'C'

For `@return self`:

> ERROR: LessSpecificImplementedReturnType - 12:16 - The inherited return type 'I&static' for I::f is more specific than the implemented return type for C::f 'C'

For `@return I`: 

> ERROR: LessSpecificImplementedReturnType - 12:16 - The inherited return type 'I&static' for I::f is more specific than the implemented return type for C::f 'I'

For `@return C`:

> ERROR: LessSpecificImplementedReturnType - 12:16 - The inherited return type 'I&static' for I::f is more specific than the implemented return type for C::f 'C'

I cannot change the definition of `I` as this is part of a PSR: https://github.com/php-fig/http-message/blob/efd67d1dc14a7ef4fc4e518e7dee91c271d524e4/src/ServerRequestInterface.php#L258

**Comment by weirdan** [comment]
I think `self` and `C` should work for final classes, and `static` should work for any. `I` is not specific enough.

**Comment by muglug** [comment]
Two acceptable answers: https://psalm.dev/r/d6ced269a9

**Comment by muglug** [comment]
Here's where allowing `@return C` would result in a fatal error: https://psalm.dev/r/0779bd1b14
