### ISSUE TITLE
trigger_error not recognized as a stop method for E_USER_ERROR?

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#3508]
For this example:
https://psalm.dev/r/713225fb77

I'd have expected the trigger_error case to behave like the others. The function will never return so the return type is irrelevant. However, this pattern can be used to force a child class to redefine the method and still force return type.

**Comment by weirdan** [comment]
The code after `trigger_error()` may still be executed if error handler returns `true` and does not abort the execution: https://3v4l.org/V5Bhl

**Comment by orklah** [comment]
You're right. Misteries of PHP :)

Is there a way to redeclare formally that it won't for a given project?

**Comment by weirdan** [comment]
This could work in a stub: https://psalm.dev/r/3938d4a2b0

Of course something like this would be much nicer: https://psalm.dev/r/9ab24a9316

**Comment by orklah** [comment]
> This could work in a stub: https://psalm.dev/r/3938d4a2b0
> 
> Of course something like this would be much nicer: https://psalm.dev/r/9ab24a9316

I'm not sure if you wanted to say that it's intended for Psalm to consider trigger_error as returning because it "may" happen, in this case, the stub should be somewhere in our project (plugin?), or if you just said that this was not yet handled by Psalm and we could push a PR with the stub.

But yeah, the stub should have been obvious to me! I didn't consider it at all, probably thought that trigger_error was more a language keyword rather than a standard function...

I agree, your second stub seem nicer, not sure what it would take to implement that.

I'm not sure you needed to use templates again for conditional. It look nicer without it: https://psalm.dev/r/e0168f02c8

**Comment by weirdan** [comment]
>  in this case, the stub should be somewhere in our project (plugin?)

Yeah, as it's specific to your project the stub have to be external to Psalm. 

> I agree, your second stub seem nicer, not sure what it would take to implement that.

I started with a separate ticket.

**Comment by orklah** [comment]
I'll close this, there is nothing else to be done on psalm itself
