### ISSUE TITLE
Referring to constants in literal types

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#3509]
Following up from #3508 
https://psalm.dev/r/7db75df29f - here Psalm fails to use free-standing constants in literal types

**Comment by muglug** [comment]
Unfortunately these are all valid classnames, so Psalm can't allow this: https://3v4l.org/qhRNZ

**Comment by weirdan** [comment]
I understand the preference for class names where they cannot be syntactically distinguished from constants , but could there be some special syntax, to say 'I actually want this constant'? Something along the lines of `const-value<E_USER_ERROR>` or similar?
