### ISSUE TITLE
Mark union types of magic properties, etc. as being from a docblock?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#351]
E.g. `@property`, `@method`, etc. Those are technically from docblocks, and can be other types without a TypeError.

This would reduce false positive RedundantCondition issues in my use case - A magic property getter for a frequently used class will almost always return a (cached) certain type, unless the database is down and an unexpected exception was thrown

- RedundantCondition is more conservative about types created from docblocks.

This is doable for `@property` with something like the following patch (will need to fix conflicts with the property-read patch):

```
--- a/src/Psalm/Visitor/DependencyFinderVisitor.php
+++ b/src/Psalm/Visitor/DependencyFinderVisitor.php
@@ -220,6 +220,7 @@ class DependencyFinderVisitor extends PhpParser\NodeVisitorAbstract implements P
                             $pseudo_property_type = Type::parseString($property['type']);
+                            $pseudo_property_type->setFromDocblock();
 
                             $storage->pseudo_property_set_types[$property['name']] = $pseudo_property_type;
                             $storage->pseudo_property_get_types[$property['name']] = $pseudo_property_type;
```

**Comment by muglug** [comment]
Great catch
