### ISSUE TITLE
`ignoreInternalFunctionFalseReturn` default value

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#3517]
The docs https://psalm.dev/docs/running_psalm/configuration/#ignoreinternalfunctionfalsereturn and the xsd https://github.com/vimeo/psalm/blob/master/config.xsd#L47 claim its default value is `false`.

But it looks like it's the opposite.

**Comment by weirdan** [comment]
https://github.com/vimeo/psalm/blob/0e298a6f13292439be2a126958994086e0769bd3/src/Psalm/Config.php#L327-L330

**Comment by weirdan** [comment]
Looks like a documentation bug to me.
