### ISSUE TITLE
Don't emit RedundantCondition for closure use variables passed by reference?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#352]
Commonly, they're unanalyzable and the reference may be modified after being passed to the closure.

(E.g. if a variable is null, it may be set to a value later on)

**Comment by muglug** [comment]
Do you have an example?

**Comment by weirdan** [comment]
Something like this, I imagine, which fails with "expecting string|null, int provided", while it's not int but null:
```php
function s(?string $p): void {}

$var = 1;
$callback = function() use(&$var): void {
    s($var);
};
$var = null;
$callback();
```

**Comment by TysonAndre** [comment]
Yes, pretty similar to that.

```php
<?php
$var = null;  // a workaround would be annotating as int|null
$callback = function() use(&$var): void {
    if ($var) {
        echo "Got $var\n";  // Unexpected 'RedundantCondition - Found a redundant condition when evaluating $var'
    }
};
$var = 1;
$callback();
```

**Comment by muglug** [comment]
Have cleared away enough leaves now to see this popping up in our own codebase. Easiest solution is just to type those variables to `mixed`.
