### ISSUE TITLE
`--set-baseline` always adds to default config

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#3521]
Running `psalm --config=blah.xml --set-baseline=blah-baseline.xml` I would expect the baseline reference to be added to `blah.xml` but it's added to `psalm.xml`

**Comment by muglug** [comment]
This should be easy to fix in src/psalm.php

**Comment by muglug** [comment]
Mind creating a PR?

**Comment by leighman** [comment]
Just had a quick look and what's there looks correct 😅. Maybe I imagined it. Will have another try
