### ISSUE TITLE
composer/semver: ^1.4 || ^2.0 || ^3.0

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#3524]
Currently `vimeo/psalm` requires `composer/semver` `^1.4`, but [it seems](https://github.com/vimeo/psalm/search?q=semver&unscoped_q=semver) as only `Semver::satisifies` is used, whose behaviour does not seem to have changed in `composer/semver` [2.0.0](https://github.com/composer/semver/releases/tag/2.0.0) or [3.0.0](https://github.com/composer/semver/releases/tag/3.0.0).

Would it be possible to update the `composer.json` accordingly?

**Comment by muglug** [comment]
Please create a PR!

**Comment by caugner** [comment]
Note: As soon as the next `paratest` version is released (which won't depend on `composer/semver` anymore), updating that dependency will effectively make `psalm` compatible with `semver` 2/3.
