### ISSUE TITLE
Psalm reports it cannot assign an array to a declared type

### ISSUE THREAD

**Issue by githoober** [vimeo/psalm#3526]
https://psalm.dev/r/3ab796cc44

```
<?php

interface EntityInterface {};

class EntityOne implements EntityInterface{};
class EntityTwo implements EntityInterface{};
class EntityThree implements EntityInterface{};

class Type {
    const TYPE_1 = 'type_1';
    const TYPE_2 = 'type_2';
    const TYPE_3 = 'type_2';
}

/**
* @template EI of EntityInterface
*/
class Map {
    /**
    * @var array<class-string<EI>, string>
    */
    private static $map = [
        EntityOne::class => Type::TYPE_1,
        EntityTwo::class => Type::TYPE_2,
        EntityThree::class => Type::TYPE_3,
   ];
}
```
Without the template declaration, it works fine. With the template,  I am getting: 

```
ERROR: UndefinedDocblockClass - 20:12 - Docblock-defined class or interface EI does not exist

ERROR: InvalidPropertyAssignmentValue - 22:27 - $this->map with declared type 'array<class-string<EI>, string>' cannot be assigned type 'array{EntityOne: string(type_1), EntityThree: string(type_2), EntityTwo: string(type_2)}'
```

**Comment by muglug** [comment]
You can solve this with `class-string-map`: https://psalm.dev/r/7d20b16245

**Comment by githoober** [comment]
@muglug should `class-string-map` be added to the Psalm documentation? I could not find anything existing there that explains how to use it.

**Comment by githoober** [comment]
I am still thinking there might a bug in the @template implementation. If I remove the template tag in the code snippet above and use the interface directly in the var tag, the issue is going away. 

https://psalm.dev/r/60eef97071

**Comment by weirdan** [comment]
I don't think the type you defined is sound. Consider the case when it's specialized over `EntityThree`. Clearly that map in `Map<EntityThree>` cannot contain the entry `EntityOne::class => Type::TYPE_1`, as the type of that array becomes `array<class-string<EntityThree>, string>`
