### ISSUE TITLE
[Question] Way to type "subclass of T"

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#3528]
Hi, is there a way to declare type as a "type that is a subtype of T but not T" without having to list a union type of those subtypes?

```php
class A {}

final class B extends A {}
final class C extends A {}
```

I need something like `@psalm-var subtype<A>` instead of having to do `@var B|C`. Is there something to achieve this?

**Comment by muglug** [comment]
Nope, sorry

**Comment by simPod** [comment]
Not sure if it's doable but might be helpful in some cases, eg. this one https://github.com/webmozart/assert/blob/7956178940dc33ff9b2ef42b2e057d85dc55a6ab/src/Assert.php#L1701 🤔
