### ISSUE TITLE
Combined object like arrays don't trigger errors

### ISSUE THREAD

**Issue by simitter** [vimeo/psalm#3530]
While combining two object like arrays in the param annotation calls to the method with wrong data in arrays won't trigger errors.

https://psalm.dev/r/4e208bdebb

**Comment by weirdan** [comment]
Psalm interprets that as `array{host?: string, port?: int, url?: string}` (see https://psalm.dev/r/95d9cd80eb), and what you're passing in is a valid instance of that array type. `["host" => 22]` would be rejected though: https://psalm.dev/r/eb26f1b1d3

**Comment by weirdan** [comment]
As this is not the first time this pops up, and it was always rejected as something that won't be changed, I'm closing this issue.

**Comment by muglug** [comment]
To flesh this out a little, fixing this would require structural array typing, which Psalm doesn't have and likely won't ever have.
