### ISSUE TITLE
Template causes UndefinedDocblockClass error when used as param on a static method

### ISSUE THREAD

**Issue by kevinsmith** [vimeo/psalm#3533]
I'm trying to use the [class-string<T>](https://psalm.dev/docs/annotating_code/templated_annotations/#param-class-stringt) param for a static factory method, but Psalm throws a UndefinedDocblockClass error with the message "Docblock-defined class or interface T does not exist":

https://psalm.dev/r/aac80a59e8

The error goes away when I remove the static modifier:

https://psalm.dev/r/ce945b8766

Why isn't this permitted in a static context?

**Comment by kevinsmith** [comment]
Nevermind. It makes sense now that I think about it. The object hasn't been instantiated at this point, so there's not a type in play yet.

**Comment by weirdan** [comment]
You probably need to make `factory()` method itself generic in this case: https://psalm.dev/r/a03435d158
