### ISSUE TITLE
[Bug] MethodReturnTypeProvider::getClassLikeNames needs to include mixin class

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3536]
I believe the following is the minimum steps to reproduce

```php
class Mixin {
    public function foo() {}
}

/**
* @mixin Mixin
*/
class Concrete {}

function test(Concrete $c) {
    return $c->foo();
}
```
and a plugin looking like this
```php
final class ReturnTypeProvider implements MethodReturnTypeProviderInterface
{
    /**
     * @return array<string>
     */
    public static function getClassLikeNames(): array
    {
        return [Concrete::class];
    }

    public static function getMethodReturnType(StatementsSource $source, string $fq_classlike_name, string $method_name_lowercase, array $call_args, Context $context, CodeLocation $code_location, array $template_type_parameters = null, string $called_fq_classlike_name = null, string $called_method_name_lowercase = null)
    {
         echo "hello";
     }
}
```

The method return type provider does not seem to be invoked unless `Mixin::class` is added to the `getClassLikeNames` array.

It also seems pretty difficult to determine that `$c` is actually an instance of `Concrete`. The references in the provider are all `Mixin`

**Comment by muglug** [comment]
I think my fix should do it – LMK if it doesn't work

**Comment by mr-feek** [comment]
Looks like I'm in business -- thanks a lot @muglug !

**Comment by mr-feek** [comment]
Hey @muglug I believe this might have regressed between this commit and the release of 3.11.6

my tests started failing again after updating https://github.com/psalm/psalm-plugin-laravel/commit/5315836374c510aa615debbbb9e7882063f6bb24
