### ISSUE TITLE
Templates not working properly with higher order functions

### ISSUE THREAD

**Issue by lmnt-dev** [vimeo/psalm#3539]
I'm trying to write a generic predicate function but Psalm seems to be over specifying the type.

```php
/**
 * @template T
 * @param T $x
 * @return callable(T): bool
 */
function eq ($x) {
    return fn ($y) => $x == $y;
}

$p = eq(5);
$p(4);
```

I'd expect this to pass, but instead I get `Argument 1 expects int(5), int(4) provided`.

**Comment by muglug** [comment]
This is by design – in most real-world situations you're not specifying real types, and so Psalm doesn't get that specific e.g. https://psalm.dev/r/10268ddb5b
