### ISSUE TITLE
Too strict LessSpecificImplementedReturnType. Cannot use with PHPStorm

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3540]
https://psalm.dev/r/7e7a4b236a

Basically, keeping `Organisation[]` is super important so phpstorm understands it, I cannot change that to `list<Organisation>`. But doctrine plugin says it returns `list<Organisaton>`. Which is also true, but I cannot use that for PHPStorm.

Can we please make Psalm understand that since user is using `allowPhpStormGenerics="true"`, it shouldn't complain when using `T[]` while parent uses `list<T>`? It should do that only using `psalm-*` notation in such scenario.

**Comment by weirdan** [comment]
There's a `@psalm-method` when you need it to be different from `@method`: https://psalm.dev/r/f2bfbac86a

**Comment by ostrolucky** [comment]
I know, but that doesn't solve the issue in correct way. What I posted is minimal reproducer. We specify 4 of those methods on dozens of repositories. And same problem is for all other methods that use find* methods in their bodies. You can imagine how much noise adding `@psalm-method` everywhere just to workaround this issue would create.

Psalm knows from `@template` exactly what those methods return. I'm using `@method` *just so PHPStorm understands it*. But Psalm takes it at face value and thinks I'm trying to return `array<array-key, Doctrine\ORM\Organisation>`. No dummy, I used `Organisation[]` because that's what I have to use. There should be a way to tell Psalm to prioritize what is in `@template` and ignore these in this case.

**Comment by muglug** [comment]
Sorry, it sounds like you're asking for some pretty boutique behaviour here which doesn't make sense for Psalm.

**Comment by ostrolucky** [comment]
What's different from what I am asking here and supporting `@var Collection|Foo[]` that already is in Psalm? Since Psalm made up `list` and `array-key` types in PHP ecosystem, it should at least care about interoperability with other tools.

**Comment by muglug** [comment]
It's very different – `Collection|Foo[]` is a special case that converts to `Collection<Foo>`. Here you're just providing the array annotation `Foo[]` which is _always_ interpreted as an array

**Comment by weirdan** [comment]
What could help here is `@phpstorm-` prefixed annotations, but that's clearly outside of Psalm's realm to implement.
