### ISSUE TITLE
@property-read support

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3542]
https://psalm.dev/r/32c1e373af

E.g. [Gocardless](https://github.com/gocardless/gocardless-pro-php/blob/master/lib/Resources/Event.php) is using it. Looks this is part of official phpdoc standard: https://docs.phpdoc.org/latest/guides/docblocks.html

**Comment by andrew-demb** [comment]
Psalm trying to find magic method '__get' for property-read annotation.

https://psalm.dev/docs/annotating_code/supported_annotations/
> @property-read Used to specify what properties can be read on object that uses __get

**Comment by andrew-demb** [comment]
https://psalm.dev/r/3d6bba6688
