### ISSUE TITLE
RedundantCondition seen inside a try/catch

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#355]
An easy solution would be to suppress RedundantCondition issues in a catch block (I think some issues are suppressed or inferences are cleared?).
A heuristic would be combining the types from before/after the try block

```
<?php

function trycatch() : void {
    $value = null;
    try {
        if (rand() % 2 > 0) {
            throw new RuntimeException("Failed");
        }
        $value = new stdClass();
        if (rand() % 2 > 0) {
            throw new RuntimeException("Failed");
        }
    } catch (Exception $e) {
        if ($value) {  // unexpected RedundantCondition - Found a redundant condition when evaluating $value
            var_export($value);
        }
    }
}
```

**Comment by TysonAndre** [comment]
I also see the same RedundantCondition if checking for $value **below** the try/catch - $value is object is assumed, but it can be null

**Comment by muglug** [comment]
Yeah, still thinking of the best way to deal with these variables.

**Comment by muglug** [comment]
Thanks – I think the solution I have is robust enough – `RedundantCondition` is suppressed inside the `catch` blocks
