### ISSUE TITLE
@method annotation is not documented

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#3550]
Just saw you don't have a way to deal with the magic method `__call`? I'd expect an annotation like `@method` or similar. Anything you've thought about?

https://psalm.dev/docs/annotating_code/supported_annotations/

**Comment by mr-feek** [comment]
@olleharstedt `@method`  syntax does indeed work 9b2bb6db1a818f988d5b4667d88dd113bfd62b69

This issue should probably remain due to the fact that it doesn't seem to be documented functionality

**Comment by olleharstedt** [comment]
Aha! Yes, please add it to the docs. :+1:

**Comment by muglug** [comment]
@olleharstedt please add it to the docs!

**Comment by olleharstedt** [comment]
Uh, how? Link to instructions?

**Comment by mr-feek** [comment]
https://github.com/vimeo/psalm/blob/master/docs/annotating_code/supported_annotations.md :)

**Comment by olleharstedt** [comment]
Fixed.
