### ISSUE TITLE
Decorated class with @mixin usage

### ISSUE THREAD

**Issue by mprokocki** [vimeo/psalm#3553]
Will start with code describing what I'm trying to achieve:
https://psalm.dev/r/86e77e606c

As you can see using static method within `Decorator` is causing false positive `PossiblyNullArgument` error. Either I'm not getting how `@mixin` should be working (I could not find any doc for it) or there's something more I'm missing. Is there any possible way for getting this work as expected??

**Comment by BackEndTea** [comment]
This might be related to #3552.

**Comment by muglug** [comment]
Yeah, fixed since that was fixed
