### ISSUE TITLE
A declared template is not available in static factory method

### ISSUE THREAD

**Issue by githoober** [vimeo/psalm#3554]
Maybe I am missing something again, but:
https://psalm.dev/r/5d2e942e70

The version with public constructor  works fine:
https://psalm.dev/r/8e06d49f67

**Comment by weirdan** [comment]
What you need here is to make the static method generic: https://psalm.dev/r/540d48af30

**Comment by weirdan** [comment]
As to explaining why - there are multiple reasons, not the least of them being that generics are implemented this way in other languages. Another is that it would be confusing when you call that `create()` method on an instance:

```php
/** @param ObjectList<ArrayObject> $list */
function f(ObjectList $list): void {
   // what should be the type of $anotherList? 
   // Should it be ObjectList<RuntimeException> or ObjectList<ArrayObject> ? 
   $anotherList = $list->create(RuntimeException::class);
}
```
