### ISSUE TITLE
Incorrectly resolved $this return of PHPDoc defined method in mixin context

### ISSUE THREAD

**Issue by SCIF** [vimeo/psalm#3556]
https://psalm.dev/r/fc69f45670

**Comment by SCIF** [comment]
That affects phpdoc defined methods only: https://psalm.dev/r/1a255b844f

**Comment by weirdan** [comment]
Fixed in #10356 . Note that the class importing the mixin should either have it's own `__call()` or you need to enable `usePhpDocMethodsWithoutMagicCall` in psalm.xml

https://psalm.dev/r/3d74f0f8cf
