### ISSUE TITLE
What's the deal with __call, @method and inheritance?

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#3561]
There's a disturbing difference between Psalm and phpstan in cases where __call is defined in a base class, and no `@method` docblock is defined. See this snippet:

```php
class A
{
  public function __call(string $method, array $args)
  {
  }
}

class B extends A
{
}

$b = new B();
$b->foo();
```

This will report no errors on Psalm, but phpstan gives

      15     Call to an undefined method B::foo().

But if you add `@magic` to class B like so:

```php
class A
{
  public function __call(string $method, array $args)
  {
  }
}

/**
 * @method void bar()
 */
class B extends A
{
}

$b = new B();
$b->foo();
```

then Psalm reports the correct error:

    ERROR: UndefinedMagicMethod - src/test.php:18:5 - Magic method B::foo does not exist (see https://psalm.dev/219)

So it's like one `@method` somehow _triggers_ Psalm to check for magic methods? This habit completely breaks proper checking of the framework Yii, where the Component class defines __call, and then e.g. the query builder extends it. Now, calling any method on a query builder will pass, BUT if you put a `@method` into the query builder, Psalm starts to report errors. Any ideas on how to solve this, to make Psalm _require_ either the definition of a method or a docblock `@method` line?

**Comment by weirdan** [comment]
> > Hey @olleharstedt, can you reproduce the issue on https://psalm.dev ?
> 
> Yes.

https://psalm.dev/r/1e04a8027e
https://psalm.dev/r/51c6d7ed9f

**Comment by weirdan** [comment]
@olleharstedt which of those behaviors you see as problematic? Reporting no errors in the absence of `@method` docblocks or reporting an error when they are there?

**Comment by olleharstedt** [comment]
@weirdan This is the failing use-case:

```php
// require Yii 2
$query = new \yii\db\Query();
$query->thisdoesntexist();  // No warning
```

The Component class implements __call(), Query extends Component, and no errors are reported.

**Comment by muglug** [comment]
@olleharstedt you can work around this with `@psalm-seal-methods` annotation: https://psalm.dev/r/0ab8fa2184

I've just pushed a fix to make that inheritable, too: https://psalm.dev/r/481c4d06c5

**Comment by olleharstedt** [comment]
OK, but the question is if we can do this in our own code, or if the framework has to do it. We can't require of Yii to implement Psalm-specific notation just to report proper errors on functions. It has to be a config in Psalm.

**Comment by muglug** [comment]
If you wanted to PR that I’d happily accept it - but I like the current behaviour to stay the default, where using magic `__call` doesn’t automatically opt you into requiring `@method` annotations

**Comment by olleharstedt** [comment]
Well, if Psalm should be useful at all with Yii, there must be a setting that doesn't ignore all function calls if any class implements __call somewhere in the inheritance chain. I can try to hack and set seal globally and see how that behaves.

I agree that __call shouldn't require the method annotation, but I also think it shouldn't make Psalm "give up". :)

**Comment by olleharstedt** [comment]
What about reading a global config at this line? "sealAllMethods" or similar.

https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php#L1234

**Comment by muglug** [comment]
> We can't require of Yii to implement Psalm-specific notation just to report proper errors on functions.

> if Psalm should be useful at all with Yii

I think the solution to both would be a Yii plugin that, at a minimum, provided stubs for the component class which defines `__call`.

**Comment by olleharstedt** [comment]
> I think the solution to both would be a Yii plugin that, at a minimum, provided stubs for the component class which defines `__call`.

But wouldn't those stubs just replicate the methods that are already explicit?

**Comment by olleharstedt** [comment]
Sorry, the correct place to read config should be here: https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MissingMethodCallHandler.php#L95

Replace

    if ($class_storage->sealed_methods) {

with

    if ($class_storage->sealed_methods || $config->seal_all_methods) {

And pass Psalm `$config` to the method `handleMagicMethod`.

Should I make a PR with this? Would it be accepted?

**Comment by weirdan** [comment]
Would love to have that option.

**Comment by muglug** [comment]
Absolutely - see my comment here: https://github.com/vimeo/psalm/issues/3561#issuecomment-642787911

**Comment by olleharstedt** [comment]
Alright, let's see if I have time next week. :)

**Comment by olleharstedt** [comment]
New PR here: https://github.com/vimeo/psalm/pull/3578
