### ISSUE TITLE
Problem with $_ENV

### ISSUE THREAD

**Issue by matiux** [vimeo/psalm#3564]
I have this function to take environment variables in various ways

https://psalm.dev/r/084f2df25d

But I'm struggling to figure out how to solve the TypeDoesNotContainType error

**Comment by weirdan** [comment]
Shouldn't the last ternary be wrapped in parens? 
https://psalm.dev/r/f48b8a52dc

**Comment by matiux** [comment]
Thanks, I hadn't considered this syntax and actually don't understand why in this way works.

**Comment by muglug** [comment]
It's about operator precedence – when in doubt, parenthesize

**Comment by matiux** [comment]
@muglug  some updates lead me to reopen this issue https://psalm.dev/r/f48b8a52dc

**Comment by weirdan** [comment]
@matiux please open a new issue.

It appears someone thought `$_ENV` usually contains `argv` element, like `$_SERVER` does:

https://github.com/vimeo/psalm/blob/d0be59e16ef6e55f0349c60eab272947e21a2c11/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php#L674-L707
