### ISSUE TITLE
class-string in ReflectionMethod

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#3566]
https://psalm.dev/r/34340dc341

- Expected a error because class-string should be used (like in ReflectionClass)
- expected a error because method does not exist

**Comment by muglug** [comment]
> Expected an error because `class-string` should be used

Fixed in ec0a4c7

> expected an error because method does not exist

You could add a `MethodParamsProviderInterface` hook that sets the second param type from the first's class string, but I think this is such an edge-case as to not be worth Psalm implementing.
