### ISSUE TITLE
Unexpected Cannot resolve types for $isCalled - false does not contain true

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#3567]
https://psalm.dev/r/06f6f501d5

**Comment by muglug** [comment]
Just move the `$isCalled` variable up: https://psalm.dev/r/282cccce24

**Comment by staabm** [comment]
Thx for your feedback

> Just move the `$isCalled` variable up: https://psalm.dev/r/282cccce24

This doesnt work for me, see https://github.com/redaxo/redaxo/pull/3716/files#diff-79cfbd60816ab0e7a1a826879abf61dd

**Comment by weirdan** [comment]
Comparing https://psalm.dev/r/06f1ea57e9 with https://psalm.dev/r/82d9e7e0c4, it appears the point of definition for `$value` (even though it's unused by both snippets) affects the inference for `$isCalled`. 
@muglug should this be the case?

**Comment by muglug** [comment]
No, on second thoughts this behaviour is a little weird
