### ISSUE TITLE
Stub files are deep scanned

### ISSUE THREAD

**Issue by joehoyle** [vimeo/psalm#3568]
I've been investigating why I'm seeing my (quite large) stub files getting a shallow scan, and then a deep scan. It seems to me that stub files should never get shallow _and_ deep scanned, as they only contain definitions, so function / method bodies etc are not present.

From the best I can tell, the reason for deep scanning is due to a project having a class that extends the stubbed class as triggered by https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Codebase/Scanner.php#L615. `$will_analyze` is `true` (analyzing the project file), and it (for some reason) forwards the `$will_analyze` to `queueClassLikeForScanning`. The subsequent lines for `required_interfaces` and `referenced_classlikes` hard code `$analyze_too` to `false`, so I'm wondering if this is an oversight?

This leads me to two questions I think:

1. Why does requiring a class in file A cause a deep scan on File B that has the class? Isn't a shallow scan enough?

1. Can stub-files always be short-circuited from deep scanning?

**Comment by muglug** [comment]
> Why does requiring a class in file A cause a deep scan on File B that has the class? Isn't a shallow scan enough?

If you have a class `AChild` extend a class `AParent` Psalm may, at some point, need to check the constructor of `AParent` to determine property initialisation. Deep scanning ensures no surprises when that happens.

> Can stub-files always be short-circuited from deep scanning?

Definitely, but deep scanning a stub file is also _very_ quick – it should have a negligible impact on performance.

**Comment by joehoyle** [comment]
@muglug given that deep scanning stubs can just be as quick as shallow, would it make sense to instead always deep scan stubs? This means it should take the same time, but avoid a double scan, which happens right now in the above scenario. Psalm takes around 6 seconds to scan my stub file (it's a stub of all wordpress functions and classes), so just setting it to deep scan initially would save a lot of time, and also solve the problem I have with a shallow scan on _some_ stubs, and then deep scans on others changing the order of stubbed function analysis.

**Comment by joehoyle** [comment]
Ping @muglug — any thoughts here on the suggestions to always deep scan stubs?
