### ISSUE TITLE
@psalm-suppress InvalidReturnType ignored

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#357]
```php
<?php

interface I {
    /**
     * @return Boolean
     */
    public function check();
}

class C implements I
{
    /**
     * @psalm-suppress InvalidReturnType
     */
    public function check(): bool
    {
        return false;
    }
}
```
results in 
```
ERROR: InvalidReturnType - qqqqq.php:15:5 - The return type 'Boolean' for I::check is different to the implemented return type for C::check 'bool'
    /**
     * @psalm-suppress InvalidReturnType
     */
    public function check(): bool
```
even though it's specifically suppressed.

**Comment by TysonAndre** [comment]
Unrelated: I'd prefer to have a different issue label for failing to match declared return type with function body vs failing to match an ancestor method's return type (e.g. completely suppress one without suppressing the other)

**Comment by muglug** [comment]
Yeah, agreed that should be changed

**Comment by muglug** [comment]
Changed in https://github.com/vimeo/psalm/commit/52f9225356774accce656af9bd9210b5444019b9

**Comment by muglug** [comment]
Thanks!
