### ISSUE TITLE
Wrongly accused InvalidReturnType with curl_exec

### ISSUE THREAD

**Issue by theseer** [vimeo/psalm#3570]
Hi,

`phive` has a wrapper around `ext/curl` with a fragment of code as follows:

```php
// [...]
/**
 * @throws CurlException
 */
public function exec(): string {
    $result = \curl_exec($this->curlHandle);

    if ($result === false) {
        throw new CurlException('Request failed');
    }

    return $result;
}
```

The `curl` instance referenced by `$this->curlHandle` as `CURLOPT_RETURNTRANSFER` set to true, ensuring that `curl_exec` will either return a boolean `false` or the content string retrieved, which of course may be empty.

When running psalm I get this error:

```
ERROR: InvalidReturnType - src/shared/http/Curl.php:56:29 - The declared return type 'string' for PharIo\Phive\Curl::exec is incorrect, got 'string|true' (see https://psalm.dev/011)
    public function exec(): string {
```

While I do realize that `psalm` at this point probably cannot know that `CURLOPT_RETURNTRANSFER` has been set, I'm not convinced that simply suppressing the InvalidReturnType error is the correct way to deal with this?

**Comment by muglug** [comment]
You can use `if (\is_bool($result))` instead, which would convince Psalm.

**Comment by xPaw** [comment]
Perhaps Psalm could detect if `CURLOPT_RETURNTRANSFER` was/is set on the curl handle?

**Comment by LauraTaylorUK** [comment]
I just wanted to let you know that this issue was never fixed and still exists today.

The function `curl_exec()` when CURLOPT_RETURNTRANSFER is set, will return the result on success and `false` on failure. Psalm misinterprets and thinks it may return `true`.

**Comment by AndrolGenhald** [comment]
This was effectively impossible before with the `resource` type. Now that we have the `CurlHandle` type it's technically possible with the use of a template, but it's probably not worth the trouble (and using templates for flags like that is a bit finicky).
