### ISSUE TITLE
InvalidArugment for `set_error_handler` when using `[$this, 'method']` construct

### ISSUE THREAD

**Issue by theseer** [vimeo/psalm#3571]
One way to specify an error handler is to pass in an array with two elements, an object or classname and a methodname:

```php
    // ...

    private function registerLocalErrorHandler(): void {
        $this->originalHandler = \set_error_handler(
            [$this, 'localErrorHandler']
        );
    }

    public function localErrorHandler(int $errno, string $errstr): void {
        throw new PharInstallerException($errstr, $errno);
    }

    // ...

```

When running psalm, it complains:

```
ERROR: InvalidArgument - src/services/phar/PharInstaller.php:102:13 - Argument 1 of set_error_handler expects callable(int, string, string=, int=, array<array-key, mixed>=):bool|null, array{PharIo\Phive\PharInstaller&static, string(localErrorHandler)} provided (see https://psalm.dev/004)
            [$this, 'localErrorHandler']
```

The error is either wrong because this construct is perfectly valid or, in case psalm looks at the actual signature of the referenced method, confusingly wrong as the signature doesn't match but is technically compatible.

**Comment by muglug** [comment]
The error will go away if you set the error handler to return `?bool`, but this error should also probably not happen in the first place.

**Comment by muglug** [comment]
Reproduced here: https://psalm.dev/r/0c1002dd00

**Comment by theseer** [comment]
Not convinced this is fixed. I extracted the code and pasted it to https://psalm.dev/r/8ac153541e.

It still complains.

**Comment by weirdan** [comment]
Hm, could it be that the return type is missing parens? If I use the type copied verbatim from the error message in a param docblock, it's interpreted as `callable|null`: https://psalm.dev/r/21270719ec

**Comment by weirdan** [comment]
> it's interpreted as `callable|nul`l

And it's actually proper signature, as you may call `set_error_handler(null);` to remove the error handler.

**Comment by muglug** [comment]
Oh sorry @theseer, my mistake – this should work: https://psalm.dev/r/e78ad276ca

**Comment by theseer** [comment]
It certainly does - but is that also correct? I mean, technically the specified return value of the method is not what is happening ;)

But then, maybe that's an edge case of an edge case ;)

**Comment by weirdan** [comment]
> I mean, technically the specified return value of the method is not what is happening ;)

Yeah, I'm surprised it's not reported. I think it should require `@return never-return`: https://psalm.dev/r/ef21c8743b

**Comment by muglug** [comment]
> Yeah, I'm surprised it's not reported.

`never-return` is a bottom type – the subtype of all possible types, so it's fine to throw when the function says it should return a value.

**Comment by weirdan** [comment]
> never-return is a bottom type

Ah, makes sense. Thanks for clarification.
