### ISSUE TITLE
UnusedClosureParam should not be reported for params defined before used params

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3574]
https://psalm.dev/r/036ec7d178

Removing first argument would break the caller that calls the closure with both arguments

**Comment by muglug** [comment]
Prepend the name with `_`: https://psalm.dev/r/8260d3972e

**Comment by weirdan** [comment]
I would consider it a bug if it *wasn't* reported. You can suppress the error or mark the parameter as ignored with underscore: https://psalm.dev/r/8260d3972e

**Comment by ostrolucky** [comment]
Where can I find this underscore convention documented? Ideally message itself should explain this.

**Comment by weirdan** [comment]
> Where can I find this underscore convention documented? Ideally message itself should explain this.

In the linked PR (#3580) for now :smile:
