### ISSUE TITLE
False negative UnusedClosureParam with underscore params

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3579]
https://psalm.dev/r/7e138b2629

No matter the name of parameter, unused last closure parameter needs to be reported

**Comment by muglug** [comment]
This is by design!

**Comment by ostrolucky** [comment]
But why? How can make Psalm to find these unused uses? I have some closures with param names prefixed with underscore.

**Comment by muglug** [comment]
> I have some closures with param names prefixed with underscore.

Remove the underscores then, I guess?
