### ISSUE TITLE
False positive InvalidReturnStatement

### ISSUE THREAD

**Issue by Krifollk** [vimeo/psalm#3583]
[https://psalm.dev/r/ee07e9cbab](https://psalm.dev/r/ee07e9cbab)

The issue could be resolved by adding additional type **|bool** for return doc block of getIterator method and for **@template-implements IteratorAggregate<int, T|bool>**

**Comment by weirdan** [comment]
**bool**|int|null|object|string|**bool** is a bug.

**Comment by muglug** [comment]
The output should say `ArrayIterator<int, (T:Test as bool|int|null|object|string)|bool>`, now corrected.
