### ISSUE TITLE
Psalm ignores @return T in factory defined in generic interface

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3584]
I am probably doing something wrong, just don't know what https://psalm.dev/r/2159c58de5

**Comment by weirdan** [comment]
The reason for this error is that, as it's written, this needs to be valid:
```php
class DescendantValue extends ApplicationCustomFieldValue {}

/** @var Application<DescendantValue> */
function f(Application $app): void {
   $app->customFieldValueFactory(); // generic promises it'll return DescendatValue, but actually returns ApplicationCustomFieldValue
}
```

I suspect, however, is that you're trying to implement parallel hierarchy here: e.g. `WebApplication` paired with `WebApplicationCustomFieldValue`, `CliApplication` paired with `CliApplicationCustomFieldValue`, etc. 

If that's the case, you actually don't need that `Application` class to be generic as it's not expected to be parameterized over different types. Rather, any specific class would have one specific `CustomFieldValue` subtype hardcoded. 

You can achieve this by extending the generic parent class in a non-generic subclass: https://psalm.dev/r/33eccd26b2

**Comment by ostrolucky** [comment]
Hmm indeed, so I shouldn't have declared Application as `@template`, gotcha! Real use case is more complicated, but there seem to be unrelated issues in those, so let me open new issue for that. Thank you for helping out.
