### ISSUE TITLE
For unknown reason, Psalm infers mixed return type in trait

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3585]
https://psalm.dev/r/43d9d89be5

This is a continuation of https://github.com/vimeo/psalm/issues/3584

**Comment by weirdan** [comment]
This
```php
    /*
     * @psalm-var array<array-key, ApplicationCustomFieldValue>
     */
```
is not considered a docblock - and thus ignored. Docblocks start with `/**`.

**Comment by ostrolucky** [comment]
Indeed. That turns it into this issue that actually matches with what I have in my real code: https://psalm.dev/r/2544f60dd9

But this doesn't match the title of this PR anymore. Should I create new issue?

**Comment by weirdan** [comment]
Yes, please.

**Comment by weirdan** [comment]
Playing with this a bit further I've distilled the reproducer to this: https://psalm.dev/r/c578b04f0f , which I think is a bug.

**Comment by ostrolucky** [comment]
Alright I'll take care of creating issue for this

**Comment by ostrolucky** [comment]
https://github.com/vimeo/psalm/issues/3586
