### ISSUE TITLE
False positive PropertyTypeCoercion for templated trait accessing property defined outside of trait

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3586]
https://psalm.dev/r/c578b04f0f

This is a continuation of https://github.com/vimeo/psalm/issues/3584 and https://github.com/vimeo/psalm/issues/3585

**Comment by weirdan** [comment]
Possible workaround is to move the property to the trait itself, but I don't think it should be necessary.

**Comment by ostrolucky** [comment]
That will work with only one implementation of IAbstract. In my real case I have 4 of them, so even if I define property inside trait as workaround, I would need a way to override it in other classes. But that doesn't seem working.

**Comment by weirdan** [comment]
Not necessarily, as you can type that property with `@var T`, and it will assume the type specified in `@use ValueTrait<SpecificConcrete>`: https://psalm.dev/r/6a3a6d866a

**Comment by ostrolucky** [comment]
Yeah but I need to declare also some specific annotations for property in C1 and C2. These are actually doctrine entities.
