### ISSUE TITLE
Cannot parse generic array @extends docblocks

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3587]
https://psalm.dev/r/1a3d576987

**Comment by weirdan** [comment]
You have mismatching angle brackets there (the one before the paren should not be there): ` * @extends Provider<(array<string, mixed>>)>`
When that is fixed, no issues are emitted: https://psalm.dev/r/68a462c22b

**Comment by ostrolucky** [comment]
I don't know what would I do without you ❤️
