### ISSUE TITLE
Constants containing long text are inferred as `string` rather than `non-empty-string`

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#3588]
I was getting a type coercion false-positive due to a long SQL query being embedded into a constant: psalm is probably skipping analysis on strings after a certain length, although some type information may indeed be retained.

See https://psalm.dev/r/9c4006b5b2

**Comment by weirdan** [comment]
Yeah, long strings should be by definition be non-empty.

**Comment by Ocramius** [comment]
This is probably similar to #1881 (optimization)
