### ISSUE TITLE
Not possible to set @var after initialization

### ISSUE THREAD

**Issue by jasverix** [vimeo/psalm#3590]
It's not possible to set @var after initialization.

In our project, we have code that can be simplified down to https://psalm.dev/r/a7893997f9. (ofc not random_int(0,1), but a $node can be Project or Task, checked by `if(in_array($node->getType(), ['Project', 'Task'])) && ($topProject = $node->GetRootProject())) {`)

Is there any possibility that this can be supported? If not, I will have to find another way of doing this.

**Comment by orklah** [comment]
I think it's basically https://github.com/vimeo/psalm/issues/1916 . If I find the time, I may work on that in the future, but don't hesitate to try yourself, it may be quicker :)

**Comment by weirdan** [comment]
Is there any reason you're not using `instanceof` or `get_class()` instead?
E.g. Psalm can understand this: https://psalm.dev/r/eeef35849f

**Comment by jasverix** [comment]
The example is simplified. But yes - it might be possible to refactor, but this is not a new, small project, but me trying to run psalm on an existing codebase - and I am very impressed on what it finds, but a lot of false errors caused by inability to read `@var` - comments unless they are on the line right before initialization. 

I think that refactor is a too big job for me right now, so I might try to create a PR on this issue.

Cool though, that it understands type in a get_class() switch 😃 No need for `@var` at all. https://psalm.dev/r/a1b26b6d99

**Comment by muglug** [comment]
Yeah, closing in favour of #1916
