### ISSUE TITLE
Typestate-oriented programming

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#3591]
Did you guys discuss typestate-oriented programming anything?

Building on article [1], it would allow you to "tag" types and resources, like so:

```php
/** @var File<Open> */
$handle = fopen("/tmp/inputfile.txt", "r");
/** @var string */
$buffer = fgets($handle, 4096));
// This changes $handle to @var File<Closed>
fclose($handle);
// Type error: $handle must have type File<Open>
fgets($handle, 1);
```

See [2] for more details about this paradigm. It corresponds loosely to what in functional programming is done with linear (or affine) types.

[1] http://marcosh.github.io/post/2020/05/26/phantom-types-in-php.html

[2] https://www.cs.cmu.edu/%7Ejssunshi/pubs/onward2009-state.pdf

**Comment by andyg0808** [comment]
@olleharstedt I'm wondering if [1] was the intended link, because the article there seems to have more to do with marking interpretations of primitive types, rather than marking states.

**Comment by olleharstedt** [comment]
@andyg0808 It was intended, since phantom types can simulate typestate in some settings.

**Comment by olleharstedt** [comment]
Psalm seem to already have typestate related features, as shown here: https://github.com/vimeo/psalm/issues/1255

Related to array_shift:

```php
/** @var array{string, int} */
$arr = ["foo", 1];
array_shift($arr);  // Modifies the type
```

Seems like this happens in method `handlePossiblyMatchingByRefParam` in Psalm? Maybe there's a way to make it possible to define your own functions like this, instead of the hard-coded list?

**Comment by muglug** [comment]
Psalm already handles closing file handlers via the `resource-closed` type: https://psalm.dev/r/2737e2dc70

**Comment by muglug** [comment]
I don't plan to add any annotations to change state beyond `@param-out` annotations

**Comment by olleharstedt** [comment]
> I don't plan to add any annotations to change state beyond existing `@param-out` annotations

@muglug Do you plan to do something with alias tracking? E.g. to fix `array_shift` in the case where argument has an alias in the same scope.
