### ISSUE TITLE
Conditional type 'func_num_args()' not properly inheriting

### ISSUE THREAD

**Issue by tvdijen** [vimeo/psalm#3593]
I was fiddling around with the new conditional type + func_num_args and was suprised the examples didn't work in my case.. I think it has something to do with an added layer of object inheritance in my case..

With some inheritance (broken):  https://psalm.dev/r/684a7f32b1
Flat hierarchy (working):  https://psalm.dev/r/5fd52e3490

**Comment by weirdan** [comment]
Also, replacing the `self::getAttribute()` call with `parent::getAttribute()` gets rid of the issue. But both calls should behave the same, as the method is not overridden.

**Comment by weirdan** [comment]
Fixed in #10357
