### ISSUE TITLE
Redis::zRevRangeByScore() argument types incorrect

### ISSUE THREAD

**Issue by jaikdean** [vimeo/psalm#3594]
The expected argument types for arguments 2 and 3 of `Redis::zRevRangeByScore()` appear to be incorrect in Psalm.

Documentation for `Redis::zRevRangeByScore()`: https://github.com/phpredis/phpredis#zrangebyscore-zrevrangebyscore
Test case: https://psalm.dev/r/ea54c4d62d

**Comment by muglug** [comment]
Please update in `CallMap.php`
