### ISSUE TITLE
Can't get @param-out to check

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#3596]
No idea what I'm doing wrong here or if it's a bug. Using latest dev of Psalm.

```php
class Open {}   
class Closed {}     

/**
 * @template T      
 */     
class File {}

/**
 * @param File<Open> $arg      
 * @param-out File<Closed> $arg                 
 * @return void
 */       
function close(&$arg): void  
{ 
}        

/** @var File<Open> */  
$file = new File(); 
close($file);
```

Fails with

> ERROR: ReferenceConstraintViolation - arraytest.php:16:15 - Variable $arg is limited to values of type File< Closed > because it is passed by reference, File< Open > type found. Use @param-out to specify a different output type (see https://psalm.dev/086)
function fun(&$arg): void

It doesn't seem to register that I'm using `@param-out` already.

**Comment by olleharstedt** [comment]
> Hey @olleharstedt, can you reproduce the issue on https://psalm.dev ?

Yep.

**Comment by muglug** [comment]
You get it to typecheck by actually changing `$arg`: https://psalm.dev/r/b26e101955
