### ISSUE TITLE
New feature: @param-out-unsafe

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#3598]
I'd like to discuss (maybe you have a support channel for discussions instead?) the addition of a possible `@param-out-unsafe` annotation, to tell Psalm "trust me, I know what I'm doing". Use-case would be to make typestate easier, without the need to create new objects at every typestate change. Another alternative would be a new global setting, like "useUnsafeParamOut", to make all `@param-out` unsafe.

Another similar unsafe feature could be `/** @var-unsafe String<Email> */`, to "tag" a type without the need to actually create a new dummy class `Email`.

**Comment by muglug** [comment]
I'd just suppress the issue that Psalm generates.
