### ISSUE TITLE
Add an option to treat undeclared **global** variables as having type mixed, not empty?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#360]
E.g. a psalm.xml option to treat the types of undefined global variables as `mixed`, not `empty` if the corresponding setting is enabled (not sure which)

- It would be convenient to limit this to just a few directories which are known to use globals from elsewhere, but possibly impractical/slow (e.g. path/to/template_directory)

An example is the below code, in a folder where I suppressed UndeclaredVariable issues, which caused confusion earlier on:

```php
<?php
// This code is in the global scope.
// Assume this was declared elsewhere.
// A workaround may be adding `/** (at)var int[] $userIds */`, but that's hard to figure out.
$count = count($userIds);
$rows = ceil($count / 4);
$row = 0;
$index = -1;
$uid = null;
for ($row = 0; $row < $rows; ++$row) {
    $index++;
    if ($index < $count) {
        $uid = $userIds[$index];
    } else {
        $uid = null;
    }
    if ($uid) {  // undesired "RedundantCondition Found a redundant condition when evaluating $uid"
        echo "Found non-empty uid $uid\n";
    }
}
```

**Comment by muglug** [comment]
I've also add https://github.com/vimeo/psalm/commit/0eedad4f6a4080b0ece8130dd1a698d5985a82cf which includes an issue you can suppress – I realise that here you want different suppression behaviour for global vars vs function scoped vars.

**Comment by muglug** [comment]
Also, if you're doing what I *think* you're doing, this might come in handy:

https://github.com/vimeo/psalm/blob/e08b11b1449a145511ee042c83edf3cd39b2c833/examples/TemplateChecker.php

It's a plugin that checks templates, and uses an annotation at the top of the file to specify the method that generated the view variables, which in this case it scrapes off `$this` vars of the method in question.

See also  https://github.com/vimeo/psalm/blob/e08b11b1449a145511ee042c83edf3cd39b2c833/tests/MethodMutationTest.php, which tests the functionality that powers this

**Comment by TysonAndre** [comment]
Thanks!

Unfortunately, the template system I'm referring to is pretty unanalyzable - templates will be reused, combinations of $this and global variables exist, and templates are rendered from the global scope ($page and setters)

**Comment by muglug** [comment]
I hear you. Also, method mutation checks are not fast, but worth it for our use case, where we have stuff like

```php

class Foo {
  public function bar() {
    $this->badger = "hello";
    $this->updateBadger(); // $this->badger now is typed to int|string[]
  }

  public function updateBadger() {
    if (rand(0, 1) {
      $this->badger = 5;
    } else {
      $this->removeBadger();
    }
  }

  private function removeBadger() {
    $this->badger = ["hello"];
  }
}
