### ISSUE TITLE
Not possible to set template property (read only?)

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#3601]
It seems like template properties are read-only? Using the example from documentation, this snippet:

```php
/**
 * @template T
 */
class MyContainer {
  /** @var T */
  private $value;

  /** @param T $value */
  public function __construct($value) {
    $this->value = $value;
  }

  /** @return T */
  public function getValue() {
    return $this->value;
  }

  /**
   * @param T $value
   * @return void
   */
  public function setValue($value) {
    $this->value = $value;
  }
}

$cont = new MyContainer(10);
$cont->setValue(11);
```

fails with

> ERROR: InvalidArgument - templatetest.php:30:17 - Argument 1 of MyContainer::setValue expects int(10), int(11) provided (see https://psalm.dev/004)

This should probably be more clear in the documentation. Or even better, make template properties both write and read. :)

NB: The situation does not improve if you use `@template T of int`.

**Comment by olleharstedt** [comment]
> Hey @olleharstedt, can you reproduce the issue on https://psalm.dev ?

Yes.

**Comment by andrew-demb** [comment]
Bot request a link with provided code on psalm.dev :)

Link to code with issue - https://psalm.dev/r/33b27f6373

**Comment by olleharstedt** [comment]
> Bot request a link with provided code on psalm.dev :)

Oh! OK, good info. :laughing:

**Comment by muglug** [comment]
Psalm will type generic params as strictly as possible, but you can override with a `@var` docblock: https://psalm.dev/r/d802d57c9b

**Comment by olleharstedt** [comment]
> Psalm will type generic params as strictly as possible, but you can override with a `@var` docblock: https://psalm.dev/r/d802d57c9b

Thanks! Can we add this info to the manual somehow?

**Comment by muglug** [comment]
@olleharstedt sure, if you can find a good place for it
