### ISSUE TITLE
Passing child argument TypeCoercion

### ISSUE THREAD

**Issue by matiux** [vimeo/psalm#3604]
I have a problem with passing child argument to a method.

Is there a way to handle this situation?

https://psalm.dev/r/732643390e

**Comment by weirdan** [comment]
The error looks valid. Can you explain what you're trying to do?

**Comment by SalvatorePollaci** [comment]
It seems to me that as RequestB simply extends RequestA without changing anything, @matiux is trying to use them interchangeably.

**Comment by muglug** [comment]
Yeah, but that violates LSP

**Comment by olleharstedt** [comment]
If RequestA and RequestB should be used interchangeably, the correct solution is to use a Reqest interface, not an object hierarchy. It's not type-safe to cast RequestA to RequestB, since RequestB is a specialization.
