### ISSUE TITLE
list does not contain iterable

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#3605]
https://psalm.dev/r/d1a18e0d8d

This is a valid and logical php: you get keys and you check all of them are strings.

I believe after the line 16 the `$keys` should be narrowed to either `list<string>` or `iterable<string>`.

Yet it does not.

**Comment by Great-Antique** [comment]
Another example: https://psalm.dev/r/15c5758fe5

If you change order of asserts then you'll get reversed error
```
docblock-defined type iterable<mixed, non-empty-string> does not contain list<string>
```
