### ISSUE TITLE
.git folder exposed on psalm.dev

### ISSUE THREAD

**Issue by lmillucci** [vimeo/psalm#3606]
You can access .git folder from https://psalm.dev (e.g.. https://psalm.dev/.git/config) and you can download it. 
If you download the .git folder you can inspect the committed files and read the history. This is not the case but this could be a potential security issue if some secret is pushed.

**Comment by weirdan** [comment]
Psalm.dev code is public anyway (https://github.com/psalm/psalm.dev) but this does look like a misconfiguration.

**Comment by muglug** [comment]
Yeah, please reopen in that repo
