### ISSUE TITLE
Unused class/method misses const strings with leading backslash

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#3607]
This one is fine:
https://psalm.dev/r/17dc5a2e45

Psalm misses this one:
https://psalm.dev/r/c5d8cd84d8

But adding a leading backslash is legal:
https://3v4l.org/R1B3f

Thanks!

**Comment by muglug** [comment]
Mind a PR? This shouldn't be too difficult

**Comment by iluuu1994** [comment]
@muglug Sure 🙂 I'll do it when I'm off from work.
