### ISSUE TITLE
InvalidPropertyFetch error emmited on accessing static properties

### ISSUE THREAD

**Issue by emodric** [vimeo/psalm#3609]
After upgrading from 3.11.5 to 3.11.6 I started getting `InvalidPropertyFetch` error on accessing static properties where class name is stored in a variable.

Issue reproducer at https://psalm.dev/r/7bad6b85e8

**Comment by mr-feek** [comment]
@muglug happy to make a PR if you'd like to provide some guidance :)

**Comment by muglug** [comment]
@mr-feek I think the solution is to narrow [this check](https://github.com/vimeo/psalm/blob/98622783ecd6ed03ab5b4b7ef42c2330ce261c30/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/PropertyFetchAnalyzer.php#L1086) to only match when `$stmt->class` has an object (where some `$stmt_class_type->hasObjectType()`

**Comment by muglug** [comment]
so you'll need to run that expression through `ExpressionAnalyzer::analyze` so the `$statements_analyzer->node_data` has the correct type

**Comment by muglug** [comment]
Actually let me have a go at this, it's a little tricky

**Comment by mr-feek** [comment]
hah, i gave it a go here https://github.com/vimeo/psalm/compare/master...mr-feek:fix-class-name-static-props-access?expand=1 @muglug

**Comment by muglug** [comment]
Thanks, I realised my suggestion would still break in this scenario:

```php
class Beep {
    public static string $boop = "boop";
}
$beep = rand(0, 1) ? new Beep() : Beep::class;
echo $beep::$boop;
```

so ended up with something a little more complex

**Comment by mr-feek** [comment]
Thanks @muglug ! Do you consider "hotfix releases" in order to fix regressions so we don't have to wait ~ 2 weeks for the next release?

**Comment by emodric** [comment]
A hotfix release would be great, to fix our CI!

Thanks @mr-feek and @muglug for speedy fix :+1:

**Comment by muglug** [comment]
Yeah I should have a release this weekend

**Comment by TysonAndre** [comment]
I still see this when the class name is returned by get_class() - https://psalm.dev/r/6fa0f75968

Maybe a different issue type should be emitted for unanalyzable static property fetches when the class is a string?

**Comment by emodric** [comment]
This one too still has issues:

https://psalm.dev/r/2835c940a7

**Comment by sapphirecat** [comment]
Found this issue because I am seeing this happen on 3.13.1.  (In my actual code base, Psalm knows it's of type class-string, but the error on the site is displaying as "of type string".  I'm not sure why that happens, or if that's important.)

https://psalm.dev/r/ecc58fd19f

**Comment by weirdan** [comment]
> but the error on the site is displaying as "of type string". I'm not sure why that happens, or if that's important.)

That's because you need to use `@param` to annotate parameters, but you used `@var` instead.

**Comment by sapphirecat** [comment]
> That's because you need to use `@param` to annotate parameters, but you used `@var` instead.

Alas, I should have checked it in PhpStorm first. Thanks. I can confirm my actual code uses `@param` properly.
