### ISSUE TITLE
func_num_args in param-out

### ISSUE THREAD

**Issue by hectorj** [vimeo/psalm#3611]
Hi!

I was trying to use `func_num_args` in a conditional type in a `param-out`, and it seems to not be possible: https://psalm.dev/r/86edc5a13e

I'm not sure if this is a bug or a feature request.

**Comment by AndrolGenhald** [comment]
Is this still wanted? The example you gave is actually incorrect, `funcOut($bool, 0)` would have a docblock return type of `false` but it would actually be `true`. I think adding automatic templates for [this](https://psalm.dev/r/7f8ac32a96) like we do for [return types](https://psalm.dev/r/4b48eb0834) and fixing [this](https://psalm.dev/r/ca03856a9b) is a better option (I think we also have an issue for that `ReferenceConstraintViolation` but I'm not seeing it right now).

**Comment by hectorj** [comment]
Hi!

Sorry, this is old and I don't really use PHP anymore.

We can close it if you want.
