### ISSUE TITLE
Support looking for classes without full analyzing

### ISSUE THREAD

**Issue by JeroenDeDauw** [vimeo/psalm#3618]
In my project I used a number of classes defined and autoloaded elsewhere. This leads to `UndefinedClass` errors, forcing me to suppress `UndefinedClass` for my whole project.

My project is an extension to MediaWiki. MediaWiki defines and autoloads the missing classes before invoking my project. I do not wish to analyze the whole of MediaWiki, which coincidentally leads to a crash https://github.com/vimeo/psalm/issues/3617. Ideally I can just tell Psalm to chill out about some specific missing classes. Or to look at the MediaWiki classes but not report on those (or crash).

I had the same issue with PhpStan and fixes it by using the `scanDirectories` option:

![image](https://user-images.githubusercontent.com/146040/85094863-1f15a100-b1f0-11ea-95ed-b5a91f56de26.png)

Twitter thread: https://twitter.com/psalmphp/status/1273817066664009728

**Comment by JeroenDeDauw** [comment]
![image](https://user-images.githubusercontent.com/146040/85095035-8895af80-b1f0-11ea-8474-fa1e3c3051b8.png)

**Comment by muglug** [comment]
This is basically a matter of adding an `<extraFiles>` block to the config – @JeroenDeDauw do you mind creating a PR with the documentation? I can do the implementation

**Comment by JeroenDeDauw** [comment]
![image](https://user-images.githubusercontent.com/146040/85098581-6fdec700-b1fb-11ea-94c7-9865b50d243f.png)

Woha that is some speed right there!

**Comment by JeroenDeDauw** [comment]
I will verify this works for me and then update the docs

**Comment by JeroenDeDauw** [comment]
Works like a charm! Documented with https://github.com/vimeo/psalm/pull/3619
