### ISSUE TITLE
`InvalidReturnType` with `@psalm-type` containing `true|false` via constants

### ISSUE THREAD

**Issue by andyg0808** [vimeo/psalm#3623]
If a `@psalm-type` definition contains constants which evaluate to `true` and `false`, we get an `InvalidReturnType` error when using it as the return type of a getter and the type of the variable being returned:
https://psalm.dev/r/15813b3d8f

**Comment by orklah** [comment]
Seems fixed since

**Comment by weirdan** [comment]
Indeed.
