### ISSUE TITLE
UndefinedMagicPropertyFetch and UndefinedMagicPropertyAssignment regression when docblock comes from trait

### ISSUE THREAD

**Issue by kevinsmith** [vimeo/psalm#3624]
This is a regression from v3.11.5 to 3.11.6.

Magic properties defined in the docblock of a trait are no longer recognized:

https://psalm.dev/r/fa32446291

Whereas if the docblock is attached to the class, the magic properties are recognized.

https://psalm.dev/r/7b9a073592

**Comment by muglug** [comment]
Hmm, that doesn't seem like it should _necessarily_ work in the first place, but I guess I can make an exception

**Comment by muglug** [comment]
i.e. it's something that worked by accident

**Comment by kevinsmith** [comment]
Totally understand. If it were my code, I’d change it, but it’s coming from code generated by https://github.com/atlasphp/Atlas.Orm

**Comment by kevinsmith** [comment]
Awesome, thank you!
