### ISSUE TITLE
"The call to ::getIterator is not used" reported right where it's used

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#3625]
Hi,

We got a strange error on phpDocumentor CI:
https://github.com/phpDocumentor/phpDocumentor/runs/790360908?check_suite_focus=true#step:9:18
The error warn of an issue with a getIterator function being unused here:
https://github.com/phpDocumentor/phpDocumentor/commit/337b40d4e57f3c45421927b672076d40006b6f2a#annotation_257518989

But that's exactly the line where it's actually used, I don't understand what psalm is trying to report here.

I couldn't reproduce the issue locally, but phpDocumentor CI is complex so I don't have the same setup.

The issue was "solved" by changing "findUnusedVariablesAndParams" to false, but it'd be cool to be able to enable this check again.

Do you have an idea what could be the issue here?

**Comment by weirdan** [comment]
`Call to ... unused` actually refers to the return value of a pure function, as calling a pure function without using its result is pointless. It doesn't seem appropriate here though.

**Comment by weirdan** [comment]
Reproduced with https://psalm.dev/r/6287fdb60c
@orklah is your code similar to that?

**Comment by orklah** [comment]
> @orklah is your code similar to that?

Kinda, but there isn't a psalm-immutable annotation in my case. And without it I can't reproduce the issue at all...

**Comment by enumag** [comment]
Here are my reproducers from #4373 - slightly cleaner as they don't have other problems:

https://psalm.dev/r/dd77299d18
https://psalm.dev/r/ab4bb38b1e

**Comment by muglug** [comment]
Thanks @enumag!
