### ISSUE TITLE
Add option to print documentation for infrequently used/experimental CLI flags?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3628]
E.g. `--extended-help`.

for example, `--taint-analysis`/`--track-tainted-input`/`--security-analysis` from https://github.com/vimeo/psalm/issues/611 is not documented, making figuring out how it's meant to be used harder.

**Comment by muglug** [comment]
If you'd waited a minute... https://github.com/vimeo/psalm/commit/d46283075d76ed244f7825b378eeb1cee246af73
