### ISSUE TITLE
MixedInferredReturnType emitted on abstract ancestor method instead of the analyzed method

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#363]
Is this the intended behavior?

Observed: Shows file and line number on MyClass, but correctly says Implementer::getEntries
Expected: Shows file and line number for the source of the method body. (If something is a trait, then either the `use` statement or the trait implementation.)

- It'd make more sense to add `@psalm-suppress` to class Implementer
- It's usually faster to fix if you're directed to the method body, either by adding a more specific return type or by fixing a bug in the method body.

```
ERROR: MixedInferredReturnType - src/abstract.php:4:8 - Could not verify return type 'array<mixed, array<mixed, string>>' for Implementer::getEntries       
    /**                        
     * @return string[][]      
     */                        
    abstract public function getEntries();    
```

```
<?php
abstract class MyClass {
    /**
     * @return string[][]
     */
    abstract public function getEntries();  // Observed: MixedInferredReturnType on *this* line
}

class Implementer extends MyClass {
    public function getEntries() {  // Expected: MixedInferredReturnType on *this* line, including the same expected return type in the message.
        /** @var mixed $x */
        $x = [];
        return $x;
    }
}
```

**Comment by muglug** [comment]
It *was* intended, but I agree that, in the harsh light of day, it doesn't make a ton of sense.
