### ISSUE TITLE
How to foreach over $_POST 

### ISSUE THREAD

**Issue by ignacvucko** [vimeo/psalm#3630]
What is the proper way of doing the below and avoiding the MixedAssignment error?

https://psalm.dev/r/b1c7d6a0cd

`foreach ($_POST as $k=>$v) { }`

ERROR: MixedAssignment - Unable to determine the type that $v is being assigned to (see https://psalm.dev/032)

Is this the ONLY way?
/** @var mixed */

**Comment by weirdan** [comment]
Something like this should work: https://psalm.dev/r/951ae831b6

**Comment by ignacvucko** [comment]
OK thanks so much!
