### ISSUE TITLE
Cannot detect check for null when assigning to a variable

### ISSUE THREAD

**Issue by Nyholm** [vimeo/psalm#3631]
I found this bug. Not sure if it is "too complex" or not. I just thought to report it.

```php
function takesAString(string $name): void {
    echo "hello: ".$name;
}

function randomReturn(): ?string {
    return rand(1,2) === 1 ? 'foo' : null;
}

$name = randomReturn();

// Assignment in if does not work
if ($hasStringValue = $name !== null) {
    takesAString($name);
}
```

https://psalm.dev/r/c9ebe1f843

**Comment by muglug** [comment]
Generally if it works in TypeScript it should work in Psalm, and the example in this ticket works in TypeScript (so it now works in Psalm too).

The other example in the link _doesn't_ work in Psalm, as it would require some pretty complex analysis:

```
$hasStringValue = $name !== null;
if ($hasStringValue) {
    takesAString($name);
}
```

**Comment by Nyholm** [comment]
Lovely. Thank you for a quick fix.

**Comment by muglug** [comment]
The fix caused a regression so I'm unfixing for now
