### ISSUE TITLE
Fail to stub NoRewindIterator

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#3632]
I am trying to add a stub of `NoRewindIterator` to my project, but `TKey`, `TValue` do not work. They work if I name the class differently.

https://psalm.dev/r/c507381060

**Comment by vudaltsov** [comment]
Same with `LimitIterator` https://psalm.dev/r/e895d1ef0a
Btw, should I suggest them to CoreGenericClasses.phpstub?

**Comment by orklah** [comment]
Not sure what was the cause for this but thise stubs have been added in Psalm since. Maybe this could be closed?
