### ISSUE TITLE
Add an option to dump php backtraces when emitting issues, for debugging?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3634]
Something along the lines of http://github.com/tysonandre/psalm/commit/3fa33e07a94b7d16e262cc0e89713e1c1ef9cf95

E.g. a CLI flag such as `--debug-emitted-issues`, or an environment variable.

This may help in debugging by making it easy to see what code/plugin caused an issue to be emitted

**Comment by muglug** [comment]
Please create a PR for that!
