### ISSUE TITLE
MixedAssignment error when copying an array<array-key,mixed> 

### ISSUE THREAD

**Issue by ignacvucko** [vimeo/psalm#3638]
Sorry to bother guys, but I am new to psalm and have wasted hours on this.  I have read the docs and tried everything but can't seem to find a solution. 

https://psalm.dev/r/043fc31e07

This is just copying an associative array, but the assignment results in the following error:
INFO: MixedAssignment - 13:5 - Unable to determine the type of this assignment

https://psalm.dev/docs/running_psalm/issues/MixedAssignment/

(NOTE: I'm not just trying to copy an array in my actual code...)

**Comment by weirdan** [comment]
Another `@var mixed` should do the trick (https://psalm.dev/r/4065bf2471), [documented here](https://psalm.dev/docs/annotating_code/typing_in_psalm/#assignment-typehints). Alternatively, you could suppress this specific issue: https://psalm.dev/r/2aa01fb375

However, it's usually better to figure out how to work with something more specific than `mixed`.

**Comment by ignacvucko** [comment]
OMG, thank you!

I had tried all of the below without success:
```
/** @var mixed $v */
/** @var mixed $k */
/** @var mixed $b */ 
/** @var mixed $b[$k] */
$b[$k] = $v;
```

I reread the documentation, but couldn't find an example where it excludes the variable name.
So when should you use @var with a variable name vs use it without a variable name.
ie:
```
 @var mixed $k
vs
 @var mixed
``` 

Thanks

**Comment by weirdan** [comment]
> So when should you use @var with a variable name vs use it without a variable name.

You can use it on any assignment.

> I reread the documentation, but couldn't find an example where it excludes the variable name.

It's right there, in the section I linked above:
> [documented here](https://psalm.dev/docs/annotating_code/typing_in_psalm/#assignment-typehints)

![image](https://user-images.githubusercontent.com/57403/85342586-a8c8b580-b4f3-11ea-9ea8-cd23ea684f4f.png)

**Comment by ignacvucko** [comment]
Sorry, I guess I meant to say, in the examples above, when should you use:
```
@var int
vs
@var int $a
```
And apart from syntax, is there difference?

Is the latter always preferred to the former only as a comment stating that it applies to the $a variable.  Should you always try to use the latter and only use the former if you can't?  For example, I assume that in my original example, I MUST use "@var mixed" because "@var mixed $b[$k]" is invalid.  Am I understanding that correctly?

**Comment by weirdan** [comment]
That's correct. Also, `/** @var type $name */` is better supported by other tools.
