### ISSUE TITLE
Unexpected MixedAssignment for returned value of __toString without `@return string`

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#364]
It's redundant to add `/** @return string */` to `__toString()`, so I'd rather not do that.
__toString was called directly to make it obvious the expression was an object.

Similarly, would prefer to not need to add `@return` for __clone(void), __debugInfo(array), __wakeup(void), __sleep(string[]), __unset(void), __isset(bool), __set(void), __construct/__destruct(void), which I haven't checked.

```php
<?php

class Test {
    public function __toString() {
        return 'testing';  // If this wasn't a string, psalm would warn.
    }
}
$t = new Test();
$x = $t->__toString();  // Unexpected MixedAssignment (psalm is expecting __toString to return a string inside the method body)
```

**Comment by muglug** [comment]
Had no idea you could call these directly. Will fix.

**Comment by muglug** [comment]
Thanks!

> Similarly, would prefer to not need to add @return for 

I check for `__` at the start of method names (except __toString) in the return type checks, so you don't have to add those. Which is probably unsafe (as I think it's not a reserved thing). Hmm.
