### ISSUE TITLE
Unexpected `ImpurePropertyAssignment`

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#3643]
This might just be me not understanding PHP/`@psalm-immutable`.
https://psalm.dev/r/a9f9ee8df8
It shouldn't be possible for anything else to hold a reference if I create it with `new` in the constructor?
Wrapping it in `clone` gets rid of the error but seems unnecessary?

**Comment by muglug** [comment]
Added to fix https://github.com/vimeo/psalm/issues/2805. Make the model immutable too and you won’t have a problem.

More generally, immutable objects also have the property that all methods should be externally-pure, which means that nothing should be able to mutate the state of the data held by immutable objects
