### ISSUE TITLE
Idea: Add a way to separately represent/suppress taint types (text, sql, etc.)

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3647]
For example, in an API rendering output to CLI output or Content-Type: text/plain, unescaped HTML won't matter, but sql or eval() or require() might be important for an end user to check for.

If a false positive for text is suppressed, there should still be a warning for sql.

Changing the issue types to TaintedInputSql/TaintedInputText/etc. is one possible way to do that.

Probably low priority - a stub filterFalsePositiveHtml() function could be used for known false positives, and errors might be rare in practice.

**Comment by muglug** [comment]
Psalm has a notion of "parent" issue types, so this could be introduced without incurring BC problems.

**Comment by orklah** [comment]
I think this has been implemented through the list of possible taints: https://psalm.dev/docs/security_analysis/
