### ISSUE TITLE
Ignore ParseError

### ISSUE THREAD

**Issue by XedinUnknown** [vimeo/psalm#3649]
Hi!

## Symptoms

Trivially, I need to parse `src` and `vendor`, and exclude `vendor` from analysis. Therefore, my `psalm.xml.dist` contains this:

```xml
    <projectFiles>
        <directory name="src"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
    <extraFiles>
        <directory name="vendor" />
    </extraFiles>
```

Unfortunately, this is [causing an issue][2] with PHPUnit 7.5.20:

```
ERROR: ParseError - vendor/phpunit/php-code-coverage/tests/_files/Crash.php:2:7 - Syntax error, unexpected '{', expecting T_STRING on line 2 (see https://psalm.dev/173)
class {CLASS}
```

Somehow, this file does not exist in [`_files`][1] at that version. Naturally, PHP parsing fails.

## Suggested Solution
I don't need to parse tests at all, and most people won't. They can contain purposefully invalid PHP, or simply some templates.
How could I exclude certain paths from being parsed at all?

[1]: https://github.com/sebastianbergmann/phpunit/tree/7.5.20/tests/_files
[2]: https://psalm.dev/r/49b9a2bdca

**Comment by XedinUnknown** [comment]
Totally.

**Comment by weirdan** [comment]
This is not a bug. You have a legitimate issue in a PHP code, and Psalm is telling you that - it's what it's designed to do. It's up to you to decide what to do with this information.

I would suggest:
1. Ignoring the error (see https://psalm.dev/docs/running_psalm/dealing_with_code_issues/)
```xml
  <ParseError>
    <errorLevel type="suppress">
      <file name="vendor/phpunit/php-code-coverage/tests/_files/Crash.ph" /> 
    </errorLevel>
  </ParseError>
```
2. Using `--prefer-dist` flag for composer (which is actually on by default). Many packages omit tests and other misc files from their dist archives.

**Comment by XedinUnknown** [comment]
Thanks!

I didn't mean at all that it's a but. But it's a case that needs to be dealt with. And what you suggest does exactly that. Only I couldn't find it in the docs. Maybe because it doesn't mention the possible errors.

Speaking of which, your suggestion doesn't work, because `ParseError` does not appear to be a possible error type in this context.

```
Problem parsing /srv/psalm.xml.dist:
  Error on line 27:
    Element '{https://getpsalm.org/schema/config}ParseError': This element is not expected.
```

My entire config file

```xml
<?xml version="1.0"?>
<psalm
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://getpsalm.org/schema/config"
        useDocblockTypes="true"
        errorLevel="1"
        strictBinaryOperands="false"
        rememberPropertyAssignmentsAfterCall="true"
        checkForThrowsDocblock="false"
        throwExceptionOnError="0"
        findUnusedCode="true"
        ensureArrayStringOffsetsExist="true"
        ensureArrayIntOffsetsExist="false"
        xsi:noNamespaceSchemaLocation="https://getpsalm.org/schema/config"
>
    <projectFiles>
        <directory name="src"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
    <extraFiles>
        <directory name="vendor" />
    </extraFiles>

    <issueHandlers>
        <ParseError>
            <errorLevel type="info">
                <file name="vendor/phpunit/php-code-coverage/tests/_files/Crash.ph" />
            </errorLevel>
        </ParseError>
    </issueHandlers>
</psalm>
```

**Comment by weirdan** [comment]
@muglug is there any reason why ParseError is not treated as a normal issue?

**Comment by muglug** [comment]
> is there any reason why ParseError is not treated as a normal issue?

Yes, because it's very rare that you want to continue analysing a file that has a parse error (unless you're in LSP mode, which has special ways to handle that).

**Comment by muglug** [comment]
@XedinUnknown your `extraFiles` can contain an `ignoreFiles` element with `<file name="vendor/phpunit/php-code-coverage/tests/_files/Crash.php" />` inside

**Comment by XedinUnknown** [comment]
@muglug, I thought it could! But couldn't find that in the docs. Still, it worked, thank you very much!

One thing that I would like to note, however, is that in the beginning I missed the last letter of the path, i.e. `Crash.ph`, and the error was saying

> Could not resolve config path to /srv//vendor/phpunit/php-code-coverage/tests/_files/Crash.ph

It was very confusing why the double slash `//` in the beginning of the path, and I was assuming that this is the problem. Took me a while to find that missing `p`. Could indicate a problem with how paths are handled internally in Psalm.

Thank you all very much!
