### ISSUE TITLE
Taint detection does not work for encapsulated strings (echo "$unsafe";)

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3655]
Observed: No TaintedInput is emitted, but it would be emitted if the quotes are removed
Expected: TaintedInput is emitted 

`$pdo->exec("select * from users where name='" . $name . "'")` in https://psalm.dev/docs/security_analysis/ suggests taint detection already works for concatenation but not encapsulation

```php
<?php

$unsafe = $_GET['unsafe'];
echo "$unsafe";
```

**Comment by TysonAndre** [comment]
src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php `analyze()` seems relevant for the concat implementation. 

src/Psalm/Internal/Analyzer/Statements/Expression/EncapsulatedStringAnalyzer.php is a candidate of where to add this taint tracking for encapsulated strings?

**Comment by muglug** [comment]
just FYI you can reproduce in psalm.dev by having `<?php // --taint-analysis` at the top

**Comment by weirdan** [comment]
> just FYI you can reproduce in psalm.dev by having `<?php // --taint-analysis` at the top

Does it work for other switches / settings?

**Comment by muglug** [comment]
That’s a negative (but feel free to add support for individual ones over at psalm.dev’s repo)
