### ISSUE TITLE
PHP_INT_MAX + 1 infers with wrong type

### ISSUE THREAD

**Issue by vladyslavstartsev** [vimeo/psalm#3658]
What psalm does 
https://psalm.dev/r/7a816734d7
What php does 
https://3v4l.org/KceOa

**Comment by muglug** [comment]
this is a silly example, I think – no real-world code looks like this.

**Comment by muglug** [comment]
Psalm does understand that some (non-division) operations between integers can result in floats, so it won't complain about `is_float` checks on the result: https://psalm.dev/r/0928e08685
