### ISSUE TITLE
Taint analysis for "`$input`" shell_exec() shorthand

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3659]
Not really a commonly used feature, but https://psalm.dev/r/45e54ce95a does not warn.

An equivalent explicit call to shell_exec() will warn.

**Comment by weirdan** [comment]
Locally it complains about `ForbiddenCode` though.

**Comment by TysonAndre** [comment]
The reasons I mention it (still low priority, could really use the better alternatives like proc_open in affected code):

- var_dump() is also the exact same issue name.
- there are some uses of `` that are safe (e.g. only literals), but others that are much less safe
