### ISSUE TITLE
Any example repo for testing the taint analysis

### ISSUE THREAD

**Issue by prabhu** [vimeo/psalm#3661]
Hello,

I am in the process of evaluating this tool for integration with shiftleft [scan](https://github.com/ShiftLeftSecurity/sast-scan/).

Is there a test vulnerable repo that I could use to understand and test the taint analysis feature?

**Comment by muglug** [comment]
No repo, but there are tons of examples in tests/TaintTest.php

**Comment by prabhu** [comment]
@muglug will you be able to share a json report or point me to a document that describes the json format used? The tool is not returning any results for me. I have tried few repos such as 

- https://github.com/appelsiini/vulnerable-laravel-app
