### ISSUE TITLE
understanding which types Psalm was not able to infer

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#3662]
If I run Psalm, I get a message like `Psalm was able to infer types for 94.5122% of the codebase`.

Is there a way to understand which types Psalm was actually not able to infer?

**Comment by muglug** [comment]
Yup, run Psalm at its strictest and it’ll tell you

**Comment by marcosh** [comment]
thanks! For future reference, when I'll be tempted to ask the same question again, there is a `totallyTyped` parameter in configuration

**Comment by weirdan** [comment]
I thought `totallyTyped` was deprecated though.

**Comment by muglug** [comment]
Yeah, errorLevel="1" is the way to go now

**Comment by thunderer** [comment]
@muglug I run Psalm with both `totallyTyped=true` and `errorLevel=1`. It infers types for about 99.1% of the code but does not show any more errors. What can I do to know where is the remaining 0.9%? Are suppressions counted in that percentage?
