### ISSUE TITLE
Improvements to parsing of `@psalm-taint-escape type` comments

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3664]
1. It may be useful to add a way to ignore all inputs (e.g. if a user must be admin to access an endpoint). E.g. `@psalm-taint-escape all`
2. `@psalm-taint-escape text some description` is unintuitively parsed - It escapes `text some description`, not `text` (the former does not exist)
3. Comma-separated lists of escaped taints such as `@psalm-taint-escape text, html` may be useful (e.g. for hashing)

**Comment by LukasReschke** [comment]
> Comma-separated lists of escaped taints such as @psalm-taint-escape text, html may be useful (e.g. for hashing)

Can't you achieve that already with separate lines?

https://psalm.dev/r/90c8f34473

**Comment by TysonAndre** [comment]
> `@psalm-taint-escape text some description` is unintuitively parsed - It escapes `text some description`, not `text` (the former does not exist)

I'm aware that separate lines are supported.

Supporting comma separated values would make writing comments more concise, and allowing spaces would allow you to provide a description of why the taint type was escaped on the same line as a taint type

**Comment by muglug** [comment]
I've fixed the parsing so only the first word is used. I'm not going to support comma-separated at the moment.
