### ISSUE TITLE
Taint detection should treat printf(), vprintf() as sinks

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3665]
and `var_dump()`, `var_export(expr, false)`, `print_r(expr[, false])`

E.g. https://psalm.dev/r/7a40cbd45d

```
/**
 * @psalm-taint-sink html $format
 * @psalm-taint-sink html $args
 */
function printf(string $format, ...$args): int {}
/**
 * @psalm-taint-sink html $format
 * @psalm-taint-sink html $args
 */
function vprintf(string $format, array $args): int {}
/**
 * @psalm-taint-sink html $var
 * @psalm-taint-sink html $args
 */
function var_dump($var, ...$args): void {}
```

One way to do that would be to add stubs such as the above to CoreGenericFunctions.php, or to a file conditionally loaded during taint-checking.

For printf(), it may be useful to be aware of the conversion specifiers, to avoid warning about `%d`. https://github.com/phan/phan/blob/master/.phan/plugins/PrintfCheckerPlugin.php and `ConversionSpec` exist to parse conversion specifiers from format strings

**Comment by orklah** [comment]
it was fixed for printf and var_dump. vprintf is still not
