### ISSUE TITLE
Support php 8.0 'mixed' type

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3667]
```php
<?php

function test(mixed $x): void {
}
test(123);
```

With `phpVersion="8.0"` in `psalm.xml`, this emits ReservedWord ... mixed is a reserved word. The type also gets parsed as TNamedObject (e.g. for return types for uniontype's 'mixed' property), which may need to be changed

**Comment by orklah** [comment]
Must have been added since: https://psalm.dev/r/7298993e91
