### ISSUE TITLE
Taint Analysis Questions (Documentation Improvement Issue)

### ISSUE THREAD

**Issue by ArtemGoutsoul** [vimeo/psalm#3672]
- Seems like --taint-analysis is a totally separate operation, it doesn't do any other analysis when this mode is enabled. If that's the case, would be nice to clarify in the docs
- How does --taint-analysis work with baseline?

**Comment by muglug** [comment]
> Seems like `--taint-analysis` is a totally separate operation, it doesn't do any other analysis when this mode is enabled. If that's the case, would be nice to clarify in the docs

Yes, that's the case, feel free to create a PR clarifying that

> How does `--taint-analysis` work with baseline?

By default Psalm uses whatever baseline you give it, but I've just added the option to use a custom baseline with `--use-baseline=<PATH>`

**Comment by ArtemGoutsoul** [comment]
Ok, made a PR https://github.com/vimeo/psalm/pull/3834
