### ISSUE TITLE
Wrong stub for Redis::getDbNum() ?

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#3673]
https://psalm.dev/r/88baf4bedf

[The docs](https://github.com/phpredis/phpredis#getdbnum) say: 

> Mixed Returns the database number (LONG) phpredis thinks it's pointing to or FALSE if we're not connected

yet Psalm seems to think it is guaranteed to return an integer.

**Comment by weirdan** [comment]
Yeah, it may return `false`: https://github.com/phpredis/phpredis/blob/a311cc4ec3cecdbaf83ba66985efa82137e37cc0/redis.c#L3368-L3377

**Comment by weirdan** [comment]
Closed by  c42dada
