### ISSUE TITLE
7.4 array_merge [...$a, $b] syntax problem

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#3674]
https://psalm.dev/r/3b4d8d27eb

**Comment by orklah** [comment]
This has been fixed

**Comment by AndrolGenhald** [comment]
@orklah Would you consider this a separate bug? https://psalm.dev/r/a346e01954 https://3v4l.org/k7r2N
Psalm seems to think there are only 2 elements in `$array`, I'm guessing due to the way loops are analyzed twice.

**Comment by orklah** [comment]
yeah, it's a separate issue

**Comment by weirdan** [comment]
https://psalm.dev/r/a346e01954
