### ISSUE TITLE
Idea: For --taint-analysis, add an multi line output mode that will output the contents of files and lines

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3676]
This would save people reading this from the need to open each file one at a time

- Keep printing the one line summary
- Below that, for each entry in the summary separated by `->`, print the entry on its own line  (optionally with N lines of surrounding context). If the entry is associated with a file and line, print the contents of that file at that line. If possible, highlight the expression that is tainted. Possibly combine entries if they're on the same file and line.

**Comment by prabhu** [comment]
Even better is to make the dataflow explicit in output format such as json.

**Comment by muglug** [comment]
Yeah, I think the json output will have a new field
