### ISSUE TITLE
Plugin Hooks: Can not implement some combinations of hooks

### ISSUE THREAD

**Issue by jarstelfox** [vimeo/psalm#3684]
The following Hooks have the same method name with different signatures:
https://github.com/vimeo/psalm/blob/master/src/Psalm/Plugin/Hook/AfterFunctionLikeAnalysisInterface.php
https://github.com/vimeo/psalm/blob/master/src/Psalm/Plugin/Hook/AfterClassLikeAnalysisInterface.php
https://github.com/vimeo/psalm/blob/master/src/Psalm/Plugin/Hook/AfterStatementAnalysisInterface.php

Since the method is the same, I can not implement more than of these interfaces at a time.

Use Case:

I want to analyze statement, class and function comments to ensure they all are either `//` or `/**` comments. Instead of `/*`.

**Comment by weirdan** [comment]
That's certainly inconvenient, however it's also not something that can be changed easily as it's a part of API. As a workaround you can implement them on separate classes that would delegate to a single internal plugin class / object:

```php
class AfterFunctionHandler implements AfterFunctionLikeAnalysis {
   public static function afterStatementAnalysis(....) {
        return InternalHandler::getInstance()->afterFunction(....);
  }
}
class AfterClassHandler implements AfterClassLikeAnalysisInterface {
  public static function afterStatementAnalysis(.....) {
       return InternalHandler::getInstance()->afterClass(....);
  }
}
....
```

**Comment by jarstelfox** [comment]
Thanks, @weirdan. I was already heading that direction with my plugin(s). I thought it was worth bringing to your attention.

Feel free to close this as I got the answer I needed.
