### ISSUE TITLE
Different type passes as template arguments

### ISSUE THREAD

**Issue by EvgeniiR** [vimeo/psalm#3686]
Hello, shouldn't psalm complain about different types passed as arguments in example: https://psalm.dev/r/f4c6715e78 ?

**Comment by orklah** [comment]
A template type doesn't need to be an atomic type, which means, it can be an union, or even a pseudo-type (like `scalar` for example)

In your case, T will just be inferred to the type `int(1)|string(a)`

**Comment by EvgeniiR** [comment]
Oh, Yes, thanks.
