### ISSUE TITLE
Idea: Treat $var() as a taint sink?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3687]
This could be a sink for all types (debug_print_backtrace(), phpinfo() for secrets, shell_exec(), etc).

https://psalm.dev/r/055225075d does not warn right now

This may have a high rate of false positives if the value is typically limited to methods of a known class

**Comment by muglug** [comment]
> if the value is typically limited to methods of a known class

That's a good point, which leads to another question: should enums (aka unions of string literals) carry tainted data?
