### ISSUE TITLE
Check filter type for filter_var() (etc) for taint detection?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3689]
https://psalm.dev/r/9a6b3a119f

Expected: No TaintedInput warnings

e.g. check if src/Psalm/Internal/Provider/ReturnTypeProvider/FilterVarReturnTypeProvider.php is possibly a type other than null/bool/int/float.

Low priority since I don't see many false positives with filter_var.

**Comment by muglug** [comment]
> Low priority since I don't see many false positives with filter_var.

Do you see any true positives? How does this compare to the MediaWiki plugin?

**Comment by TysonAndre** [comment]
I'm not deeply familiar with the MediaWiki Phan plugin. I tested it out again, and:

- It caught some of the same issues in examples I've mentioned
- I didn't figure out how to do the equivalent of `@psalm-taint-specialize` - tainted arguments to calls to one method invocation affected unrelated return values of the same expression
- The plugin currently seems to be building partial graphs and propogating taints from recorded argument types, instead of building a full graph of all of the taint edges from arguments to results, then using that to determine the taintedness result of a function call. It may also be sensitive to the order in which methods and method calls get analyzed. `--analyze-twice` may help somewhat.
- It doesn't have any references to `filter_var`, e.g. it warns about `echo filter_var($_GET['foo'], FILTER_VALIDATE_INT);`. If Phan actually inferred the type for filter_var to be int|false, I'd assume phan-taint-check-plugin wouldn't warn (taint checking is partially based on union types)
-

**Comment by mmcev106** [comment]
I'd like to invest some time in a PR to ignore false positives in this case.  Does anyone have any pointers on where to start in the code to save me some time?  It seems like this might be overlap with `psalm-taint-escape`'s conditional escaping feature, but perhaps there's a better example where we already have some conditional logic for built-in PHP functions.

**Comment by orklah** [comment]
I think this may be as easy as making a stub for filter_var like that: https://github.com/vimeo/psalm/blob/3fcfc948b0486eea8dbb346cfd2b213e184c7f06/stubs/CoreGenericFunctions.phpstub#L1188

However, filter_var have a ReturnTypeProvider and I don't know how much of the stub it overrides

**Comment by TysonAndre** [comment]
FILTER_VALIDATE_INT is only one of many types - there's also raw validation

**Comment by orklah** [comment]
> EDIT: missed that, didn't remember psalm had that feature

TBH, I just remembered it because @mmcev106 mentionned it 😄

**Comment by orklah** [comment]
I'm gonna consider this fixed. The original has another example that is still failing but everything is now in place for anyone to add more safe flags on filter_var if necessary
