### ISSUE TITLE
DocblockTypeContradiction  error seems wrong

### ISSUE THREAD

**Issue by koriym** [vimeo/psalm#3690]
Take a look at this snippet of code (https://psalm.dev/r/e4d7830656)
```php
<?php declare(strict_types=1);

function foo(int $i) : int
{
    if ($i > 0) {
        return $i;
    }
    throw new Exception;
}

function bar() : void
{
}

try {
    $a = foo(1);
    bar();
} catch (Exception $e) {
    $a = $a ?? 0;
}
echo $a;
```
`$a` is not sure in `catch` clause but the Psalm report as  `int does not contain null`.

**Comment by muglug** [comment]
The code is icky _enough_ that I won't fix it – instead you can initialise `$a` to `null`: https://psalm.dev/r/a82ae3f678

**Comment by koriym** [comment]
@muglug Ok. Thanks for the quick response!
