### ISSUE TITLE
Taint analysis aborts as soon as an unresolvable include is encountered

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#3691]
Hello,

Psalm taint analysis aborts when an include cannot be resolved.

As it cannot really be reproduced on psalm.dev (https://psalm.dev/r/9617d4dc9e) I have setup a minimal repo demonstrating the problem: https://github.com/LeSuisse/psalm-taint-analysis-abort-unresolvable-include

While continuing the analysis when a unresolvable include might be a source a false positive since a part of the information cannot be collected it also means we can miss some valuable errors. I have been a bit surprised at first because without the taint analysis Psalm still tries to continue its work.

**Comment by muglug** [comment]
>  I have been a bit surprised at first because without the taint analysis Psalm still tries to continue its work.

It doesn’t try very hard – it gives up warning about most things after an unresolvable include (which is why it's best to wrap those calls in a function)
