### ISSUE TITLE
@psalm-pure & UnusedMethodCall behave differently with mixin

### ISSUE THREAD

**Issue by micheh** [vimeo/psalm#3701]
Release 1.9.0 of webmozart/assert added a Mixin for the `all*` and `nullOr*` methods. Many of those have the `@psalm-pure` annotation.

When you tell Psalm to check for UnusedMethodCall, all methods of the Mixin are reported:
`UnusedMethodCall - ... - The call to Webmozart\Assert\Mixin::allInteger is not used (see https://psalm.dev/209)`

If you use the method for a single value (e.g. `Webmozart\Assert\Assert::integer`), no issue is reported (even though they also have a `@psalm-pure` annotation).

Psalm does not report an issue if the `@psalm-pure` annotation is removed from the mixin method (e.g. `Webmozart\Assert\Mixin::allInteger`).

https://psalm.dev/r/a92a5e3e58

**Comment by orklah** [comment]
This was fixed
