### ISSUE TITLE
psalm-suppress DuplicateFunction doesnt work

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#3703]
psalm-suppress DuplicateFunction doesnt work

This obviously is an absurd example, but it's just to showcase it:
https://psalm.dev/r/5fba1cd47c

Real use case:
if php uses a auto prepend file but I run psalm for this file, it get all functions reported as duplicate (correctly), but this is irrelevant since I am not actually executing this file but just want to fix all psalm issues in the pipeline. This is why I need the psalm suppress in this case.

**Comment by alfredbez** [comment]
Looks like a duplicate of #2872
