### ISSUE TITLE
Type overriding in Plugin

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#3707]
Could you tell me. Can I make a plugin to implement the following fp-like idea (be careful. it maybe weird for php worldview)

There is `Promise<TResult>` - represents async task.

There is `Either<TError,TResult>` - represents error or result.

I want to use a combination of them for everyday routine tasks like this:

```php
/**
 * @param string $userId
 * @psalm-return Promise<Either<UserNotFound,User>>
 */
function findUser(string $userId): Promise { ... }

/**
 * @param string $projectId
 * @psalm-return Promise<Either<ProjectNotFound,Project>>
 */
function findProject(string $projectId): Promise { ... }
```

```php
// $invite should be Promise<Either<UserNotFound|ProjectNotFound,Invite>> here
$invite = doEitherAsync(function() use ($userId, $projectId) {
    // Is User here. UserNotFound cannot be here
    $user = yield findUser($userId);
    // Is Project here. ProjectNotFound cannot be here.
    $project = yield findProject($project);

    return new Invite($project, $user);
});
```

`doEitherAsync` is something like "do notation from haskell" for poor php programmers.

Inside `doEitherAsync` `yield` means "bind".

What I want:

1. Combine all errors in `doEitherAsync` to result Either (UserNotFound|ProjectNotFound)
2. Unwrap type `Promise<Either<TLeft,TRight>>` to `TRight` inside `doEitherAsync`
3. Just understand how to do plugins for Psalm)

What I did:

1. I used `AfterFunctionCallAnalysisInterface` and I was able to collect all the errors for `TLeft`.
I fetched analysed callable from arguments of `FuncCall`. Then I traversed by all expressions with `yield` and assign new type to `$return_type_candidate`

2. For overriding type I used `StatementsSource::getNodeTypeProvider()` in the `AfterFunctionCallAnalysisInterface`:

```php
$type_provider = $statements_source->getNodeTypeProvider();
$old_type = $type_provider->getType($node_with_yield);
$new_type = // compute new type used $old_type
$type_provider->setType($node_with_yield, $new_type);
```

It seems that this doesn't work as I imagine)

How I can override type for expression?

**Comment by muglug** [comment]
Mind creating a repo with a reproducer?

**Comment by klimick** [comment]
@muglug created: https://github.com/klimick/async-either

Anything else you need?
