### ISSUE TITLE
Unexpected PossiblyUndefinedVariable in do {} while();

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#371]
```php
do {
    $result = rand(0,1);
} while (!$result);
```
Results in 
```
ERROR: PossiblyUndefinedVariable - q.php:4:11 - Possibly undefined variable $result, first seen on line 3
} while (!$result);
```
Obviously `do {} while();` is always executed at least once, so `$result` can never be undefined here.

**Comment by muglug** [comment]
Thanks – should be fixed now. Broken in https://github.com/vimeo/psalm/pull/365
