### ISSUE TITLE
Mutation in __clone should not be prohibited in @immutable classes

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#3710]
https://psalm.dev/r/72573563dd

**Comment by olleharstedt** [comment]
Why not, though?

**Comment by vudaltsov** [comment]
I would say, you don't expect that in any case. That's why it's called a **magic** method.

I think that immutability is about not changing state after an object is created. While `__clone` happens before creation is finished (within the clone operation).

I am interested in what @Ocramius thinks about this.

**Comment by Ocramius** [comment]
What's the use-case for changing state during cloning operations? Got something real-world?

Note that following psalm immutability rules, deep cloning is unnecessary, since immutable objects can only contain other immutable objects.

**Comment by vudaltsov** [comment]
I have an immutable JWT. And every time I change it via a `with*` method, I do `$clone->iat = new \DateTimeImmutable()`. I could move that to `__clone`.

**Comment by Ocramius** [comment]
I would say that `__clone` is only responsible for state cloning: it should not be used for mutating state or code reuse.

Two JWTs cloned from each other should not have a different "issued at" claim.

**Comment by vudaltsov** [comment]
@Ocramius , you expressed exactly what I was missing in my reasoning, thank you!
