### ISSUE TITLE
psalm-taint-specialize on class erases psalm-taint-source on method

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3711]
https://psalm.dev/r/0164fab5af

Also, psalm-taint-specialize on class does not track the properties an object was created with in the constructor, which is somewhat unintuitive.

- I see that psalm's stubs for `Exception`, `Throwable`, and `Error` use psalm-taint-specialize on the class. Haven't looked into how that affects getMessage() for a tainted message.

https://psalm.dev/r/8d4bec253a is a small change to the example in the docs

**Comment by TysonAndre** [comment]
Also, would it make sense to change the meaning of `psalm-taint-specialize` on `__construct` so that a constructor only affects the taintedness of that specific object, rather than all objects?

**Comment by muglug** [comment]
> Also, would it make sense to change the meaning of `psalm-taint-specialize` on `__construct` so that a constructor only affects the taintedness of that specific object, rather than all objects?

Sorry, could you give an example?

**Comment by TysonAndre** [comment]
I guess I misunderstood what `psalm-taint-specialize` does on an object. It didn't do what I thought it might do for instance properties, although that shouldn't be a surprise if the documentation said nothing about properties.

https://psalm.dev/r/b2c64ac85a

**Comment by muglug** [comment]
Oh that's definitely a bug
