### ISSUE TITLE
Unable to suppress TaintedInput on statement/function level

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3712]
Statement suppressions and function suppressions do not work on the outputted line.

Somewhat relatedly, it might be useful to suppress all taint flows that go through a specific method if `@psalm-taint-specialize` is not sufficient/appropriate. Right now, it's only possible to suppress flows through an entire file.

Expected: TaintedInput should not be emitted

```php
<?php // --taint-analysis
/**
 * @psalm-suppress TaintedInput
 */
function unsafe() {
    /** @psalm-suppress TaintedInput */
    echo $_GET['x'];
}
```

**Comment by TysonAndre** [comment]
https://psalm.dev/r/a13ccdf7b9

**Comment by muglug** [comment]
This is sadly impossible given how `TaintedInput` issues are emitted, and I don't think that will change anytime soon.

**Comment by muglug** [comment]
Oh actually this can be prevented just by checking for local suppressed issues when generating the taint paths
