### ISSUE TITLE
Distinguish between user-defined and internal functions in ImpureFunctionCall?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3713]
- ImpureFunctionCall for user-defined functions
- PossiblyImpureFunctionCallInternal for internal functions with unknown status
- Optionally, ImpureFunctionCallInternalDefinitelyImpure for known impure functions such as printf

There's a long tail of functions in https://www.php.net/mbstring which are pure but do not have stubs in psalm (e.g. mb_chr()), and extensions that are rarely used, so being able to differentiate would make it easier to get started

**Comment by muglug** [comment]
I don't think this is worth doing, sorry
