### ISSUE TITLE
Array modification leading to LessSpecificReturnStatement and MoreSpecificReturnType

### ISSUE THREAD

**Issue by iquito** [vimeo/psalm#3720]
Psalm seems to almost fully understand how arrays are put together and modified, but there seems to be a slight disconnect in this example: 

https://psalm.dev/r/1788cf6727

All the information is there specifically for Psalm to recognize the type, but the inferred type still ends up being not quite accurate.

**Comment by weirdan** [comment]
`$i[$id][$type] = true;` - the type is altered here. Commenting that line out makes the inference work as expected.

**Comment by iquito** [comment]
Yes, but $type is specifically defined as either "internal" or "ported", so it does not actually change the array type/definition.
