### ISSUE TITLE
Uncaught InvalidArgumentException: $class cannot be empty with broken @method docblock

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#3721]
Seen in the wild with [this file][1]

[1]: https://github.com/phpspec/prophecy/blob/451c3cd1418cf640de218914901e51b064abb093/spec/Prophecy/Doubler/ClassPatch/MagicCallPatchSpec.php

_Originally posted by @XedinUnknown in https://github.com/vimeo/psalm/issues/1730#issuecomment-651750564_

Reproduced: https://psalm.dev/r/ba7f32349e (psalm.dev produces no visible output because of notices polluting the JSON output).

**Comment by XedinUnknown** [comment]
Thanks for looking into it! At a glance, I couldn't determine what was wrong with the file. But in any case, no matter how wrong the file is, it should not cause Psalm to crash. Looking forward!
