### ISSUE TITLE
Mark create_function as an eval sink for taint detection?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3723]
https://www.php.net/create_function

> This function internally performs an eval() and as such has the same security issues as eval(). Additionally it has bad performance and memory usage characteristics.

https://psalm.dev/r/3824177fbb

Motivation: It's more harmful with user input than with hardcoded literal strings.

**NOTE: This is deprecated and will be removed in php 8.0 - psalm should ensure that targeting php 8.0 will infer this function does not exist**

**Comment by muglug** [comment]
Mind PRing this? It’ll follow the same pattern as the fix for `unserialize`
