### ISSUE TITLE
MixedPropertyFetch && MixedOperand on @property-read

### ISSUE THREAD

**Issue by jrushlow** [vimeo/psalm#3727]
I'm running into an issue in a laravel app where psalm is throwing a `MixedPropertyFetch` & `MixedOperand` error when calling a declared `@property-read` type hint. I have a feeling the latter would resolve on it's own once psalm understands what the property type is.

https://psalm.dev/r/199c02d75a

I haven't been able to figure out how to correctly tell psalm what the property is that's being type hinted..

**Comment by jrushlow** [comment]
just realized I could omit the null in  `..? null :...` as it isnt doing anything in the provided example.. however the result is still the same if i `...?:...`

**Comment by weirdan** [comment]
By default Psalm only considers `@property-*` docblocks when it sees magic `__get()`/`__set()` on a class: https://psalm.dev/r/57d091c044
You can override this with `usePhpDocPropertiesWithoutMagicCall="true"` in your `psalm.xml`.

**Comment by jrushlow** [comment]
ahhhh alrighty that makes sense.. thanks!

**Comment by jrushlow** [comment]
@weirdan so I set 
```
// psalm.xml
<psalm
    ....
    usePhpDocMethodsWithoutMagicCall="true"        // I have @method docs too
    usePhpDocPropertiesWithoutMagicCall="true"
>
```

I get:

`ERROR: MixedPropertyFetch - app/Models/Product.php:87:44 - Cannot fetch property on mixed var $this->line (see https://psalm.dev/034)
        (null === $this->line) ?: $name .= $this->line->name;
`

And the class: 
```
// Product.php (Eloquent Model)

/**
 * @property-read null|\App\Models\ProductLine $line
 */
class Product extends Model
....
public function aMethod(?string $name): ?string
{
    ...
    (null === $this->line) ?: $name .= $this->line->name;
    ...
}
```

**Comment by weirdan** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/57403/86405110-7704db00-bcb9-11ea-8abe-b399dc239f49.png)

Could it be something else interfering, e.g. laravel psalm plugin?

**Comment by muglug** [comment]
@jrushlow you'd need to create a reproducer repo for us to check that

**Comment by jrushlow** [comment]
When I disabled the `psalm-plugin-laravel` the error(s) went away and my results were in line with @weirdan 's results. Of course I got a slew of other errors because the laravel plugin was disabled. 

I take it that a plugin will override the base `psalm.xml` . Is it possible to override a psalm plugin or "force" a plugin to use directive(s) set in the base `psalm.xml`?

@muglug no problem. do you think you still need one now that I've confirmed this is associated with the laravel plugin being enabled?

**Comment by weirdan** [comment]
Cc: @mr-feek

**Comment by mr-feek** [comment]
@jrushlow 👋 By any chance is `line` a polymorphic relation? Could you share the entire code of the method that is causing the issue please?
