### ISSUE TITLE
`use Example\DoesntExist;` doesn't trigger UndefinedClass

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#3728]
Is this intentional, a limitation or a bug?

https://psalm.dev/r/96d8e6525a

PS: Ideally this example would also trigger an `UnusedImport` issue (as I regularly forget to remove unused imports).

**Comment by muglug** [comment]
It's intentional – a `use` is just an alias to be used later. PHPCS Fixer can remove them automatically, though.
