### ISSUE TITLE
Weird behavior with typed properties

### ISSUE THREAD

**Issue by evonicgu** [vimeo/psalm#3733]
Here's the code:
```PHP
class ...
{
    ...
    /**
     * @var array<string,array{function:string|Closure,args:array<string>,priority?:int}>
     */
    protected array $commonMethods;

    public function __call(string $name, array $args)
    {
        if (!isset($this->commonMethods)) {
            $this->commonMethods = [];
        }
        ...
    }
}
```

Psalm report: `Cannot resolve types for $this->commonMethods with type array<string, array{args: array<array-key, string>, function: Closure|string, priority?: int}> and !isset assertion (see https://psalm.dev/056)`
I think everything is ok here, because typed properties can be undefined and i must check them before using.

**Comment by evonicgu** [comment]
https://psalm.dev/r/f0c77ef782

**Comment by muglug** [comment]
You can fix by making the property nullable: https://psalm.dev/r/e6c35c2a1c
