### ISSUE TITLE
Wrong PossiblyNullArrayAccess on list-like assign

### ISSUE THREAD

**Issue by ygottschalk** [vimeo/psalm#3742]
https://psalm.dev/r/19eed59794
line 10 should not throw an error

https://3v4l.org/XasUH

**Comment by ygottschalk** [comment]
duplicate of https://github.com/vimeo/psalm/issues/3377 but the discussion there sadly died...
Is final ruling of this issue https://github.com/vimeo/psalm/issues/3377#issuecomment-629676839?

**Comment by muglug** [comment]
My decision stands on the "just suppress the warning", but Psalm will now add `null` to the resultant type so your check passes.
