### ISSUE TITLE
Add a psalm.xml config:  ./vendor/bin/psalm --init

### ISSUE THREAD

**Issue by mevsme** [vimeo/psalm#3747]
Tell me please what does it mean and where should I create this file and what I should put in it?
When I do
````php ./vendor/bin/psalm --init````
I get
````

dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../vimeo/psalm" && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated

            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

````

When I do
````./vendor/bin/psalm --init````
I get 
````
'.' is not recognized as an internal or external command,
operable program or batch file.
````

I am using Windows.
I think installation documentation is not very clear for newbies.

If I run execute src/psalm.php I get
````
Calculating best config level based on project files
Uncaught Psalm\Exception\ConfigCreationException: Problem during config autodisc
overy - could not find composer.json during initialization. in D:\Dropbox\Dev\sh
oom\www\vendor\vimeo\psalm\src\Psalm\Config\Creator.php:171
Stack trace:
#0 D:\Dropbox\Dev\shoom\www\vendor\vimeo\psalm\src\Psalm\Config\Creator.p
hp(55): Psalm\Config\Creator::getPaths('D:\\Dropbox\\Dev\\...', NULL)
#1 D:\Dropbox\Dev\shoom\www\vendor\vimeo\psalm\src\Psalm\Config\Creator.p
hp(83): Psalm\Config\Creator::getContents('D:\\Dropbox\\Dev\\...', NULL, 1, 'ven
dor')
#2 D:\Dropbox\Dev\shoom\www\vendor\vimeo\psalm\src\psalm.php(277): Psalm\
Config\Creator::createBareConfig('D:\\Dropbox\\Dev\\...', NULL, 'vendor')
#3 {main}
(Psalm 3.12.2@7c7ebd068f8acaba211d4a2c707c4ba90874fa26 crashed due to an uncaugh
t Throwable)
`````

So how do I use it? I am not familiar with composer.

**Comment by weirdan** [comment]
Can you describe your environment in more details? How did you install Psalm, and how you run it? Does any other script from `vendor/bin` works for you?

**Comment by mevsme** [comment]
Thanks for your attention and time. There is no any environment. It's my PC and Windows, I have PHP and I am a monkey-coder. How Psalm is supposed to work? I thought it is some CLI program that will scan my project and make some report. I have composer and I installed it to my project via composer. What next? I never use composer in my projects and I have no idea how to use it. Maybe I need to embed it to my project into `index.php`? I saw a post about a new version of Psalm, I have no idea how static analizators work so maybe some more detailed explanation at the installation page would be great. Cuz I did what it said and it didn't work. I haven't looked into the documentation much yet. Still don't get where should I put psalm.xml. root, vendor/vimeo/psalm or somewhere else?

**Comment by weirdan** [comment]
> There is no any environment. It's my PC and Windows, 

That's an environment as well.

> I thought it is some CLI program that will scan my project and make some report. 

That's correct.

> Maybe I need to embed it to my project into index.php? 

No, it's a standalone tool. It cannot and should not be embedded into your application.

> Still don't get where should I put psalm.xml. root, vendor/vimeo/psalm or somewhere else?

Generally people put it into the root folder of the app.

> How do I run ./vendor/bin/psalm at Windows? It's bash script

What files do you have in `vendor/bin`? If memory serves on Windows composer generates `*.bat` files, so you may need to run that instead.

**Comment by furkantopcuoglu** [comment]
windows = php vendor/vimeo/psalm/psalm --help

**Comment by orklah** [comment]
php command is not even needed `vendor\bin\psalm --init` works pretty well for me

**Comment by orklah** [comment]
closing this as answered
