### ISSUE TITLE
PossiblyFalseAgument for Echo false

### ISSUE THREAD

**Issue by jarstelfox** [vimeo/psalm#3750]
See: https://psalm.dev/r/9eb24aea1b

Null and false have the same behaviour: https://3v4l.org/3VMcK i.e. do nothing

It seems `echo null;` works fine, but `echo false;` does not.

**Comment by orklah** [comment]
Well, I can understand why some code could output null, the case for false is weirder.

I prefer to be warned on those because for me, it's most likely a bug in the code (even if you're totally right that the output is the same)

Do you care sharing a real code example where the output is echo false by purpose?

**Comment by jarstelfox** [comment]
Hey @orklah, this came about due to us using the example template checker.

We have quite a few examples where the default behavior is expected in older templates like:

`<?= date('Y-m-d H:i:s', $date) ?><
`

The psalm fix would be

`<?= date('Y-m-d H:i:s', $date) ?: '' ?>`

Although this does work around the problem, the behavior is the same.

**Comment by orklah** [comment]
I'm surprised `ignoreInternalFunctionFalseReturn` doesn't already solve the issue. Or maybe you prefer not using it for this case?

**Comment by muglug** [comment]
`ignoreInternalFunctionFalseReturn` is for return values, not argument types.

I reasoned that if `|null` is suppressed then `|false` probably should be too - both aren’t great IMO.

**Comment by jarstelfox** [comment]
@muglug thanks,

Maybe both null / false in echos deserve a config setting?

I can see a case for wanting to know about it. That or maybe an example plugin which would be enough for people.
