### ISSUE TITLE
Wrong MoreSpecificReturnType when using callable `['static', 'get']`

### ISSUE THREAD

**Issue by gharlan** [vimeo/psalm#3752]
https://psalm.dev/r/1411b7dbfb

With callable `[Foo::class, 'get']` it works just fine (`getInstances1`), 
but `[static::class, 'get']` and `['static', 'get']` are not working.

**Comment by gharlan** [comment]
I'm sorry, the code above is invalid (simplified it too much).

But here you can see the same problem, with valid code: https://psalm.dev/r/0649602d7f

**Comment by gharlan** [comment]
It seems that the main problem is solved. 
`getInstance2` (`static::class`) is not a problem anymore.
Only `getInstance3` (`'static'`) still fails.

**Comment by muglug** [comment]
Yeah, I'm happy with the string `'static'` still failing because it's pretty terrible all round.
