### ISSUE TITLE
Enhancement - Extract: infer types

### ISSUE THREAD

**Issue by jarstelfox** [vimeo/psalm#3763]
Using `extract($arr)` will cause all the types to become mixed. However, it is possible for a human to infer the types: https://psalm.dev/r/f499e58714

I think it would be valuable to track down types from the `extract` call.

**Comment by muglug** [comment]
This now works (I think I added a month ago or so)

**Comment by weirdan** [comment]
@muglug are you sure? It produces weird results: https://psalm.dev/r/2053bb6a7d

**Comment by jarstelfox** [comment]
I agree with @weirdan, it looks like psalm's state is pretty messed up here. It knows the variables' types, yet psalm thinks they are mixed when used in the next function.

https://psalm.dev/r/56b83acc18
