### ISSUE TITLE
Use variable as method name

### ISSUE THREAD

**Issue by matiux** [vimeo/psalm#3765]
I'm in this situation: https://psalm.dev/r/3d6b5f5f1b

In a phpunit test I need to call the class's method by a string variable but obviously I get this error:

MixedMethodCall - Cannot determine the type of the object on the left hand side of this expression

**Comment by weirdan** [comment]
You can put it into a variable and provide the type for with the docblock: https://psalm.dev/r/4deb045d0f

**Comment by muglug** [comment]
Yup, no easy way around this, but @weirdan's suggestion is best.
