### ISSUE TITLE
How to reach the parent $context in this use-case

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#3767]
Hey, sorry to spam you. No rush, tho.

This issue is about `@psalm-self-out` and how to manipulate the parent context.

Example:

```php
interface Bar {}

class Foo implements Bar
{
    /**
     * @psalm-self-out Bar
     * @return void
     */
    public function test()
    {
    }
}

class Baz
{
    /** @var Foo */
    private $f; 

    public function __construct()
    {
        $this->f = new Foo();
    }

    /** @return void */
    public function test()
    {
        /** @psalm-trace $this->f */
        $this->f;
        /** @psalm-trace $this->f */
        $this->f->test();
    }

    /** @return void */
    public function test2()
    {
        /** @psalm-trace $this->f */
        $this->f;
    }   
}

$b = new Baz();
$b->test();
$b->test2();
```

(https://psalm.dev/r/16ea901771)

Output:

```bash
ERROR: Trace - objecttest.php:30:9 - $this->f: Foo (see https://psalm.dev/224)
        /** @psalm-trace $this->f */
        $this->f;


ERROR: Trace - objecttest.php:32:9 - $this->f: Bar (see https://psalm.dev/224)
        /** @psalm-trace $this->f */
        $this->f->test();


ERROR: Trace - objecttest.php:39:9 - $this->f: Foo (see https://psalm.dev/224)
        /** @psalm-trace $this->f */
        $this->f;
```

The last trace should also output type `Bar` for variable `$this->f`. Question is how to reach the correct context from MethodCallAnalyzer::anayze. Both `$context->parent` and `$context->parent_context` are null. Any tips? I guess the context holding variable `$b` will need to be modified with the correct type of `$b->f`.

**Comment by muglug** [comment]
Oh that's not how Psalm works, sorry – it won't

**Comment by muglug** [comment]
Psalm doesn't work like that – you're treating it as if it's the types are evaluated at runtime. Instead they're all evaluated on a function-by-function basis, so

```
$b = new Baz();
$b->test();
$b->test2();
```
doesn't actually call `$b->test()` to manipulate any state there.

**Comment by olleharstedt** [comment]
Ah, yes. The change of `$f` would have to be part of the `test()` signature, which is not possible. Thank you.
