### ISSUE TITLE
Idea: Make taint detection compensate for missing/inaccurate types

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3770]
Right now, accurate types are necessary for taint detection to work. On projects that have just started using psalm, or for which adding comprehensive types is lower priority, taint detection would be less effective.

https://psalm.dev/r/b6fae38968

Possible ways:
1. Add a `Placeholder` object for each location with missing types and record all of the property/method accesses to that `Placeholder` as some sort of special edge type for taint detection. Then, with the types inferred during calls, add taint edges to fill out that graph. This may have a lot of edge cases and wouldn't work well with multiple levels of function calls.
2. Add a mode/script for taint analysis that would copy the repo, run automatic fixes for missing types, then run the actual taint detection in a separate folder, accounting for the possibility of `../other-project` and `/absolute/path` in files (possibly easiest). (It might be useful to pass it a mapping from absolute file paths to overridden file contents instead, when invoking psalm again.

   (If version control is used, this can probably be done manually)

The second option might be viable, possibly running psalter multiple times. Because that's something an end user would do, that may involve doing nothing, or suggesting this in the documentation files for taint detection (or CLI output, e.g. if the inferred type fraction is too low)

The example is related to https://github.com/vimeo/psalm/issues/435

**Comment by muglug** [comment]
I don't think this will happen – another open-source taint analysis system, Facebook's Pyre, [has the same limitation](https://github.com/facebook/pyre-check/blob/39b05ec141418c047e0d7799db52fb90f9826a61/docs/pysa_increasing_coverage.md#overview) and the same suggested fix.
