### ISSUE TITLE
With InvalidScope suppressed, conditionals on properties affect inferences, but assignments don't

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#378]
Use case: $this is a known class (MyTemplateClass) with methods and dynamic properties. The templates use `$this` in the global scope, which works because templates are `require`d from a method.

- This is definitely a rare use case.
- Would be convenient to specify that `$this` exists and is of a certain type for the entire folder, but not sure how to

I noticed that `if (!isset($this->value))` affects inferences on `$this`, but `$this->value = expr` does not affect or clear inferences.

```php
<?php
// Imitate global suppressions of InvalidScope in a standalone example:

/** @psalm-suppress InvalidScope */
if (!isset($this->value)) {  // It seems like the !isset is affecting psalm's inferences, but the below assignment isn't.
    /** @psalm-suppress InvalidScope */
    $this->value = ['x', 'y'];
    /** @psalm-suppress InvalidScope */
    echo count($this->value) - 2;  // Unexpected NullArgument - Argument 1 of count cannot be null, null value provided
}
```

**Comment by muglug** [comment]
> Would be convenient to specify that `$this` exists and is of a certain type for the entire folder, but not sure how to

That's one of the things the `TemplateChecker` does – it allows you to scan files with a pre-filled `Context`.

**Comment by muglug** [comment]
Rare use case, but still invalid behaviour from Psalm

**Comment by TysonAndre** [comment]
The way I ended up solving this, based on the example plugin.

I saw that adding `$this` to a file when a file is require()d within a class's method interferes when analyzing the remainder of that method.

I also added a beforeAnalyzeFile hook to TysonAndre/psalm - that seems like it should be generally useful

```
<?php
namespace Psalm\Examples\Template;

use Psalm\Internal\Analyzer\FileAnalyzer;
use Psalm\Plugin\Hook\BeforeAnalyzeFileInterface;
use Psalm\Type;

class HTMLTemplateAnalyzer implements BeforeAnalyzeFileInterface
{
    // HTMLTemplateDynamic is a subclass of HTMLTemplate adding __get() and __set() so that Psalm won't warn about undeclared properties
    const VIEW_CLASS = 'HTMLTemplateDynamic';

    /**
     * Set the type of $this to HTMLTemplate3Dynamic in files in my-app/templates
     * @override
     */
    public static function beforeAnalyzeFile(FileAnalyzer $file_analyzer)
    {
        if (!preg_match('@my-app/templates/@', $file_analyzer->getFilePath())) {
            return;
        }
        $context = $file_analyzer->context;
        if (isset($context->vars_in_scope['$this'])) {
            // require() is called from another global scope or method scope?
            return;
        }
        $context->vars_in_scope['$this'] = new Type\Union([
            new Type\Atomic\TNamedObject(self::VIEW_CLASS),
        ]);
    }
}
```

**Comment by staabm** [comment]
is it documented somewhere - or can someone give me a hint - on how this `HTMLTemplateAnalyzer` needs to be configured so I can use it for php based view-templates/files?

**Comment by muglug** [comment]
@staabm That’s explicitly what it was designed for, but it doesn’t have an abundance of documentation.

**Comment by TysonAndre** [comment]
> is it documented somewhere - or can someone give me a hint - on how this HTMLTemplateAnalyzer needs to be configured so I can use it for php based view-templates/files?



> I also added a beforeAnalyzeFile hook to TysonAndre/psalm - that seems like it should be generally useful

That will be added in the linked PR. My plugin code wouldn't work without it. Then you just 

1. Update the regexes to suit your project and save the plugin in your project.

    (I don't know how you'd save plugin configs in psalm.xml - I guess you could put it's config in a separate file if you wanted it to be generic)
2. Add the relative path to the `<plugin>` to the `<plugins>` section of psalm.xml

**Comment by staabm** [comment]
Would the suggestion in https://github.com/vimeo/psalm/issues/2032#issuecomment-522325571 be a better alternative then the mentioned plugin?

**Comment by TysonAndre** [comment]
> Would the suggestion in 2032 (comment) be a better alternative then the mentioned plugin?

That depends on the use case. psalm-this-var is definitely more widely usable and useful to have (I forget if psalm has something similar for closures, along the lines of `@phan-closure-scope`)

For example, if you have hundreds of files where `$this` is `MyTemplateClass` in one folder, then it's repetitive and error-prone to type that in hundreds of files, so there's still use cases for this.

**Comment by muglug** [comment]
The usage at Vimeo is a little weird:

We have controllers and views. Controllers have methods that assign `$this->foo = "bar";`, and then the controller does

```php
foreach ($this as $key => $value) {
    $view_args[$key] = $value;
}
```

Then those args are extracted into the current scope with `extract` so `$this->foo` becomes `$foo` in the template itself, and `$this` in the template belongs to a separate class with view-related methods.

This pattern existed many years before Psalm, so I had to accommodate it. This `TemplateChecker` contains some of the necessary logic - [it figures out the controller method from an annotation within each file](https://github.com/vimeo/psalm/blob/ce03be2dc085b66c05ef2ef0c82badaeac0b2df4/examples/TemplateChecker.php#L33), and then [figures out what controller properties are set](https://github.com/vimeo/psalm/blob/ce03be2dc085b66c05ef2ef0c82badaeac0b2df4/examples/TemplateChecker.php#L99) when the method is called. It does this by simulating a method call, also simulating any calls on `$this` within that method (that's the expensive part, as there can sometimes be a lot of them).

**Comment by staabm** [comment]
@muglug our framework has the very same semantics. Would be great to know how to configure psalm for that case

**Comment by muglug** [comment]
> Would be great to know how to configure psalm for that case

Use the `TemplateChecker` plugin with a `/** @variablesfrom Foo\Bar::baz` annotation in your template

**Comment by muglug** [comment]
_although_

Vimeo's views are also neatly separated by file extension:

```xml
    <fileExtensions>
        <extension name=".php"/>
        <extension name=".phtml" scanner="path/to/TemplateScanner.php" checker="path/to/TemplateChecker.php"/>
    </fileExtensions>
```

Not sure how it would work for you - the hook I just merged from @TysonAndre may be necessary
