### ISSUE TITLE
Template psalm-throws

### ISSUE THREAD

**Issue by adrianpanicek** [vimeo/psalm#3784]
I could not find any similar issue. I have a usecase 

```php
<?php
/**
 * @template T
 *
 * @psalm-param string|null $nullable
 * @psalm-param T $exception
 *
 * @psalm-throws T
 */
function expect(?string $nullable, Exception $exception) 
{
    if ($nullable === null) {
    	throw $exception;
    }
    
    return $nullable;
}
expect('test', new RuntimeException('Test is null'));
```

My proposal:

`@psalm-throws` should take generic parameter same as `@psalm-param` or `@psalm-var`.

**Comment by adrianpanicek** [comment]
Code on psalm.dev: https://psalm.dev/r/a6bd6f9b18

**Comment by jmglsn** [comment]
Hi,
it seems that I'm trying to to something similar, which is also failing. Maybe it's a potential feature that could be added?

https://psalm.dev/r/ed7ca295c5

```php
<?php

/**
 * @template EntityIdClass
 */
interface IdReferencedEntityNotFoundException extends \Throwable
{
    /**
     * @return ?EntityIdClass
     */
    public function getRequestedId();
}


/**
 * @template EntityIdClass
 * @template EntityClass
 */
interface GenericGetByIdCapableRepository
{
    /**
     * @param  EntityIdClass                                      $id
     * @throws IdReferencedEntityNotFoundException<EntityIdClass>
     * @return EntityClass
     * @psalm-param EntityIdClass $id
     * @psalm-return EntityClass
     */
    public function getById($id);
}
```

Gives 
>ERROR: UndefinedDocblockClass - 23:16 - Docblock-defined class, interface or enum named IdReferencedEntityNotFoundException<EntityIdClass> does not exist
 
I would expect no errors after all.

Thank you!

**Comment by adrianpanicek** [comment]
> Hi,
> it seems that I'm trying to to something similar, which is also failing. Maybe it's a potential feature that could be added?
> 
> https://psalm.dev/r/ed7ca295c5
> 
> ```
> <?php
> 
> /**
>  * @template EntityIdClass
>  */
> interface IdReferencedEntityNotFoundException extends \Throwable
> {
>     /**
>      * @return ?EntityIdClass
>      */
>     public function getRequestedId();
> }
> 
> 
> /**
>  * @template EntityIdClass
>  * @template EntityClass
>  */
> interface GenericGetByIdCapableRepository
> {
>     /**
>      * @param  EntityIdClass                                      $id
>      * @throws IdReferencedEntityNotFoundException<EntityIdClass>
>      * @return EntityClass
>      * @psalm-param EntityIdClass $id
>      * @psalm-return EntityClass
>      */
>     public function getById($id);
> }
> ```
> 
> Gives
> 
> > ERROR: UndefinedDocblockClass - 23:16 - Docblock-defined class, interface or enum named IdReferencedEntityNotFoundException does not exist
> 
> I would expect no errors after all.
> 
> Thank you!

use `@phpstan-throws` instead of `@throws`

**Comment by jmglsn** [comment]
@adrianpanicek thank you!

**Comment by orklah** [comment]
I'm reopening this, IMHO there should be no difference between @throws and @psalm-throws

@weirdan what do you think?

**Comment by weirdan** [comment]
@orklah agreed

**Comment by orklah** [comment]
Oh, after looking into it, I realize this is not a difference between @throws and @psalm-throws at all.

The advice was to use `@phpstan-throws` and the reason why it works is because Psalm does not read that at all. It also rejects `@psalm-throws`: https://psalm.dev/r/03d674aed8

So, @phpstan-throws can be used but it doesn't do anything in Psalm. My reason to reopen that is now gone so I'll close. Feel free to reopen or to create another ticket for really implementing template within Exceptions (though it would have to be quite detailed as I can't see what are the use case like that)

**Comment by jmglsn** [comment]
@orklah so is that snipped now pointing to an potential feature request or is it a bug?
Because I still think that using `* @psalm-throws IdReferencedEntityNotFoundException<EntityIdClass>` should be possible or?

**Comment by orklah** [comment]
I did not think too long about this, but what could be the point of templates on Exception classes? Could you show an example in a snippet?

**Comment by weirdan** [comment]
Something like this: https://psalm.dev/r/f877a4bbe0, perhaps?

**Comment by weirdan** [comment]
That would mean type parameter inference would affect surrounding code (the catch statement).

**Comment by marcosh** [comment]
I have use case for this (I initially reported #6098 which was closed as duplicate of this).

Sometimes you want to pass as input the exception you're going to throw, and in that case it would be nice to now that you're throwing the same time of exception you're passing in.

I would like to have this code to actually work

```
/**
 * @template A
 * @template B
 */
class Either
{
    /**
     * @template E of Throwable
     * @param E $e
     * @return B
     * @throws E
     */
    public function fromRightThrow(Throwable $e)
    {
        return $this->eval(
            /**
             * @param A $_
             * @return B
             * @throws E
             */
            function ($_) use ($e) {
                throw $e;
            },
            /**
             * @param B $b
             * @return B
             */
            fn ($b) => $b
        );
    }
}
```
