### ISSUE TITLE
False positive for interface catch

### ISSUE THREAD

**Issue by GrahamCampbell** [vimeo/psalm#3786]
While it may be a bad idea to catch an interface that does not extend `Throwable`, it is still allowed by PHP, and is necessary for simultaneous PHP 5 and 7 support in code (such as when I don't control the interface from a 3rd party package). The following example complains that `Foo` cannot be caught:

```
<?php

interface Foo {}

class Bar extends Exception implements Foo {}

try {
    throw new Bar;
} catch (Foo $e) {
    echo 'caught';
}
```

But it can be caught (since PHP 5.0.1): https://3v4l.org/ljtDf.

**Comment by muglug** [comment]
Yeah, no easy way around this, but you can suppress with

```
<InvalidCatch>
  <errorLevel type="suppress">
    <referencedClass name="Foo" />
  </errorLevel>
</InvalidCatch>
```
