### ISSUE TITLE
Documenting properties of object-like arrays

### ISSUE THREAD

**Issue by rmccue** [vimeo/psalm#3787]
We currently use phpDoc nested types to document and type object-like arrays throughout our various codebases, e.g:

```php
/**
 * @param array  $options {
 *     @type string   $build_path    Absolute file system path to the static asset output folder.
 *                                   Optional; defaults to the manifest file's parent folder.
 *     @type string   $handle        The handle to use when enqueuing the style/script bundle.
 *                                   Optional; defaults to the basename of the build folder's parent folder.
 *     @type array    $scripts       Script dependencies. Optional.
 *     @type array    $styles        Style dependencies. Optional.
 * }
 */
```

To better match Psalm's typing, we're looking at instead switching to the [object-like array syntax](https://psalm.dev/docs/annotating_code/type_syntax/array_types/#object-like-arrays) that Psalm supports. This would gain us the typing, but it appears there's no way to retain the human-readable descriptions at the same time with this.

The convention in TypeScript that I've seen is usually something like:
```ts
type Foo = {
    // This describes the `some` property.
    some?: value;

    /** Or maybe an inline doc comment */
    bar: Quux;
};
```

These don't work in Psalm (and the doc-comment style would break anyway), but a similar style could perhaps be applied. Perhaps something like:

```php
/**
 * @return array{
 *     // Optional docs?
 *     optional?: string,
 *
 *     # Or this?
 *     bar: int
 * }
 */
```

Is there a recommended solution to this that I've just missed? 🤔

**Comment by muglug** [comment]
```
/**
 * @return array{
 *     // Optional docs?
 *     optional?: string,
 * }
 */
```

seems like a good solution – though @TysonAndre, @OndrejMirtes may also have opinions

**Comment by TysonAndre** [comment]
I doubt that `//` would cause problems - lines starting with that could be filtered out easily when processing type lines. There's no current uses for `#`, but I'd rather just have one way to comment in case a use case for it is found in the future for phpdoc (symbols, etc)

**Comment by muglug** [comment]
>  I'd rather just have one way to comment

Yeah, me too

**Comment by ondrejmirtes** [comment]
Yo dawg, I heard you like comments, so I put a comment inside your comment, so you can comment while you comment :)

Personally I don't think this is something worth supporting as you can put whatever text you want in the phpDoc's description. But if other tools choose to support, I'll eventually add it to PHPStan too...

**Comment by 9brada6** [comment]
Hi @rmccue, as a workaround, you can bypass this by using @psalm-param:

```
/**
 * @param array  $options {
 *     @type string   $build_path    Absolute file system path to the static asset output folder.
 *                                   Optional; defaults to the manifest file's parent folder.
 *     @type string   $handle        The handle to use when enqueuing the style/script bundle.
 *                                   Optional; defaults to the basename of the build folder's parent folder.
 *     @type array    $scripts       Script dependencies. Optional.
 *     @type array    $styles        Style dependencies. Optional.
 * }
 *
 * @psalm-param array{build_path?:string,handle?:string,scripts?:array<string>} $options
 */
```

> To better match Psalm's typing, we're looking at instead switching to the object-like array syntax that Psalm supports. This would gain us the typing, but it appears there's no way to retain the human-readable descriptions at the same time with this.

You can use PHPDoc, for documenting, and Pslam for analyzing.

**Comment by rmccue** [comment]
Certainly, we _could_ write it twice, but I'm trying to ease Psalm adoption internally. :) Both phpDoc and Psalm are doing the same thing, which is describing a shape, so it makes sense to unify those approaches. If we can't, phpDoc is essentially a superset of Psalm's capabilities (albeit with much, much better typing), so it'll win that battle.

I don't love comments-inside-comments either FWIW, but without some sort of symbol to disambiguate text from types, not sure how to avoid parsing errors easily and consistently. The suggestions of `//` and `#` are just because those are PHP comment operators already, so at least they're somewhat familiar in meaning to devs as "the following is human-readable text" (although, `#` isn't used often).

**Comment by orklah** [comment]
Sorry, I won't see that happening in Psalm anytime soon and we certainly won't take the lead on that. If there is an accepted syntax in other tools, we'll see to jump on the train.

**Comment by mckravchyk** [comment]
@orklah 

How about allowing to define a type on its own, outside the PHP Doc.

```
/* [psalm]
type Foo = {
    /**
     * This describes the `some` property.
     */
    some?: string;

    bar: string;
}; 
[/psalm] */
```

and being able to reference the custom type in PHPDoc. Then it's not such an issue of comments inside comments. This is more like a custom syntax add-on to PHP, wrapped in a comment. Ideally the IDE integration would recognize the type (with syntax highlighting) and the doc-block comment above the property, just like with TypeScript. I understand I'm asking for a LOT, just sharing my perspective on how I wished it would work as someone new to Psalm who spent a lot of time with TypeScript :)

The current workaround with psalm-param is very DRY unfortunately

**Comment by AndrolGenhald** [comment]
@mckravchyk We already have [type aliases](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-type), but the syntax is the same as for other types. I think we're more likely to do inline comments than a separate thing like that. I opened #8168 about this more recently.

**Comment by mckravchyk** [comment]
Thanks for linking the issue. I shared my feedback there.

Regarding the workaround, I plan to handle it like this:

```
//phpcs:ignore
/**
 * //phpcs:ignore
 * @param array{
 *   a: string
 *   b: {
 *     b1: number
 *   }
 *   c: string[]
 *  d: number
 * }
 * $options .
 *
 * @return void
 *
 * Options description:
 *
 *  b - Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
 * industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
 * scrambled it to make a type specimen book.
 * 
 * b['b1'] - Nested property description 
 * 
 *  c - (optional) An array of strings
 */
function foo($options) {

}
```

This way I do not have to describe every single property and repeat the type definitions.

**Comment by rhertogh** [comment]
Just for reference: This is meanwhile supported (e.g. `key1: int,  // My comment`).
Implemented in https://github.com/vimeo/psalm/pull/10004 ([Psalm 5.14.0](https://github.com/vimeo/psalm/releases/tag/5.14.0)).
