### ISSUE TITLE
Enhancement: Emit InvalidReturnType on the offending return statement itself, where possible

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#379]
And add different issue types for the possibility of failing to return a value, or for the function body being a generator.

If there are many return statements, but only one is incompatible with the declared return type, it would be hard to figure out which return statement is causing the InvalidReturnType right now.

Renaming the issue (InvalidReturn?) may help make the distinction clearer. (E.g. to distinguish from other issue types, such as having a declared return type of string|null but only ever returning string)

```php
<?php

/**
 * @return string (Observed: InvalidReturnType is emitted on the place where phpdoc return type is written)
 * Observed message: The declared return type 'string' for getValue is incorrect, got 'string|int'
 */
function getValue() {
    if (rand() % 2 > 0) {
        // ...many other statements
        return '5';
    } else {
        // ...many other statements
        return 7;  // Desired: InvalidReturnType on *this* line (Or a new issue, such as 'InvalidReturn') is emitted on the return statement(s), unless the invalid return issue is due to failing to return or being a generator.
    }
}
```

**Comment by muglug** [comment]
So I guess I see the docblock return type as the thing that's wrong, not the `return` statement.

**Comment by nickyr** [comment]
Maybe this should throw an InvalidReturnType on the function like it already does, and then also throw an InvalidReturnValue error on the offending return statement? Then it's up to the programmer which one they fix. Psalm can't actually know which one is incorrect.

**Comment by muglug** [comment]
But this is good, as it means we see errors even when the inferred return type for the whole function is `mixed`.
