### ISSUE TITLE
Unexpected `InvalidReturnStatement`

### ISSUE THREAD

**Issue by andyg0808** [vimeo/psalm#3791]
I might be misunderstanding how Psalm template parameters work, but this looks to me like it should be valid:
https://psalm.dev/r/458f484812

I also tried rewriting it with a `foreach`, in case Psalm didn't understand that `array_map` preserves keys when passed only one array:
https://psalm.dev/r/e608df1d88

**Comment by muglug** [comment]
So this isn't really a bug, because you're not returning the _exact_ value of `T` – instead you're modifying it.

Instead you want to use a conditional return type: https://psalm.dev/r/509128286e
