### ISSUE TITLE
RedundantCondition: Is not redundant.

### ISSUE THREAD

**Issue by 9brada6** [vimeo/psalm#3792]
https://psalm.dev/r/5990f8b7cc

If running this function, sometimes it will return false, sometimes the array... etc. so the empty() check is not redundant.

Note: Instead $truth_or_false_condition could be a condition/function that verifies something on the array key.

**Comment by 9brada6** [comment]
Actually it works without condition:

https://psalm.dev/r/88b051701e

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/33442484e8

**Comment by muglug** [comment]
I fixed `array_push` so it would be treated identically to `$a[]` in 38fdf4b – this should fix the opened issue

**Comment by muglug** [comment]
I'm going to close this issue – the non-emptiness is a separate problem
