### ISSUE TITLE
Emit a different issue or no issue for NonStaticSelfCall if the calling scope is an instance method?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#380]
E.g. https://secure.php.net/manual/en/language.oop5.paamayim-nekudotayim.php#121085

While $this->method() will call `method` from the **subclass**, `self::method` will call the instance method `method` defined in the **current** class. Also, if in an instance scope, `self::method` won't warn or emit a notice, so it's not severe in that case (and may actually be deliberate).

```php
<?php

error_reporting(E_ALL);
class A11 {
    public function call() {
        $result = self::method();  // Call A1::method with $this. Don't call method from a subclass.
        return $result;
    }   

    public function method() {
        return $this;
    }   
}
$x = new A11();
var_export($x->call());
```

It's fine to continue warning about `static::` for instance methods

**Comment by muglug** [comment]
Hmm. Can you think of a time that it might be deliberate? To me it's icky code, and could lead to confusion.

**Comment by TysonAndre** [comment]
My best guess of when would be similar cases to when you would use `self::` to invoke a static method, but for instance methods instead.

- E.g. you have no expectation that the method be overridden (I suppose `final` would be more appropriate, actually)
- Or you have a utility (public method) in a base class, and want to be completely sure a different method in the base class is using the utility from the base class, and not something the subclass implemented.

But most of the examples I've seen don't have a real use case, `final` would cover most of those.

Anyway, this is less severe than the other issue types.

**Comment by muglug** [comment]
Yeah, agree - I’ll make a separate issue
