### ISSUE TITLE
[question] anotations docs

### ISSUE THREAD

**Issue by douggr** [vimeo/psalm#3816]
Hi all!

Is there an updated list of all @psalm-* annotations? Couldn't find them in the docs; e.g.: @psalm-type is not documented

**Comment by Nyholm** [comment]
Hey. See this page: https://psalm.dev/docs/annotating_code/supported_annotations/

**Comment by douggr** [comment]
I did, but It's kinda outdated.

**Comment by orklah** [comment]
Seems like @psalm-type was added since :)

**Comment by weirdan** [comment]
There used to be a list of all recognized annotations somewhere in the code (in `DocblockParser` maybe), but I can't find it anymore.

**Comment by orklah** [comment]
Maybe https://github.com/vimeo/psalm/blob/master/src/Psalm/DocComment.php#L25 ?

**Comment by weirdan** [comment]
Yeah, that one (or a very similar to that). Thanks.

**Comment by weirdan** [comment]
@douggr now there is, with a test to make sure docs are not getting worse as time passes. See `Psalm\DocComment::PSALM_ANNOTATIONS` for all recognized annotations and aptly named `Psalm\Tests\DocumentationTest::WALL_OF_SHAME` for what's still undocumented.

**Comment by SCIF** [comment]
@weirdan , any chance to add a proper page and a test for #1155 as `@return never-returns` is not documented? Thanks!

**Comment by weirdan** [comment]
It's [documented](https://psalm.dev/docs/annotating_code/type_syntax/atomic_types/#other).
