### ISSUE TITLE
Report unnecessary typecasting

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#3818]
It would be great, if psalm could return unnecessary typecasting (which often is there from legacy code).

e.g.

```
/**
 * @param float|int $a some number
 * @return float
 */
function abc( $a ) {
    return $a * 4.5;
}

echo (float) abc( 3 );
```

https://psalm.dev/r/8be05c9ac1

This could additionally also include floatval(),... too

**Comment by orklah** [comment]
This is now solved for literal casts: https://github.com/vimeo/psalm/pull/4695. It doesn't support floatval & co though.

**Comment by orklah** [comment]
@weirdan we could close this
