### ISSUE TITLE
[?] Disallow `void` as a parameter type hint (and, possibly, a class name)

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#382]
Psalm thinks this is legit:
```php
class void {}
function f(void $p): void {}
```
PHP (7.1) considers both to be fatal errors (interestingly enough, it's _not_ a **syntax** error, as those could be caught in required files).

PHP 5.6 and 7.0 considers this valid.

Psalm doesn't seem to have a way to set target PHP version. Documentation (wiki) doesn't seem to mention PHP version compatibility either (apart from saying that Psalm can _run_ on PHP5&7).

**Comment by muglug** [comment]
Yeah, using obvious reserve words should always be a no-no, so I'll make sure this is an issue.

**Comment by muglug** [comment]
Thanks! Psalm's checks for reserved words weren't terribly good. They're now much improved.

Things like `function foo() : boolean {}` were treated as `function foo() : bool {}`
