### ISSUE TITLE
Dynamic number of template params for Template class

### ISSUE THREAD

**Issue by patrickkusebauch** [vimeo/psalm#3822]
Something like this already exists for arrays, where you can write:
```
array<string> //shorthand for array<array-key, string>
array<string, string>
```
Especially for `Collection` classes, this would be also useful, in case I do not care about keys:
```php
/**
 * @template-default TKey as array-key
 * @template TValue
 */
final class Collection {
}
```

So that in code I can write:
```
Collection<string> //shorthand for Collection<array-key, string>
Collection<int, string> //But also I can define both
```

I hope the sentiment is clear.

**Comment by patrickkusebauch** [comment]
https://psalm.dev/r/ca0141fc12

**Comment by patrickkusebauch** [comment]
Potential improvement than for both this and array case would be a new issue, something like `ThrowarayTemplateParameterUsed`:

In a case like this: https://psalm.dev/r/8cb1ca4bd2 I could be warned about the usage of `$key` variable. Given maybe some switch or high enough level.

**Comment by muglug** [comment]
I won't be implementing this – it's unclear what order you want the templates to be provided in, and I can't conceive of a good solution. Also, no other language has this for generics AFAIK.
