### ISSUE TITLE
Idea: Indicate sizeof() is a confusing alias or support it for analysis?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3823]
Overall, psalm or its plugins may not support aliases, especially since they're not available from reflection

https://psalm.dev/r/ed50781a4d

Various aliases exist, e.g. [this mapping](https://github.com/phan/phan/blob/master/.phan/plugins/DeprecateAliasPlugin.php) extracted from https://www.php.net/manual/en/aliases.php

- `sizeof()` is the same name as the C expression to count the number of bytes for a type/expression

**Comment by muglug** [comment]
Eh, I don't feel this is Psalm's job.
