### ISSUE TITLE
Question: how to avoid UndefinedGlobalVariable?

### ISSUE THREAD

**Issue by aivchen** [vimeo/psalm#3826]
https://psalm.dev/r/4e3ca5bc9d

How to avoid UndefinedGlobalVariable error in this case (without suppression)? PhpStorm works ok with this annotation but not psalm...

Thank you!

**Comment by ygottschalk** [comment]
Depending on where `$sports` is defined, you could use `$sports = include('script_defining_sports');`. Inside a function you could use `global $sports;` and in any other case you could do `$sports = $GLOBALS['sports'];`

**Comment by TysonAndre** [comment]
src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php `analyze()` would be the relevant part to patch.

It might be useful to add an XML setting to psalm.xml such as a mapping from global name to a union type (e.g. `<globalsTypeMap>...</globalsTypeMap>`), to improve analysis results of projects that have globals used everywhere with a known type. Psalm's maintainers would have a better idea of whether this would be generally useful or cause issues, e.g. in combination with `--taint-analysis`

I worked on something related in a fork of psalm (TysonAndre/psalm), but that was for runkit/runkit7 superglobals, not regular globals. Something along the following lines might help in your use case, but again, XML settings for globals (not superglobals) would be better



```patch
--- a/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
+++ b/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
@@ -153,6 +153,12 @@ class VariableFetchAnalyzer
             return ExpressionAnalyzer::analyze($statements_analyzer, $stmt->name, $context);
         }
 
+        // FIXME Hack: TODO replace with config
+        if ($stmt->name === 'sports' && $from_global) {
+            $stmt->inferredType = Type::parseString('object[]');
+            return true;
+        }
+
         if ($passed_by_reference && $by_ref_type) {
             AssignmentAnalyzer::assignByRefParam(
                 $statements_analyzer,
```

**Comment by aivchen** [comment]
> Depending on where `$sports` is defined, you could use `$sports = include('script_defining_sports');`. Inside a function you could use `global $sports;` and in any other case you could do `$sports = $GLOBALS['sports'];`
> 
> **EDIT:** Or maybe add the file defining `$sports` to the files analysed by psalm

Thank you!

**Comment by ygottschalk** [comment]
@kesselb @aivchen Is this solved and can this be closed?

**Comment by aivchen** [comment]
> > Thank you!
> 
> You are welcome 
> 
> @kesselb @aivchen Is this solved and can this be closed?

Yes, it's solved for me!

**Comment by kesselb** [comment]
Yep. I added a patch https://github.com/vimeo/psalm/pull/3827 to suppress UndefinedGlobalVariable for certain variables. 
Use case are templates where variables always available but not detectable for Psalm (e.g. https://github.com/nextcloud/server/blob/9ae75a3ca9785a0400f81854b906c1e5ecb48edb/apps/settings/templates/settings/admin/server.php - `$_` and `$l`)

**Comment by ygottschalk** [comment]
@kesselb mind adding the feature to the [docs](https://github.com/vimeo/psalm/blob/master/docs/running_psalm/dealing_with_code_issues.md#config-suppression)?

**Comment by ygottschalk** [comment]
@muglug can be closed
