### ISSUE TITLE
Add ability to exclude certain files from being scanned automatically

### ISSUE THREAD

**Issue by ntzm** [vimeo/psalm#3831]
My project contains a .phpstorm.meta.php which helps developers with autocompletion, but it is not 100% accurate as its behaviour is quite complicated. I want to be able to prevent psalm from loading it, and I think it might be useful to allow any file to be ignored.

**Comment by weirdan** [comment]
Can be fixed by making the code at https://github.com/vimeo/psalm/blob/master/src/Psalm/Config.php#L1783 conditional on a new config setting.

**Comment by muglug** [comment]
Fixed!
