### ISSUE TITLE
Allow null for datefmt_create parameters

### ISSUE THREAD

**Issue by othercorey** [vimeo/psalm#3843]
https://psalm.dev/r/1e9a214d71

The first 3 parameters are allowed to be null although they cannot be default.

https://3v4l.org/TSYJO

https://www.php.net/manual/en/intldateformatter.create.php

**Comment by othercorey** [comment]
If I could find where this is mapped out, I could try to submit a PR.

**Comment by weirdan** [comment]
See https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/CallMap.php
