### ISSUE TITLE
psalm dependencies incompatible with composer2 and php < 7.4

### ISSUE THREAD

**Issue by jderusse** [vimeo/psalm#3844]
by requiring `ocramius/package-versions`, psalm can not be installed with `composer 2` and php < 7.4.

`ocramius/package-versions` < 1.8 are not compatible with composer 2
`ocramius/package-versions` >= 1.8 requires > php 7.4

**Comment by weirdan** [comment]
As a workaround, you should be able to require `composer/package-versions-deprecated` which replaces `ocramius/package-versions`.
