### ISSUE TITLE
Template<null> does not not match Template<?int> / Template<child> does not not match Template<parent>

### ISSUE THREAD

**Issue by patrickkusebauch** [vimeo/psalm#3848]
I understand `null` as a valid subtype of `?int` or `int|null` therefore where I can pass `Template<?int>` I should be able to pass `Template<null>`, there should be no problem there. I declare that `int` might be present there, but it does not explicitly have to.

Foregoing the INFO messages here, this Psalm should, in my opinion, throw no errors, as it is completely valid: https://psalm.dev/r/676c0afb09

**Comment by patrickkusebauch** [comment]
Furthermore, it does not work even for interfaces and classes implementing the interface: https://psalm.dev/r/4aad3e0952

**Comment by weirdan** [comment]
This is by design. Templates are invariant by default. You can mark `Collection` as covariant (https://psalm.dev/r/676c0afb09) but keep in mind that it's only safe to do for immutable objects. See the doc chapter on covariance for more in-depth explanation: https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance

**Comment by patrickkusebauch** [comment]
@weirdan Thank you for the reply. One more question. Is there a way so have the same template class used in both ways? Because whether I want invariance or covariance really depends on the usage of the class not as much on its definition. If I use it with primitive types and classes annotated with `@immutable` I might want the covariant version, otherwise the invariant version. Is this in any way possible with just one class?

**Comment by weirdan** [comment]
It's possible if you can segregate interfaces into invariant and covariant part. For example: https://psalm.dev/r/702c217688.
