### ISSUE TITLE
wrong return type sodium_crypto_sign_verify_detached

### ISSUE THREAD

**Issue by fkooman** [vimeo/psalm#385]
function signature (from https://paragonie.com/book/pecl-libsodium/read/05-publickey-crypto.md#crypto-sign-verify-detached):
```
bool sodium_crypto_sign_verify_detached(string $signature, string $message, string $publickey)
```

In Psalm, return type is `bool` and not `string`:

```
'sodium_crypto_sign_verify_detached' => ['string', 'signature'=>'string', 'message'=>'string', 'publickey'=>'string'],
```

**Comment by weirdan** [comment]
> In Psalm, return type is bool and not string

You probably mean it **should** be bool, because it's currently `string`

**Comment by muglug** [comment]
Thanks!
