### ISSUE TITLE
sodium_bin2hex return type inference

### ISSUE THREAD

**Issue by fkooman** [vimeo/psalm#3852]
It seems the return value of `sodium_bin2hex` can't be inferred. 

```
ERROR: MixedReturnStatement - src/Session.php:250:20 - Could not infer a return type (see https://psalm.dev/138)
            return \sodium_bin2hex($binStr);
```

I'm not sure where to look. It seems `CallMap.php` is correct. Code that triggers the error: 

```
    /**
     * @param string $binStr
     *
     * @return string
     */
    private static function bin2hex($binStr)
    {
        // in case we have ext-sodium installed we use it for constant time
        // binary to hex encoding...
        if (\function_exists('\sodium_bin2hex')) {
            return \sodium_bin2hex($binStr);
        }

        return \bin2hex($binStr);
    }
```

**Comment by fkooman** [comment]
> Hey @fkooman, can you reproduce the issue on https://psalm.dev ?

No I can't! Curious...

 https://psalm.dev/r/212fc989b4

**Comment by fkooman** [comment]
I'm using Psalm 3.12.2@7c7ebd068f8acaba211d4a2c707c4ba90874fa26

**Comment by muglug** [comment]
maybe you have the polyfill locally?

**Comment by fkooman** [comment]
> maybe you have the polyfill locally?

I don't think so. You are talking about the `paragonie/sodium_compat` polyfill? Not mentioned in `composer.json`, nor in `vendor/`...

**Comment by orklah** [comment]
If it's still an issue, we would need a psalm.dev reproducer or if it's not possible, a small repo that we could run with this issue

**Comment by orklah** [comment]
Closing as stale
