### ISSUE TITLE
UnusedVariable false positive with foreach

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#3853]
https://psalm.dev/r/5be7d0c8c2

While technically correct, there is no way in PHP to not create the value variable even though I don't need it. Because of that I consider this a false-positive.

**Comment by weirdan** [comment]
Psalm ignores unused variables starting with underscore, so if your CS allows it I would suggest to use it: https://psalm.dev/r/9e802f58d8

**Comment by enumag** [comment]
Hmm... if underscored variable is supposed to be used for this then shouldn't it be reported when it is used? https://psalm.dev/r/d4662655de

**Comment by weirdan** [comment]
Yeah, that would be nice.

**Comment by muglug** [comment]
Use underscores for unused (or, if you're feeling particular, use `foreach (array_keys(...) as $key)`
