### ISSUE TITLE
[Enhancement] type annotation for "max string length"?

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3855]
**Context:**
Imagine a database column with data type `varchar(10)`. The value that gets mapped to this column should also be able to satisfy `varchar(10)` (<= 10 chars in length), or else the likes of a `SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column` will be emitted at runtime.

**Proposal:**
Introduce a new type ala `MaxLengthString` in which we can say that a string type may not be larger than X chars

**Benefits:**
This would aid developers in helping them ensure they are satisfying their data storage requirements

**Comment by mr-feek** [comment]
Perhaps `StringOfLength<min, max>` style could work

**Comment by muglug** [comment]
No, sorry – Psalm's type system is already pretty complex, and I think this would make it much moreso.

**Comment by weirdan** [comment]
Can plugins provide their own types?

**Comment by muglug** [comment]
Sure, but the challenge is not just about providing types – it's about the logic run by TypeAnalyzer to compare two types (and no plugin hooks exist there).

**Comment by muglug** [comment]
but ALSO it's about parsing – I can clean up the TypeAnalyzer so it's a bit more comprehensible (I'm in the midst of doing that right now) but any new type support would have to hook into the type parser, too.

**Comment by mr-feek** [comment]
I'm certainly not requesting you to do that -- just ran into this issue in production the other day and thought "Hey, there's a `lowercase-string` type, maybe it'd be easy to also constrain a string to x # of chars"

**Comment by muglug** [comment]
Yeah, it's sadly not terribly easy.

BTW the refactored type comparison rules are here: https://github.com/vimeo/psalm/tree/master/src/Psalm/Internal/Type/Comparator

**Comment by still-dreaming-1** [comment]
If this ever becomes more feasible, it would be an awesome feature. The idea that a string can be any length isn't very safe. Whenever a string is checked for the correct length, it would be nice to then be able encode that information into the type system. There is already support for non-empty-string. I'm not implying that means this is easy enough to do, I'm just saying it is along the same lines of thinking in terms of desirability. Also purely in terms of why it is desirable, it is similar to int ranges. Perhaps the length could itself be an int range.
