### ISSUE TITLE
wrong return type getenv

### ISSUE THREAD

**Issue by fkooman** [vimeo/psalm#386]
```
'getenv' => ['string|string[]', 'varname='=>'string', 'local_only='=>'bool'],
```

I'd expect this, PHP manual: https://secure.php.net/getenv:
```
'getenv' => ['string|false', 'varname='=>'string', 'local_only='=>'bool'],
```

**Comment by weirdan** [comment]
`getenv()` with no params does actually return array (in CLI SAPI, PHP 7.1):
```
$ php -r '$env = getenv(); var_dump(gettype($env), count(array_keys($env)));'
Command line code:1:
string(5) "array"
Command line code:1:
int(70)
```

**Comment by weirdan** [comment]
Yeah, it's documentation problem, see [source code for getenv()](https://github.com/php/php-src/blob/dc47171523b70112b14cf9144bdf223e9db550fe/ext/standard/basic_functions.c#L4058-L4068)

**Comment by nesl247** [comment]
Unless I'm misunderstanding it, @fkooman is right. `getenv('THIS_DOESNT_EXIST')` will return false. That's the issue being mentioned here, not the default value of `getenv()`.

```bash
php -r '$env = getenv("THIS_DOES_NOT_EXIST"); echo gettype($env);'
boolean
```

**Comment by muglug** [comment]
Thanks, very good point. I've just fixed, adding a carve-out for this specific method, because its output changes based on the number of arguments.
