### ISSUE TITLE
I am getting error whenever I use ZipArchive

### ISSUE THREAD

**Issue by TopNotchProgrammer** [vimeo/psalm#3862]
ERROR: UndefinedClass - src/App/Archive.php:5:23 - Class or interface ZipArchive does not exist (see https://psalm.dev/019)
class Archive extends \ZipArchive {}

`<?php

namespace App;

class Archive extends \ZipArchive {}
`

Psalm dev-master@3ce5478e5e6a6bf8d3c81a42fb8fb7801213f930

**Comment by TopNotchProgrammer** [comment]
nope, it works on psalm.dev

**Comment by weirdan** [comment]
Is zip extension installed/enabled where you run Psalm?

**Comment by TopNotchProgrammer** [comment]
my mistake, sorry. I was running wrong php version
