### ISSUE TITLE
How to use pseudo scalar type `trait-string`

### ISSUE THREAD

**Issue by smoench** [vimeo/psalm#3865]
Unfortunately I couldn't find much documentation about [`trait-string`](https://psalm.dev/docs/annotating_code/type_syntax/scalar_types/#trait-string) and couldn't get it running as I thought it should be used:

https://psalm.dev/r/615d86ff95

Probably there is a bug or documentation needs to be updated.

**Comment by orklah** [comment]
I think trait-string is inferred when you pass through trait_exists:
https://psalm.dev/r/3bff912a5b

**Comment by smoench** [comment]
Interesting 🤔  Thank you @orklah

**Comment by muglug** [comment]
I would say `trait-string` is something you pretty much never need. I only support it in Psalm for completeness (hence why there's no documentation on it).

**Comment by ptomulik** [comment]
Hi,

phpunit 11.2 introduced [CoversTrait](https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/Attributes/CoversTrait.php) attribute, and it uses the ``trait-string``. But it seems that ``trait-string`` is still kind of broken. So running psalm on projects using phpunit 11.2 yields tons of InvalidArgument errors

```
InvalidArgument: Argument 1 of PHPUnit\Framework\Attributes\CoversTrait::__construct expects trait-string, but FooTrait::class provided (see https://psalm.dev/004)
```

Can we do something about it?
