### ISSUE TITLE
Type/null checks of return values aren't remembered

### ISSUE THREAD

**Issue by binarious** [vimeo/psalm#3867]
The check for the return value of a function (e.g. `if ($entity->getId() !== null)`) isn't remembered when doing "null-unsafe" operations:
https://psalm.dev/r/9bb096402f

I have to save and check the return value in a variable:
https://psalm.dev/r/94da9d6199

Is this the intended behaviour? Phpstan supports these kind of checks.

**Comment by weirdan** [comment]
It is. You have these options here:
  1. use [`memoizeMethodCallResults`](https://psalm.dev/docs/running_psalm/configuration/#memoizemethodcallresults) in your `psalm.xml`: https://psalm.dev/r/5381029da9
  2. annotate the method with `@psalm-mutation-free`: https://psalm.dev/r/9e1eeccff9

**Comment by muglug** [comment]
> Is this the intended behaviour? Phpstan supports these kinds of checks

Yes, it is! PHPStan's checks fail for a variety of cases: https://phpstan.org/r/01444f31-ae2d-426c-8a43-8abea20cbece

See above for suggested alternatives!
