### ISSUE TITLE
Cache directory doesn't play well with multiple users

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#3869]
I tried initializing psalm on a project, but another user on the same machine was already using psalm. Due to 775 permissions on `/tmp/psalm` creation of the cache directory failed:

```Could not create cache directory: /tmp/psalm/aaecf5d5ce10f5acd4d4d1335866e18e0a008e7a```

Having the other user `chmod o+w /tmp/psalm` fixed it, but this seems like something psalm should handle itself.

**Comment by weirdan** [comment]
User files should not be put into system temp dir. I'd suggest to follow XDG base dir spec (https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and put cache files into ~/.cache (and respect corresponding env var). There's a popular PHP implementation (https://github.com/dnoegel/php-xdg-base-dir) which also provides sensible defaults for Windows.
