### ISSUE TITLE
Overriding methods with different return types

### ISSUE THREAD

**Issue by erunion** [vimeo/psalm#387]
Experiencing a weird error with a Symfony method I'm overriding.

> ERROR: ImplementedReturnTypeMismatch - src/Application.php:38:5 - The return type 'null|int' for Symfony\Component\Console\Command\Command::execute is different to the implemented return type for Mill\Application::execute 'void'
>     /**
>      * @param InputInterface $input
>      * @param OutputInterface $output
>      * @return void
>      */
>     protected function execute(InputInterface $input, OutputInterface $output)

Mill\Application::execute:

```
/**
 * @param InputInterface $input
 * @param OutputInterface $output
 * @return void
 */
protected function execute(InputInterface $input, OutputInterface $output)
{
    $style = new OutputFormatterStyle('green', null, ['bold']);
    $output->getFormatter()->setStyle('success', $style);

    $config_file = realpath($input->getOption('config'));

    $this->container = new Container([
        'config.path' => $config_file
    ]);
}
```

Symfony\Component\Console\Command\Command::execute:
```
/**
 * Executes the current command.
 *
 * This method is not abstract because you can use this class
 * as a concrete class. In this case, instead of defining the
 * execute() method, you set the code to execute by passing
 * a Closure to the setCode() method.
 *
 * @return null|int null or 0 if everything went fine, or an error code
 *
 * @throws LogicException When this abstract method is not implemented
 *
 * @see setCode()
 */
protected function execute(InputInterface $input, OutputInterface $output)
{
    throw new LogicException('You must override the execute() method in the concrete command class.');
}
```

So I change `Application::execute` to have a documented `@return int|null` instead, but then this happens:

> ERROR: InvalidReturnType - src/Application.php:36:8 - No return statements were found for method Mill\Application::execute but return type 'int|null' was expected
>     /**
>      * @param InputInterface $input
>      * @param OutputInterface $output
>      * @return int|null
>      */
>     protected function execute(InputInterface $input, OutputInterface $output)

Ideas? Only course of action right now is to just ignore `InvalidReturnType` errors.

**Comment by weirdan** [comment]
You should actually return something from the method body.

**Comment by erunion** [comment]
Yeah I'm an idiot. It's been a long couple days.

Thanks @weirdan.

**Comment by muglug** [comment]
You're only seeing this now because of https://github.com/vimeo/psalm/issues/363

Basically, Psalm wasn't showing these errors because it was thinking the issue was where the return type was defined, in the parent method. And when that parent method was in a directory not analysed by Psalm, it would just not tell you there was a problem.

Now it does.
