### ISSUE TITLE
InternalMethod errors not detected when calling code is not inside a class

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#3872]
~This issue can be fixed by deleting the line~ https://github.com/vimeo/psalm/blob/5b06c206e065c9942beb47b05220326c9a958718/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallProhibitionAnalyzer.php#L52 , ~but I'm not sure what the original intention of that line was.~

https://psalm.dev/r/594669ef3c

**Comment by bdsl** [comment]
Sorry, it can't be fixed quite that easily. `$context->self` is used to work out what the calling namespace is as therefore whether it is a legitimate internal use of the internal method, or an illegitimate external use of it. We'd have to have an alternate way to get the calling namespace.

**Comment by muglug** [comment]
I fixed this. The only caveat is you now can't scope a public method to only be usable in that specific class – `@psalm-internal` annotations are required to be valid namespaces.

**Comment by bdsl** [comment]
Right, so people won't be able to use it as a static-only version of 'private'. I don't know if anyone would want to do that, when they could just use private and override it with reflection if really necessary. Still wouldn't it be easy enough to use a combination of the calling namespace and add calling classname if present?

I also noticed that the error messages have an English grammar error at the moment - I like the change you did to show the calling context, but that needs updating to use the namespace in this context. https://psalm.dev/r/34f69fc57c

**Comment by bdsl** [comment]
Or alternatively trigger an error at the point of the `@psalm-internal` declaration if it is used with a FQCN instead of a namespace? Not sure if that's easy to implement.
