### ISSUE TITLE
Utility Types (inspired by TypeScript)

### ISSUE THREAD

**Issue by mholubowski** [vimeo/psalm#3873]
Howdy!

It would be fantastic if psalm shipped with "Utility Types" (see https://www.typescriptlang.org/docs/handbook/utility-types.html) or some other mechanism to generate new types from existing types. 

Is there currently a preferred method for this? In Typescript, Utility Types such as `Partial<T>, Readonly<T>,  Pick<T>, Omit<T>` are so useful!

Meta question: if github issues aren't the best place to ask these types of questions, what's preferred?

**Comment by mholubowski** [comment]
@TysonAndre you seem super knowledgeable, if you have a minute to chime in on your strategy for creating types from existing types I'd love to hear and hopefully others would benefit as well :)

**Comment by muglug** [comment]
This won't happen with Psalm – utility types exist under the broad umbrella of structural typing for arrays, which Psalm doesn't do and likely won't ever do. Structural typing is the ability to define things like `array{a: int}|array{b: string}` then refine that such that this type-checks:

```php
<?php

/**
 * @param array{a:int}|array{b:string} $arr
 */
function foo(array $arr) : string {
    if (isset($arr['a'])) {
        return "hello";
    } else {
        return $arr['b'];
    }
}
```

The other factor here is time – these features are _very_ complex to implement, and (unlike in the TypeScript world) there are only a couple of PHP developers who have sufficient knowledge of type systems and interest enough in these specific features to consider implementing them.

**Comment by TysonAndre** [comment]
> The main factor here is time – these features are very complex to implement, and (unlike in the TypeScript world) there are only a couple of PHP developers who have sufficient knowledge of type systems and interest enough in these specific features to consider implementing them.

Agreed - this would also take extra time to work out details in combination with template types, and there's a large backlog of other improvements/features core to php static analysis. I was curious about TypeScript's team for a while, so I finally looked this up

https://stackoverflow.blog/2020/06/15/talking-typescript-with-ryan-cavanaugh/

> Q: What is the status right now of the team at Microsoft? How much has it grown since you joined and how large is it? 
> 
> A: The whole time we’ve been working on this, we’ve had between four and eight core compiler engineers, one or two PMs, and four to zero dedicated testers. That’s been pretty constant. We’ve been growing the team a little bit more intentionally lately. 
> 
> We historically have had a core compiler team and then another team working on the Visual Studio side of things, because integrating into a large product like Visual Studio turns out to be a pretty large amount of work. But some architectural improvements on the VS side have freed up some engineer power over there. So we’re roping in that team to help us out with refactoring and Go to Definition and that kind of thing. Same team size overall, except that now we’re gonna have more people working on the core compiler services you see on the GitHub repo.

**Comment by mholubowski** [comment]
Thank you both so much, and totally understood! @TysonAndre could you point us in the right direction as to how to best solve for this problem with that is possible? Would you simply re-define the different types "from scratch"? As always, apologies if these questions come off as ignorant. 

You guys are the best thank you for your time, and I hope others find this thread insightful. Perhaps google will index it for my original search queries: "psalm utility types" / "psalm.dev utility types"

**Comment by TysonAndre** [comment]
It depends. You'd know more about your situation than I do. There's various alternatives for solving it with available capabilities

1. Use an actual class/classes, if strict typing is important
2. Manually copy and paste an amended type (e.g. `@psalm-type`) for the type you're returning, if strict typing is important
3. Give up and switch to `array<string, mixed>` and suppress notices if there are already other ways that incorrect types/fields would show up in your team's workflow (e.g. phpunit tests that cover all code paths)
