### ISSUE TITLE
A type from @psalm-import-type cannot be resolved in @psalm-type

### ISSUE THREAD

**Issue by SCIF** [vimeo/psalm#3874]
https://psalm.dev/r/0664dbb8a8
Line 11 warning.

**Comment by SCIF** [comment]
Bot could not post an example somewhat.

**Comment by weirdan** [comment]
Sometimes it hangs on startup, for reasons yet unknown. It runs on a free heroku dyno that's terminated after 30 minutes of inactivity, so restarts are quite frequent.

**Comment by weirdan** [comment]
@psalm-github-bot, please retry this: https://psalm.dev/r/0664dbb8a8

**Comment by weirdan** [comment]
> Line 11 warning.

Check your keyboard layout :rofl:. 

You defined the alias with CYRILLIC CAPITAL LETTER ES (U+0421), but referenced it as LATIN CAPITAL LETTER C' (U+0043) 

For those who are not familiar with Cyrillic layout, those letters are bound to the same physical key with the most common En/Cyr QWERTY/ЙЦУКЕНГ layout combination, and look the same (or very very similar) in most fonts.

**Comment by SCIF** [comment]
Epic fail :rofl:
