### ISSUE TITLE
Crash not finding a class

### ISSUE THREAD

**Issue by beberlei** [vimeo/psalm#3880]
This happens on 3.7.1 and 3.12.2 (and probably inbetween):

```
Uncaught Exception: Could not get class storage for symfony\component\security\core\authentication\token\storage\tokenstorage
Stack trace in the forked worker:
#0 github.com/tideways/apm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(549): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 github.com/tideways/apm/vendor/vimeo/psalm/src/Psalm/Codebase.php(723): Psalm\Internal\Codebase\ClassLikes->classExtends()
#2 github.com/tideways/apm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/TypeAnalyzer.php(730): Psalm\Codebase->classExtendsOrImplements()
#3 github.com/tideways/apm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/TypeAnalyzer.php(952): Psalm\Internal\Analyzer\TypeAnalyzer::isObjectContainedByObject()
#4 github.com/tideways/apm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/TypeAnalyzer.php(152): Psalm\Internal\Analyzer\TypeAnalyzer::isAtomicContainedBy()
#5 github.com/tideways/apm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(625): Psalm\Internal\Analyzer\TypeAnalyzer::isContainedBy()
```
The class is available though.

This is a monorepository using https://github.com/beberlei/composer-monorepo-plugin -  meaning that we have multiple vendor directories in each component with  only `vendor/composer/` autoload code generated pointing to the `vendor/` directory in the root dir.

**Comment by beberlei** [comment]
I found this https://github.com/vimeo/psalm/issues/2419 but its only similar, the patch does not help me. I dont know how to continue debugging this.

**Comment by beberlei** [comment]
Ran with `--debug --threads=1` and the last file outputed before the crash appears does not use `TokenStorage` itself, but instantiates a class that has a constructor argument for `TokenStorageInterface` (in the same namespace as `TokenStorage`).

**Comment by beberlei** [comment]
I found this is related to using the Psalm Symfony Plugin, when I disalbe it the error goes away.

**Comment by muglug** [comment]
Mind running with `--debug-by-line` on that file too to see the exact place where it flames out? Also might be worth posting this in that repository.

**Comment by frontenac** [comment]
I've run into the same issue. Doesn't seem to be a plugin issue on my end (I'm not using the Symfony plugin). Using the `--debug-by-line` shows the error at: 

`
Uncaught InvalidArgumentException: Could not get class storage for static in /home/frontenac/.local/etc/composer/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45
`

In my case it was an annotation that seemed to be causing the issue. Here is a basic rewrite of the class that was causing the issue:

```
 <?php

 class Test
 {
     const VALUES = [1,2,3];

     /**
      * @return static::VALUES
      */
     public static function values()
     {
         return static::VALUES;
     }
 }
```

It is just the annotation `@return static::VALUES` that is causing the exception. Without the annotation it runs, or if the annotation is switched to `@return self::VALUE` there is no exception.

Have an example project setup at [https://github.com/frontenac/psalm-issue-3880](https://github.com/frontenac/psalm-issue-3880)

**Comment by beberlei** [comment]
My issue is fixed updating the Symfony plugin to the latest version from 1.1.3 to 1.4.

@frontenac I suggest opening a new ticket.
