### ISSUE TITLE
array_merge could know which keys get returned

### ISSUE THREAD

**Issue by beberlei** [vimeo/psalm#3884]
I have this following code snippet, its a pattern I use sometimes to declare the defaults of an array: https://psalm.dev/r/de69237221

```
ERROR: PossiblyNullArgument - 8:22 - Argument 1 of ltrim cannot be null, possibly null value provided
```

But from the code its clear it cannot be null.

**Comment by andrew-demb** [comment]
Tried to run your example with `var_dump` before last statement.
PHP says, that `path` is `NULL`.

```php
<?php

$dsn = parse_url('http://example.com');

$defaults = ['scheme' => '', 'user' => null, 'pass' => null, 'host' => '', 'port' => null, 'path' => null];
$dsn = array_merge($defaults, $dsn);

var_dump($dsn['path']);
```

**Comment by beberlei** [comment]
@andrew-demb args, of course. silly me. the default must be 'path' => ''...
