### ISSUE TITLE
@psalm-import-type should complain about malformed imports

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#3885]
https://psalm.dev/r/6da34cd451

Both of those imports are invalid:
1. `Types` is an unknown symbol
2. there's a typo, `form` should be `from`

**Comment by weirdan** [comment]
@muglug I'm working on this, and I would appreciate a hint on where would handling for point 1 make the most sense? Basically I want Psalm to complain about missing import source even if the alias is never used.

**Comment by muglug** [comment]
> where would handling for point 1 make the most sense?

In `ClassAnalyzer`, the same place we add errors when parent interfaces and classes don't exist

**Comment by weirdan** [comment]
Thanks.
