### ISSUE TITLE
Undesired RedundantCondition in combination with non-trivial psalm-assert functions

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3888]
https://psalm.dev/r/24ac3b1a73

In this example, assertHasAccess does not ensure $obj is not null *only*, but *also that $i is not 0*. So even if it's ensured $obj is already stdClass, since this is not the only role of the function, there shouldn't be a RedundantCondition.

**Comment by muglug** [comment]
Add an equals-sign: https://psalm.dev/r/c23fbcc69d

**Comment by ostrolucky** [comment]
Thanks. Where can I read something about this sign?
