### ISSUE TITLE
PropertyNotSetInConstructor - not detecting setter use

### ISSUE THREAD

**Issue by stefanoj3** [vimeo/psalm#3889]
https://psalm.dev/r/3bd9fed1b2

Seems like psalm is unable to detect the usage of setters inside of the constructor.

Is it working as intended?

Version
```
            "name": "vimeo/psalm",
            "version": "3.12.2",
            "source": {
                "type": "git",
                "url": "https://github.com/vimeo/psalm.git",
                "reference": "7c7ebd068f8acaba211d4a2c707c4ba90874fa26"
            },
```

**Comment by muglug** [comment]
Yes, working as intended - make that method `final`: https://psalm.dev/r/f2e7a33abe

**Comment by EvgeniiR** [comment]
@stefanoj3 It will not complain if method or class will be final - https://psalm.dev/r/0bac00a651
This is because the method can be overridden in the subclass and not set the field value

**Comment by stefanoj3** [comment]
Understood, that makes sense, thank you!
