### ISSUE TITLE
Mark property as mutation free after it's set?

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3892]
https://psalm.dev/r/480fe7964f

Here, once constructor is called, nothing should be modifying $foo, so accessing subclass even though property is typed to parent is safe. Is there a way how to tell Psalm about that? I wanted to avoid other workarounds, such creating new properties or methods in subclasses just for this.

**Comment by muglug** [comment]
This should work: https://psalm.dev/r/f2e7a33abe - I’ll fix that error

**Comment by ostrolucky** [comment]
That was simplified example, so I don't have to create additional classes. What I have in real world is more like https://psalm.dev/r/bbf6a0e471

**Comment by muglug** [comment]
Now fixed

**Comment by muglug** [comment]
@ostrolucky for that case you want to use templates: https://psalm.dev/r/1ddd9d7eb4
