### ISSUE TITLE
PDO::SQLSERV_ constants missing

### ISSUE THREAD

**Issue by othercorey** [vimeo/psalm#3895]
https://psalm.dev/r/77b8915262

The PDO_SQLSRV constants are missing.

**Comment by mr-feek** [comment]
@othercorey just to make sure, do you have the sequel server extension loaded with the php version you are invoking psalm with? I would assume that is necessary

**Comment by othercorey** [comment]
Yes, with pdo_sqlsrv loaded.

**Comment by othercorey** [comment]
FYI - pdo_mysql isn't loaded either and those constants don't throw errors.

**Comment by muglug** [comment]
Those constants don't exist with the default PDO extension – that's what's wrong.
