### ISSUE TITLE
Broken PHPDoc properties with PHP-Parser 4.7.0

### ISSUE THREAD

**Issue by ElisDN** [vimeo/psalm#3896]
Psalm does not detect PHPDoc after updating `nikic/php-parser` to 4.7.0:

https://psalm.dev/r/5a239e465e

Mark it as conflicted version in `composer.json`

**Comment by weirdan** [comment]
It's already done on master: https://github.com/vimeo/psalm/blob/1d077cc48eae58b5f7ecd014ee4a4bfc4c1c45df/composer.json#L30

**Comment by muglug** [comment]
Yeah, this will be fixed in the next release.
