### ISSUE TITLE
Initialization of private trait members is not detected by psalm

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#3897]
Psalm cannot detect initialization of typed private trait properties, even when they are in fact indirectly initialized in the class constructor.

https://psalm.dev/r/d316318ce2

**Comment by weirdan** [comment]
@psalm-github-bot, resolve this: https://psalm.dev/r/d316318ce2

**Comment by weirdan** [comment]
Just like with normal setters they need to be defined `final`: https://psalm.dev/r/18680465d4

**Comment by danog** [comment]
The same issue is present if the method is aliased: https://psalm.dev/r/d8caf723b2
