### ISSUE TITLE
File parsing errors are not cached

### ISSUE THREAD

**Issue by JoshuaBehrens** [vimeo/psalm#3898]
The latest bug in php-parser https://github.com/nikic/PHP-Parser/issues/690 made me aware that a failed code parsing is not cached and therefore not displayed when psalm is run the second time making it even more confusing.

**Comment by JoshuaBehrens** [comment]
No, I can't as the sandbox is not using caching

**Comment by muglug** [comment]
@JoshuaBehrens can you give an example in a separate repo?

**Comment by JoshuaBehrens** [comment]
Yeah, I prepare one. In theory it can be just two files. Can I also post them right here?

**Comment by JoshuaBehrens** [comment]
I am sorry I didn't follow up on this. I must admit I didn't have any issue with psalm on that lately so maybe this is even fixed. I don't have the underlying issue notes anymore so I also can't recreate :/
