### ISSUE TITLE
pcntl_signal not taken into account

### ISSUE THREAD

**Issue by iquito** [vimeo/psalm#3899]
When using the pcntl extension and `pcntl_signal` as shown in https://psalm.dev/r/023d3a427a Psalm reports `TypeDoesNotContainType: if (false) is impossible`, even though with the variable change in pcntl_signal the change could happen at any time during the execution of the script.

**Comment by weirdan** [comment]
Yeah, Psalm doesn't have a concept of volatile variables. I think your best option, right now, is to suppress the issue.

**Comment by muglug** [comment]
This goes away if you elect to stop memoising properties after calls: https://psalm.dev/r/3321058e19
