### ISSUE TITLE
Support `stdClass{prop:string}`, similar to `array{key:string}`?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#390]
E.g. APIs or methods may be passed an stdClass with fixed set of properties, similarly to an array with a fixed set of fields.

- This would help analyze $params->prop better, as well as make psalm able to detect typos.
- My use case would be to generate `stdClass{prop:string, ...}` from information about supported&mandatory API parameters elsewhere in the class.

Future tasks could be to include `object{prop:string}` and `ClassWithDynamicProperties{prop:string}`, but just stdClass seems easiest and the most commonly used (I don't have use cases for `object{prop:string}` right now.

Other notes for this proposal:

- Inferred type (object)$array could optional become more specific after this
- `$x = new stdClass()` could have type `stdClass{}`, and properties could be added after assignments. This may conflict with analysis of properties added in the local scope, and introduce too many false positives (not sure).

**Comment by muglug** [comment]
Also, relatedly, casting between `(array)` and `(object)` would transform types

**Comment by weirdan** [comment]
`object{prop:string}` seems more useful though. I rarely see `stdClass` in typehints, and where it's used it generally means 'an object with some predefined set of properties' — the situation where `object{prop:string}` would be ideal. In my projects I plan to replace `stdClass` hints with `object` typehint when we migrate to PHP 7.3

**Comment by muglug** [comment]
> when we migrate to PHP 7.3

That's a tad presumptious...

**Comment by weirdan** [comment]
Oh, that's a typo. `object` typehint is available in 7.2, which has been recently released.

**Comment by muglug** [comment]
Not going to add this, I think

**Comment by muglug** [comment]
Actually I am

**Comment by muglug** [comment]
using `object` instead of `stdClass`

**Comment by egst** [comment]
Is there a way to enforce access only to the specified properties? E.g. `$foo->bar` should be an error on `object{baz: int}`. I see no reason why objects should be less type strict than arrays.

**Comment by orklah** [comment]
It would make sense to emit a InvalidPropertyFetch indeed. Can you create an issue?

**Comment by egst** [comment]
https://github.com/vimeo/psalm/issues/6962
