### ISSUE TITLE
Syntax error with "Match"

### ISSUE THREAD

**Issue by sgourdet** [vimeo/psalm#3900]
Hello,
In our project, we are using psalm to help us in our code hardening.
Everything was ok up to this week-end, and this morning we found some new issues while checking some unchanged code :

> ERROR: ParseError - vendor/phpunit/phpunit/src/Framework/MockObject/Builder/ParametersMatch.php:15:35 - Syntax error, unexpected T_MATCH on line 15 (see https://psalm.dev/173)
> interface ParametersMatch extends Match

After some investigations, we found that psalm (release 3.12.2 - last one) is using php-parser : 
> nikic/php-parser: ^4.3

php-parser released a new tag (4.7.0) this week-end, which could explain the report we now see in psalm : it now adds support for  [match expressions](https://github.com/nikic/PHP-Parser/blob/master/CHANGELOG.md).

As a workaround, we just added a direct dependancy to php-parser 4.6.0 in our project.

**Comment by sgourdet** [comment]
The class issuing this errors is extracted from phpunit : https://psalm.dev/r/dd3f0b6d8f
its path is vendor/phpunit/phpunit/src/Framework/MockObject/Builder/ParametersMatch.php
The used releases are : 
- php 7.2.24
- phpunit 8.5.8
- psalm 3.12.2
- php-parser 4.7.0

psalm.dev doesn't report any error, but I have them every time I try on my local environment and in gitlab CIs.

Please note that migration to PHP 7.4 and phpunit 9.x will be done this summer (I don't know yet if there's a relation between the bug and these releases).

**Comment by muglug** [comment]
Hey, use latest master for now (where the version of PHP Parser is pinned). I’ll release later today, hopefully (this was sadly a breaking change in that package).

**Comment by sgourdet** [comment]
Thanks
