### ISSUE TITLE
False positive: PossiblyUndefinedArrayOffset - $arr[array_rand($arr)]

### ISSUE THREAD

**Issue by Nyholm** [vimeo/psalm#3905]
Im not sure if this code is too complicated or not. But I want to report it so the maintainers are aware. Feel free to reject this issue if you want to. 

https://psalm.dev/r/138d0478f4

**Comment by muglug** [comment]
Yeah, this is a little too tricky to fix.

Two solutions, hard one would be:
- **hard** a type that's essentially `key-of<$some-var>` and that's too fiddly to implement
- **easy** have `array_rand($objectlike_array_with_optional_keys)` return a `string`, which is sort of a hack
