### ISSUE TITLE
@psalm-param array<string> does not work with @psalm-assert non-empty-list 

### ISSUE THREAD

**Issue by dFayet** [vimeo/psalm#3906]
This issue seems quite related with https://github.com/vimeo/psalm/issues/2636

With the latest version of Psalm (3.12.2) the examples given in #2636 are working fine, but if I want to give stricter type to the the entry argument, for example `list<string>` I receive an error report:
```ERROR: TypeDoesNotContainType - 20:13 - Cannot resolve types for $values - list<string> does not contain non-empty-list<mixed>```
But not if I pass `list<mixed>` (same for `array`).

Example: https://psalm.dev/r/9d7436fe23

**Comment by greg0ire** [comment]
This also works: https://psalm.dev/r/789f4fa5e6

**Comment by dFayet** [comment]
@greg0ire yes, but what if `$values` is empty? https://psalm.dev/r/7b3899ba70

**Comment by greg0ire** [comment]
Then you get a rightful error message… if you assert the list is not empty inside `consume()`, then surely `consume()` itself is not supposed to be called with an empty list, right?
