### ISSUE TITLE
amphp/amp is required both in require and require-dev

### ISSUE THREAD

**Issue by fox91** [vimeo/psalm#3909]
Using `composer validate` command gives a warning:
```
amphp/amp is required both in require and require-dev, this can lead to unexpected behavior
```
This leads to validation problems in any project that is using `psalm` and uses this command: `composer validate --with-dependencies`.

Which of the two versions is needed? The one under `require` or the one under `require-dev`?
Is it possible to remove the superfluous one?

**Comment by fox91** [comment]
> Hey @fox91, can you reproduce the issue on https://psalm.dev ?

No, I can't as the problem is in the `composer.json` file.

**Comment by muglug** [comment]
From memory the higher version is used to verify some Psalm-specific amphp behaviour, but Psalm can happily run on amphp 2.1

**Comment by fox91** [comment]
> From memory the higher version is used to verify some Psalm-specific amphp behaviour, but Psalm can happily run on amphp 2.1

But in `require` or in `require-dev`?

**Comment by remorhaz** [comment]
That may be okay to `require` _and_ `require-dev` the same package, if dev environment requires higher version.

**Comment by fox91** [comment]
It may be correct, but `can lead to unexpected behavior` (cit).
As a developer of this package I could use only the most recent version (`require-dev`) and validate against it but a user can install it using an older version (`require`) that could not be compatible...

**Comment by orklah** [comment]
This was fixes
