### ISSUE TITLE
v3.13.0 is crashing.

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#3912]
psalm is crashing when analysing [this](https://github.com/cakephp/cakephp/blob/82cfcbd68022c4e3972b1406ed929c34a51adb91/src/Collection/Iterator/BufferedIterator.php) file.

Even with using `--debug` switch all I get is
```
...
Getting /path/to/cakephp/src/Collection/Iterator/BufferedIterator.php
Analyzing /path/to/cakephp/src/Collection/Iterator/BufferedIterator.php
Killed
```

**Comment by muglug** [comment]
I've released the fix in 3.13.1
