### ISSUE TITLE
List with appended elements in a loop should be considered a list

### ISSUE THREAD

**Issue by Daeroni** [vimeo/psalm#3915]
A non empty list that has elements appended in a loop with no keys defined, should be considered a list, and not just an non-empty-array

https://psalm.dev/r/30a8ad7259

**Comment by ygottschalk** [comment]
Seems to be fixed https://psalm.dev/r/30a8ad7259

**Comment by Daeroni** [comment]
Seems to be fixed by 9dfdcbef31b1e930294fab8645d7fbed80f7e520
