### ISSUE TITLE
falsely identified UnusedFunctionCall

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#3918]
If any `ext-bcmath` function that accepts a scale/precision argument (aside from `bcscale()`) is called without said argument subsequent to the scope of a `bscale()` call (except for `bcscale(x)` followed by `bcscale(y)`, I suppose), then `bcscale()` should not be left flagged as unused.

https://psalm.dev/r/26399f8dff

p.s. I'm wondering if there's precedent for psalm having to work around internal/extension methods that manipulate global state in this manner.

**Comment by muglug** [comment]
Please PR a change to https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Codebase/Functions.php#L299

**Comment by SignpostMarv** [comment]
would I be correct in thinking that doing specific checks on the number of decimal places in string literals/consts for redundant conditions is out-of-scope for psalm, and my be just too much of a PITA for plugins?

i.e. `bcscale(2);` followed by `'1.0' === bcadd($x, $y);` never resolving to true ?

**Comment by weirdan** [comment]
> would I be correct in thinking that doing specific checks on the number of decimal places in string literals/consts for redundant conditions is out-of-scope for psalm

I'd think so.

**Comment by weirdan** [comment]
This is fixed: https://psalm.dev/r/26399f8dff
