### ISSUE TITLE
Extracting the function signatures from the codebase

### ISSUE THREAD

**Issue by NicolasCARPi** [vimeo/psalm#3921]
Hello,

`psalm`, `phpstan` and `phan` all use a similar file to get function signatures. If you look at the three files, they only differ by minor changes. (see [psalm](https://raw.githubusercontent.com/vimeo/psalm/master/src/Psalm/Internal/CallMap.php), [phpstan](https://raw.githubusercontent.com/phpstan/phpstan-src/master/src/Reflection/SignatureMap/functionMap.php), [phan](https://raw.githubusercontent.com/phan/phan/master/src/Phan/Language/Internal/FunctionSignatureMap.php))

I believe the 3 projects would benefit from having another repository in charge of hosting/maintaining this file, so they can all have the best possible function signature file.

What do you generally think about this idea? I don't think there are any blockers (except of course the details like who is going to host it and under what name).

Regards,
~Nico

PS: see same issue on [phan](https://github.com/phan/phan/issues/4107)
see same issue on [phpstan](https://github.com/phpstan/phpstan/issues/3693)

**Comment by weirdan** [comment]
See https://github.com/phan/PHPSignatures
