### ISSUE TITLE
Is [ 0 => 0, 1 => 1 ] a valid `list` ?

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#3925]
https://psalm.dev/r/73fe3f58d1

**Comment by muglug** [comment]
Nah, leave out the keys and this passes – I don't consider this a bug

**Comment by someniatko** [comment]
@muglug Well, yeah, it is obvious that it would pass if you leave out the keys. You have unit tests for this after all. I did not mention this is a bug report, by the way. This issue is more like of question type - I've just asked whether `[ 0 => 0, 1 => 1 ]` is a valid `list` in the Psalm type system, or not. If it is not, it would be very nice to know the reason why - maybe it's documented somewhere. 

A possible outcome is that it **is** actually a `list` as defined by the docs (and common sense, imo), but Psalm doesn't infer that because it's technically hard to implement. In such case i would suggest "bug" badge to stay, and a "wontfix" badge to be added.

Another outcome is that `[ 0 => 0, 1 => 1 ]` is not a `list`. Then i suggest it's a documentation issue because, at least I failed to find anything proving it's not.

**Comment by someniatko** [comment]
BTW, the reason I have asked this issue-question is because earlier I was explaining here https://github.com/doctrine/collections/issues/242#issuecomment-667851703 the concept of `list` (vs `array`) to a, presumably, Doctrine contributor. However, now I feel myself a bit guilty because probably my explanation is wrong.
