### ISSUE TITLE
Crash referencing type-alias from a shape in type-alias

### ISSUE THREAD

**Issue by alexandrmazur96** [vimeo/psalm#3927]
https://psalm.dev/r/1a7dae191e

**Comment by muglug** [comment]
This crash shouldn't occur, but this is nevertheless unsupported.

**Comment by weirdan** [comment]
@muglug can you elaborate on what's actually is unsupported?

**Comment by muglug** [comment]
Oh, referencing the `@psalm-type` before it's declared

**Comment by weirdan** [comment]
Ah, thanks.
