### ISSUE TITLE
Unexpected ReferenceConstraintViolation when PossiblyNullArgument is suppressed

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#393]
This is surprising, is the original union type of $str getting modified or shadowed somehow?
Observed: ReferenceConstraintViolation complaining about setting $str to null
Expected: No ReferenceConstraintViolation

```php
<?php

class Test {
    /** 
     * @param ?string $str
     * @psalm-suppress PossiblyNullArgument
     */
    private static function nullable_ref_modifier(&$str) : void {
        if (strlen($str) > 5) {
            $str = null;  // Strangely, ReferenceConstraintViolation is only seen when PossiblyNullArgument is suppressed
        }
    }   

    public static function main() : void {
        $c = 'abccc';
        self::nullable_ref_modifier($c);
    }   
}
```

**Comment by muglug** [comment]
not a surprise to me, having introduced just this bug (I think) with https://github.com/vimeo/psalm/commit/146cb12277b5d0d0a90d060a729fdb2033657686
