### ISSUE TITLE
[Question] Plugin development: closure return type

### ISSUE THREAD

**Issue by zlodes** [vimeo/psalm#3930]
Hi!

I use `MethodReturnTypeProviderInterface` to provide method return type for Laravel `DB::transaction` method.

Example:

```php

$foo = DB::transaction(static function() {
	// ... some code here

	return 'bar';
});

// Now foo is 'bar';

```

Question 1:
How to get return type from Closure body? 

Question 2: 
How to provide a method return type for static methods?

**Comment by muglug** [comment]
> How to get return type from Closure body?

There's a `NodeTypeProvider` available via `$statements_source->getNodeTypeProvider()`. Pass that a PHPParser node and you should get back Psalm's inferred type for it.

> How to provide a method return type for static methods?

The `MethodReturnTypeProviderInterface` should work for those, too.

**Comment by zlodes** [comment]
@muglug thanks!
