### ISSUE TITLE
Enforce constructor signature in certain cases

### ISSUE THREAD

**Issue by UrsusArctosUa** [vimeo/psalm#3934]
I believe that it would be a good thing to enforce constructor signature checks in cases when we have `new static(...)` [somewhere in class](https://psalm.dev/r/5334fe8051). It would be great to be informed that I can't change the constructor's signature in class B when I try to extend class A.

**Comment by weirdan** [comment]
@psalm-github-bot, please fetch this: https://psalm.dev/r/5334fe8051

**Comment by weirdan** [comment]
The code is causing runtime error (https://3v4l.org/YbPm4), so it might be beneficial to catch this during static analysis.

**Comment by muglug** [comment]
I think this requires a `@psalm-newable` annotation for any class with a non-final constructor that you want to initialise with `new static`

**Comment by weirdan** [comment]
I think it might suffice to have an annotation on a class that would signal it wants to enforce constructor signatures in descendants.

**Comment by muglug** [comment]
> I think it might suffice to have an annotation on a class that would signal it wants to enforce constructor signatures in descendants.

Yeah, that's what a `@psalm-newable` annotation would do (Hack has a `<<newable>>` annotation that achieves the same thing

**Comment by weirdan** [comment]
Hack's `<<newable>>` appears to be specific to type parameters, but there's [`<<__ConsistentConstruct>>`](https://docs.hhvm.com/hack/attributes/predefined-attributes#__consistentconstruct) which seems to fit the bill.

**Comment by muglug** [comment]
I went with `@psalm-consistent-constructor` – let me know if that makes the most sense to you!

**Comment by weirdan** [comment]
`@psalm-consistent-constructor` sounds good to me.

**Comment by UrsusArctosUa** [comment]
Thanks, that absolutely makes sense, especially in combination with [plugins](https://psalm.dev/docs/running_psalm/plugins/using_plugins/)
