### ISSUE TITLE
Allow check for php native type hints only

### ISSUE THREAD

**Issue by ZeinCube** [vimeo/psalm#3935]
Hi, I am using the latest version of your repository and I have a question
I have such rules in my config file 
```
<MissingParamType errorLevel="error" />
<MissingPropertyType errorLevel="error" />
<MissingReturnType errorLevel="error" />
```
But these rules checks for docblock annotations firstly, secondly by php-native type hints.
I want to produce a native php typisation in my project and check it with your analyser, but can't do it because it checks php docs for annotation.
How can I make your analyser to check php-native type hints instead of checking docblock

**Comment by orklah** [comment]
There is a config that you can put in your psalm.xml file which ignores phpdoc:

https://psalm.dev/docs/running_psalm/configuration/#usedocblocktypes

You could probably create a psalm-strict-typing.xml in which you only check MissingParamType/MissingPropertyType/MissingReturnType. That way, with a `vendor/bin/psalm --config psalm-strict-typing.xml` , Psalm will report every missing native type

**Comment by ZeinCube** [comment]
Thanks a lot, I will check this later and post response here
