### ISSUE TITLE
Not handling assignments from functions/methods that can throw exceptions correctly

### ISSUE THREAD

**Issue by DaveLiddament** [vimeo/psalm#3936]
If you look at this snippet: https://psalm.dev/r/efcc341cc1

`$person` could be null (if `createPersonButCouldFail` throws an exception).

**Comment by DaveLiddament** [comment]
Maybe related is the handling of the try block. In this snippet https://psalm.dev/r/acec45c5bc `$person2` is always null. 

Seems similar issue with PHPStan https://github.com/phpstan/phpstan/issues/3710 so perhaps this kind of analysis is impossible/very difficult.

**Comment by muglug** [comment]
This isn't a bug – if the exception throws then the code after the `try` is never reached

**Comment by DaveLiddament** [comment]
Sorry. Yes I'm completely wrong. Sorry for wasting your time!
