### ISSUE TITLE
Unclear what options psalm demo runs with

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#3940]
When using psalm.dev demo it's not clear what options are active.
For example, are `totallyTyped` or `usePhpDocPropertiesWithoutMagicCall` used?
Is there a way to enable options like that?
It seems that some options are editable but others are not, is that for technical reasons or just what has been implemented?
Is the code for the demo somewhere?

**Comment by weirdan** [comment]
> Is the code for the demo somewhere?

See https://github.com/psalm/psalm.dev
