### ISSUE TITLE
Memory limit flag?

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#3945]
Hiya 👋 

Would you be willing to accept a PR specifying a memory limit flag for invoking psalm? I have a large, legacy, monolithic codebase in [which the default memory limit](https://github.com/vimeo/psalm/blob/6919e8842332366ce9243aae12f2eb7349214578/src/psalm.php#L192) is not enough.

I also don't want to change my ini value for the whole project -- at runtime I want a different value (smaller) than what I allocate to psalm. ``

[PHPstan has a memory limit flag](https://phpstan.org/user-guide/command-line-usage#--memory-limit), would you be willing to accept a PR for the same thing here?

I tried working around it with the following:

`php -d memory_limit=5G ./vendor/bin/psalm.phar --use-ini-defaults` does not work
`ini_set("memory_limit", "5G");` in a custom autoloader does work

**Comment by muglug** [comment]
sure, go crazy
