### ISSUE TITLE
nikic/php-parser 4.7

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#3952]
Getting a conflict between psalm and my other dependencies because psalm only allows php-parser <4.7 while my other dependencies want 4.7+. It was recently restricted [here](https://github.com/vimeo/psalm/commit/3f06d4f706e556f5535ba2acba4168ca775299df). What's the issue with the newer version?

**Comment by muglug** [comment]
When using the emulated mode `nikic/php-parser` 4.7 cannot correctly parse the PHP 7.4 code `<?php class Match {}` (which appears in PHPUnit, among other places).

The latest master version of the parser has a fix for this – once there's a release I'll bump the requirement.

**Comment by enumag** [comment]
I see. In that case since you already know it will be fixed in the next version of php-parser you might want to bump the requirement to `^4.3 !=4.7.0`. This would allow installing `^4.7@dev`.

**Comment by morozov** [comment]
> The latest master version of the parser has a fix for this – once there's a release I'll bump the requirement.

Just in case, [PHP-Parser 4.8.0](https://github.com/nikic/PHP-Parser/releases/tag/v4.8.0) is released.

**Comment by Xerkus** [comment]
@morozov  `^4.8` is already in master branch, next release will have it sorted
