### ISSUE TITLE
query: re plugins and fixers

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#3955]
It's been so long since I may have asked this question that I can't recall if I've already asked it and I didn't find it when searching; can plugins provide their own fixes?

**Comment by weirdan** [comment]
Yes. Many hooks accept a by-ref parameter where the plugin may put file changes it wants to be done. E.g. `$file_manipulations` below:
https://github.com/vimeo/psalm/blob/f831ebdbcf35b8a426862d4bd06928ef9b2a3ce3/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php#L1231-L1249

**Comment by SignpostMarv** [comment]
Do any of the example plugins do this?

**Comment by weirdan** [comment]
There's `ClassUnqualifier` that does this: https://github.com/vimeo/psalm/blob/master/examples/plugins/ClassUnqualifier.php
