### ISSUE TITLE
Psalm conflicts with PHPUnit 9.3

### ISSUE THREAD

**Issue by morozov** [vimeo/psalm#3958]
Currently, the newest supported version of PHP-Parser is 4.6:
https://github.com/vimeo/psalm/blob/166134aca3e47c5215110f45ddc37f946db83c19/composer.json#L30

PHPUnit 9.3 requires PHP-Parser ^4.7: 
```
$ composer why nikic/php-parser
phpunit/php-code-coverage  9.0.0  requires  nikic/php-parser (^4.7)  

$ composer why phpunit/php-code-coverage
phpunit/phpunit  9.3.2  requires  phpunit/php-code-coverage (^9.0) 
```
So there's effectively a conflict. If a project has a dependency on Psalm, it won't be able to upgrade to PHPUnit 9.3.

**Comment by micheh** [comment]
See https://github.com/vimeo/psalm/issues/3952

**Comment by morozov** [comment]
Thanks, @micheh. Closing as a dupliate.
