### ISSUE TITLE
query re: determining where variable ancestry in afterExpressionAnalysis

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#3974]
I'm working on a plugin that wants to classify certain operations that're performed on the results of certain function calls separately from the same operations on other values, and I'm noticing that while the declaration can be flagged as originating from the "certain function calls" the subsequent variable references can't (separate instances, no ancestry on php-parse objects).

Psalm's `Context::$vars_in_scope` *looks* like it might be useful, but I'm not sure if tracking the `Type\Union` instance for ancestry checks is appropriate (compared to the presently non-functional `Node\Expr\Variable` checking) ?

**Comment by orklah** [comment]
Ok, feel free to reopen if needed :)
