### ISSUE TITLE
Question about applicability of allowCoercionFromStringToClassConst and allowStringToStandInForClass

### ISSUE THREAD

**Issue by ktomk** [vimeo/psalm#3976]
Given I'm using class-names as verbatim strings instead of class::class constants.

When using [`allowCoercionFromStringToClassConst="true"`](https://psalm.dev/docs/running_psalm/configuration/#allowcoercionfromstringtoclassconst)  and [`allowStringToStandInForClass="true"`](https://psalm.dev/docs/running_psalm/configuration/#allowstringtostandinforclass)  I still get errors like:

> ERROR: ArgumentTypeCoercion - 22:18 - Argument 1 of assertInstanceOf expects class-string, parent type string(stdClass) provided

Example code (the options are not available there): https://psalm.dev/r/3e90f55330

Me was under the impression that I should not see the error any longer, when I run this scenario locally I have error-level 3 currently).

Is this error intended?

**Comment by weirdan** [comment]
`allowCoercionFromStringToClassConst` was removed in 3.0, but it seems nobody got around to remove it's documentation. It's been [mentioned](https://github.com/vimeo/psalm/pull/1224), but failed to attract attention.

**Comment by ktomk** [comment]
@weirdan Thanks for the feedback, much appreceated. 

I'm using 3.x so this explains it made no difference.

For part of my code in one project I could benefit from this (if I understand it correctly in the first place). what I need is that whenever @class-string is in use to upgrade/promote (take) any string to (as) a class-string. I don't need to call methods on these, I just need it for making these strings special in terms of class-string parameters (should be parameters only).

This would allow me to use more concrete type (here: class-string) - which comes with a lot of benefits from Psalm templates - with code backwards compatible to PHP before 5.6.

Would this be any of the (previous existing) configurations? Or would this be something new?

**Comment by muglug** [comment]
> with code backwards compatible to PHP before 5.6

PHP 5.5 went EOL 4 years ago, and I don't want to encourage its usage via Psalm.

**Comment by ktomk** [comment]
@muglug Yes, I can perfectly understand that, however the code is also perfectly PHP 7.4 / PHP master compatible. So I don't want to encourage Psalm use with PHP 5.x either, my main question is whether an equivalent benefit would be possible with Psalm for passing strings verbatim only for class-names where that is annotated for Psalm.

De-Facto is that I only need it currently with code that extends from more new PHP that is making use of PHP 7.2 syntax features (Phpunit 7.5+) where Psalm (rightfully) highlights such places. This would give me the benefit to the tests as well under type-coverage while the whole code needs no extra-porting (I'm also looking into more options, like having dedicated Psalm error handling, dedicated annotations etc.).

So I would technically not ask for PHP 5.3 compatibility (which is the lowest version I have under test, this is a PHP cli utility and for interoperability reasons only [PHP 5.3 - 7.4 / master]). So take it with a grain of salt, could be just the decision to not use ::class in the code but strings.

More or less wondering how it could loose information in the type-system, when class-string is explicitly annotated. But I'm also relatively new to Psalm so I might not fully grasp the reasoning, so if you could give a little bit more context about that (and given PHP has only string for such a thing in it's own type-system, put aside for a moment which specific PHP version to support). Thanks.

And additionally, I also don't fully understand what the `allowStringToStandInForClass` setting is for then. What is the use/meaning of it? Is this for `new $class()` (ctor) / `$class::static()` / `call_user_func([$class, 'static'])` only?

**Comment by muglug** [comment]
In Psalm any `Foo\Bar::class` constant can be treated as a `class-string` type. It's easy to identify in the code, and also verify that the class exists. This is not possible with `'Foo\Bar'` without incurring a very heavy performance penalty, hence the use of class constants.

As above, PHP 5.6 is the absolute minimum version of PHP I'll consider supporting.

**Comment by ktomk** [comment]
@muglug Thanks for your reply even it's not covered. 5.6 makes sense as before that there is no automatically namespaced string constants with the ::class suffix notation. It's not a blocker for the production code I have anyway, for the testsuite where this pops up more error control (suppress) should do it. It's not perfect then, but as you write, it's just not an option, and I also know such a requirement is borderline. Thanks again!
