### ISSUE TITLE
query re: third-party test reuse

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#3977]
Tests are currently flagged to not be exported; It'd be nice to able to use the testing pattern for code snippets without having to literally copy & paste large chunks of code from psalm.

What're the chances of the tests being ported in whole or in part to a separate package under the psalm org?

**Comment by mr-feek** [comment]
@weirdan maintains https://github.com/weirdan/codeception-psalm-module for testing via codeception. It's been a pleasant experience for testing plugins!

**Comment by SignpostMarv** [comment]
I'd rather use phpunit as that's what I'm most familiar with :s
