### ISSUE TITLE
Scanning wordpress plugins leads to WP_CLI_Command error

### ISSUE THREAD

**Issue by prabhu** [vimeo/psalm#3980]
Hello,

While scanning wordpress plugins that use wp-cli I am getting the below error

composer.json

```json
"require-dev": {
    "wp-cli/wp-cli-bundle": "*"
}
```

```bash
PHP Fatal error:  Class 'WP_CLI_Command' not found in vendor/wp-cli/package-command/src/Package_Command.php on line 79
Fatal error: Class 'WP_CLI_Command' not found in vendor/wp-cli/package-command/src/Package_Command.php on line 79
```

Is there any configuration required for such projects?

Example repo: https://github.com/prabhu/Wubtitle-Wordpress-Plugin

**Comment by weirdan** [comment]
It needs to be autoloadable, and `WP_CLI_Command` is by default not, as this class does not follow PSR-0 (even though the package registers PSR-0 autoloader config). You can work this around by running `composer dump-autoload -o` prior to running `psalm --init`.

**Comment by prabhu** [comment]
Hi @weirdan 

Thanks for the response. I tried this workaround and got the below warning. The same issue still remains.

```
Generating optimized autoload files
Deprecation Notice: Class WP_CLI located in ./vendor/wp-cli/wp-cli/php/class-wp-cli.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class WP_CLI_Command located in ./vendor/wp-cli/wp-cli/php/class-wp-cli-command.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

```bash
psalm --report-show-info=false --show-snippet=true --find-dead-code=always \
                    --find-unused-code=always -m --no-progress --no-file-cache --no-suggestions \
                    --no-cache --root=/github/workspace \
                    --report=reports/audit-php-report.json
                                                                                 
PHP Fatal error:  Class 'WP_CLI_Command' not found in vendor/wp-cli/package-command/src/Package_Command.php on line 79
Fatal error: Class 'WP_CLI_Command' not found in vendor/wp-cli/package-command/src/Package_Command.php on line 79
```

**Comment by weirdan** [comment]
> Thanks for the response. I tried this workaround and got the below warning.

That's expected. Those classes do not follow psr-0, and composer tells you that.

> The same issue still remains.

This, however, is not something I expected. I got it running before my previous reply.

**Comment by prabhu** [comment]
Are you able to reproduce with the command I shared?

**Comment by weirdan** [comment]
No, it worked for me (had to remove `--root` though, for obvious reasons).
