### ISSUE TITLE
Should ParamNameMismatch be invoked for magic methods (__unserialize, __call, __callStatic)?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#3981]
It's easy enough to fix, but not many projects would call those directly and use named parameters at the same time.

Then again, it's consistent and really rare to have overrides with different names
Noticed for `__call($method, $args)` and `__call($method, $params)` and updated anyway

**Comment by muglug** [comment]
I'm deliberately leaving builtin methods alone for now, and also methods with only one param (as I think they're very unlikely to be called with named params).

Indeed, there's an issue with `ArrayAccess::offsetGet` vs `ArrayObject::offsetGet` having different params.
