### ISSUE TITLE
Extend templating to support dynamic typing infered from Closure objets

### ISSUE THREAD

**Issue by fkupper** [vimeo/psalm#3986]
I am writing stubs for Laravel's Collection class and I faced the following situation:
 
The Collection class has the method `time` described as:
``` php
   /**
     * Create a new collection by invoking the callback a given amount of times.
     *
     * @param  int  $number
     * @param  callable  $callback
     * @return static
     */
    public static function times($number, callable $callback = null)
    {
        if ($number < 1) {
            return new static;
        }

        if (is_null($callback)) {
            return new static(range(1, $number));
        }

        return (new static(range(1, $number)))->map($callback);
    }
```

Which basically works as 

``` php
$collection = Collection::times(10, function (int $number): int {
    return $number * 9;
});

$collection->all();

// [9, 18, 27, 36, 45, 54, 63, 72, 81, 90]
```

So a valid templating stub for this method could be:

```
    /**
     * @param int $number
     * @param ?callable $callback
     *
     * @return Collection<int,mixed>
     */
    public static function times($number, $callback = null)
    {
    }
```

So the value type of the Collection is `mixed`, because there is no way to know what is the return type of the provided `$callback` Closure. 

But we can easily get the return type of the Closure using reflection:

``` php
$closure = function (int $number): int {
    return $number * 9;
};

$returnType = (new \ReflectionObject($closure))
    ->getMethod('__invoke')
    ->getReturnType()
    ->getName();

// 'int'
```

Would it be possible to have some templating structure to tell PSALM to infer the Collection value type from the Closure return type? 

I would gladly help to implement it if it's not there yet.

**Comment by weirdan** [comment]
You need a docblock like this:
```php
   /**
     * Create a new collection by invoking the callback a given amount of times.
     *
     * @template T
     * @param  int  $number
     * @param  callable(int):T  $callback
     * @return static<int,T>
     */
```
See this in action: https://psalm.dev/r/9e243d4316

**Comment by fkupper** [comment]
> You need a docblock like this:
> 
> ```
>    /**
>      * Create a new collection by invoking the callback a given amount of times.
>      *
>      * @template T
>      * @param  int  $number
>      * @param  callable(int):T  $callback
>      * @return static<int,T>
>      */
> ```
> 
> See this in action: https://psalm.dev/r/9e243d4316

Perfect, thank you very much!
