### ISSUE TITLE
Suppressing issues in specific calls

### ISSUE THREAD

**Issue by thunderer** [vimeo/psalm#3988]
Symfony projects frequently use the call below to obtain currently logged user ID:

```php
$currentUserId = $this->tokens->getToken()->getUser()->getId();
```

Psalm reports dozens of `PossiblyNullReference`s because `$this->tokens` refers to `TokenStorageInterface` with method `getToken()` returning `TokenInterface|null`, so the immediate call to `getUser()` may fail when the token is not there.

I would like to suppress this issue, but only for `TokenStorageInterface::getToken()`. A minimal example to reproduce this behavior [can be found here](https://psalm.dev/r/0026666f8d). This issue does support only the basic suppression rules (`directory` and `file`). As far as I understand, making it support also `referencedClass`-like rule would provide necessary tools for that.

I see that `PossiblyNullReference` error is instantiated only in a single place (`MethodCallAnalyzer` line 132). I would be happy to provide a PR with implementation if someone would be so kind to tell me what would be the right approach from the maintainer's perspective.

Thank you for all your work on Psalm.

**Comment by weirdan** [comment]
To me it sound that what you actually want is to pretend that `getToken()` never returns `null`, or, better yet, to suppress nullability issues on the result of it. In which case it's much easier done with a stub like this:
```php
<?php
namespace Insert\Appropriate\Namespace\Here;

interface TokenStorageInterface {
   /** @psalm-ignore-nullable-return */
   public function getToken(): ?TokenInterface;
}
```
Reference it in `psalm.xml` like this:
```xml
<stubs>
  <file name=".psalm/TokenStorageInterface.phpstub"/>
</stubs>
```
The result will be analyzed like this: https://psalm.dev/r/8f06bad3a6

**Comment by thunderer** [comment]
@weirdan is it a recommended approach even when a certain class or interface exists and is present in the currently installed vendor packages? I assume that stubs are loaded before all other files so that Psalm will never attempt to find `TokenStorageInterface` in the vendor directory? From the [`<stubs>` documentation](https://psalm.dev/docs/running_psalm/configuration/#stubs):

> classes and functions that are not visible to Psalm via reflection (...) that are not available on the machine running Psalm

You can think of it as pretending that something wrong is right, but then, aren't we all, when we suppress known issues? :)

I still think that call-based suppression rules could be a nice addition to Psalm. PHPStan [does this with regex](https://phpstan.org/user-guide/ignoring-errors#ignoring-in-configuration-filehttps://phpstan.org/user-guide/ignoring-errors#ignoring-in-configuration-file), but an explicit list would be even better.

**Comment by weirdan** [comment]
>  is it a recommended approach even when a certain class or interface exists and is present in the currently installed vendor packages?

It is a recommended approach to supply missing type information, yes.
