### ISSUE TITLE
Psalm gets confused by functions implemented in traits

### ISSUE THREAD

**Issue by duskwuff** [vimeo/psalm#399]
Test case:

```
trait MyTrait {
    public static function instance_of_this_class() : self {
        return new self();
    }

    public static function call_instance_of_this_class() : self {
        return self::instance_of_this_class();
    }
}

class Alpha {
    use MyTrait;
}

class Beta {
    use MyTrait;
}
```

With a default Psalm configuration, this generates the error:

> ERROR: InvalidReturnType - src/test.php:8:60 - The declared return type 'Beta' for MyTrait::call_instance_of_this_class is incorrect, got 'Alpha|Beta'
>
>     public static function call_instance_of_this_class() : self {
>         return self::instance_of_this_class();
>     }

It's almost as though Psalm sees each of the functions in the trait as a single function, rather than a separate instance in each class which uses the trait.

**Comment by muglug** [comment]
> It's almost as though Psalm sees each of the functions in the trait as a single function

Yeah, almost. What was happening was that Psalm was analysing the same set of statements, and not clearing the inferred types each time when analysing static method calls.

Thanks for finding and documenting!
