### ISSUE TITLE
ParamNameMismatch issues from vendor leak

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3991]
Since last commit f12f4c8cb3d988fc9c272a3aa52149f786cbb901, psalm reports issues for classes extending vendor classes with ParamNameMismatch issues, even though project subclass doesn't define methods that use those params. Such classes look such as

```php
use GuzzleHttp\Psr7\Request;

class OrganisationAwareRequest extends Request
{
}
```

```
 ParamNameMismatch - src/AppBundle/DataProvider/Eportfolio/Pellcomp/OrganisationAwareRequest.php:10:7 - Argument 1 of GuzzleHttp\Psr7\MessageTrait::withHeader has wrong name $header, expecting $name as defined by Psr\Http\Message\MessageInterface::withHeader (see https://psalm.dev/230)
class OrganisationAwareRequest extends Request
```

**Comment by weirdan** [comment]
Consider the following code:
```
use Psr\Http\Message\MessageInterface;

function addHeader(MessageInterface $request): MessageInterface {
    return $request->withHeader(name: 'X-Header', value: '42');
}
$request = addHeader(new OrganizationAwareRequest);
```
It will break in PHP 8 (https://3v4l.org/FfBho), so it makes sense to report it. Feel free to suppress the issue if you're targeting PHP 7.

**Comment by ostrolucky** [comment]
But this is completely vendor issue, there is nothing I can do to fix it. And I cannot exclude the rule while keeping it enabled for non-vendor issues, can I?

**Comment by weirdan** [comment]
Unfortunately it's not just vendor issue. You inherit it (literally), and if you expose the affected code it may cause issues to your class consumers as well.

I'd suggest to demote it to INFO level, make a PR to Guzzle to fix it (or waiting until they fix it), upgrade to fixed version and then re-enabling it.

**Comment by ostrolucky** [comment]
> if you expose the affected code it may cause issues to your class consumers as well.

Well it won't unless using named arguments https://3v4l.org/pptgO

Psalm should stick to known issues. It would make sense to discourage people to use different names in subclasses, but this is not the case here. Those names are defined in vendors.

I would suggest to split these issues. One issue is to define subclass with different parameter names, completely different issue is to use such class.

**Comment by ostrolucky** [comment]
It also looks to be impossible to supress this with `@psalm-suppress` :( And psalm.dev for some reason doesn't show ParamNameMismatch error. https://psalm.dev/r/a64a1b7d27

**Comment by muglug** [comment]
Sorry, this was caused by laziness when a test wouldn't pass, ended up fixing the wrong thing
