### ISSUE TITLE
Incorrect logic for guessing the return type

### ISSUE THREAD

**Issue by drupol** [vimeo/psalm#3995]
Hi,

This morning I found this issue with Psalm: https://psalm.dev/r/3d61db1887

The return type of this script can never be `\StdClass` but `T`.

**Comment by weirdan** [comment]
Is there any reason why it's not implemented in a simpler way, e.g like this: https://psalm.dev/r/d116fe0f47 ?

**Comment by weirdan** [comment]
The problem Psalm is having with the original code is that `===` with objects requires objects on the left-hand and right-hand sides to be the same object, and Psalm doesn't track value identities, only types.

> Is there any reason why it's not implemented in a simpler way

I see now, local object is used as a kind of token that could never come from the outside in the `$items` array.

In your particular case (with arrays) you could handle it like this: https://psalm.dev/r/2447d0ed16 , but that won't work with iterables or some filtering logic in the loop. Extending it to iterables and filtering would require introducing a local structure that can be inspected for emptiness, e.g. https://psalm.dev/r/7a934de262

**Comment by muglug** [comment]
Yeah, I don't see this as a bug

**Comment by drupol** [comment]
> Is there any reason why it's not implemented in a simpler way, e.g like this: https://psalm.dev/r/d116fe0f47 ?

Because the array can contains 'null' values.

Thanks for your explanations, I will see if I can improve this.
