### ISSUE TITLE
@psalm-import-type doesn't work with autoloaded files?

### ISSUE THREAD

**Issue by douggr** [vimeo/psalm#3999]
We have this (working) example: https://psalm.dev/r/531fd85425, which have only one file.

BUT, when we try to use  `@psalm-import-type` among several files, psalm fails with `ERROR: UndefinedDocblockClass - src/Error.php:16:19 - Docblock-defined class or interface DL2\PsalmIssue\TFoo does not exist (see https://psalm.dev/200)`.

Funny thing, it'll work if I add a constant within the class, but I don't want to.

I've created a simple example here: https://github.com/douggr/psalm-issues (clone, composer install && composer psalm)

So, my question is: how should I expect `@psalm-import-type` to work? Am I missing something?

I'm using psalm@dev-master:

```bash
$ ./vendor/bin/psalm --version
Psalm dev-master@bb3c5d4c388754d2e4789ddb515af0f995aa9d2f
```

refs  #3816

**Comment by marartner** [comment]
I think this is related to https://github.com/vimeo/psalm/issues/3807

**Comment by muglug** [comment]
Reproduced in https://psalm.dev/r/e856fbf28d – removing the namespace fixes the issue, so it's something trivial around that.

**Comment by douggr** [comment]
Awesome! Thank you :)
