### ISSUE TITLE
How to annotate "out" type of "use (&$var)" variable? (@psalm-use / @psalm-use-out)

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#4001]
https://psalm.dev/r/966e882711

**Comment by muglug** [comment]
There isn't a way, though I'd gladly accept a PR along the lines of this: https://psalm.dev/r/1c81d5e1e4

**Comment by muglug** [comment]
Without those sort of safeguards there's no guarantee (in the general case) as to the type of `$strings`

**Comment by caugner** [comment]
Thanks! I would suggest `@psalm-use` (instead of `@psalm-use-in`) and `@psalm-use-out` to be consistent with `@psalm-param` and `@psalm-param-out`.

Meanwhile I found a workaround in defining `@psalm-var` inside the callback and after the `array_walk_recursive` call:

https://psalm.dev/r/966e882711

**Comment by AndrolGenhald** [comment]
I would suggest some sort of strict variable annotation that requires the variable to always satisfy the type: https://psalm.dev/r/ded8bb1120. I _think_ this should be sound.

With something like `@psalm-use-out`, if it changes the type then calling the function multiple times could fail unless we implement something like Rust's FnOnce, and that seems like far more trouble than it's worth. If we instead require the out type to match the in type, it seems like a strict variable annotation would already accomplish that and be helpful in other ways as well.

**Comment by weirdan** [comment]
> I would suggest some sort of strict variable annotation

If we are going this path, we would have to ensure those strict vars are only passed by value or by reference into functions that guarantee their type to be intact (with `param-in` + `param-out` perhaps).

**Comment by danog** [comment]
Implemented!
