### ISSUE TITLE
Psalm remembers return type of mutation-free method "too long"

### ISSUE THREAD

**Issue by ygottschalk** [vimeo/psalm#4009]
https://psalm.dev/r/3b0ca0c2ca

Found this while writing #4008

After mutating the internal state, the return type of mutation-free methods should be "resetted".

**Comment by muglug** [comment]
Here the treatment is identical to native object properties, so changing the value of `rememberPropertyAssignmentsAfterCall` will result in the desired behaviour: https://psalm.dev/r/19a45fd79e
