### ISSUE TITLE
Memory Leak in AtomicMethodCallAnalyzer.php on line 203

### ISSUE THREAD

**Issue by donatj** [vimeo/psalm#4010]
I've been running Psalm for a while without issue, but suddenly on upgrading to 3.12 I started seeing this out of memory error.

I am currently running the newest version: `Psalm 3.14.1@9822043ca46d6682b76097bfa97d7c450eef9e90` and still seeing the issue.

I've increased the allowed ram upto 32 gb and I still get the error, which leads me to believe there is a memory leak.

```
Scanning files...
Analyzing files...

PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 4294967304 bytes) in /Users/jdonat/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php on line 203
Fatal error: Allowed memory size of 8589934592 bytes exhausted (tried to allocate 4294967304 bytes) in /Users/jdonat/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php on line 203

```

Using the `--debug` flag I was able to narrow it down to this file - I've whittled several thousand lines of code down to just the part that seems to be triggering the error. 

<details>

Getting rid of any of these lines seems to make the error go away. 

Getting rid of *any* of the IFs makes the error go away.

```php
<?php

namespace Mappers\User;

use Objects\User\UserAwarenessInterfaces\AdminAwareUserInterface;
use Objects\User\UserAwarenessInterfaces\ContactInformationAwareUserInterface;
use Objects\User\UserAwarenessInterfaces\CourseAwareUserInterface;
use Objects\User\UserAwarenessInterfaces\RidAwareUserInterface;
use Objects\User\UserAwarenessInterfaces\RosterAwareUserInterface;
use Objects\User\UserFactory;

class UserMapper {

	protected $factory;

	public function __construct(
		UserFactory $userFactory
	) {
		$this->factory = $userFactory;
	}

	protected function makeFromRecords( array $data ) {
		$user = $this->factory->make(0, 0, 0, 0, 0, '', '', '', '', '', '', 0, 0, 0, 0, false, 0);

		if( $user instanceof CourseAwareUserInterface ) {
			//foo
		}

		if( $user instanceof AdminAwareUserInterface ) {
			//foo
		}

		if( $user instanceof RosterAwareUserInterface ) {
			//foo
		}

		if( $user instanceof RidAwareUserInterface ) {
			//foo
		}

		if( $user instanceof ContactInformationAwareUserInterface ) {
			$user->setEmailAddress('');
		}
	}

}

```

</details>

I suspected *maybe* the interfaces formed a triangle or something, but as far as I can tell none of them reference any of the other ones. 

I'm not sure how much this helps, but here's a very chart of the inheritance tree however.

![merged2](https://user-images.githubusercontent.com/133747/90451704-04598e80-e0b2-11ea-8664-d0b41f93b9d1.png)

I'd personally *love* to just dump the full code up here for you guys, but I can't. If you think it will help, I can probably go through and anonymize them as best of my ability, but I'm avoiding the effort currently…

Let me know if there's anything else I can provide to help you with this. I'm very happy to help.

**Comment by weirdan** [comment]
Can't reproduce with https://psalm.dev/r/a9d5c1af5c, so there must be something about your interfaces/factory/user object that triggers this issues.

**Comment by donatj** [comment]
I *am* able to reproduce but when I try to copy a link I get 

![image](https://user-images.githubusercontent.com/133747/90452762-8f3b8880-e0b4-11ea-9d46-d1a68da9d18b.png)


![image](https://user-images.githubusercontent.com/133747/90452735-7c28b880-e0b4-11ea-8bba-95eb0ca1b0f8.png)

**Comment by donatj** [comment]
Is there an email address I could send the blob to? I'd rather not post all of this publicly.

**Comment by weirdan** [comment]
You can send that to the address in my profile. Note that I don't have any affiliations with Vimeo or Psalm, so you'll effectively be sending that to a random stranger.

**Comment by muglug** [comment]
But a very reliable random stranger

**Comment by dbrekelmans** [comment]
@muglug @weirdan I came across this issue and I've been able to reproduce it on 3.18 (which I'm running in my project) as well as 4.4. I'm not sure when this was introduced.

The website doesn't show the fatal error output, but try running it locally. There are some very specific steps you have to follow to reproduce it, which I've explained in a code comment.

https://psalm.dev/r/849791936a

**Comment by orklah** [comment]
Nice reproducer. You can also see the result on psalm.dev in the ajax on the console:

> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 167772160 bytes) in /var/www/vhosts/psalm.dev/httpdocs/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php on line 490

**Comment by orklah** [comment]
Psalm build a lot of complex types internally:
https://psalm.dev/r/a1e99c7462

> INFO: Trace - 34:37 - $foo: Base&A&B&C&D&E|Base&A&B&C&E|Base&A&B&D&E|Base&A&B&E|Base&A&C&D&E|Base&A&C&E|Base&A&D&E|Base&A&E|Base&B&C&D&E|Base&B&C&E|Base&B&D&E|Base&B&E|Base&C&D&E|Base&C&E|Base&D&E|Base&E

**Comment by muglug** [comment]
Ok, this should be fairly simple to work around

**Comment by muglug** [comment]
It manifests in a different form here:

```php
<?php

interface Base {}

interface E extends Base {
    public function bar() : void;
}

function foobar(Base $foo) : void {
    if ($foo instanceof E) {}

    $foo->bar();
}
```

Expected: UndefinedInterfaceMethod
Actual: PossiblyUndefinedMethod

**Comment by muglug** [comment]
Thanks @dbrekelmans for the reproducer!

**Comment by dbrekelmans** [comment]
Thank you for fixing it 😁
