### ISSUE TITLE
Different behavior for :self / :parent vs :BaseClass / :BaseClass return types

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#4015]
https://psalm.dev/r/78721127dd
but
https://psalm.dev/r/de0b75def0

For consistency reasons, either both of the examples should emit error, or none of them.

**Comment by someniatko** [comment]
It looks like Psalm ignores `/** @return static */` annotation in the former case and infers the `Base` type: https://psalm.dev/r/8447756840

However, in latter case, type is inferred from the docblock.
https://psalm.dev/r/22c35a262a

I believe that 
1) the docblock should always take precedence over the native type declarations, 
2) if parent method has a docblock, and child method does not, psalm should behave as if the child method has the same docblock, to avoid copy-pasting it in every descendent class.
please correct me if i am wrong.

**Comment by orklah** [comment]
@danog Seems like it broke, possibly since your PR. Could you take a look on occasion?

**Comment by danog** [comment]
Actually I remember this being broken on master while working on my PR, it was already broken in https://github.com/vimeo/psalm/commit/42462b8640fec7b6bcab3191f10b5fe93b0f0fd2 for example.
Will take a look!

**Comment by orklah** [comment]
This seems fixed :)
