### ISSUE TITLE
Two sequential traces do not work

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#4016]
https://psalm.dev/r/bd8b09e95f

**Comment by vudaltsov** [comment]
A statement in between fixes the issue.
https://psalm.dev/r/f87c75b7a1

**Comment by weirdan** [comment]
Or empty statement (lone `;`): https://psalm.dev/r/6413a50547

**Comment by orklah** [comment]
I'm not sure this is a bug, rather a limitation of PHP-Parser if I understood correctly. Each statement has a docblock so you have to put a statement for the docblock to be analysed.

**Comment by weirdan** [comment]
Agree. `/** @psalm-trace $a */;` looks like a good enough workaround.

**Comment by vudaltsov** [comment]
Thank you for explanations!
