### ISSUE TITLE
Using "new static" should not trigger UnsafeInstantiation in final classes

### ISSUE THREAD

**Issue by AegirLeet** [vimeo/psalm#4019]
https://psalm.dev/r/722b67a5a0

As there can't be any child classes, the constructor's signature is known in this case. UnsafeInstantiation shouldn't apply.

**Comment by muglug** [comment]
You can also fix this with `new self`

**Comment by AegirLeet** [comment]
Yeah I just prefer `static` everywhere for consistency.
