### ISSUE TITLE
Call to undefined method ReflectionParameter::isVariadic()

### ISSUE THREAD

**Issue by towndwarf** [vimeo/psalm#402]
Stuck on PHP Fatal error: Call to undefined method ReflectionParameter::isVariadic() in /vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php on line 1489

**Comment by muglug** [comment]
Are you running under PHP 5.5 or below? What version of Psalm are you using?

**Comment by towndwarf** [comment]
1. PHP 5.6.25
2. Psalm - just got it from composer today/ don't get how to get the version

**Comment by muglug** [comment]
Could you run `vendor/bin/psalm --version` and tell me the result?

A couple of odd things: [that method is defined in PHP 5.6](http://php.net/manual/en/reflectionparameter.isvariadic.php) and it's also not called on that line

**Comment by towndwarf** [comment]
1. this command line just starts psalm
2. it looks, since I'm using WAMP server, (haha even within debian virtual machine), some PHP methods might not be defined.
3. I'll check on production server later and notify.
Thank you

**Comment by muglug** [comment]
> this command line just starts psalm

Then I think you're running an old version of Psalm. What's the commit hash in your composer.lock file?

**Comment by towndwarf** [comment]
> at production: Psalm 0.3.71
> at test(on WAMP)  "version": "0.3.39", "reference": "9ea80b5ef83d10cee9c07770b296b0205ae0a152"
Tried to put to composer.json version:^0.3.7, composer did not succeed.
Copied from production the psalm folder
got
/mnt/hgfs/dup$ vendor/bin/psalm --version
PHP Fatal error:  Class 'PackageVersions\Versions' not found in /mnt/hgfs/dupcheck/vendor/vimeo/psalm/bin/psalm on line 180

**Comment by muglug** [comment]
Right, so it would be failing here: https://github.com/vimeo/psalm/blob/9ea80b5ef83d10cee9c07770b296b0205ae0a152/src/Psalm/Checker/FunctionLikeChecker.php#L1489

Still, I'm pretty sure that the stack it's running on doesn't support 5.6, else that fatal wouldn't occur. There's also an `0.2.x` branch for `5.4-5.5` you could try

**Comment by towndwarf** [comment]
Thanks,
I'll try

Also, from documentation I did not get how to exclude some libraries from errors notification.

The project I'm trying to parse, is Zend Framework 1, and, besides other folders, ZF1 folder gives zillion  of errors in psalm...
(and. if ZendFW folder is excluded,  approx 600kb of errors looking like 
`UndefinedClass - application/includes/Common/Model/AbstractSecond.php:9:36 - Class or interface Zend_Db_Table_Abstract does not exist`)

**Comment by muglug** [comment]
Closing – feel free to reopen if there's new information
