### ISSUE TITLE
Template annotation with interface

### ISSUE THREAD

**Issue by akondas** [vimeo/psalm#4022]
Maybe I'm doing something wrong, but I can't solve this problem
https://psalm.dev/r/4304d1d127

```
ERROR: InvalidArgument - 36:10 - Argument 1 of User::__construct expects Collection<Policy>, Collection<BlockingPolicy> provided
```

In this case `BlockingPolicy` implements `Policy` so it should be accepted ... :thinking:

**Comment by someniatko** [comment]
@akondas use `@template-covariant` instead: https://psalm.dev/r/d5c04fc440

**Comment by muglug** [comment]
What he said ^

**Comment by akondas** [comment]
Thanks for help :beers:
