### ISSUE TITLE
Ensure void functions do not return any value

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#403]
```php
/**
 * @return mixed
 */
function a()
{
    return 1;
}

function b(): void
{
    return a();
}
```
This is a fatal error in php 7.1, yet Psalm sees nothing wrong here. Void functions should not be allowed to have **any** `return` statements (as it's a fatal error, even when that return statement is in unreachable code part).

**Comment by muglug** [comment]
Thanks, fixed somewhere high above the Atlantic

**Comment by weirdan** [comment]
This seems to work, but not for all cases. For example, unreachable return is not complained about (without `--find-dead-code`):
```php
function a(): void {
   throw new \Exception('and thanks for all the fish');
   return 123;
}
```

**Comment by muglug** [comment]
> unreachable return is not complained about 

This is by design – Psalm does not analyse code after `throw`, `return`, or `exit`, as it can never be executed.
