### ISSUE TITLE
Apply @psalm-consistent-constructor to classes that you don't own

### ISSUE THREAD

**Issue by rybakit** [vimeo/psalm#4035]
I have this scenario: https://psalm.dev/r/86ff184a0c.

**Comment by muglug** [comment]
Sorry, not sure I follow

**Comment by rybakit** [comment]
I'm sorry I wasn't clear enough.

The snippet I posted fails with the `UnsafeInstantiation` error, which is correct and expected. The [proposed fix](https://psalm.dev/docs/running_psalm/issues/UnsafeInstantiation/) is to make the parent class constructor final or to annotate the child class with `@psalm-consistent-constructor`:

https://psalm.dev/r/a9a8fafb9f

However, I couldn't find a way to apply this annotation to the built-in class `\Exception` (something like `@psalm-consistent-constructor(\Exception)`) and I wonder if it is even possible in my scenario?

**Comment by muglug** [comment]
I'd just suppress the error – what you're doing _is_ dangerous, I think, unless you have control over the specific set of exceptions you're instantiating (in which case you could create a subclass with that annotation).
