### ISSUE TITLE
Incorrect LessSpecificReturnType

### ISSUE THREAD

**Issue by morrisonlevi** [vimeo/psalm#4038]
In this [example][1] I am getting a `LessSpecificReturnType`. If I use a return of plain `Element` then it doesn't complain. The return type is definitely nullable -- there is an explicit `return null` in one of the reachable branches. 

I've used psalm on-and-off and I can't remember how well it is expected to handle control flow. Is this supposed to work? Or maybe I have done something wrong?

As an aside, in version 3.14.1 I'm not getting the other INFOs, just the `LessSpecificReturnType`. Edit: this is probably because of the error level set.

Also, psalm is pretty great! While writing this snippet I originally used `$iterator` instead of `$iterator->current()` when passing to `$reduceWith` and the type checker caught the mistake.

  [1]: https://psalm.dev/r/d727943d80

**Comment by muglug** [comment]
@morrisonlevi reopening as there's definitely a bug here: https://psalm.dev/r/5efaab0087

**Comment by muglug** [comment]
You can also clean up your example slightly: https://psalm.dev/r/13748defd1

**Comment by morrisonlevi** [comment]
Thanks for the fix!

The suggestion for my example isn't quite right, I think, because the keys of a generic `iterable` can definitely be different from `array-key`. For instance, it is somewhat common for a `zip(['a' => 3, 'b' => 4], [1, 2])` to yield keys that look like `['a', 0]` and `['b', 1]`. In other words, they are arrays, which is not permitted for `array-key`.

However, if a parameter `$p` is an `iterable<Key, Element>` and I do `is_array($p)` then the type of key should narrow to `array-key`. I have no idea how to actually formulate this.

**Comment by muglug** [comment]
@morrisonlevi that was a bug, fixed in 9878613
