### ISSUE TITLE
Constant initialized from other constant is not handled

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#4044]
I'm trying to use [`ParameterType::*`](https://github.com/doctrine/dbal/blob/2.10.x/lib/Doctrine/DBAL/ParameterType.php) as a phpdoc for a method argument, but get error messages showing that only 16 or null is accepted:

```
ERROR: InvalidArgument - tests/Doctrine/Tests/DBAL/Query/QueryBuilderTest.php:908:42 - Argument 3 of Doctrine\DBAL\Query\QueryBuilder::setParameter expects int(16)|null, int(2) provided (see https://psalm.dev/004)
        $qb->setParameter('name', 'foo', ParameterType::STRING);
```
I dumbed the issue down to the following:

https://psalm.dev/r/6dbe1ad2dd

**Comment by muglug** [comment]
Seems to be fixed
