### ISSUE TITLE
Allow changing default severity

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#4049]
Hi,

Today, at work, I wanted to create a new xml file to show me the highest errors (which are ignored in my baseline in my default xml config).

I created a new standard file with errorLevel="8" and I was surprised to see the analysis take 13 times more than my usual analysis (it went from 354 seconds to 4820 seconds)

I narrowed down the issue to the structure of the xml file. My usual file contains every issue in issueHandler with "suppress" for each issue I don't want to see whereas the new file was only `errorLevel="8"`. I tried to add every issue from level < 8 with "suppress" and it was suddenly faster again.

That means, by default, Psalm will take it's time just to display the "XXXX issues found" (because --show-info is now false by default).

My suggestion would be to add a configuration `defaultSeverity` which could be changed to "suppress" to replace the hard coded "info" value here: https://github.com/vimeo/psalm/blob/46013a35c84a0d547e0167b87e3a7da4f045cd8d/src/Psalm/Config.php#L1600 . This config should be ignored wherever --show-info was set to true.

Additionally, I would try to define a threshold which would automatically set this config to "error" in case the number of errors in lower levels is too high when running --init.

Of course, this would mean we won't be able to count issues for the report at the end. A placeholder "Remove defaultSeverity config to see the number of errors" may be added to replace the missing report line.

Would you accept such PR? Do you see improvements or obstacles?

**Comment by weirdan** [comment]
This is likely fixed in #4095

**Comment by orklah** [comment]
Yep, it was, thanks @weirdan
