### ISSUE TITLE
Annotations for anonymous functions?

### ISSUE THREAD

**Issue by ramsey** [vimeo/psalm#4050]
I'm having trouble annotating anonymous functions. In short, Psalm does not appear to recognize my annotations.

Here is a short example to illustrate what I'm trying to accomplish:

```php
/**
 * @param list<mixed> ...$args
 *
 * @return iterable
 */
$foo = fn (...$args) => new ArrayObject($args);
```

I would expect Psalm to understand the return type and the type of `...$args`, based on my annotations, but it emits errors instead.

See here: https://psalm.dev/r/98dedd40da

**Comment by orklah** [comment]
I think you have to put the comment after the assignment:
https://psalm.dev/r/229c00c90b

**Comment by muglug** [comment]
yup, PHP parser doesn't play games – assignments are just expressions, so the annotation has to go as near to the `function` declaration as possible.

**Comment by ramsey** [comment]
Thanks! That does the trick!
