### ISSUE TITLE
Pure functions shouldn't be allowed to take `iterable` as an argument.

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#4052]
`iterable` type should not be considered ok for pure functions as it is not guaranteed that the iterable that is going to be passed is immutable.

the following should trigger an error at the `join` function as it takes an iterable: https://psalm.dev/r/2015c28f86

example of impure usage of `join`: https://3v4l.org/5ec8h

**Comment by azjezz** [comment]
Another note, `\count()` seems to be considered pure by psalm, but it is actually not 😛

**Comment by muglug** [comment]
> Another note, \count() seems to be considered pure by psalm, but it is actually not 😛

Please ticket that separately

**Comment by azjezz** [comment]
Thanks for the fix @muglug 🤗
