### ISSUE TITLE
ternary with identical IF/ELSE

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#4053]
should psalm emit a error when a ternery operator contains the same IF/ELSE path?

https://psalm.dev/r/218ad5532c

sometimes while developing DEVs FAKE the values used in a ternary to make the script run a certain path.
when those changes are forgotten one can easily introduce bugs.

IMO psalm should report such a expression as dead-code or redundant code, so the DEV cannot forget about his test-changes.

**Comment by muglug** [comment]
No, I think this should be done instead with PHPCS or similar
