### ISSUE TITLE
Different behavior for '=== false' and '!'

### ISSUE THREAD

**Issue by Great-Antique** [vimeo/psalm#4054]
Related to fix of #3811 in commit 2399643472a936b03dcf62bd981a75cdc8d32261

If you use '!' then everything works: https://psalm.dev/r/9138e3a6bd
If you use '=== false' then multiple 'assert-if-true' doesn't work: https://psalm.dev/r/a095d318cf

**Comment by muglug** [comment]
`=== false` there is unnecessary, given the function returns a `bool`.
