### ISSUE TITLE
Assignment of empty SplObjectStorage

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#4055]
There seems to be some issue with SplObjectStorage - I can't assign empty SplObjectStorage to an annotated property. Note that this works just fine for other generic types since https://github.com/vimeo/psalm/commit/b26deb434d6ff09cd53b382d3faf77018f5dd66c.

https://psalm.dev/r/747947d7b6

**Comment by muglug** [comment]
It's because the constructor doesn't take templated params, so there's nothing to be considered empty. I think the only way around this is to hack things a bit.

**Comment by ondrejmirtes** [comment]
I think it's sufficient to add the constructor with type variable parameters.
