### ISSUE TITLE
Incorrect type detected - (title might be wrong, sorry)

### ISSUE THREAD

**Issue by drupol** [vimeo/psalm#4056]
Hello,

I'm playing with Psalm and I succeeded to highlight an issue that I reproduced here: https://psalm.dev/r/6b00880829

The inferred type of the `$temp` variable should be: `Generator<int, array<TKey, T>, mixed, void>` but Psalm infer: `Generator<int, array<array-key, mixed>, mixed, void>`.

I checked with [PHPStan as well](https://phpstan.org/r/3757e572-9095-4d9b-bd91-9d8146c0b60f), no issue is found.

Feel free to close the issue if this is something that has already been asked or fixed.

**Comment by weirdan** [comment]
`Wrap` has no constructor, so there's nothing its type parameters can be inferred from. So you would have to specify them in a `@var` annotation: https://psalm.dev/r/b960666eeb
