### ISSUE TITLE
TooManyTemplateParams false-positive (cannot specify traversable type)

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#4059]
Psalm 3.14.2@3538fe1955d47f6ee926c0769d71af6db08aa488

First run on a project. Got a lot of TooManyTemplateParams errors.
In our team we always specify what kind of variables are inside an object that implements \Traversable. Something like /** @var \Traversable<string> */. PHPStan also expects generic typehinting for \Traversable (and throws errors if there aren't). But Psalm thinks this kind of typehiting is an error and on the next line can't recognize that $char will be string for sure (see snippet).

https://psalm.dev/r/47b88785b3

**Comment by muglug** [comment]
You can either explicitly type it as a `Traversable`: https://psalm.dev/r/617d4c9c85
Or explicitly type the `foreach` var: https://psalm.dev/r/fdfb3fe761
Or use a stub to supplement Psalm (and PHPStan's) knowledge of the class: https://psalm.dev/r/63abeed11c
