### ISSUE TITLE
Psalm with Symfony showing PHP Fatal error on PHPUnit

### ISSUE THREAD

**Issue by fabianofa** [vimeo/psalm#406]
Working with Symfony 3.4, I tried `./vendor/bin/psalm` on root of the project and only get

`PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in /var/www/html/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php on line 24`

`Fatal error: Class 'PHPUnit\Framework\TestCase' not found in /var/www/html/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php on line 24
`

As it depends on composer apparently, I can't run with `--root=src/AppBundle` for example, since I got the `Could not find any composer autoloaders in [...]` error.

**Comment by weirdan** [comment]
Please attach psalm.xml you're using

**Comment by muglug** [comment]
Are you extending a Symphony test? I’m puzzled as to why Psalm even cares to look there. You might also (if it doesn’t reveal too much information) run the result of `--debug`

**Comment by muglug** [comment]
I've improved Psalm's loading of vendor files to the point that I don't think this error should *ever* pop up now. Going to close unless there's more info.
