### ISSUE TITLE
Recursive object-like array throwing internal psalm error

### ISSUE THREAD

**Issue by adrianpanicek** [vimeo/psalm#4060]
Hello, 

I'm trying to typehint recursive object-like array. But psalm throws `Internal Psalm error on line 275 - /vendor/vimeo/psalm/src/Psalm/Type/Atomic.php: This should never happen`.

https://psalm.dev/r/865d17140c

**Comment by muglug** [comment]
> I'm trying to typehint recursive object-like array

FYI this is not supported (and currently I have no plans to)

**Comment by orklah** [comment]
If the fix for this issue was to get rid of the Internal Error, it's done now.

**Comment by weirdan** [comment]
It was.
