### ISSUE TITLE
PossiblyNullArgument when comparing with variable or constant

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#4061]
I am experiencing issues when comparing nullable values with a constant or a variable (both set to `null`).
Would love to contribute a PR if thats a bug.

https://psalm.dev/r/0f90195228

**Comment by muglug** [comment]
I don't see it as a bug – just check for the literal `null` – there's no good reason to create a constant for that.

**Comment by boesing** [comment]
I think there is, as in this example, its legit due to readability:

https://github.com/boesing/zend-expressive-cors/blob/b2c29c4c244a26d13d961b5f4141b034c2ac36b6/src/Service/ConfigurationLocator.php#L86

https://github.com/zendframework/zend-expressive-router/blob/3eebad8011da28e705272a20cce46eeb09a7a32d/src/Route.php#L43

what do you think @muglug
