### ISSUE TITLE
add `pure-callable` type and ban using callable arguments in pure context.

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#4062]
similar to #4052, the `callable` type doesn't guarantee that the function will be pure. in this case, I think it would be better to add a `pure-callable` type so that pure functions can still take a callable as an argument, and psalm can verify that it is pure.

pure-callable is just a normal callable but declared using the `@psalm-pure` annotation.

see: https://psalm.dev/r/50f8a9d0c2

impure behavior: https://3v4l.org/jQ4IT

**Comment by azjezz** [comment]
Hmm, maybe it would nice to have `pure-iterable` as well ( `array` + (`Iterator` + `psalm-immutable`) + `IteratorAggregate::getIterator(): ImmutableIterator` ) ?

**Comment by muglug** [comment]
I don't really see the point of `pure-iterable`, but I'd happily accept a PR for `pure-callable`

**Comment by azjezz** [comment]
on its way 🤗 

![image](https://user-images.githubusercontent.com/29315886/91243968-120eb400-e743-11ea-85ed-3042cc41609c.png)
