### ISSUE TITLE
`count()` is considered `pure` by psalm, but its not.

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#4063]
`count` is not pure as it accepts all types of iterables ( see #4052 )

**Comment by weirdan** [comment]
Not all types of iterables. `count()` works on arrays and countables, where `Countable::count()` may or may not be pure.

**Comment by azjezz** [comment]
Ah, correct. the issue is with `Countable::count()`, an example of impure `Countable::count()` in doctrine: https://github.com/doctrine/collections/blob/1.6.x/lib/Doctrine/Common/Collections/AbstractLazyCollection.php#L31 ( $this->initialize(); performs a DB query ... )

**Comment by muglug** [comment]
@azjezz can you reproduce the issue? `count` already does some purity checks...

**Comment by azjezz** [comment]
reproduce: https://3v4l.org/QJeJW

**Comment by weirdan** [comment]
That's already caught: https://psalm.dev/r/8ddbd78f47

**Comment by azjezz** [comment]
Hm, yep, i can't seem to be able to reproduce this in psalm anymore 🤔 but i thought i got this last night when i caught #4052 

closing for now, sorry for the trouble.
