### ISSUE TITLE
Iterating over an object or an iterator in a pure context should be forbidden.

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#4064]
following #4052 

the following should be forbidden: https://psalm.dev/r/7801a5f373 
> `$i` in this case is either an `Iterator` or `IteratorAggregate`, both are possibly-mutating.

the following should be forbidden: https://psalm.dev/r/ef206ffd4a
> `$i` in this case is an `Iterator` which is possibly-mutating.

**Comment by weirdan** [comment]
I would expect [`RawObjectIteration`](https://psalm.dev/docs/running_psalm/issues/RawObjectIteration/) to be emitted for the first case.
