### ISSUE TITLE
[Question] Can I define a reusable Object-like array type?

### ISSUE THREAD

**Issue by jdart** [vimeo/psalm#4067]
I've been working on a javascript codebase annotated with jsdoc and you can [declare a type with a name](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#typedef-callback-and-param), it can be imported and referenced in other files. Doing something like this with pslam could be useful when dealing with DTO's or database query responses with a predictable shape that you might pass around.

I can annotate object-like arrays like below, but I don't think I can share that shape.

`/** @psalm-param array{id: int, name: string} */`

What about something like the below:

```php
/**
 * @psalm-typedef array Thing
 * @psalm-property int id
 * @psalm-property string name
 */

/** @psalm-param Thing $thing */
```

Or maybe I should just use POPO's. Thoughts?

**Comment by weirdan** [comment]
There's `@psalm-type` and `@psalm-import-type` that do exactly that: https://psalm.dev/r/4d10b86962

**Comment by donquixote** [comment]
This is cool. Is it documented somewhere? I cannot find `@psalm-type` in the docs.

**Comment by weirdan** [comment]
It is: https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-type
