### ISSUE TITLE
What's the relation between purity and lazyness/lambdas?

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#4071]
Snippet: https://psalm.dev/r/8aa79b57df

Wrapping a side-effect in a lambda should keep the parent pure. Or am I wrong?

**Comment by olleharstedt** [comment]
A more simple example: https://psalm.dev/r/ae4be09829

**Comment by muglug** [comment]
Well, you're not actually using the lambda, which is a bug in and of itself.

**Comment by olleharstedt** [comment]
I could be using it if I returned it. Which would be pure. https://psalm.dev/r/1fed104dbc
