### ISSUE TITLE
InternalMethod error for IteratorAggregate::getIterator()

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#4073]
- Let's say there's an internal class `Foo`, and public-facing class `Bar` that extend from `Foo`. 
- If an internal class implements an interface with implicitly called methods such as `IteratorAggregate`, then `Bar` should be allowed to be used as an instance of this interface.
- Yet Psalm [thinks this is not allowed](https://psalm.dev/r/d0c7d6ce7d), giving me:

> ERROR: InternalMethod - 25:14 - The method Q\Foo::getIterator is internal to Q but called from 

```php
namespace Q {
    /**
     * @internal
     */
    class Foo implements \IteratorAggregate
    {
        /** @return \Traversable<int> */
        public function getIterator(): \Traversable
        {
            return new \ArrayIterator([]);
        }
    }

    class Bar extends Foo
    {

    }
}

namespace {
    $bar = new \Q\Bar();
    // ERROR: InternalMethod - 25:14 - The method Q\Foo::getIterator is internal to Q but called from 
    foreach ($bar as $baz) {
        return $baz;
    }
}
```

**Comment by muglug** [comment]
I don't see this as a bug (so I'd just suppress it). Willing to reconsider if @bdsl (who's thought about this a bunch) feels otherwise.

**Comment by bdsl** [comment]
It's debatable. The way I set this up was based on where the method is declared. If a class is internal then you shouldn't need to read it to write external code, and if you don't read it you won't know about `Foo::getIterator` and you won't call it. But I can see the argument that if a class is not internal you should be able to use any of its methods except those explicitly declared internal.

For now if you control both namespaces and you don't want to to suppress you can either do https://psalm.dev/r/d0c7d6ce7d or https://psalm.dev/r/a95c7a0bb9

**Comment by bdsl** [comment]
But I think there is a related bug: in the case of https://psalm.dev/r/51860dd7e3 Psalm reports an Internal method because it thinks the client is calling `Q\Foo::getIterator` which is internal to Q. But it should understand that since that's an internal method what must be meant is `\IteratorAggregate::getIterator` which is legal to call.

**Comment by sanmai** [comment]
@bdsl thank you for backing me up! Likewise, there's an error [if we declare `@method` on `Bar`](https://psalm.dev/r/2b9c542423). This is as explicit as it gets apart of defining actual method.

(This is very unfortunate but I'll be removing `@internal` declarations for time being.)
