### ISSUE TITLE
Problem with PSR-11

### ISSUE THREAD

**Issue by pawelkg** [vimeo/psalm#4074]
When use PSR-11 container, get method throw in eg. Psr\Container\NotFoundExceptionInterface.
I have Exception that implements this interface. In method that use PSR-11 get method I have throw tag with my Exception (that implements PSR-11 interface). In this case Psalm (v3.14) produce error that this should be tag for Psr\Container\NotFoundExceptionInterface but when I add it, there is a message that Psr\Container\NotFoundExceptionInterface do not implements Throwlable.

See: https://psalm.dev/r/be6d3e87a5

Note: Check for @throws docblock flag need to be set.

**Comment by andrew-demb** [comment]
See issue in PSR repo about this.
https://github.com/php-fig/container/issues/21

**Comment by andrew-demb** [comment]
Also similar issue in psalm about simple cache: https://github.com/vimeo/psalm/issues/1856

**Comment by muglug** [comment]
Add

```
<ignoreExceptions>
  <class name="Foo\Bar\ExceptionInterface" />
</ignoreExceptions>
```

and you should be good to go
