### ISSUE TITLE
Detect dead baseline-entries 

### ISSUE THREAD

**Issue by alfredbez** [vimeo/psalm#4076]
It would be helpful if there was a way to check if issues ignored by the baseline in psalm are resolved already.
We currently have a bash script we use in CI for that, but that feels a bit hacky:
```bash
#!/bin/bash
​
cp psalm-baseline.xml{,.before}
# We need to diff starting at line 3, because the second line contains the psalm-version which is not interesting here
# We only want to know if there are any issues that were resolved already
tail -n +3 psalm-baseline.xml > psalm-baseline.xml.diff-before
vendor/bin/psalm.phar --update-baseline >/dev/null 2>&1
tail -n +3 psalm-baseline.xml > psalm-baseline.xml.tmp && mv psalm-baseline.xml{.tmp,}
​
EXIT_CODE=0
if ! diff -q psalm-baseline.xml{,.diff-before} &>/dev/null; then
  echo "The baseline needs to be updated, here's the diff:"
  diff psalm-baseline.xml{,.diff-before}
  echo "Please update the baseline with: 'vendor/bin/psalm.phar --update-baseline'                 (removes fixes errors from the basline)"
  echo "                             or: 'vendor/bin/psalm.phar --set-baseline=psalm-baseline.xml' (adds new errors to the baseline)"
  EXIT_CODE=1
fi
​
rm -f psalm-baseline.xml psalm-baseline.xml.diff-before
mv psalm-baseline.xml{.before,}
​
exit $EXIT_CODE
```

Our use-case is basically to break the CI build if someone fixes an error, but forgets to update the baseline.

**Comment by alfredbez** [comment]
Hello :robot:,

I think that's not possible, sorry.

**Comment by muglug** [comment]
@alfredbez you can see the changes necessary to add a comparable config flag here: https://github.com/vimeo/psalm/pull/4041/files. You'll also probably need to futz a little with `ErrorBaseline`, but that shouldn't be too hard.

**Comment by brayniverse** [comment]
Hey, did this go anywhere? I'm happy to have a go at sending a pull request to add this functionality if there is someone around to help me if I have any questions?

**Comment by weirdan** [comment]
Feel free to try your hand at it. @orklah and me should be able to help you should you get stuck.

**Comment by weirdan** [comment]
Well, GitHub somehow manages to run it on Windows, e.g. here: https://github.com/vimeo/psalm/runs/4225825072?check_suite_focus=true

I wonder whether it's due to git settings or something else.

![image](https://user-images.githubusercontent.com/57403/142006127-7a049e24-194c-4ea6-83ae-82252daef16b.png)

**Comment by weirdan** [comment]
> Our use-case is basically to break the CI build if someone fixes an error, but forgets to update the baseline.

Now we have https://psalm.dev/docs/running_psalm/configuration/#findunusedbaselineentry for this.
