### ISSUE TITLE
Root-namespaced @method annotations fail in docblock method tag

### ISSUE THREAD

**Issue by lptn** [vimeo/psalm#4083]
example code: https://psalm.dev/r/ab7a8de1a4

see the error:
```
Psalm output (using commit d29620a): 

ERROR: InvalidArgument - 21:52 - Argument 2 of Illuminate\Support\Facades\Cache::remember expects DateInterval|Illuminate\Support\Facades\DateTimeInterface|int, Illuminate\Support\Facades\MyDateTime provided

INFO: MissingParamType - 9:38 - Parameter $method has no provided type

INFO: MissingParamType - 9:47 - Parameter $args has no provided type
 
```

Important part: 2nd argument type of `remember` method is specified as `\DateTimeInterface|\DateInterval|int $ttl`, but psalm expects `DateInterval|Illuminate\Support\Facades\DateTimeInterface|int, Illuminate\Support\Facades\MyDateTime`

in other words, `\DateTimeInterface` vs `\Illuminate\Support\Facades\DateTimeInterface`

**Comment by weirdan** [comment]
On another note, importing the `DateTimeInterface` fixes the issue, even though it's still referred to as FQCN: https://psalm.dev/r/fa27da130c

**Comment by lptn** [comment]
thanks a lot, @muglug 👍
