### ISSUE TITLE
Psalm cuts the first char in the namespace

### ISSUE THREAD

**Issue by Arslanoov** [vimeo/psalm#4086]
I got a lof of errors (something like this):

```
Class or interface omain\User\Service\PasswordValidatorInterface does not exist (see https:/
/psalm.dev/019)
```

Namespace is Domain\User... , but psalm cuts the first char

Also there are strange bugs T_NAME_FULLY_QUALIFIED:
```
ERROR: ParseError - vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php:20:11 - Syntax error, unexpected T_NAME_FULLY_QUALIFIED on line 20 (see https://p
salm.dev/173)
namespace Doctrine\Common\Annotations;
```

I do not understand why psalm analyzes the vendor folder, although I excluded it

My psalm.xml:
```
<?xml version="1.0"?>
<psalm
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://getpsalm.org/schema/config"
        xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src" useStrictTypes="true" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
</psalm>
```

Please help me

**Comment by weirdan** [comment]
Can you provide a repo reproducing the issue?

**Comment by Arslanoov** [comment]
> Can you provide a repo reproducing the issue?

Thanks for your reply.
Here is the link to the repository:
https://github.com/Arslanoov/todo
At the moment, the psalm is not installed there, since I did not manage to install it correctly.
The backend is located in the api folder
At first I assumed that the problem was that I used declare(strict_types=1), but after setting the useStrictTypes="true" it did not disappear, so I created this issue

**Comment by Arslanoov** [comment]
> Hey @Arslanoov, can you reproduce the issue on https://psalm.dev ?

Sorry i don't know how to reproduce it in psalm.dev

**Comment by weirdan** [comment]
You need to start with declaring your dependencies in `composer.json` (which is currently entirely missing). Laminas config files (`config/pipelines.php`, `config/routes.php`, etc) are missing as well.

With that said, I couldn't reproduce the issue locally, even when I figured out most dependencies.

**Comment by Arslanoov** [comment]
> You need to start with declaring your dependencies in `composer.json` (which is currently entirely missing). Laminas config files (`config/pipelines.php`, `config/routes.php`, etc) are missing as well.
> 
> With that said, I couldn't reproduce the issue locally, even when I figured out most dependencies.

It’s not missing

https://github.com/Arslanoov/todo/blob/master/api/composer.json
https://github.com/Arslanoov/todo/tree/master/api/config

**Comment by weirdan** [comment]
Confirmed both issues, when running in `api` folder.

**Comment by weirdan** [comment]
Interesting. Runnig `vendor/bin/php-parser` from that folder (supplied by `nikic/php-parser`) on `vendor/composer/autoload_static.php` produces parse error. However running the *same version* of `php-parser` installed elsewhere on that same file results in successfull parsing. So there must be some package that breaks `nikic/php-parser`.

**Comment by weirdan** [comment]
Isolated to `zircote/swagger-php`:
```console
$ vendor/bin/php-parse vendor/composer/autoload_static.php > /dev/null 2>&1 ; echo $?
1

$ composer remove zircote/swagger-php
[...]

$ vendor/bin/php-parse vendor/composer/autoload_static.php > /dev/null 2>&1 ; echo $?
0
```

**Comment by Arslanoov** [comment]
I found related issue
https://github.com/vimeo/psalm/issues/1844

**Comment by weirdan** [comment]
So the solution for the time being would be to downgrade `zircote/swagger-php` to 3.0.4 (`composer require zircote/swagger-php:'3.0.0 - 3.0.4'`). This gets rid of all the issues you were having as far a I can see.

**Comment by Arslanoov** [comment]
> So the solution for the time being would be to downgrade `zircote/swagger-php` to 3.0.4 (`composer require zircote/swagger-php:'3.0.0 - 3.0.4'`). This gets rid of all the issues you were having as far a I can see.

Thank you very much! The error disappeared
