### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#4089]
- [x] union types
- [x] static return type
- [x] mixed native type
- [x] nullsafe operator (`$a?->b()?->c()`)
- [x] named arguments
- [x] throw expression
- [x] match expression (can probably just convert to ternary equivalent)
- [x] constructor property promotion
- [x] Non-capturing catches
- [x] Stringable interface
- [x] `get_debug_type` return type provider
- [x] promote `TraitMethodSignatureMismatch` to `MethodSignatureMismatch` in PHP 8

**Comment by duskwuff** [comment]
* [ ]  attributes

It looks like parser support [just landed in PHP-Parser a few days ago](https://github.com/nikic/PHP-Parser/commit/4c22c62783667228f4af173837f843579f3beb4d).

**Comment by muglug** [comment]
@duskwuff there's nothing for Psalm to support w/r/t attributes, I think? What additional checks should it have?

**Comment by weirdan** [comment]
Psalm could check if attributes are used on valid targets (e.g. param attribute used on a property). Also it could validate attribute parameters I think, to prevent runtime errors when attribute is instantiated via reflection.

**Comment by duskwuff** [comment]
@muglug It doesn't need a lot, TBH. The main bits that'd be nice to have are:

* If a `ReflectionAttribute` is created through a call to `getAttributes()` with a class name, the return value from `$reflectionAttribute->newInstance()` should be typed as that class. This _might_ be representable through type annotations and templating, but might need some assistance.

* It'd be nice to check that any attributes are valid for instantiation (i.e, the attribute references a real class, and the attribute class has the Attribute attribute with a `TARGET_*` which is consistent with the location of the attribute).

**Comment by weirdan** [comment]
>  static return type

Does static return type covariance work?  E.g. this: https://psalm.dev/r/d830a8e15c shouldn't fail, as PHP 8 accepts that: https://3v4l.org/ZIJb9

**Comment by muglug** [comment]
@weirdan thanks, that was a more general bug affecting PHP 8 and fixed in ec3501b24

**Comment by muglug** [comment]
Closing this – if there are specific attribute things you want done, please ticket them separately.
