### ISSUE TITLE
Property-level suppression of PropertyNotSetInConstructor

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#409]
Followup to #199 

While it's currently possible to suppress PropertyNotSetInConstructor on a class and file levels, it would be great to be able to suppress this issue on individual properties:
```php
class A {
  /**
   * @var string
   * @psalm-suppress PropertyNotSetInConstructor
   */
  private $b;
  
  public function __construct() {}
}
```

My specific use-case for this is auto-populated properties of Doctrine objects (kinda like ORM behaviours).

**Comment by muglug** [comment]
Thanks, great suggestion for syntax cc @thomaskonrad
