### ISSUE TITLE
Unable to resolve UndefinedGlobalVariable with @var annotation for objects

### ISSUE THREAD

**Issue by michalm-st** [vimeo/psalm#4097]
I am working on a project built with Yii 2, which uses plain PHP files as view templates where the variables are injected into the view template by a controller. I previously used `@var` annotations to document the type of the variables that are in scope. This method has worked fine for scalars, but it does not seem to work for any classes.

The following example can be used to reproduce this problem. It's probably worth noting that the output from my machine is different than the output shown on psalm.dev. I analyzed the code in this snippet https://psalm.dev/r/d3346b7d50 with Psalm `dev-master@e8148980fff2e191e44f9a63a2fea28f2ceedbc6` and got the following output:

```
vendor/bin/psalm psalm.php
Scanning files...
Analyzing files...

░

ERROR: UndefinedGlobalVariable - psalm.php:3:6 - Cannot find referenced variable $obj in global scope (see https://psalm.dev/127)
echo $obj->getTimestamp();


------------------------------
1 errors found
------------------------------

Checks took 11.25 seconds and used 132.478MB of memory
Psalm was able to infer types for 0.0000% of the codebase
```

**Comment by muglug** [comment]
What do you get with latest master?

**Comment by michalm-st** [comment]
No more errors as of https://github.com/vimeo/psalm/commit/f105f6aca91b09c17dfa918f0e2662223f5bce14. Thank you very much!
