### ISSUE TITLE
UndefinedMethod on exception

### ISSUE THREAD

**Issue by ErikBooij** [vimeo/psalm#410]
Given the following code:

```php
try {
    $container->get('dependency');
} catch (ContainerExceptionInterface $exception) {
    Log::to('error')->error($exception->getMessage());
}
```

`ContainerExceptionInterface` is the PSR-11 one, found here: [php-fig/container](https://github.com/php-fig/container/blob/master/src/ContainerExceptionInterface.php). Psalm gives an `UndefinedMethod` error (for `getMessage()` on `$exception`). This is technically correct, because if it's purely inferred from the interface, it has no methods (the `ContainerExceptionInterface` cannot extend `Throwable` because it would break compatibility with everything < PHP 7.0.

Since every exception thrown implements `Throwable` by definition (as far as I know), I would consider it a false positive.

**Comment by muglug** [comment]
> Since every exception thrown implements Throwable by definition (as far as I know), I would consider it a false positive.

That is a very good point. I'll make sure an intersection type of `Throwable` is added to each `catch` class.

**Comment by muglug** [comment]
Thanks – I've opened #411 and #412 to improve checking of `throw`/`catch` class usage.

Although, as you rightly say, adding `Throwable` to a given class would break PHP7 usage, I think Psalm should let people know (a change in current behaviour) when `catch`ing an interface that doesn't extend `Throwable`, and leave ignoring of that generated issue up to the programmer.

**Comment by ErikBooij** [comment]
Thanks for picking this up so swiftly, your level of support here keeps surprising me. I think the solution detailed in the new issues, is a great one. Cheers!

**Comment by muglug** [comment]
Thanks!
