### ISSUE TITLE
yield from $iterable should not be acceptable in a mutation-free context.

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#4105]
The following should warn about `yield from $iter`: https://psalm.dev/r/1818600288

**Comment by weirdan** [comment]
Another example could be yielding from another generator: https://psalm.dev/r/ad4907e3d4

**Comment by veewee** [comment]
Would it make sense to introduce a `pure-iterator` and a regular `iterator` similar to the callable types introduced in v3.15?

**Comment by weirdan** [comment]
Both initial examples are now flagged.
@veewee feel free to extract you feature request to a separate GH issue.

**Comment by veewee** [comment]
Thanks! It was already discussed in #4145, so no need to open up another issue for it!
