### ISSUE TITLE
adding @psalm-consistent-constructor does not affect `--diff` runs

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#4108]
After a run of psalm, it found an instance of the new `UnsafeInstantiation` error which in this specific case I wanted to correct by asserting `@psalm-consistent-constructor` on the parent class (child classes did provide their own compatible constructor - refactoring this to have a final constructor and a separate `init()` method was out of scope for a simple "let's upgrade psalm" PR).

Re-running psalm with `--diff` will not pick up that change and the error will still be emitted.

Re-running psalm without `--diff` will clear the issue.

**Comment by orklah** [comment]
Does this still happen? The --diff option is now the default and --no-diff was introduced. I'd expected to see more of that by now?

**Comment by orklah** [comment]
Closing as stale
