### ISSUE TITLE
match recognize duplicate conditions

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#4109]
Another idea, match could recognize duplicate conditions:

https://psalm.dev/r/c76af18128

**Comment by iluuu1994** [comment]
Another variation of the same thing: https://psalm.dev/r/5313ce94b4

**Comment by muglug** [comment]
Ah, also a problem for ternaries: https://psalm.dev/r/aea99c733e

**Comment by iluuu1994** [comment]
This case is still missing: https://psalm.dev/r/c1a2238d0e
