### ISSUE TITLE
Catch classes should implement Throwable or extend Exception

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#411]
```php
class A {}

try {
  echo "hello";
} catch (A $a) {}
```

should fail with `InvalidCatch`

**Comment by TysonAndre** [comment]
A note about fixing this: InvalidCatch may be seen when a class implements an interface (my_interface_exception).

Zend PHP allows you to have `catch (my_interface_exception $e) {}`, and will catch an interface.
Aside: HHVM doesn't allow you to do that.

This can easily be solved in PHP7 by adding `interface my_interface_exception extends Throwable` if my_interface_exception isn't already throwable.

**Comment by muglug** [comment]
yeah, that problem is implicitly referenced in this test: https://github.com/vimeo/psalm/blob/fdff250c4ab2105a84867a98fc6d82d57e074f50/tests/TryCatchTest.php#L28-L37

**Comment by weirdan** [comment]
Also, docblock suppression needs to be on `try` keyword (also shown by the test above).

**Comment by ndench** [comment]
@muglug why does psalm fail with InvalidCatch when catching a random interface? Shouldn't that be allowed?

**Comment by Wirone** [comment]
@ndench that interface should extend `\Throwable`. It's known issue, for example with `GuzzleException` (interface).

@muglug is it possible to suppress `InvalidCatch` by configuration? `referencedClass` does not work.

**Comment by muglug** [comment]
@ndench @Wirone I've just made both `InvalidClass` and `InvalidCatch` both configurable by class.

**Comment by TysonAndre** [comment]
> This can easily be solved in PHP7 by adding `interface my_interface_exception extends Throwable` if my_interface_exception isn't already throwable.

My earlier comment was incorrect: classes/interfaces can't implement throwable, that causes a PHP error. Classes can only extend Error/Exception

**Comment by weirdan** [comment]
Classes can implement Throwable (or interfaces extending that) if they also extend Exception/Error.

**Comment by muglug** [comment]
There was a 2.x release the day after - sorry, should have pinged this issue.
