### ISSUE TITLE
match duplicate bodies

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#4110]
https://psalm.dev/r/b4cb058edb

```php
return match ($input) {
    1 => 'foo',
    2 => 'foo',
};
```

This could be rewritten as:

```php
return match ($input) {
    1, 2 => 'foo',
};
```

Not sure how easy it is to recognize if two bodies are the same. This could potentially be useful for other control-statements as well:

```php
if ($cond) {
    foo();
} else {
    foo();
}

$result = $cond ? foo() : foo();
```

Feel free to close this as a wontfix if don't think this is worth it.

**Comment by muglug** [comment]
yeah, this is more of a CS thing I think
