### ISSUE TITLE
`ProjectAnalyzer#checkFile()` fails to load stub information when called more than once

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#4117]
While working on https://github.com/Roave/infection-static-analysis-plugin/pull/1, I [found an issue with `ProjectAnalyzer#checkFile()`](https://github.com/Roave/infection-static-analysis-plugin/pull/1#issuecomment-685933611) (and similar `ProjectAnalyzer` API).

Discussed a bit with @bdsl on slack: https://symfony-devs.slack.com/archives/C8SFXTD2M/p1599073365027000

Here's a reproducer:

```php
<?php

declare(strict_types=1);

use PackageVersions\Versions;
use Psalm\Config;
use Psalm\Internal\Analyzer\ProjectAnalyzer;
use Psalm\Internal\IncludeCollector;
use Psalm\Internal\Provider\FileProvider;
use Psalm\Internal\Provider\Providers;
use Psalm\Report;
use Psalm\Report\ReportOptions;

(static function () : void {
    require_once __DIR__ . '/vendor/autoload.php';

    define('PSALM_VERSION', Versions::getVersion('vimeo/psalm'));
    define('PHP_PARSER_VERSION', Versions::getVersion('nikic/php-parser'));

    $psalmConfig = Config::getConfigForPath(__DIR__, __DIR__, Report::TYPE_CONSOLE);

    $psalmConfig->setIncludeCollector(new IncludeCollector());

    $projectAnalyzer = new ProjectAnalyzer(
        $psalmConfig,
        new Providers(new FileProvider()),
        new ReportOptions()
    );

    $psalmConfig->visitComposerAutoloadFiles($projectAnalyzer);
    $projectAnalyzer->checkFile(__DIR__ . '/aaa.php');
    $projectAnalyzer->checkFile(__DIR__ . '/bbb.php');

    die(var_dump(
        $projectAnalyzer->getCodebase()
            ->file_reference_provider
            ->getExistingIssues()
    ));
})();
```

`aaa.php`:

```php
<?php

function add(int $a, int $b): int {
    return $a + $b;
}
```

`bbb.php`:

```php
<?php

function hasMethod(object $input, string $method): bool {
    return (new ReflectionClass($input))
        ->hasMethod($method);
}
```

The code above will crash:

```
PHP Fatal error:  Uncaught UnexpectedValueException: Cannot get method params for ReflectionClass::hasmethod in vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php:460
Stack trace:
#0 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php(255): Psalm\Internal\Codebase\Methods->getMethodParams()
#1 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php(670): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkMethodArgs()
#2 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(173): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalyzer::analyze()
#3 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php on line 460
```

Doing more analysis, specifically comparing the `ProjectAnalyzer` instance **before** and **after** the second call to `ProjectAnalyzer#checkFile()`, I found this difference:

```diff
+           'diff_map' => 
+          array (
+            '.../vendor/vimeo/psalm/src/Psalm/Internal/Stubs/CoreGenericFunctions.phpstub' => 
+            array (
+            ),
+            '.../vendor/vimeo/psalm/src/Psalm/Internal/Stubs/CoreGenericClasses.phpstub' => 
+            array (
+            ),
+            '.../vendor/vimeo/psalm/src/Psalm/Internal/Stubs/CoreImmutableClasses.phpstub' => 
+            array (
+            ),
+          ),
```

This is the `Psalm\Internal\Provider\StatementsProvider#$diff_map` property. I traced back where it is being manipulated, and it happens in following trace:

```
Psalm\Internal\Provider\StatementsProvider->setUnchangedFile()
Psalm\Internal\Codebase\Scanner->scanFile()
Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}()
Psalm\Internal\Codebase\Scanner->scanFilePaths()
Psalm\Internal\Codebase\Scanner->scanFiles()
Psalm\Codebase->scanFiles()
Psalm\Config->visitStubFiles()
Psalm\Internal\Analyzer\ProjectAnalyzer->checkFile()
Roave\InfectionStaticAnalysis\Psalm\RunStaticAnalysisAgainstMutant->isMutantStillValidAccordingToStaticAnalysis()
Roave\InfectionStaticAnalysisTest\Psalm\RunStaticAnalysisAgainstMutantTest->testWillConsiderMutantReferencingReflectionApiAsValid()
```

So repeated calls to `ProjectAnalyzer#checkFile()` lead to repeated calls to `Config#visitStubFiles()`, which in turn lead to said stubs being marked as "unchanged" (which I assume is why they are skipped from a "deep scan"), and that in turn seems to remove part of the stub information from the system.

I think it removing (block-list or such) the stubs from being labeled as "unchanged" could help here, but I don't have an overview on how the system decides whether to check for file freshness or not...

**Comment by weirdan** [comment]
Have you tried using `ProjectAnalyzer::checkPaths()` instead? It's what Psalm itself is doing when it gets called with the file(s) on the command line. Although there is a call to `checkFile()` in a loop in `psalter` which may exhibit the same issue.

**Comment by Ocramius** [comment]
@weirdan exact same crash with `ProjectAnalyzer::checkPaths()`

**Comment by Ocramius** [comment]
I manipulated `StatementsProvider#setUnchangedFile()` from:

https://github.com/vimeo/psalm/blob/73f6fcde48b3970ea750c8806158fcde9e0ee2ea/src/Psalm/Internal/Provider/StatementsProvider.php#L318-L328

to:

```php
    /**
     * @param string $file_path
     *
     * @return void
     */
    public function setUnchangedFile($file_path)
    {
        if (1 === \preg_match('/\.phpstub$/', $file_path)) {
            return;
        }

        if (!isset($this->diff_map[$file_path])) {
            $this->diff_map[$file_path] = [];
        }
    }
```

This still leads to the same crash, so the state of this property doesn't seem to affect this particular issue.

**Comment by weirdan** [comment]
> exact same crash with ProjectAnalyzer::checkPaths()

Are you calling it more than once? It's supposed to be run once, but accepts a list of files to check:
```php
    $projectAnalyzer->checkPaths([
        __DIR__ . '/aaa.php',
        __DIR__ . '/bbb.php',
    ]);
```
I can reproduce the crash with multiple calls to `checkFile()`, but it works for me if I use `checkPaths()` as shown above.

**Comment by Ocramius** [comment]
> Are you calling it more than once?

Yes, it can only be called more than once sequentially (by design), since the runs are performed during infection mutant analysis, after the mutant is dumped and executed.

I also tried re-instantiating psalm completely (`new Config()` as well as `new ProjectAnalyzer()`, basically), but some global state still escapes.

**Comment by Ocramius** [comment]
To be clear, the bug is 100% about the following not working when/if classes used in stubs are referenced:

```php
    $projectAnalyzer->checkFile(__DIR__ . '/aaa.php');
    $projectAnalyzer->checkFile(__DIR__ . '/bbb.php');
```

**Comment by Ocramius** [comment]
Ok, the issue seems to be different from what I though.

Broken:

```php
    $projectAnalyzer->checkFile(__DIR__ . '/aaa.php');
    $projectAnalyzer->checkFile(__DIR__ . '/bbb.php');
```

Working:

```php
    $projectAnalyzer->checkFile(__DIR__ . '/bbb.php');
    $projectAnalyzer->checkFile(__DIR__ . '/aaa.php');
```

It seems like `Psalm\Storage\ClassLikeStorage::$methods` fails to be populated properly in the first example: only the methods present in the stub are put in there, while all others (there should be `53` on PHP 7.4.8) are not there.

I'm investigating how this is initialized, so perhaps I can find a difference in execution flow :-)

**Comment by weirdan** [comment]
> but some global state still escapes.

You likely need to call `RuntimeCaches::clearAll()` between runs. It's what's used by the test suite to clean up global state.

**Comment by weirdan** [comment]
```php
<?php

declare(strict_types=1);

use PackageVersions\Versions;
use Psalm\Config;
use Psalm\Internal\Analyzer\ProjectAnalyzer;
use Psalm\Internal\IncludeCollector;
use Psalm\Internal\Provider\FileProvider;
use Psalm\Internal\Provider\Providers;
use Psalm\Internal\RuntimeCaches;
use Psalm\Report;
use Psalm\Report\ReportOptions;

$f = static function ($file): void {
    require_once __DIR__ . '/vendor/autoload.php';

    define('PSALM_VERSION', Versions::getVersion('vimeo/psalm'));
    define('PHP_PARSER_VERSION', Versions::getVersion('nikic/php-parser'));

    $psalmConfig = Config::getConfigForPath(__DIR__, __DIR__, Report::TYPE_CONSOLE);

    $psalmConfig->setIncludeCollector(new IncludeCollector());

    $projectAnalyzer = new ProjectAnalyzer(
        $psalmConfig,
        new Providers(new FileProvider()),
        new ReportOptions()
    );

    $psalmConfig->visitComposerAutoloadFiles($projectAnalyzer);
    $projectAnalyzer->checkFile($file);

    die(var_dump(
        $projectAnalyzer->getCodebase()
            ->file_reference_provider
            ->getExistingIssues()
    ));
    RuntimeCaches::clearAll();
};

$f(__DIR__ . '/aaa.php');
$f(__DIR__ . '/bbb.php');
unset($f);

```
Works for me with either order of files. Note the `RuntimeCaches::clearAll()` call.

**Comment by Ocramius** [comment]
That seems like a good temporary solution: will give it a shot in a few.

Currently step-debugging the OP example.

In the case where `$projectAnalyzer->checkFile(__DIR__ . '/aaa.php');` happens (note: this is a file that does **not** reference `ReflectionClass`), the stack trace for populating `Psalm\Storage\ClassLikeStorage::$methods` for `ReflectionClass` looks like:

```
ReflectorVisitor.php:1968, Psalm\Internal\PhpVisitor\ReflectorVisitor->registerFunctionLike()
ReflectorVisitor.php:332, Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode()
NodeTraverser.php:200, PhpParser\NodeTraverser->traverseArray()
NodeTraverser.php:114, PhpParser\NodeTraverser->traverseNode()
NodeTraverser.php:223, PhpParser\NodeTraverser->traverseArray()
NodeTraverser.php:91, PhpParser\NodeTraverser->traverse()
FileScanner.php:96, Psalm\Internal\Scanner\FileScanner->scan()
Scanner.php:614, Psalm\Internal\Codebase\Scanner->scanFile()
Scanner.php:370, Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure:/home/ocramius/Documents/roave/infection-static-analysis-plugin/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php:366-372}()
Scanner.php:482, Psalm\Internal\Codebase\Scanner->scanFilePaths()
Scanner.php:328, Psalm\Internal\Codebase\Scanner->scanFiles()
Codebase.php:477, Psalm\Codebase->scanFiles()
Config.php:1864, Psalm\Config->visitStubFiles()
ProjectAnalyzer.php:1183, Psalm\Internal\Analyzer\ProjectAnalyzer->checkFile()
foo.php:33, {closure:/home/ocramius/Documents/roave/infection-static-analysis-plugin/foo.php:14-42}()
foo.php:42, {main}()
```

In the case where `bbb.php` is loaded first (file uses `ReflectionClass`), the same trace looks like:

```
Reflection.php:243, Psalm\Internal\Codebase\Reflection->extractReflectionMethodInfo()
Reflection.php:197, Psalm\Internal\Codebase\Reflection->registerClass()
Scanner.php:547, Psalm\Internal\Codebase\Scanner->convertClassesToFilePaths()
Scanner.php:332, Psalm\Internal\Codebase\Scanner->scanFiles()
Codebase.php:477, Psalm\Codebase->scanFiles()
ProjectAnalyzer.php:1181, Psalm\Internal\Analyzer\ProjectAnalyzer->checkFile()
foo.php:33, {closure:/home/ocramius/Documents/roave/infection-static-analysis-plugin/foo.php:14-42}()
foo.php:42, {main}()
```

In `aaa.php`, the stubs are loaded early on, whereas in `bbb.php`, since the file is scanned, and `ReflectionClass` is required at some point (found in the AST nodes), the `ClassLikeStorage` is populated for it via reflection directly.

**Comment by Ocramius** [comment]
@weirdan your approach with resetting everything in-between seems to work for my current use-case: it doesn't invalidate the issue, but at least I can start experimenting with the downstream projects :+1: 

Thanks for helping out!

**Comment by weirdan** [comment]
> Works for me with files in either order. Note the RuntimeCaches::clearAll() call.

Heh, you've managed to snuck a `die()` in there. The version that actually work looks like this:
```php
<?php

declare(strict_types=1);

use PackageVersions\Versions;
use Psalm\Config;
use Psalm\Internal\Analyzer\ProjectAnalyzer;
use Psalm\Internal\IncludeCollector;
use Psalm\Internal\Provider\FileProvider;
use Psalm\Internal\Provider\Providers;
use Psalm\Internal\RuntimeCaches;
use Psalm\Report;
use Psalm\Report\ReportOptions;

$f = static function ($file): void {
    require_once __DIR__ . '/vendor/autoload.php';

    defined('PSALM_VERSION') or define('PSALM_VERSION', Versions::getVersion('vimeo/psalm'));
    defined('PHP_PARSER_VERSION') or define('PHP_PARSER_VERSION', Versions::getVersion('nikic/php-parser'));

    $psalmConfig = Config::getConfigForPath(__DIR__, __DIR__, Report::TYPE_CONSOLE);

    $psalmConfig->setIncludeCollector(new IncludeCollector());

    $projectAnalyzer = new ProjectAnalyzer(
        $psalmConfig,
        new Providers(new FileProvider()),
        new ReportOptions()
    );

    $psalmConfig->visitComposerAutoloadFiles($projectAnalyzer);
    $projectAnalyzer->checkFile($file);

    var_dump(
        $projectAnalyzer->getCodebase()
            ->file_reference_provider
            ->getExistingIssues()
    );
    RuntimeCaches::clearAll();
};

$f(__DIR__ . '/bbb.php');
$f(__DIR__ . '/aaa.php');
unset($f);
```

**Comment by Ocramius** [comment]
Yeah, I noticed the `die()` in your previous example, no worries :D 

The final implementation is @ https://github.com/Roave/infection-static-analysis-plugin/pull/1/commits/2bf4772f9b94c0d48f070443b5645e1ef1c62f7a: currently testing it with a larger project.

**Comment by weirdan** [comment]
> Thanks for helping out!

Glad to help, at least hours spent on #4045 paid off once again.

**Comment by Ocramius** [comment]
Heh, I still think we got a real nasty one here. Getting rid of that bug here would speed up analysis during mutation tests by quite a lot as well :)

**Comment by muglug** [comment]
OK, so I think you don't want to use the `checkFile` endpoint, but instead something a little lower in the stack.

Have a look at how this test operates: https://github.com/vimeo/psalm/blob/master/tests/FileUpdates/ErrorFixTest.php#L53

I think you want to use `Codebase::reloadFiles()`, which should bust all the relevant cache.
