### ISSUE TITLE
Can't configure ParamNameMismatch in psalm.xml

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#4124]
> Element '{https://getpsalm.org/schema/config}ParamNameMismatch': This element is not expected.

```xml
<?xml version="1.0"?>
<psalm ...>
    <issueHandlers>
        <ParamNameMismatch errorLevel="info" />
    </issueHandlers>
</psalm>
```

For some reason this only fails in CI, any idea why?

**Comment by orklah** [comment]
I'm pretty sure it disappeared on master but not on 3.X releases. I had to delete it too when fetching psalm on master

**Comment by muglug** [comment]
Maybe you have an old version of Psalm running?

It was added here: https://github.com/vimeo/psalm/commit/6085e42fc1f783497f06a5563d3aa4939da30160

**Comment by iluuu1994** [comment]
That shouldn't happen, it updates the composer.lock on every build...

**Comment by muglug** [comment]
I'm going to preemptively say there's something off about your setup

**Comment by iluuu1994** [comment]
I don't understand it, Composer kept pulling Psalm 3.12 for absolutely no reason (we're not using prefer `--prefer-lowest`). Now that I updated the version constraint from `^3.6.4` to `^3.15` it works as expected.

Either way, you were right. Thanks!
