### ISSUE TITLE
Colorize file/line information in output

### ISSUE THREAD

**Issue by Rarst** [vimeo/psalm#4129]
Psalm colors code element in snippet that triggered the error.

That is useful, however in any large file it is impractical to locate the error by snippet. For fast IDE lookup the most important information to locate the error is file name and line number.

Also since the length of output varies, this is in different place on screen from error to error, requiring to visually scan monochrome message for it every time.

Can I suggest this part of output is made colored? Probably not red, but blue or something.

Thank you for considering. :)

**Comment by muglug** [comment]
@rarst mind giving an example of what it should look like?

**Comment by Rarst** [comment]
Ok, blue is too dark to be readable in vanilla terminal.

If I just go with more red I get something like this:

![psalm-colorize-location](https://user-images.githubusercontent.com/737584/92505256-800bae80-f20c-11ea-8534-e02add7bd198.png)

**Comment by caugner** [comment]
> Ok, blue is too dark to be readable in vanilla terminal.

Maybe it would make sense to take some inspiration from `yarn outdated` colors:

![grafik](https://user-images.githubusercontent.com/495429/125142879-253b3000-e119-11eb-8921-28446cd25c86.png)
