### ISSUE TITLE
Suppressing UndefinedTrait makes Psalm crash

### ISSUE THREAD

**Issue by Rarst** [vimeo/psalm#4130]
I have one specific class where suppressing `UndefinedTrait` causes a crash with `Could not find file for...` message.

Reduced to the most minimal code I could (strangely everything left is somehow meaningful? like removing the property or methods stops crash from happening?): https://psalm.dev/r/7e67686524

**Comment by weirdan** [comment]
> strangely everything left is somehow meaningful? like removing the property or methods stops crash from happening?

I suspect it could have happened during property initialization check. No properties -> no check -> no crash.
