### ISSUE TITLE
Parse Error on short arrow

### ISSUE THREAD

**Issue by JoeCianflone** [vimeo/psalm#4134]
I'm not sure if this is a bug or a wording issue or what exactly, but I wanted to pass it along in case it's useful to update...

I had the following function: 

```php
    public function getBySlug(string $slug): Workspace
    {
        return $this->cache('getBySlug', fn () => $this->model->whereSlug($slug)->firstOrFail());
    }
```

This code works, but I was getting a ParseError on the ` => ` and was confused to say the least...turns out the real issue was that I forgot to put `Closure` for the `cache` function itself. So it seems like the real issue should have been that I never typed the parameter on the function, but I guess it broke down because Psalm first assumes this has gotta just be a variable or something...so the arrow blows it up? I'm spitballing.

Also, the link was to `https://psalm.dev/173` which doesn't seem to exist?

**Comment by weirdan** [comment]
> This code works, 

So can we see the code that was failing? Ideally in a form of link to snippet on psalm.dev, as requested by bot above.

**Comment by muglug** [comment]
Make sure you're running Psalm in a version of PHP 7.4 or higher (or, alternative, specify `--php-version=7.4` when you run Psalm.
