### ISSUE TITLE
Feature suggestion: New bitmask type

### ISSUE THREAD

**Issue by colinodell** [vimeo/psalm#4135]
Some functions (like `json_decode()` or `preg_match_all`) can change behavior based on a bitmask argument.  For example:

| Function | Flags | Behavior |
| --- | --- | --- |
| `json_decode()` | (none) | Does not throw exceptions |
| `json_decode()` | `JSON_THROW_ON_ERROR` | May throw a `JsonException` |
| `preg_match_all()` | `PREG_PATTERN_ORDER` (default) | `$matches` argument will be of type `array<array-key, array<int, string>>|null` |
| `preg_match_all()` | `PREG_SET_ORDER` | `$matches` argument will be of type `array<int, array<array-key, string>>|null` |
| `preg_match_all()` | `PREG_OFFSET_CAPTURE` or `PREG_PATTERN_ORDER\|PREG_OFFSET_CAPTURE` | `$matches` argument will be of type `array<array-key, array<int, array{0: string, 1: int}>>|null` |
| `preg_match_all()` | `PREG_SET_ORDER\|PREG_OFFSET_CAPTURE` | `$matches` argument will be of type `array<int, array<array-key, array{0: string, 1: int}>>|null` |
| `preg_match_all()` | `PREG_UNMATCHED_AS_NULL` or `PREG_PATTERN_ORDER\|PREG_UNMATCHED_AS_NULL` | `$matches` argument will be of type `array<array-key, array<int, string\|null>>|null` |
| `preg_match_all()` | `PREG_SET_ORDER\|PREG_UNMATCHED_AS_NULL` | `$matches` argument will be of type `array<int, array<array-key, string\|null>>|null` |
| `preg_match_all()` | `PREG_SET_ORDER\|PREG_UNMATCHED_AS_NULL\|PREG_OFFSET_CAPTURE` | `$matches` argument will be of type `array<int, array<array-key, array{0: string\|null, 1: int}>>|null` |

If we could add support for a new `bitmask` type that would open up some new possibilities:

 - Validating that only known flags are being set
 - Providing more-accurate definitions for internal function behaviors and types

Perhaps this could be a superset of the `int` type?  It could automatically be "applied" to any `int` that has bitwise operators performed on it, or if a known bitwise constant value is assigned to a variable.

Something like this would likely fix #4128 since we'd know exactly what types would be returned.  Yes, this would require several very-verbose type definitions as shown above, but that might be better than having no information at all (current behavior).

**Comment by colinodell** [comment]
Using the example from #4128, note the `MixedAssignment` message in https://psalm.dev/r/f170f02c7e

**Comment by muglug** [comment]
Thanks for that write-up. I've cheated a bit here, instead hard-coding the values: https://github.com/vimeo/psalm/blob/289540226903e778513a46906e1ca36288d96550/src/Psalm/Internal/Stubs/CoreGenericFunctions.phpstub#L645-L667

**Comment by colinodell** [comment]
That approach for me :)  Also, I'm only 90% sure my write-up is correct, as it's hard to track the types in multi-dimensional arrays, so if anyone could help verify I'd appreciate it!

**Comment by muglug** [comment]
OK, I'm going to close this as essentially solved
