### ISSUE TITLE
Union param type stub is not recognized in 3.15 (including dev-master)

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#4136]
This is from stubs I am making for [symfony/forms](https://github.com/strictify/psalm-plugin-symfony/tree/symfony-forms/src/Stubs/Forms).

---

#### The problem:

For a stub like this (removed irrelevant things):

```php
/**
 * @template T
 * @template-extends FormConfigInterface<T>
 */
interface FormConfigBuilderInterface extends FormConfigInterface
{
    /**
     * @psalm-param callable(PreSetDataEvent<T>)|callable(PreSubmitEvent<T>)|callable(SubmitEvent<T>) $listener
     */
    public function addEventListener($eventName, $listener, $priority = 0);
}
```

version 3.14.2 correctly finds the problem:

![image](https://user-images.githubusercontent.com/1964158/92302842-b8429100-ef6f-11ea-90f1-c9c49a688304.png)

Psalm also knows that ``T`` is instance of ``?Campaign``.  It is very important; [based on name](https://symfony.com/doc/current/form/events.html#a-the-formevents-pre-set-data-event), symfony will send different child of ``FormEvent``, and each child has different data.

---

But in version 3.15, psalm cannot recognize this stub and throws errors like this:

![image](https://user-images.githubusercontent.com/1964158/92302934-9a296080-ef70-11ea-92f2-a4aa2988f433.png)

All events fails so I had to revert. I checked changelog, can't see anything that could be the problem.

---

Am I doing something wrong or this is really a bug? Not sure how I can put a reproducer on psalm.dev (due to so many files needed) so some simple repository would probably be better.

**Comment by zmitic** [comment]
Correction; I do have a simple repository as a reproducer: https://github.com/strictify/forms-playground

Problematic version 3.15:

![image](https://user-images.githubusercontent.com/1964158/92303351-3012ba80-ef74-11ea-965a-3363ea29090a.png)

---

Version 3.14.2 correctly knows $user will be instance of ``?User``:

![image](https://user-images.githubusercontent.com/1964158/92303371-6e0fde80-ef74-11ea-93f8-2dbb61605ce4.png)

(I put trace to be on error level)

---

I added changes in code for this reproducer, it can be downloaded.

**Comment by zmitic** [comment]
@muglug I just tested it and while it doesn't throw errors anymore, PresetDataEvent doesn't register correct data (like 3.14.2 did).

To remove variables from reproducer, I uninstalled Symfony plugin and added stubs [in repository itself](https://github.com/strictify/forms-playground/tree/psalm-reproducer/stubs).

---

So in 3.14.2:

```
ERROR: Trace - src/Controller/Users/Complex/Form/SimpleUserType.php:43:0 - $user: App\Entity\User|null 
```

changing psalm to dev-master:

```
ERROR: Trace - src/Controller/Users/Complex/Form/SimpleUserType.php:43:0 - $user: mixed 
```

**Comment by muglug** [comment]
this is now fixed @zmitic

**Comment by zmitic** [comment]
Thank you @muglug , I wasn't sure if you read github email and planned to create new issue in few days.

I just tested, works perfectly!
