### ISSUE TITLE
PossiblyNullArgument even I validate it before throwing an Exception

### ISSUE THREAD

**Issue by josecl** [vimeo/psalm#4138]
Throws an Exception if `$number` is `null`, but Psalm insist in PossiblyNullArgument after.

https://psalm.dev/r/96d623ea33

```php
<?php


class Foo {

  public function bar(int $number = null): int
  {
      /**
       * Throw Exception if  $number is null
       */
      $this->throwIf(is_null($number), 'Number is null');
      return $this->addOne($number);
  }
    
  private function addOne(int $number): int
  {
      return $number + 1;
  }
  
  private function throwIf(bool $condition, string $message): void
  {
      if ($condition) {
           throw new Exception($message);
      }
  }
}

echo (new Foo)->bar(null);
```

**Comment by weirdan** [comment]
Psalm analysis generally (there are exceptions) does not cross function boundaries. There's a syntax to surface assertions made by the function (see https://psalm.dev/docs/annotating_code/assertion_syntax/), but right now Psalm can't deduct that `$number` is not null from the truthiness of the condition (https://psalm.dev/r/14fd2285a7). It's, however, possible to do with built-in assertions: https://psalm.dev/r/f5844c8f13, so it should be possible to implement this for function assertions as well.

**Comment by muglug** [comment]
@weirdan you've just got the assertion backwards – this works: https://psalm.dev/r/0da3bcde87

**Comment by weirdan** [comment]
:facepalm:

**Comment by josecl** [comment]
Thanks for your support :)
