### ISSUE TITLE
Broke psalm while trying to type promise

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#4148]
https://psalm.dev/r/a599b50ca8

Not saying this example is validly typed though - I have omitted the parentheses around the conditional type, the `null` must belong to the template instead of being directly in `@param` etc. Anyway, the psalm crash looks like a bug for me.

**Comment by weirdan** [comment]
Pretty much any crash is a bug.

**Comment by muglug** [comment]
@someniatko your conditional return type needs brackets: https://psalm.dev/r/1fad580654

**Comment by muglug** [comment]
minimal reproducer: https://psalm.dev/r/55dbded469

**Comment by muglug** [comment]
_actually_ just 

```php
<?php

class C {}

function foo() : C {
    return fn (int $i) => '';
}
```
