### ISSUE TITLE
An official plugin registry?

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#4150]
Some popular libraries do really operate on types which are not expressible in the current PHP type system, for example, generic classes and functions. Meanwhile, they do not have psalm-ish annotations for such types, for the following set of reasons:
- the library author decided he won't litter his code with 3rdparty-driven syntax, and evangelists like Ocramius hadn't changed his mind
- a lib is old and/or slowly maintained
- the author doesn't know about Psalm yet

Examples of such libraries which I had to type myself are nikic/iter and guzzlehttp/promise.

For such cases, Psalm supports stubs and plugins 👍. However, there are some problems:
- such plugins may be hard to know about and find for the "end-user"
- as the result their popularity will be lower, than they deserve
- due to the low popularity, they may be slowly or almost not maintained, because of lack of motivation
- also it's possible that multiple plugins for the same lib would be developed independently

TypeScript community solves these issues by introducing `@types/<lib>` packages family. We could do something similar, provide a namespace for such plugin packages, and make an official list of them. Personally I could take a responsibility to support one for `nikic/iter` and maybe also `guzzlehttp/*`. Such plugins do [already](https://github.com/alexeyshockov/iter-psalm-plugin) [exist](https://github.com/alexeyshockov/guzzle-psalm-plugin), but they are slightly outdated and also not as precise as I'd wish.

**Comment by weirdan** [comment]
https://packagist.org/?type=psalm-plugin lists all of the public plugins (installable with composer).

**Comment by weirdan** [comment]
It's also available in machine-readable format here: https://packagist.org/packages/list.json?type=psalm-plugin, so I would suggest to use that to show the list on psalm.dev (the repo lives at https://github.com/psalm/psalm.dev).

**Comment by someniatko** [comment]
Oh, that's great, didn't notice this composer package type, thank you!
