### ISSUE TITLE
Add mysqli::query as a taint sink

### ISSUE THREAD

**Issue by craigfrancis** [vimeo/psalm#4155]
While this issue is detected:

    <?php
    $mysqli = new mysqli('localhost', 'test', '???', 'test');
    $result = mysqli_query($mysqli, 'SELECT * FROM user WHERE id = ' . $_GET['id']);
    ?>

This one is not:

    <?php
    $mysqli = new mysqli('localhost', 'test', '???', 'test');
    $result = $mysqli->query('SELECT * FROM user WHERE id = ' . $_GET['id']);
    ?>

**Comment by craigfrancis** [comment]
https://psalm.dev/r/a92254e11d
https://psalm.dev/r/fcf2f09014

**Comment by muglug** [comment]
@craigfrancis you should be able to PR this, making a change to `InternalTaintSinkMap.php`
