### ISSUE TITLE
query re: support for esoteric setups

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#4156]
Sometimes I'm dealing with legacy code where it's not possible/feasible to upgrade to 7.4, so I usually:

`git checkout --orphan psalm && git rm -fr .` then add the repo to itself as a submodule (as this allows issue resolutions / baseline commits to be tied together)

Usually it's fine, but I've just ran into one that I'm running under php `5.4.0`, aaaand it falls over.

If psalm has an `Uncaught UnexpectedValueException: $storage should not be null for X` where X is something under the submodule's vendor directory is it something worth fixing or is the setup too esoteric to be worth supporting?

**Comment by someniatko** [comment]
@SignpostMarv maybe try the standalone PHAR version?

**Comment by SignpostMarv** [comment]
I'm not 100% confident the PHAR would make a difference if there's weirdness between loading a modern autoloader and a legacy autoloader in the same script, but I'll put it on the mental to-do list.
