### ISSUE TITLE
PHP warnings

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#4165]
I noticed these warnings in one of my CI builds. It's a while back though so I'm not certain of the exact cause and can't reproduce them anymore. (Using Psalm 3.15.)

```
PHP Warning:  strrpos(): Offset is greater than the length of haystack string in
/usr/app/vendor/vimeo/psalm/src/Psalm/CodeLocation.php on line 295
PHP Warning:  strrpos(): Offset is greater than the length of haystack string in
/usr/app/vendor/vimeo/psalm/src/Psalm/CodeLocation.php on line 319
```

Feel free to close this if this isn't enough info to fix it. I'm unable to provide more info sadly.

**Comment by muglug** [comment]
Yeah, unless you have a reproducer this isn't particularly useful, sorry
