### ISSUE TITLE
Missing info about never reference from values from outer scope

### ISSUE THREAD

**Issue by snapshotpl** [vimeo/psalm#4166]
https://psalm.dev/r/a540d6df28

**Comment by muglug** [comment]
what’s the expected output here?

**Comment by snapshotpl** [comment]
Something like that https://psalm.dev/r/541118d8d5

**Comment by muglug** [comment]
Yes, that is correct, because indeed the statement has no effect.

**Comment by snapshotpl** [comment]
Sure, but same effect should be if statement comes not from argument, what I show early. Currently psalm doesn't do that but I think it can.

**Comment by snapshotpl** [comment]
@muglug I think you misread my issue. Can you take a look again?

**Comment by muglug** [comment]
Reasoning about closures is pretty hard, and I'm still unclear what bad code you want Psalm to tell you about
