### ISSUE TITLE
PropertyNotSetInConstructor reported once, expected twice

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#4167]
https://psalm.dev/r/b9134a8303

**Comment by Ocramius** [comment]
@ro0NL this looks correct: your object of type `b` is not complete at the time of instantiation, and this will lead to type-related runtime crashes later on.

**Comment by muglug** [comment]
Yeah, definitely bug, coincidentally crossed my mind to ticket yesterday (but I never did, so thanks)
