### ISSUE TITLE
Using @property annotations without __get() or __set() method

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#4183]
I find it useful to use the `@property` annotation independently from a `__get()` method, but unfortunately Psalm doesn't support it:

https://psalm.dev/r/055e27917e

**Background**: In this specific legacy code base I'm working on, all DB models extend a central `Base` class. All models have an `$id` property, but with varying visibility, so I cannot add it directly to the `Base` class. A solution is to add a `@property` annotation and PhpStorm displays the hierarchy nicely:

![grafik](https://user-images.githubusercontent.com/495429/93081754-0ce0bd00-f690-11ea-8404-e6d0383fd0f7.png)

However, Psalm does only accept the `@property` annotations if a `__get()` (or `__set()`) method exists.

**Comment by weirdan** [comment]
You need to enable it in `psalm.xml`, see [`usePhpDocPropertiesWithoutMagicCall` docs](https://psalm.dev/docs/running_psalm/configuration/#usephpdocpropertieswithoutmagiccall).
