### ISSUE TITLE
Allow union types in class-string (e.g. class-string<A|B>)

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#4185]
Union types are currently not allowed in `class-string`s:

https://github.com/vimeo/psalm/blob/b10c1ac280a37fb37a61231e1c15e8fdc631fe8b/src/Psalm/Internal/Type/TypeParser.php#L215-L217

However, it would be convenient if they were supported:

https://psalm.dev/r/df3b75b481

**Comment by muglug** [comment]
You can instead use `class-string<A>|class-string<B>`: https://psalm.dev/r/d59ae9cff7

**Comment by caugner** [comment]
I was aware of that workaround, but it's pretty verbose (class names anonymized):

```
with union:
class-string<Ce_________|Cr_______|Cu____________________|In________|Or___|Pr_____________|Pr_________|Re_____|Re__________|Tr_____________|Tr_________________>

without:
class-string<Ce_________>|class-string<Cr_______>|class-string<Cu____________________>|class-string<In________>|class-string<Or___>|class-string<Pr_____________>|class-string<Pr_________>|class-string<Re_____>|class-string<Re__________>|class-string<Tr_____________>|class-string<Tr_________________>
```
