### ISSUE TITLE
`MissingPureAnnotation` adds annotation to function using static variable

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#4191]
Not sure if this was just some quirk of our codebase.
I ran `MissingPureAnnotation` and then had a couple of errors for `ImpureStaticVariable`.
Seems like psalter incorrectly added the annotation to functions using static variables.
Can look more if it's not that simple.

3.15.0

**Comment by orklah** [comment]
Yeah, please post a problematic example

**Comment by orklah** [comment]
Closing this as not reproduced
