### ISSUE TITLE
random_int and positive-int

### ISSUE THREAD

**Issue by DanielBadura** [vimeo/psalm#4196]
https://psalm.dev/r/e074fe9e3a

I dont know if psalm should check if random_int could only return a positive or negative integer. What do you think?

**Comment by muglug** [comment]
Hey!

Would you mind creating a PR against `CoreGenericFunctions.phpstub`?

You'll want to add a return type with a [conditional return type](https://psalm.dev/articles/conditional-love), something like

```php
/**
 * @return ($min is positive-int ? ($max is positive-int ? positive-int : int) : int)
 */
function random_int(int $min int $max) : int {}
```

**Comment by DanielBadura** [comment]
Sure thing  👍
