### ISSUE TITLE
Way to annotate param callable as pure

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#4197]
When passing a callable to array_filter, psalm complains it's not pure. Can I somehow annotate the param callable to enforce its pureness?

> ERROR: ImpureFunctionCall - 12:10 - Cannot call an impure function from a mutation-free context

https://psalm.dev/r/aff554b882

**Comment by weirdan** [comment]
Yes, use `pure-callable(...)`: https://psalm.dev/r/4866afd3c5

**Comment by simPod** [comment]
Thanks!
