### ISSUE TITLE
query: re templating issues & defining types for import elsewhere

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#4200]
it's helpful to be able to import a type so it can be reused elsewhere without having to duplicate & maintain several instances of a type definition.

However, I'm running into some issues when using types with templating:

* works as expected: https://psalm.dev/r/d313b87ccc
* works as expected: https://psalm.dev/r/99ffa74eda
* expected to work (i.e. for T2 be an importable type) but fails: https://psalm.dev/r/328692b52a
* doesn't work but i'm not sure if it should: https://psalm.dev/r/190a61cda8
* works but I'm not sure if it should: https://psalm.dev/r/08c7ea7140
* works but I'm not sure if it should: https://psalm.dev/r/3561d475c1

**Comment by weirdan** [comment]
Duplicates #4240
