### ISSUE TITLE
Convert a class/interface into an object-like array

### ISSUE THREAD

**Issue by Patrick-Remy** [vimeo/psalm#4203]
It would be great to have an utility to create an array type of an existing class/interface. This would be extremly helpful in situations when you only have serialized representations of objects, e.g. from message queue inputs.

Proposal:
```php
// Some type declaration..
/**
 * @property bool $baz
 */
class Foo {
  public int $bar = 42;

  function doStuff(): int {
    return 42;
  }
}

// Usage of utility type
/**
 * @var Array<Foo>
 */
$serializedModel = $mqData;
$serializedModel['baz']; // bool
$serializedModel['bar']; // int
$serializedModel['doStuff']; // mixed/undefined
$serializedModel['asdf']; // mixed/undefined
```

So that `Array<Foo>` equals `array{baz: bool, bar: int}`.

**Comment by muglug** [comment]
sorry, I don't this will ever happen
