### ISSUE TITLE
PossiblyNullValue is incorrect for boolean casts

### ISSUE THREAD

**Issue by danielbeardsley** [vimeo/psalm#4206]
If `$y` is nullable, an "if" on a bool cast should be enough. These should be safe:

`if ((bool)$y) $y->getOffset();`
OR
`assert((bool)$y) && $y->getOffset();`

But psalm doesn't think they are. But it thinks doing the same with `!!` is safe:

`if (!!$y) $y->getOffset();`
OR
`assert(!!$y) && $y->getOffset();`

I'm pretty sure these are all safe and produce the same results.

Demo:
https://psalm.dev/r/0786d225c2

**Comment by muglug** [comment]
FYI `if ((bool) $foo)` is very unnecessary

**Comment by danielbeardsley** [comment]
> is very unnecessary

100% agree. I was just highlighting other permutations of the problem.

I discovered this when using `assert((bool)$x);` to protect some code from a possibly-null error.
