### ISSUE TITLE
False positive RedundantCondition

### ISSUE THREAD

**Issue by gharlan** [vimeo/psalm#4207]
https://psalm.dev/r/cb19cbfa41

`$arr` could be an empty array.

**Comment by gharlan** [comment]
Another false positive: https://psalm.dev/r/b3d964b844

**Comment by weirdan** [comment]
Case 1, simplified: https://psalm.dev/r/6e6ce9ab1e

**Comment by muglug** [comment]
Fixed in 0ae436d
