### ISSUE TITLE
Possible to mark class properties as @psalm-internal?

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#4214]
This would be an awesome feature if possible, similar to abstract types in FP. And you don't have to pollute the class API with getters/setters (which actually break encapsulation the same way as making a property public).

**Comment by weirdan** [comment]
It's possible: https://psalm.dev/r/faae6187bb (see [docs](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-internal) as well).
