### ISSUE TITLE
func_num_args() not usable in mutation-free/pure functions

### ISSUE THREAD

**Issue by colinodell** [vimeo/psalm#4215]
`func_num_args()` is detected as an impure function which prevents it from being used within a mutation-free or pure function.

In this example, I have a function which needs to differentiate between an optional parameter being explicitly set to `null` or not being provided at all: https://psalm.dev/r/2c0112de69

Psalm is technically correct that `func_num_args()` is impure since its output is not a function of its input.  However, I believe that my outer `getValue()` function is pure since its output only relies on the parameters passed in.

Should Psalm therefore make an exception to allow the impure `func_num_args()` function to be called within other pure functions?

**Comment by muglug** [comment]
Yeah, it doesn't seem impure in any context really
