### ISSUE TITLE
Returning an object on a string typed method

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#4235]
https://psalm.dev/r/b1b361febc

This should be considered as an ImplicitToStringCast.

The risk here is that if we want to put the file in strict_types=1, this will fail with a TypeError.

Example: 
https://github.com/vimeo/psalm/blob/master/src/Psalm/Codebase.php#L841

**Comment by orklah** [comment]
While we're on that type of issue:
https://psalm.dev/r/bae3e0422b

This should be one too. For example, It happens here:
https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php#L232
`$result->non_existent_magic_method_ids` is documented as array<string> but it contains class with __ToString

Maybe this should be reviewed in relation with the Stringable interface that comes in PHP 8?

**Comment by weirdan** [comment]
Original issue is now flagged. @orklah do you want to keep this open?

**Comment by orklah** [comment]
@weirdan Yes please, I'd like to revisit the second issue later. It seemed complicated earlier

**Comment by muglug** [comment]
Fixed
