### ISSUE TITLE
Dependent types

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#4239]
It would be nice in some case to be able to use at the type level information which is present at the value level.

Let me give an example: currently it is possible to define a type `array{foo: int}`, where `foo` is a sequence of characters. It would be nice to have the possibility to use a variable which evaluates to a string instead, like `array{$foo: int}`. This would imply that we need to have some evidence that `$foo` actually contains a string at compile time. This could be obtained, for example, if `$foo` is initialized as `$foo = 'foo'`; somewhere else.

This would allow to type things like the following:

```
/**
 * @template T
 * @param array<$key: T> $a
 * @param string
 * @return T
 */
function getArrayKey(array $a, string $key) {
    return $a[$key];
}
```

This would compile in this case

```
$a = ['foo' => 'bar']

$bar = getArrayKey($a, 'foo');
```

but not if there is a code path where `$key` is not explicitly defined

**Comment by weirdan** [comment]
This specific case is already possible with index types (`T[K]`): https://psalm.dev/r/6bee31cd2e

**Comment by marcosh** [comment]
Thanks @weirdan! That is nice to type my particular example! Is there any more documentation around on index types?

It would still be nice to be able to pass variables wherever strings are allowed in types. For example something like

```
/**
 * @param class-string $className
 * @return callable($className):$className
 */
public function idOn(string $className)
{
    return fn($x) => $x;
}
```

could be something one could think of doing.

Dependent types are a really nice tool for typing almost everything, so it would be really nice if things moved in that direction.

In the end, being able to do something like the following would be amazing

```
/**
 * @template A
 * @template I of int
 */
final class Vector
{
    /**
     * @var int
     */
    private $length;

    /** @var A[] */
    private $elements;

    /**
     * @param A[] $elements
     * @return self<A, count($elements)>
     */
    private function __construct(array $elements)
    {
        $this->elements = $elements;
        $this->length = count($elements);
    }

    /**
     * @template B
     * @return Vector<B, 0>
     */
    public static function empty(): self
    {
        return new self([]);
    }

    /**
     * @template B
     * @param B $head
     * @param Vector(B, $i) $tail
     * @return Vector(B, $i + 1)
     */
    public static function cons($head, self $tail): self
    {
        return new self(array_unshift($head, $tail->elements));
    }
}
```

**Comment by weirdan** [comment]
> Is there any more documentation around on index types?

Virtually none, in Psalm's own docs. It's mentioned on https://psalm.dev/docs/annotating_code/type_syntax/atomic_types/#magical-types, but that's it. It's similar to [index types in Typescript](https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types) though.

> For example something like
> ```
> /**
>  * @param class-string $className
>  * @return callable($className):$className
>  */
> public function idOn(string $className)
> {
>    return fn($x) => $x;
> }
>```
> could be something one could think of doing.

Perhaps, but there's already a syntax for that (https://psalm.dev/r/e13a907f06).

How would your last example behave when array length is unknown? E.g.:
```php
// what is the type of $envVector ?
/** @psalm-trace $envVector */
$envVector = Vector::cons(reset($_ENV), $_ENV);
```

**Comment by muglug** [comment]
Psalm won't add support for dependent types on the whole, but has added limited support where templates can be used.
