### ISSUE TITLE
Type declared with @psalm-type cannot be used in @template-extends annotation

### ISSUE THREAD

**Issue by maarekj** [vimeo/psalm#4240]
Hello,
Currently there is a bug with the using of `@psalm-type` in `@template-extends` annotation.

The following snippet (https://psalm.dev/r/f1fffe9d00), has some errors:
`ERROR: UndefinedDocblockClass - 20:13 - Docblock-defined class or interface IArgs does not exist`

```php
<?php

/**
 * @template TArgs
 * @template TReturn
 */
abstract class AbstractField
{
    /** 
     * @psalm-param TArgs $args
     * @psalm-return TReturn
     */
    abstract public function resolve($args);
}

/**
 * @psalm-type IArgs = array{id: string}
 * @template-extends AbstractField<IArgs, string>
 */
final class ClientField extends AbstractField
{
    public function resolve($args)
    {
        return $args['id'];
    }
}
```

Whereas the if I use `array{id: string}` instead of `IArgs`, that works (snippet on: https://psalm.dev/r/5173751356).

In the previous versions it worked (at least at version 3.12.1)

**Comment by maarekj** [comment]
The bug (regression) is present since the version 3.14.2

**Comment by weirdan** [comment]
@muglug this seems to be a recurring theme. I've found 4 more dupes of this issue.

**Comment by SignpostMarv** [comment]
> @muglug this seems to be a recurring theme. I've found 4 more dupes of this issue.

#4200 came first 🤷‍♂️

**Comment by jsiefer** [comment]
thanks @muglug - I was looking forward for that 👍
