### ISSUE TITLE
PropertyNotSetInConstructor and @required setter

### ISSUE THREAD

**Issue by maarekj** [vimeo/psalm#4241]
Hello,

In my code base, there are many services, who handled by symfony container (dependencies injection).
Sometimes I inject in my service an another service via a setter method.

Example:
```php
<?php

final class MyServiceA {
}

final class MyServiceB {
    private MyServiceA $a;
    public function __construct(){}

    /** @required */
    private function setMyServiceA(MyServiceA $a): void { $this->a = $a; }
}
```

In symfony, if I annotate my setter with @required annotation, symfony will inject the service in setter just after the constructor. The property `$a` will therefore always initialized.

In my exemple, Psalm raise an `PropertyNotSetInConstructor` error.
It would be nice if Psalm would handle this annotation.

Thanks you for your jobs.

**Comment by maarekj** [comment]
https://psalm.dev/r/df711a1f40

**Comment by weirdan** [comment]
I think it should be handled by the Symfony plugin: https://packagist.org/packages/psalm/plugin-symfony
