### ISSUE TITLE
Object with property types

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#4242]
Similarly to `array{foo: string}`, it could be useful to have a way to denote an object with a given public property, something like `object{foo: string}`. Then

```
/** @var object{foo: string} */
$a = new class {
    public $foo;
}
```

would work, while

```
/** @var object{foo: string} */
$a = new class {
    public $bar;
}
```

would fail

**Comment by weirdan** [comment]
`object{prop:type}` is already supported. What you have shown, though, implies variables having intrinsic type and Psalm doesn't have that notion. Psalm follows PHP semantic, and that means *values* (as opposed to *variables*) have types. Conflicting `@var` annotation just means that you're *overriding* the type Psalm inferred. There's a plugin (https://packagist.org/packages/struggle-for-php/sfp-psalm-typed-local-variable-plugin) that looks like it attempts to provide typed local variables.
