### ISSUE TITLE
PossiblyInvalidArgument not detecting previous if statements

### ISSUE THREAD

**Issue by tlmdevs** [vimeo/psalm#4244]
Hello,

I'm getting an issue with psalm detecting a PossiblyInvalidArgument which cannot be reached in the code.

An excerpt from the code
```php
if(!is_string($input->getArgument('from'))) {
	$output->writeln('<error>Bad date given!</error>');
	return;
}

$dateInt = strtotime($input->getArgument('from'));
```

Psalm gives the following error:
`Argument 1 of strtotime expects string, possibly different type array<array-key, string>|null|string provided `

While $input->getArgument() can return multiple types, it would be preferable if psalm could detect that only if the return value is string, the strotime() call is reached.

I tried to assign the variable earlier, type cast it etc., but with no avail.

EDIT 2:
Reproduced: https://psalm.dev/r/5b73ce4898

EDIT:
The workaround is currently psalm-suppress

**Comment by muglug** [comment]
Assigning early fixes things: https://psalm.dev/r/c6aaba75b7
