### ISSUE TITLE
Not all code paths return expected type - using while(true) and exceptions

### ISSUE THREAD

**Issue by DanielBadura** [vimeo/psalm#4245]
Right now I'm trying to build a game and for that i need an endless loop. I control the code paths with exceptions and im getting an error that  not all paths are returning  the defined return type. In my (and PHPStorm) perspective this example given here has all paths covered:

https://psalm.dev/r/0cf7505bf0

Am i missing something or should this be addressed in psalm?

**Comment by muglug** [comment]
Definitely a Psalm bug (albeit an edge-case)

**Comment by weirdan** [comment]
Simplified (by @timglabisch in #4380): https://psalm.dev/r/b65d92985e

**Comment by orklah** [comment]
Both examples given here now works
