### ISSUE TITLE
Inconsistent behavior with compound or

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#4246]
I've noticed some odd behavior with compound `||` expressions. I have some objects with methods that return other objects or null, and I need to access something nested several levels, so I did something like this: https://psalm.dev/r/5555a6fb52

I figured maybe psalm didn't recognize the check against the assignment expression, so I tried this to see what would happen, but it catches it as a redundant condition and correctly shows that each variable is being compared to `null` twice: https://psalm.dev/r/56b817ca77

Then I noticed prepending a condition causes `$a2` to be `mixed` as well as `$a3`, so it looks like the first expression is treated specially somehow: https://psalm.dev/r/a49a3af346

**Comment by muglug** [comment]
Initialise the conditionally-assigned variables to null, and everything should work: https://psalm.dev/r/7040fdddf5

Beyond that workaround, it's too complex to fix (assignments within conditionals are very complex things).
