### ISSUE TITLE
Types of inherited class constants don't work

### ISSUE THREAD

**Issue by dmolineus** [vimeo/psalm#4248]
Using `self::`, `static::` or `ClassName::` when accessing a constant of a parent class don't work. Only then using the class name of the parent class the type is inferred correctly:

https://psalm.dev/r/1c0ee29814

**Comment by azjezz** [comment]
*It's not a bug! It's a feature!*

```php
<?php

class A {
  public const FOO = 'a';
}

class B extends A { 
  public function hello(): string
  {
    return static::FOO; // ops, doesn't work! why?
  }
}

class C extends B {
  public const FOO = ['because the type can change.'];
}

print_r((new B)->hello());
print_r((new C)->hello());
```

see: https://3v4l.org/d3sea

however, i think the usage of `self::FOO` in `C` can be considered safe as long as the constant is not redeclared in `C` or a trait/interface that `C` uses.

but its better to be safe and use the name of the class that contains the original declaration.

**Comment by dmolineus** [comment]
For a non final class, I agree that's considered as a feature. For a final class, as I used above, there can't be any change. 

I checked my example again and with the current version (ref 2b5b255) of psalm it seems to be fixed. So I close this issue.
