### ISSUE TITLE
Unrecognised annotation @psalm-param-out

### ISSUE THREAD

**Issue by ptomulik** [vimeo/psalm#4251]
https://psalm.dev/r/afcfe74491

**Comment by ptomulik** [comment]
Simplified example
https://psalm.dev/r/f7b9ce60af

**Comment by ptomulik** [comment]
Sorry, looks I was asleep. The example could be reduced to the following

https://psalm.dev/r/301c6a3ffb

**Comment by muglug** [comment]
Mind adding this? Shouldn't be too tricky.

**Comment by ptomulik** [comment]
Where to start?

**Comment by muglug** [comment]
search for `param-out` in the repo
