### ISSUE TITLE
Feature request: return type restriction on generic return types

### ISSUE THREAD

**Issue by andyg0808** [vimeo/psalm#4254]
It seems like it would be helpful to be able to write an `assert` function that returns the value it's asserting on, so it could be wrapped around suspect calls. It doesn't currently seem possible to restrict the return type of a function using `@psalm-assert` or conditional return types:
https://psalm.dev/r/9ad9cb566e

Thanks for all your work on Psalm; it's great!

**Comment by muglug** [comment]
This should work, I think – Psalm should subtract `false` from whatever type is passed to get the new type.

```
<?php
/**
 * @template T
 * @param T|false $i
 * @return T
 */
function orThrow($i) {
    if ($i === false) {
        throw new Exception("Error");
    }
    return $i;
}

/** @param array<int> $arr */
function doThing(array $arr): void {
    $thing = orThrow(reset($arr));
    if (is_int($thing)) {}
}
```

**Comment by andyg0808** [comment]
Thanks for the suggestion; Psalm still seems to think that `$thing` is `false|int`:
https://psalm.dev/r/244fa69498

**Comment by muglug** [comment]
Yes, sorry I wasn't clear – it _should_ work, but it doesn't (yet)

**Comment by muglug** [comment]
This is now fixed
