### ISSUE TITLE
False negative: incorrect destructuring from array literals is not flagged

### ISSUE THREAD

**Issue by andyg0808** [vimeo/psalm#4256]
Psalm doesn't notice that `$a` will be `null` in this example:
https://psalm.dev/r/b35920dd45
This causes a runtime error when run with strict types:
https://3v4l.org/GBBpN

This seems to be particularly related to empty arrays; a bunch of similar examples with at least one element in the array error correctly:
https://psalm.dev/r/0ab7f09f99

**Comment by andyg0808** [comment]
A similar situation arises when using typed properties: 
https://psalm.dev/r/f7f73ef820

In this case, the assignment fails at runtime, even without the function call, because `null` can't be assigned to the type of the property:
https://3v4l.org/PS9Oa

**Comment by orklah** [comment]
What do you think about that @muglug ? Should we forbid destructuring empty arrays or just assign the results to null?

**Comment by muglug** [comment]
Now caught as a bug
