### ISSUE TITLE
False negative: Psalm doesn't notice invalid array destructuring with keyed arrays

### ISSUE THREAD

**Issue by andyg0808** [vimeo/psalm#4257]
When we have an array with known keys, Psalm doesn't notice if it's destructured into too many variables:
https://psalm.dev/r/25595fa1a1

I'd have expected this to fail, because Psalm can't guarantee those keys exist. It _does_ fail if passed to a function with an array type:
https://psalm.dev/r/fb75f4fda6
https://psalm.dev/r/141831ef79

We can cause a runtime error by passing the final destructured variable to a function that requires an `int`, which fails on  being passed `null`: https://3v4l.org/8DghL

Changing the return type of the array to not include the keys (but still include the element types) causes Psalm to correctly fail: https://psalm.dev/r/801392876d

[The docs](https://psalm.dev/docs/annotating_code/type_syntax/array_types/#object-like-arrays) seem to suggest that Psalm adds the keys internally, which seems incorrect, as using the literal array without the function call correctly fails: https://psalm.dev/r/4d22ce0e74

This is similar to #4256, but I think it's distinct because it involves incorrect numbers of keys, rather than empty arrays. #4256 happens with literal arrays, whereas this only happens with typed values (literal arrays fail correctly, as seen in https://psalm.dev/r/4d22ce0e74).

**Comment by muglug** [comment]
If you change the return type to one that Psalm recognises as a triple, everything works: https://psalm.dev/r/801392876d
