### ISSUE TITLE
Possible undefined variable not resolved via null coalescing

### ISSUE THREAD

**Issue by simitter** [vimeo/psalm#4260]
If a variable is set in a condition and later passed to a function with a null coalescing fallback for when the variable is not set psalm assumes a mixed type instead of the correct one.

Example:
https://psalm.dev/r/acc418980f

If the variable is set outside the condition to null it works:
https://psalm.dev/r/c4cc70b792

**Comment by muglug** [comment]
Just set the variable to null beforehand: https://psalm.dev/r/7f7c65498e

**Comment by marartner** [comment]
That's the workaround he gave himself, but that doesn't change that psalm isn't working as one would expect.

The null coalescing operator is a shorthand for an `isset`-ternary, which has the exact same problem:

https://psalm.dev/r/9583f4b711

`isset`, by definition, checks not just for null, but also if the variable is defined. Psalm should be able to do handle that.
