### ISSUE TITLE
Templated array-return cannot be matched with @method-phpdoc

### ISSUE THREAD

**Issue by arjenm** [vimeo/psalm#4269]
We started using Psalm a few weeks ago. We have a List-implementation, which I wanted to enhance using templates.

In this List-implementation we have a basic interface, a concrete implementation and lots of subclasses that are basically glorified concrete generics-variants. I.e. a List<SomeClass> has a SomeClassList-class that is mostly phpdoc-sugar to help with @method-annotations for code completion in PhpStorm.

Having added templates to them (if PhpStorm ever adds support for Psalm-templates, we can remove those phpdoc-only implementations) I get most methods working. One I cannot seem to get working is a method that basically returns all contained values as an array.

See this code snippet:
https://psalm.dev/r/5e30f0224c

When adding a repetition of the `@return T[]` in ListImpl, the error goes away.

**Comment by muglug** [comment]
Now fixed
