### ISSUE TITLE
Class 'Composer\XdebugHandler' not found

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [vimeo/psalm#427]
Using psalm I got this error:

```
$ psalm --init
PHP Fatal error:  Uncaught Error: Class 'Composer\XdebugHandler' not found in /psalm/vendor/vimeo/psalm/src/psalm.php:146
Stack trace:
#0 /psalm/vendor/vimeo/psalm/psalm(2): require_once()
#1 {main}
  thrown in /psalm/vendor/vimeo/psalm/src/psalm.php on line 146

Fatal error: Uncaught Error: Class 'Composer\XdebugHandler' not found in /psalm/vendor/vimeo/psalm/src/psalm.php:146
Stack trace:
#0 /psalm/vendor/vimeo/psalm/psalm(2): require_once()
#1 {main}
  thrown in /psalm/vendor/vimeo/psalm/src/psalm.php on line 146
```

The used version of the components are:
```
$ composer show
composer/ca-bundle         1.1.0  Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/composer          1.6.2  Composer helps you declare, manage and install dependencies of PHP projects, ensuring you have the right stack everywhere.
composer/semver            1.4.2  Semver library that offers utilities, version constraint parsing and validation.
composer/spdx-licenses     1.2.0  SPDX licenses list and validation library.
justinrainbow/json-schema  5.2.6  A library to validate a json schema.
muglug/package-versions-56 1.2.3  A backport of ocramius/package-versions that supports php ^5.6. Composer plugin that provides efficient querying for installed package versions (no runtime IO)
nikic/php-parser           v3.1.3 A PHP parser written in PHP
openlss/lib-array2xml      0.5.1  Array2XML conversion library credit to lalit.org
php-cs-fixer/diff          v1.2.0 sebastian/diff v2 backport support for PHP5.6
psr/log                    1.0.2  Common interface for logging libraries
seld/cli-prompt            1.0.3  Allows you to prompt for user input on the command line, and optionally hide the characters they type
seld/jsonlint              1.7.0  JSON Linter
seld/phar-utils            1.0.1  PHAR file format utilities, for when PHP phars you up
symfony/console            v4.0.3 Symfony Console Component
symfony/filesystem         v4.0.3 Symfony Filesystem Component
symfony/finder             v4.0.3 Symfony Finder Component
symfony/polyfill-mbstring  v1.6.0 Symfony polyfill for the Mbstring extension
symfony/process            v4.0.3 Symfony Process Component
vimeo/psalm                0.3.75 A static analysis tool for finding errors in PHP applications
```

**Comment by muglug** [comment]
What's the current working directory you're running Psalm in?

**Comment by MatthiasKuehneEllerhold** [comment]
My project root: "/x/"

**Comment by muglug** [comment]
what OS? also, `src/command_functions.php` contains the code that does the autoloading. Would you mind debugging for me by var_dumping `$autoload_files`?

**Comment by MatthiasKuehneEllerhold** [comment]
I'm using it under Mac OS. 
```
array(2) {
  [0]=>
  string(56) "/project/vendor/autoload.php"
  [1]=>
  string(58) "/x/vendor/autoload.php"
}
```

I thought maybe my projects dependencies were the problem. I've uncommented the code and the error is still thrown. No composer is loaded by my project... but I guess they're not responsible because it still crashed without my autoload.php?!

**Comment by muglug** [comment]
Hmm two different `vendor/autoload.php` files is definitely unexpected. Your project doesn't use composer at all?

Would it be possible for you to create a small repo that exhibits the same behaviour?

**Comment by MatthiasKuehneEllerhold** [comment]
Sorry I found the culprit...

I'm using tools & analyzers (like psalm and phpstan) in a non-traditional way: 
I don't add them to the require-dev them in my projects `composer.json`. Instead they are getting a separate directory with their own `composer.json` and symlink their executables into my $PATH. This way I can install these tools globally in their own isolated environment. Sort of like PHIVE does things with PHAR (but less sophisticated).

Psalm loads both composer autoloaders and somehow the second one is being forgotten (why though?). If I'm adding psalm to my project require-dev (as your README.md states!) everything works fine.

So I'm sorry for my non-standard way! I'd like to make an request thought: can you add PHIVE-support to psalm? Or can we fix the problem with a semi-global installation somehow?

**Comment by muglug** [comment]
It should support global installation, though it's not well-tested.

What's Phive?

**Comment by MatthiasKuehneEllerhold** [comment]
Its a way to securely install global tools. Like a package manager (apt-get). It has signature verification etc in it as well. All you have to do is create a PHAR on release and sign it right here on github.

More information at https://phar.io/

**Comment by MatthiasKuehneEllerhold** [comment]
I'm utterly confused now. Deleting both vendor folders and running `composer install` again fixes everything. 
Dont know why that didnt fix things the other 2 times I did it before opening this ticket. I'm terribly sorry for bothering you.

My hope for a phive-compatbile release still stands though :)

**Comment by weirdan** [comment]
I'm facing the same problem with psalm installed with straightforward `composer global require` (after update).

**Comment by MatthiasKuehneEllerhold** [comment]
I've included the version report in my first comment... and sadly composer/composer is listed as version 1.6.2 there. The project's vendor dir has no `composer/composer`, so the correct version should have been loaded.
I cant recreate the buggy version...

**Comment by weirdan** [comment]
1.6.1 -> 1.6.2 update was what broke everything for me, but `dump-autoload` fixed that problem (had to download composer.phar though to do that, as globally installed composer/composer wasn't working for the same reason).

**Comment by MatthiasKuehneEllerhold** [comment]
Huh! I thought the 1.6.2 was supposed to be the fix? Well then! Thanks for clearing that up. Is psalm working for you now?

**Comment by weirdan** [comment]
Yeah, working fine here.
