### ISSUE TITLE
`non-empty-array` should pass at least once in `foreach` loop body

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#4270]
If you have a `non-empty-array` and you loop through it, the body of the `foreach` should be executed at least once.

For example, [this snippet](https://psalm.dev/r/3668a3592c)

```
/**
 * @param non-empty-array $a
 */
function foo (array $a): string {
    /** @var mixed $v */
    foreach ($a as $v) {
        return (string)$v;
    }
}
```

produces a warning `Not all code paths of foo end in a return statement, return type string expected`, but actually that code always work with a non-empty array

**Comment by muglug** [comment]
Only if the `foreach` has no `break` or `continue` statements. IMO it's too much of an edge-case, so I'm going to close. Instead you could rewrite that as https://psalm.dev/r/789fcfdcf4, which (IMO) is preferable.
