### ISSUE TITLE
Detect conditions expressed inside of a switch (true) case

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#4276]
See https://psalm.dev/r/b950a0ca00, it would be a neat feature.

**Comment by danog** [comment]
This could actually be interpreted as a `if (true == ($this->a instanceof a))`, or generally `if (cond == caseLabel)`, psalm doesn't seem to do that.

**Comment by weirdan** [comment]
You're missing a `break;` after `$this->a->testA()` and Psalm is correctly reaching the conclusion that `$this->a->testB()` is reachable from the first case via fall through. Addind the break makes this pass: https://psalm.dev/r/7ff32cc7d4

**Comment by danog** [comment]
Welp my bad, it seems that the actual issue is https://github.com/vimeo/psalm/issues/4279, after all
