### ISSUE TITLE
$this => static cannot be used inside of a conditional template

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#4278]
https://psalm.dev/r/a1d47adbf0.
$this is correctly aliased to static, but then conditional template evaluation fails (the same happens when providing directly static)

**Comment by muglug** [comment]
Again, I'm not going to add this. Just use `instanceof` checks, if you can.

**Comment by danog** [comment]
Hmm, but can I even do that in a conditional template expression?

**Comment by muglug** [comment]
No – it would require Psalm to do the inverse of the conditional return type inference, which is weird and bad.

Put another way, if you can't do it in TypeScript you shouldn't be able to do it in Psalm either.
