### ISSUE TITLE
RedundantCondition when evaluating docblock type after strong type checks

### ISSUE THREAD

**Issue by tvdijen** [vimeo/psalm#428]
ERROR: RedundantCondition - lib/HTTP.php:301:13 - Found a redundant condition when evaluating $retryURL

Edit: shorter testcase
```php
/** @param string|null $bar */
function foo($bar) : void {
    if (!is_null($bar) && !is_string($bar)) {
        throw new \Exception('bad');
    }
    
    if ($bar !== null) {}
}
```

**Comment by muglug** [comment]
Not a false-positive, unless there's code you didn't include.

There's a null check for `$retryURL` at the top of the function.

Properly-formatted:

```php
<?php
function bar() {
	return "hello";  
}
/**
* Check for session cookie, and show missing-cookie page if it is missing.
*
* @param string|null $retryURL The URL the user should access to retry the operation. Defaults to null.
*
* @return void If there is a session cookie, nothing will be returned. Otherwise, the user will be redirected to a
* page telling about the missing cookie.
* @throws \InvalidArgumentException If $retryURL is neither a string nor null.
*/
function checkSessionCookie($retryURL = null)
{
    if (!is_null($retryURL) && !is_string($retryURL)) {
        throw new \InvalidArgumentException('Invalid input parameters.');
    }
    $session = bar();
    if ($session->hasSessionCookie()) {
        return;
    }
    // we didn't have a session cookie. Redirect to the no-cookie page
    $url = bar();
    if ($retryURL !== null) { 
    }
}
```

**Comment by tvdijen** [comment]
Look again...
If it's not null AND not string, an exception is thrown..
After that if-statement, variable $retryURL can still be `null`!

**Comment by muglug** [comment]
Ah, sorry. Shouldn't be looking at code a minute after waking up.

**Comment by tvdijen** [comment]
Good morning :) I thought I was going nuts here :D

**Comment by muglug** [comment]
OK. Psalm is failing to convert a docblock-asserted type into a PHP-asserted type after the input checks.

I'll have a fix tonight, hopefully.

In the meantime you can suppress `RedundantCondition`s in that function for the time being.

**Comment by tvdijen** [comment]
Thanks for your quick response!
We've decided to stick with the .72 release for a while

**Comment by muglug** [comment]
Found [the culprit](https://github.com/vimeo/psalm/commit/693c7a81fafdaf4c939b36c189c6514e128d965a#diff-810ca6a7d560572fbea4e190abd34630), a bugfix that exposed another bug.

**Comment by tvdijen** [comment]
Yes, it got introduced in one of the last releases...
Scrutinizer does some caching, so I'm not sure if it was the last release but to us the error occurred over night.

**Comment by muglug** [comment]
Should be fixed now. Let me know if you run into more issues.

**Comment by tvdijen** [comment]
Thanks very much!
We’ll give it a shot as soon as you tag a new release

**Comment by muglug** [comment]
A new release was tagged at least 200 seconds ago, please keep up...
