### ISSUE TITLE
Psalm not checking properties for abstract classes as for traits

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#4280]
https://psalm.dev/r/7c47a1d8bd

Psalm correctly checks all classes where traits are included, to make sure all properties and methods used in those traits are indeed present in the classes that use those traits (and this is an extremely useful feature, thank you for this).

However, it doesn't do the same for abstract classes, it would be nice if it did that, too.

**Comment by muglug** [comment]
This is by design. Traits are always analysed in the context of a place they're used, but abstract classes must define symbols they reference.

**Comment by danog** [comment]
Hmmm, OK then, thanks anyway!
