### ISSUE TITLE
Discussion: consider allowing class-strings for calls to defined or function_exists

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#4281]
https://psalm.dev/r/87807db16f

When checking for the existence of namespaced functions or constants, it is often more convenient to use a class-string, instead of a normal string literal (where you would have to escape backslashes, and possibly type in the whole namespace).

It would be nice if psalm didn't check for the existance of classes in class-strings, if that class-string is directly passed to `defined`, `function_exists` or `define`.

**Comment by muglug** [comment]
Nope, sorry.
