### ISSUE TITLE
Integer and string addition inferred as float

### ISSUE THREAD

**Issue by NickMolloy** [vimeo/psalm#4282]
https://psalm.dev/r/cb82de25fe

I would expect the type to be inferred as `int|float`.

**Comment by muglug** [comment]
I think this is just in master, but I may be wrong.

**Comment by NickMolloy** [comment]
I have bisected this to 29efab5cc2235f066f5f59f5dfe7a931ee76c278
I am able to reproduce it on 3.16

**Comment by muglug** [comment]
Fixed in 443025eab8f3028a95e355856469b887466b4d92
