### ISSUE TITLE
Typing callable assignment

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#4283]
If I write

```
/**
 * @param int $x
 * @return int
 */
$foo = fn ($x) => $x;
```

(see https://psalm.dev/r/4576bdb63b), the callable does not receive the provided typing.

Everything works fine if I do

```
$foo = (
    /**
     * @param int $x
     * @return int
     */
    fn ($x) => $x);
```

but that's counterintuitive to write.

It would be nice if the above syntax worked.

**Comment by muglug** [comment]
That won't ever work, sorry.
