### ISSUE TITLE
False positive array_multisort for list<int> in 3rd argument

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#4285]
https://psalm.dev/r/8242e51491

**Comment by orklah** [comment]
This seems to be a legitimate issue but Psalm is very bad at displaying it.

The fact that your type $foos has it's offset y optional makes Psalm infer the resulting type as a `list<int>` with the flag `possibly_undefined`. I think this would be better to directly makes an optional key translate to null in the result of array_column but I will need to perform some tests before that
