### ISSUE TITLE
question: param that understands phpstorm and psalm

### ISSUE THREAD

**Issue by timglabisch** [vimeo/psalm#4296]
it it possible to define `@param` in a way that phpstorm understands, that the collection is iterable and let psalm know, what type it is?

https://psalm.dev/r/6d888e91c8

line 21 in the example.

**Comment by orklah** [comment]
This is out of scope for psalm directly. However, Jetbrains is working on a solution for PHPStorm: https://github.com/JetBrains/phpstorm-psalm-plugin

It's still in active development and should be available on a future EAP (probably in a few weeks).

**Comment by muglug** [comment]
Yeah, as above

**Comment by timglabisch** [comment]
just for the case someone has the same question - here is an updated example that works:

https://psalm.dev/r/bb3dd6bdde
