### ISSUE TITLE
Type assertion not working, when accessing property through getter

### ISSUE THREAD

**Issue by tunterreitmeier** [vimeo/psalm#4298]
Snippet: https://psalm.dev/r/a5fede578c

I get a false positive PossiblyNullReference when using a getter method with an assertion on the corresponding property.
This is not the case, when using the property directly.

memoizeMethodCallResults does not change this effect.

Am I missing something?

P.S. Thank you so much for making this open source - I love this project!

**Comment by muglug** [comment]
For the assertion to be useful you have to call the method on the property directly: https://psalm.dev/r/9deea40fa3. You can also, with `memoizeMethodCalls`, use this formulation: https://psalm.dev/r/8e49e66212
