### ISSUE TITLE
Laravel support

### ISSUE THREAD

**Issue by szepeviktor** [vimeo/psalm#430]
When trying to run psalm on an empty `laravel/laravel:5.5.*` there are stange errors:

```
INFO: PropertyNotSetInConstructor - app/User.php:8:20 - Property App\User::$connection is not defined in constructor of App\User or in any private methods called in the constructor
class User extends Authenticatable
```

`App\User::$connection` does not seem to be reasonable.
 
Please advise.

**Comment by muglug** [comment]
> `App\User::$connection` does not seem to be reasonable.

What do you mean by reasonable?

**Comment by szepeviktor** [comment]
I couldn1t find a reference to it in Laravel/dependencies.

**Comment by muglug** [comment]
It's defined in `Illuminate\Database\Eloquent\Model`

**Comment by szepeviktor** [comment]
Thank you.
So technically it should set every property.

Could it be that it is done in a Facade/magic method?

**Comment by muglug** [comment]
I think it's *unlikely* that a `Illuminate\Database\Eloquent\Model` (which `User` extends) will ever have a null `$connection`, as it seems to be set in `->setConnection` in most instances of a new object being created.

But Psalm is pessimistic.

**Comment by szepeviktor** [comment]
I see. Thank you for your guidance.
