### ISSUE TITLE
MissingPureAnnotation issues

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#4300]
I ran into some issues while running `--alter --issues=MissingPureAnnotation`. I created a repo to reproduce them:

https://github.com/enumag/psalm-bug-2

```
composer install
vendor/bin/psalm --alter --issues=MissingPureAnnotation --dry-run
```

output:

```
Altering files...
/home/enumag/Projects/enumag/psalm-bug-2/src/index.php:
--- /home/enumag/Projects/enumag/psalm-bug-2/src/index.php
+++ /home/enumag/Projects/enumag/psalm-bug-2/src/index.php
@@ -5,12 +5,15 @@
 final class Arrays
 {
        /**
-        * Lorem ipsum.
+        *       * Lorem ipsum.
+        *       *
         *
         * @param mixed[]                   $array
         * @param Closure(mixed): array-key $callback
         *
         * @return mixed[]
+        *
+        * @psalm-pure
         */
        public static function indexBy(array $array, Closure $callback): array
        {
```

#### 1) Docblock text

As you noticed psalm somehow doubled the whitespace and star before the docblock description.

#### 2) `@psalm-pure` should not be added

Because the `$callback` closure is not pure.

#### 3) Impossible to mark the callback as pure

I want to keep the callback as Closure only and it won't actually be pure. However I tried to mark it a pure anyway using `@param pure-callbable&Closure(mixed): array-key $callback` just to see if it's possible. But then `vendor/bin/psalm` fails with some false-positive:

```
ERROR: InvalidDocblock - src/index.php:11:12 - Intersection types must be all objects or all object-like arrays, Psalm\Type\Atomic\TCallable provided in docblock for Arrays::indexBy (see https://psalm.dev/008)
         * @param pure-callable&Closure(mixed): array-key $callback
```

**Comment by weirdan** [comment]
re: pure param annotation - it should be possible to specify it like this: https://psalm.dev/r/add7ac5ba4

**Comment by enumag** [comment]
I see. That solves the last issue then. Thanks!

**Comment by orklah** [comment]
A lot have changed since then. Could you check if the two first issues are still there?

**Comment by enumag** [comment]
@orklah Even Psalm 4.19 is still trying to add `@psalm-pure` when the closure is not marked as pure.
