### ISSUE TITLE
Taint Analysis File Limits

### ISSUE THREAD

**Issue by bdrodes** [vimeo/psalm#4301]
I'm on Psalm 3.16@d03e5ef057d6adc656c0ff7e166c50b73b4f48f3

Is there a limit on the number of php files I can get `--taint-analysis` to check in a single directory? 

I ran psalm taint analysis on a directory containing ~800 files, it reports 429 go through analysis, and I can verify it is missing seeded vuln files when run on the full directory. The seed files are found individually, however, if I point psalm taint analysis directly to the individual file.

**Comment by bdrodes** [comment]
After some more digging, it seems like the behavior of running psalm on a directory doesn't work like I had hoped. In my tests, sometimes it analyzes nested files, and sometimes it doesn't. The safest bet I can find is running psalm taint analysis on php files one at a time. Is there a better approach than this?

**Comment by bdrodes** [comment]
And now I've managed to make the opposite scenario happen: Running psalm taint analysis on the directory finds a vuln in a nested file, whereas running psalm directly on that file finds nothing.

**Comment by muglug** [comment]
No limit, but the Psalm in general, and its taint analysis in particular, is designed to work on whole projects, not a single shallow directory (unless that's all files in your project).

**Comment by bdrodes** [comment]
The behavior I'm seeing is psalm's taint analysis has different behavior depending on if I point the taint analysis to a directory vs a single file. I've seen cases where it will miss tainted paths in either case. My current solution is to run on the entire directory, then again on each individual file. Is there any reason why running way vs the other would miss tainted paths?

**Comment by bdrodes** [comment]
Ok now I've further seen cases where if I add one file to a directory that has a vuln, the taint analysis won't detect it either way (calling psalm on the vull directory or calling on the individual file) but psalm will detect it when I put back the full directory structure. 

How am I supposed to actually call psalm taint analysis? I clearly must be doing something wrong to get these kinds of inconsistencies. Any help?

**Comment by orklah** [comment]
I think you created https://github.com/vimeo/psalm/issues/5715 for when multiple vuln goes through the same path to sink. This explains what you saw here with Psalm not reporting some paths that are similar to another. I'll close this as duplicate then
