### ISSUE TITLE
Trait using templates where the type can get inferred from the provided callback.

### ISSUE THREAD

**Issue by jsiefer** [vimeo/psalm#4304]
Given the following code: https://psalm.dev/r/c49b8c8b2a

I think I got it right, I would not expect an error, but I get:

`MixedReturnTypeCoercion - The declared return type 'SomeValue' for LazyIndex::get is more specific than the inferred return type 'TObject:LazyIndex as mixed'`

Is that not supported or am I missing something else here?

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/8c0115657f

**Comment by muglug** [comment]
This is now fixed
