### ISSUE TITLE
Why Psalm did not infer types?

### ISSUE THREAD

**Issue by XedinUnknown** [vimeo/psalm#4305]
Hi! I have set `errorLevel` to `1` in my package [`dhii/collections-interface`][]. AFAIK deps are resolved automatically from vendor libs with Composer autoloader. And yet, Psalm says that it is unable to infer types. When I run it locally with `--debug` I see that it does scan the `psr/container` classes.

How can I see why Psalm is unable to infer types?

[`dhii/collections-interface`]: https://github.com/Dhii/collections-interface/runs/1235075432?check_suite_focus=true

**Comment by XedinUnknown** [comment]
Cannot really reproduce, because it is related to vendor libs.

**Comment by XedinUnknown** [comment]
Could it be because there aren't any executable lines of code?

**Comment by XedinUnknown** [comment]
Oh, I meant to include a link to the build. Without it, I quite understand the confusion. Updated original comment with link. Sorry about that!

What I was expecting it to do is to infer the types from method signatures, inheritance trees, `@throws` tags, etc. There are no executable lines of code because this package only holds interop interfaces.

**Comment by orklah** [comment]
Oh, I see. I think Psalm only use expressions when it count the types. If the package only contains interfaces, there's no expressions to analyse

**Comment by XedinUnknown** [comment]
Oh. I didn't know that. I would assume that if I have `InterfaceA::doThing(InterfaceB $subject)`, it would have to resolve `InterfaceB`. In fact, it used to report `UnusedClass` issues for those interfaces (duh), and `InvalidThrow`, although I can no longer get it to report the latter.

Could you (or someone else) kindly confirm that code must be executable in order to be analyzed?

**Comment by orklah** [comment]
That's not what I said :) Your code is analyzed, there's just no expressions that's counted for the report at the end.

**Comment by XedinUnknown** [comment]
Well, if the `@throws`, `return`s, params, inheritance etc are not analyzed, then what is being analyzed?

**Comment by muglug** [comment]
Why do you have that `<extraFiles>` thing in your config?

**Comment by XedinUnknown** [comment]
[Not anymore][1]. I had been under the impression that `vendor` needs to be added too. It's how you do it with e.g. Phan: you add files where it should look, such as the `vendor` and `src` dirs, and then exclude what it should not analyze, such as `vendor`. I understand that with Psalm, this is not necessary.

[1]: https://github.com/Dhii/collections-interface/blob/task/add-clearable-container/psalm.xml.dist

**Comment by muglug** [comment]
This codebase is just comprised of interfaces. Psalm tells you about types it can infer, but there's nothing to infer (because there are no expressions).

**Comment by XedinUnknown** [comment]
Ok, so just to be clear: Psalm can only analyze expressions, and even if one interface depends on another in its method's signature, that will not be analyzed unless there are implementing objects interacting. Right?

**Comment by orklah** [comment]
> Ok, so just to be clear: Psalm can only analyze expressions, and even if one interface depends on another in its method's signature, that will not be analyzed unless there are implementing objects interacting. Right?

No. Psalm analyze everything it can. For example, this is what incompatible interfaces show in Psalm:
https://psalm.dev/r/f21f55d68b

BUT, there is a counter at the end that counts the number of expressions where Psalm was able to infer the type. Given there's no expression, Psalm tells you it wasn't able to infer types. It doesn't mean Psalm did nothing, It just means that the metric Psalm uses for this specific counter is useless for your repository. Just look at the other metrics (the main one being the number of errors)

**Comment by XedinUnknown** [comment]
Oh, I see! That makes sense now. Thank you!
