### ISSUE TITLE
Typing a dependency injection container

### ISSUE THREAD

**Issue by ChristophWurst** [vimeo/psalm#4310]
Hello :wave:,

I'm in the process of rolling out Psalm for more components of the Nextcloud ecosystem and I came to the following problem. If you have a dependency injection container, it would be really cool to let Psalm know the container returns an instance of the class string passed as identifier, though containers might also work with regular strings as service identifications.

Sample code: https://psalm.dev/r/f4113ff8b9

If I limit the container interface to only work with class strings, then the typing is easy: https://psalm.dev/r/b86ac518bd. But in practice you have some named services where the string is not actually a class string but just a literal.

Does Psalm automatically use the *class string* as more specific type? It looks like the union type with `string` has no effect except eliminating the error `Argument 1 of f expects class-string, parent type string(...) provided`. Therefore it still complains about every service that is queried by name instead of class name like `Class or interface hello does not exist` in the example above..

Unfortunately I could not find any other container implementation that uses psalm typing.

Are there any tricks to make this work?

What I'm trying to tell Psalm is
* If it's a class name then an instance of `T` is returned
* Fall back to `mixed` in any other case

**Comment by EvgeniiR** [comment]
Looks like conditional types( https://psalm.dev/docs/annotating_code/type_syntax/conditional_types/ ) should help here, but I'm not sure how to correctly tell psalm to allow just string as param https://psalm.dev/r/fb3073f1f0

**Comment by ChristophWurst** [comment]
Thanks a lot for the tip with the conditional types! I learned something new today :)

> but it works well if pass an argument as a variable https://psalm.dev/r/6cee64fd5e
> Is this a bug similar to what happened with callables

Indeed it works with variables but problems show as soon as literals are used: https://psalm.dev/r/5008a6ddb5.

**Comment by orklah** [comment]
This seem to work better:
https://psalm.dev/r/b4cdb6c683

**Comment by ChristophWurst** [comment]
> This seem to work better:

Thanks for looking into it but then there is no type information on the returned object. Psalm will treat it as `object` and not an instance of the type that is passed as argument. Which means I need to add a typedoc for every usage of the container method.

But with this new hint of `$name is class-string` I got it to: https://psalm.dev/r/30724e7f25. So from that snippet I would say that the conditional type does not work as expected. But I'll keep digging and experimenting.

**Comment by ChristophWurst** [comment]
@muglug you're amazing. Thanks a lot for the quick fix :raised_hands:.

**Comment by muglug** [comment]
You're welcome!
