### ISSUE TITLE
Template annotation for all of same-type in a list?

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#4316]
Hey there,

is there a way to tell psalm that a list of values should contain only values from the same type while templating?
Lets take for example a "list of integers":

https://psalm.dev/r/0bb1f26f28

Thought of something like:

```php
/**
 * @template TValue of same-type
 * @psalm-param list<TValue>
 */
public function __construct(array $foo)
{
}
```

Is there something to achieve this?
Sure, I could use inline-annotations or create a decorator for the `Collection` where I annotate `/** @var Collection<int> */` but wondering if there is another way.

**Comment by muglug** [comment]
No, unfortunately there’s no way without annotations. If PHP added explicit generics in the language then this would work fine:

```
$integers = new Collection<int>([1, 2, 3]);
$integers->add(4);
```
