### ISSUE TITLE
Cannot call an possibly-mutating method DateTimeInterface::format from a mutation-free context

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#4318]
https://psalm.dev/r/6a354b784b

**Comment by jakespencer** [comment]
Unfortunately seems really problematic to use the mutation free annotation https://psalm.dev/r/d3f2880bd9

**Comment by orklah** [comment]
We would need stubs for these two classes and a mutation free annotation on them. Please propose a PR :)
