### ISSUE TITLE
Wrong type inference

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#4326]
Consider this snippet of code (see https://psalm.dev/r/422d9413c9)

```
/**
 * @template S
 * @template T
 * @template A
 * @template B
 */
final class Prism
{
	/** @var callable(B): T */
    private $review;

    /** @var callable(S): Either<T, A> */
    private $preview;

    /**
     * @template C
     * @template D
     * @param Prism<A, B, C, D> $that
     */
    public function compose(Prism $that): void
    {
        /** @psalm-trace $preview */
        $preview = $that->preview;
    }
}
```

Psalm says that the type of `$preview` is `callable(C): Either<D, C>`, while I'm expecting it to be `callable(A): Either<B, C>`.

Am I doing something wrong or is Psalm inferring the wrong type here?

**Comment by muglug** [comment]
Reduced to https://psalm.dev/r/565bb30e0b

**Comment by muglug** [comment]
Ah, I just fixed it for methods

**Comment by marcosh** [comment]
that was fast, thank you!
