### ISSUE TITLE
TypeDoesNotContainType: Cannot resolve types for this->b with type int and !isset assertion

### ISSUE THREAD

**Issue by Legion112** [vimeo/psalm#4335]
https://psalm.dev/r/19f496a39e

**Comment by Legion112** [comment]
I think I can rewrite it in another way.
https://psalm.dev/r/aa2bed3c54

**Comment by muglug** [comment]
Yup, that's the way to do it!

Psalm assumes that all non-nullable properties are assigned in the constructor.
