### ISSUE TITLE
Null coalescing assignment operator behavior

### ISSUE THREAD

**Issue by drupol** [vimeo/psalm#4336]
Context: https://psalm.dev/r/8e514bf011

Trying to fix the `UnusedVariable` (INFO: UnusedVariable - 31:17 - Variable $callable is never referenced).

When replacing at line 31 `$callable ??=` with `$callable = $callable ??` the error is gone.

However, the Null coalescing assignment operator should behave the same.

**Comment by muglug** [comment]
Simplified to 
```php
function foo (?bool $b, bool $c): void {
    $b ??= $c;
    echo $b;
}
```

**Comment by drupol** [comment]
Nice! https://psalm.dev/r/477a83bbd5

**Comment by drupol** [comment]
Thanks!
