### ISSUE TITLE
Cannot assert parameter to be template container of other parameter

### ISSUE THREAD

**Issue by ChristophWurst** [vimeo/psalm#4339]
Hello.

I'm trying to Psalm-type an API of an event dispatcher where you pass the event class as class-string as well as the listener as class-string. The listener is a template class with the event as template argument.

I simplified the example into a container that wraps an element and wrote this snippet: https://psalm.dev/r/49995ab4a2

The goal is to assert that the `$container` argument of `wrap` is a `Container<T>` and not a `Container<object>` but it looks like Psalm does not bother mixed template types. See the last line.

Is this a limitation of how far Psalm can work with the type system or am I doing something that is not solvable by types?

PS: if anyone has a better title, shoot.

Cheers :v:

**Comment by weirdan** [comment]
I think something like this should work: https://psalm.dev/r/f407561f3e (but doesn't).

**Comment by muglug** [comment]
I don't think that's really possible, though I could see this being supported: https://psalm.dev/r/07d0b932d5

**Comment by ChristophWurst** [comment]
> I don't think that's really possible, though I could see this being supported: https://psalm.dev/r/07d0b932d5

Yeah, to be honest I wasn't quite sure if the type system would allow this, given that there might be some tricky edge cases.

> though I could see this being supported: https://psalm.dev/r/07d0b932d5

Interesting approach, though it wouldn't help with the functions I'm typing right now as I can't change their signature because they are part of a stable API.

I'm fine with closing this, just figured it might be worth reporting in case it's a bug :)

**Comment by ChristophWurst** [comment]
Loading https://psalm.dev/r/49995ab4a2 with 4.9.2 gives me

> ERROR: InvalidArgument - 37:1 - Incompatible types found for T

so this "feature" now works :rocket:
