### ISSUE TITLE
`@template-implements SomeInterface<T>` does not work if `SomeInterface` is implemented through a grandparent of a class

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#4341]
## Background

We have to deal with some terrible code that does something like:

 * `SomeEvilFramework\SomeLibrary\CollectionType`
 * `SomeSillyAdapter\SomeEvilFramework\AnotherWeirdCollection extends SomeEvilFramework\SomeLibrary\CollectionType`
 * `PoorBastardDealingWithThis\MyHttpAdapter\Collection extends SomeSillyAdapter\SomeEvilFramework\AnotherWeirdCollection`

Why?

![(JPEG Image, 326 × 155 pixels)](https://user-images.githubusercontent.com/154256/96147652-cccb5f00-0f07-11eb-8455-b5838da88612.jpeg)

We're trying to beat some type-fu into this mush.

## `Traversable` cannot be concertized when parent classes implement it

Given following snippet (https://psalm.dev/r/f2934e2db1):

```php
<?php

class Bar implements \Traversable
{
}

/**
 * @template-implements \Traversable<int, non-empty-string>
 */
class Foo extends Bar implements \Traversable 
{
}

foreach (new Foo() as $bar) {
    /** @psalm-trace $bar */
}
```

The type of `$bar` cannot be inferred, because `Bar` defines no template parameters for `Traversable`, while `Foo` does:

```
INFO: Trace - 15:0 - $bar: mixed
```

If we remove `implements \Traversable` from `Bar`, then it works (https://psalm.dev/r/ece146fa86)

```php
<?php

class Bar
{
}

/**
 * @template-implements \Traversable<int, non-empty-string>
 */
class Foo extends Bar implements \Traversable 
{
}

foreach (new Foo() as $bar) {
    /** @psalm-trace $bar */
}
```

Infers:

```
INFO: Trace - 15:0 - $bar: non-empty-string
```

Since `Traversable` is a bit of an oddball in PHP's ecosystem, I made a smaller reproducer with just some "simple" inheritance:

```php
<?php

/** @psalm-template T */
interface Gimme { 
    /** @psalm-return T */
    function thing(); 
}

class Foo implements Gimme
{
    function thing() { return 1; }
}

/** @template-implements Gimme<string> */
final class Bar extends Foo implements Gimme
{
    function thing() { return 'a string'; }
}

$value = (new Bar())->thing();

/** @psalm-trace $value */
```

https://psalm.dev/r/a99948f384

As soon as you remove the inheritance, `/** @template-implements` seems to have an actual effect:

```php
<?php

/** @psalm-template T */
interface Gimme { 
    /** @psalm-return T */
    function thing(); 
}

class Foo implements Gimme
{
    function thing() { return 1; }
}

/** @template-implements Gimme<string> */
final class Bar implements Gimme
{
    function thing() { return 'a string'; }
}

$value = (new Bar())->thing();

/** @psalm-trace $value */
```

https://psalm.dev/r/a724942e43

**Comment by muglug** [comment]
I don't really thing that's a bug – why can't you do this: https://psalm.dev/r/9f66bf9f35

I'm not sure any other language would allow you to get away with that

**Comment by Ocramius** [comment]
@muglug the problem here is that intermediate inheritance levels do not have any type declaration for the templated type `Traversable`, as they come from third party components.

**Comment by muglug** [comment]
I'd just stub them, then – I don't see any value in allowing (what I _think_ is) a bastardisation of inheritance rules.

**Comment by muglug** [comment]
What you're trying to do in effect is

```
interface A<T> {}
class AMixedClass implements A<mixed> {}
class AStringClass extends ParentClass implements A<string> {}
```

and I don't think that's kosher

**Comment by Ocramius** [comment]
Makes sense, thank you!
