### ISSUE TITLE
Problem with templated return types instantiating new objects

### ISSUE THREAD

**Issue by poolsimon** [vimeo/psalm#4342]
I experience an issue with running psalm on this code. 
```
<?php
/**
 * Class App
 * @template TPL_Config of Config
 */
class App {

	/** @psalm-var TPL_Config */
	private $oConfig;

	public function __construct(){
		$this->oConfig = $this->createConfig();
	}

	/** @psalm-return TPL_Config */
	public function createConfig() : Config{
		return new Config();
	}
}
```
It results in those errors:

```
ERROR: InvalidReturnType - src/Psalm/App.php:17:20 - The declared return type 'TPL_Config:Rentman\Core\Psalm\App as Rentman\Core\Psalm\Config' for Rentman\Core\Psalm\App::createConfig is incorrect, got 'Rentman\Core\Psalm\
Config' (see https://psalm.dev/011)
        /** @psalm-return TPL_Config */

ERROR: InvalidReturnStatement - src/Psalm/App.php:19:10 - The inferred type 'Rentman\Core\Psalm\Config' does not match the declared return type 'TPL_Config:Rentman\Core\Psalm\App as Rentman\Core\Psalm\Config' for Rentman\C
ore\Psalm\App::createConfig (see https://psalm.dev/128)
                return new Config();
```

The errors occur on methods instantiating a new object and returning it, on methods with a templated return type. It seems similar to https://github.com/vimeo/psalm/issues/1929 alltough our use case is very different. I could also not get a workaround to solve this. 

This is a frequent use case, in subclasses of this methods a subtype of Config will be returned, containing specific logic. This seems to me like a bug, since type expected and the actual type is the same. Is there any type safe workaround and is this indeed a bug?

**Comment by poolsimon** [comment]
Yes, https://psalm.dev/r/a8696d9073

**Comment by muglug** [comment]
This is not a bug – Psalm is telling you that you’re not actually returning a templated type from that function

**Comment by poolsimon** [comment]
Can you explain why, because the type I return is of the right. When I make the class abstract and do not actually return, but return in an templated subtype:

Works: https://psalm.dev/r/df87bf82f1
Does not work: https://psalm.dev/r/051c4a5e38

I don't see why the second one, where I return an object does not work. This is a common pattern where the parent class returns a object, but a subclass can extend it and returns a subclass of the return type. 

If it is not right, how is the correct way to type it in this example?

**Comment by andyg0808** [comment]
I think I can explain. Imagine you have another config class like this:
```php
class OtherConfig extends AbstractConfig{}
```
Now, if you have
```php
/**
 * @extend AbstractApp<OtherConfig>
 */
class App2 extends AbstractApp{}
```
notice that the returned config for the default `createConfig()` isn't an instance of `OtherConfig`. It's an instance of `Config`, even though the types promise that `createConfig()` always returns an instance of the parameterized type or a subtype of it. That's why Psalm doesn't let you write the version that returns a subtype of the generic type: because it violates the commitment the types make.
