### ISSUE TITLE
Psalm does not understand nested generics

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#4346]
Consider this snippet of code https://psalm.dev/r/227fe39334

I would expect to work correctly since both `left` and `right` produce generic results.

Instead Psalm gives me the following error message

```
The declared return type 'Either<Either<D:fn-foo as mixed, E:fn-foo as mixed>, C:fn-foo as mixed>' for foo is incorrect, got 'Either<Either<empty, E:fn-foo as mixed>, empty>'
```

Am I missing something?

**Comment by muglug** [comment]
> Am I missing something?

Yup. You have a bunch of functions where you're not passing Psalm enough information for it to be able to infer generic params e.g.

```
/**
 * @template C
 * @template D
 * @template E
 * @param E $e
 * @return Either<Either<D, E>, C>
 */
function foo($e)
{
	return Either::left(Either::right($e));
}
```

How can it figure out the value of `C` and `D`? It doesn't let templated parameters bleed out of a function, so it guesses (often inaccurately).

This is a by-product of PHP not supporting generics properly – there's no way of passing the correct params explicitly.

The Hack equivalent of this code (with all params explicit) looks like this:

```hack
final class Either<TA, TB>
{ 
    private function __construct(
        private bool $isRight,
        private ?TA $leftValue = null,
        private ?TB $rightValue = null)
    {
    }

    public static function left<TC, TD>(TC $value): Either<TC, TD>
    {
        return new self(false, $value);
    }

    public static function right<TC, TD>(TD $value): Either<TC, TD>
    {
        return new self(true, null, $value);
    }
}

function foo<TC, TD, TE>(TE $e) : Either<Either<TD, TE>, TC>
{
    return Either::left<Either<TD, TE>, TC>(Either::right<TD, TE>($e));
}
```

**Comment by marcosh** [comment]
Thanks for the reply and the explanation.

It looks like rewriting the `foo` function as

```
/**
 * @template C
 * @template D
 * @template E
 * @param E $e
 * @return Either<Either<D, E>, C>
 */
function foo($e)
{
    /** @var Either<D, E> */
    $eitherDE = Either::right($e);
    
    return Either::left($eitherDE);
}
```

everything works correctly.

> How can it figure out the value of `C` and `D`? It doesn't let templated parameters bleed out of a function, so it guesses (often inaccurately).

I would expect Psalm to accept the fact that at this point it is not able to decide what `C` and `D` are, keep them generic, and assign a value to them only when the `foo` function is actually used.

The expression `Either::left(Either::right($e))`, where `$e` has type `E`, should be a valid value of type `Either<Either<D, E>, C>` for any possible choice of `C` and `D`.
