### ISSUE TITLE
Psalm does not recognize check on array key existence

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#4347]
Consider this snippet of code https://psalm.dev/r/a2bb6bbf43

If I remove the checks on `$a['baz']`, then Psalm detects correctly that `$a['foo']` and `$a['bar']` are present. With the checks on `baz` present, it states that `$a['foo']` and `$a['bar']` could be undefined

**Comment by muglug** [comment]
OK, more clearly: https://psalm.dev/r/01eae6d98e

**Comment by muglug** [comment]
Ah, this was just a good ol' combinatorial explosion issue.
