### ISSUE TITLE
Add types to object properties that lack them where possible

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#435]
Using Psalter this shouldn't be too difficult

```php
class A {
  public $foo;

  public function __construct(string $foo) {
    $this->foo = $foo;
  }
}
```

to 

```php
class A {
  /** @var string */
  public $foo;

  public function __construct(string $foo) {
    $this->foo = $foo;
  }
}
```

**Comment by iluuu1994** [comment]
With typed properties coming in PHP 7.4 this seems unnecessary.

**Comment by muglug** [comment]
Why?

**Comment by iluuu1994** [comment]
Sorry, I misunderstood the issue. I thought it was about inferring the property. This seems like a good idea, for PHP 7.4 you could even add the native property type if possible.

**Comment by orklah** [comment]
Awesome!
