### ISSUE TITLE
Named types [feature request]

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#4351]
Hi,

I love being able to give a list of possible strings as a type:

```php
/**
 * @param 'a'|'b' $s
 */
```

However I would like to suggest an improvement.

I'm working on a rather large codebase where a lot of code deals with strings that can only be one of a constant set of values,  such as a list of ISO country codes. **I would love to be able to give this list of possible strings a given name.**

**An example:** I work with a list of supported ISO country codes ('US', 'GB', 'FR', etc.), and a list of supported Amazon regions ('com', 'co.uk', 'fr', etc.). These codes are hardcoded and very rarely change. When I refactor some code to accept a country code instead of an Amazon region, I'd like Psalm to warn me if I made a mistake somewhere, such as passing an Amazon region where I should be passing a country code.

My idea would be to define named types in the config, such as:

```
amazonRegion = 'com'|'co.uk'|'fr'
supportedCountryCode = 'US'|'GB'|'FR'
```

And use them just like any other type, with a syntax such as:

```php
/**
 * @psalm-param {amazonRegion} $region
 */
function doSomething(string $region) {}

doSomething('com'); // pass
doSomething('US'); // fail
```

**Is this something possible?**

Note that to be really useful, this should properly handle subsets as well, for example given the following types:

```
supportedCountryCode = 'US'|'GB'|'FR'
countryCode = 'US'|'GB'|'FR'|'CA'|'DE'|'ES'|'IT'
```

...a function accepting a `countryCode` should accept a `supportedCountryCode`, but the other way around.

**Comment by weirdan** [comment]
https://psalm.dev/r/824487bbde

**Comment by weirdan** [comment]
https://psalm.dev/r/824487bbde

**Comment by BenMorel** [comment]
Oh, wow ❤️ I'm sorry I missed this!

Can you please point me to the relevant docs? Can't even find it when googling for ["psalm-type"](https://www.google.com/search?q=%22psalm-type%22)!

**Comment by weirdan** [comment]
Of course, here it is: https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-type
Be sure to also check out the section after that, it shows how to import types from other files.

**Comment by BenMorel** [comment]
Thanks a lot, @weirdan. Psalm is amazing :+1:
