### ISSUE TITLE
[Idea] Allow traits to impose requirements on using class

### ISSUE THREAD

**Issue by NiclasvanEyk** [vimeo/psalm#4356]
It would be really helpful for traits to be able to define a set of requirements, that the classes that use these traits need to fulfill. 

## Motivation

Often times, traits are created to be used by a single class or interface, like the [`InvalidCodeAnalysisTestTrait`](https://github.com/vimeo/psalm/blob/master/tests/Traits/InvalidCodeAnalysisTestTrait.php) from psalms own test suite. Among others, this trait requires an `addFile` method to be present on the using class, but this requirement is not being statically enforced or explicitly mentioned anywhere. 

One could make the effort of defining _all_ of such requirements as abstract methods, but this could be a lot of work. On top of that it introduces duplication, as one has to change these abstract methods, when the corresponding methods from the class for which the trait was created changes. If the signature of [`TestCase::addFile`](https://github.com/vimeo/psalm/blob/37ab91aa25d6312d058878cc76f697593eb3364c/tests/TestCase.php#L84) changes, and we would have defined this requirement in the `InvalidCodeAnalysisTestTrait`as an abstract method, this abstract method would also have to be updated.

As an added benefit, these requirements would enable IDEs to provide auto-completion for the methods that the trait depends on.

With this issue I just wanted to start the discussion and maybe get an idea on how likely it is to get implemented some day.

## Examples from other languages

- [Hacks `require extends` and `require implements`](https://docs.hhvm.com/hack/classes/trait-and-interface-requirements#traits). The documentation provides some good examples. The terminology used there is the same as in the following potential implementation example.
- [Dart Mixins and the `on`-keyword](https://dart.dev/guides/language/language-tour#adding-features-to-a-class-mixins). Darts `mixin`s are very similar to PHP, but support an `on` keyword, which allows for restricting the types of classes that the mixing can be used with.

## Potential implementation

This scenario is inspired by the [`SoftDeletes`-trait](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/SoftDeletes.php) from [Laravel](https://laravel.com/docs/8.x/eloquent#soft-deleting). The `@psalm-require-extends`-annotation is an example syntax for how to define the requirements that a trait imposes on the using class.

```php
abstract class DatabaseModel {
  // methods, properties, etc.
}

/**
 * @psalm-require-extends DatabaseModel
 */
trait SoftDeletingTrait {
  // useful but scoped functionality, that depends on methods/properties from DatabaseModel
}

// ☑️ valid - MyModel extends DatabaseModel and therefore adheres to the requirements 
//            of SoftDeletingTrait
class MyModel extends DatabaseModel {
  use SoftDeletingTrait;
}

// ❌ error - this is still valid in PHP, but is more than likely to result in runtime errors, as the 
//            SoftDeletingTrait depends on methods that not available
class NormalClass {
  use SoftDeletingTrait;
}
```

If you want to be a bit more flexible and do not depend on a _specific_ implementation by a specific class, you could use introduce a `@psalm-require-implements`-annotation and specify that the using class should implement a given interface.

**Comment by weirdan** [comment]
Related: #1194

**Comment by muglug** [comment]
Yeah, this is a much more thorough argument than I provided in #1194 so I'll close that ticket

**Comment by muglug** [comment]
This is done

**Comment by weirdan** [comment]
@janopae as far as I can tell it's already works as described, with the caveat that the trait needs to be used in some class.
