### ISSUE TITLE
UndefinedPropertyAssignment on subclass of stdClass 

### ISSUE THREAD

**Issue by jsiefer** [vimeo/psalm#4357]
Hi
I would not expect an `UndefinedPropertyAssignment` error on a subclass of a `stdClass`.

See https://psalm.dev/r/c39abdac79

**Comment by muglug** [comment]
omg you can extend `stdClass`? Why? Whyyyyyy?

**Comment by jsiefer** [comment]
haha

Believe it or not, but there are sues cases for it. Some domains allow dynamic object structure that can come with predefined values. :)

**Comment by orklah** [comment]
> 
> 
> haha
> 
> Believe it or not, but there are sues cases for it. Some domains allow dynamic object structure that can come with predefined values. :)

Do you have an example? I'm also curious to see why you wouldn't create a dynamic object like 
```
$a = new stdClass();
$a->name = 'test';
```
or another object that don't inherit stdClass.

Do you also declare methods on it?

**Comment by jsiefer** [comment]
No, those object just represent data objects and do contain any methods.

Sometimes a domain/format (in my case PDF file) allows objects (Dictionaries) which can be perfectly represent by a simple object or stdClass. While the PDF specification does declare a mandatory and optional set set of properties, it is not limed to it.

So the directive basically is simple object that can old a arbitrary properties, I still extend the stdClass to get clear naming analogy to the PDF file structure. 

```php
class Dictionary extends \stdClass
{
}
```


Most not all, of more complex fixed structures within a PDF are build on those Dictionaries, and come with some mandatory predefined properties and optional properties.

e.g.
```php
/**
 * @property Outlines $Outlines
 * @property Dictionary $Threads
 * @property Action $OpenAction
 * @property AcroForm $AcroForm
 * @property Metadata $Metadata
 * @property Dictionary $Dests
 * @property Dictionary $Names
 * @property ViewerPreferences $ViewerPreferences
 * @property string $PageMode
 */
class Catalog extends Dictionary
{
    /** @var string */
    public $Type = '/Catalog';

    /** @var string */
    public $Version = '/1.4';

    /** @var Pages */
    public $Pages;

    /** @var string */
    public $PageLayout = PageLayout::SINGLE_PAGE;
}
```

In this example for a Catalog, which basically simple object, that has a view mandatory and optional properties, but could also have properties that are not listed (e.g. part of future feature sets).  Please don't mind the uc_first property names, that is just another PDF thingy.

There are other business domain that also allows similar data structures, and ideally you give those objects a meaningful name corresponding with the domain, instead of just using a meaningless stdClass that you can not properly typehint :)

**Comment by orklah** [comment]
Yeah, I get why you would need an object with arbitrary property, but does your use case break if you just remove the stdClass inheritance? Basically, every object could fit. The only case I could see, it's the case where a library expect an stdClass and nothing else(for example, defined in param type hint), but this would be extremely tricky from the library...

**Comment by jsiefer** [comment]
I am not quite following you @orklah sorry

Do you mean remove the `stdClass` inheritance and just use `stdClass` object throughout the code? 
 - I like to use unambiguous objects and names. 

Or

Remove the stdClass inheritance and only use the class? 
- Then I get `UndefinedPropertyAssignment` issues.

or did you mean something else :)

**Comment by orklah** [comment]
I meant the second option, but I don't get why you would get UndefinedPropertyAssignment if you declared your property in advance.

Unless you want to have named objects AND dynamic properties. In this case, I get it.

If that's so, I'd probably recommend putting all those value objects in the same directory and suppressing this issue with your issueHandler on your config

**Comment by jsiefer** [comment]
Ah okay, now I understand

Well, I think is valid to include the behavior that comes with a stdClass into your domain by extending it. I would even encourage it as a domain might have multiple of those. 

But if that is difficult to do then okay, I'll have to suspend those issues then.

I just saw a valid issue here for me 🙂

**Comment by muglug** [comment]
I think this gets a bit convoluted, but the recent [universalObjectCrates](https://psalm.dev/docs/running_psalm/configuration/#universalobjectcrates) config allows you to define classes that should allow undefined properties
