### ISSUE TITLE
class-string using templates incorrectly reports an error.

### ISSUE THREAD

**Issue by kapitancho** [vimeo/psalm#4359]
https://psalm.dev/r/246da1ff09

There is a template defined for a class and a class-string property that uses the template (e.g. class-string<A>). The constructor receives a parameter of the same type (class-string<A>) but a property type coercion error is being reported when trying to assign to the class property:

ERROR: PropertyTypeCoercion - 18:17 - $this->test expects 'class-string<A:Test as mixed>',  parent type 'class-string<A:Test as object>' provided.

I don't think this makes any sense. There should be no error in this scenario.

**Comment by orklah** [comment]
This should help:
https://psalm.dev/r/2266304964

**Comment by kapitancho** [comment]
The addition of "... of object" helps there but it introduces another problem:
https://psalm.dev/r/1f0808491f

ERROR: RedundantConditionGivenDocblockType - 23:10 - Docblock-defined type object for $result is never falsy
even though A|null COULD be falsy.

**Comment by orklah** [comment]
Yep, this seems like a bug. Psalm sees object|null but considers it can't be falsy:
https://psalm.dev/r/8011c03fd0

**Comment by orklah** [comment]
reduced a little, it even works with false or string '0' :
https://psalm.dev/r/f321b26f76

Seems like any type in a Union with a template of object will be considered truthy
