### ISSUE TITLE
Support PHP 8 Attributes

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#4367]
What checks on attributes would people like to see?

From @weirdan:

> Psalm could check if attributes are used on valid targets (e.g. param attribute used on a property). Also it could validate attribute parameters I think, to prevent runtime errors when attribute is instantiated via reflection.

From @duskwuff:

> If a `ReflectionAttribute` is created through a call to `getAttributes()` with a class name, the return value from `$reflectionAttribute->newInstance()` should be typed as that class. This might be representable through type annotations and templating, but might need some assistance.

> It'd be nice to check that any attributes are valid for instantiation (i.e, the attribute references a real class, and the attribute class has the Attribute attribute with a `TARGET_*` which is consistent with the location of the attribute).

**Comment by kapitancho** [comment]
If a class e.g. Test is used as attribute  #[Test] class OtherClass {}, 
then a check for existence of #[Attribute] on class Test would be nice.

**Comment by muglug** [comment]
> Psalm could check if attributes are used on valid targets

This is done
