### ISSUE TITLE
False positive for InvalidReturnStatement

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#4369]
`3.18.0` incorrect return type errors similar to the ones showed below:

1. `ERROR: InvalidReturnStatement - src/Mailer/Mailer.php:364:16 - The inferred type 'array{headers: string, message: string}' does not match the declared return type 'array{headers: string, message: string}' for Cake\Mailer\Mailer::send (see https://psalm.dev/128)`
https://github.com/cakephp/cakephp/blob/cca0943f1401cecb30e504b4519646fe841c805c/src/Mailer/Mailer.php#L364

2. `ERROR: InvalidReturnStatement - src/Database/Statement/MysqlStatement.php:44:16 - The inferred type 'bool' does not match the declared return type 'bool' for Cake\Database\Statement\MysqlStatement::execute (see https://psalm.dev/128)`
https://github.com/cakephp/cakephp/blob/cca0943f1401cecb30e504b4519646fe841c805c/src/Database/Statement/MysqlStatement.php#L44

**Comment by muglug** [comment]
This is now fixed in master
