### ISSUE TITLE
Always display Trace, even with --show-info=false

### ISSUE THREAD

**Issue by dkarlovi** [vimeo/psalm#4370]
Adding `@psalm-trace` to your code is in special circumstances where you're looking for some info, it's basically an `echo`: you add it, read it, remove it.

Having it be of type `info` is reasonable, but it shouldn't be hidden with the other info because they're not an `echo`. In my case, it was almost impossible to use it since I mark my known issues with `info` and don't hide them to be able to keep track of them, so enabling `--show-info=true` is very verbose for me.

The options, from my POV:

- always show `Trace`, regardless of `--show-info` flag
- make `Trace` some other type, not an info, and then always show it
- show it first / show it last, make it more prominent (least changes, but not as user-friendly)

**Comment by orklah** [comment]
You should be able to put this into the issueHandler:
<Trace errorLevel="error" />
to enable them

Is this okay for you?

**Comment by weirdan** [comment]
This will also make sure CI catches it and reports as error - enforcing `add it, read it, remove it` approach.

**Comment by dkarlovi** [comment]
That's a great idea @orklah! Never occurred to me, but now makes me wonder if that's not actually the correct error level to begin with. Closing here either way.

**Comment by weirdan** [comment]
When it was introduced I suggested INFO so that forgotten `@psalm-trace` wouldn't fail CI builds. After all, it's pretty harmless.

**Comment by dkarlovi** [comment]
I'd argue those **should** fail builds since they're meant for developer consumption. They're basically `var_dump` or `console.log` in a Psalm "runtime", development process artifacts.
