### ISSUE TITLE
UnusedMethodCall false positive with foreach

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#4373]
https://psalm.dev/r/dd77299d18

**Comment by orklah** [comment]
Seems similar to: https://github.com/vimeo/psalm/issues/3625

**Comment by enumag** [comment]
Yeah it's the same problem. My snippet is just a bit cleaner since it doesn't have other issues.

Immutable annotation is not completely necessary. For instance `@psalm-mutation-free` has the same effect.

https://psalm.dev/r/ab4bb38b1e

**Comment by enumag** [comment]
Closing as duplicate of #3625
