### ISSUE TITLE
ParadoxicalCondition when assignment happens inside conditionals

### ISSUE THREAD

**Issue by alecwcp** [vimeo/psalm#4374]
Psalm detects ParadoxicalCondition (and UnusedVariable) but there is no paradox and the variable is used.

https://psalm.dev/r/e23bd1a389

Looks like this is because of the assignment within the conditions, so psalm sees it as 2 comparisons of the same variable with false, but actually the value of the variable changes between the conditionals due to the assignment.

Normally I would be against assignment in conditionals for readability reasons, but In this case it is actually useful for checking multiple formats and stopping and the first that worked.

We can get around this by changing to
```
<?php

function checkDateIsRFC3339(?string $dateString): ?\DateTimeImmutable
{
    if (null === $dateString) {
        return null;
    }

    $date1 = \DateTimeImmutable::createFromFormat(DATE_RFC3339, $dateString);
    $date2 = \DateTimeImmutable::createFromFormat(DATE_RFC3339_EXTENDED, $dateString);

    if (false === $date1 && false === $date2) {
        return null;
    }
    if (false !== $date1) {
    	return $date1;
    }

    return $date2;
}
```

 but if possible it seems that supporting the assignments within the conditionals would be potentially beneficial elsewhere.

**Comment by muglug** [comment]
Here's a better working rewrite (IMO): https://psalm.dev/r/3d21ee76cc

**Comment by muglug** [comment]
Here's a lighter reproducer for the `UnusedVariable` issue

```php
<?php

function foo(string $str): ?int {
    if (!($pos = strpos($str, "a")) && !($pos = strpos($str, "b"))) {
        return null;
    }
    
    return $pos;
}
```

and for the `ParaxodicalCondition`:

```php
<?php

function foo(string $str): ?int {
    if (!$str || (!($pos = strpos($str, "a")) && !($pos = strpos($str, "b")))) {
        return null;
    }
    
    return $pos;
}
```

**Comment by alecwcp** [comment]
Thanks for the improved rewrite @muglug  :+1: 
And also a fix in under 3 hours! Psalm's such a brilliant tool, coupled with such great support too!
