### ISSUE TITLE
Scalar does not contain null with PDOStatement::fetch()

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#4382]
I have the following code:

```php
$statement = $this->pdo->prepare(
    'SELECT activity_id, parent_id, replyCount FROM Comment WHERE id = ? FOR UPDATE'
);

$statement->execute([$commentId]);
$result = $statement->fetch(\PDO::FETCH_ASSOC);

if ($result === false) {
    throw new \DomainException('The parent comment does not exist.');
}

$commentId = $result['parent_id'];

if ($commentId === null) {
    break;
}
```

Psalm complains on the last `if()`:

> ERROR: TypeDoesNotContainNull - src/Domain/Service/CommentService.php:95:21 - scalar does not contain null (see https://psalm.dev/090)
>                 if ($commentId === null) {

Looks like it assumes that `PDOStatement::fetch()` returns `scalar[]` (*pseudo-type, I don't know how Psalm represents types internally*), when it should be `(scalar|null)[]`.

**Comment by BenMorel** [comment]
Reproduce: https://psalm.dev/r/944139eef9

**Comment by DvdGiessen** [comment]
Reproduction without database schema dependency: https://psalm.dev/r/4e8fcd8554

**Comment by BenMorel** [comment]
Strangely, `PDOStatement::fetch()` is annotated as returning `mixed`, not `scalar[]`.  Excerpt from `CallMap.php`:

```php
'PDOStatement::fetch' => ['mixed', 'how='=>'int', 'orientation='=>'int', 'offset='=>'int'],
'PDOStatement::fetchAll' => ['array|false', 'how='=>'int', 'fetch_argument='=>'int|string|callable', 'ctor_args='=>'?array'],
'PDOStatement::fetchColumn' => ['string|int|float|bool|null', 'column_number='=>'int'],
```

How is it possible, @muglug?

**Comment by orklah** [comment]
Probably because of Providers:
https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Provider/ReturnTypeProvider/PdoStatementReturnTypeProvider.php
https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Provider/ReturnTypeProvider/PdoStatementSetFetchMode.php

**Comment by BenMorel** [comment]
Thanks a lot for the pointer, @orklah! I'll PR the necessary changes there.

I didn't know Psalm was able to infer types from this PDO mess. Psalm is incredible! (and so is @muglug 😉)
