### ISSUE TITLE
I can't make PSalm play nicely with WordPress

### ISSUE THREAD

**Issue by andreasciamanna** [vimeo/psalm#4383]
While scanning my codebase (it's a WordPress plugin), I get `Uncaught Exception: Call to undefined function add_action()`.

I know the error is caused by the fact that Psalm doesn't know what `add_action` is (it's a WordPress global function).

Solutions I've attempted:

- Full WordPress stub file taken from [here](https://github.com/php-stubs/wordpress-stubs)
   - Added the following to the configuration file:
      ```xml
      <stubs>
          <file name="vendor/php-stubs/wordpress-stubs/wordpress-stubs.php"/>
      </stubs>
      ```
   - I can see the stub is properly defined:
     ```php
      function add_action($tag, $function_to_add, $priority = 10, $accepted_args = 1)
      {
      }
      ```
- Added the relevant directories to the "extraFiles":
  ```xml
  <extraFiles>
    <directory name="../../../wp-includes" />
    <directory name="../../../wp-admin" />
  </extraFiles>
  ```
- Use both the above (I know, pointless, but who knows?)

None of these solutions seems to solve the problem. The error keeps showing up.

I know I'm missing something, but I don't know what it is.

**Comment by andreasciamanna** [comment]
I know this is a bot, but I suppose I must reply anyway :)

To do that, I need to add the definition of `add_action` which of course, will make the problem disappear.

I'm trying to use the stubs here.

I can't test that in https://psalm.dev

**Comment by muglug** [comment]
@andreasciamanna can you reproduce in a separate repo?

**Comment by andreasciamanna** [comment]
@muglug  I managed to replicate it with [this repo](https://github.com/andreasciamanna/psalm-issue-4383).

Mind that I use psalm as a globally installed package because I can't install it in the original project due to (too many) dependency clashes.

Another note about `psalm.xml`: is configured as such because the original project has more directories to exclude than the ones to include :)

**Comment by andreasciamanna** [comment]
@muglug I've updated the repo by using `humanmade/psalm-plugin-wordpress` (as it's recommended extension) but I get the same results.

**Comment by lib-noah** [comment]
After installing `humanmade/psalm-plugin-wordpress`, have you added the following to your psalm.xml configuration file?

`<plugins>
<pluginClass class="PsalmWordPress\Plugin"/>
</plugins>`

From the [psalm-plugin-wordpress repo](https://github.com/humanmade/psalm-plugin-wordpress/blob/master/psalm.xml.dist)

**Comment by pancheke** [comment]
After installing `humanmade/psalm-plugin-wordpress`, have you added the following to your psalm.xml configuration file?

`<plugins>
<pluginClass class="PsalmWordPress\Plugin"/>
</plugins>`

From the [psalm-plugin-wordpress repo](https://github.com/humanmade/psalm-plugin-wordpress/blob/master/psalm.xml.dist)

**Comment by andreasciamanna** [comment]
To be honest, I don't remember.

That's from more than a month ago and since I was stuck with this issue, I've moved to PHPStan.

I may try experimenting with Psalm again in the future and will check here if I get stuck again.

**Comment by XedinUnknown** [comment]
Hi! I have the same problem. I use `humanmade/psalm-plugin-wordpress`, and I enabled the plugin with `psalm-plugin enable humanmade/psalm-plugin-wordpress`, which added the above mentioned XML in my `psalm.xml.dist`. Then I dumped Composer autoloader, just in case. I still get an error:

```
UndefinedClass - src/Sites.php:42:32 - Class or interface WP_Site does not exist (see https://psalm.dev/019)
        if (!($site instanceof WP_Site)) {
```

**Comment by XedinUnknown** [comment]
Here's what I found after an investigation.

The plugin loads [stub files][1] from `vendor` dir relative to the main plugin file's directory.
If I install the plugin using Composer, then assuming my project root dir is `/app`, it will try to include e.g. `/app/vendor/humanmade/psalm-plugin-wordpress/vendor/php-stubs/wordpress-stubs/wordpress-stubs.php`. Of course, no such path exists, because `php-stubs/wordpress-stubs` will have been installed in `/app/vendor/` rather than `/app/vendor/humanmade/psalm-plugin-wordpress/vendor` - or rather _would_ have been installed that way if `php-stubs/wordpress-stubs` was a `require` dependency of `humanmade/psalm-plugin-wordpress`, whereas it is a `require-dev` dependency and therefore will not be installed at all.

[1]: https://github.com/humanmade/psalm-plugin-wordpress/blob/master/Plugin.php#L52-L53

**Comment by XedinUnknown** [comment]
Looks like the maintainer of the repo is fixing the stuff really quickly. My question, however, is now in the necessity of this particular Psalm plugin.

### Using Plugin
1. Require `humanmade/psalm-plugin-wordpress`.
2. Add `<plugins> <pluginClass class="PsalmWordPress\Plugin"/> </plugins>` to `psalm.xml`.

This simply adds the stubs from `php-stubs/wordpress-stubs` to Psalm.

### Using Stubs
1. Require `php-stubs/wordpress-stubs`.
2. Add `<stubs> <file name="vendor/php-stubs/wordpress-stubs/wordpress-stubs.php" /> </stubs>` to `psalm.xml`.

No intermediate dependency, fewer points of failure.

**Comment by Lukid** [comment]
Hi, I'm trying to run palms on my plugin, but I need to include other plugins (like ACF) as dependencies, otherwise I can't find the functions used.
it's possible ?

**Comment by orklah** [comment]
Please create a new ticket to describe your issue. What do you mean by ACF?

**Comment by Lukid** [comment]
> Please create a new ticket to describe your issue. What do you mean by ACF?

Advanced Custom Field. Ok, I'll try on new ticket.
