### ISSUE TITLE
Property nullable but not declared as such

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#4389]
Hi,

For the following code:
https://psalm.dev/r/5256e702c4

Psalm return two issues.
The first one(DocblockTypeContradiction), on level 3, says that the property phpdoc should contain null
The second one(PossiblyNullPropertyAssignmentValue), on level 4, says that the property can't be null

In this case, the code is correct, but the wrong phpdoc cause 2 issues and the one suggesting the issue is on docbloc is actually reported after.

I find this behaviour very weird considering that in this example is the opposite:
https://psalm.dev/r/ad55cfae49

Here, we tell in phpdoc that $a is a string, but the fact that the param is declared nullable is enough for psalm to consider the param can be null.

I'm not sure it can be considered a bug (and I think this is new behaviour so it may even be wanted behaviour) but I find it pretty confusing.

**Comment by muglug** [comment]
`@var` isn't a valid _function_ docblock, and Psalm doesn't add null to PHP docblocks with a null default _because_ Psalm doesn't either

**Comment by orklah** [comment]
@muglug yep, sorry for the @var, my mistake.

What I meant is there is a difference here:
https://psalm.dev/r/35fa36e60b

One has null and the other one don't when they're both declared as `string`

**Comment by weirdan** [comment]
@orklah that's because PHP is PHP: https://3v4l.org/Z4Xoc

For parameters, it's valid to express nullable types with default null value as either `?type $p = null` or `type $p = null`.

**Comment by orklah** [comment]
yeah, I know but in my exemple, there's only documentation so the difference seemed weird, but if there's an underlying reason, I guess it's okay, even if it's not visible to the user.

**Comment by weirdan** [comment]
I would find it confusing if phpdoc param types were not treated the same way as native param types.

**Comment by orklah** [comment]
> I would find it confusing if phpdoc param types were not treated the same way as native param types.

Well, it's actually not, given that when you put the type in native parameter, it cause a fatal error:
https://3v4l.org/AtuK9
and Psalm report it correctly:
https://psalm.dev/r/3d4fe4ac2d

I'd not see the harm in adding null to the type where the parameter is assigned to null. It can only be a documentation error.

**Comment by weirdan** [comment]
> Well, it's actually not, given that when you put the type in native parameter, it cause a fatal error: https://3v4l.org/AtuK9

There are no parameters there, only properties. And property types behave differently, because… because PHP, that's why.
