### ISSUE TITLE
Oddity with PossiblyNullArrayAccess

### ISSUE THREAD

**Issue by maxarvidsson** [vimeo/psalm#439]
```
<?php

/**
 * @param array $a
 * @return void
 */
function expectsArray(array $a)
{
}

/**
 * @param int $a
 * @return void
 */
function expectsInt($a)
{
}

/**
 * @param array<mixed, array{item:int}> $list
 * @return void
 */
function test($list)
{
    while (!empty($list)) {
        $tmp = array_pop($list);
        // expectsArray($tmp);
        expectsInt($tmp['item']);
    }
}
```
Checking the code above with psalm gives:
```
ERROR: PossiblyNullArgument - src/main.php:28:20 - Argument 1 of expectsint cannot be null, possibly null value provided
        expectsInt($tmp['item']);


ERROR: PossiblyNullArrayAccess - src/main.php:28:20 - Cannot access array value on possibly null variable $tmp of type null|array{item:int}
        expectsInt($tmp['item']);
```
I would except no errors.

However, if you uncomment
`// expectsArray($tmp);`
psalm no longer gives any errors, so it seems psalm is able to understand it can't possible be null?

**Comment by muglug** [comment]
Fixed in 573260b

**Comment by muglug** [comment]
> However, if you uncomment
> `// expectsArray($tmp);`
> psalm no longer gives any errors, so it seems psalm is able to understand it can't possible be null?

Not quite. There's a `@psalm-ignore-nullable-return` annotation here: https://github.com/vimeo/psalm/blob/573260b16df2043194a9f8d1279a87a1b38a7a15/src/Psalm/Stubs/CoreGenericFunctions.php#L100-L104

That tells Psalm to not worry when the result of that expression could be null, but to still allow `null` checks. That flag wasn't being adhered to in this instance, now it is.

When it comes to arrays, Psalm doesn't track their non-emptiness. But it does track their emptiness (by changing the type to `array<empty, empty>`). So it knows this is bad:

```php
function foo(array $a) : void {
  if (!$a) {
    echo $a[0]; // EmptyArrayAccess issue here
  }
}
```
But it doesn't see the flaw in this:
```php
function foo(array $a) : void {
  if ($a) {
    $var = array_pop($a);
    if ($var === null) {}
  }
}
```

**Comment by maxarvidsson** [comment]
Aha, that explains it!

And thank you for the quick fix :)
