### ISSUE TITLE
Bad Taint Path

### ISSUE THREAD

**Issue by bdrodes** [vimeo/psalm#4390]
I'm running Psalm 3.18.2@19aa905f7c3c7350569999a93c40ae91ae4e1626.

TLDR: 
- psalm can't find a trivial taint path
- the path it does find skips between unrelated files 

I've attached two files I'm using to test the psalm taint tracker, target.php and file2.php (uploaded with .txt extensions to get through the github filter) 
[file2.txt](https://github.com/vimeo/psalm/files/5417593/file2.txt)
[target.txt](https://github.com/vimeo/psalm/files/5417596/target.txt)

These files both have no includes and are separate entities, but a similarly named functions.

The target tainted sink is in target.php:

```
function set_xml_value_to_memory($node, $val): void
{
    $cmd = sprintf("xmldbc -s %s \"%s\"", $node, $val);
    //TARGET TAINT SINK
    pclose(popen($cmd, 'r'));
}
```
The only change I made to support this was I added `popen` as a signature to my `vulnerable_stubs.phpstub` file: 

```
/**
* @psalm-taint-sink shell $command
*/
function popen(string $command, string $mode) {}
```

I have two issues. 

1) If I run psalm's taint analysis on target.php by itself, it is unable to detect tainted path to the popen, but more confounding,
2) when I run psalm's taint analysis on the directory containing both target.php and file2.php it finds a path that hops between target.php and file2.php. The psalm generated tainted path json is below.

In the output below, you can see that it is reporting that the taint trace path for target.php starts in file2.php with _POST['nodes'].

My invocation of psalm is  `/vendor/vimeo/psalm/psalm --taint-analysis -m --output-format=json /test1/`

Is this somehow user error? Any help? 

```
[
  {
    "severity": "error",
    "line_from": 37,
    "line_to": 37,
    "type": "TaintedInput",
    "message": "Detected tainted shell",
    "file_name": "/test1/target.php",
    "file_path": "/test1/target.php",
    "snippet": "    exec($cmd, $res);",
    "selected_text": "$cmd",
    "from": 811,
    "to": 815,
    "snippet_from": 802,
    "snippet_to": 823,
    "column_from": 10,
    "column_to": 14,
    "error_level": -2,
    "shortcode": 205,
    "link": "https://psalm.dev/205",
    "taint_trace": [
      {
        "label": "$_POST",
        "entry_path_type": ""
      },
      {
        "line_from": 60,
        "line_to": 60,
        "label": "$_POST['nodes']",
        "entry_path_type": "array-fetch-'nodes'",
        "entry_path_description": null,
        "file_name": "/test1/file2.php",
        "file_path": "/test1/file2.php",
        "snippet": "$nodes = $_POST[\"nodes\"];",
        "selected_text": "$_POST",
        "from": 1408,
        "to": 1414,
        "snippet_from": 1399,
        "snippet_to": 1424,
        "column_from": 10,
        "column_to": 16
      },
      {
        "line_from": 60,
        "line_to": 60,
        "label": "$nodes",
        "entry_path_type": "=",
        "entry_path_description": null,
        "file_name": "/test1/file2.php",
        "file_path": "/test1/file2.php",
        "snippet": "$nodes = $_POST[\"nodes\"];",
        "selected_text": "$nodes",
        "from": 1399,
        "to": 1405,
        "snippet_from": 1399,
        "snippet_to": 1424,
        "column_from": 1,
        "column_to": 7
      },
      {
        "line_from": 62,
        "line_to": 62,
        "label": "call to get_xml_value_from_memory",
        "entry_path_type": "arg",
        "entry_path_description": null,
        "file_name": "/test1/file2.php",
        "file_path": "/test1/file2.php",
        "snippet": "$r->info = get_xml_value_from_memory($nodes);",
        "selected_text": "$nodes",
        "from": 1482,
        "to": 1488,
        "snippet_from": 1445,
        "snippet_to": 1490,
        "column_from": 38,
        "column_to": 44
      },
      {
        "line_from": 53,
        "line_to": 53,
        "label": "get_xml_value_from_memory#1",
        "entry_path_type": "arg",
        "entry_path_description": null,
        "file_name": "/test1/file2.php",
        "file_path": "/test1/file2.php",
        "snippet": "function get_xml_value_from_memory($node): array",
        "selected_text": "$node",
        "from": 1257,
        "to": 1262,
        "snippet_from": 1222,
        "snippet_to": 1270,
        "column_from": 36,
        "column_to": 41
      },
      {
        "line_from": 36,
        "line_to": 36,
        "label": "call to sprintf",
        "entry_path_type": "arg",
        "entry_path_description": null,
        "file_name": "/test1/target.php",
        "file_path": "/test1/target.php",
        "snippet": "    $cmd = sprintf(\"xmldbc -g %s \", $node);",
        "selected_text": "$node",
        "from": 794,
        "to": 799,
        "snippet_from": 758,
        "snippet_to": 801,
        "column_from": 37,
        "column_to": 42
      },
      {
        "line_from": 36,
        "line_to": 36,
        "label": "sprintf#2",
        "entry_path_type": "arg",
        "entry_path_description": null,
        "file_name": "/test1/target.php",
        "file_path": "/test1/target.php",
        "snippet": "    $cmd = sprintf(\"xmldbc -g %s \", $node);",
        "selected_text": "$node",
        "from": 794,
        "to": 799,
        "snippet_from": 758,
        "snippet_to": 801,
        "column_from": 37,
        "column_to": 42
      },
      {
        "line_from": 792,
        "line_to": 792,
        "label": "sprintf",
        "entry_path_type": "arg",
        "entry_path_description": null,
        "file_name": "/vendor/vimeo/psalm/stubs/CoreGenericFunctions.phpstub",
        "file_path": "/vendor/vimeo/psalm/stubs/CoreGenericFunctions.phpstub",
        "snippet": "function sprintf(string $format, ...$args) : string {}",
        "selected_text": "string",
        "from": 16174,
        "to": 16180,
        "snippet_from": 16129,
        "snippet_to": 16183,
        "column_from": 46,
        "column_to": 52
      },
      {
        "line_from": 36,
        "line_to": 36,
        "label": "$cmd",
        "entry_path_type": "=",
        "entry_path_description": null,
        "file_name": "/test1/target.php",
        "file_path": "/test1/target.php",
        "snippet": "    $cmd = sprintf(\"xmldbc -g %s \", $node);",
        "selected_text": "$cmd",
        "from": 762,
        "to": 766,
        "snippet_from": 758,
        "snippet_to": 801,
        "column_from": 5,
        "column_to": 9
      },
      {
        "line_from": 37,
        "line_to": 37,
        "label": "call to exec",
        "entry_path_type": "arg",
        "entry_path_description": null,
        "file_name": "/test1/target.php",
        "file_path": "/test1/target.php",
        "snippet": "    exec($cmd, $res);",
        "selected_text": "$cmd",
        "from": 811,
        "to": 815,
        "snippet_from": 802,
        "snippet_to": 823,
        "column_from": 10,
        "column_to": 14
      }
    ]
  }
]
```

**Comment by muglug** [comment]
Please try to reproduce on psalm.dev with the `<?php // --taint-analysis` flag at the top

**Comment by muglug** [comment]
as to

> the path it does find skips between unrelated files

For taint analysis Psalm assumes that functions with the same name have the same taint inputs and outputs

**Comment by bdrodes** [comment]
@muglug Trying the example as is in the psalm.dev will not find it because popen is not by default a known sink. I manually changed it to `system` in the `target.php` mentioned above and it still will not detect the vulnerability (using the --taint-analysis comment as you suggested):

```
function set_xml_value_to_memory($node, $val): void
{
    $cmd = sprintf("xmldbc -s %s \"%s\"", $node, $val);
    //TARGET TAINT SINK
    system($cmd);
}
```

Regarding the bogus path its generating for two files. Is it not a bug for psalm to not scope namespaces and consider a function in another unrelated/not imported file to be the same just becomes of a naming collision?

**Comment by bdrodes** [comment]
I reduced the example down and I find that for the case of not finding the path, it looks like the issue is psalm doesn't recognize the sprintf. 

Here's a minimal example where it won't detect a taint:

```
<?php // --taint-analysis
$a = $_POST['test'];
$cmd = sprintf("%s", $a);
system($val);
?>
```
I believe I can easily update the phpstubs to specify a trace through sprintf. Should sprintf's and their variants be part of the built in signatures of psalm?

**Comment by bdrodes** [comment]
Any updates on what's going on here?

**Comment by LukasReschke** [comment]
@bdrodes, your example can be simplified a lot. That would probably make root causing easier :-)

(https://psalm.dev/r/88355c7682)

```php
<?php // --taint-analysis

function bad_sprintf($node, $val): void
{
    $cmd = sprintf("%s %s", $node, $val);
    system($cmd);
}

bad_sprintf("php", $_POST["value"]);
```

This does *not* result in any warning. If however the first parameter to `sprintf` is tainted, it detects this successfully:

(https://psalm.dev/r/809250c907)
```php
<?php // --taint-analysis

function bad_sprintf($node, $val): void
{
    $cmd = sprintf("%s %s", $node, $val);
    system($cmd);
}

bad_sprintf($_POST["value"], "php");
```

My assumption is that `sprintf` doesn't pass the taint here on anything than the first parameter. 

@muglug, I am not sure how taint propagation works in Psalm. Is the taint of the variadic function passed properly here?

https://github.com/vimeo/psalm/blob/4e8fb9c37f182f9f556f2d2d95d7e1d824490175/stubs/CoreGenericFunctions.phpstub#L721-L728

**Comment by bdrodes** [comment]
Thanks @LukasReschke. Yea simplification would help, sorry about that. The reason I left it a bit verbose (basically in the form I was given) is that the second issue I'm seeing is psalm is taking a path through an unrelated php file when it does detect a path.

**Comment by LukasReschke** [comment]
Put up a PR for variadic taint propagation at https://github.com/vimeo/psalm/pull/4649

**Comment by LukasReschke** [comment]
> The reason I left it a bit verbose is that the second issue I'm seeing is psalm is taking a path through an unrelated php file when it does detect a path

@bdrodes, are the functions marked as taint-specific or pure? If not, that could be a cause, but without the code hard to say. https://psalm.dev/docs/security_analysis/avoiding_false_positives/#specializing-taints-in-functions

**Comment by bdrodes** [comment]
Thanks again @LukasReschke. 

I had not marked any functions with any annotation special other than adding popen as a new taint sink stub. The code that exposes the bad path is attached to the original post above (file2.txt and target.txt, the extensions are txt to get around the github filter, see the original post for more details). 

I was not aware of some of the annotations you pointed me to, especially psalm-taint-specialize which seems very relevant; however, even if the psalm-taint-specialize annotation does resolve the issue, it still seems odd that psalm taint analysis would detect a path through an unrelated function in an unrelated file. 

In my initial post using the provided examples, psalm thinks it is possible to jump between the two files through a call to `get_xml_value_from_memory`. Both php files happen to define a function with the same name, which I assume is the cause of the problem. 

Is it a general risk with psalm that functions with the same name within a project may interfere with analyses leading to false positives or is this a namespace bug?

**Comment by muglug** [comment]
> Both php files happen to define a function with the same name, which I assume is the cause of the problem.

Yeah, there's basically no good solution to that, unfortunately. Psalm's taint analysis assumes that identically-named functions have the same behaviour.
