### ISSUE TITLE
&= operator on booleans

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#4391]
In our codebase, we have some occurence of this pattern:
https://psalm.dev/r/d0dcc55389

While the code quality is questionable, this works well and output a boolean if every function returned true:
https://3v4l.org/kh9HK

Psalm react very badly to this code. It doesn't like the operator &= on booleans at all and somehow thinks the variable is unused... twice :)

Running Psalter on the code will actually break it.

**Comment by jsiefer** [comment]
Why the bit and operator? Which should only work for integers as psalm reports.

https://psalm.dev/r/80d475cec2

**Comment by orklah** [comment]
You're right, this doesn't make sense :)
