### ISSUE TITLE
InvalidArgument: usort does not work with a callback in a form of an array

### ISSUE THREAD

**Issue by githoober** [vimeo/psalm#4394]
Passing a callback as an array is a documented way to pass callbacks to usort.

A callback as a class method:

https://psalm.dev/r/ae99d2c99a

```
<?php

class A {
    private function doSort(array $data): array
    {
        return $data;
    }
    
    public function sort(array $a): array
    {
        usort($a, [$this, 'doSort']);
        
        return $a;
    }
}
```
Results in 
```
Psalm output (using commit ad5a8c2): 

ERROR: InvalidArgument - 11:19 - Argument 2 of usort expects callable(array<array-key, mixed>, mixed):int, array{A&static, string(doSort)} provided

INFO: MixedArgumentTypeCoercion - 11:9 - Type mixed should be a subtype of array<array-key, mixed>
```

A callback as a function has the same problem:

https://psalm.dev/r/c9e36fc382

**Comment by weirdan** [comment]
Psalm is right. `usort()` expects a callable that compares two values and returns an int (see [docs](php.net/usort)). So the correct `doSort()` signature would be this: https://psalm.dev/r/8af65ba5c1
