### ISSUE TITLE
Type annotations for anonymous callables seem to be ignored

### ISSUE THREAD

**Issue by asgrim** [vimeo/psalm#4404]
The type annotations for anonymous functions, such as:

```php
/**
 * @param string $foo
 */
$callable = static function ($foo): string {
    /** @psalm-trace $foo */
    return $foo;
};
```

The type of `$foo` doesn't seem to be picked up at all.

Example: https://psalm.dev/r/42e35c98d7

Workarounds:

 - Define the docblock between the `=` and `static`: https://psalm.dev/r/fa89f3bd2a
 - If on PHP 7, apply `string` type (to solve this specific example), but doesn't help if the `@psalm-param non-empty-string $foo` is used for example. Example of this - this should fail static analysis, https://psalm.dev/r/6941a83257

Possibly related and maybe even the same issue is #3431

**Comment by orklah** [comment]
see https://github.com/vimeo/psalm/issues/4050#issuecomment-679313889

I think this is expected, the docblock should be just before the function

**Comment by asgrim** [comment]
To a "human" reading the code, the docblock _is_ just before the function (yes, I understand that's not the same for the parser heh).

**Comment by muglug** [comment]
@asgrim PHPStan doesn't support (at least as of a few months ago) annotating closures at all.

This is caused by PHP allowing assignments inside expressions – nothing I can do about it.

**Comment by asgrim** [comment]
@muglug ah I see - thanks for clarification there! :+1:
