### ISSUE TITLE
Is there a EBNF file with specification of your type annotation syntax available somewhere?

### ISSUE THREAD

**Issue by klesun** [vimeo/psalm#4405]
Hello.
Is there a [EBNF](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form#:~:text=In%20computer%20science%2C%20extended%20Backus,as%20a%20computer%20programming%20language.) or similar formalized specification for your type annotation syntax? I'm talking about the:
```
@psalm-type Person = array{
    name: string,
    documents: \NamedItem<\PersonalDocument>[],
}
```
I am developing a [phpstorm](https://github.com/klesun/deep-assoc-completion)/[vscode](https://github.com/klesun/deep-assoc-completion-vscode) plugins that integrate tightly with PSALM type system and having this EBNF file would allow me to highlight injected code in the doc comments.

Here is what I'm basically going for:
![image](https://user-images.githubusercontent.com/5202330/96722861-85851880-13b6-11eb-8954-659c366be0ab.png)

I could write this formalization of the syntax [myself](https://github.com/klesun-misc/klesun-rascal-playground/blob/master/src/org/klesun/lang/PsalmTypeExp/Concrete/WithLayout/Syntax.rsc), but:
1. It will be incomplete as I have no knowledge of _all_ the possible constructs in your type syntax (and had pretty hard time attempting to collect them from the docs, as not everything seems to be documented in one place)
2. It will become outdated the moment you add some new construct to your format, like `key-of` or something.

A scratch of what I'm going with so far: (it's in [Rascal](https://github.com/usethesource/rascal) format, not EBNF, but idea same)
```haskel
lexical StringLiteral = "\'" StringChar* "\'";
lexical StringChar
	= ![\' \\]
	| "\\" [\' \\ / b f n r t]
	;

lexical IdentifierName = [_a-zA-Z][_a-zA-Z0-9]*;
lexical Fqn = "\\"? IdentifierName ("\\" IdentifierName)*;

syntax AssocMember = StringLiteral ":" PsalmTypeExp;

start syntax PsalmTypeExp 
  = StringLiteral
  | bracket "array{" { AssocMember "," }* "}"
  | bracket Fqn "\<" { PsalmTypeExp "," }+ "\>"
  > left Fqn
  > left PsalmTypeExp "|" PsalmTypeExp
  ;

layout LAYOUT = [\t-\n \r \ ]*;
```

**Comment by weirdan** [comment]
I think Psalm doesn't have that at the moment. @muglug what do you think of adopting a parser generator such as e.g. https://github.com/ircmaxell/PHP-Yacc instead of using hand-written one?

**Comment by muglug** [comment]
I'd be happy to adopt a parser-generator if it provided _reasonaly_ similar functionality. A hand-written parser sometimes has the small benefit of human-readable errors (though Psalm's errors aren't all that useful).

I don't have the bandwidth to write that grammar, though. You can look in `TypeParseTest.php` to see a list of all the strings that should be accepted (and a good deal of ones that shouldn't).
