### ISSUE TITLE
PHP 8 installation fails due to dependency

### ISSUE THREAD

**Issue by tux-rampage** [vimeo/psalm#4408]
This is more an upstream bug, but psalm is not installable with composer on PHP8 at the moment.
It requires [webmozart/glob](https://packagist.org/packages/webmozart/glob#4.1.0) which does not support PHP 8 by its composer php require constraint.

There is a PR on the required Package webmozart/glob#19 - but no EST when this will be fixed.

**Comment by muglug** [comment]
I can make it instead a suggestion, with the enhanced glob functionality conditional on having that package. A minor setback tbh.

**Comment by muglug** [comment]
Turns out it wasn't even being used...
