### ISSUE TITLE
--alter --issues=ParamNameMismatch might corrupt function signature

### ISSUE THREAD

**Issue by HenkPoley** [vimeo/psalm#4409]
I found a place where it turned:
```php
  /**
     * @param number|Attribute|VendorAttribute $type The number of the RADIUS attribute
     * @param mixed $value The value of the attribute
     */
    public function setAttribute($id, $value)
```
into:
```php
  /**
     * @param number|Attribute|VendorAttribute $type The number of the RADIUS attribute
     * @param mixed $value The value of the attribute
     */ c function setAttribute($type, $value)
```

Notice how it deleted the substring 'publi'(-c), and attached the function signature to the end of the PHPdoc comment.

Feels a bit like a multi-threaded race condition problem 🤷‍♂️. But maybe it's just a string manipulation problem. Since I didn't find the remaining characters elsewhere in the file.

And yes, the $id -> $type change was correct.

**Comment by weirdan** [comment]
Is the code publicly available? If so, please post a link to it.

**Comment by HenkPoley** [comment]
No the code is not public. But it basically extends https://github.com/dapphp/radius/blob/06d415bbc237d74d75407c9c601676d1086934d8/src/Radius.php#L804

**Comment by weirdan** [comment]
I just suspect it might be caused by the specific formatting. Can you reproduce it in a separate repo then?

**Comment by orklah** [comment]
Closing this as not reproduced.
