### ISSUE TITLE
Unable to run because of UnexpectedValueException error

### ISSUE THREAD

**Issue by Zae** [vimeo/psalm#441]
Fatal error: Uncaught UnexpectedValueException: $storage should not be null for ProjectServiceContainer::compile in Psalm/Checker/MethodChecker.php:408

**Comment by muglug** [comment]
Assuming the project is not open source, do you have any sort of reduced test case for this?

**Comment by Zae** [comment]
The project is closed search sadly, but I have no idea where to really start to debug this. I don't think it really said what file it was processing at the moment.

**Comment by muglug** [comment]
Run Psalm with `--debug` and you'll see

**Comment by Zae** [comment]
Ah ok, I'll try that tomorrow!

Thanks.

Op 15 jan. 2018 18:40 schreef "Matthew Brown" <notifications@github.com>:

**Comment by Zae** [comment]
Hey @muglug,

I ran it with --debug, also tried to run it on the complete codebase because I think if it ran to completion it would give a lot of errors about non existing functions from wordpress because I only tried to scan my theme.

I got the error in these file:

**wp-content/themes/xxxx/vendor/symfony/dependency-injection/Tests/Fixtures/php/services_locator.php**

`Fatal error: Uncaught UnexpectedValueException: $storage should not be null for ProjectServiceContainer::compile in /var/www/html/public/wp-content/themes/xxxx/vendor/vimeo/psalm/src/Psalm/Checker/MethodChecker.php:408`

I got another error when I ran it on the complete codebase, is it ok to add it to this bug or do you want me to open a new ticket for this other error?

**wp-content/plugins/adminer/inc/adminer/drivers/firebird.inc.php**

`Fatal error: Uncaught Psalm\Exception\TypeParseTreeException: Invalid characters in type in /var/wwwwp-content/themes/xxx/vendor/vimeo/psalm/src/Psalm/Type.php:49`

Btw: when running psalm on a folder with only these two files, psalm only crashes on the firebird file, not the symfony file. I'll try to replicate the crash for this file a little better for you.

Pasted the contents of the files in this gist: https://gist.github.com/Zae/d52a9b7efc48ca14fb92af13c0cd4a3d

**Comment by Zae** [comment]
Hey @muglug,

I get the same crash when I only scan the `vendor/symfony/dependency-injection/` folder.

**Comment by muglug** [comment]
You should definitely not be trying to analyse the `vendor` directory alongside your own project files, as the `vendor` directory often contains files (e.g. test files) that use classes that either don't exist, or exist only in a very specific test setup that your own codebase does not mirror.

You can ignore directories entirely with `<ignoreFiles>` in your psalm.xml.

**Comment by muglug** [comment]
The firebird.inc.php crash was due to a bug in Psalm, and fixed here: 14e7b75

**Comment by Zae** [comment]
Oh!, ran it again and now it works, I guess the last error was some kind of composer hiccup.

I'll try to install the master version of psalm to get around the firebird problem and try to run it again on the entire codebase.

Thanks a lot for the help!

**Comment by muglug** [comment]
You’re welcome!
