### ISSUE TITLE
3.x: InvalidArgument error incorrectly shown for SplObjectStorage::attach()

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#4411]
https://psalm.dev/r/98f94c8849

https://www.php.net/manual/en/splobjectstorage.attach.php

**Comment by jsiefer** [comment]
You need to specify the types.

```
<?php

/** @var SplObjectStorage<stdClass, mixed> $objStorage */
$objStorage = new SplObjectStorage();
$objStorage->attach(new stdClass());
```

**Comment by ADmad** [comment]
I don't see why one should be forced to explicitly  specify the type. If none is specified `object` should be used.

**Comment by weirdan** [comment]
This is a known limitation of generics instantiated from default array values. I think nobody ever proposed a feasible generic syntax that could be used to specify defaults for type parameters.

**Comment by ADmad** [comment]
I don't know the pslam internals well enough to understand why it can't just treat the value as `object` by default instead of `empty` for `SplObjectStorage`.

**Comment by muglug** [comment]
Yeah, I think there was a solution I proposed in another ticket – I should be able to look at this tomorrow
