### ISSUE TITLE
False positive TypeDoesNotContainType with attribute while altered by a method

### ISSUE THREAD

**Issue by ptomulik** [vimeo/psalm#4412]
This should not report any error, 

https://psalm.dev/r/2ca9814f0f

note, that modifying ``$this->x`` in ``C::g()`` would not yield any issue

https://psalm.dev/r/cdb64aac76

**Comment by muglug** [comment]
Turn off property type memoisation and it works: https://psalm.dev/r/9e08e5e0d3

**Comment by ptomulik** [comment]
Thanks! :)
