### ISSUE TITLE
psalm loses track of generic templates inside callables.

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#4422]
I noticed that PSL build failed today due to a recent change ( didn't track the commit ).

https://psalm.dev/r/19c265fae6

Expected: no issues.

The reason for creating a callable is that I want a factory to initialize a lazy iterator, the actual implementation can be found here: https://github.com/azjezz/psl/blob/develop/src/Psl/Iter/filter_with_key.php

**Comment by muglug** [comment]
This is just in master, right? I refactored Psalm's static reflection, which is a very likely candidate

**Comment by azjezz** [comment]
yes :) i use dev-master in psl ... which is something i should probably change soon

**Comment by azjezz** [comment]
Thank @muglug ❤️  🎉
