### ISSUE TITLE
Type of captured variables in the closure and after it.

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#4424]
https://psalm.dev/r/a0c748da80

```
/** @var int[] $a */
$a = [];
$f = function () use (&$a): void {
    $a[] = 1;
    $a[] = 2;
};

$f();

foreach ($a as $i) echo $i;
```

results in

> INFO: MixedArrayAssignment - 6:2 - Cannot access array value on mixed variable $a
> INFO: MixedArrayAssignment - 7:5 - Cannot access array value on mixed variable $a
> INFO: MixedAssignment - 12:16 - Unable to determine the type that $i is being assigned to

Also, commenting out `$f();` does not help psalm to infer the type of `$i`.

**Comment by muglug** [comment]
Use by-ref is generally unsound (there are a bunch of previous closed issues around this). The easiest fix is to wrap things in an object (or to ignore the `Mixed` issues): https://psalm.dev/r/87a177e756
