### ISSUE TITLE
Removing requireVoidReturnType option causes a big disruption for php 7.0 code base

### ISSUE THREAD

**Issue by ArtemGoutsoul** [vimeo/psalm#4426]
Our code base is running on php 7.0 and 7.4

After the 4.0 change requireVoidReturnType was removed, so now we get over 4 thousand MissingReturnType issues.

Current options and corresponding issues:
- just add all to baseline, force all new cases to have void return type - ISSUE: PhpStorm does not add void return types to PhpDoc, this creates a lot of extra hassle :(
- disable InvalidReturnType - ISSUE: all non-void cases do really need a type
- run fix - ISSUE: the fix generated broken php 7.0 code :(

Consider:
```
function run() {
   echo 'blah';
}
```
When I run --alter
I get:
```
function run(): void {
   echo 'blah';
}
```
Which is not valid php 7.0.

Possible fixes that could be considered in psalm:
- make it possible to --alter and not add `: void` if composer target platform is lower than php 7.1
- add MissingVoidReturnType that could be suppressed for codebases that are not using it

**Comment by muglug** [comment]
@ArtemGoutsoul you can specify a PHP version like `--alter --php-version=7.0` that will add `void` to docblocks instead.
