### ISSUE TITLE
Wrong inferred PossiblyNullReference error

### ISSUE THREAD

**Issue by alexandrmazur96** [vimeo/psalm#4427]
https://psalm.dev/r/47ae5ddbb4

**Comment by muglug** [comment]
You have a few options:

 - explicitly memoize the call: https://psalm.dev/r/72163e607c
 - turn on method call memoization for your whole project: https://psalm.dev/r/e67bbd25c9
 - make the whole class immutable: https://psalm.dev/r/72500384c0
