### ISSUE TITLE
PHP 8: class implements Stringable implicitly

### ISSUE THREAD

**Issue by ondrejmirtes** [vimeo/psalm#4429]
RFC: https://wiki.php.net/rfc/stringable

> Classes that implement __toString() can also declare the interface explicitly. Classes that don't declare the interface explicitly will still declare it implicitly.

https://psalm.dev/r/1e77feac2a

Expected: no issues (https://3v4l.org/T3uIN)

**Comment by muglug** [comment]
lol wtf

**Comment by muglug** [comment]
Thanks, that's a really dumb rule. Ugh.

**Comment by ondrejmirtes** [comment]
I guess it works for interfaces too but you have a negated boolean about is_interface in there.

**Comment by ondrejmirtes** [comment]
And of course I’m glad I brought a bit of joy into your life today 😀

**Comment by ondrejmirtes** [comment]
My thinking is that:

* Interface has `__toString()` method
* Class implements the interface and has to implement the `__toString()` method
* Class becomes Stringable
* Therefore the interface is also Stringable because there's no other way...
