### ISSUE TITLE
Misbehaviour of stdout after running psalm (OSX)

### ISSUE THREAD

**Issue by medains** [vimeo/psalm#443]
# Summary
The output of psalm messes with terminal settings in a way that "reset" or "tput reset" does not fix.  Executing bash and exiting it does fix the behaviour.

# Commentary
I first noticed this in combination with iterm2, vim and the vim plugin gitgutter.  After running psalm, gitgutter wasn't acting consistently.   Running "reset" did not fix the behaviour.

A new terminal did not exhibit the same behaviour, but repeats rendering issues after running psalm.

Attempting to isolate the issue, I replicated the problem with the following combinations.
* Using OSX built in "terminal" instead of iterm2
* Adding the '-m' to psalm
* Creating a test file to run psalm against instead of using the particular codebase
* Piping the output to /usr/bin/less to escape sequences

In each case I can repeat the behaviour in vim, and related issues in less and cat!

# Version Details
OSX version 10.12.6
iTerm 3.1 beta 9
less --version = "less 458"
psalm version 0.3.81
Bash version 4.4.12

# Test file
````php
<?php

function foo() {
    $bad = $evenworse1;
}
function afoo() {
    $bad = $evenworse2;
}
function bfoo() {
    $bad = $evenworse3;
}
function cfoo() {
    $bad = $evenworse4;
}
function dfoo() {
    $bad = $evenworse5;
}
function efoo() {
    $bad = $evenworse6;
}
function ffoo() {
    $bad = $evenworse7;
}
function gfoo() {
    $bad = $evenworse8;
}
function hfoo() {
    $bad = $evenworse9;
}
function ifoo() {
    $bad = $aevenworse1;
}
function jfoo() {
    $bad = $aevenworse2;
}
function kfoo() {
    $bad = $aevenworse3;
}
function lfoo() {
    $bad = $aevenworse4;
}
function mfoo() {
    $bad = $aevenworse5;
}
function ofoo() {
    $bad = $aevenworse6;
}
function pfoo() {
    $bad = $aevenworse7;
}
function qfoo() {
    $bad = $aevenworse8;
}
function rfoo() {
    $bad = $aevenworse9;
}
function sfoo() {
    $bad = $bevenworse1;
}
function tfoo() {
    $bad = $bevenworse2;
}
function ufoo() {
    $bad = $bevenworse3;
}
function vfoo() {
    $bad = $bevenworse4;
}
function wfoo() {
    $bad = $bevenworse5;
}
function xfoo() {
    $bad = $bevenworse6;
}
function yfoo() {
    $bad = $bevenworse7;
}
function zfoo() {
    $bad = $bevenworse8;
}
function aafoo() {
    $bad = $bevenworse9;
}
````

# Steps to repeat behaviour
* Use OSX terminal or iterm2
* Create test file above as src/foo.php
* Install psalm with "composer require --dev vimeo/psalm:^0"
* Set up psalm with "vendor/bin/psalm --init"
* Run "cat src/foo.php" - the whole file will be output.
* Run "vendor/bin/psalm" - which reports lots of bad things with that nasty file
* Run "cat src/foo.php" - the file will be truncated partway through line 66 (consistently) - occasionally with the addition of an error (or even just part of it) "cat: stdout: Resource temporarily unavailable"

# Workaround
* Run an new copy of "bash" and exit it - seems to reset stdout so that it behaves properly again.

**Comment by muglug** [comment]
Thanks, I’ll have a look this evening. Do you have XDebug turned on?

**Comment by medains** [comment]
I'm pretty sure I don't have it installed.  Using homebrew-installed php7.0 (7.0.27)

I usually run php related things in docker containers rather than natively on the mac.

**Comment by medains** [comment]
Since I was here, I checked and get the same behavior with php7.2.1 (also from homebrew)
