### ISSUE TITLE
Bring back requireVoidReturnType or add a possibility to filter missing void return type issues

### ISSUE THREAD

**Issue by ArtemGoutsoul** [vimeo/psalm#4432]
This issue is based on https://github.com/vimeo/psalm/issues/4426, but after trying possible solutions, I made a new one.

The problem:
 - psalm 4.0 removed the possibility to set requireVoidReturnType = false
 - for legacy code bases this creates a lot of errors that cannot be filtered separately
 - this is especially an issue with php version below 7.1, when you cannot specify void return type in the function declaration

# Issues with possible solutions
Two main solution groups
1. require void return type
2. do not require void return type

## 1. Require void return type
Two possibilities here:
- add to baseline
- fix using --alter

### Add to baseline
- baseline becomes huge for legacy code bases (extra 4000 errors for us, when our whole baseline was only 1000 by now)

### Fix using `--alter --php-version=7.0`
- alter modifies the phpdoc spacing and introduces some artifacts sometimes (will try to reproduce and file another issue), in case of 4000 errors, this requires a lot of manual work to check that nothing is broken
- alter will fix all MissingReturnType, not just the missing void

### Common problem even if the other ones are fixed
- PhpStorm does not add void return types to PhpDoc (or at least I could not figure out how)
- Since php 7.0 cannot do `function f(): void` one has to add 3 lines of php doc even to the simplest functions.
```
/**
 * @return void
 **/
function f()
```

## 2. Do not require void return type
This can only be implemented by suppressing MissingReturnType, which suppresses the same error for all other types. Which is really useful otherwise.
Personally I went with this one for now, since this affects the least code and causes the least disruption for our developers.

**Comment by muglug** [comment]
If this is really an issue for you I'd just stick to 3.x.

PHP 7.0 was EOLed almost two years ago, which is why I felt reasonably comfortable making this change.

If you can reproduce the alter artifacts, please ticket that separately!

**Comment by still-dreaming-1** [comment]
Even just putting void as the return type in the code itself is just extra noise for the function definition. A person looking at that code typically thinks of it as meaning nothing is returned. I would rather Psalm enforces that the lack of a specified return type means it should not return anything, and enforce that. There are many methods that do not need to return anything, especially test methods, and adding void as the return type to all of them is overly noisy.
