### ISSUE TITLE
MoreSpecificReturnType and LessSpecificReturnStatement when inheriting

### ISSUE THREAD

**Issue by bassta** [vimeo/psalm#4433]
Hi.

https://psalm.dev/r/fa9ac3908b
```php
class A
{
    private int $a = 0;
    
    public function setA(int $a): self
    {
        $this->a = $a;
        
        return $this;
    }
}

class B extends A {}

function bar(): B
{
    $b = (new B())->setA(1);
    
    return $b;
}
```
Code seems to be correct but I have following errors
```
INFO: LessSpecificReturnStatement - 21:12 - The type 'A' is more general than the declared return type 'B' for bar

INFO: MoreSpecificReturnType - 17:17 - The declared return type 'B' for bar is more specific than the inferred return type 'A'
```

As I understand it, the reason for the errors is the call `setA(1)` in `bar()`. `setA(1)` return type is `A` and `$b` treated as `A`.

How should I declare the return type of `setA()` to get rid of the error?

**Comment by orklah** [comment]
Hi,

`self` is not narrow enough for your usage.

Either replace `self` by `static` (from PHP8) or put `$this` or `static` in a `@return`

**Comment by bassta** [comment]
Thank you!
