### ISSUE TITLE
psalm --init crashes on str_replace call without required third parameter

### ISSUE THREAD

**Issue by daiwai** [vimeo/psalm#4437]
If the `psalm --init` scan encounters a call to `str_replace` with only the first two parameters `$search` and `$replace` but without the required third parameter `$subject` it crashes with

    Uncaught TypeError: Argument 1 passed to Psalm\Internal\Provider\NodeDataProvider::getType()
    must be an instance of  PhpParser\NodeAbstract, null given, 
    called in src/Psalm/Internal/Provider/ReturnTypeProvider/StrReplaceReturnTypeProvider.php on line 38 
    and defined in src/Psalm/Internal/Provider/NodeDataProvider.php:49

To reproduce this issue, run `psalm --init` on a file like

    <?php
    
    $replaced = str_replace('search', 'replace');

Not sure what would be the right thing to do here. One possibility would be to check for the right number of parameters passed to `str_replace` before attempting to get the type of the third parameter. Something like:

    if(count($call_args) !== 3) {
        return Type::getNull();
    }

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/4aef96bbac8759255501a764960f8fb1c1f2157b

**Comment by muglug** [comment]
Other similar potential crashes fixed in https://github.com/vimeo/psalm/commit/dab1aac9d424834ca28bc8942edbca35f414c89d
