### ISSUE TITLE
@param-out with template is not working in interfaces

### ISSUE THREAD

**Issue by davidbyoung** [vimeo/psalm#4441]
https://psalm.dev/r/3d452b72f1

In this example, we'd invoke `IResolver::tryResolve()` like so:

```php
$foo = null;

if (!$resolver->tryResolve(Foo::class, $foo)) {
    throw new \Exception('Foo could not be resolved');
}

// $foo is set to an instance of Foo
```

However, I'm getting a `ReferenceConstraintViolation`.

**Comment by davidbyoung** [comment]
Borrowed #4457:  https://psalm.dev/r/d415fac3f5

**Comment by muglug** [comment]
I think this is a dupe of https://github.com/vimeo/psalm/issues/2080

**Comment by davidbyoung** [comment]
Ah, you're right. Sorry about that. I'll close this issue.
