### ISSUE TITLE
Plugin API to parse custom PHP Doc type annotations

### ISSUE THREAD

**Issue by joehoyle** [vimeo/psalm#4445]
I'm wondering if Psalm provides the right hooks and extensibility for a plugin to parse types from PHP Doc comments in formats that is not natively supported by Psalm. For example, WordPress uses a almost-made-it-into-a-standard PHPdoc syntax for associative arrays as described by https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#1-1-parameters-that-are-arrays.

I believe the phpdoc project has an appropriate parser, but I'm wondering if it's possible to augment Psalm with an additional parser some how.

**Comment by muglug** [comment]
> I believe the phpdoc project has an appropriate parser

I don't think it does, as this basically breaks phpdoc. I don't believe nesting tags was ever valid.

You'd have to create some sort of `DockblockParserProvider` and implement your own logic. It's not a straightforward task, at all.

**Comment by muglug** [comment]
If you figure something out feel free to create a PR!
