### ISSUE TITLE
Feature request: allow an expectation for TypeError to mute InvalidReturnStatement/InvalidReturnType 

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#4449]
[For example](https://psalm.dev/r/9ca6d4c83e), looking at the `@throw` definition one can reason that this method intentionally returns _strictly_ `int` because returning a string is an error, an undesired behavior.

```php
class HolderForMixedValue {
    /** @var int|string */
    private $x;
    
    /** @throws \TypeError */
    public function getInt(): int
    {
        return $this->x;
    }
}
```
One way to handle this is to add [an explicit type check with a throw](https://psalm.dev/r/1695392d7d), but that's redundant since PHP will be happy to throw a pretty much same error for us.

If Psalm could understand that there's a documented possibility for a `TypeError`, then it could reason that `InvalidReturnStatement`/ `InvalidReturnType` are not to be called here.

**Comment by orklah** [comment]
After thinking about it, I don't think it's a good idea. For a getter, it's pretty straightforward because there is only one TypeError check, but on other methods, you could have dozens of calls to functions/methods that each could throw a TypeError. Suppressing silently this much errors is risky.
