### ISSUE TITLE
MethodSignatureMismatch for a trait with Psalm 4.1.0 but not with 3.18.2

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#4451]
No matter how I try I can't reproduce the issue in the playground. But here's a minimal case:

```bash
git clone https://github.com/sanmai/sdk-common.git --branch tmp/psalm
cd sdk-common/
make psalm
```
Should use Psalm 4.1.0@8929bde5 or later.

Observe error:
```
ERROR: MethodSignatureMismatch - tests/Concerns/Fixtures/ListContainerExample.php:34:13 
    - Argument 1 of CommonSDK\Concerns\ListContainer::withList has wrong type 'array<array-key, mixed>',
       expecting 'array<array-key, object>' as defined by JSONSerializer\Contracts\ItemList::withList (see https://psalm.dev/042)
final class ListContainerExample implements ItemList
```

Note that `ListContainer::withList` apparently has a wrong type of the only argument. Now:
```
grep -B5 withList src/Concerns/ListContainer.php
```
Observe that it has expected type `array<object>`:

```php
    /**
     * @param array<object> $list
     *
     * @return static
     */
    public static function withList(array $list)
```

What is it what I'm doing wrong here?

Thanks.

**Comment by sanmai** [comment]
I tried to make a minimal case, to no avail: https://psalm.dev/r/373f0dbd9c

**Comment by sanmai** [comment]
Interestingly Psalm 3.18.2 reports no issues here.

**Comment by pro2s** [comment]
I've found out that issue is reproduced only with php 7.4 for me. With php 7.3 is ok.

**Comment by muglug** [comment]
@sanmai 

I wasn't able to reproduce with the steps above, but I think this will fix it – Psalm‘s cache not busting when changing a parent signature: https://github.com/vimeo/psalm/commit/f0a30b9fd05b17f34139e7d0d1d71c291258e268
