### ISSUE TITLE
How do I define a large array type whilst keeping line lengths within limits

### ISSUE THREAD

**Issue by toby-griffiths** [vimeo/psalm#4453]
I'm new to psalm, and loving it already, but I've hit the problem whereby I need to defined a large array structure, however when I try to wrap it over multiple lines it breaks the checks.  But it I keep it all on one line it breaks my code style rules.

Is there a way of breaking a type over multiple lines, safely?

Here is an example: https://psalm.dev/r/bbd09ed831

This might be mitigated slightly if I could use a DecBlock defined type, but I can't due to #4436 .

Also, in the above example, you'll see I was able to wrap one of my `@extends` to place the the argument on the next line, however on the other I was, for some reason, as can be seen here…

https://psalm.dev/r/b90e948137

**Comment by muglug** [comment]
yup, `@extends` doesn't support multi-line yet

**Comment by toby-griffiths** [comment]
@muglug Is there a ticket/info on how this might be added, and is it already being worked on?  I'm new here, but happy to work on a PR if I can find the time?

**Comment by toby-griffiths** [comment]
Wow!  That was quick!  🙏🏼
