### ISSUE TITLE
not using parameters in declared callback closures should not be marked as an error

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#4454]
sample code:

https://psalm.dev/r/af9ebbb653

that function `afilter` is declared as taking a callable callback which in turn takes two arguments.

In this case, the callback is not using one of the arguments, but it certainly must be present. 

In case of a single parameter, we can use `$_`, but what if there are multiple parameters to the callback and the callback is only using one of them? The same name `$_` can't be reused.

**Comment by muglug** [comment]
You can just prepend the name with `_`: https://psalm.dev/r/df4147d038
