### ISSUE TITLE
mb_strtolower() should return lowercase-string rather than string

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#4455]
https://psalm.dev/r/b141bec26e

I found this while working on getting a psalm plugin updated that's creating a `\Psalm\Internal\MethodIdentifier` and I wanted to be correct and used `mb_strtolower()` on the method name - not that we're supposed to have method names where this matters, but still.

**Comment by orklah** [comment]
It should be a simple modification of
https://github.com/vimeo/psalm/blob/master/dictionaries/CallMap.php

Care for a PR?

**Comment by pilif** [comment]
yep. I know - I made changes to those call maps in the past - I've just reported it here in order to not forget 😊

submitted #4469 now.
