### ISSUE TITLE
XOR on strings

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#4456]
PHP allows to perform a XOR operation on strings:

 ```php
$string = "abc";
$xor = "\xff\xff\xff";

$string ^= $xor;

echo bin2hex($string); // 9e9d9c
```

However, Psalm complains that operands are not integers:

> ERROR: InvalidOperand - src/Internal/Calculator.php:688:9 - Cannot perform a numeric operation with non-numeric types string and string (see https://psalm.dev/058)

---

Tried to reproduce it on psalm.dev, but the site is failing: https://psalm.dev/r/fc747c6ddd
No output, and the console shows:

> Request failed SyntaxError: Unexpected end of JSON input
>     at fc747c6ddd:170

**Comment by orklah** [comment]
On psalm.dev, the issue seems caused by the string:
https://psalm.dev/r/6958905a97

I think this is an issue with the linter or somethin

**Comment by orklah** [comment]
About the fact that Psalm forbids bitwise operations on string, I think this was intended

**Comment by BenMorel** [comment]
Why was it intended? Although not used much in the wild, it's perfectly legal.

I use it in brick/math to perform bitwise operations & two's complement on arbitrary large numbers. Example:
https://github.com/brick/math/blob/cbdd9605fcfc593b42f2b82735d39f27fc562bb6/src/Internal/Calculator.php#L691

**Comment by orklah** [comment]
> Why was it intended? 

Not sure, but the error message is pretty clear. It excluded boolean opérations with bitwise operators too

**Comment by BenMorel** [comment]
Looks like this was fixed in the latest version:

https://github.com/brick/math/commit/8da162582218711eb14641df6b8a053e2d09217f
https://github.com/brick/math/runs/3215614683

**Comment by orklah** [comment]
The weird string still makes Psalm crash, but let's ignore that for now
