### ISSUE TITLE
Report mixed iterable/array typing

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#4461]
https://psalm.dev/r/95e5d79df9
https://psalm.dev/r/bf3216d7db

expected function definition error

**Comment by weirdan** [comment]
Why?

**Comment by ro0NL** [comment]
because it contradicts. Similar as https://psalm.dev/r/593976b8e8 id say.

**Comment by ro0NL** [comment]
I figured it's a covariance. But seems to merge nullability though ... https://psalm.dev/r/7668d240a3

**Comment by weirdan** [comment]
The last one looks like a bug to me (https://psalm.dev/r/7668d240a3). I'd expect `$x` to have `string` type here.

**Comment by muglug** [comment]
`null` is always added to docblock return types if it exists in the signature. It's to deal with this all-to-common pattern:

```php
/**
 * @param Foo $foo    Some description
 */
function takesFoo(Foo $foo = null) : void {}
```

**Comment by ro0NL** [comment]
well we can argue its not a nullable even, as per docblock.
