### ISSUE TITLE
Type inferrence with negated condition with OR

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#4466]
Hi,

In the example below, I'd have expected the type to be `trait-string|class-string`
https://psalm.dev/r/b09d68b1ed

Thanks

**Comment by weirdan** [comment]
This seems to be partially caused by wrong handling for autoloader flag for these functions: https://psalm.dev/r/3313a99852

**Comment by weirdan** [comment]
Short-circuiting behaviour of `||` also doesn't seem to be taken into account: https://psalm.dev/r/750ff3309a

**Comment by muglug** [comment]
I'm gonna say, with the `trait_exists` check, that this is a no-fix. Just too much of an edge-case.

**Comment by weirdan** [comment]
@muglug https://psalm.dev/r/3313a99852 is clearly wrong though, isn't it? And it doesn't involve `trait_exists()`

**Comment by muglug** [comment]
Yeah, that should be negatable

**Comment by orklah** [comment]
Thanks!
