### ISSUE TITLE
Covariant return type issue

### ISSUE THREAD

**Issue by justnero** [vimeo/psalm#4470]
PHP allows narrowing return types in child classes. In this example the only accessor of the `Foo::$bar` is `Foo::__construct`. The `Baz::__construct` narrows the actual type signature of `Foo::getBar()` to `Bar` only, but psalm tells it's still `?Bar`.

Is it a bug or it is expected? And if it's not a bug what would be the best way to fix this case?

## Snippet
https://psalm.dev/r/3e4e671072
```php
<?php

declare(strict_types=1);

class Bar {}

class Foo {
    private ?Bar $bar;
    
    public function __construct(?Bar $bar) {
        $this->bar = $bar;
    }
    
    public function getBar(): ?Bar {
        return $this->bar;
    }
}

final class Baz extends Foo {
    public function __construct(Bar $bar) {
        parent::__construct($bar);
    }
    
    public function getBar(): Bar {
        return parent::getBar();
    }
}
```

##  Output
```
ERROR: NullableReturnStatement - 25:16 - The declared return type 'Bar' for Baz::getBar is not nullable, but the function returns 'Bar|null'

ERROR: InvalidNullableReturnType - 24:31 - The declared return type 'Bar' for Baz::getBar is not nullable, but 'Bar|null' contains null
```

**Comment by muglug** [comment]
Yup, this is expected behaviour

**Comment by orklah** [comment]
It doesn't seem possible to use PHPDoc to redefine the property in the child and given it's private it's not possible to redefine it in PHP.

So the two options I see to fix this is either to assert the return of parent::getBar() is different from null or use templates like this:
https://psalm.dev/r/7602c1559b

The use of templates seems too much, but it's the only thing that I can see without touching the code

**Comment by creocoder** [comment]
@muglug What best solution to overcome this? Code looks absolutelly OK.

**Comment by 2e3s** [comment]
The code doesn't look ok because the types mismatch. Dynamically it will not cause errors in this very limited code, but statically it is incorrect.

**Comment by muglug** [comment]
@creocoder have a look at the template example from @orklah posted above
