### ISSUE TITLE
Covariant parameter type issue

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#4471]
I fail to see why null is preserved from the signature, whereas `int` isnt.

https://psalm.dev/r/c3d5a7e516

derived from #4461

**Comment by muglug** [comment]
Psalm always adds nullability from the signature to docblock types, as explained in that ticket, but not other types.

**Comment by ro0NL** [comment]
Sorry, but i didnt qualify `It's to deal with this all-to-common pattern` a reasonable explanation from my POV. It's a weird inconsistency on psalm's side IMHO.

Ultimately `X $x = null` is a broken PHP concept, superseded by `?X`.

I suggest to reconsider long term :)

**Comment by ro0NL** [comment]
@muglug what if legitimately want to exclude null from the docblock covariant ... i cant. And things become implicit overall.

**Comment by muglug** [comment]
If you want to make a PR with an opt-in flag you're more than welcome.
