### ISSUE TITLE
RedundantCondition when asserting exception sub-class

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#4473]
While creating https://github.com/doctrine/dbal/pull/4401, I noticed that Psalm complains in the following (simplified) case:

```php
class DriverException {}

class ConnectionException extends DriverException {}

interface ExceptionConverter
{
    public function convert(): DriverException;
}

class Test
{
    private ExceptionConverter $converter;

    /**
     * @param class-string<DriverException> $expectedClass
     *
     * @dataProvider exceptionConversionProvider
     */
    public function testConvertsException(string $expectedClass): void
    {
        $dbalException = $this->converter->convert();

        self::assertInstanceOf($expectedClass, $dbalException);
    }

    public function exceptionConversionProvider(): array
    {
        return [
            [ConnectionException::class],
        ];
    }
}
```

> ERROR: RedundantCondition - tests/Driver/API/ExceptionConverterTest.php:54:15 - Type Doctrine\DBAL\Exception\DriverException for $dbalException is always Doctrine\DBAL\Exception\DriverException (see https://psalm.dev/122)
        self::assertInstanceOf($expectedClass, $dbalException);

As far as I can see, the condition is not redundant: while `$dbalException` is a `DriverException`, there is no guarantee that it passes the `instanceof` check for the *subclass* of `DriverException` provided.

Full reproducer:

```sh
git clone https://github.com/BenMorel/dbal.git
cd dbal
git checkout unused-var
composer install
vendor/bin/psalm
```

**Comment by BenMorel** [comment]
Cannot reproduce it on psalm.dev I'm afraid.

**Comment by muglug** [comment]
Running the above doesn't reproduce the stated issue

**Comment by muglug** [comment]
Actually here's a simple reproducer: https://psalm.dev/r/6d85680f44

**Comment by muglug** [comment]
Actually this is an issue with PHPUnit's assertion – it should be `@psalm-assert =T`: https://psalm.dev/r/c02c5ac41f

Please open a ticket in PHPUnit's repo!

**Comment by BenMorel** [comment]
Thanks a lot, @muglug!
