### ISSUE TITLE
Integrate povils/phpmnd into psalm

### ISSUE THREAD

**Issue by povils** [vimeo/psalm#4474]
Hey team,

Long time ago I have written and still trying my best to maintain the project https://github.com/povils/phpmnd/ . Which basically detects magic numbers in your code.

I see that psalm has a much better community support and I was thinking if it would be possible to integrate phpmnd to psalm.

Please let me know what you think

**Comment by weirdan** [comment]
While it doesn't seem to be a very good fit for the Psalm core itself, you may try to implement it as a plugin. See https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/ and the list of available hooks at https://github.com/vimeo/psalm/tree/master/src/Psalm/Plugin/Hook. This way you'd be able to leverage Psalm's infrastructure for parsing/caching/diffing/reporting/LSP support, etc.

**Comment by muglug** [comment]
Yup, what he said!

This will never go into Psalm core as it has too much potential for noise, but feel free to create a plugin.
