### ISSUE TITLE
@mixin should validate method availibility

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#4477]
eg. defined or magic call

https://psalm.dev/r/d420407eb5

expected Method x::boo does not exist, or an invalid definition

**Comment by mr-feek** [comment]
@ro0NL Could you elaborate on why you expect `Method x::boo does not exist`? `@mixin` syntax means that all public methods on another class should be available on the class level with the annotation

**Comment by ro0NL** [comment]
> @mixin syntax means that all public methods on another class should be available on the class level with the annotation

"should", but it's not the case :) so i expected a warning in advance.

**Comment by mr-feek** [comment]
I see. So you would essentially like a "validation"  that if `@mixin` is being used, a class should have `__call` or `__callStatic`?

**Comment by ro0NL** [comment]
yes or imported via trait perhaps, or simply defined.

im also unsure what `@mixin interface` means over `implements interface` :sweat_smile: i guess it's a side effect.

also feel free to ignore the issue as a whole, it was rather an observation by me.

**Comment by ro0NL** [comment]
ive concluded i find `@mixin` a weird feature :) `@mixin OtherClass` is hard to grasp, `use Trait` / extends / implements at the language level is not and provides discoverable methods as well.

**Comment by mr-feek** [comment]
@ro0NL it's very helpful syntax to document classes that proxies to others via `__call` or `__callStatic`

**Comment by ro0NL** [comment]
i figured :+1:

i do think it should validate as `@method` does yes: https://psalm.dev/r/20f810a900
