### ISSUE TITLE
Feature request: detect functions that always throw or exit

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#4480]
It would be nice if Psalm could detect if a given function unconditionally throws an exception, or `exit()`s. See:

https://psalm.dev/r/a0797f9c6b

In this case, `$result` can never be null because we have `error()`ed before.

**Comment by orklah** [comment]
You can use @return `never-returns`/`never-return`/`no-return` to tell psalm that a function will not return:
https://psalm.dev/r/548118f6aa

Those 3 are aliases so use the one you like best

**Comment by weirdan** [comment]
I'd say, return types should be declared, not inferred, even if the type in question is `never`. And since there's already a way to declare that there's nothing to change here, thus closing.

**Comment by BenMorel** [comment]
Makes sense. Thank you!
