### ISSUE TITLE
UnusedVariable false positive with array spread operator

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#4484]
https://psalm.dev/r/405e954d68

**Comment by enumag** [comment]
bump

**Comment by muglug** [comment]
Ask not what Psalm can do for you, ask what you can do for Psalm (in this case reading up on [unused variable detection](https://psalm.dev/articles/better-unused-variable-detection) then creating a test case and finally getting to the root of the bug.

**Comment by muglug** [comment]
`ArrayAnalyzer::handleUnpackedArray` isn't tainting the array like it should – other similar methods in that class write to `$array_creation_info->parent_taint_nodes`. That'll be the key.

Taint analysis and unused variable detection share most of the same underlying infrastructure, so there's an equivalent false-negative here: https://psalm.dev/r/0f9a93893b (as alluded to in the above-linked article)

**Comment by weirdan** [comment]
No longer reproducible: psalm.dev/r/405e954d68
