### ISSUE TITLE
Template generics inside callables

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#4485]
Hi, I'm trying to implements templates, but psalm infer return type as `callable(empty): empty` and I don't understand why, is it a bug?

https://psalm.dev/r/eafedd80ab

**Comment by thomasvargiu** [comment]
Sorry, this is the correct snippet:

https://psalm.dev/r/6c5b012d93

**Comment by muglug** [comment]
It's not really a bug.

You're defining a lower-bound for the param, but not an upper bound. A slightly different version of the code helps Psalm understand what's going on by providing the upper bound for `T` early: https://psalm.dev/r/ee47d3ca0f

In a language like Hack you could explicitly pass the template params in the call like `tee<int>(fn (int $a): string => $a)`, setting the upper and lower bound for the value of `T` explicitly, but Psalm has to infer an upper bound and there's nothing for it to use.

**Comment by thomasvargiu** [comment]
@muglug I was playing with templates, and I'm wondering why the same function with a wrapped callable works, and a simple callable not.

https://psalm.dev/r/02085aa6f8

I don't really know the internals, and I don't know if it will be possible, maybe it could be an improvement, but why a templated object works and a callable not? If it works with an object, does it means that psalm can infer types correctly even for closures?

**Comment by muglug** [comment]
You're right, it should, and now it does!
