### ISSUE TITLE
Psalm doesn't recognize callable-string

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#4490]
Example here:
https://psalm.dev/r/d84f9a3de0

I'd expect that `$f` will be a `callable-string`.

**Comment by orklah** [comment]
It would mean Psalm need to know at every moment the full list of every sympol in your namespace to be able to infer any string variable. This is not possible.

Psalm can only infer it after it get passed to is_callable or similar

**Comment by thomasvargiu** [comment]
Right. Thanks.

**Comment by thomasvargiu** [comment]
Sorry, I reopen it.

Shouldn't this be evaluated on function call at least?

https://psalm.dev/r/5e086331bf

**Comment by muglug** [comment]
Nah, I don't see this as a bug

**Comment by thomasvargiu** [comment]
So, just a question... how can create stubs or a Plugin to use const callable-string and be interpreted as relative functions?
There is any way? Some suggestions?

Consider this:
https://github.com/functional-php/fantasy-land/blob/c855c856e70db81032a8a4fd17bd74a58d26a279/src/FantasyLand/functions.php#L7-L12

There is any way to tell Psalm that `FunctionalPHP\FantasyLand\identity` has the same signature of `FunctionalPHP\FantasyLand\identity()` function via plugin?

**Comment by muglug** [comment]
That just seems a little icky, and not very PHP-like.
