### ISSUE TITLE
MixedMethodCall error in documentation example

### ISSUE THREAD

**Issue by ramsey** [vimeo/psalm#4496]
I'm using the `@param class-string<T>` [example from the documentation](https://psalm.dev/docs/annotating_code/templated_annotations/#param-class-stringt), but I'm getting a `MixedMethodCall` error, and I'm not sure the best way to work around this.

Is the example flawed, or am I missing an obvious solution? I've tried using `class_exists($class)`, but that doesn't get rid of the error.

https://psalm.dev/r/2711c84690

**Comment by weirdan** [comment]
The example is outdated. This is valid, though: https://psalm.dev/r/9037ec3f39

**Comment by ramsey** [comment]
So, I need to define that `T` is a `Foo`?

**Comment by muglug** [comment]
Thanks, I've fixed the documentation

**Comment by ramsey** [comment]
I'm still trying to understand the proper use here. It seems that using `T of Foo` is no different than not using a template at all and doing it this way: https://psalm.dev/r/b4c0db41a2

What's the point in using the template with `class-string`, if it needs to be more specific?

**Comment by weirdan** [comment]
The difference is this: https://psalm.dev/r/e599582deb

> So, I need to define that T is a Foo?

Psalm needs to know the constructor signature to make sure you're instantiating it safely. E.g. you can't instantiate `SimpleXMLElement` with that instantiator, as its constructor has a required parameter (https://3v4l.org/f0XQ2). `T as Foo` provides that information, and `@psalm-consistent-constructor` ensures descendant constructor signatures are compatible.
