### ISSUE TITLE
Feature Request: @psalm-postcondition

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#4498]
It would be great if you could specify a type based postcondition, which would be a new contract feature for Psalm. This is different from an assertion because an assertion implies it was already true before the method was called, and all the method does is make sure it was true and then passes the assertion along. A postcondition would cause Psalm to check and see if the code actually ensures the postcondition would be true at the method return. Psalm would also pass along the information as a now true assertion about the types. Here is an example of how it could be used with explanatory code comments:

https://psalm.dev/r/ad868ee42b

**Comment by muglug** [comment]
Not going to add this, sorry. I can appreciate the usefulness of this and typestate-based programming, but I'm also wary of adding more and more bells and whistles to Psalm given, for the most part, it's just me adding features and fixing bugs.

**Comment by still-dreaming-1** [comment]
I understand what you mean. It is hard to be the primary maintainer without much of a supporting team. I think it comes down to how useful the feature is and how much complexity it adds. Personally I think this would make Psalm insanely more useful than it already is, but it sucks that you don't have an entire team building and maintaining Psalm with you. How much would I need to pay your for it to be worth your while? I imagine there is a number...

**Comment by muglug** [comment]
I appreciate the offer, but money's not quite the point of this whole thing.

I want Psalm to be a healthy open-source project without a single point of failure. That only happens if more people roll up their sleeves and try to fix bugs/add features.

**Comment by still-dreaming-1** [comment]
I'm still not sure we have really gotten to the heart of the issue here. Even if you don't add the feature, Psalm still has a single point of failure, and so it's still not a healthy open source project. One primary developer and maintainer is usually enough, as long as it is your job and not something Vimeo only allows you to do in your after hours in addition to your job.

If that is the case, then money is part of the issue. Vimeo doesn't think there is money in paying their employees to work on Psalm, or rather they don't think there is money is selling Psalm or Psalm related services. I don't exactly see a donate option either where you are donating to the project itself, in order to help you hire a team of developers that perhaps could eventually be sponsored by those donations.

I also can't help but to wonder what you really mean in another sense. Are you saying until more core Psalm developer contributors appear, you will not be adding any more features to Psalm? It seems more likely there was a little bit of contradiction in the second sentence of your opening comment which is perhaps hinting at one of the core issues here. You said "I can appreciate the usefulness of this and typestate-based programming, but I'm also wary of adding more and more bells and whistles". Saying you "appreciate the usefulness" of a feature and also referring to it as "more bells and whistles" is at least a little contradictory. I would guess you probably don't think it would be quite as useful as I do, or you see a lot more complexity added by it than a typical feature you would be willing to add, or both.

Hypothetically speaking, if someone were to make a pull request implementing this feature, would you consider merging it, or would you reject it because of the added complexity?

**Comment by muglug** [comment]
You seem to assume that my decision not to implement this feature is a bad omen for Psalm's longevity, when the opposite is true.

> Are you saying until more core Psalm developer contributors appear, you will not be adding any more features to Psalm?

Absolutely not. I'll still be adding and actively supporting features that I/Vimeo find useful, or that I think a sizeable number of Psalm's users will find useful.

> Hypothetically speaking, if someone were to make a pull request implementing this feature, would you consider merging it, or would you reject it because of the added complexity?

I'm happy to accept a pull request for pretty much any feature if I feel it's comprehensive and it's either incredibly simple, incredibly useful, or the author is committed to helping support the feature in the next year or so.

The central issue is bloat: Psalm has more features than pretty much any other static analysis tool (for dynamically-typed languages) that I'm aware of. It supports a very large number of different type annotations, and annotations for immutability and other behaviours like `@psalm-assert`. It performs full-program data flow analysis, has a language server, unused class and method detection, and fixes code automatically.

Each feature takes a toll, implementation-wise, documentation-wise and maintenance-wise. The more complex Psalm becomes, the more daunting it becomes for other people to contribute to the codebase to fix bugs etc.

I still want Psalm to be a usable open-source project five years from now, whether or not I'm actively maintaining it. Sometimes that requires me to say no to things. This is one of those times.

**Comment by still-dreaming-1** [comment]
Okay, so I was right that the real reason is you don't think of it as being as useful of a feature as I would since you are classifying this as bloat, but other new feature ideas potentially not as bloat.

**Comment by muglug** [comment]
Yup. I'm also _strongly_ influenced by what I see happening in other dynamically-typed language's type systems to gauge whether a new Psalm feature might be used heavily.

**Comment by still-dreaming-1** [comment]
Even though offering money may not exactly resolve the issue, I still wonder if there is a number. How much would I or someone I work for have to pay you to implement this feature? Would you do it for $500, $10,000, one million dollars, one billion dollars?

**Comment by ondrejmirtes** [comment]
I don't know want to put words into Matthew's mouth, but I understand that money isn't the issue. Apple, the richest company in the world, says [there's a thousand no's for every yes](https://www.youtube.com/watch?v=XAEPqUtra6E). In healty software development, you have to prioritize and actively battle against complexity, no matter the resources...

**Comment by still-dreaming-1** [comment]
Yes this is absolutely brilliant strategy. Say no to the amazing ideas that would make Psalm incredible and let it waste away in worthless complexity by implementing the okay ones.

**Comment by ondrejmirtes** [comment]
Of course everyone thinks their idea is indispensable and must be implemented 😊
