### ISSUE TITLE
Psalter doesn't add return type on switches

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#4499]
For the following example, if we try the fix button, Psalter will add `: array` in signature:
https://psalm.dev/r/fec30a288a

but for this example:
https://psalm.dev/r/5149aedc01
Psalter only adds the return type in the documentation

Thanks

**Comment by weirdan** [comment]
Looks like Psalm thinks that return is conditional. If you add an unconditional return (say, `return null;`) after the switch native return type will be added just fine: https://psalm.dev/r/16ec47c05c

**Comment by orklah** [comment]
@muglug Would this be difficult to solve? I'd like to try but I'm afraid this could prove difficult for me
