### ISSUE TITLE
Idea: Check for duplicate array keys (plugin/otherwise)

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#450]
I've implemented this [elsewhere](https://github.com/phan/phan/blob/master/.phan/plugins/DuplicateArrayKeyPlugin.php).

E.g. warn about `$v = ['key' => 'value', 'key' => 'othervalue'];`. (This helps catch bugs in long arrays)

This could be improved by adding checks for `$v = [MyClass::CONSTNAME => 'value', MyClass::CONSTNAME => 'othervalue'];`, etc. (global constants, string concatenations, etc.)

**Comment by muglug** [comment]
Yeah, this should be super easy

**Comment by muglug** [comment]
Thanks! This caught five tests that weren't being run.
