### ISSUE TITLE
Psalter doesn't add return type with returning catch blocks

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#4500]
Hi,

For the following example:
https://psalm.dev/r/0a7dc1a7c7

If we click on fix code, Psalter only add documentation where it could add a return type in signature.

Strangely, when we add an unreachable statement after the catch, it suddenly works:
https://psalm.dev/r/8124b89d61

**Comment by weirdan** [comment]
Looks quite similar to #4499 , where that could also be fixed by adding unreachable return.

**Comment by orklah** [comment]
oh nice, I didn't make the connection between the two
