### ISSUE TITLE
Conditional no-return

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#4501]
I have methods in my codebase where they can perform an exit() based on a parameter. For example, redirect:

https://psalm.dev/r/d980e72509

Could this be supported in conditional return?

**Comment by muglug** [comment]
No, I won't add this – I _strongly_ encourage you instead to refactor your code with a `redirectAndExit` (or, alternatively, `redirectAndContinue`)

**Comment by weirdan** [comment]
> No, I won't add this

@muglug , it's too late :rofl:. It works already: https://psalm.dev/r/a6ab3fc875

**Comment by orklah** [comment]
Oh, so it works but I'm not allowed to have `: void` return hint! Not sure what I'll do then!

Thank you both for your answer anyway!
