### ISSUE TITLE
isset() shortcircuiting is not accounted for in certain types

### ISSUE THREAD

**Issue by jnvsor** [vimeo/psalm#4503]
Example: https://psalm.dev/r/abf278700a

There are a lot of errors there, but the interesting one is:

```
ERROR: PossiblyNullArrayAccess - 17:27 - Cannot access array value on possibly null variable $param of type mixed|null
```

This occurs in an elseif 2 lines after a check `if (!isset($param['name']))` - `$param` cannot be null if we've entered that elseif (Neither can `$param['name']`) so this error shouldn't be occurring

**Comment by muglug** [comment]
Simplified to

```php
<?php

function processParam(mixed $param) : void {
    if (rand(0, 1)) {
        $param = null;
    }
    
    if (isset($param['name'])) {
        echo $param['name'];
    }
}
```
