### ISSUE TITLE
String concatenation with mixed value throws MixedOperand error

### ISSUE THREAD

**Issue by davidbyoung** [vimeo/psalm#4506]
https://psalm.dev/r/bff468992d

PHP automatically casts values to strings when concatenating them with a string.  I'd expect both examples in the link to work.

**Comment by weirdan** [comment]
> PHP automatically casts values to strings when concatenating them with a string.

Unfortunately it does, often producing meaningless results like this: https://3v4l.org/Llg0N. I'd say Psalm does a good job preventing you from falling into this trap.

**Comment by muglug** [comment]
Not a bug – I've added more of a description to the issue: https://github.com/vimeo/psalm/commit/43f6921efa4c26f00738b4cfc5188239aa05797a
