### ISSUE TITLE
callable-string issues

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#4508]
Similar issue: #4490 

TL;TR;
- Psalm correctly (?) infer namespace const as callable when there is a function with the same name.
- Psalm correctly (?) infer strings in global namespace as callable when there is a function with the same name.
- **Psalm doesn't infer string class constants as callable string when there is a method with the same name.**
- **When psalm infer callable strings as callable, templates doesn't work.**

*The `?` is because I see they are referenced as `callable`, would be probably better they'll be a `string&callable`?*

# Examples
## const callable string on namespace

I can't reproduce this example with playgroud, so I paste the code.
`version: 4.1.1`

`FunctionalPHP\FantasyLand` namespace code:
```php

namespace MyNamespace;

const identity = 'MyNamespace\identity';

/**
 * @template T
 * @psalm-param T $a
 * @psalm-return T
 *
 * @param mixed $a
 * @return mixed
 */
function identity($a)
{
    return $a;
}
```

Test code:
```php
<?php

use const MyNamespace\identity;

/**
 * @template T
 * @template R
 * @psalm-param callable(T): R $c
 * @psalm-param T $a
 * @psalm-return R
 */
function testFunc (callable $c, $a) {
    return $c($a);
}

/** @psalm-trace $f */
$f = identity;

/** @psalm-trace $v */
$v = testFunc(identity, 'foo');

```

Psalm result:
```
ERROR: Trace - src/test.php:33:1 - $f: string(MyNamespace\identity) (see https://psalm.dev/224)
/** @psalm-trace $f */
$f = identity;

ERROR: Trace - src/test.php:36:1 - $v: T:fn-mynamespace\identity as mixed (see https://psalm.dev/224)
/** @psalm-trace $v */
$v = testFunc(identity, 'foo');

ERROR: InvalidArgument - src/test.php:36:6 - Type string(foo) should be a subtype of T:fn-mynamespace\identity as mixed (see https://psalm.dev/004)
$v = testFunc(identity, 'foo');
```

Debugging Psalm execution **I see that const is inferred as a callable, but templates doesn't work**.
```
$statements_source->node_data->node_types[node] = [
  "obj" => "PhpParser\Node\Expr\ConstFetch",
  "inf" => "impure-callable(T:fn-mynamespace\\identity as mixed):T:fn-mynamespace\\identity as mixed"
]
```

## callable string on class const

Example: https://psalm.dev/r/4fbdc69aa0

No `InvalidArgument` error, so string is recognized as callable, but templates doesn't work.

Debugging Psalm execution **I see that const is inferred as literal string**.
```
$statements_source->node_data->node_types[node] = [
  "obj" => "PhpParser\Node\Expr\ConstFetch",
  "inf" => "string(Test::identity)"
]
```

## callable string on global namespace

https://psalm.dev/r/23fea21f4f

Debugging Psalm execution **I see that string is inferred as a callable, but templates doesn't work**.
Behavior is similar to "const callable string on namespace".

```
$statements_source->node_data->node_types[node] = [
  "obj" => "PhpParser\Node\Scalar\String_",
  "inf" => "impure-callable(T:fn-identity as mixed):T:fn-identity as mixed"
}
```

**Comment by muglug** [comment]
Sorry, as with the other tickets I'm not going to support more than already exists for string callables in templates. Callables are a really hairy part of PHP's type system, and the more Psalm goes down the road the more complex it becomes.
