### ISSUE TITLE
Expose methods to convert PhpParser\Node for a constant literal/reference to an equivalent PHP array/scalar

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#451]
(E.g. for a `PHPParser\Node\Expr\Array_` generated from `"['some_string']"` to be converted to the PHP literal `[0 => 'some_string']`, or for `"[SomeClass::CONST => 'value' . 'suffix']"` to be converted to `['ResolvedConstant' => 'valuesuffix']`

Something along the lines of [this example API](https://github.com/phan/phan/blob/master/src/Phan/AST/ContextNode.php#L1797-L1809)

- E.g. that API allows specifying if array keys are required by the callee, if array values are required, etc.

This could be used to improve the StringChecker plugin, or to develop new plugins such as #450 (detecting duplicate array keys).

Or to check if `call_user_func(MyClass::CALLBACK_NAME, 'arg')` is a valid callable and a valid use of that callable. (a possible separate GitHub issue, psalm doesn't warn)

New functionality that might have to be added:

- Add ability to look up the **resolved value** of a class constant or global constant by the constant name (And possibly cache it in the ClassStorage)
- Expose public API to resolve the value of a PhpParser\Node to an array/scalar (which uses the constant lookup).
   (Accounting for aliases, namespaces, etc.)

(My use case is extracting a public constant (with nested arrays of int/strings to strings/arrays) from the definition of a class constant with a given name, because a union type would depend on that field.)

**Comment by muglug** [comment]
Basic supported added in https://github.com/vimeo/psalm/pull/707
