### ISSUE TITLE
Conditional return on interface template doesn't work

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#4511]
Using a conditional return, behaviour is different when defined in interface or in a class.

With class docblock:
https://psalm.dev/r/3cc2367e01

Using interface docblock:
https://psalm.dev/r/4484822d18

I would expect that conditional return works when defined in interfaces too.

Another thing I noticed is that `(T is callable ? something : else)` doesn't work.

**Comment by thomasvargiu** [comment]
Probably related to #4524

**Comment by muglug** [comment]
Do you have an example of it breaking without `never-return`?

**Comment by muglug** [comment]
When both a docblock return type and a signature return type are given, Psalm performs a trivial check to see whether the docblock is more specific than the signature. If that check passes, the docblock is inheritable. Here that check isn't passing, so no inheritance of the docblock occurs (the implementing function specifies its own return type `A`.

Removing `A` from the signature allows this behaviour: https://psalm.dev/r/68e87c0681

**Comment by muglug** [comment]
`never-return` wasn't intended for conditional return types, use them there at your own risk

**Comment by muglug** [comment]
Here's the trivial check if you want to add support for conditional return types, but it wouldn't be a simple change: https://github.com/vimeo/psalm/blob/3803bbfce0e5706f4bb3d56744c0cc71af9ccfa7/src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php#L303
