### ISSUE TITLE
Template key type for array is not properly checked

### ISSUE THREAD

**Issue by tux-rampage** [vimeo/psalm#4514]
Most of the following annotations happen by accident. Besides this would be valid for `Traversable` and potentially for `iterable`, it is not for arrays. Array-Keys in PHP must be either `string` or `int`.

https://psalm.dev/r/50ea66a265

**Comment by weirdan** [comment]
Psalm interprets `array<T>` as `array<array-key, T>`: https://psalm.dev/r/82eb9ca7a4

**Comment by muglug** [comment]
This is not a bug

**Comment by muglug** [comment]
`array-key` is a super-type of `string` and `int`

**Comment by tux-rampage** [comment]
I see, thanks for clearification.
