### ISSUE TITLE
PossiblyInvalidOffset should be emitted under more circumstances?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#452]
This is documented as "Emitted when it’s possible that the array offset is not applicable to the value you’re trying to access."

Desired: When at least one of the types in the offset's union type is a valid offset of at least one of the types in the value's union type, PossiblyInvalidOffset should be emitted. (If the type of the value can't be determined, assuming `int|string` would be acceptable, not sure what's being done)

Observed: When at least one of the types in **the offset's** union type is valid (and another is invalid), InvalidArrayOffset is emitted.

If the current behavior is expected, more tests covering it would be desirable.

(The behavior may have changed recently, haven't checked)

```php
<?php
/**
 * @param array<string,stdClass> $data
 * @param array|string $offset (real use cases would be more complicated than this)
 * @return ?stdClass
 */
function testOffset($data, $offset) {
    return $data[$offset] ?? null;  // InvalidArrayOffset observed, desired PossiblyInvalidArrayOffset
}

/**
 * @param array<string,stdClass> $data
 * @param int|string $offset (real use cases would be more complicated than this)
 * @return ?stdClass
 */
function testOffset2($data, $offset) {
    return $data[$offset] ?? null;  // InvalidArrayOffset observed, desired PossiblyInvalidArrayOffset
}
```

**Comment by muglug** [comment]
This appears fixed :)
