### ISSUE TITLE
redundant isset/empty

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#4520]
should psalm emit that the isset() or empty() is redundant ?

https://psalm.dev/r/16fb3f077b

**Comment by muglug** [comment]
It's a bit bad, but `empty` and `!isset` are strictly different things

**Comment by weirdan** [comment]
@muglug If it's evaluated left-to-right, shouldn't `empty($var) || !isset($var)` trigger a redundant condition on the `!isset()` part?
