### ISSUE TITLE
The inferred type 'object' does not match the declared return type 'T:fn-stub::extend as object'

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#4521]
I have a `extend()` function

```php
    /**
     * @psalm-template T of object
     * @psalm-param    T $stub
     * @psalm-return   T
     */
    public static function extend(object $stub) : object
    {
        $class = get_class($stub);

        return self::create($class);
    }
```

that extracts classname and calls another function that constructs a class through reflection

```php
    /**
     * @psalm-template T of object
     * @psalm-param    class-string<T> $class
     * @psalm-return   T
     */
    public static function create(string $class) : object
    {
        $reflection = new ReflectionClass($class);

        $stub = $reflection->newInstanceWithoutConstructor();

        return $stub;
    }
```

Seems like psalm is not able to infer return type based on type of object passed into `extend()`. There's some incompatibility between generic annotations 🤔 

> The inferred type 'object' does not match the declared return type 'T:fn-stub::extend as object' for Stub::extend

for `self::create($class)`

https://psalm.dev/r/c69862e11d

**Comment by orklah** [comment]
This is really weird. I turned it upside down without managing to find a way to make it work. Might be related to templates in static methods?

**Comment by weirdan** [comment]
No longer reproducible.

**Comment by weirdan** [comment]
https://psalm.dev/r/c69862e11d
