### ISSUE TITLE
Implement nullsafe short-circuiting for methods

### ISSUE THREAD

**Issue by ondrejmirtes** [vimeo/psalm#4523]
From the RFC: https://wiki.php.net/rfc/nullsafe_operator

> This RFC proposes full short circuiting. When the evaluation of one element in the chain fails the execution of the entire chain is aborted and the entire chain evaluates to null. The following elements are considered part of the chain.

- Array access ([])
- Property access (->)
- Nullsafe property access (?->)
- Static property access (::)
- Method call (->)
- Nullsafe method call (?->)
- Static method call (::)

Playground link: https://psalm.dev/r/4f5df32590
Runtime proof: https://3v4l.org/GqDeo

Line 19 is fine, but line 13 should also indicate nullable result.

Feel free to also check behaviour for ArrayDimFetch, StaticCall, and StaticPropertyFetch.

**Comment by iluuu1994** [comment]
Just noticed the same issue. Somewhat simplified example. https://psalm.dev/r/1a96184835
