### ISSUE TITLE
Wrong template infer inheritance

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#4524]
**EDIT**: see comment below, this isn't a problem with stubs, I can reproduce it on playground: https://psalm.dev/r/72dd0c2084

I'm creating a plugin with stubs, and I created a [dedicated branch](https://github.com/thomasvargiu/psalm-plugin-fantasy-land/tree/98d0feea3fb02e74b91f5e9692be5535585e7540) for this issue.

The problem is with method [`Identity::map()`](https://github.com/thomasvargiu/psalm-plugin-fantasy-land/blob/98d0feea3fb02e74b91f5e9692be5535585e7540/stubs/Useful/Identity.phpstub#L37-L44).
It's the implementation from the interface [Functor](https://github.com/thomasvargiu/psalm-plugin-fantasy-land/blob/98d0feea3fb02e74b91f5e9692be5535585e7540/stubs/Functor.phpstub), which is another stub with the same signature.

Psalm doesn't recognize the return type as you can see from the CI (https://github.com/thomasvargiu/psalm-plugin-fantasy-land/runs/1376311199?check_suite_focus=true#step:8:50).

So, calling the following method with `fn (T): int` returns a `Functor<empty>` instead a `Functor<int>`.
```php
/**
 * @template T
 */
interface Functor
{
    /**
     * @template F
     * @psalm-param callable(T): F $function
     * @psalm-return Functor<F>
     */
    public function map(callable $function) : Functor;
}
```

The weird thing is that if I remove the docblock from the the [original interface file](https://github.com/functional-php/fantasy-land/blob/1.0.0/src/FantasyLand/Functor.php#L9-L16) it works as expected.

**Comment by thomasvargiu** [comment]
The problem isn't just on stubs:

https://psalm.dev/r/72dd0c2084

**Comment by thomasvargiu** [comment]
Simplified: https://psalm.dev/r/0b06235633

**Comment by muglug** [comment]
Even more concise version:

```
<?php

class Foo {}
class FooChild extends Foo {}

/**
 * @template T
 */
interface A {
    /**
     * @template U
     * @param callable(T): U $func
     * @return U
     */
    function test(callable $func);
}

/**
 * @template T
 * @template-extends A<T>
 */
interface B extends A {}

/**
 * @template T
 * @template-extends B<T>
 */
interface C extends B {}

/**
 * @param B<Foo> $b
 */
function first(B $b) : void {
    $f = fn (FooChild $foo) : FooChild => $foo;
    $b->test($f); // fails
}

/**
 * @param C<Foo> $c
 */
function second(C $c) : void {
    $f = fn (FooChild $foo) : FooChild => $foo;
    $c->test($f); // should fail but does not
}
```

**Comment by thomasvargiu** [comment]
@muglug Isn't resolved yet.

If `Pointed` has a a docblock, it doesn work: https://psalm.dev/r/40e629c932

It works:
- If I remove docblock from `Pointed`: https://psalm.dev/r/948622b9f6
- Removing the `B` interface from the interface chain: https://psalm.dev/r/ff098b1e0a

**Comment by muglug** [comment]
Yeah, two inherited interfaces each with their own docblock confuses Psalm – it's not immediately clear which docblock should take precedence.

**Comment by thomasvargiu** [comment]
So, should you open this issue again?

**Comment by muglug** [comment]
No – I'd encourage you instead to use the workarounds – either duplicating the docblock

**Comment by muglug** [comment]
Sorry, I was being a bit lazy.

**Comment by thomasvargiu** [comment]
@muglug I was about to open a PR.

@muglug I was fixing it too (I was running tests), changing the following line inverting parameters to mantain an ordered list of `parent_interfaces` and consequentially of `documenting_method_ids` respecting the interface chain.

https://github.com/vimeo/psalm/blob/b7551e712a46dc2f45683672eb5c4783d9b7c778/src/Psalm/Internal/Codebase/Populator.php#L707

**Comment by muglug** [comment]
Problem is you can't always rely on that ordering – `tests/ArrayAssignmentTest.php` was breaking in that scenario because there's something that re-adds a parent interface.

**Comment by muglug** [comment]
But thanks, I always appreciate PRs!

**Comment by thomasvargiu** [comment]
@muglug I think I found another issue about infer and inheritance:

https://psalm.dev/r/7f937bb1d0

Since `Foo::test()` returns `Foo`, which implements `B`, which implements `A`, the signature should be valid.
Instead Psalm requires that `Foo::test()` returns a type of `B`.
