### ISSUE TITLE
MissingThrowsDocblock is not propagated for callables

### ISSUE THREAD

**Issue by NickMolloy** [vimeo/psalm#4528]
https://psalm.dev/r/48240aa0e7

**Comment by weirdan** [comment]
What would you expect though?

**Comment by NickMolloy** [comment]
I would expect the anonymous function to be marked as requiring a `@throws` annotation because `a` which it calls can throw. In the example function `b` does the same as the anonymous function and does get marked.

**Comment by muglug** [comment]
Nah, it's not clear that the function throws, and there's no feasible way to annotate a throwing callable.

**Comment by leighman** [comment]
Makes the throws docblock stuff a little bit useless. Can psalm not keep track in a similar way to the taint analysis stuff? I would assume that `callable` could throw but `pure-callable` could not, maybe?

**Comment by muglug** [comment]
> Makes the throws docblock stuff a little bit useless

No it doesn't

> Can psalm not keep track in a similar way to the taint analysis stuff?Can psalm not keep track in a similar way to the taint analysis stuff?

Not really – the "taint analysis stuff" is very complex, and it's very computationally expensive. It's not a cure-all.

>  I would assume that `callable` could throw but `pure-callable` could not, maybe?

No – pure callables can still throw, in the same way that pure functions are allowed to throw. Handling those exceptions is generally impure, though.

**Comment by NickMolloy** [comment]
What about the case where the callable is throwing the exception directly? https://psalm.dev/r/226a6e3931

I would expect that `doSomething` requires a `@throws` annotation.
