### ISSUE TITLE
Uncaught InvalidArgumentException analyzing ternary operator for empty ObjectLike (i.e. `array{}`)

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#453]
This happens on the latest master branch.
Code to reproduce the crash is below.

Expected: Psalm does not crash, no issues are emitted by psalm when analyzing the below code
Observed: Psalm crashes with an uncaught InvalidArgumentException. It seems to be an edge case with merging ternary branches when a variable in scope is an empty ObjectLike (`array{}`) 

```php
<?php
class User {
    public function isValid() : bool {
        return true;
    }
}

class SomeAPI {
    /**
     * @param array{} $input_params an empty array
     * @return string
     */
    public function myMethod($input_params) {
        $user = new User();
        if (!$user || !$user->isValid()) {  // Aside: The !$user check is obviously redundant, but if I don't leave it in, Psalm doesn't crash.
            return 'value';
        }

        $result = rand() % 2 > 0 ? 'en' : 'fr';  // The uncaught InvalidArgumentException happens when analyzing this line, when trying to combine the possible types of $input_params
        return $result;
    }
}
```

The error message was:

```

Fatal error: Uncaught InvalidArgumentException: You must pass at least one type to combineTypes in /path/to/psalm/src/Psalm/Type.php:567
Stack trace:
#0 /path/to/psalm/src/Psalm/Type.php(513): Psalm\Type::combineTypes(Array)
#1 /path/to/psalm/src/Psalm/Checker/Statements/Expression/TernaryChecker.php(82): Psalm\Type::combineUnionTypes(Object(Psalm\Type\Union), Object(Psalm\Type\Union))
#2 /path/to/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(230): Psalm\Checker\Statements\Expression\TernaryChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\Ternary), Object(Psalm\Context))
#3 /path/to/psalm/src/Psalm/Checker/Statements/Expression/AssignmentChecker.php(107): Psalm\Checker\Statements\ExpressionChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\Ternary), Object(Psalm\Context))
#4 /path/to/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(90): Psalm\Che in /path/to/psalm/src/Psalm/Type.php on line 567
```

**Comment by TysonAndre** [comment]
The way the ObjectLike values get merged in Type::combineTypes seems to be related. Adding has_objectlike_entries alongside the array in TypeCombination might make more sense than the count check? (And check near the end of Type::combineTypes for has_objectlike_entries if the possible types are empty or don't contain any arrays or ObjectLike)

```
627         if (count($combination->objectlike_entries) &&                                     
628             (!isset($combination->type_params['array'])                                    
629                 || $combination->type_params['array'][1]->isEmpty())                       
630         ) {     
631             $new_types[] = new ObjectLike($combination->objectlike_entries);               
632             
633             // if we're merging an empty array with an object-like, clobber empty array    
634             unset($combination->type_params['array']);
635         }   
```

**Comment by muglug** [comment]
First off `array{}` definitely should not be allowed, so I'll fix that.

**Comment by TysonAndre** [comment]
Okay.

My use case was automatically generating types for API params in a plugin.
Some of those APIs needed to have a parameter array, but those didn't have any fields, so I wanted the PHPdoc to reflect that. I suppose `array<empty>` (something like that) would be more appropriate (Is there any way to specify that from PHPdoc?)

Other thoughts:

`$x = ['a' => 'value']; unset($x['a'])` needs to be handled if `array{}` becomes invalid.

Types might be less accurate for `$value = rand() % 2 > 0 ? [] : ['key' => 'value']` without `array{}`

**Comment by muglug** [comment]
> Some of those APIs needed to have a parameter array, but those didn't have any fields, so I wanted the PHPdoc to reflect that

Sorry, I don't quite follow – could you give an example?

**Comment by muglug** [comment]
> $x = ['a' => 'value']; unset($x['a']) needs to be handled if array{} becomes invalid.

I created #455 for that

**Comment by TysonAndre** [comment]
My example:

https://github.com/TysonAndre/psalm/blob/master/tests/integration/plugin_test/src/000_example_api.php is an example API (Extremely simplified). The expected union types are documented in `const METHOD_FILTERS = [`
https://github.com/TysonAndre/psalm/blob/master/examples/APIFilterPlugin.php is a simplified example of a plugin I'm working on.
https://github.com/TysonAndre/psalm/blob/master/tests/integration/plugin_test/expected/000_example_api.php.expected is the expected output of the plugin I'm working on, on that example API.

Imagine that it's invoked like `$api->{$methodName}(filter_input_parameters($rawParamData, $api::METHOD_FILTERS[$methodName]))`, with exactly one argument that is the filtered parameter array. (The code that does that isn't included in the example)

some API methods wouldn't need any parameters, e.g.

```
       METHOD_FILTERS = ['getInformationAboutMe' => []];  // 
```

If the implementation of getInformationAboutMe($params) accessed `$params['someFieldNotInFilters']`, then that would be a bug, and should be detected.
