### ISSUE TITLE
UnusedParam/UnusedVariable false positives in extremely complex functions

### ISSUE THREAD

**Issue by duskwuff** [vimeo/psalm#4530]
Psalm only appears to track variable usage to a maximum depth of 100 or so. If a variable or parameter is used in a way that depends on more than 100 nested operations (including assignments), it is treated as unused.

This is, obviously, a contrived example. The same issue also arises with more useful expressions. :)

https://psalm.dev/r/b1f98a6788

**Comment by muglug** [comment]
I can just bump that up to 200 – any function with more nesting than that is seriously pathological

**Comment by duskwuff** [comment]
Hmm, that feels a little less than ideal. I'm still concerned that there isn't any warning when the limit is hit -- and if psalm is running in psalter mode, it will "fix" the errors by trimming active code out of the affected functions.
