### ISSUE TITLE
Bug with partially templated callable?

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#4531]
Related to #4485 

There is a problem when I don't explicity set a template for a callable return type.

https://psalm.dev/r/ec02d9ad54

If I ignore the return type template for the callable input, even if I'm not using it, checks fail.
If I put a template, it works as expected.

In this case I don't care about callable return type, so I shouldn't need to specify a template.

**Comment by muglug** [comment]
There's no feasible way for Psalm to infer this type correctly, so it chooses the empty type (similar to a bottom type).

**Comment by muglug** [comment]
Correction: there is a way, and now it does.
