### ISSUE TITLE
False negative or by design?

### ISSUE THREAD

**Issue by b1rdex** [vimeo/psalm#4534]
https://psalm.dev/r/f1b281b967

1. Should it report while() condition as a duplicated condition?
2. Should it report an infinite loop? I'm not sure if there is such a rule in Psalm.

The code is extracted from https://github.com/phpstan/phpstan/issues/3995.
Feel free to join the discussion there.

**Comment by weirdan** [comment]
`RedundantCondition` is now reported: https://psalm.dev/r/1e09efc292
