### ISSUE TITLE
Why PossiblyUndefinedStringArrayOffset here

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#4535]
https://psalm.dev/r/8434aa7bca

There is way to win `PossiblyUndefinedStringArrayOffset` issue without explicit type annotation like this?

```php
print_r(
    // Is possibly undefined? Why?
    group(getUsers(),
    /**
     * @param array{id: string, group_id: string} $_
     */
    fn(array $_): string => $_['group_id'])
);
```

**Comment by muglug** [comment]
No.

**Comment by muglug** [comment]
Psalm doesn't know that the arguments passed to the closure first result from the `getUsers` call parameters. It can, though, detect a bug when the types disagree: https://psalm.dev/r/2a241d684b

**Comment by klimick** [comment]
@muglug thanks for answer. But.

Why it works fine? https://psalm.dev/r/279fe26579

Functions can't have the same behavior due to design?

**Comment by muglug** [comment]
@klimick it's about when Psalm can infer types – in the latter example it's already inferred that it's working on an array with `group_id`, vs the former where that inference happens within the same set of args.
