### ISSUE TITLE
Left operand considered mixed when passed through closure's use()

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#4536]
https://psalm.dev/r/405c3335ba

Having variable `$totalQueryDuration` that is passed to callable using `use(&$totalQueryDuration)`, the variable type is considered mixed event though it's obviously `int`:

```php
$totalQueryDuration = 0;
array_map(
    /**
         * @param array{executionNs: int} $query
         *
         * @return array{duration: float}
         */
    static function (array $query) use (&$totalQueryDuration) : array {
        $executionNs = $query['executionNs'];
        $totalQueryDuration += $executionNs;

        return [
            'duration' => $executionNs / 1000 / 1000
        ];
    },
    []
);
```

_I tried to simplify it and do not use `array_map` but I'm unable to type the callable input and output_ https://psalm.dev/r/e9915b81d8

When property is used for storing the value, the error is not thrown https://psalm.dev/r/9431d73d6c

**Comment by muglug** [comment]
passed-by-ref uses in closures are effectively unsound (there are a bunch of similar tickets).

You can use a traditional look here instead. It's more succinct, runs faster in PHP, and makes Psalm happy.

```php
<?php

$totalQueryDuration = 0;

$results = [];

foreach ($queries as $query) {
    $executionNs = $query['executionNs'];
    $totalQueryDuration += $executionNs;

    $results[] = [
        'duration' => $executionNs / 1000 / 1000
    ];
}
```

**Comment by simPod** [comment]
I like to make Psalm happy. Thanks! 🚀
