### ISSUE TITLE
Wrong inheritance fetching return type

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#4537]
Same as #4524 but for return types, it seems that return types as not fetched from the right parent class/interface.

I don't know if this is the right example, but debugging I noticed this bug.

https://psalm.dev/r/7f937bb1d0

Since Foo::test() returns Foo, which implements B, which implements A, the signature should be valid.

**Comment by muglug** [comment]
Simplified without generics: https://psalm.dev/r/d3c5472f7a
