### ISSUE TITLE
Wrong template inheritance with stubs

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#4539]
Seems the same resolved issue #4524, but with stubs.

See this project:

https://github.com/thomasvargiu/psalm-issues-tests/tree/wrong-template-inheritance-with-stubs

Where there are:
- [original source](https://github.com/thomasvargiu/psalm-issues-tests/tree/wrong-template-inheritance-with-stubs/src)
- [stubs](https://github.com/thomasvargiu/psalm-issues-tests/tree/wrong-template-inheritance-with-stubs/stubs)
- [test file](https://github.com/thomasvargiu/psalm-issues-tests/blob/wrong-template-inheritance-with-stubs/test.php)

In the CI you can see:
- [used stubs](https://github.com/thomasvargiu/psalm-issues-tests/runs/1391933979?check_suite_focus=true#step:7:1)
- [test file and psalm result](https://github.com/thomasvargiu/psalm-issues-tests/runs/1391933979?check_suite_focus=true#step:8:1)

```php
$identity = new Original\Identity('foo');
$function = fn (string $a): int => random_int(-1, 1);

/** @psalm-trace $value */
$value = $identity->map($function);
``` 

```
ERROR: Trace - test.php:9:1 - $value: Original\Functor<empty> (see https://psalm.dev/224)
/** @psalm-trace $value */
$value = $identity->map($function);
``` 

When instead I expect `$value` as `Original\Functor<int>`.
If I remove docblock from the original file it works.

@muglug I added you to the repository, so you can run tests again. It uses psalm master branch.

**Comment by muglug** [comment]
Before I delve into this, mind checking to see if it works with latest master?

**Comment by thomasvargiu** [comment]
Yeah it works! Thanks!

**Comment by thomasvargiu** [comment]
@muglug You're so fast!
I was reopening it founding another bug introduced in last commits! And you already resolved! Thanks for your work!
I'm not confident yet with Psalm internals to open a PR in a short time!

**Comment by muglug** [comment]
Yeah, this fix was not trivial: https://github.com/vimeo/psalm/commit/3dd185e3956bb2381f1dbe04e47fc44608ca422b (and broke Psalm itself, leading to two additional fixes).

If you want to brush up on Psalm's internals there are a ton of bugs here: https://github.com/vimeo/psalm/issues?q=is%3Aopen+is%3Aissue+label%3A%22easy+problems%22
