### ISSUE TITLE
Psalm incorrectly reports Inaccessible property inside unset

### ISSUE THREAD

**Issue by kapitancho** [vimeo/psalm#4548]
This sample code show the issue:
https://psalm.dev/r/5708e0f636

There is a class marked as psalm-immutable and a unsetting a value in a completely unrelated array should be no problem unset($a[$test->value]);
Instead an 

> ERROR: InaccessibleProperty - test::$value is marked readonly
is reported.

**Comment by muglug** [comment]
Dupe of #4529
