### ISSUE TITLE
array-key of array returned by `explode()` cannot be negative

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#4551]
this should error, because the array key cannot exist

https://psalm.dev/r/c01f81a66f

would this work in case `explode` would return a `list` instead of a `array`?

**Comment by orklah** [comment]
Weird, explode already returns a list:
https://psalm.dev/r/5b4dcff020

In fact, Psalm will warn about PossiblyUndefinedIntArrayOffset with `1` but not with `-1`:
https://psalm.dev/r/93e5a4bf94
