### ISSUE TITLE
Arguments as taint source don't yield results

### ISSUE THREAD

**Issue by LukasReschke** [vimeo/psalm#4556]
I am trying to implement a custom taint source for [Nextcloud](https://github.com/nextcloud/server). Nextcloud uses it's own AppFramework to handle requests, which uses function arguments to pass user-input.

A simple controller could look like the following:

```php
<?php

class NoteController extends OCP\AppFramework\Controller {
    public function index(string $userInput1, string $userInput2) {
       shell_exec($userInput1);
    }
}
```

I managed to write [a plugin implementing `AfterClassLikeAnalysisInterface` which would detect a Controller class and then assign a taint source to all parameters](https://gist.github.com/LukasReschke/b23a7a5c64fb3b2b343e638c546af04f). However, it was unable to find the sample flow above.

I then tried a simplified taint plugin(using `AfterFunctionLikeAnalysisInterface` instead), which would mark all parameters of all functions as tainted. And even that one didn't yield any results:

```php
<?php

use PhpParser;
use Psalm\Codebase;
use Psalm\CodeLocation;
use Psalm\Context;
use Psalm\FileManipulation;
use Psalm\Plugin\Hook\AfterFunctionLikeAnalysisInterface;
use Psalm\StatementsSource;
use Psalm\Type\TaintKindGroup;

class AnyParameterTainter implements AfterFunctionLikeAnalysisInterface
{
    public static function afterStatementAnalysis(
        PhpParser\Node\FunctionLike $stmt,
        Psalm\Storage\FunctionLikeStorage $classlike_storage,
        Psalm\StatementsSource $statements_source,
        Psalm\Codebase $codebase,
        array &$file_replacements = []
    ): ?bool {
        foreach ($stmt->params as $param)
        {
            $expr_type = new Psalm\Type\Union([new Psalm\Type\Atomic\TString()]);
  
            $expr_identifier = 'ControllerParameter'
                . '-' . $statements_source->getFileName()
                . ':' . $param->var->getLine() 
                . ':' . $param->var->name;

            if ($expr_type) {
                $codebase->addTaintSource(
                    $expr_type,
                    $expr_identifier,
                    TaintKindGroup::ALL_INPUT,
                    new CodeLocation($statements_source, $param->var)  // Note: I also tried $param instead of $param->var
                );
            }
        }
        return null;
    }
}
```

Am I missing something here, or is there possibly a Psalm bug that prevents the flow to be tracked?

**Comment by muglug** [comment]
The expression identifier needs to match the one generated in `DataFlowNode::getForMethodArgument` from this call: 

https://github.com/vimeo/psalm/blob/4e8fb9c37f182f9f556f2d2d95d7e1d824490175/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php#L1267-L1272

That's a little fiddly – let me know how I can improve the API

**Comment by LukasReschke** [comment]
Thanks for the reply, @muglug. Much appreciated 🚀 

Using a matching expression identifier works indeed. This was somewhat unexpected to me, as [the documentation](https://psalm.dev/docs/security_analysis/custom_taint_sources/) seems to make it look one could take any arbitrary globally unique identifier:

```php
// should be a globally unique id
// you can use its line number/start offset
$expr_identifier = '$bad_data'
   . '-' . $statements_source->getFileName()
   . ':' . $expr->getAttribute('startFilePos');
```

Some thoughts here from my side:

1. Figuring out the expected identifier doesn't seem straight forward and relies on internal Psalm behaviour not changing. A clear helper functionality would certainly be helpful. (but maybe I just didn't find it 😄 )
2. From my experience with dealing with Static Analysis on a big scale, having to write code for new sources can put off some people. (e.g. think about penetration testers without much coding experience). - Having a simple JSON configuration file to mark function arguments/returns as taint/sink would probably be helpful for these. (and could potentially even result in Psalm being used at security consultancies for security audits)

Anyhow, I realize that this is wishful thinking and may not be a priority at all. So feel to dismiss this, no hard feelings. Psalm is already awesome and superb as-is ⭐ 

For future references (hello dear search machine user), this is the solution that I came up ultimately. There could be further refining on the expression types (e.g. int, bool), as right now everything would be treated as a string:

```php
<?php

use PhpParser;
use Psalm\Codebase;
use Psalm\CodeLocation;
use Psalm\Context;
use Psalm\FileManipulation;
use Psalm\Plugin\Hook\AfterFunctionLikeAnalysisInterface;
use Psalm\StatementsSource;
use Psalm\Type\TaintKindGroup;

class AppFrameworkTainter implements AfterFunctionLikeAnalysisInterface
{
    public static function afterStatementAnalysis(
        PhpParser\Node\FunctionLike $stmt,
        Psalm\Storage\FunctionLikeStorage $classlike_storage,
        Psalm\StatementsSource $statements_source,
        Psalm\Codebase $codebase,
        array &$file_replacements = []
    ): ?bool {
        if($statements_source->getFQCLN() != null) {
            if($codebase->classExtendsOrImplements($statements_source->getFQCLN(), \OCP\AppFramework\Controller::class)) {
                if($stmt instanceof PhpParser\Node\Stmt\ClassMethod) {
                    if($stmt->isPublic() && !$stmt->isMagic()) {
                        foreach ($stmt->params as $i => $param)
                        {
                            $expr_type = new Psalm\Type\Union([new Psalm\Type\Atomic\TString()]);
                            $expr_identifier = (strtolower($statements_source->getFQCLN()) . '::' . strtolower($classlike_storage->cased_name) . '#' . ($i+1));

                            if ($expr_type) {
                                $codebase->addTaintSource(
                                    $expr_type,
                                    $expr_identifier,
                                    TaintKindGroup::ALL_INPUT,
                                    new CodeLocation($statements_source, $param)
                                );
                            }
                        }
                    }
                }
            }
        }
        return null;
    }
}
```

**Comment by muglug** [comment]
> Having a simple JSON configuration file to mark function arguments/returns as taint/sink would probably be helpful for these.

I generally prefer stubs with docblocks over config files, as stubs can eventually be integrated into the project code if desired (and Psalm already supports a bunch of different taint annotations).

Here I don't think there's a neat annotation (or even config) that would capture the behaviour.

>  (and could potentially even result in Psalm being used at security consultancies for security audits)

If they want to contribute to the project, the code's open-source :)
