### ISSUE TITLE
`@return array|T` wrongly interpreted as empty array

### ISSUE THREAD

**Issue by gharlan** [vimeo/psalm#4557]
https://psalm.dev/r/7e79d62beb

**Comment by staabm** [comment]
Maybe its the same problem: https://psalm.dev/r/d4c1bfe432

I don't think psalm should render an error because it cannot know this index will not exist (and php-src does not error/emit warnings when `unset()`-ing keys which might not exist

**Comment by orklah** [comment]
Both examples don't emit issues anymore
