### ISSUE TITLE
Weird behaviour of value-of type

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#4558]
I have a couple of questions.

Is this behavior legal for the key-of?
https://psalm.dev/r/5072cdab18

And if it's legal. Why does value-of behave the same as key-of?

This case looks logical, but it does not work as expected (if you refer to the example from the key-of)
https://psalm.dev/r/516948df7b

**Comment by muglug** [comment]
Right, sorry – `value-of` is not supported for templates, only `key-of` is.
