### ISSUE TITLE
PossibilyNullIterator and PossiblyInvalidIterator on preg_filter($array) result

### ISSUE THREAD

**Issue by mstilkerich** [vimeo/psalm#4561]
Hello,

  I am getting spurious errors reported by psalm when attempting to iterate an array returned by the `preg_filter` PHP function.

According to the [preg_filter doc](https://www.php.net/manual/en/function.preg-filter.php):

> Returns an array if the subject parameter is an array, or a string otherwise.
> If no matches are found or an error occurred, an empty array is returned when subject is an array or NULL otherwise. 

In my case, psalm knows that `$subject` is an array, so according to the above it can be assumed an array will be returned by `preg_filter`, even in case of error. Consequently, psalm should throw neither of these error messages which are based on either a `null` or a `string` return value.

Snippet:
https://psalm.dev/r/fa931259f1

(I know this is a very specific case and preg_filter may return null or a string given different parameters, but it would nevertheless be great if psalm could handle this without throwing errors)

**Comment by orklah** [comment]
Hey!

This should be pretty easy to add, you just have to copy the stub made for preg_replace here:
https://github.com/vimeo/psalm/blob/master/stubs/CoreGenericFunctions.phpstub#L654

And adapt it for preg_filter.

Do you want to try to propose a PR?

**Comment by mstilkerich** [comment]
Thanks for the hint, that really was easy to fix.
