### ISSUE TITLE
Incorrect handling of `object` union?

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#4565]
https://psalm.dev/r/b82584869b

The union type does not look correct here.
If it was correct, I would expect to be able to distinguish cases by using `property_exists`.

**Comment by muglug** [comment]
This is identical, basically, to https://github.com/vimeo/psalm/issues/4566 – Psalm doesn't support structural typing on arrays or objects

**Comment by leighman** [comment]
In this case i would at least expect consistent behaviour between `object{}` and `array{}`?
