### ISSUE TITLE
Weird `@psalm-trace` when using `array_key_exists`

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#4566]
https://psalm.dev/r/773401a5a6

`array{'\'id\'': mixed, a?: int, b?: bool, id: string}` doesn't look correct

**Comment by muglug** [comment]
Psalm doesn't have structural typing for arrays, and likely never will. Use objects instead!

**Comment by weirdan** [comment]
@muglug the trace output look wrong though.
