### ISSUE TITLE
Incorrect PossiblyFalseOperand

### ISSUE THREAD

**Issue by gharlan** [vimeo/psalm#4567]
https://psalm.dev/r/530d68cf2f

**Comment by weirdan** [comment]
Why do you think it's incorrect? Left branch of `||` eliminates `true` out of `bool|int`, leaving `false|int` (`(bool|int)&!true => false|int`) to be handled by the right branch.

**Comment by gharlan** [comment]
>  Left branch of || eliminates true out of bool|int, leaving false|int

Correct. But the right branch is `$checkFlag === ($checkFlag & $flag)`. Psalm says it isn't falsable. But it is falsable, for `$flag = false`, `$flag = 1`, etc.
https://3v4l.org/rT8EQ

**Comment by gharlan** [comment]
Ah! I have misinterpreted the message. Right operand is just `$flag` of `$checkFlag & $flag`, and psalm disallows to use false for bitwise operands.
So I should add an explicit condition for `false`, like this:

```php
if (true === $flag || false !== $flag && $checkFlag === ($checkFlag & $flag)) {}
```

Result is the same, but I agree, that it is a good rule to forbid booleans for bitwise operands.
