### ISSUE TITLE
Different issue type for passing extra fields where an ObjectLike array is expected?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#457]
Observed: InvalidScalarArgument - src/objectlike.php:14:17 - Argument 1 of print_field expects array{field:string}, array{field:string, otherField:string} provided
Expected: UnexpectedExtraFieldInArgument for invocation of print_field (This issue type should be emitted when the argument would be valid for every other reason except for the unwanted extra fields).

This is low priority, my use case isn't general. In the rare case when arrays have 10 or so properties (and some types are inferred via plugin), this issue becomes more common.

Example code:

```php
<?php

/**
 * @param array{field:string} $array (It'd be nice to ignore unrelated fields)
 */
function print_field($array) : void {
    echo $array['field'];
}

/**
 * @param array{field:string,otherField:string} $array
 */
function has_mix_of_fields($array) : void {
    print_field($array);
}
```

Other thoughts:

- Passing a consecutive 3-element array (keys = [0,1,2]) to something declared as expecting a 2-element array might make sense if it continued to be an InvalidArgument?

**Comment by muglug** [comment]
Sorry, late getting to this but definitely a bug that needs fixing. There shouldn't be any issue emitted IMO.
