### ISSUE TITLE
[Question] Is there a way to template-type a function that adds key-value to array?

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#4570]
I tried to type a function `function addValueToArray($value, string $targetKey, array $array)` that receives array, key and value and returns array that contains the value under provided key.

However, I'm currently unable to intersect two arrays as psalm needs object types: `Intersection types must be all objects or all object-like arrays`

```php
 * @template TInput of array
 * @param TInput $array
 * @return array{K: V}&TInput
```

https://psalm.dev/r/6d65848c52

**Comment by muglug** [comment]
No, `array{K: V}` always means an array with the literal key `'K'` and I don't think that'll change any time soon
