### ISSUE TITLE
substr() with class-string

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#4573]
could psalm infer the class-string in this case and therefore handle it like a string literal which would then know that `substr` on this literal will not be false?

https://psalm.dev/r/d16b9d5084

**Comment by weirdan** [comment]
Valid class-strings are probably never empty, so it should be possible.

**Comment by muglug** [comment]
`substr(A\B::class, 4)` returns `false` in PHP 7.4.

It returns the empty string in PHP 8, and Psalm has been updated to match: 42802e11d
