### ISSUE TITLE
Calling a public static trait function

### ISSUE THREAD

**Issue by gdejong** [vimeo/psalm#4574]
Given https://psalm.dev/r/c9f4090d04

The output is:
```
Psalm output (using commit 4e8fb9c): 

ERROR: UndefinedClass - 9:12 - Class or interface TestTrait does not exist
```

I would have expected no error since this is allowed by PHP: https://3v4l.org/sPN6V

**Comment by muglug** [comment]
It might be allowed, but it's really not great, as it's not how traits are meant to be used. Move that static function to a class.

**Comment by weirdan** [comment]
This is also going to be removed from PHP, see https://wiki.php.net/rfc/deprecations_php_8_1#accessing_static_members_on_traits
