### ISSUE TITLE
Idea: Allow indicating that ObjectLike fields are optional (e.g. key may not exist)

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#458]
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#optional-parameters-and-properties is similar to what I had in mind.

One possible syntax is to place a `?` before the `:`. (An optional nullable string would be `array{field?:?string}`, which is parseable but possibly confusing.)

Another syntax could be to place an `=` after the type (like JSDoc). `array{field:?string=}` 

E.g. `@param array{field?: string, other:string} $params` would be a parameter that would accept both `['other' => 'value']` and `['field' => 'v1', 'other' => 'v2']`

Casting rules: 

- Can cast required fields to optional (references may be an exception). E.g. casting `array{field:string}` to `array{field?:string}`.
- Can cast an absent field to an optional field, e.g. casting `array{field:string}` to `array{field:string, otherOptionalField?:string}`

The implementation details of this may affect https://github.com/vimeo/psalm/issues/457 (Different views on whether or not fields not mentioned in the union type are allowed to exist or not).

---

Use cases: Option arrays for function calls, global constructors.
E.g. http://php.net/unserialize would have these template annotations if there was union type support for it.

```php
<?php

/**
 * @param string $str
 * @param {allowed_classes?:string[]|bool} $options
 * @return mixed
 */
function unserialize($str, $options = []) {...}
```

**Comment by muglug** [comment]
Yes, even just a better internal representation is necessary to see the issue here, currently missed:
```php
if (rand(0,1)) {
  $a = ['a' => 1];
} else {
  $a = [2, 3];
}

echo $a[0];
```

**Comment by muglug** [comment]
This is one step further: https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#smarter-object-literal-inference

Probably too tricky to implement that though

**Comment by TysonAndre** [comment]
[Minor changes to the upstream call map](https://github.com/phan/phan/pull/1557/files#diff-51d74031f390b02c2f3cced18a13d964) are related. I went with `array{key:type=}` because it was slightly easier to unserialize/serialize; the fact that something could be undefined was added onto the union type representation.

**Comment by muglug** [comment]
eesh. Not sure I'm a fan of that annotation, but I understand the reasoning.

How hard would it be to also support `key?:type`? I was planning to add that to Psalm this weekend...

**Comment by muglug** [comment]
In particular, I want to improve generated return types for https://github.com/vimeo/psalm/issues/575

**Comment by TysonAndre** [comment]
Probably easy: just add a few checks to __toString for array shapes and another check for key? when parsing.

**Comment by TysonAndre** [comment]
Also, there isn't a standard for allowing spaces, punctuation, etc in object like keys, on an unrelated note.
(E.g could quote or use escaped hex for ASCII)
