### ISSUE TITLE
Idea: High level plugin API for overriding analysis of function/method calls

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#459]
Many plugins that could be thought up would involve manipulating the way psalm analyzes function/method calls.

1. Allow plugins to emit custom warnings when a specific function/method is called, based on the **values** (and types) of parameters.  Call the plugins after psalm does its own analysis
   (E.g. plugins could be written warn about passing an invalid regex literal/constant to the preg_match family of functions, checking printf-style args, passing a constant where a variable is usually expected, analyzing uses of a composer library, etc.)
2. Allow plugins to override the return type based on the values (and types) of parameters.

   (E.g. PHPUnit's createMock returns an instance of the class name passed as the first argument)
   (E.g. json_decode has a return type that can only be array when the second parameters is true)

   (Support for `@template` covers many (but not all) of the other possible use cases here... The createMock scenario could probably be an extension to `@template` - E.g. `@template string<T>`, `@param string<T>`, and `@return T`)

The two possible use cases are mentioned separately because return values may be unused.

Current state: Plugins would have to determine what function/method is being called on their own (in the hooks provided to analyze expressions). This makes it harder to write a plugin, and makes the plugin slower.

One way to implement this is to have plugins return an array mapping FQSENs of functions&methods to Closures(or objects) implementing the desired plugin analysis behavior.

A similar API in another project: [The interface exposed](https://github.com/phan/phan/blob/master/src/Phan/PluginV2/AnalyzeFunctionCallCapability.php) and [an example plugin analyzing values of types](https://github.com/phan/phan/blob/master/.phan/plugins/PregRegexCheckerPlugin.php)

**Comment by muglug** [comment]
So essentially a hook inside the bowels of both [`MethodCallChecker`](https://github.com/vimeo/psalm/blob/eb69d55b2943784215d5774552658d2f3e5acf7c/src/Psalm/Checker/Statements/Expression/Call/MethodCallChecker.php#L427) and `StaticCallChecker` that call out to a plugin with both the method id being analysed and reference to the currently inferred return type.

**Comment by muglug** [comment]
If we had a similar one for properties it would eliminate a bunch of the plugin code I've written for Vimeo.

**Comment by TysonAndre** [comment]
>  that call out to a plugin with both the method id being analysed and reference to the currently inferred return type.

Yes, as well as the argument list. (Either via passing the analyzed PHPParser Node or the Node/array for the argument list)

There might be a use case for knowing the variable/expression it's called on, but that's probably uncommon (E.g. $var->isObject() narrows type of var from BaseClass to ObjectClass)

**Comment by muglug** [comment]
Ok, I've added this in latest master. I've also converted plugins to use a static method call syntax, as you suggested.

**Comment by muglug** [comment]
> I don't remember suggesting that part, but I can't think of any problems with static methods

Oh right, sorry. I meant the bit about using reflection to figure out what plugin methods were implemented, then just running those methods.

Using static methods means not having to create a new instance at the bottom of the plugin code.
