### ISSUE TITLE
[Security] Improve LDAP injection documentation

### ISSUE THREAD

**Issue by LukasReschke** [vimeo/psalm#4593]
https://owasp.org/www-community/attacks/LDAP_Injection

Ref https://github.com/vimeo/psalm/issues/4590

**Comment by LukasReschke** [comment]
https://github.com/vimeo/psalm/blob/1708bae984c42fce21af22bc6737b64d3551ab91/dictionaries/InternalTaintSinkMap.php#L13 seems already to have that. Deserves it's own category + wiki though :-)

**Comment by muglug** [comment]
If so, then `header` probably also deserves its own category, right? Or is it considered SSRF?

**Comment by LukasReschke** [comment]
Yup. New category for that one as well. "Header Injection".

Impact there could range from "super bad" (e.g. on a server with XSendFile) to "meh" (e.g. open redirect)

**Comment by muglug** [comment]
Yeah, I caught an open-redirect on vimeo.com a few months ago
