### ISSUE TITLE
[Security] Benchmark against known vulnerable web apps

### ISSUE THREAD

**Issue by LukasReschke** [vimeo/psalm#4597]
Let's figure out what Psalm finds and what it doesn't. (and why not)

Out of my mind, these could be good candidates:

- https://github.com/digininja/DVWA (actively maintained)
- https://github.com/OWASP/Vulnerable-Web-Application (last update 2 years ago)
- https://github.com/OWASP/OWASPWebGoatPHP (last serious update 4 years ago)

**Comment by LukasReschke** [comment]
Setup DVWA at https://github.com/LukasReschke/DVWA

**Comment by muglug** [comment]
@LukasReschke you can use psalm.dev to narrow down examples with `// --taint-analysis` at the top.

https://github.com/digininja/DVWA/blob/ba23da2d1808f6e7df004b304c2aea92442092d3/vulnerabilities/exec/source/impossible.php#L8-L27

can be narrowed to https://psalm.dev/r/6167a74f94 (i.e. `stripslashes` isn't stubbed out)

https://github.com/digininja/DVWA/blob/ba23da2d1808f6e7df004b304c2aea92442092d3/vulnerabilities/sqli/source/high.php#L5-L8

can be narrowed to https://psalm.dev/r/28aee75a41 (as you say, `$_SESSION` is not currently treated as tainted)

**Comment by orklah** [comment]
stripslashes example seems to work now.

$_SESSION does not but I'm not sure if we should consider it tainted. Shouldn't that be considered a sink instead to avoid creating false positives everywhere?

I'll close this, please reopen with individual psalm.dev examples so we can discuss cases separately
