### ISSUE TITLE
[Security] Add support for XML External Entity Processing (XXE)

### ISSUE THREAD

**Issue by LukasReschke** [vimeo/psalm#4598]
https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing

That's a tricky one though as the code is only vulnerable after someone calls `libxml_disable_entity_loader(true);`. So for reliable detection, Psalm would also need to detect this state.

**Comment by muglug** [comment]
Yeah, this is a current flaw in Psalm's analysis: it only cares about taint flows in between data in types.

That means it can't deal with rules like `every object deletion must be authenticated` to catch this issue:

```php
function authed_deletion(User $current_user, Video $object) {
  if ($object->canBeDeleted() && $current_user->id === $object->user_id) {
    $object->delete();
  } elseif ($some_other_condition) {
    $object->delete(); // a bug without authentication
  }
}
```

On the other hand this is the sort of thing that I think CodeQL couuld excel at (though there's no PHP support atm)

**Comment by orklah** [comment]
Closing as out of scope for Psalm
