### ISSUE TITLE
Psalm does not understand references

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#4602]
Psalm does not understand this code:

https://psalm.dev/r/b9dcd495d4

```php
$number = 1;

function getSqlFilePath(int $number): string {
    return $number . '.sql';
}

$f = function() use (& $number): void {
    echo getSqlFilePath($number) . "\n";
    $number++;
};

$f();
$f();
```

> INFO: MixedArgument - 10:25 - Argument 1 of getSqlFilePath cannot be mixed, expecting int

Even though it's pretty clear here that `$number` is, and will always be, an `int`.

**Comment by muglug** [comment]
Yes, it's clear here but in general by-ref uses are unsound. There's an issue for an annotation (similar to `@param-out`) that would make it sound: https://github.com/vimeo/psalm/issues/4001
