### ISSUE TITLE
link to taint error articles dont work within GithubActions log

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#4616]
I guess the GithubAction auto-linking feature thinks that the `)` char is part of the url, and therefore the link opens a 404 error page, when clicked

![grafik](https://user-images.githubusercontent.com/120441/99637216-cff4c600-2a44-11eb-8f45-a69bcddd23f0.png)

see https://github.com/redaxo/redaxo/runs/1422847143

**Comment by staabm** [comment]
also reported to github in https://github.community/t/links-in-action-logs-not-recognized-correctly/144390

**Comment by muglug** [comment]
Yeah, I don't consider this a bug in Psalm
