### ISSUE TITLE
How to use phpVersion when having to support a range of PHP versions?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#4618]
in 1 application I have to support PHP 5.6 - 8.0
I have PHP 8.0 installed on my machine
There is no php version set in composer.json

Which setting should I be using for the phpVersion/`--php-version=` option?
(to ensure that I wont be using any deprecated things that were removed from PHP 8.0, but also that I won't be using anything that's not available in e.g. PHP 5.6 or 7.0)

**Comment by kkmuffme** [comment]
No, since this isn't an issue but a question

**Comment by weirdan** [comment]
I'd start with running it with lowest and highest possible versions, using `--php-version=` cli flag.

**Comment by kkmuffme** [comment]
This means I have to run it twice? (kind of tried to avoid that, as it adds a lot of build time)

**Comment by orklah** [comment]
you can do an analysis on lower version with --set-baseline and then on upper version and use --update-baseline. That way, issues that appear only on one will be ignored. But yeah, no alternative for now and it's probable there never will be. PHPStan works the same way.
