### ISSUE TITLE
taint on empty strings

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#4620]
I dont expect a error in this case

https://psalm.dev/r/a020e4ddc2

as soon as I drop the `if ($file) {` it works like expected.

**Comment by staabm** [comment]
the initially reported taint error is still reproducible 

https://psalm.dev/r/a020e4ddc2

**Comment by weirdan** [comment]
> the initially reported taint error is still reproducible

At the very least it's titled misleadingly - there's no guarantee that `$_GET['filename']` contains a string, as evidenced by type errors reported by Psalm: https://psalm.dev/r/d25318bfb9

If you make sure it's a string (e.g. by using strict comparison) the taint is gone: https://psalm.dev/r/3fd7e9379c
