### ISSUE TITLE
taint analysis and result cache

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#4623]
when working locally thru the taint issues of our project I realized that psalm somehow does some caching and does not always realize my changes to the source.

when running with `--no-cache` it gets more errors then when running without.

should psalm either properly prune the cache when running taint analysis, or maybe disable cache for taint-analysis because its important to have a fresh and up2date result while working on security issues?

**Comment by muglug** [comment]
This is fixed in latest master — planning a release today
