### ISSUE TITLE
taint on predefined constants

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#4624]
after validating a value against a list of predefined list of constants, no taint warning should be emitted

https://psalm.dev/r/fdec68c380

**Comment by staabm** [comment]
It seems the above posted example still taint-errors on latest master

**Comment by weirdan** [comment]
@staabm you've got your `in_array()` call backwards and missed strict flag. With those issues fixed the taint is gone: https://psalm.dev/r/b4dd637aa8
