### ISSUE TITLE
array_key_exists doesn’t infer key type

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#4626]
This should not error - similar to https://github.com/vimeo/psalm/issues/4624

https://psalm.dev/r/f4f5e5a159

**Comment by muglug** [comment]
It's really this: https://psalm.dev/r/3fef8040e6

**Comment by staabm** [comment]
my initial report was about the taint error reported.

in case this taint error will go away when psalm realizes the key-type this might be the same thing then.
