### ISSUE TITLE
How to tell psalm that the return type corresponds to the input type?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#4629]
How can I tell psalm that the return type corresponds to the input type, to avoid having to check the returned type unnecessarily.

```
<?php

/**
 * lalal
 * @param string|array $i
 *
 * @return string|array
 */
function foo( $i ) {
    return $i;
}

echo 'hello' . foo( 'gruel' ) . 'world';
```

https://psalm.dev/r/71e011ccae

**Comment by orklah** [comment]
You basically have two choices. You can use conditional returns:
https://psalm.dev/r/15045580f3

or templates:
https://psalm.dev/r/893f4c5098

Both have their pro and cons, but for a simple example like this, both can work.

**Comment by kkmuffme** [comment]
Thank you!
