### ISSUE TITLE
PHP 8: buggy named arguments analysis

### ISSUE THREAD

**Issue by ondrejmirtes** [vimeo/psalm#4631]
https://psalm.dev/r/bc6bd69528

Expected 4 errors:

* Line 6: Named parameter $param overwrites previous argument
* Line 6: Missing $param2 argument
* Line 8: Named parameter $param overwrites previous argument
* Line 8: Missing $param2 argument

**Comment by ricardoboss** [comment]
I found a case where this bug causes a false positive: https://psalm.dev/r/cb7b0e358d

**Comment by muglug** [comment]
@ricardoboss that's fixed here: 4807d3850
