### ISSUE TITLE
Psalm 4.2.0 release has no PHAR

### ISSUE THREAD

**Issue by sebastianbergmann** [vimeo/psalm#4635]

**Comment by ADmad** [comment]
Phar for `4.2.0` is available now. It takes a while for the CD job to complete and new phar to be available after a new release is tagged.

**Comment by muglug** [comment]
Yeah, I need to migrate away from Travis for building the Phar.

**Comment by ADmad** [comment]
With recent throttling on Travis it can be even hours rather than minutes for the phar to be build.
