### ISSUE TITLE
Psalter and Union types

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#4643]
Hi,

Union Types in PHP8 allow us to change Psalter so it can add more types in signature than before.

Currently, the only Union Type than can be added in signature is a Nullable Type:
https://github.com/vimeo/psalm/blob/master/src/Psalm/Type/Union.php#L480

I can try to propose a PR but I think we should define some arbitrary(or not) rules to avoid messes.

Here are the rules I think of, could you tell me if you agree with those or not and if I forgot some?

Don't add the Union in signature if:
- There's a void type in the union => forbidden by RFC
- There's two or more objects, one is named and the other one is just "object" => forbidden by RFC
- There's one type in the union who returns no php type => This would break code
- There's a mixed type in the union => This adds no meaning
- There's more than 3 different types in the result signature (null included). This means string|numeric-string|class-string|callable-string will pass => to avoid mess in signature
- There's a mix of scalar and other types in the Union => to avoid mess in signature

Thanks

**Comment by orklah** [comment]
Note: Types like ArrayKey will be an issue as they represent two types by themselves. This means if it's nullable, we can't just do `?<<result>>` because we will get `?int|string` and this syntax is forbidden by RFC.
Ideally, we would transform this into `null|int|string` but currently, the role of adding the "?" is left to Union and it doesn't know what each part will return.

**Comment by orklah** [comment]
Note: TFalse could also be a special case given that `string|false` is allowed. However, this will have to be handled by Union because `false` and `false|null` are not allowed by themselves

**Comment by muglug** [comment]
I've done a basic thing (that doesn’t allow `string|false`) which we can refine
