### ISSUE TITLE
Remove hard coded memory limit

### ISSUE THREAD

**Issue by DeepDiver1975** [vimeo/psalm#465]
I have no idea why this is set in the first place - https://github.com/vimeo/psalm/blob/78e34c05484d83b2bfd8c55fa6cefbec10866c96/src/psalm.php#L12

But larger projects require more memory.

Simply drop that line? I'm happy to submit a pull request

**Comment by DeepDiver1975** [comment]
> Yeah maybe with ini_set('memory_limit', '-1');?

why not leave it to the php environment?



> Impressed that you're running into that limit though... are you running it in a single thread?

I just run psalm with  the generated default config ;-)

**Comment by muglug** [comment]
> I just run psalm with the generated default config 

It’s a command-line option - `--threads=[number]`

**Comment by muglug** [comment]
> why not leave it to the php environment?

Because some people’s defaults are dumb, and I want to reduce friction wherever possible. That’s also why I disable XDebug.

**Comment by DeepDiver1975** [comment]
on my local test I just went beyond 20GB mem 🎉

**Comment by muglug** [comment]
How big is your project?

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/core

**Comment by muglug** [comment]
Yup, going to close this – 2GB should be more then enough for just about any PHP project, as long as you're using Psalm correctly (i.e. not running on the `vendor` dir)

**Comment by SignpostMarv** [comment]
Currently running into this, although oddly also while reinitialising the config file with `./vendor/bin/psalm --init src` o_O

**Comment by muglug** [comment]
You can bypass this with `--use-ini-defaults`

**Comment by SignpostMarv** [comment]
@muglug I'm wondering if it's a 32/64 bit issue, since I only have the problem running psalm locally not on CI systems.
