### ISSUE TITLE
Internal Psalm error when handling self references in Psalm type

### ISSUE THREAD

**Issue by morozov** [vimeo/psalm#4653]
https://psalm.dev/r/c88c7db126

On Psalm 4.1.1 where I discovered this issue, the behavior is a bit different and produces the following error:
```
ERROR: UndefinedDocblockClass - lib/Doctrine/DBAL/DriverManager.php:140:21 - Docblock-defined class or interface Doctrine\DBAL\Params does not exist (see https://psalm.dev/200)
     * @psalm-param Params $params
```

**Comment by morozov** [comment]
The actual problem is reproducible by moving the code above into a namespace: https://psalm.dev/r/a725397137

**Comment by morozov** [comment]
> ERROR: InvalidDocblock - 8:17 - Invalid type alias SomeType provided in docblock for test

The new error message is still misleading:

1. `InvalidDocblock`. What is invalid about the docblock? The syntax is valid, the used annotation names are valid as well.
2. Invalid type alias SomeType. What is invalid about the alias? If I change the `parent` element type to something else, the error goes away, so the alias _is_ valid.

**Comment by orklah** [comment]
Judging by the test name `noCrashWithSelfReferencingType`, I believe Psalm emit an error because recursion is not supported in alias Types

**Comment by morozov** [comment]
In this case, it still would be nice to have that reflected in the error message. Although, I realize that at the moment of parsing the type, the engine may be not aware of the recursion as such.

The point is, the side effect of adding a not-yet-supported self-reference to an existing type is getting new random error messages across the codebase which is quite confusing.
