### ISSUE TITLE
Taint analysis: support conditional escaping

### ISSUE THREAD

**Issue by gharlan** [vimeo/psalm#4661]
Example:

```php
function foo(string $string, bool $escape): string
{
    if ($escape) {
        $string = htmlspecialchars($string);
    }

    return $string;
}

echo foo($_GET['foo'], true);
echo foo($_GET['foo'], false);
```

https://psalm.dev/r/f26a4dd650

It would be cool if conditional escaping would be supported somehow (automatically, via annotation or via plugin).

**Comment by LukasReschke** [comment]
Whilst conditions on sanitizer definition would be cool, your case can be addressed easier :-)

`htmlspecialchars` is already defined as sanitizer for `TaintedHtml`: 

https://github.com/vimeo/psalm/blob/3943b55f8a0f33de3d4a107888a74ed82ee338d8/stubs/CoreGenericFunctions.phpstub#L662

The reason that you get the results that you get, is that you haven't annotated the function with `psalm-pure` (https://psalm.dev/docs/security_analysis/avoiding_false_positives/).

Check https://psalm.dev/r/307ed9c3f7

**Comment by LukasReschke** [comment]
Wait. I am wrong. Pure doesn't help here :/

**Comment by gharlan** [comment]
> Wait. I am wrong. Pure doesn't help here :/

Hmm, why are you wrong? It seems the error is correctly gone for the first function call.

**Comment by LukasReschke** [comment]
@gharlan, because it would still trigger if there's only one of them: https://psalm.dev/r/ad0a0afd0f. 

On a general note, something like the return conditional support would be helpful to have for taint / sink / sanitizer sources indeed. There's quite some cases where functions become harmless if passed the right values. So I can see the value.

**Comment by LukasReschke** [comment]
> Hmm, why are you wrong? It seems the error is correctly gone for the first function call.

It seems there are cases where Psalm isn't going into if blocks even if one can be 100% sure they would be executed. The following gives an error, but shouldn't:

```php
<?php // --taint-analysis

/**
 * @psalm-pure
 */
function foo(string $string)
{
    if (true) {
        return 'asdf';
    }

    return $string;
}

echo foo($_GET['bar']);
```

https://psalm.dev/r/94e2d719e5

**Comment by muglug** [comment]
@LukasReschke Psalm’s taint analysis doesn't currently do anything clever when it comes to calling functions.

Ignoring the `if (true)` pathological case, If there is a path where the return value of a function is not escaped, Psalm considers all return values of that function potentially unescaped.

I think the best way of handling this is with annotations like

```php
/**
 * @psalm-taint-escape ($escape is true ? 'html' : null)
 */
function foo(string $string, bool $escape = true): string
{
    if ($escape) {
        $string = htmlspecialchars($string);
    }

    return $string;
}
```
