### ISSUE TITLE
ReferenceConstraintViolation when not changing the type of a pass-by-reference variable

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#4665]
https://psalm.dev/r/94433440e0

**Comment by Jean85** [comment]
I have the same issue when I pass by reference to refresh a Doctine entity in my tests, hence assuring that the param has the same type. I used `@psalm-assert` as a workaround:

    /**
     * @template T of object
     * @param T $entity
     * @psalm-assert T $entity
     */
    protected function refreshEntity(object &$entity): void
    {
        $this->getEntityManager()->refresh($entity); // forced refresh
    }

**Comment by rzvc** [comment]
I have the same issue. My workaround in this case was to redeclare the parameter at the end of the function:
```php
function foo($param)
{
	// Do things that trigger this bug.

	/** @var T $param */
}
```
Of course, this has the effect of suppressing the `ReferenceConstraintViolation` issue also when it shouldn't.

**Comment by orklah** [comment]
Seems fixed!
