### ISSUE TITLE
Using higher phpVersion than currently installed?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#4672]
I have PHP 7.4 installed. Can I set phpVersion to 8.0 to enable checks that are PHP 8 specific?

EDIT: Will psalm also report things that are deprecated as of PHP 8? e.g. `Method ReflectionParameter::getClass() is deprecated` ...

**Comment by kkmuffme** [comment]
Nope, since this is a config question

**Comment by muglug** [comment]
> I have PHP 7.4 installed. Can I set phpVersion to 8.0 to enable checks that are PHP 8 specific?

Yes

> Will psalm also report things that are deprecated as of PHP 8

No, but you can create a ticket for that
