### ISSUE TITLE
How to: dynamically suppress specific issue type based on inheritance

### ISSUE THREAD

**Issue by ludofleury** [vimeo/psalm#4684]
Hi there, 

I'm struggling since hours to achieve this.
I tried almost every hooks on the plugin interface.

Here's my use-case:

If an interface "MyInterface" is implemented by a class, I want to disable "PropertyNotSetInConstructor" issue.

I know that I can suppress them with xml config or annotation (note that class annotation "@psalm-suppress" is not working in 4.X-dev). I do not want to go this way, is there a "plugin" way ?

Right now I'm so desperate that the only solution after hours is: modifying the code of `Psalm\Internal\Analyzer\ClassAnalyzer` L1492

**Comment by orklah** [comment]
Did you try suppressing the issue through XML config?
```xml
    <issueHandlers>
        <PropertyNotSetInConstructor>
            <errorLevel type="suppress">
                <file name="path_to_file1"/>
            </errorLevel>
        </PropertyNotSetInConstructor>
    </issueHandlers>
```

**Comment by ludofleury** [comment]
It does work with the XML. This i not what i'm trying to achieve. 
In order to ease maintainability & still enforce a standard, I'd like to dynamically add suppression rule based in inheritance :)

**Comment by orklah** [comment]
> It does work with the XML. This is not what i'm trying to achieve.
> In order to ease maintainability & still enforce a standard, I'd like to dynamically add suppression rule based in inheritance :)

If I understand correctly, you don't want to list the files in the xml because this would imply changing the config on each new class?

Did you consider changing the code to allow ignoring a specific implemented class in XML config instead of files?

Something that would look like:
```xml
    <issueHandlers>
        <PropertyNotSetInConstructor>
            <errorLevel type="suppress">
                <inheritedClass name="\Name\Space\Of\Interface"/>
            </errorLevel>
        </PropertyNotSetInConstructor>
    </issueHandlers>
```

**Comment by ludofleury** [comment]
I tried:

`AfterClassLikeVisitInterface`: sadly here the class info are partially populated (inheritance/interface are not available)

`afterStatementAnalysis`: with `StatementsSource->->addSuppressedIssues()`, the doc on `addSuppressedIssues()` is not clear itself, I tried an array of short class name or an array of issue FQCN. yet it seems "too late" to suppress as the CLI progress is reporting an "E" and the errors is still there on the final output

`afterAnalysis`: with parsing the issue and `unset`, seems brutal but didn't work.

**Comment by ludofleury** [comment]
> If I understand correctly, you don't want to list the files in the xml because this would imply changing the config on each new class?

Exactly!

I did not consider your option yet, I was trying to achieve it with a plugin at first.
If I understand correctly, that would change the config XML handler (it is not a plugin, rather a PR to this repo right? @orklah ?)

**Comment by muglug** [comment]
> If I understand correctly, that would change the config XML handler (it is not a plugin, rather a PR to this repo right?)

Yeah, would require a change to the XSD and also some slightly more laboursome issue handling, which is not out of the question. This is definitely on the line of should-it-be-in-config vs should-it-be-in-plugin

**Comment by ludofleury** [comment]
Alright, I can definitely try. 
But i'm very curious: is it achievable with a plugin ?

**Comment by muglug** [comment]
@ludofleury the way to solve this, I think, is by adding to `ClassLikeStorage::$suppressed_issues` in the `AfterClassLikeVisitInterface` interface.

That would mean Psalm behaved like this: https://psalm.dev/r/651f0ec068

**Comment by ludofleury** [comment]
Thank you very much @muglug & @orklah for your super fast answers & support.
I'd try this right now.

**Comment by ludofleury** [comment]
So after checking
`ClassLikeStorage->class_implements` is not populated at this stage.

Which means, I need to do a Reflection there that will impact every class visited. but since it's cached, it seems affordable for my use case.

thank you again, I let you close this issue if needed.

**Comment by muglug** [comment]
Yeah at that stage `ClassLikeStorage::$class_implements` only shows things discovered from visiting that particular class. It's not until everything is populated that there's reliable data.

**Comment by muglug** [comment]
@ludofleury mind pasting a snippet of working code that I can include in documentation?

**Comment by ludofleury** [comment]
@muglug I just submitted a PR: https://github.com/vimeo/psalm/pull/4686
Small contribution & big thank you for your support guys :)
