### ISSUE TITLE
PossiblyNullArgument inside an if statment with type declarations

### ISSUE THREAD

**Issue by 1ed** [vimeo/psalm#4687]
I think this is a false positive

https://psalm.dev/r/62cd4847b8

**Comment by muglug** [comment]
Simplified to https://psalm.dev/r/ed293d65a7

**Comment by orklah** [comment]
I think this is basically the same issue as https://github.com/vimeo/psalm/issues/4493

**Comment by orklah** [comment]
I think this is https://github.com/vimeo/psalm/issues/4358 too

**Comment by weirdan** [comment]
Those two deal with non-strict comparison, not sure how much difference does that make.
