### ISSUE TITLE
MixedAssignment false-positive after type-narrowing

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#4688]
https://psalm.dev/r/9ebb1b267c

I expect no errors after type narrowing.

**Comment by weirdan** [comment]
This is by design. You have (at least) 3 options here:

* Enable call memoization: https://psalm.dev/r/115cee85c4
* Call the method once and work on a variable: https://psalm.dev/r/2780ef4109
* Mark the method as mutation-free: https://psalm.dev/r/38e3c96ae5
