### ISSUE TITLE
PHP warning when running in taint analysis mode

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#4690]
Issue has been identified while upgrading from 4.1.0 to 4.2.1.

```
PHP Warning:  array_intersect(): Expected parameter 1 to be an array, string given in vendor/vimeo/psalm/src/Psalm/Internal/Codebase/TaintFlowGraph.php on line 263
```

https://github.com/vimeo/psalm/blob/2bf25d5f503811c6c74bbb8488f857559b23ed7b/src/Psalm/Internal/Codebase/TaintFlowGraph.php#L279

In my situation when the warning is throw, `$sinks[$to_id]->taints` is the string `file`.
I have not yet been able to reproduce the issue with a minimal scenario :/

**Comment by muglug** [comment]
@LeSuisse I wonder if this is an issue with a custom integration you're using?

**Comment by LeSuisse** [comment]
We do not have any plugins playing with the taint analysis but out of caution I just tried a run without the `<plugins>` and `<stubs>` sections of our config but the warning is still here.

I will try to see If I can pinpoint the issue more precisely.

**Comment by LeSuisse** [comment]
I have found the source of the issue thanks to git bisect, the internal taint sink map is not correctly defined for `rmdir`.
https://github.com/vimeo/psalm/blob/78f4a0691cb413d4696446f0f858f0f1e7a6ebfa/dictionaries/InternalTaintSinkMap.php#L22

I'm going to open a PR with the fix.
