### ISSUE TITLE
Psalm does not recognize argument unpacking

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#4691]
Probably related to #2481.

https://psalm.dev/r/bd75ca928b

```php
class Foo {
    public function __construct(string $a, int $b, bool $c) {}
}

/**
 * @psalm-param array{0: string, 1: int, 2: bool} $arguments
 */
function createFoo(array $arguments): Foo
{
    return new Foo(...$arguments);
}
```

> INFO: MixedArgument - 12:23 - Argument 1 of Foo::__construct cannot be mixed, expecting string

**Comment by muglug** [comment]
It does if you omit the int keys: https://psalm.dev/r/50caca73b6

That formulation (without the int keys) requires the array be a tuple (or in this case, a triple).

**Comment by muglug** [comment]
whereas `[1 => 5, 0 => "hello", 2 => true]` is a valid argument for the example you provided

**Comment by BenMorel** [comment]
Thanks, I didn't know that argument unpacking had this behaviour, I'm always using it with lists! TIL.

But actually my use case was simplified, here is the real one, with the last parameter being optional:

https://psalm.dev/r/ac05dc89ec

And I am passing an array that may not have the last key present. i.e. I may pass either:

```php
['hello', 1, true]
 ```
```php
['hello', 1, true, null]
 ```
```php
['hello', 1, true, 'test']
 ```

Is there a solution to document this? With explicit keys, I can do `3?:string`, but I'm not sure if that's possible with tuples.

**Comment by muglug** [comment]
Optional keys aren't possible with tuples, sorry.

**Comment by BenMorel** [comment]
Makes sense, I guess; thank you for your reply! I'll refactor my code to not depend on this, then.

**Comment by MauricioFauth** [comment]
> Is there a solution to document this? With explicit keys, I can do `3?:string`, but I'm not sure if that's possible with tuples.

The solution is to use `list` instead of `array`.

```diff
-  * @psalm-param array{0: string, 1: int, 2: bool, 3?:string} $arguments
+  * @psalm-param list{0: string, 1: int, 2: bool, 3?:string} $arguments
```

https://psalm.dev/r/53bdab5962
