### ISSUE TITLE
uasort with array values

### ISSUE THREAD

**Issue by christeredvartsen** [vimeo/psalm#4697]
Not sure if this is a bug or if I'm just misunderstanding something:

https://psalm.dev/r/3aa586482e

Does psalm not look at the first argument to `usort` when it validates the params for the callback?

**Comment by weirdan** [comment]
> Does psalm not look at the first argument to usort when it validates the params for the callback?

It doesn't. Generally Psalm stops inferring things on function boundary - so types outside the function do not affect the types inside. Also, parameter is just an (arbitrary complex) expression - so Psalm would have to work it backwards to the function definition and then cross the function boundary, potentially many times, as the expression could be a immediately invoked function expression returning a closure that returns a closure... and so on.

If it did, should it be failing with the following?

```php
<?php
/** @var array<int,array{name:string}> */
$teams = [
	['name' => 'some name'],
	['name' => 'some other name'],   
];

usort($teams, $f = fn($a, $b) : int => $a <=> $b));
usort([1, 2, 3], $f);
```
If yes, why? If not, why?

And how it is really different from 
```php
<?php
/** @var array<int,array{name:string}> */
$teams = [
	['name' => 'some name'],
	['name' => 'some other name'],   
];
$f = fn($a, $b) : int => $a <=> $b);
usort($teams, $f);
usort([1, 2, 3], $f);
```
which I believe no one would expect to fail?

**Comment by christeredvartsen** [comment]
So in my original example I guess it would make sense to simply suppress the error?

**Comment by weirdan** [comment]
I would probably spell it out as https://psalm.dev/r/2ba94d7179, but suppression is an option too.

**Comment by christeredvartsen** [comment]
Nice, thanks!
