### ISSUE TITLE
DuplicateArrayKey with very large numeric string keys

### ISSUE THREAD

**Issue by gdejong** [vimeo/psalm#4698]
https://psalm.dev/r/dc22a5ec25

I would not expect a `DuplicateArrayKey` error since the keys are different. It seems to have something to do with `PHP_INT_MAX`. Using numbers less than `PHP_INT_MAX` gives no error.

```
php > echo PHP_INT_MAX;
9223372036854775807
```

**Comment by orklah** [comment]
It may be related to the fact that PHP cast string to int when possible, but it can't happen for literals that are higher than PHP_INT_MAX.

Psalm seem stuck to this value anyway:
https://psalm.dev/r/232eda4ed0
Here we don't use `9223372036854775807` at all, but Psalm still emit that this key is present twice...

**Comment by gdejong** [comment]
@orklah indeed you are right:

From https://www.php.net/manual/en/language.types.array.php

```
Strings containing valid decimal ints, unless the number is preceded by a + sign, will be cast to the int type. E.g. the key "8" will actually be stored under 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer.
```

A `var_dump` reveals this behavior:
```
array(2) {
  [9223372036854775807] =>
  int(1)
  '9223372036854775808' =>
  int(2)
}
```

**Comment by orklah** [comment]
The root cause was that castring a string that contains an int > PHP_INT_MAX will "reduce" its value to PHP_INT_MAX:
https://3v4l.org/sOaGd.

I proposed a PR to avoid changing the value to int (PHP does too: https://3v4l.org/M0Ssb)

**Comment by gdejong** [comment]
Hi thanks for having a look!

I am not sure if this fix actually solved the issue though:
https://psalm.dev/r/232eda4ed0

On commit 01ceaf7 the DuplicateArrayKey error still shows up.

**Comment by gdejong** [comment]
I think the fix does not work since casting to an integer has an upper boundary: https://3v4l.org/XAuN2

A possible solution could be to use [bccomp](https://www.php.net/manual/en/function.bccomp.php) like: https://3v4l.org/eUJrA

**Comment by orklah** [comment]
> 
> 
> I think the fix does not work since casting to an integer has an upper boundary: https://3v4l.org/XAuN2
> 
> A possible solution could be to use [bccomp](https://www.php.net/manual/en/function.bccomp.php) like: https://3v4l.org/eUJrA

Oh I didn't saw your second reply before fixing it. I solved it by testing that the original string was different than PHP_INT_MAX. bccomp is a good idea too!

**Comment by gdejong** [comment]
Something like the following works:
```
diff --git a/src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php b/src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
index 1f7243877..ccad19375 100644
--- a/src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
+++ b/src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
@@ -171,7 +171,7 @@ class ArrayAnalyzer
 
                     if ($item->key instanceof PhpParser\Node\Scalar\String_
                         && preg_match('/^(0|[1-9][0-9]*)$/', $item->key->value)
-                        && (int) $item->key->value <= PHP_INT_MAX
+                        && bccomp($item->key->value, PHP_INT_MAX) < 1
                     ) {
                         $key_type = Type::getInt(false, (int) $item->key->value);
                     }
```

I am checking for the return value of `bccomp` to be **less than 1**:
- `0` if the operands are equal
- `-1` if the left operand is smaller than the right operand

In both of those cases the value can be safely cast to an integer.

(see https://www.php.net/manual/en/function.bccomp.php#refsect1-function.bccomp-returnvalues)

But it would require adding `ext-bcmath` to `composer.json`

**Comment by gdejong** [comment]
Thanks for fixing!
