### ISSUE TITLE
Classes within the vendor dir can hold optional code ... be a bit more relaxed here ...

### ISSUE THREAD

**Issue by DeepDiver1975** [vimeo/psalm#470]
Example:
- the class AbstractDb uses the trait AdapterAwareTrait.
- since we don't use this class we don't care about the missing dependency to Zend/Db
- psalm should ignore this as well

THX

```bash
$ lib/composer/bin/psalm
PHP Fatal error:  Trait 'Zend\Db\Adapter\AdapterAwareTrait' not found in ***/lib/composer/zendframework/zend-validator/src/Db/AbstractDb.php on line 28

Fatal error: Trait 'Zend\Db\Adapter\AdapterAwareTrait' not found in ***/lib/composer/zendframework/zend-validator/src/Db/AbstractDb.php on line 28
d

**Comment by muglug** [comment]
You were getting caught out because of the vendor dir symlink. While I haven't fixed #252, this fixes your use case
