### ISSUE TITLE
Template type from implemented stub interface is leaked into outer scope

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#4705]
13b83e6 (confirmed with bisect) broke the following use case (in doctrine plugin):

```php
<?php
// https://github.com/weirdan/doctrine-psalm-plugin/blob/master/stubs/EntityManagerInterface.phpstub

namespace Doctrine\ORM;

use Doctrine\Common\Persistence\ObjectManager;

interface EntityManagerInterface extends ObjectManager
{
    /**
     * @param class-string<T> $entityName
     * @param mixed           $id
     *
     * @return T|null
     *
     * @template T
     */
    public function getReference(string $entityName, $id);
}
```

```php
<?php
// https://github.com/weirdan/doctrine-psalm-plugin/blob/master/stubs/EntityManager.phpstub

namespace Doctrine\ORM;

class EntityManager implements EntityManagerInterface
{
    /**
     * @template T
     * @param class-string<T> $entityName
     * @param mixed           $id
     *
     * @return null|T
     */
    public function getReference($entityName, $id)
    {
    }
}
```

```gherkin
  @EntityManager::getReference
  Scenario: Getting a reference
    Given I have the following code
      """
      <?php
      use Doctrine\ORM\EntityRepository;
      use Doctrine\ORM\EntityManager;
      interface I {}
      /**
       * @psalm-suppress InvalidReturnType
       * @return EntityManager
       */
      function em() {}
      atan(em()->getReference(I::class, 1));
      """
    When I run Psalm
    Then I see these errors
      | Type            | Message                                      |
      | InvalidArgument | Argument 1 of atan expects float, I provided |
    And I see no other errors
```

Instead of reporting the return type of `getReference()` as `I|null` Psalm now infers it as `I&(T:fn-doctrine\orm\entitymanagerinterface::getreference as object)|null` which doesn't make sense in the outer scope.

Apparently this affects stubs only, as I haven't been able to reproduce it on psalm.dev (futile attempt is here: https://psalm.dev/r/4c7cf7bb67)

**Comment by weirdan** [comment]
So I spent quite a while trying to debug this, but wasn't able to fix the issue. `TemplateResult::$upper_bounds` does not contain an entry for the inherited template, but the type has it as an intersection, so the replacement is not happening for the intersected (inherited) template.

I also couldn't produce a proper test for it. Something strange is going on here.

@muglug do you have any pointers on how I can track this down?

**Comment by weirdan** [comment]
I guess huge part of the problem I'm facing is that I'm looking for something that **does not** happen, and I'm not even sure where it's supposed to be happening.

**Comment by muglug** [comment]
Do you have any sort of failing test?

**Comment by muglug** [comment]
I mean, in Psalm's own repo

**Comment by weirdan** [comment]
Not in Psalm repo, no. But I can reproduce it in doctrine-psalm-plugin repo:

```console
git clone git@github.com:weirdan/doctrine-psalm-plugin.git
cd doctrine-psalm-plugin
git checkout allow-psalm-4
composer install
vendor/bin/codecept run acceptance tests/acceptance/EntityManager.feature:'Getting a reference'
```
After it runs (and fails) there will be `tests/_run` folder left behind, which contains a PHP file and `psalm.xml` file - running `../../vendor/bin/psalm` inside that folder will reproduce the issue. Note that you would need to run Psalm from the vendor folder - otherwise the plugin wouldn't load.

Sorry if that looks overly complicated, but that's the only way I'm able to reproduce the issue.

**Comment by muglug** [comment]
Have you tried in StubsTest?

**Comment by weirdan** [comment]
I did, it doesn't produce the same effect (i.e. it reports `I|null` as opposed to what I'm getting in the plugin repo). Below is what I tried:

```diff
diff --git a/tests/StubTest.php b/tests/StubTest.php
index 1a0fecd9e..fd8f7e3da 100644
--- a/tests/StubTest.php
+++ b/tests/StubTest.php
@@ -1178,4 +1178,41 @@ public function testStubOverridingMissingMethod(): void
 
         $this->analyzeFile($file_path, new Context());
     }
+
+    public function testStubImplementingStubDoesNotLeakTemplate(): void
+    {
+        $this->project_analyzer = $this->getProjectAnalyzerWithConfig(
+            TestConfig::loadFromXML(
+                dirname(__DIR__),
+                '<?xml version="1.0"?>
+                <psalm>
+                    <projectFiles>
+                        <directory name="src" />
+                    </projectFiles>
+                    <stubs>
+                        <file name="/home/weirdan/src/psalm/plugins/doctrine-psalm-plugin/stubs/EntityManagerInterface.phpstub" />
+                        <file name="/home/weirdan/src/psalm/plugins/doctrine-psalm-plugin/stubs/EntityManager.phpstub" />
+                        <file name="/home/weirdan/src/psalm/plugins/doctrine-psalm-plugin/stubs/ObjectManager.phpstub" />
+                    </stubs>
+                </psalm>'
+            )
+        );
+
+        $file_path = getcwd() . '/src/somefile.php';
+
+        $this->addFile(
+            $file_path,
+            '<?php
+                  use Doctrine\ORM\EntityManager;
+                  interface I {}
+                  /**
+                   * @psalm-suppress InvalidReturnType
+                   * @return EntityManager
+                   */
+                  function em() {}
+                  atan(em()->getReference(I::class, 1));
+            '
+        );
+        $this->analyzeFile($file_path, new Context());
+    }
 }
```
Also tried to put the stubs in `tests/fixtures/stubs/`, that produce exactly the same effect.

**Comment by weirdan** [comment]
Ok, I'm getting closer - the key thing to reproduce it is to have actual `EntityManagerInterface` in the vendor folder.

**Comment by weirdan** [comment]
@muglug I've finally managed to reproduce it, please see linked PR.

**Comment by muglug** [comment]
Psalm sets a `ClassLikeStorage::$documenting_method_ids` variable to point to the method with param and return types. This was set one way during the initial scan (because of the implicit inheritdoc from the class to the interface) but when scanning with stubs it should be emptied out, as its no longer valid (here the class provides its own params and return types).

**Comment by weirdan** [comment]
Thanks!
