### ISSUE TITLE
Improve documentation to have more contributors

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#4714]
It's almost 2 months that I starting looking on Psalm internals code, I know it evolved so fast (and it's nice because bug fixing and features are developed fast), but the code it's not easy to understand. It's not something relative to php internals knowledge or something else, it's about the excessive use of arrays and more.

I would like to contribute, but it's not easy to understand the code, and I can't dedicate days to understand just a piece of code, I think it's something that discurage a lot of developers. Maybe for some people can be easier, but I contribute often on PHP projects, and it's quite difficult in this project.

Just an example:
```php
$template_result->upper_bounds[$template_name] = [
    'fn-' . $function_id => [Type::getEmpty(), 0]
];
```

It's normal to ask myself: what is it that zero? Why is it a tuple? Why later is an array of 3 elements?
Maybe comments on there and where it's used will help me to understand in less time.

So I propose and ask to improve documentation on code, even using comments, description on methods, on classes, on primitives and value-objects.
I saw there are just few contributors, and a lot of issues to handle, and giving some help to understand, can help developers to contribute and choose Psalm over other projects.

Then, maybe, in the future would be nice a refactor, before the codebase will be too much big.

BTW, a lot of good work has been done on this project, so.... thanks to all the people working on it!

**Comment by weirdan** [comment]
I certainly share the sentiment - Psalm has a high entry barrier, but then the domain is not easiest either. However somebody has to actually do this (read: this is question of available resources), and Psalm has been largely @muglug's one-man show so far. This seems to be changing slowly (e.g. @orklah is fairly active recently, with some very nice contributions). 

Surely you've learned something about Psalm internals during those two months, mind creating some PRs to share the knowledge?

**Comment by TysonAndre** [comment]
- I'd expect the problem domain of writing a static analyzer is going to be complex and take months to understand the specifics of that analyzer for new contributors, even with good documentation or a refactoring - I'm familiar with a different static analyzer, but I'm only slightly familiar with Psalm (enough to write a few plugins)
- Some functions are hundreds of lines long and low on documentation - in some cases that's unavoidable (e.g. union type logic) but often functionality can be moved to helper methods if it isn't performance sensitive 
- Some classes/methods/properties didn't have any documentation - enforcing the existence of documentation (e.g. one line summary) may help people understand the intent of methods they've never seen before or where new code should be added. It's possible to write a plugin to check for summaries in comments, or to [reuse something else](https://github.com/phan/phan/blob/master/.phan/plugins/HasPHPDocPlugin.php) for phpcs or other tools

**Comment by orklah** [comment]
I noticed this too, There's a lot of times where there's an obscure notion in code and I have to spend time just to look at similar patterns somewhere else to understand what's going on. There's even features or bugs that I tried to implement for hours and just gave up for now due to obscure functionnality. But as @weirdan said, @muglug is pretty much alone for now and I prefer having bug fix and new features for now than documentation.

I may try to add some documentation in the near future in code that I understand enough, but it's a long term task

**Comment by muglug** [comment]
> Psalm has been largely @muglug's one-man show so far

Luckily I’m not *that* alone — about 7/8ths of all commits are mine, which is roughly on par with other complex open-source projects lead by a single active developer (or company) — but I accept all the points above about the code’s inscrutability.

As concerns the size of individual functions, a couple of weeks ago I started working on a metric that highlights which functions are too long and complex based on each function’s data-flow graph. I then got side-tracked with a flurry of contributions related to taint analysis, but I plan to get back to that earlier work. That metric will guide my work to break too-large functions, and will hopefully become something that breaks the build whenever a function becomes too large. You can play with it by [making this value “true”](https://github.com/vimeo/psalm/commit/bf696bf82e4db14fc70a7af7836f7c652be67188#diff-2d20a98059390e83ae58234d4bda07fe9319b822009ce8c4479e0f3ae1943fbfR17) and running Psalm with the `--no-diff` flag

It would also be interesting to explore breaking the build whenever a function with a high complexity level doesn’t have a docblock description.

Thanks for bringing up the use of tuples in template upper-bounds — a very good point, and it should be simple to refactor into an object. The template code is the toughest to understand in Psalm’s codebase, mainly because it’s doing incredibly complicated things. I’m not sure proper documentation in the templating code will spur many new contributions, but at least it’ll help me whenever I have to revisit that code to fix bugs.

**Comment by muglug** [comment]
@thomasvargiu I've made the change to the template result bounds, with a bit of documentation in 5f065d3

**Comment by thomasvargiu** [comment]
@muglug fantastic! It was just an example, but it's what I hoped would happen, a focus on this kind of thing, improve code readability! Thanks! Hope this kind of approch will continue, refactoring small pieces when it's possible, step by step, when implementing or fixing something. I'm sure in the future it will help other contributors!

**Comment by muglug** [comment]
> It was just an example

If you have any similar examples, please create a ticket!

**Comment by muglug** [comment]
You can now see the really complex methods in master by running `./psalm --show-info=true`. If any of you want to take a stab at one of these 18 methods, you'll have my undying respect and admiration.

```
INFO: ComplexMethod - src/Psalm/Internal/Analyzer/ClassAnalyzer.php:100:21 - This method’s complexity is greater than the project limit (method graph size = 241, average path length = 136) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php:143:21 - This method’s complexity is greater than the project limit (method graph size = 220, average path length = 178) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php:531:29 - This method’s complexity is greater than the project limit (method graph size = 346, average path length = 165) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php:1227:29 - This method’s complexity is greater than the project limit (method graph size = 396, average path length = 168) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php:1896:28 - This method’s complexity is greater than the project limit (method graph size = 202, average path length = 159) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php:65:28 - This method’s complexity is greater than the project limit (method graph size = 388, average path length = 111) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/InstancePropertyAssignmentAnalyzer.php:63:28 - This method’s complexity is greater than the project limit (method graph size = 302, average path length = 367) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php:58:28 - This method’s complexity is greater than the project limit (method graph size = 292, average path length = 310) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php:439:28 - This method’s complexity is greater than the project limit (method graph size = 291, average path length = 164) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php:40:28 - This method’s complexity is greater than the project limit (method graph size = 206, average path length = 134) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php:38:28 - This method’s complexity is greater than the project limit (method graph size = 326, average path length = 319) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php:377:28 - This method’s complexity is greater than the project limit (method graph size = 747, average path length = 311) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php:49:28 - This method’s complexity is greater than the project limit (method graph size = 267, average path length = 208) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php:41:28 - This method’s complexity is greater than the project limit (method graph size = 258, average path length = 165) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php:121:21 - This method’s complexity is greater than the project limit (method graph size = 229, average path length = 232) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Type/AssertionReconciler.php:49:28 - This method’s complexity is greater than the project limit (method graph size = 268, average path length = 102) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Type/TypeCombiner.php:77:28 - This method’s complexity is greater than the project limit (method graph size = 229, average path length = 79) (see https://psalm.dev/260)

INFO: ComplexMethod - src/Psalm/Internal/Type/TypeParser.php:118:28 - This method’s complexity is greater than the project limit (method graph size = 430, average path length = 190) (see https://psalm.dev/260)

```

**Comment by TysonAndre** [comment]
Related to https://github.com/vimeo/psalm/issues/304 ("Write Contributing guidelines/Developing guidelines?")

**Comment by TysonAndre** [comment]
https://psalm.dev/docs/what_makes_psalm_complicated/  https://psalm.dev/docs/how_psalm_works/ - I see that these pages are on the psalm.dev site, but I'm not sure what links to them if you're looking for them from the home page of psalm.dev. The index.html page generated from https://psalm.dev/ doesn't seem to have an obvious link to either that or "contribute"? (but the docs on writing plugins are linked)

(But the repo itself does a good job of this - https://github.com/vimeo/psalm/blob/master/CONTRIBUTING.md is linked to from the main README)

https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/ - it might make sense to link to the how psalm works page from the plugin guide (e.g. for the description of how to get property/class constant/class declaration info from storage)

**Comment by muglug** [comment]
@TysonAndre I've consolidated the contributing docs here: https://psalm.dev/docs/contributing/ (now linked to by CONTRIBUTING.md

**Comment by mr-feek** [comment]
> There's even features or bugs that I tried to implement for hours and just gave up for now due to obscure functionnality

Hah, I share this sentiment too! It makes me wonder, _am I dumb, is @muglug merely a demigod_ 😂 

When tracing through the internals via xdebug, I often find myself wondering _what_ a specific variable is. I can almost certainly chalk this up as not having a strong background within the theory of computer science and type systems, but perhaps this is a barrier we can work to dismantle.
-------


I'm totally just going to nitpick a random chunk of code I've come across before, and wondered what two different variables really represented.

https://github.com/vimeo/psalm/blob/master/src/Psalm/Plugin/Hook/MethodReturnTypeProviderInterface.php#L17-L37

```
public static function getMethodReturnType(
        StatementsSource $source,
        string $fq_classlike_name,
        string $method_name_lowercase,
        array $call_args,
        Context $context,
        CodeLocation $code_location,
        ?array $template_type_parameters = null,
        ?string $called_fq_classlike_name = null,
        ?string $called_method_name_lowercase = null
    ): ?Type\Union;
```
Just from looking at this, I don't have the slightest clue as to what `called_method_name_lowercase` is vs. `method_name_lowercase`. I typically just set an xdebug breakpoint and look at them to see which is the one that I want.

--------------------

Honestly, there are lots of terms that I don't understand (or didn't at first) in the codebase. Would any sort of glossary be worthwhile do we think?

AKA `lhs_type_part`, `classlike`, `naive_method_exists`, the likes.

**Comment by weirdan** [comment]
LHS and RHS are fairly standard: **L**eft-**H**and **S**ide and **R**ight-**H**and **S**ide. These usually refer to the corresponding operands of an infix binary operator (`LHS op RHS`).
'Classlike` seems to be inherited from `nikic/php-parser` and refers to class, interface or trait.

**Comment by weirdan** [comment]
You may also see FQ, FQCLN or FQCN in Psalm's source code - these are **F**ully-**Q**ualified <something>, **F**ully-**Q**ualified **C**lass**L**ike **N**ame and **F**ully-**Q**ualified **C**lass **N**ame, respectively.

**Comment by muglug** [comment]
yeah, the FQ prefix I picked up from browsing Phan's source code. Early on I had no idea what I was doing.

Method calls are complex.

When I call `$foo->bar()` there are three interesting different method ids:

```php
trait T {
  public function traitDefinedBar() : void {}
}

class FooParent {
  use T {
    traitDefinedBar as bar;
  };
}

class Foo extends FooParent {}
```

The called classlike is `Foo` and the called method name is `bar`.
The appearing classlike (the one that `bar` appears in) is `FooParent`
The declaring classlike is T and the declaring method name is `traitDefinedBar`.

The main invocation of the plugin is here:

https://github.com/vimeo/psalm/blob/e702e472fc89d91fd243283aa349e0e7fc8509f6/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php#L69-L79

You can see that the declaring classlike & method name are passed in at the top and, a bit less obviously, the calling class and name are passed lower down

**Comment by muglug** [comment]
I'm certainly not a demigod.

As @TysonAndre mentioned above there's a certain amount of implicit complexity around static analysis –– code I've written for Psalm is far more complex (by necessity) than anything I've written for Vimeo.

Still, there's clearly more I can do to document the code for the people who come after me. I'm making some small strides, but more awaits.

**Comment by orklah** [comment]
I'll close this, documentation was improved since the creation of this ticket, and *ancient knowledge* has been lost :D 

No point in keeping this open for now
