### ISSUE TITLE
Int accepted as float in iterable template definition

### ISSUE THREAD

**Issue by zoltanka** [vimeo/psalm#4715]
I don't know if its a bug or not, I couldn't find anything in the documentation regarding this, BUT I think this is a bug.

This is accepted
```php
/**
 * @return array<int, ?float>
 */
public function getBar(): array
{
    return [1, 2, 4, 5];
}
```

But neither are accepted:

```php
/**
 * @return array<int, ?int>
 */
public function getFoo(): array
{
    return [1.3, 2.1];
}
    
/**
 * @return float
 */
public function getBaz(): int
{
    return 2;
}
```

https://psalm.dev/r/e0f4629d30

**Comment by orklah** [comment]
I don't think this is a bug.

We consider float to be more precise than int. You can cast (implicitly or nor) an int to float without losing data, so whenever a float is expected, you can send an int. This explains the first case.
However, the second case is inverted, you declare int but you send floats. Even if it's just in documentation, this is not safe and  is either a documentation error or a code error.
The third case is different, Psalm says that you declared different types in documentation and signature. This means, even if you declare a float in signature but actually return an int, Psalm will be okay with it.

**Comment by zoltan-fekete** [comment]
Well now I just tested that even the PHP accepts `int` passed to a `float` parameter. I just never did this... well. Then fine by me I'll still not pass back an `int[]` for `float[]`. Maybe creating an option to handle this strictly?

**Comment by orklah** [comment]
I wish that existed too 👍 

But PHP has its quirks, for example, ceil/floor will always return float. This would mean add casts at every usage
