### ISSUE TITLE
Invalid docblock type in external library causes UndefinedDocblockClass on it's method calls

### ISSUE THREAD

**Issue by jackbentley** [vimeo/psalm#4720]
We use the library https://github.com/ADOdb/ADOdb at version 5.20.18. The method `ADOConnection::qstr()` has an invalid docblock return clause:

```php
	/**
	 * ...
	 * @return  quoted string to be sent back to database
	 */
	function qstr($s,$magic_quotes=false) {
```
https://github.com/ADOdb/ADOdb/blob/v5.20.18/adodb.inc.php#L2978-L2980

When running Psalm on our codebase, this causes the following error on method usage:
```
ERROR: UndefinedDocblockClass - src/test.php:18:16 - Docblock-defined class or interface quoted does not exist (see https://psalm.dev/200)
        return $this->ado->qstr('foobar');
```

The error shouldn't be emitted on the method call. This is confusing and incorrect.

If the class was part of the same code base, this error is not emitted on the method call. It's instead emitted in the docblock definition correctly:
https://psalm.dev/r/4c83f864d9

However, when the class definition is outside the `<projectFiles>` directive, it emits the error mentioned above.

Reproducer repo:
https://github.com/jackbentley/psalm-reproduce-UndefinedDocblockClass

**Comment by weirdan** [comment]
Does this also happen if you **don't** call the method, but just fetch the property, e.g. `$this->ado;`?

**Comment by jackbentley** [comment]
> Does this also happen if you **don't** call the method, but just fetch the property, e.g. `$this->ado;`?

It doesn't happen when just fetching the property, no

**Comment by weirdan** [comment]
Until this gets looked at, the way to overcome this would be to add a stub file ([docs](https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/#stub-files)) where the method would be overridden as `@return string`, then reference it in `psalm.xml` ([docs](https://psalm.dev/docs/running_psalm/configuration/#stubs)).

Frankly, I'm not sure it's a bug. Usually Psalm is configured to not report anything in vendor folder, but this issue affects what it infers for the code that is calling the method, so if it was suppressed it could lead to even more confusing results (e.g. https://psalm.dev/r/62d6ecb8dc).

Proper way to deal with it is either to fix the library or to stub.

**Comment by muglug** [comment]
Yeah, this is by design. Stubbing out the dependency is the way to go (or using a `@var` docblock)

**Comment by jackbentley** [comment]
Thanks for the workaround suggestion. It looks like it's been fixed in the library, but not released yet.

I do think **it's a bug**, though. And the reason for it being confusing it that it's moaning about a docblock on a method call that has no docblock - that's weird and confusing.

<details>
<summary>With <code>src</code> set to <code>./</code> in the reproducer repo, it gives the following output:</summary>

```
ERROR: UndefinedDocblockClass - external/external.php:6:16 - Docblock-defined class or interface quoted does not exist (see https://psalm.dev/200)
     * @return quoted string


ERROR: MissingParamType - external/external.php:8:26 - Parameter $string has no provided type (see https://psalm.dev/154)
    public function qstr($string) {


ERROR: InvalidReturnType - src/test.php:15:16 - The declared return type 'string' for Foo::bar is incorrect, got 'quoted' (see https://psalm.dev/011)
     * @return string


ERROR: InvalidReturnStatement - src/test.php:18:16 - The inferred type 'quoted' does not match the declared return type 'string' for Foo::bar (see https://psalm.dev/128)
        return $this->ado->qstr('foobar');
```
</details>


<details>
<summary>With <code>src</code> set to <code>./src/</code> in the reproducer repo, it gives the following output:</summary>

```
ERROR: InvalidReturnType - src/test.php:15:16 - The declared return type 'string' for Foo::bar is incorrect, got 'quoted' (see https://psalm.dev/011)
     * @return string


ERROR: UndefinedDocblockClass - src/test.php:18:16 - Docblock-defined class or interface quoted does not exist (see https://psalm.dev/200)
        return $this->ado->qstr('foobar');


ERROR: InvalidReturnStatement - src/test.php:18:16 - The inferred type 'quoted' does not match the declared return type 'string' for Foo::bar (see https://psalm.dev/128)
        return $this->ado->qstr('foobar');
```
</details>

 - The two are inconsistent.
 - It took me a while to understand what the `UndefinedDocblockClass` on the method call was referring to.
 - It gives no information that it's about the method that's being called and not the calling of the method its self.

My preferred output would be only the `InvalidReturnType` and `InvalidReturnStatement` errors as seen in your example. This gives sufficient information for me to fix what's happening - be that by a stub or a PR to the library.

Alternatively, there could be scope for a new error type here. But either way, `UndefinedDocblockClass` on a method call is just plain wrong.

**Comment by weirdan** [comment]
Docblock class is a class referenced in docblock, somewhere. What I think may help is an indication of where it was referenced from that caused an error - @muglug do you think it would be easy to add? E.g. something like:
```
ERROR: UndefinedDocblockClass - src/test.php:18:16 - Docblock-defined class or interface quoted (in external/external.php:6:16) does not exist (see https://psalm.dev/200)
```

**Comment by jackbentley** [comment]
Another reason this is a bug is that if I fix the variable locally, the error is still emitted:

```
-        return $this->ado->qstr('foobar');
+        /** @var string $response */
+        $response = $this->ado->qstr('foobar');
+
+        return $response;
```

I've updated the reproducer repo.
