### ISSUE TITLE
mutation-free annotation is not inherited from interface

### ISSUE THREAD

**Issue by andrew-demb** [vimeo/psalm#4721]
https://psalm.dev/r/04cd73cd7a

Expected: no errors - implementation without explicit annotation `@psalm-mutation-free` are also mutation free

Is it intended to force developers explicit write annotation?
https://psalm.dev/r/110632d86e (no errors with explicit annotation)

**Comment by weirdan** [comment]
> Is it intended to force developers explicit write annotation?
It is, there's even `MissingImmutableAnnotation` specifically intended to signal this to the end user.
However accessing a properly typed property (either natively or with a docblock) somehow suppresses this issue: https://psalm.dev/r/d0e1559878

**Comment by andrew-demb** [comment]
Thank you for explanation.
Should I open separated issue to track this "suppressing"?

**Comment by weirdan** [comment]
Yes please.
