### ISSUE TITLE
Offers to fix ComplexMethod but fails to do so

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#4728]
Can't be bothered to reproduce on psalm.dev. Reproducible with current master on Psalm's own codebase:

![image](https://user-images.githubusercontent.com/57403/100524468-18d51900-31c1-11eb-9c76-6ca38dbbd44b.png)

**Comment by muglug** [comment]
Oof definitely not deliberate — fixing ComplexMethod is certainly beyond Psalm’s understanding

**Comment by weirdan** [comment]
That's a pity - I had hopes for a moment :rofl:

**Comment by muglug** [comment]
I've tried using PhpStorm's `Extract Method` functionality to slim down [these methods](https://github.com/vimeo/psalm/issues/4714#issuecomment-735005994) and it's surprising there aren't more bugs, given how complex its analysis has to be. I can't imagine anyone has touched that code in a good long while (the feature was added in 2011).
