### ISSUE TITLE
Spurious InvalidReturnType resulting from try/finally construct

### ISSUE THREAD

**Issue by duskwuff** [vimeo/psalm#473]
The following code generates an `InvalidReturnType` warning ("Not all code paths of missing_return end in a return statement"):

```
function missing_return() : bool {
    try {
        return true;
    } finally {
    }
}
```

However, even if the code in the `try` clause could throw an exception (which I'll grant; tracking exceptions is outside the scope of Psalm), any such exception would be propagated after running the `finally` clause. There's no way for code flow to leave the `try` block.

**Comment by muglug** [comment]
Thanks. It had not occurred to me to check for this useful pattern.
