### ISSUE TITLE
Nested template params are not getting matched

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#4731]
Work as expected: https://psalm.dev/r/c6e26f711f

But if I change return type of `Map::__invoke`
from `array<array-key, TOut>`
to `$items is non-empty-array ? non-empty-array<array-key, TOut> : array<array-key, TOut>`
then psalm will stop verify input arguments of `Map::__invoke`

https://psalm.dev/r/901e3c7476

**Comment by muglug** [comment]
Under the hood that code is converted to this (which exhibits the same bug): https://psalm.dev/r/c624585f60
