### ISSUE TITLE
False negative with generics

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#4733]
Found in Doctrine Collections (https://github.com/doctrine/collections/pull/258#discussion_r532218343)
https://psalm.dev/r/0e6ed07b18

The problem here is that Psalm fails to verify that `createFrom()` expects `array<TKey,T>`, but is getting passed `array<TKey,U>`. 
PHPStan catches this: https://phpstan.org/r/6f58c4f8-5985-440f-a152-cfa6ee048091

Obviously the code is wrong as `createFrom()` should have been declared generic, but Psalm should have flagged this.

**Comment by muglug** [comment]
Simplified: https://psalm.dev/r/da5e7436e0
