### ISSUE TITLE
UndefinedThisPropertyFetch on properties set during runtime

### ISSUE THREAD

**Issue by ekisu** [vimeo/psalm#4737]
I'm trying to use Psalm on some CakePHP code, and it has a lot of code that looks like this (https://psalm.dev/r/d9e3504a05). Those properties set by the `loadModel` call seem to go undetected by Psalm, causing an `UndefinedThisPropertyFetch` error. Is there a way to deal with those errors, aside from just supressing the issue entirely?

**Comment by weirdan** [comment]
No, not really.

**Comment by orklah** [comment]
I'd advice using https://psalm.dev/r/33e261ddc8
The error is still there in psalm.dev but there is a config you can add is psalm.xml: usePhpDocPropertiesWithoutMagicCall="true"

I think this should do the trick

**Comment by ekisu** [comment]
Whoa, didn't expect to be replied so quickly. Alright, thanks, the docblocks seem to be a good way out of this.
