### ISSUE TITLE
INFO messages highlight code with white-on-white

### ISSUE THREAD

**Issue by duskwuff** [vimeo/psalm#474]
`Psalm\IssueBuffer::getConsoleOutput()` uses the escape sequence `\e[;47m` to highlight code for INFO output. This escape sequence sets the background to white without setting a foreground color, resulting in unreadable white-on-white output in white-on-black terminals.

Consider using `\e[30;47m` to explicitly request black-on-white, or `\e[7m` for inverse video.

(A similar issue exists in the use of `\e[0;31m` for the word "ERROR", although it's less likely to be noticed, as red terminal backgrounds are uncommon.)

**Comment by muglug** [comment]
Thanks. I noticed this a week ago in Travis, but was super lazy about fixing.

**Comment by muglug** [comment]
Broken by https://github.com/vimeo/psalm/commit/49981f63c649c24b4c09354129ad47fd6749e567
