### ISSUE TITLE
Overriding list items by existing key makes it not a list anymore

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#4741]
When overwriting list keys this way:

```php
$list = ['a', 'b', 'c'];

foreach ($list as $key => $value) {
    $list[$key] = $value . '!';   
}
```

The list becomes an `array<int, string>`, even though it should stay a `list<string>`.

https://psalm.dev/r/5e22300c5c

*Note: I do know that I'd better use `array_map()` in such a case!*

**Comment by muglug** [comment]
Yeah, this is a known bug (as in, I know about it).

It's definitely a tricky one though. For this to work, Psalm would need to be sure `$key` was a member of `$list`'s keys.

So something like this:

```
$list = ['a', 'b', 'c'];

foreach ($list as $key => $value) {
    $list[$key + 1] = $value . '!';   
}
```

Would still invalidate the list type.

**Comment by muglug** [comment]
It's so hard, in fact, that I'm tempted to close this 😕

**Comment by alexanderpas** [comment]
Some form of array taint analysis might be the solution here.

If we have a list, there are only a few actions we can do, without breaking the list data type.

- Writing to any key between the start (0) and the end of the list.
- Removing the last item from the list.
- Writing to the position which would be the next item in the list.

While any of the following actions would break the list datatype automatically:

- Writing to any key which is beyond the next item on the list.
- Removing any key which is not the last item on the list.

**Comment by BenMorel** [comment]
> - Removing the last item from the list.

Actually, all `array_push()`/`pop()`/`shift()`/`unshift()` should be allowed?

**Comment by weirdan** [comment]
> Actually, all array_push()/pop()/shift()/unshift() should be allowed?

They are allowed: https://psalm.dev/r/cc9f4c576b

**Comment by muglug** [comment]
This is currently blocked by #4794, but once that's fixed it should be _relatively_ easy

**Comment by muglug** [comment]
Still quite hard

**Comment by muglug** [comment]
I've fixed the examples given in the issue description, but there are still some false-positives I'm seeing in Psalm's own codebase that I would have hoped this had fixed.

**Comment by muglug** [comment]
For reference: https://github.com/vimeo/psalm/blob/a4ac52aea467d2e53f75db17c913195348dc200a/src/Psalm/Internal/Type/AssertionReconciler.php#L745

I think it’s due to nested loops

**Comment by muglug** [comment]
ACTUALLY never mind, they were all special cases and this _is_ fixed.

**Comment by BenMorel** [comment]
This is awesome, thanks! 🎉
