### ISSUE TITLE
Performance issue with array_key_exists

### ISSUE THREAD

**Issue by gdejong** [vimeo/psalm#4743]
After upgrading from `v4.1.1` to `v4.2.1` I noticed Psalm took a very long time to run in my project. I narrowed it down to coming from `v4.2.0`.

See https://psalm.dev/r/c96b5ec5ba

Some items in the map are commented out, here is why:

This example runs on my PC in ~2s.
Including the `k` element, Psalm runs in ~4s.
Including the `l` element, Psalm runs in ~11s.
Including the `m` element, Psalm runs in ~44s.

Here comes the best part:
Including the `n` element, Psalm runs in ~2s.
Including more items seems to not affect runtime performance anymore.

In my project I happened to have a similar construct as the example with exactly 13 items.

Any idea on what's going on?

**Comment by weirdan** [comment]
Reproducible on psalm.dev: 
![image](https://user-images.githubusercontent.com/57403/100632085-14317180-3335-11eb-857d-152f8f2c38cc.png)

**Comment by gdejong** [comment]
Thanks!
