### ISSUE TITLE
@psalm-suppress MethodSignatureMismatch doesn't work when overriding a class with `@final`

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#4751]
See https://psalm.dev/r/d5b55a598b

**Comment by weirdan** [comment]
And the use case would be to override a third-party class declared `@final`?

**Comment by VincentLanglet** [comment]
> And the use case would be to override a third-party class declared `@final`?

Yes.

Sonata use @final to inform that the class will be final in next major version ; but currently we can still override it.
I wont have to override this class in next major (since all the changes needed are already done) but until that I need to.

**Comment by muglug** [comment]
I don't think this is a bug – presumably there should still be some sort of warning when overriding a class with `@final`? Otherwise what's the point in Psalm supporting it?

**Comment by VincentLanglet** [comment]
> I don't think this is a bug – presumably there should still be some sort of warning when overriding a class with `@final`? 

`@final` is just an annotation ; there is maybe some warning but no php error.

> Otherwise what's the point in Psalm supporting it?

I changed the title of my issue: my concern is the fact that `@psalm-suppress MethodSignatureMismatch` doesn't work for this case. I understand the fact that Psalm return a warning, but I should be able to silent it if I have good reason.

**Comment by muglug** [comment]
Ok, them `MethodSignatureMismatch` is wrong for `@final`.

The fix will be to add some sort of flag to denote that the `final` comes from a docblock.

@weirdan I understand why this could be considered a bug, it's sort of on the edge.

**Comment by weirdan** [comment]
Yeah, my thinking was like: if I suppress the issue it shouldn't be reported.

**Comment by muglug** [comment]
Now suppressing will work, but only when the `@final` annotation is used instead of the language-level one

**Comment by VincentLanglet** [comment]
Thanks a lot !
