### ISSUE TITLE
PossiblyUndefinedIntArrayOffset when null coalescing operator ?? on array

### ISSUE THREAD

**Issue by jsiefer** [vimeo/psalm#4752]
Hi

I just tried the latest version. This seems to be a false positive.

https://psalm.dev/r/7812b726b5

**Comment by weirdan** [comment]
Interesting. I did not realize that `??` could suppress all null-related warnings, including those in more complex expressions like chained property fetches: https://3v4l.org/00KGD

**Comment by muglug** [comment]
Yeah, I believe this is just in latest master – thanks for this testcase

**Comment by muglug** [comment]
Since Psalm (in latest master) now treats null coalesce almost identically to `isset`, this issue also occurs in the `isset` equivalent (in the latest release):

https://psalm.dev/r/8ba0ed8a16
