### ISSUE TITLE
verify constants via arary-key 

### ISSUE THREAD

**Issue by voku** [vimeo/psalm#4753]
I can't verify constants values, if the constants are in the key and not in the value of an array.

https://psalm.dev/r/8f08c9fdcc

**Comment by orklah** [comment]
simpler reproducer:
https://psalm.dev/r/f7f624f571

This is complicated for a lot of reasons:
- PHP implicitly casts array-keys *sometimes*
- array_key_exists doesn't have a strict flag (the example with in_array above doesn't work with strict flag to false)
- isset will return false if the array-key is present but its value is null

**Comment by muglug** [comment]
I've fixed the `array_key_exists` check in 6f91655 – that was due to Psalm not honouring _int_ keys, only string ones, in `array_key_exists`.

I'm not going to fix the `isset($values[$key])` one because that sadly doesn't tell us everything we'd want due to array key permissiveness.

**Comment by voku** [comment]
Thanks for the fix that was fast. :D
