### ISSUE TITLE
Too many suppressions required

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#476]
Until some recent master version it was enough to only suppress `ImplementedReturnTypeMismatch` here. Now I have to individually suppress 4 issues instead of 1.
```php
use Monolog\Handler\HandlerWrapper;

class PsrLogWrapper extends HandlerWrapper
{
    /**
     * @psalm-suppress ImplementedReturnTypeMismatch parent has wrong return type
     * @psalm-suppress InvalidReturnType
     * @psalm-suppress InvalidReturnStatement
     * @psalm-suppress UndefinedClass
     * @todo: remove suppression when https://github.com/Seldaek/monolog/pull/1037 is merged
     */
    public function handle(array $record): bool
    {
        $record['context']['monolog_channel'] = $record['channel'];
        $record['context']['monolog_extra'] = $record['extra'];
        return parent::handle($record);
    }
}
```
The culprit here is parent docblock, which defines return type to be `Boolean` (instead of `bool`, fixed in the referenced PR, but not merged upstream yet).

To reproduce you need to `composer require monolog/monolog:^1.22`

**Comment by muglug** [comment]
Yeah, I hate that signature. The simplest workaround is:

```php
class A {
  /** @return Boolean */
  public function foo() {
    return true;
  }
}

class B extends A {
  /** @psalm-suppress ImplementedReturnTypeMismatch */
  public function foo(): bool {
    return (bool) parent::foo();
  }
}
```

If you don't want the explicit cast you can do

```php
class B extends A {
  /** @psalm-suppress ImplementedReturnTypeMismatch */
  public function foo(): bool {
    /** @var bool */
    return parent::foo();
  }
}
```

**Comment by weirdan** [comment]
That would still complain about `UndefinedClass`, but at least it's two suppression tags instead of 4.

**Comment by muglug** [comment]
Right, yes. It might be useful to allow projects to define the ways in which they manipulate (or correct issues with) packages they use. Maybe via explicitly partial stub files?

**Comment by weirdan** [comment]
That could be quite useful indeed, for example for doctrine classes with magic methods and such.

**Comment by muglug** [comment]
Closing in favour of https://github.com/vimeo/psalm/issues/482
