### ISSUE TITLE
Write output to file and not fail

### ISSUE THREAD

**Issue by ttomdewit** [vimeo/psalm#4762]
Hi team 👋,

Over at `vimeo/psalm/src/Psalm/IssueBuffer.php:689` you've implemented to safeguards to not throw an exit code 1 to stop pipelines from running in GitHub Actions.

Is it at all feasible we can get this to work for GitLab as well?

Over at https://github.com/overtrue/phplint/pull/88 I proposed we use the `-q` or `--quiet` flag. Would this be an option?

Kind regards,

Tom

**Comment by ttomdewit** [comment]
> Hey @ttomdewit, can you reproduce the issue on https://psalm.dev ?

Unfortunately not. It's a core issue, rather than a code issue.

**Comment by weirdan** [comment]
Can't this be done externally, e.g. `psalm --with --whatever --options || [ $? -eq 1 ]`

**Comment by ttomdewit** [comment]
> Can't this be done externally, e.g. `psalm --with --whatever --options || [ $? -eq 1 ]`

I think so. Over at https://github.com/phpstan/phpstan/issues/4178#issuecomment-737920768 they mentioned a similar option.

I thought it best to support it natively but I’ll give these options a go first.

**Comment by ttomdewit** [comment]
I'm happy to report that the following line works in GitLab pipeline:

```sh
./vendor/bin/phpstan analyse app --level max --error-format=gitlab > phpstan.json || [ $? -eq 1 ]
```

**Comment by weirdan** [comment]
@ttomdewit note that the check for error code `1` (` [ $? -eq 1]`) is specific to Psalm. PHPStan may use different error code to signal successful completion with errors detected.

**Comment by ttomdewit** [comment]
> @ttomdewit note that the check for error code `1` (` [ $? -eq 1]`) is specific to Psalm. PHPStan may use different error code to signal successful completion with errors detected.

I’ve tested and confirmed it also works with PHPStan but that’s good to know!

**Comment by muglug** [comment]
@ttomdewit what about a PR to add the Gitlab check to Psalm, too?

**Comment by ttomdewit** [comment]
> @ttomdewit what about a PR to add the Gitlab check to Psalm, too?

Hi @muglug. Unfortunately I'm in no mental health position to implement such a feature. A shortcut works for me now.
