### ISSUE TITLE
False positive RedundantCast

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#4765]
https://psalm.dev/r/dc8cad0f30

`hexdec` can return float so `hexdec($x) + 1` can also be float.

**Comment by muglug** [comment]
When can `hexdec` return a float?

**Comment by enumag** [comment]
I don't know but the documentation claims so. https://www.php.net/manual/en/function.hexdec.php

**Comment by orklah** [comment]
>  The function can convert numbers that are too large to fit into the platforms int type, larger values are returned as float in that case.

**Comment by muglug** [comment]
OH @orklah the fix is to not complain about int casts if the type has the `$from_calculation` flag set

**Comment by orklah** [comment]
Ok, I'll check that
