### ISSUE TITLE
false-positive more specific type

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#4767]
see https://github.com/azjezz/psl/pull/104/checks?check_run_id=1490660317

**Comment by weirdan** [comment]
I believe this is a minimal reproducer: https://psalm.dev/r/08b0d969e9

**Comment by azjezz** [comment]
do you think it makes sense to revert https://github.com/vimeo/psalm/commit/6ed7a811463537d27f6669d6fd52946d0426621b? 

I'm making sure that PSL always has a successful build.

The bug with Psl\Collection + generics has appeared multiple times here:

- #3760
- #2849 
- #2581 
- #2569 
- #2556 

so in my opinion, Psl\Collection is a great  real-world test case for generics in Psalm.

**Comment by muglug** [comment]
Agreed – I disabled tests because at the time there were bugs in PSL, now the shoe is on the other foot.

This was broken by https://github.com/vimeo/psalm/commit/15a5bd5e295d3dcf4f9e97fce9b6b6f3e01fed28

**Comment by muglug** [comment]
To be clear, though, this is a different bug than those others

**Comment by muglug** [comment]
This is one of those fun times where a "straightforward" refactor exposed an underlying bug that had been there for a while – that after stubs have been scanned, all explicit _and_ implicit (via inheritance) implemented interfaces were re-evaluated. It was the implicit ones that were causing trouble.

I've re-enabled PSL integration tests with 5fc2b4e04

**Comment by azjezz** [comment]
Thank you for the quick fix.

but it seems there is still an issue with `getIterator` ( I see you added `@psalm-suppress` for it in the tests ), is the error valid? or awaiting a fix? https://github.com/azjezz/psl/runs/1498607963
