### ISSUE TITLE
implements and extends annotations of templated types aren't validated

### ISSUE THREAD

**Issue by BackEndTea** [vimeo/psalm#4770]
Maybe i'm misunderstanding something, but it looks like these templates aren't validated, meaning the following code will produce a type error, while psalm will think its all fine.

https://psalm.dev/r/47c9bb8b12

**Comment by weirdan** [comment]
https://psalm.dev/r/7bad8de902

Basically if `B::boo()` is flagged, then `B::gen()` should probably be too.

**Comment by orklah** [comment]
I think this is correctly flagged now
