### ISSUE TITLE
phar asset is missing for the release 4.3.1

### ISSUE THREAD

**Issue by lptn** [vimeo/psalm#4771]
https://github.com/vimeo/psalm/releases/tag/4.3.1

![image](https://user-images.githubusercontent.com/5278175/101087381-2fb1ac00-35c3-11eb-993b-834bf1af254f.png)

**Comment by orklah** [comment]
I think it was just building. It should be ok now

**Comment by lptn** [comment]
I see. Thanks, closing 

PS: I've created an issue for that because 4 hours passed from the release

**Comment by weirdan** [comment]
Phar is built by Travis, and Travis CI is anything but quick nowadays. We need to move phar builds elsewhere.
