### ISSUE TITLE
False positive function does not exist

### ISSUE THREAD

**Issue by GrahamCampbell** [vimeo/psalm#4773]
```
ERROR: UndefinedFunction - src/Util/Regex.php:105:34 - Function preg_last_error_msg does not exist (see https://psalm.dev/021)
```

But `symfony/php80-polyfill` is a dependency, so the function does exist.

**Comment by GrahamCampbell** [comment]
No, because that version is force marked as analyzing using PHP 8.0 instead of 7.4.

**Comment by GrahamCampbell** [comment]
Which causes a different error: https://psalm.dev/r/b4caf19d04.

**Comment by weirdan** [comment]
@GrahamCampbell does this still happen?

**Comment by SiebelsTim** [comment]
I think this is a duplicate of #4628

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell does this still happen?

Yes. Just verified this is still an issue on 4.8.1.

**Comment by GrahamCampbell** [comment]
> So it seems to look for the function in the current namespace instead of taking the globally defined from the polyfill?

No. I have the same issue when I write `\get_debug_type`.

**Comment by weirdan** [comment]
Mind reproducing it in a separate repo?

**Comment by GrahamCampbell** [comment]
What do you mean? You can reproduce it with 2 lines, exactly how I described:


```php
<?php

require __DIR__ . “vendor/autoload.php”;

get_debug_type(123);
```

**Comment by GrahamCampbell** [comment]
(Ignore the smart quotes… typing in an iPhone)

**Comment by SiebelsTim** [comment]
> Mind reproducing it in a separate repo?

As far as I'm concerned, this is a duplicate of #4628, where psalm cannot find autoloaded functions, that itself uses. It only happens when using Psalm via phar.

**Comment by GrahamCampbell** [comment]
Yeh, maybe. I'll leave this open for the maintainers to decide how they wanna track this. :)

**Comment by orklah** [comment]
@GrahamCampbell are you also using a phar?

**Comment by GrahamCampbell** [comment]
Yes... 😆

**Comment by Arkemlar** [comment]
Why is it closed? I have same problem by just importing this function:
```
use function Symfony\Component\DependencyInjection\Loader\Configurator\service_locator
...
service_locator($services)
```
Guess that will happen with any namespaced function same way.
