### ISSUE TITLE
is_a accepts `mixed` as first param

### ISSUE THREAD

**Issue by gmazzap** [vimeo/psalm#4776]
[`is_a()`](https://www.php.net/manual/en/function.is-a.php) signature says first param is `mixed`.

However, Psalm enforces it to be a object or a string.

Note that for the `instanceof` statement, which works pretty much same way, Psalm correctly accepts anything.

See https://psalm.dev/r/c456cebe2e

And see how in PHP that is fine code: https://3v4l.org/Rb2MP

**Comment by websupporter** [comment]
The related XML definition of `is_a`: https://github.com/php/doc-en/blob/master/reference/classobj/functions/is-a.xml#L12
