### ISSUE TITLE
issue with TypeDoesNotContainType & is_a()

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#478]
https://github.com/SignpostMarv/daft-object/blob/b8336110a6c6f70ff47d02a95c5cef3aed1ec0dd/tests/DaftObjectImplementationTest.php#L1354

I've got an issue where I'm suppressing psalm errors because psalm is asserting that `string does not contain SignpostMarv\DaftObject\AbstractDaftObject`, when said string is being checked as `is_a($className, DaftObject\AbstractDaftObject::class, true)`. While `string` might not contain the type, inside the code path where `is_a(string $object, string $class, true)` returns `true`, the assertion is irrelevant- the variable *does* have the specified type.

**Comment by muglug** [comment]
Ah right, sorry – those assertions assume that the first arg of `is_a` is an object, not a string. Will fix.

**Comment by muglug** [comment]
Fix is in `dev-master`
