### ISSUE TITLE
@extends annotation not working for interfaces

### ISSUE THREAD

**Issue by ndench** [vimeo/psalm#4781]
Modifying an interface results in a BC break. One way to get around this is to use annotations to specify added methods or extending other interfaces.

For some reason, the `@extends` annotation seems to be ignored on interfaces: https://psalm.dev/r/834e21b79e

You can see if you use `extends` it works as expected: https://psalm.dev/r/9aa201d8d7

**Comment by weirdan** [comment]
I believe you want `@mixin` here: https://psalm.dev/r/975f66e329
`extends` implies the instance would pass `instanceof` checks, and it's not true in your use case.

**Comment by ndench** [comment]
Right you are @weirdan. Thanks for the quick response, can't believe I missed that one in the documentation :sweat_smile:.

**Comment by weirdan** [comment]
> can't believe I missed that one in the documentation

The documentation itself misses it, so that doesn't come as a big surprise :laughing:
