### ISSUE TITLE
Reset key and value types when convert iterator to array

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#4783]
https://psalm.dev/r/b415b01d3c

```php
/**
 * @psalm-param iterable<array-key, string> $a
 * @return array
 */
function myfn(iterable $a): array {
    return array_map('strval', (array)$a);
}
```

**Comment by weirdan** [comment]
That cast doesn't properly convert iterator to array though. Yes, the result is array, but it has no data: https://3v4l.org/KbNSI

What you probably need here is something like this: https://psalm.dev/r/4755eae651

**Comment by vjik** [comment]
> That cast doesn't properly convert iterator to array though. Yes, the result is array, but it has no data: https://3v4l.org/KbNSI

In you example `function g()` not iterable (`is_iterable` returned false). For objectcs implemented `Traversable` (`is_iterable` returned true) cast via `(array)$var` correctly work,

**Comment by weirdan** [comment]
> In you example function g() not iterable (is_iterable returned false). 

Of course it's iterable: https://3v4l.org/WGILq

> For objectcs implemented Traversable (is_iterable returned true) cast via (array)$var correctly work,

Not really: https://3v4l.org/bgtr2

**Comment by vjik** [comment]
Thank you for examples!
I tested with ArrayObject, but not try simple IteratorAggregate.
