### ISSUE TITLE
Template with constant wildcard syntax T::* 

### ISSUE THREAD

**Issue by DanielBadura** [vimeo/psalm#4784]
I came to the issue that i couldn't use `Foo::STATUS_*` or better `Foo::*` syntax with templates. So my example would be `T::*`. Here i have an example: https://psalm.dev/r/5877b299ba

Should it already have worked, or better: Is this feature desired?
Some context: I'm trying to get more type safety for an enum library which is heavily working on constants defined in the child class.

**Comment by muglug** [comment]
No, this feature isn't supported (and I don't think it should be). If the [enum rfc](https://wiki.php.net/rfc/enumerations) passes there may be some more work around that, but for now I'm going to close this.
