### ISSUE TITLE
Missing TaintedHtml error

### ISSUE THREAD

**Issue by gharlan** [vimeo/psalm#4792]
https://psalm.dev/r/a1d12e2ca4

In line 22 there should be a TaintedHtml error, but it is missing.

**Comment by weirdan** [comment]
@gharlan nitpick - `$type` should be passed to `data()`. The output is the same though.

**Comment by gharlan** [comment]
Oh, you are right. Here is the correct code: https://psalm.dev/r/2e80fb2e24

**Comment by muglug** [comment]
OK so this is sort of a structural issue with conditional `@psalm-taint-escape`: it only works if it can determine the input directly e.g. https://psalm.dev/r/dcba8c8476

I've made a change so that now if it can't determine the input types it'll stop escaping.
