### ISSUE TITLE
Attempting to register two stubs for the same global function results in hard to trace errors

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#4795]
Psalm currently allows registering two different stubs for the same global method. The resultant behavior can be very hard to debug if you do not know that a second stub is being added.

I will take a stab at implementing. I can't think of any scenarios off the top of my head where two different stubs being registered for the same global function would be ideal?

**Comment by muglug** [comment]
>  I can't think of any scenarios off the top of my head where two different stubs being registered for the same global function would be ideal?

It isn’t. What do you think Psalm should do in that scenario?

**Comment by orklah** [comment]
Closing as stale
