### ISSUE TITLE
Wrong ftp_mlsd return type

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#4799]
According to documentation `ftp_mlsd` returns array or false. Psalm thinks it always returns an array.

https://www.php.net/manual/en/function.ftp-mlsd.php

**Comment by enumag** [comment]
https://psalm.dev/r/d73bb0b919

**Comment by TysonAndre** [comment]
There's a typo in the release notes - this should be a lowercase L in MLSD
https://www.php.net/manual/en/function.ftp-mlsd.php

```patch
- @villfa improved the return type for ftp_misd (#4830)
+ @villfa improved the return type for ftp_mlsd (#4830)
```
