### ISSUE TITLE
@property should apply to internal __get and __set calls

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#480]
This should generate an issue cc @nickyr 

```php
/**
 * @property string $foo
 */
class A {
  public function __get(string $name): ?string {
    if ($name === "foo") {
      return "hello";
    }
  }

  /** @param mixed $value */
  public function __set(string $name, $value): void {
  }
  
  public function badSet(): void {
    $this->__set('foo', new stdClass());
  }
}
```

**Comment by TysonAndre** [comment]
Similarly, should `@method` apply to internal __call and __callStatic calls?

**Comment by muglug** [comment]
@TysonAndre `@method` is [not currently supported](https://github.com/vimeo/psalm/blob/master/docs/supported_annotations.md#phpdoc-tags) - feel free to open a ticket or, even better, a PR ;)

**Comment by muglug** [comment]
I'm currently in the midst of a big refactor of the `Codebase` class, attempting to create a decent public API for plugins while breaking up the class. But it doesn't touch `MethodCallChecker` or `DependencyFinderVisitor`, where that functionality would be added, much at all

**Comment by muglug** [comment]
Update - refactor is done.
