### ISSUE TITLE
json_encode() causes: Detected tainted HTML

### ISSUE THREAD

**Issue by thomasbley** [vimeo/psalm#4800]
Should json_encode() be treated as a html sink?

https://psalm.dev/r/63f034a4ae

**Comment by muglug** [comment]
Yes I think so? e.g. `echo json_encode(['<script src=\'foo.js\'>']);` will be interpreted as code by the browser.

**Comment by muglug** [comment]
cc @LukasReschke unless I'm missing something

**Comment by LukasReschke** [comment]
`json_encode` should IMO stay a pass-through for HTML strings and not act as sanitiser by default.

XSS is still possible depending on the Content-Type and No-Sniff headers being set. For frameworks that have something like `new JsonResponse`, which set these headers properly, they should mark these as a sanitizer themselves.

Let's rather err here on detecting potential bad bugs. XSS bugs are account-take-overs after all and some companies like Facebook would pay around 40k for these in their bug bounty program. And everyone that uses some OOP-style MVC framework can just mark their JsonResponse handlers as sanitizers :)

That said, there is some stuff we could do on the $flags parameter for `json_encode`. If something like `JSON_HEX_TAG` is set, the risk is significantly minimized. (https://www.php.net/manual/en/json.constants.php) - That said, from my personal experience the amount this is used is minimal. (and I don't have the capacity at the moment to add this sadly. Will see if I can free some cycles for some other improvements though)
