### ISSUE TITLE
EmptyArrayAccess when assigning in null coalescing

### ISSUE THREAD

**Issue by xPaw** [vimeo/psalm#4802]
I have code similar to this: https://psalm.dev/r/e888d934a6

This error appeared in 4.3.0. Either it was detecting this correctly before, or it simply skipped it entirely.

**Comment by muglug** [comment]
Does the code look better than that? Because I'm not sure that's code I want Psalm to be able understand

**Comment by xPaw** [comment]
I do understand it's not exactly clear code (and can be fixed trivially), psalm does essentially report an incorrect error here though.

**Comment by muglug** [comment]
Yeah, this should be `PossiblyUndefinedVariable`: https://psalm.dev/r/70363de5b2
