### ISSUE TITLE
Idea: Support a non-null-mixed type, like non-empty-mixed?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#4809]
https://psalm.dev/r/48de2898a2

Low priority since psalm just warns about anywhere where mixed is inferred and this may require work in a lot of places to support. For codebases that are missing types, this may help detect some redundant checks, but not many.

Making it an alias for `mixed` just in phpdoc may be useful, but may not be widely adopted.

**Comment by muglug** [comment]
Yeah, I don't see much benefit in this, sorry
