### ISSUE TITLE
Psalm creates many 0-byte directories in $TMPDIR

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#4815]
Hey there,

I am currently debugging some stuff and checked my `$TMPDIR` for something psalm-unrelated.
However, I've realized, that there are thousands of temp directories related to psalm:

```
max@macbook [/var/folders/ty/7p8zhqjs2yd7v9sjgw6fwjc40000gn/T] 
→ ls -ld Psalmtemp_folder* | wc -l
    1318
```

Not sure if this is related to the latest PHPStorm integration or just due to the normal usage of psalm. 
However, having that many 0-byte directories will still consume inodes on non-macOS systems (afaik, macOS uses HFS+ which does not have inodes).

As I did not dig into the source of psalm, I am not sure if these folders are created by psalm or by PHPStorm tho.

Could someone has a look into that?

**Comment by weirdan** [comment]
Cache folders created by Psalm itself are SHA1 hashes of the project paths:
![image](https://user-images.githubusercontent.com/57403/101552865-43428580-39bc-11eb-9b8e-4da785e00c3f.png)

So you have as many cache folders as there are projects - and it's unlikely you have thousands.

Psalm does not create anything called `Psalmtemp_folder` (unless you configure it in `psalm.xml`). And the only two results on Google when searching for that name both lead to Jetbrains issue tracker ([WI-56216](https://youtrack.jetbrains.com/issue/WI-56216) and [WI-55972](https://youtrack.jetbrains.com/issue/WI-55972)). So I'd say it looks very much like PHPStorm issue.
