### ISSUE TITLE
Wrong inferred type from constant accessed via $this::

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#4822]
A code block is worth a thousand words:

```php
class View {
    protected const VALUES = [
    	'A',
        'B'
    ];
    
    protected function render(): string {
        return implode(', ', $this::VALUES);
    }
}
```

> INFO: MixedArgument - 10:30 - Argument 2 of implode cannot be mixed, expecting array<array-key, mixed>

When replacing `$this::VALUES` with `self::VALUES` it works fine, even though they're equivalent.

https://psalm.dev/r/0c978cf812

**Comment by weirdan** [comment]
`$this::CONSTANT` is an equivalent of `static::CONSTANT`, and it is not safe as it may get overridden by descendants: https://3v4l.org/JHM8K

**Comment by weirdan** [comment]
It should be ok for final classes, so still nominally a bug (https://psalm.dev/r/7279f3e529), but your original code should still be flagged.

**Comment by BenMorel** [comment]
Hmm, I understand, thanks. Indeed, `static::CONSTANT` reports the same error.

Not reporting it on final classes would do it for me! :+1:

**Comment by weirdan** [comment]
`static::CONSTANT` works now (when your class is final): https://psalm.dev/r/85d26a48b0

**Comment by orklah** [comment]
static::VALUES and $this::VALUES behave the same way now:
https://psalm.dev/r/ff0e80d21a

**Comment by BenMorel** [comment]
Thank you!
