### ISSUE TITLE
False positive on property is always isset

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#4823]
https://psalm.dev/r/0e302e2436

When calling `final public` method from constructor, that initializes the property, psalm wrongly thinks that the property is initialized and throws `RedundantPropertyInitializationCheck` and `RedundantCondition` when checking for `isset()`.

**Comment by muglug** [comment]
This is just one of those unavoidable things – I'd suppress the issue. There's no feasible way to square the circle.
