### ISSUE TITLE
Array shape is being misinterpreted when using array_filter

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#4824]
Hey there,

I want to verify if an array contains specific keys with specific types.
All keys are optional, thus I have to check for `nullOr*` and removing `null` afterwards.

https://psalm.dev/r/5e3c90aa3a

I would expect, that psalm realizes only the remained types after applying `array_filter` which drops all `null` values.

Do I have a design flaw in my logic and thus I could get to what I need in another way or is this something psalm could properly detect?

Thanks in advance!

**Comment by muglug** [comment]
Simplified to https://psalm.dev/r/7e40df2916

```php
/**
 * @param array{scheme:?string, user_info:?int} $c
 * @return array{scheme?:string, user_info?:int}
 */
function foo(array $c) : array {
    return array_filter(
        $c,
        function ($value): bool {
            return !is_null($value);
        }
    );
}
```

**Comment by boesing** [comment]
Hm, even tho it would be quite "easy" to tell psalm that due to the usage of `array_filter`, all `null` values will be dropped (as of the usage of `is_null`), this would become more complex with multi-line statements, etc.

Since I can fix my problem by just removing the closure from `array_filter` which will fallback to the PHP default (dropping all falsy values), I'll close this for now.

**Comment by AndrolGenhald** [comment]
I think this could be made to work by using assertions: https://psalm.dev/r/db921bff71
