### ISSUE TITLE
Switch fallthrough with gettype doesn't work as expected

### ISSUE THREAD

**Issue by theodorejb** [vimeo/psalm#4827]
I have a fallthrough case for both "double" and "integer" to return `true`. Psalm reports an error saying "Type float|int for $val is always double".

I can work around the error by adding an additional return statement instead of the fallthrough, but Psalm reporting an error for this code seems unexpected.

https://psalm.dev/r/e0ed7e072a

**Comment by theodorejb** [comment]
This is really strange. If the order of the "double" and "integer" cases is reversed, then Psalm doesn't report any error: https://psalm.dev/r/2320458f82.

Why is there an error when the double case is before integer?

**Comment by muglug** [comment]
> Why is there an error when the double case is before integer?

This is something I added eons ago because PHP always allows ints where a `float` is expected.

I should narrow that behaviour to function calls, return type checks and property setting
