### ISSUE TITLE
Psalm Hangs on chained eloquent query

### ISSUE THREAD

**Issue by robov** [vimeo/psalm#4831]
I am using laravel 8 and when I let psalm analyze my package it hangs and completely freezes up my entire system on this section
```
        $items = Context::where('project_id', $project->id)
            ->where('key', '=', $key)
            ->where('language', '=', $language)
            ->where('url', '=', $url)
            ->latest()
            ->get();
```

When I change it to the following, everything runs smoothly
```
        $items = Context::where('project_id', $project->id);

        $items
            ->where('key', '=', $key)
            ->where('language', '=', $language)
            ->where('url', '=', $url);

        $items
            ->latest()
            ->get();
```

**Comment by muglug** [comment]
Are you using the Laravel plugin?

**Comment by robov** [comment]
I AM using the laravel plugin

`    <plugins>
        <pluginClass class="Psalm\LaravelPlugin\Plugin"/>
    </plugins>`

**Comment by muglug** [comment]
Does it still hang if you disable the plugin?

**Comment by mr-feek** [comment]
This should technically be a bug in the plugin. I'm still debugging it. We can chat in https://github.com/psalm/psalm-plugin-laravel/issues/120

I have tracked it down to psalm incorrectly binding the type of `static` when in mixin-hell. I'll open a separate issue here when I can get a smaller repro.

**Comment by muglug** [comment]
Gonna close this out, but @mr-feek please feel free to ticket anything you find

**Comment by robov** [comment]
I can confirm by disabling the plugin psalm keeps running fine

**Comment by lptn** [comment]
@robov 
This issue was fixed in the plugin, version https://github.com/psalm/psalm-plugin-laravel/releases/tag/v2.5.0 (just for a history)
