### ISSUE TITLE
psalm-require-implements | psalm-require-extends not recognised

### ISSUE THREAD

**Issue by zoltanka** [vimeo/psalm#4838]
The `@psalm-require-implements` and `@psalm-require-extends` do not seem to be recognized. 
The problem not happen on psalm.dev, but locally I could reproduce this in all the projects I'm working with. Even in an empty project. 

```PHP
namespace Foo {
	interface IBaz {} 
}

namespace Where\The\Is {
    /**
     * @psalm-require-implements \Foo\IBaz
     */
    trait Bar { }   
}

namespace Something {
    use Where\The\Is\Bar;
    
    class ClassA {
        use Bar;
    }
}

```

https://psalm.dev/r/29f6fbf1d6

Can anybody reproduce the error? 

```
application@2d9cbf26933a:/app$ vendor/bin/psalm --version
Psalm 3.18.2@19aa905f7c3c7350569999a93c40ae91ae4e1626
```

**Comment by muglug** [comment]
Upgrade Psalm to version 4
