### ISSUE TITLE
UndefinedVariable for variable set in by-ref that should be PossiblyUndefinedVariable

### ISSUE THREAD

**Issue by CsabaNa** [vimeo/psalm#4839]
Might be i am wrong but i just started to use this tool. 
My problem is this tool set an undefined error e.g.: like this:
```
        if ($someCondition) {
            $command = 'some cli command';
            exec($command, $output, $returnVal);
        }

        if (!isset($returnVal) || $returnVal) {
            throw new RuntimeException('some msg');
        }
```
The error is:
```
ERROR: UndefinedVariable - src/test.php:10:20 - Cannot find referenced variable $returnVal (see https://psalm.dev/024)
        if (!isset($returnVal) || $returnVal) {
```
I think this is a false error as the if condition already checks the variable(`isset`).
So The `$returnVal` would exist if the exec was running(`!isset($returnVal)` > the exec was not running) 
if it was running `!isset($returnVal)` would be false so the other part of the condition will be executed and check its value.
the `if` condition processes left to right in case of `or` when the condition becomes false it will quit so in this case the second condition will never run so it is safe.

**Comment by CsabaNa** [comment]
It is weird but not on the page it is working fine. I used error level 6 in our project.(we are using stan on the highest level but wanted to check with this as well)

**Comment by CsabaNa** [comment]
I just created a similar what we have it is creating a database a simple class:
https://psalm.dev/r/fe12521850
it is not working on your page.
```
<?php

namespace App;

use Exception;
use PDO;
use RuntimeException;

class PsalmTestClass
{
    private PDO $pdo;
    public function __construct(PDO $pdo)
    {
        $this->pdo = $pdo;
    }

    /**
     * @throws Exception
     */
    public function createDatabase(?string $schema = null): void
    {
        $sql = 'CREATE DATABASE `some_database` DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`;';
        $stmt = $this->pdo->query($sql);
        if (!$stmt) {
            throw new RuntimeException('some error');
        }

        $credentials = '--host=localhost --user=\'user\' --password=\'pass\'';
        if ($schema && preg_match('#^\w*$#', $schema)) {
            $command = 'mysqldump  ' . $credentials . ' --set-gtid-purged=OFF ' . $schema .
                ' | mysql ' . $credentials . ' some_database';
            exec($command, $output, $returnVal);
        }

        if (!isset($returnVal) || $returnVal) {
            throw new RuntimeException('some error');
        }
    }
}

$t= new PsalmTestClass( (new PDO('credentials')) );
$t->createDatabase();
````
the simpler one is working: 
https://psalm.dev/r/e7b6db135f
```
<?php
$schema = 'something';
$c = rand(0, 1);
$credentials = '--host=localhost --user=\'user\' --password=\'pass\'';
if ($c && preg_match('#^\w*$#', $schema)) {
   $command = 'mysqldump  ' . $credentials . ' --set-gtid-purged=OFF ' . $schema .
      ' | mysql ' . $credentials . ' some_database';
   exec($command, $output, $returnVal);
}

if (!isset($returnVal) || $returnVal) {
   throw new RuntimeException('some error');
}
```

**Comment by weirdan** [comment]
Initializing the variable outside of that if should help.

**Comment by weirdan** [comment]
E.g. https://psalm.dev/r/34f2b80978

**Comment by CsabaNa** [comment]
@weirdan Yes but whole point of this algorithm is to do not init the variable. 
but also it is ok for the second "simpler" code but not in the class...

**Comment by muglug** [comment]
This is basically what you're doing: https://psalm.dev/r/8218b27425

There is a bug here on Psalm's side, since assigning `$b` to `null` inside the conditional results in a different issue: https://psalm.dev/r/87757510b6

You can work around this for the moment by assigning the variable to `null`: https://psalm.dev/r/a1ec0e9070
