### ISSUE TITLE
Make it easier to use igbinary?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#484]
Igbinary makes psalm much faster the second time psalm is run. (a bit slower the first time)

1. Add "suggest" "ext-igbinary" to https://getcomposer.org/doc/04-schema.md#suggest
2. Optional: Use different file names (or folders) when igbinary was used to serialize php-parser output
    (E.g. sha1('igbinary:' . regular_hash($contents))

    This avoids the need to delete the old contents if a mix of psalm installations or PHP binaries is used
3. Instead of explicitly enabling igbinary in config.xml, enable it by default (As long as igbinary functions exist), and add an option to disable it if needed.
4. Possibly require 2.0.5+

**Comment by muglug** [comment]
Thanks - fixed

**Comment by TysonAndre** [comment]
Can you link me to an example large project?

https://github.com/igbinary/igbinary#how-to-use For large projects, is it still slower when igbinary.compact_strings is off? (Maybe it's a cache locality issue - If strings are deduplicated, they're in various places in RAM instead of close together for a PHPParser\Node)
