### ISSUE TITLE
Invalid variable type on explicitly instantiated object

### ISSUE THREAD

**Issue by matgrula** [vimeo/psalm#4840]
Consider the following code:
`class Foo {
    /**
    * @param object|array $objectOrArray The object or array to modify
    */
    public function setValue(&$objectOrArray): void
    {
        ...
    }
}

class Bar {
    public function doStuffWithA(?A $a) 
    {
        ...
    }
}

$a = new A();
$foo = new Foo();
$bar = new Bar();

$foo->setValue($a);
$bar->doStuffWithA($a);
`

Psalm will report error on the last line:
**Argument 1 of Bar::doStuffWithA expects A|null, array<array-key, mixed>|object provided**

Not sure if the issue is, that setValue is passing the argument by reference, in my real case Foo is \Symfony\Component\PropertyAccess\PropertyAccessor

However, the variable $a has an explicit class type, so this error should not be thrown.

**Comment by matgrula** [comment]
Yes: https://psalm.dev/r/8fe92320ec
It is because of the reference, it works ok when it's removed

**Comment by weirdan** [comment]
With references, there's no guarantee the method won't replace the object with something else (array or some other object). If you know for sure the type is not modified, you can get around this by using templates: https://psalm.dev/r/42af105dfb
