### ISSUE TITLE
Array and InvalidArrayOffset

### ISSUE THREAD

**Issue by mj4444ru** [vimeo/psalm#4847]
https://psalm.dev/r/e58247c551

**Comment by weirdan** [comment]
Can you elaborate on what you believe to be problematic here?

**Comment by mj4444ru** [comment]
> Can you elaborate on what you believe to be problematic here?

1. Code `$arr = [$index => 5];` is analogous to `$arr = []; $arr[$index] = 5;`. And that means it should be similar to `$arr[$index] = 6;`. In the examples, we see the opposite.

2. Keys bool and float are valid in strict mode. It follows from this that the scalar type is valid for an array key. In all 3 examples, the relation to keys is not string or integer in two ways.

**Comment by orklah** [comment]
Every case should be reported as incorrect here. I must have missed the `$arr[$index] = 6;` syntax when adding this issue. I'll check if I can add this

**Comment by weirdan** [comment]
> Code $arr = [$index => 5]; is analogous to $arr = []; $arr[$index] = 5;. And that means it should be similar to $arr[$index] = 6;. In the examples, we see the opposite.

Agree, both should be flagged. I'd say this inconsistency should be taken care of in #4846

> Keys bool and float are valid in strict mode. It follows from this that the scalar type is valid for an array key.

Float keys do cause real problems https://3v4l.org/cgP4d. Consequently this rules out scalar as well. Rejecting bool keys is less clear cut, but it makes sense from type purity perspective. So unless you can come up with a useful and widely used pattern that requires bool keys it's going to stay. 'PHP allows that' argument doesn't carry much weight, as Psalm can and should be more strict than PHP - it was specifically designed to be that way and it's the reason to use it.

So:
 * Array construction / offset access inconsistencies with invalid / mixed keys is to be dealt with in #4846 
 * Float keys are no-go
 * Bool keys could be argued for in a separate issue

**Comment by mj4444ru** [comment]
Issue https://github.com/vimeo/psalm/issues/4846 has been resolved. But the errors described here are still present.
Closing this issue was a mistake.
