### ISSUE TITLE
Exclude files with patterns not working

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#4853]
It seems that directory wildcards aren't working (or only on 1 level)

e.g.
`<directory name="*stubs*">`

`Could not resolve config path to /myhome//*stubs*`

but my stubs are located in a variety of places.
Is there a way to make ignoreFiles match ANY stubs file(s)?

**Comment by kkmuffme** [comment]
No, since the issue is with the config, which cannot be changed on psalm.dev

**Comment by muglug** [comment]
The wildcard just matches file/folder names, so `src/*/stubs` will match `src/foo/stubs` and `src/bar/stubs` but not `src/foo/bar/stubs`.
