### ISSUE TITLE
Possibly incorrect handling of session_name()

### ISSUE THREAD

**Issue by christeredvartsen** [vimeo/psalm#4854]
According to the PHP manual, this is the signature of [session_name](https://php.net/session_name):

    session_name ([ string|null $name = null ] ) : string|false

Psalm does not seem to think that `session_name` returns anything other than a string:

https://psalm.dev/r/7fc1845367

**Comment by weirdan** [comment]
Should be fixable in `dictionaries/CallMap.php`

**Comment by christeredvartsen** [comment]
Guess this can be closed now, or do you want to wait until the fix has been released?

**Comment by weirdan** [comment]
Thanks for the fix!
