### ISSUE TITLE
Array and InvalidArrayOffset

### ISSUE THREAD

**Issue by mj4444ru** [vimeo/psalm#4858]
https://psalm.dev/r/e58247c551

Issue https://github.com/vimeo/psalm/issues/4846 has been resolved. But the errors described here are still present.
Closing this issue was a mistake.

_Originally posted by @mj4444ru in https://github.com/vimeo/psalm/issues/4847#issuecomment-747218311_

**Comment by muglug** [comment]
This is now improved with @orklah's recent changes
