### ISSUE TITLE
Filtering errors based on message regex per issue handler

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#4880]
Following this issue https://github.com/vimeo/psalm/issues/4823 is there a way to suppress issues based on regex of message? Similar is possible in phpstan via `ignoreErrors` config.

Sugested way to resolve the mentioned issue was to disable `RedundantPropertyInitializationCheck` and `RedundantCondition` checks but that would result in losing some valuable checks in the whole codebase.

I'd like to suppress `RedundantCondition` for eg. only `~Type .+? for \$this->\w+? is always isset~`

**Comment by orklah** [comment]
This would be handy, but it would mean that messages would be a BC contract. Fixing a typo in an error message could break thousands of builds. Not sure if it's something we want...

PS: do you know you can suppress issues with a phpdoc comment @suppress and that you can suppress an issue only for some directory/files only too?

**Comment by simPod** [comment]
Yes, I know but wanted to avoid modifying code in order to be able to upgrade from v4.2 and not to disable those checks either. But so far it seems there's no feasible way around this when using private methods to initialize properties.

**Comment by orklah** [comment]
> I wonder if fixing a typo – bug is a BC break as well?

With your example: `~Type .+? for \$this->\w+? is always isset~` changing a single letter in the word "always" would make it not match your regex anymore. This means the error is not suppressed anymore, which in turn will make your CI fail. Business have strict policy where they can't release with a fail on CI. 

I'm not saying this is not a cool feature, but cases like this will happen, unless we commit to never change an error message in a minor version anymore.

**Comment by simPod** [comment]
Yes, same here. Need CI to pass. But psalm version is locked so when upgrading version this would have to be fixed ofc.

Recently I upgraded phpstan version where message changed (because of improved type resolving). CI failed so I fixed patterns and the job was done, not much of an issue. But I see your point, yes.

I'm just trying to come up with a solution to avoid those false positives that are not going to be fixed.

> There's no feasible way to square the circle

without bending the code around it and keeping issue handlers enabled.

**Comment by VincentLanglet** [comment]
I don't think it requires message to be a BC contract.
Psalm could explicitly explains that the regex feature won't be under the BC contract.
It could still satisfy user like simPod or me ^^.

My use case is the following,
```
    public function testConstructorWithException(): void
    {
        $this->expectException(\InvalidArgumentException::class);

        new TypeGuesserChain([new \stdClass()]);
    }
```
Here, I get an error from psalm because I don't pass the right argument. But this is made on purpose.
Since we're doing this a lot, I'd like to disable the `InvalidArgument` for these case. But not for others.

It would be also great to be able to combine this with a path.

This way I could disable this error for all the occurence 
- `Argument .* of Sonata\\AdminBundle\\ .* expects .* provided` 
- In the test directory

**Comment by orklah** [comment]
> Psalm could explicitly explains that the regex feature won't be under the BC contract.

Easy to say at first :) I already read a lot of complaints or jokes about Psalm breaking builds at each bugfix version, this will make it worse.

As I said I'm not really opposed to the idea, but we have to be aware of drawbacks. I guess Muglug will make the final choice!

**Comment by weirdan** [comment]
> lot of complaints or jokes about Psalm breaking builds at each bugfix version

Since breaking builds is the main feature of Psalm, we should only start worrying if people *stop* complaining about that :smile:

**Comment by orklah** [comment]
I'm closing this as "won't do" right now, though feel free to try to implement it
