### ISSUE TITLE
Ensuring not null in while loop condition still results in PossiblyNullReference.

### ISSUE THREAD

**Issue by ZealJared** [vimeo/psalm#4882]
I may be wrong, but I believe the error thrown on the following code snippet is incorrect:
https://psalm.dev/r/95dc0c1455

If I add a redundant null check inside the loop, no error is thrown:
https://psalm.dev/r/80368ec4d8

Correct me if I'm wrong, but this seems like a bug.

**Comment by weirdan** [comment]
Psalm generally does not assume methods to return the same value every time, so the latter snippet should also be flagged. Use a variable: https://psalm.dev/r/72d9bd11f8

**Comment by weirdan** [comment]
Ah, your second snippet has call memoization enabled, so that `if()` is truly useless, and Psalm would not complain even if you removed it: https://psalm.dev/r/db60afe7d5

**Comment by ZealJared** [comment]
@weirdan , thanks. That makes sense. On the other hand, the if statement does prevent the error, even with call memoization disabled. The error returns if I disable property memoization. Why would that be?

**Comment by weirdan** [comment]
I think that may be a bug. When you disable both property and call memoization the error is reported as expected (https://psalm.dev/r/27385f89f2), but when *property* memoization is enabled the *call* appears to be memoized (https://psalm.dev/r/e0e7a8ee03)

**Comment by weirdan** [comment]
> I think that may be a bug.

Reported separately (#4886).
