### ISSUE TITLE
Add `@psalm-template` alternate annotation?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#489]
This may eventually conflict with other `@template` syntaxes.
(Or something may complain because it can't find a use of `@template T`)

Low priority since suppressions and `@psalm-return`/`@psalm-param` can be used to work around this.

**Comment by muglug** [comment]
Yes, but I'd also love to collaborate with you to have an annotation that works the same way it does in Phan (which I've wanted since https://github.com/etsy/phan/issues/522)

**Comment by muglug** [comment]
And something that @ondrejmirtes / @JanTvrdik could support (see [here](https://github.com/phpstan/phpstan/issues/652#issuecomment-348478616) for Jan's idea)
