### ISSUE TITLE
Incorrect definition of the array type

### ISSUE THREAD

**Issue by mj4444ru** [vimeo/psalm#4894]
https://psalm.dev/r/0bf218383c

1)
```php
$arr1 = [$index => 5];
```
2)
```php
$arr2 = [];
$arr2[$index] = 5;
```
The above two examples do the same thing, but in the second example, the array type is not defined correctly.

**Comment by weirdan** [comment]
Less noisy reproducer: https://psalm.dev/r/c22316392a
