### ISSUE TITLE
Get rid of the unused variable notification

### ISSUE THREAD

**Issue by tabuna** [vimeo/psalm#4895]
When checking my project, an unpleasant thing was discovered. To run a certain script over an array, a closure function is required, where the first argument is a value, and the second is a key. But when we don't need to use the value, we get an unused variable error:

```
 - Param $value is never referenced in this method (see https://psalm.dev/188)

```

Here's a small [example to reproduce](https://psalm.dev/r/7f6eab13de):
```php
$arr = ['a' => 1, 'b' => 2, 'c' => 3, 'd' => 4];

$new = array_filter($arr, function(int $value, string $key) {
    return $key == 'c';
}, ARRAY_FILTER_USE_BOTH);


print_r($new);
```

Is this correct behavior? How can you suppress this without listing each file or disabling the scan globally?

**Comment by weirdan** [comment]
The issue link (https://psalm.dev/188) offers a solution to that (prefixing the parameter with underscore): https://psalm.dev/r/d5bb676021

You can also suppress the issue with a docblock: https://psalm.dev/r/8ed98da818
