### ISSUE TITLE
Should new stubs be created as CallMap or stubs?

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#4897]
I'd like to PR support for the [GEOS](https://github.com/libgeos/php-geos) extension.

Should I add entries to `CallMap.php`, or full stubs in `stubs/`? What's the difference?

**Comment by orklah** [comment]
Hi!

CallMap is pretty simple, it covers standard param and return syntax so it's usually the first thing that's completed. Stubs are used when a more specific phpdoc syntax is needed. In particular, they allow taint annotations, template annotations, conditional returns and syntaxes like MyClass::* for constant references. There is also a third source of data called Providers. They're needed when phpdoc and standard types in signature are not enough to describe what the function/method does. You can directly code in php what type a function should return depending on it's params for example.

So, the first step would be to add the extension to CallMap, and then, if needed, add stubs, and if that's not precise enough, add Providers

**Comment by BenMorel** [comment]
Thank you for this thorough answer, @orklah! Much appreciated.

One last question: where should I stub constants provided by the extension?

**Comment by orklah** [comment]
Good question. I don't remember seeing that elsewhere than in stubs

**Comment by BenMorel** [comment]
I couldn’t find where constants are stored either. GEOS provides a few constants, so what should I do? Put functions/methods in CallMap, and constants in stubs, or everything in stubs?

Note that I [already have stubs](https://github.com/brick/geo/tree/master/stubs), so that would be easier for me anyway.

**Comment by weirdan** [comment]
Do you even need to stub them? If extension is available during analysis Psalm will use reflection to get constant types without you needing to do anything.

**Comment by BenMorel** [comment]
I usually don't have the extension installed locally when I run Psalm. Typically I run my tests locally against MySQL, and GEOS is only tested on CI!

**Comment by BenMorel** [comment]
Stubs PR'ed as https://github.com/vimeo/psalm/pull/4902.
