### ISSUE TITLE
Regression: wrong return type inferred when one template method calls another

### ISSUE THREAD

**Issue by ChristophWurst** [vimeo/psalm#4901]
Hello there :v:

We possibly identified a regression in 4.3.x (tested with .0 and .1). This code https://psalm.dev/r/e6c15e6d03 used to work but doesn't anymore. Also the suggested "fix" spits out the same code with different formatting.

As far as I understand the type declarations are sound. But the analysis fails.

Ref https://github.com/nextcloud/server/pull/24521 <- the original Dependabot PR where we identified this

If you need any more info please let me know

Cheers

**Comment by weirdan** [comment]
Simplified a bit: https://psalm.dev/r/18f9282800
