### ISSUE TITLE
Add issue for contradicting docblock vars

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#491]
Currently the `Reconciler` class is more lenient with docblock-defined types. This allows input-checking behaviour like

```php
/** @param string $s */
function foo($s) {
  if (!is_string) {
    throw new Exception('bad input');
  }
}
```

But it can also mean that Psalm ignores logic issues with the types a programmer says a thing should be and what their code tries to do with it e.g.

```php
/** @param array[] $arr */
function foo($arr) {
   if ($arr === "hello") {}
}
```

which is plainly wrong, but Psalm overlooks.

Maybe `DocblockTypeContradiction` is a good name

**Comment by nickyr** [comment]
I think that's a good name!

**Comment by weirdan** [comment]
THIS. IS. BRILLIANT!

It has caught a lot of issues in our codebase that was previously overlooked. One particular pattern that it really shines at is when the caller calls a function that uses exceptions to signal errors, but assumes it would use null/false when it fails:
```php
$object = fetchObject($id); // throws exceptions, does not return falsy values
if (!$object) {
    $this->logger->logNotFound($id);
    throw new NotFoundException('object ' . $id . ' is not found');
}
```

**Comment by muglug** [comment]
@weirdan I'm glad!

I added it because Psalm missed a lot of bugs in an exploratory [Php Parser 4-compatible](https://github.com/vimeo/psalm/compare/phpparser-4) branch (lots of property types changed between versions), and tracking down those bugs was really tiresome.
