### ISSUE TITLE
Giving a closure with too few params should not be a problem

### ISSUE THREAD

**Issue by BackEndTea** [vimeo/psalm#4917]
For example i can use array_reduce, but only care about the `$carry` param, and not the current item like in the snipptet. This shouldn't be an issue

https://psalm.dev/r/b97840b938

**Comment by muglug** [comment]
I think that's just specific to `array_reduce`

**Comment by BackEndTea** [comment]
I could also pass a closure that doesnt take args into array_map. 

Typescript also allows this.

**Comment by muglug** [comment]
I've fixed it so that now only one arg is needed, because `array_reduce` closures without any args aren't useful.
