### ISSUE TITLE
getting error RedundantConditionGivenDocblockType is a false positive?

### ISSUE THREAD

**Issue by igor-mobapps** [vimeo/psalm#4919]
## Problem

It is the first time that I am using psalm, and I am having trouble running, it is returning me a `RedundantConditionGivenDocblockType`, but there are no risks in this method.

## Use case

I have a method that searches for data in the database by filtering by ID, but Doctrine2 `find` method can return an object or null, if it doesn't find any element with that id.

With that, I'm checking if the result is equal to null and throwing an exception, otherwise, I just return the object.

### Error
![error psalm](https://user-images.githubusercontent.com/58818072/103389326-f5b5c600-4aec-11eb-82b2-9208492951b0.png)

### My code
![error psalm 01](https://user-images.githubusercontent.com/58818072/103389331-fc443d80-4aec-11eb-9302-384ee76a418b.png)

## Code Snippet

I tried to simulate what I'm doing in my real code.

https://psalm.dev/r/574b9c7bb3

## Settings

php -v
7.4.3

Psalm
"vimeo/psalm": "^4.3"

**Comment by orklah** [comment]
Can you tell us : 
- which version of doctrine/orm you're using, and also go to the definition of find() and copy here the entire docblock for the method
- Wether or not you're using the psalm plugin for doctrine: weirdan/doctrine-psalm-plugin

**Comment by igor-mobapps** [comment]
Activate the plugin, solved the problem, thanks !!

**Comment by orklah** [comment]
Can you just tell what version of doctrine/orm you're using please?

The psalm annotations have been added in recent versions so the plugin should not be needed for this particulat function

**Comment by igor-mobapps** [comment]
Doctrine Version:
"doctrine/orm": "^2.8"

DocBlock method Find():

````
/**
     * Finds an Entity by its identifier.
     *
     * @param string       $className   The class name of the entity to find.
     * @param mixed        $id          The identity of the entity to find.
     * @param integer|null $lockMode    One of the \Doctrine\DBAL\LockMode::* constants
     *                                  or NULL if no specific lock mode should be used
     *                                  during the search.
     * @param integer|null $lockVersion The version of the entity to find when using
     *                                  optimistic locking.
     *
     * @return object|null The entity instance or NULL if the entity can not be found.
     *
     * @throws OptimisticLockException
     * @throws ORMInvalidArgumentException
     * @throws TransactionRequiredException
     * @throws ORMException
     *
     * @template T
     * @psalm-param class-string<T> $entityName
     * @psalm-return ?T
     */
````

**Comment by orklah** [comment]
Thanks! That's weird though, the psalm annotation seems correct...
