### ISSUE TITLE
Release 4.3.2 lacks the phar assets

### ISSUE THREAD

**Issue by jk** [vimeo/psalm#4920]
We automatically use psalm in our CI environment and there download the phar assets of a new release. The latest release 4.3.2 lacks the phar asset and only contains the standard sourceballs. 

Can it be added and for the future do you consider automatically build and add it the phar to the release?

**Comment by jk** [comment]
> Hey @jk, can you reproduce the issue on https://psalm.dev ?

That does not apply here.

**Comment by weirdan** [comment]
It is automatically built, but the build failed: https://travis-ci.org/github/vimeo/psalm/builds/752007382

**Comment by muglug** [comment]
Closing as subsequent releases do
