### ISSUE TITLE
False positive InvalidArgument related to @template after upgrade

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#4932]
I'm updating from psalm 3.x to latest version and getting following error, I don't see what's wrong https://psalm.dev/r/1c41f0e72b

**Comment by weirdan** [comment]
`ActivityController::$activityManager` is underspecified (lacks type parameters). `Activity` needs `@psalm-consistent-constructor` for `new $class()` instantiation.

When both issues are fixed, no flags are raised: https://psalm.dev/r/da241fd759

**Comment by ostrolucky** [comment]
@weirdan and what about this? https://psalm.dev/r/0b3ee416f7 It reports same issue, but `ActivityController::$activityManager` is not underspecified now

**Comment by weirdan** [comment]
Now it's a bug, ticketed as #4949
