### ISSUE TITLE
psalm.phar --init fails due to not enough memory

### ISSUE THREAD

**Issue by pablosebastianr** [vimeo/psalm#4937]
I have my php environment running on WSL 2, it's an ubuntu 20

When I run free -b I see

```
              total        used        free      shared  buff/cache   available
Mem:    13327413248  1722212352 11175759872   220467200   429441024 11128008704
Swap:    4294967296  1093926912  3201040384
```

I installed the phar version of psalm on a Laravel 5.8 project. It's running on php 7.3

Issuing ./vendor/bin/psalm.phar --init . blows up with this:
```
Calculating best config level based on project files
Scanning files...
PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 20480 bytes) in phar:///.../vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Fork/Pool.php on line 275
Fatal error: Allowed memory size of 8589934592 bytes exhausted (tried to allocate 20480 bytes) in phar:///.../vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Fork/Pool.php on line 275
```

In /etc/php/7.3/cli/php.ini I have memory_limit = -1 though I don't know if that matters when running the .phar version of Psalm.

**Comment by pablosebastianr** [comment]
> Hey @pablosebastianr, can you reproduce the issue on https://psalm.dev ?

I don't know how to run the --init command con psalm.dev ? Can anyone even do that ?

**Comment by orklah** [comment]
> I don't know how to run the --init command on psalm.dev ? Can anyone even do that ?

No, You can't 😄 

Can you try to run with --debug-by-line to see if it fails on a specific file? It will give you the filename and line it visited last, please check if the code does anything weird or unusual

**Comment by weirdan** [comment]
`Fork/Pool:275` is likely where child process output is read. Chances are Psalm is getting some garbage there (e.g. notices). Try running with `--threads=1` which would disable forking and will possibly spit out the problematic output into your console.

**Comment by orklah** [comment]
Interesting, it seems there's no way to push --thread option with --init:
`--init --threads=1` results in `The given path "C:\Users\Ronan\PhpstormProjects\psalm\\--threads=1" does not appear to be a directory`
`--init . --threads=1` results in `Config strictness must be a number between 1 and 8 inclusive`

Please try to create a psalm.xml manually:
```php
<?xml version="1.0"?>
<psalm
    errorLevel="1"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
</psalm>
```

and then run
`./vendor/bin/psalm.phar --threads=1` as suggested by @weirdan

**Comment by pablosebastianr** [comment]
Yup, manually creating the psalm.xml file worked. Thanks!

**Comment by orklah** [comment]
Can you try to run it without --threads=1? That's weird it didn't reproduce the issue? Maybe it's because the psalm.xml I gave you already has `src` filled up and the error came from another directory?

**Comment by pablosebastianr** [comment]
I changed the src directory for "app" in the psalm.xml. My project doesn't have a src folder

The option threads=1 doesn't seem to matter, I run ./vendor/bin/psalm.phar without a problem (with or without threads=1), it shows a lot ERROR: MixedArgument , ERROR: MissingReturnType , etc, etc,

**Comment by orklah** [comment]
Ok, let's roll with it then!

**Comment by mal-tee** [comment]
`--threads` in combination with `--init` still seems to mess things up.
Steps to reproduce:
```bash
wget https://github.com/vimeo/psalm/releases/download/4.20.0/psalm.phar
chmod +x psalm.phar
./psalm.phar --threads=1 --init . # results in "Config strictness must be a number between 1 and 8 inclusive"
```
works fine without "--threads". The akward thing: The crash doesn't set a non-zero exit code, as it's using `die` directly:
https://github.com/vimeo/psalm/blob/36d5a2a83c1d7b3e2aca1cfe9e9dcc916619e962/src/Psalm/Internal/Cli/Psalm.php#L523

<details>
<summary>php version</summary>
php -v
PHP 8.1.2 (cli) (built: Jan 24 2022 10:42:51) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
</details>
