### ISSUE TITLE
Which is the status of autocomplete feature for LSP?

### ISSUE THREAD

**Issue by juanrgm** [vimeo/psalm#4942]
The documentation says:

> It currently supports diagnostics (i.e. finding errors and warnings), go-to-definition and hover.

And there is not mentions to autocomplete feature but it works partially, at least for me. So what is the status for autocomplete feature?

I did some tests and it does not work with `functions`/`use className`, and the `CoreGenericFunctions.phpstub` does not include the descriptions in the docblocks. I also found other cases like this (https://github.com/vimeo/psalm/issues/2318). 

It may be interesting to specify the LSP features supported (https://microsoft.github.io/language-server-protocol/specifications/specification-current/) to avoid confusions and appeal to the developers to collaborate with this project (including me).

Currenty there is not a full PHP support for VSCode and this project has all the potential for it.

**Comment by muglug** [comment]
There's partial support – and I've just updated the documentation.

LSP autocomplete support in Psalm is not a feature I'm going to spend much time on as it's a pretty complex area and Psalm has more pressing features & issues.

If you're looking for better autocomplete support I welcome PRs, but there are also tools like [Intelephense](https://intelephense.com/) that have more LSP features, and also a paid plan.

**Comment by juanrgm** [comment]
The problem with [Intelephense](https://intelephense.com) is that the source code of LSP server is private and there is not support for advanced features like `@template` (https://github.com/bmewburn/vscode-intelephense/issues/1144) or `array shapes`.

It is for that reason that I am searching alternatives but no luck.

**Comment by muglug** [comment]
The only thing holding back Psalm's LSP support is that nobody's working on it. I'd be very happy for someone to work on more completion features, but that sort of work is well outside what most PHP developers do day-to-day.
