### ISSUE TITLE
Psalm should subtract types from templated param where possible

### ISSUE THREAD

**Issue by maarekj** [vimeo/psalm#4943]
Hello, 
This snippet works in psalm 4.3.1 and fail in psalm 4.3.2

https://psalm.dev/r/dbbde8ec72

The $b value must be of type string. (and psalm 4.3.2 say that it be of type null|string)

```php
<?php

/**
* @template T
* @psalm-assert !null $var
* @param T|null $var
* @return T
*/
function notNull($var)
{
    if ($var === null) {
        throw new \InvalidArgumentException("");
    }

    return $var;
}

/** @psalm-trace $a */
$a = 1 == 0 ? "" : null;

/** @psalm-trace $b */
$b = notNull($a);

/** @psalm-trace $a */
$a;
```

Here the good output (with psalm 4.3.1)
```
INFO: Trace - 19:1 - $a: null|string()
INFO: Trace - 22:1 - $b: string()
INFO: Trace - 25:1 - $a: string()
```

Here the current bad output (with psalm 4.3.2)
```
INFO: Trace - 19:1 - $a: null|string()
INFO: Trace - 22:1 - $b: null|string()
INFO: Trace - 25:1 - $a: string()
```

**Comment by muglug** [comment]
It's not clear how Psalm should behave here.

While the assertion is processed as intended, if you just separate out the type it's not _obvious_ that `null` isn't part of `T`.

You could help Psalm by narrowing the type of `T` like so: https://psalm.dev/r/f1f4dc3216.

I agree, though, that some sort of subtraction is probably expected, [TypeScript is able to deal with this logic](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABGOUByIA2mA8AVAPgAoASANwEMAnALkTwB8wtMBKROvRAbwChEBiGMESlKVRAF5pyFuz6DFiKAAsqcAO6IARACMKAE20BufoIC+vMwKoBTKCCpJy1U5d6hIsBMooBrWwBnDGwKXUxbAGUoKhgwAHMiYDg4OkCYuPimOQ5EMjgYAx5rRGS4ADoIhNVTRQioRH0JSWRUEMwklNZawSbK22qVNyA)

**Comment by muglug** [comment]
This is a clearer example:

```php
<?php

/**
 * @template T
 * @param T|null $var
 * @return T
 */
function notNull($var) {
    if ($var === null) {
        throw new \InvalidArgumentException("");
    }

    return $var;
}

function takesNullableString(?string $s) : string {
    return notNull($s);
}
```

This should work for all types, not just `null`

**Comment by maarekj** [comment]
Okai, it is workaround acceptable for me.
On the other hand, in the previous versions it worked.

**Comment by maarekj** [comment]
Idea of a workaround:
Implement a `@psalm-assert-return !null` annotation

**Comment by muglug** [comment]
> On the other hand, in the previous versions it worked.

Yeah, I'm sorry for the apparent regression, but given there aren't any tests I don't believe this was ever intended functionality.

**Comment by maarekj** [comment]
Whatever happens thank you very much for your work
