### ISSUE TITLE
What is the use of phpVersion?

### ISSUE THREAD

**Issue by juanrgm** [vimeo/psalm#4944]
The documentation says:

> Set the php version Psalm should assume when checking and/or fixing the project.

I understant that if I set `phpVersion` to 7.3, all features of PHP 7.4 (https://www.php.net/manual/es/migration74.new-features.php) should throw warnings but this is not the case.

So what is the use of `phpVersion`?

**Comment by weirdan** [comment]
It's used to load correct callmap, stubs, and also by psalter to choose whether to output native types or docblocks (for older PHP versions).

Most of the features you refer to would be parse errors, so would have to be handled by `nikic/php-parser`. However the parser doesn't have an option to select specific version, it only allows choosing between PHP 5 and PHP 7 syntax.

**Comment by muglug** [comment]
> However the parser doesn't have an option to select specific version, it only allows choosing between PHP 5 and PHP 7 syntax.

It actually does, though it prevents some PHP 7.4 features (https://psalm.dev/r/92da00ab3c?php=7.3) and not others (typed properties). Ultimately Psalm is not the best tool for checking whether PHP code can be parsed by a given version of the PHP interpreter. `php -l` will always be better.

**Comment by weirdan** [comment]
> `php -l` will always be better.

There's also `php-parallel-lint/php-parallel-lint` which adds multithreading.

**Comment by weirdan** [comment]
> I found these snippets:

Bot should handle query params, ticketed here: weirdan/psalm-github-bot#315
