### ISSUE TITLE
Magic templated method return type is not inferred correctly

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#4949]
https://psalm.dev/r/0b3ee416f7 It reports same issue, but `ActivityController::$activityManager` is not underspecified now

_Originally posted by @ostrolucky in https://github.com/vimeo/psalm/issues/4932#issuecomment-756261712_

Simplified: https://psalm.dev/r/4fcfd600c7
Only happens for magic methods (declared via `@method`). Similar code using actual methods exhibits no such issue.

**Comment by muglug** [comment]
Renaming templates to be a bit clearer: https://psalm.dev/r/93383e0bb8

**Comment by muglug** [comment]
Seems fixed!
