### ISSUE TITLE
Psalm 4.x infers in some cases "object" instead of "T of object"

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#4953]
I specified `/** @template T of object */` so I don't know why Psalm infers just `object`

https://psalm.dev/r/a1ba6cf1e7

This was working in Psalm 3.x

**Comment by muglug** [comment]
here the `instanceof` check isn't enough to refine to `EntityEvent<T>` – just `EntityEvent<object>`, so it doesn't disqualify the other side of the union. You'll need something like this: https://psalm.dev/r/7431a6cf1f

**Comment by ostrolucky** [comment]
Alright but why isn't it enough? Why is psalm ignoring docblock in such case?

**Comment by weirdan** [comment]
Because `EntityEvent` itself also matches `Provider:T of object`:  https://psalm.dev/r/ccefbe44a7

**Comment by ostrolucky** [comment]
Then it shouldn't, looks like a bug to me. Docblock clearly says `EntityEvent<T>`.

**Comment by weirdan** [comment]
Docblock says `EntityEvent<T of object>|T of object`. When `instanceof` eliminates union members it checks what union members are matching its right parameter (`EntityEvent` in this case). Given `EntityEvent`, is it `EntityEvent<T>` - yes, it is => left side of union matches. Is it `object` - yes, it is => right side of union matches as well.
