### ISSUE TITLE
Bogus bar|(T:foo as bar) inferred, instead of just T:foo as bar, as specified when having class-string<T> parameter present

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#4955]
See https://psalm.dev/r/2fe73e8f63

issue for some reason disappears when `string $instance = File::class` is removed from method definition

**Comment by muglug** [comment]
Actually I'm not sure that's invalid. Mind fleshing out your example a bit?

**Comment by ostrolucky** [comment]
This is as fleshed you as I can think of https://psalm.dev/r/2fe73e8f63 Why is presence of $instance affecting behavior here?

**Comment by ostrolucky** [comment]
Wrong link https://psalm.dev/r/ce739a90de

**Comment by weirdan** [comment]
For `FileManager<FileDescendant>` where `class FileDescendant extends File {}` `update()` expects `FileDescendant`, yet `create()` may return `File`.

The issue Psalm reports looks totally valid to me.

**Comment by ostrolucky** [comment]
create() returns T, I don't know how psalm figured it doesn't. Behavior you are describing would be more something like https://psalm.dev/r/435ac72834

**Comment by weirdan** [comment]
Indeed. You're not giving it `class-string<T>` when you invoke it with no params though, so Psalm should complain (about the default parameter value, not the return type).

**Comment by ostrolucky** [comment]
https://psalm.dev/r/1d4982c2c1 this looks to satisfy psalm

**Comment by muglug** [comment]
This definitely is a bug: https://psalm.dev/r/05e276af09

Psalm should error on line 38
