### ISSUE TITLE
@inheritDoc inconsistency

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#4957]
It's not obvious whether it's now intentional, or accidentally broken as a fix for https://github.com/vimeo/psalm/issues/4803 in https://github.com/vimeo/psalm/commit/1e0bcc18764e3095268b7aa95a5dccc280131c7a but now the following example errors (it didn't in 4.3.1)

https://psalm.dev/r/75feb0a012

Line 23 was all clear in 4.3.1

**Comment by zerkms** [comment]
Okay, it looks like it's deliberately changed because of (https://github.com/vimeo/psalm/issues/4803#issuecomment-740745906)

> This follows the rule introduced in 4.2.0: a function signature (parameter and return types) can only come from one method. If you redefine either a parameter type or a return type in a child method, that method must also provide local param types.

right?

**Comment by weirdan** [comment]
I would think so, yes.
