### ISSUE TITLE
 T:Collection as mixed, TChild:fn-collection::get as T:Collection as mixed provided

### ISSUE THREAD

**Issue by jaapio** [vimeo/psalm#4958]
Given the example below: https://psalm.dev/r/a88e5c7436

I would expect in this case that `TChild of T` is a permitted value since `TChild` is in the same inheritance tree. Psalm doesn't seem to understand what is going on. 

I think the next case: https://psalm.dev/r/c07205de87 is in the same line. Also, no respecting the `D of T` template.

**Comment by weirdan** [comment]
Never seen generics used like that, but TypeScript seems to allow it: https://www.typescriptlang.org/play?#code/FAYwNghgzlAEDCB7MYCmIAuBLRA7APACoB8sA3sMLNbAA4BOWAbhBqrBACacAUA+hgBchAJSxBsJoiydyAXyo1F1WgFcARmCwhYAc1QYi8ABZYws1AA82uTnBI8AJJ1QAzCKrBDYhE2c4iyuRBNLAYplAAdFy8zm4eXiIA3CFKoaH0Bqr0uLBx7p4YKaEKCqCQMLAAkmwAtvLl0HAAyrToWK7aNaj1VjZ21XUNwK6quJg4ua5OIBJIKOjYePjdtcQiEq3tnSCrwTSZGNm5jiCR+hg8uKgA7rBbIB1ddcnAckA
