### ISSUE TITLE
False positive RedundantCondition on gzread string can never contain false

### ISSUE THREAD

**Issue by dFayet** [vimeo/psalm#4959]
Hello,

Since PHP 7.4.0  [gzread](https://www.php.net/manual/fr/function.gzread.php) function can return a `string` or `false` on failure.

But asserting `gzread` output is a string (or false) leads to an error, see https://psalm.dev/r/ec30401e77

**Comment by weirdan** [comment]
So, before 7.4 the return type was `0|string`, and in 7.4 it changed to `false|string`.
