### ISSUE TITLE
Empty array not considered a subtype of the intersection of an object-like array type and an array type

### ISSUE THREAD

**Issue by mstilkerich** [vimeo/psalm#4963]
Hello,

  I have an associative array whose entries can be from a set of different types, say `string` and `list<string>`. The type is fixed depending on the key. However, some of the keys are computed/dynamic, so I cannot fully define the type as an object-like array.

Example:
```php
$contact = [
    'firstname' => 'John', // <-- always string
    'surname' => 'Doe', // <-- always string
    'email:work' => [ 'john.doe@example.com' ], // <-- email:* keys always have values of list<string>, but the 'work' part of the key is dynamic and not known
];
```

Now my options appear to either type this as an object-like array with all the static keys, like `array{firstname?: string, surname?: string}`. But then for any extra key I guess psalm considers the type to be mixed (actually I just discovered this option by finding from another issue that object-like array definitions allow for extra keys). The other option is to define the array type in a generic way `array<string, string|list<string>>`.

Now what would be great is if I could specify an object-like array type with extra constraints for all the extra keys, like `array{firstname?: string, surname?: string}<string, string|list<string>>`.

So my questions would be:
- Is this may already possible, but not documented?
- If not, is there a suggested best practice to deal with this situation?

(Changing the type is not an option in my case, as it is part of an interface to another project my code interfaces with.)

**Comment by orklah** [comment]
Seems like this shape can exist internally in psalm but it doesn't seem like it can parse it directly in a docblock:
https://psalm.dev/r/d1ed6fd7d1

**Comment by orklah** [comment]
Interesting, this seem to work: https://psalm.dev/r/531651fada

**Comment by mstilkerich** [comment]
Reading through the release notes I just found for release 3.16:

> Allow intersection of object-like arrays and regular arrays
> Psalm now allows the docblock array{foo: string}&array<string, string>, understanding it to mean an array of strings with one explicit known key.

This seems to be just what I'm looking for, will try. Also I have to say that this is a non-intuitive behavior for the type intersection operator.

**Comment by mstilkerich** [comment]
I tried this now, and it seems to generally work, but there appears to be a bug with empty arrays. For the plain object-like array with all-optional keys, an empty array is considered a subtype. But when I add the intersection with the other array type, the empty array is not considered a subtype any more. Seems like a bug to me.

https://psalm.dev/r/342da918bb

(btw I take back my note on non-intuitive behavior - I was still thinking of object-like arrays as being exhaustive; considering they are non-exhaustive, the intersection makes sense)

**Comment by weirdan** [comment]
> For the plain object-like array with all-optional keys, an empty array is considered a subtype. But when I add the intersection with the other array type, the empty array is not considered a subtype any more. Seems like a bug to me.

Yep, looks like a bug to me as well.

**Comment by VincentLanglet** [comment]
I made https://github.com/vimeo/psalm/pull/5677 to try to fix it,
It works for me, but I think it can be improve ; could you help me @weirdan ?
