### ISSUE TITLE
False positive UnusedParam in private constructor with property promotion

### ISSUE THREAD

**Issue by gharlan** [vimeo/psalm#4964]
https://psalm.dev/r/fda66a2764

**Comment by weirdan** [comment]
Only private constructors are affected.

**Comment by localheinz** [comment]
@muglug @weirdan 

Any news on this one?

**Comment by weirdan** [comment]
I think I fixed it locally, waiting for tests to complete.

**Comment by orklah** [comment]
> I think I fixed it locally, waiting for tests to complete.

I made the fix too, let's see if you fixed it the same way!

**Comment by localheinz** [comment]
Thank you, @muglug!
