### ISSUE TITLE
2 times faster with php 8 and JIT

### ISSUE THREAD

**Issue by michabbb** [vimeo/psalm#4969]
i tested my code with 

PHP 7.4: 20 seconds
PHP 8 + JIT: 10 seconds

i just wanted to mention this here so that people might find that note.
even your project is write in PHP 7, you can use psalm scanning with PHP 8,
it really makes a difference.

cheers 🥂

**Comment by weirdan** [comment]
@michabbb did you run it with `--no-cache`? I don't see any significant speed up running Psalm on Psalm's own codebase (17.39s vs 18.01s).

**Comment by michabbb** [comment]
no, did not use that parameter, testing a folder with 15 files and about 40k lines of code. it may be very situational, but in my case, I am really surprised.

**Comment by weirdan** [comment]
The speed up you have seen might be due to the cache then. Mind sharing your jit config (`php -i | grep jit`)?

**Comment by michabbb** [comment]
@weirdan pardon, in my special example i was parsing 4248 lines of code. anyway, my params are the same phpstorm is using:

`--show-info --find-unused-psalm-suppress --show-info`

in my tests, i used the same psalm code and the same cache folder.

but, to be fair, i guess it makes a difference in php modules that are running within php docker containers:

`PHP 8`
```
[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
ftp
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```

`PHP 7.4`
```
[PHP Modules]
bcmath
bz2
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gd
gearman
gmp
hash
iconv
imagick
intl
json
libxml
mbstring
memcached
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
soap
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

my `jit.ini`:

```
opcache.enable=1
opcache.enable_cli=1
opcache.jit_buffer_size=1000M
opcache.jit=tracing
opcache.jit=1235
opcache.file_cache=/tmp/php-opcache
```

this is my first time testing JIT, so there might be something in this config that has no effect in some cases.
so php7 for instance uses "file_cache" but php8's JIT does not use it - if i am not wrong. 
for testing cli calls, you don´t have to use "enable=1", i was just testing some stuff.

my `Dockerfile` for ph8:

```
FROM php:8.0.1-cli-alpine3.12

COPY docker-php-ext-* docker-php-entrypoint /usr/local/bin/
RUN chmod u+x  /usr/local/bin/docker-php-ext-* /usr/local/bin/docker-php-entrypoint
ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/
RUN chmod uga+x /usr/local/bin/install-php-extensions && sync 

RUN docker-php-ext-install opcache
```

**Comment by HenkPoley** [comment]
On Windows 10 20h2 and PHP 8.0.3 I notice a _slowdown_:
```
;Disabled JIT
;opcache.jit_buffer_size=256M
```

With JIT disabled Psalm takes 40-45 seconds.

- With 32M _enabled_ (uncommented) it takes 50s. 
- With 64M it takes 60s. 
- With 256M it takes 100s. 
- With 512MB it takes 128s. 
- With 1G it takes 200s.
