### ISSUE TITLE
Example config using all IssueHandlers

### ISSUE THREAD

**Issue by ndench** [vimeo/psalm#497]
I noticed after looking at https://github.com/vimeo/psalm/blob/master/assets/config_levels/5.xml and  https://github.com/vimeo/psalm/tree/master/src/Psalm/Issue that there are a lot of Issue's that are available but not specified in the `5.xml` file. Are these Issue types not stable or is there some other reason that there's no example config that includes them?

**Comment by muglug** [comment]
All issues are included by default in Psalm's analysis. The example config files list only the issues that are downgraded/suppressed - a blacklist rather than a whitelist.

**Comment by muglug** [comment]
So 5.xml is currently the most lenient, though I plan to add an even more lenient file with more ignored issues.

**Comment by ndench** [comment]
Ah that makes sense, must have missed that part of the docs. It's a good idea to blacklist rather than whitelist too 👍
