### ISSUE TITLE
False positive on Attributes with IS_REPEATABLE

### ISSUE THREAD

**Issue by jpresutti** [vimeo/psalm#4970]
#[Attribute(Attribute::TARGET_METHOD | Attribute::IS_REPEATABLE)]

This should be valid, instead the following error appears
ERROR: InvalidArgument - Feast/Attributes/Param.php:24:13 - Argument 1 of Attribute::__construct expects int(1)|int(10)|int(11)|int(12)|int(13)|int(14)|int(15)|int(16)|int(17)|int(18)|int(19)|int(2)|int(20)|int(21)|int(22)|int(23)|int(24)|int(25)|int(26)|int(27)|int(28)|int(29)|int(3)|int(30)|int(31)|int(32)|int(33)|int(34)|int(35)|int(36)|int(37)|int(38)|int(39)|int(4)|int(40)|int(41)|int(42)|int(43)|int(44)|int(45)|int(46)|int(47)|int(48)|int(49)|int(5)|int(50)|int(51)|int(52)|int(53)|int(54)|int(55)|int(56)|int(57)|int(58)|int(59)|int(6)|int(60)|int(61)|int(62)|int(63)|int(7)|int(8)|int(9), int(68) provided (see https://psalm.dev/004)
#[Attribute(Attribute::TARGET_METHOD | Attribute::IS_REPEATABLE)]

Note that #[Attribute(Attribute::TARGET_ALL| Attribute::IS_REPEATABLE)] appears to work correctly

**Comment by jpresutti** [comment]
Couldn't duplicate on psalm.dev

**Comment by weirdan** [comment]
Likely duplicate of #4892
