### ISSUE TITLE
How to perform tests on new Plugin?

### ISSUE THREAD

**Issue by klebann** [vimeo/psalm#4978]
Hi,

I added a new plugin and I want to make automated tests. (errors counting  will be enough)

My repo: https://github.com/klebann/moodle-psalm-plugin

I inspire myself with https://github.com/orklah/psalm-strict-visibility

I created this psalm-baseline.xml file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<files psalm-version="3.9.4@352bd3f5c5789db04e4010856c2f4e01ed354f4e">
  <file src="tests/SqlTest.php">
    <PossibleSqlInjection occurrences="16">
        <code>get_records_sql</code>
    </PossibleSqlInjection>
  </file>
</files>
```

So I assume that is possible to check if Test.php throws 16 times an warning.

Im using `../../bin/psalm --no-diff --show-info=true` command to test plugin, but it works same as normal checking php files with psalm.

**Comment by weirdan** [comment]
strict-visibility plugin just runs Psalm and makes sure it does not fail (see https://github.com/orklah/psalm-strict-visibility/tree/master/.github/workflows)

If you need something more advanced, several other plugins use `weirdan/codeception-psalm-module` + Codeception to run tests written in Gherkin, similar to this: https://github.com/weirdan/codeception-psalm-module/blob/master/tests/acceptance/PsalmModule.feature

**Comment by orklah** [comment]
Yeah, the checks in my plugins are *very* flawed. @weirdan solution is the way to go.

Also if https://github.com/vimeo/psalm/pull/4923 were to be accepted, we could use Psalm's internal too for testing itself

**Comment by weirdan** [comment]
> Yeah, the checks in my plugins are very flawed

I call that 'simple and elegant, if a little unorthodox' (a hack, in an old-school sense of the word) :smile:
