### ISSUE TITLE
Type narrowing to list breaks if there is an array_filter condition after it

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#4979]
https://psalm.dev/r/863fd7a230

Expected: `list<mixed>|stdClass` (actually, `list<stdClass>|stdClass`, but ok, #4976 about it)
Got: `array<array-key, mixed>|stdClass`

**Comment by orklah** [comment]
You can get close like that:
https://psalm.dev/r/d018ae5b77

But your check for list is not complete in the current exemple (I'm not sure mine is either, because an array with -1, 0 and 1 will still satisfy my check).
Also, the OR with stdClass on the same if seem to be too much for psalm to handle correctly everything

**Comment by fluffycondor** [comment]
> the list check is fine but it doesn't seem to be recognized by psalm

It is perfectly recognized if I just drop the array_filter check:
https://psalm.dev/r/35589f2d39
So I got `list<mixed>|stdClass`. Add an array_filter check - whoops - it becomes `array<array-key, mixed>|stdClass`.

**Comment by orklah** [comment]
Oh, interesting. It also works if `$array === array_values($array)` is put after the array_filter check.

It must be the array_filter provider that's messing with the assertions.

**Comment by weirdan** [comment]
`array_filter()` analysis is expected to reset `list` to `array` - as it may skip some keys (https://3v4l.org/WvrUE). It's the equality that makes it into a poor man substitute of `all()` - but then it outside of the function call expression, so I don't think checks like that belong to return type provider. 

Just split that into separate functions with appropriate asserts: https://psalm.dev/r/4fbfa5dc7d

**Comment by fluffycondor** [comment]
> so I don't think checks like that belong to return type provider
Seems reasonable to me. But if any list and any array are compared to each other and the condition is true - shouldn't the list stay with its type, and the array becomes a list as it's equally to a list? Now we have quite the opposite: if a list equals to an array, the list's type becomes array.

**Comment by weirdan** [comment]
Perhaps not every array, but you're right.

**Comment by fluffycondor** [comment]
Seems like after @muglug's fixes in #4976, now it works as expected in this case:
https://psalm.dev/r/e6d36c4927
Expected `list<stdClass>`, and got it.

But the fix is really fragile:
https://psalm.dev/r/468c1279f5
Expected `list<stdClass>|stdClass`, got `array<int, stdClass>|stdClass`.

**Comment by muglug** [comment]
I'd consider this basically fixed, though

**Comment by muglug** [comment]
It's probably better to use an assertion function here – the `array_is_list` function that seems likely to arrive in PHP 8.1 has a polyfill: https://psalm.dev/r/858625e3ee

**Comment by fluffycondor** [comment]
> I'd consider this basically fixed, though

@muglug In this case narrowing to list is still broken
https://psalm.dev/r/468c1279f5
Expected list<stdClass>|stdClass, got array<int, stdClass>|stdClass.
