### ISSUE TITLE
Unsetting array's entry in loop prevents accessing the entry in following loop iterations

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#4988]
Psalm prevents accessing `$row['a']` before unsetting it.

> InvalidArrayOffset - Cannot access value on variable $row using offset value of a, expecting 'b'

```php
foreach ($data as $row) {
    echo $row['a'];
    // unset($row['a']); having this commented psalm has no issues with it
    
    $buffer[] = $row;
}
```

https://psalm.dev/r/20401ec2ce

**Comment by orklah** [comment]
This must have been fixed, the error is gone
