### ISSUE TITLE
When will be released a new version with bug fixes?

### ISSUE THREAD

**Issue by Aerendir** [vimeo/psalm#4989]
My problem is that I have CIs broke due to the issue with symfony mbstring polyfill.

It was fixed here: https://github.com/vimeo/psalm/commit/c1a710999c7007aeb1786f855e44de659a84ad18

But I'm waiting for the release to have CIs pass again...

Any idea?

**Comment by Aerendir** [comment]
No 😅

**Comment by danog** [comment]
Just load dev-master, I usually always add psalm:dev-master directly to the dev dependencies of my composer.json)

**Comment by Aerendir** [comment]
@danog , yes, this is an option, but then I have to change again the packages (they are a lot, over 15)... I want to use a stable version, not a dev one... I can use a dev version for testing purposes on one or two packages, but not as a stable solution in all of them...

**Comment by weirdan** [comment]
Myself I just marked offending polyfill versions as `conflicts` (https://github.com/weirdan/codeception-psalm-module/commit/8f54c62e15122cf8397b74e0d704bc6af2506ed1), until the fix is released.

**Comment by Aerendir** [comment]
@weirdan , yes, this is another solution... But as I said, I would like to avoid changing anything than the version of Psalm used to avoid duplicate work: first add the conflicting version, then remove it.

This solution has also the drawback that basically will block the upgrade of the polyfill and this will cause issues in future if the `conflicts` key is not removed from the `composer.json`..

The easistes way for me, is to understand when the next patch release will be released and wait for it...

**Comment by muglug** [comment]
I'll create a new release today!

**Comment by muglug** [comment]
Sorry, that was a lie, it'll be tomorrow (Wednesday).

**Comment by Aerendir** [comment]
@muglug , no problem :) If you can, obviously I will be really happy, but if if you can't... amen 😅

I wanted to simply understand, more or less, the estimated duedate 😀

**Comment by Aerendir** [comment]
Thank you @muglug ! 💪
