### ISSUE TITLE
Bug: value changes when accessing an array item

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#4994]
Look at this example:

https://psalm.dev/r/b9d347d464

When reading an array value, the property of `$v` property change, reading only the assigned value.

**Comment by orklah** [comment]
Simplified a little:
https://psalm.dev/r/5f988faf4d
It seems the coalesce operator somehow change the type in property. When we remove it, the type is unchanged

**Comment by thomasvargiu** [comment]
@orklah In your example, if you remove the wrong semicolons after the comments, the value is always the assigned value.

This probably is the most complete example:

https://psalm.dev/r/d6c7b744f1

**Comment by orklah** [comment]
If you remove the first semicolon, the trace will be executed after the statement. The semicolon make sure the trace is made before any execution.

The second semicolon has no effect, as expected

**Comment by muglug** [comment]
Two types of behaviour here depending on the array type: https://psalm.dev/r/2f63df2287

**Comment by muglug** [comment]
This is fixed!
