### ISSUE TITLE
FailedTypeResolution emitted for docblock-declared types

### ISSUE THREAD

**Issue by paragonie-scott** [vimeo/psalm#50]
```php
/**
 * @param string $foo
 */
function foo($foo)
{
    if (!is_string($foo)) {
        throw new TypeError("test");
    }
}
```

This is failing in https://github.com/paragonie/sodium_compat

**Comment by muglug** [comment]
**Short answer**
To get rid of this particular issue, add `<FailedTypeResolution errorLevel="suppress" />` to the `<issueHandlers>` block in your Psalm config.

**Longer answer**
Psalm is treating the above as *directly* equivalent to
```php
function foo(string $foo)
{
    if (!is_string($foo)) {
        throw new TypeError("test");
    }
}
```

In the above function, the exception cannot ever be thrown, and so Psalm emits an issue when trying to change a variable to an impossible type.

Unfortunately, Psalm doesn't record whether a variable's type is asserted in a docblock or in a more iron-clad fashion (e.g. a parameter type or `instanceof` check), and I want to add that in the near future. So I'll keep this open until that's fixed.

**Comment by muglug** [comment]
In Vimeo's PHP 5 codebase we have `<FailedTypeResolution errorLevel="info" />` so we can see where these issues can crop up, but they don't prevent Psalm running succesfully.

**Comment by paragonie-scott** [comment]
Other failures:

```
ERROR: TooManyArguments - src/Core/Util.php:121 - Too many arguments for method pack
            $hex .= pack(
                'CC',
                (55 + $b + ((($b - 10) >> 8) & ~6)),
                (55 + $c + ((($c - 10) >> 8) & ~6))
            );
```

Well, `pack()` can actually accept an arbitrary number of parameters.

**Comment by muglug** [comment]
@paragonie-scott fixed that error here: https://github.com/vimeo/psalm/commit/e59dba3c70118c7819f748ce150a201b9a280577
