### ISSUE TITLE
Psalm 4.4 fatal: not a git repository

### ISSUE THREAD

**Issue by sidz** [vimeo/psalm#5008]
I've updated to the Psalm 4.4 and at the end of the analyzing files procedure I've got a message:

```
fatal: not a git repository (or any parent up to mount point /srv)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

It's something new as 4.3.2 doesn't have such issue. Not sure is that an issue in psalm itself or permissions a different for some files.

**Comment by sidz** [comment]
No, unfortunately I can't reproduce it

**Comment by orklah** [comment]
I also have the message. I think it's related to the diff functionnality

**Comment by muglug** [comment]
@orklah I think it's related to the DTO plugin change. It looks like the Shepherd after analysis hook is now being run for everyone?

**Comment by orklah** [comment]
Oh. I'll take a look

**Comment by muglug** [comment]
Psalm 4.4.1 is now released with a fix!

**Comment by orklah** [comment]
Thanks!
