### ISSUE TITLE
Psalm has surprising behavior analyzing a switch statement with a missing constant in case

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#501]
Expected: Either of the following options:

- Psalm should analyze the inner case options as if the constant was defined
- Psalm should stop analyzing after the switch.

Observed: Psalm thinks that $x will be undefined. This is somewhat unexpected, and people unfamiliar with psalm might try to solve that first.

```php
<?php
function main() : string {
    switch (rand(0, 50)) {
    case FORTY: // Observed a valid UndeclaredConstant warning
        $x = 'value';
        break;
    default:
        $x = 'other';
    }
    return $x;  // unexpected " UndefinedVariable - src/switch.php:11:12 - Cannot find referenced variable $x"
}
echo main();
```

**Comment by TysonAndre** [comment]
Also, if there are multiple undefined class constants, psalm only warns about the last one. Warning about all of them would save a bit of time, but is relatively unimportant

**Comment by muglug** [comment]
Thanks for this - should be better now
