### ISSUE TITLE
literal strings as non-empty-string

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#5017]
Should literal strings be a `non-empty-string`?

The problem I occurred is the following:

```php
/**
 * @return list<non-empty-string>
 */
function a(): array
{
    // Imaging I have an external declared type like this:
    /** @var array{foo?: list<non-empty-string>} $array */
    $array = [];

    return $array['foo'] ?? ['bar'];
}
```

https://psalm.dev/r/0cb0b9aa53

**Comment by weirdan** [comment]
> Should literal strings be a non-empty-string?

Not necessarily. `''` is an empty literal string.

It's reconciliation between literal and non-empty strings that should result in non-empty string here, but that doesn't currently happen: https://psalm.dev/r/6d680d86b6

**Comment by orklah** [comment]
Simplified with https://psalm.dev/r/01d729395b then?
