### ISSUE TITLE
Type Intersecting With Exception Not Recognized In @throws

### ISSUE THREAD

**Issue by XedinUnknown** [vimeo/psalm#5018]
Psalm [declares support for intersection types][1]. However, this does not seem to apply to `@throws` tags in docblocks, as demonstrated [here][2]. Meanwhile, vimeo/psalm#410 hints that this should work.

[1]: https://psalm.dev/docs/annotating_code/type_syntax/intersection_types/
[2]: https://psalm.dev/r/5c9e42034a

**Comment by weirdan** [comment]
Duplicate of #3621
