### ISSUE TITLE
Psalm incorrectly reports DocblockTypeContradiction when testing for expected exceptions

### ISSUE THREAD

**Issue by theodorejb** [vimeo/psalm#5020]
I have a bunch of PHPUnit tests following this pattern:

```php
try {
    someFunctionExpectedToThrowForThisValue("test value");
    $this->fail('Failed to throw exception for bad value');
} catch (Exception $e) {
    $this->assertSame("Whatever the expected exception message is", $e->getMessage());
}
```

When there is a second try/catch block testing for another expected exception for a different test value, Psalm incorrectly seems to assume that `$this->assertSame()` in the second try/catch is matching against the exception potentially thrown by `$this->fail()` in the first try/catch block. Example: https://psalm.dev/r/9b4c68b7d9.

**Comment by toaomatis** [comment]
I have the same issue on the following lines of code in my PhpUnit tests
```php
        $this->assertSame(30, $provider->getKnownDeliveryStatusCutOffTime());
        $provider->setKnownDeliveryStatusCutOffTime(14);
        $this->assertSame(14, $provider->getKnownDeliveryStatusCutOffTime());
```
On the second `assertSame` I get the message 
```
psalm: DocblockTypeContradiction: Docblock-defined type 30 for $provider->getknowndeliverystatuscutofftime() is never int(14)
```
The test obviously succeeds. 

When I change my test to 
```php
        $this->assertSame(1234, $provider->getKnownDeliveryStatusCutOffTime());
        $provider->setKnownDeliveryStatusCutOffTime(14);
        $this->assertSame(14, $provider->getKnownDeliveryStatusCutOffTime());
```
The error changes accordingly 
```
psalm: DocblockTypeContradiction: Docblock-defined type 1234 for $provider->getknowndeliverystatuscutofftime() is never int(14)
```

Version info:
```
PHP 7.4.27 (cli)
psalm: Both 4.18.1 and 4.20.0
phpunit: 9.5.13
```

**Comment by orklah** [comment]
@toaomatis can you create a new issue for that please?

**Comment by toaomatis** [comment]
@orklah done https://github.com/vimeo/psalm/issues/7669
