### ISSUE TITLE
RecursiveDirectoryIterator errors on FilesystemIterator constants

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#5021]
https://psalm.dev/r/3d66686169

expected: no error

**Comment by staabm** [comment]
Hmm should the constants re-defined here, just be inherited from the parent class?

https://github.com/vimeo/psalm/blob/0e17a3354fda992d7113b97d15c75ff4a92ad800/stubs/CoreGenericIterators.phpstub#L804-L810

**Comment by weirdan** [comment]
It's not about specific constants. You can drop any of the three and it works: https://psalm.dev/r/79233b7288

**Comment by weirdan** [comment]
Actual cause is Psalm's inability to infer literal value for bitwise OR when one of the sides is an expression, even if it qualifies as constexpr: https://psalm.dev/r/84621f04aa
