### ISSUE TITLE
Give an error for unnecessary defined/isset/empty conditions

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#5023]
Often people use unnecessary duplicate conditions (left overs from refactoring or just unknowingly), bloating ifs and making it less readable.

https://psalm.dev/r/8b9baacf0b

Psalm should give an error for these unnecessary uses (like it already does for unnecessary typecasts)

**Comment by muglug** [comment]
I don't think this is particularly useful – these sort of `defined` checks are generally frowned upon in modern PHP
