### ISSUE TITLE
False positive TypeDoesNotContainType for bool property

### ISSUE THREAD

**Issue by gharlan** [vimeo/psalm#5026]
https://psalm.dev/r/2cba361060

**Comment by orklah** [comment]
Hi,

Check the settings, you can disable memoization for properties, that will solve the issue:
https://psalm.dev/r/2cba361060

You can do it with a property in your xml file too.

**Comment by weirdan** [comment]
@psalm-github-bot please fetch this: psalm.dev/r/2cba361060

**Comment by gharlan** [comment]
> Check the settings, you can disable memoization for properties, that will solve the issue:
> https://psalm.dev/r/2cba361060
> 
> You can do it with a property in your xml file too.

Thanks, I didn't know this.
But after changing this setting, I get many other issues in my project. So this is not an option in my case.
I use `@psalm-suppress` instead, for this single problematic occurrence in my project.

So should we close here?

**Comment by muglug** [comment]
Yes, we should close!
