### ISSUE TITLE
Custom taint analisys - check argument

### ISSUE THREAD

**Issue by klebann** [vimeo/psalm#5027]
# Hi again!

## Problem:

**Now I want to make simple Taint analyser.**

On the bottom you can see a simplified code example. ( I can change the code definition for my specific usuage. )

I want to detect usage of optional_param().
Then I want to analyze if (3rd argument == 1) and then `$codebase->addTaintSource()`.

## Explenation: 
Because 3rd argument is equal to 1 it will turn off text parsing. And it should be tainted.

## Example:

So if
```
$a = optional_param( ... , ... , 1);
sql_run($a);
```
Then add TaintSource `$codebase->addTaintSource()`

Sound easy, but I don't know if AfterFunctionCallAnalysisInterface will work for this case?
Maybe I should use other Interface?

## Test Code:

```php
/**
 * @psalm-taint-source input
 * @psalm-taint-specialize
 */
function optional_param($parname, $default, $type) : bool {
    return true;
}

/**
 * @psalm-taint-sink sql $sql
 */
function sql_run($sql) {
    return true;
}

$a = optional_param('test',NULL,1);
sql_run($a);
$b = optional_param('test',NULL,2);
sql_run($b);
```

**Comment by klebann** [comment]
I'm stuck on this:

https://github.com/klebann/moodle-taint-analysis/blob/main/hooks/MoodleScanner.php

I don't know only what should I put into `$expr_type`
and how to trigger this test for $a = optional_param('test',NULL,1) :

```php
function optional_param($parname, $default, $type) : bool {
    return true;
}

/**
 * @psalm-taint-sink sql $sql
 */
function sql_run($sql) : bool {
    return true;
}
$a = optional_param('test',NULL,1);
sql_run($a);
$b = optional_param('test',NULL,2);
sql_run($b);
```

**Comment by ohader** [comment]
This issue sounds a bit like conditional sinks in #4669 

Besides that, you can resolve the expression type by e.g.

```
$expr_type = $statements_source->getNodeTypeProvider()->getType->($expr);
```

`$expr` is supposed to be the PHP parser node triggering a taint source in this case - most probably the functions return type in your case.
