### ISSUE TITLE
Static return type and if statements don't work together?

### ISSUE THREAD

**Issue by jenshaase** [vimeo/psalm#5029]
Hi,

I have a generic abstract class with a method `foo` that should return `static<T>`. It works as long there is be no if statement in the method. If I add a if statement to call the constructor with different parameters it will give me an error. 

```
INFO: MoreSpecificReturnType - 21:17 - The declared return type 'A<T:A as mixed>' for A::foo 
is more specific than the inferred return type 'A<T:A as mixed>'
```

Here is a snippet: 
https://psalm.dev/r/50b704a810

Is this a bug or did I miss something?

**Comment by orklah** [comment]
This really looks like a bug

**Comment by jenshaase** [comment]
Thanks!
