### ISSUE TITLE
PHP8 false positive MixedAssignment error for "createFromInterface" methods

### ISSUE THREAD

**Issue by shandyDev** [vimeo/psalm#5038]
Hello,
Latest 4.4.1 psalm version & PHP8 environment.
This code - https://psalm.dev/r/a3d4cdf5a0 show
> MixedAssignment: Cannot assign $this->date to a mixed type 

This is psalm bug? 

P.S. It seems it's not related to https://github.com/vimeo/psalm/issues/2809 & https://github.com/vimeo/psalm/pull/5036

**Comment by orklah** [comment]
> P.S. It seems it's not related to #2809 & #5036

Not directly, but #5036 contains the fix anyway.

If you want you can take the 2 lines in CallMap and CallMap_80_delta and propose a separate PR to fix this issue.

We have difficulties with #5036 so I'm not sure it will be ready before next release.

**Comment by shandyDev** [comment]
Then #5036 not fully.
First: method createFromInterface have in both classes - DateTimeImmutable & DateTime
Secondly: Return type detected wrong way (it is should not just DateTimeInterface and should be hard "self" reference)

**Comment by orklah** [comment]
Thanks! Care to push the PR?
