### ISSUE TITLE
Better types for the `explode()` function?

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#5039]
I was trying to get more precise types for `explode($delimiter, $input, $limit = PHP_MAX_INT)`, which is used quite a lot.

Specifically:

 * `explode()` returns `array<empty, empty>|non-empty-list<string>|false` on PHP 7.4
 * `explode()` is `array<empty, empty>|non-empty-list<string>|never-return` on PHP 8.x, with `@throws ValueError` (https://3v4l.org/rmaRS)

I tried applying some improvements to the stubs, but am a bit puzzled about what needs to be done ( https://psalm.dev/r/b52283d0f5 ).

In the case of `$limit` being negative (`!positive-int && !0`, not sure if there's a way to verify this), the return type is `array<empty, empty>`.
In the case of `$limit` being `positive-int|0`, the return type is restricted to `non-empty-list<string>|false` or `non-empty-list<string>|never-return`.

## The Question

The big question is:

 * do we treat a `ValueError` as a type error, as in require `explode()` to have a `non-empty-string` for `$delimiter`?
 * do we treat a `ValueError` as an assertion (`@psalm-assert`)?
 * do we ignore the `ValueError` and instead map the `never-return`?

Overall, I tried a bit of everything, and am tempted to say (my opinion!) that people should never expect a `ValueError` nor an `array<empty, empty>` here, and we should map the function as `explode(non-empty-string $delimiter, string $input, positive-int|0 $limit)`

Thoughts?

**Comment by orklah** [comment]
This can be delicate to document a parameter as `0|positive-int`. This is not a standard type on a standard function used a lot. This means, unless `$limit` is a literal, any code that use this parameter will have to document the type as `0|positive-int`...

However, if this parameter is not documented as such, we have a situation when there is a value for that param that will return a `never-return`. [And this is not possible with psalm.](https://github.com/vimeo/psalm/issues/4501)

Fortunately, I think the gigantic majority never use this param, and when it's used, it's often a literal. So I don't think there will be a big impact to document the param as `0|positive-int`, allowing to use conditional return correctly for those values.

Another possibility would be to keep $limit as int, but create a ReturnTypeProvider to handle the return type depending on $limit value without the need of conditional return

**Comment by Ocramius** [comment]
Careful, we have two problems at hand:

 1. `$delimiter` determines the `never-return|T` type decision (where `T of non-empty-list<string>|array<empty, empty>`)
 2. `$limit` determines the `non-empty-list<string>|array<empty, empty>` type decision
 
 * Documenting `$limit` should be less risky, since very few people use it, and generally in a hardcoded way.
 * Documenting `$delimiter` is more risky due to it being a required argument (everyone uses it), but in fact, in PHP 8, passing in an `''` as `$delimiter` is a runtime error (not a type error - https://www.php.net/manual/en/class.valueerror.php)
