### ISSUE TITLE
phpstorm permission denied error

### ISSUE THREAD

**Issue by Ahmard** [vimeo/psalm#5041]
![Screenshot from 2021-01-18 12-05-58-cropped](https://user-images.githubusercontent.com/44737217/104907797-eb694800-5985-11eb-9af6-21a5a242eb0e.png)

**Comment by Ahmard** [comment]
> Hey @Ahmard, can you reproduce the issue on https://psalm.dev ?

No, this is idea-related problem.

**Comment by weirdan** [comment]
This should be reported to Jetbrains, not here.

**Comment by Ahmard** [comment]
Okay
