### ISSUE TITLE
InvalidPropertyAssignmentValue error when trying to use indexed array with templated key

### ISSUE THREAD

**Issue by ramsey** [vimeo/psalm#5069]
When trying to set a value on an array using a templated key `as array-key`, I'm getting an `InvalidPropertyAssignmentValue`:

https://psalm.dev/r/462ba68291

When I use `array-key` directly (and not the template name), it works:

https://psalm.dev/r/de718bfed8

Is this a bug or my misunderstanding of how templates should be used with arrays?

**Comment by weirdan** [comment]
Misunderstanding. `@var array<array-key,...>` means any type valid for array keys is accepted, while `@var array<TKey,...>` means the type specified for TKey when instantiating the Foo (with, e.g. `@var Foo<string,...>`) is expected. `$this->data[] = ...` is invalid for `Foo<string,...>`, so Psalm has to flag that.

**Comment by ramsey** [comment]
Thanks!

**Comment by ramsey** [comment]
If I define my template at `@template TKey as array-key`, why doesn't that still mean "any type valid for array keys is accepted?"

**Comment by weirdan** [comment]
`array-key` in `TKey as array-key` is not a type, it's a *type constraint*. Meaning `TKey` can be `int`, `string` or `array-key`, but not all of them at the same time. For the code that *uses* your generic class Psalm will figure out to what of those specific types `TKey` corresponds based on either explicit docblock or constructor parameters. But for the class code itself Psalm has to validate all possible types that `TKey` can be. 

Take for example your first snippet (with TValue removed for simplicity):
```php
<?php
/**
 * @template TKey as array-key
 */
class Foo
{
    /**
     * @var array<TKey, string>
     */
    private $data = [];

    public function add(string $value): void
    {
        $this->data[] = $value;
    }
}
```
It's basically three classes merged into one, and *each of them has to be valid on its own*:
```php
class IntFoo // TKey = int
{
    /**
     * @var array<int, string>
     */
    private $data = [];

    public function add(string $value): void
    {
        $this->data[] = $value; // generates int key => valid
    }
}

class ArrayKeyFoo // TKey = array-key
{
    /**
     * @var array<array-key, string>
     */
    private $data = [];

    public function add(string $value): void
    {
        $this->data[] = $value; // generates int key => valid as int is a subclass of array-key
    }
}

class StringFoo // TKey = string
{
    /**
     * @var array<string, string>
     */
    private $data = [];

    public function add(string $value): void
    {
        $this->data[] = $value; // generates int key => invalid, as key has to be string for TKey = string
    }
}
```

**Comment by ramsey** [comment]
Thank you for the detailed explanation!
