### ISSUE TITLE
Namespace prevents use of template in @psalm-type

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#5072]
Related to #5071, adding a namespace causes issues with using `TValue` within `@psalm-type`: https://psalm.dev/r/ce427c1d88

**Comment by danog** [comment]
Encountering the same issue here.

**Comment by albe** [comment]
Can confirm. It even doesn't work if a psalm-type is just used for restricting a template type. Currently keeping us from adding templates to our code base more extensively.

https://psalm.dev/r/e78f88c1a7

**Comment by weirdan** [comment]
@albe your example work if you put the typedef under namespace declaration: https://psalm.dev/r/81c824ed73

**Comment by weirdan** [comment]
@AndrolGenhald to me it looks like it kinda works by pure coincidence. What you have in there is effectively a generic typedef, but Psalm does not officially support it. It doesn't work outside of the class it was defined on (https://psalm.dev/r/077d96a6d2), and typedefs are supposed to be file-scoped. It most likely doesn't work when imported. I would not be surprised if it stops working in future versions, especially if proper generic typedefs will get implemented.

**Comment by AndrolGenhald** [comment]
Well #5071 was fixed, so my particular use case for this isn't needed anymore, and if it was never actually supported to begin with and just happened to almost work then I'll go ahead and close this. I'm not sure I even tested importing it in another file since the namespace issue prevented it from working in the first place.

**Comment by albe** [comment]
> @albe your example works if you put the typedef under namespace declaration: https://psalm.dev/r/81c824ed73

Interesting. It didn't work in our code base and failed with such an `expecting 'Acme\Foo\T'` namespaced template error - I will take another look, maybe something else was off (going a bit wild with trying things to get things to behave as I expect). Thanks for the heads-up!
