### ISSUE TITLE
Possibility to ignore UndefinedClass exception

### ISSUE THREAD

**Issue by ohader** [vimeo/psalm#5075]
Given that the file to be analyzed looks like the following

```
<?php
namespace MyVendor\MyApp;
class MyController extends \OtherVendor\OtherController
{
    public function execute()
    {
        eval($_GET['value']);
    }
}
```
→ https://psalm.dev/r/1f4b47409a

With `vimeo/psalm:^4.4` I get the following in CLI

```
ERROR: UndefinedClass - examples/test.php:3:28
- Class or interface OtherVendor\OtherController does not exist (see https://psalm.dev/019)
class MyController extends \OtherVendor\OtherController
```

The specific implementation of `\OtherVendor\OtherController` does not really matter in this case - that base class might stem from some other framework or library that is not given in the scenario to be analyzed.

Is there a way to ignore and continue analyzing `MyController` (as shown above)?

**Comment by weirdan** [comment]
https://psalm.dev/r/b9c50a18f2 - you should be able to suppress those issues in `psalm.xml` as well (see [Dealing with code issues](https://psalm.dev/docs/running_psalm/dealing_with_code_issues/)).

**Comment by ohader** [comment]
`/** @psalm-suppress UndefinedClass */` (and corresponding XML configuration) completely skips the class and does not report the obvious flaws.
At the end of the shared link, `AfterClassLikeVisitInterface` might offer the possibility to handle that individually. Another strategy might be to pre-parse all candidates, resolve missing classes and provide some empty class aliases, e.g.

```
class ArbitraryClass {}
class_alias(\ArbitraryClass::class, \MyVendor\MyController::class);
new \MyVendor\MyController(); // works now
```

Of course it would be much better to handle that on a analyzer/parser level at https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php#L301-L314 (even if exception is suppressed, execution stops at `return null` for that missing class).

**Comment by ohader** [comment]
Thanks again for previous feedback! I'm leaving the code here in case somebody has a similar issue or even a better idea.
(Disclaimer: I'm still not really sure whether I'm doing things correctly here - but "It works for me"™ 😉 )

The following event handler purges `invalid_dependencies` for (expected) missing parent classes in order to continue processing and again showing e.g. tainted results. This way Psalm can be used on 3rd party code that is not maintained by me.

```
class EventHandler implements AfterClassLikeVisitInterface, AfterClassLikeExistenceCheckInterface
{
    public static function afterClassLikeVisit(AfterClassLikeVisitEvent $event): void
    {
        // @todo currently not used
    }

    public static function afterClassLikeExistenceCheck(AfterClassLikeExistenceCheckEvent $event): void
    {
        $storage = $event->getCodebase()->classlike_storage_provider->get($event->getFqClassName());
        // skip if subject is not user-defined, does not have any invalid dependencies or parent classes
        if (!$storage->user_defined || empty($storage->invalid_dependencies) || empty($storage->parent_classes)) {
            return;
        }
        $invalidParentClasses = array_filter(
            $storage->parent_classes,
            function (string $parentClass) use ($storage): bool {
                return in_array(strtolower($parentClass), $storage->invalid_dependencies);
            }
        );
        $storage->parent_classes = array_diff(
            $storage->parent_classes,
            $invalidParentClasses
        );
        // @todo currently keeps invalid interfaces (check `$storage->parent_interfaces`)
        $storage->invalid_dependencies = array_diff(
            $storage->invalid_dependencies,
            array_map('strtolower', $invalidParentClasses)
        );
    }
}
```
