### ISSUE TITLE
Context aware completions in LSP Advice

### ISSUE THREAD

**Issue by joehoyle** [vimeo/psalm#5076]
I'd like to have a go add adding more / better completions in the LSP. Currently there's only support for class-like-things as seen in https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/LanguageServer/Server/TextDocument.php#L260

I'd like for it to support full-completions for many more cases, whereby essentially Psalm will complete all known possible values for the current context. Rather than starting with more possible completions (of say function names), it seems starting with an understanding of the curser position's context would be needed. In `$this->remove_dir( |` knowing the context of "method call" along with the class and method object to then only autocomplete items that match the parameter type.

As far as I can see, there is nothing in Psalm to parse out the context based off position. [`getCompletionDataAtPosition`](https://github.com/vimeo/psalm/blob/master/src/Psalm/Codebase.php#L1234) seems closest. I _think_ the context would be essentially mapped to "all possible types" for that given context, and then it's a case providing completions that can result in a compatible type for the context.

Given:

```php

function get_name( bool $return ) {}

get_name(|
```

I'd expect the context to give me `FunctionParameter`, along with `get_name`, so I can look up the type, and then provide all known completions that result in `bool`.

So, is this something that's worth pursuing? If so, does this approach seem sane?

**Comment by weirdan** [comment]
https://github.com/vimeo/psalm/blob/c912b6c2b953a4a1e99e19d67f7213e37781fd0d/tests/LanguageServer/SymbolLookupTest.php#L430 seems to be the closest thing, using https://github.com/vimeo/psalm/blob/c912b6c2b953a4a1e99e19d67f7213e37781fd0d/src/Psalm/Codebase.php#L1118 to show signature help.

**Comment by joehoyle** [comment]
Thanks for the pointer @weirdan !
