### ISSUE TITLE
Cannot docblock-suppress issues in traits

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5081]
https://psalm.dev/r/cb7327dd79

I have a trait with uninitialized property in constructor. I want to suppress the issue but psalm ignores docblock suppresion.

**Comment by 7ochem** [comment]
If you use `@psalm-suppress PropertyNotSetInConstructor` instead of `@psalm-suppress MissingConstructor` then there's no error anymore.

**Comment by 7ochem** [comment]
I think `MissingConstructor` is a class level issue. So if you were to put it on both `class A` and `class B`, then there's also no error anymore...

https://psalm.dev/r/1a12bd7dd4

**Comment by weirdan** [comment]
You can suppress it on the class level. Alternatively, as pointed out above, you can suppress `PropertyNotSetInConstructor` on the individual property level.
