### ISSUE TITLE
Bug: string(stdClass) can never contain class-string on compare get_class with string

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#5094]
```php
function isStdClass(object $o): bool {
    return get_class($o) !== "stdClass";
}

isStdClass(new \stdClass());
```

Result: `string(stdClass) can never contain class-string`. But should be pass.

Example: https://psalm.dev/r/6769afb49b

**Comment by orklah** [comment]
You can use this:
https://psalm.dev/r/34441d9229

Or activate `allowStringToStandInForClass=true` in your psalm config

**Comment by vjik** [comment]
> allowStringToStandInForClass

Thank you!
