### ISSUE TITLE
Exiting with status of 1 with only INFO errors?

### ISSUE THREAD

**Issue by paragonie-scott** [vimeo/psalm#51]
https://github.com/vimeo/psalm/blob/91328838e22f50efa72e46f69cea0a7742546189/src/Psalm/IssueBuffer.php#L191

https://travis-ci.org/paragonie/sodium_compat/builds/191811956

Any chance we can configure a threshold for "worst error level allowed for exiting with a status of nonzero?"

**Comment by muglug** [comment]
Ah, definitely a bug - a non-zero exit code should only happen if the console output includes errors.  In the meantime, does `--show-info=false` fix it?
