### ISSUE TITLE
Discover missing dependencies

### ISSUE THREAD

**Issue by mxr576** [vimeo/psalm#510]
It occurred that my library had a missing dependency in its composer.json. It has not been discovered until somebody did not install it without dev dependencies, because one of the dev dependencies of my library has installed that missing, but required dependency as its dependency. After this problem had been discovered I tried to update my Travis script to run Psalm on an installation of my library where dev dependencies are not being installed. I hoped Psalm will be able to find missing dependencies in my library because I think it should be discoverable by static code analysis if a used class does not exist.
Actually, it did not find the missing dependency.

```sh
/var/www/html$ vendor/bin/psalm --version
Psalm 0.3.93@a8ab9728898f529914c83d968f8b3d14af862e65
```

If I try to run an example script from my library I clearly got a PHP error

```
Fatal error: Uncaught Error: Class 'phpDocumentor\Reflection\DocBlockFactory' not found in /tmp/test/vendor/symfony/property-info/Extractor/PhpDocExtractor.php on line 56

Error: Class 'phpDocumentor\Reflection\DocBlockFactory' not found in /tmp/test/vendor/symfony/property-info/Extractor/PhpDocExtractor.php on line 56
```
 The code part that triggers this error is in a constructor:

 ```php

class Foo {
   public function __construct()
    {
        $reflectionExtractor = new ReflectionExtractor();
        $phpDocExtractor = new PhpDocExtractor();

        $this->propertyTypeExtractor = new PropertyInfoExtractor(
            [
                $reflectionExtractor,
                $phpDocExtractor,
            ],
            // Type extractors
            [
                $phpDocExtractor,
                $reflectionExtractor,
            ]
        );
    }
}

```

**Comment by muglug** [comment]
>  I hoped Psalm will be able to find missing dependencies in my library because I think it should be discoverable by static code analysis if a used class does not exist.

Yup, I agree. I've added a check when calling constructors.

**Comment by mxr576** [comment]
Thanks this was quick.

I have installed dev-master with Composer from Psalm but it was still unable to find the mentioned problem. Can you double check your implementation?

```sh
/var/www/html$ composer show vimeo/psalm
name     : vimeo/psalm
descrip. : A static analysis tool for finding errors in PHP applications
keywords : code, inspection, php
versions : * dev-master
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/vimeo/psalm.git be75c143d4a434ea4fc0930f8c1771e8d5830c71
dist     : [zip] https://api.github.com/repos/vimeo/psalm/zipball/be75c143d4a434ea4fc0930f8c1771e8d5830c71 be75c143d4a434ea4fc0930f8c1771e8d5830c71

```

**Comment by muglug** [comment]
I've just added https://github.com/vimeo/psalm/commit/279b0bc16e19d7bc9fcd5924536247516fd1a82e, which adds a check for missing dependencies every time we encounter a class. Does that work for you?

**Comment by mxr576** [comment]
Nope, it is still not working.

**Comment by muglug** [comment]
What dependencies do you have in `composer.json`? If I have those I should be able to recreate with the first example code you posted.

**Comment by mxr576** [comment]
```
git clone https://github.com/apigee/edge-php-sdk.git
cd edge-php-sdk
git reset --hard 7f4d9b09c7e # Before the missing dependency has been added.
composer install --no-dev
composer require vimeo/psalm:dev-master
composer update --no-dev
composer show phpdocumentor/reflection-docblock # Should return that this library is not installed.
composer analyze

```
or instead of the last command `vendor/bin/pslam --config=psalm.xml.dist --show-info=false --stats`

If I try to validate the problematic file directly it also does not yeld an error:

`vendor/bin/psalm --config=psalm.xml.dist src/Entity/EntityNormalizer.php`

**Comment by muglug** [comment]
Ah ok. Psalm doesn't look inside methods when they're defined outside of the project directory, for performance reasons. If you want to go crazy, you could use
```xml
    <projectFiles>
        <directory name="src" />
        <directory name="vendor" />
        <ignoreFiles>
            <directory name="vendor/*/*/tests" />
        </ignoreFiles>
    </projectFiles>
```
but obviously there'll be a ton of issues there that you don't care about.

**Comment by muglug** [comment]
And thanks for the example, by the way.
