### ISSUE TITLE
Not sure how to docblock the matches array from preg_match

### ISSUE THREAD

**Issue by MetalArend** [vimeo/psalm#5109]
I had this little snippet in my codebase: 

https://psalm.dev/r/c918282572
```
<?php

function go(string $text, string $regex): ?string
{
    preg_match($regex, $text, $matches, PREG_UNMATCHED_AS_NULL);

    return $matches[1] ?? null;
}
```

I would expect the function to always be returning either string or null.

- The `$matches` variable is documented as `string[]` in the PhpStorm's fills.
- The official PHP documentation talks about `$matches` being filled with text in normal circumstances, and the flag PREG_UNMATCHED_AS_NULL only makes it possible that some values become `NULL`.
- With the null coalescing operator, the `$matches[1]` not being such a string would result in null being returned from the function.

I found this MR https://github.com/vimeo/psalm/commit/3e549e275bc36f9a6b5b8dfc1c2a43c3825f418c, where the type for `$matches` changes from `string[]` to `array` if any flags are set. This is true for the flag `PREG_OFFSET_CAPTURE`, but not for the newer `PREG_UNMATCHED_AS_NULL` flag (since 7.2). Is it possible to change the types depending on the flag being given? 

_The reason I submit this is because it has conflicts with other tools like phpstan and phpcs when I try to "help" Psalm with documentation. For example: if I document the resulting $matches variable with `/** @var array{0: string, 1: ?string}|null $matches */` between `preg_match` and `return`, Psalm is happy, but phpcs gets annoyed. If I document above the `preg_match` function, phpstan tells me it already knows._

**Comment by weirdan** [comment]
I suppose `preg_match` needs a stub similar to those Psalm has for `preg_match_all`: https://github.com/vimeo/psalm/blob/06240988657c656b02f2b45f910b194206c2c32f/stubs/CoreGenericFunctions.phpstub#L848-L882

**Comment by orklah** [comment]
Seem fixed
