### ISSUE TITLE
Psalm 4.4.1 Taint Analysis freezes when Analyzing Files is at 100%

### ISSUE THREAD

**Issue by ArtemGoutsoul** [vimeo/psalm#5111]
This worked before (tested it when taint analysis first appeared, not sure which version). Decided to try it again, but the analysis seems to freeze here:

```
Copying psalm-4.4.1.phar to /usr/local/bin/psalm

+ exec psalm --set-baseline=psalm_taint_baseline.xml --report=_reports/psalm_taint_report.txt --report=_reports/psalm_checkstyle.xml --show-info=false --taint-analysis
Scanning files...
Analyzing files...

████████████████████████████████████████████████████████████  1796 / 1796 (100%)
```

The process seems to be running and using the processor (at least the docker VM is).

I left it for about an hour, to check if it would ever exit, but it didn't.

Would you have any debugging suggestions?

The project is very large (about 1800 files not including the lib/vendor folder), so unfortunately I cannot provide a test case :(

**Comment by orklah** [comment]
I got this too in a big project. I think there was too much routes to calculate. I launched it again on a smaller scope and I got better results. Turns out we have a direct route from our entry point to every page of the project. I think once this one is fixed, Psalm will have a lot less to do on the bigger scale

**Comment by weirdan** [comment]
I wonder if it would be possible to put some limits on the number of paths analyzed.

@ArtemGoutsoul, have you tried running with `--debug` switch? It will be even slower, but it prints some debug info along the way, so you'll at least have something to stare at :smile:, and it may provide some useful insight into what's going on.

**Comment by ArtemGoutsoul** [comment]
I with the debug I noticed that it freezes on one of the test files. I'll try to remove the tests from analysis.

**Comment by muglug** [comment]
@ArtemGoutsoul mind trying on latest master? I fixed a bug yesterday that matched this behaviour

**Comment by ArtemGoutsoul** [comment]
> @ArtemGoutsoul mind trying on latest master? I fixed a bug yesterday that matched this behaviour

My environment is setup only to work with phar version of psalm, how can I get one from master? I remember it was somehow possible. At least I noticed there's a circleci job that builds it :)

**Comment by weirdan** [comment]
https://21607-74386167-gh.circle-artifacts.com/0/build/psalm.phar is the latest master build at the moment.

**Comment by ArtemGoutsoul** [comment]
@weirdan thanks for the link!
now I feel stupid, just noticed the artifacts tab :):
<img src="https://user-images.githubusercontent.com/1379350/106567626-cb678600-653a-11eb-874d-d6b240569140.png" width="200">

@muglug finally got a few mins to try the build from the link above (Psalm 4.x-dev@0f2a07a9a36d3942da0481f08d4fe89f27d72925), and it finished successfully! got 1724 errors, so the next step for me is to build some sensible config / baseline for our code base

**Comment by ArtemGoutsoul** [comment]
@muglug by running the latest psalm from master, I was able to improve the config and add some annotations to reduce the number of errors by an order of magnitude, so now I was even able to run the existing version successfully!

**Comment by muglug** [comment]
awesome!
