### ISSUE TITLE
Template types are not resolved for keys during array access

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#5112]
https://psalm.dev/r/7532f345b1

**Comment by weirdan** [comment]
You need `isset()` check prior to accessing the key, with or without generics. I don't see problem (with Psalm) here.

**Comment by danog** [comment]
I should've used a more specific example :)
https://psalm.dev/r/2dd569265c

**Comment by weirdan** [comment]
Well, that's a bit of an edge case with a single union member. Even with `Tkey as 0|1` accessing the key would not be safe without the `isset()/array_key_exists()` check.

**Comment by danog** [comment]
Yeah, you're right, no biggie :)
