### ISSUE TITLE
json_decode($foo, true) should be considered as an array

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#5114]
See https://psalm.dev/r/c35f67ce91

I don't know if it's not related to json_decode, because if I remove the `if` part I get a Mixed error
https://psalm.dev/r/248b3e3561

**Comment by weirdan** [comment]
You just need additional `is_array()` check: https://psalm.dev/r/73e458266f

**Comment by orklah** [comment]
Even with true as a second param, json_decode can still return a lot of things:
https://3v4l.org/23fRa
At best, you could refine mixed into `scalar|array|null`

As @weirdan said, you'll have to check manually the output.
