### ISSUE TITLE
Array type doesn't match when used in callable()

### ISSUE THREAD

**Issue by joehoyle** [vimeo/psalm#5116]
Best described by https://psalm.dev/r/3bdee1af3b

When specifying `array<array-key, mixed>` as a `callable()` argument, Psalm doesn't seem to allow `array{ foo: 1 }` to match `array<array-key, mixed>` which I think it should.

**Comment by muglug** [comment]
Nah, this breaks: https://psalm.dev/r/cfb0ffa304

**Comment by joehoyle** [comment]
Ahh I guess this is because `return_arr` requires a more specific array struct, with `callable(array)` being the type implies the function could be called with a less specific array type
