### ISSUE TITLE
Type widening fails for property union type

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#5119]
https://psalm.dev/r/ee715ba6c3

The type assertion contained in `if ($this->source instanceof \Countable) {` does not effectively widen the type of `$this->source` to include Countable.

**Comment by weirdan** [comment]
It's actually narrowing, not widening. Psalm should remove `Iterator` in that `if`.
It also works with no templates: https://psalm.dev/r/0adaa78eef

**Comment by muglug** [comment]
Hmm since `XIterator` extends `Iterator` you can rewrite this with https://psalm.dev/r/66e2672a19

**Comment by muglug** [comment]
This is fixed
