### ISSUE TITLE
Support for types in $_SERVER

### ISSUE THREAD

**Issue by joehoyle** [vimeo/psalm#5121]
Not opening a PR for this, as not sure if this behavior would be wanted. Currently `$_SERVER` is types as `array`. It might be useful to add optional keys for all the known types in $_SERVER. https://www.php.net/manual/en/reserved.variables.server.php says "You may or may not find any of the following elements in $_SERVER.". 

Could we add at least something like:

`array{ PHP_SELF?: string }` etc, or is the thinking that it's a mutable super global, so even defining optional keys is not a good idea?

Mostly this would be useful for completions, to prevent typos and needing to look up docs. Alternatively, I could just not declare the type, but have a completions heuristic separate from the valid types.

**Comment by weirdan** [comment]
Psalm takes a middle ground here and allows you to express your assumptions with [`<globals>`](https://psalm.dev/docs/running_psalm/configuration/#globals) directive, e.g.
```xml
<globals>
   <var name="_SERVER" type="array{REQUEST_TIME_FLOAT:float}"/>
</globals>
```

Programmatically it can be accessed with `VariableFetchAnalyzer::getGlobalType()`.
