### ISSUE TITLE
Text descriptions for Classes, functions and parameters

### ISSUE THREAD

**Issue by joehoyle** [vimeo/psalm#5129]
Following on from a question I asked in https://twitter.com/joe_hoyle/status/1350184540992659458. I'd like to add support for showing documentation in the LSP for all function-likes, classes and parameters. The most natural way to do this would be to add properties to `ClassLikeStorage`, `FunctionLikeStorage` and `FunctionLikeParameter`. On scanning the phpDoc description field would then populate the respective storage.

A few questions:

1. Is it worth only populating these fields when running via LSP? Thinking the memory usage might not be insignificant.
2. Would the project be willing to accept a PR for this?
3. This would mean potentially needing to add documentation descriptions for the php stdlib which could be a future burden? It looks like `CoreGenericClasses.phpstub` actually has descriptions but not the other files.

**Comment by muglug** [comment]
>  Is it worth only populating these fields when running via LSP? Thinking the memory usage might not be insignificant.

Yes, and regular Psalm won't be confused – LSP and regular Psalm uses entirely separate caches

> Would the project be willing to accept a PR for this?

Definitely

> This would mean potentially needing to add documentation descriptions for the php stdlib which could be a future burden? It looks like CoreGenericClasses.phpstub actually has descriptions but not the other files.

It might, but (on the other hand) php.net is very good, and I think LSP suggestions probably shouldn't try to take its place. 

On the other hand when the function/param/class description defined in regular PHP code, where there might not exist a good API documentation website, then I think LSP help is great.

**Comment by joehoyle** [comment]
Opened https://github.com/vimeo/psalm/pull/5267

**Comment by orklah** [comment]
I believe this has been fixed in #5267
