### ISSUE TITLE
Incorrect docblock for newInstanceArgs

### ISSUE THREAD

**Issue by kapitancho** [vimeo/psalm#5136]
The ReflectionClass::newInstanceArgs method is currently defined as 
@param array<int, mixed> $args

but for PHP8 it should be instead @param array<array-key, mixed> $args

Here is a perfectly valid example with a false positive:

https://psalm.dev/r/8481bf4b77

**Comment by orklah** [comment]
This should be a simple fix in https://github.com/vimeo/psalm/blob/master/dictionaries/CallMap_80_delta.php and CallMap.php.

Care for a PR?
