### ISSUE TITLE
Invalid return type when using Finally block statement

### ISSUE THREAD

**Issue by marcu87** [vimeo/psalm#5139]
When I use a Finally and an If before it, both returning the same thing, Psalm complains.

You can see it here: https://psalm.dev/r/00a021d43f

is this a bug or am I missing something?

**Comment by boesing** [comment]
I am experiencing problems with `finally` as well.
Somehow, variable usage is not properly detected.
Interesting is, that also ignores suppression of the error and when applying "fix code", the unused variable is being removed and a new error appears (`PossiblyUndefinedGlobalVariable`).

https://psalm.dev/r/90d0e94597

**Comment by muglug** [comment]
This is now fixed!
