### ISSUE TITLE
TypeDoesNotContainType error "$var is never falsy" for $var that can be falsy

### ISSUE THREAD

**Issue by M1ke** [vimeo/psalm#5147]
https://psalm.dev/r/21ff628a72

In this case `random_int()` has been used to demo the issue, but this works for any integer value that can't be determined by static analysis (e.g. value from database, user input, actual random number). In this case the code itself is handling an assertion case (i.e. checking that the value is not null) before doing other processing. However Psalm picks it up as it can never be falsy.

After encountering the issue I tried adding `/** @var array<int, string> */` to the const but this doesn't fix the issue. There may be some required type on the MAP that could specify a key can be falsy or maybe the code _must_ use isset rather than a falsy check, but the code here looks OK to me in terms of its error risk for the goal.

**Comment by azjezz** [comment]
the solution is to replace `MAP[$id]` by `MAP[$id] ?? null`.

since you are using `MAP[$id]` without a fallback, psalm assumes you are sure that the index exists.

If `$id` in this case was a user input, and it's out-of-bound, it will result in a runtime warning: https://3v4l.org/7Z10Z.

however, using `$v = MAP[$id] ?? null` tells psalm that you are not sure about whether $id is within-bound, and it assumes that the variable `$v` can now either `Tk` ( from `array<Tv, Tk>` ), or `null` ( from the fallback ).

IMHO, the bug is not that psalm is considering the value not-falsy, that is totally true as `MAP` contains only `non-falsy-string` values, but the bug ( or missing feature ), is psalm is not warning you about potential out-of-bound issue as the value of `$id` is unknown.

**Comment by M1ke** [comment]
@azjezz I'd agree with that; that would be a clearer suggestion by Psalm for the developer to implement (i.e. add `?? null` or otherwise) than at present where it's unclear how to stop Psalm from complaining because it's saying something that _can_ be falsy _can't_ be falsy.

**Comment by muglug** [comment]
Yeah, I don't really see this as a bug – it's bad code, which hopefully the person seeing the error is able to figure out.

**Comment by azjezz** [comment]
@M1ke my suggestion is to add an error handler that converts warnings to exceptions, and you will see that $var can never be falsy :) 

https://3v4l.org/rs6g1

**Comment by M1ke** [comment]
Yeah, that doesn't work so well in a lot of codebases. The nice thing about Psalm is that it allows fixing those kind of issues case by case, especially with the ability to define a baseline, and now the integration into PhpStorm.

I think what's not clear from the error here is what will fix it. I.e. I now know that `?? null` fixes it (and so does `?: false` and likely other combinations) but it's not obvious from the error that that's a fix, and the underlying code emits only a notice in PHP <8. So I am wondering if there's a way to statically analyse that we haven't done enough to avoid said notice/warning. In fact, what's interesting is that both `?? null` and `?: null` fix the Psalm error, but the latter still emits a notice/warning.

I'm not sure where to start with adding a rule, but @muglug would you accept a PR that highlighted the potential for an invalid key as an issue?

**Comment by azjezz** [comment]
>  what's interesting is that both ?? null and ?: null fix the Psalm error, but the latter still emits a notice/warning.

`??` and `?:` operator are not the same

```
$a = $map[$key] ?? null;
// same as:
$a = isset($map[$key) && null !== $map[$key] ? $map[$key] : null;

$a = $map[$key] ?: null;
// same as
$a = $map[$key] ? $map[$key] : null;

```

the difference is using `?:`, `$map[$key]` will be called, when with `??`, `isset` is called first to ensure that it is within-bound.

use `??` :)

**Comment by M1ke** [comment]
Yes this is true; my point was more that there's two ways to stop the Psalm error but one of those still leaves a potential runtime issue. Psalm could probably flag the potential for the call to be out of bounds is my main contention. So this would go from a bug issue to an enhancement issue.
