### ISSUE TITLE
Psalm complains about incorrect return type when using conditional type based on param value

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5150]
I tried to implement conditional type for returning modified param `a` based on param `b`

`@psalm-return ($x is true ? array<TKey, TValue> : array<array-key, TValue>)`

However, psalm complains about invalid return type `Docblock has incorrect return type`  and suggests to use `array<array-key, mixed>` instead. Am I missing something or am I trying to do something that is not supported?

https://psalm.dev/r/8550940a32

**Comment by orklah** [comment]
You just need to type your TKey https://psalm.dev/r/83d9fdf3d9

**Comment by simPod** [comment]
Oh god, right. Thanks!
