### ISSUE TITLE
Add unique issue's footprint to baseline (dupe_key?)

### ISSUE THREAD

**Issue by zakirullin** [vimeo/psalm#5155]
I am developing a psalm plugin, and I stumbled upon a problem - in my case baselined issues are fragile since both `code` and `occurrences` are subject to change. Looking for a unique issue's footprint. 

While throwing a `PluginIssue` I can unambiguously provide a unique (code independent) string key (dupe-key?) which can be later used in baseline.
That footprint would be way more stable than code & occurrences counter.

Just fake and naive example:

```xml
    <MissingContainerDependency occurrences="1">
      <code>$container->get('service')</code>
    </MissingContainerDependency>
```

Would turn into:
```xml
    <MissingContainerDependency occurrences="1">
      <footprint>get_dependency:service</footprint>
    </MissingContainerDependency>
```

Now `$container->get('service')` could be refactored to `$c->get($serviceName)` without ruining the baseline file.
The example is naive, but it gives a basic idea.

**Comment by orklah** [comment]
Closing as stale
