### ISSUE TITLE
Psalm doesn't understand conditional return types with variadic param

### ISSUE THREAD

**Issue by davidrans** [vimeo/psalm#5159]
Here's a pretty simple repro:
https://psalm.dev/r/5130a624d7

Checking if a variadic argument is empty in a conditional return type has unexpected behavior. In the example linked above, I'd expect psalm to understand that `$f('asdf')` returns a `string`.

**Comment by orklah** [comment]
The type `empty` is a special type that exclude every other type. It's used by psalm to describe things that are not there, for example `[]` is an `array<empty, empty>`. If you iterate on the array, you'll technically have a variable with `empty` type but that should not happen at runtime.

I was gonna suggest to reverse the condition and use `non-empty-array` but there's something weird going on:
https://psalm.dev/r/d13b235272

**Comment by muglug** [comment]
You can use `func_num_args()` instead: https://psalm.dev/r/70e364874e

**Comment by davidrans** [comment]
Thanks!
