### ISSUE TITLE
Enhancement: suppress error output with --find-references-to

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#516]
Currently when you run `psalm --find-references-to='Class\Name'`, in addition to found references it additionally outputs a lot of errors (UnusedVariable and UnusedParam, which are not reported during regular runs).

It clutters the output and is not something you're interested in when you're trying to find where the class is used. Could it be automatically suppressed?

**Comment by muglug** [comment]
This is a bug, and regression

**Comment by muglug** [comment]
Thanks for reporting!

**Comment by weirdan** [comment]
I'm still getting errors (though Unused* are no longer reported) with Psalm dev-master@ ec5c9c862c13097b47af82ae0743d475adeeb510
Now they appear to be the same set of errors I would get with regular `psalm` run on this codebase: TypeCoercion, MissingParamType, PossiblyNullPropertyAssignmentValue, PropertyNotSetInConstructor, LessSpecificReturnStatement, MoreSpecificReturnType, UndefinedMethod, UndefinedClass

**Comment by weirdan** [comment]
/ping @muglug 
I think it makes sense to reopen this issue, see https://github.com/vimeo/psalm/issues/516#issuecomment-366489171

**Comment by muglug** [comment]
Thanks, should be fixed now

**Comment by weirdan** [comment]
Yep, works now.
