### ISSUE TITLE
UndefinedClass error when using static methods of traits directly

### ISSUE THREAD

**Issue by enkarito** [vimeo/psalm#5160]
False positive error is detected when trait with static method is being used directly/

```
<?php
trait TraitWithStaticMethods {
    public static function foo() {}
}

class Bar {
    public static function bar(): void 
    {
        TraitWithStaticMethods::foo();
    }
}
```

`ERROR: UndefinedClass - 9:9 - Class or interface TraitWithStaticMethods does not exist`

Sample:
https://psalm.dev/r/56475171ed

**Comment by weirdan** [comment]
This is not supposed to work with Psalm, see #4574

**Comment by weirdan** [comment]
This is also going to be removed from PHP, see https://wiki.php.net/rfc/deprecations_php_8_1#accessing_static_members_on_traits
