### ISSUE TITLE
Wrong "Docblock-defined class or interface MyTrait does not exist" when declaring as Trait

### ISSUE THREAD

**Issue by obeobe** [vimeo/psalm#5168]
I get "Docblock-defined class or interface MyTrait does not exist" when I declare a function parameter as a Trait.
I believe that it's wrong.
Note that PhpStorm can process this and offer type checks and auto completion based on this declaration.

Code:
```
trait MyTrait {
    
}

/**
 * @param MyTrait $myParam
 * @return void
 */
function myFunction($myParam) {
	
}
```
Snippet: https://psalm.dev/r/2943919fc8

**Comment by weirdan** [comment]
Trait is not a type, thus it cannot be used as a parameter type. E.g. this fails: https://3v4l.org/LU7YM

**Comment by obeobe** [comment]
I thought the idea of Psalm was to go beyond PHP's type system.

I don't know if PHP devs have plans to support Traits as types in the future, but it's useful, and supported by PhpStorm.

The alternative is to declare a separate interface, declare all of the Trait's public functions, and `implement` it in every class that uses the Trait. And I believe that even this will still be limited because a Trait could also expose variables, which AFAIK cannot be declared in an `interface`.

So, I understand that it's not a bug, but maybe treat it as a feature request?

**Comment by weirdan** [comment]
> I thought the idea of Psalm was to go beyond PHP's type system.

Sure, where it doesn't contradict PHP type system.

> I don't know if PHP devs have plans to support Traits as types in the future

That seems very unlikely.

> but it's useful

Traits provide no guarantees about method availability: https://3v4l.org/BIS6U
Traits do not have a way to check if they are used by the class (`instanceof` wouldn't work).

So they are not useful as types to Psalm.

**Comment by obeobe** [comment]
> Traits provide no guarantees about method availability: https://3v4l.org/BIS6U
Traits do not have a way to check if they are used by the class (instanceof wouldn't work).

I believe that both of these can be determined with certainty using Reflection (with the help of `ReflectionClass::getMethods()` and `ReflectionClass::getTraits()`, respectively). But I'm hardly an expert on this so apologies if I'm wrong here.
