### ISSUE TITLE
@const doesn't work, or type doesn't propagate

### ISSUE THREAD

**Issue by obeobe** [vimeo/psalm#5170]
It seems that `@const` doesn't work, or the type assigned via `@const` is not propagated in later assignments.

It reproduces with this code:
```
<?php

abstract class HisClass {

}

/**
 * @template T of HisClass
 */
class MyClass {
    /**
     * @const class-string<T>
     */
    const HIS_CLASS = null;
    
    /**
     * @return T
     */
    public function thisDoesNotWork() {
        $cls = static::HIS_CLASS;
        
        /** @psalm-suppress UnsafeInstantiation, MixedMethodCall */
        $hisClassInstance = new $cls();
        return $hisClassInstance;
    }
}
```

This results in several errors, which I believe all boil down to the first:
```
INFO: MixedAssignment - 20:3 - Unable to determine the type that $cls is being assigned to
```

I also tried to replace the `@const` with `@var` but it didn't help.

If I add `/** @var class-string<T> $cls */` above the `$cls = ...` line - it resolves the issue (also shown in the snippet below).

Snippet: https://psalm.dev/r/dbf8296514

**Comment by weirdan** [comment]
`@const` is not something Psalm knows about. Is it documented anywhere?

**Comment by obeobe** [comment]
I haven't seen it in Psalm documentation.
As I mentioned, `@var` doesn't work as well. Is there any way to designate a type for ` const`? If not then maybe it can be treated as a feature request...

**Comment by muglug** [comment]
Nothing designed for `const`, as Psalm infers those types in normal operation.

**Comment by weirdan** [comment]
> I haven't seen it in Psalm documentation.

I mean is there a formal (or informal) specification for that docblock tag?

**Comment by obeobe** [comment]
Well, I found this: https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/var.html#var , which contains:
```
You may use the @var tag to document the Type of the following Structural Elements:

    Constants, both class and global scope
```

It doesn't say anything about `@const`, and I actually don't need specifically `@const`. I just want to tell Psalm that a constant is `class-string`. This cannot be inferred (at least not to specify a class-string of a template). `@var` is fine too.

**Comment by weirdan** [comment]
Until PHP supports abstract constants it's better to use a method instead: https://psalm.dev/r/caf600892c
