### ISSUE TITLE
Way to type extending of object-like arrays?

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5175]
Consider fn input `array{TKey: string}` and output `array{TKey: string, TKey2: string}`

Is there a way to type that return type extends input type with field(s) added?

```php
/**
 * @param list<S> $rows
 * @param SKey $source
 * @param TKey $target
 *
 * @return list<T>
 *
 * @template SKey of string
 * @template TKey of string
 * @template S of array{SKey: mixed}
 * @template T of array{TKey: mixed} // how to say that T is {TKey: mixed, ...S} ?
 */
```

https://psalm.dev/r/d5d8b8e9c2

Not sure how it is considered here, whether `{a: string, b:string}` extends `{a: string}`. Works like this in TS, AFAIK.

**Comment by muglug** [comment]
How would you do it in TypeScript?

**Comment by simPod** [comment]
Something of this style

https://www.typescriptlang.org/play?#code/MYewdgzgLgBApgDynMATGBeGAeAUAZQGk4BPeJFVCGaAJwEswBzAGhlwBVizFk1q6jVuwDy5PlRgBvANr4YjGEVIBdAFw0oDZgF82uAHLjK1WRwVgYXUgB9lJdZu1MdAPgAUuGN5ggARgBWMBoi+j40IACutMBwGvZhPlAAhrRMcFAa1iS4AJRqRhiu0l4+tBnRllKl4d4yKWkZjv4BMhBRMXAqLDW1AHQDLb06ANy4OriToJCwLZjGaO5SyRoARKt6MKvJq2yrfqu5Y9PtADZwfacgTO4tfclHuCcg55fXt4F9fo+TT+DQvkCACZ5rxKEsVlsNntgLstqhDsd-i8Llcbi0gfdHs9XmiPgFMd8kZAUW90cC+sBscjce8MX1UEcgA

**Comment by muglug** [comment]
Hmm I just don't think that's particularly practical, sorry.

**Comment by simPod** [comment]
Aight, thank you.
