### ISSUE TITLE
Callable [$object, 'method'] does not work when providing a result of a generic type

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#5176]
https://psalm.dev/r/51a298227b

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/d96c1e7411

**Comment by muglug** [comment]
Simplified better I think? https://psalm.dev/r/bf31ddfe4c

**Comment by vudaltsov** [comment]
> Simplified better I think? https://psalm.dev/r/bf31ddfe4c

yes!
