### ISSUE TITLE
Utf8 Rune Pseudo Type

### ISSUE THREAD

**Issue by mnavarrocarter** [vimeo/psalm#5185]
Hi! First of all, big kudos to all the maintainers. Psalm is, in my opinion, one of the PHP projects that I could not live without! So thank you.

The purpose of this issue is to pitch a possible pseudo-string type. 

Pseudo types like the `class-string` are really useful. And if is possible and you guys deem it a possible good feature to have, to have a `utf8-rune` pseudo string type would be amazing. This type would represent a utf8 code point. I don't know how technically possible implementing this could be. In my ignorance I imagine if `class-string` can be done, this one could too. 

This request is pretty much inspired in Golang's rune type.

What do you think?

**Comment by weirdan** [comment]
New types takes a lot of effort. Do you have examples of multiple unrelated codebases that could be simplified or their typechecking could be significantly improved by introducing this new type?

**Comment by mnavarrocarter** [comment]
Hey @weirdan not really. I have a few libraries where that would come in handy for is pretty much a whim. If is that complex as you mention then it's probably not worth the effort.

**Comment by weirdan** [comment]
It's fairly complex.
