### ISSUE TITLE
Class or interface does not exist + Could not verify return type

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#5188]
I'm sorry but I was unable to reproduce this issue on https://psalm.dev/, so I created a minimum reproduce project here:

https://github.com/BenMorel/psalm-bug

## Trimmed down offending script

```php
<?php

use thiagoalessio\TesseractOCR\TesseractOCR;
use thiagoalessio\TesseractOCR\TesseractOcrException;

class Image
{
}

class Service
{
    public function store(string $hash): Image
    {
        $image = $this->tryFindByHash($hash);

        if ($image !== null) {
            return new Image();
        }

        $ocr = new TesseractOCR();

        try {
            /** @var string $ocrText */
            $ocrText = $ocr->run();
        } catch (TesseractOcrException $e) {
            $ocrText = null;
        }

        return new Image();
    }

    private function tryFindByHash(string $hash): ?Image
    {
        return null;
    }
}
```

## How to reproduce

```bash
git clone https://github.com/BenMorel/psalm-bug.git
cd psalm-bug
composer install
vendor/bin/psalm
```

## Result

> ERROR: MixedInferredReturnType - src/test.php:12:42 - Could not verify return type 'Image' for Service::store (see https://psalm.dev/047)
> `public function store(string $hash): Image`

> ERROR: UndefinedClass - src/test.php:25:18 - Class or interface thiagoalessio\TesseractOCR\TesseractOcrException does not exist (see https://psalm.dev/019)
> `} catch (TesseractOcrException $e) {`

**I think there are two issues in one:**

- `thiagoalessio\TesseractOCR\TesseractOcrException` **does exist**; however, it's defined in the same file as the [FriendlyErrors](https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/2.10.0/src/FriendlyErrors.php) class, which is autoloaded when an exception is thrown from within the [TesseractOCR](https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/2.10.0/src/TesseractOCR.php) class. Not good practice if you ask me, but it does work at runtime because exceptions are only ever thrown from within the `FriendlyErrors` class;
- even if the exception did not exist, I'm not sure why Psalm would complain that the return type cannot be verified, when all function exit points return an `Image` instance.

**Comment by weirdan** [comment]
That package declares being PSR-4 autoloadable, but doesn't exactly follow the standard. Psalm needs a way to resolve class names to file names and when it sees PSR-4 autoloader it uses that.

The latter point does look like a legitimate Psalm bug though.

**Comment by weirdan** [comment]
Reproduced and simplified: https://psalm.dev/r/f0a85594df
Basically Psalm stops checking the rest of the method when it encounters `catch()` with unknown exception type.
