### ISSUE TITLE
Implementation of templated interface are not accepted as parameter

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#5191]
Hello,

Before Psalm 4.5.0 the following code https://psalm.dev/r/a065b9f1e1 did not throw an InvalidArgument error.

To me it looks like this situation should not throw an error since `AccessKeyScope` implements `AuthenticationScope`.

**Comment by muglug** [comment]
Make the template covariant and you're golden: https://psalm.dev/r/3ddfb5ce65

**Comment by LeSuisse** [comment]
@muglug Thanks for the hint. I took a closer look this morning and I am still confused on why this sort of code now gets an error: https://psalm.dev/r/8ed8969689

I saw this was changed by https://github.com/vimeo/psalm/commit/8b5e0fc754f8b29b21b1aa8b1ddc91e49062d428 but if took your example in #5172 I would have expected something like this to work https://psalm.dev/r/d0ba5ce80c

What do I miss?

**Comment by muglug** [comment]
Read up about covariance: https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance

**Comment by muglug** [comment]
You can fix this by making the param type more specific: https://psalm.dev/r/22daffda44
