### ISSUE TITLE
Nullable result with some ifs

### ISSUE THREAD

**Issue by franmomu** [vimeo/psalm#5193]
I've tried to simplify the example, hence it doesn't make much sense, but the idea is that if you remove one (or both) of the random `if`, it does not complain.

https://psalm.dev/r/3bcb50ec89
https://psalm.dev/r/4c278fef42

**Comment by weirdan** [comment]
Something funny is going on here: https://psalm.dev/r/fd4f04b6c4

**Comment by orklah** [comment]
I'll flag this as "more info needed". There is indeed something funny going on, but it all goes back to the content of the given offset being impossible. Psalm tries to juggle with the fact there's nothing in here.

We could possibly try to remove the fact that $a[$b] even exist in the remaining scope (which would lead to psalm-trace being impossible), but I don't think it will help a lot of people and it's added complexity.

I'd be more interested to know what was the original code here and whether or not it could make sense while still reproducing this error

**Comment by franmomu** [comment]
I've just tried again and the issue is not showing up anymore, it was in this method:

https://github.com/doctrine/persistence/blob/f8af155c1e7963f3d2b4415097d55757bbaa53d8/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php#L221

At that time, it was psalm 4.3.1, so I think it's fine to close here and report in a new issue if this comes up again, thanks @orklah
