### ISSUE TITLE
False-positive RedundantCondition caused by templated `@psalm-assert`

### ISSUE THREAD

**Issue by remorhaz** [vimeo/psalm#5195]
Conditions: 

1. We annotate `foo()` function so that it asserts that her first argument `$a` is of class that's name is passed as a string in a second argument.
2. We call `foo()`, passing there a `B` instance as a first argument and `B::class` as a second argument.

https://psalm.dev/r/7a3ca82e29

Expected behavior: everything is okay. We can use `foo()` in different contexts, and I think there's no crime in passing there a value which type is known and valid before the assertion is made.

Actual behavior: `RedundantCondition` is reported.

**Comment by weirdan** [comment]
This is by design. For methods with assertions assertions are interpreted as the main outcome of the method. Just suppress it.
