### ISSUE TITLE
Psalm 4.5 does not recognize interface-implementations as valid types

### ISSUE THREAD

**Issue by arjenm** [vimeo/psalm#5202]
We have a few new issue-reports on our code base with 4.5.1 in contrast to 4.4.1. Some of those are valid, but a few seem to be bugs in Psalm. Specifically where it does not recongize subclasses or interfaces-implementations as valid types.

https://psalm.dev/r/e77387d4b9

I don't know if that example covers all code-paths that result in the invalid reports. Unfortunately, not all examples in our real code can easily be converted in such self-contained examples.

One of those is a `RedundantCondition` in our codebase with that Identity. Where a test with a method parameter of type Identity is tested with an instanceof like `$identity instanceof StringIdentity`. And that results in the message: `Identity<int|string> cannot be identical to StringIdentity (see https://psalm.dev/122)`.

And another hard to self-contain example results in a `TypeDoesNotContainType`. It has a similar instanceof but with a more complex hierarchy. This time the error states that the SubClass is not contained in 'ParentClass|null'.

**Comment by muglug** [comment]
The template needs to be covariant: https://psalm.dev/r/636d9fe327

**Comment by muglug** [comment]
The change here is Psalm now treats any `Identity` it sees lacking params as `Identity<int|string>`. This is a bugfix, and it's consistent with other tools.

**Comment by matiux** [comment]
I have same error

https://psalm.dev/r/8041057cfb

**Comment by matiux** [comment]
If I use @template-covariant I get this error:

https://psalm.dev/r/a5270a8d6f

**Comment by matiux** [comment]
@muglug do you have some suggestion for me?
