### ISSUE TITLE
Psalm 4.5 does not recognize interface as valid type when overriding property-doc

### ISSUE THREAD

**Issue by arjenm** [vimeo/psalm#5203]
We have a overriden protected property with a more specific type-hint, similar to this self-contained example.

https://psalm.dev/r/fdb4ea2952

It states ERROR: NonInvariantDocblockPropertyType - 20:15 - Property ProcessIt::$identity has type IntIdentity, not invariant with Base::$identity of type Identity2
 
But the IntIdentity does implement Identity2. This simpler variant also fails, with just a single interface:
https://psalm.dev/r/e5febeb93e

**Comment by muglug** [comment]
Use templates: https://psalm.dev/r/2629d1d351
