### ISSUE TITLE
psalm 4.5.1 syntax error on php 7.2 

### ISSUE THREAD

**Issue by etremblay** [vimeo/psalm#5206]
With PHP 7.2, we get the following error.  PHP 7.3 is ok.

I guess it's caused by the trailing coma on constructor call.

You may increase the php requirement in composer.json in the braking change is intended.

```
Uncaught ParseError: syntax error, unexpected ')' in /home/circleci/project/vendor/vimeo/psalm/src/Psalm/Codebase.php:1635
Stack trace:
#0 /home/circleci/project/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/circleci/...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Psalm\\Codebase')
#2 /home/circleci/project/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(277): spl_autoload_call('Psalm\\Codebase')
#3 /home/circleci/project/vendor/vimeo/psalm/src/psalm.php(620): Psalm\Internal\Analyzer\ProjectAnalyzer->__construct(Object(Psalm\Config), Object(Psalm\Internal\Provider\Providers), Object(Psalm\Report\ReportOptions), Array, 11, Object(Psalm\Progress\DefaultProgress))
#4 /home/circleci/project/vendor/vimeo/psalm/psalm(2): require_once('/home/circleci/...')
#5 {main}
(Psalm 4.5.1@257a1ca672a79dedc852be1285a7b97154646418 crashed due to an uncaught Throwable)
```

**Comment by etremblay** [comment]
> Hey @etremblay, can you reproduce the issue on https://psalm.dev ?

No, it's not an analysis related issue.

**Comment by etremblay** [comment]
Thanks !

**Comment by XedinUnknown** [comment]
Thanks for the quick fix! It would be great to see a release quickly too, even an alpha one.

**Comment by XedinUnknown** [comment]
@muglug I see you are building only on PHP 8. Why not run tests on all target version, i.e. 7.1, 7.2, 7.3, 7.4, 8.0? You declare compat with 7.1, but how do you know it's compatible? 🤔

**Comment by XedinUnknown** [comment]
I am also able to reproduce this problem on 4.5.0 by the way.

**Comment by XedinUnknown** [comment]
Oh, that's quick! Cool, thanks!
