### ISSUE TITLE
Explore language server compatibility

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#521]
This is a v3 feature, may never happen. But it'd be cool.

**Comment by TysonAndre** [comment]
I think that using a PHP wrapper of psalm (That invokes `./psalm` manually via system()/proc_open()), it would be feasible for projects that have a working autoloader (E.g. the composer autoloader for src/)

- The wrapper would need virtually no knowledge of psalm's internals (Except maybe to avoid unnecessarily starting psalm for a change to an irrelevant file)

However, two (or one) CLI options would have to be added, and there would need to be some work on writing a wrapper:

- `--analyze-file path/to/file1.php [--analyze-file path/to/file2.php]`. A CLI option that would limit `<projectFiles>` to the specified file names, excluding other files and directories.
  (Psalm should ignore files that weren't in the original projectFiles files or directories, e.g. vendor, `.txt` files, etc)

- `--override-file-contents {"path/to/file1.php":"raw_contents"}`

---

E.g. as an experiment:

```diff
     <projectFiles>
-        <directory name="src" />
-        <directory name="tests" />
-        <directory name="examples" />
-        <ignoreFiles>
-            <file name="src/Psalm/CallMap.php" />
-            <directory name="src/Psalm/Stubs" />
-            <directory name="tests/stubs" />
-        </ignoreFiles>
+       <file name="src/Psalm/CodeLocation.php" />
     </projectFiles>
```

Command used: `./psalm src/Psalm/CodeLocation.php` (I haven't looked into why I had to pass CodeLocation twice)

Time needed to analyze src/Psalm/CodeLocation with a modified psalm invocation and CLI command: 0.20 seconds (That can be reduced to 0.15 with igbinary)
Time needed for a full psalm analysis of psalm itself: 5.23 seconds

- Hopefully, even if analyzing a much larger project that takes minutes to analyze, analyzing a single file (or 3 files) would still take around 0.20 seconds)

php-language-server can be used as a base (Or [this project forked from php-language-server to focus on linting](https://github.com/phan/phan/tree/master/src/Phan/LanguageServer))

didOpen/didChange/didClose/didChangedWatchedFiles could be used as a base.

Aside: If psalm takes 0.20 seconds to analyze a small set of files (or even 1 second), it may receive events faster than it can respond. https://github.com/phan/phan/blob/df577b0699869df888d33c7d18d1f451d8264378/src/Phan/LanguageServer/LanguageServer.php#L140-L183 (Separate events for 'message' and for 'readMessageGroup' are one way to mitigate that).

**Comment by muglug** [comment]
This is what I have at the moment: https://github.com/vimeo/psalm/compare/server

Running `./psalm --server` puts it into a mode where you can query node types via telnet. Shouldn't be too much work to have it spit out errors there.

**Comment by muglug** [comment]
After banging my head against many walls, that branch has something that works with LSP, thanks in no small part to Phan's version of Felix's code. Very far to go though.
