### ISSUE TITLE
Language Server: Autocomplete for PHPUnit

### ISSUE THREAD

**Issue by thomasbley** [vimeo/psalm#5210]
I'm using psalm-vscode-plugin v1.2.2 with vs-code 1.52.1 / 1.53.0 (and code-server 3.8.1) and tried to get auto-complete working for phpunit 9.5.2 (loaded as composer library). E.g. $this->assertTrue() cannot be autocompleted from PHPUnit\Framework\TestCase -> PHPUnit\Framework\Assert.
When I type $this->assertTrue() manually, detecting invalid parameters works.

![107127636-b6cb1b00-68b7-11eb-86d5-db5a6e398fae](https://user-images.githubusercontent.com/941223/107809230-094e8080-6d6b-11eb-8a57-c8d1e4b35a4d.png)

![107127639-bd599280-68b7-11eb-9d46-1fdb24eb79e2](https://user-images.githubusercontent.com/941223/107809227-08b5ea00-6d6b-11eb-9f11-6f2ef7a03042.png)

I'm not sure it's related to psalm-vscode-plugin or psalm itself, so I also reported this in https://github.com/psalm/psalm-vscode-plugin/issues/34 .

Happens with psalm 4.4.1 and psalm 4.5.1

**Comment by thomasbley** [comment]
I think I found my issue:

assertTrue is defined as static: public static function assertTrue().

But I call it in class context $this->assertTrue() as advised by the documentation https://phpunit.readthedocs.io/en/9.5/assertions.html#asserttrue

A change could be this, but I'm not sure it's good for all cases:

```
+++ b/src/Psalm/Codebase.php
@@ -1497,16 +1497,10 @@ class Codebase
             }
         }
 
-        if ($gap === '->') {
-            $completion_items = $instance_completion_items;
-        } else {
-            $completion_items = array_merge(
-                $instance_completion_items,
-                $static_completion_items
-            );
-        }
-
-        return $completion_items;
+        return array_merge(
+            $instance_completion_items,
+            $static_completion_items
+        );
```

What do you think about it?

**Comment by muglug** [comment]
Sorry, again. This is fixed.

**Comment by thomasbley** [comment]
No problem, thanks for fixing this issue!
