### ISSUE TITLE
Endless loop when using generic instance

### ISSUE THREAD

**Issue by corphi** [vimeo/psalm#5211]
Given the snippet 

```php
<?php

/**
 * @psalm-template TKey of object
 * @psalm-template TValue
 * @template-extends SplObjectStorage<TKey, TValue>
 */
class ObjectStorage extends SplObjectStorage
{
}

$foo = new ObjectStorage();
```

Psalm endlessly ponders its last line, until it hits the `memory_limit`. The demo snippet https://psalm.dev/r/95d73fc1a4 has no output, because the worker supposedly crashes, too.

Current versions (tested with 4.4+) choke on it, but Psalm 3.18.2 does not.

**Comment by corphi** [comment]
It seems to be introduced by a8d7248c3106d65afcfd8d23aeb5d11d622a3d8b in 4.2.0.

**Comment by muglug** [comment]
A (very dumb) workaround is just to rename your generic param to be anything _but_ `TValue`

**Comment by corphi** [comment]
Thanks, that was quick! :+1:
