### ISSUE TITLE
Union of list types incorrectly allows list of union types

### ISSUE THREAD

**Issue by zdmitchell** [vimeo/psalm#5212]
Typing a parameter as `list<A>|list<B>` seems to allow `list<A|B>`.

https://psalm.dev/r/2477ec20a8

**Comment by muglug** [comment]
Yes, Psalm treats arrays different than other generics – `list<A>|list<B>` is treated identically to `list<A|B>`

**Comment by n7olkachev** [comment]
@muglug but why?

**Comment by orklah** [comment]
Standards and supports of standard about how to annotate types in php have a long history. For example, until a few months, the best way to document that a function could take an array of int or string in PHPStorm was to annotation `int[]|string[]`. Advanced phpdoc like `(int|string)[]` or generic notation like `array<int|string>` was not supported.

If Psalm were to start understanding `int[]|string[]` as "either an array of string or an array of ints", it would leave a lot of projects with a lot of false positives.

Note that PHPStan and Phan also accept your code as valid

**Comment by n7olkachev** [comment]
Thanks for the detailed response!

But what about array shapes? Consider this example: https://psalm.dev/r/c16764f72c
It's clearly 
AFAIK there was no way to document something like this for phpstorm earlier, so there should be no problems with many projects?

Also, maybe there is a chance that this can be a configurable behaviour?

**Comment by orklah** [comment]
Indeed, the explanation must not be the same for array shapes and if there's a reason, I don't know what it is.

Unless it's just a way to reduce complexity. Type system can lead to weird errors very quick. Keep in mind for example that `array{type: "userCreated", userID: int}` means "at least two keys type and userId", it wouldn't mean that `productID` can't be in the first part of `array{type: "userCreated", userID: int}|array{type: "productCreated", productID: int}`

So you have shapes that are exclusionary with one another but also can contain keys from the other shape.

I don't believe there is a way to make this configurable, I wouldn't have the skills to do that and it would mean double maintenance on this. The only way would be to change it for everyone.

You can open an issue for this if you want as this is a valid suggestion (PHPStan is actually handling arrays shapes like you propose) but unless we get more regular contributors. I'm afraid this won't change in the next few years
