### ISSUE TITLE
Virtual nodes created by Psalm sent to plugins

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#5215]
I'm currently implementing AfterExpressionAnalysisInterface in order to detect and change == into === when safe.

It seemed pretty easy but I'm stuck with an issue I don't know how to solve.

In SwitchCaseAnalyzer (and probably elsewhere), Psalm is creating a new Expr\BinaryOp\Equal in order to analyse operations. This Equal Expression is then sent to the plugin as if it was in the original code as a real "==" node.

Unfortunately, When I try to replace with a === it just breaks the code. I couldn't find a way to differentiate between those virtual nodes and real one.

Is there a way to do that I'm missing or could we maybe flag those node somehow to exclude them in plugin analysis?

**Comment by orklah** [comment]
Ok, I gave it some thought, the solutions I came up were:
- Add an attribute `virtual => true` to every node created in Psalm. (probably a few hundreds)
- Create classes extending PHPParser's Nodes (for example VirtualString_) and use those in Psalm instead of native ones
- Register every virtual node created in some sort of storage (kinda like nodeTypeProvider) that the plugin could call to know if the node is virtual or not

I'm out of ideas :)

Creating classes seems the most clean to me, @muglug can you tell me if it's worth it before I start a PR?

Thanks

**Comment by muglug** [comment]
> Creating classes seems the most clean to me, @muglug can you tell me if it's worth it before I start a PR?

It's definitely the most clean, and I also don't see any drawbacks to that approach. I guess each would implement a `VirtualNode` interface or somesuch to differentiate them

**Comment by orklah** [comment]
Fixed by linked PR
