### ISSUE TITLE
Uncaught ParseError: syntax error, unexpected ')' in vimeo/psalm/src/Psalm/Codebase.php:1635

### ISSUE THREAD

**Issue by williamdes** [vimeo/psalm#5216]
Uncaught ParseError: syntax error, unexpected ')' in /home/runner/work/phpmyadmin/phpmyadmin/vendor/vimeo/psalm/src/Psalm/Codebase.php:1635

https://github.com/phpmyadmin/phpmyadmin/pull/16642/checks?check_run_id=1895071425#step:7:6

**Comment by muglug** [comment]
Yeah, this is fixed in master – I'll release in 10-15 minutes

**Comment by muglug** [comment]
This is released
