### ISSUE TITLE
Broken ??= on array items or pre-defined null on arrays and on other variables without type hints

### ISSUE THREAD

**Issue by jpresutti** [vimeo/psalm#5223]
ERROR: TypeDoesNotContainType - 4:1 - Type null for $return['readable'] is never isset

INFO: MixedAssignment - 8:1 - Unable to determine the type of this assignment

ERROR: TypeDoesNotContainType - 12:1 - Type null for $returnC is always null

See https://psalm.dev/r/6c6ebaf3a0

**Comment by orklah** [comment]
Why not use `=` when you know there can't be any value?

**Comment by jpresutti** [comment]
My specific code I was running this on has multiple if statements and still gives the error.  I could refactor my code I guess but it seems to me like the whole point of ??= is for "assign if null" and this check is overly strict. I would not be upset if you close as won't fix, the more I think about it the more I think it's my own thinking that's the problem.

**Comment by orklah** [comment]
Well, if you have an example where Psalm can't see the value could be there, it'd definitely be a bug. It would not mean it would automatically be worth fixing, but with the example you gave, it's a useful check to avoid dumb mistakes in code, it'd be a mistake to remove it

**Comment by jpresutti** [comment]
After analyzing some more I guess I'm the problem. I just need to make the first if a `=` instead of a `??=`. Not uniform, but correct. Closing. Sorry!
