### ISSUE TITLE
fputcsv $fields parameter should be array of strings

### ISSUE THREAD

**Issue by DaveLiddament** [vimeo/psalm#5226]
I _think_ the `fields` parameter for `fputcsv` should be an array of strings. See [PHP manual](https://www.php.net/manual/en/function.fputcsv.php).

[This snippet](https://psalm.dev/r/2478131ecf) should report an error on line `22`.

Running the code in the snippet on PHP 8.0 (`PHP 8.0.0 (cli) (built: Dec  6 2020 06:56:11) ( NTS )`) results in this error:
```
PHP Fatal error:  Uncaught Error: Object of class Person could not be converted to string in /home/vagrant/example/csv.php:24
Stack trace:
#0 /home/vagrant/example/csv.php(24): fputcsv()
#1 {main}
  thrown in /home/vagrant/example/csv.php on line 24
```

NOTE: I've seen  a similar error with PHP 7.3 too.

**Comment by DaveLiddament** [comment]
See also: https://github.com/phpstan/phpstan-src/pull/448

**Comment by orklah** [comment]
Indeed, the function is documented as `array`. However, please consider allowing int or floats too at least. They can be casted to a string without any issue

**Comment by DaveLiddament** [comment]
Good point @orklah 

As a starting point for a test case I've created [another snippet](https://psalm.dev/r/45dc241a38) . 

I only raise this as I was caught out when I changed a string to a value object and my CSV generation failed.   PHPStan didn't flag this as an issue, and nor would have have Psalm.

**Comment by DaveLiddament** [comment]
`null` also works.... So here in updated [snippet](https://psalm.dev/r/58b7ab935a)
