### ISSUE TITLE
Inconsistent behavior with template-extends and template constraints

### ISSUE THREAD

**Issue by simitter** [vimeo/psalm#5229]
Hello,

If a class extends a template and puts in the constraints  directly in the extends tag seems to work fine.
If template extends derives the constraints from another template psalm reports a MixedArgumentTypeCoercion

It seemed to work in the 4.4 versions.
Is this a bug or am i missing something?

https://psalm.dev/r/6258a74579

**Comment by githoober** [comment]
I have a similar case:

https://psalm.dev/r/a73291657c

**Comment by githoober** [comment]
This behavior is not present in psalm 4.4 and shows up in 4.5 and continues in 4.6.
