### ISSUE TITLE
Result of instanceof assigned to a variable inside if (...) is considered always true

### ISSUE THREAD

**Issue by sad-spirit** [vimeo/psalm#5232]
https://psalm.dev/r/9b7d186a4b

If assignment is done outside of `if (...)` condition
```PHP
$check = $foo instanceof Bar;
```
the error does not appear;

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/cf8f812eee

**Comment by muglug** [comment]
Now fixed
