### ISSUE TITLE
ERROR: NonInvariantDocblockPropertyType

### ISSUE THREAD

**Issue by 0x450x6c** [vimeo/psalm#5234]
Hello.

Got this error after upgrade to 4.5.0 version.

Example:
https://psalm.dev/r/a42b5d1833

**Comment by 0x450x6c** [comment]
There was other error too in the example.

Corrected example here:
https://psalm.dev/r/ce4641acb0

**Comment by muglug** [comment]
You can just remove the property entirely with no change to your program: https://psalm.dev/r/73c6273338

**Comment by 0x450x6c** [comment]
It is not always possible to remove property with no change, for example, if property has a new annotation or default value.

https://psalm.dev/r/d212be8a86
