### ISSUE TITLE
Psalm 4.5 and later ignores assertions of instanceof Interface

### ISSUE THREAD

**Issue by ArtemGoutsoul** [vimeo/psalm#5236]
Here's an example:
https://psalm.dev/r/863377401f

This worked in 4.4.1

**Comment by weirdan** [comment]
It appears assert *removes* `HeaderInterface` in this case :open_mouth: : https://psalm.dev/r/50cf76d7eb

**Comment by ArtemGoutsoul** [comment]
@weirdan Should have tried the trace too, thanks for the example! :)

**Comment by muglug** [comment]
Simplified: https://psalm.dev/r/84f2bd0e92

**Comment by muglug** [comment]
Sorry, this is a pretty bad bug and should have been caught in a test
