### ISSUE TITLE
Unable to Suppress

### ISSUE THREAD

**Issue by XedinUnknown** [vimeo/psalm#5238]
In [this example][1], I am unable to suppress `PossiblyUndefinedVariable`.

[1]: https://psalm.dev/r/a400f57bea

**Comment by orklah** [comment]
This should works:
https://psalm.dev/r/111296bf97

**Comment by XedinUnknown** [comment]
So, I have to suppress this issue in the whole block? I cannot suppress a specific known occurrence? Beacause this way, there may be other possibly undefined variables in the block that would actually cause problems.

**Comment by weirdan** [comment]
Suppression is statement-wide. So you can suppress on e.g. `throw new` (https://psalm.dev/r/313ca8a248), but can't use suppression on individual arguments (as those are not statements but expressions). You can also extract the expressions into separate variables and use suppression on those (https://psalm.dev/r/6268b4f130).

**Comment by XedinUnknown** [comment]
I understand that it's statement-wide. And `print_r($newValue, true)` is a statement. If I include the suppression directive on the line immediately preceding this statement, it does not work. This is why I split that statement into multiple lines: just in case it needs to be somehow connected specifically to the variable, and not the statement. But neither work. Which is why I've opened this issue :)

**Comment by weirdan** [comment]
> And `print_r($newValue, true)` is a statement.

Actually it's not. See https://github.com/nikic/PHP-Parser/blob/master/grammar/php7.y#L241-L290

Statement would be an expression followed by semicolon (`expr semi` in the grammar file) - which obviously you can't do in the argument list.

**Comment by weirdan** [comment]
I don't think it's feasible to implement this.

**Comment by XedinUnknown** [comment]
> I don't think it's feasible to implement this.

That's fair enough. But it is a statement though, and the fact that suppressing it has no effect means that this check is broken, and it's very confusing. Maybe worth putting it in the docs?
