### ISSUE TITLE
Regression in psalm 4.5 - 4.6, invalid PossiblyUndefinedVariable error

### ISSUE THREAD

**Issue by ArtemGoutsoul** [vimeo/psalm#5241]
I could not reproduce the test case in psalm.dev yet.

But I added trace and I can see some weirdness:
```
	/**
	 * @return mixed
	 */
	public function actionAction()
	{
		$form_id = Nexus_Widget::getWidgetId($_POST);

		$form = $form_id ? Nexus_Widget::get($form_id) : false;

		if (!($form instanceof Nexus_Widget_Form)) {
			return $this->redirect(Nexus::getErrorRedirect('', true));
		}

		try {
			$form->process($_POST, $_FILES);
			$task = Nexus_Task::factory($form->task_name);
			$_SESSION['last_task_result'] = $task->run((array)$form->getValues());
		}
		catch (Nexus_Exception $e) {
			Nexus::$log->err($e);
			Nexus::addMessage(tt('Error processing your request! See the logs for more details') . ': ' . $e->getMessage());
		}

		$_SESSION['previous_log'] = Nexus::getLogString();

		/** @psalm-trace $redirect_url */
		$redirect_url = $form->redirect_url;
		/** @psalm-trace $redirect_url */
		return $this->redirect($redirect_url);
	}
```

$redirect_url clearly exists and it's clearly is defined AFTER the try block, not inside, but we get this kind of error.

```
INFO: Trace - nexus_app/controllers/TasksController.php:123:3 - $redirect_url: string (see https://psalm.dev/224)
		/** @psalm-trace $redirect_url */
		$redirect_url = $form->redirect_url;

INFO: Trace - nexus_app/controllers/TasksController.php:125:3 - $redirect_url: string (see https://psalm.dev/224)
		/** @psalm-trace $redirect_url */
		return $this->redirect($redirect_url);

ERROR: PossiblyUndefinedVariable - nexus_app/controllers/TasksController.php:125:26 - Possibly undefined variable $redirect_url defined in try block (see https://psalm.dev/018)
		return $this->redirect($redirect_url);
```

p.s. don't judge the legacy code pls, I'm gradually refactoring (with the help of phpstorm, psalm, phan and phpstan :) )

**Comment by orklah** [comment]
Can you try running psalm with --threads=1 and tell us if it disappears ? It looks a lot like https://github.com/vimeo/psalm/issues/4748

**Comment by ArtemGoutsoul** [comment]
@orklah Tried it with `--threads=1`, no change, got the same error

**Comment by weirdan** [comment]
Reproducer required.

**Comment by ArtemGoutsoul** [comment]
The issue is still reproducible exactly the same way with 4.6.2 with our code base. As you see the trace shows that Psalm knows that $redirect_url is string, at the same time it says "Possibly undefined variable"...

I tried reproduce it in psalm.dev, but didn't really manage, here's my attempt: https://psalm.dev/r/2b74bd98f8

**Comment by orklah** [comment]
@ArtemGoutsoul #4748 was very similar and was fixed. Can you check if you can reproduce in last master?

**Comment by orklah** [comment]
I'll close this, I'm afraid there isn't anything we can do without being able to reproduce...
