### ISSUE TITLE
[Plugin] add ability to have custom purity checkers.

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#5242]
currently, some php builtin functions are conditionally pure ( e.g: `count`, `array_map` ... etc ), psalm have a special case for these functions internally ( https://github.com/vimeo/psalm/blob/bd6efd7cf2b7e6fdf01b343be0c5bbb9aacdbbbb/src/Psalm/Internal/Codebase/Functions.php#L386 ), but it would be a great addition to allow plugins to do provide a class that would be able to check for purity as well based on arguments.

ref: https://github.com/azjezz/psl/issues/130

**Comment by muglug** [comment]
No, not happy to make it pluggable. I want to keep the notion of purity pretty simple.

**Comment by olleharstedt** [comment]
Bump for this discussion, seems like a reasonable request to enable a plugin for better effect types. Hacklang is already going that way, and multiple other languages as well.
