### ISSUE TITLE
Class constant wildcards don't work with subclasses and static::*

### ISSUE THREAD

**Issue by ntzm** [vimeo/psalm#5243]
As an example: https://psalm.dev/r/d9a8e8df8e

What I'm trying to say is, I want `$value` to be a valid constant value on subclasses of `Enum`, so I want it to behave like this: https://psalm.dev/r/56587aec53

I hope this makes sense

**Comment by weirdan** [comment]
I think it should expressed like this: https://psalm.dev/r/84ee52adcc
As you can see, it almost works, except there's a false-positive `InvalidTemplateParam`

**Comment by weirdan** [comment]
False-positive looks like a bug to me.

**Comment by orklah** [comment]
False positive was fixed
