### ISSUE TITLE
PossiblyNullReference in a condition

### ISSUE THREAD

**Issue by ricardomouraspl** [vimeo/psalm#5246]
Even when I check if a variable is null then PSALM throws the following errors:

```sh
ERROR: PossiblyNullReference - MyClass:113:39 - Cannot call method toString on possibly null value (see https://psalm.dev/083)
            $fileId = $log->fileId()->toString();


ERROR: PossiblyNullReference - MyClass:119:47 - Cannot call method toString on possibly null value (see https://psalm.dev/083)
            $resourceId = $log->resourceId()->toString();
```

[Live code](https://psalm.dev/r/324983972c)

**Comment by weirdan** [comment]
That's expected, as there's no guarantee that methods will always return the same value. Either extract that call and store the result into a variable or declare the method as mutation-free: https://psalm.dev/r/203f9b0b99
