### ISSUE TITLE
SimpleXMLElement::attributes() can be falsy

### ISSUE THREAD

**Issue by captain-igloo** [vimeo/psalm#5249]
SimpleXMLElement::attributes() returns SimpleXMLElement which is falsy if the element has no attributes.  Psalm incorrectly raises an error.

https://psalm.dev/r/13c7bf7def

**Comment by weirdan** [comment]
To my knowledge, Psalm currently does not consider any object to be falsy.

**Comment by fullbl** [comment]
Actually simplexml_* could return null (https://www.php.net/manual/en/simplexmlelement.attributes.php, it's wrong in description but good in return values), but psalm doesn't accept it!

https://psalm.dev/r/dcb40d5ec7

**Comment by orklah** [comment]
Note: the original issue has been fixed, this issue is left open for https://github.com/vimeo/psalm/issues/5249#issuecomment-792120759

**Comment by orklah** [comment]
This has been fixed
