### ISSUE TITLE
Is there any way to perform an inline type check?

### ISSUE THREAD

**Issue by egst** [vimeo/psalm#5254]
Sorry, if this is not the right place to post questions, but I haven't found anything else.

I was wondering whether there is any way to check the type of a variable or expression that is not a function parameter or a class property. For example:

```PHP
// Some function, that I cannot declare any more specifically:
function f (array $parrams): void {}

/** @psalm-type Data = array{foo: int, bar: string} */
class C {
    function __construct () {
        f(/** @check Data */ ['foo' => 1]); // Error: Missing the 'bar' key.
    }
}
```

The semantics of the potential `@check` construct would be similar to `@var`, but instead of ignoring the actual inferred type and replacing it with the provided one, it would emit an error on type mismatch.

What I currently do, is:

```PHP
class C {
    function __construct () {
        $this->f(['foo' => 1]); // Error: Missing the 'bar' key.
    }
    /** @param Data $params */
    function f (array $params): void { f($params); }
}
```

...which is OK, but very verbose. I also thought about this approach:

```PHP
class C {
    function __construct () {
        f($this->f = ['foo' => 1]); // Error: Missing the 'bar' key.
    }
    /** @var Data */
    private array $f;
}
```

...which is a little less verbose but might look very confusing and might also introduce some `PropertyNotSetInConstructor` errors.

To explain my specific use-case: The function `f` loads a view (MVC architecture) that relies on the data given as `$params` and I only want a simple check, that I am not forgetting to pass something to this view without some major refactoring and restructuring of an existing project, that uses this approach.

**Comment by orklah** [comment]
So, If I understood correctly, you'd like to assert statically that the type is correct.

I'm not sure if you already know but this kind of things is possible: https://psalm.dev/r/9db6980264

But it's more of a glorified @var with potential runtime checks than a static check.

I could see uses for that and it doesn't seem very far from current mechanics in Psalm

**Comment by egst** [comment]
That works, but it would require manually checking all the properties. I meant something more like:

```PHP
/** @psalm-type Data = array{foo: int, bar: string} */
class C {
    function __construct () {
        $arr = ['foo' => 1];
        /** @static-assert Data $arr */
        f($arr);
    }
}
```

...where `@static-assert` (or what I referred to previously as `@check`) would do the same thing as `assert(is_array($arr) && array_key_exists('foo', $arr') && array_key_exists('bar', $arr) && is_int($arr['foo']) && is_string($arr['bar']))` but statically.

BTW thanks for pointing out that `@psalm-trace` directive, that will be very useful for me. I always did this kind of thing by assigning to some typed class property and looking for the "wrong" type mentioned in a Psalm error.

**Comment by orklah** [comment]
yeah yeah, I got that. That's when I said I could see uses for a thing like that but it doesn't exists yet.

**Comment by weirdan** [comment]
There's `@psalm-check-type` now: https://psalm.dev/r/034ecf6530

One limitation is that it doesn't seem to support type aliases. Please open a separate issue for that.
