### ISSUE TITLE
Idea: Add a 'warning' level, in addition to 'error'/'info'

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#526]
Vaguely related to #521 

DiagnosticSeverity of the language server protocol has ERROR, WARNING, and INFORMATION (and HINT). This shows up in the UI of a language server client.

Additionally, some continuous integration tools have separate categories for error/warning/info (or notice == info) (e.g. jenkins violations plugin)

Minor issues (e.g. invalid phpdoc) can remain as 'info', other things which are possibly errors could be changed from error/info to 'warning'

- An 'error' would be undeclared classes/functions/methods.

For backwards compatibility, everything of a severity of at least 'warning' could cause a non-zero exit code.

A `<minimum-severity/>` xml setting could be added for users who wish to tune that. (default 'warning')

**Comment by muglug** [comment]
> For backwards compatibility, everything of a severity of at least 'warning' could cause a non-zero exit code.

I disagree? I don’t think warnings should contribute to non-zero exit codes. This would also be a useful feature for teams working to improve a codebase – you upgrade something from `info` to `warning`, PHP notice the problem areas in their files, allowing groups of people to tackle something without it breaking a build.

**Comment by mindplay-dk** [comment]
I also came here looking for a `warning` error-level.

> I don’t think warnings should contribute to non-zero exit codes. This would also be a useful feature for teams working to improve a codebase – you upgrade something from info to warning, PHP notice the problem areas in their files, allowing groups of people to tackle something without it breaking a build.

Exactly.

Here's a table to illustrate how `warning` would differ:

| Level    | Visible  | Breaks the build |
| -------- | -------- | ---------------- |
| suppress | Never    | No
| info     | Optional | No
| warning  | Always   | No
| error    | Always   | Always

Here's how I'd expect to use these error-levels in the config-file:

 * `suppress` for inspections we don't care about, at all.
 * `info` for inspections the developer can choose to see or not - really just "information" or "advice", things that aren't always values and might get too overwhelming or noisy if you're trying to focus on a task.
 * `warning` for inspections the developer *must* see - you can't disable these inspections with a command-line switch: if you're doing these things, you *must* be made aware that you're running a risk. ("You've been warned")
 * `error` for things that are definitely errors and should never be committed to a codebase, at all.

I think there is definitely a case for another error-level?

**Comment by mindplay-dk** [comment]
In addition, we might want a strict switch of some sort - you wouldn't use this on a CI server, but a developer might choose to treat warnings as errors during local development: keeping the number of warnings low helps others take warnings more seriously, which is less of a concern for `info` level inspections, which you can disable to keep the noise down when you need to focus.

**Comment by muglug** [comment]
Actually not going to do this – I think adding an extra layer is too complicated.
