### ISSUE TITLE
Unexpected: Cannot call method callB on possibly null value

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#5269]
Didnt expect the 

> Cannot call method callB on possibly null value

error on https://psalm.dev/r/524f122f20

**Comment by staabm** [comment]
Ohh I guess its a purity thing..

**Comment by weirdan** [comment]
> Didnt expect the Cannot call method callB on possibly null value

Why? It's fairly obvious that every call to `getB()` can return null, even if the previous did not.

**Comment by staabm** [comment]
You are right. My example was flawed while reducing.

https://psalm.dev/r/ef379f44c1

**Comment by orklah** [comment]
Psalm can't be sure that getB() return is consistent (your previous link was an example of that)

There's a setting [`memoizeMethodCallResults`](https://psalm.dev/docs/running_psalm/configuration/#memoizemethodcallresults) that allow you to change this behaviour and make Psalm understand that *every* consecutive call is consistent: https://psalm.dev/r/d1a73d45f6

Be warned that changing this setting will probably solve this case but create false positives elsewhere
