### ISSUE TITLE
Support igbinary for the caching of class-like storage 

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#527]
https://github.com/vimeo/psalm/blob/81fd0161207c7925ac0a76b2b9e62e129ba5b361/src/Psalm/Provider/ClassLikeStorageCacheProvider.php#L105

Related to https://github.com/vimeo/psalm/issues/193 

> Update: this doesn't have a massive effect on individual file analysis, because unserialising from cache can be somewhat slow. But it's vital for server mode.

- (In the latest igbinary release, serialize() is somewhat slower, but unserialize() should be faster)
- Reuse the `serializer="igbinary"` setting from psalm.xml?
- igbinary works as a substitute for serialize() - It supports __sleep(), __wakeup(), serializable interfaces, etc.

Also see https://github.com/vimeo/psalm/issues/484 (File name could depend on whether or not igbinary was used, making it easy to switch between php installations)

**Comment by muglug** [comment]
Thanks, this makes a ton of sense. I had disabled these cachers in master, but this allows me to re-enable them.
