### ISSUE TITLE
Support for taint analysis in LSP

### ISSUE THREAD

**Issue by joehoyle** [vimeo/psalm#5283]
I _think_ at the moment, taint analysis does not work via the LSP, however I think conceptually it would make sense to do that?

I tried adding `$project_analyzer->trackTaintedInputs();` to `psalm-language-server.php` that did work, but only for the initial analysis, file update don't cause the taint errors to change. I don't really know much about how taint analysis is implemented. Would this be difficult to get working in the LSP?

**Comment by muglug** [comment]
Nah, it's not possible to have it in language server mode due to how it finds routes between sinks and sources, and the amount of storage that requires.
