### ISSUE TITLE
Parameter types lost when assigning a anonymous function to a variable

### ISSUE THREAD

**Issue by neclimdul** [vimeo/psalm#5288]
Maybe I'm doing something wrong but I assumed the first version of this function documentation would work but it seems to loose the hinted property types.

https://psalm.dev/r/90b5f02025

From the variations including the hacky use of php's whitespace parsing the docblock seems to only be associate with the variable and not the assignment loosing all hinting.

**Comment by muglug** [comment]
Due to how elements are parsed the docblock has to be nearer the function definition: https://psalm.dev/r/8179a1edc6

**Comment by neclimdul** [comment]
:-D That was the second example.
