### ISSUE TITLE
User defined assertions works incorrectly for generic iterable types

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#5294]
Lets take a look at this https://psalm.dev/r/12ed2787e9
or this https://psalm.dev/r/a4ab076a44
example.

Works fine. As expected.

But if go deeper and try to assert generic type like `list<int>` then psalm lose types:

psalm-assert-if-true: https://psalm.dev/r/58dbc19d8a
psalm-assert: https://psalm.dev/r/4c25ed702c

**Comment by klimick** [comment]
Hmmmmm.

This example https://psalm.dev/r/205e1d64ea contains generic assertion too. But it is working.

It seems issue only with `iterable` type.

**Comment by weirdan** [comment]
Then it's possibly related to #5310

**Comment by klimick** [comment]
Seems a problem at this place:
https://github.com/vimeo/psalm/blob/110c9ef4e12c1247e7a87d51796e0a0b2fa26ef9/src/Psalm/Storage/Assertion.php#L63

`getKey` returns `list` instead of `list<T>`

Can we change it to `getId`? @weirdan
