### ISSUE TITLE
Add non-empty-list or even non-empty<T>

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5296]
_Currently I'm working on achieving 100% types on few projects and this need is still emerging again and again_

I'm returning lists here and there. However I have to find a compromise and choose whether I type `list<T>` or `non-empty-array<int, T>`

I'd like to express `non-empty-list`. I even tried `non-empty-array&list` but that's not supported and I'm not sure it would work anyway.

Expressing non-emptiness using types is definitely valuable but the way `list` says "there are no keys" is too.

Might be related to https://github.com/vimeo/psalm/issues/5277.

I wonder that `non-empty<list<T>>` might be universal and the best solution for all of it.

**Comment by muglug** [comment]
`non-empty-list` already exists!

**Comment by simPod** [comment]
Oh god wow
