### ISSUE TITLE
TypeDoesNotContainType - psalm still considers a property always null even if it may be set in called method

### ISSUE THREAD

**Issue by sad-spirit** [vimeo/psalm#5298]
Issue #5231 was closed, but only the "simplified" code example was actually fixed.

The code I posted originally still triggers the error with latest psalm:
https://psalm.dev/r/2afe4e3c4b

> ERROR: TypeDoesNotContainType - 26:23 - Type null for $this->pairFirst is always null
> ERROR: TypeDoesNotContainType - 40:13 - Type null for $this->pairFirst is always null

**Comment by muglug** [comment]
Sorry! Your example, simplified again: https://psalm.dev/r/3d9228342e
