### ISSUE TITLE
Idea: Make `psalm --init` read files and directories from "autoload" and "bin"

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#530]
(in composer.json)

This information (E.g. if "lib" is used, "src/MyProject", etc.) is usually available in projects that are configured to use the composer autoloader. User input can be avoided if directories can be inferred.

Something along these lines:

[For reading composer directories (need to add 'files' autoload setting)](https://github.com/phan/phan/blob/7287fd6f8182c79ca9e152b66e31a34bfb05ea45/src/Phan/ConfigInitializer.php#L359-L395)

[For guessing if a binary provided with the project is a php script that can be analyzed](
https://github.com/phan/phan/blob/7287fd6f8182c79ca9e152b66e31a34bfb05ea45/src/Phan/ConfigInitializer.php#L330-L334)

See https://getcomposer.org/doc/04-schema.md#autoload

There may already be other libraries or helper methods in composer itself that do a better job than this.
(Also, `""` (empty string) is a valid directory in composer.json, and the linked example doesn't check for that yet)
(Also, some applications use their own autoloaders, so an implementation should check for failures to read directory lists)

**Comment by muglug** [comment]
Was just thinking about doing this yesterday:

In `--init` Psalm looks for an `src` directory, and it would be trivial for Psalm to also scan that directory, figuring out a dependency tree and pre-caching objects that are likely to get used in analysis.

**Comment by muglug** [comment]
It reads from autoload now
