### ISSUE TITLE
Split if statements cause variables to trigger PossiblyUndefinedGlobalVariable

### ISSUE THREAD

**Issue by neclimdul** [vimeo/psalm#5301]
I have some code that needs to wrap some general code when an option is provided. Psalm sees the variables defined in the first block as possibly undefined in the second block even though they have to be defined if the second block runs.

https://psalm.dev/r/768dd97a05

**Comment by muglug** [comment]
Initialise the variable to `null` beforehand: https://psalm.dev/r/71d00bb1fb

In Psalm variables have to be determinably in scope. Psalm does not support conditional scopes.

**Comment by neclimdul** [comment]
@muglug Thanks for the fast response.  I think then not supporting conditional scopes seems to be the bug then. Your solution works for the simplified example I gave but is not a generalized solution for this problem. Just assigning it to null doesn't work if there is any sort of complexity int the two blocks.

For example, if the variable is simply a class everything breaks.
https://psalm.dev/r/1c16afef3d

Can we re-open this or open a feature request for conditional scope handling or something?
