### ISSUE TITLE
Annotation for terminating functions?

### ISSUE THREAD

**Issue by iamcal** [vimeo/psalm#5312]
I'm looking for something similar to hack's `noreturn` type: https://docs.hhvm.com/hack/built-in-types/noreturn

I have a nullable var, which if null (error condition) will call a function which itself is guaranteed to call `exit`. Any statements after that point can assume that the var is no longer null. The same would be true if the function always throws an exception.

https://psalm.dev/r/5f7f737e2a

**Comment by weirdan** [comment]
Use [`@return no-return`](https://psalm.dev/docs/annotating_code/type_syntax/atomic_types/#other): https://psalm.dev/r/15b1d8b500

**Comment by iamcal** [comment]
Thank you! The psalm.dev site search engine does not index terms with dashes in them, so it's a bit un-findable.
