### ISSUE TITLE
Problem inferring type when using generic types

### ISSUE THREAD

**Issue by morozov** [vimeo/psalm#5318]
See the code snippet: https://psalm.dev/r/49adfff55c.

There seems to be enough information for Psalm to understand that if the argument is of type `string`, then the function will return a string, which doesn't violate the method signature.

**Comment by weirdan** [comment]
That doesn't seem to be a bug. Psalm's type system has subtypes for string (unlike PHP's). Given the function definition Psalm expects the result of `trimIfString("  aa  ")` to be still `"  aa  "` (https://psalm.dev/r/e660eb3aa6) and your function clearly breaks that contract.

**Comment by morozov** [comment]
Thanks for the explanation, @weirdan. As far as I understand, the `T` in my case represents just an abstract type, not a PHP type. And if my function receives a `non-empty-string` (which is a type defined by Psalm), it won't return a `non-empty-string`. Makes sense.
