### ISSUE TITLE
"No files analyzed" instead of "Psalm was able to infer types for X% of the codebase" when cache is up-to-date

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#5319]
Running `vendor/bin/psalm` twice with cache enabled seems to cause the second run to just print `No files analyzed`, while the first  run prints `Psalm was able to infer types for X% of the codebase`.

Unfortunately, neither `--stats` nor `--no-reflection-cache` helps, only `--no-cache` does.

Is there another way to force the type coverage output **with** cache?

(Background: I'm using GitLab CI to capture the output and display the diff in merge requests and I noticed since about January 2021 that in some cases the difference couldn't be calculated, because the psalm job on `main` had just printed `No files analyzed`, especially after merging merge requests whose branches where up-to-date with `main`.)

**Comment by orklah** [comment]
Try --no-diff

**Comment by caugner** [comment]
Thanks @orklah, `--no-diff` did the trick!

**Comment by caugner** [comment]
@orklah I thought about it again and shouldn't running psalm without `--no-diff` still display the type coverage? After all, it could probably be cached.

**Comment by orklah** [comment]
I don't know if it is (it may be interesting to check with shepherd.dev if no-diff runs are counted). Do you mind explaining in details why you need to display coverage when running Psalm when no change has been done?

**Comment by caugner** [comment]
We're running Psalm as part of Continuous Integration. GitLab can extract coverage metrics from the CI output. By comparing the latest coverage metrics between the source and target branch of a MR/PR, it prominently displays the impact of changes towards (type) coverage:

![grafik](https://user-images.githubusercontent.com/495429/110031999-ebf04f00-7d37-11eb-8ac9-d16fb88ea0ba.png)

However, if the latest CI run of either the source or the target branch did not print the coverage metrics, this difference cannot be shown:

![grafik](https://user-images.githubusercontent.com/495429/110032048-fca0c500-7d37-11eb-8b81-d36ed9cb308e.png)

This happens especially on CI runs directly following a merge (if the CI run of the merged branch was the last CI job that ran) or if a commit does not change any PHP files (e.g. docs):

**Comment by orklah** [comment]
Mmmh, interesting, I didn't know Gitlab had such a feature.

After a very short test (more checks may be needed), it turns out the only thing preventing the coverage output is 
https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Codebase/Analyzer.php#L1256

I guess you could propose a PR when the "No file analyzed" is part of the standard output instead of replacing it.
