### ISSUE TITLE
Psalm cannot match `class-string<T<V>>` with `class-string<T<V1>>` when `V1 implements V`

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#5324]
I have a somewhat complex inheritance scenario with templated types:

```php
<?php

/** @psalm-template ExpectedResponse of Response */
interface Command {}
interface Response {}

/** @template-implements Command<CookiesEaten> */
class EatCookies implements Command {}
class CookiesEaten implements Response {}

class CommandMap
{
    /** @psalm-param array<class-string<Command>> $commands */
    public function __construct(array $commands) {
        throw new \Exception(\json_encode($commands)); // irrelevant
    }
}

return new CommandMap([EatCookies::class]);
```

The code above fails:

```
ERROR: InvalidArgument - 19:23 - Argument 1 of CommandMap::__construct expects array<array-key, class-string<Command<Response>>>, array{EatCookies::class} provided
```

https://psalm.dev/r/259be13bd2

If I change `/** @template-implements Command<CookiesEaten> */` to `/** @template-implements Command<Response> */`, then everything works as expected: https://psalm.dev/r/f6fc1ca022

It seems like `class-string<Command<T>>` cannot be reconciled with `class-string<Command<T1>>` when `T1` extends `T`.

**Comment by Ocramius** [comment]
Note: the above worked with `vimeo/psalm:4.4.1`, so it's potentially a regression.

**Comment by weirdan** [comment]
Shouldn't `ExpectedResponse` be declared covariant for that to be valid?

**Comment by Ocramius** [comment]
Hey @weirdan,

Is that a new addition/capability of templates? The `ExpectedReaponse` can
only be a `Response` already, so covariance is already implied...

**Comment by weirdan** [comment]
Bisect points to this commit: https://github.com/vimeo/psalm/commit/8b5e0fc754f8b29b21b1aa8b1ddc91e49062d428

**Comment by muglug** [comment]
Yeah that just exposed the bug, which I think already existed in this more explicit version:

https://psalm.dev/r/a5cf03f725

**Comment by muglug** [comment]
Actually per @weirdan this is not a bug.

Removing the class strings and adding explicit generics makes it more obvious: https://psalm.dev/r/e04f843c69

Make the template covariant to allow it

**Comment by muglug** [comment]
Here's how variance could be violated (in a slight change to your example): https://psalm.dev/r/7d9b956a01

**Comment by Ocramius** [comment]
Right, variance could be violated when performing writes (since subtype is contravariant when templated in parameters), but I'm using it as a return type of my methods.

For example, this is valid.

```php
/** @template T of Response */
class MyCommand
{
    /** @psalm-return T */
    function execute(): Response; // <- this is where the specific templated type would be used
}
```

Wouldn't that be a valid use-case, since `MyCommand` is covariant when concretized?

From discussion above, what I infer is that following is invalid instead:

```php
/** @template T of Request */
class MyCommand
{
    /** @psalm-param T $input */
    function execute(Request $input): void; // <- here we are expecting something too precise
}
```

In the last example, we are being contravariant, hence why I understand this should already be invalid.

Is this a case where `@template-covariant` would help?

**Comment by weirdan** [comment]
Yes, and it would mark covariant type used in contravariant position as invalid: https://psalm.dev/r/8054343f98
