### ISSUE TITLE
Psalm seems to assume that subsequent calls to a method return the same value in a final class with property memoisation

### ISSUE THREAD

**Issue by morozov** [vimeo/psalm#5325]
https://psalm.dev/r/59477194c3
https://3v4l.org/JDhkU

Judging by the error messages (false does not contain true; types for $mode->isautocommitenabled()), it looks like Psalm uses the assertion made against the first return value (`false`) to narrow down the type of the second return value (`bool&false=false`) although they are independent (the method isn't pure).

Also, the `DocblockTypeContradiction` issue type may be misleading since the code sample doesn't contain a single docblock.

**Comment by muglug** [comment]
Note: using a property does not show the same bug: https://psalm.dev/r/5134acfe28

**Comment by weirdan** [comment]
This seems to be caused by simple getter memoization, as making the the getter non-trivial gets rid of the error: https://psalm.dev/r/69a40b1221
