### ISSUE TITLE
Out of memory on switch with lots of cases

### ISSUE THREAD

**Issue by dbrekelmans** [vimeo/psalm#5327]
**Description**
If you have a switch statement with a lot of cases, psalm runs out of memory.

**How to reproduce**
The following example runs out of memory. Remove a few cases from the switch statement and it will run normally:

https://psalm.dev/r/3313c3f953

**Comment by umulmrum** [comment]
I have a similar case with a huge if statement, maybe it's related:

<pre>
if (($id1 === 565 && $id2 === 7885)
        || ($id1 === 605 && $id2 === 6738)
        || ($id1 === 757 && $id2 === 7881)
        || ($id1 === 765 && ($id2 === 7954 || $id2 === 489))
        || ($id1 === 279 && $id3 === 65190)
        || ($id1 === 194 && $id2 === 3219)
        || ($id1 === 229 && $id2 === 1947)
        || ($id1 === 221 && $id2 === 2072)
        || ($id1 === 3745 && $id2 === 62749)
        || ($id1 === 5079 && $id2 === 66995)
        || ($id1 === 4613 && $id2 === 62204)
        || ($id1 === 5214 && $id2 === 69596)
        || ($id1 === 5101 && $id2 === 67459)
        || ($id1 === 3287 && $id2 === 39337)
        || ($id1 === 3287 && $id2 === 73753)
        || ($id1 === 5381 && $id2 === 75021)
        || ($id1 === 829 && $id2 === 8500)
        || ($id1 === 4549 && $id2 === 58014)
        || ($id1 === 6926 && $id2 === 2938)
        || ($id1 === 5945 && $id2 === 82261)
        || ($id1 === 6399 && $id2 === 91853)
        || ($id1 === 7071 && $id2 === 5718)
        || ($id1 === 349 && $id2 === 74)
        || ($id1 === 6012 && $id2 === 83522)
        || ($id1 === 7044 && $id2 === 6863)
        || ($id1 === 6926 && $id2 === 2938)
        || ($id1 === 3745 && $id2 === 1428)
        || ($id1 === 7563 && $id2 === 19806)
        || ($id1 === 7719 && $id2 === 23775)
        || ($id1 === 7719 && $id2 === 25989)
        || ($id1 === 8357 && $id2 === 33829)
        || ($id1 === 8311 && $id2 === 32698)
        || ($id1 === 7778 && \in_array($id2, [35162, 65098, 29298, 64752, 2664, 2662]))
        || ($id1 === 4292 && $id2 === 7841)
        || ($id1 === 63 && $id2 === 80)
        || ($id1 === 6848 && $id2 === 5456)
        || ($id1 === 7642 && $id2 === 38525)
        || ($id1 === 507 && $id2 === 1929)
        || ($id1 === 8667 && $id2 === 41001)
        || ($id1 === 7942 && $id2 === 26167)
        || ($id1 === 8504 && $id2 === 37117)
        || ($id1 === 8797 && $id2 === 44203)
        || ($id1 === 8234 && $id2 === 54093)
        || \in_array($id1, [729, 427, 432, 279, 382, 83, 536, 676, 691, 692, 547, 841, 932, 2865, 2401, 3025, 1764])
    ) {
        // do things
    }
</pre>

Yes that's a bit awkward but it's legacy code I can't really change for now (also changed a few details as it is not public code). With this block included an OOM occurs when running Psalm on a code base of ~500k LOC, but will complete if commented out.

Any help with that is appreciated, thanks :-)

**Comment by umulmrum** [comment]
@muglug Thank you for working on this issue. Unfortunately the problem isn't solved for me even with the current release 4.7.3 (it still works when removing the large conditional, as before). Would you be so kind to have another look? I'm very unfamiliar with Psalm code, so am unsure on how to help.
