### ISSUE TITLE
Erroneous UndefinedMethod

### ISSUE THREAD

**Issue by WDD-Marv** [vimeo/psalm#533]
> UndefinedMethod - Method DOMDocumentFragment::getelementsbytagname does not exist
               ($nodes = $frag->getElementsByTagName($nodeToRemove)) &&

This'll likely be another one of those shortcomings in reflection from php-src.

**Comment by muglug** [comment]
Is it supposed to exist? Would you mind giving example code?

PHP doesn't think it exists:

```php
$doc = new DOMDocument();
$fragment = $doc->createDocumentFragment();
$fragment->appendChild($doc->createElement('foo'));
$elements = $fragment->getElementsByTagName('foo');
// Fatal error: Uncaught Error: Call to undefined method DOMDocumentFragment::getElementsByTagName()
```

**Comment by WDD-Marv** [comment]
apologies @muglug, it turns out the pertinent bit of code is no longer being used in the project.

**Comment by muglug** [comment]
no problem!
