### ISSUE TITLE
How to handle dynamic includes?

### ISSUE THREAD

**Issue by mortenson** [vimeo/psalm#5336]
Hi there - I'm adding psalm support for Drupal and am wondering how to best handle dynamic includes.

Specifically, in Drupal ".module", ".theme", and ".profile" files are treated as PHP, but these files are never explicitly `require`d, so psalm doesn't know about them. I don't want to add them to `projectFiles` because I don't want scan results for their defined functions, I want to include them in the same way a `require` would include them.

I've found a weird way to do this, byadding them all as stubs in my custom psalm plugin, this works OK. Is there a better way to handle dynamically included files?

Thanks for the work on this!

**Comment by mortenson** [comment]
@psalm-github-bot Since this requires multiple files in different directories, no.

**Comment by weirdan** [comment]
As it stands, it's a little thin on details. Since you're adding those files as stubs, you probably want to make some symbols defined there to be available (where?). Have you tried adding them to [`<extraFiles>`](https://psalm.dev/docs/running_psalm/configuration/#extrafiles)?

**Comment by mortenson** [comment]
Ah! `extraFiles` looks like what I need. Sorry for the light details, I could have ignored Drupal and provided a more direct test case. Thanks for the tip.
