### ISSUE TITLE
UX: improve baseline format

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#5341]
The current baseline format (taint and regular errros) are not easily human readable.

its hard to reason about which lines in the actual source related to which error in the baseline.

its also hard to make sense of when/why some changes add/remove occurences within a existing baseline 

In contrast: a phpstan baseline makes it very explicit which errors actually are contained and therefor allow more easily to relate the baseline with the actual code

**Comment by orklah** [comment]
I'm not sure exactly what you're suggestiong. Can you be more explicit?

**Comment by orklah** [comment]
I understood the issue but I'm not sure how you suggest fixing it. What exactly in phpstan's baseline would help you in this case?

**Comment by staabm** [comment]
example 2:

In a regular psalm baseline (taint disabled) a baseline looks like
https://github.com/redaxo/redaxo/blob/c67ccafdf651baf39cf7edef746711eb6646df8b/.tools/psalm/baseline.xml

just by reading the baseline (like a todo list for things to fix)  its pretty hard to identify which lines in the referenced file will fix the baseline errors.

in contrast, phpstan gives more context which helps to fix the underlying problems, see e.g.
https://github.com/redaxo/redaxo/blob/c67ccafdf651baf39cf7edef746711eb6646df8b/.tools/phpstan/baseline.neon

**Comment by orklah** [comment]
So both contains a number of occurences, both contains the path, so I assume the difference is that the message doesn't appear in psalm baseline?

Would that help?

Note that the fundamental difference between the two is that PHPStan rely on the error message to disable issues whereas Psalm use the name of the issue and the flagged code piece.

**Comment by staabm** [comment]
> so I assume the difference is that the message doesn't appear in psalm baseline?

i think so. At least for the regular baseline this would work.

the tainted baseline seems to be even harder to cope with, because its a pretty long was from reading the taint-error to the actual method, which in our case most of the time is missing a `@taint-specialize` tag

**Comment by orklah** [comment]
I'm gonna close this as answered. I don't feel adding the message in the baseline is a good idea. Baselines are sometimes enormous and it would make them bigger yet. Also, the current baseline currently regroup similar errors with an errorCount. If we wanted to add the message, this couldn't be done anymore.

There is multiple ways to output the errors from Psalm, the baseline should not become one of them
