### ISSUE TITLE
Psalm thinks explode() can return false

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5347]
I have enabled `ignoreInternalFunctionFalseReturn="false"`

(I cannot do it in playground) https://psalm.dev/r/96ef362b30

`explode()` returns false when value is empty string.

I asserted the value is not empty string but psalm still reports it can return false

> Cannot iterate over falsable var false|non-empty-list<string>

**Comment by weirdan** [comment]
> `explode()` returns false when value is empty string.

Actually it returns false when *separator* is empty.
Reproduced in https://psalm.dev/r/6b3a3e88a6

**Comment by simPod** [comment]
Ah, u're right. I had delimiter in constant as `const D = ',';`. My brain somehow ruled it out and rather focused on exploded value.
