### ISSUE TITLE
UnusedPsalmSuppress reported in vendor dir

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#5356]
I have the following `psalm.xml` config file:

```xml
<?xml version="1.0"?>
...
    <projectFiles>
        <directory name="lib" />
        <directory name="src" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
</psalm>
```

On first run, the `vendor/bin/psalm --find-unused-psalm-suppress` command returns the following error:

```
ERROR: UnusedPsalmSuppress - vendor/myclabs/php-enum/src/Enum.php:65:33 - This suppression is never used (see https://psalm.dev/207)
            /** @psalm-suppress InvalidCast */
```

I cannot reproduce it on second run. Is this a bug?

**Comment by muglug** [comment]
> I cannot reproduce it on second run. Is this a bug?

Yes, anything that changes dependent on caching is a bug

This is a bit of an edge-case, but still a bug

**Comment by orklah** [comment]
@BenMorel would you mind creating a small repo that replicate this issue?

**Comment by BenMorel** [comment]
@orklah I haven't seen the bug in a while, let's consider it fixed. I'll come back if it appears again!

**Comment by simPod** [comment]
@orklah I've managed to reproduce it here https://github.com/simPod/PsalmBugs/pull/1
