### ISSUE TITLE
PHP8: ReflectionType::getName reported as false positive

### ISSUE THREAD

**Issue by eithed** [vimeo/psalm#5358]
https://psalm.dev/r/afc3a59a14

PHP docs state that `ReflectionProperty::getType` returns `ReflectionType|null`,  with `ReflectionType` not having `getName` method. As such, one would say that current Psalm behaviour is correct.

However the behaviour in question is dependant upon the type of the property as showcased in example. If property is of one type, instance of `ReflectionNamedType` is returned, which implements `getName`. If property is of multiple types, as per PHP8, instance of `ReflectionUnionType` is returned, which doesn't implement `getName`. Both of these extend `ReflectionType`, so one would say that PHP docs behaviour is correct as well.

I don't know if it's possible to deduce in Psalm what kind of `ReflectionType` will be actually returned by `getType` method and if that class will actually support `getName`, or is it actually an issue that should be solved on Psalm end.

**Comment by weirdan** [comment]
This can be solved with custom return type provider, if you really want to. Of course it could only be done when the property name is known. To me it seems it's much more common to loop over all properties, in which case you really should check the type returned by `getType()`.

**Comment by eithed** [comment]
I agree - in the end I've resorted to explicitly checking type of `getType()` against `ReflectionNamedType` and throwing exceptions in other cases (as developer could define that the type of property is an union or untyped). Thank you for looking into this.
