### ISSUE TITLE
Possibly NULL value provided with getter which has been checked

### ISSUE THREAD

**Issue by sidz** [vimeo/psalm#5365]
Hi guys.

Is it possible to teach or fix Psalm to understand that I did a check on possible null getter? except the case when result is assigned to some variable.

here is an example: https://psalm.dev/r/74878f68ed

**Comment by orklah** [comment]
There is a setting "Memoize simple method calls" on psalm.dev that you can use for that sort of thing:
https://psalm.dev/r/6e170c0974

You can also declare your class as immutable, Psalm will know the function return is consistent but you'll have additional constraints with what you can do in the class:
https://psalm.dev/r/22f28f3510
