### ISSUE TITLE
Typed collection template invariance issue.

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#5368]
I have an abstract collection and an abstract item, with the intention being that `FooCollection` holds `Foo`, `BarCollection` holds `Bar`, etc. I then have a collection of such collections.

https://psalm.dev/r/161165882c

This results in `Argument 1 of Collection::add expects ItemCollection<Item>, FooCollection provided`.
If you change line 12 to not require `of Item` it works fine.

https://psalm.dev/r/bc792f7e51

It looks like the issue is that psalm treats `ItemCollection`'s `TItem of Item` as an invariant when using `Collection<ItemCollection>`. I expect that with the template not specified, it's treating it as `Collection<ItemCollection<Item>>` due to the `of Item` constraint. If written explicitly that way I can see that the `Item` type is an invariant and the `InvalidArgument` error is correct, but I want to allow multiple different subtypes of `Item` which are invariants for the individual `ItemCollection`s.

I'm open to the idea that unspecified templates that have constraints should be treated as invariant by default, but I at least need some way to indicate to psalm that that's not the case here (and maybe it already exists and I've overlooked it). Ideally, psalm would show no issues with my current code, but would show an error for `$test[0]->add(new Foo())`, since it wouldn't know if `$test[0]` is a `FooCollection` or a `BarCollection` (ie have a separate `TItem` invariant for each `ItemCollection` in the `Collection`, rather than having a single `Item` invariant for all `ItemCollection`s).

**Comment by AndrolGenhald** [comment]
Of course I figured it out right after posting the issue... After reading through #1670 I tried using `extends` instead of `of`, and it works!

https://psalm.dev/r/911bfd12d8

Could `@template T extends Type` be documented in the [Template constraints](https://psalm.dev/docs/annotating_code/templated_annotations/#template-constraints) section, and how exactly it differs from `@template T of Type`?

**Comment by weirdan** [comment]
> Could `@template T extends Type` be documented 

It's not a syntax Psalm understands so it just ignored `extends` and everything that followed, effectively turning the constraint into `of mixed`, which also would work: https://psalm.dev/r/d175e663a1

**Comment by AndrolGenhald** [comment]
Ah, I see. I didn't test well enough, that means it's not going to understand that `TItem` is an `Item` for the rest of the class implementation.

**Comment by weirdan** [comment]
The way you structure it it calls for covariant template, but you won't be able to use it in contravariant positions (e.g. method params). It probably cannot be made type-safe the way it is now.

**Comment by muglug** [comment]
It took me a while to find how this example could blow up, but here's your same example in a comparable language with reified generics (Hack):

```hack
class CustomCollection<reify T> {
    public function add(T $t, Item $item): void {
        if ($t is ItemCollection<Item>) {
            $t->add($item, null);
        }
    }
}

abstract class ItemCollection<reify TItem as Item> extends CustomCollection<TItem> {
    public function add(TItem $t, ?Item $item): void {
    }
}

abstract class Item {}

class Foo extends Item {}
class Bar extends Item {}

class FooCollection extends ItemCollection<Foo> {}

function foo() : void {
    $test = new CustomCollection<ItemCollection<Item>>();

    $foo_collection = new FooCollection();

    $test->add($foo_collection, new Bar());
}
```

It's provably unsound, basically.

**Comment by muglug** [comment]
Feel free to ignore Psalm's error if you think your code is safe!

**Comment by AndrolGenhald** [comment]
Thanks for the example!
