### ISSUE TITLE
Misleading documentation of `--init`

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#537]
An actual example is `vendor/bin/psalm --init script 1`

There's no `--level` flag. `[level=3]` would be clearer. Including the value of the level in the error message would make it clearer that `level=` shouldn't be part of the CLI invocation. (Or mentioning an example invocation)

- Another possible approach would be to a `--level`/`--init-level` flag? If more flags for init get added, providing an un-named list would get unwieldly.
- As an example, a user might want to provide multiple source directories?

The current help text:

```
    -i, --init [source_dir=src] [--level=3]
        Create a psalm config file in the current directory that points to [source_dir]
        at the required level, from 1, most strict, to 6, most permissive
```

**Comment by muglug** [comment]
Thanks!
