### ISSUE TITLE
False positive NonInvariantDocblockPropertyType with template.

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#5371]
I have an abstract `ItemCollection` that can hold abstract `Item`s, and a concrete `FooCollection` that holds concrete `Foo` items. When I redeclare the `$items` property in `FooCollection` it gives a `NonInvariantDocblockPropertyType` false positive even though it's using `Foo` for the template.

https://psalm.dev/r/d84346cfe5

**Comment by AndrolGenhald** [comment]
Fixed a template syntax error, issue persists. https://psalm.dev/r/5063097d3b

**Comment by weirdan** [comment]
Why would you need to redefine property at all? Psalm knows it's a `list<Foo>` already: https://psalm.dev/r/c13bb4fa11

**Comment by AndrolGenhald** [comment]
Well I suppose that's fine. I had it for consistency with the rest of the class's properties having `@var` annotations, but if that's the official solution, is there or should there be something like `@psalm-var-inferred` to tell psalm to infer the type while leaving the `@var` annotation for non-psalm users? I haven't found the time to dig into psalm's code yet, so I don't know the complexity of fixing it, but as a user it seems like it'd be preferable for it to "just work".

**Comment by weirdan** [comment]
From Psalm's type system perspective supporting this would actually be sound, and it already seems to be supported for other types: https://psalm.dev/r/8fa0853348. PHP does not allow it for native types (e.g. https://3v4l.org/9cWYX), but PHP doesn't have generics yet. This is similar to what we had before PHP supported covariant returns - people would put parent return type as native return type and specify descendant type via `@return` doblock tag.

**Comment by AndrolGenhald** [comment]
Should probably also fix this false negative with templates: https://psalm.dev/r/40bd875b72
