### ISSUE TITLE
(Possibly)UnusedProperty false negative

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#5377]
https://psalm.dev/r/5d3132643b

Psalm could recognize that, since this property is only ever written to, it is unused. This doesn't seem to work with constructor property promotion either.

https://psalm.dev/r/62555410ce

**Comment by weirdan** [comment]
It does work if you enable checks for unused classes/methods and actually use the class: https://psalm.dev/r/db59050771, https://psalm.dev/r/d9d2d10b93

**Comment by iluuu1994** [comment]
@weirdan Oh I see. Well, both classes are services so their never instantiated explicitly which is likely why this is never triggered.

**Comment by weirdan** [comment]
Use is not necessarily an instantiation. Just referencing the class somewhere (e.g. parameter or return type, class name access) should be enough. Of course that code should be used somewhere as well.

**Comment by iluuu1994** [comment]
@weirdan Not necessarily. Lots of services are used exclusively from other services or controllers, which in turn are called from the framework itself. https://psalm.dev/r/d79f9e295d

**Comment by muglug** [comment]
The unused property check appears when unused class/method detection is turned on: https://psalm.dev/r/d9d2d10b93

**Comment by muglug** [comment]
The unused class & unused method checks are seen as more important than the unused property ones. It's assumed that if you're ignoring those, you also want to ignore unused property & method checks on that particular class.

**Comment by iluuu1994** [comment]
> The unused class & unused method checks are seen as more important than the unused property ones.

Problem is, services are often seen as unused because they're instantiated by the DI framework. So I'm usually suppressing the `UnusedClass` error for service classes.
