### ISSUE TITLE
Psalm complains when passing an array with extra properties

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#5379]
Repro: https://psalm.dev/r/440c1cd447

```php
/**
 * @psalm-template K
 * @psalm-template V
 */
class Collection {}

/**
 * @psalm-param Collection<int, array{code: string}> $items
 */
function test(Collection $items): void {}

/** @var Collection<int, array{code: string, value: string}> $value */
test($value);
```

Result:

> ERROR: InvalidArgument - 17:6 - Argument 1 of test expects Collection<int, array{code: string}>, Collection<int, array{code: string, value: string}> provided

If I change `Collection` for an `array`, it works fine: https://psalm.dev/r/0ae6a8d4a3

**Comment by weirdan** [comment]
Generics are invariant, so you cannot pass Collection of a subtype where Collection of a supertype is expected. You would have to mark corresponding type parameter covariant for that to work: https://psalm.dev/r/015291e4ca

**Comment by BenMorel** [comment]
Thanks for the pointer! I don't understand why generics are not covariant by default, though: what's a use case when covariance would *not* be desirable?

**Comment by weirdan** [comment]
Because of this: https://github.com/vimeo/psalm/issues/1603

**Comment by weirdan** [comment]
The same example is also discussed in the docs: https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance

**Comment by BenMorel** [comment]
Thank you, I understand the issue now. But can't the covariance / contravariance be inferred from the use case though: when it's used as a parameter or as a return type?

Why does it works with plain arrays?

**Comment by weirdan** [comment]
Array that you receive as a parameter is copied once you change it. It does not affect the array that was passed.
