### ISSUE TITLE
Better support for `static<T>`

### ISSUE THREAD

**Issue by gharlan** [vimeo/psalm#5383]
https://psalm.dev/r/b9d50b9872

It would be nice if psalm could fail here, because `static<bool>` does not match `C2 extends C1<string>`.
(But I don't know how difficult that would be to implement.)

**Comment by muglug** [comment]
No idea how to solve this offhand.

**Comment by weirdan** [comment]
If static method had access to containing class type parameters we could probably require `$value` to have `TFrom&T` type or flag `new static($value)` call.

**Comment by muglug** [comment]
Yeah, thinking about it more we probably need to prohibit `new static` inside any templated class. Should be a simple fix.

**Comment by gharlan** [comment]
> Yeah, thinking about it more we probably need to prohibit `new static` inside any templated class.

Hmm, I think using `new static` is a common pattern, [e.g. in myclabs/php-enum](https://github.com/myclabs/php-enum/blob/af4b5622434b2e129c28fab6d1a5bab436070e88/src/Enum.php#L301).
I know that `new static` is problematic because of child constructor params, but for this we already have `UnsafeInstantiation`. I'm not sure if `new static` should really be prohibited in all templated classes.

> If static method had access to containing class type parameters

This would be cool, then I would write it like this: https://psalm.dev/r/f42ebc781f
It would also help here: https://github.com/myclabs/php-enum/pull/143

But I think I understand why template variables are coupled to instances only.
Theoretically, it could maybe be possible to enforce the base constraints of the template variables in static methods? I'm not sure.
But when calling the static method on a subclass, the overwritten constraint for the template variable should be used.

**Comment by muglug** [comment]
> Hmm, I think using new static is a common pattern

Yeah, people currently do it, but it's still unsound (as you demonstrate)

There's a fundamental difference between `C1&static` and `C2` whenever `C2` extends with a parameter either explicitly or implicitly, and that's underlying problem.

The alternative would be to force `C2` to implement its own version of `from`: https://psalm.dev/r/f4989147d8, but this would be more noisy (creating an issue for every class extending the base one).

**Comment by muglug** [comment]
I don't think it's too burdensome to tell the maintainer of `myclabs/php-enum` that the code is _theoretically_ unsound, even if it's practically safe.
