### ISSUE TITLE
Templated return type from callable is not properly inferred when used in union type

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#5384]
When using a templated callback within a union type like in the example given below, the return type is not properly inferred.

https://psalm.dev/r/a932ac6a4b

**Comment by muglug** [comment]
the `is_callable` only checks that `$value` is a `callable`, not that it's a `callable(int):TValue`. This can lead to unsound behaviour e.g. https://psalm.dev/r/2c0726d520

**Comment by boesing** [comment]
Whoot? But the phpdoc provides the Details that only a callable with that return type is allowed.

For nullables this works perfectly... having nullable string in phpdoc without native typehint and using `!is_null` also only ensures it is not null. Could be any other type unless checking for string explicitly.

But callables are special here 😔

**Comment by weirdan** [comment]
> Whoot? But the phpdoc provides the Details that only a callable with that return type is allowed.

No, not really. Docblock effectively says that param type is `mixed|callable(int):mixed`. Any callable that does not match the right side of that union would still match the left one.
