### ISSUE TITLE
Templated parameter type not working when inherited

### ISSUE THREAD

**Issue by jasverix** [vimeo/psalm#5385]
See this: https://psalm.dev/r/c3f34adaec

TaskNode is clearly a BaseNode<Task>, but it does not pass the parameter check for some reason. This is causing a lot of problems in our code-base, and I had to disable InvalidArgument and PossiblyInvalidArgument for now.

**Comment by weirdan** [comment]
Templates are invariant, so you cannot pass `BaseNode<Task>` where `BaseNode<BaseModel>` is required. See https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance
