### ISSUE TITLE
Custom atomic scalar types

### ISSUE THREAD

**Issue by SerafimArts** [vimeo/psalm#5394]
I'm trying to write a plugin that provides extended typing for unmanaged (FFI) code.

To do this, I would like to provide several additional scalar types, which were a PHP representation of CData values, in particular: `int8`, `uint8`, `int16`, `uint16`, `int32`, `uint32`, `int32`, `uint32`, `char`, `float32`, `float64`, `float80`, etc...

However, I ran into the problem of missing documentation on registering custom global scalar types. Can you please provide a short example of the plugin hook with registration of an arbitrary type and its constraint?

I tried type injection, like this, however it doesn't work:
```php
use Psalm\Plugin\Hook\BeforeFileAnalysisInterface;

class CTypesHook implements BeforeFileAnalysisInterface
{
    public static function beforeAnalyzeFile(
        StatementsSource $statements_source,
        Context $file_context,
        FileStorage $file_storage,
        Codebase $codebase
    ): void {
        $file_storage->type_aliases['uint32'] = new ClassTypeAlias([
            new Type\Atomic\TInt(),
        ]);
    }
}
```

Testing:

```php
namespace Path\To;

class Example
{
    /** @var uint32 */
    public int $example = 0;
}

// Errors:
//  > uint32 is not a valid type
//  > Docblock-defined class or interface Path\To\Example\uint32 does not exist
//  > Parameter  Path\To\Example::$example has wrong type
//  > $this->example with declared type 'Path\To\Example\uint32' cannot be assigned type '0'
```

**Comment by orklah** [comment]
IIRC, we discussed this once or twice here and the set of types is not easily extensible.
- To my knowledge, there is no way to extends the parser to make it read a new type
- If you extends a type, you'll probably have no choice to make it extends from an existing type and it will behave exactly like its parent type. This means you'll have no way to say an int16 can't fit into an int8

**Comment by SerafimArts** [comment]
> To my knowledge, there is no way to extends the parser to make it read a new type

The list of types, as far as I understand, is now hardcoded into the `Atomic::create`.

> If you extends a type, you'll probably have no choice to make it extends from an existing type and it will behave exactly like its parent type. This means you'll have no way to say an int16 can't fit into an int8

Hmmm... Isn't this simple inheritance?

**Comment by orklah** [comment]
> Hmmm... Isn't this simple inheritance?

Well, if every uint/int you create extends `TInt` then every new type will be compatible with each other (or none of them will if Psalm were to ignore inheritance and check only class name)

**Comment by SerafimArts** [comment]
I think that the usual typealias to php int is enough for a start =)

**Comment by orklah** [comment]
But then, what is the point to adding new types in the first place? If it's just for documentation, maybe  [@psalm-type](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-type) would be enough to make an alias?

**Comment by orklah** [comment]
Closing as stale
