### ISSUE TITLE
@psalm-yield not documented

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5397]
I have stumbled over `@psalm-yield` in 3rd party code. There's no mention of it in docs though I have found some traces in source code in this repo.

Edit: just found this, o'lol https://github.com/vimeo/psalm/blob/fc29d268797b1493018cd5f4e47781411d54f6ea/tests/DocumentationTest.php#L60-L74 🙃

**Comment by orklah** [comment]
Is it bad that I have no idea what the majority of those does either? :D
