### ISSUE TITLE
Wrong version when using PHAR distribution

### ISSUE THREAD

**Issue by julpar** [vimeo/psalm#5399]
While using phar distribution generic dev branch is displayed as version number.

```
root@81907ae44f79:/var/www# psalm -v
Psalm 4.x-dev@
```

Same for baseline generation:
```
root@81907ae44f79:/var/www# grep psalm-version psalm-baseline.xml 
<files psalm-version="4.x-dev@">
```

p.s: bring this topic here from an issue in repo psalm/phar bc it seems that repo is not where the discussion takes place, right? (https://github.com/psalm/phar/issues/7)

**Comment by llaville** [comment]
It's very difficult to know in this condition if we have the latest version or not !

**Comment by llaville** [comment]
Another case where version is displayed as a pattern is in SARIF report (used psalm 4.12.0) : 
```
{
    "version": "2.1.0",
    "$schema": "https:\/\/json.schemastore.org\/sarif-2.1.0.json",
    "runs": [
        {
            "tool": {
                "driver": {
                    "name": "Psalm",
                    "informationUri": "https:\/\/psalm.dev",
                    "version": "4.x-dev@"
                }
            },
            "results": []
        }
    ]
}
```

**Comment by villfa** [comment]
I have the same issue than OP. After digging a bit I think it's related to this: https://github.com/box-project/box/issues/460
