### ISSUE TITLE
BC break in 4.6.3

### ISSUE THREAD

**Issue by adamturcsan** [vimeo/psalm#5405]
A BC Break has been introduced in a patch version.

https://github.com/vimeo/psalm/commit/205fdd197e914a5377053f9378a7112236a83b50#diff-58b56f2d1a81b22decaddcb6bce7b755662ebf12b8e17e20fd60dc5809787c99

Plugins relying on IssueBuffer::finish are now failing.
https://github.com/Roave/you-are-using-it-wrong/issues/114

**Comment by adamturcsan** [comment]
> Hey @adamturcsan, can you reproduce the issue on https://psalm.dev ?

It's not a user facing issue, so no, I cannot.

**Comment by weirdan** [comment]
Would tagging a new patch version without this change resolve your issue?
