### ISSUE TITLE
TypeDoesNotContainType - list<Foo> does not contain iterable<mixed, ExpectedType:fn-assert::allisinstanceof as Foo>

### ISSUE THREAD

**Issue by bendavies** [vimeo/psalm#5406]
Hi,

The following previously worked on 4.6.1. It seems psalm doesn't now like mixing the `list` and `iterable` types.
Is this now valid error?

https://psalm.dev/r/b8e4a1af20

Thanks

**Comment by weirdan** [comment]
Should be reported as `RedundantConditionGivenDocblockType`

**Comment by bendavies** [comment]
thanks @muglug !

**Comment by bendavies** [comment]
hey @muglug , this still errors using `list<Foo>`, while you used `array<Foo>` in your test case

**Comment by weirdan** [comment]
`listundefinedFooundefined` (https://psalm.dev/r/b8e4a1af20) looks totally broken

**Comment by weirdan** [comment]
> `listundefinedFooundefined` looks totally broken

This is psalm.dev issue though.

**Comment by muglug** [comment]
Psalm.dev issue is fixed

**Comment by orklah** [comment]
It doesn't anymore :)
