### ISSUE TITLE
Unpacked arguments should be checked for non-emptiness

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#5412]
https://psalm.dev/r/cfd244d27d
https://3v4l.org/VhvZI

**Comment by AndrolGenhald** [comment]
Not quite that simple, psalm has `non-empty-array` but I don't think there's currently any way to type "array with at least n elements".

n=0 (should allow empty)
https://psalm.dev/r/7936207c7f

n=3
https://psalm.dev/r/cfd244d27d

**Comment by vudaltsov** [comment]
@AndrolGenhald , yeah, thank you. Didn't think this way about the issue.

But at least a simple non-empty check for `$requiredParamsCount >= 1` could be a small improvement over the current situation.

**Comment by weirdan** [comment]
> Not quite that simple, psalm has non-empty-array but I don't think there's currently any way to type "array with at least n elements".

Not very straightforward, but tuple type can express that: `array{mixed,mixed,mixed}` is a packed (having consecutive integer indexes starting with 0, with no gaps) array with at least 3 elements.

**Comment by orklah** [comment]
> Not quite that simple, psalm has `non-empty-array` but I don't think there's currently any way to type "array with at least n elements".

I learned today that non-empty-array has a `count` property:
https://github.com/vimeo/psalm/blob/b60c42adca4805bb9d905697837196a4929dd120/src/Psalm/Type/Atomic/TNonEmptyArray.php#L13
It seems to be used when inferring `count()` return for example:
https://github.com/vimeo/psalm/blob/8b5e0fc754f8b29b21b1aa8b1ddc91e49062d428/src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php#L313

**Comment by AndrolGenhald** [comment]
> I learned today that non-empty-array has a `count` property:

Interesting! I was thinking if we wanted a "array-min-size(n)" type it would work like that, didn't realize TNonEmptyArray already had that. Problem is, for full support I think there'd need to be a way to annotate it, and it'd probably need to use a template for count, and it'd get complicated fast:
```
/**
 * How to annotate? Parentheses for min-size?
 * @template TCount
 * @param array(TCount) $array
 * @return array(TCount)
 */
function my_array_map($array, $callable): array {}
```

**Comment by orklah** [comment]
This was fixed
