### ISSUE TITLE
Composer PHP version detected incorrectly

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#5415]
I have a project requiring `"php": "^7.2.5"`. It looks like Psalm only cares about semver major and minor versions, but the way it detects it is by finding the lowest MAJOR.MINOR version that satisfies the composer required version. Since this project requires 7.2.5, 7.2 does not satisfy that, but 7.3 does, so it returns 7.3. I would expect it to detect 7.2.

https://github.com/vimeo/psalm/blob/3046468d1e151a22a19d4c8cb2988ce3cf2633c4/src/Psalm/Config.php#L2056-L2060

**Comment by orklah** [comment]
It would also not return anything for a project that pinned it's PHP version to "7.2.5" because it doesn't satisfy 7.2 nor 7.3
