### ISSUE TITLE
Warn or fail if unrecognized CLI options are used.

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#542]
E.g. if `./psalm --check-for-dead-code` is used instead of `./psalm --find-dead-code`, psalm currently gives no indication that the argument was invalid. Possible approaches:

1. Emit a warning to stderr and proceed.
2. Exit with a non-zero exit code and print an error and a usage message.

https://github.com/getopt-php/getopt-php may also be useful (e.g. for checking for extra options)

A simpler approach would be to try to determine which arguments are invalid via regex.

**Comment by muglug** [comment]
Yeah this is very good
