### ISSUE TITLE
Variadic parameters and list type

### ISSUE THREAD

**Issue by yakimun** [vimeo/psalm#5420]
Hello!

In PHP 8, it is possible to unpack an array with string keys into the argument list when calling functions.

This variadic function example https://psalm.dev/r/8374b93983 passes analysis without any errors. Annotation shows that the function must return a list, but we return an array containing any keys.

Is there a way to specify that only positional arguments could be passed to a variadic function?
It looks like `@no-named-arguments` should cover this case, but it doesn't work (https://psalm.dev/r/b3faaf9d3f).

Thanks!

**Comment by AndrolGenhald** [comment]
Using `@no-named-arguments` to require `int` keys on an array makes sense to me, and I've gotten a bit of work done on supporting it, but I got stuck trying to figure out what error to use.
It doesn't look like psalm currently complains about using named arguments when `@no-named-arguments` is specified, all it does is ignore the named arguments when checking types. Should a new error type be added for this?

https://psalm.dev/r/774181c490

@muglug @weirdan

**Comment by weirdan** [comment]
I would say yes, we need a new issue for call utilizing naming parameters to methods annotated with `@no-named-arguments`.
