### ISSUE TITLE
Variadic parameters and non-empty-list

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#5421]
https://psalm.dev/r/7f75a28f23

In this example `$x` can be empty, but psalm understand this as non-empty-list. It is bug.

**Comment by AndrolGenhald** [comment]
I'm seeing several other issues creating arrays with the spread operator, here's a false negative: https://psalm.dev/r/e7aeb5831c
Should be like this: https://psalm.dev/r/2ac2479ad5
