### ISSUE TITLE
Inherit enum type hint from interface

### ISSUE THREAD

**Issue by gdejong** [vimeo/psalm#5425]
No error: https://psalm.dev/r/8a80c30e24
Also no error: https://psalm.dev/r/71812667c8

Error (as expected): https://psalm.dev/r/096a29017c

Would it be possible to make Psalm check the enum type hint from the interface? So the first example would also trigger an error?

Currently you would need to copy the docblock from the interface to all implementations.

**Comment by muglug** [comment]
This is now caught
