### ISSUE TITLE
Array numeric-string key issues

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#5426]
I'm a bit conflicted on how this should be handled. The way it works right now has a lot of incorrect types due to PHP's automatic string to int for array keys, but handling it correctly would mean `array<string, T>` would basically be the same as `array<string|int, T>`.

Some examples:

- https://psalm.dev/r/fa3e1020f9 key is actually an integer
- https://psalm.dev/r/4885fe5aa9 key is integer again, should maybe be `numeric` in this case?
- https://psalm.dev/r/75bde3bed3 like previous case, but it's actually a string this time

Sorry if this is already documented somewhere, I couldn't find anything with a quick search.

**Comment by robchett** [comment]
is this the same issue just in reverse?
https://psalm.dev/r/f8450a4fc7

**Comment by weirdan** [comment]
@robchett in your case Psalm correctly inferred key to be int.

**Comment by muglug** [comment]
This is really less of a “hard problem” and more of an “impossible problem”. This is the one well-known gaping hole in Psalm’s type system, caused by PHP’s handling of array keys. There’s basically no way to fix this, unfortunately.

**Comment by orklah** [comment]
Couldn't it be improved though?

- Psalm already have the notion of numeric-string. We could infer that the return will be int
- We could trace the origin of a type coming from an array-key and allow string casts on it even when redundant
- At level 0, we could have an issue emitted each time we use a string coming from an array-key as this may be a bug

It will never be perfect and there will be probably some amount of false positive but we can mitigate the issue

**Comment by orklah** [comment]
Oh yeah, I was pretty naive when I wrote that!

I since made a whole post in a discussion in phpstan repo to basically demolish anything I tried to suggest here :D

I'm now pretty convinced that the only good solution would be another structure in php itself but I'm afraid it won't happen in the foreseeable future
