### ISSUE TITLE
ArrayAnalyzer int_offset broken

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#5427]
For object-like arrays with some keys specified and some not `$int_offset` assigns the wrong key.
https://psalm.dev/r/1066dc35a8
~~It's out of order too (assuming object-like arrays are supposed to retain order).~~ Edit: sorting properties on non-list keyed arrays seems to be intentional.

**Comment by AndrolGenhald** [comment]
Should this be allowed?
https://psalm.dev/r/a37bd3cac6
Technically valid, but seems weird.

**Comment by weirdan** [comment]
>  Technically valid, but seems weird.

Looks like a false-positive to me.
