### ISSUE TITLE
Array spread operator false negative

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#5431]
Caused by fix to #2852. It might be slightly annoying to have to annotate with `list<mixed>` or `array<int, mixed>` instead of just `function test(): array {}`, but this is definitely a false negative considering that this code crashes: https://psalm.dev/r/ef5d2a6084 https://3v4l.org/9q0Eq

**Comment by weirdan** [comment]
Note that spread with string keys will become valid in 8.1: https://3v4l.org/DSLic/rfc#git.master, https://wiki.php.net/rfc/array_unpacking_string_keys

**Comment by AndrolGenhald** [comment]
> Note that spread with string keys will become valid in 8.1

Cool! Maybe I'll work on adding support sometime since I've already familiarized myself with ArrayAnalyzer.
