### ISSUE TITLE
Passing class-string-map to variadic crashes psalm

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#5434]
https://psalm.dev/r/93f8d3fbc4

**Comment by AndrolGenhald** [comment]
So the issue is [here](https://github.com/vimeo/psalm/blob/42d3bceb4ed1b7b4f7259952f15a8f7eb5459d67/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php#L446-L483), and the `@var` annotation prevents psalm from catching the issue.
I was thinking about adding a `@psalm-type Type=array{array?: array-types, int?: int-types, etc}` to Union and having `getAtomicTypes()` return that, which would be beneficial in a lot of other places as well, but it's currently a `non-empty-array` and it's not possible to have a non-empty object like array when all keys are optional. It looks like object like arrays are _supposed_ to be nonempty when there are required keys, but that's a bit finicky too: https://psalm.dev/r/23869e7fec
Would it be a good idea to add support for `non-empty-array{a?: string, b?: string}`?

**Comment by muglug** [comment]
I think it might be useful to have an alias of all the possible array types for such situations (all types where the `getKey` method returns `'array'`)
