### ISSUE TITLE
PHP8 + DateTimeZone::listIdentifiers

### ISSUE THREAD

**Issue by tarlepp** [vimeo/psalm#5442]
With PHP8 return type is always an `array` and not `array|false` - https://www.php.net/manual/en/datetimezone.listidentifiers.php

I tried to add `phpVersion="8.0"` to my `psalm.xml` configuration file but no luck with that one. I found this related pull request - https://github.com/vimeo/psalm/pull/4870

There is this snippet for this - https://psalm.dev/r/ef384390a5

Also should that `psalm.dev` have option to choose used PHP version?

**Comment by weirdan** [comment]
> Also should that psalm.dev have option to choose used PHP version?

It has it, but it has no UI for that. Just add `?php=x.y` to the URL.

**Comment by tarlepp** [comment]
> > Also should that psalm.dev have option to choose used PHP version?
> 
> It has it, but it has no UI for that. Just add `?php=x.y` to the URL.

Oh, didn't know that, thanks for the information! Is there a repository for that UI where we could report this issue?

**Comment by weirdan** [comment]
https://github.com/psalm/psalm.dev
