### ISSUE TITLE
Phar providing

### ISSUE THREAD

**Issue by Soullivaneuh** [vimeo/psalm#545]
Is a `.phar` planned? As a tool, it would be great to be able to use it globally like phpunit and other PHP tools.

Thanks!

**Comment by muglug** [comment]
Hasn't really crossed my radar tbh (although Psalm [supports](https://github.com/vimeo/psalm/issues/132) `--global` composer installation)

**Comment by weirdan** [comment]
@muglug, I have initial implementation for this (using `humbug/box`). You can see it here: https://github.com/weirdan/psalm/tree/build-phar . Would you be willing to take it over? If so, I can do the PR.

It requires some minor changes to the code (strategically dropping some `realpath()` calls) and then, probably, changes to your release process (to build and upload the phar).

**Comment by muglug** [comment]
@weirdan sure!

`realpath` is used in `src/Psalm/Config.php` instead of `file_exists`/`is_dir`, so that's an easy replacement

**Comment by weirdan** [comment]
see #549

**Comment by muglug** [comment]
Yes!

**Comment by inverse** [comment]
Enabled me to create my first arch package. Thanks :) 

https://aur.archlinux.org/packages/psalm/
