### ISSUE TITLE
Making Psalm play nicely with jsonSerialize()

### ISSUE THREAD

**Issue by garethellis36** [vimeo/psalm#5450]
Hello 🙂🙂🙂

I am trying to add a Psalm return type to a `jsonSerialize()` implementation. 

Is there a way to make this play nicely so that I don't have to add the `@psalm-var` declarations in the conditionals? `department()` returns either `null` or a PHP object, but because we are in `jsonSerialize()` what is ultimately returned is the array representation from `Department::fromSerialize()`'s `jsonSerialize()` implementation. I thought about calling `json_encode()` on those objects (I haven't checked if that works), but if it's possible to achieve without actually changing the code, I'd prefer that option.

**Comment by garethellis36** [comment]
https://psalm.dev/r/1fa01470ae

**Comment by AndrolGenhald** [comment]
You forgot to call `jsonSerialize()` on `$this->department`: https://psalm.dev/r/067e0dbe22

**Comment by garethellis36** [comment]
> You forgot to call `jsonSerialize()` on `$this->department`: https://psalm.dev/r/067e0dbe22

Yes, this works, but it's not necessary from the POV of the PHP code: https://3v4l.org/ohlPi

I'd like to avoid changing the way that code is written to keep Psalm happy, if at all possible. I assume this isn't possible without some modification of Psalm internals?

**Comment by AndrolGenhald** [comment]
The thing is, you're `not` actually returning an array for that key, you're returning an object and `json_encode` automatically turns it into an array. If you try to use the return value of `jsonSerialize` anywhere other than `json_encode` the type information will be incorrect.
https://3v4l.org/iiYpi

**Comment by garethellis36** [comment]
That does make sense. *sigh*

If I call `jsonSerialize()` as you've suggested, I get:

> ERROR: PossiblyNullReference - src/Registration/Contact.php:96:48 - Cannot call method jsonSerialize on possibly null value (see https://psalm.dev/083)

**Comment by AndrolGenhald** [comment]
You could try updating psalm. If it's the same code you posted the `$this->department !== null` check should allow psalm to infer that `$this->department` is a `Department`.

**Comment by garethellis36** [comment]
I'm on the latest version (4.6.4) already. Perhaps a config thing?

```
<?xml version="1.0"?>
<psalm
    errorLevel="1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
</psalm>

```

**Comment by orklah** [comment]
Closing as stale
