### ISSUE TITLE
I'm getting InvalidArrayOffset, but the value will be within bounds

### ISSUE THREAD

**Issue by ghost** [vimeo/psalm#5458]
This code:

```php
<?php
$numbers      = '23456789';
$letters      = 'abcdefghjklmnpqrstuvwxyz';

$number_count = \strlen($numbers);
$letter_count = \strlen($letters);

$pass = '';

while (\strlen($pass) < 9) {
	$pass .= $letters[\random_int(0, $letter_count - 1)];
}

while (\strlen($pass) < 12) {
	$pass .= $numbers[\random_int(0, $number_count - 1)];
}

echo $pass;
```
(https://psalm.dev/r/7a14bebce5)

Produces an error on line 15:

> ERROR: InvalidArrayOffset - 15:11 - Cannot access value on variable $numbers using a int offset, expecting -8|-7|-6|-5|-4|-3|-2|-1|0|1|2|3|4|5|6|7

because it seems that Psalm can't infer that the return will be within bounds. But strangely, it seems it can correctly infer the return value on line 11, where the same logic is being used.

Is this psalm being confused, or me doing something wrong?

**Comment by weirdan** [comment]
It depends on the string length. Simplified: https://psalm.dev/r/66210a004b

**Comment by weirdan** [comment]
Perhaps this could be solved by inferring literal int for `strlen()` called on literal string.

**Comment by pencil-dog** [comment]
So it the `InvalidArrayOffset` check is only performed on strings where strlen < 10?

For some `int` returning functions (`strlen` in your example, `random_int` in mine) the possible values can be inferred. In this case, currently the "solution" seems to be suppressing the error, right?

**Comment by weirdan** [comment]
> In this case, currently the "solution" seems to be suppressing the error, right?

Correct.

**Comment by orklah** [comment]
I'll close this as this is a pretty narrow edge case. However, random_int now use integer ranges, so all this would need is for strlen to return a literal integer when given a literal string. We'll accept a PR that does that so if someone want to make progress on that, the road is clear :)
