### ISSUE TITLE
support inherting side effects.

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#5462]
### problem

wrapper functions hide the side effects of the callable being wrapped.

e.g ( https://psalm.dev/r/abe87d6f93 ):

```php
/**
 * @param callable(): void $fun
 */
function call_my_function(callable $fun): void
{
  $fun();
}

$c = 
  /**  @throws Exception */
  function(): void { throw new Exception('foo'); };

call_my_function($c); // throws exception, no warning from psalm
```

### solution

a new annotation `@inherits-effects [callable-function]`

```php

/**
 * @param callable(): void $fun
 *
 * @inherit-effects $fun
 */
function call_my_function(callable $fun): void
{
  $fun();
}

$c = 
  /**  @throws Exception */
  function(): void { throw new Exception('foo'); }

call_my_function($c); // Exception thrown but not caught
```

### additional context

This is the closest thing we can get to conditional purity, while keeping things simple as possible, it is insipred by the context and coeffects feature in HackLang ( see: https://github.com/facebook/hhvm/blob/master/hphp/hack/doc/HIPs/contexts_and_coeffects.md )

`@inherit-effects` can probably also support function names, and method names.

e.g:

```php
/**  @throws RuntimeException */
function biz(): void {
  throw new RuntimeException('foo');
}

class Foo
{
  /**  @throws Exception */
  public function bar(): void { throw new Exception('foo'); }

  /**
    * @inherit-effects Foo::bar()
    * @inherit-effects biz()
    */
  public function baz(): void { 
    if (rand(0, 1) {
     $this->bar();
    }

    biz();
  }
}
```

side effects that should be inherited:
- `@pure`
- `@mutation-free`
- `@external-mutation-free`
- `@throws`

`@pure`/`@mutation-free`/`@external-mutation-free` rules:

- If a function inherits from multiple sources, and one of these sources is not `@pure`, the function should not be considered pure.
- If a function inherits from multiple sources, and one of these sources is not `@mutation-free`, the function should not be considered mutation free.
- If a function inherits from multiple sources, and one of these sources if not `@external-mutation-free`, the function should not be considered external mutation free.

**Comment by muglug** [comment]
Sorry, I don't want to add indirection there – I think there's a value in seeing upfront what effects a function has

**Comment by azjezz** [comment]
I'm sorry, but closing this issue promotes the complete opposite, as mentioned before, in this example:

```php
/**
 * @param callable(): void $fun
 */
function call_my_function(callable $fun): void
{
  $fun();
}

$c = 
  /**  @throws Exception */
  function(): void { throw new Exception('foo'); };

call_my_function($c); // throws exception, no warning from psalm
```

There's no way to see effects that `call_my_function` will cause.
