### ISSUE TITLE
IBM_DB2 constants are not stubbed

### ISSUE THREAD

**Issue by morozov** [vimeo/psalm#5466]
The `ibm_db2` extension is stubbed but its constants aren't: https://psalm.dev/r/5c5902f4dd

I haven't found a way to add a constant to the existing extension stub. Is it currently supported?

**Comment by muglug** [comment]
> I haven't found a way to add a constant to the existing extension stub. Is it currently supported?

Yeah see here: https://github.com/vimeo/psalm/blob/master/stubs/Xdebug.phpstub#L3

**Comment by muglug** [comment]
You'd need to add a conditional like this: https://github.com/vimeo/psalm/blob/2edf61399a4f85a3c9dbd76d5fe204aa7231ed55/src/Psalm/Config.php#L1747-L1755

And load in those constants
