### ISSUE TITLE
Cannot suppress an error from a plugin with the issue handler

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#5475]
HI @muglug 

I'm using the symfony plugin.
When I tried 
```
    <issueHandlers>
        <ContainerDependency errorLevel="suppress" />
    </issueHandlers>
```
I got
```
Problem parsing /Users/vincentl/Perso/SonataAdminBundle/psalm.xml:
  Error on line 16:
    Element '{https://getpsalm.org/schema/config}ContainerDependency': This element is not expected.
```

The `ContainerDependency` errors are introduced by the plugin, so it should be allowed to disable them this way.

**Comment by orklah** [comment]
Please check https://psalm.dev/docs/running_psalm/dealing_with_code_issues/#suppressing-issues

There is an example to show how to suppress a plugin error

**Comment by VincentLanglet** [comment]
Sorry, I just find out this line `<PluginIssue name="IssueNameEmittedByPlugin" errorLevel="info" />`

I think it's kinda hidden, what do you think about put it more on light ?

**Comment by orklah** [comment]
Fine by me :) I think I added this here a few weeks ago because it wasn't documented in the first place

**Comment by VincentLanglet** [comment]
Another question, you may help me @orklah ; is there a way to ignore error with a regex ?

With phpstan, I do
```
            message: '#^Parameter .* of class Sonata\\AdminBundle\\.* constructor expects .*, .* given\.$#'
            path: tests/
```
But I didn't find something similar in the documentation of psalm.
It would avoid me to ignore all the `InvalidArgument` error (or having to add a new line to the baseline every time I have a new error I want to ignore).

**Comment by orklah** [comment]
> 
> 
> Another question, you may help me @orklah ; is there a way to ignore error with a regex ?
> 
> With phpstan, I do
> 
> ```
>             message: '#^Parameter .* of class Sonata\\AdminBundle\\.* constructor expects .*, .* given\.$#'
>             path: tests/
> ```
> 
> But I didn't find something similar in the documentation of psalm.
> It would avoid me to ignore all the `InvalidArgument` error (or having to add a new line to the baseline every time I have a new error I want to ignore).

Not at the time. This was discussed here: https://github.com/vimeo/psalm/issues/4880
While phpstan way to handle errors is admittedly useful, it has its flaws, starting by making every error message a potential backward compatibility issue.
What Psalm has is the possibility of ignoring errors for certain classes/variables etc... but it's not always useful for the use-case
