### ISSUE TITLE
Add support for ::class type inference

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5479]
Calling `$class = get_class($obj);` for `$obj` of type `T` correctly resolves `$class` to `class-string<T>`.

But `$class = $obj::class` resolves `$class` to `mixed`

https://psalm.dev/r/57434e1f10

**Comment by AndrolGenhald** [comment]
Ideally support would be conditioned on PHP 8, and previous versions would show an error: https://3v4l.org/ZCj6L

**Comment by simPod** [comment]
It's PHP8+ syntax.
