### ISSUE TITLE
assert does not constrain to string union to evaluate accessed value type under array key

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5483]
https://psalm.dev/r/9805391eca

asserting $var to be of value `'x'` does not help psalm to understand that `$a['a' . $var]` accesses `$a['ax']`. Although, psalm knows `$var` is of type `'x'` after assertion.

So for `$a = array{ax: int, ay: string}`, psalm does not know `$a['a' . $var]` is of type `int` (thinks `int|string` instead).

**Comment by AndrolGenhald** [comment]
I'm not sure this is feasible in general, concatenation with unions means exponentially more types.
This example would have 125 types: https://psalm.dev/r/f966651f47
Add another variable with 5 different types to the concatenation and it would be 625.

There has to be a cutoff somewhere, and I think avoiding reconciling known string concatenations when there is more than one type is reasonable.

You can do [this](https://psalm.dev/r/bf14ce844f) or [this](https://psalm.dev/r/209cd535c5) instead.
