### ISSUE TITLE
False negative ParamNameMismatch

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#5486]
https://psalm.dev/r/43d6b7c791

Possibly intentional, commenting out [this line](https://github.com/vimeo/psalm/blob/9f746765245166bd955b8c67a7f9a0244ed2842e/src/Psalm/Internal/Analyzer/MethodComparator.php#L401) causes some of the tests to fail.

**Comment by orklah** [comment]
Maybe this was made to handle variadics where `$bar` would become `...$baz` but it seems like a bug indeed

**Comment by muglug** [comment]
My assumption here was that people wouldn't use named parameters when there's only a single argument passed, so it wouldn't be an issue. Maybe that assumption was too laissez-faire

**Comment by VincentLanglet** [comment]
> My assumption here was that people wouldn't use named parameters when there's only a single argument passed, so it wouldn't be an issue. Maybe that assumption was too laissez-faire

You can take the habit to always use named parameters, without having to count the arguments.
I think the consistency would be better.

I started a PR: https://github.com/vimeo/psalm/pull/5732

**Comment by VincentLanglet** [comment]
This can be closed since #5732 is merged :)

**Comment by AndrolGenhald** [comment]
Thanks!
FYI you can put ["Fixes #[issue#]"](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) in the pull description and it'll close automatically when merged.
