### ISSUE TITLE
Invalid RedundantPropertyInitializationCheck for static singleton properties 

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#5489]
An uninitialized static property cannot be initialized in an instance constructor: https://psalm.dev/r/05e21b46c0

**Comment by muglug** [comment]
I've reverted the initial fix — instead, if it's possible for the property to not be initialised, make it nullable: https://psalm.dev/r/b5888c4b99

I realised the engine treats each those cases differently, but I prefer Psalm to advocate for that safer state of affairs.

This stops Psalm from

**Comment by muglug** [comment]
Sorry, confusingly I'm reapplying @weirdan's change, but have added a second commit that changes the previous error message to one more specific to static properties.

**Comment by muglug** [comment]
Old:

> Property type Singleton::$instance with type Singleton should already be set in the constructor

New:

> Static property type Singleton::$instance with type Singleton has unexpected isset check — should it be nullable?
