### ISSUE TITLE
@param-out contradicts with its own warning message

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#5490]
https://psalm.dev/r/f9dec3dc4d

```php
<?php

/**
  * @param-out array{errors: int}|null $info
  */
function idnToAsci(?array &$info = []): void
{
}
```

**Comment by muglug** [comment]
I don't really think the _exact_ example you gave is a bug, but this has the same error:

```
<?php

/**
 * @param-out array{errors: int}|null $info
 */
function idnToAsci(?array &$info = null): void {}
```

**Comment by muglug** [comment]
Oh actually that's still not a bug, because there's nothing guaranteeing the output.

**Comment by muglug** [comment]
I've pushed c64e87917 which should help with your specific code, though.

**Comment by zerkms** [comment]
> because there's nothing guaranteeing the output.

right, I didn't realise the output should have been asserted as well. It makes sense now, thanks.
