### ISSUE TITLE
`class-string|trait-string` does not accept `class-string` 

### ISSUE THREAD

**Issue by ngmy** [vimeo/psalm#5491]
HI,

In the example below, `class-string|trait-string` does not accept `class-string`:
https://psalm.dev/r/bc07216add

Thank,

**Comment by weirdan** [comment]
Interpreted as `trait-string` only: https://psalm.dev/r/a7deef5790

**Comment by ngmy** [comment]
Thanks, it worked fine with version 4.7.0.
