### ISSUE TITLE
Incorrect unused variable

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#5493]
https://psalm.dev/r/2830ccf759

I think `$element` is required if you want to access to the key in a foreach.

By the way, it's reported as fixable, but clicking on `Fix code` does nothing.

**Comment by weirdan** [comment]
Prefix the variable name with underscore (or just use underscore as a name) and Psalm will ignore it for dead code checks: https://psalm.dev/r/0f9d180766

This also signals whoever reads the code later that you do not intend to use the value.

**Comment by VincentLanglet** [comment]
> Prefix the variable name with underscore (or just use underscore as a name) and Psalm will ignore it for dead code checks: https://psalm.dev/r/0f9d180766
> 
> This also signals whoever reads the code later that you do not intend to use the value.

Can you consider re-opening the issue @weirdan @muglug ?

Starting variable with `_` is not compatible with multiple linters.
Moreover, it's not because you're currently not using the variable that I don't intend to use it later.

You can add or remove logic in the foreach loop, and it seems not appropriate to keep swapping multiple times the name from `$value` to `$_value`.

Since the foreach syntax is forcing me to write the value, it shouldn't be reported IMHO or at least an option could exists.

Moreover there is still one issue. The error is marked as fixable, but is not, so the issue shouldn't be closed.
