### ISSUE TITLE
Issue with template inheritance

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#5496]
The following code is valid with phpstan
https://phpstan.org/r/3475a9a3-539c-49d8-a476-77fb11b77d98

But not with psalm https://psalm.dev/r/a9385e48ec

Copy pasting the `$classs` property fix the issue
https://psalm.dev/r/498a052aff

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/f32dc309ac
