### ISSUE TITLE
RedundantCondition false positive ??

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [vimeo/psalm#550]
Trying psalm for the first time. It did find some bugs I am grateful it found, but because some of my tests require APCu in a web server I can't use PHPUnit so I wrote my own unit tests to run in a web server and psalm is flagging many errors that I think are false positive - making it hard for me to find the real errors within the see of red.

Example -

    //float
        $caught = false;
        $key = 7.6;
        try {
            $simpleCache->getMultiple($key);
        } catch (\TypeError $e) {
            $reference = "Caching functions for multiple cache operations require an iterable argument. You supplied type double.";
            $actual = $e->getMessage();
            if ($reference === $actual) {
                $caught = true;
            } else {
                print($actual . "\n");
            }
        }
        if (! $caught) {
            return false;
        }

I assign $caught to false. I then have a try block to make sure the type error gets caught, where $caught gets assigned to true.

After the try/catch block I check to see if it was caught and with the right error message - and psalm seems to think that is a RedundantCondition. Dozens and Dozens of them like that, filling the output.

The code works. I'm not sure what psalm wants me to do.

**Comment by muglug** [comment]
Hey! Thanks for trying Psalm.

I'm unable to reproduce the issue just with the code you provided, but there are a few options available:
- You can [suppress](https://github.com/vimeo/psalm/blob/master/docs/dealing_with_code_issues.md) `RedundantCondition` across your project
- If the code is open-source, point me in the direction of the repo and I'll find and fix the bug

**Comment by AliceWonderMiscreations** [comment]
Okay I suppressed the issue in the psalm.xml file, fixed vast majority of other issues (and doc block suppressed intentional issues) and when down to now just two errors and a few warnings - I removed the suppression and no longer am seeing those errors.

So I can not reproduce it now.
