### ISSUE TITLE
False MIxedArgumentTypeCoercion for splat arguments

### ISSUE THREAD

**Issue by KartaviK** [vimeo/psalm#5500]
Argument  1 of SomeClass::method expects array<int, \<Foo\>, parent type array<array-key, Foo> provided

When method is

```php
class SomeClass
{
    public function method(Foo ...$args)
    {
         // code
    }
}
```

$args will always contain array<int, Foo>|list<Foo>

if i try override type with `@param list<Foo> $args` it will work incorrectly

**Comment by Etherlord** [comment]
https://psalm.dev/r/43fe7b3458

https://3v4l.org/bkkbh

**Comment by weirdan** [comment]
It's `array<string, string>` when called with named arguments: https://3v4l.org/AOO6O
Add `@no-named-arguments` if you do not intend to support calling that function with named arguments: https://psalm.dev/r/e1f6a88779

**Comment by Etherlord** [comment]
thanks!

**Comment by KartaviK** [comment]
But i have php version 7.4 that does not have named arguments. Any ideas how psalm can detect it?

**Comment by weirdan** [comment]
@KartaviK add `@no-named-arguments` annotation - it's a future-proof option you can use already. After all, one day you'll probably upgrade.
