### ISSUE TITLE
Type of variable arguments should be `list`

### ISSUE THREAD

**Issue by dsech** [vimeo/psalm#5503]
https://psalm.dev/r/107e02f378

The inferred type for `$others` is `array<array-key, int>`, which leads to a `DuplicateArrayKey` when unpacking.

I would say the inferred type for variable arguments should always be `list<>`

**Comment by weirdan** [comment]
It'll have string keys when called with named arguments: https://3v4l.org/SfPvM

You can declare it should not be called with named arguments, and Psalm will infer `list` for `$others` then: https://psalm.dev/r/fc37910e85
