### ISSUE TITLE
NoValue false positive when @return never used within match expression

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5504]
Throwing an exception directly inside `match` is ok

`default => throw new Exception('nope')`

throwing an exception through a function with return `never` gives

> This function or method call never returns output

```php
/**
 * @psalm-pure
 * @psalm-return no-return
 */
function never() : void
{
    throw new Exception('nope');
}
```

`default => never()`

https://psalm.dev/r/5af9df684e

**Comment by simPod** [comment]
https://psalm.dev/r/5af9df684e

**Comment by weirdan** [comment]
Cannot reproduce anymore.
