### ISSUE TITLE
psalm-suppress for UnusedVariable does not work

### ISSUE THREAD

**Issue by Etherlord** [vimeo/psalm#5507]
https://psalm.dev/r/8d5547bfdd

With errorLevel="1" and findUnusedPsalmSuppress="true" :
```
ERROR: UnusedPsalmSuppress - src/test.php:4:20 - This suppression is never used (see https://psalm.dev/207)
* @psalm-suppress UnusedVariable
```
```
ERROR: UnusedVariable - src/test.php:6:24 - $row is never referenced or the value is not used (see https://psalm.dev/077)
foreach ([123, 456] as $row) {
```

**Comment by muglug** [comment]
`UnusedVariable` issues are suppressed a little differently: you have to prefix the variable name with an underscore: https://psalm.dev/docs/running_psalm/issues/UnusedVariable/

**Comment by weirdan** [comment]
If `UnusedVariable` cannot be suppressed with `@psalm-suppress` it would be handy to tell people it won't work when they do that.
