### ISSUE TITLE
Psalm uses its own types to analyse third-party code when installed globally

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#551]
I've noticed this when I tried to build psalm as phar. In `humbug/box` there's an option to strip down docblocks, and results from psalm.phar were different (one additional issue on my codebase, tons of issues reported on psalm's own codebase) depending on whether that option was enabled or not.

If this is the case, it may lead to subtle (or not-so-subtle) bugs. Imagine you're using `symfony/console:1.0` and the codebase analysed uses `symfony/console:4.0` - should there be any class name clashes psalm would be using it's own version (1.0) to analyse the code that actually works with another version (4.0).

I see references to `\Reflection*` which suggests that psalm actually loads and executes files - consequently you cannot have several versions of the same class loaded. Have you considered `roave/better-reflection` (that advertises that it doesn't execute parsed files) instead?

**Comment by muglug** [comment]
> one additional issue on my codebase, tons of issues reported on psalm's own codebase

That would make sense – Psalm uses docblocks for a large chunk of its types internally, and without them its analysis is pretty limited. You can simulate the effects with `useDocblockTypes="false"` in the config.

> If this is the case, it may lead to subtle (or not-so-subtle) bugs. Imagine you're using `symfony/console:1.0` and the codebase analysed uses `symfony/console:4.0`

I think this is impossible right now because they execute in the same vendor dir. So if your codebase requires `symfony/console:4.0`, and Psalm were to require `symfony/console:1.0` (which it doesn't), Psalm would just not install.

> Have you considered `roave/better-reflection` (that advertises that it doesn't execute parsed files) instead?

Not possible, because Psalm allows people to use their own autoloader if they so wish. So I have to use reflection, though *only* to get the file name of the class after which point Psalm behaves very similarly to `roave/better-reflection`.

Psalm uses composer's generated list of files for the `vendor` directory, bypassing reflection if it exists. But reflection is used for project files, and as a fallback in case the generated composer autoload file is missing.

**Comment by muglug** [comment]
> one additional issue on my codebase

What kind of issue?

**Comment by weirdan** [comment]
> I think this is impossible right now because they execute in the same vendor dir.

I don't think it's the case (for global composer installation anyway, as well for phar build, which bundles vendor dir). Psalm registers it's own autoloader in addition to project autoloader, supposedly to be able to load its own classes from its own (or composer global) vendor dir. For project installation (when you require-dev it) you would be right.

> Not possible, because Psalm allows people to use their own autoloader if they so wish.

Yeah, that's problematic, as autoloaders can do anything. It would be interesting to see how many psalm users are actually using something non-default (psr-4, composer). Vimeo, I suppose, does.

> Psalm uses composer's generated list of files for the vendor directory, bypassing reflection if it exists. But reflection is used for project files, and as a fallback in case the generated composer autoload file is missing.

What's 'project files' in this context?

> What kind of issue?

MissingReturnType for `execute()` method of a class inheriting from `Symfony\Component\Console\Command\Command`. The method is annotated with `@inheritdoc`. When psalm's docblocks are stripped, it complains that the method should declare its return type as `int|null`, when (psalm's) docblocks are intact it does not emit this issue. Obviously my project depends on `symfony/console` and our version in our vendor dir have the following docblock:
```
$ grep 'function execute' -B14 vendor/symfony/console/Command/Command.php
    /**
     * Executes the current command.
     *
     * This method is not abstract because you can use this class
     * as a concrete class. In this case, instead of defining the
     * execute() method, you set the code to execute by passing
     * a Closure to the setCode() method.
     *
     * @return null|int null or 0 if everything went fine, or an error code
     *
     * @throws LogicException When this abstract method is not implemented
     *
     * @see setCode()
     */
    protected function execute(InputInterface $input, OutputInterface $output)
```

**Comment by weirdan** [comment]
> and Psalm were to require symfony/console:1.0 (which it doesn't), 

It's indirect dependency (`composer/composer  1.6.3  requires  symfony/console (^2.7 || ^3.0 || ^4.0)`) through `composer/composer`. In this particular case it would get eliminated when #350 lands, but there could be other issues (with `nikic/php-parser` for example, that couldn't be easily dropped).

**Comment by muglug** [comment]
>  It would be interesting to see how many psalm users are actually using something non-default. Vimeo, I suppose, does.

It doesn't anymore. But it definitely used to (hence the option).

> What's 'project files' in this context

Non-vendor files

**Comment by muglug** [comment]
what happens when you run with `--debug --no-cache`? 

I'm interested in whether it's using composer or reflection for `vendor/symfony/console/Command/Command.php`

**Comment by weirdan** [comment]
> what happens when you run with --debug --no-cache?

Outputs a lot of ASCII characters :laughing: , but here's relevant ones:

```
❯ ~/src/psalm/build/psalm.phar --debug --no-cache | egrep Command.Command
Using reflection to locate file for Symfony\Component\Console\Command\Command
Parsing phar:///home/weirdan/src/psalm/build/psalm.phar/vendor/symfony/console/Command/Command.php
Deep scanning phar:///home/weirdan/src/psalm/build/psalm.phar/vendor/symfony/console/Command/Command.php
Have populated Symfony\Component\Console\Command\Command
Parsing phar:///home/weirdan/src/psalm/build/psalm.phar/vendor/symfony/console/Command/Command.php
Parsing phar:///home/weirdan/src/psalm/build/psalm.phar/vendor/symfony/console/Command/Command.php
Parsing phar:///home/weirdan/src/psalm/build/psalm.phar/vendor/symfony/console/Command/Command.php
Parsing phar:///home/weirdan/src/psalm/build/psalm.phar/vendor/symfony/console/Command/Command.php
```

**Comment by weirdan** [comment]
> Psalm uses composer's generated list of files for the vendor directory, bypassing reflection if it exists. 
 
Right, the issue goes away if I do `composer dump-autoload -o` (generate classmap) for my project.

**Comment by muglug** [comment]
> Right, the issue goes away if I do `composer dump-autoload -o` (generate classmap) for my project.

Doesn't composer need that autoload classmap to run properly anyway (locally)?

**Comment by muglug** [comment]
As in, Psalm just uses the vendor dir classmap generated by `composer install` (doesn't need to have optimised classmap)

**Comment by muglug** [comment]
(I've added some more debugging output for vendor classmap loading)

**Comment by muglug** [comment]
Also makes sense that Psalm should *never* load a file in a vendor dir upstream of its folder. I think an appropriate action would be to check the project's vendor dir for the same file, and use that instead (if it exists) and error out otherwise.

So that's the proper fix for this bug.

**Comment by muglug** [comment]
Another example is when the project is missing a dependency that Psalm has in the phar/global installation, and Psalm fails to catch that.

**Comment by weirdan** [comment]
> I think an appropriate action would be to check the project's vendor dir for the same file, and use that instead (if it exists) and error out otherwise.

Assuming that the class is not loaded yet, isn't that the question of autoload order then? I see psalm tries to properly append itself to the autoload queue by including it's autoloader last. However psalm's `vendor/composer/autoload_real.php` calls `$loader->register(true); // $prepend = true` (and it's the same in my project) and it effectively makes the FIFO autoload queue into LIFO, so psalm's autoloader gets called first.

**Comment by muglug** [comment]
Yeah. Of course, if `prepend-autoloader` is set to false then there's a chance the project's vendor files could be used instead of Psalm's, causing Psalm to break in weird ways.

The obvious solution to this (at least for the phar) is to prepend every namespace in the Phar with `PsalmPhar\` or similar (which is how I believe Phpstan does it). It's slightly non-trivial, but would avoid this confusion entirely.

**Comment by muglug** [comment]
But to reiterate https://github.com/vimeo/psalm/issues/551#issuecomment-370164601
If we have a situation where there's no composer classmap, then use reflection, but if the file exists in Psalm's own directory (i.e. running globally or in a phar while analysing `symfony/console` or another Psalm deb) then exit and *demand* the user run `composer dumpautoload` so Psalm can use that classmap.

**Comment by weirdan** [comment]
> As in, Psalm just uses the vendor dir classmap generated by composer install (doesn't need to have optimised classmap)

I have doubts about that classmap really. For example, when I erased psalm's vendor dir, changed '.config["optimize-autoloader"]' to false and did `composer install --no-dev` `vendor/composer/autoload_classmap.php` ended up containing only `php-cs-fixed/diff`s classes, even though psalm directly requires at least `nikic/php-parser`. Parser's classes were not in that classmap. They did not appear until I did `dump-autoload -o` (I also tried `dump-autoload` before, to no avail).

**Comment by muglug** [comment]
> I have doubts about that classmap really

hmmmm

**Comment by muglug** [comment]
By default, BetterReflection [uses the same technique](https://github.com/Roave/BetterReflection/blob/8f672307c95957568a3c8a7b0d256ef19946af20/src/SourceLocator/Type/AutoloadSourceLocator.php) Psalm uses to get filenames from class names.

If we stick to requiring `composer/composer`, then we can `Composer\Autoload\ClassLoader::findFile`, passing in the specific autoloader for the project, and using reflection as a backup if the user isn't using composer, or the file cannot be found.

**Comment by muglug** [comment]
I'm going to experiment with that latter option which could solve a bunch of other issues (for example, Reflecting PHP 7-incompatible files with a PHP-7 runtime).

**Comment by weirdan** [comment]
> If we stick to requiring composer/composer, then we can use

You don't need full `composer/composer` for that. `ClassLoader::findFile()` is available in `vendor/composer/ClassLoader.php`, and the instance of that object is returned from `require 'vendor/autoload.php';`, so it's just:
```php
$autoloader = require 'vendor/autoload.php';
$file = $autoloader->findFile($class_name);
```
This might be specific for composer version, of course.

**Comment by muglug** [comment]
> You don't need full `composer/composer` for that

You're absolutely right – BetterReflection's docs say you need it for their specific handling, but it's possible they do something differently, or that their docs are just wrong.

I've added this to the master branch - let me know if it works for you globally.

**Comment by weirdan** [comment]
> As in, Psalm just uses the vendor dir classmap generated by composer install (doesn't need to have optimised classmap)

It appears that classmap generated without `-a/-o` only includes those packages that define their own classmap entry in their `composer.json`. `php-cs-fixer/diff` has `classmap` entry, `nikic/php-parser` (and many others) hasn't. So it has to be optimized classmap to include everything (and fall back to autoload/reflection when the file is not found, risking to get wrong filename from the psalm's version).

**Comment by weirdan** [comment]
> I've added this to the master branch - let me know if it works for you globally.

It appears to be picking up my local Symfony Command class, even without the optimized classmap, thanks. 

I wonder why generating the classmap didn't help psalm.phar to be able to check it's own codebase? Is there a check for `class_exists()` somewhere that could be dropped to make psalm read files on disk even if the class is in the memory already?

**Comment by weirdan** [comment]
> I wonder why generating the classmap didn't help psalm.phar to be able to check it's own codebase? 

Right, you mentioned that project files are always loaded with reflection. So even for projects using PhpParser it wouldn't be a problem because its classes will be located with composer, and it's just psalm's codebase psalm cannot check (meaning psalm version X cannot check the source of psalm version Y, or psalm.phar cannot check the source it was built from). And maybe custom autoloaders of the composer dependencies (do they even exist?). 

I guess it's where the problem turns from practical into purely academic one.

**Comment by muglug** [comment]
> psalm version X cannot check the source of psalm version Y, or psalm.phar cannot check the source it was built from

I think it can now, though?

**Comment by weirdan** [comment]
It couldn't, as of https://github.com/weirdan/psalm/commit/24e9092c8969dce4f623e99c2570017a8f9824a3 (build-phar branch rebased on latest master). psalm.phar with stripped comments reports 341 issues, while non-stripped version reports 0.

**Comment by muglug** [comment]
Closing this issue as it was resolved by calling the composer autoloader directly

**Comment by muglug** [comment]
The reason for the issues is that Psalm relies on a couple of stub files to have comments - https://github.com/vimeo/psalm/tree/master/src/Psalm/Stubs. It scans them at the start of each run.

If the docblocks on those files are removed then it cannot infer array access properly.

**Comment by weirdan** [comment]
Ah, that's what I was going to realize soon enough, seeing that debug output of non-stripped version had a couple of lines like 'using reflection to locate file for TValue'. I'll see if I can exclude those from compacting then.

**Comment by muglug** [comment]
And if you can't, with the separate xdebughandler package it's under 800K :)
