### ISSUE TITLE
PossiblyFalseArgument error in using `getenv()`

### ISSUE THREAD

**Issue by ngmy** [vimeo/psalm#5513]
Even in the if statement that the return value of `getenv()` is not `false`, it is said to be possibly `false`.
https://psalm.dev/r/ad72147dd4

**Comment by AndrolGenhald** [comment]
For this to be safe, psalm would need to memoize `getenv` calls based on the name, but clear the memoized result whenever `putenv` is called with the same name. To make matters worse, `putenv` just accepts an assignment string like `'HOGE=foo'`, so it would need to be parsed. I don't see that this is worth it when you can just do: https://psalm.dev/r/4ecf1d0a9d

**Comment by weirdan** [comment]
Agree.

**Comment by ngmy** [comment]
It seems that phpstan can parse it well, probably because it is partially dynamic:
https://phpstan.org/r/cc195994-09fe-4033-a020-756ac20a3de9

I agree that I should just assign it to a variable.

If it is not worth the cost of implementation, then please close this issue.

**Comment by AndrolGenhald** [comment]
PHPStan is just ignoring the fact that environment variables can change:
https://phpstan.org/r/844b0014-1e4b-4bf1-ba86-a7085666043c
https://3v4l.org/sPTli

**Comment by ngmy** [comment]
Oh! I didn't know that😅 

Thank you,
