### ISSUE TITLE
Any way to infer object companion type?

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#5515]
Sorry, I couldn't find a better title to express my intent.

Here is my use case: domain queries. Each `Query` object has an associated `Result` object.

For example:

```php
/** @var ProfessionalCategoriesResult $result **/
$result = $this->queryDispatcher->dispatch(new ProfessionalCategoriesQuery(...));
```

**Is there any way to infer the return type of `dispatch()` depending on the type of object provided?** I can't think of a way to annotate this with `@template`.

**Comment by orklah** [comment]
Maybe something like that?
https://psalm.dev/r/f3adfeff55

**Comment by BenMorel** [comment]
Incredible, thank you @orklah! I can't seem to get it working with `Query` and `Result` as interfaces, though? Is that possible?

**Comment by orklah** [comment]
The syntax is a little bit different for interfaces: 
https://psalm.dev/r/cc8cbd3540

**Comment by orklah** [comment]
@BenMorel Can this be closed?

**Comment by orklah** [comment]
@BenMorel Can this be closed?

**Comment by BenMorel** [comment]
@orklah Sorry for the lack of feedback. It took me some time to wrap my head around this 🙂

This is indeed solved. Thank you!
