### ISSUE TITLE
Psalm-Suppress broken

### ISSUE THREAD

**Issue by jpresutti** [vimeo/psalm#5516]
Using psalm/phar 4.7

ERROR: UnusedVariable - Router/Router.php:491:13 - $val is never referenced or the value is not used (see https://psalm.dev/077)
            /**
             * @psalm-suppress UnusedVariable 
             */
            $val = urlencode($val);

**Comment by AndrolGenhald** [comment]
It's documented on the link it gives you, prefix the variable name with an underscore. See also #5507, maybe this should be documented [here](https://psalm.dev/docs/running_psalm/dealing_with_code_issues/#docblock-suppression) as well?

**Comment by jpresutti** [comment]
Why would I have to *change* my variable name to suppress an (actually false in this instance, see my other open issues) error? My variable names should not be relevant to an inspection. Petition to reopen as a bug.
