### ISSUE TITLE
DuplicateArrayKey with spread operator

### ISSUE THREAD

**Issue by davidbyoung** [vimeo/psalm#5520]
I'm getting `DuplicateArrayKey` errors when using the spread operator to create an array of non-string objects.  https://psalm.dev/r/b96f6fedb1

**Comment by weirdan** [comment]
`Foo[]` is `array<array-key, Foo>` which allows strings as *keys*, and strings *keys* (but not values) are forbidden in array splats (https://3v4l.org/tna6e).

**Comment by davidbyoung** [comment]
Is the solution to use `list<Foo>` as the type hint?  Also, just thinking out loud here, I'm curious if most people interpret `Foo[]` _as_ a list of `Foo` rather than `array<array-key, Foo>`.

**Comment by weirdan** [comment]
> Is the solution to use list<Foo> as the type hint?

Yes, `list<Foo>`, `array<int,Foo>` or none at all. Psalm is smart enough to figure out it's a list if you drop the annotation: https://psalm.dev/r/02ae9ad816

> I'm curious if most people interpret `Foo[]` as a list of `Foo`

Some may, I suppose. Other use it to denote any array of `Foo`. E.g. https://github.com/doctrine/collections/blob/94918256daa6ac99c7e5774720c0e76f01936bda/lib/Doctrine/Common/Collections/Criteria.php#L154-L166

Until recently many IDEs had no docblock syntax to specify array key type, so we have to be conservative here. It seems to be changing, now that some of them started to understand `array<K,V>`, but there's a lot of already existing code that uses that old syntax.
