### ISSUE TITLE
Rest operator doesn't result in a list

### ISSUE THREAD

**Issue by MidnightDesign** [vimeo/psalm#5526]
Take this code:
```php
/**
 * @return list<int>
 */
function foo(int ...$items) {
    return [69, 42, ...$items];
}
```
https://psalm.dev/r/a51f3eb778

The expected behavior is that Psalm finds no problems.

The actual behavior is that it raises an error:
> ERROR: DuplicateArrayKey - 7:24 - String keys are not supported in unpacked arrays

It seems like Psalm sees `$items` as `array<array-key, int>` instead of `list<int>`. But the rest operator always results in a list, right?

**Comment by MidnightDesign** [comment]
I just found out that in PHP 8, when you spread a map, it retains the map's keys inside the function. So Psalm is right here. But this is a really, really weird behavior.

**Comment by weirdan** [comment]
Duplicate of #5500, #5520, #5514 and #5508
