### ISSUE TITLE
Imporoper namespace resolution in doc block type

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [vimeo/psalm#553]
The project -
https://github.com/AliceWonderMiscreations/SimpleCacheAPCu

Present state, you can run psalm in that repo and get two errors. The errors are valid and I am both impressed and grateful they were caught, I misread the spec for the interface I implemented - but the report shows a namespace bug.

    expecting 'null|int|Psr\SimpleCache\DateInterval' as defined by Psr\SimpleCache\CacheInterface::set

The Psr\SimpleCache\CacheInterface actually specifies

    null|int|\DateInterval

psalm is injecting the Psr\SimpleCache namespace into it, which I believe is a bug as I am certain the interface means the DateInterval class in PHP root namespace.

**Comment by muglug** [comment]
Your version of `psr/simple-cache` needs to be on `dev-master`: https://github.com/php-fig/simple-cache/commit/408d5eafb83c57f6365a3ca330ff23aa4a5fa39b

**Comment by weirdan** [comment]
Meaning the problem is actually with `php-fig/simple-cache`, and the fix you've seen was never released and only available on `dev-master`.

**Comment by AliceWonderMiscreations** [comment]
Ah okay, thanks.
