### ISSUE TITLE
Self-check reports issues in src/Psalm/Stubs/*

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#554]
Is this supposed to happen? I tried finding the revision to start bisect from, but self-check was failing even in older version (as old as 0.3.60, 0.3.50 is not installable on PHP 7.2.2).

**Comment by muglug** [comment]
Yeah, I've removed the option entirely in https://github.com/vimeo/psalm/commit/88e0a65f184e23be39b68f84692ef2474bdb2c91. It was somewhat useful when Psalm wasn't in its own repo. Now it's just totally redundant.
