### ISSUE TITLE
False positive UnusedFunctionCall with @psalm-pure annotation

### ISSUE THREAD

**Issue by Etherlord** [vimeo/psalm#5540]
With @psalm-pure https://psalm.dev/r/8b8c7787b4
Without @psalm-pure https://psalm.dev/r/f979691a2a

**Comment by weirdan** [comment]
`Unused*Call` applies to pure functions / methods only, but it shouldn't be reported in the first snippet.

**Comment by 1ed** [comment]
Maybe related to https://github.com/vimeo/psalm/issues/5528
