### ISSUE TITLE
ImplementedReturnTypeMismatch on trait method used from class implementing a covariant interface

### ISSUE THREAD

**Issue by TPHRyan** [vimeo/psalm#5553]
It's very hard to sum this up in a title but I essentially have.

Say interface `B` extends interface `A`, which has a `@template-covariant T of scalar` annotation. There is a method in both of these interfaces that returns `T`. Interface `B`'s annotation is `@template-extends A<string>`.

If you were to then create a trait that implements this method, and use it in a class implementing `B`, you would get an `ImplementedReturnTypeMismatch`.

Here is a repro snippet: https://psalm.dev/r/71ab83ad7e

**Comment by orklah** [comment]
The error seem gone, probably fixed by @ptomulik
