### ISSUE TITLE
Add support for JetBrains\PhpStorm\ArrayShape

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5554]
# Feature request

https://psalm.dev/r/a10658302a

Psalm could be able to infer array shape type from `#[ArrayShape]` attribute. What would be the correct approach to implement it? Should it be on psalm or Jetbrains attributes lib side?

https://packagist.org/packages/jetbrains/phpstorm-attributes

**Comment by simPod** [comment]
Closing. https://github.com/phpstan/phpstan/issues/4790#issuecomment-811883250

**Comment by muglug** [comment]
Yeah, see https://psalm.dev/articles/php-8-attributes#not-currently-supported

**Comment by luckydonald** [comment]
How can I write `#[ArrayShape([self::FIELD_NAME => "array"])]` in the docblock annotation style?
