### ISSUE TITLE
Issue with inclusion of composer autoloaded code

### ISSUE THREAD

**Issue by designermonkey** [vimeo/psalm#5562]
I have code that is included from another directory (`./libs`) using the [composer installers plugin](https://github.com/composer/installers), so it is properly available via the composer autoloader.

Unless I explicitely include the `./libs` folder in my psalm config, I get loads of `UndefinedClass` errors even though composer autoloader is used.

If I do include the `./libs` folder then I obviously get all of the code under libs analysed, which I do not expect as they are libraries that are analysed in their own 'projects'.

Is there an option to include a directory yet prevent it from being analysed?

**Comment by AndrolGenhald** [comment]
Try including it in your config, but add it to `<ignoreFiles>` (haven't tested myself).
```
<projectFiles>
    <directory name="src"/>
    <directory name="libs"/>
    <ignoreFiles>
        <directory name="libs"/>
    </ignoreFiles>
</projectFiles>
```
https://psalm.dev/docs/running_psalm/configuration/#project-settings

**Comment by weirdan** [comment]
There's [`<extraFiles>`](https://psalm.dev/docs/running_psalm/configuration/#extrafiles) config settings that does what you need.

**Comment by designermonkey** [comment]
Totally missed that, thanks.
