### ISSUE TITLE
Incorrect type for variadic function arguments

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#5569]
https://psalm.dev/r/4378014a5c

```php
function go(string ...$items): array {
...
}
```

`$items` should be `list<string>` or `array<int, string>`, but now is `array<array-key, string>`.

**Comment by orklah** [comment]
It can have a string offset here:
https://3v4l.org/BtGji

If you want to avoid that, you can add a @no-named-arguments in phpdoc and your variadics will be back to a list

**Comment by vjik** [comment]
Thank you!
