### ISSUE TITLE
array_map: callback signature should not be considered when called on empty array

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#557]
```php
array_map(function(string $a): string { return $a; }, []);
```
Here psalm complains:
```
ERROR: InvalidScalarArgument - q.php:2:11 - First parameter of closure passed to function array_map expects string, empty provided
array_map(function(string $a): string { return $a; }, []);
```
However when the array is empty (and psalm knows it) the callback won't be called at all, so it's signature is irrelevant. It might make sense to emit something about useless call when `--find-dead-code` is on though.

**Comment by muglug** [comment]
Yes but also why are you doing this

**Comment by weirdan** [comment]
Because people do stupid things, or (possibly) psalm being smarter then them. In this case, though, I was just trying to minimize repro code for another ticket.

**Comment by muglug** [comment]
Permalink: https://getpsalm.org/r/ae643132cd

**Comment by muglug** [comment]
Actually I think this is good and not a bug.
