### ISSUE TITLE
Specific docblock type for ::class constants

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#558]
There are a bunch of times that we may want to pass a string that represents a class, but don't want to use templated types.

Something like
```php
/**
 * @param array<class-string>
 */
function takesClassConstants(array $arr) : void {}

class A {}
class B {}

takesClassConstants([A::class, B::class]);
```

**Comment by nickyr** [comment]
syntax seems reasonable!

**Comment by muglug** [comment]
or maybe just `array<class>`, given it's a reserved word, and `::class` constants may not be used.
