### ISSUE TITLE
Callables and __invoke

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#5581]
https://psalm.dev/r/2615afc63a

What's the relationship between `callable`s and classes implementing `__invoke`? Is there a way to make psalm happy here? In other words, I see the following two ways of using the index operator as largely equivalent, but psalm doesn't like the second :

```
array_map(new IndexOperator('name'), [['name' => 'john']]);

array_map(index('name'), [['name' => 'john']]);
```

**Comment by weirdan** [comment]
As far as I know Psalm currently does not support generic callables (i.e. those with free type params). Could declaring an interface with `__invoke()` be a sufficient workaround in your case?

**Comment by vasily-kartashov** [comment]
@weirdan It seems that Psalm doesn't like the generics on `__invoke` either.

https://psalm.dev/r/066371c1a8

**Comment by orklah** [comment]
I'm gonna close this. The original snippet is fixed and the additional one is not super clear for me
