### ISSUE TITLE
False positive InvalidArgument ?

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#5582]
Is this a bug or there is a way to solve 
https://psalm.dev/r/48fc0c49ad ?

**Comment by weirdan** [comment]
Seem to be working as expected. Why do you think it's a false positive?

**Comment by VincentLanglet** [comment]
`Truc` expect an argument `Base` and `MyClass` extends `Base` so it should be accepted.

If we compare generics, `SuperFooInterface` extends `FooInterface` so `Base<SuperFooInterface>` extends `Base<FooInterface>`, so MyClass extends `Base<FooInterface>` and it should be accepted.

**Comment by weirdan** [comment]
Generics are invariant (see [docs](https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance)). `Truc` expects `Base<FooInterface>`, so it does not accept `MyClass` which is not `Base<FooInterface>`.

**Comment by VincentLanglet** [comment]
Thanks, I solved it this way: https://psalm.dev/r/371df4ff5e

But I got some issue if the annotation are inversed https://psalm.dev/r/f3f6be8f4d
Should it be reported as a bug @weirdan ?

**Comment by weirdan** [comment]
> But I got some issue if the annotation are inversed

That's because of `@phpstan-template` annotation. Dropping it, or reordering so that Psalm's annotation comes first (https://psalm.dev/r/371df4ff5e) fixes this, but it's brittle and needs to be fixed.
