### ISSUE TITLE
Support class const covariance checks

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#5589]
Non-private class constants should be covariant, so a child can't change the type of a parent's const: https://psalm.dev/r/e287a07e3f

Same reasoning as #4184, but since consts can't be changed there's no need for contravariance, hence they should be covariant rather than invariant.

`@var` or `@const` should also be used to specify the type (`@var` seems wrong but [seems to be](https://stackoverflow.com/q/6706051) what's used other places).

**Comment by orklah** [comment]
blocked by https://github.com/vimeo/psalm/issues/942

**Comment by AndrolGenhald** [comment]
I believe properties must be invariant because a parent method can be called on a child class and change a child property, potentially violating its type on the child (eg parent defines property as `array`, child defines it as `array<int>`, parent method assigns `array<string>` to the property). Since constants can't be changed, there's no risk of the parent method changing it and violating the type given in the child.

To quote the first paragraph of the issue I linked:
> Non-private properties in child classes need to be covariant for reading, like function returns and simultaneously contravariant for writing, like function params. That adds up to them needing to be invariant, or have exactly the same type as the property in the parent class.

Consts also need to be covariant for reading, but since they can't be written they have no need for contravariance.

**Comment by orklah** [comment]
Right, I had a slight déja-vu about this discussion :)

I'm not sure I follow your argument that class constants should behave like return types.

They're more related to property types, no? And those are invariants

(I have a possible legit explanation why we should consider them covariant, but I need to make sure I'm not just rationalizing here)

**Comment by AndrolGenhald** [comment]
@orklah My argument is [here](https://github.com/vimeo/psalm/issues/5589#issuecomment-950243787). Since properties can be written there's a risk of passing a child to a function taking the parent as an argument, and that function could change the property to something that matches the parent type but not the child type. Constants can't be written so there's no such risk.

If I'm right, the same also applies to read-only properties, they could be made covariant, but I don't care enough to do it personally.

**Comment by orklah** [comment]
Ok, I arrived to the same conclusion, I'm convinced :)

**Comment by muglug** [comment]
Looks like this is now caught?

**Comment by AndrolGenhald** [comment]
Yes, looks like GitHub stopped recognizing "fixes #..." comments recently.

**Comment by AndrolGenhald** [comment]
@orklah Since you changed literal strings to use single quotes, maybe types should be quoted with double quotes now? https://psalm.dev/r/e287a07e3f

**Comment by orklah** [comment]
Yeah, that could be great

**Comment by bdsl** [comment]
I think the same probably doesn't apply generally to read-only properties. Read-only really means write-once. If it's not contravariant there still seems to be a risk that the parent could write it before the child does, and set it to something not assignable to the type defined in the child.
