### ISSUE TITLE
False-positive mixed nullable properties set in constructor promotion

### ISSUE THREAD

**Issue by robchett** [vimeo/psalm#5594]
https://psalm.dev/r/e60098079c

Psalm is requiring the impossible type `mixed|null` if an overloaded `mixed` property is set to `null` in constructor promotion.
The same does not occur if the property is defined as a traditional class property (B2)

Attempting to used mixed|null results in Fatal error: Type mixed can only be used as a standalone type

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/215402514b
Expected: `mixed`
