### ISSUE TITLE
Reporting redundant @param and @return annotations

### ISSUE THREAD

**Issue by dbalabka** [vimeo/psalm#5596]
Can psalm report redundant `@param` (`@psalm-param`) and `@return` (`@psalm-return`) annotations in DocBlock?
https://psalm.dev/r/99c9518fa7

**Comment by weirdan** [comment]
I'd say that would be a job for coding standard checker. E.g. https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/Commenting/UselessFunctionDocCommentSniff.php seems to be doing just that.

**Comment by dbalabka** [comment]
@weirdan thanks a lot! I think it will work :)
