### ISSUE TITLE
Variadic parameter type is array<array-key, int> instead of list<int>

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#5618]
```php
<?php

function bug(int ...$_): void
{
    /** @psalm-trace $_ */ // should be list<int> but actual type is array<array-key, int>
}
```

https://psalm.dev/r/c18fde3c28

**Comment by orklah** [comment]
nope:
https://3v4l.org/Grv2u

but you can add: 
https://psalm.dev/r/b9351433a1

**Comment by zour228** [comment]
![1](https://user-images.githubusercontent.com/45079391/114438043-e9530600-9bcf-11eb-904f-2fc95ffe16bc.gif)

**Comment by klimick** [comment]
@orklah thanks for fast answer! 
Didn't know about such a detail.

**Comment by zour228** [comment]
@klimick 
This behaviour was described in changelog [v4.7.0](https://github.com/vimeo/psalm/releases/tag/4.7.0).
Pull request is https://github.com/vimeo/psalm/pull/5455

You should better examine changelog though
