### ISSUE TITLE
minor quibble with InvalidOperand error message

### ISSUE THREAD

**Issue by WDD-Marv** [vimeo/psalm#563]
```php
function (string $a, string $b) : int {
    $aTime = strtotime($a);
    $bTime = strtotime($b);

    return $aTime - $bTime;
}
```

Error message says "Cannot add a numeric type to a non-numeric type false".
Operation is subtraction, not addition :)

**Comment by muglug** [comment]
Much bigger quibble: this message shouldn't appear at all, as `strtotime` has `@psalm-ignore-falsable-return` set. Will fix that, and the message.
