### ISSUE TITLE
False positive LessSpecificReturnStatement when subtracting from a positive-int

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#5635]
It is difficult to work with positive-int values if there will be any math involved, even basic decrement. I'm not sure if this can be practically "fixed", but it would be nice.

https://psalm.dev/r/1ed8a99bc6

**Comment by AndrolGenhald** [comment]
This should be doable with int ranges, which is something I've been working on, but it's still quite a ways from being ready.

**Comment by still-dreaming-1** [comment]
> This should be doable with int ranges, which is something I've been working on, but it's still quite a ways from being ready.

Interesting. I figured out a different way of expressing the code that is almost as elegant and doesn't trigger the errors. It's not quite as nice as the original code, but doesn't exactly involve "extra" checks either to prevent the Psalm errors from showing up.

https://psalm.dev/r/d18c2b99c7

**Comment by still-dreaming-1** [comment]
@AndrolGenhald I think int ranges are a very, very good idea. I can't make any commitments at this time, but I might be willing to help with it. Is there somewhere I can see the work on this and possibly contribute? It fits is perfectly with my development philosophy/style I call TOP (type oriented programming).

I was wondering though, in your estimation, if int ranges ever gets implemented and added to Psalm, do you think the work on it would make the original example posted here work? I mean, if I changed the type to an int range there should be a version of this code that would work, but what if I left it as a positive-int? I think the ideal scenario is the work on int rages would also improve the support of existing int types.

**Comment by AndrolGenhald** [comment]
Nothing much to look at yet, mostly just discussion at #5560, but yes, the way I envision it that example should work. `positive-int` would basically be implemented as `int<1,>` where `int<x,y>` is `x <= $int <= y`, and blanks default to `PHP_MIN_INT` and `PHP_MAX_INT`. Operations should all work properly, where `int<5, 10> * int<10, 20> = int<50, 200>`.

As long as I get everything working correctly `$value > 1` should reconcile `$value` to `int<2,>`, then `int<2,> - 1 = int<1,PHP_MAX_INT-1>`, which satisfies `positive-int`.

**Comment by orklah** [comment]
This example will be fixed by the above PR
