### ISSUE TITLE
[bug]: invalid `NoValue` error with union types.

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#5638]
see https://psalm.dev/r/133a625085

in this case, psalm should simplify the return of `$this->future->join()` to `int` instead of `no-return`.

**Comment by azjezz** [comment]
this should result in an error since it doesn't return `no-return` but `void|no-return` 

https://psalm.dev/r/bf95766619

**Comment by azjezz** [comment]
another case: https://psalm.dev/r/eecccf1e66

the issue here seems that psalm simplifies `T|never` to `never`, while it should actually be simplified to `T` ( `never` is always a sub type of `T`, no matter what `T` is )

**Comment by weirdan** [comment]
@azjezz all cases are currently working as expected, but I'd like to see if #5710 would break any

**Comment by weirdan** [comment]
None broken.
