### ISSUE TITLE
Fatal error on parsing assertions

### ISSUE THREAD

**Issue by Sander-Toonen** [vimeo/psalm#564]
The following code snippet results in a fatal error:

```php
<?php

if (isset($foo['bar[]'])) {

}
```

> PHP Fatal error:  Uncaught InvalidArgumentException: Unexpected divider ] in /srv/artikelbank/dev/vendor/vimeo/psalm/src/Psalm/Checker/AlgebraChecker.php:122

**Comment by muglug** [comment]
Thanks, this exposed a flaw in how Psalm evaluated nested array offsets, now fixed.

**Comment by Sander-Toonen** [comment]
Awesome! Thank you for the quick work. 👍
