### ISSUE TITLE
Incorrect errors when final class implements interface and use immutability method

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#5646]
Errors `LessSpecificReturnStatement`  and `MoreSpecificReturnType`, but should be success: https://psalm.dev/r/038571e9e3

**Comment by orklah** [comment]
Weird, if we add `/** @return static */` on the method in child class the error disappears. Kinda like psalm did not inherited the phpdoc

**Comment by orklah** [comment]
This seems fixed :)
