### ISSUE TITLE
Way to document dynamic key name in object-like?

### ISSUE THREAD

**Issue by devnix** [vimeo/psalm#5650]
Hi all! I have a case where I want to document a key => value array, and document as an object-like the inner keys.

I've not been able to document this well using Object-like arrays syntax, and  I thought there should be a way to express this structure by mixing lists with object-like. This example does not comply with Psalm rules, but it's an example of what I'm trying to do.

Is there a way to document this kind of structure that I didn't find in the documentation, or it's just not possible at the moment?

``` php
/**
 * @psalm-return array<int, array<string, array{joinType: string, joinTable: string, joinAlias: string, joinCondition: string}>>>
 */
function test(string $table): array
{
    return [
        [
            $table => [
                'joinType' => '',
                'joinTable' => '',
                'joinAlias' => '',
                'joinCondition' => '',
            ]
        ]
    ];
}
```

**Comment by devnix** [comment]
Yup, sorry: https://psalm.dev/r/ef7aa222ee

**Comment by orklah** [comment]
https://psalm.dev/r/432a8867b8

You just had a `>` extra at the end

**Comment by weirdan** [comment]
I suppose @devnix wanted that `$table` value to appear in the output type. I think the closest you can get is https://psalm.dev/r/549d5d112b

**Comment by devnix** [comment]
Not exactly, I was trying to accomplish what @orklah did. Shame on me 🤦🏻
