### ISSUE TITLE
never and __toString

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#5653]
I wanted to do that on a project:

https://psalm.dev/r/61f31601cb

The goal is to forbid the use of __toString for a class even when the parent has this defined. According to LSP, I should be able to use the bottom type here. Ideally Psalm would then emit an issue when using __toString somewhere.

**Comment by someniatko** [comment]
According to Wikipedia, LSP is not only about types, but also about some behavioral characteristic, including exceptions:

> New exceptions cannot be thrown by the methods in the subtype, except if they are subtypes of exceptions thrown by the methods of the supertype.

https://en.m.wikipedia.org/wiki/Liskov_substitution_principle

**Comment by someniatko** [comment]
I think this rule makes sense, because normally you would except that you can **safely** swap any subtypes and be sure the behavioral contract is preserved.

**Comment by orklah** [comment]
My point is still valid if I had call `die();` or any other no-return function instead of throwing an exception.

But yeah, technically, `@throws` in child classes should always be more specific than the parent. I don't know if Psalm already enforces that when enabling exception handling config

**Comment by muglug** [comment]
@orklah this should be a super-easy problem to fix

**Comment by orklah** [comment]
oh? I'll look at it then :) Thanks!
