### ISSUE TITLE
Feature: psalm-assert "one of" while providing the list of possible values via variable

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#5657]
Hey there,

I think, many of us are using `webmozart/assert`.
I am experiencing some kind of problem for now, as I cannot tell that a value contains one of the values provided by another value.

Lets assume, I have this piece of code:
https://psalm.dev/r/e5faadd216

I dont know any way to provide `psalm-assert` informations that the `unknownValue` is one of these which were provided via the `$values` argument of `Assert::oneOf`.

Is that something which could be achieved in any way?

**Comment by weirdan** [comment]
I would expect something like this to work: https://psalm.dev/r/13845d6d06 (but it doesn't)

**Comment by boesing** [comment]
Closed with #8077
