### ISSUE TITLE
Crash on analysis - strrpos: Offset is greater than the length of haystack string

### ISSUE THREAD

**Issue by simonberger** [vimeo/psalm#5662]
I got the following error after upgrading to the newest version.

`Uncaught RuntimeException: PHP Error: strrpos(): Offset is greater than the length of haystack string in vendor/vimeo/psalm/src/Psalm/CodeLocation.php:282 in vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66`

I debugged it a bit which brought me to the problematic class. It then took me a lot of time to isolate two classes and removing all stuff that is not needed to cause the crash so I hope this helps to find the reason.

It might be a long existing problem (#4165) which just recently converted to an error.

Attached is a minimum project containing:
- a psalm config
- composer file to install psalm and create the autoloader
- two classes

[psalmbug01.zip](https://github.com/vimeo/psalm/files/6360160/psalmbug01.zip)

**Comment by weirdan** [comment]
Simplified a bit further: https://github.com/weirdan/psalm-issue-5662

**Comment by muglug** [comment]
Thanks for the reproduction!
