### ISSUE TITLE
`PossiblyUndefinedVariable` when variable is defined in a matching conditional

### ISSUE THREAD

**Issue by lukasbestle** [vimeo/psalm#5666]
https://psalm.dev/r/ac9fd30846

Also there's a false-positive `MixedArgument` error, but I guess this is because there's currently no stub for the return value of this function.

**Comment by weirdan** [comment]
Just initialize it outside of the condition: https://psalm.dev/r/86d297c8d9

**Comment by lukasbestle** [comment]
@weirdan It's a solution, but should it be necessary? It's a false-positive in any case.

**Comment by weirdan** [comment]
That's the general stance Psalm has on possibly undefined variables, a limitation if you like.

**Comment by lukasbestle** [comment]
OK, I see. Thanks for your fast reply! :)
