### ISSUE TITLE
Invalid TypeDoesNotContainType error with generics and template of

### ISSUE THREAD

**Issue by digilist** [vimeo/psalm#5669]
https://psalm.dev/r/82f4a6ce1c

At runtime `$var` is instanceof `ContainerA`, but Psalm gives the error that the type `ContainerA` is not contained in `AbstractContainer<Item>`.

This happens only with `@template T of Item`. After removing the `of Item` there is no error anymore.

`getContainer` could also return other container classes that contain different item classes. Returning a more specific type does not work when any returned `AbstractContainer` is okay and the contained type is not relevant at that point.

**Comment by weirdan** [comment]
It's likely you need a covariant template there (https://psalm.dev/r/fd8ee98cff), but be sure to read https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance
