### ISSUE TITLE
PHP 8 ::class | Round #2

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5671]
When using `$object::class` in switch statement, narrowing the type using `case $child::class` does not narrow it for psalm

`get_class()` still works fine.

https://psalm.dev/r/c8c3fadc13

_crosslink for previous issue https://github.com/vimeo/psalm/issues/5479_

**Comment by orklah** [comment]
simplified: https://psalm.dev/r/03a8ed173c
