### ISSUE TITLE
Release 4.7.1 lacks the phar assets

### ISSUE THREAD

**Issue by jk** [vimeo/psalm#5674]
We automatically use psalm in our CI environment and there download the phar assets of a new release. The latest release 4.7.1 lacks the phar asset and only contains the standard sourceballs.

It's the same issue as https://github.com/vimeo/psalm/issues/4920 for 4.3.2. I've seen that there is a circle ci config file in the repo instead of the old travis ci workflow. But it looks like the the circle ci workflow doesn't automatically upload the phar as a github release.

Is a PR welcome, to achieve this via a github actions workflow? I probably can add this.

**Comment by weirdan** [comment]
There's already a workflow to build phar (https://github.com/vimeo/psalm/blob/master/.github/workflows/build-phar.yml) but it seems it failed to upload assets.

**Comment by muglug** [comment]
Just tagged a release

**Comment by muglug** [comment]
Oh sorry that was for `psalm/phar`

**Comment by muglug** [comment]
I've added phar assets to the release
