### ISSUE TITLE
Return value of array_splice should be of a list type

### ISSUE THREAD

**Issue by panychek** [vimeo/psalm#5678]
This piece of code causes a MixedArgumentTypeCoercion issue:
https://psalm.dev/r/8cb09c981d

Works fine with array_slice though.

**Comment by weirdan** [comment]
Simplified a bit: https://psalm.dev/r/22d7fa5bbf

It appears `array_splice()`, when invoked on a list always return a list (regardless of offset / length) parameter.

Feel free to propose a PR to https://github.com/vimeo/psalm/blob/master/stubs/CoreGenericFunctions.phpstub using [conditional types](https://psalm.dev/docs/annotating_code/type_syntax/conditional_types/)

**Comment by orklah** [comment]
> It appears `array_splice()`, when invoked on a list always return a list (regardless of offset / length) parameter.

I think we can go one step further: only arrays with string offset will return anything else than a list (because numerical keys are not preserved)

**Comment by weirdan** [comment]
Would that be expressible with a conditional type though?

**Comment by orklah** [comment]
I can get pretty close with something like that:
https://psalm.dev/r/7ef7c49938

Unfortunately, the template is too precise for literal values, it returns very specific types that will be changed by the method.

We should be able to change that by making a big conditional structure like `(T is string ? array<string> : (T is int ? array<int> : ...))`.
