### ISSUE TITLE
FunctionLikeDocblockParser.php Failure

### ISSUE THREAD

**Issue by bdrodes** [vimeo/psalm#5680]
Example code: https://psalm.dev/r/746fc26620 
```
<?php // --taint-analysis

    
    /**
     * @param
     *          $p
     * @return bool;
     */
    function test($p);
```

I'm on verstion `Psalm 4.7.1@cd53e047a58f71f646dd6bf45476076ab07b5d44`

Running taint analysis on this example results in the following exception in FunctionLikeDocblockParser.php

```
Uncaught RuntimeException: PHP Error: Uninitialized string offset: 0 in psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php:62 in psalm/src/Psalm/Internal/ErrorHandler.php:66
```

**Comment by weirdan** [comment]
Reproducible without taint analysis flag on as well: https://psalm.dev/r/67820f1a18
