### ISSUE TITLE
Float bug with incorrect issues count from baseline while code analyzing

### ISSUE THREAD

**Issue by KartaviK** [vimeo/psalm#5683]
Version: 4.7.1

I integrate a psalm to big project and generate baseline - it generates really huge, over of thousands issues (like incorrect phpdocs, calls on nullable objects and other shit)

After that, when i try to fix some issues and than run psalm to validate them - it shows me a different results of found issues

What is more interesting, it always show by next pattern:
- correct issues count (i see issues that not in baseline)
- incorrect issues count (i see issues that exactly in baseline)  
- correct issues count
- incorrect issues count

The result not hardly different, with thousands issues it gives me divergence with 50-100 issues, interesting moment that it always same ones

I run psalm always with `no-cache` and `threads=8`

I thought that problem with `threads` but with single thread gives same problem. Without `no-cache` it even can not understand that I fixing issues

Also, when i try to update baseline with option `update-baseline` - it generates different results in same pattern. I add `set-baseline` and problem of updating baseline partially resolved, but in 1 of 5 cases gives me invalid baseline

Consuming, i event dont understand how to reproduce this with custom clean php

**Comment by weirdan** [comment]
While fixing an issue can reveal some additional issues (e.g. adding a missing return type may highlight other issues at call sites) I gather it's not what happening, right?

Can you elaborate on how you're getting that correct / incorrect results? Are those for subsequent runs without code changes after you had fixed a baselined issue? And what kind of issues get fixed and what reappear?

**Comment by KartaviK** [comment]
@weirdan I try different ways to find pattern of this behavior

And it is not relate to fixing issues

It always shows me correct/incorrect issues count even if i nothing change in my codebase

**Comment by KartaviK** [comment]
@weirdan Maybe psalm have some strict debug mode with mega-verbose options, i can try to some debug this or find wich issues skipped from baseline?

**Comment by weirdan** [comment]
There's `--debug` and `--debug-by-line`, the latter being the most verbose option. `--debug-emitted-issues` could stop Psalm at the first issue reported by converting it into an exception.

**Comment by KartaviK** [comment]
@weirdan Is there possible that problem in external psalm plugins? I'll try to test without plugins, give me a sec

**Comment by KartaviK** [comment]
I can not find any dependency with this float bug, may one day

**Comment by orklah** [comment]
Closing as stale, Please reopen an issue if you manage to reproduce
