### ISSUE TITLE
Extended Include Analyzer

### ISSUE THREAD

**Issue by bdrodes** [vimeo/psalm#5684]
I'm looking for any advice on the proper way I could add a plugin to extend the `IncludeAnalyzer`. 

In particular, in the example below, psalm can't resolve the directory variable  (`$srcdir`) , but the basename is constant. I would like to extend the include analyzer to look for any matching basename in the file system and include any matches as a work around heuristic. 

```
include_once("$srcdir/foo.inc");
```
My current direction is to examine `visitInclude`, and take its lead on how to add new files for deep analysis and simply make a `afterExpressionAnalysis` plugin, but I didn't know if there was a way in psalm to plug into deeper core analyses (like `IncludeAnalyzer`). 

Thanks

**Comment by bdrodes** [comment]
To further clarify, I would like to use this heuristic to address taint analysis where paths go through includes of this form.

**Comment by orklah** [comment]
No, there's no specific plugin hook for include. The best you can hook into is AfterExpressionAnalysisInterface I believe
