### ISSUE TITLE
false-positive InvalidReturnStatement: numeric + 0 should return int or float

### ISSUE THREAD

**Issue by lptn** [vimeo/psalm#5686]
There is a well-known hack to convert numeric-string to int or float: add a zero. 

https://psalm.dev/r/ad297e3f98

Psalm 4.7.1

Sorry in advance if I've missed for edge cases or there is a better approach to convert string into int or float

**Comment by canvural** [comment]
If you use `numeric-string` (like you described in issue) it [works.](https://psalm.dev/r/cb3deca5bf)

**Comment by lptn** [comment]
@canvural 
thanks a lot, I was confused by numeric-string vs numeric. But, I think the behaviour for both should be the same in my example: should return int|float

**Comment by orklah** [comment]
This was solved
