### ISSUE TITLE
Static trait properties can not be found

### ISSUE THREAD

**Issue by MaxBoeh** [vimeo/psalm#5688]
Accessing a static trait property is not valid, because the "class" (which is a trait in that case) can not be found.

https://psalm.dev/r/5ded6a3cbf

**Comment by SCIF** [comment]
@MaxBoeh ,Trait cannot be used on it's own. Use it in class and it works fine: https://psalm.dev/r/6d07ff47dc

**Comment by MaxBoeh** [comment]
Hi @SCIF ,

Thank you for your fast reply. 
I wasn't sure if that's actually valid php code either, so I tried before creating this issue. It executes fine with at least php 7.1 and php 8.

**Comment by orklah** [comment]
This is deprecated in PHP 8.1: https://3v4l.org/4bSbN

we won't be supporting that, sorry
