### ISSUE TITLE
Feature: `Countable::count` return type is interpreted as int, could be 0|positive-int 

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#5690]
https://psalm.dev/r/b1eeba85ed

Imho, it would be invalid to implement `Countable` and then return integer `< 0`, not?
Wondering if this would be a potential feature or if its too unsafe due to the possibility of manually return `-1` as a return statement?

Regular usage would be something like:

```php
final class Foo implements Countable
{
    public function $data = [];
    public function count(): int
    {
        return count($this->data);
    }
}
```

Or what might be another use-case for `Countable`? Even if it uses in combination with `Stringable` while we return a count of a string, it is not possible to have `-1` 🤔

**Comment by weirdan** [comment]
Related: #4997

**Comment by boesing** [comment]
I see, even tho I do not fully understand the reasons why it would be allowed in any `Countable` implementation to return negative-int, I am fine with adding it to the methods I need.

If you have time to answer this, it would give me a broader perspective on why thats the case:

What implementation of `Countable` would be allowed to return negative integer?
Imho, this should get marked as an error by psalm due to the fact that a count of something cannot be negative by definition (at least based on my current knowledge).

```php
final class Foo implements Countable
{
     public function count(): int 
     {
         return -1;
     }
}
```

**Comment by weirdan** [comment]
> What implementation of Countable would be allowed to return negative integer?

I do agree that ideally it should return `0|positive-int` (@Ocramius seems to disagree, judging by his comments on the linked discussion). However I do think this may cause some (and maybe quite a bit of) false positives where Psalm wouldn't be able to infer the return type as non-negative.

**Comment by Ocramius** [comment]
I mean, it's just a defect of countable there.

What could be done is enforce countable to return `positive-int|0` at
interface level too, but that's a bit more of a BC break

**Comment by boesing** [comment]
> I mean, it's just a defect of countable there.

Maybe worth a RFC for PHP 8.X?
