### ISSUE TITLE
array<string, mixed> becomes array<array-key, mixed> on conditional append

### ISSUE THREAD

**Issue by robchett** [vimeo/psalm#5693]
https://psalm.dev/r/f96a8d08d6

This seems to only happen when the if/else statement is present.
I think it's trying to do a union on  array{a: 2}<string, mixed> array{b: 1}<string, mixed> and getting confused. 

Sorry if I'm missing something obvious.

**Comment by weirdan** [comment]
Simplified a bit: https://psalm.dev/r/6f6f797111
