### ISSUE TITLE
array_filter() without 2nd argument treats positive-int as int

### ISSUE THREAD

**Issue by SCIF** [vimeo/psalm#5694]
Not something really simple but want to report it though.

The behavior of `array_filter()` on lack 2nd argument is determined and replicate's `empty()` check. So https://psalm.dev/r/628170286f should not have possible absent keys. All keys must be preserved for `non-empty-string`, `positive-int`, `true`, `object`, `non-empty-array`

**Comment by orklah** [comment]
I'm not sure I understood. Could you add the expected output to your example?

**Comment by SCIF** [comment]
@orklah , I defined an array of non-empty/not-nullable values, so calling `array_filter()` must not change those elements. But trace shows these elements could absent(`a?` and `b?`, but `a` and `b` are expected)

**Comment by orklah** [comment]
Oh, I get it, but your example is slightly wrong. non-empty-string could be `'0'` and still be false. The correct type that should be kept is `non-falsy-string`

**Comment by SCIF** [comment]
@orklah , ok, that's good to know but what's about `positive-int`?

**Comment by SCIF** [comment]
WOw. Object behaves fine, while `positive-int` apparently is not (i included test of zero for positive-int): https://psalm.dev/r/1a19e774d1

**Comment by orklah** [comment]
Ok, so the issue is only with `positive-int`? Maybe rename the issue to show that

**Comment by SCIF** [comment]
Let me check and narrow down for other types :)
