### ISSUE TITLE
Configurable Taint Targets

### ISSUE THREAD

**Issue by bdrodes** [vimeo/psalm#5695]
Is there a way to tell psalm's taint analysis to only examine certain taint types, or to  ignore other types? 

For example, if I only wanted to find `sql ` taint or analyze for all but `html` taint.

**Comment by muglug** [comment]
You can suppress issues with your `psalm.xml` config

**Comment by bdrodes** [comment]
Thanks @muglug. That did it. I thought there would be more to it than just suppress <name of vuln type>, but apparently not. Thanks again.
