### ISSUE TITLE
Ternary statement changing type of read scalar value

### ISSUE THREAD

**Issue by robchett** [vimeo/psalm#5696]
https://psalm.dev/r/cefcc458f3

This seems to be only an issue with scalar, removing the other  types from the return of a() stops the error being raised.

**Comment by weirdan** [comment]
@psalm-github-bot, you missed this: psalm.dev/r/cefcc458f3

**Comment by weirdan** [comment]
Psalm assumes `$a` is a `empty-scalar|null` after the first ternary.

**Comment by weirdan** [comment]
https://psalm.dev/r/d3bbab3804
