### ISSUE TITLE
Shut-up operator (@) suppresses function output parameter definition

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#570]
```php
<?php
@exec('pwd 2>&1', $output, $returnValue);
if ($returnValue === 0) {
    echo "success";
}

exec('pwd 2>&1', $output, $returnValue);
if ($returnValue === 0) {
    echo "success";
}
```
Here first call should cause `$returnValue` to be defined just like the second call does.

**Comment by muglug** [comment]
thanks! Turns out no error-suppressed function calls were getting analysed so, er, they are now.

**Comment by fkooman** [comment]
However, now it seems to lose its type? 

> ERROR: MixedAssignment - src/test.php:3:1 - Cannot assign $a to a mixed type
$a = @file_get_contents('foo');

It should be able to figure out `false|string` as type...
```
/** var false|string */
$a = @file_get_contents('foo');
```

fixes it though.

**Comment by muglug** [comment]
Sorry, I'll mark this as a new bug
