### ISSUE TITLE
Cannot call method on possible array<array-key, mixed> variable $this->propertyAccessor

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#5701]
Hi @muglug.

I have a really weird issue I didn't succeed to reproduce on psalm.dev
It's in the draft PR: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1432

The following code 
```
$this->propertyAccessor->setValue($object, $property, $value);
```
is throwing the error:
```
Cannot call method on possible array<array-key, mixed> variable $this->propertyAccessor
```

But when looking at the whole class
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/src/Model/ModelManager.php

The only occurence are
```
    /**
     * @var PropertyAccessorInterface
     */
    private $propertyAccessor;
```
```
    public function __construct(ManagerRegistry $registry, PropertyAccessorInterface $propertyAccessor)
    {
        $this->registry = $registry;
        $this->propertyAccessor = $propertyAccessor;
    }
```
```
    public function reverseTransform(object $object, array $array = []): void
    {
        $metadata = $this->getMetadata(\get_class($object));

        foreach ($array as $name => $value) {
            $property = $this->getFieldName($metadata, $name);
            $this->propertyAccessor->setValue($object, $property, $value);
        }
    }
```

So how psalm does believe `$this->propertyAccessor` can be an array ?

**Comment by VincentLanglet** [comment]
@weirdan Any idea how I could debug this ?

**Comment by weirdan** [comment]
Run Psalm with `--emit-debugged-issues`, this will show you the place where issue is generated. Then set a breakpoint there and run Psalm with `PSALM_ALLOW_XDEBUG=1 XDEBUG_MODE=debug XDEBUG_SESSION=your-session-key psalm --threads=1` - it will attach to the debugger. Then you can run it step by step.

**Comment by VincentLanglet** [comment]
I find out it's something wrong with the stub of PropertyAccessorInterface
https://github.com/psalm/psalm-plugin-symfony/blob/master/src/Stubs/common/PropertyAccessorInterface.stubphp

The `psalm-self-out` is changing the variable `$this->propertyAccessor`.
I made a reproducer https://psalm.dev/r/dffb7eb2d2

It's a psalm-symfony  issue. But maybe you know how to fix this ?

**Comment by orklah** [comment]
> Run Psalm with `--emit-debugged-issues`, this will show you the place where issue is generated.

If anyone wanders here in the future and try this like I did, the correct spelling is `--debug-emitted-issues` 😄

**Comment by weirdan** [comment]
@VincentLanglet I suspect it needs to be `@psalm-assert self<T> $this`, but it needs some testing.
