### ISSUE TITLE
Psalm adds `mixed` to variable when passed by reference using `use` statement in anonymous function scope

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#5702]
Hey there,

we've experienced an interesting behavior when a variable passed by reference to an anonymous function.

https://psalm.dev/r/89812c068d

When the variable is not passed by reference, the type is preserved. 
Temporary fix is to simply add `assert(is_array($list));` before adding something to that list.

**Comment by weirdan** [comment]
By-reference captures are treated as mixed: https://psalm.dev/r/81fc8439cf
