### ISSUE TITLE
No PHAR for Psalm 4.8.1

### ISSUE THREAD

**Issue by sebastianbergmann** [vimeo/psalm#5703]

**Comment by eclipxe13** [comment]
Looks like the GH action to upload the PHAR is still failing as #5674 
@muglug do you have the opportunity to upload the asset manually also for 4.7.2 ?

Thanks!

**Comment by sebastianbergmann** [comment]
**bump**

**Comment by ADmad** [comment]
The phar file is now available https://github.com/psalm/phar/tree/4.8.1. Can someone please just upload it to the release of this repo https://github.com/vimeo/psalm/releases/tag/4.8.1  so that this issue can be closed?

**Comment by weirdan** [comment]
Done. https://github.com/psalm/phar/tree/4.8.1 had the files from one revision later, so I uploaded files for f73f229
