### ISSUE TITLE
Is findUnusedCode default to true now?

### ISSUE THREAD

**Issue by DavideBicego** [vimeo/psalm#5714]
I'm updating to 4.7.2 from 4.4.1 and I have some issues regarding UnusedMethodCall.

It seems to me that the default value for findUnusedCode in this version is set to true.
Is this the wanted behavior?

**Comment by weirdan** [comment]
Should be still `false`. Can you provide a reproducer, in a separate repo?

**Comment by DavideBicego** [comment]
Here you go https://github.com/KanbanBOX/PsalmIssueTest

**Comment by weirdan** [comment]
Confirmed locally, thanks.

**Comment by weirdan** [comment]
Well, that's intentional, see release notes for https://github.com/vimeo/psalm/releases/tag/4.7.0

**Comment by DavideBicego** [comment]
Oh ok... This is really a pain when using Webmozart Assert all<something>() to assert that an array contains just values of some type.

Thanks anyway!

**Comment by Ocramius** [comment]
This has been solved in `webmozart/assert` through https://github.com/webmozarts/assert/pull/214
