### ISSUE TITLE
Missing Multiple Taint Paths to Sink

### ISSUE THREAD

**Issue by bdrodes** [vimeo/psalm#5715]
I have a project where a vuln sink is accessible by two separate tainted input sources in two separate php modules.

```
tainted_input1.php --includes and calls into--> vuln_sink.php
tainted_input2.php --includes and calls into--> vuln_sink.php
```

Here is a specific example:

tainted_input1.php:
```
// vuln_sink.php defines function foo
include_once "vuln_sink.php";

$req = $_REQUEST['req'];

foo($req);
```

tainted_input2.php:
```
// vuln_sink.php defines function foo
include_once "vuln_sink.php";

$req = $_POST['req'];

foo($req);
```

vuln_sink.php:
```
function foo($cmd){
   vuln_sink($cmd);
}
```

In this example, I have defined my own stub files for `vuln_sink`, in this case I have defined it as a sql taint sink:
```
/**
* @psalm-taint-specialize
* @psalm-taint-sink sql  $cmd
*/
function vuln_sink(string $cmd) {}
```

Despite having the sink established as a @psalm-taint-specialize, psalm taint analysis will only report that the first vuln source (e.g., tainted_input1.php) has a path the vuln sink. 

Reverse engineering the psalm codebase I found `src/Internal/Codebase/TaintFlowGraph.php` around line 260 is related to the issue:

```
            if (isset($visited_source_ids[$to_id][implode(',', $new_taints)])) {
                continue;
            }
```

Removing this check will expose the missing paths to the vuln, but at scale, on a large project, psalm's taint analysis appears to stall forever after analyzing the last file (i.e., the status bar is complete, but it stalls apparently generating the final output report). 

Any recommendations for how I can get all the paths to sink without resulting in an apparent infinite loop or by modifying some configuration directly?

**Comment by bdrodes** [comment]
I have condensed the example into a single file to further illustrate, found here: https://psalm.dev/r/f85ab89ed7

**Comment by orklah** [comment]
I'm not completely sure it should. Taint analysis is already a big and memory hungry module as it is. This would only make it worse.

I think Psalm is already doing its job when it warns you about the first path. One fixed, if the second is still an issue, you'll get notified, no?

**Comment by orklah** [comment]
Closing as answered
