### ISSUE TITLE
Can't suppress unused variable in array unpacking

### ISSUE THREAD

**Issue by robchett** [vimeo/psalm#5727]
https://psalm.dev/r/185d7179be

I could skip the entry with [,,] but that limits comprehenssion

/** @var array{string, int, string, int, int, int, int, int, int, int} $info */
$info = unpack('a8/N/A4/N/N/C/C/C/C/C', ...);

[$sig, $chunksize, $chunktype,,, $bitDepth, $color,,, $interface] = $info;
v 
[$sig, $chunksize, $chunktype, $width, $height, $bitDepth, $color, $compression, $filter, $interface] = $info;

I could also use named args in the unpack, but that has it's own comprehenssion issues

**Comment by weirdan** [comment]
You can prefix throwaway variables with underscore (or use `$_`): https://psalm.dev/r/7c247fc5a4

**Comment by robchett** [comment]
Thanks bruce, I have used that elsewhere, but in this case I thought naming them with a suppression provides more clarity.
I'll use $_ and a comment to explain what the skipped values are.
