### ISSUE TITLE
PossiblyUndefinedIntArrayOffset is used inconsistently

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#5730]
Example A: https://psalm.dev/r/dba09c4360
Example B: https://psalm.dev/r/eb5601c1ae

Given the description of PossiblyUndefinedIntArrayOffset as "Emitted when ... an integer-keyed offset is not checked for existence" it looks like example B is a false negative.

**Comment by weirdan** [comment]
Indeed: https://psalm.dev/r/9aac565d0c

**Comment by muglug** [comment]
Fixed!
