### ISSUE TITLE
ParamNameMismatch does not trigger for one param method.

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#5731]
https://psalm.dev/r/94377dd9b2

Following the doc https://psalm.dev/docs/running_psalm/issues/ParamNameMismatch/
There is no mention of one param method.

And I assume name parameters could be used for one param methods, so the check should be made.

**Comment by orklah** [comment]
The original reason is https://github.com/vimeo/psalm/issues/5486#issuecomment-808735677 . I think this can be closed as a duplicate

**Comment by VincentLanglet** [comment]
Indeed
