### ISSUE TITLE
@psalm-mutation-free causes UnusedMethodCall despite of @psalm-assert

### ISSUE THREAD

**Issue by zakirullin** [vimeo/psalm#5735]
It seems like usage of `@psalm-mutation-free` results in psalm ignoring `@psalm-assert`, hence throwing `UnusedMethodCall`.

https://psalm.dev/r/87a00ec467

**Comment by weirdan** [comment]
Assert does work (https://psalm.dev/r/c98d8a9968) but UnusedMethod is a false positive.
