### ISSUE TITLE
Treat `iterable` as union of `array` and `Traversable`

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#574]
`iterable` pseudo-type in PHP is (currently) equivalent to `array|\Traversable`. It's not treated as a union type by Psalm though, for example it cannot be narrowed in `else` branches:
```php
<?php
function castToArray(iterable $arr): array {
   return $arr instanceof \Traversable ? iterator_to_array($arr, false) : $arr;
}
function castToArray2(iterable $arr): array {
   return is_array($arr) ? $arr : iterator_to_array($arr, false);
}
```
Both examples are completely sound from type perspective view, but Psalm rejects both. Similar example with union types in docblocks checks fine:
```php
<?php

/**
 * @param array|\Traversable $arr
 */
function castToArray3($arr): array {
  return $arr instanceof \Traversable ? iterator_to_array($arr, false) : $arr;
}
```
Edit: updated counter-example with union

**Comment by muglug** [comment]
Thanks!

**Comment by weirdan** [comment]
Hmm, it seems to work with the examples I provided, but fails in the real-world case I was investigating (simplified version):
```php
<?php
    function setPreTransforms(iterable $transforms): void
    {
        // \Traversable|array
	if (!is_array($transforms)) {
            // !array -> \Traversable
            $transforms = iterator_to_array($transforms, false);
            // array
        }
        // array|array
        array_reverse($transforms); // definitely an array, should not complain
    }
```
I annotated my expectations about types at various points of code. Is this a different issue?

**Comment by weirdan** [comment]
Yeah, seems to be different, as adding explicit useless `else` branch clears up the error:
```php
    public function setPreTransforms(iterable $transforms): void
    {
        if (!is_array($transforms)) {
            $transforms = iterator_to_array($transforms, false);
        } else {
            $transforms = $transforms;
        }

        array_reverse($transforms);
}
```

**Comment by weirdan** [comment]
But variant with `\Traversable|array` checks fine, even without the reassignment in the `else` branch. So it might actually be `iterable`-specific thing.

**Comment by muglug** [comment]
The bug is in `Psalm\Type\Union::substitute`, where we should make an exception to allow us to remove

**Comment by muglug** [comment]
Closing in favour of https://github.com/vimeo/psalm/issues/579
