### ISSUE TITLE
Question: annotation to tell psalm that return type must not be handled when working with immutables

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#5740]
Hey there,

I wonder if there is already a way to do so or if that could be added somehow.

I have a self-executing promise (mostly due to backwards compatibility but also that one does not actually have to interact with that return value) https://github.com/boesing/typed-arrays/blob/1d07dddfa975085244e88c8d7c8a472101a99755/src/OrderedListInterface.php#L136

When using that method without actually working with the promise, psalm tells me that the return value is not used (what is absolutely okay from the immutable perspective!) but I'd like to add an annotation or so which tells psalm that the return value is actually not part of the immutability concept of that interface and thus it does not asserts `UnusedMethodCall`.

https://psalm.dev/r/8468251beb

**Comment by boesing** [comment]
Closing here as I think I already provided the answer myself.

**Comment by AndrolGenhald** [comment]
@boesing That's a bit of a hack, as having a method with `@psalm-external-mutation-free` makes the class not really immutable anymore, as Psalm will assume that calling that method will possibly change the object's properties. If it works well enough for you though that's fine, I think warning about this is almost always desired and this is a weird edge case.
