### ISSUE TITLE
Question: Could anyone explain to me what the TooManyTemplateParams in this case means?

### ISSUE THREAD

**Issue by Ilyes512** [vimeo/psalm#5745]
So I am using this library for [enums](https://github.com/myclabs/php-enum) and currently I am getting the following message:

```
ERROR: TooManyTemplateParams - file.php:<line>:<column> - Acme\ConnectionType<empty> has too many template params, expecting 0 (see https://psalm.dev/184)
                $t = ConnectionType::from('DSL');
```

After calling the following snippet:

```php
$t = ConnectionType::from('DSL');
```

My enum looks like:

```php
<?php

declare(strict_types=1);

namespace Acme\Enums;

use MyCLabs\Enum\Enum;

/**
 * @method static static DSL()
 * @method static static FIBER()
 *
 * @psalm-immutable
 */
class ConnectionType extends Enum
{
    private const DSL = 'DSL';
    private const FIBER = 'FIBER';
}

```

Could someone exaplain to me whats going on? I did read https://psalm.dev/docs/annotating_code/templated_annotations/, but I am missing something? To many template params? Expecting 0? Why does it say `<empty>`.

I tried adding some class docblocks to the ConnectionType class like `@extends Enum<int>` without success.

FYI: Currently I am running psalm on error level 3.

**Comment by orklah** [comment]
Please show us some more code. There is no snippet indicating any use of templates in your post.

Ideally, please reproduce on psalm.dev

**Comment by Ilyes512** [comment]
Forgot to add that... I updated my initial post :).

**Comment by orklah** [comment]
Wow, a lot of questions here.

1) templates are not inherited implicitly. Not sure why, but it's clearly by purpose
2) yes, you should. `@template` declares your template. `@template-extends` deals with the inheritance.
3) yes, `@template T of string` should do nicely
4) yes, they're aliases along with `@inherits`

**Comment by Ilyes512** [comment]
Thank you for your time :)
