### ISSUE TITLE
Problem with "new static" in static method call

### ISSUE THREAD

**Issue by matiux** [vimeo/psalm#5747]
I get the UnsafeGenericInstantiation error despite putting final in the constructor

https://psalm.dev/r/f9fe1e15bb

**Comment by weirdan** [comment]
Constructor being final does not prevent a descendant to declare it has narrower type parameter with e.g. `@template-extends BasicServiceResponse<int>`

**Comment by matiux** [comment]
Thank you @weirdan . So how can I fix?

**Comment by matiux** [comment]
by the way, since the class is abstract, I can't do `new self`

**Comment by matiux** [comment]
up
this is a shorter example

https://psalm.dev/r/ce85a892e2

**Comment by AndrolGenhald** [comment]
@orklah Are you sure this is a bug? I think this is correct solution is to use `@psalm-consistent-templates` as noted in the documentation: https://psalm.dev/r/650ada1ab1

**Comment by orklah** [comment]
Yep, I learned that tag existed not long ago. Closing this as not a bug indeed.
