### ISSUE TITLE
Psalm says `Argument 2 of password_hash cannot be mixed, expecting int|null|string` but the PHP docs say its `mixed`.

### ISSUE THREAD

**Issue by lovephpforever** [vimeo/psalm#5757]
- https://www.php.net/manual/en/function.password-hash.php

**Comment by lovephpforever** [comment]
`mixed` is only for PHP 8. So this would be a breaking change.

**Comment by weirdan** [comment]
PHP docs are obviously wrong, see https://github.com/php/php-src/blob/01b3fc03c30c6cb85038250bb5640be3a09c6a32/ext/standard/password.c#L655
