### ISSUE TITLE
How to custom sources and sinks for finding POP chains?

### ISSUE THREAD

**Issue by nth347** [vimeo/psalm#5758]
In a POP chain, a magic method is the starting point (or taint source, I think) of the POP chain, for example:
```
public function __destruct()
    this->exec($this->command, $this->parameters);
}
```
And a taint sink of a POP chain is something like this:
```
public function exec($command, $parameters) {
    call_user_func($command, $parameters);
}
```
I want to check, whether there are any __destruct() method reaches to taint sinks like exec() method, so how I can do it with Psalm?

**Comment by ohader** [comment]
https://psalm.dev/r/a7f1dbef8c

This example demonstrates how it might be used
* `@taint-param-sink` for `exec` declares this method is "doing something dangerous" with callables
* usage of `$_GET` implicitly a "taint source"
* using a user-controlled _source_ in a corresponding dangerous _sink_ defines a vulnerability

* `@taint-param-source` currently does not work for properties in stubs, just for methods
  + see issue #3745 
  + see alternative using [individual handler](https://psalm.dev/docs/security_analysis/custom_taint_sources/) in your [custom plugin](https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/)

**Comment by orklah** [comment]
I'm closing this as answered
