### ISSUE TITLE
abs should allow int|float|string? as first parameter

### ISSUE THREAD

**Issue by jaydiablo** [vimeo/psalm#576]
psalm is throwing this error for me on some code that calls `abs`:

>Argument 1 of abs expects int, numeric provided

The "numeric" type is inferred here because there's an `is_numeric` check on the variable a bit earlier in the code.

According to the php.net docs, `abs` accepts "mixed" as the first parameter: https://secure.php.net/abs

As far as I can tell there is no internal typehint on that parameter (based on reflection information).

https://3v4l.org/2YW72

>$ php --rf abs
```
Function [ <internal:standard> function abs ] {

  - Parameters [1] {
    Parameter #0 [ <required> $number ]
  }
}
```

Should psalm be expanded to allow "numeric" (or "mixed", like the php docs) as the first parameter?

Code for getpsalm.org:

```php
<?php
  
/**
 * @param mixed $var
 * @return mixed
 */
function testAbs($var)
{
        if (!\is_numeric($var)) {
            return $var;
        }

        if ($var == 0) {
            return 0;
        }

        if ($var < 0) {
            $var       = \abs($var);
        }
}
```

Thanks!

**Comment by jaydiablo** [comment]
Was looking at `CallMap.php` and noticed this line: https://github.com/vimeo/psalm/blob/master/src/Psalm/CallMap.php#L57

Are the `'1` versions of the function names other variations of how the function can be called?

This means that `abs` returns int when is given an int,  and returns float when given a float (which is what the docs describe)?

I suppose my issue is that the value is "numeric" (again, implied via psalm).  So I guess I'm curious if "numeric" should be allowed here (mixed seems too general since that won't protect the developer from passing a non-numeric value, which causes `abs` to return `0`).

**Comment by muglug** [comment]
Thanks!

**Comment by muglug** [comment]
> I suppose my issue is that the value is "numeric" (again, implied via psalm). So I guess I'm curious if "numeric" should be allowed here (mixed seems too general since that won't protect the developer from passing a non-numeric value, which causes abs to return 0).

Numeric should be allowed (but then `numeric` should be returned)

> Are the '1 versions of the function names other variations of how the function can be called?

Yeah, PHP doesn't allow this for user-defined functions, but its standard lib allows this.
