### ISSUE TITLE
`opcache_invalidate()` calls reported as unused function calls

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#5761]
Given this snippet ( https://psalm.dev/r/4d51eeab35 ):

```php
<?php

function invalidate_cache_for(string $path): void {
    opcache_invalidate($path);
}

invalidate_cache_for('foo');
```

Psalm reports the `opcache_invalidate()` call as `UnusedFunctionCall`. I'm wondering if `opcache_invalidate()` is perhaps inferred as a pure function? The only reference to it that I could find is in https://github.com/vimeo/psalm/blob/1a59e8180878cd7a1758e30c1558cd27e42f7478/dictionaries/CallMap.php, but no purity markers are there.

I'd gladly fix these, if I could get a pointer to where purity is determined.

**Comment by orklah** [comment]
This [method ](https://github.com/vimeo/psalm/blob/105c6f3a1c6521e4077da39f05a94b1ddbd76249/src/Psalm/Internal/Codebase/Functions.php#L384)seems to be where it happens and the first thing in it is a list of impure functions. Maybe it was quicker to assume every function is pure and get rid of the exceptions?

**Comment by Ocramius** [comment]
@orklah thanks, will send a patch shortly :-)
