### ISSUE TITLE
strpos' second parameter

### ISSUE THREAD

**Issue by jaydiablo** [vimeo/psalm#577]
According to the php docs, the second parameter of `strpos`, if not a string, is converted to an int:

>If needle is not a string, it is converted to an integer and applied as the ordinal value of a character. 

Does this seem like a normal use case that psalm should accept?  I ran into this today in a third party lib that we have in our codebase:

```php
$org_buf = \substr($org_buf, 0, \strpos($org_buf, 0));
```

(It's reading from a shared memory resourcce)

**Comment by muglug** [comment]
> Does this seem like a normal use case that psalm should accept?

Well, not *normal*. But Psalm should support it.

**Comment by muglug** [comment]
Thanks!

**Comment by jaydiablo** [comment]
Thanks!
