### ISSUE TITLE
The phpdoc is not inherited anymore when we're adding phpdoc for one param.

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#5776]
https://psalm.dev/r/8b358668a7

Here, I would expect to inherit the `@param int|string $id` annotation.

**Comment by orklah** [comment]
I think it's on purpose. IIRC, I saw that Psalm either inherits every parent tag or none

**Comment by VincentLanglet** [comment]
> I think it's on purpose. IIRC, I saw that Psalm either inherits every parent tag or none

I assume it was made on purpose too, but I don't think it's a good idea.
As a comparison phpstan does inherit https://phpstan.org/r/33fef061-c461-4cf9-8e38-77198433d1ac

If I want to wilder the param typehint, I can use `@param mixed $id`.
If I want to use the same I shouldn't have to copy `@param int|string $id`.
Because if the vendor update the typehint, I'll have to update it too.

**Comment by VincentLanglet** [comment]
> I think it's on purpose.

@orklah Should I close this or could it be plan to be changed ? (For instance for psalm 5 ?)

**Comment by orklah** [comment]
I'm not sure. I'd have loved to find the reason why it's like this but I don't remember reading Matt about this particular topic...

**Comment by AndrolGenhald** [comment]
The main point of contention here (for me at least) is that it becomes unclear what tags apply and where they come from. I'd almost want to require `@override` or something (which could also have additional semantics like [Phan](https://github.com/phan/phan/issues/926)) to make it clear that there may be annotations coming from the parent.

IDEs also help a lot with that, maybe we could improve our language server to provide better info when overriding methods as well? It'd be nice to see what method is being overridden when you hover on the declaration.

**Comment by VincentLanglet** [comment]
> I'm not sure. I'd have loved to find the reason why it's like this but I don't remember reading Matt about this particular topic...

@muglug I would be really interested if you can give us the reason behind.

I personally think it would be better to have a consistent behavior with phpstan https://phpstan.org/r/33fef061-c461-4cf9-8e38-77198433d1ac ; so either psalm should change the behavior (which could be done in psalm 5 @orklah) or phpstan in a potential 2.0 version (one day).

**Comment by muglug** [comment]
@VincentLanglet Psalm's behaviour — respecting paramater contravariance — is correct, and is consistent with PHPStan in strict mode: https://phpstan.org/r/8cae8b3d-4a33-416a-8950-faf66f9edbff.

The [Wikipedia article on covariance and contravariance](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)) has more information.

PHPStan has slightly weird behaviour re covariance and contravariance — by default (in non-strict mode) it doesn't tell you that this is wrong: https://phpstan.org/r/6d838379-17b4-427b-841d-ff17ebc0fe3f

That's something you should ticket in PHPStan's repo 🙂

**Comment by VincentLanglet** [comment]
> @VincentLanglet Psalm's behaviour — respecting paramater contravariance — is correct, and is consistent with PHPStan in strict mode: https://phpstan.org/r/8cae8b3d-4a33-416a-8950-faf66f9edbff.
> 
> The [Wikipedia article on covariance and contravariance](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)) has more information.
> 
> PHPStan has slightly weird behaviour re covariance and contravariance — by default (in non-strict mode) it doesn't tell you that this is wrong: https://phpstan.org/r/6d838379-17b4-427b-841d-ff17ebc0fe3f
> 
> That's something you should ticket in PHPStan's repo 🙂

I think you misunderstood, I was not concerned about the class-string param but the id one @muglug.

No error on phpstan: https://phpstan.org/r/17efbd7c-387b-40bc-b9f0-6261e16bbc42
Missing param on psalm: https://psalm.dev/r/a4d0870113 (even with inheritdoc https://psalm.dev/r/40639ef455).

As far as know, phpdoc inheritance is implicit, so it's weird to go against this behavior.
https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#41-making-inheritance-explicit-using-the-inheritdoc-tag

**Comment by muglug** [comment]
Oh ok sorry!

So in this case I decided that if a function includes a docblock and doesn't specify all the parameter types, it's treated as `mixed`. It's because I dislike the spooky action-at-a-distance effect. It also goes against the idea of a function docblock to document how the function is supposed to behave — what its inputs and outputs are — in a way that's not obvious from the function signature itself.

If you don't include _any_ docblock then the doc is automatically inherited: https://psalm.dev/r/1e8b954d13

**Comment by AndrolGenhald** [comment]
@muglug What do you think about doing something like [this](https://github.com/vimeo/psalm/issues/5776#issuecomment-1027401324) to add additional clarity? The language server improvements only help people that actually use it, but the `@override` tag should at least indicate that there is a parent somewhere.

**Comment by muglug** [comment]
@orklah/@weirdan I'm reopening this issue because I don't want to have the last word on this — I'll leave it to you

**Comment by muglug** [comment]
@AndrolGenhald I think the thing that could be improved, if we stick with my decision, is the "MissingParamType" error message to make clear the previous docblock type is not inherited automatically. I don't think the Language Server should be a crutch there.

More broadly, and at the risk of going off-topic, I'm now writing a static analysis tool for Hack, a cousin of modern PHP, which basically means porting most of Psalm to work on that language. Hack is much more strict than Psalm/PHP in what it allows, which means the implementation of static analysis is much more straightforward.

Psalm would not have been half as successful if it was as strict as Hack's typechecker — the latter's strictness is one of many reasons I believe Hack/HHVM has not suceeded outside a few large companies. But I also believe that Psalm can help developers when it nudges them towards more explicit patterns of documentation. And adhering to those rules also helps Psalm's internals stay somewhat sane.

**Comment by VincentLanglet** [comment]
> @muglug What do you think about doing something like [this](https://github.com/vimeo/psalm/issues/5776#issuecomment-1027401324) to add additional clarity? The language server improvements only help people that actually use it, but the `@override` tag should at least indicate that there is a parent somewhere.

I'm not sure we need a new "override" tag, that's the purpose of inheritdoc, IMHO.

Anyway, I let you decide @orklah, I can survive adding the extra param phpdoc ; I was just looking for consistency with phpstan, in one way or another. So should we close this or do you think about updating the behavior ?

**Comment by AndrolGenhald** [comment]
> that's the purpose of inheritdoc, IMHO.

`@inheritDoc` is a bit more complicated than that though, it specifically allows importing the description, which might or might not be desired.

https://docs.phpdoc.org/guide/guides/inheritance.html
https://stackoverflow.com/a/26554272
