### ISSUE TITLE
Bug with static and generics

### ISSUE THREAD

**Issue by melihovv** [vimeo/psalm#5778]
https://psalm.dev/r/28bcffadfc

```php
<?php

declare(strict_types=1);

namespace Skyeng\ProductsCore\Collection;

use function is_array;

/**
 * @template TKey as array-key
 * @template TValue
 */
abstract class Collection
{
    /**
     * @readonly
     *
     * @var array<TKey, TValue>
     */
    private array $items;

    /**
     * @param array<TKey,TValue>|static<TKey,TValue> $items
     */
    final public function __construct($items = [])
    {
        $this->items = is_array($items) ? $items : $items->toArray();
    }

    /**
     * @return array<TKey, TValue>
     */
    public function toArray(): array
    {
        return $this->items;
    }
}

/**
 * @template-extends Collection<int,int>
 */
final class StudentIds extends Collection
{
}

$studentIds = new StudentIds([1, 2, 3]);
$copyFromCollection = new StudentIds($studentIds);
echo $copyFromCollection->toArray()[0] ?? null;
```

Psalm does not allow to pass child to constructor of templated base class if it accepts `static<TKey,TValue>`. If I change static to self, it works. The produced error is
```
INFO: MixedArgumentTypeCoercion - 47:38 - Argument 1 of Skyeng\ProductsCore\Collection\StudentIds::__construct expects Skyeng\ProductsCore\Collection\StudentIds<int, int>|array<int, int>, parent type Skyeng\ProductsCore\Collection\StudentIds provided

  The type of $studentIds is sourced from here - 46:1
    $studentIds = new StudentIds([1, 2, 3]);
```

**Comment by weirdan** [comment]
Not sure if that's a bug, really. `StudentIds` has zero type parameters, yet you request the parameter to be `StudentIds<int,int>`. I wonder whether it would make sense to treat `static` as if all parameters specified in `extends` signature were provided and valid.

**Comment by melihovv** [comment]
I see error message `expects Skyeng\ProductsCore\Collection\StudentIds<int, int>|array<int, int>, parent type Skyeng\ProductsCore\Collection\StudentIds provided` and I can't understand why `Skyeng\ProductsCore\Collection\StudentIds` is not the same as `Skyeng\ProductsCore\Collection\StudentIds<int, int>`. I specified that StudentIds extends Collection<int,int>, now StudentIds it is the same as StudentIds<int,int>, isn't it?

**Comment by weirdan** [comment]
`StudentIds<int,int>` is basically invalid.

**Comment by weirdan** [comment]
The issue is no longer emitted: https://psalm.dev/r/28bcffadfc
