### ISSUE TITLE
Question: how get `assert` behavior in plugin

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#5779]
As we know `assert` can change types for flow analysis:

```php
/**
 * @return positive-int
 */
function toPositiveInt(?int $number): int
{
    assert(null !== $number);
    assert($number > 0);

    return $number;
}
```
https://psalm.dev/r/1d45dd2099

So how can I get `assert` behavior for my custom function in plugin?

**Comment by orklah** [comment]
You mean you want to modify the return type of a custom function of yours through a plugin? If not, can you explain in details what you want to do?

**Comment by klimick** [comment]
I have 2 examples.
I wanna to solve both.
One easy to understand and one to difficult.

## example 1:
For example I have a collection `Seq<T>`.
The collection have a method `filter`.

I wanna that `filter` could change return type by assertions inside closure:

```php
/** @var Seq<array{name?: string}> $persons */
$persons = Seq::of(...);

$filtered = $persons->filter(fn($p) => array_key_exists('name', $p));

// now $filtered should be Seq<array{name: string}>
// name is not undefined anymore
```

## example 2:
I have a function `proveTrue`. It returns `None` if `$isTrue` is `false` and `Some` if `$isTrue` is `true`:
```php
/**
 * @return Option<true>
 */
function proveTrue(bool $isTrue): Option
{
     // ...
}
```

In some context it should behaves like built php `assert` function. But without throwing errors.
Look at this snippet:

```php
/**
 * @return Option<string>
 * note: the yield interrupts a computation if Option is None and resolves the computation to None
 */
function asStringWithFoo(mixed $maybeString): Option
{
    return Option::do(function() use ($maybeString) {
        yield proveTrue(is_string($maybeString));
        yield proveTrue(str_contains($maybeString, 'foo')); <- psalm error here

        return $maybeString;  <- psalm error here
    });
}
```

If would `proveTrue` behave like `assert` in this context then psalm would not be angry.

Now it has become clearer what I want? @orklah

**Comment by weirdan** [comment]
Wouldn't a stub with `@psalm-assert` annotations be an acceptable solution?

**Comment by klimick** [comment]
what do you mean? @weirdan

**Comment by weirdan** [comment]
https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/#registering-stub-files
https://psalm.dev/docs/annotating_code/adding_assertions/
and https://psalm.dev/docs/annotating_code/assertion_syntax/
