### ISSUE TITLE
psalm incorrectly identifies some array keys as int?

### ISSUE THREAD

**Issue by jaydiablo** [vimeo/psalm#578]
Ran into a case where psalm complained about an array key being passed to `strlen` since it detected that the array key was an int, sample code:

```php
<?php

$array = ['01' => '01', '02' => '02'];

foreach ($array as $key => $value) {
    $len = strlen($key);
}
```

Those keys are numerical, but PHP sees them as strings when iterated: https://3v4l.org/UPUH2

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/a253463ba8c2e65be5ca2bfed6b9198242440a43
