### ISSUE TITLE
Type imports on methods are silently ignored

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#5782]
https://psalm.dev/r/9392781c99

#### Expected

Either no issues or `InvalidDocblock: type imports on methods have no effect, move it to class docblock`

**Comment by orklah** [comment]
More broadly, `@var` on methods or `@param` on attributes should be checked too

**Comment by weirdan** [comment]
Fixed `@var` on methods, but flagging `@param` on properties is harder due to how property docblocks are parsed, so I'm not going to pursue that for now.
