### ISSUE TITLE
Support for template of template

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#5788]
`doctrine/persistence` defines a generic `ClassMetadata` interface, and its generic `ClassMetadataFactory`. Templating `ClassMetadataFactory::getMetadataFor()` does not seem possible:

https://psalm.dev/r/0ff07df695

I would expect no errors.

**Comment by orklah** [comment]
Not sure I know enough of ClassMetadata structure, but isn't https://psalm.dev/r/4b0ca83540 good enough?

**Comment by greg0ire** [comment]
Sadly no. My end goal is to let Psalm understand that the ClassMetadataFactory::getMetadataFor returns _ORM_ ClassMetadata, which has a lot of fields not defined in the ClassMetadata defined in Persistence.

**Comment by orklah** [comment]
Well, given that ORM\ClassMetadata is a child of ODM\ClassMetadata, I'd say the contract allows for ORM\ClassMetadata to be returned. I'd say it's up to the caller of the contract to check what kind of ClassMetadata it received.

Do you mind explaining the difference between an entity and a document?

**Comment by greg0ire** [comment]
> Well, given that ORM\ClassMetadata is a child of ODM\ClassMetadata

It isn't the ORM and the ODM are 2 different projects, both depend persistence. The former users entities, the later documents.

From https://www.doctrine-project.org/projects/doctrine-phpcr-odm/en/latest/reference/introduction.html

> As PHPCR allows NoSQL like data storage, we speak of Documents rather than Entities to stress the fact that there need not be a rigid database model.

> I'd say it's up to the caller of the contract to check what kind of ClassMetadata it received.

[That's currently what happens](https://github.com/doctrine/orm/search?q=assert%28%24metadata+instanceof+ClassMetadata%29%3B) but as long as in the ORM, you expect to be dealing with ORM ClassMetadata. It would be great not to have to do all these assertions.

**Comment by orklah** [comment]
Sorry, I confused ODM for persistence. I understand better. How does persistence knows which one it's dealing with? Ideally, when creating the ClassMetadata, we would give it the type correct type as a template

**Comment by greg0ire** [comment]
My plan would be to use `@template-extends AbstractClassMetadataFactory<ORMClassMetadata>` in the ORM `ClassMetadataFactory`. I tried it when working on https://github.com/doctrine/orm/pull/8699 this evening, but got many more errors I did not understand. My goal was to get rid of the three `@method` annotations show here: https://github.com/doctrine/orm/blob/2.8.x/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php#L58 , but that will be a story for tomorrow :sleeping:

**Comment by orklah** [comment]
Oh right, so the end goal would have been something like https://psalm.dev/r/725182085a, but then the error about the template not recognized pops up, right?

**Comment by greg0ire** [comment]
Yes exactly!

**Comment by weirdan** [comment]
Doesn't `ORM` have its own factory interface? E.g. https://psalm.dev/r/61c14d2a53

**Comment by greg0ire** [comment]
@weirdan it's not an interface, it's a class, and I think it would be more elegant to have `@class-extends PersistenceMetadataFactory<ClassMetadata>` here, wouldn't it?

**Comment by weirdan** [comment]
> it's not an interface, it's a class,

That seems irrelevant, it'll work the same way with a class.

> I think it would be more elegant to have `@template-extends PersistenceMetadataFactory<ClassMetadata>`

Why though? Is it to avoid having to specify a docblock for `ORM\ClassMetadataFactory::getMetadataFor()`?

**Comment by greg0ire** [comment]
> Why though? Is it to avoid having to specify a docblock for ORM\ClassMetadataFactory::getMetadataFor()?

Yes. Note that this method is defined in the abstract class, in persistence, and not overridden in the ORM. I manage to circumvent that by using `@method`, but then you have https://github.com/vimeo/psalm/issues/5786 that prevents me from continuing to do so.

**Comment by muglug** [comment]
That’s unsafe in a number of ways, I think. It’s a no from me.

**Comment by muglug** [comment]
Unless this works in Hack, which I doubt.

**Comment by muglug** [comment]
From Hack:

```
Naming[2047] T is a type parameter. Type parameters cannot take type arguments (e.g. T<int> isn't allowed) [1]

static.hack:5:77
    3 | interface ClassMetadataFactory<T as ClassMetadata>
    4 | {
[1] 5 |     public function getMetadataFor<T2 as object>(classname<T2> $className): T<T2>;
    6 | }
```

**Comment by greg0ire** [comment]
Ok, fair enough.
