### ISSUE TITLE
Regression in switch() handling

### ISSUE THREAD

**Issue by SCIF** [vimeo/psalm#5789]
We've got new errors in our codebase after Shepherd checks. The simplified reproduction: https://psalm.dev/r/9675c244be Apparently, introduced here: https://github.com/vimeo/psalm/commit/836587ec1d57baf76e391716ab5b50875b1d141d

**Comment by muglug** [comment]
This is just in latest master, right?

**Comment by SCIF** [comment]
Thanks @muglug! Fixed!
