### ISSUE TITLE
Support substitution of meta-types

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#579]
Psalm treats two meta-types as unions of others:
 - `bool` (`true|false`)
 - `iterable` (`Traversable|array`)

But type substitutions (which happen occasionally when an `else` clause is missing in an `if` statement) don't currently support this properly.

```php
function foo(bool $b) : void {
  if (!$b) {
    $b = true;
  }
  
  if ($b) {}
}
```

Expected: `RedundantCondition`
Actual: no issue

```php
function foo(iterable $i): array {
  if (!is_array($i)) {
    $i = iterator_to_array($i, false);
  }
  
  return $i;
}
```

Expected: No issue
Actual: `InvalidReturnType`

**Comment by weirdan** [comment]
Thanks. It's not on getpsalm.org it appears, though.

**Comment by muglug** [comment]
It is now (I deploy to getpsalm.org manually, and sometimes I'm slow)
