### ISSUE TITLE
Can't find Wordpress built-in function __(

### ISSUE THREAD

**Issue by cjohansson** [vimeo/psalm#5791]
**How to reproduce**
Create `test.sh` file with contents:
```bash
composer require --dev vimeo/psalm;
wget https://wordpress.org/latest.tar.gz;
tar -zxf latest.tar.gz;
echo "<?php echo __('Here', 'test'); ?>" > wordpress/wp-content/plugins/test.php
echo '<?xml version="1.0"?><psalm><projectFiles><file name="wordpress/wp-content/plugins/test.php" /></projectFiles><extraFiles><directory name="wordpress/" /></extraFiles></psalm>' > psalm.xml;
./vendor/bin/psalm
```
Run in terminal `bash test.sh`

**Expected**
No warning about function `__()` not being defined

**Actual**
```shell
ERROR: UndefinedFunction - wordpress/wp-content/plugins/test.php:1:11 - Function __ does not exist (see https://psalm.dev/021)
?php echo __('Here', 'test'); ?>
```

**Comment by orklah** [comment]
May be related to https://github.com/vimeo/psalm/issues/3758

Do you know how wordpress adds this function to the global scope?

**Comment by cjohansson** [comment]
Yes the function definition is like this:

```php
/**
 * Retrieve the translation of $text.
 *
 * If there is no translation, or the text domain isn't loaded, the original text is returned.
 *
 * @since 2.1.0
 *
 * @param string $text   Text to translate.
 * @param string $domain Optional. Text domain. Unique identifier for retrieving translated strings.
 *                       Default 'default'.
 * @return string Translated text.
 */
function __( $text, $domain = 'default' ) {
	return translate( $text, $domain );
}
```
in `wordpress/wp-includes/l10n.php:288`

**Comment by cjohansson** [comment]
If you visit `index.php` the file flow seems to be like this

`index.php` -> `wp-blog-header.php` -> `wp-load.php` -> `wp-includes/load.php` -> `wp-includes/l10n.php`

**Comment by orklah** [comment]
@weirdan I remember you saying that function had to be included manually in the xml file but I'm not sure I remember in which context. Can you help here?

**Comment by weirdan** [comment]
Most likely that was about using [`<extraFiles>`](https://psalm.dev/docs/running_psalm/configuration/#extrafiles) to let Psalm know of global functions. Unlike classes, where we can rely on autoloading to figure out where the code is located there's no such mechanism for functions.

**Comment by orklah** [comment]
Thanks, I see that the whole wordpress dir has been pushed inside the <extraFiles> here so it should work...

@cjohansson Can you try running Psalm with `--debug-by-line` and check if you can spot wp-includes/l10n.php in there?

**Comment by cjohansson** [comment]
Yes the file is included there in two lines
```shell
Parsing /home/christian/Documents/psalm-test/wordpress/wp-includes/l10n.php
Scanning /home/christian/Documents/psalm-test/wordpress/wp-includes/l10n.php
```

**Comment by cjohansson** [comment]
Here is a link to the file on GitHub [https://github.com/WordPress/WordPress/blob/master/wp-includes/l10n.php#L288](https://github.com/WordPress/WordPress/blob/master/wp-includes/l10n.php#L288)

**Comment by orklah** [comment]
This is easily reproduced without wordpress. If you just create another file with a function and you put it in <extraFile> the result is the same.

After some debugging, I concluded that Psalm does not appear to try to add functions from there in its dictionnary. Not sure why.

**Comment by cjohansson** [comment]
I also tried using the autoloader argument but then it does not scan any files at all

```xml
<?xml version="1.0"?><psalm autoloader="wordpress/index.php"><projectFiles><file name="wordpress/wp-content/plugins/test.php" /></projectFiles><extraFiles><directory name="wordpress/" /></extraFiles></psalm>

**Comment by orklah** [comment]
Closing as stale

**Comment by XedinUnknown** [comment]
Do I understand correctly that currently, the solution is to add the file containing the function to `<stubs>`? Even if the directory containing it is already added to `<extraFiles>`?

**Comment by kkmuffme** [comment]
Afair this affects only functions - however there's a config flag now that will make the functions loaded via require/extra available in the calling context: https://psalm.dev/docs/running_psalm/configuration/#allfunctionsglobal
Didn't test this use case, but afaik this should solve the issue for extraFiles too
