### ISSUE TITLE
Using @psalm-type-import on Traits

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#5794]
Is it supported?

This does work: https://psalm.dev/r/a58ebfd0b4
This doesn't: https://psalm.dev/r/a8c4aae1af

**Comment by vasily-kartashov** [comment]
My bad

**Comment by franmomu** [comment]
hi, how did you make it work? I'm struggling with the same I think.

https://psalm.dev/r/6a27647b70

**Comment by vasily-kartashov** [comment]
https://psalm.dev/r/ccbd5f8212

The parser got offended by single `/*` instead of `/**`, in my case it was `@psalm-type-import` instead of `@psalm-import-type`.

**Comment by franmomu** [comment]
> https://psalm.dev/r/ccbd5f8212
> 
> The parser got offended by single `/*` instead of `/**`, in my case it was `@psalm-type-import` instead of `@psalm-import-type`.

🤦 thanks! I got the issue from PHPStan and seeing this example fail I thought Psalm didn't support that, but it works fine 👍 .
