### ISSUE TITLE
(array)string returns array<int, string> instead of list<string>

### ISSUE THREAD

**Issue by othercorey** [vimeo/psalm#5795]
This comes from trying to satisfy the new @psalm-var hints in laminas packages.

https://psalm.dev/r/71d8338586

Since the array value type is `string|list<string>`, the cast to array should always return `list<string>` type. There isn't a generic array returned from the cast since the value is always string.

```
/**
  @psalm-var array<string, list<string>>
  */
protected $headers = [];
    
/**
  @psalm-param array<string, string|list<string>> $headers
  */
public function addHeaders(array $headers): void {
    foreach ($headers as $key => $val) {
        $this->headers[$key] = (array)$val;
    }
}
```

**Comment by orklah** [comment]
simplified:
https://psalm.dev/r/a12c452233

**Comment by orklah** [comment]
Github failed to close this issue
