### ISSUE TITLE
Add editor url option

### ISSUE THREAD

**Issue by Jean85** [vimeo/psalm#5798]
PHPStan just released a patch with an `editorUrl` new options, that makes file names clickable in the terminal, and opens them in your editor of choice: https://github.com/phpstan/phpstan-src/pull/515

This is a huge benefit for a small improvement... Could we think of adding the same here on Psalm? Being able to jump to the exact line highlighted by errors would speed up the workflow by a long shot!

**Comment by weirdan** [comment]
That would better fit a machine-local config, and Psalm doesn't have local configs right now.
