### ISSUE TITLE
 LessSpecificReturnStatement: 'positive-int' is more general than the declared return type '1|2|3|null'

### ISSUE THREAD

**Issue by Legion112** [vimeo/psalm#5801]
https://psalm.dev/r/c30483b8ac

**Comment by weirdan** [comment]
You can replace `isset()` with `array_key_exist()`: https://psalm.dev/r/0d50492987

**Comment by weirdan** [comment]
However for known non-nullable arrays `isset()` should probably behave the same.

**Comment by orklah** [comment]
This was fixed
