### ISSUE TITLE
tidy cannot be cast to string

### ISSUE THREAD

**Issue by jaydiablo** [vimeo/psalm#581]
This code will cause psalm to throw an InvalidCast error:

```php
<?php
  
$tidy = new tidy();

$tidy->parseString('<html></html>');

//echo $tidy;

echo (string) $tidy;
```

If you remove the commented line, it also throws an error, just a different one:

>Argument 1 of echo expects string, tidy provided

According to the PHP manual, echoing the tidy object directly seems to be the acceptable usage:

```php 
<?php
ob_start();
?>

<html>
  <head>
   <title>test</title>
  </head>
  <body>
   <p>error<br>another line</i>
  </body>
</html>

<?php

$buffer = ob_get_clean();
$config = array('indent' => TRUE,
                'output-xhtml' => TRUE,
                'wrap' => 200);

$tidy = tidy_parse_string($buffer, $config, 'UTF8');

$tidy->cleanRepair();
echo $tidy;
?>
```

https://secure.php.net/manual/en/tidy.parsestring.php

There's not really any way to know this from the reflection information though:

> $ php --rc tidy
>Class [ <internal:tidy> class tidy ] {
>
>  - Constants [0] {
>  }
>
> - Static properties [0] {
>  }
>
>  - Static methods [0] {
>  }
>
>  - Properties [0] {
>  }
>
>  - Methods [19] {
>    Method [ <internal:tidy> public method getOpt ] {
>    }
>
>    Method [ <internal:tidy> public method cleanRepair ] {
>    }
>
>    Method [ <internal:tidy> public method parseFile ] {
>    }
>
>    Method [ <internal:tidy> public method parseString ] {
>    }
>
>    Method [ <internal:tidy> public method repairString ] {
>    }
>
>    Method [ <internal:tidy> public method repairFile ] {
>    }
>
>    Method [ <internal:tidy> public method diagnose ] {
>    }
>
>    Method [ <internal:tidy> public method getRelease ] {
>    }
>
>    Method [ <internal:tidy> public method getConfig ] {
>    }
>
>    Method [ <internal:tidy> public method getStatus ] {
>    }
>
>    Method [ <internal:tidy> public method getHtmlVer ] {
>    }
>
>    Method [ <internal:tidy> public method getOptDoc ] {
>    }
>
>    Method [ <internal:tidy> public method isXhtml ] {
>    }
>
>    Method [ <internal:tidy> public method isXml ] {
>    }
>
>    Method [ <internal:tidy> public method root ] {
>    }
>
>    Method [ <internal:tidy> public method head ] {
>    }
>
>    Method [ <internal:tidy> public method html ] {
>    }
>
>    Method [ <internal:tidy> public method body ] {
>    }
>
>    Method [ <internal:tidy, ctor> public method __construct ] {
>    }
>  }
>}

 This code is valid though (sorry, 3v4l.org doesn't have tidy available, so just ran locally):

```shell
php > $tidy = new tidy();
php >
php > $tidy->parseString('<html></html>');
php >
php > echo (string) $tidy;
<html>
<head>
<title></title>
</head>
<body>
</body>
</html>
php > echo $tidy;
<html>
<head>
<title></title>
</head>
<body>
</body>
```

**Comment by muglug** [comment]
Tidy doesn‘t have a `__toString` method. Instead it [casts strings to a specific value](https://github.com/php/php-src/blob/fa9ea3c9ebd8f3f781821fdc83a1bd6b38d866cd/ext/tidy/tidy.c#L776-L782), and that behaviour cannot be automatically picked up by Psalm.

I'd rather not add a workaround just for this lib - instead you can use [`tidy_get_output($tidy)`](http://php.net/manual/en/function.tidy-get-output.php) to get the same result.

**Comment by jaydiablo** [comment]
Apparently this also works:

```php
echo $tidy->root()->value;
```

```
php > echo $tidy->root()->value;
<!DOCTYPE html>
<html>
<head>
<title></title>
</head>
<body>
</body>
</html>
php > echo $tidy;
<!DOCTYPE html>
<html>
<head>
<title></title>
</head>
<body>
</body>
</html>
```

(This is after a `cleanRepair` call, which adds the doctype)

Thanks for the info/reply!
