### ISSUE TITLE
Detect properties written, but never read?

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#5810]
Other tools offer such a feature in some form:

- PHPStan has a way to [detect unused private properties](https://phpstan.org/blog/detecting-unused-private-properties-methods-constants).
- PHPStorm has a "Property usages have same access" inspection, that reports private properties that are:
    - written but never read
    - read but never written

I couldn't find an equivalent in Psalm, would this be an addition you'd be willing to make? Cheers!

**Comment by muglug** [comment]
Like this: https://psalm.dev/r/217e2d379b

**Comment by muglug** [comment]
Chore: https://github.com/vimeo/psalm/commit/4f9067f5c88679d859eeb0c6929ae7c8c395f041

**Comment by orklah** [comment]
Awesome :)

**Comment by BenMorel** [comment]
Wow, thank you so much @muglug, I couldn't expect any better or faster ;-)

Looking forward to using it! :tada:

**Comment by BenMorel** [comment]
Looks like this doesn't work yet: https://psalm.dev/r/4e7c6e421d

Even though the related commit has been released now. Any reason why?

**Comment by orklah** [comment]
@BenMorel it works, as soon as Psalm can see at least one usage of the class and with the right config enabled: https://psalm.dev/r/680a180631

**Comment by BenMorel** [comment]
@orklah What's the right config? We use Psalm level 1, and Psalm never detects an unused private property, even when the class is in use.

Is it because these classes are injected via DI, so never instantiated via their constructor explicitly?

**Comment by orklah** [comment]
@BenMorel do you have findUnusedCode="true" in your config?

I don't think the DI is an issue, Psalm doesn't look for explicit instantiation, it looks for any method call, so as long as Psalm doesn't tell you to get rid of the class completely, it should also detect unused properties

**Comment by BenMorel** [comment]
@orklah Sorry, I didn't know that some inspections had to be enabled explicitly. I thought that level 1 had all of them enabled.

It works fine now, thank you!
