### ISSUE TITLE
Bug: MissingConstructor when property set in constructor via setter

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#5812]
Example: https://psalm.dev/r/7738f35d08

**Comment by orklah** [comment]
Psalm is right, you made a typo in the constructor name:
https://psalm.dev/r/65595e6137

**Comment by vjik** [comment]
@weirdan please, reopen issue.
I'm fixed example: https://psalm.dev/r/d58a655b11

**Comment by weirdan** [comment]
@vjik This https://psalm.dev/r/d58a655b11 is unsafe as `setX()` could be overridden in a descendant. Make the setter `final` (or the whole class for that matter) and the issue will go away: https://psalm.dev/r/286c1d2b72
