### ISSUE TITLE
var annotation is lost when setting a value.

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#5818]
Hi @muglug @weirdan 

In https://psalm.dev/r/d2e5390ba6
The value is considered as `$this->date: DateTime&B`, but I would expect to keep `$this->date: DateTime`.

This behavior is causing me some errors like in https://psalm.dev/r/cd19a2fc83
The phpdoc of `$this->query` is ProxyQueryInterface but it's restricted to ProxyQueryInterface&MockObject by psalm.
Then `$this->datagrid = new Datagrid($this->query, ...)` is returning an error because it's not a `Datagrid<ProxyQueryInterface>` but a `Datagrid<ProxyQueryInterface&MockObject>`

I end up with a funny situation, adding 
```
assert($this->query instanceof ProxyQueryInterface);
```
to redefined the type of `$this->query`...

Would it be possible for psalm to respect the phpdoc `@var` ?

**Comment by orklah** [comment]
Simplified:
https://psalm.dev/r/2d40fcf08c

Psalm refuse `A&B` for a template defined as `A`. This should be accepted because it's a valid `A`. Not sure of the implications though

**Comment by VincentLanglet** [comment]
> Psalm refuse `A&B` for a template defined as `A`. This should be accepted because it's a valid `A`. Not sure of the implications though

I think this is refused for covariance reason.
If I use `@template-covariant T` it works, but I cannot for some others reasons.

But here, I don't care bout the `&MockObject` part. I'd like the variable to be considered as `ProxyQueryInterface` only.
I'd like the code to be considered like this one: https://psalm.dev/r/a1db4947c2

So I used 
```
    /**
     * @var ProxyQueryInterface
     */
    private $query;
```
and not 
```
    /**
     * @var ProxyQueryInterface&MockObject
     */
    private $query;
```

Then I don't want the `psalm-trace` to consider that `$this->query` is `ProxyQueryInterface&MockObject` if I told him it's not.

**Comment by orklah** [comment]
> I think this is refused for covariance reason.
> If I use `@template-covariant T` it works, but I cannot for some others reasons.

Yep, I'm still confused by template covariance. I don't see the difference between sending `1` to an `int` template and sending `A&B` to an `A` template. Yet only one of them works.

That said, you say you don't want to keep the most precise inferred type and want to keep the attribute type but it makes no sense for the vast majority of usages. Think about this code: https://psalm.dev/r/d3120c2d05. Widening the given type to match a property type would break this and many other codes.

**Comment by VincentLanglet** [comment]
> Think about this code: https://psalm.dev/r/d3120c2d05. Widening the given type to match a property type would break this and many other codes.

Do you have another example @orklah ?
Cause here you could just write 
```
$this->expectStdClass($object);
```

**Comment by orklah** [comment]
The source of the variable doesn't matter, only its type. Also you can't expect people to follow arbitrary code style rules that change the way the static analyzer interpret the type.

**Comment by VincentLanglet** [comment]
> Also you can't expect people to follow arbitrary code style rules that change the way the static analyzer interpret the type.

This is exactly what you're asking here, since 
https://psalm.dev/r/a1db4947c2
is valid.

I would have to write a new method
```
    public function createDatagrid(ProxyQueryInterface $query) {
        return new Datagrid($this->query);
    }
```
in order to have `$this->query` considered as `ProxyQueryInterface` (and not anymore as `ProxyQueryInterface&MockObject`).
Because writing directly `new Datagrid($this->query)` is invalid.

In your example
```
public function __construct(stdClass $object){
    	$this->object = $object;
        $this->expectStdClass($this->object);
    }
```
is a bad pattern, since if someone add some code
```
public function __construct(stdClass $object){
    	$this->object = $object;
        $this->foo();
        $this->expectStdClass($this->object);
    }
```
You then cannot be sure that `$this->object` is still a StdClass.

See https://psalm.dev/r/1fb5bd44fc.

So when you're using `$this->foo` you should only look at the phpdoc of the `foo` property.

**Comment by muglug** [comment]
You're basically asking for this to be treated as an error: https://psalm.dev/r/9e306303e8 I think? That's untenable for me

**Comment by VincentLanglet** [comment]
> You're basically asking for this to be treated as an error: https://psalm.dev/r/9e306303e8 I think? That's untenable for me

I understand this is a difficult choice.

But if I modify a little your example, I end up with a not working code, with no psalm error @muglug
https://github.com/vimeo/psalm/issues/5818#issuecomment-846598505

**Comment by VincentLanglet** [comment]
I messed up with the link.
Here my example: https://psalm.dev/r/62dba7c1b4

Seems like phpstan behave like psalm about this: https://phpstan.org/r/169d6601-175b-4972-909a-a30e5537c065
But there is an error if I call `$this->foo()` https://phpstan.org/r/b19910f1-b4d6-429f-9663-5c0aedd1dce1

At least I found a psalm bug ^^' 

But then, can I have a better way than writing
```
/** @var ProxyQueryInterface $query */
$query = $this->createMock(ProxyQueryInterface::class);
$this->query = $query;
$this->datagrid = new Datagrid($query);
```
in order to avoid the covariance error with the `new Datagrid` call ?
```

**Comment by muglug** [comment]
> At least I found a psalm bug

Not really — just a slightly different approach. If you want to guarantee that property types are maintained, turn off property memoisation: https://psalm.dev/r/face062b41

**Comment by muglug** [comment]
Here you can see that PHPStan behaves like Psalm if that config is set:
https://phpstan.org/r/136d3674-ad8d-45c9-93d6-472983972dad

BUT if the function has a non-`void` return type PHPStan allows it:
https://phpstan.org/r/79afc549-30c0-4c77-91c5-4d1b450b68cd

Psalm doesn't have this distinction of return types determining effects — instead the config flag determines behaviour for invalidating properties:
https://psalm.dev/r/1d8904c6f9 vs https://psalm.dev/r/a149b25e51

In the default scenario some invalidation can still occur if Psalm knows that some properties change:
https://psalm.dev/r/33967627dd

This change is not caught by PHPStan: https://phpstan.org/r/63fccf1a-b0e4-49c9-a67a-3a8bc354b0b5

**Comment by VincentLanglet** [comment]
And for my use case ?

Do I have to write this ?
```
/** @var ProxyQueryInterface $query */
$query = $this->createMock(ProxyQueryInterface::class);
$this->query = $query;
$this->datagrid = new Datagrid($query);
```

It would be nice to at least be allow to write
```
/** @var ProxyQueryInterface $this->query */
$this->query = $this->createMock(ProxyQueryInterface::class);
$this->datagrid = new Datagrid($query);
```

**Comment by muglug** [comment]
If this is your issue:

https://psalm.dev/r/510161e2e7

You can add a docblock: 

https://psalm.dev/r/60c0bff5e0
