### ISSUE TITLE
Question: callable marked as impure even tho it supposed to be pure

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#5833]
Hey there,

if I understand purity correct, the callable in the given example supposed to be pure:
https://psalm.dev/r/c8366edbd2

Is that supposed to be a bug or do I just miss-understood purity?

> A pure function is a function that, given the same input, will always return the same output and are side-effect free.

**Comment by orklah** [comment]
Your Foo object should be marked mutation-free, or else `$foo->id` may perfectly call `__get` and do all sorts of things.
https://psalm.dev/r/d1ae9067e2

**Comment by boesing** [comment]
Nice, thanks!
