### ISSUE TITLE
trait-string doesn't accept Trait::class strings

### ISSUE THREAD

**Issue by Slamdunk** [vimeo/psalm#5834]
https://psalm.dev/r/d341cf1e62

```php
/** @psalm-param trait-string $i */
function takesATrait(string $i): void {}
trait MyTrait {}

takesATrait(MyTrait::class);
```

### Output

```console
ERROR: InvalidScalarArgument - 11:13 - Argument 1 of takesATrait expects trait-string, MyTrait::class provided
```

**Comment by weirdan** [comment]
Not sure whether that is an issue. Docs say:

> Psalm also supports a trait-string annotation denote a trait *that exists*.

However you did not use `trait_exist()` to validate that, and if you did Psalm would not complain: https://psalm.dev/r/9d9bf8d7c8

More generally, though, why would you need to operate on traits at runtime?

**Comment by Slamdunk** [comment]
I was using it for PHPUnit `getObjectForTrait`, but now I opted for a more reliable `new class { use Trait; }`.

Thank you for the feedback though
