### ISSUE TITLE
PossiblyNullReference not possible

### ISSUE THREAD

**Issue by roukmoute** [vimeo/psalm#5836]
Hi,

I've just reported this kind of code: https://psalm.dev/r/157ae3cf00

But in fact it is not possible to have a null because it is initialized in `__construct`.

Thanks in advance!

**Comment by weirdan** [comment]
```php
class Bar extends Foo {
  public function __construct() {
    parent::__construct();
    $this->logger = null;
  }
}
```
breaks that assumption: https://3v4l.org/nRsqn
