### ISSUE TITLE
InvalidArgument for parameter with template of object

### ISSUE THREAD

**Issue by weph** [vimeo/psalm#5839]
Stumbled upon this while working on a symfony project.
There's already a ticket for the symfony plugin (https://github.com/psalm/psalm-plugin-symfony/issues/154), but I guess it's more of a general issue.

https://psalm.dev/r/fc5c021e82

**Comment by muglug** [comment]
This is by design.

Possible workarounds: https://psalm.dev/r/12e4919d62 and https://psalm.dev/r/a2c818dfaa
