### ISSUE TITLE
[InvalidArrayOffset] Cannot access value on variable  using a string offset, expecting class-string

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#584]
Not sure what is psalm trying to tell me, or what's wrong with this code

> Cannot access value on variable  using a string offset, expecting class-string

```php
<?php

class A {
  const F = [self::class => 'foo'];
  
  function bar(string $f): bool {
    return isset(self::F[$f]);
  }
}
```

**Comment by muglug** [comment]
Ah. Psalm has [a feature](https://github.com/vimeo/psalm/blob/master/docs/supported_annotations.md#class-constants) that allows you to specify all users of `bar` call it with an explicit `::class` constant.

But that also requires you to do the extra work of adding a `@psalm-param class-string $f` annotation, and that's unfair.

So I'll figure out how to get rid of this notice by default, or at least make it super clear how to fix.

**Comment by ostrolucky** [comment]
Ohh I like that feature!

Does it not respect inline annotation though? Given was simplified example, in my real use case it still screams after adding annotation. It's also weird it does that when string was pulled via get_class.

```php
foreach ($objects->getObjects() as $key => $object) {
    /** @psalm-param class-string $className */
    $className = get_class($object);
    if (isset(self::CLASSES_USING_CUSTOM_CALLBACK[$className])) {
      ...
    }
}

```

**Comment by muglug** [comment]
You want `@psalm-var` instead of `@psalm-param` there

**Comment by muglug** [comment]
You could also use `$object::class` I think, meaning you could remove the hint for Psalm.

**Comment by ostrolucky** [comment]
Indeed, it works with that! It should still infer this for all get_class calls though.

**Comment by muglug** [comment]
Definitely

**Comment by karser** [comment]
Does it literally has to be `class-string` or the class name I'm looking up?
I mean, `/** @psalm-var class-string $className */` or `/** @psalm-var \App\Entity\User $className */`?

**Comment by iluuu1994** [comment]
@karser It's literally `class-string` or `class-string<YourClassName>` if you know a common type:

https://psalm.dev/r/be96459a43
