### ISSUE TITLE
[LessSpecificReturnStatement] Punishes for more specific return type in docblock

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#585]
> LessSpecificReturnStatement - src/Entity/Company/Company.php:212:9 - The type 'Doctrine\Common\Collections\Collection' is more general than the declared return type 'Doctrine\Common\Collections\Collection<mixed, App\Entity\Survey\Survey>' for App\Entity\Company\Company::getActiveSurveys

```php
/**
 * @return Survey[]|Collection
 */
public function getActiveSurveys(): Collection
{
    return $this->surveys->filter(function (Survey $survey) {
        return $survey->getCompletedAt() === null;
    });
}
```

**Comment by muglug** [comment]
This is due to `Doctrine\Common\Collections\Collection::filter` having a return type of `Collection`. I'll try to come up with a decent solution to this. Hopefully I can do it within Psalm itself, without resorting to a plugin, with support for popular libraries in a properly-versioned format.

**Comment by muglug** [comment]
But to be clear, the issue (and message) is accurate.

**Comment by ostrolucky** [comment]
Oh wow, I did not infer at all this is because of mismatch between return type of Company::getActiveSurveys and Collection::filter. I really miss reference to Collection::filter method in that message.

Thanks for trying to tackle this issue!

**Comment by weirdan** [comment]
> Hopefully I can do it within Psalm itself, without resorting to a plugin,
Psalm template syntax seems to be able to express many of these cases, but is there a way to provide psalm with altered docblocks/types without changing the original library?

**Comment by muglug** [comment]
@weirdan not at the moment, but it’s pretty easy for me to add an API allowing users to shoehorn it in using that template syntax

**Comment by muglug** [comment]
I think this should be solved by plugins

**Comment by weirdan** [comment]
> I think this should be solved by plugins

I think this specific case is already handled by https://packagist.org/packages/weirdan/psalm-doctrine-collections

**Comment by muglug** [comment]
Awesome!
