### ISSUE TITLE
Checkstyle output not escaped correctly

### ISSUE THREAD

**Issue by schmengler** [vimeo/psalm#5865]
The checkstyle XML output may contain unescaped null bytes which cannot be parsed. I had a PhpUnit data provider like this:
```
    public static function invalidIds()
    {
        yield 'null byte' => ["\0"];
    }
```

which is rendered in checkstyle like this:
```
 <error line="123" column="28" severity="info" message="MissingReturnType: Method XXX::invalidIds does not have a return type, expecting Generator&lt;&quot;null byte&quot;, array{&quot;�&quot;}, mixed, void&gt;"/>
```

Literal escaping should be improved to not break the XML markup.

**Comment by schmengler** [comment]
@psalm-github-bot No because I cannot get checkstyle XML from the interactive sandbox

**Comment by weirdan** [comment]
Does it happen on `master` as well? #5846 (merged a couple of days ago) may have improved this.

**Comment by schmengler** [comment]
Tested it on master and it looks good! `&quot;\000&quot;` - Thank you!
