### ISSUE TITLE
PossiblyInvalidArrayAssignment on method which only change array via pointer

### ISSUE THREAD

**Issue by roukmoute** [vimeo/psalm#5867]
Hi,

I've just reported this kind of code: https://psalm.dev/r/20748fd80b

How can I remove thoses errors:

```
ERROR: PossiblyInvalidArrayAssignment - 56:9 - Cannot access array value on non-array variable $normalized['application'] of type object

ERROR: PossiblyInvalidArrayAssignment - 57:9 - Cannot access array value on non-array variable $normalized['log'] of type object

INFO: MixedArrayAssignment - 57:9 - Cannot access array value on mixed variable $normalized['log']['original']
```

Without adding something like:

```php
if (!is_array($normalized)) {
    throw new Exception();
}
```

?

PropertyAccessor comes from [Symfony](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/PropertyAccess/PropertyAccessor.php)

Thanks in advance!

**Comment by orklah** [comment]
You may try to propose phpdoc improvement to the interface or the implementation:
https://psalm.dev/r/c4b507a8d5
If it's not an option, you may want to create a stubs for this or suggest this in symfony psalm plugin
