### ISSUE TITLE
Recognition of non-empty-array by count()

### ISSUE THREAD

**Issue by a-nakano** [vimeo/psalm#5869]
Recognition of non-empty-array by count()

Even after the conditional branch `count($a) === 0` $a is recognized as an array.
Shouldn't it be recognized as a non-empty-array?

`count($a) ! == 0`, `$a === []` seems to be recognized correctly.

https://psalm.dev/r/38efb9b0b9

**Comment by weirdan** [comment]
Simplified a bit: https://psalm.dev/r/ed9b177794

Inverse of the non-empty assertion doesn't seem to be generated for the `else` branch.

**Comment by orklah** [comment]
`count($a) === 0` was not used to narrow the inferred type. With the PR above it will be the case although I'd recommend `$a === []` for clarity which was already supported
