### ISSUE TITLE
[TooManyArguments] Doesn't expect methods to utilize func_get_args

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#587]
This is how `andWhere` method in doctrine QueryBuilder looks like

```php
/**
 * @param mixed $where The query restrictions.
 *
 * @return self
 *
 * @see where()
 */
public function andWhere()
{
    $args  = func_get_args();
    $where = $this->getDQLPart('where');
    ...
    return $this->add('where', $where);
}
```

calling it with argument will result in following message

> ERROR: TooManyArguments - src/EventListener/SimpleKnpFilterSubscriber.php:49:9 - Too many arguments for method Doctrine\ORM\QueryBuilder::andWhere - expecting 0 but saw 1

Is there a way to configure psalm to tell it to listen to docblock and ignore missing argument in some methods, so I don't have to do it each time I call that method?

**Comment by ostrolucky** [comment]
I'm really impressed how quick you fixed this!

**Comment by muglug** [comment]
Let me know if it’s still broken. This was only configured for your own functions and methods. This fix extends the detection to library ones as well.

**Comment by ostrolucky** [comment]
Ok, so I monkey-applied the referenced patch. Unfortunately it doesn't seem to have any effect (And I confirmed it's in effect by adding `die()` and running it again). Please re-open this issue and tell me if you need any further information.

**Comment by muglug** [comment]
Run Psalm with `--clear-cache` and try again?

**Comment by ostrolucky** [comment]
No dime. I've run it previously with --no-cache

**Comment by weirdan** [comment]
Tried Psalm dev-master@95b5f205c45dfd4e0dccc4762fc9db4881acb3c6 - it indeed still fails with TooManyArguments

**Comment by muglug** [comment]
Sorry, I’ll actually fix later today

**Comment by mdeboer** [comment]
I can confirm that in 4.6.4 this still fails but it got a bit better. It doesn't pick up the `func_get_args()` as argument as it is currently used:

```php
public function orX($x = null)
{
    return new CompositeExpression(CompositeExpression::TYPE_OR, func_get_args());
}
```

As changing it to this works:

```php
public function orX($x = null)
{
    $args = func_get_args();
    return new CompositeExpression(CompositeExpression::TYPE_OR, $args);
}
```

So in this case it needs to check even deeper.

**Comment by 7ochem** [comment]
The Docblocks of the methods @mdeboer is referencing contain:

```
     * @param mixed ...$x
```

So maybe that's (also) something to work with?

**Comment by kissifrot** [comment]
Error also happens with the `select()` method

**Comment by weirdan** [comment]
@janopae please open a new issue. Chances are even if the symptoms are similar it's caused by a different root cause. A lot has changed in 6 years.
