### ISSUE TITLE
Assertion negation doesn't work inside generic context

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#5871]
Without generic context plsam negates assertion correctly: https://psalm.dev/r/54d962f958

With generic context incorrectly: https://psalm.dev/r/6a9d6ed02a

Here psalm tries remove `Valid<T>` from `Union`. But unsuccessfully. Because atomic type has `Valid<T:fn-insidegenericcontext>` as key, not `Valid<T>`.

https://github.com/vimeo/psalm/blob/36d670b9559eae0d5ce067d23e242aa589ea6311/src/Psalm/Internal/Type/NegatedAssertionReconciler.php#L233-L235

Why `fn-insidegenericcontext` is missing ?)

**Comment by whsv26** [comment]
Could you guys fix it pls?

**Comment by klimick** [comment]
Or give advice how to fix it

**Comment by whsv26** [comment]
It's frustrating to write something like [this](https://github.com/whsv26/functional/blob/fb125bc3c9d07f44ad75a9acb7d0b56e8edd14b5/src/Fp/Functional/Either/Either.php#L92), [this](https://github.com/whsv26/functional/blob/fb125bc3c9d07f44ad75a9acb7d0b56e8edd14b5/src/Fp/Functional/Either/Either.php#L122) and [this](https://github.com/whsv26/functional/blob/fb125bc3c9d07f44ad75a9acb7d0b56e8edd14b5/src/Fp/Functional/Either/Either.php#L181)
