### ISSUE TITLE
Invalid doctype for password_needs_rehash()

### ISSUE THREAD

**Issue by paragonie-security** [vimeo/psalm#5875]
```
ERROR: InvalidArgument - src/PasswordLock.php:169:45 - Argument 2 of password_needs_rehash expects int, "2y" provided (see https://psalm.dev/004)
        return password_needs_rehash($hash, PASSWORD_DEFAULT, $hashOptions);
```

https://www.php.net/manual/en/function.password-needs-rehash.php

This is not defined as an `int`.

**Comment by weirdan** [comment]
It was, before PHP 7.4. Psalm assumes the minimum PHP version allowed by your `composer.json`, and it's 7.3: https://github.com/paragonie/password_lock/blob/11ea1ae344e64c2b591f4cd7488d78d7632064f1/composer.json#L31

Use `--php-version=${{ matrix.php-versions }}` cli switch in your GH workflow to force Psalm to use the PHP version corresponding to the one used by you CI job.

**Comment by paragonie-security** [comment]
Thanks!
