### ISSUE TITLE
Cannot rule out types by checking for present key in array shape union

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5876]
https://psalm.dev/r/223af3cf9b

Having `array{a: string}|array{b: string}`, checking for `isset($arr['a'])` should narrow the type to `array{a: string}`

**Comment by weirdan** [comment]
That's not how Psalm interprets that union. See the trace output here: https://psalm.dev/r/8966f31aac

**Comment by simPod** [comment]
@weirdan hmm, I see. And is that correct behaviour? I'd declare `array{a?: string, b?: string}` if I meant it but I meant type union, either `a` or `b` 🤔  

I guess I need tests instead of types here.
