### ISSUE TITLE
psalm-type closure with variadic parameter:  InvalidDocblock - Unexpected token ... in docblock

### ISSUE THREAD

**Issue by tdtm** [vimeo/psalm#5878]
I can't seem to find the correct syntax to either:
- do @psalm-type for a closure/callable that includes variadic params
- make a nullable arg for a closure/callable that includes variadic params

When used as a param:
- This works as expected: `@param Closure(...mixed): string $closure`
 https://psalm.dev/r/b2b4f62ffc
- but if the closure is made nullable, it fails whether or not I attempt to wrap with () to avoid the ambiguity:
 https://psalm.dev/r/63cd6f483c

When used with `@psalm-type`, it fails regardless:
- https://psalm.dev/r/4511faa7a5 `@psalm-type ClosureType = Closure(...mixed): string`
- https://psalm.dev/r/d78840cf28 `@psalm-type ClosureType = callable(...string): string`
- https://psalm.dev/r/e2daf359f8 `@psalm-type ClosureType = (callable(...string): string)`

**Comment by tdtm** [comment]
For anyone coming across this, my [temporary workaround](https://waywardpreacher.com/wp-content/uploads/2018/02/ORlyTemporaryWorkarounds.jpg) has been to do:

```php
/**
 * @psalm-type ClosureType = Closure(mixed): string
 *   |Closure(mixed, mixed): string
 *   |Closure(mixed, mixed, mixed): string
 *   |Closure(mixed, mixed, mixed, mixed): string
 *   |Closure(mixed, mixed, mixed, mixed, mixed): string
 */
```
...etc, adding as many lines of this as needed. Far from ideal, super ugly, but allows you to still use the type alias.

Obviously the ideal solution is to dig into Psalm's parser and submit a PR to solve it 🙃

**Comment by weirdan** [comment]
Note that the canonic way to express a variadic type is `typename...` rather than `...typename`. The former works: https://psalm.dev/r/8ad6badf35, https://psalm.dev/r/c40231e0b3. The latter is also expected to work, but it doesn't in your case.

**Comment by tdtm** [comment]
Gosh I should have known/realized that! Thank you.
