### ISSUE TITLE
anonymous class triggers errors

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [vimeo/psalm#588]
Hello,

Using PHPUnit to test an abstract class by creating an anonymous class as an extension of the abstract class.

Within the anonymous class I define a couple things not in the abstract needed for the unit testing - I define a public array intended to emulate a key => value pair cache engine, and I define a method to retrieve a protected property.

Anyway psalm triggers on them as errors because they are not defined in the defined in the abstract class. Since this only seems to happen when defining an anonymous class and not when defining a regular class that extends an abstract class, I suspect it is a bug.

Repo where it happens: https://github.com/AliceWonderMiscreations/SimpleCache

**Comment by muglug** [comment]
Thanks – was an easy fix.
