### ISSUE TITLE
Inability to negate more than one assertion

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#5889]
Psalm can negate single assertion: https://psalm.dev/r/9a2a94531d

But what about double one https://psalm.dev/r/6503ba07bb
or even more triple one https://psalm.dev/r/eef449c5f2

What's the difference between all of them?

**Comment by weirdan** [comment]
`!(A & B) = !A || !B`. So taking your second example the only thing Psalm could possibly infer for the else branch is that one of (or both) variables are not `Valid`. Taken individually, either of them could be Valid (when the other one is not). So their types are quite obviously `Invalid|Valid`.

**Comment by weirdan** [comment]
Now if you had `if ($val1 instanceof Valid || $val2 instanceof Valid)` Psalm would be able to narrow types for the else branch to `Invalid`, because `!(A || B) = !A && !B`: https://psalm.dev/r/a2bccf7168

**Comment by klimick** [comment]
Thanks for lesson) @weirdan

**Comment by whsv26** [comment]
!(Valid && Valid) = !Valid || !Valid = Invalid || Invalid = Invalid
