### ISSUE TITLE
Psalm is losing type of array shape when setting a value.

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#5891]
https://psalm.dev/r/dfa14b0c90

This code works if I remove
```
$result[] = 1;
```
or change to
```
$result['foo'] = 1;
```

But it shouldn't consider `$result['_labels']` as possibly an int.

**Comment by orklah** [comment]
reduced to https://psalm.dev/r/99d243f287

Seems like using the push syntax to a KeyedArray transform it, but it should not be necessary

**Comment by orklah** [comment]
I've fixed that in a PR merged today. It's not the optimal fix for this issue, but the error is gone at least
