### ISSUE TITLE
`InvalidReturnType` false positive if all branches terminate abruptly

### ISSUE THREAD

**Issue by duskwuff** [vimeo/psalm#5893]
If a function with a non-`void` return type contains multiple branches which all terminate abruptly (e.g. by throwing an exception or calling a non-returning function like `exit`), Psalm will complain that "no return statements were found":

https://psalm.dev/r/b0dc2e3893

Oddly, the same error _does not_ appear if there are no branches surrounding the non-returning code:

https://psalm.dev/r/eff2b97f91

Psalm offers to fix this by changing the function to return `void`, but this causes additional failures if the function is a method whose signature requires a particular non-void return type.

**Comment by orklah** [comment]
Yeah, this is a current limitation of Psalm's flow module. The same happen with switch (see https://github.com/vimeo/psalm/issues/5835#issuecomment-849070029)

However, you can document in phpdoc that the method return `never`. It will make psalm understand what's going on and it will not clash with your current return type: https://psalm.dev/r/368b6cc307
