### ISSUE TITLE
MethodSignatureMismatch does not infer the type from phpdoc in child class

### ISSUE THREAD

**Issue by Snowfall022** [vimeo/psalm#5899]
In [this](https://psalm.dev/r/aecae498b8) snippet it properly works, but in my project I have this scan result:

```Scanning files...
Analyzing files...

░░

ERROR: MethodSignatureMismatch - src/ChildClass.php:13:39 - Argument 1 of ChildClass::doUpdate has wrong type 'array<array-key, mixed>', expecting 'array<array-key, int>' as defined by AbstractClass::doUpdate (see https://psalm.dev/042)
    protected function doUpdate(array $oldTemplateParameters, array $newTemplateParameters): bool


ERROR: MethodSignatureMismatch - src/ChildClass.php:13:69 - Argument 2 of ChildClass::doUpdate has wrong type 'array<array-key, mixed>', expecting 'array<array-key, int>' as defined by AbstractClass::doUpdate (see https://psalm.dev/042)
    protected function doUpdate(array $oldTemplateParameters, array $newTemplateParameters): bool


------------------------------
2 errors found
------------------------------
```

What could be the reason and how to force psalm to use my phpdoc?

**Comment by orklah** [comment]
Seems like Psalm ignored the phpdoc. Do you have any ParseError reported by Psalm? (If it can't read the doc, it fallbacks to the signature and `array` is `array<array-key, mixed>`

**Comment by Snowfall022** [comment]
@orklah there is no mention of ParseError in the report. Psalm 4.6.3, also repeats on 4.7.3. PHP 7.4

**Comment by orklah** [comment]
This is weird. We'd need to reproduce it somehow. Is your project public or can you make a reproducer on a github repo?

**Comment by orklah** [comment]
I'll take a look this afternoon. In the meantime, could you try to reduce the list of stubs until you identify which one cause the issue?

**Comment by Snowfall022** [comment]
@orklah any of them, actually. Reduced to single item.

**Comment by orklah** [comment]
It even reproduce when the only stub is actually an empty file, as long as there is `preloadClasses=true` in the stub xml tag.

**Comment by orklah** [comment]
This is actually a duplicate of https://github.com/vimeo/psalm/issues/5626 where @markrandall already analyzed the issue and came to the same conclusion :)
