### ISSUE TITLE
Incorrect signature for SessionHandlerInterface

### ISSUE THREAD

**Issue by christeredvartsen** [vimeo/psalm#5903]
It seems that the signatures for `SessionHandlerInterface` in the callmap does not match the PHP manual. There are some mismatches with regards to both types and variable names.

Class synopsis from [the manual](https://www.php.net/manual/en/class.sessionhandlerinterface.php):

```
SessionHandlerInterface {
  /* Methods */
  abstract public close ( ) : bool
  abstract public destroy ( string $id ) : bool
  abstract public gc ( int $max_lifetime ) : int|bool
  abstract public open ( string $path , string $name ) : bool
  public read ( string $id ) : string|false
  abstract public write ( string $id , string $data ) : bool
}
```

the current signatures found in [the callmap](https://github.com/vimeo/psalm/blob/master/dictionaries/CallMap.php):

```
'SessionHandlerInterface::destroy' => ['bool', 'session_id'=>'string'],
'SessionHandlerInterface::gc' => ['bool', 'maxlifetime'=>'int'],
'SessionHandlerInterface::open' => ['bool', 'save_path'=>'string', 'name'=>'string'],
'SessionHandlerInterface::read' => ['string', 'session_id'=>'string'],
'SessionHandlerInterface::write' => ['bool', 'session_id'=>'string', 'session_data'=>'string'],
```

Here is a link to psalm.dev with a dummy handler implementation with signatures according to the PHP docs where you can see the issue:

https://psalm.dev/r/afd42116f5

**Comment by weirdan** [comment]
Fixed in #5904 (thanks).
