### ISSUE TITLE
Don't should be error on concatenate with `null`

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#5906]
https://psalm.dev/r/77bdbf245e

PHP 7.4+ don't throw error on concatenate with `null`. Why psalm throws error?

**Comment by vjik** [comment]
I'm wrong.

**Comment by weirdan** [comment]
> Why psalm throws error?

Because it's what it designed to do - to flag wrong / risky / problematic code. That includes the code that may work, but just shouldn't be that way, like concatenating with non-strings.
