### ISSUE TITLE
List becomes mixed with array when used in closure

### ISSUE THREAD

**Issue by vpArth** [vimeo/psalm#5909]
https://psalm.dev/r/9971db4119

```php
/** @return list<string> */
function x() {
  $a = [];
  $foo = function() use (&$a): void {
  	$a[] = "x";
  };
  $foo();
    
  return $a;
}
```

Errors:
```
INFO: MixedArrayAssignment - 7:4 - Cannot access array value on mixed variable $a
INFO: MixedReturnStatement - 11:10 - Could not infer a return type
INFO: MixedInferredReturnType - 3:13 - Could not verify return type 'list<string>' for x
```

How should I deal with lists in the closure?

**Comment by muglug** [comment]
This is by design — passing variables by reference into closures is inherently unsound, so Psalm picks the widest type (`mixed`). Instead you can wrap the data in an object and Psalm will be happy.

**Comment by vpArth** [comment]
Is there any way to help psalm with that without introducing new entities(object suggested)?

https://psalm.dev/r/a9aef7fa89

**Comment by muglug** [comment]
Like this: https://psalm.dev/r/18638658ce
