### ISSUE TITLE
Document `value-of` and `key-of`types

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#5912]
These are mentioned at https://psalm.dev/docs/annotating_code/type_syntax/atomic_types/ but without any explanation of what they represent. I should be able to write the docs for them and make a PR.

There's also `T[K]` documented alongside them - I'm not sure what that is.

**Comment by weirdan** [comment]
That's indexed access type, similar to the one in TypeScript: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#keyof-and-lookup-types

**Comment by muglug** [comment]
Yeah, and I've _just_ fixed the implementation for indexed access (a previous change uncovered a bug and I skipped some breaking tests).

It enables this sort of behaviour: https://psalm.dev/r/0e8b8db7f8

**Comment by weirdan** [comment]
Documented now.
