### ISSUE TITLE
Variable loses type if bound to closure, both by reference or by value

### ISSUE THREAD

**Issue by remorhaz** [vimeo/psalm#5916]
I've found weird behavior of a variables being bound to closure using `use ()` syntax. See the attached code snippet:

https://psalm.dev/r/bdf5b3db37

In first case, we pass `$a` by reference and `@psalm-trace` reports `mixed`, messing all the following code. I've failed to found the workaround for this case other but suppressing `MixedOperand` after hinting the type explicitly with `@var`.

In second case, we pass `$b` by value and `@psalm-trace` reports correct `int` value; but result seems to evaluate to `mixed`.

**Comment by muglug** [comment]
The second works, the first is by design — passing values by reference is inherently unsound (other tools allow it, but also allow unsound behaviour). Instead wrap the values in an object or similar.

**Comment by hrombach** [comment]
@muglug if this behavior is by design, maybe it would make sense for psalm to point that out. 

The error message the user gets makes it read like a bug in psalm.
