### ISSUE TITLE
Using strip_tags() incorrectly prevents taint detection

### ISSUE THREAD

**Issue by mmcev106** [vimeo/psalm#5918]
Taint detection does not report a vulnerability in the following code, even those there is one.  Passing a value of `');alert('injection');//` as the `param` excercises it:
```
<?php
$param = strip_tags($_GET['param']);
?>

<script>
    console.log('<?=$param?>')
</script>
```

If this is fixable and anyone can give me a tiny bit of guidance to get me started, I'd be willing to take a crack at it.

**Comment by mmcev106** [comment]
That demo feature doesn't seem to test taint detection...

**Comment by mmcev106** [comment]
@muglug, would you mind adding a little context as to why this was closed?  Adding javascript taint detection does sound difficult, but not necessarily impossible...

**Comment by orklah** [comment]
@mmcev106 It was implemented in https://github.com/vimeo/psalm/commit/47bf5ed56797e5605eeb656bd7ec98bb87650d8f. It is now documented here: https://psalm.dev/docs/running_psalm/issues/TaintedTextWithQuotes/

**Comment by weirdan** [comment]
> Can you explain how strip_tags is not sufficient here please?

it's unsafe in html as well: https://psalm.dev/r/52ba6d8da9 (https://3v4l.org/RF0OR).

Overall, `strip_tags()` should never be relied upon to sanitize output for HTML.

**Comment by mmcev106** [comment]
Awesome.  Thank you all!

**Comment by ohader** [comment]
Hm... just stumbled over this issue - I still need to have a closer look into the new `TaintedTextWithQuotes`
Seems like `htmlspecialchars` (without `ENT_QUTOES`) produces some false-positives here...

https://psalm.dev/r/890dbfd386

Sure, I'll create a new issue once I managed to dig deeper.

**Comment by weirdan** [comment]
That's not a false positive if you have single-quoted attributes in your html: https://3v4l.org/5P0t9 (Psalm is unaware of the context, so it must assume you could).

**Comment by ohader** [comment]
> That's not a false positive if you have single-quoted attributes in your html: https://3v4l.org/5P0t9 (Psalm is unaware of the context, so it must assume you could).

Perfectly fine for `... class='<?= $param ?>'` - but I did not see a problem with `... class="<?= $param ?>"` (double-quoted). Am I missing something here?

**Comment by weirdan** [comment]
Psalm doesn't analyse code outside of PHP tags, at all, and neither it understands HTML. So to play safe it forbids echoing any data that may contain any quote.
