### ISSUE TITLE
MissingPropertyType errors when I use phpVersion="7.3"

### ISSUE THREAD

**Issue by fedorovmixail** [vimeo/psalm#5922]
Hi. I use phpVersion="7.3" option in psalm.xml, but I have such error
```
ERROR: MissingPropertyType - src/main.php:8:10 - Property Main\Worker::$foo does not have a declared type - consider int (see https://psalm.dev/045)
  public $foo = 5;
```

Although typed properties are available since php 7.4

**Comment by orklah** [comment]
Psalm does not really discriminatebetween a type in code and a type in phpdoc, however it needs to have one

**Comment by fedorovmixail** [comment]
Thanks, I understood it, but such behavior seems isn't obvious.
Thanks again!)
