### ISSUE TITLE
Issue labels

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#5928]
Hi,

I'm creating this issue to suggest adding new labels to categorize issues based on the (probable) source of the issue.

It would help categorize, find similar issues or duplicates and see on a glance which module needs work

So far I came up with those labels:
- internal assertions
- userland assertions
- type reconciliation
- templates
- internal stubs/callmap
- taint
- refactor
- flow inference
- psalter
- parser
- type inference
- plugins
- return type providers
- internal error
- storage error
- documentation

Some probably overlap with others but I think it could be a good starting point

**Comment by muglug** [comment]
`userland assertions` => `docblock assertions` perhaps?

`internal assertions` and `type reconciliation` are _usually_ one and the same — I'd scrap the former in favour of the latter.

`taint` should be `taint analysis`

`flow inference` and `type inference` should probably be rolled into a `control flow` label — issues like `switch` statements not being treated correctly, or `try` statements having funky control flow are good candidates.

`storage error` and `internal error` might be rolled into a `causes crash` category

**Comment by orklah** [comment]
Thanks for the improvements! Could you create the labels? I can't create new ones

**Comment by weirdan** [comment]
I'll do that

**Comment by weirdan** [comment]
Added:
![image](https://user-images.githubusercontent.com/57403/121785219-2a13cf00-cbc1-11eb-9e33-2cca1783dc9f.png)

Do you have any color preferences or would you like to add label descriptions?

**Comment by orklah** [comment]
Seems fine like that for now :)

I'm closing the issue as I consider this solved!

Thanks!

**Comment by weirdan** [comment]
We probably would need another label for issues that are caused by user misunderstanding how Psalm works, e.g. template invariance. Something like `by design`, `question`, `faq`, etc. And maybe pin some of them.

**Comment by weirdan** [comment]
I've added `question` label.
