### ISSUE TITLE
[MismatchingDocblockReturnType] I don't get how this works

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#593]
```php
class Foo {
  /** @var \stdClass[]|\ArrayObject */
  public $bar;
  
  /**
   * @return \stdClass[]|\ArrayObject
   */
  public function getBar(): \ArrayObject
  {
    return $this->bar;
  }
}
```

In real use case, this is a problem for Doctrine Collections, where docblock is specified like this
```php
/**
 * @return RoomItem[]|Collection|Selectable
 */
public function getRoomItems(): Collection
{
    return $this->roomItems;
}
```

> ERROR: MismatchingDocblockReturnType - src/Entity/Item.php:75:8 - Docblock has incorrect return type 'Doctrine\Common\Collections\Collection<mixed, App\Entity\RoomItem>|Doctrine\Common\Collections\Selectable', should be 'Doctrine\Common\Collections\Collection'

If I change it to 

```php
/**
 * @return RoomItem[]|Collection
 */
public function getRoomItems(): Collection
{
    return $this->roomItems;
}
```

error is no longer shown, even though it's pretty same like original example code

**Comment by muglug** [comment]
What is the actual PHP-asserted type of `$this->roomItems`?

**Comment by ostrolucky** [comment]
```php
/**
 * @var RoomItem[]|Collection|Selectable
 *
 * @ORM\OneToMany(targetEntity=RoomItem::class, mappedBy="item")
 */
private $roomItems;
```

**Comment by muglug** [comment]
No, I mean what does `get_class($this->roomItems)` return?

**Comment by ostrolucky** [comment]
In doctrine, such collections are in reality ArrayCollection or PersistentCollection classes, depending if they were already fetched from database

**Comment by muglug** [comment]
Ok, so to make Psalm happy you'd need to change the docblock to

```
@param ArrayCollection<mixed, RoomItem>|PersistentCollection<mixed, RoomItem>
```

When I add support for [intersection types in docblocks](https://github.com/vimeo/psalm/issues/594) you'd use this instead:

```
@param Collection<mixed, RoomItem>&Selectable
```

**Comment by weirdan** [comment]
`@param ArrayCollection<mixed, RoomItem>` - wait, is this a generic syntax in docblocks? Does psalm support this? If so, it's missed from the docs and needs to be added there.

**Comment by weirdan** [comment]
Or was that psr-5 collection syntax, @muglug ?

**Comment by muglug** [comment]
PSR-5 yes

**Comment by muglug** [comment]
Closing because this message is correct

**Comment by ostrolucky** [comment]
Not sure, because first example still triggers this error. PHPdoc is here only to say what kind of iterable this is and psalm understands that. But this rule sometimes doesn't and says it's not same as native return type, hence must be wrong.

**Comment by muglug** [comment]
The type you gave is
```
@return RoomItem[]|Collection|Selectable
```

When `allowPhpStormGenerics="true"` in the config, Psalm turns that into

```
@return Collection<mixed, RoomItem>|Selectable
```

The function typehint is just `Collection`, so Psalm thinks there's a mismatch. And indeed, that `@return` type *is* wrong - the function doesn't return a `Collection` *or* a `Selectable` - it returns a `Collection` *and* a `Selectable`.

**Comment by ostrolucky** [comment]
What about this though? This is what I called first example

```php
class Foo {
  /** @var \stdClass[]|\ArrayObject */
  public $bar;
  
  /**
   * @return \stdClass[]|\ArrayObject
   */
  public function getBar(): \ArrayObject
  {
    return $this->bar;
  }
}
```

**Comment by muglug** [comment]
That works fine: https://github.com/vimeo/psalm/commit/def0d87782c8633bcc6bb62af4fe71bade5aa223

**Comment by ostrolucky** [comment]
Ok so maybe just website needs to be updated?

![image](https://user-images.githubusercontent.com/496233/37559327-267b2894-2a24-11e8-9906-109d2d84512a.png)

**Comment by muglug** [comment]
The website doesn't have that config option (`allowPhpStormGenerics="true"`) enabled because it's terrible, and breaks the notion of union types.

**Comment by muglug** [comment]
`stdClass[]|ArrayObject` implies the variable can be an `array`, but it actually cannot ever be an `array`.

**Comment by ostrolucky** [comment]
Ahh fair enough

**Comment by muglug** [comment]
`@param Collection<mixed, RoomItem>&Selectable` should work now
