### ISSUE TITLE
False positive for PossiblyNullReference and getter method returning nullable object

### ISSUE THREAD

**Issue by michalsalon-mall** [vimeo/psalm#5934]
When a getter method returning a nullable object has a method called on returned object, psalm complains about `PossiblyNullReference` even with a check that the getter does not return a `null` value just before the call (null-safe accessor `?->` works, but I must support PHP 7.4).

https://psalm.dev/r/5279e0f89d

My only guess why this might be happening is, that psalm sees a possibility of the return value changing between calls, but that could also be the case when accessing a nullable property (if there is magic involved), which does not cause `PossiblyNullReference`.

**Comment by michalsalon-mall** [comment]
Also, it seems to only happen when using inherited property (whether the method is overridden or not, does not matter, only the property): https://psalm.dev/r/0440b473f9

**Comment by orklah** [comment]
Consider the following code:
https://psalm.dev/r/dc9b576b5e

Psalm can't consider that getDummyObject() return will always be coherent, so it can't assume the value is never null when you call the method a second time.

You can either: 
- use a local variable, 
- declare your getter mutation-free: https://psalm.dev/r/8dfd55b25f
- use the psalm config to memoize simple method calls: https://psalm.dev/r/0ad9d6b4d8 (be aware that this applies to your entire code so it may have side effects in another piece of code that needs to reset the return type of a method)

(In your second link, Psalm is able to figure out there is a property behind the method. The error come back if we uncheck "Memoize property assignments": https://psalm.dev/r/4257e5d6c2 )
