### ISSUE TITLE
Support intersection type parsing in docblocks

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#594]
e.g. `@psalm-param FirstInterface&SecondInterface`

**Comment by ostrolucky** [comment]
Not sure if you should do this. Currently, this syntax is phpstan specific invention. It's very non-standard, nothing outside phpstan world supports it. Phpstan dev told me they might help to add such thing to PSR-5 when it becomes active again. Maybe you should join the gang.

**Comment by muglug** [comment]
> Maybe you should join the gang.

Yup, I've offered to work on PSR-5: https://groups.google.com/d/msg/php-fig/ywaSYo_tXdc/WwzgsrXSAAAJ

**Comment by muglug** [comment]
>  Currently, this syntax is phpstan specific invention

No it's not. Intersection types have been around for a while e.g. https://flow.org/en/docs/types/intersections/

**Comment by ostrolucky** [comment]
I stand corrected. Didn't check other languages. 

I just know that ondrej couldn't pin point what else except phpstan supports this syntax and I had issues with various tools not working with this syntax (phpstorm), or outright crashing (phpDocumentor)
