### ISSUE TITLE
`MethodSignatureMismatch` when concrete class implements interface with return type `static`.

### ISSUE THREAD

**Issue by simondeeley** [vimeo/psalm#5946]
Given the following pseudo-code:

```php
interface FooInterface
{
    public static function newFoo(): static;
}

class Foo implements FooInterface
{
    public static function newFoo(): static
    {
         $foo = new static();
         return $foo;
    }
}
```

PHP natively resolves the inheritance and understands that when `FooInterface` is implemented it, the method `FooInterface::newFoo` will return an instance of the concrete class, in this case an instance of `Foo`.

However, Psalm reports  `MethodSignatureMismatch` citing `Foo::newFoo` returns `Foo` but was expecting `FooInterface`, which is technically true but it should also not report any error due to the interface being implemented correctly as far as PHP is concerned.

**Comment by orklah** [comment]
Closing as non reproduced
