### ISSUE TITLE
Document alternate types in list?

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#5947]
When using the QueryBuilder of Doctrine ORM, you may end up with a list of 2 alternate types as a result:

```php
$query = $entityManager->createQueryBuilder()
    ->select('a')
    ->addSelect('b')
    ->from(A::class, 'a')
    ->innerJoin(B::class, 'b', Join::WITH, 'b.a = a')
    ->getQuery();

$results = $query->getResult();
```

Here, `$results` contains a list of [`A`, `B`, `A`, `B`, `A`, `B`, ...], always in this order. I could type-hint it as `list<A|B>`, but this does not accurately reflect the contents of the array.

**Is there a better way to document it?** If Psalm could understand it so that this:

```php
foreach (array_chunk($results, 2) as $chunk) {
    /** @psalm-trace $chunk */
}
```

would yield `array{A, B}`, it would be fantastic.

If it's not possible, it's OK, I guess this is an edge case.

**Comment by weirdan** [comment]
Is there a precedent in some other language? This looks fairly esoteric.

**Comment by muglug** [comment]
yeah definitely too esoteric to type it as anything but `list<A|B>`

**Comment by BenMorel** [comment]
Fair enough. Thanks for replying!
