### ISSUE TITLE
Iterating over \DatePeriod objects does not automatically yields \DateTimeInterface typed values

### ISSUE THREAD

**Issue by flaviovs** [vimeo/psalm#5954]
See: https://psalm.dev/r/e0a3a36944

Add `/** @var \DateTimeInterface $day */` right above the `foreach`  and the errors go away.

**Comment by weirdan** [comment]
So basically it should be stubbed along the lines of:
```php
/**
 * @template-covariant T of DateTimeInterface
 * @template-extends IteratorAggregate<int, T>
 */
class DatePeriod {
    /** @param T $start */
    public function __construct($start, $interval, $end, $options) {}
}
```
(template is needed because `DatePeriod<DateTime>` yields `DateTime` while `DateTime<DateTimeImmutable>` produces `DateTimeImmutable`).

**Comment by weirdan** [comment]
Type parameter is defined by `$start` type, unless `__construct(string $isostr, int $options = 0)` signature is used, in which case it yields `DateTime`.

**Comment by Rarst** [comment]
Seems related to template bits, I started to get `DatePeriod<DateTimeImmutable> has too many template params, expecting 0` in a library dependency that hints that.

https://psalm.dev/r/880b8ac85d

**Comment by Rarst** [comment]
Possibly related PHP core change:

> 8.0.0 `DatePeriod` implements `IteratorAggregate` now. Previously, `Traversable` was implemented instead.
