### ISSUE TITLE
Typo in 4.8.0 release notes?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#5959]
https://github.com/vimeo/psalm/releases/tag/4.8.0

> Psalm’s taint analysis can also help detect this general class of issues, but a `literal-int` type allows the type-checker to provide guarantees much earlier in the process.

Should this say `literal-string` instead of int to match the example (execute_sql takes literal-string)? Or say both, since both types were added.

EDIT: Also, https://psalm.dev/docs/annotating_code/type_syntax/scalar_types/#literal-string is documented, but not literal-int

**Comment by muglug** [comment]
Fixed, thanks
