### ISSUE TITLE
Wrong line numbers reported in some cases

### ISSUE THREAD

**Issue by codyhatch** [vimeo/psalm#5962]
I'm not quite sure what triggers it, but here's a minimal test case: https://psalm.dev/r/ed2836fc4b

The error analysis seems correct enough, but the issue is the *location reference*. Psalm reports the issue as being on line 3, column 12. But here line 3 is actually the comment open block, and doesn't *have* 12 characters. I'm pretty sure this is intended to refer to line 4.

This is a particular issue if you're trying to feed the results into Sonarqube, since the scanner entirely crashes when given an invalid column reference.

If you compare to https://psalm.dev/r/76ee877256 it appears it's not an off by one issue, but rather that it's reporting the error in the doc block as belonging to the first line of the docblock. I'd assume that's wrong (it should report the line of the `@method` annotation, not the line the comment starts on), but it's got to be wrong for it to mix a line reference with a column reference from an entirely different line, right?

**Comment by weirdan** [comment]
When running locally it's fairly obvious that it should be reported on the `@method` line: 
![image](https://user-images.githubusercontent.com/57403/122702147-6f866b00-d257-11eb-87be-c472332e9b3b.png)
