### ISSUE TITLE
Broken type assertion in case of null coalescing

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#5966]
https://psalm.dev/r/7496fb6493

**Comment by orklah** [comment]
Also doesn't work with a cast: https://psalm.dev/r/70e50f3030

This would be pretty complex to add though, PHPStan doesn't support that either: https://phpstan.org/r/03683664-8da5-48da-98c7-f7e058246209

It would open the way to too much complexity (?: would follow soon after)

You can bypass that by using empty or checking both null and 0 separately
