### ISSUE TITLE
phar file missing for 4.8.1 release (psalm/phar repo).

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#5968]
https://github.com/psalm/phar/releases is missing 4.8.0 and 4.8.1

**Comment by muglug** [comment]
Sorry, 4.8.1 release created

**Comment by ADmad** [comment]
https://github.com/vimeo/psalm/releases/tag/4.8.1 still doesn't have the phar file listed under assets and trying to update psalm using phive gives `[WARNING]  psalm 4.8.1: No downloadable PHAR`.

**Comment by weirdan** [comment]
That's why this ticket is titled 'psalm/phar repo'

**Comment by ADmad** [comment]
Well you renamed the title :slightly_smiling_face:. 

To put it simply my ticket was about the non-existent phar file for the 4.8.1 release. The ticket was closed with the comment `4.8.1 release created` which made me think the phar file was created, which doesn't seem to be the case. 

So IMHO opinion this issue was prematurely closed.

**Comment by ADmad** [comment]
I see now that my issue is a duplicate of #5703 which is still open, so NVM, I'll just subscribe to that.
