### ISSUE TITLE
Check if XML schema and default configs are valid

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#597]
Something in xsd and xml is not valid

![image](https://user-images.githubusercontent.com/496233/37566653-80714d5e-2abc-11e8-82c3-2d9ab7a27848.png)

I assume xsd must contain attributes `xmlns` and `targetNamespace` and xml must contain `xmlns` attribute, as that's what helped in my case to add. But I don't usually use XML, so I don't really know if that's proper solution.

To reiterate, this is what helped in my case to solve this issue:

psalm.xml:
```diff
 <psalm
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
-        xsi:schemaLocation="vendor/vimeo/psalm/config.xsd"
+        xmlns="urn:Test.Namespace"
+        xsi:schemaLocation="urn:Test.Namespace vendor/vimeo/psalm/config.xsd"
```
config.xsd:
```diff
-<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
+<xs:schema 
+        xmlns:xs="http://www.w3.org/2001/XMLSchema" 
+        elementFormDefault="qualified" 
+        targetNamespace="urn:Test.Namespace"
+        xmlns="urn:Test.Namespace">
```

Namespace obviously will need to be changed.

**Comment by mrmark** [comment]
Ran into the same problem and came up with the same solution (just with different namespace).  Another big bonus of doing this is that PHPStorm will then validate the config file and offer autocompletion for all tags and attributes, big win!

Symfony does the same thing for their XML files, EG dependency injection XML files:
```xml
<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
```

And then in http://symfony.com/schema/dic/services/services-1.0.xsd:
```xml
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns="http://symfony.com/schema/dic/services"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     targetNamespace="http://symfony.com/schema/dic/services"
     elementFormDefault="qualified">
```

**Comment by ostrolucky** [comment]
@muglug you have used placeholder prefixes and forgot to modify XSD. I am working on this right now, let me create PR :)

**Comment by muglug** [comment]
OK thanks, I clearly don't know what I'm doing here.
