### ISSUE TITLE
MissingPropertyType not emitted

### ISSUE THREAD

**Issue by thomasbley** [vimeo/psalm#5974]
current: no error
expected: INFO: MissingPropertyType - Property test::$test does not have a declared type

https://psalm.dev/r/2971313991

**Comment by weirdan** [comment]
This is by design, in this case Psalm infers the type from the assignment in constructor. You should be able to turn it off with `inferPropertyTypesFromConstructor` flag in `psalm.xml`, but currently the flag is missing from the schema (and documentation).

**Comment by thomasbley** [comment]
Would be good to have it in the schema and the documentation!

Using: inferPropertyTypesFromConstructor="false"

I get:
```
Problem parsing psalm.xml:
  Error on line 22:
    Element '{https://getpsalm.org/schema/config}psalm', attribute 'inferPropertyTypesFromConstructor': The attribute 'inferPropertyTypesFromConstructor' is not allowed.
```

**Comment by thomasbley** [comment]
Thank you!
