### ISSUE TITLE
Ignore line ending characters when matching code issues against baseline

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#5979]
I was puzzling over why my Psalm run was passing locally, but had many errors in CI. The answer was that I had autocrlf turned on in git settings, so my local PHP files were in a different format to those generated in the CI environment. Specifically I had many `<code>` elements in the baseline that ended with `&#13;</code>`

I wonder if it would be worth making Psalm ignore the `&#13;` (carriage return), and also not add it when generating the baseline.

**Comment by bdsl** [comment]
@psalm-github-bot sorry, psalm.dev doesn't support baselines.

**Comment by weirdan** [comment]
Remind me how that works: you have CR LF line endings locally, but CR is stripped during commit and reinstated during checkout, right? So CR is never added to the repository and thus is missing on machines with autocrlf disabled?

**Comment by bdsl** [comment]
In my case I had LF endings locally on a linux machine and CR LF endings on the PHP files in the repo. Git with autocrlf=true converts the php files to my local format on checkout.

Then when I generate a baseline file locally it doesn't match the files as they are in the repository, so Psalm reports errors in the CI environment where autocrlf is set to false.

**Comment by weirdan** [comment]
But if you don't have CRs locally how they ended up in the baseline (&#13; is encoded CR)?

**Comment by weirdan** [comment]
Also, [docs say `autocrlf`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf) always causes files to be stored in the repo with LF line endings.

**Comment by bdsl** [comment]
Hmm, I'm not 100% sure now - looks like at list some of the files must have had CRLF on my local - quite possibly there was a mixture of both format, maybe between files maybe even within one file. I'm not entirely sure - I just know that I fixed the issue by generating a new baseline within the CI executor and committing that.

**Comment by reeperbahnause** [comment]
Hey,  
I'm facing the same behavior.   
In our case the line ending in the git repo is `LF`. The psalm baseline file was created on a linux dev environment.  
Once I checkout the branch for testing psalm on windows the line endings will be changed to `CRLF` because of the git client configuration `autocrlf`
Running psalm on windows won't match the baseline rules because of the extra character (for example at the end of a function definition)

Here is an example of the linux baseline file vs the windows baseline file:

![image](https://user-images.githubusercontent.com/14199872/123421376-0a1add00-d5bd-11eb-81c1-52d7365d57a8.png)

**Comment by bdsl** [comment]
@weirdan I'm happy to try and PR an implementation for this if you think it's the right thing to do for Psalm.

**Comment by weirdan** [comment]
@bdsl sure, please do

**Comment by bdsl** [comment]
Will try and get that in in the next few days.

**Comment by bdsl** [comment]
@weirdan btw, is there a set policy on when to close Psalm issues? Might it make sense to leave it open until there's a release available with the fix?

**Comment by weirdan** [comment]
That would require some additional automation, while closing them when PR is merged is a Github's native functionality.
