### ISSUE TITLE
Psalm get wrong property type (Symfony)

### ISSUE THREAD

**Issue by mirkhamidov** [vimeo/psalm#5987]
Psalm reads property of the `Kernel.php ($this->environment)` differently on branch builds and on my and Colleagues workstations.

Intro:
```php
# Kernel.php
class Kernel extends BaseKernel
{
    protected function configureRoutes(RoutingConfigurator $routes): void
    {
        $routes->import(sprintf('../config/{routes}/%s/*.yaml', $this->environment));
        ...
    }
}
```

* php-storm reads `this->environment` correct, as a string
* on my local-machine and on feature branch in CI of Bamboo im getting error (on my Colleagues local-machines there is no issues), 
<img width="1551" alt="2021-06-23_15-52-05" src="https://user-images.githubusercontent.com/2736223/123108769-fd6e7b80-d43a-11eb-9bea-98cdc4562208.png">

* and if add cast to string on "develop" branch and on some Colleagues local-machines we are getting error
<img width="707" alt="2021-06-23_17-51-55" src="https://user-images.githubusercontent.com/2736223/123128771-b5a42000-d44b-11eb-8ee7-a71b2a5b9f51.png">

In all environments we are using same docker image (already builded and placed in nexus).
In psalm image:
- php:8.0.5-cli-alpine3.13
- psalm 4.7.0 (even tested on 4.8.1).

Any ideas? Help? Advice?

**Comment by mirkhamidov** [comment]
> Hey @mirkhamidov, can you reproduce the issue on https://psalm.dev ?

:) no

**Comment by weirdan** [comment]
Do you use https://github.com/psalm/psalm-plugin-symfony?

**Comment by mirkhamidov** [comment]
@weirdan no, do you think it can help?

**Comment by orklah** [comment]
@mirkhamidov yeah, certainly

**Comment by mirkhamidov** [comment]
ok, I will try, but, even if so, why is same code and the same psalm - but behavior  different?

**Comment by orklah** [comment]
Are you certain they don't use the plugin? It seems very likely that a successfull check by psalm on a symfony project use it.

If they don't, check the dependancies, maybe you have two different symfony versions

**Comment by weirdan** [comment]
I'm not familiar with symfony kernel, but if there's something like `$this->environment = require '/path/to/file.php'; ` and Psalm can't find that file (e.g. it's only present locally in some working copies) it may affect type inference, especially if that happens in constructor.

**Comment by mirkhamidov** [comment]
@orklah yes, im sure that we all have same psalm image and symfony version.

@weirdan not so, there only one assignment like 
```php
abstract class Kernel 
{
    protected $environment;
    public function __construct(string $environment)
    {
        ... $this->environment = $environment ...
    }
}
```
and phpStorm reads this correct

**Comment by mirkhamidov** [comment]
update to 4.8.0 and Installation of plugin https://github.com/psalm/psalm-plugin-symfony didnt help.

**Comment by orklah** [comment]
Do you have specific errors that are suppressed? That could hide the real issue

**Comment by mirkhamidov** [comment]
for this class - no.

**Comment by orklah** [comment]
Well, that's all I got! Maybe try to reproduce on a public repo

**Comment by orklah** [comment]
I'll close this. We can't help without reproducer in this case
