### ISSUE TITLE
TooManyArguments when using func_num_args in class from vendor directory

### ISSUE THREAD

**Issue by gdejong** [vimeo/psalm#5995]
Given a class like this: https://psalm.dev/r/2d390cb619, Psalm understands that a variable amount of parameter can be given.

However it seems this code triggers a `TooManyArguments` error when that class comes from a Composer dependency (from the `vendor` directory). (not something I can reproduce on https://psalm.dev unfortunately)

Psalm config:
```
<?xml version="1.0"?>
<psalm
        errorLevel="4"
        resolveFromConfigFile="true"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://getpsalm.org/schema/config"
        xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src"/>
    </projectFiles>
</psalm>
```

In the `src/` directory I have a file that instantiated the class: `new Test(1);`
 
When explicitly adding the file from the vendor directory to the config, the `TooManyArguments` error disappears:
```
    <projectFiles>
        <directory name="src"/>
        <file name="vendor/path/to/file.php"/>
    </projectFiles>
```

Is this expected behavior or a bug? To me it feels like Psalm is not fully analyzing the usage of the `Test` file.

**Comment by weirdan** [comment]
For vendor files (except those referenced by composer autoload) Psalm performs a shallow scan where it collects signatures only and doesn't analyze function bodies. If you're unable to contribute docblock changes upstream I would suggest to stub that class (see https://psalm.dev/docs/running_psalm/configuration/#stubs) like this:
```
<?php

class Test
{
    /** @param int $test */
    public function __construct($test)
    {
    }

    public function getTest(): int
    {
    }
}
```
