### ISSUE TITLE
Capture variable ist not recognized if used by-ref

### ISSUE THREAD

**Issue by kapitancho** [vimeo/psalm#5996]
As shown here, $idx is incorrectly considered as mixed when passed by-ref.
https://psalm.dev/r/f9df7a65db
If passed by-value everything is fine.

A workaround is to put inside
```
			/**
			 * @var int $idx
			 */
```
but then PhpStorm warns that the variable is already inferred by the source.

**Comment by weirdan** [comment]
By-ref uses cannot be reasoned about as the type of the variables they reference can change at any moment.

Related: #4536, #4602, #4424 and #4001 (there are probably more, but these are what I found with a quick search).
