### ISSUE TITLE
Taint-Types: html and html_attr

### ISSUE THREAD

**Issue by paragonie-security** [vimeo/psalm#5998]
There are some cases where user-provided input that touches HTML is okay (especially if run through a library like HTMLPurifier or Twig's `|e('html')` filter). However, it wouldn't be okay to stick arbitrary HTML in the middle of an HTML attribute.

Most templating systems logically separate `html` and `html_attr`. Would it be possible to do the same in Psalm?

**Comment by paragonie-security** [comment]
No, because this is a feature request based on the documentation. I haven't tried to implement anything with it.

**Comment by muglug** [comment]
Psalm has a recently-added `has_quotes` taint which is I think what you're looking for. More information here: https://psalm.dev/docs/running_psalm/issues/TaintedTextWithQuotes/
