### ISSUE TITLE
Cache Directory Config Improvements

### ISSUE THREAD

**Issue by Fleshgrinder** [vimeo/psalm#60]
The cache directory is currently hard coded as `/var/tmp/psalm` which obviously is available on *nix system only. It would be better to use [`sys_get_temp_dir()`](https://php.net/function.sys-get-temp-dir) for proper cross platform support.

It is also annoying that the directory must be created manually by the user. Other tools, e.g. PHPUnit, allow one to define relative paths and they are created automatically. I tried `build/psalm/cache` but it kept failing, so I tried `./build/psalm/cache` but no luck either.

**Comment by muglug** [comment]
It's not quite hard-coded – use `cacheDirectory="path/to/dir" in the config file.

**Comment by muglug** [comment]
What system are you running Psalm on?

**Comment by Fleshgrinder** [comment]
Should I create a separate ticket for the auto-creation of directories?

**Comment by muglug** [comment]
That directory should be created here: https://github.com/vimeo/psalm/blob/dde39ed841598b06d8fb7a752c1393590a9b4568/src/Psalm/Checker/FileChecker.php#L563
but maybe it's failing due to nesting?

**Comment by muglug** [comment]
And to your question, yes please.
