### ISSUE TITLE
Null check for getter

### ISSUE THREAD

**Issue by nscheer** [vimeo/psalm#6002]
https://psalm.dev/r/8018a440e2

The getter just returns the object, which might be unset.
But between the two calls of the getter, there's no chance that the object gets set.

Could psalm be enhanced to recognize this, or is it just too complex?

**Comment by orklah** [comment]
You can tell Psalm that your function does not change state (so it will return the same result): https://psalm.dev/r/2b629708cb

**Comment by nscheer** [comment]
Thanks for the clarification!
