### ISSUE TITLE
LessSpecificReturnStatement and MoreSpecificReturnType false-positive when return type `static` is used

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#6004]
https://psalm.dev/r/21e5027303

I'm not quite sure how it should work, because it's a new language feature, but this code looks correct to me.
These warnings can be avoided with `final class` declaration, but what if I don't want it to be final?

**Comment by orklah** [comment]
Psalm will be fine if you declare the class Bar or the method getInstance as 'final': https://psalm.dev/r/e1467dbe5f

However, without it, Psalm can't guarantee there isn't a child of Bar that returns something that isn't "static" (but just Bar)

**Comment by fluffycondor** [comment]
> Psalm can't guarantee there isn't a child of Bar that returns something that isn't "static" (but just Bar)

How this can be even possible? Such kind of code just will explode in PHP 8.0.
http://sandbox.onlinephpfunctions.com/code/07784be2d34896e3ac3a92d7634148571da50bd0
> <b>Fatal error</b>:  Uncaught TypeError: Bar::getInstance(): Return value must be of type Baz, Bar returned

**Comment by orklah** [comment]
> How this can be even possible? Such kind of code will just explode in PHP 8.0.

And that's exactly why Psalm prevent you from doing that by ensuring you won't create a child of Bar :)

Either you declare something final or you have to return a `new static()` instead of a `new Bar()`;

**Comment by fluffycondor** [comment]
> return a `new static()`
But Psalm will yield an issue for this too
https://psalm.dev/r/496c67b55a

It seems to me like too strict behavior to allow `static` return type only in the final classes. It would be better to yield a warning on the children that break the contract, not on the parent that define contract that can be violated (and may not be!) by a child.

**Comment by orklah** [comment]
`new static()` is unsafe for a similar reason. A child could inherit Bar and create a __construct with a different signature. You can use the `@psalm-consistent-constructor` to make Psalm check that: https://psalm.dev/r/041ae01680 or declare your __construct final: https://psalm.dev/r/502f59ce5c

Reporting your error only on childs would prevent issues to be emitted for libraries that offers classes that can be inherited.

Do you have a specific reason not to add final to the class or method?

**Comment by fluffycondor** [comment]
> Do you have a specific reason not to add final to the class or method?

No, I don't have any right now.
Thanks for the detailed explanation!
