### ISSUE TITLE
General usage for multiple projects

### ISSUE THREAD

**Issue by marcelloh** [vimeo/psalm#601]
Ok, I want to use it from an installation directory, separate from my projects, so I won't get them contaminated.

I have to run something like d:\installdir\psalm --init d:\projectdir1
it creates a psalm-xml file in the d:\installdir

When I want to check it, I run:
d:\installdir\psalm --root=d:\projectdir1
(it was unclear where I should put that root statement, so I had to experiment.
(could be changed in the documentation for clearness)

Anyway: this goes wrong
I have to move the creates config file to the d:\projectdir1,
change the config into <directory name="" />
then it runs.

Can this be done simpler?

and after a little while, I get this: Fatal error: Class 'Symfony\Component\ExpressionLanguage\ExpressionLanguage' not found in d:\installDir\vendor\symfony\dependency-injection\ExpressionLanguage.php on line 24

But, my original question is, what to do for the next project?
because I now have to run something like d:\installdir\psalm --init d:\projectdir2
and here it complains, that the config file allready exists.

I thinjk, the solution is, to create the psalm.xml in the target dir,
or create a name that is not only spalm.xml, so the configuration file is per project.

**Comment by weirdan** [comment]
> I thinjk, the solution is, to create the psalm.xml in the target dir,
That's pretty standard to put various project configs into project root (`phpunit.xml`, `.editorconfig`, `phpcs.xml`, to name a few).

**Comment by muglug** [comment]
> I think, the solution is, to create the psalm.xml in the target dir

I've just fixed Psalm so that you can run `--root=[targetdir] --init` and the new file will be placed there.
