### ISSUE TITLE
[Q] Associated with InvalidReturnType & InvalidReturnStatement

### ISSUE THREAD

**Issue by realodix** [vimeo/psalm#6016]
PHP 8, Level 6

<details>
  <summary>Screenshot</summary>
  
  ![cats](https://user-images.githubusercontent.com/1314456/123750178-790b7500-d8e0-11eb-964b-c323fc035376.jpg)
</details>
Why is this considered an error, what's wrong?

According to the PHP documentation, by default [`str_word_count`](https://www.php.net/manual/en/function.str-word-count.php) will return the value as an int.

Even `str_word_count($this->content, 0)` is also considered an error

**Comment by weirdan** [comment]
https://psalm.dev/r/41ab9fa005

**Comment by weirdan** [comment]
This needs a stub added in https://github.com/vimeo/psalm/blob/master/stubs/CoreGenericFunctions.phpstub
