### ISSUE TITLE
Illegal annotations

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#602]
So apparently, under current phpDocumentor specs, some of the psalm annotations are illegal. I found about this because of this issue https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3611#issuecomment-374044282

Here is a relevant [excerpt from phpDocumentor](http://docs.phpdoc.org/guides/docblocks.html):

> A DocBlock is always associated with one, and just one, Structural Element in PHP; so this may either be a file, class, interface, trait, function, constant, method, property or variable.

Problem is, that annotations like `@psalm-suppress NameOfError` do not conform to this. In this case, Psalm does not have association to a variable, but to following statement, which apparently isn't control structure.

AST extension probably doesn't allow you to read the normal comment, so I guess we are stuck for now. I definitely don't suggest to remove such annotations though!

One thing which can be done in future if you get to PSR-5 group is to treat this issue there as well as other things.

I would like to hear your feedback on this.

**Comment by muglug** [comment]
> So apparently, under current phpDocumentor specs, some of the psalm annotations are illegal

Yup. But that spec should be updated IMO. A strict reading of that spec forbids `@var` annotations on variable assignments e.g.

```php
// in badly-typed file
function withoutReturnType() {
  return "always a string";
}

// in well-typed file
/** @var string $a */
$a = $foo->someUntypedFunctionCall();
```

Of course you can always put `@psalm-suppress` on function docblocks, where it's totally kosher.

**Comment by ostrolucky** [comment]
That spec does not forbid inline `@var` annotations, because such annotation have clear association to a variable, which is control structure.

Fingers crossed this thing will be dealt with in PSR-5

**Comment by muglug** [comment]
it's really really hazy. What is a control structure? is `byRefFunction($foo);` a control structure if it creates `$foo`?

**Comment by ostrolucky** [comment]
Ok I got it a little wrong it's not a control structure, but *structural element*, and their [list is according to phpDocumentor](http://docs.phpdoc.org/glossary.html#term-structural-elements) this:


    file
    require(_once)
    include(_once)
    class
    interface
    trait
    function (including methods)
    property
    constant
