### ISSUE TITLE
[4.8] False positive PossiblyUnusedReturnValue

### ISSUE THREAD

**Issue by frederikbosch** [vimeo/psalm#6021]
[This method](https://github.com/moneyphp/money/blob/master/src/Calculator/BcMathCalculator.php#L50) errors since 4.8.0. Why?
```php
    /** @psalm-pure */
    public static function divide(string $amount, string $divisor): string
    {
        if (bccomp($divisor, '0', self::SCALE) === 0) {
            throw InvalidArgumentException::divisionByZero();
        }

        return bcdiv($amount, $divisor, self::SCALE);
    }
```
`
ERROR: PossiblyUnusedReturnValue - src/Calculator/BcMathCalculator.php:50:69 - The return value for this method is never used (see https://psalm.dev/273)
    public static function divide(string $amount, string $divisor): string
`

The method is used [via an interface in the `Money` class](https://github.com/moneyphp/money/blob/4feac4c74682d653c1a63cdf9a49b036c5acc812/src/Money.php#L265) and in both [unit](https://github.com/moneyphp/money/blob/4feac4c74682d653c1a63cdf9a49b036c5acc812/tests/Calculator/BcMathCalculatorTest.php#L103) and [spec](https://github.com/moneyphp/money/blob/4feac4c74682d653c1a63cdf9a49b036c5acc812/spec/Calculator/CalculatorBehavior.php#L47) tests.

**Comment by frederikbosch** [comment]
Nope, it [doesn't generate the error](https://psalm.dev/r/4bc24ccef1).

**Comment by orklah** [comment]
It does if you actually call the methode somewhere (without using its return value) and you activate the option in settings :)

**Comment by orklah** [comment]
The issue may be that the type here is too wide: https://github.com/moneyphp/money/blob/4feac4c74682d653c1a63cdf9a49b036c5acc812/src/Money.php#L66 and Psalm fails to register that the function is called here. Can you try to reproduce in psalm.dev with the same structure you have in the lib?

**Comment by frederikbosch** [comment]
@orklah This did not happen in 4.7.0. It is a very recent change. I still [cannot reproduce, not with similar structure](https://psalm.dev/r/e547671d08).

**Comment by orklah** [comment]
@frederikbosch It's pretty new yeah, https://github.com/vimeo/psalm/pull/5917 introduced the new Issue

**Comment by orklah** [comment]
Closing as stale. Please reopen with a reproducer if you manage to make one

**Comment by yyueniao** [comment]
I have managed to reproduce this issue: https://psalm.dev/r/ba6aad7b6a

However, I'm not entirely certain if it's for the same reason as @frederikbosch 's case. In my situation, the error occurs when `TestImpl::method1` is called within the `TestImpl` class, and the return value is not used.

**Comment by orklah** [comment]
There has been a lot of changes since this issue, it's probably not related. Could you open a new issue please? @kkmuffme IIRC you have manipulated those rules a lot, maybe you could take a look?

**Comment by Miters-Community** [comment]
@orklah Sure! I will open a new issue.
