### ISSUE TITLE
[4.8] Ignores @property when method with same name exists

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#6023]
We have ` usePhpDocPropertiesWithoutMagicCall="true"` enabled in our `psalm.xml` and declare a property using PhpDoc, which has the same name as a method in the parent method.

When assigning that property to a variable and calling methods on that value or use the value as a typed parameter, we are getting `MixedAssignment` / `MixedMethodCall` / `MixedArgument` issues.

```php
/**
 * @property-read UploadedFile $file
 */
class StoreFileRequest extends Request
{}

class Request
{
    public function file(): void
    {}
}

class FileController
{
    public function store(StoreFileRequest $request): void
    {
        // MixedAssignment
        $file = $request->file;

        // MixedMethodCall
        $file->foo();

        // MixedArgument
        $this->handleFile($file);
    }

    private function handleFile(UploadedFile $file): void
    {
        // ...
    }
}
```

Example: https://psalm.dev/r/c8c362664b

PS: Do the psalm.dev snippets allow for Psalm configuration options to be set?

**Comment by weirdan** [comment]
> PS: Do the psalm.dev snippets allow for Psalm configuration options to be set?

Some options can be set by opening settings pane:

![image](https://user-images.githubusercontent.com/57403/124000958-ca992a00-d9dc-11eb-8f19-8a3ce97639d4.png)

**Comment by weirdan** [comment]
Are you sure it's caused by the property/method name collision? Does it disappear if you rename the property (or method)?

**Comment by caugner** [comment]
> Some options can be set by opening settings pane:

Unfortunately `usePhpDocPropertiesWithoutMagicCall` doesn't seem to be one of them. Is that editor somewhere on GitHub so I could open a PR to add that option?

> Are you sure it's caused by the property/method name collision? Does it disappear if you rename the property (or method)?

Yes, it disappears if we rename the property to `filex`, for example. Other properties work fine as well.

**Comment by weirdan** [comment]
> Is that editor somewhere on GitHub so I could open a PR to add that option?

It is, see https://github.com/psalm/psalm.dev

**Comment by weirdan** [comment]
I'm afraid I can't reproduce either of your issues locally (neither this, nor #6024): https://github.com/weirdan/property-docblock

**Comment by weirdan** [comment]
Have you tried the following troubleshooting steps:

1. Try with `dev-master`: `composer require --dev vimeo/psalm:dev-master`
2. Clear cache: `vendor/bin/psalm --clear-cache`

?

**Comment by caugner** [comment]
I did try to run `vendor/bin/psalm --no-cache`, with the same issues, but actually `vendor/bin/psalm-plugin disable psalm/plugin-laravel` made the issue disappear, so it seems to be caused by that plugin after all.

So sorry to have wasted your time. ☹️
