### ISSUE TITLE
[4.8] @property type resolution ignores imports

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#6024]
We have Psalm configured with `usePhpDocPropertiesWithoutMagicCall="true"`, but Psalm seems to ignore imports when resolving types within the `@property` annotations.

In other words, the following two code snippets, although equivalent, don't produce the same result:

```php
<?php

namespace App\Models;

/**
 * @property \Carbon\CarbonInterface|null $accepted_at
 */
class Invitation {}

function accept(Invitation $invitation): void {
    $date = $invitation->accepted_at;
    /** @psalm-trace $date */
    // $date: Carbon\CarbonInterface
}
```

VS

```php
<?php

use Carbon\CarbonInterface;

namespace App\Models;

/**
 * @property CarbonInterface|null $accepted_at
 */
class Invitation {}

function accept(Invitation $invitation): void {
    $date = $invitation->accepted_at;
    /** @psalm-trace $date */
    // $date: App\Models\CarbonInterface
}
```

**Comment by caugner** [comment]
@psalm-github-bot No, I cannot, because psalm.dev doesn't support enabling `usePhpDocPropertiesWithoutMagicCall` (see also [here](https://github.com/vimeo/psalm/issues/6023#issuecomment-871598625)).

**Comment by weirdan** [comment]
Unfortunately I failed to reproduce your issue here: https://github.com/weirdan/property-docblock

**Comment by caugner** [comment]
Sorry, it's the same with this issue: Disabling `psalm/plugin-laravel` resolves the issues, so they are a side-effect of that plugin. ☹️
