### ISSUE TITLE
Flag @property annotations without $

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#6028]
It appears that PhpStorm's *Add @property* quickfix adds a `@property` annotation without the `$` in front of the property name, e.g.:

```
 * @property string foo
```

instead of

```
 * @property string $foo
```

Unfortunately, Psalm currently ignores these annotations.

Since Psalm.dev now has the new *Use PHPDoc methods and properties without magic call* setting, I even have an example to make @psalm-github-bot happy: https://psalm.dev/r/c03daf695c

**Comment by weirdan** [comment]
Both PSR and PHPDocumentor show property names with `$` sigil:

* https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#510-property
* https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/property.html#property-property-read-property-write

Jetbrains themselves consider this a bug: https://youtrack.jetbrains.com/issue/WI-34398

So I don't think Psalm should work around PHPStorm bugs.

**Comment by caugner** [comment]
@weirdan To be fair, neither PSR nor PHPDocumentor specify that `[name]` contains the `$`, even though the examples all use it. Strictly speaking, their specifications both omit the `$` explicitly. The specification with `$` would be:

```
@property[<-read|-write>] ["Type"] $[name] [<description>]
```

It's a shame that Jetbrains knows about this issue for 5 years and nobody went for this probably easy fix yet.

As for Psalm, if those `@property` annotations aren't supported, at least they should cause [InvalidDocblock](https://psalm.dev/docs/running_psalm/issues/InvalidDocblock/) errors, shouldn't they?

**Comment by weirdan** [comment]
> Strictly speaking, their specifications both omit the $ explicitly

It depends on whether you consider `$` a part of the name. I don't think that specified explicitly in either of those documents.

> if those `@property` annotations aren't supported, at least they should cause `InvalidDocblock` errors, shouldn't they?

Makes sense.

**Comment by caugner** [comment]
> It depends on whether you consider $ as part of the name.

Yup, it's definitely a philosophical question, but when I refer to a property by name in a meeting, I never regard the sigil as part of the property name (same for variables, actually). 😄

**Comment by caugner** [comment]
PS: Interestingly, phpDocumentor doesn't seem to regard the sigil as part of the property name internally (https://github.com/phpDocumentor/phpDocumentor/blob/8f303dd43ac9f8af4f6b2540e9494ebde3ababc9/src/phpDocumentor/Descriptor/PropertyDescriptor.php#L59-L61), so I would guess they strip the sigil during parsing and support the property names *without* sigil, either intentionally or as a side-effect.

**Comment by weirdan** [comment]
PHPStorm fixed this the next day after they were nudged.

**Comment by caugner** [comment]
Wow, I hadn't seen that. So now a fix in Psalm should no longer be necessary.
