### ISSUE TITLE
Question about conditional typing 

### ISSUE THREAD

**Issue by vaawebdev** [vimeo/psalm#6034]
I have an interface of a web page parser like the following: 
![image](https://user-images.githubusercontent.com/47596772/124276298-a6f8ef80-db54-11eb-998b-4efdf5230850.png)

If the url parameter is a string then an instance of `ParsedWebsiteInterface` will be returned, and if an array of strings are passed as `url` parameter, then an array of `ParsedWebsiteInterface` objects will be returned.

I have no idea how to annotate that behavior. Would be pleased if you can help me!

**Comment by vaawebdev** [comment]
Here is the link https://psalm.dev/r/4afe896344

**Comment by vaawebdev** [comment]
Here is the link https://psalm.dev/r/8e3e2f8ac3

**Comment by simonhammes** [comment]
@vaawebdev This should work:
```php
/**
 * @psalm-return ($url is string ? ParsedWebsiteInterface : ParsedWebsiteInterface[])
 */
```

**Comment by vaawebdev** [comment]
@simonhammes  Wow! That was great! Thanks for the quick response!
