### ISSUE TITLE
@psalm-assert-if-true does not work if method is called outside of class

### ISSUE THREAD

**Issue by simonhammes** [vimeo/psalm#6035]
Snippet: https://psalm.dev/r/3364a2cde7

This should work, right? Or is this currently not supported?

**Comment by weirdan** [comment]
No, it's not expected to happen. Outside of the class `$this->exception` is not visible. However you can use multiple `@psalm-assert-is-true`, and you can assert method returns, e.g. `@psalm-assert-if-true Exception $this->getException()`: https://psalm.dev/r/9e92f7b7b6

**Comment by simonhammes** [comment]
@weirdan Okay, thank you very much. This works perfectly!

Would you mind it if I would open a PR to add an example to the docs? 
The examples page at https://psalm.dev/docs/annotating_code/adding_assertions/ currently does not contain any examples for methods.

**Comment by weirdan** [comment]
> Would you mind it if I would open a PR to add an example to the docs?

Not at all, please do!
