### ISSUE TITLE
Class 'Symfony\Component\ExpressionLanguage\ExpressionLanguage' not found

### ISSUE THREAD

**Issue by marcelloh** [vimeo/psalm#604]
Psalm 1.0.3@d6e0708e888fae2ec9211703c5c3d9ee301f349a
Scanning files...

Fatal error: Class 'Symfony\Component\ExpressionLanguage\ExpressionLanguage' not found in D:\installdir\vendor\symfony\dependency-injection\ExpressionLanguage.php on line 24

**Comment by muglug** [comment]
Would you mind printing the output when running with `--debug`?

**Comment by marcelloh** [comment]
'''
Psalm 1.0.3@d6e0708e888fae2ec9211703c5c3d9ee301f349a
Scanning files...
Deep scanning D:\myproject1\vendor\illuminate\support\Traits\CapsuleManagerTrait.php
Deep scanning D:\myproject1\vendor\illuminate\support\Traits\Macroable.php
Deep scanning D:\myproject1\vendor\psr\log\Psr\Log\LoggerAwareTrait.php
Deep scanning D:\myproject1\vendor\psr\log\Psr\Log\LoggerTrait.php
Deep scanning D:\myproject1\vendor\slim\slim\Slim\CallableResolverAwareTrait.php
Deep scanning D:\myproject1\vendor\slim\slim\Slim\MiddlewareAwareTrait.php
Deep scanning D:\myproject1\vendor\symfony\console\Command\LockableTrait.php
Using reflection to locate file for T
Using reflection to locate file for TKey
Using reflection to locate file for TValue
Using reflection to get metadata for Serializable
Using reflection to get metadata for Countable
Using reflection to locate file for callback
Using reflection to get metadata for SeekableIterator
Using reflection to get metadata for PDO
Using reflection to get metadata for RuntimeException
Using reflection to locate file for myproject1\Common\Helpers\Container
Using reflection to locate file for PHPMailer
Using reflection to locate file for Services\WebException
Using reflection to get metadata for RegexIterator
Using reflection to get metadata for RecursiveDirectoryIterator
Using reflection to get metadata for RecursiveIteratorIterator
Using reflection to locate file for myproject1\Common\Helpers\Response
Using reflection to locate file for myproject1\Common\Helpers\ResponseInterface
Using reflection to get metadata for ReflectionClass
Using reflection to get metadata for ReflectionException
Using reflection to get metadata for ReflectionMethod
Using reflection to get metadata for Exception
Using reflection to locate file for myproject1\Modules\Admin\Controllers\Container
Using reflection to locate file for myproject1\Modules\Admin\Controllers\Request
Using reflection to locate file for myproject1\Modules\Admin\Controllers\Response
Using reflection to get metadata for Closure
Using reflection to get metadata for InvalidArgumentException
Using reflection to locate file for static
Using reflection to locate file for Illuminate\Auth\Access\Response
Using reflection to locate file for Symfony\Component\HttpFoundation\Response
Using reflection to locate file for Illuminate\Http\Request
Using reflection to get metadata for DateTime
Using reflection to locate file for Illuminate\Foundation\Bus\PendingDispatch
Using reflection to locate file for Symfony\Component\HttpFoundation\Cookie
Using reflection to locate file for Symfony\Component\HttpFoundation\Request
Using reflection to locate file for dynamic
Using reflection to get metadata for Throwable
Using reflection to locate file for Illuminate\Redis\Connections\Connection
Using reflection to locate file for Illuminate\Routing\Route
Using reflection to locate file for Illuminate\Http\Response
Using reflection to locate file for Illuminate\Http\JsonResponse
Using reflection to locate file for Symfony\Component\HttpFoundation\StreamedResponse
Using reflection to locate file for Symfony\Component\HttpFoundation\BinaryFileResponse
Using reflection to get metadata for SplFileInfo
Using reflection to locate file for Illuminate\Http\RedirectResponse
Using reflection to get metadata for SessionHandlerInterface
Using reflection to get metadata for JsonSerializable
Using reflection to locate file for self
Using reflection to get metadata for CachingIterator
Using reflection to locate file for Illuminate\Filesystem\Filesystem
Using reflection to locate file for Symfony\Component\Process\ProcessUtils
Using reflection to locate file for Symfony\Component\Process\PhpExecutableFinder
Using reflection to locate file for Symfony\Component\Process\Process
Using reflection to locate file for Symfony\Component\VarDumper\Dumper\CliDumper
Using reflection to locate file for Symfony\Component\VarDumper\Cloner\VarCloner
Using reflection to locate file for Symfony\Component\VarDumper\Dumper\HtmlDumper
Using reflection to locate file for Illuminate\Database\Eloquent\Model
Using reflection to locate file for Mockery
Using reflection to locate file for Mockery\Expectation
Using reflection to locate file for Mockery\MockInterface
Using reflection to locate file for Illuminate\Notifications\ChannelManager
Using reflection to locate file for Illuminate\Database\Schema\Builder
Using reflection to locate file for Illuminate\Foundation\Application
Using reflection to locate file for Illuminate\Console\Application
Using reflection to locate file for PHPUnit\Framework\Assert
Using reflection to locate file for Illuminate\Mail\PendingMail
Using reflection to locate file for Ramsey\Uuid\Uuid
Using reflection to locate file for Illuminate\Mail\Mailable
Using reflection to locate file for Illuminate\Queue\QueueManager
Using reflection to get metadata for BadMethodCallException
Using reflection to locate file for Elastica\Document
Using reflection to locate file for Gelf\Message
Using reflection to locate file for MongoDate
Using reflection to get metadata for SoapFault
Using reflection to locate file for Monolog\Handler\Boolean
Using reflection to get metadata for LogicException
Using reflection to get metadata for UnexpectedValueException
Using reflection to locate file for AMQPExchange
Using reflection to locate file for PhpAmqpLib\Channel\AMQPChannel
Using reflection to locate file for PhpAmqpLib\Message\AMQPMessage
Using reflection to locate file for Doctrine\CouchDB\CouchDBClient
Using reflection to locate file for Aws\DynamoDb\DynamoDbClient
Using reflection to locate file for Aws\DynamoDb\Marshaler
Using reflection to locate file for Aws\Sdk
Using reflection to locate file for Elastica\Client
Using reflection to locate file for Elastica\Exception\ExceptionInterface
Using reflection to locate file for Monolog\Handler\FingersCrossed\Boolean
Using reflection to locate file for Gelf\Publisher
Using reflection to locate file for Gelf\PublisherInterface
Using reflection to locate file for Gelf\IMessagePublisher
Using reflection to locate file for Swift_Message
Using reflection to locate file for MongoClient
Using reflection to locate file for Mongo
Using reflection to locate file for MongoDB\Client
Using reflection to locate file for MongoDB\Collection
Using reflection to locate file for PhpConsole\Connector
Using reflection to locate file for PhpConsole\Helper
Using reflection to locate file for PhpConsole\Handler
Using reflection to locate file for Raven_Client
Using reflection to locate file for Predis\Client
Using reflection to locate file for Redis
Using reflection to locate file for RollbarNotifier
Using reflection to locate file for Swift_Mailer
Using reflection to locate file for Swift
Using reflection to get metadata for DateTimeImmutable
Using reflection to get metadata for DateTimeZone
Using reflection to locate file for Monolog\Boolean
Using reflection to locate file for PHPUnit_Framework_TestCase
Using reflection to get metadata for stdClass
Using reflection to locate file for PHPUnit_Framework_Error_Warning
Using reflection to get metadata for ReflectionProperty
Using reflection to get metadata for ErrorException
Using reflection to locate file for Elastica\Request
Using reflection to locate file for Elastica\Response
Using reflection to locate file for Gelf\MessagePublisher
Using reflection to locate file for PHPUnit_Framework_MockObject_MockObject
Using reflection to locate file for PhpConsole\Dispatcher\Debug
Using reflection to locate file for PhpConsole\Dispatcher\Errors
Using reflection to locate file for Monolog\Handler\Monolog\Handler\SocketHandler
Using reflection to locate file for Monolog\Monolog\Formatter\FormatterInterface
Using reflection to locate file for com_exception
Using reflection to locate file for COM
Using reflection to locate file for Sodium
Using reflection to get metadata for Phar
Using reflection to get metadata for FilesystemIterator
Using reflection to get metadata for SplObjectStorage
Using reflection to locate file for PHPUnit\Framework\TestCase
Using reflection to get metadata for PDOException
Using reflection to get metadata for PDOStatement
Using reflection to get metadata for SimpleXMLElement
Using reflection to get metadata for SplStack
Using reflection to get metadata for SplDoublyLinkedList
Using reflection to locate file for Slim\Views\Slim\Http\Uri
Using reflection to locate file for Symfony\Component\DependencyInjection\Compiler\PriorityTaggedServiceTrait
Deep scanning D:\data\Git\QualityReport\vendor\symfony\dependency-injection\Compiler\PriorityTaggedServiceTrait.php
Using reflection to locate file for Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface
Using reflection to locate file for Symfony\Component\DependencyInjection\ContainerBuilder
Using reflection to locate file for Symfony\Component\DependencyInjection\Argument\IteratorArgument
Using reflection to get metadata for RecursiveCallbackFilterIterator
Using reflection to locate file for Symfony\Component\Finder\Finder
Using reflection to locate file for Symfony\Component\Finder\Glob
Using reflection to get metadata for ReflectionParameter
Using reflection to locate file for iterable
Using reflection to locate file for Symfony\Component\DependencyInjection\Reference
Using reflection to get metadata for ReflectionObject
Using reflection to locate file for Symfony\Component\Config\Tests\Fixtures\Resource\MissingClass
Using reflection to get metadata for libXMLError
Using reflection to get metadata for DOMDocument
Using reflection to get metadata for DOMElement
Using reflection to get metadata for DOMText
Using reflection to get metadata for DOMComment
Using reflection to locate file for Symfony\Component\EventDispatcher\EventDispatcherInterface
Using reflection to get metadata for ReflectionFunction
Using reflection to locate file for Symfony\Component\DependencyInjection\Exception\InvalidArgumentException
Using reflection to get metadata for DOMNode
Using reflection to locate file for Symfony\Component\EventDispatcher\Event
Using reflection to locate file for Symfony\Component\EventDispatcher\EventSubscriberInterface
Using reflection to locate file for Symfony\Component\Console\Exception\Exception
Using reflection to locate file for Symfony\Component\Process\ProcessBuilder
Using reflection to locate file for Symfony\Component\Process\Exception\ProcessFailedException
Using reflection to locate file for Symfony\Component\EventDispatcher\EventDispatcher
Using reflection to locate file for UnknownClass
Using reflection to locate file for Symfony\Component\HttpKernel\Bundle\Bundle
Using reflection to locate file for Symfony\Component\DependencyInjection\Definition
Using reflection to get metadata for ParseError
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\HttpExceptionInterface
Using reflection to locate file for Symfony\Component\HttpFoundation\Exception\RequestExceptionInterface
Using reflection to get metadata for __PHP_Incomplete_Class
Using reflection to locate file for Symfony\Component\HttpKernel\Debug\FileLinkFormatter
Using reflection to locate file for Symfony\Component\ClassLoader\ClassLoader
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\NotFoundHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\BadRequestHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\ConflictHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\GoneHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\LengthRequiredHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\PreconditionFailedHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\PreconditionRequiredHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\ServiceUnavailableHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException
Using reflection to locate file for Symfony\Component\HttpKernel\Exception\UnsupportedMediaTypeHttpException
Using reflection to locate file for Symfony\Component\HttpFoundation\Exception\SuspiciousOperationException
Using reflection to get metadata for DateTimeInterface
Using reflection to get metadata for DateInterval
Using reflection to get metadata for OutOfBoundsException
Using reflection to get metadata for LimitIterator
Using reflection to get metadata for IteratorIterator
Using reflection to locate file for Twig_Extension_ExtensionInterface
Using reflection to locate file for Twig_Node_SetTemp
Using reflection to get metadata for SplFileObject
Using reflection to get metadata for DirectoryIterator
Using reflection to get metadata for recursiveiterator
Using reflection to get metadata for ReflectionExtension
Using reflection to get metadata for ReflectionType
Using reflection to locate file for Symfony\Component\Process\Pipes\PipesInterface
Using reflection to get metadata for Generator
Using reflection to get metadata for PharData
Using reflection to locate file for Symfony\Component\DependencyInjection\Container
Using reflection to locate file for Symfony\Component\DependencyInjection\TaggedContainerInterface
Using reflection to locate file for Symfony\Component\DependencyInjection\Extension\ExtensionInterface
Using reflection to locate file for Symfony\Component\DependencyInjection\Alias
Using reflection to locate file for Symfony\Component\DependencyInjection\Compiler\Compiler
Using reflection to locate file for Symfony\Component\DependencyInjection\LazyProxy\Instantiator\InstantiatorInterface
Using reflection to locate file for Symfony\Component\DependencyInjection\ExpressionLanguage

Fatal error: Class 'Symfony\Component\ExpressionLanguage\ExpressionLanguage' not found in D:\installdir\vendor\symfony\dependency-injection\ExpressionLanguage.php on line 24

**Comment by muglug** [comment]
Is composer initialised in the target folder?

**Comment by marcelloh** [comment]
I don't know what you mean by that.
(does the project folder uses composer: yes)

**Comment by muglug** [comment]
I imagine this is now fixed.
