### ISSUE TITLE
ZipArchive::open() never returns false

### ISSUE THREAD

**Issue by chapa** [vimeo/psalm#6052]
In the [ZipArchive::open documentation](https://www.php.net/manual/en/ziparchive.open.php):
> Returns true on success, or one of the following error codes: [...]

Psalm seems to interpret the return value as `bool|int` instead of `true|int`:
https://psalm.dev/r/13a184ea04

**Comment by orklah** [comment]
This should be a simple change in https://github.com/vimeo/psalm/blob/master/dictionaries/CallMap.php

Care to propose a PR?

**Comment by chapa** [comment]
Yes of course! I didn't know where it was configured, thank you for guiding me.

**Comment by weirdan** [comment]
It does return `false` though: https://github.com/php/php-src/blob/ca8247654c1e324d412bb6f40ef14fb506487983/ext/zip/php_zip.c#L1454-L1471

**Comment by chapa** [comment]
@weirdan interesting! I'm not able to understand this piece of code enough to produce a call that return `false` in real life. E.g. I tried `php -r '$z = new ZipArchive(); var_dump($z->open("test.zip"));'` but it gives me `int(9)`. Do you have an example where the method returns `false` ?

I'll propose a PR anyway, free to those who know to accept it or not :wink:

**Comment by weirdan** [comment]
PHP 8.0.7:
```console
$ php -d open_basedir=/tmp -r '$z = new ZipArchive; var_dump($z->open("/etc/zip.zip"));'
PHP Warning:  ZipArchive::open(): open_basedir restriction in effect. File(/etc/zip.zip) is not within the allowed path(s): (/tmp) in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. ZipArchive->open($filename = '/etc/zip.zip') Command line code:1
Command line code:1:
bool(false)
```
There should be more, as the above covers just the first if.
