### ISSUE TITLE
Including split configuration files from subdirectories

### ISSUE THREAD

**Issue by turnabout** [vimeo/psalm#6058]
In my `psalm.xml` config file, I'd like to include bits of configuration from split xml files that are located in subdirectories relative to my `psalm.xml`.

I've followed the instructions on https://psalm.dev/docs/running_psalm/configuration/ which shows how to accomplish that using XInclude tags. Here is a barebones example of what I'm trying to do with my configuration:

**`psalm.xml`**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<psalm
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    xmlns:xi="http://www.w3.org/2001/XInclude"
>
    <xi:include href="vendor/anotherProject/configurations/psalm-projectFiles.xml" />
</psalm>
```

**`vendor/anotherProject/configurations/psalm-projectFiles.xml`**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<projectFiles xmlns="https://getpsalm.org/schema/config">
    <directory name="src"/>
    <ignoreFiles>
        <directory name="vendor"/>
    </ignoreFiles>
</projectFiles>

```

Running psalm with the above configuration results in this error:
```
Problem parsing /applications/src/myApp/psalm.xml:  Error on line 2:
    Element '{https://getpsalm.org/schema/config}projectFiles', attribute '{http://www.w3.org/XML/1998/namespace}base': 
    The attribute '{http://www.w3.org/XML/1998/namespace}base' is not allowed.
```

**Comment by orklah** [comment]
Weird, it seems to complain about a `base` attribute on `projectFiles` element but I see no such thing in your snippets.

Are you sure you showed us the correct ones?
