### ISSUE TITLE
Psalm does not understand variable initialization order when initialized within array.

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#6061]
https://psalm.dev/r/d4185292b9

I'd expect not errors about variable `$timestamp` being not found or unused.

**Comment by muglug** [comment]
Few comments:

- IMO this is bad code and should be rewritten as https://psalm.dev/r/366293c0e1
- the bug is caused by evaluation order — currently all keys are evaluated first, which is wrong. It should be possible instead to do it by key and value

**Comment by simPod** [comment]
Definitely agree the code is not perfect though it's still valid or is it not?

Stumbled upon it in legacy code base where there's complex array structure in tests and the lowest level array is constructed like this. Hard to squeeze foreach inside. I would have to wrap it in a function, call it and unpack `...` or sth like that.

```php
[22=>[
    $timestamp = (new DateTimeImmutable('2017-08-06 00:00:00'))->getTimestamp() => [
        'timestamp' => $timestamp,
    ],
    $timestamp = (new DateTimeImmutable('2017-08-06 01:00:00'))->getTimestamp() => [
        'timestamp' => $timestamp,
    ],
    $timestamp = (new DateTimeImmutable('2017-08-06 02:00:00'))->getTimestamp() => [
        'timestamp' => $timestamp,
    ]
]];
```

->

```php
<?php

[22=>(function() {
    $dates = ['2017-08-06 00:00:00', '2017-08-06 01:00:00', '2017-08-06 02:00:00'];

    $arr = [];

    foreach ($dates as $date) {
        $timestamp = (new DateTimeImmutable($date))->getTimestamp();
        $arr[$timestamp] = ['timestamp' => $timestamp];
    }

    return $arr;
})()]
```
