### ISSUE TITLE
 UndefinedVariable in closure declaration of a global variable

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#607]
```php
<?php
$MY_TEST = [1,2,3];
function example() {
    return function() {
        global $MY_TEST;  // unexpected UndefinedVariable - src/global.php:5:16 - Cannot find referenced variable $MY_TEST     
        return $MY_TEST[2];
    };
}
```

**Comment by muglug** [comment]
Ugh why does this work. This should not work.

Also Psalm used not to check `global` vars, but now it does, so this was always lurking.

**Comment by muglug** [comment]
I'm leaning towards making this a `wontfix` issue. Nesting `global` usage seems like an even worse code smell than just using `global`, and you can pass Psalm checks with:

```php
$a = [1,2,3];
function example() : Closure {
    global $a;
    return function() use ($a) : int {
        return $a[2];
    };
}
```

Does that seem fair? Or just lazy?

**Comment by TysonAndre** [comment]
What if a user wants the **most recent** value of the global (E.g. it's an array that can be modified?)

That isn't my use case, but `use(&$a)` would be non-obvious, even though it's about the same

**Comment by muglug** [comment]
Permalink: https://getpsalm.org/r/6b9579328e

**Comment by muglug** [comment]
This is fixed
