### ISSUE TITLE
Generic parameter does not accept a union of generics

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#6073]
The new system for capturing generic constrains introduced in https://github.com/vimeo/psalm/commit/acc7ee261c106b4ae91f333ff4a9939b6e858bf3 breaks PSL build.

see: https://github.com/azjezz/psl/runs/3041183878?check_suite_focus=true

I couldn't make a smaller repro 🤔

**Comment by weirdan** [comment]
Simplified to https://psalm.dev/r/86a60c6f13

**Comment by weirdan** [comment]
@muglug any idea what could be wrong here? It looks like Psalm breaks union apart into constituent types and believes each of them is an upper (?) bound for `T:acceptsContainer` and that doesn't sound right.

**Comment by muglug** [comment]
Yeah, have a look at this: hhttps://psalm.dev/r/bbef3b2bdb

If there's one type for `T` then Psalm allows `Container<int>|Container<string>` to become `Container<int|string>` which is a violation of generic stuff.

**Comment by muglug** [comment]
PHPStan emits a slightly different but comparable error: https://phpstan.org/r/b1097877-6b2c-4f5b-b897-30a0b069bad4
