### ISSUE TITLE
Incorrectly found errors in ignored paths if class contains a trait from excluded directory

### ISSUE THREAD

**Issue by pkly** [vimeo/psalm#6076]
Hi, I have a config that contains the ignoreFiles -> vendor path, for obvious reasons.
But since one of the classes I have extends a class from vendor, which then has a trait and the trait itself contains an error, an issue is shown in my log as following

![Screenshot](https://cdn.discordapp.com/attachments/824191574598483979/864117106948964372/unknown.png)

This is rather weird and likely not supposed to happen.

**Comment by pkly** [comment]
> Hey @pkly, can you reproduce the issue on https://psalm.dev ?

No, since it requires folders.

**Comment by orklah** [comment]
yeah, sorry for not spotting this earlier, this is to be expected. Psalm need to be able to parse docblocks, even in vendors to be able to work properly. Unfortunately, the "." after $this makes it an invalid syntax. Please provide a PR upstream to fix the syntax on their end or create a stub on your end.
