### ISSUE TITLE
Not recognizing return of `get_class` when passing object casted arrays

### ISSUE THREAD

**Issue by thor-juhasz** [vimeo/psalm#6079]
If you pass `(object)` casted arrays to the `get_class` method, it returns the string "stdClass".

Psalm doesn't play very nice with that:
https://psalm.dev/r/5e66171eab

**Comment by orklah** [comment]
Actually it does: https://psalm.dev/r/ee963c777f, but unless you put `allowStringToStandInForClass` to true in your config, Psalm won't allow you to use `"stdClass"` in place of `stdClass::class`

**Comment by thor-juhasz** [comment]
Ahh, thanks @orklah, didn't realize Psalm was just being picky :)
