### ISSUE TITLE
Calling function with `string|callable` parameter requires it to be valid function name

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#608]
```php
<?php
  /**
   * @param string|callable $middlewareOrPath
   */
  function pipe($middlewareOrPath, ?callable $middleware = null): void {  }

pipe("zzzz", function() {});
```
Here the intention is to allow string **or** callable as the first parameter, and when that is not valid callable (checked in the function body) use it as an ordinary string.

Psalm complains that 'zzzz' is not a valid callable, even though it's not supposed to be.

Real-world example: https://github.com/zendframework/zend-expressive/blob/3beef69db7b2a88ed0d8507c9a1f008b46da9a61/src/Application.php#L102

**Comment by muglug** [comment]
Yup, Psalm needs a `PossiblyUndefinedFunction`

**Comment by muglug** [comment]
Thanks!
