### ISSUE TITLE
Static methods in abstract classes using templates break assertions

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#6090]
Hey there,

not sure how to provide a better title but I recently stumbled over this problem:
https://psalm.dev/r/0c91cb03c8

When using an abstract class with a template, some static methods seem to lose the connection to the implementing class and thus, the template type cannot be properly detected, even tho, the implementing class is being called.

I'd expect that `$foo` becomes `non-empty-string` after calling `Foo\Bar::isValid`

**Comment by orklah** [comment]
You can't use class level templates in static methods. I'd expect an error from Psalm here to tell you that T does not exists instead.

However, I'm not even sure templates are supported in docblock assertions, those snippets are weird:
https://psalm.dev/r/2ce9852351
https://psalm.dev/r/a79b4bfa12

The latter acts like T was a perfectly valid class named MyCLabs\Enum\T without emitting errors but the first reacts to the template named T but just returns `T` weirdly

**Comment by boesing** [comment]
Mhm, I have another issue which might be related, where this was considered a bug: https://github.com/vimeo/psalm/issues/5657

Or is that totally unrelated? The only difference is, that it uses a method-level template rather than a class-level template - or do I miss something?

**Comment by orklah** [comment]
Psalm stopped supporting the use of class-level templates in static methods. IIRC, the rationale is that class-level templates are supposed to represent the content of a particular instance of a class, so each object may have a specific value for a template (think of a `Collection<int>` and `Collection<string>` are both `Collection<T as scalar>` so what does `T` represent in a static method?

I can see what you'd like to use the template for in this case, but I don't thinks it's feasible right now

**Comment by boesing** [comment]
Thanks for clarification. 👍🏼  
Very appreciated!

---- 

> think of a Collection<int> and Collection<string> are both Collection<T as scalar> so what does T represent in a static method

Depends on what psalm detected previously.
- If the generic is unknown, I'd say psalm can report that as an error.
- If the generic is known (either due to an annotation like `/** @psalm-var Collection<int> $collection */` (or however), it could abstract that somehow from the implementing class. But I guess thats something which is/was quite hard to achieve, so I take that bullet.
- If the implementing class does not require a template because it has a concrete implementation (like my specific enum example in the initial comment), that might be quite "easy" (in my eyes - but sadly, I am not yet that deep in how the whole parsing thing works 🙈 )

So for now, I will just call that method and add an additional `/** @psalm-var Foo::* $foo */` after calling that method.

Guess we can close this as I don't see that we can make any progress with my current understanding of psalm internals and this should not be a burden for you guys.

**Comment by boesing** [comment]
Oh, this was related https://github.com/vimeo/psalm/issues/5372
