### ISSUE TITLE
Overwriting method in extending class to not have nullable return

### ISSUE THREAD

**Issue by thor-juhasz** [vimeo/psalm#6097]
Take this example:
https://psalm.dev/r/ceaab19955

I have those classes in separate files.
The project is using composer, and the psalm.xml does not overwrite the `autoload` option.

When I run psalm on only the `AnotherClass`, it does not report any issues.
Should it not be able to pick up the parent class to statically analyze the method signatures and return types being correct?

**Comment by weirdan** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/57403/125788816-701b659b-b07c-4796-a0ec-70899065bf23.png)

**Comment by weirdan** [comment]
Can you reproduce it in separate public repo?
