### ISSUE TITLE
Sandbox: add confirmation window on the page unload if there are code in the editor, or save it in the LocalStorage

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#6100]
It's really easy to drop all your changes on the https://psalm.dev/ sandbox if you follow one of the links from the error report.
I think there should be a confirmation window before leaving the sandbox, or opening a new window for these links, or saving the code in the LocalStorage.

**Comment by orklah** [comment]
Hey! Thanks for reporting this. Can you create a ticket on https://github.com/psalm/psalm.dev instead? It's the repo that hosts the website

Thanks
