### ISSUE TITLE
False-positive InvalidArgument: psalm can't deduct that an object implements a generic interface

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#6101]
https://psalm.dev/r/597c4c52ed

**Expected**: no errors.
**Got**: InvalidArgument.

**Comment by weirdan** [comment]
But `IFoo<Foo>` (Foo) is not compatible with invariant `IFoo<IBar>`. There's no issues emitted for covariant `IFoo<IBar>`: https://psalm.dev/r/696a880991
