### ISSUE TITLE
CI and Psalm checking itself

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#6105]
Looking at CI running on my PR, I noticed that 2 jobs seem to do the same thing:
https://github.com/vimeo/psalm/blob/master/.circleci/config.yml#L11
and
https://github.com/vimeo/psalm/blob/master/.github/workflows/shepherd.yml#L6

Given that shepherd need to run Psalm on itself in order to work, the CircleCI seem redundant (in addition on being triggered later and using a third party site).

Could we drop the CircleCI one?

**Comment by weirdan** [comment]
Github Actions run with PHP 8, and CircleCI jobs are using 7.4, so there is a difference (possibly irrelevant).

**Comment by orklah** [comment]
If we wanted to check other php versions, I'd find more appropriate to run the tests instead. And we would be inspired to run them on the lowest version supported and highest version supported instead of just two close versions...

**Comment by weirdan** [comment]
As I said, it's probably irrelevant. No objections from me to remove that.
