### ISSUE TITLE
false positive UnusedVariable

### ISSUE THREAD

**Issue by williamdes** [vimeo/psalm#6109]
The variable is defined in https://github.com/phpmyadmin/phpmyadmin/blob/be43ee4862253319f3047f0cf45c1a1aaf573ed0/libraries/classes/Table.php#L1176

and then an isset checks it https://github.com/phpmyadmin/phpmyadmin/blob/be43ee4862253319f3047f0cf45c1a1aaf573ed0/libraries/classes/Table.php#L1389

Reproduced by https://psalm.dev/r/5faa4128b2

**Comment by orklah** [comment]
Yeah, Psalm really doesn't like working with undefined variables

I'm gonna add the bug label on this because if Psalm considers this to be bad, it should not be hidden by isset(). For example, here's what happens without isset: https://psalm.dev/r/cd1100bc9e There's a PossiblyUndefinedVariable that pops up. This is an issue that can be fixed, however psalm fixes it wrong and removes `$toCheck = false` altogether

**Comment by williamdes** [comment]
This one is similar and psalm thinks that  `trigger_error` makes the code exit I suppose: https://psalm.dev/r/38c501845b

Source: https://github.com/phpmyadmin/phpmyadmin/blob/e7c2557f0245a9a618a4263115924ad22c2cf501/libraries/classes/ThemeManager.php#L68

**Comment by orklah** [comment]
> This one is similar and psalm thinks that `trigger_error` makes the code exit I suppose: https://psalm.dev/r/38c501845b

It does in this case but I don't like it. I made an issue some time ago for the exact opposite issue and I was told Psalm can't assume trigger_error will exit :p https://github.com/vimeo/psalm/issues/3508 Psalm should at least be coherent. Can you create a new issue for this please?

**Comment by williamdes** [comment]
Same: https://github.com/phpmyadmin/phpmyadmin/blob/8e4d6229a999bfd9c5eb94eea27d601ab2a43546/libraries/classes/Plugins.php#L365

it is used after as `if (! empty($not_subgroup_header)) {`

**Comment by williamdes** [comment]
This is really a wide problem, it would want to remove the following assignments
- https://github.com/phpmyadmin/phpmyadmin/blob/1c084de30b76a1e044bf717739c691346cd62a28/libraries/classes/Plugins/Export/ExportHtmlword.php#L421
- https://github.com/phpmyadmin/phpmyadmin/blob/1c084de30b76a1e044bf717739c691346cd62a28/libraries/classes/Plugins/Export/ExportHtmlword.php#L428

**Comment by orklah** [comment]
I'm gonna close this issue. The trigger_error has been fixed and the PossiblyUndefined was explained in more details here: https://github.com/vimeo/psalm/issues/7237
