### ISSUE TITLE
obvious WTF UnusedVariable case

### ISSUE THREAD

**Issue by williamdes** [vimeo/psalm#6111]
https://psalm.dev/r/d4c10c74f0

What is wrong ?, really this one is special 😄 

Source: https://github.com/phpmyadmin/phpmyadmin/blob/cab899d7b5716559d025a0751ec2b8d763bd5111/libraries/classes/Utils/HttpRequest.php#L66

**Comment by orklah** [comment]
simplified:
https://psalm.dev/r/e8c7c7b638

Psalm should consider a variable fetched with global behave similarly to a reference. Any modification made to the variable is "using" the variable. Even if there are no other use of the variable in the current scope

**Comment by orklah** [comment]
Note that if your code use globals, there's a config in your xml file to help Psalm figure out what's in each variable: https://psalm.dev/docs/running_psalm/configuration/#globals
It should help a lot in the search for Mixed variables

**Comment by williamdes** [comment]
> Note that if your code use globals, there's a config in your xml file to help Psalm figure out what's in each variable: https://psalm.dev/docs/running_psalm/configuration/#globals
> It should help a lot in the search for Mixed variables

Thank you so much !

It also triggers without the global: https://psalm.dev/r/fa23212ad8

**Comment by orklah** [comment]
> It also triggers without the global: https://psalm.dev/r/fa23212ad8

Yeah, but without the global, it's legit. You effectively don't use $cfg after so there's no need to push content in it
