### ISSUE TITLE
UnusedVariable in a for list

### ISSUE THREAD

**Issue by williamdes** [vimeo/psalm#6112]
https://psalm.dev/r/0c6199539f

Psalm would remove the variable at: https://github.com/phpmyadmin/phpmyadmin/blob/9adaa912e1d284a09dab73cf9f6fc0d148fbdf96/libraries/classes/Controllers/HomeController.php#L125

**Comment by orklah** [comment]
I have no idea what's going on here. I guess it's a issue with how Psalm thinks the loop operates but it's weird.

**Comment by williamdes** [comment]
It also would want to remove https://github.com/phpmyadmin/phpmyadmin/blob/1835ebb4fccc20aa06868be88ab8bcaa9c395ccf/libraries/classes/Gis/GisMultiPolygon.php#L135

But I am not sure this is valid

**Comment by orklah** [comment]
I think it's valid. IIRC, explode never returns an empty-array (it returns an array with an empty string if given an empty string).  This means you'll enter the foreach loop at least once, and inside you have an if and else that both overwrite the variable.

**Comment by orklah** [comment]
This is actually more sensible than I thought:

All you need is to initialize your variable $charsetsList before the loop. As I said in a previous issue, Psalm really doesn't like dealing with non-initialized variables (I'd suggest fixing those before removing UnusedVariable.

I'm closing this as there is no real issue with UnusedVariable
