### ISSUE TITLE
Report usage of depreacted properties

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#6118]
In a large class or a class with widely used public properties it may be difficult to immediately delete an unwanted property, and preferable to deprecate it.

I would like Psalm to report usages of deprecated properties, as at 

https://psalm.dev/r/34c8584df8

**Comment by weirdan** [comment]
Actually Psalm reports deprecated properties when they are accessed from outside of the class. I don't see a reason why we shouldn't report when accessed from the class scope.

**Comment by weirdan** [comment]
Moreover, we already report property writes: https://psalm.dev/r/66aa00201a
