### ISSUE TITLE
Argument 2 of ArrayIterator::__construct expects 1|2|3

### ISSUE THREAD

**Issue by roukmoute** [vimeo/psalm#6119]
Hi,

I have this error : 

```sh
ERROR: ArgumentTypeCoercion - src/MyFile.php - Argument 2 of ArrayIterator::__construct expects 1|2|3, parent type int provided (see https://psalm.dev/193)
        parent::__construct($scopes, $flags);
```
with this code : 

```php
public function __construct(array $scopes = [], int $flags = 0)
```

I understand this because we have theses link: 
- https://www.php.net/manual/en/arrayiterator.setflags.php
- https://www.php.net/manual/en/class.arrayiterator.php#arrayiterator.constants

But we have two links: 
- The documentation: https://www.php.net/manual/fr/arrayiterator.construct.php use 0 by default
- And the source code: https://github.com/php/php-src/blob/54c4c7d747e8d656853f490e90b0fed66258f841/ext/spl/spl_array.c#L1166-L1178

So do you think is it possible to accept 0, or to update the error to add what it is the best choice instead of 0?

Thanks in advance

**Comment by roukmoute** [comment]
Ok https://psalm.dev/r/ec62c23746 works but I'm on 4.8, I suppose that I must wait a new version.

**Comment by weirdan** [comment]
You missed the parent call though: https://psalm.dev/r/47adc27234

0 should be added (as it represents both flags to be off), but your code needs to make sure you don't pass e.g. 255. You can propagate the check one level up by using `int-mask<>` param type: https://psalm.dev/r/6f9119f9b6

**Comment by weirdan** [comment]
Actually I think 0 should always be allowed for `int-mask<>` and `int-mask-of<>`.
