### ISSUE TITLE
Cannot access array value on mixed variable

### ISSUE THREAD

**Issue by roukmoute** [vimeo/psalm#6124]
Hi,

With this snippet: https://psalm.dev/r/a1d1fdc1d7

Is it possible if the `try/catch` has been passed that the `$responseDecoded` is not an array?

To do not have `MixedArrayAccess` I can add a condition to check if this is an array, but for me is it useless, am I wrong?

Thanks in advance

**Comment by orklah** [comment]
json_decode returns a lot of types: https://3v4l.org/1U5bF so yeah, the variable is kinda mixed. The best we could do is something like `scalar|null|array` when `$associative` is true and `scalar|null|array|stdClass` when it's true and check the flags when it's null.

I guess technically your issue would disappear: https://psalm.dev/r/fbe9b8706e
Feel free to propose a PR for that, though I'm not certain it will be accepted, this may have some impacts on projects

**Comment by roukmoute** [comment]
Thanks for your examples, I had never paid attention to these possibilities.

**Comment by orklah** [comment]
I'll close this. The current behaviour seem sound
