### ISSUE TITLE
psalter doesn't respect the indentation?

### ISSUE THREAD

**Issue by burzum** [vimeo/psalm#613]
Is there any way I can control how psalter fixes / adds things?  The indentation is wrong, the way we declare the @return is different as well. Also why does it add `@psalm-return`?

![image](https://user-images.githubusercontent.com/162789/37804721-f8156d82-2e35-11e8-952d-0bd899beb190.png)

Is there any way besides writing my own fixer to control this?

**Comment by muglug** [comment]
Oh this is embarrassing. Psalter currently just works with space-based indentation. I’ll fix tonight

**Comment by muglug** [comment]
`@psalm-return` is added when Psalm has more information about return values than can be expressed with a phpdoc-compatible type. So here for instance, it’s specifying that the function returns an array of a particular shape. That information can be used by Psalm to find other issues e.g

```php
$a = $obj->searchProfiles()['tile']);
```

**Comment by muglug** [comment]
Would you be able to paste this code verbatim in a gist? I’m having a little trouble replicating (tabs work fine locally)

**Comment by muglug** [comment]
If you have a chance to try again, please feel free to reopen this ticket
