### ISSUE TITLE
`print`, `exit`, and `die` effect IO but they are considered pure.

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#6136]
ref: https://psalm.dev/r/f3713595ce

**Comment by azjezz** [comment]
Note: `foo()` function in the example is `pure`, the error should be in the return type, as it claims to return a pure callable, while it returns an impure one ( uses `print` )

**Comment by orklah** [comment]
I'm onboard for print, but can you explain what's the desired behaviour for die() and exit()? From what I see, purity is only useful in the context of the process still running. Is this only for principle or does this have practical applications?

**Comment by azjezz** [comment]
a function signature might be `noreturn` ( `never` ), which is okay to use in pure code, it might throw an exception, or stops the process, however, interacting with I/O is not a pure behavior, as it results in a side effect, stopping the process and throwing are also side effects, however, in psalm it's kept simple, and they are not considered side effects ( even tho most other languages consider them that ).

I think die should only be considered pure when it's called without an argument.

**Comment by weirdan** [comment]
I can imagine cases where you may want to make sure no unexpected output generated. E.g. language server, generating images, etc.

**Comment by weirdan** [comment]
> I think die should only be considered pure when it's called without an argument.

`die()` and `exit()` do not affect IO when called with integer argument (I don't think setting the exit code qualifies as IO).

**Comment by azjezz** [comment]
> die() and exit() do not affect IO when called with integer argument (I don't think setting the exit code qualifies as IO).

yea, so conditionally pure if the type of the argument is not a string.

**Comment by Jack97** [comment]
I can pick this up if it hasn't already been started, I've briefly looked into the issue and can see that it's caused by both the `ExitAnalyzer` and `PrintAnalyzer` lacking purity checks.
