### ISSUE TITLE
Overwriten parent 

### ISSUE THREAD

**Issue by roukmoute** [vimeo/psalm#6137]
Hi,

Is it possible to fix this kind of error: https://psalm.dev/r/cc6ce91bfd in my project?

Because if I dump `$vars`, I get this:

```sh
array(12) {
  'VAR_FOO' =>
  string(6) "foo"
  'VAR_BAR' =>
  string(10) "bar"
  'VAR_BAZ' =>
  string(11) "baz"
}
```

So my `@param array<string, string> $scopes` is correct but I don't know if I can overwrite the parent about `mixed` and prefer a more precise type hint.

**Comment by weirdan** [comment]
You can override inference for any expression by using `@var` tag: https://psalm.dev/r/667f32291c
