### ISSUE TITLE
FilesystemIterator::__construct bitwise flags generates ridiculous error

### ISSUE THREAD

**Issue by othercorey** [vimeo/psalm#6143]
https://psalm.dev/r/84049d652b

https://www.php.net/manual/en/filesystemiterator.construct.php

Even when passing the exact same flags as documentation for default, it generates a massive error which I assume is trying to show all bitwise combinations.

> ERROR: ArgumentTypeCoercion - 4:32 - Argument 2 of FilesystemIterator::__construct expects 0|16|32|48|256|272|288|304|512|528|544|560|768|784|800|816|4096|4112|4128|4144|4352|4368|4384|4400|4608|4624|4640|4656|4864|4880|4896|4912|8192|8208|8224|8240|8448|8464|8480|8496|8704|8720|8736|8752|8960|8976|8992|9008|12288|12304|12320|12336|12544|12560|12576|12592|12800|12816|12832|12848|13056|13072|13088|13104, parent type int provided

I'm not sure this should be trying to verify that every input is a specific bitwise combination, but should certainly pass with a valid combination of constants.

The callmap just show an `int` type so I don't know how this is generated:
```
'FilesystemIterator::__construct' => ['void', 'path'=>'string', 'flags='=>'int'],
```

**Comment by orklah** [comment]
If you give psalm the flags directly, it will be happy: https://psalm.dev/r/b1fd01ba3e

But in your example, you push it any int, so Psalm warns you there are invalid values.

You should do https://psalm.dev/r/1f496d334c to "pass" the constraint to the calling method
