### ISSUE TITLE
Protect from double iteration when we're not 100% sure that an `iterable` is rewindable?

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#6157]
In following code snippet, psalm does not currently find any error ( https://psalm.dev/r/714ff9beb1 ):

```php
<?php

/** @param iterable<array-key, int> $input */
function brokenIteration(iterable $input): void
{
    foreach ($input as $value) {
        consume($value);
    }
    
    // expecting a type error here: `$input` is a consumed iterator, and cannot be re-used
    foreach ($input as $value) {
        consume($value);
    }
}
    
function consume(mixed $value): void {
    throw new Exception('irrelevant ' . var_export($value, true));
}
```

This code is, from a type perspective, un-sound though. The reason is that in PHP, `iterable`, as well as any `Traversable` in general, does not guarantee that traversal can be performed multiple times.

In practice, operations like `foreach ()`:

 * should accept only `iterable&!consumed-iterable` (or similar pseudo-type)
 * should turn an `iterable` into an `iterable&consumed-iterable` after the first `foreach` statement, or `$iterator->next()` call

Pushing this further, if we declare that a function returns an `iterable`, we could decide to implicitly add an `iterable&!consumed-iterable` to its declaration. That would prevent an `iterable` from being consumed, then being passed on to other functions, like in following example ( https://psalm.dev/r/5127f0acfe ): 

```php
<?php

/** 
 * @param iterable<array-key, array> $items
 * @return iterable<array-key, array>
 */
function appendSomethingToEachItem(iterable $items): iterable {
    foreach ($items as &$item) { // by-ref yuck, but just making an example
        $item['decorated'] = 'haha';
    }
    
    return $items;
}

/** @param iterable<array-key, array> $items */
function useIterable(iterable $items): void {
    $items = appendSomethingToEachItem($items); // $items is now broken/unusable
    
    foreach ($items as $item) { // this will lead to a crash, when a non-rewindable iterator is given
        consume($item);
    }
}
    
function consume(mixed $value): void {
    throw new Exception('irrelevant ' . var_export($value, true));
}
```

Taking the example above, we can see the actual crash in a runtime scenario ( https://3v4l.org/N86IE ):

```php
<?php

/** 
 * @param iterable<array-key, array> $items
 * @return iterable<array-key, array>
 */
function appendSomethingToEachItem(iterable $items): iterable {
    foreach ($items as $item) { // note: removed by-ref, since it's not compatible with generators anyway
        // empty, expected, just making an example.
    }
    
    return $items;
}

/** @param iterable<array-key, array> $items */
function useIterable(iterable $items): void {
    $items = appendSomethingToEachItem($items); // $items is now broken/unusable
    
    foreach ($items as $item) { // this will lead to a crash, when a non-rewindable iterator is given
        consume($item);
    }
}
    
function consume(mixed $value): void {
    var_dump($value);
}

useIterable([['a'], ['b'], ['c']]); // ok
useIterable((function () {
    yield ['a'];
    yield ['b'];
    yield ['c'];
})()); // not rewindable - crash
```

Which produces:

```
array(1) {
  [0]=>
  string(1) "a"
}
array(1) {
  [0]=>
  string(1) "b"
}
array(1) {
  [0]=>
  string(1) "c"
}

Fatal error: Uncaught Exception: Cannot traverse an already closed generator in /in/N86IE:19
Stack trace:
#0 /in/N86IE(33): useIterable(Object(Generator))
#1 {main}
  thrown in /in/N86IE on line 19
```

**Comment by weirdan** [comment]
> `$items = appendSomethingToEachItem($items); // $items is now broken/unusable`

Note that `$items` is broken even if it's not assigned to:
```php
appendSomethingToEachItem($items); // as broken as the one above
```
even though it is not an in/out param. IMO this makes it a bad fit for a type. It looks like Rust-like ownership/borrowing system would solve this, but introducing that just for iterables seems an overkill.

**Comment by Ocramius** [comment]
> It looks like Rust-like ownership/borrowing system

Pretty much that: it's a very hard to crack problem, and perhaps not one that is necessarily easy to fix.

Considering every `iterable` as inout parameter could also work for that, if mutating the type in the PHI form would be the outcome.

**Comment by orklah** [comment]
This could probably be implemented in userland with some variation of this: https://psalm.dev/r/4f546d8ce1

**Comment by Ocramius** [comment]
Closing here: I really like @orklah's suggestion of using `@psalm-this-out self<never>` or such.

While it doesn't help with generic `iterable` types, it is a good enough use-case for documenting some specific iterator types as unsafe.
