### ISSUE TITLE
`array_slice()`ing templated array parameter infers array<array-key, mixed>

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#6160]
https://psalm.dev/r/e5c56d6c48

Versions 
without `@template`: https://psalm.dev/r/e933bf53a9
and without `array_slice`: https://psalm.dev/r/42bab64fa6

behave as expected

**Comment by weirdan** [comment]
That template on the method is a bit useless though, as it does not constrain neither the output nor other parameters.

**Comment by someniatko** [comment]
@weirdan Yeah, i know, it's just a minimal case.

Here's the production-ish code: https://psalm.dev/r/d740c96dea
