### ISSUE TITLE
Access by key immediately after array_key_exists return true

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#6174]
Is there a way to make Psalm happy here (https://psalm.dev/r/0d792bc92e):

```php
class C
{
    public function __construct(private string $key) {}
    
    /**
     * @template K as array-key
     * @template V
     * @param array<K,V> $record
     */
    public function f(array $record): void {
        if (!array_key_exists($this->key, $record)) {
            throw new RuntimeException;
        }
        print_r($record[$this->key]);
    }
}
```
> ERROR: PossiblyInvalidArrayOffset - 16:17 - Cannot access value on variable $record using a string offset, expecting K:fn-c::f as array-key

**Comment by orklah** [comment]
Something like that should do:
https://psalm.dev/r/a3c55ce9b2

If you want to use $this->key as an offset of your `array<K, V>`, then it must be `K`, not just any string
