### ISSUE TITLE
Conditional interfaces

### ISSUE THREAD

**Issue by designermonkey** [vimeo/psalm#6175]
Please see https://psalm.dev/r/105b581007

I'm sure I've done this before and it's worked in the PHP interpretor although I don't actually remember. I've tried this on PHP 7.4 and 8.

Is this error correct? Is this legal syntax?

**Comment by weirdan** [comment]
It is valid syntax in PHP, but Psalm currently does not support conditional interfaces nor traits.

**Comment by designermonkey** [comment]
Okidoke. Should I leave this open then as a reminder?

**Comment by weirdan** [comment]
Yep, please do.

**Comment by weirdan** [comment]
> Psalm currently does not support conditional interfaces nor traits.

Conditional traits are now supported.

**Comment by weirdan** [comment]
Duplicate of #5338
