### ISSUE TITLE
shell_exec can return `false`

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#6177]
Related to https://github.com/phpstan/phpstan/discussions/5376#discussioncomment-1050042
Seems like unlike is saying the php documentation, shell_exec can return `false` https://github.com/php/php-src/pull/7306

But psalm consider the return type to be `string|null`
https://psalm.dev/r/36a3eb5fa8

Where should I update the return type definition ?

**Comment by weirdan** [comment]
> Where should I update the return type definition ?

Just `dictionaries/CallMap.php` (no changes to deltas are required).

**Comment by VincentLanglet** [comment]
Thanks, https://github.com/vimeo/psalm/pull/6178
