### ISSUE TITLE
InvalidLiteralArgument should allow class-string (on `strpos`, `trim` etc.)

### ISSUE THREAD

**Issue by 7ochem** [vimeo/psalm#6191]
I stumbled upon the error `Argument 1 of strrpos expects a non-literal value, App\FooBar::class provided`. See below example.

Caused by #4070

```php
<?php

namespace App;

class FooBar {}

$class = FooBar::class;

echo strtolower(substr($class, (int)strrpos($class, '\\') + 1)); // Gives "foobar"

// You might argue that you as a programmer already know the outcome. Why not write:
echo 'foobar';
```

I think the usage of `FooBar::class` construction here is very useful for instance when searching for usages of the `FooBar` class with your popular IDE or when refactoring the name of the `FooBar` class (by automation).

Should class-string be excluded from this error? Or is there a suppression in the config possible?

https://psalm.dev/r/b29f268ede

In the referenced snippet 👆🏻 there might be another/different issue in the second example, already (partially?) solved via #4070 mentioning _an explicit check for strings with sequential characters_. This second example might not be a real user-land example tough...

**Comment by weirdan** [comment]
> Or is there a suppression in the config possible?

You can suppress `InvalidLiteralArgument` in the config, just like most other issues.

**Comment by 7ochem** [comment]
> > Or is there a suppression in the config possible?
> 
> You can suppress `InvalidLiteralArgument` in the config, just like most other issues.

Of course that is a possibility, but the check is there to prevent certain situations. My opinion is that a class-string is a special case in this rule. So instead of disabling it completely, I wish it could ignore class-strings.

**Comment by orklah** [comment]
This was fixed
