### ISSUE TITLE
False-positive LessSpecificReturnType when interface implementation returned

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#6201]
https://psalm.dev/r/d905ad8090

It seems to me an interface implementation shouldn't trigger `LessSpecificReturnType` 🤔

**Comment by weirdan** [comment]
With the settings you used it should.
![image](https://user-images.githubusercontent.com/57403/127490884-864a41c3-66e4-441a-8d82-5b06945ec597.png)
