### ISSUE TITLE
Deprecate TPositiveInt for removal in Psalm 5?

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#6209]
Hi,

I want to talk about TPositiveInt and it's future. With the introduction of TIntRange, it has become a redundancy of a more precise type. I checked how it's handled in PHPStan, and it seems like "positive-int" and "negative-int" are just aliases of their Integer Range type and that makes sense.

This would probably help issues like https://github.com/vimeo/psalm/issues/6020 that are really hard to do with the current internal assertions system.

Unfortunately, we can't just remove TPositiveInt as there are plugins (including mine) that uses it, so we have to go through a deprecation process. However, the enhancement I intend to do on TIntRange will probably be made different whether or not we want to keep TPositiveInt in the long term, so I'm creating this issue so we can decide something

**Comment by muglug** [comment]
That sounds like a good idea!

**Comment by weirdan** [comment]
Sounds good to me.
