### ISSUE TITLE
`in_array` assertion with dynamic haystack doesn't reconcile needle type to array's value type

### ISSUE THREAD

**Issue by supersmile2009** [vimeo/psalm#6220]
Example:
```
function inArrayFromRange(?int $val): int {
    if (!in_array($val, range(0, 4), true)) {
        throw new \Exception();
    }
    
    return $val;
}
```

Errors:
```
ERROR: NullableReturnStatement - 29:12 - The declared return type 'int' for inArrayFromRange is not nullable, but the function returns 'int|null'

ERROR: InvalidNullableReturnType - 24:39 - The declared return type 'int' for inArrayFromRange is not nullable, but 'int|null' contains null
```

I expect `$val` to be `int` type after the assertion.
In all the cases I tested with haystack being `non-empty-list<T>` psalm fails to reconcile the needle type to `T` after the assertion. It works fine with fixed arrays though (e. g. `[0, 1]`)

More examples:
https://psalm.dev/r/53fed31716

**Comment by orklah** [comment]
If you want to take a look, it's handled in AssertionFinder::getInarrayAssertions
