### ISSUE TITLE
Suppression is being detected as unused even tho it is not unused when removing that suppression

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#6225]
Hey there,

sadly, I can not toggle the option `findUnusedPsalmSuppress` for psalm.dev and thus, I can not provide examples of both cases.
But actually, I have the following code and psalm (4.9.2) says, that the suppression is unused.

When I remove the suppression, I get the error which should be suppressed.

https://psalm.dev/r/36d3ff1418

Not sure why this is the case and sadly, I can not change the abstract class as it is provided by 3rd-party.
I'll create a PR for that but until then, I'd like to suppress the error without using a baseline.

Any ideas what could confuse psalm there?

**Comment by weirdan** [comment]
This seems to have been fixed since.
