### ISSUE TITLE
Psalm doesn't understand validation inside constructor

### ISSUE THREAD

**Issue by tssge** [vimeo/psalm#6226]
https://psalm.dev/r/5d63696e20

**Comment by orklah** [comment]
What about https://psalm.dev/r/b7b2e6c050 ?

**Comment by weirdan** [comment]
If `$this->something` can never be null, why you're declaring it nullable in the first place?

**Comment by tssge** [comment]
@orklah Here's a better example https://psalm.dev/r/477c90b06a

@weirdan in our real world code we initialize user from session if one exists. Some subclasses require user, some don't (validation in constructor, die if $this->user === null). I know it's bad code, but just trying to annotate it for Psalm to refactor it away eventually

**Comment by zmitic** [comment]
@tssge Use this as a temporary solution: https://psalm.dev/r/65e89f5f8b

**Comment by bitwise-operators** [comment]
I wouldn't consider this a bug. Just because the constructor doesn't allow null values, doesn't mean the property can't become null through other means. something is a public variable, and declared as int|null. So the test() function can't assume it's not null.

The question remains: If you don't want to allow null values, why is the property nullable?

The proper code would be something like this:
https://psalm.dev/r/f1fd88ecae

**Comment by tssge** [comment]
@bitwise-operators I'd understand if @ readonly worked. However even marking the property readonly does not fix the issue, even though there's no way anything could write null to it there.

Yes, there are better ways to do it, it's shitty code, but when trying to modernize an old codebase Psalm would help greatly to offer a safety net when refactoring.

Here's more real worldly example: https://psalm.dev/r/d0d5508202

**Comment by bitwise-operators** [comment]
Not exactly. Check this example:
https://psalm.dev/r/9314c87648
A child class could overwrite the constructor, but not the doSomethingWithUser() method. 

Granted, this could be solved with a final keyword, in which case the NullableReturnStatement is still there. With that as an example, I'm not actually sure whether it's a bug or not.

Easiest workaround for you right now, that won't bite you too much when you refactor at a later date, would probably to add 
`/** @var int */ `
above the return statement of the doSomethingWithUser() method. This will be valid even if the property is turned into a pure int later.

**Comment by orklah** [comment]
Sorry but this won't make it into Psalm. This would mean lowering the standard of Psalm for everyone to support an edge case that would probably introduce new bugs. Feel free to look into Plugins to alter types inside your classes
