### ISSUE TITLE
Callable array syntax with literal second element

### ISSUE THREAD

**Issue by timdev** [vimeo/psalm#6230]
Psalm seems to treat a string literal differently from a non-literal string in the method element of an array-style callable.

This works:

https://psalm.dev/r/2464c26fc3

while this emits errors:

https://psalm.dev/r/d647c75ab1

Which seems wrong.

**Comment by orklah** [comment]
This is working: https://psalm.dev/r/331cf4b863

So there's 2 potential issues here:
- Psalm is less strict when given an `array{class-string, string}` for a callable than it is when given `array{class-string, 'MyMethod'}`
- The in_array + class_implements does not work in Psalm

For the first, it kinda makes sense. The same way accessing an array with an `int` offset is allowed but accessing with a `1` offset is forbidden without using isset().

For the second, it's a difficult construct to understand and I believe is_a() is more appropriate here anyway.

So I'm inclined to close this. With these elements, do you agree @timdev or do you still want something changed, and if so, what would you change?

**Comment by timdev** [comment]
`is_a()` is indeed better, and it's not surprising that the original expression's semantics are not reasonable to analyze. My original construction of that sub-expression was something of a brain-fart.

It remains somewhat astonishing, at least on the surface, that `array{string, string}` satisfies `callable`, but `array{class-string, string}` does not (until the programmer explicitly checks/demonstrates the method exists). Sometimes, psalm verifies that `callable` is actually a valid callable, other times it only verifies that it can't be certain it isn't valid.

If I were to suggest a change, it would be that `array{string, string}` shouldn't satisfy `callable`:

https://psalm.dev/r/4fd9fb064f

But there may be cases where that would be too cumbersome?

**Comment by orklah** [comment]
Note that `array{class-string, string}` does satisfy the callable. `array{class-string, 'MyMethod'}` doesn't though.

I'm not sure what the impact would be if we forced every `array{string, string}` to be checked by is_callable...

But it didn't seem unreasonable because we have the same behaviour here: https://psalm.dev/r/09b3889c7d
`int` is allowed but `1` is not.

**Comment by timdev** [comment]
I not experienced enough with psalm to tell whether forcing an is_callable check would be a good idea or not, but it does seem as though there might be cases where that would frustrate users.

Conceptually, I'm not sure I like the `int`/`1` behavior either. At least initially, that seems astonishing, since we again have a situation where something that holds true for a wider type no longer holds for a narrower one.

I'm fine with closing this. I think we've explored the relevant issues, and there's not a clear improvement to be made. 

Thanks for your time; I've learned something.

**Comment by orklah** [comment]
You're welcome :) It's one of my goals!

I'm also not a big fan of `int`/`1` but I recognize that if the goal is to maximize bug finding while keeping false positives low, it's a reasonable compromise. Maybe something to be enforced at a higher level one day?

@weirdan what would you think about enforcing that every `array{string, string}` must be checked for callable-ness?

**Comment by weirdan** [comment]
> what would you think about enforcing that every array{string, string} must be checked for callable-ness?

I'm good with that, it does look like an omission to me.

**Comment by orklah** [comment]
I tried to do it but I think I understand why this is like this.

- If I try to make Psalm understand the Keyed Array is coerced to be a callable but the comparison is still true, I get no error
- If I try to make the comparison false, I now get an error but unfortunately, it breaks Psalter. Psalter need to know this is a potential callable to be able to register the method name and or class name and prevent deletion of any method that could match as `UnusedMethod`

I'm gonna close this, but if anyone want to work on this in the future, they're welcome. I guess a solution would be to make Psalm understand that it must emit an error even when the Keyed Array is considered a callable BUT the type is still flagged as coerced. Not sure what other side effect could occur then.
