### ISSUE TITLE
Template is not verified when concrete implementation is returned

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#6236]
Hey there,

not sure if there is a shorter example but I think that a template type is not properly resolved when a concrete implementation is returned:

https://psalm.dev/r/c308dbe33d

I'd expect this to be valid but actually its not. Is there something wrong in my brain or is that a bug?

Thanks in advance.

**Comment by weirdan** [comment]
Templates are invariant, so if return type says you must return `Foo<Baz>` you cannot return `Foo<Bar>`, even if `Bar` inherits `Baz`. See https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance
