### ISSUE TITLE
Use different issue type from PossiblyUndefinedVariable for possibly undefined array keys

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#624]
Array key warnings will probably have a higher false positive rate than variables.

Changing to `PossiblyUndefinedArrayOffset` (or something like that) would allow array key warnings to be suppressed without also suppressing warnings about variables

**Comment by muglug** [comment]
On the other hand, use of optional array keys is fairly limited. But I agree this is something to think about for version 2 (when I can safely change APIs a little)
