### ISSUE TITLE
PHP 8 Bug: Argument 2 of `date()` cannot be null, possibly null value provided

### ISSUE THREAD

**Issue by masonmcelvain** [vimeo/psalm#6243]
Psalm complains when `null` is passed as the 2nd argument (`$timestamp`) of [`date()`](https://www.php.net/manual/en/function.date.php). As of PHP 8, `$timestamp` is a nullable int whereas it was just an int in prior versions.

## Example

https://psalm.dev/r/52eb795065

## Proposed Solution

Add a callmap for `date()` in https://github.com/vimeo/psalm/blob/master/dictionaries/CallMap_80_delta.php

**Comment by orklah** [comment]
> Add a callmap for `date()` in https://github.com/vimeo/psalm/blob/master/dictionaries/CallMap_80_delta.php

Indeed, do you want to give it a try?
