### ISSUE TITLE
Sum of two `0|positive-int` variables result in `int`

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#6245]
Hey there,

when I add two variables of `0|positive-int`, psalm infers `int` rather than `0|positive-int`.
I guess thats an edgecase, as it works with `positive-int`.

https://psalm.dev/r/750408a26f
https://psalm.dev/r/ca3721fbf8

**Comment by orklah** [comment]
It's because when Psalm does all the combinations, 0 + positive, positive + 0 and positive + positive, everything is positive.

As soon as you introduce the second 0, there is one combination which is not positive and Psalm didn't handle this edge case.

If you want to take a shot, it's handled here: https://github.com/vimeo/psalm/blob/019b35850ac31b3919143ea8e202881e863c925f/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonDivArithmeticOpAnalyzer.php#L669

**Comment by boesing** [comment]
Will do, getting warm with psalm internals 😄

**Comment by weirdan** [comment]
@orklah shouldn't that also have `|float`? E.g. `PHP_INT_MAX + PHP_INT_MAX` is `float`: https://3v4l.org/o3od1

**Comment by orklah** [comment]
It would be statically correct, but do we want to force people adding two positive ints together to check for float each time? (I wish I could disable this in PHP...).

**Comment by weirdan** [comment]
As long as it still allows for float check I think we're good. And it does seem to be the case: https://psalm.dev/r/d6cf1af7f1

**Comment by orklah** [comment]
This is handled by the from_calculation flag I think

**Comment by boesing** [comment]
Actually, anything greater than `PHP_INT_MAX` or lower than `PHP_INT_MIN` is treated as float.
https://3v4l.org/o0oYb

But actually, there is not yet a psalm type reflecting `PHP_INT_MAX` or `PHP_INT_MIN` and since these differ between 64-bit and 32-bit versions of PHP (32-bit is still a thing, right? never thought about it TBH 😂)  I don't think that there is a way to verify if `positive-int + positive-int` will result in float until it is passed as a `TLiteralInt` while calculating the outcome in psalm itself.

Maybe its worth adding a opt-in flag via psalm config to enable such check that any `int + int` or `int - int` may result in `float`? 🤷🏼‍♂️

**Comment by boesing** [comment]
https://3v4l.org/jR46X

🤦🏼‍♂️

**Comment by orklah** [comment]
It's already handled when you have two literal ints (check arithmeticOperation)

But yeah, PHP start doing some weird things around those limits, not worth loosing sleep over IMHO

**Comment by boesing** [comment]
Hm, `PHP_INT_MAX` constant is only detected as `int` not `positive-int`. 
https://psalm.dev/r/270380ae25

So this really adds up 🙈

**Comment by weirdan** [comment]
@boesing if you want to fix `PHP_INT_MAX` inference it's here: https://github.com/vimeo/psalm/blob/6f1d43813f0586b931cdea32a5a7733980dc8f51/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ConstFetchAnalyzer.php#L167-L173

**Comment by orklah** [comment]
I'm not sure of the best way to fix that though...
TPositiveInt is very wide for that, TIntRange has no way to tell `int<max, max>` and TLiteralInt would generate a fixed number dependant on Psalm's env and not dependant on the actual production environment, that could lead to weird issues

**Comment by boesing** [comment]
@orklah yah, I dont think that it is possible to fix the initial issue but the constant does not need to be a range. assuming it is positive would be fine I guess

**Comment by weirdan** [comment]
> TPositiveInt is very wide for that,

It's still narrower than full `int`, so that's still an improvement.

**Comment by orklah** [comment]
The initial issue can be fixed too. The float result is not really an issue. Anyway, it should be fixed with the TIntRange introduction and TPositiveInt deprecation in a few weeks

**Comment by boesing** [comment]
What does `TPositiveInt` deprecation mean? Are `positive-int` annotations deprecated with that as well?

**Comment by orklah** [comment]
A new type was introduced a few release ago who looks like `int<5, max>` to describe any int from 5 to infinity(technically, PHP_INT_MAX). positive-int will stay a valid annotation, but the goal is to make it an alias of `int<1, max>`. This way we could easily have a negative-int `int<min, -1>` and this will make it easier to talk about any range (`0|positive-int` will just become `int<0, max>`). Once this is done, it will be easier to do operations on ints, no need to have a special handling for `0` when it's just another int in the range.

**Comment by orklah** [comment]
Oh nice, it has been solved by a previous PR where I extended Psalm's capacity to do literal arithmetic, it doesn't need to go through the whole 'is_always_positive' flags anymore for it to work
