### ISSUE TITLE
C<string> ← C<lowercase-string> covariance checks

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#6246]
https://psalm.dev/r/bb0f49d71b

I guess this behavior is expected?

This unfortunately bite me by the `doctrine/collections` after Psalm recent update, `ArrayCollection<lowercase-string>` inferred by the following code:

```php
new ArrayCollection(
    array_unique(array_map('mb_strtolower', $strings))
)
```

 became incompatible with `Collection<string>`.

**Comment by weirdan** [comment]
It is indeed expected, as template type parameters are invariant by default. Unfortunately doctrine collections are mutable, so their type parameters cannot be made covariant.

**Comment by weirdan** [comment]
Of course you can override that with a `@var` docblock: `@var ArrayCollection<array-key, string>`
