### ISSUE TITLE
Invalid offsets warnings

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#625]
I'm getting invalid offsets running Psalm on a project that includes Doctrine:
```
PHP Notice:  Undefined offset: 6 in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 380

Notice: Undefined offset: 6 in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 380
PHP Notice:  Undefined offset: 7 in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 380

Notice: Undefined offset: 7 in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 380
```
`--debug` points to `vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php`

I suspect it originates from here: https://github.com/doctrine/doctrine2/blob/87ee409783a4a322b5597ebaae558661404055a7/lib/Doctrine/ORM/Query/SqlWalker.php#L196 (the line some previous commit crashed on), but I'm not 100% sure.

**Comment by muglug** [comment]
Thanks! Should be fixed now.
