### ISSUE TITLE
non empty string constants should be considered as a non empty string

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#6266]
With the option
```
ignoreInternalFunctionFalseReturn="false"
```

In
```
/** @var non-empty-string $foo */
$foo = PHP_EOL;
$bar = explode($foo, $diff);
```
$bar is considered as always an array.

In
```
$bar = explode(PHP_EOL, $diff);
```
$bar is considered as array|false.

So I would say that explode is correctly supporting non-empty-string, but some constant are not considered as non-empty-string. I tried
- PHP_EOL
- DIRECTORY_SEPARATOR
- a custom class constant `public const FOO = 'foo';`

Should these be `non-empty-string` ?
https://psalm.dev/r/377464f1cd

**Comment by weirdan** [comment]
> a custom class constant `public const FOO = 'foo';`

This one should be inferred as literal `"foo"`.

**Comment by weirdan** [comment]
The other two, I believe, would safe to assume non-empty.

**Comment by orklah** [comment]
`public const FOO = 'foo';`

Can be inherited and change value in the child

**Comment by VincentLanglet** [comment]
> `public const FOO = 'foo';`
> 
> 
> 
> Can be inherited and change value in the child
> 
> 

If I use static::FOO, or if it's final, it should be ok no ?
