### ISSUE TITLE
Psalm uses incorrect function when class exists multiple times

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#6269]
Since 4.9.0

I have a file that declares class Foo
I have stubs that also have the methods of Foo

in file of Foo, when using $this->some_function( 'hello' ) === false I get loads of errors, like DocblockTypeContradiction, TooManyArguments,... since psalm checks the some_function method of the stubs (which do have different number of args, param types,...) instead of the method some_function in the CURRENT file.

This was working as expected before 4.9.0, but not working anymore now.

Obviously cannot reproducet this on https://psalm.dev since I would need to be able to set stubs.

If you want a test case, I can prepare a repo

**Comment by orklah** [comment]
@kkmuffme yes, a repo would be great. Can you also explain why your stubs and class doesn't match and why the class should have priority?

@weirdan I think it must be related to the change about stubs loading.

**Comment by weirdan** [comment]
@orklah it very well could be, but let's see the repro.

**Comment by kkmuffme** [comment]
This actually is quite interesting because it will report errors in the stubs to be in my code.

e.g.

```
STUBS:
function hello() {}

MY CODE:
/**
 * do something
 * @return void
 */
function hello() {
    echo "hello";
}
```

Will generate a `MissingReturnType` for my code (file/line of my code) even though the error is in the stubs.
This should be sufficient to easily reproduce it (as fixing this error will fix all of my issues).

Could you check it like this?

**Comment by orklah** [comment]
Closing a stale, need a reproducer to check what's going on

**Comment by kkmuffme** [comment]
It's the same problem as https://github.com/vimeo/psalm/issues/3249 with repro here: https://github.com/vimeo/psalm/pull/6733#issuecomment-955682300
