### ISSUE TITLE
ext/hash compatibility

### ISSUE THREAD

**Issue by paragonie-scott** [vimeo/psalm#627]
https://travis-ci.org/paragonie/sodium_compat/jobs/358854868 - PHP 5.6 test on Travis CI

> Argument 1 of hash_update expects HashContext, resource provided

I'd like to be able to typehint this as `resource|HashContext`. Trying to conditionally define (`if PHP < 7.2, resource; else, HashContext`) doesn't seem possible.

**Comment by paragonie-scott** [comment]
Note: For my project, pinning to `^1.0` instead of `dev-master` fixes this type assertion, so that might be the trick for the time being.

**Comment by muglug** [comment]
@paragonie-scott do that for now. I'll add an optional config in `psalm.xml` specifying a PHP version, and use supplemental call maps like Phan does now.
