### ISSUE TITLE
@psalm-assert does not assert expected

### ISSUE THREAD

**Issue by loevgaard** [vimeo/psalm#6283]
https://psalm.dev/r/e42b19dfd4

Why doesn't Psalm understand that the offset `classes` is set?

**Comment by weirdan** [comment]
It does. However assertions are local to the context (in this case, the constructor). There's no guarantee that they will hold for all of the objects lifetime, so Psalm does not assume that. Use the property type instead.

**Comment by loevgaard** [comment]
Do you mean this? https://docs.phpdoc.org/latest/guide/references/phpdoc/tags/property.html

**Comment by loevgaard** [comment]
Or this one: `@psalm-type`?

**Comment by weirdan** [comment]
No, I mean the `@var` tag on a property: https://psalm.dev/r/6cc3c42d2d

**Comment by loevgaard** [comment]
Okay, thank you :)
