### ISSUE TITLE
Invalid PossiblyUndefinedVariable when try/catch/finally

### ISSUE THREAD

**Issue by ArtemGoutsoul** [vimeo/psalm#6286]
With this code
```
function func(string $name): void {
    try {
    }
    catch (Throwable $e) {
        if ($name === 'stuff') throw $e;
        echo $e->getCode();
    }
    finally {
    }
}
```

I get and error for line `echo $e->getCode();`:
```
INFO: PossiblyUndefinedVariable - 9:14 - Possibly undefined variable $e defined in try block
```
Funny thing, if I remove `if ($name === 'stuff') throw $e;` or if I remove `finally`, the error disappears...

Link: https://psalm.dev/r/e9822c86ed

**Comment by weirdan** [comment]
Not reproducible anymore: https://psalm.dev/r/e9822c86ed
