### ISSUE TITLE
UndefinedClass error when calling \GuzzleHttp\Psr7\uri_for

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#629]
> ERROR: UndefinedClass - src/Service/Http/StripeHttplugClient.php:36:16 - Class or interface GuzzleHttp\Psr7\UriInterface does not exist
        $uri = Psr7\uri_for($absUrl)->withQuery(http_build_query($params, '', '&', PHP_QUERY_RFC3986));

Not sure why is psalm trying to locate `GuzzleHttp\Psr7\UriInterface`. `functions.php` file where `uri_for` function is located refers to `Psr\Http\Message\UriInterface`

Here's the function Psalm complains about https://github.com/guzzle/psr7/blob/99bfec281379c040f37dc3c3e9312476875a2f62/src/functions.php#L54

**Comment by muglug** [comment]
Looks like a bug inferring namespaced function return types. Will fix.

**Comment by muglug** [comment]
Psalm wasn't properly analysing vendor-dir function's files (whereas classes would be properly scanned).
