### ISSUE TITLE
false-positive InvalidArgument on literal unions.

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#6292]
rep: https://psalm.dev/r/1530ea75be

This used to work in psalm, and `$e` would be `Type<'A'|'B'>`, since `$d` is `Type<'A'>` and `$c` is `Type<'B'>`

**Comment by weirdan** [comment]
Imagine that `union()` invokes some methods that alter `$_a` or `$_b` (e.g. exchanges their values). If Psalm was to allow that (because it would infer `T` to be `A|B`) it would mean that the code outside would still treat `$c` as `Type<A>`, while actually it would be `Type<B>` after the call.

Luckily it's easy to fix in this case: https://psalm.dev/r/684150f308

**Comment by azjezz** [comment]
> Imagine that union() invokes some methods that alter $_a or $_b (e.g. exchanges their values). If Psalm was to allow that (because it would infer T to be A|B) it would mean that the code outside would still treat $c as Type<A>, while actually it would be Type<B> after the call.

can you provide an example? i can't see a case where $_a or $_b values change results in the already created type to also change, unless it is passed by reference? 🤔 

> Luckily it's easy to fix in this case: https://psalm.dev/r/684150f308

This however doesn't solve the case of using multiple arguments ( which is done in `Psl\Type\union` and `Psl\Type\intersection` ).

https://psalm.dev/r/966574fd12

**Comment by weirdan** [comment]
> can you provide an example?

Sure, here you go: https://psalm.dev/r/8f07c64141

**Comment by azjezz** [comment]
Hm, what do you suggest as a solution where `T` value is known not to change?

**Comment by weirdan** [comment]
> T value is known not to change

That knowledge would be quite hard to formalize, I suppose. The closest I can think of is declaring the type parameter for `Type` as covariant: https://psalm.dev/r/3538a70cb8
