### ISSUE TITLE
DateTimeInterface does not include a lot of methods

### ISSUE THREAD

**Issue by fox91** [vimeo/psalm#6293]
See: https://psalm.dev/r/8c54b43157

The `DateTimeInterface` does not include many methods present in both of its implementations (`DateTime` and `DateTimeImmutable`) such as: `add`, `createFrom*`, `set*`, `sub`, etc.

If I have not misinterpreted issue #6152, shouldn't this psalm thing have been resolved with PR #6181?

For reference: https://bugs.php.net/bug.php?id=75195

**Comment by weirdan** [comment]
It wasn't the intention of that PR to allow mutating methods on DateTimeInterface. What that PR did, is that it let Psalm know that if you have a DateTimeInterface and check that it's a DateTime, in the `else` branch that same object would be treated as DateTimeImmutable.

I explained why what you're requesting is unsafe and should be flagged by Psalm here: https://github.com/vimeo/psalm/issues/6152#issuecomment-884005919

**Comment by fox91** [comment]
Thanks for the clarification, I missed your comment on this.

I think might be useful to include some explanation on this page https://psalm.dev/181 or generate a new one dedicated to this interface in particular.
