### ISSUE TITLE
Variadic arguments should be inferred as list

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#6299]
Hey there,

when using variadic function/method arguments, I would expect them to be a list - or is there a sneaky PHP "feature" which allows passing variadic arguments as non-list values which will then be interpreted by the method as a non-list as well?

https://psalm.dev/r/36abc5d42d

**Comment by boesing** [comment]
Nvm, PHP 8 allows variadic arguments to be passed as a map 🤦🏼‍♂️

**Comment by orklah** [comment]
@boesing you can add `@no-named-parameters` to tell psalm to watch for those and to revert the type back to a list
