### ISSUE TITLE
Asserts with constant wildcards

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6300]
https://psalm.dev/r/fc2b99f6eb

**Comment by weirdan** [comment]
When unions are spelled literally (`"a"|"b"|"c"`) it does work for `@psalm-assert`, but doesn't for `@psalm-assert-if-true`: https://psalm.dev/r/d1b97805cd

**Comment by weirdan** [comment]
Duplicate of #5939
Possibly related: #5372
Was once rejected in #2452, but it appears it was reconsidered (as it works for explicit unions with `@psalm-assert`)

**Comment by boesing** [comment]
@orklah it is broken for class-constants. It worked somewhen in an older version (4.7.0 for sure) but stopped working in later versions (havent checked which version broke this).
thats actually why I've created #6529
