### ISSUE TITLE
Psalm acts differently depending on what version of PHP it is executed on.

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#6305]
Context: I'm trying to fix an error that does not happen in the CI of doctrine/orm, but does happen on my machine where I use PHP 7.4.

I tried fixing it with an `assert`, but now I get the opposite situation: https://github.com/doctrine/orm/pull/8917

I cannot reproduce the issue on psalm.dev, that presumably does not run PHP 8

https://psalm.dev/r/a8f882ff61

On a machine with PHP 8, as well as on the CI, I know get this:

```
ERROR: RedundantConditionGivenDocblockType - lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php:912:13 - Docblock-defined type SimpleXMLElement for $action is never null (see https://psalm.dev/156)
            assert($action !== null);


ERROR: RedundantConditionGivenDocblockType - lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php:912:20 - Docblock-defined type SimpleXMLElement ca never contain null (see https://psalm.dev/156)
            assert($action !== null);
```

Either way, there is a difference in results depending on the version of PHP, and hardcoding `phpVersion` to `7.1` in psalm.xml does not help. I'm not sure what to try next.

See also: https://symfony-devs.slack.com/archives/C8SFXTD2M/p1628964600095200

**Comment by weirdan** [comment]
Steps to reproduce:
```
gh repo clone doctrine/orm
cd orm/
gh pr checkout 8917
phpenv local 8.0.7
composer install
vendor/bin/psalm lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
phpenv local system # 7.4.21
composer update -W
vendor/bin/psalm --clear-cache
vendor/bin/psalm lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
```

**Comment by orklah** [comment]
Thanks for digging into this @greg0ire !

**Comment by weirdan** [comment]
Under 8.0, `$action` is inferred as `SimpleXMLElement`, while under 7.4 it's thought to be `SimpleXMLIterator|null`

**Comment by orklah** [comment]
It's unfortunate, we actually have a test case with a foreach loop over SimpleXmlElement::children, but it doesn't reproduce the issue...

**Comment by weirdan** [comment]
I think this may have to do with inheritance change in 8.0. In 8.0 `SimpleXMLIterator::current()` is inherited from `SimpleXMLElement`, and in 7.4 it's not.

**Comment by weirdan** [comment]
Yep. Stubbing `SimpleXMLIterator` as `class SimpleXMLIterator extends SimpleXMLElement {}` makes the error consistently appear for both 8.0 and 7.4.

Context: https://externals.io/message/108789 and https://github.com/php/php-src/pull/5234

Still not sure what would be the best way to address this.

**Comment by greg0ire** [comment]
Shouldn't this be changed to `SimpleXMLElement|null`: https://github.com/vimeo/psalm/blob/4c262932602b9bbab5020863d1eb22d49de0dbf4/stubs/DOM.phpstub#L96-L97 (like in the docs at https://www.php.net/manual/en/class.simplexmlelement.php?)
