### ISSUE TITLE
int|float != numeric

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#631]
`The declared return type 'int|float' for testArraySum is incorrect, got 'numeric'`

one would suspect that `@return int|float` should match anything that gets flagged as `numeric` ?

```php
<?php
/**
* @param array<int, int|float> $things
*
* @return int|float
*/
function testArraySum(array $things) {
  return array_sum($things);
}
```

**Comment by weirdan** [comment]
`int|float` is narrower than numeric (it does not include number-like strings, which `numeric` includes). However `array_sum()` is documented in PHP manual as returning *number*, not *numeric*, and *number* is exactly `int|float`.

**Comment by weirdan** [comment]
Psalm doesn't seem to support `number` as a type name, thus `array_sum()` entry should be fixed in `CallMap.php`

**Comment by muglug** [comment]
@SignpostMarv that supplied code seems to work fine on getpsalm.org

**Comment by SignpostMarv** [comment]
works fine now, yes :)
