### ISSUE TITLE
Strange InvalidReturnType/InvalidReturnStatement since 4.9.3

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#6316]
https://psalm.dev/r/30e1b04cd7

**Comment by orklah** [comment]
Adding phpdoc manually solve the issue: https://psalm.dev/r/31dad97d4d

**Comment by WossomGonzo** [comment]
I have a similar code that in Psalm 4.9.3 it runs ok, but in Psalm 4.10 it returns:

`ERROR: InvalidReturnType - index.php:23:30 - The declared return type 'array<array-key, mixed>' for multiply is incorrect, got 'array<array-key, mixed>|object' (see https://psalm.dev/011)
function multiply($numbers): array {`

`ERROR: InvalidReturnStatement - index.php:27:12 - The inferred type 'array<array-key, mixed>|object' does not match the declared return type 'array<array-key, mixed>' for multiply (see https://psalm.dev/128)
    return $numbers;
`



```php
<?php
require 'vendor/autoload.php';

class Num {
    public int $value;

    public function __construct(int $value) {
        $this->value = $value;
    }
}

$numbers = [
    new Num(1),
    new Num(2),
    new Num(3),
    new Num(4),
    new Num(5),
];

$numbers = multiply($numbers);
printThem($numbers);

function multiply($numbers): array {
    array_walk($numbers, function($number) {
        $number->value = $number->value * $number->value;
    });
    return $numbers;
}

function printThem($numbers): void {
    print_r($numbers);
}
```

**Comment by orklah** [comment]
@WossomGonzo your issue is related to #6441 and has been fixed. The original issue here is not yet identified

**Comment by klimick** [comment]
Issue resolved. Can be closed.

**Comment by vudaltsov** [comment]
Thank you, @klimick !
