### ISSUE TITLE
Support for @method-ish annotation syntax

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#632]
This is especially useful when specifying concrete methods in children of doctrine repositories. Following returns TypeCoercion error

```php
<?php

namespace A;

class A {
}

namespace B;

use A\A;

/**
 * @method A find()
 */
class B extends \E\VendorE {
  
}

namespace C;

use B\B;
use D\D;

class C {
  public function bar(): void {
    $a = (new B())->find();
    $d = new D() ;
    $d->baz($a);
  }
}

namespace D;

class D {
  public function baz(\A\A $a): void {
    return;
  }
}

namespace E;

class VendorE {
  public function find(): object {
     return new $_GET['stuff'];
  }
}

```

**Comment by muglug** [comment]
What you're asking for here is not support for [`@method` annotations](https://docs.phpdoc.org/references/phpdoc/tags/method.html) (which are only strictly applicable for classes with a magic `__call` method).

Boiled down, it seems like you want this:

```php
abstract class Entity {}
abstract class EntityFinder {
  /** @return Entity */
  public function getOne() {
    return new self;
  }
}

class MyEntity extends Entity {}
/** @psalm-override-method-return MyEntity getOne */
class MyEntityFinder extends EntityFinder {}
```

**Comment by ostrolucky** [comment]
Ah, I didn't know `@method` annotation is strictly applicable only for classes with __call method, all that time we do use it for this and IDE accepts it as one with higher priority :/

Standardized syntax for narrowing down type of parent methods would be useful though. Can you add it to list of things to talk about in PSR-5? :)

**Comment by muglug** [comment]
I created https://github.com/vimeo/psalm/issues/633 to track `@method` support

**Comment by ostrolucky** [comment]
My impression was that @psalm-override-method-return already exists. Just tried it and it doesn't work. Shall I reopen, or will this be part of #633 ?

**Comment by muglug** [comment]
`@psalm-override-method-return` doesn't exist, but you can create a new ticket to support that syntax. #633 will only support magic method descriptions.
