### ISSUE TITLE
InvalidNullableReturnType: False positive after checking with if is_string

### ISSUE THREAD

**Issue by ThomasLandauer** [vimeo/psalm#6336]
https://psalm.dev/r/826596001d

My function `foo()` will always return a string, but psalm says:

> ERROR: InvalidNullableReturnType - 3:17 - The declared return type 'string' for foo is not nullable, but 'null|string' contains null

**Comment by weirdan** [comment]
There's no guarantee that `bar()` will always return the same value, as far as Psalm is concerned. Use a variable: https://psalm.dev/r/711e251ed7

**Comment by ThomasLandauer** [comment]
OK, I see your point.
But in my case it's within an entity. `bar()` is a getter, and `foo()` a convenience method to return a string for sure. Declaring a variable for each try would bloat the code.
Is there maybe a smarter solution than suppressing these errors for all entities?

**Comment by weirdan** [comment]
If your entity is immutable (doesn't change once created), you can declare it as such, with `@psalm-immutable`. If `bar()` does't change any state, you can mark it with `@psalm-mutation-free`.

https://psalm.dev/r/2a0e883bb3

**Comment by ThomasLandauer** [comment]
Cool, thanks, `@psalm-mutation-free` fixes it. So in fact ***every* getter should be annotated `@psalm-mutation-free`, right?**

**Comment by weirdan** [comment]
Correct. Immutable objects are preferable, but of course there are cases where they can't be used, for one reason or another.
