### ISSUE TITLE
Typehints on specific variables via PHPDoc is not working as expected

### ISSUE THREAD

**Issue by niconoe-** [vimeo/psalm#6341]
Hi there.

Please take a look at: https://psalm.dev/r/1e64e874ef

Expected: no issue.
Actual: errors are found while all variables are specifically typed via the `@var` annotation.

Refering to the documentation:
> You can also use typehints on specific variables e.g.
> 
> ```php
> <?php
> /** @var string $a */
> echo strpos($a, 'hello');
> ```
>
> This tells Psalm to assume that $a is a string (though it will still throw an error if $a is undefined).
(https://psalm.dev/docs/annotating_code/typing_in_psalm/#assignment-typehints)

I don't know how to help here.

Thanks.

**Comment by weirdan** [comment]
Variable types are not preserved on reassignment, unless they are declared in the docblock immediately preceding the statement. So you need to tweak your docblocks a little: https://psalm.dev/r/fae6c129ac

**Comment by niconoe-** [comment]
I think the behavior is confusing as I would expect the types to be kept if there's no reassignment for the specific variable, but I'm ok with your last syntax. Thanks!
