### ISSUE TITLE
MissingClosureParamType on unused closure parameters

### ISSUE THREAD

**Issue by flaviovs** [vimeo/psalm#6348]
Psalm raises a **MissingClosureParamType** on untyped closure parameters, even when they are explicitly flagged as unused (e.g. by prefixing then with an underscore). Since the parameter is flagged to be ignored already, it would be good if we those warnings are suppressed, or at least an option to do so is provided, since type hinting or `@param` annotating unused closure parameters is generally pointless and cumbersome.

See https://psalm.dev/r/23ff409151

**Comment by flaviovs** [comment]
@orklah, I am aware that I can suppress the message. This issue (more a request for enhancements than a bug report itself) is about **not having** to add the suppression since the parameter is being ignored anyway. Perhaps flagging those cases with a specific warning (such as *MissingClosureIgnoredParamType*) would make sense?

**Comment by orklah** [comment]
Somehow it was fixed? Not sure how

**Comment by AndrolGenhald** [comment]
@orklah Is this actually a regression? Seems like it should emit `MissingClosureParamType` [here](https://psalm.dev/r/c914c786fd) shouldn't it?

**Comment by orklah** [comment]
It's possible indeed. I'm not quite inclined to dig too deep on these kind of issues...

**Comment by weirdan** [comment]
https://psalm.dev/r/c914c786fd
