### ISSUE TITLE
How to tell psalm that the return type corresponds to the input type if more than 2/mixed?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#6351]
When param and return type correspond, I can do https://psalm.dev/r/15045580f3

However how do I do this, if I have "mixed" or more than 2 (e.g. float/int/bool) types?

(sanpo)

**Comment by orklah** [comment]
The syntax can be nested:
https://psalm.dev/r/5046d944f3

Also note that if you send a mixed variable in, the output will be an union of all possible cases

**Comment by kkmuffme** [comment]
Thank you
