### ISSUE TITLE
Variable-length argument lists should parse as list<T>

### ISSUE THREAD

**Issue by jsiefer** [vimeo/psalm#6362]
Example: https://psalm.dev/

I would expect that variable length argument `int ...$ints` is of type  `list<int>` not `array<array-key, int>`.

**Comment by weirdan** [comment]
https://3v4l.org/Ck7p8 - it's not a list when named arguments are used. Use `@no-named-arguments` if you don't intend to support that, and Psalm will infer arguments as `list<...>`: https://psalm.dev/r/45b48934ca

**Comment by jsiefer** [comment]
Ahh I did not know about that. Thanks!
