### ISSUE TITLE
ReflectionClass and impurity of methods

### ISSUE THREAD

**Issue by TheCelavi** [vimeo/psalm#6378]
Found a strange issue: https://psalm.dev/r/770fadfec3

I believe that this is a bug, once initiated \ReflectionClass should have immutable state, right? 

Didn't checked for other reflective classes....

**Comment by weirdan** [comment]
Unfortunately `ReflectionClass` is not fully immutable: https://3v4l.org/uu1un

However most of its methods are mutation-free. If you want to propose a PR addressing this it would be more than welcome. You can add docblock tags in `stubs/Reflection.phpstub` and Psalm should pick that up.
