### ISSUE TITLE
Built-in NoRewindIterator stub does not work

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#6387]
https://psalm.dev/r/a7edd80625

**Comment by orklah** [comment]
It seems to work when we push an Iterator instead of a Generator: https://psalm.dev/r/b8a3eaff57

**Comment by orklah** [comment]
The stub declare it accepts an `Iterator` so `Generator` should be accepted: https://3v4l.org/lqr5D

**Comment by weirdan** [comment]
Reproducible with user-defined classes as well: https://psalm.dev/r/36a0f142e0
