### ISSUE TITLE
wierd behaviour with `switch` statement

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#6389]
With the following snippet of code https://psalm.dev/r/88960656f8 psalm produces some unexpected errors `UnusedFunctionCall` and `ParadoxicalCondition`

**Comment by weirdan** [comment]
There are two issues here. One is invalid `ParadoxicalCondition`: https://psalm.dev/r/88960656f8 and another is invalid `UnusedFunctionCall`: https://psalm.dev/r/069efdfa96 . Both require a fall-through case to reproduce though.
