### ISSUE TITLE
Return, break, die do not propagate assertions

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#6393]
https://psalm.dev/r/b61522c880

**Comment by weirdan** [comment]
It looks like assertions produced by `count()` cannot be negated. If you replace `count($var) === 0` with `$var === []` it works as expected.

**Comment by orklah** [comment]
I couldn't find where Psalm does the negation in assertions, but `non-empty-countable` can be negated (at least when the assertion is set: https://github.com/vimeo/psalm/blob/1a7a44a602430ef3176f9f03130f6cef6c907337/src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php#L2992)

The difference between `count($var) === 0` and `$var === []` seems to be that for the former, Psalm is looking for non empty counts to assert `non-empty-countable` whereas for the latter Psalm is looking for empty arrays to assert `!non-empty-countable`. Seems like the second strategy is working the best
