### ISSUE TITLE
ReferenceConstraintViolation seen after calling `array_walk(array|object &rw_array, ...)`

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#6394]
https://psalm.dev/r/5c8bd06393

It seems like array_walk accepts arrays or objects, which leads psalm to infer that the type may be changed to `object` after the function is called?

array_walk_recursive is also affected

```
dictionaries/CallMap.php
423:'array_walk' => ['bool', '&rw_array'=>'array|object', 'callback'=>'callable', 'arg='=>'mixed'],
```

Psalm itself ignores the `rw_` prefix (used by Phan) so I don't think that's related. There aren't any special cases for array_walk at all other than warning about raw object iteration. The lack of special cases is probably the issue, psalm is treating `array_walk` just like any other function accepting references and outputting values in the references.

**Comment by orklah** [comment]
Thanks for the feedback! Indeed, this function could use a stub with a conditional return. @niconoe- are you up for the task?

reproducer without references (I hate those!): https://psalm.dev/r/589e8c7298

**Comment by TysonAndre** [comment]
I also updated this ticket to note that array_walk_recursive is also affected

**Comment by niconoe-** [comment]
From what I know, there's no way that array_walk (or array_walk_recursive) could change the type of argument # 1 from `array` to `object` or `object` to `array`. Therefore, whatever type `&rw_array` is receiving, it must not be detected as a possible change of type. 

```php
function foo(array $val): void {
    array_walk($val, /** @param mixed $arg */ function (&$arg): void {});
    // Expected $val to be array<array-key, mixed>
}

function bar(object $val): void {
    array_walk($val, /** @param mixed $arg */ function (&$arg): void {});
    // Expected $val to be object
}
```

Unfortunately, I don't know how to make Psalm understand this in this way 😞.

To be honest, I don't know how PHPStan did this or if it actually detects the issue as I never got any trouble with referenced parameters with it: probably the check is not as strict as Psalm is.

**Comment by orklah** [comment]
Sorry, when I answered, I thought about conditional returns but they can't be used for parameters.

However, I think you could add two different signatures for those functions. There's an example here:
https://github.com/vimeo/psalm/blob/master/dictionaries/CallMap_73_delta.php#L40

hrtime has two signatures, one where as_number is true and one where it's false. I think declaring two signatures for array_walk and array_walk_recursive  could work (one where rw_array is an array and one where it's an object)

**Comment by niconoe-** [comment]
I'll give it a try with `array_walk'1` and `array_walk_recursive'1` and I if managed to learn how to do it, I'll add some test cases.
I will not be able to work on this until Monday however. I just hope it'll work as expected.

Thanks for the tip!

**Comment by orklah** [comment]
Thanks! Don't worry if it doesn't work, we'll find another solution :)

**Comment by niconoe-** [comment]
Hey @orklah sorry for treating this a little bit late today, that's still a long day at work and I didn't find a minute to make you this proposal until now.

I'm not really confident about this PR, so feel free to edit it with your preferences.

Have a nice day,
Regards,

**Comment by orklah** [comment]
Hey @niconoe- don't worry for the delay, it's fine, if people are bothered, they can always set a fixed version in composer (to be honest, it's even recommended)
