### ISSUE TITLE
[Help wanted] Listing PHP 8.1 features

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#6395]
The first release candidate for PHP 8.1 is out now and the feature freeze is past, We may start looking at the new features and ensuring they're implemented in Psalm. Some were already implemented by Matt but not all.

This thread will regroup every new feature to come and what impact it will have on Psalm.

PHP release notes can be found here: https://github.com/php/php-src/blob/PHP-8.1/UPGRADING.

If you want to help, please respond here with the feature name, a small reproducer of the feature(and the impact it must have on Psalm analysis). For example: 

- [x] **array_is_list** type inference: https://psalm.dev/r/fe157fd547
- [x] **array_is_list** impossible type: https://psalm.dev/r/bb9d8800b1
- [x] **readonly** keyword: https://psalm.dev/r/ec599a194c
- [x] **string key array unpacking** support: https://psalm.dev/r/a25339af39

### Callmap/stub changes

- [x] **array_is_list** function : https://psalm.dev/r/8bef57c13a -> fixed: #6398
- [ ] #6401
- [x] #6402
- [x] #6403
- [x] #6404
- [x] #6405
- [x] #6406
- [x] #6407
- [x] #6408
- [x] #6414
- [x] #6415
- [x] #6416
- [x] #6417
- [x] #6418
- [x] #6422
- [x] #6731

### Parser changes
- [x] #6410
- [x] #6412
- [x] #6413
- [x] #7668

### Enum support
- [x] #6425

I'll update this post with new items as well as progress

**Comment by niconoe-** [comment]
I'm thinking about managing `readonly` in promoted constructors: https://psalm.dev/r/ec599a194c

I'm using [this blog](https://stitcher.io/blog/new-in-php-81) to have a list of new features and deprecated stuff in PHP 8.1. You could probably extract a list from this, as it regroups a lot.

**Comment by orklah** [comment]
@niconoe- thanks, I added your case. Yeah, I know where to find the new features, but creating every repro, thinking of impact on Psalm would take me a long time. It's a good opportunity to make the community participate, even when they lack technical insight of Psalm.

Ideally, I'll then create issues for the simpler cases with an explanation how to do it and encourage people to try and implement the feature

**Comment by simPod** [comment]
Array unpacking with string keys should be supported and new array type inferred

https://psalm.dev/r/a25339af39

**Comment by orklah** [comment]
Thanks @simPod!

**Comment by weirdan** [comment]
> can you tag this with "help wanted" and pin the issue?

Done. I also added milestone that we can assign to issues / PRs.

**Comment by niconoe-** [comment]
With Enum:

* Already used case: https://psalm.dev/r/ceaa9c9892
* Already used value for several cases: https://psalm.dev/r/108275cc1c
* Only `string` and `int` are allowed types as enum values: https://psalm.dev/r/89eb27ab21
* Implement callmap `Enum::from`, `Enum::tryFrom` and `Enum::cases`: https://psalm.dev/r/3a77b77825
* `Enum` are objects: https://psalm.dev/r/d153c9d4f0
* Enum's reflection and automatically defined stuff: https://psalm.dev/r/ec911f5510
* New function `enum_exists`: https://psalm.dev/r/9b5935609d
* Attributes are allowed on Enums and TARGET_CLASS also references Enums (I don't know how to explain this with a snippet)

I think that's already something 😄

**Comment by weirdan** [comment]
> Enum are objects 

Can you elaborate? It seems Psalm already knows that: https://psalm.dev/r/a57335dce7

**Comment by niconoe-** [comment]
> > Enum are objects
> 
> Can you elaborate? It seems Psalm already knows that: https://psalm.dev/r/a57335dce7?php=8.1

Sorry, I didn't know I could test against PHP 8.1 using the GET parameter, I was tesing on PHP 8.0 (or default version).
You can remove this then, as it's already implemented.

**Comment by kkmuffme** [comment]
Those things that are merged already (outlined in OP), are already available when setting `phpVersion="8.1"` now?

**Comment by weirdan** [comment]
@kkmuffme yes. Some may be available in master only though, but most are already a part of some release.

**Comment by GrahamCampbell** [comment]
Match statements seem to be partially supported, only. In a switch statement, if I switch on the type of an object, psalm understands it has that type in the case blocks. For a match statement, it does not.

**Comment by orklah** [comment]
Could you provide a snippet please?

**Comment by orklah** [comment]
Yeah, explaining to Psalm that mapping `$x::class` values with specific literals will make `$x` type change is possibly non-trivial, though it works with conditionals: https://psalm.dev/r/ae73672517

Could you create a new issue for that? It's not really related to PHP 8.1 if switch has the same issue

**Comment by GrahamCampbell** [comment]
Switch has a different issue. It understands the type, but doesn't understand the matching is complete.

**Comment by kkmuffme** [comment]
Pending https://github.com/vimeo/psalm/issues/8374

**Comment by weirdan** [comment]
This is pretty much done.
