### ISSUE TITLE
feature request re: getpsalm.org

### ISSUE THREAD

**Issue by WDD-Marv** [vimeo/psalm#640]
Possibly with or without a github issue template, would it be possible have a button on getpsalm.org in order to easily copy & paste error messages into github issues ? :)

**Comment by muglug** [comment]
Great idea!

**Comment by muglug** [comment]
Yeah, the challenge is juggling the UX so it's not intrusive for people who just want to play. Something more like https://3v4l.org/ would be ideal

**Comment by muglug** [comment]
Also I'll only ever offer `dev-master` there, though it should be updated via a git hook and not manually as it is at the moment.

**Comment by ostrolucky** [comment]
Oh it's based on dev-master? That's good to know. Commit version displayed there would be nice as well

**Comment by muglug** [comment]
Here's a sketch of idea for a better website:

![idea1](https://user-images.githubusercontent.com/2292638/38658743-62629eda-3df4-11e8-8724-50e15f4e160d.png)

**Comment by ostrolucky** [comment]
Big improvement!

**Comment by WDD-Marv** [comment]
I like the minimalist design :)

Any thoughts on having a repo for the front-end code for getpsalm.org ?

**Comment by nickyr** [comment]
In terms of using getpsalm.org for bug reports, I've found that displaying the issue name instead of just the message would be helpful

**Comment by muglug** [comment]
@WDD-Marv Psalm source is here: https://github.com/muglug/getpsalm.org

**Comment by muglug** [comment]
New site shaping up at http://v2.getpsalm.org/

**Comment by muglug** [comment]
getpsalm.org now supports creation of snippets and shows Psalm's output for a given input
