### ISSUE TITLE
Fileinfo resources have been converted to objects

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6402]
>  The fileinfo functions now accept and return, respectively, finfo objects instead of resources.

Guide to editing callmaps: [Editing callmaps](https://psalm.dev/docs/contributing/editing_callmaps/).
Example of conversion: https://github.com/vimeo/psalm/pull/6421

**Comment by tomasnorre** [comment]
I would be happy to try doing this. 

How can I verify that I'm done and have done it correctly?

**Comment by orklah** [comment]
There are tests that checks the integrity of the callmap itself so don't be afraid to break things. 
We usually don't add tests for to check for the callmap changes but you totally can if you want. Just add an entry in FunctionCallTest::providerValidCodeParse. You can look for examples where a specific PHP version is set, so when the version is <8.1, fileinfo functions should return a resource (check at the `assertions` array), but for 8.1, they should return objects.

**Comment by tomasnorre** [comment]
Thanks, will give it a spin.

**Comment by tomasnorre** [comment]
Reading the diff, for the example with FTP Functions that is referred. 

I don't quite get why the `Callmap.php` have a change like this. 
```diff
- 'ftp_alloc' => ['bool', 'ftp'=>'resource', 'size'=>'int', '&w_response='=>'string'],
+ 'ftp_alloc' => ['bool', 'ftp'=>'FTP\Connection', 'size'=>'int', '&w_response='=>'string'],
```
I would have expected this only to be in the `CallMap_81_delta.php`. 


as I read the https://github.com/vimeo/psalm/blob/master/docs/contributing/editing_callmaps.md#delta-file-format changes should be done in the respective delta version of the callmap  e.g. (`CallMap_81_delta.php`)and not in the `CallMap.php` itself. 

Can you explain this to me?

**Comment by orklah** [comment]
CallMap.php contains up to date changes.

Then we take delta files to incrementally *remove* newer signature by their old ones. Then, once every delta file has been applied, we should be left with the exact content of CallMap_historical

So yeah, changes must be made in the two files
