### ISSUE TITLE
IMAP resources have been converted to objects

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6404]
> The IMAP functions now accept and return, respectively, `IMAP\Connection` objects instead of resources

Guide to editing callmaps: [Editing callmaps](https://psalm.dev/docs/contributing/editing_callmaps/).
Example of conversion: https://github.com/vimeo/psalm/pull/6421

**Comment by tomasnorre** [comment]
Could you please assign me to this one too? Then I'll give this a spin too.
