### ISSUE TITLE
`mysqli::connect()` returns true rather then null on success

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6406]
> `mysqli::connect()` will now return true instead of null on success.

Guide to editing callmaps: [Editing callmaps](https://psalm.dev/docs/contributing/editing_callmaps/).

**Comment by himanshu007-creator** [comment]
hi, i would like to work on this issue. Please guide me further.

**Comment by weirdan** [comment]
@himanshu007-creator Sure! I've added a guide on how to edit callmaps to psalm.dev site: https://psalm.dev/docs/contributing/editing_callmaps/ (also linked above).

In this case, it appears we're missing `mysqli::connect()` signature entirely, so you will need to add it into `CallMap_historical` with the old signature, to `CallMap.php` with the new signature and add an entry into `CallMap_81_delta` listing both, in `changed.old` and `changed.new` keys respectively.

**Comment by SMAtaurRahman** [comment]
Since it's been a while, is it okay if I pick this one?

**Comment by weirdan** [comment]
Sure.
