### ISSUE TITLE
PgSQL resources have been converted to objects

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6407]
>  * The PgSQL functions now accept and return, respectively, `\PgSql\Connection` objects instead of `pgsql link` resources. 
>  * The PgSQL functions now accept and return, respectively, `\PgSql\Result` objects instead of `pgsql result` resources.
>  * The PgSQL functions now accept and return, respectively, `\PgSql\Lob` objects instead of `pgsql large object` resources.

Guide to editing callmaps: [Editing callmaps](https://psalm.dev/docs/contributing/editing_callmaps/).
Example of conversion: https://github.com/vimeo/psalm/pull/6421

**Comment by tomasnorre** [comment]
I can look at this some when next week, if no one else jump in before that.
