### ISSUE TITLE
PSpell resources have been converted to objects

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6408]
> * The PSpell functions now accept and return, respectively, `PSpell\Dictionary` objects instead of `pspell` resources.
> * The PSpell functions now accept and return, respectively, `PSpell\Config` objects instead of `pspell config` resources.

Guide to editing callmaps: [Editing callmaps](https://psalm.dev/docs/contributing/editing_callmaps/).
Example of conversion: https://github.com/vimeo/psalm/pull/6421

**Comment by tomasnorre** [comment]
You can assign me to this one too @weirdan @orklah then I'll give it a spin too tonight.

**Comment by tomasnorre** [comment]
I took the liberty to do the PR without being assigned.
