### ISSUE TITLE
Allow class-string type to store type values

### ISSUE THREAD

**Issue by WDD-Marv** [vimeo/psalm#641]
While trying to get a teeny reproduction for another issue (erroneous TooManyArguments on results of an implementation of the `nikic/fast-route` package), I stumbled across this one:

"cannot treat type object as callable" gets triggered by `$bar(1, 2, 3)` despite it being inside an if condition that verifies $foo refers to an implementation of `Foo`, which is invokeable ?

```php
<?php
class Foo
{
  public function __invoke(int $a, int $b, int $c) : string {
    return (string) var_export([$a, $b, $c]);
  }
}

/**
* @return string|null
*/
function Bar() {
  return mt_rand(0, 1) === 1 ? Foo::class : null;
}

$foo = Bar();

if (is_string($foo) && is_a($foo, Foo::class, true)) {
  $bar = new $foo();
  $bar(1, 2, 3);
}
```

**Comment by weirdan** [comment]
I suspect psalm just doesn't (fully) support dynamic class instantiation (`new $foo()`).

**Comment by muglug** [comment]
This is a tricky one. It requires, as a prerequisite, the ability to do

```php
$class = mt_rand(0, 1) === 1 ? Foo::class : Bar::class;
$object = new $class();
```

and have  `$object` typed to `Foo|Bar`.

To do that I'd need to overload `TClassString` with the class or classes that it represents, and then include those values when unioning types.

**Comment by WDD-Marv** [comment]
@muglug fyi, `mt_rand()` was used for illustrative purposes- in practice, this was from fast-route's dispatch method being wrapped in an is_a() check (this router is configured to return the name of a class designed to handle a route, another implementation of fast-route returns an array of middleware)- but this `callable|null`.

tl:dr, would `(string&callable)|null` work as a shortcut in psalm-land ? (it'd still trigger toomanyarguments because it doesn't know how many arguments the object accepts, but at least it'd know it was callable)

**Comment by muglug** [comment]
> would `(string&callable)|null` work as a shortcut in psalm-land?

Nope, because `new [callable]` is meaningless.

I used `mt_rand` above to indicate that Psalm would have to take into account regular rules for applying unions to string representations of classes - there are no easy outs here.
