### ISSUE TITLE
Closures for callables with `myfunc(...)`

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6412]
https://psalm.dev/r/a33ad9cfa6

https://wiki.php.net/rfc/first_class_callable_syntax

`nikic/php-parser` support for 8.1 is tracked here: https://github.com/nikic/PHP-Parser/issues/801

**Comment by trowski** [comment]
Anyone working on this? If not, I can take a stab at it.

**Comment by orklah** [comment]
@trowski not for the moment, please do :)
