### ISSUE TITLE
`mysqli_result::fetch_column()`

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6418]
https://psalm.dev/r/cdc80e4506

https://wiki.php.net/rfc/mysqli_fetch_column

Guide to editing callmaps: [Editing callmaps](https://psalm.dev/docs/contributing/editing_callmaps/).

**Comment by brayniverse** [comment]
@weirdan I can give this a crack if nobody else is yet.

**Comment by weirdan** [comment]
@brayniverse sure! Ping me if you get stuck.

**Comment by weirdan** [comment]
Last night I fixed some test suite failures on 8.1 - there weren't that many, at least on linux. We will look into testing on Windows / PHP 8.1 later (we do have CI jobs running Win / PHP 8 now).

For 8.0 issues, mind posting that as a separate ticket? One appears to be symlink related (who knew Win can do symlinks?) and the other looks like composer internal issue, but this will need to be investigated further.

Callmaps are tested by `tests/Internal/CallMapTest.php` so you can run just that test locally, and CI will take care of the rest.

**Comment by brayniverse** [comment]
I've updated the callmap files and ran the subset of tests you mentioned. Do you need me to add any tests specifically for the new function/method? I'll open a ticket for the errors I encountered tomorrow.

**Comment by weirdan** [comment]
> Do you need me to add any tests specifically for the new function/method

No, with over 16k functions we have in the callmap that would be untenable. The change to callmap is enough.

**Comment by weirdan** [comment]
Fixed in #6447
