### ISSUE TITLE
query re: RedundantCondition & pass-by-ref arguments

### ISSUE THREAD

**Issue by WDD-Marv** [vimeo/psalm#643]
Does `elseif ($maybe instanceof Foo)` come up as a RedundantCondition because of `if (false === ($maybe instanceof Foo))` or `if(is_null($maybe))` ?

```php
<?php
class Foo{}

function Bar() : ? Foo
{
  return mt_rand(0, 1) ? new Foo() : null;
}

function Baz(Foo & $foo=null) : void
{
  if (mt_rand(0, 1)) {
    $foo = new Foo();
  }
}

$maybe = Bar();

if (false === ($maybe instanceof Foo)) {
  Baz($maybe);
  
  if (is_null($maybe)) {
    die('do something');
  } elseif ($maybe instanceof Foo) {
    die('do something else');
  }
}
```

**Comment by muglug** [comment]
argh by-ref variables are really hard to reason about.

**Comment by WDD-Marv** [comment]
fyi: this is more stuff related to a nikic/fast-route implementation, not just random code :P

**Comment by WDD-Marv** [comment]
is not entirely untyped though? it's always either null or Foo ? (or does untyped pointers mean something else here).

**Comment by muglug** [comment]
This isn't really a bug – at least, Psalm tries to ensure that when you put a variable of type X into a pass-by-ref setting, it always has that type afterwards. In the case that you're checking for null *and* checking for the object, Psalm thinks there's nothing else it can be (hence `RedundantCondition`).

**Comment by muglug** [comment]
(I misunderstood at a glance, but putting into getpsalm.org confirms my suspicions)

**Comment by WDD-Marv** [comment]
A version without the pass-by-ref also has a similar issue:

```php
<?php
class Foo{}

function Bar() : ? Foo
{
  return mt_rand(0, 1) ? new Foo() : null;
}

function Baz(Foo $foo=null) : ? Foo
{
  if (is_null($foo) && mt_rand(0, 1)) {
    return new Foo();
  }
  
  return $foo;
}

$maybe = Bar();

if (false === ($maybe instanceof Foo)) {
  
  $maybe = Baz($maybe);
  
  if (is_null($maybe)) {
    die('do something');
  } elseif ($maybe instanceof Foo) {
    die('do something else');
  }
}
```

**Comment by muglug** [comment]
Yeah - do you understand why?

At `elseif ($maybe instanceof Foo)`, `$maybe` can *only* be `Foo`. So the check there is redundant (and it should be an `else` instead)

**Comment by WDD-Marv** [comment]
Best to use the return pattern in future then? :)
