### ISSUE TITLE
Enums: new function `enum_exists`

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6431]
psalm.dev/r/9b5935609d

Guide to editing callmaps: [Editing callmaps](https://psalm.dev/docs/contributing/editing_callmaps/).

**Comment by weirdan** [comment]
psalm.dev/r/9b5935609d

**Comment by brayniverse** [comment]
I should be able to do this one as well if you want @weirdan?

**Comment by weirdan** [comment]
Sure. Although this one will need some more work, as it's similar to `class_exist()` for which Psalm has special treatment here and there:

```console
$ rg "'class_exists'" src
src/Psalm/Internal/Codebase/Functions.php
452:            'class_exists', // impure by virtue of triggering autoloader

src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
1772:            && strtolower($stmt->name->parts[0]) === 'class_exists'

src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
81:        if ($function_id === 'class_exists') {

src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php
327:        if ($function->name->parts === ['class_exists']

src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
169:            if ($method_id === 'class_exists'
```

**Comment by orklah** [comment]
If you're stuck, just ping us, we'll help :)

**Comment by brayniverse** [comment]
Interesting, I'll give it a crack tonight and let you know if I get stuck.

**Comment by brayniverse** [comment]
I had a first attempt last night but got a little lost. I'll try again tonigh and tell you where I'm getting lost if I don't make any progress.

**Comment by brayniverse** [comment]
Hey, sorry I've gone quiet. I haven't had enough time to get into this. Please let anyone else pick this up if they want to do it. Whenever I do have time I'll pick something else up.
