### ISSUE TITLE
array_walk functions change inferred type of array argument

### ISSUE THREAD

**Issue by theodorejb** [vimeo/psalm#6432]
This code worked fine in Psalm 4.9, but now errors in Psalm 4.10:

https://psalm.dev/r/601a9b8349

Most likely this is due to PR #6339. But just because `array_walk` and `array_walk_recursive` also accept an object, doesn't mean they can change the type of an array argument. So Psalm should not change the inferred type of a passed array variable to `array|object`.

**Comment by orklah** [comment]
Thanks for the feedback. This was already reported here: #6394 so I'll close this one
