### ISSUE TITLE
possibly erroneous error when using class names as string literals, rather than magic const

### ISSUE THREAD

**Issue by WDD-Marv** [vimeo/psalm#645]
`Bar2` gets the error `$this->baz with declared type 'string' cannot be assigned type 'Foo'`, I'm guessing the magic const string gets special treatment?

```php
<?php
interface Foo {}

class Bar1
{
  /**
  * @var string
  */
  protected $baz;
  
  public function __construct(string $maybeBaz)
  {
    if (!is_a($maybeBaz, Foo::class, true)) {
      throw new Exception('not Foo');
    }
    $this->baz = $maybeBaz;
  }
}
class Bar2
{
  /**
  * @var string
  */
  protected $baz;
  
  public function __construct(string $maybeBaz)
  {
    if (!is_a($maybeBaz, 'Foo', true)) {
      throw new Exception('not Foo');
    }
    $this->baz = $maybeBaz;
  }
}
```

**Comment by muglug** [comment]
> I'm guessing the magic const string gets special treatment?

Yeah, and it should be extended to any string

**Comment by WDD-Marv** [comment]
just wondering, should this be psalter-fixable? i.e. use magic const when possible ?

**Comment by muglug** [comment]
> should this be psalter-fixable? i.e. use magic const when possible ?

Yeah, totally. Create a ticket! Or even better, a PR...
