### ISSUE TITLE
Provide a way of enforcing specification of a type|subtype in callable arguments

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#6450]
See https://psalm.dev/r/05249b72a7.
What I'd love is a way to specify that the passed callable **must** take an ArrayObject or a subtype, never a supertype.
I'll give a try at implementing this later probably, leaving this here just in case :)

**Comment by weirdan** [comment]
> subtype, never a supertype.

That goes against LSP. Imagine you expect a callable accepting an `Exception`, and you're getting a callable that only accepts `InvalidArgumentException`. Passing, say, `BadFunctionCallException` to that callable will result in runtime errors.

Getting a callable that accepts `Throwable` is fine though.
