### ISSUE TITLE
Incorrect RedundantConditionGivenDocblockType / DocblockTypeContradiction

### ISSUE THREAD

**Issue by tvdijen** [vimeo/psalm#6452]
See https://psalm.dev/r/628ac07bfc

I don't see how this is legitimate.. `preg_filter()` returns either a `string` or `null` (if fed with a string)..

**Comment by orklah** [comment]
indeed: https://3v4l.org/Bi8oa

The change to be made is there: https://github.com/vimeo/psalm/blob/master/stubs/CoreGenericFunctions.phpstub#L892

**Comment by tvdijen** [comment]
@orklah Is it as easy as changing `string` to `string|null`? I can file a PR

**Comment by weirdan** [comment]
@tvdijen it is, but you will likely need to change it in two places. See this guide for details: https://psalm.dev/docs/contributing/editing_callmaps/

**Comment by tvdijen** [comment]
@weirdan Unless I misunderstand, this is the only place that needs fixing

**Comment by orklah** [comment]
The callmap is indeed already correct. Only the stub was overriding that and removed the null
