### ISSUE TITLE
Use Psalm with dependencies from other plugins 

### ISSUE THREAD

**Issue by Lukid** [vimeo/psalm#6455]
Hi, I'm trying to run psalm on my custom wp plugin, but I need to include other plugins (like Advanced Custom Field Pro) as dependencies, otherwise psalm can't find the functions used.
It's possible ? How ?

I already use humanmade/psalm-plugin-wordpress for the core wp APIs.

**Comment by Lukid** [comment]
> Hey @Lukid, can you reproduce the issue on https://psalm.dev ?

https://psalm.dev/r/e96486bf90

**Comment by orklah** [comment]
So when you run Psalm without external dependancies, your function are not found by Psalm, but with dependancies they are?

Can you share your config file? Did you setup a custom autoloader?

**Comment by Lukid** [comment]
Wordpress loads all activated plugins, ACF (advanced custom field) is one of the first that loads.
For this in my code (custom plugin) I don't need to put any require and I can use the functions of ACF.
Psalm instead loads, with the necessary plugin (PsalmWordpress), all the functions of the WP core, but not those of the activated plugins.

No, I have not put any autoloaders.

Here my psalm config: 

`<?xml version="1.0"?>
<psalm
    errorLevel="3"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    findUnusedCode="1"
>
    <projectFiles>
        <file name="index.php"/>
        <file name="uninstall.php"/>
        <file name="n7-iperionhs.php"/>
        <directory name="includes"/>
        <directory name="admin"/>
        <directory name="public"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
<plugins><pluginClass class="PsalmWordPress\Plugin"/></plugins></psalm>`

**Comment by orklah** [comment]
Do you use composer to install both wordpress and ACF?

**Comment by Lukid** [comment]
> Do you use composer to install both wordpress and ACF?

No

**Comment by orklah** [comment]
What are the steps you make to install ACF? I'm trying to understand what ACF would change anything but I don't know wordpress at all so you're gonna need to be more explicit

**Comment by Lukid** [comment]
ACF prois a paid plugin (there is also a free version). In this case I bought it, downloaded it, put it in the plugin directory (wp-content / plugins) and activated it from the backend. Alternatively, I often use wp-cli, to download and install free plugins.

If ACF (or any other plugin) is active on the site you do not need to include its files as they are all being included in the wordpress initialization process. The only tricky part is that you don't know the order in which files are included and yours might be included before the ACF files are included, therefor I wait for the init action or even later action before using ACF functions.

Maybe I have to overwrite the Psalm default autoloader and put in the ACF plugin path ?

**Comment by orklah** [comment]
Does this also happen with free plugins? If so, could you create a small github repo to replicate the behaviour with and without plugin?

**Comment by mckravchyk** [comment]
@orklah I have the same issue. I tried to use `extraFiles` to load the plugin. 

I think a potential problem here may be that Psalm needs to require files in order for their definitions to be defined? If so, this does not play well with WordPress development, as other plugins are loaded by WordPress, outside of the source code that is being developed.

I'm attaching a very simple test case. https://storage.googleapis.com/github_3uywydaqrm/psalm-wp-plugin.zip

**Comment by orklah** [comment]
I don't see the issue with your example.

Psalm run without problem and does not emit issues

**Comment by paulshryock** [comment]
Hi @Lukid, in case you still have this issue, you can install [acf-prof-stubs](https://packagist.org/packages/php-stubs/acf-pro-stubs) to provide Psalm with stub files for all the ACF Pro functions.

> Stub files provide a way to override third-party type information when you cannot add Psalm's extended docblocks to the upstream source files directly.
> - https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/#stub-files

```bash
composer require --dev php-stubs/acf-pro-stubs
```

In `psalm.xml`:
```xml
<psalm>
    <stubs>
        <file name="vendor/php-stubs/acf-pro-stubs/acf-pro-stubs.php" />
    </stubs>
</psalm>
```
