### ISSUE TITLE
Incorrect type for reserved $http_response_header variable: array<array-key, mixed> instead of list<string>

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#6456]
https://psalm.dev/r/ca2f17ab48

According to the PHP documentation, $http_response_header is a list of strings.
https://www.php.net/manual/en/reserved.variables.httpresponseheader.php

**Comment by weirdan** [comment]
Inferred in `Psalm\Internal\Analyzer\Statements\Expression\Fetch\VariableFetchAnalyzer::getGlobalType()`
