### ISSUE TITLE
possibly erroneous RedundantConditionGivenDockblockType when used with empty

### ISSUE THREAD

**Issue by WDD-Marv** [vimeo/psalm#646]
`scalar|null` can include falsey values, so I'm not sure what it's a contradiction when fed to `empty()`.

```php
<?php
/**
* @param scalar|null $value
*/
function Foo($value=null) : bool {
  if (empty($value)) {
    return true;
  }
  return false;
}
```

additionally, when I was trying to make the most minimal reproduction on getpsalm.org, this version gave 2 different errors:
* Could not verify return type
* Could not infer a return type

Guessing it's function map related perhaps?
```php
<?php
/**
* @param scalar|null $value
*/
function Foo($value=null) : bool {
  return empty($value);
}
```

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/0b268eb602be9459393712b68feb4b354c38bf63

**Comment by muglug** [comment]
Was just related to the rules for reconciling `falsy` or `empty` - there were already carve-outs for numeric types and `string`, but not `scalar`.
