### ISSUE TITLE
InvalidPropertyAssignmentValue with template type

### ISSUE THREAD

**Issue by matiux** [vimeo/psalm#6461]
https://psalm.dev/r/a69dc1f7b2

Template T doesn't behave as I expect.
By declaring the type directly on the variable instead then it works

What am I doing wrong?

**Comment by orklah** [comment]
Seems like a bug to me:
https://psalm.dev/r/6a94c2f9a8

**Comment by weirdan** [comment]
> Seems like a bug to me

Why? Suppose `T` is a `non-empty-array` - `$telefono = []` should still be valid in this case, and it obviously isn't.

**Comment by weirdan** [comment]
> Template `T` doesn't behave as I expect.

Do you even need a template there? Could this be better served by [`@psalm-type`](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-type)?

**Comment by orklah** [comment]
> 
> 
> > Seems like a bug to me
> 
> Why? Suppose `T` is a `non-empty-array` - `$telefono = []` should still be valid in this case, and it obviously isn't.

Well, if we wanna go there, Psalm should combine the type from the property default with the type received in the constructor to build a correct template. The default type can never be bad.

If you don't consider the property's default type as part of the template type, then you should not consider the param's default type either: https://psalm.dev/r/5c7a9267d2

**Comment by weirdan** [comment]
Param (including default) type is an input for type param inference in my book, and property type is an output.

```php
new Foo(["a" => 1]);
```
won't cause the type to be inferred as `Foo<array{a?:1}>` (note the optional key), but using empty array from the property type necessarily would.

**Comment by orklah** [comment]
mmh, not sure what we should do then

**Comment by matiux** [comment]
The problem of the discussion is not entirely clear to me. However in this specific case, `@psalm-type` is the one for me, much more correct than a template

**Comment by orklah** [comment]
Great then :)
