### ISSUE TITLE
false `PossiblyUndefinedStringArrayOffset` for shape.

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#6463]
example: https://psalm.dev/r/d3ce80c00a

In this scenario, `T` ( and therefor `$datum` ) is known to contain `array{foo: string}`

**Comment by azjezz** [comment]
first reported at: https://github.com/azjezz/psl/discussions/226

**Comment by weirdan** [comment]
> It's probably possible to constrain the closure signature if it's defined inside a function call and *[edit: this is important]* there's no references to it in the enclosing scope, but it's not something that we have at the moment, not for calls to user-defined functions anyway.

**Comment by orklah** [comment]
This was fixed
