### ISSUE TITLE
Why no check error when trait not use?

### ISSUE THREAD

**Issue by aleksandr-yulin** [vimeo/psalm#6466]
Example 
- no error https://psalm.dev/r/6aa59af048
- has error https://psalm.dev/r/a02e830d19

**Comment by weirdan** [comment]
Traits can only be meaningfully analyzed in the context of classes where they are used. E.g. `$this->something()` in a trait method (where trait does not have `something()`) really depends on whether the consuming class has method called `something()`, its signature, etc. Without that information analysis is at best incomplete and at worst it produces a lot of false positives.
