### ISSUE TITLE
Enum: readonly "value" attribute not recognized as defined on Backed Enums

### ISSUE THREAD

**Issue by alexanderpas** [vimeo/psalm#6468]
Psalm doesn't seem to be aware that Backed Enums have a readonly `value` property which contains the scalar backing value of the Backed Enum case.

For example, when doing `$this->value` inside a method within a Backed Enum, it classified the instance property as not defined.

    <?php
    
    enum Status: string
    {
        case DRAFT = 'draft';
        case PUBLISHED = 'published';
        case ARCHIVED = 'archived';
        
        public function get(): string
        {
            return $this->value;
        }
    }
    
    echo Status::DRAFT->get();

Psalm Output for PHP 8.1.0RC1:

    Psalm output (using commit f496cca): 
    ERROR: UndefinedThisPropertyFetch - 11:16 - Instance property Status::$value is not defined
    INFO: MixedReturnStatement - 11:16 - Could not infer a return type
    INFO: MixedInferredReturnType - 9:28 - Could not verify return type 'string' for Status::get

(correct) PHP Output:

    draft

- https://psalm.dev/r/93b7037dcb?php=8.1
- https://3v4l.org/98bPT/rfc#vgit.master
- https://wiki.php.net/rfc/enumerations

**Comment by weirdan** [comment]
https://psalm.dev/r/93b7037dcb?php=8.1

**Comment by weirdan** [comment]
Works when accessed from the outside: https://psalm.dev/r/272b6dceea
