### ISSUE TITLE
Abstract class declaring @property should not have to declare __get

### ISSUE THREAD

**Issue by alex-dev** [vimeo/psalm#6483]
https://psalm.dev/r/40db33b9ea

A child could define the property or use magic method. The parent should not try to force it.

**Comment by orklah** [comment]
The goal of a tool like Psalm is to prevent you from making errors. This is a potential error.

If your childs use magic methods, that's fine, add the abstract signature in your class and the error is solved. If the property is defined in your child, you should not document it in the parent class neither.

However, if you really don't want Psalm to check this error, you can use this config: https://psalm.dev/docs/running_psalm/configuration/#usephpdocpropertieswithoutmagiccall
