### ISSUE TITLE
xdebug_get_profiler_filename return type

### ISSUE THREAD

**Issue by ssnepenthe** [vimeo/psalm#6484]
Wasn't sure if this is the sort of thing that should be overridden in the xdebug stub or if it can be pulled from elsewhere...

It looks like psalm assumes a return type of string for xdebug_get_profiler_filename(), but it should be string|false (https://xdebug.org/docs/profiler#xdebug_get_profiler_filename).

https://psalm.dev/r/5ef2b9cf17

**Comment by orklah** [comment]
You're right. This can be easily fixed here: https://github.com/vimeo/psalm/tree/master/dictionaries

see this documentation for guidance: https://psalm.dev/docs/contributing/editing_callmaps/#intro

**Comment by ssnepenthe** [comment]
Thanks for pointing me in the right direction!
