### ISSUE TITLE
Ds\Sequence<int, mixed> has too many template params, expecting 1

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#6490]
https://psalm.dev/r/bee32f879c

Working with DS Sequence gives 

> Ds\Sequence<int, mixed> has too many template params, expecting 1

I looked into a stub if I see a way how to fix but no idea why this is happening. The definition looks correct.

**Comment by orklah** [comment]
DS\Sequence seem to only have one template:
https://github.com/vimeo/psalm/blob/93e9054f98b040bf246c2023201503db3dbf162c/stubs/ext-ds.phpstub#L595

The int part is actually not a template you have to fill.

**Comment by simPod** [comment]
Yup but I did not fill any and it complains about it having too many of them.

Even Sequence<mixed> reports it.

**Comment by orklah** [comment]
Oh right, the issue is there then: https://github.com/vimeo/psalm/blob/93e9054f98b040bf246c2023201503db3dbf162c/stubs/ext-ds.phpstub#L602

There should be only `Sequence<TValue>` here

**Comment by simPod** [comment]
oh right
