### ISSUE TITLE
`mb_str_split()`: non-empty-list<string> actually can be empty

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#6492]
https://psalm.dev/r/f24bf29c4c

**Expected**: `list<string>`
**Got**: `non-empty-list<string>` (but it's actually empty!)

**Comment by fluffycondor** [comment]
I found that `list` was changed to `non-empty-list` a month ago.
https://github.com/vimeo/psalm/pull/6324
But the whole discussion is based on a false premise that  str_split('', 42) is [0 => '']. It's an empty array, at least on 8.0.0.
http://sandbox.onlinephpfunctions.com/code/82ba443b987841df81e318800e8db2c3fc153695

**Comment by VincentLanglet** [comment]
The `str_split` part is still valid. so the PR should be reverted on the mb_str_split part only. Feel free to do it.
