### ISSUE TITLE
How mark abstract class as internal, but public methods should be not internal?

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#6496]
Example: https://psalm.dev/r/8393019f86

I want deny users of package inherit from abstract class, but methods should be not internal. How make it?

**Comment by weirdan** [comment]
You can do something like this: https://psalm.dev/r/2fb67afdaa, though it hardly an elegant way to approach this.

I would rather apply dependency inversion here and provide a factory returning a private implementation of a public interface: https://psalm.dev/r/d88f1492bb

**Comment by vjik** [comment]
thank you!
