### ISSUE TITLE
UnsafeInstantiation on private constructor

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#6510]
With [this snippet](https://psalm.dev/r/0cfc9a1784)

```php
class Foo
{
    private function __construct()
    {
    }
    
    public static function build(): self
    {
    	return new static();
    }
}
```

I get a

```
ERROR: UnsafeInstantiation - 11:13 - Cannot safely instantiate class Foo with "new static" as its constructor might change in child classes
```

error. But actually the constructor can not change in child classes because it is private

**Comment by danog** [comment]
Actually, child classes __can__ override a private constructor, they just can't call it.
You should follow the error's instructions and make the class final, if no classes are supposed to extend it.

**Comment by marcosh** [comment]
You're right, my fault. The idea was to force child classes to use only constructors form the parent class. In my code I already changed it with a trait instead of an abstract class
