### ISSUE TITLE
False positif of UndefinedInterfaceMethod

### ISSUE THREAD

**Issue by Kwadz** [vimeo/psalm#6515]
Even though this issue seems to have already been fixed in https://github.com/vimeo/psalm/issues/1515 and https://github.com/vimeo/psalm/issues/1764, it is still happening, see [this example](https://psalm.dev/r/bcefaa2b9c).

**Comment by Kwadz** [comment]
You're right, my example is not meaningful enough. I completed it here: https://psalm.dev/r/a8f7705731. 

The problem is that Psalm should not trigger the issue _UndefinedInterfaceMethod_ since a class that implements `Environment`, here `InitializedContextEnvironment`, contains `getContext()`.

Here the method `gatherContexts()` is the way with Behat to [access a context from another one](https://behat.org/en/latest/cookbooks/accessing_contexts_from_each_other.html#accessing-contexts-from-each-other). The rest is the source code of Behat itself (of course simplified).

**Comment by orklah** [comment]
Seems useful to avoid this: https://3v4l.org/dR4fX

https://psalm.dev/r/d5e0da65ae

**Comment by Kwadz** [comment]
Indeed, it seems to be more of a problem of design from Behat. Let me open an issue there.
