### ISSUE TITLE
InvalidTemplateParam when implementing ArrayAccess with @template-covariant

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#6520]
https://psalm.dev/r/a8b8d39ee4

**Comment by whsv26** [comment]
```ArrayAccess``` methods accept ```$offset``` and ```$value``` as parameters. 
 
 Covariant templates can't be used as method parameter types outside of ```@psalm-immutable``` context. Covariant parameter can be used as indicator of possible mutation.

There is contradiction between mutating nature of ```ArrayAccess``` and covariant template restrictions.

**Comment by vudaltsov** [comment]
@whsv26 , thanx! Your answer and rereading https://psalm.dev/docs/annotating_code/templated_annotations/#but-what-about-immutability helped!
