### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by stanstst** [vimeo/psalm#6523]
Hi

After running **psalm version 4.10.0** on a single file or small or empty directory - `# ./vendor/bin/psalm --debug  app`

It exited with `PHP Fatal error:  Out of memory`
I have checked via another php script that  php can use up to 5G memory.

This is shorten summery of the output :

Registering autoloaded files
/var/www/html/vendor/autoload.php
   /var/www/html/vendor/composer/autoload_real.php
   /var/www/html/vendor/composer/platform_check.php
........................
Using reflection to get metadata for OutOfBoundsException
Using composer to locate file for Composer\Semver\VersionParser
Using reflection to locate file for Swift_DependencyContainer
Using reflection to locate file for Swift_Preferences
Parsing /var/www/html/vendor/phpunit/phpunit/src/Framework/Assert.php
Scanning /var/www/html/vendor/phpunit/phpunit/src/Framework/Assert.php

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 88813568) (tried to allocate 20480 bytes) in /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageCacheProvider.php on line 81
Fatal error: Out of memory (allocated 88813568) (tried to allocate 20480 bytes) in /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageCacheProvider.php on line 81

**Comment by stanstst** [comment]
> Hey @stanstst, can you reproduce the issue on https://psalm.dev ?

no

**Comment by orklah** [comment]
The error is your system that says your machine can't provide more memory to PHP. Are you sure your system has enough available memory?

Also, can you try running with --thread=1

**Comment by stanstst** [comment]
@orklah may be you are right. 
This is how I tested my machine memory limit:

root@8c1ac0a2ebc3:/var/www/html# php -i | grep memory_limit000*5)));"
memory_limit => -1 => -1
root@8c1ac0a2ebc3:/var/www/html#
root@8c1ac0a2ebc3:/var/www/html#
root@8c1ac0a2ebc3:/var/www/html#
root@8c1ac0a2ebc3:/var/www/html#
root@8c1ac0a2ebc3:/var/www/html#
root@8c1ac0a2ebc3:/var/www/html# php -r "echo strlen((str_repeat('-',1000*1000*1000*5)));"
5000000000root@8c1ac0a2ebc3:/var/www/html#

I've repeated 1 char 5000000000 times, ~= 5G memory-usage.
If I do it say for 9G the entire container crashes/stops, but I do not get any "Out of memory output", as my docker is allowed up to 6G.

But when running Psalm the error output comes out and it's trying to allocate far less memory (megabytes).

--thread=1 does not help either

**Comment by orklah** [comment]
would you happen to have usage of ini_set('memory_limit', ...) somwhere in your code that could be executed by Psalm?

**Comment by stanstst** [comment]
> would you happen to have usage of ini_set('memory_limit', ...) somwhere in your code that could be executed by Psalm?

definitely not, I forgot to mention that I am running psalm on docker 20.10.8, php 7.4 and Mac with Chip M1

**Comment by orklah** [comment]
I don't have a lot of ideas there... Is the memory limit in the error consistent or does it change wildly between runs?

**Comment by stanstst** [comment]
> I don't have a lot of ideas there... Is the memory limit in the error consistent or does it change wildly between runs?

It is consistent on every single run with the exact numbers.
I when I debuged it crashes after few iterations in:
https://github.com/vimeo/psalm/blob/9d9dba156cbd90c60ad354a94a250897efa52825/src/Psalm/Internal/Codebase/Scanner.php#L293

You are right though it might be an environment issue with my docker and Mac with M1 chip.
Thank you for your support

**Comment by orklah** [comment]
I'll close this as it doesn't seem to be a bug in Psalm but rather in your environment. 

I found a few cases with a similar issue than yours:
https://github.com/docker/for-mac/issues/5204
https://github.com/davidalger/warden/issues/341
