### ISSUE TITLE
Narrowing `mixed` with negative assertions

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#653]
In totallyTyped mode:
```php
<?php
function takesObject(object $p) : void {}

/**
 * @return mixed
 */
function returnsMixed() { return rand(0,1) ? "1" : 1; }

/**
 * @var mixed $q
 */
$q = returnsMixed();

if (!is_scalar($q) && !is_array($q) && !is_resource($q) && !is_null($q)) {
  // mixed & !scalar & !array & !resource & !null => object
  takesObject($q);
}
```
Here, the first error reported is probably the same as #652 , but the second one is a bit unexpected, unless I misunderstand the structure of php type hierarchy.
```
ERROR: MixedAssignment - q.php:12:1 - Cannot assign $q to a mixed type
/**
 * @var mixed $q
 */
$q = returnsMixed();

ERROR: MixedArgument - q.php:16:15 - Argument 1 of takesObject cannot be mixed, expecting object
  takesObject($q);
```

**Comment by muglug** [comment]
This is not a bug – at least, it's outside the parameters of how I want Psalm to work.

To Psalm, `mixed` doesn't mean `scalar|array|resource|null|object` - it means "I give up".

Therefore a `mixed` variable filtered by an `!is_scalar` doesn't evaluate to `array|resource|null|object` - rather, it still evaluates to `mixed`.

This allows Psalm, when not in `totallyTyped` mode, to ignore sub-par code like

```php
<?php
function a($b) : void {
  if (!is_scalar($b)) {
    echo $b["c"];
  }
}
```

If it `$b` were typed to `array|resource|null|object` there'd be a `PossiblyInvalidArrayAccess` issue emitted (unnecessarily, in my opinion).
