### ISSUE TITLE
False PropertyNotSetInConstructor error

### ISSUE THREAD

**Issue by pawelkg** [vimeo/psalm#6540]
Hi,

I have trait that set up all my configuration values passed to constructor. When unincialized property is set in method called by triat's method called in contructor there is error 'PropertyNotSetInConstructor'

Example: https://psalm.dev/r/4ae71a480a

Expected result in this case is no error.

**Comment by orklah** [comment]
I'll close this because we already have multiple variations of the same issue already: https://github.com/vimeo/psalm/issues?q=is%3Aissue+is%3Aopen+trait+PropertyNotSetInConstructor
