### ISSUE TITLE
Invalid 'PossiblyNullArgument' error

### ISSUE THREAD

**Issue by pawelkg** [vimeo/psalm#6541]
In this example code https://psalm.dev/r/aeaa24335d PossiblyNullArgument error should not be emmit, because at this point method do not return null.

**Comment by whsv26** [comment]
Consider this example. Second call will indeed return null. You need to assert a variable and not the method call.

[](https://psalm.dev/r/dc7d80ff16)

**Comment by pawelkg** [comment]
Agree. I'm closing issue.

**Comment by orklah** [comment]
Note that immutable and pure flag will allow you to do that (since Psalm will know the method returns the same result each time)
