### ISSUE TITLE
try...finally in one function affecting a completely separate function

### ISSUE THREAD

**Issue by akrabat** [vimeo/psalm#6543]
On it's own, Psalm passes this function with no issues:

```php
<?php
function two(): mixed
{
    $r = exec('ls', $lines);
    if ($r !== false) {
        return $lines;
    }
    return false;
}
```
(as seen in https://psalm.dev/r/ae1083cb24)

However, if I add another function before it that calls exec() within a try..finally, then it fails:

```php
<?php
function one(string $originalPdf): ?string
{
    try {
        exec('pdfgrep "FOO" -n ' . $originalPdf, $output, $retval);
        if ($retval === 0 && isset($output[0])) {
            return (string)$output[0];
        }
    } finally {
        unlink($originalPdf);
    }

    return null;
}

function two(): mixed
{
    $r = exec('ls', $lines);
    if ($r !== false) {
        return $lines;
    }
    return false;
}
```
(as seen in https://psalm.dev/r/ec585fea79)

Error is:

> INFO: PossiblyUndefinedVariable - 20:16 - Possibly undefined variable $lines defined in try block
 
Note that the issue relates to function `two()` but  the `try` block is in function `one()`.

If I comment out the try block in `one()` - i.e. lines 4 (`try {`), 9 (`} finally {`) and 11 (`}`), then it works as per https://psalm.dev/r/7144ceac33.

From what I can tell the `exec()` call within the try call must use `exec()`'s $output parameter for this issue to occur.

In my actual project the real two functions are in separate methods in separate classes in separate files. 

What am I doing wrong? I didn't expect that wrapping `exec()` in a try...finally in one function to affect a completely different function that also uses `exec()`.

**Comment by orklah** [comment]
This seems like a deep bug in Psalm.

minimal reproducer: https://psalm.dev/r/7f28a78d3a
