### ISSUE TITLE
WeakReference should not be immutable

### ISSUE THREAD

**Issue by alex-dev** [vimeo/psalm#6544]
A `WeakReference` does mutate in unpredictable ways. Flagging it as immutable allows us to assume a previous `WeakReference::get()` ensured the reference was still alive. This assumption is wrong.
https://psalm.dev/r/6839ad5622

**Comment by orklah** [comment]
@weirdan I see you added this stub and marked it immutable. Does this seem legit?

**Comment by weirdan** [comment]
My idea was that `WeekReference` *itself* is immutable. But I clearly failed to account for `get()` being volatile.

**Comment by orklah** [comment]
@alex-dev it should be a simple change. Care to remove the annotation from the stubs?

**Comment by weirdan** [comment]
And the parameter of the `WeakReference::create()` should be called `$object` rather than `$referent` to allow calls with named parameters.

**Comment by alex-dev** [comment]
Got no problem doing it.
