### ISSUE TITLE
Invalid count guessing with optional array indexes

### ISSUE THREAD

**Issue by pkly** [vimeo/psalm#6548]
It's possible to declare an array shape with an optional index, in that case the count should assume that the count of items in the array may be either mix or max of array shape, yet it only assumes that the maximum is possible.

https://psalm.dev/r/cbf9b63ac4

**Comment by orklah** [comment]
This should be fixed by #6423 once it's merged

**Comment by orklah** [comment]
Just checked, there's no more error with the PR.

**Comment by pkly** [comment]
Lovely, can't wait till it's merged then.
