### ISSUE TITLE
Incorrect __DIR__ handling under Windows

### ISSUE THREAD

**Issue by srsbiz** [vimeo/psalm#655]
Test script: `src/index.php`

```php
<?php
declare(strict_types=1);

require_once __DIR__ . '/../vendor/autoload.php';
```

Result:

```
ERROR: MissingFile - src\index.php:4:1 - Cannot find file F:\playground\psalm-test\F:\playground\psalm-test\src/../vendor/autoload.php to include
require_once __DIR__ . '/../vendor/autoload.php';
```

It seems that actual `__DIR__` value is prefixed with current working directory path. Problem occurs both while running in natvie cmd as well as under cygwin (bash provided by https://gitforwindows.org/ )

**Comment by WDD-Marv** [comment]
out of curiosity, what happens if you require_once dirname(__DIR__) . '/vendor/autoload.php'; ?

**Comment by srsbiz** [comment]
Even worse -  current working dir is pre-appended two times.

**Comment by muglug** [comment]
@srsbiz thanks for opening this issue - do you still see the problem with latest dev-master? I just pushed f9b6027 which should convert slashes to native directory separators.

**Comment by srsbiz** [comment]
No change, I think this issue is caused by this line:
https://github.com/vimeo/psalm/blob/f9b6027bbc811ed58a406860f96c01e4b78eee53/src/Psalm/Checker/Statements/Expression/IncludeChecker.php#L44

since on windows paths starts with drive letter and not directory separator

**Comment by muglug** [comment]
Thanks, makes sense – I'll hopefully have a fix tonight (I have a little-used Windows PC for such things).

**Comment by terremoth** [comment]
<img width="1168" height="136" alt="Image" src="https://github.com/user-attachments/assets/0b3de99b-2529-47c7-bc88-f1880f5dfff9" />

PSalm is pointing `__DIR__` to `C:\Users\<user>\AppData\Local\Temp\Psalmtemp_folder3348`

What is happening here? Why it is behaving like this?

Edit: nevermind, for some reason the warning disappeared 🤷‍♂️
