### ISSUE TITLE
Arrays checked with `count` should be considered as non-empty-list

### ISSUE THREAD

**Issue by Braxilior** [vimeo/psalm#6551]
Hey,
I encountered some errors of this kind: 
`Argument 1 of max expects non-empty-array<array-key, mixed>, parent type array<array-key, int>`

The thing is that all my calls to the `max` function were not concerned by these errors. The difference was the way I was checking the emptiness of my array. 

https://psalm.dev/r/fa6da48c3f

**Comment by orklah** [comment]
I'm pretty sure this is fixed in #6423. I'll check tonight

**Comment by orklah** [comment]
Just checked, no more errors with that PR.
