### ISSUE TITLE
"Undefined offset: 1" in PLS Psalm/Codebase.php::1473 

### ISSUE THREAD

**Issue by NikolayZhebet** [vimeo/psalm#6559]
Psalm Language Server returns output(IDE VS code) with next error(cli command doesn't show any stderr):
```Undefined offset: 1 in /home/home/Projects/psalm/src/Psalm/Codebase.php:1473```
in file https://github.com/vimeo/psalm/blob/master/src/Psalm/Codebase.php#L1473

- Tested on master.
- How to reproduce: https://psalm.dev/r/114d1d4b31

Seems like minor issue because IDE(Vs code in my case) still shows popup hint with message
```
Too many arguments for funcWithOneArg - expecting 1 but saw 2Psalmhttps://psalm.dev/026
@var int $argTwo
```
**How to fix:**
Line https://github.com/vimeo/psalm/blob/master/src/Psalm/Codebase.php#L1469

*Instead of* 
```
if (!$function_storage || !$function_storage->params) {
            return null;
 }
 ```
 *Use next approach(add isset check):*
 ```
if (!$function_storage || !$function_storage->params || !isset($function_storage->params[$argument_num])) {
            return null;
 }
 ```
 
Full error message:
`Error - 7:21:34 PM] Request textDocument/completion failed.
  Message: RuntimeException: PHP Error: Undefined offset: 1 in /home/home/Projects/psalm/src/Psalm/Codebase.php:1473 in /home/home/Projects/psalm/src/Psalm/Internal/ErrorHandler.php:66
Stack trace:
#0 /home/home/Projects/psalm/src/Psalm/Codebase.php(1473): Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}()
#1 /home/home/Projects/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php(274): Psalm\Codebase->getTypeContextAtPosition()
#2 /home/home/Projects/psalm/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(168): Psalm\Internal\LanguageServer\Server\TextDocument->completion()
#3 /home/home/Projects/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(140): AdvancedJsonRpc\Dispatcher->dispatch()
#4 [internal function]: Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#5 /home/home/Projects/psalm/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#6 /home/home/Projects/psalm/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#7 /home/home/Projects/psalm/vendor/amphp/amp/lib/functions.php(61): Amp\call()
#8 /home/home/Projects/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(78): Amp\{closure}()
#9 /home/home/Projects/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(118): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit()
#10 /home/home/Projects/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(67): Psalm\Internal\LanguageServer\ProtocolStreamReader->readMessages()
#11 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#12 /home/home/Projects/psalm/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#13 /home/home/Projects/psalm/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#14 /home/home/Projects/psalm/vendor/amphp/amp/lib/Deferred.php(53): class@anonymous->resolve()
#15 /home/home/Projects/psalm/vendor/amphp/byte-stream/lib/ResourceInputStream.php(109): Amp\Deferred->resolve()
#16 /home/home/Projects/psalm/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#17 /home/home/Projects/psalm/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#18 /home/home/Projects/psalm/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#19 /home/home/Projects/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(533): Amp\Loop::run()
#20 /home/home/Projects/psalm/src/Psalm/Internal/Cli/LanguageServer.php(313): Psalm\Internal\Analyzer\ProjectAnalyzer->server()
#21 /home/home/Projects/psalm/psalm-language-server(4): Psalm\Internal\Cli\LanguageServer::run()
#22 {main}
  Code: -32603 `

**Comment by orklah** [comment]
Thanks for the detailed issue.

Care to propose a PR with your suggested fix?

**Comment by NikolayZhebet** [comment]
@orklah, thanks, of course! I'll be happy)
