### ISSUE TITLE
Array keys problem

### ISSUE THREAD

**Issue by matiux** [vimeo/psalm#6561]
I have defined a type to represent a well known part of an array. However the array will have other keys. I know that in the example I can make type more strict. but is it is only an example. The concept is that I have a well know part and other unknown keys. 

https://psalm.dev/r/0f070598ba

Is there a syntax to handle this case?

Something like that where I don't specify the optional key name

```
@psalm-type SerializedObj = array{class: class-string, payload: array{id: string, ?: mixed}}
```

**Comment by orklah** [comment]
This syntax can be used: https://psalm.dev/r/ee9eebfca8

But in this particular case, Psalm will still warn you about possibly undefined key

**Comment by matiux** [comment]
@orklah I will try in my concrete example.
However I suppose that doesn't exist a better way

**Comment by orklah** [comment]
Well, what you're doing is inherently unsafe. Either describe the key in the shape, check its existence through isset or add an @var docblock above.
