### ISSUE TITLE
incorrect InvalidArgument when using generic arrays of multiple value types

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#6563]
see: https://psalm.dev/r/e80523194f

expected: no errors, the array passed is of type `array<string, Node<string>|Node<int>>`

**Comment by azjezz** [comment]
actually, not a bug, but the error message should be clearer ( Node is not covariant ).

https://psalm.dev/r/991ca76408

**Comment by orklah** [comment]
I'll close this, the message was improved slightly

**Comment by AndrolGenhald** [comment]
Seems like this could still be improved to work like [this](https://psalm.dev/r/2c5a043897) without requiring the `@var` annotation.

**Comment by orklah** [comment]
@AndrolGenhald The real fix is: https://psalm.dev/r/45db240ac3

The message was cryptic before, now it explains the issue, but it doesn't show the possible solution

**Comment by AndrolGenhald** [comment]
I think it's also fine to widen the type even when the template isn't covariant, but I guess I'm fine requiring that to be an explicit annotation.

I know we've talked about some sort of alternate annotation to `@var` that's not so dangerous, it would be nice to have that here too for type widening (eg `/** @strict-var int */ $i = 1` widens `$i` from `1` to `int`, but `/** @strict-var int */ $i = 'foo';` should emit an issue).

**Comment by weirdan** [comment]
https://psalm.dev/r/2c5a043897
https://psalm.dev/r/45db240ac3
