### ISSUE TITLE
unrecognized polymorphic function

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#6564]
As in https://psalm.dev/r/714f905304, if I define a polymorphic function

```php
final class Functions
{
    /**
     * @template A
     * @return callable(A): A
     */
	public static function id()
    {
        return fn($a) => $a;
    }
}
```

and I try to use it in

```php
/**
 * @param callable(int): int $f
 * @return int
 */
function onZero(callable $f)
{
	return $f(0);
}

echo onZero(Functions::id());
```

I get a `Argument 1 of onZero expects callable(int):int, callable(empty):empty provided` error, which seems incorrect

**Comment by marcosh** [comment]
Thanks @weirdan for your reply, though I'm not sure I fully understand it.

What do you mean by `unbound` type parameter? `A` is a generic type parameter which is there to denote that the input and the output of the function must have the same type. It should be unified with `int` at the call site.

More generally, is there a way in Psalm to type correctly a function like

```haskell
id :: forall a. a -> a
id a = a
```

a pass it around so that it is recognised with that type?

Am i missing something?

**Comment by Richard87** [comment]
I am also looking for this exact issue:

```php

interface SelfExecutingAggregateCommand extends AggregateCommand
{

    /**
     * @template T
     * @param callable(T):AggregateRootRepository<T> $getRepo
     * @return mixed
     */
    public function __invoke(callable $getRepo);
}

class CheckOutUserCommand implements SelfExecutingAggregateCommand
{
    public function __construct(public string $uuid, public string $username){}

    /** @inheritDoc **/
    public function __invoke(callable $getRepo)
    {
        $repo = $getRepo(Building::class);
        $building = $repo->retrieve(Uuid::fromString($this->uuid));
        $building->checkOutUser($this->username); // Would **love** to have autocompletion here!
        $repo->persist($building);
    }
}
```

Watching this issue!

**Comment by weirdan** [comment]
> What do you mean by unbound type parameter?

`Functions::id()` is a generic method with a single type parameter, `A`. Psalm needs to bind that parameter when it sees a call to that method, but there's nothing to bind it to and this results in it be bound to `empty`. Usually generic method would accept something of type `A` and return some derivative type, e.g. `list<A>`. In your case, however, it's left unbound.

**Comment by marcosh** [comment]
this actually works fine in PHPStan, see https://phpstan.org/r/55ce3965-cacc-424e-ab81-719ae2ff0f29

Personally, being able to write generic callables would make a huge difference to me and would open a lot of new possibilities

**Comment by orklah** [comment]
This was fixed

**Comment by drupol** [comment]
Excellent, thanks !
