### ISSUE TITLE
(support) Iterator template in PhpStorm

### ISSUE THREAD

**Issue by donquixote** [vimeo/psalm#6565]
_This might be a support request. Or a documentation request. Or if there is no solution, it is a feature request..
This might be the responsibility of PhpStorm, or it could be the responsibility of Psalm itself.._

I am using Psalm in PhpStorm.
I had the phpstorm stubs enabled, and then switched to psalm stub files (by adding *.phpstub to file extensions for php).
Results were almost the same, except IteratorAggregate has worse support with psalm stub files.

EDIT: As in comments below, Psalm seems to be working correctly here, the limit seems to be in PhpStorm integration.

```php
interface I0 {
    public function f0();
}

interface I1 {
    public function f1();
}

/**
 * @param iterable<I0, I1> $iterable
 * @param \Iterator<I0, I1> $iterator
 * @param \IteratorAggregate<I0, I1> $ia
 * @param \Traversable<I0, I1> $traversable
 * @param \Iterator|I1[] $itPseudo
 */
function foo(iterable $iterable, \Iterator $iterator, \IteratorAggregate $ia, \Traversable $traversable, \Iterator $itPseudo) {
    foreach ($iterable as $k => $v) {
        $k->f0();  // Type for $k is resolved.
        $v->f1();  // Type for $v is resolved.
    }
    foreach ($iterator as $k => $v) {
        $k->f0();  // Type for $k is NOT resolved.
        $v->f1();  // Type for $v is NOT resolved.
    }
    foreach ($ia as $k => $v) {
        $k->f0();  // Type for $k is NOT resolved.
        $v->f1();  // Type for $v is resolved with phpstorm stub, but not with psalm stubs.
    }
    foreach ($traversable as $k => $v) {
        $k->f0();  // Type for $k is NOT resolved.
        $v->f1();  // Type for $v is NOT resolved.
    }
    foreach ($itPseudo as $k => $v) {
        $k->f0();  // Type for $k is NOT resolved (that's expected).
        $v->f1();  // Type for $v is resolved.
    }
}
```

Is there a way to have full template support for all the cases above?
Or should I use `iterable<..>` all the time?

**Comment by donquixote** [comment]
https://psalm.dev/r/e43412c0d7
Cool. All the types are correctly resolved.
Must be a problem with PhpStorm integration.
Any ideas?

**Comment by donquixote** [comment]
Better version: https://psalm.dev/r/4269afa303
Still, types are resolved correctly.

**Comment by orklah** [comment]
PHPStorm doesn't use Psalm at all for type resolutions. All they do is include errors from Psalm analysis and then they added some support for generics in their internal resolution engine.

Please create a ticket on their issue tracker https://youtrack.jetbrains.com/issues to ask them for a better support for generics

**Comment by donquixote** [comment]
> PHPStorm doesn't use Psalm at all for type resolutions.

Thanks! I should have concluded that.

Issues in PhpStorm:
https://youtrack.jetbrains.com/issue/WI-63230
https://youtrack.jetbrains.com/issue/WI-62323

I opened one of these in the past, but I was not sure if this is purely a PhpStorm problem or partly a Psalm problem.
