### ISSUE TITLE
Is it possible to return type from template method? @return returnOf(T=>__invoke())

### ISSUE THREAD

**Issue by Richard87** [vimeo/psalm#6568]
Hi!

Iam working on a CQRS example, and have a execute method that takes a AggregateCommand argument...

```php
    /**
     * @template T
     * @psalm-param T $command
     * @psalm-return TypeOf(T::__invoke)
     */
    public function execute(AggregateCommand $command)
    {
        return $this->handle($command);
    }
 ```

Here is how i use it:
```
    #[Route("/register-new-building", name: "register")]
    public function register(Request $request): Response {
        $name     = $request->get("name");

        /** @var Uuid $uuid */
        $uuid = $this->commandBus->execute(new RegisterNewBuildingCommand($name));

        return $this->redirectToRoute("building", ["uuid" => $uuid->toString()]);
    }
```

I would love if Psalm would realize that execute returns the same type as `RegisterNewBuildingCommaind->__invoke()`

**Comment by orklah** [comment]
Please try to have a working snippet in psalm.dev. You should assume we don't know anything about the tools and framework you're using (I certainly don't). It's hard to give you a meaningful answer otherwise

**Comment by Richard87** [comment]
I have made a example here: https://psalm.dev/r/f505d77298...

I'm looking for a annotation like this: `@psalm-return returnTypeOf(T::__invoke)`, is that possible?

**Comment by orklah** [comment]
Something like that should work: https://psalm.dev/r/ba296702bd

But I couldn't get it to work while still keeping your signature type

**Comment by weirdan** [comment]
I would just make `Command` generic, like this: https://psalm.dev/r/4a9911427f

**Comment by Richard87** [comment]
Nice, that works!

Thanks for helping me out! 👍
