### ISSUE TITLE
possible false positive somewhere between 6abbc2394703c7badfa651b2dfdc8542652b7e63 and bf7bf1ab3ce04f9f1bf71ec6d920a3de9de8035b

### ISSUE THREAD

**Issue by WDD-Marv** [vimeo/psalm#657]
A lot of my `array_filter`s are now coming up with `First parameter of closure passed to function array_filter expects string, empty provided`, or `First parameter of closure passed to function array_filter expects array<mixed, mixed>, empty provided` etc.

Can't reproduce on getpsalm.org, source repo is private I'm afraid.

**Comment by muglug** [comment]
And latest Psalm master is fine?

**Comment by muglug** [comment]
Or not fine?

**Comment by muglug** [comment]
And you think Psalm should be able to infer the param type? Is this happening in some sort of loop?

**Comment by WDD-Marv** [comment]
will need to get back to you on this one, switching projects a lot this week.

**Comment by WDD-Marv** [comment]
can't recall which project it was on now, but the basic gist was initialising an empty array, which is then conditionally filled, finishing off with an array_filter(), i.e. `array_filter($foo, function($maybeObject) : bool {});`, or `array_filter($foo, function (string $maybeSomethingSpecial) : bool {});`, with the *function* being highlighted with the example error messages.

**Comment by WDD-Marv** [comment]
shall we just close this as "cannot reproduce", as I can't even recall what project I was working on at the time that caused this issue?

**Comment by muglug** [comment]
happy to!
