### ISSUE TITLE
Psalter can break code in case of certain string types

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#6581]
Before: https://psalm.dev/r/fbfac47708
After: https://psalm.dev/r/a0462b5533

**Comment by orklah** [comment]
I'm not even sure how to fix that. Can this be escaped so that it doesn't close the comment?

**Comment by weirdan** [comment]
I don't think there's any escape sequences Psalm would recognize here.

**Comment by orklah** [comment]
Well, I think we can close this. It's a very niche problem and it will be caught by the user very easily. The fix will just be to replace the literal string by `non-empty-string` or something like that
