### ISSUE TITLE
Docs - 403?

### ISSUE THREAD

**Issue by OmgImAlexis** [vimeo/psalm#6586]
Docs link https://psalm.dev/docs/ shows a 403 for me.

![image](https://user-images.githubusercontent.com/6525926/135926486-1e1f5c89-3da2-4166-be96-e7d918ea277b.png)

**Comment by orklah** [comment]
I can't reproduce in my browser. Maybe a temporary issue or you triggered an anti abuse?

**Comment by OmgImAlexis** [comment]
>  you triggered an anti abuse

That makes no sense at all.

**Comment by OmgImAlexis** [comment]
Seems to be working now.
