### ISSUE TITLE
Stubs in Reflection.phpstub should implement `\Reflector`.

### ISSUE THREAD

**Issue by donquixote** [vimeo/psalm#6618]
https://psalm.dev/r/374b6ca3b8 (EDIT: fixed the link)

When passing a `\ReflectionClassConstant` object to a function that requires a `\Reflector`, I get:

> ERROR: InvalidArgument - 8:14 - Argument 1 of f expects Reflector, ReflectionClassConstant provided

This works just fine here: https://3v4l.org/iBjV7

The reason, I suspect, is that in Reflection.phpstub, some classes do not implement `\Reflector`.
This said, I am not really sure how these stubs are supposed to work at all, considering they have only a small subset of the methods available for those classes.

**Comment by donquixote** [comment]
See also #6619 , it seems that reflection stubs are generally a bit weird..

**Comment by orklah** [comment]
We have three sources of knowledge for classes/methods
- the stubs
- the callmaps
- reflection itself

The stubs may not need to be complete if we have intel from callmap.

Please submit a PR for inheritance if it's missing from stubs. Let's see if it  fixes your case

**Comment by donquixote** [comment]
Here we go :)

**Comment by weirdan** [comment]
Fixed in #7317
