### ISSUE TITLE
[?] expects callable():void, Closure():bool provided

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#662]
Is this supposed to be complained about? Given that `callable():void` is expected, the return type of the parameter is not supposed to be used, so passing in `callable():bool` seems safe. TypeScript, for example, would allow it. PHP, in a similar situation (but using inheritance) would *not*.

PHP (function type):
```php
<?php
  /**
   * @param callable():void $p
   */
  function doSomething($p): void {}
  doSomething(function(): bool { return false; });
```
TypeScript (function type):
```typescript
function doSomething(p: () => void): void { }
doSomething(() => { return true;});
```
PHP (inheritance):
```php
<?php

class A {
    public function doSomething(string $q): void {}
}
class B extends A {
    public function doSomething(string $q): bool {}
}
```

**Comment by muglug** [comment]
Yup, this should be fine. Will fix.
