### ISSUE TITLE
Psalm assumes $e is mixed after eval() + catch

### ISSUE THREAD

**Issue by donquixote** [vimeo/psalm#6630]
https://psalm.dev/r/6b3be28f88

**Expected**: `$e` is assumed to be a `\Throwable` object in both catch blocks.
**Actual**: `$e` i assumed to be a `mixed` value in the catch block after `eval()`.

Why does it happen?
Psalm (correctly) assumes that `eval()` can set local variables to any random value.
However, even if the eval'd code sets `$e`, this variable will be overwritten in `catch (\Throwable $e)`.

See https://3v4l.org/ZbJer

Or are we worried about shenanigans with reference variables, that would overwrite `$e` magically? I don't see how that could happen..

Workaround:
One can move the eval() to a separate method to prevent tainting of local variables.
(Or we can discuss that eval() is bad.. but I think that's not really what we are here for)

**Comment by orklah** [comment]
When Psalm encounters `eval` or similar construct where anything can go (like unresolved includes), it marks the current context with two flags: `check_classes` and `check_variables`. The reason for that is that the rest of the scope is very likely to use unresolved symbols, so Psalm will analyse the rest of the scope very lightly.

In the case of method calls, it's here:
https://github.com/vimeo/psalm/blob/8b07e696455a70f1308eb7f35bf42728a697f21f/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php#L103

On a glance, it seems like it could be handled better. If we know the class, the method and the args, maybe we could try to continue.

I have no particular interest working for a better eval() support though so I won't try this myself. Feel free to give it a go, I'm here for advices

**Comment by weirdan** [comment]
The original snippet doesn't produce any errors anymore. `$e` is correctly inferred as `Throwable` in both cases: https://psalm.dev/r/c6775d73fa
