### ISSUE TITLE
MixedArgumentTypeCoercion: `I[]` is interpreted differently in param vs property.

### ISSUE THREAD

**Issue by donquixote** [vimeo/psalm#6632]
https://psalm.dev/r/2b60883841

> Psalm output (using commit f62c76a): 
> 
> INFO: MixedArgumentTypeCoercion - 15:18 - Argument 1 of C::a expects array<array-key, I<object>>, parent type array<array-key, I> provided

Expected:
- `@var I[]` and `@param I[]` should be seen as the same type.
- `I[]` and `I<object>[]` should be seen as the same type, because of the `as object` in the template declaration.

Actual:
- Property type inferred as `array<array-key, I>`. Parameter type inferred as `array<array-key, I<object>>`.
- `array<array-key, I>` is seen as distinct from and parent type of `array<array-key, I<object>>`.

**Comment by donquixote** [comment]
Workaround:
Use `@var I<object>` on properties.
On parameters it is fine to use just `@param I`.

**Comment by donquixote** [comment]
Workaround:
Use `@var I<object>` on properties.
On parameters it is fine to use just `@param I`.
https://psalm.dev/r/52e0811001
(re-post to trigger the bot)

**Comment by AndrolGenhald** [comment]
This is fixed on my type system rewrite, which might eventually get released with Psalm 6.

**Comment by orklah** [comment]
good to know :)

Do you get notifications when I add a label to an issue??

**Comment by AndrolGenhald** [comment]
> Do you get notifications when I add a label to an issue??

I'm not quite crazy enough to try that "Watch -> All Activity" option on a project this active :laughing:
I sort open/closed issues and pull requests by "Recently updated", that way a few times a day (or more if I'm bored) I can skim through anything that's changed since the last time I checked without spamming my email more than necessary.

**Comment by orklah** [comment]
oohh, makes sense, thanks. FYI, "all activity" doesn't report reactions nor labels as far a I know, that's why I was surprised you were able to see when I labelled this old issue :p

**Comment by weirdan** [comment]
No snippets here produce any errors now.
