### ISSUE TITLE
How to properly annotate `@param class-string<T>|null` as fallback to `object`?

### ISSUE THREAD

**Issue by donquixote** [vimeo/psalm#6638]
I have a function/method with an optional `@param class-string<T>|null $class` parameter.
The function should return `T` or `T[]` if $class is provided, or `object` if $class is NULL.

https://psalm.dev/r/bea75ab401

> Psalm output (using commit 5134a92): 
>
> INFO: MixedAssignment - 26:46 - Unable to determine the type that $item is being assigned to

The MixedAssignment only happens in foreach() from `@return T[]`, not on the single-value case.
However, in both cases the return value is resolved as `empty` instead of `object`.

(heads up: I might get my hands dirty with development at some point, but I need to make time for it. For now I am simply reporting what I find)

**Comment by donquixote** [comment]
@weirdan I noticed that even the built-in stubs in psalm don't follow this syntax.
They would have to be like this:
https://github.com/vimeo/psalm/compare/master...donquixote:patch-1

In ReflectionMethod:
```diff
      * @since 8.0
      * @template TClass as object
      * @param class-string<TClass>|null $name
-     * @return array<ReflectionAttribute<TClass>>
+     * @return array<ReflectionAttribute<$name is null ? TClass : object>>
      */
     public function getAttributes(?string $name = null, int $flags = 0): array {}
```

I think it would be simpler to just treat the `as object` in `@template T as object` as a fallback type, or introduce a new syntax for this purpose, instead of introducing the conditional syntax in all the stubs.

**Comment by orklah** [comment]
Please read https://psalm.dev/docs/annotating_code/type_syntax/conditional_types/ again, your syntax is not valid

**Comment by donquixote** [comment]
@orklah I noticed one mistake: I swapped object and class. Corrected in my message, but not in the linked diff.

Otherwise, my code is based on the comment by @weirdan.

The docs suggest that I can only use template types in the condition, not parameter names.
E.g. `T is null` but not `$name is null`. But weirdan's post suggests otherwise, and it works.

The docs also say I need to use parentheses around the ternary expression. But it works fine without.
https://psalm.dev/r/7b0ec389fa

Seems more like a case of incomplete docs. Or perhaps I am relying on undocumented features that might be removed in a future version?

**Comment by orklah** [comment]
Yeah, I was referring to the parentheses at least because I thought conditional inside the generic type was not working either.

Turns out it does. I'm quite surprised, I never saw that before. I think you found some feature that was maybe not meant to work.

I think it'd be safer to use something like 
`($name is null ? array<ReflectionAttribute<object> : array<ReflectionAttribute<TClass>)`

**Comment by donquixote** [comment]
@orklah The docs suggest that some kind of nesting is supported..
The nesting example in the docs uses multiple layers of ternaries. But one could also expect that nesting ternaries inside other type expressions should work.

> Turns out it does. I'm quite surprised, I never saw that before. I think you found some feature that was maybe not meant to work.

Perhaps create test cases for this and then make sure it continues to work?

**Comment by orklah** [comment]
> Perhaps create test cases for this and then make sure it continues to work?

Psalm is very complicated and its author is not there anymore to maintain it. I won't do anything to break it, but if it's just a different syntax to express the same thing, I'm not sure it's a good idea to add constraints like that. Especially so if it was not by design
