### ISSUE TITLE
request for per-projectFiles entry totallyTyped config

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#666]
It'd be handy to treat `psalm[totallyTyped]` as the default config value for `psalm > projectFiles` entries & cli paths, with the additional config of `psalm > projectFiles > file, psalm > projectFiles > directory` being given a totallyTyped attributed, so it can be disabled/enabled on a per-file/per-directory basis (i.e. I don't care so much about my tests not being totally typed)

**Comment by muglug** [comment]
Currently `totallyTyped` is a proxy for "don't ignore [these specific  issues](https://github.com/vimeo/psalm/blob/e58274acaa82c7508fb8b91ca28fa53191c48477/src/Psalm/Config.php#L32-L46)".

Removing it on a per-folder basis might complicate matters. I'll give it a think.

**Comment by muglug** [comment]
Yeah, I'm not going to enable this. But you can add rules for those issues, suppressing them in tests. You could also have a look at the Psalm PHPUnit and Mockery plugins to increase the non-mixed coverage in tests.
