### ISSUE TITLE
Docker psalm

### ISSUE THREAD

**Issue by rudireg** [vimeo/psalm#6680]
Hi.
I use Docker.
Phpstorm.
XDebug 3
php 8
Symfony.
I installed: **composer require --dev vimeo/psalm**
The psalm have installed in vendor folder of the project.
When it starts I have the error
`0:38	Psalm
			psalm: [17-Oct-2021 00:38:16 Europe/Moscow] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.17.0.1:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
			[17-Oct-2021 00:38:16 Europe/Moscow] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.17.0.1:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
			Uncaught RuntimeException: PHP Error: Could not create cache directory: //.cache/psalm/d2b6c12ab2d22552b3a7faee0509e6139f633afc in /app/vendor/vimeo/psalm/src/Psalm/Config.php:914 in /app/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
			Stack trace:
			#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}(256, 'Could not creat...', '/app/vendor/vim...', 914)
			#1 /app/vendor/vimeo/psalm/src/Psalm/Config.php(914): trigger_error('Could not creat...', 256)
			#2 /app/vendor/vimeo/psalm/src/Psalm/Config.php(662): Psalm\Config::fromXmlAndPaths('/app/&#3...
			Open Psalm Inspection Settings (show balloon)`

But, if I switch on the button of the PhpStorm: **Start listening for PHP Debug connection**
there is no the error.

How can I use PSALM without switch on the debug mode ?

I have also tried install psalm on local host, it works, but **it does not see extended classes of the Symfony located in vendor folder.** Psalm says that there is no such class

How can I fix it?

**Comment by orklah** [comment]
Closing as stale
