### ISSUE TITLE
Providing `iterable` to `array|\Traversable` triggers an `InvalidArgument` error

### ISSUE THREAD

**Issue by driehle** [vimeo/psalm#6682]
In [doctrine/doctrine-laminas-hydrator](https://github.com/doctrine/doctrine-laminas-hydrator) we are using the function `ArrayUtils::iteratorToArray()` from [laminas/laminas-stdlib](https://github.com/laminas/laminas-stdlib). Though the name of that method suggests to expect an `iterable`, the method actually expects an `array|\Traversable` like this:

```php
    /**
     * @param array|\Traversable  $iterator     The array or Traversable object to convert
     * @return array
     */
    public static function iteratorToArray($iterator, $recursive = true)
    {
        return [];
    }
```

Now in our library, there is a `mixed` argument which is explicitly checked for being an `array` or an instance of `\Traversable`, before being passed to `ArrayUtils::iteratorToArray()`. This looks like this:

```php
    /**
     * @param  mixed $identifier
     */
    private function isNullIdentifier($identifier)
    {
        if ($identifier instanceof \Traversable || is_array($identifier)) {
            ArrayUtils::iteratorToArray($identifier);
        }
    }
```

It seems like Psalm - from the if statement - infers that `$idendifier` is an `iterable`, but then it complains because `iterable` is not an valid input for `ArrayUtils::iteratorToArray()`. The following error raises:

```
ERROR: InvalidArgument - 22:45 - Argument 1 of ArrayUtils::iteratorToArray 
  expects Traversable|array<array-key, mixed>, 
  iterable<array-key|mixed, mixed> provided
```

Probably a bug in Psalm? See https://psalm.dev/r/0e02a5ccf0 for the full example.

**Comment by orklah** [comment]
It is indeed a bug.

From what I could tell, Psalm correctly infer two assertions about `$identifier`: `array` and `Traversable`. It then takes the initial `mixed` type and apply the `array` assertion to it, and it outputs the atomic type `TArray`. It does the same from `mixed` to `TNamedObject` with a value as `Traversable`

Then it pass the two of them to the TypeCombiner, which is the class that outputs 1 type from a list of multiples types. This is what outputs iterable. What puzzle me right now is that the TypeCombiner doesn't have a notion of union or intersection, so I'm not sure how it's actually supposed to do the difference between 
`is_array && Traversable` and `is_array || Traversable`
