### ISSUE TITLE
Invalid `ParadoxicalCondition` raised with nested conditions in if statement

### ISSUE THREAD

**Issue by driehle** [vimeo/psalm#6683]
The following code raises two `ParadoxicalCondition` errors:

```php
$isImmutable = substr($typeOfField, -9) === 'immutable';

if (
    ($isImmutable && $value instanceof DateTimeImmutable)
    || (! $isImmutable && $value instanceof DateTime)
) {
    return $value;
} elseif ($isImmutable && $value instanceof DateTime) {
    return DateTimeImmutable::createFromMutable($value);
} elseif (! $isImmutable && $value instanceof DateTimeImmutable) {
    return DateTime::createFromImmutable($value);
}
```

```
ERROR: ParadoxicalCondition - src/DoctrineObject.php:620:23 - Condition (($value is DateTime) && ($isImmutable)) contradicts a previously-established condition ($value is not DateTime) (see https://psalm.dev/089)
                } if ($isImmutable && $value instanceof DateTime) {


ERROR: ParadoxicalCondition - src/DoctrineObject.php:622:27 - Condition (($value is DateTimeImmutable) && (!$isImmutable)) contradicts a previously-established condition ($value is not DateTimeImmutable) (see https://psalm.dev/089)
                } elseif ((! $isImmutable) && $value instanceof DateTimeImmutable) {
```

Rewriting the first if condition in two statements makes the error disappear:

```php
$isImmutable = substr($typeOfField, -9) === 'immutable';

if ($isImmutable && $value instanceof DateTimeImmutable) {
    return $value;
} elseif (! $isImmutable && $value instanceof DateTime) {
    return $value;
} elseif ($isImmutable && $value instanceof DateTime) {
    return DateTimeImmutable::createFromMutable($value);
} elseif (! $isImmutable && $value instanceof DateTimeImmutable) {
    return DateTime::createFromImmutable($value);
}
```

Code example: https://psalm.dev/r/d26bab675e

**Comment by driehle** [comment]
@greg0ire has further simplified down the issue to https://psalm.dev/r/53f79d44aa.

**Comment by orklah** [comment]
Reduced even more: https://psalm.dev/r/e79c2894ec

Must be a flaw in boolean module of Psalm. Which I believe is located in `FormulaGenerator::getFormula`. It's 400 lines of recursive boolean operations. It's gonna be tricky

**Comment by muglug** [comment]
OK so this is tricky.

```php
($a && $b) || (!$a && $c)
```

is expanded by Psalm to the conjunctive normal form

```php
($a || $c) && (!$a || $b) && ($b || $c)
```

This equivalent (to Psalm) version [demonstrates the same bug](https://psalm.dev/r/76864ff3a5).

But when you enter that CNF into Wolfram Alpha it tells you [the last term is unnecessary](https://www.wolframalpha.com/input/?i=%21%28%28%21a+%7C%7C+b%29+%26%26+%28a+%7C%7C+c%29+%26%26+%28b+%7C%7C+c%29%29).

If you remove the unnecessary term [the bug disappears](https://psalm.dev/r/bc5487153d).

The buggy method is `Algebra::combineOredClauses`, but I don't know how to fix it — `combineOredClauses` is a pretty simple method that just applies the standard distributed method for converting DNF to CNF. Then it looks like `Algebra::negateFormula` has incorrect behaviour when passed a formula with unnecessary terms, but I don't think _that_ is a bug — `negateFormula` expects an optimal CNF.

I don't, honestly, remember how to obviously get the DNF to CNF conversion correct (missing the unnecessary term) on paper — once that was correct, fixing the `combineOredClauses` method wouldn't be too difficult. Either way the solution would probably slow down `combineOredClauses`.

**Comment by muglug** [comment]
Another example:

These two are functionally similar but give different output: https://psalm.dev/r/8f6b691a68

**Comment by orklah** [comment]
This is fixed! Thanks Matt!
