### ISSUE TITLE
__toString return type issues

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#6692]
1. `__toString` with explicit `string` return type does not complain when `Stringable` is actually: https://psalm.dev/r/27c9d59a38.
2. `__toString` without return type should also complain about `Stringable`: https://3v4l.org/rHHbP.

**Comment by orklah** [comment]
Not in strict types: https://3v4l.org/4pnV3#v8.0.11

So every case should emit an `ImplicitToStringCast` at the very least
