### ISSUE TITLE
Getting Psalm to play along with Neomake

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#670]
Neomake can be configured to deal with different error formats. Are there any options to configure Psalm's output?

**Comment by muglug** [comment]
You can run with `--output-format=emacs` to get single line output

**Comment by olleharstedt** [comment]
Ah, that's great. I already solved it with

    \'errorformat': '%tRROR:\ %s\ \\-\ %f:%l:%c\ \\-\ %m,%tNFO:\ %s\ \\-\ %f:%l:%c\ \\-\ %m',
