### ISSUE TITLE
array-to-object conversion not checked

### ISSUE THREAD

**Issue by Patrick-Remy** [vimeo/psalm#6750]
It seems that `(object) []` conforms to all `object{}` types in psalm, as following does not throw any errors. It would be expected to claim about missing `a` property, like it's the behavior for arrays.

https://psalm.dev/r/f68a6ef77a

**Comment by weirdan** [comment]
`MoreSpecificReturnType`/`LessSpecificReturnStatement` are now emitted for `object{}`
