### ISSUE TITLE
false positive RedundantCondition re: comparing get_class() to ::class magic constant

### ISSUE THREAD

**Issue by WDD-Marv** [vimeo/psalm#677]
Method type hints `Foo`, class `Bar` extends `Foo`, method can return `Bar`, conditional checking for root class is erroneously considered a redundant condition.

https://getpsalm.org/r/c5c9e4e159

**Comment by muglug** [comment]
Solution here is to do have `get_class` create a similar sort of assertion that `is_a` does, that gets recognised by the `Reconciler` class.

Simpler testcase: https://getpsalm.org/r/946e5b68ad

**Comment by muglug** [comment]
Thanks, added that and fixed. Snippet now has no issues.
