### ISSUE TITLE
psalter throws error if autoloader file defines constants

### ISSUE THREAD

**Issue by devbanana** [vimeo/psalm#6772]
I have a custom autoloader defined in order to set constants I need. My code depends on WordPress so I need to define some WordPress constants.

But when I run vendor/bin/psalter, I get this error for each constant in the autoload file:

```
Uncaught RuntimeException: PHP Error: Constant ABSPATH already defined in /path/to/project/tests/psalm/bootstrap.php:13 in /path/to/project/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
```

I haven't been able to find any other reports on this. My file is pretty simple so I can't see how it'd be anything on my end.

**Comment by orklah** [comment]
This should be fixed now
