### ISSUE TITLE
MixedInferredReturnType with static variables

### ISSUE THREAD

**Issue by WDD-Marv** [vimeo/psalm#678]
conditionals on scoped static variables don't appear to be processed as one would expect. This is similar logic to #151 

https://getpsalm.org/r/aae3e18cf0

**Comment by muglug** [comment]
This is by design, currently.

It's to avoid this bug:

```php
function foo() {
  static $bar = null;
  
  if ($bar === "hello") { // other packages report a bug here
    // do something
  }
  
  $bar = "hello";
}
```

The solution would be to scan any function with `static` vars twice like we do loops, to collect all possible values a variable can have.

Not sure how necessary that is, though - I haven't seen `static` used too often in the wild.

**Comment by WDD-Marv** [comment]
for giggles, I tried to see what would happen if I tried to resolve the type detection issue with a typed-property value object.
* https://getpsalm.org/r/5ff50c102b getter/setter
* https://getpsalm.org/r/c66827f3e0 public property

**Comment by WDD-Marv** [comment]
similar issue or separate issue?: https://getpsalm.org/r/db51e2e0b3

```php
/**
* @var DateTimeInterface|null
*/
$foo = null;

$bar = function () use(& $foo) : DateTimeInterface {
  if (is_null($foo)) {
    $foo = new DateTimeImmutable();
  }
  
  return $foo;
};

$bar();
```

> INFO: MixedReturnStatement - 22:3 - Could not infer a return type
> INFO: MixedInferredReturnType - 17:34 - Could not verify return type 'DateTimeInterface' for /var/www/vhosts/getpsalm.org/httpdocs/src/somefile.php:17:210:-:closure

**Comment by bugreportuser** [comment]
@muglug Could Psalm support annotations on static variables as a workaround?

Example:
```php
<?php
function example(): void {
    /** @var string|bool */
    static $x = true;

    if ($x) {
        $x = 'x';
    }
    ord($x); // error
    chr($x); // error

    $x = false;
    $x = 0; // error
}
```

Same idea as:
```php
<?php
class Clazz {
    /** @var string|bool */
    private $x = true;

    function example(): void {
        if ($this->x) {
            $this->x = 'x';
        }
        ord($this->x); // error
        chr($this->x); // error

        $this->x = false;
        $this->x = 0; // error
    }
}
```

**Comment by gharlan** [comment]
This is the last thing that prevents me from using `totallyTyped="true"`.

**Comment by muglug** [comment]
@gharlan one can always suppress issues on a per-function or per-file basis, but this is now fixed along the lines @bugreportuser suggested (it uses the same mechanism by which Psalm restricts the values of by-ref variables).

**Comment by bugreportuser** [comment]
Thanks! This is really great for `totallyTyped`.
