### ISSUE TITLE
@psalm-type does not support parentheses

### ISSUE THREAD

**Issue by sctice-ifixit** [vimeo/psalm#6782]
https://psalm.dev/r/a55241a2df

The error message implies a syntax error, but it seems to be the case that parentheses are just unsupported in `@psalm-type`. Perhaps that's by design (last I checked, the docs have very little to say about parentheses). If it is intentional or not worth supporting, perhaps the error message could be a little more straightforward? "Unterminated parentheses" seems incorrect; perhaps "Parentheses are not supported in @psalm-type"?

The parentheses in the example are obviously superfluous. It's less obvious (though probably still superfluous?) if you want to define a large union over multiple lines.

**Comment by danielbeardsley** [comment]
Hi Shawn! I ran into the same thing, but I think it's even more odd.

`@psalm-type, anything after the `>` greater-than symbol is just straight-up ignored by the parser:

https://psalm.dev/r/67abe4ae45
