### ISSUE TITLE
Could not infer a return type for return statement that reads property

### ISSUE THREAD

**Issue by rightfold** [vimeo/psalm#679]
Running Psalm 1.1.0 against the following file fails to infer the type of the expression in `PsalmTest\Example::get`.

```php
<?php
declare(strict_types = 1);

namespace PsalmTest;

/**
 * @template T
 */
final class Example
{
    /** @var T $x */
    private $x;

    /** @param T $x */
    public function __construct($x)
    {
        $this->x = $x;
    }

    /** @return T */
    public function get()
    {
        return $this->x;
    }
}
```

The following error is printed.

```
ERROR: MixedReturnStatement - src/PsalmTest/Example.php:23:9 - Could not infer a return type
        return $this->x;
```

The following is my Psalm configuration.

```xml
<?xml version="1.0"?>
<psalm
    totallyTyped="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="/home/r/psalm-test/vendor/vimeo/psalm/src/config.xsd"
>
    <projectFiles>
        <directory name="src" />
    </projectFiles>
</psalm>
```

It seems like it should work. If I change the return statement to `return 42;` then it gives an error about returning an `int` where a `T` is expected, as expected.

**Comment by muglug** [comment]
Ah ok, this is a side-effect of templating. Will fix (but feel free to ignore that issue in that file).

Templating still works fine for that method: https://getpsalm.org/r/b7cb745441

**Comment by muglug** [comment]
Thanks - necessitated a slight refactoring of the way templated types are handled which I hope will open up new possibilities in the future.
