### ISSUE TITLE
deprecate exitFunctions in Psalm 5?

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#6794]
This is an undocumented config that allows adding always exiting functions for Psalm.

However, this is not considered everywhere and it has drawbacks (you have to remember it's there, retrieving them from config, resolving calls to check them...).

Fortunately, since we now have `never`, the whole feature became redundant, as declaring never on phpdoc or on a stub will have the same benefits without drawbacks. 

That's why I'm suggesting to drop this config for Psalm 5

**Comment by weirdan** [comment]
Totally agree, let's ditch it.
