### ISSUE TITLE
PropertyNotSetInConstructor error for PHPunit test

### ISSUE THREAD

**Issue by A2DNEW** [vimeo/psalm#6799]
Error:

```
ERROR: PropertyNotSetInConstructor - tests/ConfigTest.php:9:7 - Property Name\New\TestCase\ConfigTest::$backupStaticAttributes is not defined in constructor of Name\New\TestCase\ConfigTest and in any methods called in the constructor (see https://psalm.dev/074)
class ConfigTest extends TestCase
```

How can I fix it?

**Comment by HFMohammad** [comment]
> Hey @A2DNEW, can you reproduce the issue on https://psalm.dev ?

This test with super-linter

**Comment by weirdan** [comment]
Are you using [PHPUnit plugin](https://packagist.org/packages/psalm/plugin-phpunit)?

**Comment by A2DNEW** [comment]
> Are you using [PHPUnit plugin](https://packagist.org/packages/psalm/plugin-phpunit)?

I use this: https://phpunit.de/getting-started/phpunit-8.html
And check codes with super-liter on github actions

**Comment by A2DNEW** [comment]
> > Hey @A2DNEW, can you reproduce the issue on https://psalm.dev ?
> 
> This test with super-linter

Yes

**Comment by A2DNEW** [comment]
> > Hey @A2DNEW, can you reproduce the issue on https://psalm.dev ?
> 
> Is this test with super-linter?

yes

**Comment by A2DNEW** [comment]
I added this lines to composer but don't work it:

```
"require-dev": {
        "phpunit/phpunit": "^8.0",
        "psalm/plugin-phpunit": "^0.16.1"
    }
```

**Comment by weirdan** [comment]
To use the plugin you have to enable it: https://psalm.dev/docs/running_psalm/plugins/using_plugins/#managing-known-plugins

**Comment by weirdan** [comment]
Replace `plugin-vendor/plugin-package` with `psalm/plugin-phpunit`. Do you have any suggestions on how we could make that more clear in the docs? 

> super-linter?

Never heard of it, so I won't be able to help you with it.

> And how can I enable it for github actions?

If you commit both `psalm.xml` and `composer.lock`, and run `composer install` as a part of your action it's already enabled.

**Comment by A2DNEW** [comment]
After add psalm I get this error:

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.24. in /var/www/html/vendor/composer/platform_check.php on line 24

My composer:

```
"require": {
        "php": "^7.3||^8.0",
        "psalm/plugin-phpunit": "^0.16.1"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.0"
    }
```

**Comment by SandroMiguel** [comment]
This solved my problem:
```
composer require --dev psalm/plugin-phpunit
vendor/bin/psalm-plugin enable psalm/plugin-phpunit
```

**Comment by A2DNEW** [comment]
> This solved my problem:
> 
> ```
> composer require --dev psalm/plugin-phpunit
> vendor/bin/psalm-plugin enable psalm/plugin-phpunit
> ```

Thank you
But I get this error:

`  Cannot find Psalm config  `

**Comment by orklah** [comment]
You have to run psalm --init first if you don't already have a config file

**Comment by A2DNEW** [comment]
Thank you

**Comment by 0fuzz** [comment]
Thanks, run in this problem just now.
