### ISSUE TITLE
False positive - instanceof exception check

### ISSUE THREAD

**Issue by ErikBooijCB** [vimeo/psalm#680]
In our exception handler, we try to determine if an exception is one thrown by a data store and if so, we want to return the response with a 503 status code, otherwise a 500 status code will suffice.

```php
function (
    ServerRequestInterface $request,
    ResponseInterface $response,
    Throwable $exception
): ResponseInterface {
    if ($exception instanceof ElasticsearchException || $exception instanceof PDOException) {
        return $response->withStatus(503);
    }

    return $response->withStatus(500);
}
```

It generates the following error:

```
ERROR: TypeDoesNotContainType - src/Infrastructure/Error/ErrorHandlerFactory.php:55:21 - Cannot resolve types for $exception - Throwable&Elasticsearch\Common\Exceptions\ElasticsearchException does not contain PDOException
```

Weird thing is that if we switch the `instanceof` checks around, the error message remains identical, instead of indicating that `PDOException` does not contain `ElasticsearchException`.

**Comment by muglug** [comment]
What version of Psalm?

**Comment by muglug** [comment]
Simpler testcase: https://getpsalm.org/r/f4815ff60e

**Comment by muglug** [comment]
I'm unable to reproduce, after going back and forth a bit. The closest I can get is: https://getpsalm.org/r/9ba0dbf925, but latest Psalm has no issues with that.

What version of Psalm are you running? And what version of PHP?

**Comment by ErikBooijCB** [comment]
Hmm, interesting. I'm running `Psalm 1.1.1` on `PHP 7.2.4`.

I've created a somewhat more extensive example, I guess I took out a little bit too much when I was converting it to a sample I could publish here.

https://getpsalm.org/r/cb72cc0d91

**Comment by muglug** [comment]
Ah, it appears to be an order of operations thing, which is why me changing names was unhelpful: https://getpsalm.org/r/b4c7111819. Will fix underlying bug.

**Comment by muglug** [comment]
Thanks for being patient. Should be good now in `dev-master` and `1.x`.

**Comment by muglug** [comment]
You can also document that function's return type more explicitly: https://getpsalm.org/r/f2699efd4f

**Comment by ErikBooijCB** [comment]
@muglug Patient? I've never seen an OSS maintainer respond to and fix issues as quickly as you do. Thanks a lot! I wasn't aware of the fact the callable return type could be documented this specifically, will implement :) Great work!

**Comment by muglug** [comment]
Idle bugs are the devil’s plaything
