### ISSUE TITLE
coveralls.io PHPUnit test coverage is out of date over 1.5 years.

### ISSUE THREAD

**Issue by sasezaki** [vimeo/psalm#6800]
coveralls.io PHPUnit test coverage is out of date over 1.5 years.
Test coverage was no longer output after moving to parallel testing.

https://coveralls.io/github/vimeo/psalm

> LAST BUILD ON BRANCH master 
> Committed 12 Apr 2020 - 18:32

**Comment by sasezaki** [comment]
At first, I propose remove coverage badge in README.md.
Because it is mostly useless.

Secondly, to re-enable output coverage, ...it seems very heavey task.

I had tried upload to codecov, but coverage files is too big. (4.61GB)
https://github.com/sasezaki/psalm/pull/1/fil
<img src="https://user-images.githubusercontent.com/42755/140005260-cec2eff8-344b-4723-b154-f4c7bc7de5c4.jpg" width=400 />
<img src="https://user-images.githubusercontent.com/42755/140005269-e5286b18-9c70-4646-9f7c-d40c591002cc.png" width=400 />

**Comment by orklah** [comment]
This was apparently done on purpose for the same reason you have troubles reenabling it: https://github.com/vimeo/psalm/commit/eb08e101fb8f60128ea36d96d49cc3078d8d7417

I'd say we get rid of the badge
