### ISSUE TITLE
False positive when 'true' passed to print_r() or var_export()

### ISSUE THREAD

**Issue by mmcev106** [vimeo/psalm#6806]
I believe both these are false positives:

https://psalm.dev/r/44c35f665c

I tried creating a PR by adding `@psalm-taint-escape ($return is true ? 'html' : null)` in `CoreGenericFunctions.phpstub`, but the sink seems to take precedence.  Assuming I'm on the right track, can anyone direct me to the place code where a check could be added to make the sink conditional based on the escape?

**Comment by orklah** [comment]
I don't think `@psalm-taint-escape ($return is true ? 'html' : null)` is correct. print_r will not escape anything on its own and `echo print_r($tainted_value, true);` should still be flagged.

However, print_r is only a sink if the second parameter is not true. Which means we would need conditional sink (like we already have conditional escapes)

By taking a quick glance at it, you should start in FunctionLikeDocblockParser.
This is the part that spot we have a conditional escape and sanitize it:
https://github.com/vimeo/psalm/blob/0cdb0dc04ad27379120ee5446b619ad1170cec4a/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php#L280

It's then put in $info who is a FunctionDocblockComment and will be handled in FunctionLikeDocblockScanner here: https://github.com/vimeo/psalm/blob/6fa2da0f297b1437a67aff5c2efc22c27cee38f3/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php#L326

I guess we would need something similar for conditional sinks

**Comment by gharlan** [comment]
conditional sinks: https://github.com/vimeo/psalm/issues/4669
