### ISSUE TITLE
Error when suppression is no longer required

### ISSUE THREAD

**Issue by polothy** [vimeo/psalm#681]
First, thanks for the great project, just completed setting up one of my projects to use Psalm!

So, the result of the project setup is that now I have a `psalm.xml` file with a bunch of `suppress`'s - most are file specific.  As things change and or improve, those suppresses might become irrelevant (EG: I fix my code or vendor code is improved).  Would be nice if Psalm would error or at least warn when a suppression was no longer required in order to keep the config file up-to-date.

**Comment by muglug** [comment]
This is a great idea

**Comment by muglug** [comment]
This was essentially implemented in https://github.com/vimeo/psalm/pull/1049

**Comment by weirdan** [comment]
Would still be useful for docblock suppressions though.
