### ISSUE TITLE
Psalm ignores values after 102th when inferring array value type

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6814]
Psalm uses at most 101 elements to infer array shape: https://psalm.dev/r/5f192e37bf
And at most 102 elements to infer array value type: https://psalm.dev/r/62d9666fdc
Elements after 102th are ignored: https://psalm.dev/r/6462ff9bcc

This doesn't look right. While it's understandable that we cannot allow unbounded shapes, we probably should still be able to use all elements to infer array value/key type (as we actually process all elements).

_Originally posted by @weirdan in https://github.com/vimeo/psalm/issues/6810#issuecomment-960262781_

**Comment by weirdan** [comment]
This probably could be solved by inferring the type iteratively instead of collecting element types and combining the all at once.

**Comment by orklah** [comment]
Seems fixed
