### ISSUE TITLE
Level 1 not avoid for spaces

### ISSUE THREAD

**Issue by A2DNEW** [vimeo/psalm#6822]
This is my code:

`throw new Exception($hi." hello");`

This line most be:

`throw new Exception($hi . " hello");`

I run this command:

`./vendor/bin/psalm --show-info=true`

But not show error for me.

**Comment by A2DNEW** [comment]
> Hey @A2DNEW, can you reproduce the issue on https://psalm.dev ?

Yes.  but I don't give any error!

**Comment by weirdan** [comment]
Psalm does not enforce any coding style, it's outside of its scope. You may want to look into PHP CodeSniffer or similar tools.
