### ISSUE TITLE
don't emit issue for functions or class after a never-returning function call

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#6827]
https://psalm.dev/r/d043c70a10?php=8.1

**Comment by weirdan** [comment]
Did you mean you wanted something to be emitted (e.g. MissingReturnType)?

**Comment by orklah** [comment]
No, I want to prevent the emission of UnevaluatedCode because even when the function is declared after the `never`-returning call, it's still allowed by PHP: https://3v4l.org/3HPc0

UnevaluatedCode implies that the code could be deleted but it can't
