### ISSUE TITLE
Error message: "Cannot declare class, already in use"

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#683]
When running Psalm on one of our files, I get this error:

```
Using reflection to locate file for Template
PHP Fatal error:  Cannot declare class Twig_Template, because the name is already in use in /var/www/lime25/limesurvey/application/third_party/Twig/Template.php on line 24
```

I don't know if this error is related to the fact that two classes, `Twig_Template` and `Template` both use the same filename: `Template.php`?

Any way to debug further?

**Comment by muglug** [comment]
`Using reflection to locate file for X` appears when Psalm finds something it thinks might be a class, but that it cannot find via composer.

Then it tries creates a `ReflectionClass` instance for `X`, which in turn forces PHP to use whatever autoloaders are available.

In this case the autoloader appears to try and read `application/third_party/Twig/Template.php` assuming it represents the class `Template`, when it actually represents `Twig_Template`. That's as much as I can tell from a distance.

But essentially it's an autoloader problem, not a Psalm problem. If the file you're running on is also opensource, maybe I can have more of an idea.

**Comment by olleharstedt** [comment]
OK, this problem disappears if I manually import the model class instead of depending on the autoloader. Not sure if that's the required fix.

**Comment by muglug** [comment]
could you add the path as a psr-0 route in `composer.json`?
