### ISSUE TITLE
Argument 3 of openssl_sign expects resource|string, OpenSSLAsymmetricKey provided

### ISSUE THREAD

**Issue by jirkace** [vimeo/psalm#6842]
Function `openssl_sign` [accepts](https://www.php.net/manual/en/function.openssl-sign.php) `OpenSSLAsymmetricKey|OpenSSLCertificate|array|string` for third parameter for PHP8

> 8.0.0 | private_key accepts an OpenSSLAsymmetricKey or OpenSSLCertificate instance now; previously, a resource of type OpenSSL key or OpenSSL X.509 was accepted.

This is new bug in version 4.12.0

**Comment by jirkace** [comment]
> Hey @jirkace, can you reproduce the issue on https://psalm.dev ?

yes :-)

here is it: https://psalm.dev/r/bd9b345da1

**Comment by weirdan** [comment]
> This is new bug in version 4.12.0

Hardly. The types in the callmap entry for this function weren't updated since 2018.

Feel free to propose a PR to update callmaps. We have a guide on doing that here: https://psalm.dev/docs/contributing/editing_callmaps/

**Comment by jirkace** [comment]
Ok, sorry - I understood it as a new bug because it appeared after upgrade from 4.11.2 to 4.12.0. :man_shrugging:

**Comment by orklah** [comment]
@weirdan what changed is https://github.com/vimeo/psalm/pull/6758/files who outputs objects since 4.12.0 and lead to the new error in the function called after

**Comment by jirkace** [comment]
whats is wrong? [there](https://github.com/vimeo/psalm/actions/runs/1431009766) something failed, but I don't know why

**Comment by orklah** [comment]
You can ignore that. All PR requires having a label in order to get merged. I added the label for yours but the check was already made so there was an error at one point but it is now solved

**Comment by jirkace** [comment]
@orklah ok, thank you :-)
