### ISSUE TITLE
ReturnTypeWillChange  on PHP 8.0 or earlier

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#6854]
ReturnTypeWillChange  was introduced in PHP 8.1 in order to prevent PHP from emitting deprecated error when it sees return types that are not respected.

This was needed to make sure libraries that need to stay compatible with more than one version of PHP can have a code that doesn't emit deprecation nor errors.

The issue for us is that ReturnTypeWillChange  did not exists in PHP 8.0 so Psalm is reporting it as undefined. While technically true, it's still legit to have this on PHP 8.0 code and it's not an error from user perspective.

Should we make a special case for this and ignore the fact the attribute doesn't exists on PHP 8.0 and earlier?

**Comment by derrabus** [comment]
I think we should.

To take this a step further, I could imagine that later PHP releases introduce more attributes that will fall in the same category: an attribute that should be interpreted by the PHP runtime and that has no effect on PHP versions prior to the version that introduced the attribute.

I think, it is fine to use such an attribute to create a forward-compatible codebase. Psalm should not complain about such an attribute being used. Instead, Psalm could check if the usage of that attribute conforms to the stubbed version of Psalm.

**Comment by orklah** [comment]
Yep, there may be more in the future but no rule can be inferred for now for the others.

For that one, it feels right to makes Psalm understand it exists even on older versions but I don't see what checks could be done when seeing this attribute <8.1 in addition of what Psalm already does by default.

I'll make this change then
