### ISSUE TITLE
Possibility to forbid eval() in code

### ISSUE THREAD

**Issue by thomasbley** [vimeo/psalm#6855]
I'd like to forbid the usage of eval() in the code.

Using "forbiddenFunctions" to forbid "eval()" does not work since it's a language construct, I tried:

```
<psalm>
    <forbiddenFunctions>
        <function name="eval" />
    </forbiddenFunctions>
</psalm>
```

Tested with psalm 4.12.0.

**Comment by orklah** [comment]
@weirdan implemented the same feature for die() and exit() a week ago, you should be able to do the same for eval with a quick glance: https://github.com/vimeo/psalm/pull/6784

**Comment by thomasbley** [comment]
Thanks for the hints, I will create a PR.
