### ISSUE TITLE
array_flip and array_rand

### ISSUE THREAD

**Issue by mj4444ru** [vimeo/psalm#6859]
https://psalm.dev/r/b14406d8ed

How to fix it?

**Comment by orklah** [comment]
array_flip transform your array into `array<array-key, array-key>`, which is correct but not very precise.

For your need, you'd need `array<"~"|"!"|"@"|"#"|":"|"$"|"%"|"^"|"&"|"*"|"?", int>`. This can be done by adding a return type provider here: https://github.com/vimeo/psalm/tree/master/src/Psalm/Internal/Provider/ReturnTypeProvider

**Comment by weirdan** [comment]
I think it would be enough to update the stub like this:

```patch
diff --git a/stubs/CoreGenericFunctions.phpstub b/stubs/CoreGenericFunctions.phpstub
index e8b3026cf..802f7498d 100644
--- a/stubs/CoreGenericFunctions.phpstub
+++ b/stubs/CoreGenericFunctions.phpstub
@@ -123,7 +123,7 @@ function array_diff_assoc(array $array, array ...$arrays)
  *
  * @param array<TKey, TValue> $array
  *
- * @return array<TValue, TKey>
+ * @return ($array is non-empty-array ? non-empty-array<TValue, TKey> : array<TValue, TKey>)
  * @psalm-pure
  */
```

**Comment by orklah** [comment]
Oh, it might indeed
