### ISSUE TITLE
@var for public promoted properties leading to property not found

### ISSUE THREAD

**Issue by iquito** [vimeo/psalm#6860]
In version 4.12.0 of Psalm there are increased levels of problems with constructor property promotion - any `@var` annotations within constructor property promotion for public properties leads to those properties not even existing to Psalm:

https://psalm.dev/r/db3ba03f68

Gives the errors:

```
ERROR: InvalidDocblock - 9:9 - Param string of A::__construct should be documented as a param or a property, not both

ERROR: UndefinedPropertyAssignment - 15:1 - Instance property A::$string is not defined
```

**Comment by orklah** [comment]
Yeah, this is the same issue as https://github.com/vimeo/psalm/issues/6857

I'll fix that

**Comment by iquito** [comment]
Great, thanks!
