### ISSUE TITLE
is_subclass_of fails with string $class

### ISSUE THREAD

**Issue by jnvsor** [vimeo/psalm#6864]
> Argument 2 of is_subclass_of expects class-string, parent type "XYZ" provided

https://psalm.dev/r/770e2fb466

Is this expected behavior? If so is there an option to disable it?

**Comment by orklah** [comment]
This is indeed expected behaviour. A config exists to allow this kind of things https://psalm.dev/docs/running_psalm/configuration/#allowstringtostandinforclass but it only applies to a few cases and this is not one of them.

Why would you want to push strings here instead of class-strings?

**Comment by weirdan** [comment]
If you're operating on strings coming from external source (e.g. database or config file) you can make Psalm treat them as class-strings by checking whether the class exists: https://psalm.dev/r/4f53408906

**Comment by jnvsor** [comment]
> Why would you want to push strings here instead of class-strings?

This codebase has (up until recently) supported _oooold_ versions of PHP that didn't have `::class` constants. I can change that, just wondered if there was an option to support it.

Thanks for the info.
