### ISSUE TITLE
SimpleXMLIterator can be falsey

### ISSUE THREAD

**Issue by jnvsor** [vimeo/psalm#6865]
See also #4814 - #6650 needs some expansion

https://3v4l.org/fk96N

https://psalm.dev/r/40e441d4f2

I've also seen this error from calls to `children()`

**Comment by orklah** [comment]
Indeed, you seem to have identified the code that needs changing. Care to push a PR?

**Comment by jnvsor** [comment]
I've never delved into the psalm code, but I'll see if I can give it a shot this weekend

**Comment by orklah** [comment]
Great! Feel free to ping me if you have questions! This should be pretty straightforward if you look at the PR you linked
