### ISSUE TITLE
__halt_compiler() is treated as an expression

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#6875]
https://psalm.dev/r/e29d657d55

`__halt_compiler()` is not really an expression and should not be part of the `UnevaluatedCode` check.

This regressed somewhere between 4.9.3 and 4.12 (which I'm upgrading to ATM)

**Comment by orklah** [comment]
Thanks for feedback, I didn't know this

Fixing this is just a variation of what I did in https://github.com/vimeo/psalm/pull/6828

Care for a PR?

**Comment by pilif** [comment]
Sure. Thanks for the pointer to where to look. I'll have a PR later today

**Comment by pilif** [comment]
you were right. this was ridiculously easy 😝

**Comment by orklah** [comment]
There's quite a few changes in Psalm where the only hard part is figuring out where to look :p Once it's done, it's usually not too complex!
