### ISSUE TITLE
Disabling autocomplete does not work

### ISSUE THREAD

**Issue by Nadyita** [vimeo/psalm#6879]
`src/Psalm/Internal/Cli/LanguageServer.php` checks for the `$options['enable-autocomplete']` to be a string with the text `'false'`, but it's actually always passed as a bool with value `false`, because it's declared as a long option flag. There is no way for this to accept a value.

The fix would be to declare the argument as having an optional value: `"enable-autocomplete::"`

Currently, no matter what, i cannot disable autocomplete

**Comment by Nadyita** [comment]
Very funny, Mr. bot ;o)

**Comment by orklah** [comment]
Can you propose a PR doing just that? :)

**Comment by Nadyita** [comment]
@orklah There you go :o)
