### ISSUE TITLE
webmozart/path-util is abandoned - use symfony/filesystem instead

### ISSUE THREAD

**Issue by garrettw** [vimeo/psalm#6883]
Just installed the latest version of psalm and was surprised to see an abandoned package warning:

    Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.

https://github.com/vimeo/psalm/blob/8c761dd6d90f115e5a2ffae822c6c7a0e33da60c/composer.json#L38

**Comment by weirdan** [comment]
Not going to happen until we drop PHP 7.1 support, as `symfony/filesystem:5.4` (where `webmozart/path-util` was merged) is not compatible with 7.1. Besides, there were no stable releases in 5.4 branch yet.

**Comment by Dgame** [comment]
> Not going to happen until we drop PHP 7.1 support, as `symfony/filesystem:5.4` (where `webmozart/path-util` was merged) is not compatible with 7.1. Besides, there were no stable releases in 5.4 branch yet.

Do you have any idea when this will happen? PHP 7.1 and 7.2 have already reached EOL in 2019 / 2020.

**Comment by orklah** [comment]
We still have to figure this out for the next major release of Psalm.

Psalm 4 was scheduled to drop 7.1 and 7.2 but after user feedback and seeing we didn't use features from those versions, it was reverted back.

Static analysis is a tough tool to upgrade because user kinda expect to analyse their code with the same version they have in production...

**Comment by weirdan** [comment]
> because user kinda expect to analyse their code with the same version they have in production...

even though Psalm is mostly able to analyze code targeting older PHP runtime even when it runs on a modern one.

**Comment by weirdan** [comment]
> Psalm 4 was scheduled to drop 7.1 and 7.2 but after user feedback and seeing we didn't use features from those versions, it was reverted back.

https://packagist.org/packages/vimeo/psalm/php-stats#4 - currently it's 10% Psalm installations on 7.2 on a bad day.

**Comment by jraller** [comment]
https://github.com/symfony/filesystem/releases/tag/v5.4.0 has a stable release and appears to support `"php": ">=7.2.5",`.

**Comment by ricardoboss** [comment]
Can you reopen the issue until it is fixed? I feel like this shouldn't be closed...

**Comment by weirdan** [comment]
@ricardoboss This is already fixed in master (future Psalm 5): #7292

**Comment by mdeboer** [comment]
I don´t know when Psalm 5 is due to be released but judging by the PR, this could _very_ easily be backported to Psalm 4 right?

**Comment by orklah** [comment]
Unfortunately no, because Psalm 4 support PHP 7.1 and symfony/filesystem does not as explained above
