### ISSUE TITLE
Various problems with mb_convert_encoding

### ISSUE THREAD

**Issue by rarila** [vimeo/psalm#6886]
https://psalm.dev/r/fb4e03dccd

# :heavy_check_mark: Case 1 – ``string`` input

> INFO: Trace - $case1: false|string

Return type ``false|string`` – everthing as expected, ok.

# :x: Case 2 – ``array<int, string>`` input

> INFO: Trace - $case2: array<int, string>

Return type ``array<int, string>`` – don’t know how to force some error to test and didn’t found out by looking at the PHP source code, but I suspect it also returns ``false`` in case of an error so the correct return type would probably be ``false|array<int, string>`` in that case.

# :x: Case 3 – ``array<string, string>`` input

> ERROR: InvalidCast - array{idx: "abc"} cannot be cast to string
> ERROR: InvalidArgument - Argument 1 of mb_convert_encoding expects string, array{idx: "abc"} provided
> INFO: Trace - 21:2 - $case3: false|string

Psalm seems to expect ``string|array<int, string>`` as type for the first function parameter. A short test shows the functions also works with ``array<string, string>`` as input:

```php
var_dump(mb_convert_encoding(['idx1' => 'abc', 'idx2' => 'abc'], 'ASCII'));
var_dump(mb_convert_encoding([123 => 'abc', 456 => 'abc'], 'ASCII'));
```
results in
```
array(2) {'idx1' => string(3) "abc", 'idx2' => string(3) "abc"}
array(2) {[123] => string(3) "abc", [456] => string(3) "abc"}
```
so array indexes won’t be touched by php.

# :x: Case 4 – ``string|array`` input

> INFO: MixedArgumentTypeCoercion - Argument 1 of mb_convert_encoding expects array<int, string>, parent type array<array-key, mixed>|string provided
> INFO: Trace - $case4: array<int, string>

Return type should be something like ``array<array-key, mixed>|string|false`` instead.

**Comment by rarila** [comment]
… just noticed, the first parameter of ``mb_convert_encoding`` should even accept ``string|array<mixed>`` as input, because as the manual says:

> If string is an Array, all its String values will be converted recursively.

```php
var_dump(mb_convert_encoding([
   123 => 'abcäöü',
   'ABC' => 'xyz',
   123, 
   true, 
   false, 
   0, 
   ['abcäöü']
], 'HTML-ENTITIES'));
```
results in:

```
array(7) {
  [123] => string(21) "abc&auml;&ouml;&uuml;"
  'ABC' => string(3) "xyz"
  [124] => int(123)
  [125] => bool(true)
  [126] => bool(false)
  [127] => int(0)
  [128] => array(1) {
    [0] =>
    string(21) "abc&auml;&ouml;&uuml;"
  }
}
```

So you can pass in whatever array you want, only string values get converted.

So in pseudo code (there’s no ``typeof`` operator in Psalm?!) the stub should be something like:

```php
/**
 * @param array<mixed>|string $string
 * ...
 * @return ( typeof $string | false )
 */
mb_convert_encoding function(array|string $string, ...)
```

**Comment by orklah** [comment]
You seem to have a pretty good understanding of this function, mind submitting a PR to fix this?

It's specified in CallMap.php here:
https://github.com/vimeo/psalm/tree/master/dictionaries

Currently we have:
```
'mb_convert_encoding' => ['string|false', 'string'=>'string', 'to_encoding'=>'string', 'from_encoding='=>'mixed'],
'mb_convert_encoding\'1' => ['array<int, string>', 'string'=>'array<int, string>', 'to_encoding'=>'string', 'from_encoding='=>'mixed'],
```

Basically, there are two signatures, one where we receive an string and returning string|false, the second one we expect `array<int, string>` and we return `array<int, string>`

You should be able to make the changes with that :)

**Comment by rarila** [comment]
Hehe, just did some tests with that function :-)

Anyway, thanks for pointing me to the right place to patch.

Seems like an easy patch then:
```
'mb_convert_encoding' => ['string|false', 'string'=>'string', 'to_encoding'=>'string', 'from_encoding='=>'array<string>|string|null'],
'mb_convert_encoding\'1' => ['array<mixed>|false', 'string'=>'array<mixed>', 'to_encoding'=>'string', 'from_encoding='=>'array<string>|string|null'],
```

``'from_encoding='=>'mixed'`` seems to be a bit too broad also, as the manual says ``array|string|null`` for that parameter.

Gonna test my version next week and if it works as expected I'll submit a PR.

**Comment by orklah** [comment]
Great! Thanks! Here's a resource if you need more details on CallMaps: https://psalm.dev/docs/contributing/editing_callmaps/

Don't hesitate to ask for help!

**Comment by rarila** [comment]
FYI and for further reference…

After a deeper look at the [php source](https://github.com/php/php-src/blob/1a4f49f1fe8c7e81ec974f6b51c2cc85f6696b70/ext/mbstring/mbstring.c#L2550-L2567) I came to the conclusion, that ``false`` can only be returned with string input. Reason for that can be "Unable to detect character encoding". I still haven’t found a way to trigger this.

With array input it seems only warnings are issued and the failing conversion is simply skipped, but still the array returned.

Simple test:

```php
$test = [
    'test1_öäü',
    (object) ['obj'], // => Object is not supported
    &$test,           // => Cannot convert recursively referenced values
    'test2_ß',
    '€' => 'test2_€'
];

var_dump(mb_convert_encoding($test, 'HTML'));
```

results in:

>Warning: mb_convert_encoding(): Object is not supported...
>Warning: mb_convert_encoding(): Cannot convert recursively referenced values in ...
>...
>array(4) {
>  [0] => string(24) "test1_&ouml;&auml;&uuml;"
>  [2] => array(0) { }
>  [3] => string(13) "test2_&szlig;"
>  '&euro;' => string(12) "test2_&euro;"
>}

Fun fact: even array keys are converted :-)
