### ISSUE TITLE
UneavaluatedCode issue causes further processing to stop for detecting class usage

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#6887]
https://psalm.dev/r/1f6cbc8ca8

the class `Foo` in the example is detected as used once the erroneous line 5 is fixed.

IMHO further scanning of the file should not stop at that error because this will lead to some very confusing "Unused*" errors.

I noticed this when upgrading from psalm 4.9.3 to 4.12 where the `UnevaluatedCode` inspection got *much better* (especially with regards to methods flagged `no-return`, but now there are countless instances where psalm flags a method as unused making it very hard to systematically fix newly detected issues.

**Comment by orklah** [comment]
Oh, interesting, I didn't know it skipped the rest of the file like that.

Can you try submitting a PR replacing the `return false` after emitting the UnevaluatedCode by a `return null`?

It should tell Psalm to continue analysis but I'm unsure about possible side effects. Ideally, this should still emit UnusedClass: https://psalm.dev/r/96477562e5

**Comment by pilif** [comment]
I'm going to try and make a PR for this. Currently struggling a bit with the test suite because I need it to not blow up in the first issue to check for the second. 

I'll have something today I guess.

**Comment by orklah** [comment]
Not sure what you mean, don't hesitate to push what you have if you're stuck and we'll help from there

**Comment by pilif** [comment]
> Not sure what you mean, don't hesitate to push what you have if you're stuck and we'll help from there

the rest of the UnusedTest tests rely on `throw_exceptions` to either blow up on the first issue or not at all.

But in order to make a test for this, there's always at least one issue (the unevaluated code one).

Unfortunately, if you disable `throw_exception` on the config with otherwise identical code to the existing tests, no issues will be recorded in the `IssueBuffer` because the `$file_path` defined by the other tests is outside of the test project directory.

But no worries. I found a solution and fixed the path for new tests.

Your intuition was right - all all that was needed was returning `null` instead of `false`

**Comment by orklah** [comment]
oh, you could have /** @psalm-suppress */ the first issue, it would have been easier :)

**Comment by pilif** [comment]
I'm not so sure about that: If I suppress the issue, the class is seen as used even without this patch.

**Comment by orklah** [comment]
There may be a reason behind that behavior but I can't see it... great job then :)

**Comment by pilif** [comment]
I have seen in the past that suppressing an issue causes psalm to actually assume the issue to not be there in the first place.

In this case, if the issue was suppressed `IssueBuffer::accepts()` returns false, so then the second `return null ` would be hit
