### ISSUE TITLE
 Support for @internal annotations

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#689]
This is a feature request for inspection which triggers when calling methods / using class marked internal that were not explicitly allowed to use. See following testcase

```php
namespace A;

class A {
  /** 
   * @internal
   */
  public function foo(): void {}
}

namespace B;

class B {
  public function foo(): void {
    $a = new \A\A();
    $a->foo();
  }
}
```

It is already implemented in Phan, where it's called `PhanAccessMethodInternal`

**Comment by muglug** [comment]
presumably this is fine?

```php
namespace A\B;

class Foo {
  /** 
   * @internal
   */
  public function foo(): void {}
}

namespace A\C;

class Bar {
  public function foo(): void {
    $a = new \A\B\Foo();
    $a->foo();
  }
}
```

**Comment by ostrolucky** [comment]
Not sure. Originally I wanted it to just be triggered every time you call such method in any namespace. 
But your post has gave me idea that doing it only when calling methods outside of root "autoload" composer.json directives would be nice touch :+1:

**Comment by muglug** [comment]
I think restricting use of `@internal` to namespace brethren (as above) is *good enough* - from no checks to some checks.

**Comment by muglug** [comment]
Thanks! Should work now.
