### ISSUE TITLE
`ignoreInternalFunctionFalseReturn=false` does not trigger errors for (at least) `base64_decode`

### ISSUE THREAD

**Issue by bendavies** [vimeo/psalm#6893]
Hi,

This example with `ignoreInternalFunctionFalseReturn="false"` does not trigger an error, but it should.
https://psalm.dev/r/d83a11b4b6

`base64_decode` can return false in this instance because `strict=true`

As an aside, the [return type](https://github.com/vimeo/psalm/blob/a2d6861f12a1c044d3e6c028cc9255b1a5f5fafb/stubs/CoreGenericFunctions.phpstub#L1259) is incorrect, and should be conditional base on `strict=true`, but that should not be the source of this issue.

**Comment by orklah** [comment]
Ok, I get what's going on, stubbed function are not impacted by ignoreInternalFunctionFalseReturn, but rather individual `@psalm-ignore-falsable-return` added on the stub.

This shouldn't be the case and we should respect the config

**Comment by orklah** [comment]
@weirdan I'm not sure we can make the difference between our internal stubs, user files and user stubs once they're in queue for scanning.
This means either we'd need slightly change the meaning of `@psalm-ignore-falsable-return` to be conditional on the config flag. This could impact user code and user stubs, and it would mean the config called `ignoreInternalFunctionFalseReturn` would now apply to not-internal functions too.

Is this something we can do? I'd hate to create a new config and new properties everywhere in code to differentiate internal stubs from code

**Comment by weirdan** [comment]
There's a flag called `$register_stub_files` on the `Codebase` instance that is on when stubs are being scanned. It includes user/plugin stubs as far as I can see, but is off when normal files are scanned.
