### ISSUE TITLE
invalid assumption of array key assignment

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#6900]
https://psalm.dev/r/388b75208a

it looks to me like the condition in line 8 is ignored and psalm assumes the assignment in line 9 to always happen.

This was fine in 4.9.3 where I'm upgrading from.

**Comment by pilif** [comment]
according to `git bisect`, this was  broken by dd5c2904d8e4420cfc2f765d30c9549026d5c8f4 in #6518 

I will investigate further.

**Comment by orklah** [comment]
This was not broken on that PR, it was broken before but Psalm got better at reporting what it thought to be always true/always false so when it's wrong, it shows.

There is something wrong in the reconciliation of contexts when we exit an if() I think: https://psalm.dev/r/9de1cfc820

The last trace should not look like that but rather be `array{x?: "b"}`

**Comment by orklah** [comment]
If you want to look at that closer, I'm pretty sure the issue is either in IfConditionalAnalyzer or IfElseAnalyzer. Be warned though, it's pretty complex

**Comment by pilif** [comment]
I'm really hitting a wall here. I do see how the `if_context` is correctly tracking the assignment via `possibly_assigned_var_ids` rather than `assigned_var_ids`, so that's what I expect. 

However, in the `handleParadoxicalCondition()` method of `IfConditionalAnalyzer`, the `$statements_analyzer->node_data->getType($stmt);` call will contain the erroneous type.

I could track the corresponding `setType()` down and it's always called for each assignment, so that's also not necessarily wrong.

I'm a bit lost in the execution flow to see where psalm is taking these `possibly_assigned_var_ids` into consideration compared to the `assigned_var_ids`.

**Comment by orklah** [comment]
Yeah, I already try to take some time  untangling what's going on here with no success so far.

Just to explain: Contexts vars are objects passed along the analysis that represent what's going on for a specific scope. Say `$a` is changed in an if(), the context used will have this variable in `$assigned_var_ids` or `$possibly_assigned_var_ids` if not all branches inside the scope contains the assignation

`$statements_analyzer->node_data->getType($stmt);` is the way Psalm fetch a type for a specific statement (as parsed by PHP-Parser)

That means at one point, Psalm calculated an erroneous type and put it in storage for `$stmt`. 

I think the error must come from a place like this one: https://github.com/vimeo/psalm/blob/b29737f2b154748430250effdbcf47de8a5904df/src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php#L312

Where we have two (or more?) contexts and we try to reconcile the global context with what happened inside a subcontext

**Comment by pilif** [comment]
oh - that pointer was very helpful.

now I can narrow down to where things are going wrong which is here:

https://github.com/vimeo/psalm/blob/53e4719c1903a0c612d637567931ef6fab29ea35/src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php#L443-L445

this is where `$a['x']` gets seen as redefined with with a type that has `possibly_undefined = false`

Now I need to figure out whether that assignment is wrong and the re-assgined `$type` should still be `possibly_undefined` or whether the whole if is wrong and the type should only be merged later when psalm is dealing with `possibly_redefined_vars`.

Do you know that perchance?

**Comment by pilif** [comment]
ooh - narrowing this down some more:

this is where the issue happens: getRedefinedVariables() returns the `$a['x']` variable with possibly_undefined = false, even though that's clearly not correct.

https://github.com/vimeo/psalm/blob/ae1afd90c64d54a1887305e493130545be6b19a3/src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php#L457

**Comment by pilif** [comment]
I have to give up on this - between the deep nesting of function calls and the mutation going on, I'm really unable to get to the bottom of this.

However, I have noticed one thing: Given the existence of 4 if clauses, I would expect `IfElseAnalyzer::analyze()` to be called 4 times, but it's only called 3 times.

However, when I change the `!isset()` to `empty()` in the snippet (https://psalm.dev/r/969bd53032), then the incorrect issue goes away *and* `IfElseAnalyzer::analyze()` is called 4 times, so there must be some short-circuit going on somewhere.

Also, as `IssetAnalyzer` and `EmptyAnalyzer` are pretty much identical in what they are actually doing and one works whereas the other doesn't, this boils down the source of the issue to the handling of the condition in the `if`. 

But really, I cannot spend more time on this as whatever I'm doing, I'm turning in circles with stuff looking ok and then still being wrong in the end 😢

**Comment by orklah** [comment]
No worries, as I said, this is a tough piece of code.

FYI, EmptyAnalyzer and IssetAnalyzer are not the only pieces of code triggered when using empty() or isset(). The assertion module is triggered too, and isset() and empty() are two different assertions that are resolved their own ways.

**Comment by pilif** [comment]
thanks for that additional info.

I also *just* got one more thing: the erroneous `redefined_vars` in the `!isset()` case is removed in the `empty()` case by the `ElseAnalyzer` of all things (which I never thought of even looking at given there's no else involved)

**Comment by pilif** [comment]
last update from me as I'm just getting more confused, but in this update:

https://github.com/vimeo/psalm/blob/ae1afd90c64d54a1887305e493130545be6b19a3/src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php#L216-L222

in the case of the `!isset()` statement, the type of `$a['x']` in `$old_if_context` is Union of TEmpty (which makes sense because we just proven that it's not set), whereas in the empty() case, it retains its `TLiteralString`, but now with `possibly_undefined = true`.

Something must be making the wrong conclusions of that TEmpty (even when I hack `possibly_undefined` of that type to be true, the behavior doesn't change).

But really, this is as far as I could go. I'm hitting a wall here 🥴

**Comment by orklah** [comment]
I'll try to take a look at this in a few days. It's interesting that it works with empty, that may bring some insight

**Comment by pilif** [comment]
I found a few hours to look into this some more and I have found the first thing that makes me stop and suspect I might finally have found where things are going wrong.

While analysing line 7 of the snippet (thats the `!isset()` check), `IfAnalyzer::updateIfScope` will unconditionally redefine $a from `array{x?: "y"}` to `array{x: "y"}` which I think is where things go wrong. Why would the `!isset()` check redefine the `x` member to be defined? If this were `isset()`, then, yes, surely, that's the correct assumption. But !isset should IMHO not change the variable's definition (or in this case even reset it to `empty`).

Am I on the right track here?

**Comment by pilif** [comment]
that call to `IfAnalyzer::updateIfScope()` comes from `ElseAnalyzer` which, seeing that there is a negated_clause (line 36) doesn't return early but analyzes the (non-existing) `else` part, calling `Algebra::getTruthsFromFormula()` and then reasonably getting back `else_types`.

that looks fine to me as if there were an else, $a[x] would indeed be defined.

But there is no `else` and thus I don't understand why the if scope is updated with any of this. Maybe you can enlighten me on why the outer (and in this case global) scope is being with the state a non-existing `else` would have.

Or maybe I'm overlooking something yet again.

**Comment by orklah** [comment]
> that looks fine to me as if there were an else, $a[x] would indeed be defined.

Not if the else had no statements. For example:
https://psalm.dev/r/43050d5ec7

This change nothing to the issue. That means, Psalm is not completely wrong to consider that a call to ElseAnalyzer can make sense as long as you do the same thing as if it were empty.

I guess it was made to simplify the code by having the same path between an empty else and no else at all.

**Comment by orklah** [comment]
Not sure it's relevant, but on ElseAnalyzer on line 53, you get only one element in `$else_context->clauses` for `empty` but you get two for `!isset`...

**Comment by pilif** [comment]
mmmh - at line 53, I get the same amount of clauses in both the `!isset` and the `empty` case, however, on line 86, in the !isset case, the `$a['x'] => "!isset"` clause is removed, but `*352:360 => falsy` is kept whereas in the empty() case, both clauses remain.

https://github.com/vimeo/psalm/blob/6abce3525ac34f815aaa3b7953739b744ca5c39e/src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseAnalyzer.php#L86

Seeing that we're analysing an `else` branch (for a non-existing `else` in the source code no less), I would actually intuitively think that the `empty()` case is actually incorrect (we're in an else of `if(empty())`, so how can `$a['x']` still be `empty`?) which makes fixing this even harder, unless I'm misunderstanding something.

**Comment by orklah** [comment]
I don't think it's the issue, the two clauses are `empty` and `falsy`, and in the isset cases, they are `!isset` and `falsy`. Everything seems coherent.

However, I found something interesting. In line 86 you showed above, in the `!isset` case, the `!isset` clause actually disappears after calling removeReconciledClauses, but in the empty case, the `empty` clause doesn't disappear.

It has to do with $changed_var_ids being an empty array in the `empty` case, whereas it has `$a['x']` in the `!isset` case

**Comment by weirdan** [comment]
Looks like it's fixed already: https://psalm.dev/r/388b75208a
