### ISSUE TITLE
E_USER_ERROR is not necessarily a fatal error

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#6907]
https://psalm.dev/r/c379018ea4

depending on the use of error handler, E_USER_ERROR is not a fatal error.

Is there a way to configure psalm to be aware of this? (so it won't report an unevaluated code error here)

**Comment by orklah** [comment]
Yeah, check this link: https://psalm.dev/docs/running_psalm/configuration/#triggererrorexits

You can set to default, always or never.
