### ISSUE TITLE
preg_match stub/callmap

### ISSUE THREAD

**Issue by rarila** [vimeo/psalm#6914]
I'm about to prepare a PR for ``preg_match`` and I guess I need some help/advice.

First problem, I have a stub like this (simplified here):

```
/**
 * @template TFlags as int-mask<0, 256, 512>
 * @param TFlags $flags
 * @param-out (TFlags is 256 ? 'M256' :
 *            (TFlags is 512 ? 'M512' :
 *            (TFlags is 768 ? 'M768' :
 *                             'M0'    ))) $matches
 */
```

Executing

```php
preg_match('//', '', $m256, 256);
/** @psalm-trace $m256 */;
```

gets me

> $m256: (TFlags:fn-preg_match is 256|257 ? "M256" : (TFlags:fn-preg_match is 512 ? "M512" : (TFlags:fn-preg_match is 768 ? "M768" : "M0")))

instead of expected

> $m256: "M256"

Works with the other stubs like ``preg_match_all`` – so what I`m doing wrong here?

**Comment by orklah** [comment]
Can you post that in psalm.dev please? I'm not sure your error matches your stub (the `256|257` match preg_match_all, but not the stub you posted)

**Comment by rarila** [comment]
Sorry for the ``256|257``, that was just a mistake copying from another try. Shoild be ``256``.

Ok, normally that that would be in CoreGenericFunctions.phpstub, but I made something analogous in psalm.dev:

https://psalm.dev/r/848d76d405

**Comment by orklah** [comment]
mmh, weird, I get the same effect with preg_match_all as soon as the stubs doesn't come from internal files:
https://psalm.dev/r/a2da224c7e

Seems like @param-out with conditionals works only for internal stubs

**Comment by rarila** [comment]
But I had added my version to CoreGenericFunctions.phpstub and still got this wierd result.

**Comment by orklah** [comment]
Maybe check in ArgumentsAnalyzer, there's a special case for preg_match_all when a flag is provided that could explain why it seems to work only with a function with that name. Try adding preg_match to it

**Comment by rarila** [comment]
I saw that too and wondered what happens there.

The source could benefit from a comment here and there :innocent:

**Comment by orklah** [comment]
Agree :)

I think it's related to the param-out and flag. Given that the flag is needed to process the conditional, Psalm reverses the array in order to process it first, before reaching the matches.

Honestly, I didn't even know you could add conditional in a @param-out, and I think that's precisely the reason. It will only work if the flag is positionned before the argument that has the conditional (except when handled like that)

**Comment by rarila** [comment]
That could be an explanation. Gonna try then…

**Comment by rarila** [comment]
You’re right: https://psalm.dev/r/e4d61c214f

But then its bad if that's hardcoded in the analyser. Then you can't use it in your code or some other library stubs.

**Comment by orklah** [comment]
Yeah,  There may be a way to check if an arg has a @param-out and arrange the order to process it last

In the other hand, I have no objections to keeping conditionals in @param-out an internal thing only either

**Comment by rarila** [comment]
Still could be usefull for writing stub files for some libraries.

Ok, for passing variables per reference isn`t good design anyway and Psalm makes it finally possible to reliable return something like ``array{result: bool, matches?:} array}`` instead but I`m sure there`s enough code out there that uses return per reference.

preg_match would be better returning null for no match, array for matches and throwing in case of error… but hey, that's how PHP works :cry:

Ok, enough rant, I'll add another exception in ArgumentsAnalyzer and we can think about a better solution later…

**Comment by rarila** [comment]
Probably simple solution: two pass.
In pseudo code:

```php
foreach ([1, 2] as $pass) {
    foreach ($args as $arg) {
        if ($pass === 1 && $arg->isPassedByReference() ||
            $pass === 2 && !$arg->isPassedByReference()
        ) {
            continue;
        }

        ...
    }
}
```

**Comment by orklah** [comment]
The issue is not really the reference, it's more the conditional in param-out I believe.

And I feel like it'd be more easy to do a uasort and just push those to the end of the array for clarity of code

**Comment by rarila** [comment]
Ok, back to the topic…

Say we run

```php
$matches = 'whatever';
preg_match('/(/', 'foobar', $matches);
var_dump($matches);
```
we get
> Warning: preg_match(): Compilation failed: missing closing parenthesis at offset 1 in ...
> string(8) "whatever"

So in case of error the variable isn’t changed at all.

_(Desirable behavior of PHP would be to throw on error or at least set ``$matches`` to ``null`` – but that would be an ideal world and does not lie in our hands)_

So correct would be

```php
/**
 * @param-out (mixed) $matches
 */
```

But that doesn’t help anyone. I think the following (pseudo code) isn’t possible:

```php
/**
 * @psalm-out (return is false ? TypeOf<$matches> :
 *             TFlags is 256   ? ... ) $matches
 */
```

So I think we have to model the non failing cases and hope everybody handles the failing ones.

**Comment by orklah** [comment]
I have absolutely no issue discarding the case with an error. I hope people check the result of the function before trying to use the result in $matches.

If we do want to handle that though, it should be possible using a "Core Plugin" implementing AfterFunctionLikeAnalysisInterface in order to change the reference value in any way we like
