### ISSUE TITLE
String keys are not supported in unpacked arrays - for partial application

### ISSUE THREAD

**Issue by alincota** [vimeo/psalm#6915]
I have a partial application function that is throwing these errors:

`ERROR: DuplicateArrayKey - src/general.php:39:40 - String keys are not supported in unpacked arrays (see https://psalm.dev/151)
    return fn(...$args2) => $fn(...[...$args1, ...$args2]);

ERROR: DuplicateArrayKey - src/general.php:39:51 - String keys are not supported in unpacked arrays (see https://psalm.dev/151)
    return fn(...$args2) => $fn(...[...$args1, ...$args2]);`

If I use @no-named-arguments for the main function, it removes the first error but I can't seem to make it get rid of the second one.
Is there any way I could configure psalm to ignore this particular function?

**Comment by orklah** [comment]
Please try to replicate on psalm.dev. We can't help with no context

**Comment by alincota** [comment]
Unfortunately I couldn't replicate on psalm.dev, I was getting a different error there.

I can provide the full function (with docblock), psalm config and php version if that helps.

**Comment by weirdan** [comment]
Could you reproduce in a separate repo instead? Just to make sure there are no unaccounted external factors at play.

**Comment by alincota** [comment]
I've been able to reproduce it in a separate repo - [.](https://github.com/alincota/psalm_issue_6915) It's a bare bone repo but has the same errors showing.
I hope this helps.
In case it's required, this environment is running PHP 7.4.3 (cli) (built: Oct 25 2021 18:20:54)

**Comment by orklah** [comment]
Reproduced with https://psalm.dev/r/ff419ad820?php=7.4

Psalm.dev now runs on 8.1 by default where this errors is now supported in core, that's why you couldn't reproduce

**Comment by orklah** [comment]
This can be fixed like this: https://psalm.dev/r/048d2b211c

This is due to $args1 and $args2 being potentially string keyed arrays, and PHP did not support that. For example: https://3v4l.org/tXIqL#v8.0.13

`@no-named-argument` allows Psalm to check that named argument were not used in this context and that no string offset can appear.
