### ISSUE TITLE
Uncaught UnexpectedValueException: Shouldn't get here

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#692]
When analyzing https://github.com/thephpleague/csv/blob/master/src/Reader.php#L32

**Comment by weirdan** [comment]
Another example: https://github.com/guzzle/guzzle/blob/master/src/Client.php#L12

**Comment by weirdan** [comment]
It appears psalm expects `@method` annotation to contain something resembling syntactically valid PHP code, but it's not the way people use it. 

1. It appears union types are not invalid in the `@method` annotation according to phpdoc manual
2. Description (arbitrary text after the method signature) is certainly valid

**Comment by muglug** [comment]
Not throwing exceptions now, and Psalm now strips text after methods.

`@method foo(int|string $bar)` will result in `InvalidDocblock` for now - though I may change that later.
