### ISSUE TITLE
Parser fails on type alias of callable with generic array parameter

### ISSUE THREAD

**Issue by spawnia** [vimeo/psalm#6928]
Hi 👋 

I found that Psalm fails to parse a very specific combination: a type alias that is a callable with a parameter that is a generic array.

```php
@psalm-type TypedArrayHandler callable(array<string>): void
```

https://psalm.dev/r/2a189c7ff9

**Comment by orklah** [comment]
Indeed. You can use this workaround it seems: https://psalm.dev/r/d05cba9b24

**Comment by spawnia** [comment]
Thanks for the feedback. This problem was triggered through a dependency, so I can not change their code.

Is there anything I can do to help with getting this fixed?

**Comment by orklah** [comment]
I have very little experience with Psalm's Parser, but if you want to get your hand in it, the error comes from here: https://github.com/vimeo/psalm/blob/b29737f2b154748430250effdbcf47de8a5904df/src/Psalm/Internal/Type/ParseTreeCreator.php#L143

The parser is trying to create a tree of tokens and it seems it didn't expect what it got. I guess the first step would be to check how it's doing that, what exactly makes it emitting this issue and adapt code until it doesn't :)

**Comment by spawnia** [comment]
Here is a PR with a failing test case: https://github.com/vimeo/psalm/pull/6929

I think the parser is probably fine, `ClassLikeNodeScanner::getTypeAliasesFromComment()` appears to be the culprit. The code in there seems quite complicated, lots of `preg_replace` and the likes going on.

**Comment by MidnightDesign** [comment]
Here's another workaround. Put the generic parameter in a separate type:

Before:
```
/**
 * @psalm-type Resolve callable(string, list<TypeInterface>): TypeInterface
 */
```
After:
```
/**
 * @psalm-type ListOfTypes list<TypeInterface>
 * @psalm-type Resolve callable(string, ListOfTypes): TypeInterface
 */
```

**Comment by ramsey** [comment]
I've encountered this same issue:

https://psalm.dev/r/0f1355a445

I'm able to use the work-around.

**Comment by weirdan** [comment]
No longer reproducible:

* https://psalm.dev/r/0f1355a445
* https://psalm.dev/r/2a189c7ff9
