### ISSUE TITLE
Psalm removes "unused" variables that are used through reference assignment

### ISSUE THREAD

**Issue by kamil-tekiela** [vimeo/psalm#6943]
https://psalm.dev/r/2ee16efe41

The code works https://3v4l.org/R0PRb and it should produce output:

> This be the value

However, Psalm removes the assignment which breaks the code. https://3v4l.org/Kr1u3

**Comment by orklah** [comment]
Oh, turns out this issue is also a duplicate. We already have this problem described here: #6108
