### ISSUE TITLE
Callable with PHPDoc block has unexpected error.

### ISSUE THREAD

**Issue by niconoe-** [vimeo/psalm#6944]
Hi !

When adding doc block to my methods returning callable or Closure, I encountered an unexpected error of parsing that doc block.

https://psalm.dev/r/7e6d62d70d

From what I have tested, this is due to the combination of both using intersection type and variable name in parameter.

For instance, there's no error when I remove the parameter name: https://psalm.dev/r/e8594f08e6  
Also, there's no error when I am dealing with a single type: https://psalm.dev/r/bf4bd51574

Having the parameter name in my doc-block is important to me, as I find it helps a lot in readability.

I don't want to try with a `psalm-type` annotation or something that could merge my intersection type into a generic or an alias, as I am also using PHPStan and I don't want to mix with specificities of both tools.

Using Psalm 4.12.0, on PHP 8.1.0RC6 (but also occurs on PHP 8.0.x).

Thanks a lot!

**Comment by orklah** [comment]
Very similar to https://github.com/vimeo/psalm/issues/4867#issuecomment-748439393

Psalm does not understand complex types in a callable when the variable is named

**Comment by weirdan** [comment]
No longer reproducible: https://psalm.dev/r/7e6d62d70d
