### ISSUE TITLE
Missing key-value for stream_get_meta_data function

### ISSUE THREAD

**Issue by mallardduck** [vimeo/psalm#6947]
When [`stream_get_meta_data`](https://www.php.net/manual/en/function.stream-get-meta-data.php) is passed an SSL stream it will also have a `crypto` key on it.
The shape in that case should look like this:
```
array(8) {
  'crypto' =>
  array(4) {
    'protocol' =>
    string(7) "TLSv1.2"
    'cipher_name' =>
    string(29) "ECDHE-ECDSA-AES256-GCM-SHA384"
    'cipher_bits' =>
    int(256)
    'cipher_version' =>
    string(7) "TLSv1.2"
  }
  'timed_out' =>
  bool(false)
  'blocked' =>
  bool(true)
  'eof' =>
  bool(false)
  'stream_type' =>
  string(14) "tcp_socket/ssl"
  'mode' =>
  string(2) "r+"
  'unread_bytes' =>
  int(0)
  'seekable' =>
  bool(false)
}
```

For reproduction see here: https://psalm.dev/r/9c3df127fc

EDIT: To my surprise I also do not see this documented in PHP docs. However it is included in the stubs used by Phpstorm.

**Comment by mallardduck** [comment]
Here is the commit to [php-src](https://github.com/php/php-src) that added this information to the results: https://github.com/php/php-src/commit/676a5059b215c2d725ed219d4258d8221759ee0c

**Comment by weirdan** [comment]
If you want to try your hand at it feel free to submit a PR to fix that. See https://psalm.dev/docs/contributing/editing_callmaps/ for some hints on editing callmaps.

**Comment by mallardduck** [comment]
@weirdan - thanks for that link and point in the right direction. From what I can see it should be PHP 7.0 and forward. I'll def give editing the callmaps a shot this weekend.
