### ISSUE TITLE
`psalm-assert-if-true` not working on objects

### ISSUE THREAD

**Issue by mariosimao** [vimeo/psalm#6948]
I do not know when it stoped working, but `pslam-assert-if-true` is not working properly on objects.

Take the [documentation](https://psalm.dev/docs/annotating_code/adding_assertions/#asserting-return-values-of-methods) as example:

https://psalm.dev/r/66ce8ba63c

**Comment by orklah** [comment]
documentation also says: 
> Please note that the example above only works if you enable method call memoization in the config file or annotate the class as immutable.

And indeed, enabling the config makes it work like a charm :) 
https://psalm.dev/r/3cbab84b31

**Comment by mariosimao** [comment]
Sorry, I did not read the rest of the documentation. It is working properly. Thanks, @orklah
