### ISSUE TITLE
Is the phpparser cache safe for migrating from phpparser 3 to 4?

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#695]
E.g. would the file name for the cache entry be the same but contain a mix of PhpParsser\Node from PHPParser 3 and 4? I don't see how the cache file name depends on the php parser version in any way, but may have missed something

While investigating, I noticed that there seems to be some dead code in the 2.0.0-dev release

`$lexer = version_compare(PHP_VERSION, '7.0.0dev', '>=')` would always be true in StatementsProvider.php, now that php 5 support is dropped (in statementsProvider

**Comment by muglug** [comment]
> I don't see how the cache file name depends on the php parser version in any way, but may have missed something

I thought they would have been via a flag I had added; but I see that was stripped somewhere along the way - will add that now.

**Comment by weirdan** [comment]
Yeah, I've seen crashes after upgrade. Nothing a quick `--clear-cache` couldn't fix though.
