### ISSUE TITLE
Errors thrown on using arrow function as callable

### ISSUE THREAD

**Issue by pamtbaau** [vimeo/psalm#6950]
Psalm throws the following errors:
> ERROR: ParseError - classes/FormUtils.php:73:49 - Syntax error, unexpected T_DOUBLE_ARROW, expecting ')' on line 73 (see https://psalm.dev/173)
        $container['comment'] = $container->factory(fn () => new Comment());

> ERROR: ParseError - classes/FormUtils.php:73:65 - Syntax error, unexpected ')' on line 73 (see https://psalm.dev/173)
        $container['comment'] = $container->factory(fn () => new Comment()); 

On the following codeline:
```
$container['comment'] = $container->factory(fn () => new Comment());
```

Whereby factory is defined as: See [Pimple Container lines 162-180](https://github.com/silexphp/Pimple/blob/69bba50d1600342deae9dca3372a2b5f1ac32ae6/src/Pimple/Container.php#L162-L180)
> public function factory($callable) { }
@param callable $callable — A service definition to be used as a factory
@return callable — The passed callable
@throws ExpectedInvokableException
Service definition has to be a closure or an invokable object

Psalm excepts the following refactored line:
```
$container['comment'] = $container->factory(function () {
    return new Comment();
});
```

From the PHP docs on [callable](https://www.php.net/manual/en/language.types.callable.php#language.types.callable.passing):
> Apart from common user-defined function, anonymous functions and arrow functions can also be passed to a callback parameter.

Would you mind explaining what I'm overlooking here?

**Comment by orklah** [comment]
you're probably running Psalm with a version of PHP that does not include arrow functions.

This is usually the result of running Psalm on a codebase that allows a php version (in composer.json) that is older than the syntax you're trying to use.

Please make sure your composer.json is up to date. In any case, you can manually set the php version you want to use with --php-version=X.Y

**Comment by pamtbaau** [comment]
You're right, that's it! 

My `composer.json` sets' a minimum of 7.3.6 A case of blind copy/paste from other library...

Psalm is even more clever then I thought...

By the way, many thanks to the Psalm team (and collaborators) for creating this tool.
