### ISSUE TITLE
@var on promoted properties not enforced/recognized

### ISSUE THREAD

**Issue by iquito** [vimeo/psalm#6951]
Psalm 4.13.0 solved many of the promoted properties problems recently, thanks! What is still missing is that Psalm recognizes and uses `@var` information on promoted properties:

https://psalm.dev/r/c3adfd753c

Expected would be that Psalm complains about the wrong type for `new A` and setting `$a->licenseType`, as only "cti", "basic", "teams" and "" are allowed according to the `@var`. When using that property more errors propagate through the codebase (`ArgumentTypeCoercion` when using that property where only these limited values are allowed, for example).

**Comment by orklah** [comment]
Seems like the signature type for param takes precedence on docblock type for property instead of overriding it:
https://psalm.dev/r/cee4baaedb

This should not be a complex fix if you want to try to fix that :)
