### ISSUE TITLE
Broken assertion

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#6958]
https://psalm.dev/r/1f61a568e0

**Comment by orklah** [comment]
This works:
https://psalm.dev/r/a6fdb1b02c

Combining assertions is hard, especially when they don't makes sense...

I'm not sure it would be worth it to fix that.

Note: I think Psalm translate a single variable in a condition into an `!empty` assertion. It's interesting to see PHPStan has the same issue when using !empty: https://phpstan.org/r/4a2936bb-10ec-42d7-a7d9-afc693e675eb

**Comment by weirdan** [comment]
Looks like it has been fixed: https://psalm.dev/r/677699aadb
