### ISSUE TITLE
PHP_INT_MAX isn't positive-int, but int

### ISSUE THREAD

**Issue by kelunik** [vimeo/psalm#6968]
https://psalm.dev/r/6c3860181f

**Comment by kelunik** [comment]
See https://github.com/vimeo/psalm/blob/6f1d43813f0586b931cdea32a5a7733980dc8f51/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ConstFetchAnalyzer.php#L167-L173.

**Comment by orklah** [comment]
Good catch. Care to provide a PR?

(I'm really curious about the use case if this is a legit piece of code :D)

**Comment by kkmuffme** [comment]
>(I'm really curious about the use case if this is a legit piece of code :D)

It's probably not, but (u)sleep is the most convenient function to reproduce psalm false positives with positive-int/int type, see https://github.com/vimeo/psalm/issues/6966 :)

**Comment by kelunik** [comment]
It's a legit piece of code, yeah: https://github.com/revoltphp/event-loop/commit/dc9fbe7102ba80aafff970e4940e43dd18921b7e

**Comment by ricardoboss** [comment]
I opened a PR that may fix this: #7070
