### ISSUE TITLE
Weird TypeDoesNotContainType

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#6969]
https://psalm.dev/r/1958a1aa02

error in line 17 - no idea how psalm thinks this is int<3, max> ?

- when I remove code line 13-15 the error is suddenly gone
- or: when I remove the elseif in line 10/11 we suddenly have int<2, max>
- or: when I remove the if in line 8/9 and the elseif in line 10/11 the error is suddenly gone too

**Comment by orklah** [comment]
Yeah, that's pretty weird.
Reduced to: https://psalm.dev/r/7127934c57

The `A` has nothing to do here

**Comment by orklah** [comment]
ooh wait, I think I get it.

Psalm use `empty` as a value from some key to literally say the key can't be defined here.

However, when using count, we use the number of properties, without checking the type in there.

`empty` and `never` should be excluded when trying to count the number of elements in a keyed array
