### ISSUE TITLE
Use positive-int|0 for sleep() argument

### ISSUE THREAD

**Issue by evannoronha** [vimeo/psalm#6978]
## Problem

php-src says `$seconds` cannot be < 0. https://github.com/php/php-src/blob/ef5558a8cda5a8c62e8de7694202ac669d74f1b3/ext/standard/basic_functions.c#L1216-L1230

```php
PHP_FUNCTION(sleep)
{
	zend_long num;

	ZEND_PARSE_PARAMETERS_START(1, 1)
		Z_PARAM_LONG(num)
	ZEND_PARSE_PARAMETERS_END();

	if (num < 0) {
		zend_argument_value_error(1, "must be greater than or equal to 0");
		RETURN_THROWS();
	}

	RETURN_LONG(php_sleep((unsigned int)num));
}
```

As does the php docs: https://www.php.net/manual/en/function.sleep.php#refsect1-function.sleep-errors

> If the specified number of seconds is negative, this function will generate a E_WARNING.

sleep(0) has long been a way of coaxing PHP to yield to the OS.

In  #6861, we modified the call map to specify that `sleep()` should only take a `positive-int`

## Do This

Modify the call map to allow the `$seconds` argument passed to `sleep()` to be `positive-int|0`.

**Comment by evannoronha** [comment]
https://psalm.dev/r/54897797d8

Seems like https://psalm.dev is running 4.12.0?

**Comment by orklah** [comment]
No, it's running the future 4.14.0 where this is already changed ;)
https://github.com/vimeo/psalm/pull/6955

I'll close this as solved!
