### ISSUE TITLE
Enums cases as attribute params

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6982]
Enums in attributes are not properly detected for their types https://psalm.dev/r/3615c731dc?php=8.1 (simplified)

_Originally posted by @jpresutti in https://github.com/vimeo/psalm/issues/6425#issuecomment-977229637_

**Comment by weirdan** [comment]
Fixed in #6984

**Comment by jpresutti** [comment]
Thank you for the super quick turnaround on this!

**Comment by weirdan** [comment]
I think I've seen @muglug fixing some issues within 15 minutes of them being reported, so we still have some room for improvement :laughing:

**Comment by jpresutti** [comment]
> I think I've seen @muglug fixing some issues within 15 minutes of them being reported, so we still have some room for improvement 😆

Either way, @weirdan this was gonna potentially block me from releasing the next version of my framework tomorrow, due to my strict Psalm rule for errorLevel 1 clean with 100% type inference (except in VERY limited cases for psalm-suppress) so this makes me happy.
