### ISSUE TITLE
array_values on a `list` isn't marked as a paradox

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#6988]
https://psalm.dev/r/24ce4a0009

**Comment by orklah** [comment]
That should be pretty easy to add, we actually do exactly that for strtolower:
https://github.com/vimeo/psalm/blob/64df00baba61af63af4cf42ab1489cc43a959974/src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php#L367
