### ISSUE TITLE
Self-referencing object falsely tagged as unused

### ISSUE THREAD

**Issue by arudolph-cxt** [vimeo/psalm#6990]
https://psalm.dev/r/4aa37163e9

thats how we currently resolve promises, psalm has issues with it and we're unable to use @psalm-suppress to get rid of the individual warnings

**Comment by orklah** [comment]
Thanks for the feedback!

We actually have another issue describing this problem: https://github.com/vimeo/psalm/issues/6943 so I'll close this one as a duplicate
