### ISSUE TITLE
Question: why psalm detects more issues on 2+ run?

### ISSUE THREAD

**Issue by lptn** [vimeo/psalm#6999]
that makes difficult to run psalm locally: it often detects more errors than on CI. If I suppress these errors (most of them are false-positives), psalm on CI reports about unused suppressions (we use `findUnusedPsalmSuppress`).

I tried to clear local cache (` --clear-global-cache --clear-cache`), but it didn't help - locally psalm still detects more issues.

**Comment by orklah** [comment]
Please try to reproduce the false positives.

Also, make sure your CI environment is the same as your dev environment, it could explain the differences.

**Comment by danog** [comment]
Probably due to a different number of threads, psalm will report false positives/not report some issues if threading is enabled, run with `--threads=1` to fix.

**Comment by lptn** [comment]
thanks guys, I've solve the problem by fixing all false-positives (it was tricky on a big Laravel project). Still don't know why it happened, but we can reopen the issue when have more input.


>Probably due to a different number of threads on the CI machine vs locally, psalm will report false positives/not report some issues if threading is enabled, try running with --threads=1.

that's correct, on CI we use 2 threads (GitHub actions), locally we use only one
