### ISSUE TITLE
[?] Possibly unexpected merge of alternative union branches in `@return` annotation 

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#704]
https://getpsalm.org/r/e0eda65d16
```php
<?php
  /**
   * @return array{0:true,1:null}|array{0:false,1:string}
   */
  function f(): array {
     return [true, "asd"];
  }
```
Shouldn't Psalm complain here since none of the union branches accept `array{0:true,1:string}`? Currently this return annotation is interpreted as `array{0:bool, 1:null|string}`

**Comment by muglug** [comment]
This is definitely by design. If you want that sort of behaviour, you need to use classes instead.
