### ISSUE TITLE
[TAINT] report invalid `psalm-taint-sink`

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#7046]
would be great, psalm would error when using `psalm-taint-sink` without providing the param name.

this should error

```php
/**
 * @psalm-taint-sink sql
 */
fuction query($query) {
}
```

because it is missing the `$query`:

done right it would be:
```php
/**
 * @psalm-taint-sink sql $query
 */
fuction query($query) {
}
```

I feel from a DX perspective it should be handled  similar to forgetting the parameter reference in a `@param`

**Comment by orklah** [comment]
That should be easy to change here:
https://github.com/vimeo/psalm/blob/a2d6861f12a1c044d3e6c028cc9255b1a5f5fafb/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php#L210

You should be able to throw a IncorrectDocblockException here to make sure this case doesn't happen

**Comment by staabm** [comment]
Will send a PR tomorrow

**Comment by weirdan** [comment]
> Will send a PR tomorrow

@staabm It must have been lost somewhere; feel free to resend :grin:

**Comment by staabm** [comment]
thanks for the reminder

;-)
