### ISSUE TITLE
`--find-unused-psaml-suppress` false positive

### ISSUE THREAD

**Issue by RSickenberg** [vimeo/psalm#7048]
Hello, I recently got a false positive on a psalm suppress inexistent.
![image](https://user-images.githubusercontent.com/16922548/144449698-111a4fe0-c0b3-4138-9f27-2e6bc66cebf1.png)

Regards

**Comment by RSickenberg** [comment]
No

**Comment by weirdan** [comment]
Sorry, we would have to get more information to troubleshoot that. Please provide a minimal reproducer.

**Comment by orklah** [comment]
Teah a repro is needed.

Sharing my thoughts in the meantime:

I'd bet the issue with the Psalm suppress is the same that shifted the coloration, Psalm registers the suppression with a position offset in the file so there is probably a common reason for both issue.

Are you sure you didn't change the file during the analysis?

**Comment by RSickenberg** [comment]
@orklah Yeah, pretty sure in fact. 

@weirdan I tested on psalm.dev and I'm not sure if it reports the `find-unused-psalm-suppress` or not, but I can provide a snippet if needed and if it can help you :)

**Comment by orklah** [comment]
Yes, please do!

**Comment by RSickenberg** [comment]
@orklah @weirdan https://gist.github.com/RSickenberg/449f6f81abab80fae429b0e58881f529

**Comment by orklah** [comment]
Thanks, but we need something we can analyse on its own. Can you remove all references to external symbols while still reproducing the error?

**Comment by RSickenberg** [comment]
@orklah Thank you, I edited my Gist and the error is still reproducible.
![image](https://user-images.githubusercontent.com/16922548/144587839-4b70c8e4-c23a-460c-902d-b36dbd70b19f.png)

**Comment by orklah** [comment]
I can now run the snippet, but there's not event a @psalm-suppress in it. I suppose you do have one in your code? Can you enlarge your snippet so it contains the psalm-suppress too?

**Comment by orklah** [comment]
Can you run psalm with --clear-global-cache ? Does it persists?

Also make sure you don't have psalm-suppress in methods above or below the one you copy-pasted

**Comment by RSickenberg** [comment]
@orklah I use with `--no-cache` args and no suppress in the next 100 lines up / down.

The `--clear-global-cache` did the job, I don't know why.

**Comment by orklah** [comment]
Not sure what's going on, your cache files must have been corrupted somehow. Feel free to recreate an issue if it happens again, we'll try to go deeper

**Comment by RSickenberg** [comment]
Sure, many thanks @orklah & @weirdan !
