### ISSUE TITLE
[bug] changing only the values of a parameter template type changes its type

### ISSUE THREAD

**Issue by mathroc** [vimeo/psalm#7051]
https://psalm.dev/r/2462b0b042

I'm trying to say that this function takes an array with at least a `'flags: int', and return the same type (with all the other keys that exists in the array parameter). The same problem appears when I want to add a key to a

**Comment by weirdan** [comment]
Not a bug. Template `as` gives the upper bound for the type, but Psalm will infer the most specific type possible at the call site: https://psalm.dev/r/71acb89f84

Changing the value here indeed means you're changing the type, so you're not returning the same type you received - and Psalm tells you you're not.

**Comment by mathroc** [comment]
oh I see. Would [that](https://psalm.dev/r/2b4491393a) work then ? (if https://github.com/vimeo/psalm/issues/5459 was fixed)

**Comment by orklah** [comment]
no, the intersection of `array{flags:99}` and `array{flags:int}` is `array{flags:99}`

**Comment by orklah** [comment]
What you want would be an union instead: https://psalm.dev/r/e6d84f65ee

But Psalm does not handle modifications on an array template very well...

**Comment by weirdan** [comment]
@mathroc what's your actual use case? I've seen people using `@template` where `@psalm-type` (a type alias) would suffice.

**Comment by mathroc** [comment]
> @mathroc what's your actual use case? I've seen people using `@template` where `@psalm-type` (a type alias) would suffice.

arrays with different shapes are given to this function, and I'd like to tell Psalm that the array is still the same. Or at least that the other keys are still there with the same type

I also have another function where I have a very similar issue, this function only add (or override) a few keys to this array.

It's not how I would have written the functions, I'm mostly trying to document the existing behavior. Maybe I should refactor those, but it's hard to do that safely
