### ISSUE TITLE
Intersection/generics parsing in annotations

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#706]
https://getpsalm.org/r/6bcd7e9271
```php
<?php
  namespace NS;
  use Countable;

  class Item {}
  /**
   * @var iterable<Item>&Countable $collection
   */
  $collection = [];
  count($collection);

  /**
   * @param iterable<Item>&Countable $collection
   */
  function mycount($collection): int {    
      return count($collection);
  }
  mycount($collection);
```
None of the above should fail, as far as I understand, but psalm reports this:
```
ERROR: InvalidArgument - 10:9 - Argument 1 of count expects array<mixed, mixed>|Countable, iterable<NS\Item, NS\&Countable> provided

ERROR: UndefinedClass - 13:13 - Class or interface NS\ does not exist

ERROR: InvalidArgument - 17:20 - Argument 1 of count expects array<mixed, mixed>|Countable, iterable<NS\Item, NS\&Countable> provided
```
Note the `iterable<NS\Item, NS\&Countable> provided` part. Here, `Countable` shouldn't be a part of iterable type params, and `NS\&Countable` is not even a type.

**Edit**: This is namespace resolution issue. [Similar test case](https://github.com/vimeo/psalm/blob/392f3194c005ae09095ae97c5e07c6abf97982ee/tests/ForeachTest.php#L42) in the global namespace works just fine, but [fails if you put it into a namespace](https://getpsalm.org/r/bc6917797e).

**Comment by muglug** [comment]
Do you have `allowPhpStormGenerics` turned on?

**Comment by muglug** [comment]
Thanks!
