### ISSUE TITLE
Make strlen return 0|positive-int

### ISSUE THREAD

**Issue by ricardoboss** [vimeo/psalm#7062]
This will prevent warnings like `MoreSpecificReturnType: The declared return type '0|positive-int' for x:getSize is more specific than the inferred return type 'int'`.

**Comment by ricardoboss** [comment]
https://psalm.dev/r/e073a3eb98

**Comment by weirdan** [comment]
PR is incoming that fixes it for `strlen`, `mb_strlen`, `grapheme_strlen` and `iconv_strlen`

**Comment by ricardoboss** [comment]
It seems that this issue persists: https://github.com/vimeo/psalm/issues/7062#issuecomment-986142057

**Comment by orklah** [comment]
Yeah, strlen has a stubs that overrides the callmap where int is left: https://github.com/vimeo/psalm/blob/master/stubs/CoreGenericFunctions.phpstub#L744

It should just be a matter of replacing this by 0|positive-int

**Comment by ricardoboss** [comment]
Thank you!
