### ISSUE TITLE
Wrong type inference: yield with array expression

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#7067]
https://psalm.dev/r/7648bd04ee

```php
<?php

/** @psalm-suppress MissingClosureReturnType */
$fn = function() { return [yield "a"]; };

/** @psalm-trace $fn */;
```

Psalm infer for `$fn` wrong type: ` pure-Closure():array{"a"}`
Should be: `pure-Closure():Generator<int, "a", mixed, array{"a"}>`

**Comment by orklah** [comment]
This is an improvement to do in [ReturnTypeCollector::getReturnTypes](https://github.com/vimeo/psalm/blob/e9d9481ea650b72a0b9b0ef39920b32e448749c4/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php#L30). This is a recursive piece of code that browse the AST searching for yields (and returns) in statements. The yield in array case must not have been anticipated
