### ISSUE TITLE
PropertyTypeCoercion when setting an index on a list

### ISSUE THREAD

**Issue by ricardoboss** [vimeo/psalm#7069]
I stumbled upon this peculiar case today: https://psalm.dev/r/534e675307

For some reason the type tends to change when setting a specific index on a `list<T>`. As you can see, if I omit the index, it works fine.

**Comment by orklah** [comment]
This is expected behavior, `list` implies that index are consecutive, you usually can't just add an arbitrary index in a list without changing it to a simple array.

**Comment by ricardoboss** [comment]
I see, that makes sense. But I still want to be able to update existing indexes. However even with a suppress, it still complains: https://psalm.dev/r/577d6322a5

**Comment by ricardoboss** [comment]
nvm, the comment should be:

```
/**
 * @psalm-suppress PropertyTypeCoercion
 */
$this->list[$index] = $value;
```

**Comment by weirdan** [comment]
`isset` would have worked too: https://psalm.dev/r/9352e031d4
