### ISSUE TITLE
parse_url() may return false for any combination of inputs

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#7078]
```php
if (parse_url('', -1) === false) {}
```
Gives:
```
ERROR: TypeDoesNotContainType - 2:5 - int|null|string does not contain false
```

https://psalm.dev/r/98278bec0b

Compare this with the source if this function:

https://github.com/php/php-src/blob/051b3967a9408fe60f6f9f62816a90193abbbe39/ext/standard/url.c#L346-L350

Note it returns `false` if a URL fails initial checks.

**Comment by weirdan** [comment]
See `src/Psalm/Internal/Provider/ReturnTypeProvider/ParseUrlReturnTypeProvider.php` if you want to fix it. It appears we just consider `-1` invalid, as `false` is included when you invoke `parse_url()` without the second parameter.
