### ISSUE TITLE
Mark enum functions as pure

### ISSUE THREAD

**Issue by ricardoboss** [vimeo/psalm#7086]
The enum functions introduced with #6429 should be considered pure, as they must never change the state of the enum.

**Comment by ricardoboss** [comment]
Besides the error saying that `JetBrains\PhpStorm\Pure` is not defined, this is the issue I mean: https://psalm.dev/r/06ce83e980

**Comment by ricardoboss** [comment]
This may require changes to `Functions::isCallMapFunctionPure` (row 393)

**Comment by weirdan** [comment]
https://psalm.dev/r/5373490ac9?php=8.1

**Comment by azjezz** [comment]
i was going to report this issue but found this ^^
https://psalm.dev/r/05ff25591c

**Comment by orklah** [comment]
Adding pure attributes here should be enough: https://github.com/vimeo/psalm/blob/41256c74d1049c5cccd718a78b3ffe9890f7f396/stubs/Php81.phpstub#L11
