### ISSUE TITLE
0 cannot be used in an assertion

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#7087]
Using the `webmozart/assert` library, I get the issue mentioned in the title of the issue.

The weird thing is that the issue should be reported on the library code and not on the consumer's code which is actually not declaring any annotation

https://psalm.dev/r/6d71c3312d

**Comment by weirdan** [comment]
Do you see any reason why we do not allow literals?

**Comment by orklah** [comment]
If we take into account that unions in assertions are (were?) not working properly, this reduce a lot the benefits of having a literal int in there (what's the point of a function that can only assert that the parameter is `5`?)

But no, I don't see a specific reason to ban them directly

**Comment by orklah** [comment]
Seems fixed
