### ISSUE TITLE
ReferenceConstraintViolation with non-empty-literal-string in array

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#7095]
`non-empty-literal-string` should be a subtype of `non-empty-string`, but it still results in a `ReferenceConstraintViolation`: https://psalm.dev/r/2756501f64

This seems specific to `ReferenceConstraintViolation`, it acts correctly when a `non-empty-literal-string` is used as an argument that requires `non-empty-string`: https://psalm.dev/r/f8845a750d

In fact, it seems to be something about using it in an array, just having it as the parameter itself works fine: https://psalm.dev/r/c9ad19355c

**Comment by craigfrancis** [comment]
I'm not familiar with Psalm internals (and I've run out of time today), but it looks like `$all_types_contain` is getting set to `false` in [ArrayTypeComparator.php](https://github.com/vimeo/psalm/blob/8bd525a55f4f5303637c43cc1441a865bdbdf2a1/src/Psalm/Internal/Type/Comparator/ArrayTypeComparator.php#L266) (I assume that shouldn't be the case).
