### ISSUE TITLE
Could not get class storage for opensslcertificate

### ISSUE THREAD

**Issue by dvaeversted** [vimeo/psalm#7100]
Ran into this issue, when changing from running psalm on PHP 7.4 to PHP 8.0

After a lot of trial and error, i was able to create a simple reproducer that shows on the psalm.dev interface aswell.

https://psalm.dev/r/f8a923cc47

**Comment by weirdan** [comment]
It's interesting that we still have this issue even when Psalm is targeting 7.1: https://psalm.dev/r/f8a923cc47?php=7.1

**Comment by dvaeversted** [comment]
I believe it is entirely dependent on the actual PHP version that is being used to run it, and not the language level at all.

If i run the above test script through psalm, while using PHP 7.4 i do not get the internal error.
However running it on 8.0 or 8.1, the internal error happens.

Perhaps it is related to the introduction of the [OpenSSLCertificate class](https://www.php.net/manual/en/class.opensslcertificate.php) introduced in PHP 8.0 ?

I noticed that another function, that also takes the OpenSSLCertificate class as argument does not cause an internal error.
For example the `openssl_x509_read()` function.

Which led my to try this out: https://psalm.dev/r/7b64ca57f3

It seems, as long as there is a prior call that loads in the OpenSSLCertificate class, everything is happy.
Instantiating the class for no reason, also stops the internal error from happening: https://psalm.dev/r/4f4e4b8e61


Lastly the `openssl_x509_verify()` function, is not present in the `dictionaries/CallMap.php` file.

Adding the following line to that file, seems to remove the crash. 

`'openssl_x509_verify' => ['int', 'certificate'=>'string|resource', 'public_key'=>'string|resource'],`

But i honestly have limited idea whether that is the right thing to do ?


Not sure if any of this is of any help,

**Comment by orklah** [comment]
This should be fixed in latest release. Sorry it took so long, this was a pretty simple change that you even suggested... I just missed it completely
