### ISSUE TITLE
Explicit `mixed` return triggers `MixedAssignment` when called

### ISSUE THREAD

**Issue by asgrim** [vimeo/psalm#7117]
```php
<?php

function returnsMixed(): mixed
{
    return 1;
}

$v = returnsMixed();
echo (string) $v;
```

https://psalm.dev/r/7070ff5aeb

When function explicitly returns `mixed`, Psalm will still pick up the `MixedAssignment` here, even though it is intentional. Workaround is to add `/** @var mixed $v */` above the assignment, but this is superfluous really. In `totallyTyped=true` the `MixedAssignment` becomes an error, but it is not.

I suppose there is a distinction: 

 * I intentionally marked a function as having mixed return type (`function returnsMixed(): mixed`)
 * vs I did not yet define a type, so Psalm could not infer the type and fell back to mixed (`function returnsMixed()`)

But I'm not sure how to make it clear to Psalm that the function returning mixed is intentional, and it is "okay" for `$v` to be mixed in this case, perhaps?

**Comment by orklah** [comment]
I don't think we can really assume the intention of the developer by looking at whether the type is in signature or not. And what if it is in phpdoc?

IMHO, the best way to declare the real intent here is 
`/** @psalm-suppress MixedAssignment reason for suppression */` . It's also a great complement to documentation :)

**Comment by asgrim** [comment]
> IMHO, the best way to declare the real intent here is 
> `/** @psalm-suppress MixedAssignment reason for suppression */` . It's also a great complement to documentation :)

That's perfectly reasonable I think. Thank you for your thoughts! :)
