### ISSUE TITLE
Fatal error: During inheritance of ArrayAccess on psalm runing

### ISSUE THREAD

**Issue by novafree1** [vimeo/psalm#7118]
Hi

I updated my project to php to 8.1. After that my psalm project crashed with the error:
Fatal error: During inheritance of ArrayAccess: Uncaught RuntimeException: PHP Error: Return type of Tightenco\Collect\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /sata1/home/users/panel/www/class/vendor/tightenco/collect/src/Collect/Support/Collection.php:2060 in /sata1/home/users/panel/www/composer/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66

I have two questions:
1. How to skip this inheritance. I checked this library, I have last version of it. Maybe it's not supporting php 8.1 
2. It's seams to me that psalm shouldn't throw exception and stop his work on this error
Thank You!

**Comment by novafree1** [comment]
> Hey @novafree1, can you reproduce the issue on https://psalm.dev ?

Hi! Sorry, but I don't understand how to do that. Problem package tightenco/collect  was installed by composer as dependence of the spatie/ssl-certificate-chain-resolver

**Comment by weirdan** [comment]
Psalm may have triggered the error due to autoload call, but the problem lies with that package, and not with Psalm. Make sure you updated `tighten/collect` to 8.68.0+ (https://github.com/tighten/collect/compare/v8.34.0...v8.68.0)

**Comment by VincentLanglet** [comment]
@weirdan I currently have the same error with some sonata package https://github.com/sonata-project/SonataFormatterBundle/runs/4988136265?check_suite_focus=true

All our CI are on php 8.1 and tests are working fine, we do have a notice, but it should stay a notice.
Here it seems like psalm is transforming this notice into a fatal error.

**Comment by orklah** [comment]
@VincentLanglet Please create a new issue, it seems quite harsh. This is different than this ticket where the autoloader was emitting a fatal

**Comment by VincentLanglet** [comment]
I created https://github.com/vimeo/psalm/issues/7516 @orklah
