### ISSUE TITLE
Unnecessary `EmptyArrayAccess` after checking if key exists

### ISSUE THREAD

**Issue by GeorgeCadwallader** [vimeo/psalm#7120]
https://psalm.dev/r/b4217d10dd

**Comment by weirdan** [comment]
The code, as presented, is pointless, as `if` won't be ever entered. Do you have a more realistic example of where you have this issue?

**Comment by AdeAttwood** [comment]
@weirdan I think there maybe something different with our setup to the playground. The test code we were working with is

```php
<?php

/** @return array<array-key, string> */
function get_array(): array { return []; }
function get_string(): string { return 'a'; }

function get_int(): int {
    /** @psalm-trace $array */
    $array = get_array();
    /** @psalm-trace $counts */
    $counts = array_count_values($array);
    
    if (array_key_exists(get_string(), $counts)) {
        return $counts[get_string()];
    }
    
    return 0;
}
```

Both environments give the same type for `$array` of `array<array-key, string>` however `$counts` is giving different types the playground is `array<array-key, positive-int>` however in our environment its `array<empty, empty>`.

We are on `PHP 8.0` and `vimeo/psalm v4.15.0`. I don't know if the playground is using the master branch or its using a tagged version.

For now we can fix our code by adding a var comment to the differing type and that seems to be a acceptable work around for us.

**Comment by weirdan** [comment]
Playground is running `dev-master`. The difference you see is due to #7115 (not yet a part of any release).

**Comment by AdeAttwood** [comment]
@weirdan thank you, I have run our code on `dev-master` and that has fixed the issue. This will be resolved in the next release :+1:
