### ISSUE TITLE
Psalm reports incorrect declared return type when dealing with generics.

### ISSUE THREAD

**Issue by TJ09** [vimeo/psalm#7126]
https://psalm.dev/r/a000037f0e

Imagine an ORM or something. Via generics, the "mutator" for an object declares that it contains a possible reference to that object. When trying to call a method on that object, Psalm appears to correctly infer the return type `int|null` based on the provided generics, but incorrectly claims that the "declared" return type is `null`.

This error appears to have first surfaced between v4.9.2 and v4.9.3.

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/e5bb095f67

**Comment by TJ09** [comment]
If it helps, this a) still repros, and b) bisects to 9687836519fe005ca7136f9666222e73ec816bf8

**Comment by AndrolGenhald** [comment]
As I mentioned on #8195, this might have something to do with docblock inheritance: https://psalm.dev/r/eeb56959ae

That bisection will probably be more help though.

**Comment by TJ09** [comment]
As of 96cb44b (and likely earlier), all of the linked psalm.dev links are reporting no issues.

I'm going to assume that this has been fixed in one of the 5.x releases and close this.
