### ISSUE TITLE
PropertyTypeCoercion when constructing WeakMap

### ISSUE THREAD

**Issue by dvdoug** [vimeo/psalm#7131]
When initialising an (appropriately annotated) property that is a WeakMap, Psalm complains about type coercion when calling the constructor. There cannot be any possibility of type coercion at that point, the newly constructed map is empty.

Reproducer: https://psalm.dev/r/b3a63077ef

Potentially a variation of https://github.com/vimeo/psalm/issues/4055 ?

**Comment by weirdan** [comment]
At this point this is well-known limitation of Psalm generics. To work around this you have to provide the type information missing at the generic construction point using `@var`: https://psalm.dev/r/a0a3590bcd

**Comment by dvdoug** [comment]
Hi

You say "well-known" but I wasn't able to find anything in the docs when I looked or in the existing issues list. Is there a link where I can find out more?

**Comment by bwoebi** [comment]
Hey @weirdan,

I just encountered that same issue, is there any reason it cannot be initialized the same way than SplObjectStorage is, similarly to https://github.com/vimeo/psalm/commit/346d475f557bef871b902df1d641cb028a0e1679?

**Comment by danog** [comment]
I've started working on https://github.com/vimeo/psalm/pull/10577 to fix this.
