### ISSUE TITLE
Analyze dir without reporting errors

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#7144]
Hi, we're using Psalm on our `src` directory, but not on our `tests` directory, intentionally.

However, we have a couple of methods in classes lying in `src` that are only used in tests. On these methods, Psalm reports `PossiblyUnusedMethod`.

**Is there a way to make Psalm analyse the `tests` directory for usages, but without reporting any errors on this one?**

What I tried:

- adding `tests` to `<projectFiles><directory>` => Psalm reports error on the `tests` directory, which is not what we want
- adding `tests` to `<projectFiles><directory>` **plus** `<ignoreFiles><directory>` => Psalm still reports `PossiblyUnusedMethod` on `src`

What I'd like to avoid:

- adding `<issueHandlers>` for every possible error in `tests` :slightly_smiling_face:

**Comment by orklah** [comment]
Well, if you have a public API you don't use internally, it would make sense to suppress PossiblyUnusedMethod on the whole class, maybe even in the directory.

Other than that, I'm afraid there isn't a good solution on a single run.

You may want to consider creating a psalm-unused.xml on level 8 with your test directory with only the flag for unused errors. It would only report very serious errors in your tests (that you can baseline if needed) and unused errors

**Comment by BenMorel** [comment]
Thank you! Not sure if I should leave this open as a feature request, or if this is a won't fix?

**Comment by orklah** [comment]
I don't intend to implement that myself in the near future, but I'd not be opposed to merge a PR that implement that, so if you want to propose something, leave this open. Otherwise I'd close it

**Comment by BenMorel** [comment]
Let's close it for now, if the need becomes urgent enough to justify a PR, I'll reopen this!
