### ISSUE TITLE
Cannot type standalone function IO

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#7146]
Hello

https://psalm.dev/r/c724231682

I'm trying to tell psalm type of argument of standalone function. 

So I added a docblock saying the $arg is of type `string[]` but psalm still interprets it as `mixed[]`. What am I doing wrong?

**Comment by weirdan** [comment]
`@var` docblock does not affect the signature, you need a correctly placed `@param` instead: https://psalm.dev/r/11d240dd33

**Comment by simPod** [comment]
Oh right, forgot this line-break thing. Thanks!
