### ISSUE TITLE
`array{"a string"} is not in list<string>`

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#7147]
When dealing with templates, it looks like that Psalm is not able to recognize that an array containing a string could be considered of type `list<string>`

https://psalm.dev/r/e450462519

**Comment by orklah** [comment]
This is a covariance issue: https://psalm.dev/r/c3a8aa6014

You need to declare your template covariant if you want to allow pushing subtypes: https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance

I'm still not perfectly clear how the error shown in the doc applies in this specific context, but I'd say it's not a bug

**Comment by marcosh** [comment]
Thanks a lot @orklah! I thought about checking if covariance solved the issue but forgot to try it before posting here. Sorry about this.

Just a note: the error message is quite cryptic
