### ISSUE TITLE
Incorrect TNonEmptyList TKeyedArray comparison

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#7176]
Psalm seems to think that non-empty-lists are guaranteed to have any number of values: https://psalm.dev/r/0e4fecbaf1

**Comment by orklah** [comment]
Not sure if this is a bug or an intentional way to reduce false positives.

In any way, I'd be okay to have an error there, only if we can make this work: https://psalm.dev/r/c1e15d9a0c

**Comment by weirdan** [comment]
Both cases work now (the second one with `count($a) === 3` because shapes are sealed now).
