### ISSUE TITLE
mysqli->ssl_set() nullable parameters

### ISSUE THREAD

**Issue by igitur** [vimeo/psalm#7184]
Hi

New psalm.dev user here.

Reproduction: https://psalm.dev/r/a35f79c981 

As far as I can see, `ssl_set` accepts nullable strings and it looks like psalm is thinking they're non-nullable.
https://www.php.net/manual/en/mysqli.ssl-set.php

**Comment by orklah** [comment]
Nice catch!

These definitions are defined here:
https://github.com/vimeo/psalm/blob/master/dictionaries/CallMap.php
and here:
https://github.com/vimeo/psalm/blob/master/dictionaries/CallMap_historical.php

Would you mind submitting a PR with the changes?

If you need guidance, we have a whole page on this topic here: https://psalm.dev/docs/contributing/editing_callmaps/
