### ISSUE TITLE
enhancement: array_column output inference

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#719]
```php
<?php
  /**
   * @psalm-param array<array{id:int}> $in
   * @psalm-return int[]
   */
  function f(array $in): array {
    return array_column($in, 'id');
  }
```
Similar to special handling of `array_map` and others, it could be very useful to infer array_column return type.
Basically, array_column return type is an array of $in[*][$key] type, and where that is known (as in the above code) psalm could eliminate mixed output.
It probably only makes sense when input type uses array shapes, not ordinary phpdoc array definition.

**Comment by muglug** [comment]
Fixed with https://github.com/vimeo/psalm/pull/787

**Comment by weirdan** [comment]
Totally forgot I reported this. Object properties are likely not yet supported though.
