### ISSUE TITLE
Closure parameters type inference broken in generic context

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#7199]
https://psalm.dev/r/d6b778ff32
Expected: no MissingClosureParamType

**Comment by orklah** [comment]
Why? What's the type of $_a here? Psalm need to be able to bound `A` with a provided type. It may be mixed, but you have to document it, like you would do for any other method

**Comment by weirdan** [comment]
> What's the type of `$_a` here

It's `T`, isn't it?

**Comment by klimick** [comment]
>  It may be mixed, but you have to document it, like you would do for any other method

https://psalm.dev/r/c4568c8c73
So why doc comment is not need here?

**Comment by klimick** [comment]
I don't understand what the difference between the template type and the specific type for the closure param type inference

**Comment by orklah** [comment]
> It's `T`, isn't it?

That would need assuming that the callback given always has the right type expected by the map method, no? Usually we work the other way, we know the type of T, so we need to make sure that $_a has a compatible type. @klimick after your fix, does Psalm still detects if you have a docblock type or a signature type incompatible with the type of T?

> So why doc comment is not need here?

yeah, that's definitely a inconsistency. I'm just not sure which is the correct behavior

**Comment by klimick** [comment]
> after your fix, does Psalm still detects if you have a docblock type or a signature type incompatible with the type of T?

```php
/**
 * @template T
 * @template B
 *
 * @param ArrayList<T> $list
 * @return ArrayList<array{T}>
 */
function genericContext(ArrayList $list): ArrayList
{
    return $list->map(
        /** @param B $_a */
        function ($_a) {
            return [$_a];
        }
    );
}
```

It throws `InvalidArgument`: Argument 1 of _ArrayList::map expects Closure(T:fn-genericcontext as mixed):mixed, pure-Closure(B:fn-genericcontext as mixed):array{B:fn-genericcontext as mixed} provided_

I'll add this to tests

**Comment by orklah** [comment]
well okay then :) Thanks for the test!

**Comment by weirdan** [comment]
> Usually we work the other way

Closures are special. IIRC Psalm tries to infer param/return types for them from the surrounding context unless docblock types are provided.
