### ISSUE TITLE
@property annotation and UndefinedThisPropertyAssignment error

### ISSUE THREAD

**Issue by jaydiablo** [vimeo/psalm#721]
I'm not sure that I understand psalm's handling of the `@property` annotation.  I have a situation that's similar to this:

```php
<?php

class A {
    public function __get(string $name)
    {
    }
  
    /**
     * @param mixed $value
     */
    public function __set(string $name, $value)
    {
    }
}

/**
 * @property string $test
 */
class B extends A {
  
}

class C extends B {
    public function test(): void
    {
      	$this->test = 'test';
    }
}
```

Psalm throws an `UndefinedThisPropertyAssignment` error on the `$this->test = 'test';` line of `C:test`:

>Instance property C::$test is not defined

The inheritance here doesn't seem to matter, I was just trying to setup some sample code that mimics the code I'm testing, but even this simpler test case complains in the same way:

```php
<?php

/**
 * @property string $test
 */
class C {
    public function __get(string $name)
    {
    }
  
    /**
     * @param mixed $value
     */
    public function __set(string $name, $value)
    {
    }
  
    public function test(): void
    {
      	$this->test = 'test';
    }
}
```

How can I make psalm respect the `@property` annotation in this situation?  Note that reading the property is fine (just setting it complains):

```php
<?php

/**
 * @property string $test
 */
class C {
    public function __get(string $name)
    {
    }
  
    /**
     * @param mixed $value
     */
    public function __set(string $name, $value)
    {
    }
  
    public function test(): string
    {
      	return $this->test;
    }
}
```

Thanks!

**Comment by muglug** [comment]
Running `$this->__set('test', 'test')` should work, just as `$this->__set('test', 5)` should fail (but does not at the moment.

Also `@property` should be inherited, but isn't (currently). So this should also work: https://getpsalm.org/r/a246d86538

**Comment by muglug** [comment]
So to be clear, `$this->test = 'test'` is still bad - when using `@property` you should invoke the getters and setters explicitly
