### ISSUE TITLE
`pow` written as `**`: FP

### ISSUE THREAD

**Issue by voku** [vimeo/psalm#7218]
I think `**` should be the same as `pow` but I see different results:

https://psalm.dev/r/4c9f5290b6

https://3v4l.org/9MfYo

PS: Happy Christmas :christmas_tree:

**Comment by weirdan** [comment]
For operator case, it happens here: https://github.com/vimeo/psalm/blob/08413d71bbba7bd85d6770807e4baf62e980fe22/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php#L905-L906

You can mimic that with a return type provider for function call case, but I'm not sure it's really worth it.
