### ISSUE TITLE
InvalidDocblock error when comparing array with special characters in string keys

### ISSUE THREAD

**Issue by theodorejb** [vimeo/psalm#7222]
I have a PHPUnit test that asserts that an `array<string, int>` array in an object property matches the expected value. However, if the expected value contains special characters in its string keys, Psalm reports an error saying the array cannot be used in an assertion:

https://psalm.dev/r/d3c81c61d3

This worked fine in Psalm 4.14 and then broke starting in Psalm 4.15.

**Comment by orklah** [comment]
This is related to https://github.com/vimeo/psalm/pull/7076 that drastically improved the way assertions for arrays works. This seems related to escaping some chars in the string representation of the array. I'll try to check that.
