### ISSUE TITLE
MissingFile - with composer v2.2.x

### ISSUE THREAD

**Issue by bzajacc** [vimeo/psalm#7226]
When using composer:latest and run `bin/psalm` we getting error:

![image](https://user-images.githubusercontent.com/15036507/147469594-5eab8814-f85d-4f6a-b975-c4c262a2dea8.png)

```
ERROR: MissingFile - 
17 include("composer-bin-proxy://" . __DIR__ . '/..'.'/vendor/vimeo/psalm/psalm');
```

When locking composer to v2.1 - works fine.

**Comment by orklah** [comment]
Can you tell us the path of the analyzed file? Is it your own code or a dependency that is being analyzed here?

**Comment by bzajacc** [comment]
This is my psalm.xml.
```xml
<?xml version="1.0"?>
<psalm
  errorLevel="2"
  resolveFromConfigFile="true"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="https://getpsalm.org/schema/config"
  xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
  <projectFiles>
    <directory name="src" />
    <ignoreFiles>
      <directory name="vendor" />
    </ignoreFiles>
  </projectFiles>
</psalm>
```

It analyze my own code.

**Comment by iambrosi** [comment]
The same thing happened to me with the latest composer. I fixed it by ignoring `bin/psalm` in psalm's config. I wonder if psalm should not skip analysis of this file unless explicitly included in psalm's config.

**Comment by weirdan** [comment]
This is a binary proxy generated by composer.

**Comment by vstm** [comment]
Yes composer 2.2 stopped using symlinks for "aliasing" binaries in composer packages in bin-dir. PR #7210 improves the $argv handling so that the "proxy" file is not accidentally considered a file to be scanned.

**Comment by bzajacc** [comment]
@vstm thanks for info :)
