### ISSUE TITLE
MixedArgumentTypeCoercion

### ISSUE THREAD

**Issue by semercom** [vimeo/psalm#7227]
[psalm dev](https://psalm.dev/r/aa207ce53b)
Is it my mistake?

**Comment by orklah** [comment]
This feels weird. I couldn't say if it's on purpose or if it's a bug. This could be bypassed by some variation of this: https://psalm.dev/r/05fac06214

**Comment by semercom** [comment]
@orklah TestInterface and TestInterface<T, T2> and any other variants of TestInterface with templates have only one class name string. I think that this is wrong psalm behavior. Can you fix it? I also think that it is not correct to change code without mistake for psalm.

**Comment by weirdan** [comment]
`TestInterface::class` is most certainly not `class-string<TestInterface<T, T2>>`. What makes you think it is? Consider, e.g., `T=int`, `T2=string` - it's pretty obvious that property would expect `class-string<TestInterface<int, string>>` (the name of the and implementor of `TestInterface`, having `@implements TestInterface<int, string>`), and `TestInterface::class` is too generic to fulfill that contract.

**Comment by semercom** [comment]
@weirdan ok, i got it, thanks for the help
