### ISSUE TITLE
unreachable code & type detection

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#724]
https://getpsalm.org/r/e50c9bd89a
```php
function foo() : bool {
    return true;

    return false;
}
```

In the above example, we have a function with a strict bool return type, with two returns- both of the type bool. psalm reports `Could not verify return type 'bool' for foo`, although I'm hoping it's possible for it to evaluate all return statements & instead return just the `Expressions after return/throw/continue` error ?

**Comment by muglug** [comment]
> I'm hoping it's possible for it to evaluate all return statements & instead return just the Expressions after return/throw/continue error ?

Yeah, I did that. Thanks for the suggestion!
