### ISSUE TITLE
Cannot use `psalm-if-this-is` and `psalm-self-out` at the same time

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#7248]
https://psalm.dev/r/75f554a0bc

It seems `psalm-self-out` works before `psalm-if-this-is`

**Comment by klimick** [comment]
Also error message `ERROR: IfThisIsMismatch - 17:7 - Class is not App<string> as required by psalm-if-this-is` is inaccurate.

**Comment by orklah** [comment]
@danog would you mind looking at this? :)

For reference: https://github.com/vimeo/psalm/pull/6514
