### ISSUE TITLE
Flaw in the co-dependant variables types

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#7249]
In the example here: https://psalm.dev/r/9bc618221f

Psalm doesn't detect that $type_context can't be null because we're in a scope where $completion_data is null and we already stated that both can't be null.

Psalm manages to make it work if the conditional is outside the try/catch: https://psalm.dev/r/ab2b600564.

This is pretty low priority because it's an edge case of a complex module and the code, while correct, is a little confusing anyway.

Found by: https://github.com/vimeo/psalm/pull/7247

**Comment by weirdan** [comment]
Psalm now infers `non-falsy-string` for both snippets.
