### ISSUE TITLE
Psalm stopped seeing errors

### ISSUE THREAD

**Issue by Hast** [vimeo/psalm#7257]
I'm here with the one of the weirdest questions in my life. Suddenly psalm stopped seeing any errors in my code. I was fixing some issues, and then all of a sudden I stopped getting errors from psalm. I know there are many of them, because I used to ignore some of them within `psalm.xml`. Now I rolled back to master (stable code), and removed all exceptions from the config. Still nothing.

**psalm.xml:**

    <?xml version="1.0"?>
    <psalm
        errorLevel="1"
        resolveFromConfigFile="true"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://getpsalm.org/schema/config"
        xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    >
        <projectFiles>
            <directory name="src/" />
            <ignoreFiles>
                <directory name="vendor" />
            </ignoreFiles>
        </projectFiles>
        <issueHandlers>
            <MixedPropertyTypeCoercion>
                <errorLevel type="suppress">
                    <file name="src/Transport/Message/Params/SendMessageParams.php"/>
                </errorLevel>
            </MixedPropertyTypeCoercion>
        </issueHandlers>
        <stubs><file name="./config/bootstrap.php" /></stubs>
    </psalm>

Note, I removed about 20 entries from `issueHandlers` which would trigger errors (just to test if psalm working).

**Command:**
`sudo -u wwwbm -E -H /usr/bin/php -d memory_limit=2048M vendor/bin/psalm`

**Output:**

    Scanning files...
    Analyzing files...
    
    ░
    ------------------------------
    No errors found!
    ------------------------------
    
    Checks took 2.14 seconds and used 217.018MB of memory
    Psalm was unable to infer types in the codebase

I'm stuck. I'm not even sure at which moment it stopped showing errors, just in the middle of coding actually.

I know the question is too broad now, so I'll try to make it a little bit more strict:

Is there any way to debug psalm? Any kind of verbose mode, or maybe any internal debugging system exists for the lib? I'm literally going crazy.

**Psalm version:** 3.18.2

**Comment by Hast** [comment]
Solved by updating to the last psalm version without any changes to the code. Still don't know what was that.

**Comment by weirdan** [comment]
> Psalm version: 3.18.2

That's way too old. Is there any chance you can upgrade to the latest 4.x?

> Solved by updating to the last psalm version without any changes to the code.

:+1:
