### ISSUE TITLE
Activating psalm plugin via psalm config file?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#7267]
https://psalm.dev/docs/running_psalm/plugins/using_plugins/

For some reason I cannot enable psalm plugins (`psalm-plugin show` works fine, but `enable` says "Cannot find Psalm config").

Is there any way I can enable a plugin via the custom psalm config file I am using?

**Comment by orklah** [comment]
Can you show the command you run?

But yeah, you can absolutely add plugins manually to the xml. It's just a matter of having the right tag. Here you can see both syntax Psalm accepts: https://github.com/vimeo/psalm/blob/4.x/psalm.xml.dist#L46
Either with a class or a file

**Comment by kkmuffme** [comment]
Thanks, using:

```
<plugins>
	<pluginClass class="Psalm\PhpUnitPlugin\Plugin"/>
</plugins>
```

worked.

**Comment by kkmuffme** [comment]
Sorry, I added it but it's not loaded?

`php /opt/composer/vendor/bin/psalm-plugin show --config=path/psalm-with-stubs.xml`

I get:

```
Enabled
-------

 ! [NOTE] No plugins enabled

Available
---------

 ---------------------------------- ----------------------------
  Package                            Class
 ---------------------------------- ----------------------------
  humanmade/psalm-plugin-wordpress   PsalmWordPress\Plugin
  psalm/plugin-phpunit               Psalm\PhpUnitPlugin\Plugin
 ---------------------------------- ----------------------------
 ```

Is this just a display bug in psalm-plugin or is the plugin really not loaded?

**Comment by weirdan** [comment]
Did you add it to `path/psalm-with-stubs.xml`?

**Comment by kkmuffme** [comment]
Yes :-)

**Comment by kkmuffme** [comment]
Ah yes, I added it but it didn't sync to the server, bc I got disconnected due to a power outage earlier and forgot to reconnect my FTP.
