### ISSUE TITLE
psalm confuses "scopes" of different branches in multilevel switch

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#728]
https://getpsalm.org/r/f844bdfa16
```php
$a = new A;

switch (rand(0,1)) {
  case 0:
  case 1:
    $dt = $a->maybeReturnsDT();
    if (!is_null($dt)) {
      $dt = $dt->format(\DateTime::ISO8601);
    }
    break;    
}

class A {
    public function maybeReturnsDT(): ?\DateTimeInterface {
        return rand(0,1) ? new \DateTime('now') : null;
    }
}
```
This is heavily stripped-down real-world (read: horrible) code. None of the branches falls through, but psalm thinks $dt is string where it's actually object.

**Comment by muglug** [comment]
Edited to simplify sample

**Comment by muglug** [comment]
Using a regular function doesn't show same bug: https://getpsalm.org/r/456150783c
