### ISSUE TITLE
Support Hack code

### ISSUE THREAD

**Issue by fredemmott** [vimeo/psalm#73]
This would be neat, even if you ignore things specific to the Hack type system.

https://github.com/phplang/phack contains a fair bit of the required work to extend nikic/php-parser

**Comment by muglug** [comment]
Not sure it's worth the overhead of supporting two languages. Are there specific features Psalm supports that Hack's typechecker doesn't?

**Comment by fredemmott** [comment]
Not that I'm aware of, but this would make it possible to directly compare them on my existing code.

**Comment by muglug** [comment]
Ah, well sorry. While Psalm's type system shares a lot of the same ideas of Hack's, it's not a project goal to have a one-to-one comparison between the two systems (but Psalm will always support and enforce type-related features in native PHP code as they become available).

There are a number of features in Hack's type system that are not supported in any concrete fashion by Psalm (such as [Enums](https://docs.hhvm.com/hack/enums/introduction)), and it would complicate matters to be building support for them mostly blindly.

**Comment by muglug** [comment]
But https://getpsalm.org is kept up-to-date with the latest version of Psalm, so all of Psalm's features (and, I'm sure, its bugs) are exposed there.

**Comment by muglug** [comment]
Oh, and the only feature that Psalm has that Hack doesn't, to my knowledge, is a slightly better understanding of type algebra (as detailed here: https://github.com/vimeo/psalm/pull/28)

**Comment by fredemmott** [comment]
Yep - I wasn't wanting full support - but this would make it easy to see if moving to PHP7+Psalm would be a good choice for me. For this, I'd have to stop using Hack features even if Psalm supported them, so I don't particularly care about them for this request.

**Comment by muglug** [comment]
Ohh, well I'll see what I can hack together over the next few days.

**Comment by muglug** [comment]
Had a play around with turning property types into `@var` comments [here](https://gist.github.com/muglug/e2dc90560827bc502cac05ee84cd9684), and I think that avenue – transpiling Hack into PHP, then analysing that output in Psalm just as it analyses any PHP – is the only feasible approach.

Writing the above transformation also highlighted that Hack is better than Psalm in at least one area – finding [not-set-in-constructor](https://github.com/vimeo/psalm/issues/3) issues.

**Comment by muglug** [comment]
Psalm now finds [not-set-in-constructor](https://github.com/vimeo/psalm/commit/6bcc763414a6d819027a48ffbb153171c111107d) issues (I just copied HHVM's approach, only allowing private method calls.
