### ISSUE TITLE
compatibility with amphp v3

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#7307]
Psalm is not compatible with Amphp version 3, which wouldn't usually be a problem, however, if a project is using amphp version 3, it is, even if using phar release.

reproduce:

```php
$ mkdir test
$ cd test
$ git init
$ composer require amphp/amp:v3.x-dev
$ composer require vimeo/psalm # fails, let's try phar
$ composer require psalm/phar
$ php vendor/psalm/phar.phar -c psalm.xml # fail, due amphp functions re-declaration in vendor.
```

**Comment by azjezz** [comment]
@psalm-github-bot no.

**Comment by orklah** [comment]
I have little experience with amphp, Is it just a matter of allowing it in composer or is there more to it?

**Comment by weirdan** [comment]
Once amp ships a stable release, we would welcome a PR to support 3.0. Meanwhile, it should still work with phar, and I'm surprised it doesn't. Scoper should have renamed those functions in the phar file.

**Comment by weirdan** [comment]
> Scoper should have renamed those functions in the phar file.

And it did namespace them under `_HumbugBoxae36b421c4ce\Amp;` namespace, so I would expect no conflicts there.

**Comment by weirdan** [comment]
Also, it works for me with `psalm/phar`. Mind creating a repro repo, and posting the actual error you're getting?

**Comment by azjezz** [comment]
I'm closing this issue because i'm dumb ^^"

phar build doesn't actually fail, what fails is vimeo/psalm, but the build using phar fails as it doesn't support plugins.
