### ISSUE TITLE
Dont have the psalm-github-bot reply when there are links there already

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#7316]
It makes sense to auto-reply with the both on the first message, if there are no psalm.dev links in it.

But always replying with `I found these snippets:` is useless, isn't it? (and just bloats all issues)

**Comment by weirdan** [comment]
Point of order: the bot has its own repo: https://github.com/psalm/psalm-github-bot/

> But always replying with I found these snippets: is useless, isn't it?

Quite the opposite. It's just what the bot was initially meant to do. It brings the snippet and the output into the issue (and the following discussion) and, as a side effect, to the email notifications that Github sends.

**Comment by weirdan** [comment]
Did you know that the links in the bot reply are expandable? 

![image](https://user-images.githubusercontent.com/57403/148302707-fe64bc35-9446-4b34-ae71-4f9ecb3f5b10.png)

**Comment by orklah** [comment]
That's very useful when looking back on resolved issues. I use it as a versioning tool once the bug is resolved in psalm.dev :D
