### ISSUE TITLE
Add ability to verify recursively-defined templated return type

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#732]
Mentioned in TypeScript [here](https://www.youtube.com/watch?v=hDACN-BGvI8#t=23m0s) (thanks @ocramius)

Related to https://github.com/vimeo/psalm/issues/730#issuecomment-388483171

```php
<?php
  namespace NS;
  /**
   * @template T
   * @psalm-param callable():T $action
   * @psalm-return T
   */
  function retry(int $maxRetries, callable $action) {
    try {
      return $action();
    } catch (\Throwable $e) {
      if ($maxRetries-- > 0) {
        return retry($maxRetries, $action);
      }
      throw $e;
    }
  }

  function takesInt(int $p): void{};
  
  takesInt(retry(1, function(): int { return 1; }));
```

Expected: no issues
Actual: [`Could not verify return type 'T' for NS\retry` (among others)](https://getpsalm.org/r/0999ce12f7)

Explicit version (no templated types) can be verified: https://getpsalm.org/r/556485b35e

**Comment by weirdan** [comment]
Note the linked part of the video shows `Foo<T>` that refers to `Foo<Foo<T>>`. That's recursive type. However the _type_ of `retry` is not recursive, even though the function itself is.

**Comment by weirdan** [comment]
This particular snippet works fine as of c6aa396
