### ISSUE TITLE
"Cannot treat type object as callable" when implementing __invoke

### ISSUE THREAD

**Issue by ricardoboss** [vimeo/psalm#7322]
https://psalm.dev/r/0db80c0f40

This only happens when using first-class callables. When I switch out `$classInstance(...)` with `Closure::fromCallable($classInstance)` it works.

**Comment by villfa** [comment]
Here another example to show that is not only related to first-class callables: https://psalm.dev/r/cf384c261f

**Comment by orklah** [comment]
It's handled in FunctionCallAnalyzer::getAnalyzeNamedExpression starting from line 637. We loop over the type in the union in order to detect potential callables. It seems your two examples are not detected as callables. It should not be too difficult to handle them if you want to try

**Comment by villfa** [comment]
Here more examples to illustrate the remaining issues:

* works : https://psalm.dev/r/001d69e1dc
* doesn't work: https://psalm.dev/r/d78ef327e9
* doesn't work: https://psalm.dev/r/001d69e1dc

**Comment by orklah** [comment]
Those are gonna be hard. We don't have a type TClassStringWithProperties...

**Comment by orklah** [comment]
I'll close this as I don't think it's worth implementing. I'd not be opposed to merging an implementation of that but it's a lot of work for such a small use case

**Comment by AndrolGenhald** [comment]
I'll see if it's easier to fix with my type system rewrite, but it looks like that will probably have to wait for Psalm 6 at this point.
