### ISSUE TITLE
False-positive: NoValue

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#7323]
Example: https://psalm.dev/r/5670fbfa74

I have a case when returned Closure must immediately throw exception when called, but under some condition (used random_int for that). Adding `never` to closure returns `InvalidReturnType`.

**Comment by ricardoboss** [comment]
Seems to be an issue with short function notation: https://psalm.dev/r/0651e3f89e

**Comment by orklah** [comment]
> Seems to be an issue with short function notation: https://psalm.dev/r/0651e3f89e

Not exactly. Psalm considers @zmitic's snippet is identical to this: https://psalm.dev/r/d30dcfd371. It's the `return throws ...` that causes an issue. In short closures, the return is implied.

There is also a second issue when trying to document the return type of the short closure: https://psalm.dev/r/69b04c1caf

So, to fix this, Psalm should allow never returning statements in short closures  (calling exit() will do the same) and also allow implicit returns of never returning statements when the return type is `never`

This seems to be also an issue with `void` short closures: https://psalm.dev/r/eb3536c071

**Comment by orklah** [comment]
The case with void is actually correct. PHP will emit a fatal error no matter what the content of the closure is because it will try to return it: https://3v4l.org/sH2Zn

**Comment by orklah** [comment]
oh, actually, the explicit never case is not possible either. This is more weird: https://3v4l.org/JFuMf
