### ISSUE TITLE
MixedArgumentTypeCoercion with local var using template type.

### ISSUE THREAD

**Issue by donquixote** [vimeo/psalm#7333]
For an interface `I` annotated with `@template T as object`.
It seems that function parameters with `@param I` are understood as `I<object>`, but local vars with `@var I` are understood as just  `I`.
Also inferred type of local vars is always `I`, not `I<object>`.
This leads to MixedArgumentTypeCoercion inspection warning.

https://psalm.dev/r/6b70724235

**Comment by weirdan** [comment]
The snippet no longer produces any errors: https://psalm.dev/r/6b70724235
