### ISSUE TITLE
`json-string` type

### ISSUE THREAD

**Issue by ricardoboss** [vimeo/psalm#7334]
It would be great if we had a type which denotes a string parameter to be an encoded json object/array, maybe even with a template param declaring the properties/keys of the decoded json value via a `@psalm-type x = array{...}` or an interface.

Do you think this is worthwhile and doable?

**Comment by ricardoboss** [comment]
It could look like this: https://psalm.dev/r/ee988661fc

**Comment by ricardoboss** [comment]
My bad: this is what I meant https://psalm.dev/r/8735272e42

**Comment by orklah** [comment]
Possibly worthwhile, probably not doable.

When adding a type, you have to code somewhere every interaction with every other type. Which means, each new type implies exponentially more work.
It also implies that unless you have a very clear way to insert the new type in the hierarchy of other types, you're gonna have issues.

For example:

```php
<?php
$a = json_encode($array);
// $a is now a json-string
$b = strtolower($a);
// if $b is now a lowercase-string, you can't guarantee it's a valid json anymore. If $b is still a json-string, you can't know it's a lowercase-string so it will be refused by any function that expects lowercase-string
```

**Comment by ricardoboss** [comment]
I didn't think about that... You're definetly right, but I would argue a `lowercase-json-string` is too niche to be useful. A `json-string` is a valid JSON string. Once modified it may no longer be a valid JSON string, that's why the type should change and loose its connection to JSON IMO.

**Comment by orklah** [comment]
yeah, that was just the easiest example I could think of, you could get the same result with

```php
$a = json_encode(5);
assert(is_numeric($a);
// what is the type of $a now? numeric or json-string?
```

**Comment by orklah** [comment]
I'll close this as there is not much to do here. We can continue to discuss about it though

**Comment by ricardoboss** [comment]
I'd say in this case it would be a `json-string<numeric>`. It should just be a wrapper around existing types, which makes it possible to infer which type gets returned by a `json_decode`.

**Comment by orklah** [comment]
but then you created a new special case that will need to be handled everywhere numeric must work.

This is a very difficult issue...

**Comment by ricardoboss** [comment]
In what case is it special? `json_encode` currently returns `string|false` (https://psalm.dev/r/45f2321565). Adding a `json-string` extending `string` would give it a bit more context. Plus we would be able to type-hint methods to make sure we get JSON where we expect it.

**Comment by orklah** [comment]
I mean if you create a json-string<numeric>. You would have a TString that would behave in some cases like a TNumeric. This would need to be coded everywhere

Extending TString is not complex, adding the type in parser and then in documentation is not either.

What's hard is:
- making sure the type is kept intact through the code. For example, if somewhere we made a `if($type instanceof TString){ $return_type = new TString();}`, you lost your specific type
- coding every interaction between your type and other types. For example, can a json-string be empty? can it be falsy? can it be a numeric? what happens if you check a is_numeric() on it? etc...
