### ISSUE TITLE
DOMDocument::appendChild returns input value where Psalm thinks its always a DOMNode

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#734]
This makes Psalm think that it has neither `setAttribute` nor `getAttribute` methods, [yet it has them](http://php.net/manual/en/domelement.setattribute.php).

- https://getpsalm.org/r/39265a1f04
- https://3v4l.org/chZ0Y

```php
$doc = new DOMDocument("1.0");
$node = $doc->createElement("foo");
$newnode = $doc->appendChild($node);
$newnode->setAttribute("bar", "baz");
var_dump($newnode->getAttribute('bar'));
var_dump(method_exists($newnode, 'getAttribute'));
```

**Comment by muglug** [comment]
*weeps bitterly* why oh why isn't it documented. why?

**Comment by muglug** [comment]
Ah, `DOMNode` really doesn't have those methods. But it looks like `DomDocument::appendChild`, contra the documentation, returns a `DomElement`

**Comment by muglug** [comment]
At least in some instances

**Comment by sanmai** [comment]
Well, it appears that `createElement()` always returns what is given.

**Comment by sanmai** [comment]
I'm closing this as a bogus because Psalm can't help it.

**Comment by muglug** [comment]
Yes it most certainly can :)
