### ISSUE TITLE
`dir` has wrong return type Directory|false|null instead of Directory|false

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#7345]
Hi @orklah, 

I run into the following issue
- Psalm consider `dir` to return `Directory|false|null`
- PHPStan consider `dir` to return `Directory|false`

The previous type was introduced by @voku in https://github.com/vimeo/psalm/pull/1541

I did some research, and it seems that the php doc was updated recently from `Directory|false|null` to `Directory|false`.
https://github.com/php/doc-en/pull/903

But I'm not sure which CallMap should be modified then...

**Comment by weirdan** [comment]
It's changed in PHP 7.2: https://github.com/php/php-src/commit/b71b12843c08dafea897f105d791741f2c098827#diff-a6738c9e7e606e49fc4e7225c281deca86191ada31a5dc077169418541541d1cL218

**Comment by weirdan** [comment]
Actually, in 8.0: https://3v4l.org/RfVEi, when ZPP started to throw. But since this was zpp-null, you need to drop null from all callmaps.

**Comment by VincentLanglet** [comment]
> But since this was zpp-null, you need to drop null from all callmaps.

Did https://github.com/vimeo/psalm/pull/7347 then
