### ISSUE TITLE
Feature request: merging `issueHandlers` elements

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#7353]
On `doctrine/orm`, we would like to be able to run Psalm with `doctrine/dbal` 2 and 3 without repeating code.
Currently we are able to do so because the set of errors we get for DBAL 3 is included in the set of errors we get for DBAL 2, so having one file does the trick. The downside is that it breaks `--update-baseline`, which will remove DBAL-2-specific issues.

I've attempted to leverage the include system to have a DBAL-2-specific file, but I got stuck because including a file that has an `issueHandlers` root element seems to result in subsequent `issueHandlers` being ignored.

It would be great to be able to have several `issueHandlers` elements in a single config and have them deep-merged together.

**Comment by orklah** [comment]
@greg0ire If I'm not mistaken, @wouterj's PR fixed part of the error. The other issue was that deep nested merge between two issueHandlers is not done yet, but this was reported here already: https://github.com/vimeo/psalm/issues/6888 so I'm closing this one
