### ISSUE TITLE
`extract($arr, EXTR_SKIP)` should not invalidate previous variables

### ISSUE THREAD

**Issue by gharlan** [vimeo/psalm#7361]
https://psalm.dev/r/35e85a72e3

When using the `EXTR_SKIP` flag for `extract()`, the existing variable types should not be invalidated by the `extract` call.

**Comment by orklah** [comment]
It's handled here: https://github.com/vimeo/psalm/blob/7c24d33bb20e127676f8e99e4f974f83eabbb2e0/src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php#L200

Currently, every variable in the scope except a few exception is turned into mixed
