### ISSUE TITLE
Stderr should only output actual errors

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#7370]
Currently stderr outputs all kind of info, like:

```
Target PHP version: 8.1 (set by config file)
Scanning files...
Analyzing files...
E
```

When using psalm in CI, this makes things much harder to automatically parse.

Would it be possible to add a flag in config or CLI to only get actual errors (e.g. could not resolve config, could not resolve stubs file,...) in stderr?

**Comment by orklah** [comment]
I don't think we even need a config on that. Please propose a PR on master branch, this is something that could go on Psalm 5

**Comment by weirdan** [comment]
@orklah where would informational messages (and progress) go then?

**Comment by orklah** [comment]
stdout would be more appropriate, no?

**Comment by kkmuffme** [comment]
@orklah just fyi: if you want this in stdout, it also needs handling/adjustment for e.g. --output-format=json

**Comment by AndrolGenhald** [comment]
Using stderr for progress is pretty standard.
https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout

Including progress in stdout makes stdout more difficult to parse. Perhaps there are other improvements that could be done to simplify stderr parsing for your use case?

**Comment by kkmuffme** [comment]
>Maybe adding a --quiet flag to disable the version and progress info?

Exactly; like I said initially a "a flag in config or CLI" would be perfect

**Comment by weirdan** [comment]
Alternatively, a log level prefix could be used, e.g.:
```
INFO: Target PHP version: 8.1 (set by config file)
INFO: Scanning files...
ERROR: File a/b/c not found
INFO: Analyzing files...
```

**Comment by kkmuffme** [comment]
Just found out that `--no-progress` (which isn't documented anywhere I could find online) already kind of does this.

**Comment by orklah** [comment]
Don't hesitate to make a PR to add this to the documentation, contributions are always welcome! I'll close this if you found your answer
