### ISSUE TITLE
$config in plugin invoke always null

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#7388]
psalm plugin:

```
class Plugin implements PluginEntryPointInterface
{
    public function __invoke(RegistrationInterface $api, ?SimpleXMLElement $config = null): void
    {
```

$config is always not set/null, even though I'm calling psalm with --config=some-config.xml

What am I doing wrong?

**Comment by weirdan** [comment]
`$config` represents the *plugin* configuration, e.g.
```xml
<pluginClass class="Your\Plugin">
  <option1 value="123"/>
  <complexOption>
     <something>important</something>
  </complexOption>
</pluginClass>
```
Here you will get a SimpleXMLElement containing all children of the `<pluginClass>` element

https://github.com/vimeo/psalm/blob/7dc1c454fb8baaaf94a1c76c48287a7dfb1f47bb/src/Psalm/Config.php#L1171-L1177
