### ISSUE TITLE
Incomplete return type for mb_split() function

### ISSUE THREAD

**Issue by ryanhobrock** [vimeo/psalm#7421]
Function ```mb_split()``` should have a return type of ```array|false``` [per the PHP documentation](https://www.php.net/manual/en/function.mb-split.php). The Psalm call maps only have ```array``` leading to a ```TypeDoesNotContainType``` "list\<string\> does not contain false" error when type checking. See https://psalm.dev/r/0b69779c9f to reproduce the issue.

Changing the call maps from:

```
'mb_split' => ['list<string>', 'pattern'=>'string', 'string'=>'string', 'limit='=>'int'],
```
to:
```
'mb_split' => ['list<string>|false', 'pattern'=>'string', 'string'=>'string', 'limit='=>'int'],
```
should resolve it.

**Comment by orklah** [comment]
Do you have a code that would actually make mb_split returns false?

Sometimes, when we're sure Psalm will catch every case that would make a function errors, we allow ourselves to not include the error return for better inference, but I'm not sure this is the case here...

**Comment by AndrolGenhald** [comment]
@orklah I spent a minute looking at that a couple hours ago because I had the same thought, there's [one case](https://github.com/php/php-src/blob/20d8561ed4986c3ca1e514b7bcb2dda8b6fbe0ee/ext/mbstring/php_mbregex.c#L1243:L1249) that probably shouldn't happen, but there are also 2 [valid cases](https://github.com/php/php-src/blob/20d8561ed4986c3ca1e514b7bcb2dda8b6fbe0ee/ext/mbstring/php_mbregex.c#L1200:L1207): https://3v4l.org/EQJKd

**Comment by orklah** [comment]
Cool, thanks for confirmation. @ryanhobrock you correctly identified what needed to change. Small caveat, you need to change this in CallMap and CallMap_historical.

Can you push a PR?

**Comment by orklah** [comment]
With pleasure :)

**Comment by RishiKumarRay** [comment]
Hey @orklah in which directory can i Find the files CallMap and CallMap_historical as you said the changes are to be made in this 2 files?

**Comment by orklah** [comment]
Just right here: https://github.com/vimeo/psalm/tree/4.x/dictionaries

**Comment by RishiKumarRay** [comment]
@orklah cool ! I found it , Thanks a lot , will be generating a PR soon

**Comment by RishiKumarRay** [comment]
@orklah please do the review

**Comment by ryanhobrock** [comment]
Thank you @orklah, @AndrolGenhald, and @RishiKumarRay for the quick work on this!
