### ISSUE TITLE
Foreach loops which guarantee casting all elements get mixed types

### ISSUE THREAD

**Issue by jnvsor** [vimeo/psalm#746]
In the code below an array of strings is cast to floats, but psalm types it as `string|float`

Is this a quick fix for complex cases where `continue`, `break`, and/or other control flow might skip the cast, or is it a bug that should be fixed?

```php
<?php

/**
 * @return float[]
 */
function test () {
    $a = '1,2,3';
    $b = explode(',', $a);
    foreach ($b as $i => $c) {
        $b[$i] = (float) $c;
    }
    return $b;
}
```

```
ERROR: InvalidReturnStatement - 12:4 - The type 'array<int, string|float>' does not match the declared return type 'array<mixed, float>' for test

ERROR: InvalidReturnType - 4:12 - The declared return type 'array<mixed, float>' for test is incorrect, got 'array<int, string|float>'
```

For reference, replacing the loop with `$b = array_map('floatval', $b);` fixes the errors.

**Comment by muglug** [comment]
I don't quite think it's a bug, mainly because it requires some quite complicated analysis to get right.

Related to https://github.com/vimeo/psalm/issues/649

**Comment by muglug** [comment]
In the meantime you can fix by assigning a separate variable: https://getpsalm.org/r/f7d1e23b60

```php
/**
 * @return float[]
 */
function test () {
    $a = '1,2,3';
    $b = explode(',', $a);
    $b2 = [];
    foreach ($b as $i => $c) {
        $b2[$i] = (float) $c;
    }
    return $b2;
}
```

**Comment by jnvsor** [comment]
I just added the `array_map` call afterwards as a workaround, but I figured I'd make the issue anyway since it seems like it would be useful

**Comment by muglug** [comment]
Yeah it's just a low-priority one, because PHP/JS are special in allowing you to rewrite the types of variables this way.

Flow just [prevents you from changing an array type](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMBDMAXjAG0BGAGjACYqBmAXQG5Uo4AnMACi1wEsiYAAxMwAgDxg6ovgGpZASjABvVGHwk+DQXk0MAdNjgBlbOz4A7AOZcFLAL5A) - might add similar functionality to Psalm at some point in the future, though it'd probably be under a flag.

**Comment by muglug** [comment]
Going to close this - anyone encountering this same issue should either use the workaround above or suppress the issue in the function.
