### ISSUE TITLE
Upcast Generator<TKey,TValue> to Traversable<TKey,TValue>

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#747]
https://getpsalm.org/r/c738519681
```php
<?php
  /**
   * @template TKey
   * @template TValue
   * @param Traversable<TKey,TValue> $t
   * @return array<TKey,TValue>
   */
  function f(Traversable $t): array {
    $ret = [];
    foreach ($t as $k => $v) $ret[$k] = $v;
    return $ret;
  }
  /** @return Generator<int,stdClass> */
  function g():Generator { yield new stdClass; }
  
  $noCast = g();
  /** @var Traversable<int,stdClass> $cast */
  $cast = g();

  takesArrayOfStdClass(f($noCast)); // should be as good as $cast
  takesArrayOfStdClass(f($cast));

  /** @param array<stdClass> $p */
  function takesArrayOfStdClass(array $p): void {}
```
Here psalm thinks `f($noCast)` is `array<mixed,mixed>` even though `Generator` is `Iterator` and `Iterator` is `Traversable` (and thus `Generator<TKey,TValue>` should be able to fill in for `Traversable<TKey,TValue>`). Perhaps `Generator` needs to be defined as a generic that template-extends `Iterator`.

Related to #745 (I tried to add `iterator_to_array` as a core generic function)

**Comment by muglug** [comment]
Yeah, so at the moment templating just works on exact matches for the container type. Obviously works fine when it's `array<TKey, TValue>` and you're passing in arrays, but breaks down for this use case.

**Comment by weirdan** [comment]
What does `@template-extend` annotation do then?

**Comment by muglug** [comment]
precisely nothing. I suppose I wrote it assuming it would do something in the future, but the future never came. It's a good place to start, at any rate.
