### ISSUE TITLE
What is T=, no docs about it

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#7481]
I was looking at [Doctrine collection](https://github.com/doctrine/collections/blob/1.6.x/lib/Doctrine/Common/Collections/Collection.php#L194) which has lots of generics but with equals sign like ``T=`` .

But documentation doesn't say anything about it and how it is different than just ``T``. Searching thru existing issues for ``optional`` or ``default`` didn't help; is it explained somewhere I can't find it?

**Comment by orklah** [comment]
It is indeed used to express the param is optional. It is present in the doc here: https://psalm.dev/docs/annotating_code/type_syntax/callable_types/ but it could probably be improved.

Where did you expect to find this information? Maybe we can add it at the place you expected it

**Comment by zmitic** [comment]
@orklah 

OMG, I feel stupid now! I didn't even look there but thru issues, collections repo, template annotations section... instead of in most obvious place :smile: 

I think if top-search could return result for ``T=`` it would be good, or under [templates](https://psalm.dev/docs/annotating_code/templated_annotations/) section with a link to closures. The reason is this is the page I always use as a starter point but that probably doesn't apply to everyone.

---

Anyway closing as this is 100% my fault, sorry.
