### ISSUE TITLE
getpsalm.org Report which version of psalm is being used?

### ISSUE THREAD

**Issue by jaydiablo** [vimeo/psalm#750]
I ran into a case that seemed like a false positive today, but when I copied the code to getpsalm.org to verify (and submit an issue), the issue didn't show up.

Looking at commit history since the last release, it seems possible that the bug was fixed already (and I'm assuming that getpsalm.org uses a copy of the `master` branch?).

Would it be possible to have getpsalm.org report which version of psalm it's running (tagged version if that's the case, or commit hash possibly?).

**Comment by jaydiablo** [comment]
Related, but let me know if you'd like a separate issue for it...

Possible to enable the dead code finder on getpsalm.org?

**Comment by muglug** [comment]
Yeah, I can definitely add a version hash.

**Comment by muglug** [comment]
Could you ticket the dead code finder thing? A bunch more work is necessary to make that usable.

**Comment by muglug** [comment]
This is fixed on getpsalm.org

**Comment by muglug** [comment]
@jaydiablo dead code detection is back on getpsalm.org

**Comment by jaydiablo** [comment]
Nice!  I mainly thought it would be nice when trying to report false positives.  I'll try to start reporting them when I see them now.

Thanks!
