### ISSUE TITLE
Wrong type with static

### ISSUE THREAD

**Issue by ddebin** [vimeo/psalm#7507]
Wrong type resolution when class property is defined as `static`.

https://psalm.dev/r/f5f3b15557

**Comment by orklah** [comment]
This is on purpose. Psalm made a design choice that class-level templates and static properties/method should not mix.

**Comment by AndrolGenhald** [comment]
Related to #5753 and #7482. Class templates are currently ignored on static properties and methods. I think there are some cases where this should be allowed for methods, but it could cause harder problems if allowed on properties: https://3v4l.org/ZcQMS.
