### ISSUE TITLE
Uncaught Exception: InvalidArgumentException Could not get class storage for doctrine\dbal\dbalexception

### ISSUE THREAD

**Issue by inlb** [vimeo/psalm#7524]
psalm 4.19.0
weirdan/doctrine-psalm-plugin v2.2.0
Symfony 6.0.3
PHP 8.1

```
> ./vendor/bin/psalm --show-info=true
Target PHP version: 8.1 (inferred from composer.json)
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░Uncaught Exception: InvalidArgumentException Could not get class storage for doctrine\dbal\dbalexception
Emitted in /Users/dmitriyrybin/PhpstormProjects/.../app/api/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:46
Stack trace in the forked worker:
#0 /Users/dmitriyrybin/PhpstormProjects/.../app/api/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(628): Psalm\Internal\Provider\ClassLikeStorageProvider->get('Doctrine\\DBAL\\D...')
...

```

If I comment `<pluginClass class="Weirdan\DoctrinePsalmPlugin\Plugin"/>` in psalm.xml everything works fine

**Comment by orklah** [comment]
Hi! Thanks for reporting. It's most likely related to https://github.com/vimeo/psalm/issues/7518. We're working on it. You should be able to use 4.18 in the meantime

**Comment by inlb** [comment]
Same exception with 4.18 and weirdan/doctrine-psalm-plugin v2.1.0. And only downgrading to v2.0.1 resolves the problem

**Comment by inlb** [comment]
psalm 4.19 with weirdan/doctrine-psalm-plugin v2.0.1 also works without exception

**Comment by orklah** [comment]
Oh, so it's not the same issue then. Could you open an issue on doctrine psalm plugin? It seems to be the culprit
