### ISSUE TITLE
Callables with union types and argument names syntax are not supported

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#7527]
This works fine

```php
@psalm-type T callable(int $int):string
@psalm-type T callable(?int):string
@psalm-type T callable(int|null):string
```

But neither of this

```php
@psalm-type T callable(int|null $i):string
@psalm-type T callable(?int $i):string
```

https://psalm.dev/r/ddc4117a1d

AFAIK there's some kind of parity between syntax supported by phpstan and psalm https://phpstan.org/writing-php-code/phpdoc-types#callables

**Comment by orklah** [comment]
Yeah, the parser has limited support for variable names in callables. This has been reported already somewhere but for other similar syntax.

Note that this works fine: https://psalm.dev/r/058563626a

**Comment by simPod** [comment]
> Note that this works fine: https://psalm.dev/r/058563626a

Thanks, I wanted to express that by first example but removed `|null` accidentally :/

**Comment by weirdan** [comment]
Works now: https://psalm.dev/r/ddc4117a1d
