### ISSUE TITLE
TypeParseTreeException in v2.0.0

### ISSUE THREAD

**Issue by polothy** [vimeo/psalm#753]
When I run this [code](https://getpsalm.org/r/3f354ae2fc) through v2.0.0 locally, it gives me one of these:
```
Fatal error: Uncaught Psalm\Exception\TypeParseTreeException: Unrecognised character in type in /path/to/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Type.php:86
Stack trace:
#0 /path/to/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(588): Psalm\Type::parseString('')bar/')')
#1 /path/to/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(116): Psalm\Type\Reconciler::reconcileTypes('')bar/')', Object(Psalm\Type\Union), '$pattern', Object(Psalm\Checker\StatementsChecker), Object(Psalm\CodeLocation), Array, false)
#2 /path/to/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/BinaryOpChecker.php(113): Psalm\Type\Reconciler::reconcileKeyedTypes(Array, Array, Array, Array, Object(Psalm\Checker\StatementsChecker), Object(Psalm\CodeLocation), Array)
#3 /path/to/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(187): Psalm\Checker\Statements\ in /path/to/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Type.php on line 86
```

When I run with `--debug-by-line` it fails on line 15, `if ($pattern === $getString && $count > 0) {` and it seems tied to related to this variable definition: `$getString = '/(_string.*,.*)("|\')bar/';`.  If I change it to `$getString = 'bar';` then no exception.

Cheers!

**Comment by muglug** [comment]
Sorry - should have a fix tonight or tomorrow.

**Comment by mrmark** [comment]
No worries, thanks so much for looking!

**Comment by muglug** [comment]
Fixed in master. It's a bad hack (preventing those special strings from become literal string types) until I complete work on https://github.com/vimeo/psalm/compare/more-literal-strings, which will fix the issue more robustly.

**Comment by mrmark** [comment]
Fixed, thanks!
