### ISSUE TITLE
Parsing array shapes is somehow greedy and having gql within a docblock causes parse error

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#7531]
I have an array shape in a doc block

```php
@psalm-type sth array{
   ...
 }
```

that is followed by gql snippet

```gql
 *     fragment A($var: Boolean = false) on T  {
 *       ...
 *     }
```

that contains `{` and `}`. Those cause psalm to fail parsing the shape:

https://psalm.dev/r/176bfc4220

**Comment by weirdan** [comment]
https://psalm.dev/r/176bfc4220

**Comment by weirdan** [comment]
Works now: https://psalm.dev/r/da32da50a3
