### ISSUE TITLE
False Positive: TypeDoesNotContainType: Values int(1) and int(2) can never be identical

### ISSUE THREAD

**Issue by mrmark** [vimeo/psalm#754]
Example: https://getpsalm.org/r/26a011182a

I'm using dev-master as of today (ec381308ddeb9e0e264eda8802d36815fa60b61e).

Cheers!

**Comment by muglug** [comment]
This is fixed now

**Comment by mrmark** [comment]
Thanks so much for fixing the random issues that I find!  Really is appreciated 😃 Not sure how you do it so quickly, it's amazing!
