### ISSUE TITLE
`use const Foo\foo;` infer const type as mixed

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#7541]
It seems Psalm already support const with new expression: https://psalm.dev/r/a273debeb2

But if I import const from other file Psalm infers it as mixed.

file1.php:
```php
<?php

namespace Foo;

final class Foo {}
const foo = new Foo();
```

file2.php:
```php
<?php

namespace Bar;

use const Foo\foo;

$_foo = foo;
/** @psalm-trace $_foo */ //$_foo is mixed
```

**Comment by orklah** [comment]
Does it infer it as the real type when the const contains something that is not an object?

**Comment by orklah** [comment]
It seems to happen here: https://github.com/vimeo/psalm/blob/5758d3116117423f540c15c721d8213edc22e47b/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php#L286

SimpleTypeInferer must not be able to simply infer the object yet
