### ISSUE TITLE
Checking variable's type doesn't exclude it from the method's return types

### ISSUE THREAD

**Issue by jaydiablo** [vimeo/psalm#755]
I don't think that issue title is the best, but easier to show with code:

```php
<?php
  
class A {
 
  public function test(): stdClass
  {
    $user = 'jane';
    
    $status = $this->check($user);
    if ($status !== true) {
      // Will only be stdClass here, not `true`
      return $status;
    }
   
    $status = new stdClass();
    return $status;
  }
  
  /**
   * @return stdClass|true
   */
  public function check(string $user)
  {
   	 if ($user === 'carl') {
      	return true; 
     } else {
        return new stdClass();
     }
  }
}
```

The `check` method only returns `stdClass` or `true`, but if I check that a variable that holds that return `!== true` psalm doesn't seem to remove `true` as a possible return type in the `test` method.

https://getpsalm.org/r/f70e9e8818

**Comment by muglug** [comment]
Yeah, it currently only removes `false`, not `true`. Will fix.
