### ISSUE TITLE
Support for properties in interfaces extending `\UnitEnum` & `\BackedEnum`

### ISSUE THREAD

**Issue by whatUwant** [vimeo/psalm#7551]
https://psalm.dev/r/f798b76295

`\UnitEnum` has property `name`.
`\BackedEnum` extends `\UnitEnum` and has additional property `value`.

**Comment by orklah** [comment]
This is handled here:
https://github.com/vimeo/psalm/blob/82d84b0b3aec2ce94d9f8ad020921b459a9d4874/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php#L1012

I didn't thought about inheritance when I added this condition.

This should be easy to fix though, you can look into $interface_storage, it should contain a property $parent_interfaces filled with the interfaces extended by the current interface. You just have to check if those two are in the parents

**Comment by whatUwant** [comment]
The fix seemed easy to me at first but there came a new issue of determining return type. I'm not so familiar with the ins and outs of psalm code and had to give up on it.

**Comment by orklah** [comment]
there's no return type for this method. It's a void method. All that matters is that if you enter the conditional, it emits the issue, if you don't enter it, the issue won't be emitted

**Comment by whatUwant** [comment]
This is the change I proposed
```diff
            if (!$class_exists &&
                //interfaces can't have properties. Except when they do... In PHP Core, they can
-               !in_array($fq_class_name, ['UnitEnum', 'BackedEnum'], true)
+               !in_array($fq_class_name, ['UnitEnum', 'BackedEnum'], true) &&
                !in_array('UnitEnum', $codebase->getParentInterfaces($fq_class_name))
            ) {
```
with these 2 new test cases https://github.com/vimeo/psalm/issues/7551#issue-1120736339

And the test result is
```
Psalm\Exception\CodeException : MixedReturnStatement - src/somefile.php:8:66 - Could not infer a return type
 /psalm/src/Psalm/IssueBuffer.php:314
 /psalm/src/Psalm/IssueBuffer.php:149
 /psalm/src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php:343
 /psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php:543
 /psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php:206
 /psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php:473
 /psalm/src/Psalm/Internal/Analyzer/ClosureAnalyzer.php:205
 /psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php:319
 /psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php:78
 /psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php:569
 /psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php:206
 /psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php:205
 /psalm/tests/TestCase.php:135
 /psalm/tests/Traits/ValidCodeAnalysisTestTrait.php:87
```

**Comment by orklah** [comment]
Oh, I get it now, thanks!

Seems like we also miss inheritance for properties. I'll try to take a look

**Comment by AndrolGenhald** [comment]
> Seems like we also miss inheritance for properties. I'll try to take a look

Oh, yeah, that makes sense given that interfaces can't have properties...except when they can. Maybe just hard-code it like [here](https://github.com/vimeo/psalm/blob/ff2636eed80624a3af648628d450b08dabe3a0a8/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php#L207) (I think that's the spot at least, but maybe that's only for actual enums, so it might need reworked a bit)? I can't imagine this sort of thing will be common.
