### ISSUE TITLE
`$tmp_parent_var` pollutes context

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#7556]
@vincent4vx re #7414
https://psalm.dev/r/49d35dd90e
Looks like the [same applies](https://psalm.dev/r/e3c3120f6c) to `$tmp_mixin_var`, so that can probably be fixed at the same time in the same manner.

It would also be a good idea to use `$__tmp_parent_var__`, with underscores like MatchAnalyzer and ArrayMapReturnTypeProvider so that it's less likely to collide with an actual variable.

It also doesn't work [with static](https://psalm.dev/r/65b4820537), but that's a separate issue.

**Comment by vincent4vx** [comment]
I'll do that :wink: 

But third error, it's seems that psalm do not support syntax `@method static method(): returnType`. When declaring return type before the method name it works : https://psalm.dev/r/8d800f5e5d
It's also the phpstan's behavior.
