### ISSUE TITLE
Uncaught Error: Class "DOMDocument" not found

### ISSUE THREAD

**Issue by PythooonUser** [vimeo/psalm#7560]
## Summary
I use the VSCode extension for running Psalm inside the editor. When opening a PHP Symfony project, Psalm crashes immediately multiple times and shuts down.

The error is as follows:
```
[INFO] Starting language server
[INFO] Psalm Version was detected as 4.19.0
[ERROR] Uncaught Error: Class "DOMDocument" not found in /path/to/project/vendor/vimeo/psalm/src/Psalm/Config.php:707
Stack trace:
#0 /path/to/project/vendor/vimeo/psalm/src/Psalm/Config.php(734): Psalm\Config::loadDomDocument()
#1 /path/to/project/vendor/vimeo/psalm/src/Psalm/Config.php(697): Psalm\Config::validateXmlConfig()
#2 /path/to/project/vendor/vimeo/psalm/src/Psalm/Config.php(661): Psalm\Config::loadFromXML()
#3 /path/to/project/vendor/vimeo/psalm/src/Psalm/Internal/CliUtils.php(491): Psalm\Config::loadFromXMLFile()
#4 /path/to/project/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(255): Psalm\Internal\CliUtils::initializeConfig()
#5 /path/to/project/vendor/vimeo/psalm/psalm-language-server(7): Psalm\Internal\Cli\LanguageServer::run()
#6 {main}
(Psalm 4.19.0@a2ad69ae4f5ab1f7d225a8dc4e2ec2d9415ed599 crashed due to an uncaught Throwable)
```

When running Psalm via CLI, `$ vendor/bin/psalm`, everything works normal.

Which additional information do you need?

### System Info
-   PHP version: PHP 8.1.2 (cli) (built: Jan 24 2022 10:43:09) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
-   Psalm version: 4.19.0

### User Settings
```
phpExecutablePath: "/usr/bin/php"
phpExecutableArgs: ["-dxdebug.remote_autostart=0","-dxdebug.remote_enable=0","-dxdebug_profiler_enable=0"]
psalmVersion: null
psalmScriptPath: "vendor/vimeo/psalm/psalm-language-server"
psalmScriptArgs: []
disableAutoComplete: false
maxRestartCount: 5
unusedVariableDetection: false
enableVerbose: false
connectToServerWithTcp: false
enableUseIniDefaults: false
logLevel: "INFO"
analyzedFileExtensions: [{"scheme":"file","language":"php"},{"scheme":"untitled","language":"php"}]
configPaths: ["psalm.xml","psalm.xml.dist"]
hideStatusMessageWhenRunning: true
```

**Comment by PythooonUser** [comment]
@psalm-github-bot I'm afraid this is an issue with the language server and not PHP code validation.

**Comment by orklah** [comment]
This looks like a missing Dom extension, but if you say that vendor/bin/psalm runs normally, it's weird.

Are you sure you have only one version of php? Or maybe a different ini file depending on the way you run php?

@tm1000 Is there anything in the vscode plugin that could change the php configuration?

**Comment by PythooonUser** [comment]
Yeah, my bad. I had this issue time ago and just remembered how I fixed it.

Had to run `$ sudo apt-get install php8.1-xml` indeed.

But I actually just have this one version of PHP installed, yes.

**Comment by PythooonUser** [comment]
Would it make sense to throw an exception when the XML extension is not available?

**Comment by tm1000** [comment]
@orklah we should actually define this as a requirement in composer.json of psalm

**Comment by orklah** [comment]
@tm1000 we have it :) 
https://github.com/vimeo/psalm/blob/4.x/composer.json#L20

unless run without platform requirement, composer should check this at install

**Comment by tm1000** [comment]
Ok we actually already require it (https://github.com/vimeo/psalm/blob/4.x/composer.json#L20)

I've seen this happen before in another project I used to work for (@freepbx). Even if you require it sometimes PHP doesn't load it. 

We could just check for the class as well and die/exit with a nicer error?

**Comment by orklah** [comment]
Yeah, a nicer error would be great. I'll flag this as enhancement :)

**Comment by PythooonUser** [comment]
Okay, I re-checked the issue just now.

When the XML extension is not loaded, BOTH the language server and the CLI don't work. Which makes sense, right?

Not sure how I missed it, but I ran the language server locally and the CLI in my docker container (where the extension is installed already).

However, I created a fresh PHP project, installed Psalm and it did not tell me about to require the extension. So I think having a nicer error message shown would be great!

CC @AndrolGenhald

**Comment by PythooonUser** [comment]
Also, maybe the `php-dom` extension is not correct anymore?

When I try to install it, it redirects me to the `php-xml` extension.

```
$ sudo apt-get install php8.1-dom
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'php8.1-xml' instead of 'php8.1-dom'
The following NEW packages will be installed:
  php8.1-xml
```

**Comment by AndrolGenhald** [comment]
> Also, maybe the `php-dom` extension is not correct anymore?

It's correct. The dom extension requires the xml extension, I would guess Debian or Ubuntu decided to package them together since they're closely related, but they're still separate extensions to PHP.

**Comment by weirdan** [comment]
Fixed in #8771

**Comment by PythooonUser** [comment]
Thanks @weirdan !

**Comment by weirdan** [comment]
Actually it wasn't :disappointed:
