### ISSUE TITLE
MixedArrayAssignment when anonymous function inherits array by-reference

### ISSUE THREAD

**Issue by stevekr** [vimeo/psalm#7568]
Getting MixedArrayAssignment "Cannot access array value on mixed variable $test"
```
$test = [];
function () use (&$test): void {
    $test[] = 'test';
};
```

https://psalm.dev/r/df31c7bbd2

**Comment by AndrolGenhald** [comment]
This is correct, when `use`ing a non-reference changing it later doesn't cause the code to fail. When using a reference it can: https://psalm.dev/r/9e9cada79b https://3v4l.org/aHTC1

**Comment by stevekr** [comment]
Thanks for the info :)

**Comment by AndrolGenhald** [comment]
@orklah We may want to take another look at this if we ever introduce a tag to constrain a variable's type (I know this has been discussed, but I don't remember where). [This](https://psalm.dev/r/ded8bb1120) should be fine.
