### ISSUE TITLE
Generic child classes not detected

### ISSUE THREAD

**Issue by mkroeders** [vimeo/psalm#7569]
Code: https://psalm.dev/r/2e705d804a

My understanding of type checking is that this should be ok, because the code is tightening from `odd` to `one`.

**Comment by AndrolGenhald** [comment]
It works fine if you declare the template as covariant: https://psalm.dev/r/7d2b3cdedd
See [here](https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance). If you don't want the template to be covariant, you'll have to explicitly upcast: https://psalm.dev/r/27a72dd106

**Comment by mkroeders** [comment]
@AndrolGenhald thanks for the explanaition never thought about it that way.
