### ISSUE TITLE
FunctionLikeDocblockScanner exception

### ISSUE THREAD

**Issue by AdamCoulterOz** [vimeo/psalm#7571]
While starting the language server in vscode, on macos, with php 7.2:

```
Server initialization failed.

Message: Exception: RuntimeException PHP Error: Uninitialized string offset: 0 in 
~/.composer/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php:449
Emitted in 
~/.composer/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
```

**Comment by AdamCoulterOz** [comment]
@psalm-github-bot - its not a functional issue... it can't start the language server because of a reference bug

**Comment by AdamCoulterOz** [comment]
@weirdan - how do I start the language server from cli?

**Comment by weirdan** [comment]
So it's something having to do with the code at those last lines
```
Deep scanning /ProjectFolder/www/******.php
Parsing /ProjectFolder/www/******.php
Parsing /ProjectFolder/www/******.php
Parsing /ProjectFolder/www/******.php
Parsing /ProjectFolder/www/******.php
```

Mind posting them? Or devising a reproducer on psalm.dev?

**Comment by AdamCoulterOz** [comment]
@weirdan They are very large 400+ line files with references to other classes etc. I'm not quite sure how to reproduce it?

Also, I can't publicly share the code as it's part of a proprietary production system which I can't compromise.

Could I share it with you privately?

**Comment by weirdan** [comment]
> They are very large 400+ line files with references to other classes

But log entries point to specific code lines.

> Could I share it with you privately?

Sure. If that happens to be hosted on GitHub, you can add me as a collaborator. Otherwise, contact me on either Symfony Slack (`@weirdan`, symfony-devs.slack.com) or Twitter (`@weirdan`), and we can arrange the access.

**Comment by AdamCoulterOz** [comment]
@weirdan - I invited you to dm on slack ...

<img width="467" alt="image" src="https://user-images.githubusercontent.com/6822248/154869258-ed7c33cd-e5c9-4e37-8c56-48954f228871.png">
