### ISSUE TITLE
EmptyArrayAccess is assumed on property once set forever

### ISSUE THREAD

**Issue by jsiefer** [vimeo/psalm#7572]
Sample: https://psalm.dev/r/627362a6fb

Hi, 

Psalm seems to keep the value (empty-array) of a property, though a preceding function call could have changed its value.

**Comment by orklah** [comment]
There is a setting in psalm.dev (and in your config.xml) that forbid Psalm to "remember" the type of a property when it goes through methods like this: https://psalm.dev/r/0784e6ff68

But beware, it is likely to make Psalm less smart about other pieces of code.

You should consider avoiding these constructs for clarity of code

**Comment by jsiefer** [comment]
Right, I'll work something out, I'd rather keep that option enabled for know. Thank you!
