### ISSUE TITLE
Possible XSS on psalm.dev?

### ISSUE THREAD

**Issue by Patrick-Remy** [vimeo/psalm#7609]
I accidentally found out, that the psalm.dev playground renders the generated errors without escaping HTML chars.

Unfortunately I didn't find a security policy for this project or any other way to contact you @orklah @weirdan 

https://psalm.dev/r/8754ae5fb4

**Comment by Patrick-Remy** [comment]
Thanks for your fast fix and the note to your reachability!

I think this broke the highlighting inside output?

![image](https://user-images.githubusercontent.com/20044441/153069210-329b41b3-26e0-445a-b980-0a7eee84214a.jpeg)

**Comment by orklah** [comment]
Well, to be honest, I'm not really familiar with JS so I took an escape function that was already used somewhere else. It seemed to look like the solution I found on stackoverflow as well so I didn't look further. My priority was to fix the breach.

Can you create an issue on psalm.dev repo to get this fixed? Maybe someone more familiar than me with JS will take the task
