### ISSUE TITLE
UndefinedFunction not suppressed when set in config

### ISSUE THREAD

**Issue by cklm** [vimeo/psalm#7610]
We have the same problem as in #4773 - when running psalm as PHAR it does not know about the polyfill-functions from newer php-versions.

So we want to suppress these errors with the following entry in psalm.xml:
```xml
<issueHandlers>
    <UndefinedFunction>
        <errorLevel type="suppress">
            <referencedFunction name="str_starts_with" />
            <referencedFunction name="array_key_last" />
        </errorLevel>
    </UndefinedFunction>
</issueHandlers>
```

However, that does not work, psalm still gives UndefinedFunction-errors where the two functions are used. Changing the type from `suppress` to `info` also does not work. 
Are we setting this option wrong or is this a bug in psalm?

**Comment by weirdan** [comment]
Could you provide a GH repository with a minimal reproducer?

**Comment by cklm** [comment]
> Could you provide a GH repository with a minimal reproducer?

sure, please see here: https://github.com/cklm/vimeo-psalm-7610

**Comment by weirdan** [comment]
Thanks. It seems that Psalm fails to see the polyfilled function when it's called using namespace fallback from a namespaced scope.

Workarounds:
1. import your functions with `use function str_contains;`
2. use a fully qualified function reference: `if (\str_contains(.....))` (note the backslash)

**Comment by cklm** [comment]
Wow, thanks for the good work, guys!
