### ISSUE TITLE
False-positive for "unused" variable in try-catch

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#7613]
https://psalm.dev/r/585b7b7e67

**Comment by weirdan** [comment]
I would expect `$step = 'zero';` to be marked as unused.

**Comment by zerkms** [comment]
That too: without `zero` `$step` is thought to be possibly undefined.

**Comment by AndrolGenhald** [comment]
> I would expect `$step = 'zero';` to be marked as unused.

I think Psalm just assumes it's possible that an exception is thrown immediately upon entering a `try` block, and makes no attempt to understand that `$step = 'one'` will always happen.
