### ISSUE TITLE
Sort invalidates non-empty-list assertions

### ISSUE THREAD

**Issue by SLaVeZ** [vimeo/psalm#7615]
Without sort https://psalm.dev/r/eeb9d954f9
With sort https://psalm.dev/r/88c8ae8075

**Comment by orklah** [comment]
Indeed, you'd need to refine the stub with a conditional return in order to handle the non-empty case: https://github.com/vimeo/psalm/blob/4.x/stubs/CoreGenericFunctions.phpstub#L203

Note that other sort function seems affected too

**Comment by AndrolGenhald** [comment]
I prefer `array<T>` syntax over `T[]`, but that looks good!

**Comment by hirokinoue** [comment]
Thanks! I'll follow that way.

In the code below, the assertion of `$b`  is `list<int>` currently. After applying the change above the assertion of `$b`  is `non-empty-list<int>`. Is it OK to create a PR to 4.x or should it target master?
```
$b = ["b" => 5, "a" => 8];
sort($b);
```

**Comment by AndrolGenhald** [comment]
4.x is probably fine for these since they're just stub changes, are you planning to do all of the sort functions?

**Comment by hirokinoue** [comment]
Thanks! I got it.

> are you planning to do all of the sort functions?

I'm planning to do sort functions such as rsort(), shuffle(), sort(), uasort(), uksort() and usort(), which are in the `CoreGenericFunctions.phpstub`.
