### ISSUE TITLE
failing CI on 4.x

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#7616]
Something must have changed on the CI on 4.x. A run from a few days ago that passed is now failing on rerun:
https://app.circleci.com/pipelines/github/vimeo/psalm/8420/workflows/e0559bf5-9d8e-484a-a4cd-f54dfb49dc71/jobs/31963

**Comment by weirdan** [comment]
Dependencies may have been updated. I see there are quite a few deps referencing `dev-master`. With that said, the specific list of errors currently reported looks awfully familiar.

**Comment by orklah** [comment]
This was resolved
