### ISSUE TITLE
`$this` cannot be referenced in immutable enums?

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#7629]
Perhaps a misunderstanding question, but https://psalm.dev/r/83ff12ab7a should probably work:

```php
<?php

/** @psalm-immutable */
enum MyEnum
{
    case FOO;
    case BAR;
    
    /** @psalm-pure */
    public function someSwitch(): int
    {
        return match ($this) {
              self::FOO => 1,
              self::BAR => 2,  
        };
    }
}
```

```
Psalm output (using commit c885dbc): 

ERROR: [ImpureVariable](https://psalm.dev/235) - 12:23 - Cannot reference $this in a pure context
```

Shouldn't an immutable object be allowed in a pure function? :thinking: 

Related: https://github.com/vimeo/psalm/issues/7438

/cc @lucian-Olariu @mitzaalex

**Comment by Ocramius** [comment]
> told that an immutable class can contain a mutable object (as a property)

Uhhh, that seems extremely wrong upfront :| Perhaps 5.0 should make this a bit more "safe", and prevent non-`@psalm-immutable` references inside object state?

**Comment by weirdan** [comment]
Discussed in #6881

**Comment by AndrolGenhald** [comment]
I'm in favor of `@psalm-immutable-strict` or similar to allow reading but not writing `$this` properties, and requiring all properties to be immutable. I think that would solve #7438 as well, it seems to be the same issue as #6881 if I understand correctly.

**Comment by Baptouuuu** [comment]
Isn't the problem in the given example the `@psalm-pure` annotation ? If I'm not mistaken all methods of an immutable object are by definition pure and here the `@psalm-pure` override the default behaviour and forbid the use of `$this`.

See https://psalm.dev/r/24faca0cfb

**Comment by Ocramius** [comment]
@Baptouuuu if the `$this` is immutable, or if you call an immutable method on that, it should be OK.

**Comment by Ocramius** [comment]
This seems to be another variation of `@psalm-pure` vs `@psalm-mutation-free`.

Annotating the class as `@psalm-immutable`, then skipping `@psalm-pure` on instance methods seems to work:

https://psalm.dev/r/07285c1b10
