### ISSUE TITLE
Incorrect list comparison when overriding type

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#7639]
I'm really confused by this one, why would it be different when using `@var` vs inferring?

https://psalm.dev/r/c871a0204d
https://psalm.dev/r/80e305d4b2

**Comment by orklah** [comment]
TKeyedArray has a is_list property that's hidden. It's only set for array creation like `$arr[] = ...` or `[..., ..., ...]`. When a TKeyedArray has the is_list property to true, it's actually compatible with a list.

In your case, Psalm can't know if you have a sealed `array{0?: 'a'|'b'}` or if you have undocumented offset in there too, so it can't be matched with a list

**Comment by AndrolGenhald** [comment]
Oh, of course. Whenever I forget about sealed vs unsealed it's always what causes the behavior that confuses me. I really need to get around to allowing type hinting of sealed arrays.

**Comment by orklah** [comment]
Note that I'm not completely sure sealed array would have worked here (though a sealed array with only a 0 offset should work like a list, I'm not sure it actually does right now)
