### ISSUE TITLE
Backed enums not correctly returning as instances of enums

### ISSUE THREAD

**Issue by davidbyoung** [vimeo/psalm#7654]
Sorry, the title is a little vague, but when I am setting a variable to a backed enum value, and then checking if it's an instance of that backed enum, Psalm gets a little tripped up.  In my example below, `$intCode` will always be an integer.

https://psalm.dev/r/6953255922

**Comment by weirdan** [comment]
But ultimately `enum(Code::Ok)` and `Code` should be collapsed into `Code` when used in a union.
