### ISSUE TITLE
Parameter $line does not exist on function ErrorException::__construct

### ISSUE THREAD

**Issue by chloekek** [vimeo/psalm#7658]
The `ErrorException` constructor takes a parameter called `line`, but Psalm disagrees.

Source code: https://github.com/php/php-src/blob/0b524a56f5ed1fa878a7f1f402643eb0aa52b09b/Zend/zend_exceptions_arginfo.h#L51-L58
3v4l example (runs fine): https://3v4l.org/E6A1i
Psalm example (fails type checking): https://psalm.dev/r/acebce1efa

```php
<?php

new ErrorException(line: 1);
```

The other parameters (`message`, `severity`, `filename`) are all known to Psalm; only `line` appears to be problematic.

**Comment by weirdan** [comment]
If you're up for a PR you can find a guide on callmap editing here: https://psalm.dev/docs/contributing/editing_callmaps/

**Comment by chloekek** [comment]
Seems like the parameter was renamed in this commit: https://github.com/php/php-src/commit/4c821cf20668776737272587e7a87876b4fca25e

I’ll add it to the relevant callmap delta and make a PR.

**Comment by weirdan** [comment]
You can omit delta in this case. The rename happened prior to 8.0 stable, and before 8.0 parameter names were ignored anyway. So it's safe to update `Callmap_historical` instead of putting this into a delta.
