### ISSUE TITLE
Cannot declare class LogicException

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#767]
This may or may not be a problem, as it has not necessarily caused any issues for me, but I thought you might want to know. PHP 7.2.5 will not run or lint the file `vimeo/psalm/tests/stubs/logicexception.php` without an error message:

`php -l ./vendor/vimeo/psalm/tests/stubs/logicexception.php`
`PHP Fatal error:  Cannot declare class LogicException, because the name is already in use in ./vendor/vimeo/psalm/tests/stubs/logicexception.php on line 9
Errors parsing ./vendor/vimeo/psalm/tests/stubs/logicexception.php`

Related information: http://php.net/manual/en/class.logicexception.php

**Comment by muglug** [comment]
Yeah, not an issue - stubs are designed to tell Psalm more information that reflection provides.
