### ISSUE TITLE
Incorrect type for RuntimeException::getCode()

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#7672]
https://psalm.dev/r/512ac9662c https://3v4l.org/RBCW0

@VincentLanglet re #7390

I suggest copy/pasting https://github.com/vimeo/psalm/blob/06ce3adba5dca8491ba144256d0abccc060f7984/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php#L99 and doing a `RuntimeException::class` check as well.

Also, PDOException should return `int|string` (or maybe `0|string` but I'm not sure): https://3v4l.org/9vu2u

**Comment by VincentLanglet** [comment]
I followed PHPStan on this https://phpstan.org/r/42089d28-dbaa-4b67-ac00-154372ce55a8
But indeed, it need to be fixed.

**Comment by orklah** [comment]
PDOException is a child of RuntimeException? :o

What a mess :( ...

**Comment by VincentLanglet** [comment]
I just opened an issue https://github.com/phpstan/phpstan/issues/6651 and a PR https://github.com/phpstan/phpstan-src/pull/1018 on PHPStan. I'll hope it will be reviewed quickly to be sure phpstan is going in the same direction.

Do you want to make the fix on psalm @AndrolGenhald or should I ?

**Comment by AndrolGenhald** [comment]
You can go ahead, I'm in the middle of rewriting TryAnalyzer.

**Comment by VincentLanglet** [comment]
I made https://github.com/vimeo/psalm/pull/7673. But I would recommend to wait for a response from the phpstan-side in order to copy the behavior.
