### ISSUE TITLE
Make maximum TLiteralString length configurable

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#768]
E.g. enforce a minimum of 30, but let users raise that in psalm.xml.

Higher limits may be useful for plugin developers (e.g. to analyze uses of sql statements, HTML template languages, etc)

**Comment by muglug** [comment]
What if I made this into a constant defined when loading the config? It'd be impossible to test, but still pretty performant.

**Comment by TysonAndre** [comment]
That'd be fine for my purposes.

**Comment by muglug** [comment]
I expanded it to 50, still haven't addressed this

**Comment by TysonAndre** [comment]
I noticed that you added phpmyadmin/sql-parser as a dependency. This is a strange distinction to me, and it'd make more sense just to make the maximum length configurable without that dependency

- there are other queries - `INSERT INTO (....long....) VALUES (......LONG......)` does not have the substring `select`
- The sql-parser targets the mysql dialect of sql and does not support all language features - other sql dialects have incompatible syntax which it'd fail to recognize. Instead, it'd make more sense for the plugins to do the checking if TLiteralString was valid sql.

  e.g. these keywords ('MERGE', 'RETURNING', 'FETCH', 'START', 'WITH', 'STD', 'KEY', 'UNION ALL') cause false positives with that library for my use cases  https://github.com/TysonAndre/PhanSQLPlugin/blob/master/src/PhanSQLPlugin.php#L131-L133
- Are there any plugins yet (didn't see any in google search)? https://github.com/TysonAndre/PhanSQLPlugin may be useful as a reference, but it's too overspecialized for syntax it uses to be useful

**Comment by LeSuisse** [comment]
It looks this one can be closed, the enhancement seems to have been implemented in d1f4622a80009a5beb3dc0706b850633ae57febd.

**Comment by muglug** [comment]
Thanks!
