### ISSUE TITLE
Include php standard behaviour into custom function

### ISSUE THREAD

**Issue by AurelienTisserand** [vimeo/psalm#769]
Hello, 

I wonder if it is possible to configure PSALM for not showing issue about null variable if my code runs a function testing nullability of my var. Bellow one very simple example, not very interesting but showing my problem. I have a function "isValidString" checking for a string to be not null and a string.
`function isValidString($myVar) : bool {
return ($myVar !== null && internalVerification($myVar));
}`
`$myString = getMyString(); 
if(isValidString($myString){
  echo 'Ma chaine'.$myString;
}
`
In this example PSALM show the following issue: Cannot concatenate with a possibly null string|null 

I want PSALM to understand that calling isValidString should assume that $myString is not null. Is this possible ? I watch the psalm customed annotation but i did not find a way to do that...

Thanks by advance.

**Comment by weirdan** [comment]
Psalm has a similar feature, but it assumes a bit different pattern: the function has to include 'assert' in its name and it should throw on invalid inputs.

See it in action: https://getpsalm.org/r/8649d74175

**Comment by muglug** [comment]
Yeah. I could also add docblock support via `@psalm-assert-if-true string $x` or similar

**Comment by weirdan** [comment]
Kinda like [user-defined type guards in Typescript](http://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards)? That could be useful.

**Comment by AurelienTisserand** [comment]
Thank you weirdan and muglug ! Muglug, it will be perfect if you can add that ! Do you think that can be a part of a future release ?

**Comment by muglug** [comment]
absolutely

**Comment by AurelienTisserand** [comment]
Great ! Thank you ! Let me know when you will have a release date :)
