### ISSUE TITLE
Wrong ternary operator analyze

### ISSUE THREAD

**Issue by ValentinNikolaev** [vimeo/psalm#770]
```
ERROR: PossiblyNullReference - modules/Entity/ModuleName/File/IncludedFile.php:27:35 - Cannot call method getDownloadUrl on possibly null variable 
        return $this->getMeta() ? $this->getMeta()->getDownloadUrl() : null;
```

Analyzer doesn't check for condition. In fact, if $this->getMeta() is null then 2nd case will be fired.

@Sarana-Anna

**Comment by weirdan** [comment]
I don't think there's any guaranties that a random method returns the same instance every time it's called. Store the result of `$this->getMeta()` into a local variable and use ternary on that: https://getpsalm.org/r/c5696c1360

**Comment by muglug** [comment]
Psalm has a setting for this (but it's not yet documented).

Add `memoizeMethodCallResults="true"` to your `psalm.xml` config and this error should disappear.

**Comment by muglug** [comment]
@weirdan I wholeheartedly agree (but some love this pattern, for whatever reason).

**Comment by weirdan** [comment]
> Psalm has a setting for this (but it's not yet documented).

Does this memoize every function call? Or is there some heuristic to not memoize some methods?

**Comment by muglug** [comment]
It memoises every method call that doesn't have arguments. But it's dumb, and can lead to bugs in your code.

On the other hand, so can this (allowed by default):
```php
class Foo {
  /** @var ?int **/
  private $x;

  public function getX(): int {
    $this->x = 5;
    $this->modifyX();
    return $this->x;
  }

  private function modifyX(): void {
    $this->x = null;
  }
}
```
though Psalm allows you to forbid that behaviour with `rememberPropertyAssignmentsAfterCall="false`
