### ISSUE TITLE
UndefinedDocblockClass: Docblock-defined class, interface or enum named UnitEnum does not exist

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#7703]
We have no matches of "UnitEnum" in entire SncRedisBundle codebase, but psalm is reporting such issue on psalm @dev branch https://github.com/snc/SncRedisBundle/actions/runs/1871801246

Could be related to https://github.com/vimeo/psalm/pull/7404 @orklah ?

**Comment by weirdan** [comment]
What's the return type of `$container->getParameter()`?

**Comment by ostrolucky** [comment]
True, it contains UnitEnum https://github.com/symfony/symfony/blob/92d183eb0c1423821657f0e6d598534a9da15788/src/Symfony/Component/DependencyInjection/Container.php#L110. But there is no way around that, Symfony supports both PHP 7 and  8.1, while psalm in SncRedisBundle is running on PHP 7. Not sure why is psalm reporting issue that's actually in vendor/ and not in SncRedisBundle.

**Comment by orklah** [comment]
You call on a method that returns an unknown class, how is that an issue in vendors?

What is Psalm supposed to do when you try to cast to string a type that is not known?

I think this is more an issue with Symfony here. What if you use Symfony in a PHP 7 codebase where you have a class named UnitEnum? (or polyfills?). The docblock they use is dangerous

I guess a stub could be added to the symfony plugin to prevent `getParameter` from returning UnitEnum on PHP 7 (I think something like https://github.com/vimeo/psalm/blob/8cd5ccd076f1cc1ea4c86c5080fea5b492d32a08/stubs/CoreGenericFunctions.phpstub#L1000 may be seen as too specific to belong in the repo)

**Comment by weirdan** [comment]
You're attempting to call `__toString()` on an unknown class in some places, so the issue is technically on the SncRedisBundle's side. It'll also cause a fatal error if an enum case would actually get returned.

I think the easiest way around this is to define that interface conditionally somewhere, e.g.
```
if (!interface_exists(\UnitEnum::class)) {
  interface UnitEnum {}
}
```

**Comment by ostrolucky** [comment]
Psalm error message doesn't indicate it's complaining about trying to cast an unknown class. It indicates it doesn't like mere presence of unknown type in union of return type that's defined in vendor/. Hence the confusion. Expected issue type should be `PossiblyInvalidCast`, or maybe even do whatever you do when psalm cannot infer the type, similarly it does with mixed? Anyways yeah I think I should suppress this issue or now in sncredis.
