### ISSUE TITLE
while loop causes false positive for MixedArrayAccess, MixedOperand

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#7707]
https://psalm.dev/r/d4878dab51

**Comment by kkmuffme** [comment]
Also, getting `InvalidArrayAccess` for

`while( !empty( $post_meta[ '_foo_' . $i ][0] ) ) {`

which psalm.dev doesn't report (I'm on 4.21.0)

**Comment by orklah** [comment]
This is on purpose, Psalm doesn't know the type of `$post_meta[ '_foo_' . $i ][0]` so it treats it as mixed

You might want to document your input like that: https://psalm.dev/r/4a9e7ad23b

**Comment by kkmuffme** [comment]
@orklah when I check if it's a string, I still get the same issue though: https://psalm.dev/r/7a1fd17c23

**Comment by orklah** [comment]
This should work better: https://psalm.dev/r/8a07d81c76

Psalm don't try to infer the shape of a nested array when offsets are not simple.

**Comment by kkmuffme** [comment]
>Psalm don't try to infer the shape of a nested array when offsets are not simple.

Thanks, that really is good to know and solves my problem
