### ISSUE TITLE
False positive NonStaticSelfCall when attributes are used

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#7710]
Issue:

https://psalm.dev/r/7f3d9feda6

But this is legit usage, take a look at:

https://3v4l.org/faA2D#v8.1.3

#### Update:

Suppressing this error still leaves ``MixedArgument`` problem. Version 4.21.0 works normally, only ``dev`` fails.

**Comment by AndrolGenhald** [comment]
Fix one thing and break another. Looks like since we used to cobble together a virtual statement based on types the constants were already resolved. After I changed it to use the attribute nodes directly it no longer resolves the constant with the correct context.
