### ISSUE TITLE
Forbid implementation of UnitEnum & BackedEnum by classes

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#7722]
https://psalm.dev/r/b7187df53e
https://3v4l.org/iL7gQ

**Expected**: Psalm should warn about implementation of `Z` by `C`

**Comment by AndrolGenhald** [comment]
Also forbid implementing methods from `UnitEnum` and `BackedEnum`
https://3v4l.org/k5i42
https://psalm.dev/r/d0aece15a6

[This](https://3v4l.org/2bfve) is technically allowed since it's a `UnitEnum` and not a `BackedEnum`.
