### ISSUE TITLE
Unexpected MoreSpecificImplementedParamType with generics

### ISSUE THREAD

**Issue by ollieread** [vimeo/psalm#7728]
I'm receiving a `MoreSpecificImplementedParamType` error where I shouldn't be.

I am unable to recreate the specific issue in psalm playground, but fortunately the code that causes the issue is online here: https://github.com/smplphp/container/blob/main/src/Bindings/Builder.php#L42

The problem is that I have a class `Builder` which has a template of `A of object`. In the `Builder` class there is a method `from` which is as follows.

```php
/**
 * @param A|class-string<A> $abstract
 *
 * @return static
 */
public function from(object|string $abstract): static
{
    if (is_object($abstract)) {
        $this->abstract = $abstract::class;
        return $this->to($abstract);
    }

    $this->abstract = $abstract;
    return $this;
}
```

Psalm seems to be complaining that the docblock type `A|class-string<A>` which would be `object|string` in valid PHP code is more specific than `object|string`. 

The exact message is:

```
ERROR: MoreSpecificImplementedParamType - src/Bindings/Builder.php:42:40 - Argument 1 of Smpl\Container\Bindings\Builder::from has the more specific type '(A:Smpl\Container\Bindings\Builder as object)|(class-string<A:Smpl\Container\Bindings\Builder as object>)', expecting 'object|string' as defined by Smpl\Container\Contracts\BindingBuilder::from (see https://psalm.dev/140)
    public function from(object|string $abstract): static
```

**Comment by ollieread** [comment]
> Hey @ollieread, can you reproduce the issue on https://psalm.dev ?

I cannot

**Comment by ollieread** [comment]
It looks like the problem here is that Psalm doesn't support method level generics, but rather than say that, it just assumes it's a class, even though it cannot be found.

**Comment by orklah** [comment]
Are you sure about this docblock?
https://github.com/smplphp/container/blob/f50c493856a2912ffac419657e22362ea9fec347/src/Contracts/BindingBuilder.php#L17

`object<A>` should be `A`, no?

**Comment by ollieread** [comment]
> Are you sure about this docblock? https://github.com/smplphp/container/blob/f50c493856a2912ffac419657e22362ea9fec347/src/Contracts/BindingBuilder.php#L17
> 
> `object<A>` should be `A`, no?

Yeah, I did catch that earlier, and that actually fixed it, though it wasn't particularly clear from the error.
