### ISSUE TITLE
Narrowing down template types

### ISSUE THREAD

**Issue by egst** [vimeo/psalm#7730]
Is it possible to narrow down a template type with type checks as it happens with types of variables? (I don't know if "narrowing" is a correct term for it. Maybe "specializing"?) In the following example, the type of the `$x` variable is correctly narrowed from `T as mixed` down to `T as string`, but the type `T` itself stays just `T as mixed`. As a result, returning a string is an error, even though at this point, T is a string and the function is supposed to return T.

https://psalm.dev/r/7982a87ede

**Comment by orklah** [comment]
saying `T is a string so I can return any string` is not correct. If you declare that you return T, you must return exactly T, not `something with the same type as T`. 

Let me show you an example: https://psalm.dev/r/9cf0c4eb16
I used your foo function and I sent `'hello world'` to it, and you can see, it returns `'hello world'` in the return, not `'foo'`, not `string`.

So you can see what's wrong in your foo function. If you return `'foo'` in some cases, `'foo'` is not `'hello world'` which is another way to say `foo` is not `T`. Your function should always return `T`, so it must return `$x`

If you wanted to document what you've done in foo, the best approximation would be https://psalm.dev/r/f824f492ed.

(I'm closing this as answered but feel free to keep discussing)

**Comment by egst** [comment]
Ah, ok. I didn't think about the fact, that `string` is a super type of other types (even `class-string`, `numeric-string` etc. would brake it). So the problem is that `is_string($x)` doesn't imply that `T` is exactly `string`. And actually even `$x === 'foo'` doesn't imply that `T` is `'foo'` because the caller could see it as `string` or `nonempty-string` or any other supertype of `'foo'`. There's no way to deduce (narrow down) a template type with a run-time check inside a function, basically because only runtime type info is passed to the call.

I guess I'll have to rethink a few forced `/** @var ... */` declarations in my code then. It's not the first time that I thought that Psalm is just a bit stubborn with some typings but it was actually saving me from my incorrect conclusions.
