### ISSUE TITLE
4.21.0 phar missing

### ISSUE THREAD

**Issue by GrahamCampbell** [vimeo/psalm#7737]

**Comment by GrahamCampbell** [comment]
@psalm-github-bot N/A.

**Comment by orklah** [comment]
I was not sure how to fix that so I made a new release. Can you check if 4.22.0 has its phar?

**Comment by GrahamCampbell** [comment]
I think the issue is that only the master branch is being synced across, so all 4.x releases arebroken now.

**Comment by orklah** [comment]
Seems like 4.22.0 is available on packagist: https://packagist.org/packages/psalm/phar#4.22.0

But 4.21.0 was missing. Previous release seemed OK too.

Must have been a temporary failure
