### ISSUE TITLE
Add stub for Interface \UnitEnum not found in PHP 8.0

### ISSUE THREAD

**Issue by YetiCGN** [vimeo/psalm#7738]
I just ran into an issue with Psalm 4.22 on PHP 8.0 after updating Symfony to 5.4.5 (released a bit over 5 hours ago).

```
ERROR: UndefinedDocblockClass - src/Service/SomeService.php:283:23 - Docblock-defined class, interface or enum named UnitEnum does not exist (see https://psalm.dev/200)
            "mode" => $this->parameters->get('mode'),
```

What happened is that Symfony [introduced a Docblock type hint](https://github.com/symfony/symfony/commit/ac3661711985479ee150013f1b0aaf68f79f225f#diff-cb54946ea8e3ff2f61a882cfa22b7e4e340ade25c461356791f11b99a7b5979b) for PHP 8.1's `\UnitEnum` all over the place.

My app is still on PHP 8.0 and while I could easily upgrade it to support PHP 8.1, for now my quick solution is to implement a `\UnitEnum` stub in userland code within the project. As that is not ideal I was wondering if this stub could be included in Psalm, much alike to [how Rector is doing it](https://github.com/rectorphp/rector-src/blob/main/build/target-repository/bootstrap.php#L40)?

**Comment by YetiCGN** [comment]
Unfortunately not, psalm-github-bot, as I don't know how to switch that to run on PHP 8.0.

**Comment by orklah** [comment]
This is an issue for Psalm for a few reasons:
- we want to be able to warn about wrongly using UnitEnum in a PHP8 project (or a user who run Psalm on the wrong version)
- a project using a version before PHP8.1 could very well already have a UnitEnum class that won't match our stub
- doing this would create a precedent for other reserved keywords (what about `never` before PHP8 or things like that?) that will break analysis for older projects based on new features for new versions

I can understand the choice from Symfony not to wait until their range of version fully support a new feature, but for static analysis, this is fundamentally wrong.

About your fix, you have the correct solution but the wrong implementation, you should instead think about stubbing the class that return UnitEnum to "fix" their docblock.

However, this is exactly the kind of thing that should be handled by https://github.com/psalm/psalm-plugin-symfony. They could introduce a stub depending on the php version or a conditional return using "magic" variables `PHP_MAJOR_VERSION`/`PHP_MINOR_VERSION` to make sure to return the correct result
