### ISSUE TITLE
TypeDoesNotContainType - DateInterval does not contain false

### ISSUE THREAD

**Issue by Ne-Lexa** [vimeo/psalm#7747]
https://psalm.dev/r/07a940ed95

This is a mistake, because [`DateInterval::createFromDateString`](https://www.php.net/manual/ru/class.dateinterval.php) can return `false`. 

```php
public static DateInterval::createFromDateString(string $datetime): DateInterval|false
```

**Comment by orklah** [comment]
Seems right! The signature is detailed in https://github.com/vimeo/psalm/blob/4.x/dictionaries/CallMap.php

Care to propose a PR?

**Comment by orklah** [comment]
Indeed :)
