### ISSUE TITLE
`InvalidReturnStatement` reported when using a template type of array shape as return type, such as `@psalm-template TReturn of array{foo: int}`

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#7748]
Consider following example:

```php
<?php

/**
 * @psalm-template TParams as array{
 *      licenseId: int
 * }
 */
final class MyReportDefinition
{
    public function __construct(private int $licenseId) {}
    /**
     * @psalm-return TParams
     */
    public function getParams(): array
    {
        return [
            'licenseId' => $this->licenseId,
        ];
    }
}
```

Psalm reports ( https://psalm.dev/r/119b68d58f ):

```
Psalm output (using commit 766fc17): 

ERROR: [InvalidReturnStatement](https://psalm.dev/128) - 16:16 - The inferred type 'array{licenseId: int}' does not match the declared return type 'TParams:MyReportDefinition as array{licenseId: int}' for MyReportDefinition::getParams

ERROR: [InvalidReturnType](https://psalm.dev/011) - 12:22 - The declared return type 'TParams:MyReportDefinition as array{licenseId: int}' for MyReportDefinition::getParams is incorrect, got 'array{licenseId: int}'
 
Psalm detected 1 [fixable issue(s)](https://psalm.dev/docs/manipulating_code/fixing/)
```

Overall, I think this is related with quirkiness of `@template` with `array{ ... }` shape type definitions, but I don't have better words to match it with other potentially pre-existing issues.

Is this straight out a bug, or a limitation?

**Comment by orklah** [comment]
I'm not sure I see what the goal is here but I'd expect TParams to be bounded at some point.

Otherwise, you basically have a more complex version of this: https://psalm.dev/r/64b3326670, which outputs the same errors

**Comment by orklah** [comment]
The issue is the same IMHO

How do you intend to implement a method that can satisfy this: https://psalm.dev/r/bf23b1d902

Remember that `array{licenseId: int}` is equivalent to `array{licenseId: int, otherKey: mixed}` so `array{licenseId: int, otherKey: int}` is a valid value for your template

**Comment by Ocramius** [comment]
Will close here. The correct approach would be to use `@psalm-type` instead of `@psalm-template`, which is not being bound to anything in this case (and therefore stays abstract, which isn't useful).

Here's an example taking the OP as reference ( https://psalm.dev/r/1150420355 ):

```php
<?php

/**
 * @psalm-type TParams = array{
 *      licenseId: int
 * }
 */
final class MyReportDefinition
{
    public function __construct(private int $licenseId) {}
    /**
     * @psalm-return TParams
     */
    public function getParams(): array
    {
        return [
            'licenseId' => $this->licenseId,
        ];
    }
}
```

Closing here: sorry for not doing so earlier, @orklah!
