### ISSUE TITLE
array_column type inference

### ISSUE THREAD

**Issue by alex-dev** [vimeo/psalm#7750]
`array_column([['a' => 1], ['a' => 2]], null, 'a')` should infer a return type of `array<int, array{a: int}>`.

**Comment by alex-dev** [comment]
https://psalm.dev/r/4b8b2058fe

**Comment by orklah** [comment]
You're right. This is handled by a small 100 line plugin dedicated to array_column here: https://github.com/vimeo/psalm/blob/b924032850df54dd05ffae409a709820fd6e688e/src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayColumnReturnTypeProvider.php#L32

It must lack some case, possibly related to when the second argument is null here: https://github.com/vimeo/psalm/blob/b924032850df54dd05ffae409a709820fd6e688e/src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayColumnReturnTypeProvider.php#L84 (it checks for literal integers and literal strings but not for null)

Care to propose a PR?

Feel free to ask questions!

**Comment by mtk3d** [comment]
Hey, I tried to fix this problem, that's my proposition https://github.com/vimeo/psalm/pull/7760 😃
