### ISSUE TITLE
Feature Request: Add new scalar type non-negative-int as an alias to positive-int|0

### ISSUE THREAD

**Issue by isfedorov** [vimeo/psalm#7769]
The current set of psalm types contains `positive-int` but this type doesn't include 0 so one have to declare the type as `positive-int|0` to, for example, annotate return type of function like `length()`, `size()` etc, e.g. functions that can return 0 or some positive integer. It would be nice to add a new built-in type `non-negative-int` as an alias of  `positive-int|0` so that code would look like
```
<?php

/**
 * @param non-negative-int $i
 */
function takesAPositiveIntOrZero(int $i):void {
}

takesAPositiveIntOrZero(0);
```
https://psalm.dev/r/49624738ff

**Comment by AndrolGenhald** [comment]
Integer ranges were added some time ago, you can use [`int<0, max>`](https://psalm.dev/r/9c4982fd52) now instead.
