### ISSUE TITLE
Infer types based on psalm-flow

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#7773]
When a function defines `@psalm-flow` And the return-type is known, couldn‘t this information be utilized to specifiy/narrow the type of the parameter, which flows thru the function.

see https://psalm.dev/r/78576f9081 which shows the idea applied to strings.
It would work the same way for non-empty-array etc. - I guess.

This idea was born, as I was filling a similar but more concrete use-case for phpstan:
https://github.com/phpstan/phpstan/issues/6792

**Comment by orklah** [comment]
`@psalm-flow` is not what you want to use in this case.

The flow annotation only tells that any taint coming in is going out, but you have no idea what the function does.

It could completely transform the string (like truncate it or concatenate it). You can't deduce anything about the format of the output based on the input nor the other way around

**Comment by AndrolGenhald** [comment]
`@psalm-flow` isn't documented, but from what I gather it's really there to which arguments apply a taint to the return value, it doesn't actually say the return value will contain those arguments. For example, I believe [this](https://3v4l.org/fJGGa) is entirely valid, which makes htis impossible.
