### ISSUE TITLE
PDOStatement::fetchAll() has incorrect type

### ISSUE THREAD

**Issue by hc-jworman** [vimeo/psalm#7784]
https://psalm.dev/r/388cd46537

According to the documentation, https://www.php.net/manual/en/pdostatement.fetchall.php, PDOStatement::fetchAll() never returns false as of PHP 8.0.

**Comment by orklah** [comment]
Hi! It can be fixed here: https://github.com/vimeo/psalm/blob/4.x/dictionaries/CallMap_80_delta.php along with in CallMap.php in the same dir.

We have a documentation page to help contributing on those files: https://psalm.dev/docs/contributing/editing_callmaps/

**Comment by hc-jworman** [comment]
I'll make the PR then
