### ISSUE TITLE
Nullability of return should be inferred from typehint

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#779]
in PHP 7.1 and up:

```php
/**
 * @psalm-suppress InvalidNullableReturnStatement
 * @psalm-suppress NullableReturnType
 * @return stdClass
 */
function foo() : ?stdClass {
  return rand(0, 1) ? new stdClass : null;
}

$f = foo();
if ($f) {}
```

Expected: no issue
Actual: RedundantCondition in `if ($f)`

https://getpsalm.org/r/9d6275e373

**Comment by Wirone** [comment]
Actually my original question was slightly different, [based on `if (!$f) {}`](https://getpsalm.org/r/7d7e238232) (TypeDoesNotContainType), but genesis is the same - not getting nullability from typehint :)

**Comment by muglug** [comment]
Yup, same ultimate cause for both messages.

**Comment by muglug** [comment]
Making a note that this should also remain fine: https://getpsalm.org/r/3660cafffb
