### ISSUE TITLE
Invalid redis types

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#7794]
https://psalm.dev/r/6c1bda5975, which is weird since the callmap seems to contain the correct type.

**Comment by AndrolGenhald** [comment]
A stub was added in #7614 that overrides the CallMap. This is actually the correct type, see [here](https://github.com/vimeo/psalm/issues/7709#issuecomment-1047200294) for discussion. If you want better types you can try making a plugin, I'd suggest using a template to track pipeline/multi state, but I've had trouble with using templates for state before so I'm not sure if that would work.
