### ISSUE TITLE
Allow class names for `@psalm-internal` annotations

### ISSUE THREAD

**Issue by janopae** [vimeo/psalm#7796]
Currently, you can use `@psalm-internal A\Namespace` to make a class or method accessible only from `A\Namescpace`. This resembles `package-private` in languages like Java or C#.

These languages also know the concept of "inner classes" or "nested classes", which are classes that are only accessible from within their outer class. This is not possible in PHP, however, if Psalm allowed using `@psalm-internal A\Namespace\Classname` with class names, you could achieve something very similar.

**Comment by weirdan** [comment]
You can do that already: https://psalm.dev/r/75a2e2aeed

**Comment by janopae** [comment]
> You can do that already: https://psalm.dev/r/75a2e2aeed

Not if you explicitly define a constructor: https://psalm.dev/r/f6329c9450

Maybe it does work for the class itself, but not for methods defined in that class?

**Comment by weirdan** [comment]
Works as expected now.

**Comment by janopae** [comment]
Nice, thanks a lot!
