### ISSUE TITLE
autocomplete for array shape

### ISSUE THREAD

**Issue by ging-dev** [vimeo/psalm#7804]
I'm using Psalm Language Server with a few problems:

```php
/** @var array{name: string, deep: array{name: string}, generic: Type<B>} $data **/
....
$data[// psalm can suggest name, deep, generic

$data['deep'][// can't suggest
$data['generic']-> // can't suggest
```

Is it possible to improve the autocomplete for array?

**Comment by tm1000** [comment]
@orklah can you assign this to me. I will work on it in my work on Language Server
