### ISSUE TITLE
Variable used in closure by reference not getting typed

### ISSUE THREAD

**Issue by ciaranmcnulty** [vimeo/psalm#7805]
https://psalm.dev/r/bc013e5d2b

There are of course no native type hints in `use()` but the `$triggered` variable is treated as `mixed` inside the closure, and immediately after the closure is declared (but before it is potentially executed) the type has changed to `mixed` when really the only value it can still be is `0`

Adding `@var` inside and immediately after the closure declaration works to fix this, but I think it _could_ be inferred?

**Comment by AndrolGenhald** [comment]
This part is expected, see #7568. I think the real issue here is [this crash](https://psalm.dev/r/5f4d6eb920) and [this](https://psalm.dev/r/2e06ad994f) incorrect type inference when `use`ing a non-existent variable with and without reference.

**Comment by ciaranmcnulty** [comment]
Hm, I see. I guess the closure being declared inline made me think something more could be done
