### ISSUE TITLE
Narrower integer types in array shapes are not properly verified anymore

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#7809]
Hey there,

it seems that somewhen in older commits the validation of array shape types with more specific integer values were dropped. 
I am not 100% sure if that was the case in an earlier version but I'm pretty sure I've had this in one of our projects.

https://psalm.dev/r/0299d16957

**Comment by boesing** [comment]
I have no idea what I was reporting here. Given the comment from the github bot, the output seems legit as the function does consume an argument which is not used within the function.

**Comment by AndrolGenhald** [comment]
@boesing Isn't the issue that `$foo["bar"]` is supposed to be `int<0, max>` but you're passing `int` without error?

**Comment by boesing** [comment]
Oh, you're right! Good catch 😅
