### ISSUE TITLE
Psalm is unaware of a handful of methods on the various core reflection classes

### ISSUE THREAD

**Issue by ollieread** [vimeo/psalm#7810]
I've only created examples for the ones that I encountered, but if my understanding is correct, and `stubs/Reflection.phpstub` is how Psalm understands reflection classes, there is a lot missing.

`ReflectionProperty::hasDefaultValue()` https://psalm.dev/r/7de1ce446b
`ReflectionProperty::isPromoted()` https://psalm.dev/r/0b4cc46fd2
`ReflectionParameter::isPromoted()` https://psalm.dev/r/62322a32a6

If my assumption/understanding is correct, I'm more than happy to create a PR that updates all of the Reflection stubs to accurately match what is available.

**Comment by ollieread** [comment]
It is also unaware of `Attribute::$flags` https://psalm.dev/r/8f628693b7

**Comment by AndrolGenhald** [comment]
> I'm more than happy to create a PR

Go for it!

**Comment by ollieread** [comment]
> > I'm more than happy to create a PR
> 
> Go for it! Just be sure to use the correct `Phpxx.phpstub` for things that don't exist in all PHP versions.
> 
> 

Sorry, this got buried under mountain if other things. If this still hasn't been fixed I will take a look and create a PR for the reflection stubs.
