### ISSUE TITLE
First class callable method crashes on undefined object variable

### ISSUE THREAD

**Issue by michaeldnelson** [vimeo/psalm#7815]
https://psalm.dev/r/16a7bedf08

```php
$z = $x->do(...);
```

I would expect this to report undefined variable $x, instead it crashes with an internal error.

For additional context, I discovered this while trying recreate an  `assert(!$this->isFirstClassCallable())` error I keep getting in my project but was not able to reproduce in the online parser.  I'm hoping it is related.

Thanks!

**Comment by orklah** [comment]
Definitely related. Unfortunately, the online parser is badly configured and does not crash when asserting fail, so it just continues through it

**Comment by weirdan** [comment]
Reports `UndefinedGlobalVariable` now: https://psalm.dev/r/16a7bedf08

Likely fixed by #8814
