### ISSUE TITLE
AmbiguousConstantInheritance does not handle multiple interhitances of same interface

### ISSUE THREAD

**Issue by jasverix** [vimeo/psalm#7818]
https://psalm.dev/r/b1dfb3d8c0

We are using a similar construct. A main interface for all Services, and several interfaces for what the Service supports. The supporting interface must implement ServiceInterface, so we are clear that it is a service interface.

ServiceWithPermissionsInterface extends ServiceInterface
DistributeableServiceInterface extends ServiceInterface

etc.

Tried to add `final` to solve the problem, but it just became worse. PHP itself handles the `final` very well.
https://psalm.dev/r/99f7bf3fc4

**Comment by weirdan** [comment]
`OverriddenFinalConstant` is no longer emitted: https://psalm.dev/r/99f7bf3fc4

**Comment by gmazzap** [comment]
To add: the error is reported on the interface that declares the constant, making it even harder to find the issue.

I have a "base" interface, then 3 interfaces extending the base, and ~20 classes extending one or more of the "extending" interfaces.

I got reported 20+ identical errors  _on the base interface_, making it very hard to understand where the error is, and in the end, the error is nowhere. And if I suppress AmbiguousConstantInheritance on the base interface the errors are reported anyway. See https://psalm.dev/r/112cd6e0ac

The only solution is to suppress AmbiguousConstantInheritance globally.

**Comment by orklah** [comment]
If the two AmbiguousConstant comes from the same place, it shouldn't be considered Ambiguous at all. It should be a pretty simple fix as the two are emitted from the same file: https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php#L859

**Comment by svwezel** [comment]
I think this is still a bug!
https://psalm.dev/r/99f7bf3fc4
