### ISSUE TITLE
Psalm Trace highlights the next uncommented line if there is code after Trace

### ISSUE THREAD

**Issue by tm1000** [vimeo/psalm#7820]
I am not sure if this is intended but its more confusing in the IDE (and also in Psalm.dev)

See: https://psalm.dev/r/a897eda34d

I declare `$foo` on line 3. I declare `/** @psalm-trace $foo */` on line 5. I declare `$bar` on line 7. 

Psalm highlights line 7 with the trace declared on 5 about the variable on line 3. However the highlighted line 7 has nothing to do with the traced variable.

I feel like the trace should be set against the line where the trace actually is (line 5)

**Comment by tm1000** [comment]
I see how to fix this in the code but I'm not sure if that would be intended or not. The trace attaches itself to the next line of code because of how the parser works (The docblock itself is considered part of the next line of code). 

Therefore if I trace a variable that has not been defined but it IS defined in the next line then trace will happily output the value from that next line

https://psalm.dev/r/95abe4b651

However if the next line after trace is not relevant to watch trace is tracing then trace will output an undefined error

https://psalm.dev/r/a897eda34d

Because of the association of docblocks with proceeding code psalm-trace can sometimes be inaccurate:

https://psalm.dev/r/a06fd9ddf3

The end result is that this is either the intended operation (that psalm-trace is actually tracing the variable starting at the NEXT line) or that this is a bug

**Comment by orklah** [comment]
Yeah, we get that a lot, the behaviour can be a little counter intuitive sometimes. I made an habit to always add a comma after closing the phpdoc: `/** @psalm-trace $a */;` that way, the trace applies to the next statement, which I'm sure has no side effect and will display the value of the variable exactly between the previous and next statement

**Comment by tm1000** [comment]
@orklah ah I see. Adding the `;` makes it attach to the `;` itself and thus works exactly like you said.

If this is intended then this can be closed.

Surprisingly  Psalm.dev works almost identically to how an IDE would show statements using the Language Server functionality in Psalm which is quite handy.
