### ISSUE TITLE
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.

### ISSUE THREAD

**Issue by karaka200** [vimeo/psalm#7826]
When I install psalm package, this warning show:

`Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.`

how can I fix this warning?

**Comment by orklah** [comment]
This will be solved by Psalm 5 which is yet to be released

**Comment by dmitryuk** [comment]
https://github.com/vimeo/psalm/pull/7292

**Comment by netandreus** [comment]
+1
Just reproduced at psaml 5.0.0-beta1

**Comment by weirdan** [comment]
Fixed in `master`.

**Comment by VincentLanglet** [comment]
> Fixed in `master`.

Can't this be back-ported to psalm 4 ? The PR seems small, and there is still some Psalm 4 releases.

**Comment by dmitryuk** [comment]
+1

**Comment by in4s** [comment]
+1

**Comment by weirdan** [comment]
> Can't this be back-ported to psalm 4 ? The PR seems small, and there is still some Psalm 4 releases.

It can't. Psalm 4 supports PHP 7.1, but the replacement package version (`symfony/filesystem:5.4`) where path utils were moved is not compatible with PHP 7.1
