### ISSUE TITLE
Cannot access value on variable using a numeric-string offset, expecting int

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#7850]
https://psalm.dev/r/0e90527fa7

On the other side, phpstan is not reporting any error https://phpstan.org/r/4e68cdc3-87de-4de9-a1f1-4dd949fc92a5,
the error is only reported for a string https://phpstan.org/r/73703465-946a-4b26-806d-ffa7ad582748

The error is technically true, but I don't see a real way to solve this currently since there is no `integer-string` type.
I was wondering if relaxing the check could be considered.

At least, to me it should be a `PossiblyInvalidArrayOffset` and not a `InvalidArrayOffset` like in this example.
https://psalm.dev/r/9da6974f72

This would be already better to have the error on level 4 and not 6.

**Comment by orklah** [comment]
Is there a reason not to add a cast to int in this case?

**Comment by VincentLanglet** [comment]
> Is there a reason not to add a cast to int in this case?

If it's sure it's an `integer-string`, this is kinda redundant but yeah that's a solution.

> At least, to me it should be a PossiblyInvalidArrayOffset and not a InvalidArrayOffset like in this example.
> https://psalm.dev/r/9da6974f72

I still believe this part should be considered.
When accessing array key, `numeric-string` is the same than `int|numeric-string`.
The first one give an InvalidArrayOffset, when the second gives a PossiblyInvalidArrayOffset.

**Comment by VincentLanglet** [comment]
> > At least, to me it should be a PossiblyInvalidArrayOffset and not a InvalidArrayOffset like in this example.
> > https://psalm.dev/r/9da6974f72
> 
> I still believe this part should be considered. When accessing array key, `numeric-string` is the same than `int|numeric-string`. The first one give an InvalidArrayOffset, when the second gives a PossiblyInvalidArrayOffset.

Same exists with `numeric` https://psalm.dev/r/e6f6c73225

**Comment by orklah** [comment]
Difference between PossiblyUndefined et Undefined is processed by checking individual provided type against the expected type. This means a given type can either be valid or not, there's no "potentially valid type", because if you go that route, then mixed is a "potentially valid type" for every value

> If it's sure it's an integer-string, this is kinda redundant but yeah that's a solution.

Well not really, you're dealing with an `array<int, mixed>` so it's expecting int, not even an `integer-string`. Sure, PHP will cast that for you IF you push a compatible type, but it's kinda ugly.

**Comment by VincentLanglet** [comment]
I see, closing then
