### ISSUE TITLE
performance: parsing files multiple times

### ISSUE THREAD

**Issue by vognev** [vimeo/psalm#7873]
I've noticed, that analyzing code which is using tcpdf library (example here - https://github.com/vognev/psalmbug) 
is taking significant time.

with debug logging enabled it is seen that single `tcpdf.php` is parsed more than 150 times
https://github.com/vognev/psalmbug/blob/master/debug.log

still not fully understanding if that is really needed, but my question is about if it is possible to reduce analysis time in this case?
maybe by using/introducing volatile internal cache for reusing parsing results within single analysis run

**Comment by vognev** [comment]
by quickly hacking `src/Psalm/Internal/Provider/StatementsProvider.php` in following way:

```
        $file_content_hash = md5($version . $file_contents);

        if (!$this->parser_cache_provider
            || (!$config->isInProjectDirs($file_path) && strpos($file_path, 'vendor'))
        ) {
            static $__cache = [];

            if (array_key_exists($file_content_hash, $__cache)) {
                return $__cache[$file_content_hash];
            }

            $progress->debug('Parsing ' . $file_path . "\n");

            $has_errors = false;

            $stmts = self::parseStatements($file_contents, $php_version, $has_errors, $file_path);

            return $__cache[$file_content_hash] = $stmts ?: [];
        }
```

makes analysis run in about 12 seconds

maybe you can accept a PR containing this small fix or suggest how to implement properly that kind of volatile cache (LRU maybe)

**Comment by AndrolGenhald** [comment]
Wow, I'm surprised no one has noticed that before! We'll need to make sure the cache is appropriately invalidated for the language server, and make sure it doesn't have any weird interactions with the existing cache, but that's a fantastic improvement!

**Comment by vognev** [comment]
guess can be closed
