### ISSUE TITLE
List allows string key if it is numeric and incremental

### ISSUE THREAD

**Issue by zoltanka** [vimeo/psalm#7883]
According to [documentation](https://psalm.dev/docs/annotating_code/type_syntax/array_types/#lists) `list<Foo> is a subtype of array<int, Foo>.`

But in here: https://psalm.dev/r/eb721f68a2

**Comment by orklah** [comment]
I need to think more about this, but due to PHP weird array handling, this actually becomes a valid list:
https://3v4l.org/601RZ

**Comment by zoltanka** [comment]
> I need to think more about this, but due to PHP weird array handling, this actually becomes a valid list: https://3v4l.org/601RZ

Oh right forgot about that one... Ok this is not up to me, but I would ignore this "wierd" behavior, meaning only do the analysis check on the code. If there is a single or double quote for the key, then it's already considered to be a string key, regardless what is within.

**Comment by orklah** [comment]
I'll close this. It would feel weird to change code to make Psalm analysis diverge from PHP result. Also this is consistent with the way phpstan behaves. If this is important to you, a Psalm plugin or a CS rule could be created to forbid this syntax

**Comment by AndrolGenhald** [comment]
I've had a dream of eventually supporting some sort of strict `array<string&!int-string, mixed>` type that would ensure you never end up with an int in your array, but until/unless that happens array types are always going to be a bit weird no matter what we do (and even if we do that, you'd have to verify something like `!ctype_digit($key)` before using `$key`, which also sucks). 

There's really just not a good way to support weird PHP quirks like this, when the language itself is fighting against you there's not a lot you can do. If you really need this to work in a non-weird way, I'd just use [`Ds\Map`](https://www.php.net/manual/en/class.ds-map.php) and [`Ds\Vector`](https://www.php.net/manual/en/class.ds-vector.php) which _do_ behave normally.
