### ISSUE TITLE
Union types in @method annotations

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#789]
I've just encountered `@method returnType methodName(A|B $param)` annotation used in a popular project ([Guzzle HTTP Client](https://github.com/guzzle/guzzle/blob/0773d442aa96baf19d7195f14ba6e9c2da11f8ed/src/Client.php#L12-L23)). While it's non-standard (non-PSR5 I mean), PHPStan seems to allow it (https://phpstan.org/r/0e92f575c0d23418e8d63ecdb7a1288c). Psalm, on the other hand, rejects it:
https://getpsalm.org/r/355717ebc7

I suspect this was unintended omission from the PSR-5 draft. Would be great to see it supported in Psalm (and, eventually, in PSR-5 or whatever comes to replace it).

**Comment by muglug** [comment]
Yeah, this is slightly cumbersome on Psalm's end - I use PHPParser for those `@method` annotations, and PHPParser obviously doesn't accept union types.

The likely fix will be to add some sort of hacky placeholder (so `A|B` becomes  `A__UNIONOR__B`) so that PHPParser will parse without issue.

**Comment by muglug** [comment]
And thanks for opening this - I noticed yesterday, after adding PHP Parser 4.0.2 compatibility.

**Comment by weirdan** [comment]
Also I suspect the error handling is a bit off in this case: I'd expect psalm to consider those invalid 'virtual' methods non-existing (and do not complain unless the class is sealed), but psalm was insisting `Guzzle\Client::post()` accepts 0 arguments - so it apparently was aware of the method, even though docblock was invalid.
