### ISSUE TITLE
False Positive: InvalidAttribute

### ISSUE THREAD

**Issue by cspray** [vimeo/psalm#7898]
I have discovered what I believe is a false positive when dealing with Attributes. Specifically, I am attempting to get a `ReflectionAttribute` using a `ReflectionMethod`. I am passing an enum where the value is a string representing the type of Attribute to return. I was able to replicate this on https://psalm.dev, see https://psalm.dev/r/c00ee9b5ed.

I believe that if the enum in question was marked as being backed by a `class-string` this would not trigger an error. However, I could not determine a way to do this with the provided annotations.

Thanks, in advance, for taking the time to review this issue!

**Comment by weirdan** [comment]
I think we should preserve the class-string type on enum cases if that was what they were initialized with.

**Comment by weirdan** [comment]
This has been fixed in `master` (#10165) and will eventually be available in Psalm 6.
