### ISSUE TITLE
Since version 2.0.2 psalm includes vendor folder

### ISSUE THREAD

**Issue by fnagel** [vimeo/psalm#790]
I'm using following (shortened) configuration for a Symfony project:

````
<?xml version="1.0"?>
<psalm>
    <projectFiles>
        <directory name="src/MyVendor" />
        <ignoreFiles>
            <directory name="src/MyVendor/MyProject/Tests" />
        </ignoreFiles>
    </projectFiles>
</psalm>
````

Since version 2.0.2 psalm checks my composer vendor folder too. Moving back to 2.0.1 fixes this.
Is this a bug?

**Comment by muglug** [comment]
Not exactly a bug.

https://github.com/vimeo/psalm/releases/tag/2.0.2 introduced a change where any files that your classes depend on (either via inheritance, trait use or explicit `require` inclusion) are listed in error output. You can hide them by adding the `vendor` dir to `ignoreFiles`, but my aim was to ensure that you're aware of the problem areas even in code you don't control.

If the errors you're seeing are not in files you're extending, that's a bug.

**Comment by fnagel** [comment]
Ok, ignoring the vendor directory works as expected. Thanks for the fast response!
