### ISSUE TITLE
Missing param type causes false positive for missing type for all subsequent param/return

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#7902]
https://psalm.dev/r/af8681be3d shows a `MissingReturnType` error even though the return type is there.
When making the @param valid, the `MissingReturnType` error goes away.
https://psalm.dev/r/3027253976

https://psalm.dev/r/4011d3af99 shows `MissingParamType` for `$hello` even though it's there
but:
https://psalm.dev/r/ebd7f96328 correctly only reports `MissingParamType` only for `$bar`

Summary:
when specifying a @param without a type, this will break all subsequent param/return types and falsely report an error.

**Comment by AndrolGenhald** [comment]
Error recovery during docblock parsing is a bit harder than it seems because we support multi-line tags for things like [array shapes](https://psalm.dev/r/62de1ac672). I was worried an `@` in an array shape key would completely mess things up, but it looks like we [require](https://psalm.dev/r/2a972a82e6) that to be [quoted](https://psalm.dev/r/26fb84f6b4) already anyway, so this could probably be fixed without too much trouble.

**Comment by kkmuffme** [comment]
It's not really an issue with matching here though - psalm correctly parses it (and outputs the error)

I think it boils down to the fact that in case the param is invalid, FunctionLikeDocblockParser::parse just skips that param in further handling, thus causing all kinds of follow up issues.
e.g. [params] will only include the valid ones, which means the "params" array count does not match the actual number of @param comments specified.

**Comment by orklah** [comment]
Any error in parsing a docblock emits an InvalidDocblock and will prevent any data from being read from said docblock.

Even previously parsed tags are just ignored. This could probably be improved

**Comment by kkmuffme** [comment]
That would really be necessary, since this causes lots of false positives, e.g. the return type is not missing at all, just the @param is invalid. e.g. in this very basic case 2/4 errors are false positives due to this behavior.

**Comment by kkmuffme** [comment]
That's a good input, however in some instances it cannot be fixed (e.g. bc it's a library, and I'm not going to fix 100s of files, where there is some issue in the docblock, but the @return is fine).
But bc I call functions from this library, I don't get accurate return types, since psalm chooses to ignore the whole invalid docblock.

At least changing it for "Badly-formatted @param" extremely helpful. Right now it throws (and therefore returns from the loop)

**Comment by orklah** [comment]
Well, feel free to propose a PR to improve on that then, even if fixing the source could help every user of this library :)

**Comment by kkmuffme** [comment]
What would be the right way to do this, instead of the current "throw new" in that case? I just need a little guidance, then I will change it for all places and PR it.

The library is some proprietary crap. The only one I'd be helping with that is the vendor of it :(

**Comment by orklah** [comment]
this was fixed :)
