### ISSUE TITLE
Invalid Argument with Attributes arguments

### ISSUE THREAD

**Issue by michnovka** [vimeo/psalm#7905]
Getting lot of

```
ERROR: InvalidArgument - src/Entity/Admin.php:12:31 - Argument 1 of Doctrine\ORM\Mapping\Entity::__construct expects class-string<Doctrine\ORM\EntityRepository<object>>|null, App\Repository\AdminRepository::class provided (see https://psalm.dev/004)
#[ORM\Entity(repositoryClass: AdminRepository::class)]
```

when using `ORM\Entity` attributes in Symfony project:

```php
#[ORM\Entity(repositoryClass: AdminRepository::class)]
class Admin { //....
```

I am defining AdminRepository with these PHPDoc:

```php
/**
 * @extends ServiceEntityRepository<Admin>
 */
class AdminRepository extends ServiceEntityRepository
{
```

So I decided to make a minimal example of the issue:

https://psalm.dev/r/1df2bd0be8

**Comment by AndrolGenhald** [comment]
I think this may have gotten worked out on slack, but just for reference something like [this](https://psalm.dev/r/aaaad51d7c) needs to happen. To avoid [barking cats](https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance) templates are invariant by default, so `AdminRepository` is an `EntityRepository<Admin>`, but that's not a subtype of `EntityRepository<mixed>` as the `Entity` annotation is expecting.
