### ISSUE TITLE
Could not intersect two array shapes

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#7909]
https://psalm.dev/r/c2e2af5818

**Comment by klimick** [comment]
May be intersection doesn't work only with psalm-alias.
https://psalm.dev/r/3af7cbf3d7

**Comment by orklah** [comment]
Yeah, we're missing something to support that. I believe we already have an issue  for this

**Comment by AndrolGenhald** [comment]
Duplicate of #5148.
