### ISSUE TITLE
[TypeCoercion] argument accepted by closure is downcasted to argument accepted by default closure

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#791]
```php
<?php
  
interface File {}
  
interface HandleImageInterface
{
    public function getImage(): ?string;

    public function shouldBeImageDeleted(): bool;
}

interface ImageInterface
{
    public function setImage(?File $file): self;

    public function getImage(): ?File;
}
  
function execute(
        HandleImageInterface $dto,
        object $imageAwareEntity,
        callable $imageGet = null
    ): void {
        $imageGet = $imageGet ?: function (ImageInterface $imageAwareEntity): ?File {
            return $imageAwareEntity->getImage();
        };

        $imageGet($imageAwareEntity);
    }
```

> Psalm output (using commit c4f3bd1):
> 
> ERROR: TypeCoercion - 28:19 - Argument 1 expects ImageInterface, parent type object provided

https://getpsalm.org/r/8eb057faee

I am purposely accepting closure in that function to be able to process objects not conforming to interface default closure works with

Interesting is that I tried to fix this by annotating the closure, but ran into another bugs: https://getpsalm.org/r/831fb174ba

**Comment by ostrolucky** [comment]
I've solved this by splitting this to two methods, where one accepts non-optional closure and doesn't require $imageAwareEntity to be passed at all. Second method accepts ImageInterface and just calls first method with closure which just `uses` $imageAwareEntity, not expecting such entity will be passed into closure

**Comment by muglug** [comment]
Well this related thing is a bug: https://getpsalm.org/r/c8a36443a1

I'll fix that

**Comment by muglug** [comment]
The split-function thing is the right solution: https://getpsalm.org/r/74ce7cd68e

I've improved handling of `callable():?Foo` in 3a3c10d so it's treated like `callable():(null|Foo)`, not `(callable():null)|Foo`
