### ISSUE TITLE
Using destructure for array merge cause an undesired error

### ISSUE THREAD

**Issue by gianiaz** [vimeo/psalm#7911]
Hi, I'm updating code from 8.0 to 8.1 and I think I've run across a bug.

Here's a code sample:
https://psalm.dev/r/3f33ec2def

Same with annotation:
https://psalm.dev/r/1323d8edaa

There's a flag or something to instruct psalm to follow a set of rules for PHP 8.1 instead of 8.0 (where this warning is right?)

**Comment by AndrolGenhald** [comment]
Duplicate of #7297.
