### ISSUE TITLE
Class, interface or enum named APCuIterator does not exist

### ISSUE THREAD

**Issue by ricardoboss** [vimeo/psalm#7912]
See: https://psalm.dev/r/8daba04c8c

Ref: https://www.php.net/manual/en/apcuiterator.construct.php

**Comment by KevinVanSonsbeek** [comment]
Mhm, having a look around, seems i can find the APCuIterator in the CallMap and CallMap_historical. Could this behavior be caused by the lack of a stub for the extension? @orklah 

Seeing how adding a stub locally for the class fixes the errors.
