### ISSUE TITLE
Infer object shape when array is cast to object

### ISSUE THREAD

**Issue by theodorejb** [vimeo/psalm#7916]
When an array is cast to an object, Psalm only sees the type as `stdClass` instead of `object` with the same shape as the array. This prevents detecting if the object shape is invalid:

https://psalm.dev/r/5584585af9

## Expected output

```
ERROR: InvalidReturnStatement - The inferred type 'object{notstatus: 'failed'}' does not match the declared return type 'object{status: string}' for foo
```

## Actual output

No issues!

**Comment by AndrolGenhald** [comment]
It also seems odd to me that `stdClass` apparently satisfies all object shapes, it seems like that should be invalid as well.

**Comment by orklah** [comment]
indeed. This is wrong: https://github.com/vimeo/psalm/blob/525a86e19d3f518bb4e964eb405eda106dfc5fa9/src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php#L204

Changing that into a `TObjectWithProperties` should not be too difficult. Care to propose a PR?

**Comment by mr-feek** [comment]
> It also seems odd to me that `stdClass` apparently satisfies all object shapes, it seems like that should be invalid as well.

just fyi, that happens here https://github.com/vimeo/psalm/blob/ebffd5258af5caf3f1c5059f96808736d20dd63f/src/Psalm/Config.php#L157-L165

**Comment by AndrolGenhald** [comment]
Well we definitely _do_ want to still allow arbitrary properties to be _set_ on `stdClass`.
