### ISSUE TITLE
psalm: MixedReturnTypeCoercion

### ISSUE THREAD

**Issue by oleg-andreyev** [vimeo/psalm#7917]
While trying to define more narrow type.

psalm: MixedReturnTypeCoercion: The declared return type 'iterable<array-key, App\Entity\Product>' for App\Repository\ProductRepository::getProductsByBrandIterator is more specific than the inferred return type 'iterable<mixed, mixed>'

https://psalm.dev/r/eec3619163

**Comment by AndrolGenhald** [comment]
I don't see how this is a bug, you're returning a type that doesn't match the declared return type.

**Comment by orklah** [comment]
Yeah, seem consistent. Psalm doesn't stop you from returning a more precise type. It is telling you that you didn't check the returned type really contains stdClass (instead of mixed, as declared by A::toIterable)

**Comment by oleg-andreyev** [comment]
is there a way to tell Psalm that, toIterable will return more precise type, if I don't have control over toIterable annotation/docblock?

**Comment by orklah** [comment]
You can:
- stub the library and change the phpdoc
- use an assertion library (or a psalm-assert) to check that the type is correct
- use an @var to force Psalm to change the type
- suppress the error with an explanation
