### ISSUE TITLE
Psalm does not recognize namespace constants

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#7920]
https://psalm.dev/r/fa4c5a13f4
https://psalm.dev/r/ab0d00c01c

**Comment by boesing** [comment]
I did experience the same in my psalm plugin. 
The class-const is part of the `context`, but the const is missing.

Constants from the same namespace are properly detected:
https://psalm.dev/r/9227d1aa88

**Comment by weirdan** [comment]
> `\Foo::FOO`

It references a class constant `FOO` from class `Foo` in the global namespace. You can't use constants (except class constants and enum cases) as types in docblocks, as PHP allows class `FOO` to coexist with constant `FOO` in the same namespace.
