### ISSUE TITLE
Resolve classes in directories elsewhere. Eg up the folder tree.

### ISSUE THREAD

**Issue by pamtbaau** [vimeo/psalm#7925]
I'm building plugins for a CMS. The location where I develop plugins is outside the root of the CMS, and symlinked from within the CMS tree. At runtime all goes well.

During editing, I'm in the root of the plugin. Of course this will cause issues for tools like PHP Intellephense which needs to be able to find the definitions of imported classes which are provided by the CMS. Luckily, PHP Intellephense can be told where classes can be found by adding relative or absolute paths to folders containing referenced classes.

When running Psalm from withing */path-to-dev/plugins/myplugin*, it also throws issues because classes cannot be found. Currently I resolve this by included the CMS as a dev required package in composer. 

Instead of installing the entire CMS inside the */vendor* of the plugin, is there a way Psalm can be told where class definitions can be found?

```
// Location of cms and its required plugins

/path-to-cms/
  system/
    src/
  user/
    plugins/
      myplugin/                                 <--  symlink to /path-to-dev/plugins/myplugin
  vendor/

// Location of plugin development

/path-to-dev/
  plugins/
     myplugin/
        classes/
        myplugin.php
        psalm.xml
        vendor/
```

**Comment by orklah** [comment]
I'm not sure I follow. Path should be described in your Psalm's config. You can give any path you want.

If it's autoloading you're worried about, you can provide a custom autoloader to Psalm to help it find your classes

**Comment by pamtbaau** [comment]
The unclarity of the question might be caused be me not being well versed with PHP, Composer and Psalm. I've edited my question hoping it provides more clarity.

**Comment by orklah** [comment]
Please check this; https://psalm.dev/docs/running_psalm/configuration/

You should have a config file in which you configure paths

**Comment by pamtbaau** [comment]
On second look, I suspect it might be &lt;extraFiles> ?

> Optional. Same format as &lt;projectFiles>. Directories Psalm should load but not inspect.

Will try soon.

**Comment by pamtbaau** [comment]
&lt;extraFiles> does indeed allow to add paths in which Psalm should try to resolve classes.
