### ISSUE TITLE
Outcome of is_a() does not remove a class from a union

### ISSUE THREAD

**Issue by bitwise-operators** [vimeo/psalm#7926]
See the attached code:

https://psalm.dev/r/8059c9a8c6

Two possible types go in, a specific object-type or an int.
If the `is_a()` doesn't evaluate to true, the incoming type should be resolved to int, but the `is_a()` call doesn't correctly trigger this.

Using `instanceof` instead of `is_a()` works as expected.

Swapping the branches of the if-statement and using `is_int()` instead of `is_a()` also works as expected.

**Comment by kkmuffme** [comment]
Example showing that instanceof works correctly: https://psalm.dev/r/986170e71d
