### ISSUE TITLE
`Using ${var} in strings is deprecated, use {$var} instead` in PHP 8.2

### ISSUE THREAD

**Issue by ricardoboss** [vimeo/psalm#7931]
Psalm is unable to run with PHP 8.2 because of the now deprecated use of `${var}`.

Example: https://github.com/elephox-dev/framework/runs/6340072292?check_suite_focus=true#step:7:14

**Comment by orklah** [comment]
I'd fix that but I can't find the issue: https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/ErrorHandler.php#L69

We don't use ${var} in a string here (in fact, I couldn't find any instance of that in Psalm...)

**Comment by ricardoboss** [comment]
Looking at the stack trace it seems that some file is being loaded and psalm just handles the error thrown by PHP.

The actual problem seems to be in `symfony/console` and in the composer autoloader itself: https://github.com/elephox-dev/framework/runs/6340072242?check_suite_focus=true#step:7:8

I'll open issues there...
