### ISSUE TITLE
Assertion dependent type not recognized in dev-master, but works in 4.x-dev.

### ISSUE THREAD

**Issue by rzvc** [vimeo/psalm#7968]
```php
function test(mixed $mixed, bool $b) : void
{
	if ($b && !is_string($mixed))
		return;
    
	echo $b ? $mixed : '';
}
```
https://psalm.dev/r/8979ac9579

**Comment by orklah** [comment]
Possibly a regression of https://github.com/vimeo/psalm/pull/7484

@muglug do you have an opinion on that?

**Comment by muglug** [comment]
This is a somewhat more simple reproducer: https://psalm.dev/r/3b5374dddc but removing the ternary fixes it: https://psalm.dev/r/7a167ba5cd

So it’s likely an issue with ternary analysis.

I’ll have a look at this tomorrow if you don’t get to it.

**Comment by muglug** [comment]
Fixed in latest by ensuring clause simplification in ternaries matches behaviour in if/else analysis
