### ISSUE TITLE
Unable to specify single-value literal string

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#799]
```php
  // psalm complains about this:
  /** @param 'a' $p */ 
  function acceptsA(string $p): void {}
  // but accepts this:
  /** @param 'a'|'a' $p */ 
  function acceptsA(string $p): void {}
```
This is probably low-priority, as constant parameters don't make much sense. Still might make sense for return types of inherited methods (e.g. narrowing down enum to it's single element).

**Comment by muglug** [comment]
I don't think this is a bug, really.
