### ISSUE TITLE
Use faster hashing algorithm for cache

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#7996]
Currently all places uses sha1 algorithm

When tracing psalm, I can see that ClassLikeStorageCacheProvider.php `private function getCacheHash` is extremely slow and makes up 20-25% of the whole psalm run time just with sha1 calls.

To avoid hash conflicts, we'd need at least a 64bit, better a 128bit hash (sha1 is 160bit, but that's overkill) https://stackoverflow.com/a/14210379

Checking https://php.watch/articles/php-hash-benchmark we can see that xxh128 is about 20 times faster than sha1, and md4 is ~2 as fast as sha1.

We could change all `sha1(` calls to something like:
`version_compare( phpversion(), '8.1', '>=' ) ? hash('xxh128', $data ) : hash( 'md4', $data )`

This improves psalm run time by about 20% in PHP8.1 case and about 10% for older PHP versions

I'm happy to provide a PR, just want to discuss it beforehand.

**Comment by kkmuffme** [comment]
No, as this is an internal issue

**Comment by orklah** [comment]
We have a few md5 as well.

From the profiling I made a while ago, I didn't see a big hash issue, but even then, if we can improve that, I'm all in!
