### ISSUE TITLE
Null-coalesce on ArrayAccess var overrides mixed type

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#800]
https://getpsalm.org/r/28786888ab
```php
<?php
  function f(ArrayAccess $p): void {
     $a = $p['a'] ?? '';
     acceptsA($a);
  }
  /** @param 'a'|'a' $p */
  function acceptsA(string $p): void {}
```
Theoretically here `$a` should be inferred as `(mixed&!null)|string()`, however psalm thinks it's just empty `string()`.

**Comment by weirdan** [comment]
Looks similar to #791

**Comment by muglug** [comment]
This is due to some behaviour that happens to allow loops to be analysed better.

**Comment by muglug** [comment]
Oh it's *only* for `ArrayAccess`. `array` version works fine: https://getpsalm.org/r/2f240c9658
