### ISSUE TITLE
ParadoxicalCondition with reassignment in if

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#801]
https://getpsalm.org/r/4cc5639061
```php
<?php
  function nullableString(): ?string { return rand(0,1) ? "a" : null; }
  function f(string $name = null): void {
    if (null !== $name || null !== ($name = nullableString())) {
    }
  }
```
Admittedly it's one horrible piece of code, but found in a popular library: https://github.com/symfony/console/blob/ac3d14fa82aad7ab067ecc84e0e1a4d01789cc76/Command/Command.php#L73

**Comment by muglug** [comment]
Thanks!
