### ISSUE TITLE
Misleading error after not empty assertion on empty array

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#8041]
https://psalm.dev/r/125683552a

The NoValue error complains that `This function or method call never returns output` for `$foo`, which isn't a function or method.

In my actual code the `TypeDoesNotContainType` didn't show up for some reason, which made it much more confusing. I think in this case it would probably be better if after the paradoxical `!empty` condition `$foo` were changed to `array<array-key, mixed>` instead of `never`.

**Comment by orklah** [comment]
> This function or method call never returns output

This text should definitely be updated, we're now using NoValue in a lot more contexts than method/function calls. I kinda lack the correct words to express it, but `NoValue` express the right meaning for me. It will be emitted whenever we're trying to use a variable/expression that can't have a valid type/can't happen

So in this case, the assert will always stop the execution, so there is no possible type possible for $foo. If you assign a type to $foo, NoValue will never be emitted, and in whatever case you had where TypeDoesNotContainType was not emitted, you'll have an issue not reported

**Comment by AndrolGenhald** [comment]
> the assert will always stop the execution

Wouldn't it be better to continue execution with the type set to something reasonable? I thought that was how reconcilation normally worked, where impossible conditions cause the type to be `mixed` and then execution continues.

**Comment by orklah** [comment]
There was a lot of inconsistencies in that. I made some cleanup in there, the behaviour should now be:
a reconciliation between a type "from_docblock" will result in a mixed type (we assume the error was the docblock and that we just don't know the result. However, when the type is not from_docblock, we know the code can't happen and we let the user know

Example: https://github.com/vimeo/psalm/blob/cf25363fa179a89fcdead87f29ee6f6e4c418ca3/src/Psalm/Internal/Type/SimpleAssertionReconciler.php#L2096

I'm not sure why we wouldn't want that. Could you elaborate what would be the benefit of having a type for a var that can't have this type?

**Comment by AndrolGenhald** [comment]
Makes sense, I just prefer to avoid stopping execution if at all possible. If there's a false positive for some reason and it's suppressed, that means all further issues in the function are silently missed.

**Comment by orklah** [comment]
when I said the execution stops, I don't mean Psalm's execution, but user's code execution. In you example, there is no way the count is actually executed (assuming assert is configured to error)

**Comment by derrabus** [comment]
I have another example where the error message is misleading.

https://psalm.dev/r/7b6c67e81b

In this example, the switch block exhausts all possible values for `$state` and the `default` case contains defensive code against a contract violation. I'm fine with suppressing the error here, but the error message and the explanation on the linked web page are highly misleading.

**Comment by orklah** [comment]
Right, documentation and error message was never updated. I'll fix that

**Comment by orklah** [comment]
What would you think of `All possible types for this argument were invalidated` in your specific case? Feel free to suggest things, I'm sometimes bad in choosing phrasing in english :)

**Comment by derrabus** [comment]
I'm not a native speaker either, but it sounds good to me.
