### ISSUE TITLE
Static return type & inheritance

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#8057]
Psalm complains about the following code:

```php
abstract class Geometry {
    abstract public function toXY(): static;
}

class Point extends Geometry {
    public function toXY(): static {
        return new Point;
    }
}
```

https://psalm.dev/r/5f9ee8cf1b

> Psalm output (using commit 3a24488): 
> 
> INFO: [LessSpecificReturnStatement](https://psalm.dev/129) - 9:16 - The type 'Point' is more general than the declared return type 'Point&static' for Point::toXY
> 
> INFO: [MoreSpecificReturnType](https://psalm.dev/070) - 8:29 - The declared return type 'Point&static' for Point::toXY is more specific than the inferred return type 'Point'

Even though this is perfectly legal PHP: https://3v4l.org/Kfq9s

**Comment by AndrolGenhald** [comment]
Psalm is correct, your code is broken if another class extends `Point`: https://3v4l.org/EK2PD.

Fix this by:

 - [Not returning static](https://psalm.dev/r/b038fa0def)
 - Use `@psalm-consistent-constructor` and [construct a `static` to return](https://psalm.dev/r/b116d6b99c)
 - [Mark the class final](https://psalm.dev/r/735ca5cebc)
