### ISSUE TITLE
Add more int type aliases

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#8062]
Oh, I thought I already added negative-int but I guess not. It should be easy to do if someone wants to add that

_Originally posted by @orklah in https://github.com/vimeo/psalm/issues/8060#issuecomment-1147641957_

Should be trivial to add in `Atomic::create` (see how `positive-int` is handled there).

We'll probably want

 - non-negative-int
 - negative-int
 - non-positive-int

just for completeness sake.

**Comment by orklah** [comment]
Note to my future self: I need to think of pinging Ondrej on that if new keywords are implemented

**Comment by weirdan** [comment]
I don't think we need those now that we have integer ranges:

* `non-negative-int` = `int<0, max>`
* `negative-int` = `int<min,-1>`
* `non-positive-int` = `int<min, 0>`
