### ISSUE TITLE
Null offset is wrongly considered as `0` instead of `''`

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#8063]
https://psalm.dev/r/2a78c82e27

The code can be tried here: https://onlinephp.io/?s=s7EvyCjg5dLXV3DNK0ktUqjMLy1SSM5PSVXISC1K1VFIzcvKr1Tk5VJJVLBViI615uUCsaPzSnNyYoEixmCBssSi-JTS3AINlURNawA%2C&v=8.1.6

The array should be considered by psalm as `['' => '3']` and not `[0 => '3']`.

**Comment by weirdan** [comment]
The offset issue is valid, however I don't see why you expect `= 3` to result in `, string>`.

**Comment by VincentLanglet** [comment]
> The offset issue is valid, however I don't see why you expect `= 3` to result in `, string>`.

I don't, I updated the psalm.dev snippet. I should have used `array<string, mixed`, because I'm only concerned by the keys here.

**Comment by weirdan** [comment]
Interestingly enough, `$a = [null => 3]` behaves as expected: https://psalm.dev/r/d022156e7f
