### ISSUE TITLE
Nullsafe chained calls lose the null possibility

### ISSUE THREAD

**Issue by mkilmanas** [vimeo/psalm#8073]
https://psalm.dev/r/4bc16afe84

When a chain of calls after a nullsafe operator has another non-nullable element, Psalm seems to forget that the whole chain can result in `null` and then complains about null coalescing.

Side note: adding another nullsafe operator after that non-nullable element seems to actually pass the Psalm check, but it is not needed or required by the language. You can see it working here: https://3v4l.org/rCZDL#v8.1.7

**Comment by AndrolGenhald** [comment]
Duplicate of #6057 and/or #6237.

> Side note: adding another nullsafe operator after that non-nullable element seems to actually pass the Psalm check, but it is not needed or required by the language. You can see it working here: https://3v4l.org/rCZDL#v8.1.7

I'm sure this has come up before as well, but I can't find the issue right now.

Our nullsafe support needs some improvement :confused:
