### ISSUE TITLE
Different schemas on website and here in the repo

### ISSUE THREAD

**Issue by szepeviktor** [vimeo/psalm#8076]
```bash
diff <(wget -qO- https://github.com/vimeo/psalm/raw/4.23.0/config.xsd) <(wget -qO- https://getpsalm.org/schema/config)
```
v4.23.0 vs. website: 124 lines of difference

Is it intentional?

**Comment by szepeviktor** [comment]
@psalm-github-bot No

**Comment by weirdan** [comment]
Kinda. getpsalm.org/schema/config returns the schema for Psalm 5 (`master` branch).

**Comment by szepeviktor** [comment]
Thank you!
Indeed: `master` has no difference to the website.
