### ISSUE TITLE
Crash on scanning /nikic/php-parser

### ISSUE THREAD

**Issue by AurelienTisserand** [vimeo/psalm#809]
Hello 

I encounter a fatal error during scanning /nikic/php-parser folder. I have update psalm to its latest version. Before this update all was working fine with this folder. You can found in attachment the full stack trace.

![crashpsalm](https://user-images.githubusercontent.com/36203816/41230710-20ff29ec-6d81-11e8-9433-5663b87651a3.PNG)

**Comment by weirdan** [comment]
Have you tried dev-master?

**Comment by muglug** [comment]
I've just released 2.0.4 - please try with that

**Comment by AurelienTisserand** [comment]
It works with dev-master. I am going to relaunch with 2.0.4 to tell you if this is ok.

**Comment by muglug** [comment]
2.0.4 is, for the moment at least, `dev-master`
