### ISSUE TITLE
Call map definitions for nullable and optional parameters are inconsistent

### ISSUE THREAD

**Issue by SamMousa** [vimeo/psalm#8107]
In the call map parameters are specified as optional by postfixing them with an `=` sign.

However in many cases there seems to be inconsistency about whether to explicitly specify nullability for optional arguments:
```php
[
'mysqli_commit' => ['bool', 'mysql'=>'mysqli', 'flags='=>'int', 'name='=>'?string'],
'pg_last_error' => ['string', 'connection='=>'\PgSql\Connection', 'operation='=>'int'],
'ReflectionClass::getProperties' => ['list<ReflectionProperty>', 'filter='=>'int'],
]
```
Looking at the above definitions it seems reasonable to conclude:
- Parameter `name` is optional and nullable
- Parameter `connection` is optional and not nullable
- Parameter `filter` is optional and not nullable

In reality these are all nullable.

**Comment by SamMousa** [comment]
https://psalm.dev/r/eb852217a6

**Comment by weirdan** [comment]
https://psalm.dev/r/7895235082 - all of the originally listed problematic entries seem to have been fixed, and callmap is now validated against the reflection data. Ping me if there's anything else left to do here.
