### ISSUE TITLE
Procedural style parameter counts and types

### ISSUE THREAD

**Issue by SamMousa** [vimeo/psalm#8108]
Procedural functions like `datefmt_set_timezone` (alias of `IntlDateFormatter::setTimeZone`) seem to not be properly defined in the callmap:

```php
'datefmt_set_timezone' => ['bool', 'formatter'=>'mixed'],
```
Not only is the number of parameters wrong, so is the type.

https://psalm.dev/r/0f182617cf

In PHP, 2 arguments are required and the first must be of type `IntlDateFormatter`.

**Comment by orklah** [comment]
This function was fixed :)
