### ISSUE TITLE
Incorrect inference of template definition using nested templates

### ISSUE THREAD

**Issue by emmanuelGuiton** [vimeo/psalm#8112]
Hi,

I would expected the 2 following snippets to work :
https://psalm.dev/r/f444f78efa
https://psalm.dev/r/f8c537da60

It seems Psalm does not get that it has the same template definition in `Utils::aFunction()` and in the `Repository` interface.
Am I missing anything ?

Regards,
 - Emmanuel

**Comment by AndrolGenhald** [comment]
I think this is another case where Psalm's support for using nested templates is buggy :slightly_frowning_face:

**Comment by emmanuelGuiton** [comment]
It seems I have yet another case : https://psalm.dev/r/dd644437de
Is there any work around ?

**Comment by emmanuelGuiton** [comment]
I think the simplest case to reproduce the issue is that one : https://psalm.dev/r/73c1e5aa67
Psalm behaves correctly when there are 2 nested templates, it fails with 3 nested templates.
