### ISSUE TITLE
Split the callmap by prefix

### ISSUE THREAD

**Issue by SamMousa** [vimeo/psalm#8115]
The callmap is way too large, this leads to a horrible dev experience.

Given that the time spent on loading the callmap pales in comparison to the actual static analysis, we can (and imo should) just split the callmap into a separate file for each starting letter.

This would lead to having the current callmap and the historical callmap be refactored in to 28 files each.
27 parts and 1 file to include all the parts.

This is a simple issue to resolve and shouldn't have any consequences as the internal API will stay the same (`require` the map to get all entries)

**Comment by orklah** [comment]
I agree that those files are too big. PHPStorm make my fans blow at high speed when I open them and github won't display or index the files leading to poor contributor experience (if one want to search where functions are listed)

Splitting them by letter doesn't seem a great way to reduce that though IMO. Having a generated file we never touch and then a file of exceptions/refinement seems like a better idea, in complement of excluding extensions

**Comment by SamMousa** [comment]
By letter is a < 30 min job. We can always further improve it, since it is a purely internal change. While I agree there are better solutions, I'm guessing they haven't been implemented due to time / priority constraints...

**Comment by orklah** [comment]
we mainly lack contributors to make this project as lively as it should be :p

Honestly, by letter would not be too great for me, I prefer the current solution to that
