### ISSUE TITLE
Uncaught InvalidArgumentException: Unrecognised parse tree type Psalm\Type\ParseTree\ObjectLikePropertyTree 

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#812]
Observed: Psalm crashes due to uncaught exception
Expected: Psalm does not crash. It warns about the phpdoc being unparseable or does nothing.

The following snippet can reproduce this crash on the latest master branch:

```
<?php

/**
 * @return int[]|string[]|object|null:-
 */
function test() {
    return null;
}
```

**Comment by muglug** [comment]
Thanks - previously my hackish fix for all these issues was just to catch all exceptions where you added your own extra catch, but I don't think that's good for the project in the long-run.
