### ISSUE TITLE
Invalid template instantiation for iterable

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#8124]
https://psalm.dev/r/6dbd395818 (`array|Travesable` against `iterable`)
https://psalm.dev/r/383c7f3677 simplified (only `iterable`)

**Comment by orklah** [comment]
output changed radically, did the situation improve?

**Comment by AndrolGenhald** [comment]
@orklah nope, just the false negative I mentioned showing up everywhere. Here's a fixed version of the second link: https://psalm.dev/r/0d58749a8f
