### ISSUE TITLE
Incorrect PossiblyUndefinedVariable after consecutive if statement blocks

### ISSUE THREAD

**Issue by colin-saunders-bluefruit** [vimeo/psalm#8157]
Vimeo appears to not follow through all the potential code branches to work out that variable will be set it all cases.

Involves try/throw/catch so wondered if it was related to [#7688](https://github.com/vimeo/psalm/pull/7688) but in the snippet provided you will see that it is working with exceptions - the charlie case. It seems to get confused by two consecutive if statements in the delta case.

[https://psalm.dev/r/19db0757ab](https://psalm.dev/r/19db0757ab)

Note: I currently have psalm configured at level 3 so the snippet includes 2 issues which I hadn't seen before but may, I think, be related to the PossiblyUndefinedVariable issue.

**Comment by AndrolGenhald** [comment]
Reproduced without the try/catch: https://psalm.dev/r/7c174098a1
Further simplified: https://psalm.dev/r/f5087b6b3c

I think this is similar to a few other open issues, the difficulty is that Psalm would have to understand the relation between `$submitted`, `$response`, and `$showForm`.

**Comment by orklah** [comment]
@AndrolGenhald note that in your repro, initializing the variable first resolves the issue. But yeah, basically, this is horrible for Psalm (and I'd also argue that I'd hate to be the dev debugging that particular code)

**Comment by colin-saunders-bluefruit** [comment]
Thanks for the responses.
