### ISSUE TITLE
`substr_count` does not accept literal values

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#8160]
https://psalm.dev/r/b6e785b82c
IMO this should be valid.

**Comment by weirdan** [comment]
This is intentional. See https://github.com/vimeo/psalm/blob/36d5a2a83c1d7b3e2aca1cfe9e9dcc916619e962/docs/running_psalm/issues/InvalidLiteralArgument.md and the discussion in the original PR: https://github.com/vimeo/psalm/issues/4070
