### ISSUE TITLE
`global` is allowed as a method name in PHP 7+

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#817]
That's something I didn't know myself, but you can name method `global` in PHP7+ (not in older versions though). Currently psalm rejects `@method retType global()` annotation, but not `public function global(): Client {...}` method.

**Comment by fesor** [comment]
not only `global` - any keyword can be used as method name since php7.0. You could find list of available keywords in this RFC: https://wiki.php.net/rfc/context_sensitive_lexer

**Comment by muglug** [comment]
this is due to the fact that I'm [using PHPParser](https://github.com/vimeo/psalm/blob/7fb4c4acad9ee037b45e836c90f5d199e49e38a5/src/Psalm/Checker/CommentChecker.php#L429) to parse `@method` annotations.

**Comment by weirdan** [comment]
Probably could be worked around by wrapping the extracted "method" into a class before parsing, so that parsing happens in a proper context.

**Comment by muglug** [comment]
yeah, that's what the fix will do
