### ISSUE TITLE
InvalidReturnType due to void and null not treated the same

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8178]
https://psalm.dev/r/f4bb991d20

void and null must be treated as the same thing.

**Comment by AndrolGenhald** [comment]
Hmmm, I don't think it actually makes sense to have a return type of `void|never`. Regardless though, that error is incredibly misleading.

**Comment by orklah** [comment]
> Hmmm, I don't think it actually makes sense to have a return type of `void|never`. Regardless though, that error is incredibly misleading.

It can make sense for assertions methods where you either throw or do nothing. but the snippet in example doesn't do that. So yeah, it's just a wrong phrasing

**Comment by AndrolGenhald** [comment]
> It can make sense for assertions methods where you either throw or do nothing.

Shouldn't that just combine to `void` though? `never` is the bottom type, so it's a subtype of all other types, so if you do `x|never` it should just simplify to `x`.

**Comment by orklah** [comment]
True. The case I had some times ago was something like `($die_on_redirect is true ? never : void)`. So technically it's the same case but the combination doesn't happen

**Comment by AndrolGenhald** [comment]
> The case I had some times ago was something like `($die_on_redirect is true ? never : void)`.

Ahh, yeah I could see that then. Interestingly though, [this](https://psalm.dev/r/8dad765588) actually works fine while [this](https://psalm.dev/r/d162606c86) doesn't.
