### ISSUE TITLE
Class overriding templated parent method and constraining nullable type errors

### ISSUE THREAD

**Issue by pauljohnston2009** [vimeo/psalm#8195]
When constraining the return type on derived classes, for strict type checking, psalm errors with ' The inferred type "null|string' does not match the declared return type 'null'". It seems to think the return type of StringA::value() is always null.

Seems to only happen when return type of parent is nullable

https://psalm.dev/r/753dc8ac29

Making the template not nullable fixes the issue
As does specifying the return type in the override function
```
    /**
     * @return null|string 
     */
    public function value(): ?string
```

Removing the function override  also fixes the issue.

**Comment by AndrolGenhald** [comment]
Well that's unfortunate, it appears to be a bad interaction between templates and docblock inheritance. If you override the docblock it [works fine](https://psalm.dev/r/80ef952a3b).

**Comment by AndrolGenhald** [comment]
Duplicate of #7126.
