### ISSUE TITLE
generics + static = invalid type inference

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#8200]
https://psalm.dev/r/5d79e9217a

**Comment by someniatko** [comment]
BTW, `Maybe<Maybe>|Maybe<never>` is almost like a song! 🎶

**Comment by AndrolGenhald** [comment]
Hmm, looks like the `static` type is maybe leaking into the `Maybe` template and making it think the template is itself.

**Comment by someniatko** [comment]
simplified a bit https://psalm.dev/r/c8124aae78

**Comment by someniatko** [comment]
type `Test` (of `Maybe<Test>` inferred return type) changes to `Maybe` (so it will be inferred as `Maybe<Maybe>`) in `TypeExpander::expandNamedObject` on line 672 in the following chunk of code:

```php
elseif ($return_type->was_static && is_string($static_class_type) && $final) {
    $return_type->value = $static_class_type;
    $return_type->was_static = false;
}
```

here `$return_type->value` was `Test`, now it changes to `Maybe`.

**Comment by AndrolGenhald** [comment]
Btw, why not go with `Option`, `Option::some()`, and `Option::none()` if you're copying Rust?

**Comment by someniatko** [comment]
I'm not sure I understand you. Is it relevant to this issue, and where is "copying Rust"?

**Comment by AndrolGenhald** [comment]
Not really relevant, just curious. `Maybe` seems pretty clearly to be copying Rust's [Option](https://doc.rust-lang.org/std/option/enum.Option.html), and you have `tryFrom` as well which also [comes from Rust](https://doc.rust-lang.org/std/convert/trait.TryFrom.html) (but maybe that name is actually taken from `BackedEnum::tryFrom`?).

**Comment by someniatko** [comment]
I first learned about Maybe monad from Haskell (which is much older than Rust btw), and tryFrom() is just a common name I've seen in the wild.
