### ISSUE TITLE
Intersection types not yet supported

### ISSUE THREAD

**Issue by root-aza** [vimeo/psalm#8229]
<details>
  <summary>StackTrace</summary>
  
Target PHP version: 8.1 (inferred from composer.json)
Scanning files...
Uncaught UnexpectedValueException: Intersection types not yet supported in /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php:822
Stack trace:
#0 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php(212): Psalm\Internal\PhpVisitor\Reflector\FunctionLikeNodeScanner->getTranslatedFunctionParam(Object(PhpParser\Node\Param), Object(PhpParser\Node\Stmt\ClassMethod), false, 'App\\Shared\\Prop...')
#1 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(235): Psalm\Internal\PhpVisitor\Reflector\FunctionLikeNodeScanner->start(Object(PhpParser\Node\Stmt\ClassMethod))
#2 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#3 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#4 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#5 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#6 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#7 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#8 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(88): PhpParser\NodeTraverser->traverse(Array)
#9 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(589): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#10 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(339): Psalm\Internal\Codebase\Scanner->scanFile('/Users/aza/Phps...', Array, true)
#11 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(459): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(128, '/Users/aza/Phps...')
#12 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(303): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#13 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/vimeo/psalm/src/Psalm/Codebase.php(518): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 7)
#14 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(639): Psalm\Codebase->scanFiles(7)
#15 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(373): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/aza/Phps...', true)
#16 /Users/aza/PhpstormProjects/kazahstan_back/vendor-bin/qa/vendor/vimeo/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#17 /Users/aza/PhpstormProjects/kazahstan_back/vendor/bin/psalm(120): include('/Users/aza/Phps...')
#18 {main}
(Psalm 4.24.0@06dd975cb55d36af80f242561738f16c5f58264f crashed due to an uncaught Throwable)
make: *** [analysis-code] Error 1

</details>

**Comment by root-aza** [comment]
Repoduce https://github.com/root-aza/repoduce-fail-psalm

**Comment by orklah** [comment]
Can you try with Psalm in version 5 (we released it as a beta for now)

**Comment by lptn** [comment]
@orklah 
v5 fails currently on my codebase (both beta and master versions). When I exclude some dirs, it finally works, but reports about a lot of false-positives (`NoValue`, `UnevaluatedCode`, `InvalidCast`). Should I report about these issues, or your are aware about them?

**Comment by orklah** [comment]
Please report them, AFAIK, these should not be false positives

**Comment by root-aza** [comment]
In pslam v5 fixed current bugs

**Comment by orklah** [comment]
Great! I'll close this then
