### ISSUE TITLE
array_map adds incorrect null type

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8232]
https://psalm.dev/r/1af296b52a

When array_map why does it suddenly have type null|string in there? should be string only, like in the non-array_map case

**Comment by orklah** [comment]
https://psalm.dev/r/3c8d0ec883

If you feed it a non-empty-string, it will be happy.

str_getcsv returns a string [only if the input is not empty](https://github.com/vimeo/psalm/blob/e0acf22e402d45d1aebb75f4365ebf701fabce2f/stubs/CoreGenericFunctions.phpstub#L1111), (which Psalm is sure of when you feed it 'foo')
