### ISSUE TITLE
Consider accessing a property on an interface that does not exist as "Always Treated As Errors

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#8235]

**Comment by AndrolGenhald** [comment]
> I would expect this code to always fail

https://3v4l.org/Vrgcs

**Comment by mr-feek** [comment]
interesting yeah 🤔 😞 Kinda unfortunate, and understandably extremely difficult for psalm to handle _efficiently_. Luckily my phpstorm analyzer caught it in my editor for me.

Happy to close this if ya think nothing more can be done than already is being done!

**Comment by mr-feek** [comment]
I wonder if this should be treated as an error unless the annotation is something like

`Interface&MyInstanceWithPropertyDefined` 🤔

**Comment by orklah** [comment]
> Interface&MyInstanceWithPropertyDefined

Unless you have only one class implementing the interface, it's hard to enforce. User would be forced to make an abstract class with the property to be inherited (and at that point, when you have an abstract class implementing an interface, you might as well use the abstract class in signature :p)
