### ISSUE TITLE
array_filter return type wrong

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8238]
https://psalm.dev/r/3547e71018

When array contains only strings, array_filter returns `array<int, non-empty-string>` - not `array<int, non-falsy-string>`

Issue is just with this case. When I have it declared explicitly, it gets an explicit type which is correct: https://psalm.dev/r/e2e0e02c4b

**Comment by orklah** [comment]
Not sure I understood your issue.

The only difference between non-empty-string and non-falsy-string is that the latter does not contain the string `'0'`. (which means non-falsy-string IS a non-empty-string).

array_filter does filter the `'0'` string, so any string passing through array_filter becomes a non-falsy-string

**Comment by kkmuffme** [comment]
Nvm, there were some other issues that caused a weird behavior with the results. Thanks for your reply though
