### ISSUE TITLE
instanceof interface kinda loses generic types on object

### ISSUE THREAD

**Issue by mathroc** [vimeo/psalm#8239]
https://psalm.dev/r/12b262aadc

I'm not sure how to explain / describe this issue (I don't like the issue title I found)

but I think the example above should be valid

**Comment by mathroc** [comment]
It does work when it's a class instead of an interface: https://psalm.dev/r/d75a820851

**Comment by AndrolGenhald** [comment]
Given that [this](https://psalm.dev/r/02bd4c3591) works I'm guessing it's not fully checking the intersection, only whatever happens to be first. I bet we've got a lot of stuff like this that'll need fixed...

**Comment by orklah** [comment]
This seems to be working as expected now

**Comment by mathroc** [comment]
nice! thank you :)
