### ISSUE TITLE
Badly placed parenthesis in conditional return causes crash

### ISSUE THREAD

**Issue by gsteel** [vimeo/psalm#8251]
I hope this issue isn't just noise 🤞

In short, if you mess up where you close parenthesis for a conditional return, psalm crashes rather than yield an `InvalidDockblock` issue:

https://psalm.dev/r/cea33e07ae

**Comment by AndrolGenhald** [comment]
Turns out I ran into this myself! Duplicate of #7575, I'll try to look at that in the next week.
