### ISSUE TITLE
Generate stub files for a particular package given its components 

### ISSUE THREAD

**Issue by connerbw** [vimeo/psalm#827]
I would like psalm to be able to generate stub files for a particular package given its components.

The use case is that I want to statically analyse my own code, but not the underlying package, in this case WordPress, but it could be any 3rd party code.

Looking through the Psalm documentation, the only thing I can find about this is creating my own stub file? Well it actually says [to use PhpStorm stub files](https://github.com/JetBrains/phpstorm-stubs) but there's no such directory for WordPress.   The other option proposed is  `require_once("path_to_wordpress/wp-load.php")` and Psalm should know everything it needs to but it'll also be pretty slow, because it'll be analyzing all the contents of those files too.

Looking for a 3rd option:  Psalm generate stub files for a particular package. Not analyze it.

Thank you for your consideration.

Related to: https://github.com/muglug/WordPressAnalysis/issues/1

**Comment by AdamMarton** [comment]
Hi @connerbw 

Sorry for the shameless self-promotion but I've struggled with the same issue, so if you're interested, feel free to take a look at [my repo](https://github.com/AdamMarton/Stub) which aims to fill the void in this area: generating stubs from WP. It's still early in the development, but I'm already using it for my projects. Comments and suggestions are also welcome! I'm about to introduce a Psalm plugin to make it more convenient.
