### ISSUE TITLE
Internal: "Get link" should copy to clipboard

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8271]
https://psalm.dev/

When pressing the "Get link" button, it should not only put it in the URL bar, but also copy it to clipboard.

```js
navigator.clipboard.writeText( url ).catch( ( error ) => {
    alert( 'Error: could not copy URL to clipboard' );
});
```

I don't know where the repo for psalm's website is, otherwise I would have added a PR/issue there.

**Comment by AndrolGenhald** [comment]
https://github.com/psalm/psalm.dev
