### ISSUE TITLE
False MixedArgument and TooFewArguments errors when unpacking a parameter method from an array.

### ISSUE THREAD

**Issue by mj4444ru** [vimeo/psalm#8276]
https://psalm.dev/r/619d1410de

**Comment by orklah** [comment]
This should be better:
https://psalm.dev/r/d0caa05433

the `array{0: string, 1: int, 2: string}` does not guarantee the order of elements in the array. Which means it is strictly identical to `array{1: int, 0: string, 2: string}`, however, destructuring would have a different result

**Comment by mj4444ru** [comment]
> This should be better: https://psalm.dev/r/d0caa05433
> 
> `array{0: string, 1: int, 2: string}`the does not guarantee the order of elements in the array. Which means it is strictly identical to `array{1: int, 0: string, 2: string}`, however, destructuring would have a different result

Thanks for explaining. Thanks for the example.
