### ISSUE TITLE
False-positive `TypeDoesNotContainType` while using conditional type for return

### ISSUE THREAD

**Issue by MaSpeng** [vimeo/psalm#8286]
### Description
While trying to use a conditional type for a method return value based on the cases of an UnitEnum/BackendEnum, a `TypeDoesNotContainType` issue arises indicating that the value of parameter with the enum type could never be one of the enum cases.

The issue exists for me while using `UnitEnum`, `BackedEnum<int>`, and `BackendEnum<string>`.

### Psalm Snippets
UnitEnum: https://psalm.dev/r/3a92e4a91f
BackedEnum (int): https://psalm.dev/r/cd28e96568
BackedEnum (string): https://psalm.dev/r/4c57a77aa8

### PHPStan Snipppets
UnitEnum: https://phpstan.org/r/667b3feb-6a7e-4444-8666-64b37759c0d4
BackedEnum (int): https://phpstan.org/r/01028541-f166-4c1c-9ad1-f6c937fccb7f
BackedEnum (string): https://phpstan.org/r/04041665-afd1-4ebe-9b9b-5ed4725895ff

**Comment by weirdan** [comment]
This is partially fixed by #9286. All traces produce expected results, but TypeDoesNotContainType is still there.

**Comment by weirdan** [comment]
`TypeDoesNotContainType` is no longer reported, and results match those of PHPStan
