### ISSUE TITLE
Error with array references in Reconciler 

### ISSUE THREAD

**Issue by ohader** [vimeo/psalm#8289]
https://psalm.dev/r/03af5df16f

Check XHR response in browser's dev console (actually it's "just" a warning, however analyzer stops)

```
Warning: Undefined array key "$doesNotMatter[$a]" in /var/www/vhosts/psalm.dev/httpdocs/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php on line 128
{"error":{"message":"\/vendor\/vimeo\/psalm\/src\/Psalm\/Type\/Reconciler.php: __clone method called on non-object","line_from":128,"type":"psalm_error"}}
```

https://github.com/vimeo/psalm/blob/e268a053070ca1272df727673ea4f750ab3212b6/src/Psalm/Type/Reconciler.php#L128

**Comment by ohader** [comment]
@AndrolGenhald Just create a test-case for this, feel free to reuse them from PR #8290

**Comment by AndrolGenhald** [comment]
I'll try to get this fixed soon, but I've given up on further improving support for arrays and objects with references, they're (imo) incredibly buggy and unintuitive: https://3v4l.org/3RncH

**Comment by ohader** [comment]
Incredible, I was not aware of that flaw in PHP! 😮 
For the time being I think, it would be enough to encapsulate those scenarios and just not process the buggy ones.
