### ISSUE TITLE
Crash when iterating iterable checked with instanceof

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#8293]
This works fine: https://psalm.dev/r/cf4d41e75e
[This](https://psalm.dev/r/0fd9a8b4ff) crashes: https://psalm.dev/r/a315359995

Presumably this is because the `instanceof` check results in a `TNamedObject` instead of `TGenericObject`, but it should really work either way.

(see also #8292)

**Comment by orklah** [comment]
Seems fixed
