### ISSUE TITLE
False positive `ParadoxicalCondition` when using null-coalescing assignment

### ISSUE THREAD

**Issue by blackwolf12333** [vimeo/psalm#8303]
https://psalm.dev/r/dfb092ce4c

If you remove the `?? []` on line 16 the snipped above will error out with an `Undefined offset: 1` error.

So this is seen as a `ParadoxicalCondition` while it really is required.

**Comment by edsrzf** [comment]
Somewhat simplified: https://psalm.dev/r/3703120ab5

I would say this error is correct. If the the `array_merge` is running, then it means `$map[$key]` is unset or null, so the empty array `[]` will always be used. This code is equivalent and causes no error: https://psalm.dev/r/3703120ab5 (In fact with this change, the `array_merge` is now unnecessary.)

The thing that seems like a bug to me, however, is that we don't get the `ParadoxicalCondition` when we change the array to a variable, eg: https://psalm.dev/r/f6745c6ba3

**Comment by weirdan** [comment]
That's because $v is undefined (=mixed). Fix that and you'll get `TypeDoesNotContainType` (=paradox): https://psalm.dev/r/55695988d8

**Comment by weirdan** [comment]
Overall, I don't see any bugs here.
cc: @AndrolGenhald
