### ISSUE TITLE
Class constants where value starts with an operand are not recognized

### ISSUE THREAD

**Issue by bitwise-operators** [vimeo/psalm#8307]
If the value for a class constant starts with an operand, like `!` or `~`, Psalm doesn't register it, and throws an `UndefinedConstant` error.

https://psalm.dev/r/b100090d84

**Comment by bitwise-operators** [comment]
As an aside, I've had a quick look through the code to see if I could fix this, but I'm having a hard time figuring out what part of the code this is likely to be in. If someone could give a pointer where this is likely to originate, I'd be happy to give it another go.

**Comment by AndrolGenhald** [comment]
My first guess would be it's a parsing issue in either `ParseTreeCreator` or `TypeParser`, but it's possible the issue is somewhere else as well.

**Comment by weirdan** [comment]
Fixed in #8360
