### ISSUE TITLE
`@immutable` on a singleton with a static method where a field populated makes Psalm crash

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#8313]
https://psalm.dev/r/51731007b1
Sandbox responds 500

> Warning: Undefined array key "self::$doctrineNullLink" in /var/www/vhosts/psalm.dev/httpdocs/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/InstancePropertyAssignmentAnalyzer.php on line 526
> {"error":{"message":"\/vendor\/vimeo\/psalm\/src\/Psalm\/Internal\/Analyzer\/Statements\/Expression\/Assignment\/InstancePropertyAssignmentAnalyzer.php: __clone method called on non-object","line_from":526,"type":"psalm_error"}}

If I don't set the private field, everything works fine:
https://psalm.dev/r/1a2579acd5

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/809ad5cc65

**Comment by weirdan** [comment]
Seems to only happen when unused code detection is turned on.
