### ISSUE TITLE
concat of 2 non-empty-strings should lead to non-falsy-string

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#8315]
https://psalm.dev/r/c77d73090f

Implemented in phpstan with https://github.com/phpstan/phpstan-src/pull/1542

**Comment by orklah** [comment]
It must be a pretty niche issue but it's correct given the only non-empty falsy string is '0' and it can't be the result of the concatenation of two other non-empty-strings

This should be handled in ConcatAnalyzer
