### ISSUE TITLE
Union assertions not detecting paradoxes

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#8322]
Possibly introduced by #8077: https://psalm.dev/r/49f98e503d

**Comment by AndrolGenhald** [comment]
Shouldn't it assert `!T`? https://psalm.dev/r/07f65c80ea

**Comment by AndrolGenhald** [comment]
`assert` [works fine](https://psalm.dev/r/a6dc1e3b9a) but behaves slightly differently, since it will generally be ignored in production environments. I wasn't aware we actually supported that, but it [works for non-unions](https://psalm.dev/r/97bbacb893), so it should probably work for unions too.

**Comment by orklah** [comment]
fixed in master :)
