### ISSUE TITLE
Psalm crashing with intersection types in latest builds

### ISSUE THREAD

**Issue by davidbyoung** [vimeo/psalm#8333]
https://psalm.dev/r/c189b6d2b0

**Comment by AndrolGenhald** [comment]
@petewalker care to look into it? Looks like we should be returning `never` instead of throwing, and we should probably add an issue explaining that the type is impossible.

**Comment by davidbyoung** [comment]
I'm not sure if this is a separate issue or not, but my [CI](https://github.com/aphiria/aphiria/runs/7570560788?check_suite_focus=true#step:7:12) is also failing on what I think might be another issue with an intersection type with PhpUnit's `MockObject`. I have tried to repro it on psalm.dev, but have not been successful.

**Comment by AndrolGenhald** [comment]
I would guess that's a separate issue. The issue here is that the type is impossible (PHP doesn't support multiple inheritance) and Psalm is crashing instead of telling you that the type is impossible. `MockObject` is an interface, so as long as you're intersecting it with another class or interface (and not something silly like `int`) it should be fine.

**Comment by petewalker** [comment]
> @petewalker care to look into it? Looks like we should be returning `TNever` instead of throwing, and we should probably add an issue explaining that the type is impossible.

Yep, I can take a look today, hopefully!

**Comment by davidbyoung** [comment]
> I'm not sure if this is a separate issue or not, but my [CI](https://github.com/aphiria/aphiria/runs/7570560788?check_suite_focus=true#step:7:12) is also failing on what I think might be another issue with an intersection type with PhpUnit's `MockObject`. I have tried to repro it on psalm.dev, but have not been successful.

I think this issue might be [the same one I posted earlier this year](https://github.com/vimeo/psalm/issues/7520).

**Comment by AndrolGenhald** [comment]
> I think this issue might be https://github.com/vimeo/psalm/issues/7520.

It might be semi-related, but that one is still failing due to not finding the class storage, while this one is failing due to the newer support for PHP intersections.

**Comment by petewalker** [comment]
@AndrolGenhald better late than never... I've had a go at fixing

**Comment by davidbyoung** [comment]
Do we have any rough idea of when this may be fixed in a future release?  Thanks!

**Comment by orklah** [comment]
This is now fixed :)
