### ISSUE TITLE
ADT / tagged union emulation?

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#8340]
I'd like to mark somehow that my abstract class, or an interface, has only a restricted set of available extenders / implementers.

This can also be achieved on a language level by further extension of the enum concept as Larry Garfield planned. Also, another option is to use a union type, but it's too cumbersome to type each time.

**Comment by AndrolGenhald** [comment]
> Also, another option is to use a union type, but it's too cumbersome to type each time.

We have [type aliases](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-type) for that, though admittedly they could use some improvement.

I swear this has come up before, but I can't find anything right now.

**Comment by ZebulanStanphill** [comment]
`DaveLiddament/php-language-extensions` has an attribute called [`Sealed`](https://github.com/DaveLiddament/php-language-extensions#sealed) for this purpose. Sadly, there's no Psalm extension for this package yet (only a PHPStan one), but one for Psalm is planned.

**Comment by klimick** [comment]
See #1450

**Comment by someniatko** [comment]
Oh, thank you, that's a duplicate then!
