### ISSUE TITLE
Nested callables + templates -> something went wrong

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#8342]
I can't figure out whether it's me typing `Option:all()` incorrectly, or it's a bug in Psalm:

https://psalm.dev/r/5b9a372af4

**Comment by AndrolGenhald** [comment]
A bit hard to tell what's going on here, but this does look like a Psalm bug.

**Comment by someniatko** [comment]
@AndrolGenhald It's like `Promise:all()` from JavaScript.

**Comment by someniatko** [comment]
@AndrolGenhald It seems it is fixed by now!
