### ISSUE TITLE
Docblock with @param string|array is not recognised

### ISSUE THREAD

**Issue by LauraTaylorUK** [vimeo/psalm#8343]
A docblock with `@param string|array $variable` is not recognised by psalm.

Please take a look at the following code:
https://psalm.dev/r/7b0e4c4384

Thank you.

**Comment by orklah** [comment]
it is recognized. Psalm is telling you your `elseif` is redundant because if your param can only be a string or an array, then once you checked is_string, the leftover can only be an array so you don't need to check it.

It's expected behavior

**Comment by LauraTaylorUK** [comment]
Thank you for the quick reply and explanation.

I think the error message is not good enough, it is misleading. Maybe it can be improved a little bit?

Better wording would avoid invalid issues like this one, in the future :)

**Comment by orklah** [comment]
Could you propose a better one in a PR?

**Comment by AndrolGenhald** [comment]
I think the misunderstanding here comes from what Psalm means by "Docblock-defined type". It doesn't mean "the type from the docblock", it actually means "the type from the docblock modified by all of the previous checks", as opposed to "the type from signature modified by all of the previous checks" (https://psalm.dev/r/47e23a5004). If you can think of a better phrasing for that it would help.
