### ISSUE TITLE
nullable return types in CallMap functions technically correct but make no sense

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8351]
This was recently changed in f28ac737

```
'curl_multi_getcontent' => ['?string', 'handle'=>'CurlHandle'],
```

While technically it's correct, that this is nullable, this adds tons of unnecessary conditions, as psalm is not able to infer that `CURLOPT_RETURNTRANSFER` is set, e.g. `curl_setopt( $multi_curl[ $url ], CURLOPT_RETURNTRANSFER, 1 );` in which case this never returns null.

Can we revert this for these cases again? Or should we just use @var annotation to overwrite the type?

**Comment by orklah** [comment]
So, when CURLOPT_RETURNTRANSFER  is set, curl function return a string but when it's not set it returns `void`? There are no cases where they could return null even with CURLOPT_RETURNTRANSFER  set?

**Comment by kkmuffme** [comment]
Yes.
https://www.php.net/manual/en/function.curl-multi-getcontent.php

**Comment by orklah** [comment]
Let's revert the change that was made, it would be great to have a better behaviour that could detect the flag, but as long as we don't have it, it's better to have a version that works in most cases. Can you provide the PR?

**Comment by othercorey** [comment]
@orklah Just went through this function in the callmap tests. It will return null if CURLOPT_RETURNTRANSFER is not set. 

I've patched the php docs but will leave this ignored.

**Comment by orklah** [comment]
Yeah, Psalm would to handle that specifically, this behavior can't be integrated in callmap as is unfortunately
