### ISSUE TITLE
Release tag naming convention

### ISSUE THREAD

**Issue by mpdude** [vimeo/psalm#8352]
Hi there 👋🏼,

since I use automation to build a Docker image over at https://github.com/webfactory/docker-psalm and use it in build pipelines on our projects further down the line, I noticed that there is a slight inconsistency regarding tags used to mark releases.

While the majority of release tags used here to not include a leading `v` (like `4.24.0` or `4.18.1`), the last `v4.25.0` release as well as `v4.14.0` and `v4.15.0` deviate from this pattern.

To make it easier to parse and use version numbers downstream, do you think it would be possible to somehow enforce either of both conventions and make sure it's applied consistently?

Thanks!

**Comment by orklah** [comment]
Sorry, that's a mistake on my part. I'll try to be more careful next time

**Comment by AndrolGenhald** [comment]
Should we retroactively add `4.14.0` and `4.15.0` tags pointing to the same commits as the `v4.*` tags so they're there at least?

**Comment by orklah** [comment]
I have no idea how, but if we can, sure, if there's no downside

**Comment by AndrolGenhald** [comment]
I added tags for 4.14.0, 4.15.0, and 4.25.0. The releases on github still point to the old tags, but idk if that matters as much.
