### ISSUE TITLE
How can I document this return type correctly?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8354]
https://psalm.dev/r/bd80b95172

the return type depends on the value of an array element

**Comment by AndrolGenhald** [comment]
This should work: https://psalm.dev/r/a87cd959ae

That's basically how conditional return types work behind the scenes, there's just some syntactic sugar to allow creating the template automatically when using `($arg is ... ? ... : ...)`, but it looks like that sugar fails for array offsets.

**Comment by kkmuffme** [comment]
Thanks a lot.

Yes, exactly, it sets a union type in case the key is not set. But it's no big deal.
