### ISSUE TITLE
Missing InvalidArgument when all array arguments nullable

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8356]
https://psalm.dev/r/23251bc8d7

I expect to get the same error for abc() as I get for def()

**Comment by AndrolGenhald** [comment]
This is expected behavior, array shapes allow extra keys and there's no way to disable that at the moment (eg [this](https://psalm.dev/r/49d0b482e0) works for both). See [here](https://github.com/vimeo/psalm/issues/5299#issuecomment-1019579981) and the numerous linked issues.
