### ISSUE TITLE
first-class callables type is not inferred if it is an inherited static method

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#8363]
refs #6412

it seems the support for the first-class callables is not yet complete:
https://psalm.dev/r/bbc03df04c

**Comment by someniatko** [comment]
Found a much easier reproducer: https://psalm.dev/r/428333f418

**Comment by someniatko** [comment]
@AndrolGenhald I found a fix for the "easier" reproducer (see the message above), but I'll need your help for fixing the original case. I'll submit a PR shortly.

**Comment by AndrolGenhald** [comment]
I'm afraid I'm not very familiar with any of this, it looks like first class callable support was added in #7113 so maybe @trowski or @orklah would be better help.
