### ISSUE TITLE
PHP 8.0+ "final private" functions should give error

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8374]
https://psalm.dev/r/ee7881fa31?php=8.1

"final private" functions should give error

https://php.watch/versions/8.0/final-private-function#final-private

Related https://github.com/vimeo/psalm/issues/7668 https://github.com/vimeo/psalm/pull/7666

**Comment by AndrolGenhald** [comment]
8.0 actually: https://3v4l.org/puSnk

**Comment by weirdan** [comment]
Constructor should be allowed to be declared `final private` though: https://3v4l.org/iErYc
