### ISSUE TITLE
First class callable analysis crashes when method name is passed as a string

### ISSUE THREAD

**Issue by agustingomes** [vimeo/psalm#8377]
Issue reproduction: https://psalm.dev/r/44f1037001

### Context
`$eventListeners` values are constructed within Symfony's Dependency Injection. Unfortunately First class callable syntax is not available to define event listeners within that Symfony component, so this is an alternative way to define those listeners as callables.

Let me know if you need further information and/or context.

Edit: the version of Psalm in use at the moment of finding the issue is `dev-master 4b2935f`

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/13761b6983
