### ISSUE TITLE
str_starts_with(), str_ends_with() don't assert string as non-empty-string

### ISSUE THREAD

**Issue by SCIF** [vimeo/psalm#8378]
https://psalm.dev/r/1c49ff9da6

True result on non-empty $needle should lead to asserting the $haystack as non-empty-string.

Probably `str_*_with()` functions should be extracted from ClassMap and introduced into stub files. That's just my assumption though.

**Comment by AndrolGenhald** [comment]
[Should it](https://3v4l.org/WMpWd)?

We could probably make it conditional on `$needle` being non-empty though.

**Comment by orklah** [comment]
It's not possible to make conditional assertions though, so it would need to be a special handling.

If someone want to take a shot, it would probably need something here:
https://github.com/vimeo/psalm/blob/b69e22a33be8520bba9052d0bbabd5e6d525719c/src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php#L751

This is the method in charge of finding assertions. The first if in there will handle every `is_string`, `is_bool`... function. Then comes `is_a`, `is_callable`, `class_exists` etc...

We could probably add a `str_starts_with` case just before the final else to handle this assertion, only when the needle is not an empty string

**Comment by AndrolGenhald** [comment]
> It's not possible to make conditional assertions though

Almost works: https://psalm.dev/r/b00677937e
Just depends on #7096.

**Comment by orklah** [comment]
Oh, I didn't remember we could do that!

**Comment by AndrolGenhald** [comment]
> Oh, I didn't remember we could do that!

I was actually not really sure myself until I tried it :laughing:

**Comment by VincentLanglet** [comment]
PHPStan is even able to restrict to non-falsy-string
https://phpstan.org/r/462542dc-32e6-433c-8ee9-7adc10a8cdb0
