### ISSUE TITLE
UnitEnum cannot be cast to string

### ISSUE THREAD

**Issue by bakhtiyor** [vimeo/psalm#8380]
I have a variable declared in config/services.yaml

```
parameters:
    login_url: '%env(string:APP_FRONTEND_DOMAIN)%'
```
I am accessing it in my controller like this:

`$loginUrl = (string) ($this->getParameter('login_url') ?? "");`

Everything works fine, but psalm is giving following error:

```
ERROR: PossiblyInvalidCast - src/Controller/MyController.php:57:31 - UnitEnum cannot be cast to string (see https://psalm.dev/190)
$loginUrl = (string) ($this->getParameter('login_url') ?? "");
```
Any suggestions, how to fix it, please?

Duplicated from my stackoverflow question: https://stackoverflow.com/questions/73209831/unitenum-cannot-be-cast-to-string

**Comment by bakhtiyor** [comment]
> Hey @bakhtiyor, can you reproduce the issue on https://psalm.dev ?
Unfortunately, it is hard to reproduce it, but it is easy to check, because it is symfony code

**Comment by AndrolGenhald** [comment]
Are you using any plugins? What is the return type of `$this->getParameter()` in the vendor code? It's working fine for me, and when I check `AbstractController` it says `getParameter()` returns `array|bool|float|int|string|null`

**Comment by orklah** [comment]
https://github.com/symfony/symfony/blob/6.2/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php#L76

On 6.2 it can return an UnitEnum in special cases

**Comment by orklah** [comment]
Sorry, I was not completely clear on StackOverflow, I wanted to suggest creating the issue on the plugin repo (here: https://github.com/psalm/psalm-plugin-symfony). Ultimately, Psalm itself is correct in saying that UnitEnum is not a valid value here: https://3v4l.org/41Wr2

However, there is a special handling that allow the plugin to refine the actual return by looking at conf files. If the plugin manage to exclude UnitEnum from here, Psalm won't have an issue with the rest

**Comment by bakhtiyor** [comment]
Also created a new issue here https://github.com/psalm/psalm-plugin-symfony/issues/272. Thanks @orklah for your help.

**Comment by AndrolGenhald** [comment]
Closing this, as it's not an issue in Psalm itself.
