### ISSUE TITLE
Can't resolve relative config path with tilde (~)

### ISSUE THREAD

**Issue by LauraTaylorUK** [vimeo/psalm#8382]
I can't get psalm to run with a relative config path by using the tilde to point to my home directory.

```
$ psalm --config=~/dev/psalm.xml
Could not resolve path to config ~/dev/psalm.xml
```

I was expecting that this would be a basic linux "thing" and would just work?

Thank you.

**Comment by AndrolGenhald** [comment]
Tilde expansion is the shell's responsibility, if Psalm is getting a string with a tilde in it then your shell isn't expanding it. Using a space instead of `=` works for me with bash: `psalm --config ~/dev/psalm.xml`.
