### ISSUE TITLE
The assertion finder isn't complaining about non-list literal arrays

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#8389]
https://psalm.dev/r/40837d89d3

**Comment by AndrolGenhald** [comment]
This might actually be a bit difficult. Right now if `$is_list` is `true` then it's definitely a list, but if it's `false` it might still be a list and we just don't know it. We might actually need a `$definitely_not_list` to be tracked.

**Comment by orklah** [comment]
Though it's easy to list array transformations that leads to a list invalidation, it may be way harder to list and handle every case that could lead to an array becoming a list
