### ISSUE TITLE
No way to indicate that a returned shaped array is a list

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#8394]
https://psalm.dev/r/a606a79ed9

**Comment by AndrolGenhald** [comment]
https://psalm.dev/r/dc3cf6b8ae, though it's a [bit funky](https://github.com/vimeo/psalm/issues/8277).

**Comment by danog** [comment]
Actually I opened this as a placeholder issue since I already implemented list{} syntax on my fork, and was just fixing some testcases
