### ISSUE TITLE
Use of psalm in a Drupal project

### ISSUE THREAD

**Issue by Renrhaf** [vimeo/psalm#841]
Hello,

I tried to use psalm to improve code quality in one of our Drupal 8 projects.
But when I launch the command, many errors appears that seems related to autoloading and methods detection in the Drupal & contributed modules codebase.

Examples : 

```
ERROR: UndefinedFunction - web/modules/custom/MY_MODULE/src/Services/MyService.php:123:18 - Function Drupal\MY_MODULE\Services\t does not exist
       $message = t('Successfully inserted datas.');
```

In Drupal the `t(...)` method is globally defined to translate strings.

```
ERROR: UndefinedClass - web/modules/custom/MY_MODULE/src/Services/MyService.php:103:16 - Class or interface Drupal\node\Entity\Node does not exist
      $study = Node::create([
```

In Drupal the `Node` class is located in web/core/modules/node/Entity/Node and Drupal should be able to find it via it's autoloading workflow.

Does anyone encountered this before, and how to fix this via configuration or else ? I already tried overriding the autoloader to Drupal one but it seems it's the same as composer that is already used.

And more importantly, many thanks for this nice tool !

**Comment by muglug** [comment]
Hey! Thanks for using Psalm!

The only functions that Psalm knows to exist are ones either in the generated composer `autoload_files.php` or ones included via `include`/`require`. How does your project reference the Drupal source files?

**Comment by Renrhaf** [comment]
Hello @muglug, 

Thanks for your quick answer, here is the file I was using for psalm configuration : 

```
<?xml version="1.0"?>
<psalm
    totallyTyped="false"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config file:///app/vendor/vimeo/psalm/config.xsd">

    <projectFiles>
        <directory name="web/modules/custom" />
        <directory name="web/themes/custom" />
    </projectFiles>

    <issueHandlers>
        <LessSpecificReturnType errorLevel="info" />

        <!-- level 3 issues - slightly lazy code writing, but provably low false-negatives -->
        <DeprecatedMethod errorLevel="info" />
        <DeprecatedProperty errorLevel="info" />
        <DeprecatedClass errorLevel="info" />
        <DeprecatedInterface errorLevel="info" />
        <MissingClosureReturnType errorLevel="info" />
        <MissingReturnType errorLevel="info" />
        <MissingPropertyType errorLevel="info" />
        <InvalidDocblock errorLevel="info" />
        <MisplacedRequiredParam errorLevel="info" />
        <PropertyNotSetInConstructor errorLevel="info" />
        <MissingConstructor errorLevel="info" />
        <MissingClosureParamType errorLevel="info" />
        <MissingParamType errorLevel="info" />
        <RedundantCondition errorLevel="info" />
        <DocblockTypeContradiction errorLevel="info" />
        <RedundantConditionGivenDocblockType errorLevel="info" />
        <UnresolvableInclude errorLevel="info" />
        <RawObjectIteration errorLevel="info" />

        <!-- Suppress some errors -->
        <!-- @see https://github.com/vimeo/psalm/blob/master/docs/dealing_with_code_issues.md -->

        <!-- Do not take into account errors with Drupal\Tests\UnitTestCase -->
        <UndefinedClass>
            <errorLevel type="suppress">
                <directory name="web/modules/custom/*/tests" />
            </errorLevel>
        </UndefinedClass>

        <!-- Do not take into account undefined methods in tests (results from the above) -->
        <UndefinedMethod>
            <errorLevel type="suppress">
                <directory name="web/modules/custom/*/tests" />
            </errorLevel>
        </UndefinedMethod>
    </issueHandlers>
</psalm>
```

Drupal autoloading works specifically for modules, as described here : https://www.drupal.org/docs/develop/coding-standards/psr-4-namespaces-and-autoloading-in-drupal-8

I'm not sure yet how to make Psalm able to detect these custom autoloading rules. I'll update the issue once I will be able to make it work properly.

**Comment by lammensj** [comment]
I had the same issue and resolved it partially by adjusting 3 things:
- in psalm.xml: configured an additional autoloader (web/autoload.php)
- included [fenetikm/autoload-drupal](https://github.com/fenetikm/autoload-drupal) in composer.json (read their docs for including modules)
- autoloaded `web/core/includes/bootstrap.inc` in composer.json (autoload -> files)

The only problem left is including functions declared in `.module`-files.

**Comment by muglug** [comment]
@lammensj if there's one or two open source Drupal projects I could look at for examples, I could start on a plugin to make all that simple

**Comment by mglaman** [comment]
There are examples in https://github.com/mglaman/phpstan-drupal, for bootstrapping Drupal's autoloading. Although I think @muglug already found it :)

I would be willing to give a hand as well.

**Comment by muglug** [comment]
@mglaman I have zero experience with Drupal, though - I don't know how it approaches file loading.

Psalm can be told that `.module` files are the same as PHP:
```
    <fileExtensions>
        <extension name="php" />
        <extension name="module" />
    </fileExtensions>
```

I could add some sort of plugin hook for that, too.

**Comment by mglaman** [comment]
@muglug bringing this up once again, does Psalm provide a way to add a `bootstrap.php` to bootstrap autoloading at all? I was looking and I see it does autoloader detection, but Drupal does some magical non-dumped autoloading that we'd have to implement.

**Comment by muglug** [comment]
@mglaman yeah, `autoloader="path/to/autoloader.php"`

**Comment by muglug** [comment]
in your Psalm config

**Comment by slifin** [comment]
Does any one have psalm working in a Drupal code base? I'm looking at Drupal 7 specifically

**Comment by mortenson** [comment]
I'm working on adding Drupal support - nothing to show yet but I'll post back here when a repo is public.

**Comment by xurizaemon** [comment]
🔥 🌮 🔥

Excited to see @mortenson has shared this work - see https://mortenson.coffee/blog/drupal-security-testing-everyone/
