### ISSUE TITLE
Remove the memory limit hard coded 

### ISSUE THREAD

**Issue by auroraeosrose** [vimeo/psalm#842]
The excuse to just use the thread option is useless on windows since it doesn't support the threading with the pcntl forking model

And on windows - the 32 bit version of PHP is still in use in many places (sigh)

With the memory limit commented out, everything works fine.

```
Checks took 1.29 seconds and used 57.952MB of memory
Psalm was able to infer types for 86.760% of analyzed code (37 files)
```

If you're absolutely sure you need to police people - I'd recommend making the memory limit a command line option so people can override it without hacking code.

**Comment by muglug** [comment]
I don't want to disable the memory limit in a minor version, but I've added `--use-ini-defaults` to prevent Psalm from overriding any PHP defaults.

**Comment by auroraeosrose** [comment]
thank you :)

**Comment by muglug** [comment]
Keeping this around for next major version

**Comment by SignpostMarv** [comment]
without:
> Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 114688 bytes) in D:\_git\daft-framework\daft-markup\vendor\composer\autoload_static.php on line 254
> PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 114688 bytes) in D:\_git\daft-framework\daft-markup\vendor\composer\autoload_static.php on line 254

with:
> Checks took 7.25 seconds and used 56.890MB of memory
> Psalm was able to infer types for 100.000% of analyzed code (18 files)

something funky is going on here if 56mb > 4gb :P

**Comment by SignpostMarv** [comment]
@muglug @auroraeosrose have just ran some experiments by manually editing `./vendor/vimeo/psalm/src/psalm.php`:

- `ini_set('memory_limit', '4096M');` : fails
- `ini_set('memory_limit', '4096MB');` : fails
- `ini_set('memory_limit', '4G');` : fails
- `ini_set('memory_limit', '4GB');` : fails
- `ini_set('memory_limit', 4294967296);` : passes
- `ini_set('memory_limit', '4294967296');` : passes
- `ini_set('memory_limit', '4294967296b');` : passes
- `ini_set('memory_limit', 4 * 1024 * 1024 * 1024);` : passes

> $ php -v
> PHP 7.0.20 (cli) (built: Jun  6 2017 14:32:47) ( ZTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

looks like `--use-ini-defaults` is unnecessary if `ini_set()` is called with an int for `memory_limit` ?

**Comment by fkupper** [comment]
Is this ever gonna change?

**Comment by weirdan** [comment]
There's a flag (`--memory-limit`) introduced in #3947
