### ISSUE TITLE
FilesystemIterator current return value is incorrect in CallMap

### ISSUE THREAD

**Issue by auroraeosrose** [vimeo/psalm#843]
### FilesystemIterator current reflection is incorrect

The mapping for FilesystemIterator is incorrect
the return value for the current function is mixed, NOT string
what this returns is controlled by the second parameter to the constructor, and the DEFAULT is an SplFileInfo instance

(default flags are FilesystemIterator::KEY_AS_PATHNAME | FilesystemIterator::CURRENT_AS_FILEINFO | FilesystemIterator::SKIP_DOTS)

Changing

https://github.com/vimeo/psalm/blob/master/src/Psalm/CallMap.php#L2774

'FilesystemIterator::current' => ['string'],

to 

'FilesystemIterator::current' => ['mixed'],

would be enough - although really

'FilesystemIterator::current' => ['string|SplFileInfo'],

if that syntax works - would be the most accurate

**Comment by muglug** [comment]
I've made it `mixed` for now - making it `string|SplFileInfo` (which is valid syntax) would penalise code that rightly assumed the output could only be one of `string` or `SplFileInfo`. But I'll also think of a better workaround for this.

**Comment by muglug** [comment]
Thanks for ticketing, though!
