### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by ftzdomino** [vimeo/psalm#844]
I haven't been able to narrow this down to a concise test case, but the fix seems straightforward.
./vendor/bin/psalm

Gives output:
Warning: Division by zero in /home/jsnell/public_html/psalm/vendor/vimeo/psalm/src/Psalm/Codebase/Analyzer.php on line 324
Psalm was able to infer types for nan% of analyzed code (5 files)

This may fix the issue:
```
	$total_percent = '';
	if ($total === 0) {
            $total_percent = '0';
        } else {
            $total_percent = number_format(100 * $nonmixed_count / $total, 3);
	}
        return 'Psalm was able to infer types for ' . $total_percent . '%'
            . ' of analyzed code (' . $total_files . ' file' . ($total_files > 1 ? 's' : '') . ')';
```

**Comment by muglug** [comment]
Thanks, I've fixed with a specific error message
