### ISSUE TITLE
docblock assertions on methods not working

### ISSUE THREAD

**Issue by annervisser** [vimeo/psalm#8446]
Docblock assertions on methods don't seem to have any effect.

The example from the docs fails (https://psalm.dev/docs/annotating_code/adding_assertions/#asserting-return-values-of-methods):
https://psalm.dev/r/66ce8ba63c

Minimal reproduction:
https://psalm.dev/r/fb21e226a7

**Comment by orklah** [comment]
Please note the phrase after this example:
> Please note that the example above only works if you enable [method call memoization](https://psalm.dev/docs/running_psalm/configuration/#memoizemethodcallresults) in the config file or annotate the class as [immutable](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-immutable).

As far as I know, doc examples can't fail because they're part of the CI of Psalm itself (meaning Psalm ensure each of its doc example still work properly on each build)
