### ISSUE TITLE
Multiple DocBlock statements

### ISSUE THREAD

**Issue by phpshko** [vimeo/psalm#8455]
In many files on our project, we used multiple DocBlock  statements, like that https://psalm.dev/r/4d4ff8ea51 and psalm show errors. If used in one statement all is correct https://psalm.dev/r/5a967f996f 

I found an issue with the reverse case https://github.com/vimeo/psalm/issues/493

Is this bug, or we should declare all variables in one statement?

**Comment by orklah** [comment]
I think it's a limitation of PHP-Parser. IIRC, docblocks are linked to the next statement, so when two docblocks are declared, one is just not linked.

You can add a semicolon to trick PHP-Parser to see a statement but it's pretty ugly...

**Comment by AndrolGenhald** [comment]
Just to illustrate the workaround: https://psalm.dev/r/9389002e05

**Comment by phpshko** [comment]
Ok, thanks for the workarounds. 
If this error is not in the psalm part, then we will rewrite it to single docblock
