### ISSUE TITLE
Include the path to the config file used in json report

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8458]
When using dynamically generated psalm config files, it would be extremely helpful for debugging if the config file used for a psalm run were included in the json output.

**Comment by AndrolGenhald** [comment]
I don't think we actually support "dynamically generated psalm config files" do we? Is that some external tooling you've built?

**Comment by orklah** [comment]
I wouldn't want to clutter outputs too much if it can be avoided. Can't you just display the command you just run that displays the --config ?
