### ISSUE TITLE
Inferred return type is more specific than declared return type

### ISSUE THREAD

**Issue by tomtomau** [vimeo/psalm#847]
Given this example: https://getpsalm.org/r/94be4f9e5c

As a user, my expectation is that I can implement Bar without any violations as it is technically valid?

Obviously, Baw is a passable work around for now, but it would be great to not have to be so explicit.

Cheers!
Tom

**Comment by fesor** [comment]
your code is valid from LSP point of view, psalm just doesn't encounter covariance/contravariance... this is really annoying sometimes.

**Comment by muglug** [comment]
Thanks for bringing this up.

Psalm knows that this is annoying, and ignores it by default for all generated configs: https://github.com/vimeo/psalm/blob/master/assets/config_levels/1.xml

I agree with you all that your example shouldn't be a bug, nor: https://getpsalm.org/r/338d5a3582

Two possible solutions:
 - only enable check for private methods and regular functions
 - disable check for protected/public methods if Psalm detects that method is overridden somewhere (obviously only covers your code, not any importers)

Which would you prefer?

**Comment by muglug** [comment]
I chose the latter here - disable check for protected/public methods if Psalm detects that method is overridden somewhere (obviously only covers your code, not any importers)
