### ISSUE TITLE
Type information missing from autoloaded functions?

### ISSUE THREAD

**Issue by Riimu** [vimeo/psalm#848]
I'm not sure if I'm doing something wrong, but it seems that psalm has some issues getting type information for functions defined in autoloaded files via configuration or include files from autoloaded composer files.

To illustrate, let's say that we have a project with following files

* `src/functions.php`
* `src/MyClass.php`
* `autoload.php`
* `composer.json`

The `src/functions.php` is defined like:

```php
<?php

namespace TestSpace\Stuff;

/**
 * @return string[]
 */
function getStrings(): array
{
    return ['foo', 'bar'];
}
```

The `src/MyClass.php` as:

```php
<?php

namespace TestSpace\Stuff;

class MyClass
{
    public function outputString(): void
    {
        $values = getStrings();

        foreach ($values as $value) {
            $this->output($value);
        }
    }

    private function output(string $string): void
    {
        echo $string;
    }
}
```

The `autoload.php` as:

```php
<?php

require_once __DIR__ . '/src/functions.php';
```

 And finally the `composer.json` as:

```json
{
  "autoload": {
    "psr-4": {
      "TestSpace\\Stuff\\": "src/"
    },
    "files": [
      "autoload.php"
    ]
  }
}
```

With this setup, if we run `psalm --init src 1` and run the analysis, we get the following errors:

```
$ psalm
Scanning files...
Analyzing files...

ERROR: MixedAssignment - src/MyClass.php:11:29 - Cannot assign $value to a mixed type
        foreach ($values as $value) {


ERROR: MixedArgument - src/MyClass.php:12:27 - Argument 1 of TestSpace\Stuff\MyClass::output cannot be mixed, expecting string
            $this->output($value);


------------------------------
2 errors found
------------------------------
```

**However**, if we change the composer `files` autoloader entry to load the `functions.php` directly (i.e. via `"files": ["src/functions.php"]`, we won't get any errors.

Also, if we dropped the the "files" entry entirely from the autoloader and used either `autoload="autoload.php"` or `autoload="src/functions.php"` xml configuration instead, we will also get the errors. Whether the file is included or not directly via a `<file>` tag seems to have no effect.

It seems an odd inconsistency that adding the file directly to the autoloaded files will result in the types being detected correctly, but it no other case they are.

I've attached the sample test case where typing `psalm` will result in the errors: 
[psalm-types.tar.gz](https://github.com/vimeo/psalm/files/2148592/psalm-types.tar.gz)

**Comment by muglug** [comment]
Related to: https://github.com/vimeo/psalm/issues/629#issue-309296051 where I removed the functionality that would interpret these docblocks to prevent another bug.

It should be possible to overwrite the autoloaded function information, scanned in `Psalm\Codebase\Reflection` with information found in `Psalm\Visitor\DependencyFinderVisitor`.

**Comment by muglug** [comment]
Thanks for the detailed description and files, btw!
