### ISSUE TITLE
Feature: environments to allow some specific checks for CLI

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8485]
https://psalm.dev/r/f8d4abb85a

Some variables are only accessible in CLI (e.g. $argv, $argc) as well as some things do only/not work in CLI, e.g. `filter_input` doesn't work in CLI with `INPUT_SERVER` (always empty),...
By checking for environments a lot of those often "hidden" issues could be unearthed.

**Comment by orklah** [comment]
Merged :)
