### ISSUE TITLE
Compress cache using gzip

### ISSUE THREAD

**Issue by dkarlovi** [vimeo/psalm#8495]
Using gzip, cache could be stored more efficiently space wise. For reference, my PHPStan cache folder is 16MB, my Psalm folder is 385MB on a project, they run in about the same time.

[Symfony uses gzinflate / gzdeflate to decorate the cache marshaler](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Cache/Marshaller/DeflateMarshaller.php), Psalm could do the same. It provides quite an improvement over nothing or igbinary, gzip features are also bundles in PHP while igbinary might require additional extensions.

cc @bendavies @orklah

**Comment by orklah** [comment]
I'd be fine with that. Provided some tests on the space gained and time added (if too impactful, we could put this under a config flag).

It shouldn't be too difficult to implement

**Comment by callmetushar123** [comment]
@orklah I am new to open source can you guide me a bit?

**Comment by dkarlovi** [comment]
@callmetushar123 the idea here would be to add the concept from Symfony's [`DeflateMarshaller`](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Cache/Marshaller/DeflateMarshaller.php) to Psalm's [`FileStorageCacheProvider`](https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Provider/FileStorageCacheProvider.php).

**Comment by dkarlovi** [comment]
BTW thinking about how the implementation would work here, there's an opportunity to also fix #8679 here:

1. read current cache (even non-`gzdeflate`d) as if it was, using `gzinflate`
2. current (old) cache will not be able to be inflated, because it wasn't deflated, producing an error
3. we treat this error as if there wasn't a cache file to read at all, this is exactly what fixes #8679 (making reading cache more robust)
4. store cache using `gzdeflate`, meaning 2. and 3. will no longer trigger (but we still keep the robustness)

@orklah what do you think?

**Comment by dkarlovi** [comment]
@callmetushar123 there's typically no assigning of issues, you've stated you'll work on it, [create a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) and start working on it, it's super unlikely somebody will jump in and steal your thunder, especially since you've said here you'll work on it.

**Comment by orklah** [comment]
We don't use assignation a lot but it can help track things so I did :)

The steps @dkarlovi provided seems on point to ensure a correct deployment for the new version. Another possibility would be to make sure Psalm stores its cache in a directory named like with its version. This would ensure any change in cache structure will never cause deployment issues. (However, we would need to remove old directories if they exist)

**Comment by dkarlovi** [comment]
We could do the same thing with versions: reuse cache only if versions match, otherwise treat like it's not there and overwrite. But IMO that's not part of this effort.
