### ISSUE TITLE
Ignore missing void return types

### ISSUE THREAD

**Issue by skyrpex** [vimeo/psalm#85]
AFAIK, there's no need to explictely document when a method returns void, am I right?

Psalm still triggers...

BTW, awesome project!

**Comment by muglug** [comment]
You can disable the requirement for `void` return types via the config (added at the behest of @nikic).

Psalm will complain unless you have `requireVoidReturnType="false"` attribute-value pair in your config.

That config attribute was [just](https://github.com/vimeo/psalm/commit/a0711de023d7847ed84f83679b82afe57657004b) renamed to be more explicit, so if you don't have latest dev-master use `addVoidDocblockReturnType` instead.

**Comment by skyrpex** [comment]
Oh, sorry, I must have skipped that option while looking at the docs.

Thanks!

**Comment by muglug** [comment]
Not to worry. There are many, many options! And I also only added that to the wiki yesterday.
