### ISSUE TITLE
conflict with type hint vs conditional

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#850]
https://getpsalm.org/r/d81661ee83

```php
/**
* @param scalar|array|null $thing
*/
function Foo($thing) : void
{
  if ( ! is_null($thing) && is_numeric($thing)) {
    echo 'bar';
  }
}
```

psalm correctly determines that $thing goes from being `scalar|array|null` to `scalar|array`, but seems to incorrectly assume that a subset of scalar can't be numeric. ints, floats, specifically formatted strings can all be numeric- so I'm guessing that psalm is bypassing any aliasing of `scalar` to the full set of scalar types ?

**Comment by muglug** [comment]
Thanks!

**Comment by SignpostMarv** [comment]
yw :D
