### ISSUE TITLE
null type ignored

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#851]
if a method or function specifies two or more types, one of which is null, null is ignored.

https://getpsalm.org/r/6ac44a6fd1

```php
/**
* @param scalar|null|array|object $b
*/
function Foo1(string $a, $b) : array
{
  return [$a, $b];
}

Foo1('a', null);
```
> Psalm output (using commit 1ca5ef9): 
>
> ERROR: NullArgument - 10:11 - Argument 2 of Foo1 cannot be null, null value provided

**Comment by weirdan** [comment]
>  specifies two or more types, one of which is null, null is ignored.

That's three or more. `null|string`,`null|object` etc work fine.

**Comment by muglug** [comment]
I think it’s more about the union of those _particular_ types (as this works fine: https://getpsalm.org/r/abba1fe149)

**Comment by muglug** [comment]
Null is ignored in `null|object|*`
