### ISSUE TITLE
False postive on print_r($v, true)

### ISSUE THREAD

**Issue by mmcev106** [vimeo/psalm#8519]
The `print_r()` function should NOT be considered a taint sink when the second parameter is `true` (causing the value to be returned rather than printed).  The following example should NOT report any taints:

https://psalm.dev/r/d533d3ca4c

**Comment by orklah** [comment]
closing as duplicate of https://github.com/vimeo/psalm/issues/4669

**Comment by mmcev106** [comment]
It looks like I also posted this here #6806 last year.  I did attempt to look for duplicates.  Apparently not very well...

**Comment by orklah** [comment]
No worries ;) It's hard for me to find things even when I know there are in there sometimes so I get it can be hard!
