### ISSUE TITLE
Incorrect type inference when using `key`/`current`/`reset` on non-empty array

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#8521]
Hey there,

when both key and value types of an array are known, I'd expect psalm to be able to infer the return value of `key`/`current` in case of a `non-empty-array` or `non-empty-list`.

https://psalm.dev/r/bc365e8080

Not sure if this can already be done with some conditional magic (even tho, I did never understood how these internal functions are typed 😅).

But something like this might work, right?
```php
/**
  * @template T of array-key
  * @param array<T,mixed> $array
  * @return ($array is non-empty-list ? 0|positive-int : ($array is non-empty-array ? T : mixed))
  */
function key(array $array): mixed
{
}

/**
  * @template T
  * @param array<mixed,T> $array
  * @return ($array is non-empty-list ? T : ($array is non-empty-array ? T : T|false))
  */
function current(array $array): mixed
{}

/**
  * @template T
  * @param array<mixed,T> $array
  * @return ($array is non-empty-list ? T : ($array is non-empty-array ? T : T|false))
  */
function reset(array $array): mixed
{}
```

**Comment by orklah** [comment]
Yeah, that looks like it would work :) In fact, you can check that it does by just renaming the functions: https://psalm.dev/r/b9f82704bf

Note that is theory, a non-empty-list is a non-empty-array so you should be able to simplify your condition by getting rid of the non-empty-list case

**Comment by boesing** [comment]
Nice, I'll give that a try when I find some time.
Sorry for raising so many issues without trying to fix them on my on in an appropriate timeframe. 😅

**Comment by orklah** [comment]
It's okay :) We're short staffed too! Issues are still useful for other users when searching an issue or to centralize discussions
