### ISSUE TITLE
Exception when using @template T of Closure

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#8526]
https://psalm.dev/r/cb38f1fdc4

Server returns 500.

`Uncaught Exception: RuntimeException PHP Error: Undefined array key 0 in vendor/vimeo/psalm/src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php:1052`

**Comment by orklah** [comment]
Looks fixed :)

**Comment by vudaltsov** [comment]
Thank you!
