### ISSUE TITLE
count on shaped list does not change the number of possibly undefined elements

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#8528]
https://psalm.dev/r/7dc77f9e1d

**Comment by orklah** [comment]
Yeah, you won't be able to improve on that without a complete rework of Psalm type system or the introduction of strict-arrays

`array{0, 1}|array<never, never>` is instantly collapsed into `array{0?: 0, 1?: 1}` which means, an array with two possibly defined elements *but maybe more*. The last part is the problem, once you acknowledged there could be keys that are not documented, count is not enough to be sure 0 and 1 are actually defined.

**Comment by danog** [comment]
Actually, I'm aware of that (should've directly provided the collapsed typehint in the phpdoc), but the problem is that asserting the count on an (at least sealed) list should guarantee that keys are defined: https://psalm.dev/r/a18b67f382

**Comment by orklah** [comment]
yeah, seems legit on sealed arrays indeed, though it's quite rare to find those in the wild given dev are unlikely to have to count-check the result of merging two known sealed array. But it will be useful one day when strict-array are added
