### ISSUE TITLE
Elseif causes incorrect type inference (4.x only)

### ISSUE THREAD

**Issue by theodorejb** [vimeo/psalm#8532]
Reproduction:

```php
function possiblyNull(): string|null
{
    return random_int(0, 1) ? "x" : null;
}

$data = [
    'a' => possiblyNull(),
    'b' => possiblyNull(),
    'c' => possiblyNull(),
];

if (!$data['a'] || !$data['b']) {
    throw new Exception("a or b is null");
} elseif (!$data['c']) {
    throw new Exception("c is null");
}

echo strlen($data['a']);
```

Expected: no error

Actual result:

> ERROR: MixedArgument - test.php:20:13 - Argument 1 of strlen cannot be mixed, expecting string

If I remove the `elseif` condition, the error goes away. E.g. there is no error with the following identical logic using `if` instead of `elseif`:

```php
if (!$data['a'] || !$data['b']) {
    throw new Exception("a or b is null");
}

if (!$data['c']) {
    throw new Exception("c is null");
}
```

This bug seems specific to the 4.x branch (I reproduced with v4.27 and the latest commit on the 4.x branch, but couldn't reproduce with dev-master or on https://psalm.dev/).

**Comment by orklah** [comment]
Can you also reproduce it on an oldest version of Psalm?

If this is a recent regression, it may not be merged on master yet. If this is something that was fixed on master, I fear this won't ever be on 4.x. There was a lot of change made on master that can't be put back in current version. 

Psalm 5 is to be released very soon now

**Comment by theodorejb** [comment]
I tested all the way back to v4.7.1 and the issue also exists there. It turns out it was fixed on master by https://github.com/vimeo/psalm/commit/faaf7690f64aef40865e1f81a3fd34f51db4a50c (pull request #7484).

If Psalm 5 is planned for release soon, I'm fine with closing this issue as won't-fix for 4.x.

**Comment by orklah** [comment]
Nice to know this PR has fixed things :)

I'll close this then!
