### ISSUE TITLE
For loop does not define proper int range

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#8534]
https://psalm.dev/r/cec3f51807

**Comment by orklah** [comment]
I know :( I never was able to make it run correctly. If you're interested in taking a look, I made a summary of the issue I encountered somewhere, tell me and I'll find it

**Comment by danog** [comment]
Yeah, I'd be interested in making this work eventually (after I finish immutability :)

**Comment by orklah** [comment]
Here's what I concluded when I tried to work on that:
https://github.com/vimeo/psalm/pull/6474#issuecomment-958198889

a few point are obsolete or not very relevant. For example, we got rid of positive-int and LoopInvalidation  definitely needs to go, but other points are still an issue. Especially the last one.

**Comment by orklah** [comment]
Seems fixed :)

**Comment by danog** [comment]
Ayy, didn't expect the fix to be so small :)

**Comment by orklah** [comment]
Well, I prepared a lot of things, but I couldn't get it to work at that time. I think recent improvements in arrays made it possible to reenable what I commented

There are still things that needs fixing that may not be as simple!
