### ISSUE TITLE
Incorrect `LessSpecificReturnStatement` and `MoreSpecificReturnType`

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#8535]
https://psalm.dev/r/7e0e38ad57

**Comment by AndrolGenhald** [comment]
I don't think this is a bug, if you change the `@return static` to be part of the signature [PHP will complain about it](https://3v4l.org/pEXpI) (and for [good reason](https://psalm.dev/r/b01e4cb44f),  it can cause [fatal errors](https://3v4l.org/4JRIv)). Marking the class `final` [fixes it](https://psalm.dev/r/20e0cd5bc5), as does [actually returning `static`](https://psalm.dev/r/4271418468) like the interface requires.
