### ISSUE TITLE
Support for @phpstan-assert, -if-true, -if-false

### ISSUE THREAD

**Issue by ondrejmirtes** [vimeo/psalm#8536]
Hi, PHPStan 1.9.0 will bring support for the same assert tags Psalm already has. Besides supporting already widespread `@psalm-` prefix for these tags, PHPStan will also support its own tag `@phpstan-`. Could you please add support for `@phpstan-`prefixed tags so that we're cross-compatible?

Thanks :)

**Comment by orklah** [comment]
Thanks for bringing this up! We'll update Psalm to support those indeed!

For reference: https://github.com/vimeo/psalm/blob/b924032850df54dd05ffae409a709820fd6e688e/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php#L454

**Comment by VincentLanglet** [comment]
phpstan 1.9.0 is released so this it would be interesting to add this feature soon with a psalm release.

There is also
```
phpstan-self-out
phpstan-this-out
```

This seems easy to add, I opened https://github.com/vimeo/psalm/pull/8654 @orklah

**Comment by orklah** [comment]
Thanks for this! Couldn't find time to do it myself!
