### ISSUE TITLE
getpsalm.org fails to serve json response with uncaught exceptions

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#854]
in the process of testing #851, I discovered that check.php doesn't have an exception handler to return a json-formatted error message.

see: https://getpsalm.org/r/d727dcda15

**Comment by muglug** [comment]
Fixed in https://github.com/muglug/getpsalm.org/commit/7661a84a49a897ae643b2fdd66fe940e5cd24e11

**Comment by SignpostMarv** [comment]
ah, that's where the repo was (couldn't find it, would've posted there :P ).

ty for fixing :D
