### ISSUE TITLE
string not inferred after `is_string`

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#8543]
it seems psalm does not recognize a array-key beeing narrowed to string after `is_string` in this case:

https://psalm.dev/r/0032ebda88

**Comment by AndrolGenhald** [comment]
This is actually correct, `$from` needs to be an array (or immutable) for this to be safe: https://psalm.dev/r/e8fbaaba22.

See eg: https://3v4l.org/8ni6E

**Comment by staabm** [comment]
just noting, phpstan agrees with a `string` type https://phpstan.org/r/16b41380-0970-49f9-9249-c568d1a29703

but I get your point, thx for your feedback.

**Comment by orklah** [comment]
Well, we're a little more correct than phpstan on this one then  :p
