### ISSUE TITLE
?T vs T|null in extended interface

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#8549]
https://psalm.dev/r/8da86fba89

I researched a little and found that types have different order in `$input_class_storage->template_extended_params`, but [TemplateStandinTypeReplacer::getMappedGenericTypeParams on line 1209](https://github.com/vimeo/psalm/blob/52e96bea381e6cb07a672aefec791a5817694a26/src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php#L1209) implies that template param goes first.

I want to work on this issue. What is the best way to fix that?

**Comment by orklah** [comment]
Sorry, I have no idea :( I never went looking in that method yet
