### ISSUE TITLE
"Hard coded" values defined using a backed enum are wider than they could be

### ISSUE THREAD

**Issue by asgrim** [vimeo/psalm#8568]
https://psalm.dev/r/ce8f48f2b1

```php
enum Allowed: string {
    case A = 'A';
    case B = 'B';
}

// This is hard-coded so should always be 'A'
$alwaysA = Allowed::A->value;
```

In this example, the value `$alwaysA` could be `'A'|'B'`, which is technically correct, but since it is defined literally as `Allowed::A->value`, the actual type is really just `'A'`.

I'm not sure if it's possible to narrow the type of `$alwaysA` here, since it's hard-coded?

Note, that using the string literal assignment, e.g. `$alwaysA = 'A';` instead of the backed enum value, will eliminate the issue, so is a potential workaround.

**Comment by Ocramius** [comment]
Note: psalm already correctly infers the ENUM type, but fails to infer `$enum->value` afterwards.

```php
<?php

enum Allowed: string {
    case A = 'A';
    case B = 'B';
}

$a = Allowed::A;

/** @psalm-trace $a */

$aValue = $a->value;

/** @psalm-trace $aValue */

return [$a, $aValue]; // suppressing unused symbols
```

**Comment by orklah** [comment]
Thanks for the feedback!

This should be trivial to fix I think. It should be handled here (interestingly, there's already a TODO left for that):
https://github.com/vimeo/psalm/blob/b671117417578dc4df45642879317b38f1b2a65a/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php#L925

We have the AST node for the statement in $stmt for which we should be able to extract the type through $statements_analyzer->node_data->getType(). We should get a Union composed of (possibly more than one) TEnumCase. 

TEnumCase contains the case_name as a property which can be used to avoid looping over every case in handleEnumValue and instead targeting a specific case
