### ISSUE TITLE
[Proposal] Require PHP 8.0 for Psalm v5

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#8573]
Currently working on immutable storages, and usage of constructor property promotion and named parameters would really help cut down on boilerplate, since most InaccessibleProperty issues are caused by post-construction initialization of storages.

PHP 7.4 will reach EOL in [November](https://www.php.net/supported-versions.php), and IMO it would be a bit strange to release Psalm v5 with 7.4 support a month before it goes EOL.

I propose raising the minimum support version of PHP for psalm v5 to PHP 8.0.

**Comment by orklah** [comment]
Hey! We had this discussion here: https://github.com/vimeo/psalm/discussions/7171

This was admittedly a long time ago, but I'd like it to stay like this for some reasons:

- 8.0 may be a big milestone for some projects. It's easier to migrate minor versions than major so it's not likely to evolve fast
- Currently, from a quarter to a third of our users are still using 7.4. This is a lot of people to annoy
- We're bound to have some users that won't want (or be able to) run a 8.x environment only to run Psalm on their 7.X project
- I don't want to have to maintain 4.x. This means the more people are stuck with it, the more likely I'll be to have to fix things there or tell them to deal with it

**Comment by danog** [comment]
The last argument is particularly convincing, I guess we can postpone this until 2023 or psalm v6 :)
