### ISSUE TITLE
Implode does not complain about a list of non-stringable objects

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#8575]
https://psalm.dev/r/53090c73ee
https://3v4l.org/lQ7Zv

**Comment by orklah** [comment]
yeah, clearly bugged: https://psalm.dev/r/8233ca5c0a

**Comment by weirdan** [comment]
> could you PR this? Should be an easy fix, since you only need to adjust the callmap to be more strict than generic "array"

As mentioned in the linked PR, there's no problem with the `implode()` signature (which comes from stubs, not the callmap). It's Psalm's handling of `stringable-object` type (used by the stubs) that is buggy.
