### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 4 passed to  Psalm\Checker\FunctionLike\ReturnTypeChecker::checkSignatureReturnType()

### ISSUE THREAD

**Issue by roma11111122** [vimeo/psalm#858]
PHP 7.2 
"vimeo/psalm": "^2.0"

$ ./vendor/bin/psalm
Scanning files...
Analyzing files...

Notice: Undefined index: apiresponse in C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\FunctionLikeChecker.php on line 221

Notice: Trying to get property 'suppressed_issues' of non-object in C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\FunctionLikeChecker.php on line 252

Warning: array_merge(): Argument #2 is not an array in C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\FunctionLikeChecker.php on line 252

Notice: Trying to get property 'template_types' of non-object in C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\FunctionLikeChecker.php on line 261

Notice: Trying to get property 'params' of non-object in C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\FunctionLikeChecker.php on line 267

Warning: Invalid argument supplied for foreach() in C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\FunctionLikeChecker.php on line 267

Fatal error: Uncaught TypeError: Argument 4 passed to Psalm\Checker\FunctionLike\ReturnTypeChecker::checkSignatureReturnType() must be an instance of Psalm\Storage\FunctionLikeStorage, null given, called in C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\FunctionLikeChecker.php on line 457 and defined in C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\FunctionLike\ReturnTypeChecker.php:508
Stack trace:
#0 C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\FunctionLikeChecker.php(457): Psalm\Checker\FunctionLike\ReturnTypeChecker::checkSignatureReturnType(Object(PhpParser\Node\Stmt\Function_), Object(Psalm\Checker\ProjectChecker), Object(Psalm\Checker\FunctionChecker), NULL, Object(Psalm\Context))
#1 C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\StatementsChecker.php(461): Psalm\Checker\FunctionLikeChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#2 C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\Statements\Block\IfChecker.php in C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\FunctionLike\ReturnTypeChecker.php on line 508

How fix  it ?

**Comment by muglug** [comment]
I've just added an exception in `dev-master` in place of the first notice.

How is the `apiresponse` function defined in your code?

**Comment by roma11111122** [comment]
Fatal error: Uncaught UnexpectedValueException: Function apiresponse should be defined in C:\OpenServer\domains\wello\app\helpers.php in C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\FunctionLikeChecker.php:224
Stack trace:
#0 C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\StatementsChecker.php(461): Psalm\Checker\FunctionLikeChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#1 C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\Statements\Block\IfChecker.php(565): Psalm\Checker\StatementsChecker->analyze(Array, Object(Psalm\Context))
#2 C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\Statements\Block\IfChecker.php(365): Psalm\Checker\Statements\Block\IfChecker::analyzeIfBlock(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Scope\IfScope), Object(Psalm\Context), Object(Psalm\Context), Object(Psalm\Context), Array)
#3 C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\StatementsChecker.php(21 in C:\OpenServer\domains\wello\vendor\vimeo\psalm\src\Psalm\Checker\FunctionLikeChecker.php on line 224

**Comment by muglug** [comment]
Thanks - what's the context of this function? How is it defined?

**Comment by roma11111122** [comment]
`<?php

use App\Api\ApiResponse;

if (!function_exists('apiResponse')) {
    function apiResponse($result = '', int $code = 200, $errorDescription = '')
    {
        $responseData = new ApiResponse($result, $code, $errorDescription);

        return response()->json($responseData);
    }
}` 

"autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        },
        "files": [
            "app/helpers.php"
        ]
    },

**Comment by muglug** [comment]
Oh that’s very helpful, thanks!

**Comment by muglug** [comment]
Is this the _only_ place that `apiResponse` is defined? And is it defined in `app/helpers.php`?

**Comment by roma11111122** [comment]
yes, its only in `app/helpers.php` defined

**Comment by muglug** [comment]
Could you try with latest `dev-master`?

**Comment by roma11111122** [comment]
Also this error, but if i commented functions in this file `helpers.php` its worck. 
Elso i set 
`    <projectFiles>
        <directory name="app" />
    </projectFiles>`
but psalm looking mistake in vendor folder also. Possibly because of this error?

**Comment by roma11111122** [comment]
If i dont use `if (!function_exists('apiResponse')) ` its work too
