### ISSUE TITLE
Signature of non_null function

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#8589]
Is there a way to specify a function that checks if the value is not null, otherwise throws an exception. Something like the following

```php
/**
 * @template T !null
 * @param T|null $value
 * @return T
 */
function non_null(mixed $value): mixed {
    if ($value == null) {
        throw new RuntimeException;
    }
    return $value;
}
```

**Comment by orklah** [comment]
It's done through @psalm-assert: https://psalm.dev/docs/annotating_code/adding_assertions/
