### ISSUE TITLE
Psalm ignores suppress annotations

### ISSUE THREAD

**Issue by color-space** [vimeo/psalm#8596]
Is this a joke?
![image](https://user-images.githubusercontent.com/8644906/196200535-d0e4085f-7dcd-4feb-83c6-67b18f49ead4.png)

**Comment by color-space** [comment]
Even the all keyword doesn't work

![image](https://user-images.githubusercontent.com/8644906/196201917-10d7c4e3-6bce-4080-a61b-5f0923cd5634.png)

**Comment by orklah** [comment]
@color-space Please try to be more respectful there. It helps when you ask for others to do things for free.
