### ISSUE TITLE
Template related issue: how to store an object under its class-name key and return it using template

### ISSUE THREAD

**Issue by roxblnfk** [vimeo/psalm#8606]
Hello. I'm not sure, is it a bug or not?

https://psalm.dev/r/aa096baaad

I'm trying to explain to IDE and psalm that function returns an object of the same class as the one passed in the argument. Like this:

```php
$style = StyleState::getStuffValue(MyStyle::class);
assert($style instanceof MyStyle);
```

**Comment by danog** [comment]
You need something like this: https://psalm.dev/r/dadb5b043c
