### ISSUE TITLE
Using a deprecated interface in generics triggers `DeprecatedClass` error

### ISSUE THREAD

**Issue by derrabus** [vimeo/psalm#8617]
Consider this piece of code:

```php
/** @deprecated */
interface MyInterface {}

/** @extends ArrayObject<array-key, MyInterface> */
class MyClass extends ArrayObject {}
```

https://psalm.dev/r/f908cae9ef

Psalm correctly detects that the interface that is referenced here is deprecated. However, the error reported is of type `DeprecatedClass` and the message reads "Class MyInterface is marked as deprecated".

I would have expected a `DeprecatedInterface` error instead and an error message that refers to `MyInterface` being an interface, not a class.

**Comment by orklah** [comment]
Thanks for reporting!

If someone wants to tackle this:
https://github.com/vimeo/psalm/blob/0a81f8cd6cfb4d6db37b9d29c0e7b51d5af0f498/src/Psalm/Internal/TypeVisitor/TypeChecker.php#L191

We emit the issue from there, it should only be a matter of checking the ClassLikeStorage if we're dealing with an interface or a class (we have a is_interface for that) and emit the correct issue
