### ISSUE TITLE
Messed up type of `$_FILES`

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#8621]
https://psalm.dev/r/c50da60b25

`$_FILES['key']` can never be an integer: I understand that this issue was introduced by a recent PR that added types to `$_FILES`, trying to cover at least the basic case of one-dimensional file arrays.

I propose covering only the basic `array<non-empty-string, array{error: int<0, 8>, name: string, size: int<0, max>, tmp_name: string, type: string}>` case for `$_FILES`, and resolving nested types with separate logic in the ArrayFetchAnalyzer, since `$_FILES` can contain infinitely nested arrays for multi-level file arrays:

![image](https://user-images.githubusercontent.com/7339644/198024792-223eead9-451b-4f61-a0e2-fb47af921e12.png)

**Comment by orklah** [comment]
Yeah, I'd be fine reducing the complexity there. I'm not sure what's the best solution but I noticed some nonsense issues popping up with the detailed signature
