### ISSUE TITLE
False InvalidNamedArgument on 3rd LimitIterator Constructor Argument

### ISSUE THREAD

**Issue by MaxBoeh** [vimeo/psalm#8631]
The third argument of `LimitIterator` ([php doc](https://www.php.net/manual/de/limititerator.construct.php)) is named `$limit`, however Psalm has a different opinion and outputs:

> ERROR: [InvalidNamedArgument](https://psalm.dev/238) - 5:49 - Parameter $limit does not exist on function LimitIterator::__construct

The first two arguments can be passed as named arguments without any trouble.

Example: https://psalm.dev/r/6f037a2c89

**Comment by orklah** [comment]
Indeed, Psalm has it wrong: https://github.com/vimeo/psalm/blob/4.x/stubs/CoreGenericIterators.phpstub#L564

Could you fix this? :)

**Comment by weirdan** [comment]
Fixed in #8639
