### ISSUE TITLE
Generic constrains

### ISSUE THREAD

**Issue by dbalabka** [vimeo/psalm#8632]
While enjoying using Psalm, I found there is no possibility of placing a constraint on generic/templated param `T`. Mainly, interested in the not-nullable constrain that already exists for assertion annotation (e.g., `@psalm-assert !null`)

I want to create a function that accepts any nullable type `T` and returns a constrained not-nullable type otherwise throws an exception. 
```php
/**
 * @psalm-pure
 * @psalm-assert !null $value
 * @template T
 * @psalm-param T $value
 * @psalm-return T 
 *
 * @throws InvalidArgumentException
 */
function notNull($value)
{
    if (null === $value) {
        throw new InvalidArgumentException();
    }
    return $value;
}
```

It might be useful to avoid creating temporary variables to perform assertions:
```php
$firstName = getParam('firstName');
$lastName = getParam('lastName');
notNull($firstName);
notNull($lastName);

createCustomer(
    $firstName,
    $lastName
);
```

There is a workaround by creating a specific function for each type:
```php
function notNullableString(?string $value) : string
{
    notNull($value);
    return $value;
}
```

Still, the desired approach is to have a single function for any type:
```php
createCustomer(
    notNull(getParam('firstName')),
    notNull(getParam('lastName'))
);
```

Complete example:
https://psalm.dev/r/89294fd3db

Question:
1. Is there any other workaround? Maybe I've missed something.
2. Implementing constraints on generics might be a complicated task. Is there a possibility of implementing the not-nullable constraint?

References:
1. https://www.typescriptlang.org/docs/handbook/2/generics.html#generic-constraints
2. https://users.rust-lang.org/t/how-to-exclude-a-type-from-generic-trait-implementation/26156/2
3. https://docs.oracle.com/javase/tutorial/java/generics/bounded.html
5. https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/Validate.html#notNull(T)

**Comment by danog** [comment]
You probably want something like this: https://psalm.dev/r/6e62448102 :)

**Comment by dbalabka** [comment]
@danog, thanks a lot! I had this in my thoughts, but I haven't tried it for some reason.

**Comment by dbalabka** [comment]
It is a valid case for TypeScript as well: https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABGOUByIA2mA8AVAPgAoA3AQ0xAFMAuRPAHzC0wEpE68BYAKAG9eiRDGCJSFauwE8hQgE5UoIOUnKUqAbkGIAvtqgALOXADuyKmYCic43KKstPPT16hIsBIgAOcmGCji6nQAylC+YADm7HQkcDAAJrzSQhRUcgFqko7OvFAAnl5UiBjYZABGmFT4BIgAvPSIDMgsjq7g0PBIEYoAahJU9hzFLOWVOADOYX4RBEnaCkoqzdjZvLw+fgEo6CxE3VB96vasrGs8QA

**Comment by danog** [comment]
A more complete solution would actually be the following (which is what we use @ work): https://psalm.dev/r/6cd2f6a338
