### ISSUE TITLE
Meta: `mheap/github-action-required-labels` GitHub action fails on CI (on a new PR)

### ISSUE THREAD

**Issue by lptn** [vimeo/psalm#8635]
Example: https://github.com/vimeo/psalm/actions/runs/3360306942/jobs/5569335904

Output:
```
Run mheap/github-action-required-labels@v2
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
✖  fatal     Label error. Requires at least 1 of: release:typo, release:fix, release:feature, release:deprecation, release:internal, release:docs. Found: 
```

This is the only workflow fails when everything else done right
<img width="853" alt="image" src="https://user-images.githubusercontent.com/5278175/198983436-a543fc17-3e75-4241-8524-0ce607fef6a4.png">

**Comment by orklah** [comment]
@weirdan that part too?
`Warning: The `set-output` command is deprecated and will be disabled soon`?

**Comment by weirdan** [comment]
@orklah kinda. I see this a lot in various repos. I believe we will just need to upgrade the actions that use it when the time comes.

**Comment by lptn** [comment]
it provides bad UX/DX. What is the endgoal - simplify building changelogs? If son, I can invest my time to research to improve this workflow

**Comment by orklah** [comment]
@lptn Every improvement is welcome :)

The goal was to have a reminder for maintainers before merging in order to classify the PR for release notes. 

Maybe it's just a matter of better explaining that in the failure message?

**Comment by weirdan** [comment]
> it provides bad UX/DX

I do agree it's suboptimal for new contributors.

> What is the endgoal - simplify building changelogs?

That, and providing guidance to maintainers on versioning (semver). Having assembled the release notes manually in the past, I wouldn't call that task simple.

> But I need a bit more context for easy start
See https://github.com/vimeo/psalm/blob/4.x/.github/release.yml and https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

**Comment by weirdan** [comment]
Things you need to consider if you want to improve this workflow:

1. PR reviews/merges are done async. E.g. an e-mail to a maintainer would be too intrusive. As a maintainer (albeit not too active atm) I very much prefer an indicator on the PR itself and something that would block the merge until I categorized the change. This allows me to work at my own pace. 
2. It shouldn't require changes to the workflow on the contributor part. E.g. conventional commits (https://www.conventionalcommits.org/en/v1.0.0/) are a no-go.
