### ISSUE TITLE
is_array() fails to eliminate some non-array type from union

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#864]
https://getpsalm.org/r/b745e8a2dc
```php
<?php
interface I {}

function takesArray(array $_a): void {}

/** @param string|I|string[]|I[] $p */
function eliminatesNonArray($p): void {
  if (is_array($p)) { // expected: $p : string[]|I[] => compatible with array<mixed,mixed>
    takesArray($p);
  }
}
```
**Expected**: no issues
**Actual**: 
> Psalm output (using commit af14d69): 
>
> ERROR: PossiblyInvalidArgument - 9:16 - Argument 1 of takesArray expects array<mixed, mixed>, possibly different type array<mixed, string|I>|I&array provided

**Comment by muglug** [comment]
Thanks, sorry for this awkwardness introduced by https://github.com/vimeo/psalm/commit/5f251a9d88da42b14e8094ab025fdfb1d5534728#diff-cf2a24e2800013628f6c1bda0b677505
