### ISSUE TITLE
UnusedFunctionCall reported when using unserialize or serialize

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#8646]
`serialize` and `unserialize` can throw exceptions.

I got the issue with a unit test
```
public function testCannotSerialize(): void
    {
        $this->expectException(BadMethodCallException::class);
        serialize(new Foo());
    }
```

but it can be reproduce this way https://psalm.dev/r/c501b39d6d
so psalm shouldn't report an error.

**Comment by orklah** [comment]
serialize is considered pure. This is *very* questionnable, as serialize will possibly call a bunch of code that can't be determined.

Given it's pure and we don't have a specific stub that documents the function can throw, we consider it useless.

So 2 ways to fix: changing serialize to impure here: https://github.com/vimeo/psalm/blob/2ef993928c5d59a16c74de3841122ed30cd4e1ea/src/Psalm/Internal/Codebase/Functions.php#L406
or adding a stubs in CoreGenericFunctions to document the throw

**Comment by VincentLanglet** [comment]
I tried https://github.com/vimeo/psalm/pull/8650 @orklah.
The idea was to still mark serialize as pure if we're not passing an object, because I have a psalm error with the code base (see first commit).
