### ISSUE TITLE
Native return type conflicting with parent declaration, while docbloc type with same definition accepted

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#8660]
Given following example ( https://psalm.dev/r/e51bdf311a ), psalm seems to infer the incorrect types in `EnumField::fromMixedToValue()` 

```php
<?php

/** @template-covariant TValue of scalar|DateTimeImmutable */
abstract class Field
{
    /** @psalm-return TValue|null */
    abstract public function from(mixed $value): mixed;
}

/** @extends Field<string> */
class EnumField extends Field
{
    public function from(mixed $value): string|null
    {
        if ($value === null) {
            return null;
        }

        return (string) $value;
    }
}
```
```
Psalm output (using commit 51838a5): 

ERROR: [InvalidReturnStatement](https://psalm.dev/128) - 19:16 - The inferred type 'string' does not match the declared return type 'null' for EnumField::from

ERROR: [InvalidReturnType](https://psalm.dev/011) - 13:41 - The declared return type 'null' for EnumField::from is incorrect, got 'null|string'
 
Psalm detected 1 [fixable issue(s)](https://psalm.dev/docs/manipulating_code/fixing/)
```

Adding an `/** @return string|null */` solves the issue:

```php
<?php

/** @template-covariant TValue of scalar|DateTimeImmutable */
abstract class Field
{
    /** @psalm-return TValue|null */
    abstract public function from(mixed $value): mixed;
}

/** @extends Field<string> */
class EnumField extends Field
{
    /** @return string|null */
    public function from(mixed $value): string|null
    {
        if ($value === null) {
            return null;
        }

        return (string) $value;
    }
}
```
```
Psalm output (using commit 51838a5): 

No issues!
```

I wonder if type inference is overriding native types here? :thinking:

**Comment by orklah** [comment]
I think it's Psalm failing to correctly infer the type of the template when it's redefined in a child class.

The return type of `from` is `(TValue as scalar|DateTimeImmutable)|null` in `Field`. When EnumField inherits Field, `from` must take the most precise return type (which is still the parent docblock). It should become `(TValue as string)|null` because EnumFields extends `Field<string>` but I think it fails to do that and just infers something like `never|null` which become `null`.

I'm not sure where this should be fixed though

**Comment by Ocramius** [comment]
Is there any way this can be reduced further, perhaps? :thinking: 

We have suspicions, but we don't know what's going on precisely.

/cc @guidobonuzzi

**Comment by orklah** [comment]
Well, this shows the same thing: https://psalm.dev/r/57e10b684b with every unnecessary thing stripped (and I replaced null with bool just in case)

I really think it's an issue with TValue just being dropped by Psalm's inference.

**Comment by orklah** [comment]
I'm surprised but it seems to have been fixed :)

**Comment by danog** [comment]
It was thanks to https://github.com/vimeo/psalm/pull/8926, which fixed a bug I introduced earlier when I added improved the intersection logic :)
