### ISSUE TITLE
Receiving an InvalidArgument error because inheritance is ignored

### ISSUE THREAD

**Issue by ollieread** [vimeo/psalm#8667]
If I have an expected generic type of say `SomeInterface<array-key, E>` and I pass in `SomeImplementation<E>`, which implements `SomeInterface` and has a `@implement SomeInterface<int, E>` tag in the class docblock, I get told that I'm passing an invalid argument.

Recreated here: https://psalm.dev/r/29b36bd9d1

In my particular use case, an interface is used as the type, and I'm trying to pass an implementation.

**Comment by orklah** [comment]
Templates don't allow you to pass implementations by default, the explanation is there: https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance

https://psalm.dev/r/e47a05b99c should fix it for you :)

**Comment by ollieread** [comment]
> Templates don't allow you to pass implementations by default, the explanation is there: https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance
> 
> https://psalm.dev/r/e47a05b99c should fix it for you :)

Excellent, thank you. This seems to have caused a bunch of `@psalm-suppress` tags to be unused. Appreciate it.
