### ISSUE TITLE
Getting a PossiblyInvalidMethodCall error complaining about a method call on a possibly other variable

### ISSUE THREAD

**Issue by ollieread** [vimeo/psalm#8669]
I have a value storing the following property

```php
/**
 * @var \Smpl\Utils\Contracts\Supplier<\Smpl\Collections\Contracts\Collection<array-key, E>>|iterable<E>
 * @noinspection PhpDocFieldTypeMismatchInspection
 */
private Supplier|iterable $elementSupplier;
```

Then later on I have the following method.

```php
/**
 * @return iterable<E>
 *
 * @throws \Smpl\Collections\Exceptions\InvalidArgumentException
 */
protected function getElements(): iterable
{
    $elements = $this->elementSupplier;

    if ($elements instanceof Supplier) {
        $elements = $elements->get();
    }

    if (! is_iterable($elements)) {
        throw InvalidArgumentException::invalidElementSupplier(static::class);
    }

    return $elements;
}
```

The `$elements = $elements->get()` line is causing the following error, even though it's wrapped in an `instanceof` check.

```
ERROR: PossiblyInvalidMethodCall - src/Concerns/SuppliesElementsForOperation.php:40:36 - Cannot call method on possible iterable<mixed, E:Smpl\Collections\Operations\DifferenceOperation as mixed> variable $elements (see https://psalm.dev/113)
            $elements = $elements->get();
```

**Comment by orklah** [comment]
That's weird indeed, did you try reproducing on psalm.dev?

Is it a new issue since Psalm 5 or did you already had this on Psalm 4?

**Comment by ollieread** [comment]
> That's weird indeed, did you try reproducing on psalm.dev?

Will try and recreate now @orklah.

> Is it a new issue since Psalm 5 or did you already had this on Psalm 4?

No, I actually had 0 errors on 4, and now I'm down to 95 XD

**Comment by ollieread** [comment]
> That's weird indeed, did you try reproducing on psalm.dev?

Here you go, recreated https://psalm.dev/r/937ba0306a

**Comment by ollieread** [comment]
Thanks all.

**Comment by orklah** [comment]
😄 Thanks for those reports , really! Everything that can be fixed before release is a lot of pain we won't have to go through the day after !

If you have more, please post them!
