### ISSUE TITLE
TypeDoesNotContainType when comparing string to PHP_SAPI constant

### ISSUE THREAD

**Issue by mrmark** [vimeo/psalm#867]
See https://getpsalm.org/r/343806e96b

Think the trick is that the constant changes value based on how PHP is run.

**Comment by mrmark** [comment]
Workaround: use `php_sapi_name()`

**Comment by muglug** [comment]
Yeah, I may add a short-term fix for some constants. Basically it's about distinguishing the constants whose values may change based on runtime vs the ones that can't.

**Comment by mrmark** [comment]
Thanks so much!
