### ISSUE TITLE
Generic templates in traits being disconnected from implementation

### ISSUE THREAD

**Issue by ollieread** [vimeo/psalm#8671]
I have the following error, and though I'm not _entirely_ convinced it's a Psalm bug rather than a bug with my code, I've managed to recreate it here https://psalm.dev/r/1a0dd73f46.

```
ERROR: InvalidArgument - src/Concerns/SortsCollection.php:291:82 - Argument 2 of Smpl\Utils\Contracts\Comparator::compare expects E:Smpl\Collections\SortedQueue as mixed, but E:Smpl\Collections\Concerns\SortsCollection as mixed provided (see https://psalm.dev/004)
            $result = get_sign($this->getComparator()->compare($existingElement, $element));
```

If this isn't a bug, would appreciate any direction.

**Comment by orklah** [comment]
Seems like a bug to me. The analysis is aware that compare expects E:SomeClass in Comparator, it should realize it also has E:SomeClass in the trait

**Comment by klimick** [comment]
It can be closed. There are no issues anomore.
