### ISSUE TITLE
Recieving PossiblyInvalidArgument for iterable<int, mixed> when the array is created from a vararg

### ISSUE THREAD

**Issue by ollieread** [vimeo/psalm#8674]
I'm receiving a `PossiblyInvalidArgument` error when passing a variadic array to another method that explicitly expects `iterable<int, mixed>`, and it's complaining about `iterable<array-key, mixed>`.

I can fix this using `array_values()` in my code, but I believe that an array assembled from a variadic parameter will always be a list (`array<int, mixed>`).

Recreation: https://psalm.dev/r/cf0ab3145e

**Comment by danog** [comment]
Arrays created from variadic parameters can have string keys on PHP 8+ due to named arguments.

**Comment by danog** [comment]
You could try using `@no-named-arguments` though

**Comment by ollieread** [comment]
> Arrays created from variadic parameters can have string keys on PHP 8+ due to named arguments.

Ah, my bad. I actually needed that to be a thing for something else but was convinced it wasn't. Thanks.
