### ISSUE TITLE
`testCallMapCompliesWithReflection` failures

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#8675]
I'm seeing quite a few failures of `testCallMapCompliesWithReflection` locally, all caused by functions from the `ssh2` extension, both with `4.x` and `master` branches.

None of those functions has a return type provided by reflection, so the test insists that the corresponding callmap entries should have their return type specified as `''` (implicit mixed?).

This doesn't seem right to me. Return types coming from Psalm callmap are typically more detailed (and the test correctly checks for that if any return type was actually returned from reflection). In this particular case, any type coming from the callmap is going to be more specific than the implicit `mixed` specified by reflection, so it seems to me we need to drop the assertion here:
https://github.com/vimeo/psalm/blob/1e454fa3d5a182bde8dfba7ecc933645370e310d/tests/Internal/Codebase/InternalCallMapHandlerTest.php#L771

@othercorey thoughts?

**Comment by weirdan** [comment]
Nope, that's a test failure.

**Comment by othercorey** [comment]
Removing that assert seems correct. I cannot remember the specific scenario I was trying to catch there, but we should just assume the callmap is valid if PHP does not provide a return type.

I was hoping to help improve these tests more, but had to delay until other work is done.
