### ISSUE TITLE
The function version_compare can return different value types depending on parameters

### ISSUE THREAD

**Issue by mrmark** [vimeo/psalm#868]
See https://getpsalm.org/r/c6f171baf8

So...
* `version_compare($version1, $version2)` returns int (-1, 0, 1)
* `version_compare($version1, $version2, $operator)` returns bool

Which is pretty funky - they should have made two funtions right? 🤦‍♂️

**Comment by mrmark** [comment]
Link to PHP docs: http://php.net/manual/en/function.version-compare.php

**Comment by weirdan** [comment]
@muglug 
Specifying `version_compare` in CallMap as:
```
'version_compare' => ['?bool', 'ver1'=>'string', 'ver2'=>'string', 'oper='=>'string'],
'version_compare\'1' => ['int', 'ver1'=>'string', 'ver2'=>'string'],
```
does not fix this issue, unfortunately. Psalm seems to ignore the second signature, whatever that is.

The test failing is:
```
            'version_compare' => [
                '<?php
                    $a = version_compare("5.0.0", "7.0.0");
                    $b = version_compare("5.0.0", "7.0.0", "==");
                ',
                'assertions' => [
                    '$a' => 'int',
                    '$b' => 'null|bool',
                ],
            ],
```

**Comment by muglug** [comment]
Yeah, because callmap options are only used (I think) for selecting the correct param types, not for switching return types.

I'll fix in `FunctionChecker`

**Comment by muglug** [comment]
Thanks for ticketing!

**Comment by mrmark** [comment]
Thanks for fixing 👍
