### ISSUE TITLE
Literal string key is being casted to integer

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#8680]
https://psalm.dev/r/791f571f06

**Comment by orklah** [comment]
Yeah, this is closely related to https://github.com/vimeo/psalm/issues/4553 

Basically, there's no way of guaranteeing a `array<string, XXX>`. In fact, your specific code doesn't return that. The keys are integers now: https://3v4l.org/rDcdn

Unfortunately, this is the kind of issue where almost every move you'll make will break some use case. If I had to change something in PHP, this is one of the first thing I would change and I'm not the only one :p https://twitter.com/OndrejMirtes/status/1504736388247400449

**Comment by weirdan** [comment]
@orklah the literal array key type part looks wrong though: `'79268724911'|'79313044964'|...`

Shouldn't we remove those literal strings in this case?

**Comment by danog** [comment]
> https://3v4l.org/rDcdn

Holy cow that's the weirdest thing I've ever seen, and I thought I knew all of PHP's weird quirks :P

Anyway I think this can be easily fixed by checking if the string is numeric, and in this case specifying only integers.

**Comment by orklah** [comment]
> Shouldn't we remove those literal strings in this case?

I believe it was made on purpose to allow users to use the string again like this: https://psalm.dev/r/ecf0649a4d. This could possibly be removed but you'll have to handle the access side of things too and redo the implicit casting

But this will unfortunately work only with literals. For real life arrays with unknown string offset, you can never really be sure you won't end up with numeric-strings in there that will mess up your strictly typed array :p
