### ISSUE TITLE
Plugin afterExpressionAnalysis missing constants?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8682]
https://psalm.dev/r/48629160c4

Psalm knows the constant has a value of 0

However when checking with a plugin, the value/type of this constant is unknown/NULL.
Demo plugin:

```php
<?php

namespace MyPlugin;

use Psalm\Plugin\EventHandler\AfterExpressionAnalysisInterface;
use Psalm\Plugin\EventHandler\Event\AfterExpressionAnalysisEvent;
use PhpParser\Node\Expr\ConstFetch;

class MyPlugin implements AfterExpressionAnalysisInterface
{
    public static function afterExpressionAnalysis(AfterExpressionAnalysisEvent $event): ?bool
    {
        $expr = $event->getExpr();
        if ($expr instanceof ConstFetch) {
            $node_provider = $event->getStatementsSource()->getNodeTypeProvider();
            $type = $node_provider->getType($expr);
            \trigger_error($type, \E_USER_WARNING);
        }
        
        return true;
    }
}
```

If you run the plugin for https://psalm.dev/r/48629160c4, the $type is NULL.

**Comment by orklah** [comment]
Are you able to check if we pass here:
https://github.com/vimeo/psalm/blob/97e6511fab6622c1ca434c665dd895e77a0eeca2/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ConstFetchAnalyzer.php#L90
for your constant?

**Comment by orklah** [comment]
Also, can you check the name of the constant that doesn't have a type. Psalm does all kind of analyzing(stubs for example) in background that could end up in your plugin
