### ISSUE TITLE
Schedule for next 5.0 beta release

### ISSUE THREAD

**Issue by othercorey** [vimeo/psalm#8683]
Issues asking for schedule updates are annoying, but I'm not sure where else to ask.

The last 5.0 beta release was at the beginning of May, and I don't see any tags since then.

I suspect there are a lot of changes since that release and was wondering if there will be more beta and RC releases before final. Is there any way to release another beta version to so we can test new changes?

**Comment by danog** [comment]
We've actually been thinking of directly releasing v5, we're just waiting on @romm and @ondrejmirtes to merge https://github.com/CuyZ/Valinor/pull/246 and https://github.com/phpstan/phpdoc-parser/pull/161

Valinor is the main blocker here, as I've mentioned in the new docs for strict arrays, I already pinged Romain and he reassured me he'd make time to review the PR ASAP :)

**Comment by danog** [comment]
>the ecosystem can sync up to Psalm v5 after its release.

You're right, however the case of valinor is a bit different since I mentioned it in the docs, I suppose I could comment it out for the time being...

**Comment by orklah** [comment]
Sorry for the lack of communication and organization. It's mainly due to my lack of experience (and quite frankly, some apprehension!). We had very few feedback from the two pre-releases so I did not bother too much, but I suspect there has been more testing than I thought initially and it would have been good to do more of them.

We passed some big changes in the last few weeks (Thanks @danog !), they're bound to generate some catch-up for plugin maintainers but I feel Psalm 5 has been to much retarded to make a new cycle of beta so I think we're going to release it as is. 

@danog let's comment the doc, we'll do the release tomorrow unless something comes up

**Comment by danog** [comment]
>@danog let's comment the doc, we'll do the release tomorrow unless something comes up

+1 on my side, make sure to mention the performance speedups and multi-threaded bugfixes in the release notes, as the PR names aren't all that informative ;)

**Comment by othercorey** [comment]
> Sorry for the lack of communication and organization. It's mainly due to my lack of experience (and quite frankly, some apprehension!). We had very few feedback from the two pre-releases so I did not bother too much, but I suspect there has been more testing than I thought initially and it would have been good to do more of them.

Not a problem, was just curious what was hidden behind such a long day. We've only recently switch to 5.0-beta for a new major release since it supports new features.

**Comment by danog** [comment]
@romm merged the Valinor PR, we should be clear for release after the merge of 4.x :D

**Comment by ondrejmirtes** [comment]
As the maintainer of PHPStan, I'd argue there's no practical difference between doing an RC and then 5.0 vs. doing 5.0 and then 5.0.1 with fixes. I've never released a release candidate :)

**Comment by othercorey** [comment]
> As the maintainer of PHPStan, I'd argue there's no practical difference between doing an RC and then 5.0 vs. doing 5.0 and then 5.0.1 with fixes. I've never released a release candidate :)

There is a clear difference. A major release is expected to work (although there are usually bugs) and many projects will start adopting it after release. However, if that release is *never* tested and fails to even start up or load then you have many people trying to debug that error on their projects. A RC is not well tested, but it allows some projects to confirm whether it loads or not.

**Comment by ondrejmirtes** [comment]
That's not how it works. You can't make useful work without getting as much feedback as possible.

The basic kinks should be worked out thanks to CI, so any release, beta or not, doesn't have catastrophic bugs. But you can make the software better only by getting massive amounts of feedback.

**Comment by othercorey** [comment]
> That's not how it works. You can't make useful work without getting as much feedback as possible.

That seems incredibly short sighted.

**Comment by ondrejmirtes** [comment]
I'm all for making better software as fast as possible. No betas = faster progress. Betas with less users = slower progress.

Works well for me.

**Comment by othercorey** [comment]
Going to close this since the question was answered. Whatever you decide to release next is ok with me.
