### ISSUE TITLE
Magic method does not parse union type of two generic arrays in parameter type

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#870]
Possibly related to https://github.com/vimeo/psalm/issues/802

```php
<?php

/**
 * @method bool hmset(string $key, string[]|int[] $members) - Description
 */
class MyRedisWrapper {
    public function __call(string $method, array $args) {
        return false;
    }
}
$r = new MyRedisWrapper();
$r->hmset('rediskey', ['subkey' => 'value'])
```

See https://getpsalm.org/r/a55821b59b (I get both InvalidDocBlock and TooManyArguments).

- If psalm doesn't recognize the syntax, it might be better just to not parse the method or treat it like the remaining arguments are variadic

**Comment by muglug** [comment]
Thanks - I bit the bullet and added method-parsing support to the type parser
