### ISSUE TITLE
PossiblyInvalidArgument

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#8703]
I can't see how line 14 could be reached with `$literal` still being a float or an integer. IMO Psalm should consider it to be a string at that point.

https://psalm.dev/r/034888a55f

**Comment by greg0ire** [comment]
Note that this works: https://psalm.dev/r/034888a55f

**Comment by orklah** [comment]
You posted the same link twice :)

On a glance, I'd say it's an issue with `scalar` - `numeric` being unknown:
https://psalm.dev/r/c7be279a44

We could however consider that numeric will match with every int, float and only some strings, so `scalar` - `numeric` could result in `bool|string`. If I'm right, it should be a new elseif around here: https://github.com/vimeo/psalm/blob/b69e22a33be8520bba9052d0bbabd5e6d525719c/src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php#L1146

**Comment by greg0ire** [comment]
> You posted the same link twice :)

Sorry, fixed :)
