### ISSUE TITLE
Psalm incorrectly identifying array as non-empty-array

### ISSUE THREAD

**Issue by jnvsor** [vimeo/psalm#8719]
https://psalm.dev/r/d2a5d7fe21

I don't know why it's doing this, since trace shows the condition (`$v`) is `null|object`

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/d2a5d7fe21

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/bb4ef92632

**Comment by orklah** [comment]
@danog I feel like this was not the case before. Could it be a bug added in recent PR about sealed arrays additions?

**Comment by jnvsor** [comment]
@orklah It's a regression, I noticed when I updated my dependencies. I was on 212281dbcd17700bd6a577a61cbd088b7e0c8d13 before this showed up if you're looking to bisect
