### ISSUE TITLE
Supressing all issues from a directory e.g. vendor

### ISSUE THREAD

**Issue by Isinlor** [vimeo/psalm#872]
I was wondering: is there a way to suppress all issues from a directory?

I have following issue (the issue is located in vendor directory, I guess because I extend this class):
```
ERROR: UndefinedClass - vendor/zendframework/zend-feed/src/Reader/Reader.php:54:13 - Class or interface Zend\Cache\Storage\StorageInterface does not exist
    /**
     * Cache instance
     *
     * @var CacheStorage
     */
    protected static $cache = null;
```

I know that I can use [the specific issue config suppression](https://github.com/vimeo/psalm/blob/master/docs/dealing_with_code_issues.md#config-suppression), but would it be a nice feature to be able to suppress all issues in a directory e.g. vendor in my case?

**Comment by muglug** [comment]
You can remove vendor dir issues by adding 

```xml
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
```

to the `<projectFiles>` element in your config.

You're right that you're only seeing that issue because you extend that class.

I've made it so Psalm will ignore issues in `vendor` by default when initialising a config file.

**Comment by marcelloh** [comment]
But what do you write when you want to ignore more directories?

I have:
```
        <ignoreFiles>
            <directory name="database" />
            <directory name="vendor" />
            <directory name="tests" />
        </ignoreFiles>
```
and it only ignores the vendor folder :-(

**Comment by marcelloh** [comment]
I aslo tried:
```
<PropertyNotSetInConstructor>
	<errorLevel type="suppress">
	  <directory name="./database" />
	</errorLevel>
</PropertyNotSetInConstructor>
```
and
```
<PropertyNotSetInConstructor>
	<errorLevel type="suppress">
	  <directory name="database" />
	</errorLevel>
</PropertyNotSetInConstructor>
```
without any effect

**Comment by skyzyx** [comment]
Can we please re-open this? I'm running into the same issue with the latest release of Psalm.

**Comment by heiglandreas** [comment]
When adding the vendor-folder to the `ignoreFiles` section, I get a lot of errors due to `MissingDependency` in my test-folder as psalm seems not to be able to find the PHP-Unit TestCase-file. So this solution seems not to be the one we are looking for...

**Comment by XedinUnknown** [comment]
I had 3.18.2 installed, and that used to give me vimeo/psalm#4961. I allowed 4.0 and higher, got 4.3.2, and now it's giving me this:

```
ERROR: ParseError - vendor/vimeo/psalm/dictionaries/scripts/update_signaturemap_from_other_tool.php:33:31 - Syntax error, unexpected T_DOUBLE_ARROW, expecting ')' on line 33 (see https://psalm.dev/173)
uksort($new_local, fn($a, $b) => strtolower($a) <=> strtolower($b));


ERROR: ParseError - vendor/vimeo/psalm/dictionaries/scripts/update_signaturemap_from_other_tool.php:33:67 - Syntax error, unexpected ')' on line 33 (see https://psalm.dev/173)
uksort($new_local, fn($a, $b) => strtolower($a) <=> strtolower($b));
```

I can't wrap my head around why Psalm is reporting syntax errors inside the `vendor` folder. Anyone?

**Comment by orklah** [comment]
Please open a new issue and post your psalm.xml there.

**Comment by AlexP11223** [comment]
> I can't wrap my head around why Psalm is reporting syntax errors inside the `vendor` folder.

It's not "reporting" I think, it just crashes failing to parse. And it parses them to be able to resolve these functions etc. in the project itself.

But yeah, strange that we cannot just completely ignore something in vendor, e.g. for https://github.com/vimeo/psalm/issues/4961#issuecomment-756760242
