### ISSUE TITLE
`ReflectionIntersectionType#getType()` is not `@psalm-pure`

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#8720]
Just reporting this, may get to fix it myself, but for now I found it :) 

https://psalm.dev/r/bb142a0346

```php
<?php

/** @psalm-pure */
function gimmeType(ReflectionIntersectionType $type): array
{
    return $type->getTypes();
}
```
```
Psalm output (using commit 9d4c718): 

ERROR: [ImpureMethodCall](https://psalm.dev/203) - 6:19 - Cannot call a non-mutation-free method ReflectionIntersectionType::getTypes from a pure context
```

Some stub adjustments needed

**Comment by weirdan** [comment]
I think all methods here should be marked as pure: https://github.com/vimeo/psalm/blob/4e17585093880573d1ba4164bf7ca4370a5903e5/stubs/Php81.phpstub#L1

`::getName()` purity should be fixed on `ReflectionClassConstant` stub though, as it's inherited.
