### ISSUE TITLE
Splat operator calls for arrays only, yet an iterable would work just fine

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#873]
```php
function foo(iterable $args): int {
    return intval(...$args);
}
```
[Errors with:](https://getpsalm.org/r/788e69cc86)
```
Psalm output (using commit a887d09): 

ERROR: InvalidArgument - 4:12 - Argument 1 of intval expects array, iterable provided
```
Yet the code is [perfectly valid in PHP 7.1+.](https://3v4l.org/pcARL)

```php
var_dump(foo(new ArrayIterator(["123"])));
// outputs int(123)
```

[Quoting the docs:](http://php.net/manual/en/migration56.new-features.php)

> Arrays and Traversable objects can be unpacked into argument lists when calling functions by using the ... operator. 

So there comes another specimen:

```php
function foo(ArrayIterator $args): int {
    return intval(...$args);
}

foo(new ArrayIterator(["123"]));
```

[Fails with](https://getpsalm.org/r/90b9bd4652)

    ERROR: InvalidArgument - 4:12 - Argument 1 of intval expects array, ArrayIterator provided

**Comment by muglug** [comment]
Thanks! Unpacking traversables completely passed me by.
