### ISSUE TITLE
is_iterable() won't allow a null through, but that's not seen

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#874]
Example: https://getpsalm.org/r/464baf9294

    ERROR: PossiblyNullArgument - 13:18 - Argument 1 of A::d cannot be null, possibly null value provided

```php
if (is_iterable($foo)) {
  // $foo is definitely not null  
}
```
[Proof:](https://3v4l.org/Hugqa)

```php
var_dump(is_iterable(null));
// outputs bool(false)
```

**Comment by muglug** [comment]
Easy fix, I just need to add `is_iterable` to `AssertionFinder`

**Comment by sanmai** [comment]
Is that what I as a user can do?
