### ISSUE TITLE
5.0.0-rc1 on PHP 7.4

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#8743]
The composer config has constraints `"php": "^7.4 || ~8.0.0 || ~8.1.0"` but the code using functions like [str_starts_with()](https://github.com/vimeo/psalm/blob/8f39de9001c995eb203cee3399307570f322076a/src/Psalm/Internal/Type/TypeParser.php#L1475) which are not available on PHP 7.4.

So is v5 meant to support PHP 7.4?

**Comment by ADmad** [comment]
I see that the `symfony/polyfill-php80` package is required but running on PHP 7.4 I still get the error 
```
Uncaught Error: Call to undefined function str_starts_with() in phar:///some/path/psalm.phar/src/Psalm/Internal/Type/TypeParser.php:790
```

**Comment by orklah** [comment]
Thanks for the report!

That could be a phar issue. All things equal, I'd prefer avoid using polyfills when possible. 

I'll see if I can fix that tomorrow

**Comment by orklah** [comment]
Can you test with that phar? https://output.circle-artifacts.com/output/job/a6ac6136-b427-49d6-b82c-c98009efc45e/artifacts/0/build/psalm.phar

**Comment by ADmad** [comment]
Thanks, runs fine now on PHP 7.4.
