### ISSUE TITLE
PossiblyFalseOperand: false is not erased after `> 0` comparison

### ISSUE THREAD

**Issue by derrabus** [vimeo/psalm#8745]
Found while testing 5.0.0-rc1

https://psalm.dev/r/72fd1e5782

A variable typed as `int|false` is compared with zero (`$length > 0`). Afterwards, Psalm correctly infers that it has to be 1 or higher (`int<1, max>`). But it still considers `false` to be possible although `(false > 0) === false`.

**Comment by orklah** [comment]
Thanks for reporting!

Given that you tested the beta, this would be a new regression in the RC, correct?

**Comment by derrabus** [comment]
This happened on a different codebase than I tested the beta on. I can't tell whether the beta was affected already, sorry.

**Comment by derrabus** [comment]
Thank you for the quick bugfix! 🚀
