### ISSUE TITLE
Allow PHP 8.2 for Phar usage in composer.json

### ISSUE THREAD

**Issue by Andi2405** [vimeo/psalm#8747]
I am using psalm as a phar via phive. Executing it results in the following error message. 

```
Box Requirements Checker
========================
> Using PHP 8.2.0RC6
> PHP is using the following php.ini file:
  WARNING: No configuration file (php.ini) used by PHP!
> Checking Box requirements:
  E...........
                                                                                
 [ERROR] Your system is not ready to run the application.                       
                                                                                
Fix the following mandatory requirements:
=========================================
 * The application requires the version "^7.4 || ~8.0.0 || ~8.1.0" or greater.
```

I am not sure but I assume that the require php value in composer.json should be updated to allow PHP 8.2 and thereby allow the execution in PHP 8.2. The composer.json contains exactly the same statement as shown in the last line of the error message: 
```json
[...]
  "require": {
        "php": "^7.4 || ~8.0.0 || ~8.1.0",
[...]
```

**Comment by Andi2405** [comment]
> Hey @Andi2405, can you reproduce the issue on https://psalm.dev ?

Sorry @psalm-github-bot , this is not helpful in this case. Refering to phar usage only

**Comment by orklah** [comment]
Note 1: This applies to master branch (so Psalm 5 release)
Note 2: we didn't try to run our CI on PHP 8.2 yet so we have to do that before adding 8.2 in composer.json

Let's see if we can do that before releasing

**Comment by orklah** [comment]
I made https://github.com/vimeo/psalm/pull/8752 to test the CI on 8.2

We currently depends on prophecy who does not allow 8.2 yet so dependencies can't be resolved as of now. We'll have to wait until it does (or make changes to stop depending on it). 

I suggest using 8.1 for the foreseeable future

**Comment by weirdan** [comment]
> or make changes to stop depending on it

It's done; we're now using Mockery instead.

**Comment by Andi2405** [comment]
Great news, thank you very much! I guess I can expect a new release (candidate) in the next few days to weeks, right?

**Comment by weirdan** [comment]
I don't have 8.2 locally. Would you mind checking whether https://output.circle-artifacts.com/output/job/425711a7-0268-4aec-93ff-da3a7a865eef/artifacts/0/build/psalm.phar works for you?

**Comment by Andi2405** [comment]
It totatlly works for me!
