### ISSUE TITLE
issue with the handling of parse_url & conditional offsets/values

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#875]
tested [on phpstan playground w/ 0.10.1](https://phpstan.org/r/e734a56a0ce27cee7710c9096e7443f2) & [vimeo/psalm#a887d09](https://getpsalm.org/r/8f4ea156e2)

[see also near-identical phpstan issue](https://github.com/phpstan/phpstan/issues/1191)

### Summary of a problem or a feature request

when one parameter is passed to `parse_url()`, the return type is `array<int, string|int>|false`, with `false` when the input is a malformed url, with the offsets all being optional (although at least one offset will be present), and with currently only the offset corresponding `PHP_URL_PORT` being an `int` if present.

If you're using multiple parts of a parsed url, one may prefer to assign the result to a variable, rather than using multiple calls with 2 parameters.

### Code snippet that reproduces the problem

```php
<?php declare(strict_types = 1);
  
function foo(string $s) : string {
    return parse_url($s)[PHP_URL_HOST];
}

function bar(string $s) : string {
    /**
    * @var array<int, string> $parsed
    */
    $parsed = parse_url($s);
  
    return $parsed[PHP_URL_HOST];
}

function baz(string $s) : string {
    /**
    * @var array<int, string|false> $parsed
    */
    $parsed = parse_url($s);
  
    return $parsed[PHP_URL_HOST];
}

function bat(string $s) : string {
    /**
    * @var array<int, string|false> $parsed
    */
    $parsed = parse_url($s);
  
    return is_string($parsed[PHP_URL_HOST] ?: false) ? $parsed[PHP_URL_HOST] : '';
}

function bag(string $s) : string {
    /**
    * @var array<int, string|false> $parsed
    */
    $parsed = parse_url($s);
  
  	if (is_string($parsed[PHP_URL_HOST] ?? false)) {
        return $parsed[PHP_URL_HOST];
    }
    
  return '';
}


function hereisanotherone(string $s) : string {
    /**
    * @var array<int, string|false> $parsed
    */
    $parsed = parse_url($s);
  
  	if (isset($parsed[PHP_URL_HOST]) && is_string($parsed[PHP_URL_HOST])) {
        return $parsed[PHP_URL_HOST];
    }
    
  return '';
}
```

### Expected output

* Any access to an offset on the array form of a `parse_url()` result should throw up a warning that the offset is undefined, if the offset is not tested.
* the type of the `PHP_URL_PORT` should be assumed to be `int` if tested to be present, otherwise should be treated as an undefined offset.
* `is_string($parsed[PHP_URL_HOST] ?? false)` should be parsed as `string`, not `string|false` (line 41 of example)

**Comment by weirdan** [comment]
Is this the output you expect? 
```
ERROR: MixedInferredReturnType - q.php:3:27 - Could not verify return type 'string' for foo
function foo(string $s) : string {
    return parse_url($s)[PHP_URL_HOST];
}


ERROR: PossiblyUndefinedArrayOffset - q.php:4:12 - Possibly undefined array key
    return parse_url($s)[PHP_URL_HOST];


ERROR: MixedInferredReturnType - q.php:7:27 - Could not verify return type 'string' for bar
function bar(string $s) : string {
    $parsed = parse_url($s);

    return $parsed[PHP_URL_HOST];
}


ERROR: PossiblyUndefinedArrayOffset - q.php:10:12 - Possibly undefined array key $parsed[PHP_U
RL_HOST]
    return $parsed[PHP_URL_HOST];


ERROR: MixedInferredReturnType - q.php:13:27 - Could not verify return type 'string' for baz
function baz(string $s) : string {
    $parsed = parse_url($s);

    return $parsed[PHP_URL_HOST];
}


ERROR: PossiblyUndefinedArrayOffset - q.php:16:12 - Possibly undefined array key $parsed[PHP_U
RL_HOST]
    return $parsed[PHP_URL_HOST];


ERROR: MixedReturnStatement - q.php:29:9 - Could not infer a return type
        return $parsed[PHP_URL_HOST];


------------------------------
7 errors found
------------------------------

Checks took 0.14 seconds and used 22.639MB of memory
```
That's what I got with the following patch:
```patch
diff --git a/src/Psalm/CallMap.php b/src/Psalm/CallMap.php
index d5296fbc..94d9f1ee 100644
--- a/src/Psalm/CallMap.php
+++ b/src/Psalm/CallMap.php
@@ -8034,7 +8034,7 @@ return [
 'parse_ini_file' => ['array|false', 'filename'=>'string', 'process_sections='=>'bool', 'scanner_mode='=>'int'],
 'parse_ini_string' => ['array|false', 'ini_string'=>'string', 'process_sections='=>'bool', 'scanner_mode='=>'int'],
 'parse_str' => ['void', 'encoded_string'=>'string', '&w_result='=>'array'],
-'parse_url' => ['mixed', 'url'=>'string', 'url_component='=>'int'],
+'parse_url' => ['false|array{0?:string,1?:string,2?:int,3?:string,4?:string,5?:string,6?:string,7?:string}', 'url'=>'string', 'url_component='=>'int'],
 'ParseError::__clone' => ['void'],
 'ParseError::__construct' => ['void', 'message='=>'string', 'code='=>'int', 'previous='=>'?Throwable|?ParseError'],
 'ParseError::__toString' => ['string'],
```

> is_string($parsed[PHP_URL_HOST] ?? false)

I don't think Psalm can currently infer that  `is_string($parsed[PHP_URL_HOST]) === true` from that expression.

**Comment by SignpostMarv** [comment]
pretty much, yeah :D

**Comment by muglug** [comment]
Complicated response, but here goes:

- Your example has a bug ([that Psalm now detects](https://getpsalm.org/r/02ef1217be)): the array that results from calling `parse_url` without the additional component arg has string offsets `"host", "scheme"` etc. but you're requesting the array with an int offset `PHP_URL_HOST`
- Using @weirdan's patch (which Phan uses, and I manually remove when copying over changes) introduces a bunch of `PossiblyUndefinedArrayOffset` false positives when analysing Vimeo's codebase, and I'm averse to changes which I know will introduce a greater number of false positives than the number of bugs they fix
- @weirdan's also correct that Psalm only infers things from `is_string` when the expression inside is straightforward - `is_string($var)` or `is_string($array['offset'])`. It's unable to infer anything from `is_string($some_thing ?? $something_else)`
- have a look at the examples in the [test](https://github.com/vimeo/psalm/commit/166706a35d080663facf363e3457c07864d6ba88#diff-86ef5f07d504014d9647f1b7059c2c06) to see the limits of Psalm's analysis - specifically, the first test ignores `mixed` issues when inferring return type

**Comment by SignpostMarv** [comment]
not 100% sure I doing this right- mind if you take a peek before I make a pull request? https://github.com/vimeo/psalm/compare/master...SignpostMarv:875-addendum

**Comment by weirdan** [comment]
As far as I understand, function analyzer doesn't have access to the call-site argument values, so all of the following infer the same type - and thus you only need one of those:
```patch
+                    $port1 = portismaybeint("");
+                    $port2 = portismaybeint("localhost");
+                    $port3 = portismaybeint("localhost:");
+                    $port4 = portismaybeint("localhost:8080");
+                    $port5 = portismaybeint("localhost:443");
```
The return value would be typed as `array....|false`. Psalm does not execute the function, and won't be able to tell if a specific string parses or not.

**Comment by muglug** [comment]
@SignpostMarv awesome, thanks for noticing the bug! Feel free to PR

**Comment by SignpostMarv** [comment]
so pulled, in #876
