### ISSUE TITLE
PHP Warning when configuring referencedMethod

### ISSUE THREAD

**Issue by Chi-teck** [vimeo/psalm#8759]
### Problem
I have the following in my psalm.xml file.
```xml
<issueHandlers>
    <UndefinedInterfaceMethod>
        <errorLevel type="suppress">
            <referencedMethod name="ask"/>
        </errorLevel>
    </UndefinedInterfaceMethod>
</issueHandlers>
```

When running `psalm` the following error shows up.

> PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /var/www/project/vendor/vimeo/psalm/src/Psalm/Config/FileFilter.php on line 440

After checking the [corresponding code](https://github.com/vimeo/psalm/blob/5.0.0-rc1/src/Psalm/Config/FileFilter.php#L434)  I think the idea was to suppress the warnings while validating the regexp. However, it doesn't work because the temporary error handler returns `false` which causes the default error handler to continue.

### Proposed solution
Return `true` from the error handler or use `@` to suppress any errors from `preg_match()`.

**Comment by weirdan** [comment]
> Return `true` from the error handler

Yeah, I believe this was the idea. Feel free to PR.
