### ISSUE TITLE
Template params for classes implementing IteratorAggregate and Iterator

### ISSUE THREAD

**Issue by sebastianbergmann** [vimeo/psalm#8791]
After updating to Psalm 5, I get
```
ERROR: MissingTemplateParam - src/CodeUnitCollection.php:20:54 - SebastianBergmann\CodeUnit\CodeUnitCollection has missing template params when extending IteratorAggregate, expecting 2 (see https://psalm.dev/182)
final class CodeUnitCollection implements Countable, IteratorAggregate


ERROR: MissingTemplateParam - src/CodeUnitCollection.php:25:54 - SebastianBergmann\CodeUnit\CodeUnitCollection has missing template params when extending IteratorAggregate, expecting 2 (see https://psalm.dev/182)
final class CodeUnitCollection implements Countable, IteratorAggregate


ERROR: MissingTemplateParam - src/CodeUnitCollectionIterator.php:14:51 - SebastianBergmann\CodeUnit\CodeUnitCollectionIterator has missing template params when extending Iterator, expecting 2 (see https://psalm.dev/182)
final class CodeUnitCollectionIterator implements Iterator
```
for https://github.com/sebastianbergmann/code-unit/blob/main/src/CodeUnitCollection.php and https://github.com/sebastianbergmann/code-unit/blob/main/src/CodeUnitCollectionIterator.php.

Please advise what I need to put into the docblocks of those classes to make Psalm happy. Thanks!

**Comment by sebastianbergmann** [comment]
> Hey @sebastianbergmann, can you reproduce the issue on https://psalm.dev ?

No, because psalm.dev does not work right now: 
![image](https://user-images.githubusercontent.com/25218/204851733-cc1539f9-ca35-464a-96d3-ee86634cfe15.png)

**Comment by danog** [comment]
I introduced this check to make sure all template parameters of parent classes (including native iterator classes like `Iterator<TKey, TValue>`) are satisfied.

To fix, ` CodeUnitCollectionIterator` should `@implement Iterator<int, CodeUnit>` and `CodeUnitCollection` should `@implement IteratorAggregate<int, CodeUnit>`, so code using and passing around the iterators knows which types they return.

**Comment by sebastianbergmann** [comment]
Thank you, @danog, for your quick response.

Here is what I did:
```patch
diff --git a/src/CodeUnitCollection.php b/src/CodeUnitCollection.php
index b866a08..281756f 100644
--- a/src/CodeUnitCollection.php
+++ b/src/CodeUnitCollection.php
@@ -15,6 +15,8 @@
 use IteratorAggregate;
 
 /**
+ * @template-implements IteratorAggregate<int, CodeUnit>
+ *
  * @psalm-immutable
  */
 final class CodeUnitCollection implements Countable, IteratorAggregate
diff --git a/src/CodeUnitCollectionIterator.php b/src/CodeUnitCollectionIterator.php
index 7043e87..31fdbe2 100644
--- a/src/CodeUnitCollectionIterator.php
+++ b/src/CodeUnitCollectionIterator.php
@@ -11,6 +11,9 @@
 
 use Iterator;
 
+/**
+ * @template-implements Iterator<int, CodeUnit>
+ */
 final class CodeUnitCollectionIterator implements Iterator
 {
     /**
```
Now I get
```
ERROR: MissingTemplateParam - src/CodeUnitCollection.php:27:54 - SebastianBergmann\CodeUnit\CodeUnitCollection has missing template params when extending IteratorAggregate, expecting 2 (see https://psalm.dev/182)
final class CodeUnitCollection implements Countable, IteratorAggregate
```
What am I missing? Thanks!

**Comment by danog** [comment]
Hmm, applying the patch to https://github.com/sebastianbergmann/code-unit seems to work just fine, could you try running again with --no-cache?

**Comment by sebastianbergmann** [comment]
No, I did not use `--no-cache`. I "just" deleted the cache directory. When I use `--no-cache` then it works (thanks!). But when the cache directory does not exist and I do not use `--no-cache` then I get the error. Weird.

**Comment by danog** [comment]
Probably due to the global cache, have you tried both `--clear-cache` and `--clear-global-cache`?

That's a curious cache issue anyway, will try fixing later :)

**Comment by sebastianbergmann** [comment]
I only did `rm -rf .psalm/cache`. Do I want to know what the global cache is? :-) But you're right, this is a different issue. Thanks for your help on this one!
