### ISSUE TITLE
Psalm 5: Unable to determine the type for ZipArchive property

### ISSUE THREAD

**Issue by kamil-tekiela** [vimeo/psalm#8797]
I don't know if this is a more general bug, but I was able to reproduce it with `ZipArchive`.  The type should obviously be int as specified in the PHP manual. 

https://psalm.dev/r/57dc6bd858

**Comment by kamil-tekiela** [comment]
I believe it's a regression as I only observed it today after upgrading to Psalm 5.

**Comment by danog** [comment]
The problem is just an incorrect casing of the property in Psalm's stubs: https://psalm.dev/r/542226d4a0

**Comment by orklah** [comment]
I was pretty sure those were case insensitive (and actually all lowercased in the file). Maybe something changed...

It should be case sensitive however, as property are actually case sensitive in PHP itself...

**Comment by orklah** [comment]
Something did change. I actually forgot about that: https://github.com/vimeo/psalm/pull/8000/files#diff-05767d078a39dade308500b084250222a67729fbf3db16ffb1aaf0247724755dL34

We're bound to have some more property that were lowercased by error in there
