### ISSUE TITLE
Psalm 5: Unsealed arrays and compatibility with other analysis tools

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8800]
The `...` annotation for unsealed arrays in Psalm v5 is incompatible with all other PHP analysis (and parser) tools and creates tons of unnecessary errors there, which in turn means this syntax cannot be used (unless you use psalm only).

Is there perhaps the possibility of some other syntax to not have a breaking change with the whole PHP analysis ecosystem?

**Comment by danog** [comment]
The `array{}&array` syntax may also be used with the same effect, and it is compatible with other tools as well.

Obviously I personally always recommend using sealed shapes, or even better not using arrays at all and switching to valinor DTOs (though the first recommendation is considerably easier to implement compared to the second :)
