### ISSUE TITLE
Uncaught InvalidArgumentException: Could not get class storage for static in ..

### ISSUE THREAD

**Issue by veloxy** [vimeo/psalm#8801]
Hello, I'm running into issues with a particular version (5.4) of `symfony/string`

I've replicated it in this repo here, along with the error:

https://github.com/veloxy/psalm-issue

It seems to error on this line https://github.com/symfony/string/blob/5.4/AbstractUnicodeString.php#L162
The error doesn't occur on version 6.0 https://github.com/symfony/string/blob/6.0/AbstractUnicodeString.php#L159

The only difference is the return type `parent` in 5.4 and `static` in 6.0

Sorry if this is a duplicate issue

**Comment by weirdan** [comment]
Already fixed on master:
![image](https://user-images.githubusercontent.com/57403/205178338-4459346b-90f7-4bf7-a79e-232fd691be91.png)
