### ISSUE TITLE
TypeDoesNotContainType error when matching enums by interface type

### ISSUE THREAD

**Issue by tuqqu** [vimeo/psalm#8807]
I am running into a `TypeDoesNotContainType` error when trying to match an interface value either with `match` construct or a strict comparison. 

https://psalm.dev/r/87738ff2d1

I don't think it is justified, since enum implements this interface and therefore the comparison can result in `true` (the above example shows that for instance)

**Comment by weirdan** [comment]
Seems to be fixed
