### ISSUE TITLE
InvalidCast when working with ::class on generics

### ISSUE THREAD

**Issue by davidbyoung** [vimeo/psalm#8810]
I copy/pasted the relevant parts of my code here:  https://psalm.dev/r/13175e171b.  When dealing with somewhat complex constrained generics, using `::class` gives me an `InvalidCast {NameOfClass} cannot be cast to string`.  This is happening on the master branch of Psalm.

**Comment by weirdan** [comment]
Simplified a bit: https://psalm.dev/r/db793e0df3

**Comment by orklah** [comment]
That's really weird, Psalm transforms the TLiteralClassString into a TNamedObject at some point and then complains it can't cast it to string...

**Comment by vudaltsov** [comment]
Looking forward to the fix. We have many such issues in our project.

**Comment by roxblnfk** [comment]
Yet another example https://psalm.dev/r/80771a0b51

**Comment by orklah** [comment]
Fixed by @klimick  on https://github.com/vimeo/psalm/issues/8810 \o/

**Comment by vudaltsov** [comment]
Awesome, thank you!
