### ISSUE TITLE
Psalm 5 does not consider loop condition for interval of loop variable

### ISSUE THREAD

**Issue by mstilkerich** [vimeo/psalm#8821]
Hello,

  with the new integer interval types in psalm 5, I am getting spurious errors on my code base where I use an integer index as a loop variable. It appears psalm does not consider the loop entry condition for the interval type, whereas it properly appears to consider the conditions in a conditional if block.

Example:
https://psalm.dev/r/61f0d6b47d

**Comment by orklah** [comment]
Could you check again if things are better now?

**Comment by danog** [comment]
Hmm, the specific example that was specified in this issue now works OK, so I guess we can close this after all, if there's another range-related problem a new issue could be opened :)

**Comment by mstilkerich** [comment]
Hello,

  unfortunately, it still doesn't work:

https://psalm.dev/r/6da66feef1

**Comment by danog** [comment]
@mstilkerich Mind opening a new issue for this?

**Comment by mstilkerich** [comment]
Sure, i opened #8991
