### ISSUE TITLE
Variadic arguments should be resolved as list<mixed>

### ISSUE THREAD

**Issue by Chi-teck** [vimeo/psalm#8830]
Currently variadic arguments are resolved as `array<array-key, mixed>` which is more generatl type than `list<mixed>`.

Example: 
https://psalm.dev/r/0a5f9d5e55

**Comment by orklah** [comment]
Variadics can receive named arguments with a string offset: https://3v4l.org/iXILr

If you want to forbid this, Psalm has a `@no-named-argument` that will make the argument back to a list: https://psalm.dev/r/5df217293b
