### ISSUE TITLE
Psalm is deleting legitimate sections of code

### ISSUE THREAD

**Issue by nmeri17** [vimeo/psalm#8840]
When I run psalter across the project, I observed significant removals in my diffs! I'm very sure this isn't intended behavior, so it's obvious I'm doing something wrong, although I have no clue what that is. My guess is that your library has a hard time understanding or writing to file indentation style. It's actually not of my making but a Rector transformation. Anyways, I arrived at this conclusion after finding a constructor mangled from this:

```php
class ModelReplicator implements OrmReplicator {

		private BaseModel $activeModel;
  
  private $databaseConnection;
  private $migrator;

		public function __construct (OrmDialect $ormDialect, private readonly LaravelContainer $laravelContainer, 
  private readonly Container $container) {

			$this->databaseConnection = $ormDialect->getConnection();

			$this->migrator = $laravelContainer->make("migrator");
		}
```
To this:
```
<?php
	class ModelReplicator implements OrmReplicator {

		private BaseModel $activeModel;
  
  private object $databaseConnection;
  private $migrator;


  private readonly Container $container) {

			$this->databaseConnection = $ormDialect->getConnection();

			$this->migrator = $laravelContainer->make("migrator");
		}
```
But this is a benign example indentation style may excuse. The scary omission is this one that went from this:

```php
class ComponentEjector {

		private $componentList;

		public function __construct (

			private readonly Container $container,

			ComponentTemplates $templateConfig
		) {

			$this->componentList = $templateConfig->getTemplateEntries();
		}

		public function depositFiles (?array $componentsToOverride):bool {

			$hydratedComponents = array_map(
				fn($component) => $this->container->getClass($component),

				$this->componentList
			);

			foreach ($hydratedComponents as $component) {

				if (
					!$component->hasBeenEjected() ||

					$this->shouldOverride($component, $componentsToOverride)
				)

					$component->eject();
			}

			return true;
		}

		protected function shouldOverride (BaseComponentEntry $component, ?array $componentsToOverride):bool {

			if (is_null($componentsToOverride)) return false;

			if (empty($componentsToOverride)) return true;

			return in_array($component::class, $componentsToOverride);
		}
	}
```
To this:
```php
<?php
	namespace Suphle\ComponentTemplates;

	use Suphle\Hydration\Container;

	use Suphle\Contracts\Config\ComponentTemplates;

	class ComponentEjector {

		private $componentList;
		private array $componentList;

		public function __construct (

			private readonly Container $container,

			ComponentTemplates $templateConfig
		) {

			$this->componentList = $templateConfig->getTemplateEntries();
		}

		

		protected function shouldOverride (BaseComponentEntry $component, ?array $componentsToOverride):bool {

			if (is_null($componentsToOverride)) return false;

			if (empty($componentsToOverride)) return true;

			return in_array($component::class, $componentsToOverride);
		}
	}
```

One full method, gone. No clue what to attribute that to. Here's my psalm.xml

```xml
<?xml version="1.0"?>
<psalm
    errorLevel="7"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
</psalm>
```
Please let me know if you need any other detail

**Comment by nmeri17** [comment]
There are no accented characters anywhere. Not even emojis. 100% English
php characters

**Comment by orklah** [comment]
I see. It would be really great to reproduce on psalm.dev, it's really hard to debug without that...

**Comment by nmeri17** [comment]
You can see the typing is beyond just one file. If you've got a virtual
machine or somewhere isolated, you can clone the project I sent the link
to. Run composer install, then psalter

**Comment by nmeri17** [comment]
@orklah I'm about to launch my project and this issue is still pending. Please help me, brother. It just discards portions of code tabbed beyond 4 tabs

**Comment by nmeri17** [comment]
On the Rector docs, it's stated that nikic's ast is used to process files, so code formatting may not be respected. The recommended way to prevent garbled output is to have a code style enforcer in place

So I guessed that may be the reason psalter deletes my code and installedphp-cs-fixer with the following config https://pastebin.com/x3dY93eR. Re-ran psalter but it still doesn't respect it and deletes code beyond 4 tabs indentation. Is there a way to hard-connect it to the cs-fixer installation for it to understand that that isn't rubbish but code that should be preserved or processed?

**Comment by nmeri17** [comment]
I just saved that config to a .php_cs.php file and ran `psalter --issues=all --safe-types=true`, and it wiped my code as usual. This

```
<?php
	namespace AllModules\Products\Coordinators;

	use Suphle\Services\ServiceCoordinator;

	class BaseCoordinator extends ServiceCoordinator {

		public function handleHello ():array {

			return ["message" => "World"];
		}
	}
?>
```
Became this

```
<?php
	namespace AllModules\Products\Coordinators;

	use Suphle\Services\ServiceCoordinator;

	class BaseCoordinator extends ServiceCoordinator {


	}
?>
```

**Comment by orklah** [comment]
This could be related to code style but Psalter should never break code. What rector is suggesting is that after changes are made in the code, you should run your code style fixer because the changes made automatically won't respect your code style

There's definitely a bug here that should be investigated

**Comment by orklah** [comment]
Oh wait, you're using --issues=all ?

Then it might not be a bug. Psalm just detected your method is never used and removed it.

You should probably be more selective in the errors you try to fix. Some of them could be false positive (or true positive that you want to keep)

**Comment by nmeri17** [comment]
> Psalm just detected your method is never used and removed it

There are no unused methods. I have lost the context of the OP but at present, I can confirm those are either routing or controller methods. They are not invoked as usual. If that is the case, is it possible to exclude unused method in the config and run "all"? Will it be respected? The reason "all" is needed is that this is being run automatically. If errors are caught in the code, server build (which triggers this scan fails). Otherwise, it attempts to fix all suggestions using psalter. So there's no room for filtering issues. Is it possible to cover this use case?

**Comment by nmeri17** [comment]
You were absolutely correct with your assumption. Excluding those rules worked wonders!

One more thing: Analysis takes an excruciating length of time against just a handful files. Is it owing to the codebase being complex or my system specs are poor? Should I speed things up by generating baselines each time?

**Comment by orklah** [comment]
> Analysis takes an excruciating length of time

Try --debug-performance and tell us what it outputs, possibly there's some construct in your code that generates insane amount of things to check for Psalm you could ignore

Generating baseline won't help with speed (possibly the contrary)

**Comment by nmeri17** [comment]
@orklah 

------------------------------
 [0;31m8 errors [0m found
------------------------------
26 other issues found.
You can display them with  [30;48;5;195m--show-info=true [0m
------------------------------
Psalm can automatically fix 7 of these issues.
Run Psalm again with
 [30;48;5;195m--alter --issues=InvalidReturnType,MissingReturnType --dry-run [0m

to see what it can fix.
------------------------------

Checks took 417.73 seconds and used 1,240.023MB of memory
Psalm was able to infer types for 90.9910% of the codebase
-----------------
Slow-to-analyze functions
-----------------

AllModules\Products\Tests\Exceptions\DisgracefulShutdownTest::inDirectory: 108.3
7ms per node
AllModules\Products\Meta\CustomInterfaceCollection::getConfigs: 70.42ms per node

AllModules\Products\Tests\Exceptions\DisgracefulShutdownTest::isEmptyDirectory:
68.77ms per node
AllModules\Products\Meta\ProductsDescriptor::globalConcretes: 55.98ms per node
AllModules\Products\Tests\Exceptions\DisgracefulShutdownTest::assertLacksEntries
: 26.63ms per node
AllModules\Products\Tests\Exceptions\ServerBuildTest::serverIsReady: 23.15ms per
 node
AllModules\Products\Tests\Exceptions\DisgracefulShutdownTest::assertSavedFiles:
22.46ms per node
AllModules\Products\Tests\Exceptions\DisgracefulShutdownTest::safeGetIterator: 1
8.99ms per node
AllModules\Products\Tests\Exceptions\DisgracefulShutdownTest::assertEmptyDirecto
ry: 14.52ms per node
AllModules\Products\Routes\BrowserCollection::_prefixCurrent: 11.58ms per node

**Comment by nmeri17** [comment]
`inDirectory` is an asserter that scans given path for expected files. Does Psalm also try to loop the file system as well?

**Comment by nmeri17** [comment]
And this is `CustomInterfaceCollection::getConfigs`

```php
class CustomInterfaceCollection extends BaseInterfaceCollection {

		public function getConfigs ():array {
			
			return array_merge(parent::getConfigs(), [

				Router::class => RouterMock::class
			]);
		}

		public function simpleBinds ():array {

			return array_merge(parent::simpleBinds(), [

				_module_name::class => ModuleApi::class,

				UserContract::class => EloquentUser::class
			]);
		}
	}
```

The parent returns strings without computation. Nothing suggests it should take longer than usual

**Comment by orklah** [comment]
If you try to ignore those 2 files, does your analysis speed up significantly?

**Comment by nmeri17** [comment]
I can only see the ignore directory directive. How do I ignore files?

**Comment by orklah** [comment]
There's an ignoreFiles in projectFiles that can contain either directory or file in your config

**Comment by nmeri17** [comment]
> There's an ignoreFiles in projectFiles that can contain either directory or file in your config

Yea. I'm using this now

```xml
<projectFiles>
        <directory name="AllModules" />

        <ignoreFiles>
            <directory name="vendor" />
            <directory name="ModuleTemplate" />

            <file name="AllModules\Products\Tests\Exceptions\DisgracefulShutdownTest.php" />

            <file name="AllModules\Products\Meta\CustomInterfaceCollection.php" />
        </ignoreFiles>

        <ignoreFiles>
            <directory name="*/compiled-views" />
        </ignoreFiles>
    </projectFiles>
```
It cut down scan time to 114.30 seconds. So I guess, I have to provide wildcards for those classes, right?

`<file name="*/DisgracefulShutdownTest.php" />`

Is it possible to do it for the underlying methods themselves, since they will be used on other classes and not just these? This specific `inDirectory` is from a trait

**Comment by orklah** [comment]
You can't exclude methods only from analysis, only files.

You could try to replicate to see what's taking a long time so we could see if we can work around that

**Comment by nmeri17** [comment]
> You could try to replicate to see what's taking a long time

Functions making use of this method
https://github.com/nmeri17/suphle/blob/37f0c25bd7af21b333adce7d46ca0c194e5dde28/src/Testing/Condiments/FilesystemCleaner.php#L79
