### ISSUE TITLE
Include specifics about invalid type references

### ISSUE THREAD

**Issue by dkarlovi** [vimeo/psalm#8842]
It's hard to understand WHAT references are actually invalid

https://psalm.dev/r/e582824f31

**Comment by weirdan** [comment]
With #8996 it would read:

| SEVERITY | LINE | ISSUE           | DESCRIPTION                                                            |
|----------|------|-----------------|------------------------------------------------------------------------|
| ERROR    | 55   | InvalidDocblock | @psalm-type TCreateQueryArgs contains invalid reference: Invalid type alias TCreateQueryArgsMatching provided                                |
| ERROR    | 55   | InvalidDocblock | @psalm-type TCreateQueryArgsMatching contains invalid reference: Invalid type alias TRawQuery provided                                       |
| ERROR    | 55   | InvalidDocblock | @psalm-type TRawQuery contains invalid reference: Invalid type alias TSourceArgs provided                                                    |
| ERROR    | 55   | InvalidDocblock | @psalm-type TSortArgs contains invalid reference: Invalid type alias TSortArg provided                                                       |
| ERROR    | 55   | InvalidDocblock | @psalm-type TSortArg contains invalid reference: Invalid type alias TSortArrayArg provided                                                   |

It won't tell you *why* it's invalid, though.

**Comment by dkarlovi** [comment]
Thanks @weirdan! 🎉
