### ISSUE TITLE
Can not use class constants type as part of new list{} (n-tuple) types

### ISSUE THREAD

**Issue by gmazzap** [vimeo/psalm#8844]
In Psalm v5, we can now define n-tuple types via `list{T1, T2}`.

For a while now, we can also use `ClassName::SOME_PREFIX_*` to declare a type pointing to a set of class constants having a given prefix.

However, we can't use the two things together. See:

https://psalm.dev/r/f185d94aae

I'm guessing Psalm finds a `::` inside an array-type definition and assumes it is an array _key_, not considering it could be an array _value_.

**Edit**: please note, in array-shapes definition it works: https://psalm.dev/r/9df7ce7dca so looks like it is really a matter of Psalm assuming `::` is used in the key.

**Comment by weirdan** [comment]
Implemented in #10678
