### ISSUE TITLE
Suppress UnusedMethod using docblock annotation

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#885]
![image](https://user-images.githubusercontent.com/57403/42599149-04f40b48-8567-11e8-9e1e-f38cdd235bc6.png)

Currently Psalm seems to ignore method-level docblock suppression of `UnusedMethod` (see this travis job output: https://travis-ci.org/vimeo/psalm/jobs/402845680#L852-L854). However it seems to be the most natural place to suppress this issue.

**Comment by muglug** [comment]
Yeah, this could be better

**Comment by muglug** [comment]
Happily a very simple fix, thanks
