### ISSUE TITLE
Factory function class-string

### ISSUE THREAD

**Issue by garethellis36** [vimeo/psalm#8856]
I have a function that takes a class-string and returns an instance of `\App\Data\{class-string}`. How do I tell psalm what the specific return type of the factory is?

e.g. `queryBuilder(\User::class)` returns `\App\Data\User`

https://psalm.dev/r/1f1b9d81b2

**Comment by orklah** [comment]
There is no native way to go from a class named `User` in a namespace to another class named `User` in another namespace dynamically.

I'm afraid your use case is too specific. You might be able to do that through a plugin without too much effort though...

**Comment by danog** [comment]
I also noticed a mistake in your phpdoc, you should be using a `@param class-string<...>`, not a `@class-string`.

As mentioned orklah, this specific usecase cannot be implemented directly using phpdocs, but can be easily implemented using [plugins](https://psalm.dev/plugins).
