### ISSUE TITLE
Incorrect inferred return type 'never'

### ISSUE THREAD

**Issue by jack-worman** [vimeo/psalm#8862]
https://psalm.dev/r/4d5cfb806a

`void|never` is being incorrectly reduced to `never` instead of `void`.

**Comment by weirdan** [comment]
Currently it's ef02ded - a couple of commits behind the HEAD of master.

**Comment by weirdan** [comment]
@kkmuffme it requires (undocumented) `restrictReturnTypes="true"` attribute (`Force return types to be as tight as possible` on psalm.dev).
