### ISSUE TITLE
Syntax error on enum

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#8877]
Weird issue that I cannot reproduce on https://psalm.dev/r/b10ef1cbd6 : https://github.com/doctrine/lexer/actions/runs/3664018448/jobs/6194159893#step:6:54

> ParseError: Syntax error, unexpected T_STRING on line 7

Why is Psalm having an issue with enums? I'm using version 5.1.0

**Comment by danog** [comment]
Make sure nikic/php-parser was also updated to the latest version

**Comment by greg0ire** [comment]
```
composer outdated
Info from https://repo.packagist.org: #StandWithUkraine
Color legend:
- patch or minor release available - update recommended
- major release available - update possible

Direct dependencies required in composer.json:
Everything up to date

Transitive dependencies not required in composer.json:
phpstan/phpdoc-parser 1.13.1 1.15.0 PHPDoc parser with support for nullable, intersection and generic types
```
Almost everything seems up to date

**Comment by greg0ire** [comment]
> Target PHP version: 7.1 (inferred from composer.json)

Maybe this is the cause?

**Comment by greg0ire** [comment]
Closing, I think that's expected, I should be using `phpVersion=8.1` (right?)

**Comment by weirdan** [comment]
And to reproduce it on psalm.dev you could add `?php=7.1` to the URL: https://psalm.dev/r/b10ef1cbd6?php=7.1

**Comment by greg0ire** [comment]
Good to know! Thanks!
