### ISSUE TITLE
Hard to get symbol in some issues for plugins

### ISSUE THREAD

**Issue by jack-worman** [vimeo/psalm#8886]
I am trying to write a plugin that will suppress UnusedProperty if it is a doctrine column. But I am struggling to retrieve the symbol (class name and property name) to do the reflection to achieve this.

My code would looks something like this:
```php
<?php

declare(strict_types=1);

namespace App\Psalm\Hook;

use Psalm\Issue\UnusedProperty;
use Psalm\Plugin\EventHandler\BeforeAddIssueInterface;
use Psalm\Plugin\EventHandler\Event\BeforeAddIssueEvent;

class DoctrinePropertySuppressUnusedHook implements BeforeAddIssueInterface
{
    public static function beforeAddIssue(BeforeAddIssueEvent $event): ?bool
    {
        $codeIssue = $event->getIssue();
        if ($codeIssue instanceof UnusedProperty) {
            // $class = ...
            // $property = ...
            // TODO: Use reflection to test for ORM attributes
        }
        return null;
    }
}
```

Is there a better way to do this?
Or should fully qualified symbol names be added to issues?

**Comment by orklah** [comment]
Seems like UnusedProperty doesn't inherit PropertyIssue:
https://github.com/vimeo/psalm/blob/a331ac0b21fa9b8919b6981c439f550ed75156ed/src/Psalm/Issue/UnusedProperty.php#L5

If it was, you'd be able to retrieve the property_id:
https://github.com/vimeo/psalm/blob/97e6511fab6622c1ca434c665dd895e77a0eeca2/src/Psalm/Issue/PropertyIssue.php#L12

You could PR that change if you want

**Comment by jack-worman** [comment]
This was already done by @weirdan in another issue. :)

**Comment by weirdan** [comment]
Yep, in #8883
