### ISSUE TITLE
Variable defined in exception throwing statement of try is always seen as being set?

### ISSUE THREAD

**Issue by jaydiablo** [vimeo/psalm#889]
This code:

```php
<?php

  /**
   * @throws Exception
   */
function test (): string {
    throw new Exception('test');
}

try {
    $var = test();
} catch (Exception $e) {
    
}

if (isset($var)) {
  echo $var;
} else {
    echo 'var is unset';
}
```

Throws this psalm error:

>ERROR: RedundantCondition - 16:5 - Found a redundant condition when evaluating $var and trying to reconcile type 'string' to isset

https://getpsalm.org/r/a5543ba187

But `$var` doesn't get set in this case because the exception halts execution before it can be set to anything:

https://3v4l.org/bTT3E

So psalm shouldn't complain about calling `isset` on a `string` here no?

Obviously this is a simple example, and it's probably harder for psalm to know which variables get set and which don't in a try block, but it seems safer to me that psalm should see any variables defined in a try block as potentially being unset.

I think phpstan has a config setting for this (as of 0.10.x), which defaults to off:

>If you use some variables from a try block in your catch blocks, set polluteCatchScopeWithTryAssignments boolean parameter to true.

That said, phpstan doesn't complain with or without that config parameter defined:

https://phpstan.org/r/8f92b37704c5854859dd4e3dc6795d0a (without)
https://phpstan.org/r/270f48a2a9dc490d0bc67356e0abf430 (with)

Is this intentional (to minimize false positives)?

**Comment by muglug** [comment]
@jaydiablo sorry, never responded here - Psalm shouldn't worry about `isset` checks when the variables are defined in a `try`. I've fixed that behaviour
