### ISSUE TITLE
psalm-assert-if-true has an effect when returning false

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#8896]
[The docs about assert](https://psalm.dev/docs/annotating_code/adding_assertions/) say:

> Similarly, @psalm-assert-if-true and @psalm-assert-if-false will filter input if the function/method returns true and false respectively:

To me this "respectively" means `@psalm-assert-if-true` will be used when the method returns `true`, and not when it returns `false`, yet Psalm seems to deduce things when in the `else` branch of the code below: https://psalm.dev/r/8e07c21ba3

I think this means what I did in https://github.com/doctrine/lexer/pull/95 was wrong.

**Comment by still-dreaming-1** [comment]
As far as I can tell, Psalm is not deducing anything in the else branch. It is telling you the type of $l->lookahead as it was originally defined in the docblock for that property. In the if, the type is further refined, in the else it is not.

**Comment by greg0ire** [comment]
Thanks @still-dreaming-1 ! You made me realise that I posted the wrong link, again! Here is the one I meant to post: https://psalm.dev/r/8e07c21ba3

**Comment by orklah** [comment]
Yeah, Psalm should not try to infer the negation of the assertion in the false case. We noticed that too and it can clearly be wrong. It works well for basic functions like `is_string` where the opposite of being a string is "not being a string", but it's not always the case for user defined functions

ping @ondrejmirtes This is probably something we would need to change in both tools

**Comment by greg0ire** [comment]
Using both is not a workaround: https://psalm.dev/r/58464921be

**Comment by ondrejmirtes** [comment]
I don't want to change this. To me this behaviour is reasonable.

If you use "equality assertion" (documented on psalm.dev), it already does what you want in both Psalm and PHPStan: https://phpstan.org/r/6a843ce9-5514-4d9a-a5e3-5f4001324aff

**Comment by greg0ire** [comment]
Oh right, this definitely looks like it could help!

**Comment by orklah** [comment]
Oh, I may have misunderstood things then! Thanks Ondrej!
