### ISSUE TITLE
Highlight method for MixedMethodCall instead of the whole expression

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#890]
Currently Psalm highlights entire statement where MixedMethodCall occurs:
![image](https://user-images.githubusercontent.com/57403/42716617-0559eebe-8705-11e8-83f6-7b6bd5771e71.png)

Here, the problem was that `addUsage()` lacked `@return` annotation, so Psalm was thinking that it returns `mixed` on which the second `addUsage()` was called.

If it highlighted the method call (second `addUsage()`) it would be much more clear that `addUsage()` return type was not inferred.

PS: Travis job output is even more confusing, there's only `$this` is highlighted:
![image](https://user-images.githubusercontent.com/57403/42716752-d9ec1ddc-8705-11e8-8030-21e5a3919e47.png)

**Comment by muglug** [comment]
Good point, PHP Parser 4 allows you to target the names themselves (thanks @nikic) and so I've used that: https://getpsalm.org/r/8333ee4196

This can't be backported to V1 (nor your PHPUnit bump) for compatibility reasons.

**Comment by weirdan** [comment]
Oh, that's slick!
