### ISSUE TITLE
Param with default value reported as null

### ISSUE THREAD

**Issue by andraaspar** [vimeo/psalm#8904]
Please see:

https://psalm.dev/r/035aeb3824

I get a PossiblyNullOperand. I expected it to **not** show an error, like in this case:

https://psalm.dev/r/4d6f56f17b

**Comment by orklah** [comment]
Why do you expect to have the same behavior when you don't handle the null value than when you do?

This is the intended behavior for this issue (you can handle the null value more effectively with a cast: https://psalm.dev/r/ecc1ba7527)

**Comment by orklah** [comment]
I'll mark this as closed, feel free to respond if I missed something :)

**Comment by andraaspar** [comment]
I am sorry about this. You are right. I totally forgot that passing `null` does not result in the default value being used in PHP. I was under the assumption that you could not pass `null` to a parameter with a default value.
