### ISSUE TITLE
Support include path

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#891]
http://php.net/manual/en/ini.core.php#ini.include-path

**Comment by erunion** [comment]
I don't remember what I did, but yay me!

**Comment by f-skold** [comment]
I downloaded psalm and tried to run it. We have a repo layout where the php-code is located in 'repo/lib' and we have . and repo/lib in the include path.

I could not find anything when trying to read the documentation, or searching it.

It would be a shame to have to mute all warnings about missing fies when doing require_once.

It would be nice to have an example of how it can ve solved here!

Can someone point me in the right direction? @muglug, @erunion?
