### ISSUE TITLE
Psalm 5: InvalidReturnType regression for final classes

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#8925]
https://psalm.dev/r/7a0b9aed9f

Works fine if `Foo` is not final
https://psalm.dev/r/0641fa1047

It was working fine on Psalm 4 too.

**Comment by danog** [comment]
The problem is caused when computing the intersection between the template type `(T:RepositoryInterface as EntityInterface)|null` and `Foo|null`.

A temporary workaround is to remove the strict typehint and rely exclusively on the template.
https://psalm.dev/r/a67ed9715b
