### ISSUE TITLE
Psalm 5: TypeDoesNotContainType is thrown instead of DocblockTypeContradiction

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#8932]
The following example is throwing a TypeDoesNotContainType with Psalm 5 but not with 4
https://psalm.dev/r/9950912ce2

This seems related to the union type since
https://psalm.dev/r/66b46ed7a0
works fine.

**Comment by pilif** [comment]
given the type of the `$value` parameter (array or null), after the null check, I expert $value to always be array and thus the check to be redundant, so I don't feel like this is a bug

**Comment by VincentLanglet** [comment]
> given the type of the `$value` parameter (array or null), after the null check, I expert $value to always be array and thus the check to be redundant, so I don't feel like this is a bug

I agree it's redundant but i expect it to be redundant with the PHPDoc, and not a "native type".
That's why I expect a different type of error.

This should be:
```
    public function reverseTransform(array|null $value): null
    {
        if (null === $value) {
            return null;
        }

        if (!\is_array($value)) { // TypeDoesNotContainType
```
```
/**
     * @param array|null $value
     */
    public function reverseTransform($value): null
    {
        if (null === $value) {
            return null;
        }

        if (!\is_array($value)) { // DocblockTypeContradiction
```

That's why I gave the second example (without the union).
The `is_array` check is redundant, but is reported as a DocblockTypeContradiction ; the behavior I want.

This is something important for open-source library.
When type cannot be added for some reason, we cannot consider the PHPdoc as enough and need to add extra-safety check with specific message. So I generally use `treatPhpdocTypeAsCertain: false` on phpstan and ignore `DocblockTypeContradiction` on psalm.

**Comment by orklah** [comment]
WIP: https://github.com/vimeo/psalm/compare/master...orklah:psalm:from_docblock?expand=1

**Comment by VincentLanglet** [comment]
> WIP: https://github.com/vimeo/psalm/compare/master...orklah:psalm:from_docblock?expand=1

I added a test about this change.
Seems like psalm consider now it's a `RedundantConditionGivenDocblockType`, I would say it's right indeed.
And especially it fix my issue since I ignore both
```
DocblockTypeContradiction
RedundantConditionGivenDocblockType
```
to reproduce the behavior of `treatPhpdocTypeAsCertain: false` on PHPStan.

PR is https://github.com/vimeo/psalm/pull/8999

**Comment by VincentLanglet** [comment]
https://psalm.dev/r/76264cec79 is working as expected, so I don't think it's an issue with the MutableUnion but more when parsing the Type.

With some dump, I get that the type is an Union of
`Tarray (from_docblock=false)` and `TNull (from_docblock=true)`.

But the TArray should be `from_docblock=true`, too.
