### ISSUE TITLE
Incorrect `TypeDoesNotContainType` after `@psalm-assert-if-true`

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#8937]
https://psalm.dev/r/0141da27c1

**Comment by danog** [comment]
This is correct, isIt triggers a return if $var is an array, so after if (isIt($var)) $var cannot possibly be an array.

**Comment by vjik** [comment]
> This is correct, isIt triggers a return if $var is an array, so after if (isIt($var)) $var cannot possibly be an array.

No. If `isIt()` returns false then `$var` type is not change. For example, new snippet: https://psalm.dev/r/4814a51940

**Comment by danog** [comment]
Make sure to provide the correct type in the assertion: https://psalm.dev/r/cbb9914c83

**Comment by vjik** [comment]
Does Psalm consider if functions returns false, then type always === NOT `@psalm-assert-if-true`?

**Comment by danog** [comment]
No, it doesn't, but in this specific case, if the functions returns true a return is triggered in the `a` function, so any code after the isIt call cannot possibly be an array, and this is the correct behavior.

**Comment by danog** [comment]
Your problem is that the assertion type you're specifying is not specific enough: if isA can return false in some conditions where $var is an array, the assertion type must be restricted to account for those conditions (as specified in my example above).

**Comment by vjik** [comment]
> Your problem is that the assertion type you're specifying is not specific enough: if isA can return false in some conditions where $var is an array, the assertion type must be restricted to account for those conditions (as specified in my example above).

Yes, I understand it. But can be cases when I don't can set specific enough type. For example: https://psalm.dev/r/58af292965

**Comment by vjik** [comment]
May be `@psalm-assert-if-true` should be applied if function returns true only, otherwise ignore?

**Comment by danog** [comment]
You can use literals: https://psalm.dev/r/e52d2935e9

**Comment by vjik** [comment]
OK. If found suitable case I returns to this issue. Thank you for explains!
