### ISSUE TITLE
__invoke() return type not checked

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#894]
https://getpsalm.org/r/f94cdf9b18
```php
<?php
  class C {
     public function __invoke(): int {}
  }
```
**Expected**: return type mismatch, must return int, but nothing is returned
**Actual**: 
```
Psalm output (using commit e836f69): 

No issues!
```

**Comment by muglug** [comment]
Thanks, that was a silly oversight

**Comment by muglug** [comment]
I've updated title to encompass the full scope of the bug
