### ISSUE TITLE
Multiple array/list are incorrectly merged as return type

### ISSUE THREAD

**Issue by arjenm** [vimeo/psalm#8940]
Symfony has a fairly complex return type specified on their [EventSubscriberInterface](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/EventDispatcher/EventSubscriberInterface.php).

`@return array<string, string|array{0: string, 1: int}|list<array{0: string, 1?: int}>>`

I copied both their `@return` and the phpdoc (which includes examples), so you can just read the psalm.dev-snippet:

https://psalm.dev/r/49064bc34c

When using the most complex variant (a string-key => list of array<string, ?int>), Psalm fails to recognize that.

```
does not match the declared return type array<string, array{0?: array{0: string, 1?: int}|string, 1?: int, ...<int<0, max>, array{0: string, 1?: int}>}|string>
```

So according to Psalm the array-value should be either of these:
- `string`
- `array{0?: array{0: string, 1?: int}|string, 1?: int, ...<int<0, max>, array{0: string, 1?: int}>}`

That second option seems to be a mix of the array and list options from the phpdoc, but merged such that this bit doesn't match anymore, while it should match the list-option:
```
'b' => [
                ['methodB1', 0],
                ['methodB2', 10],
            ],
```

The snippet also fails with only the above key 'b'.

**Comment by danog** [comment]
Simplified: https://psalm.dev/r/c2aaf91701
