### ISSUE TITLE
InvalidReturnStatement for lists with shape inferred from PHP code with conditions

### ISSUE THREAD

**Issue by lptn** [vimeo/psalm#8942]
Psalm: 5.3.0

`list<string>` should be a superset of `list{0?: string, 1: string}`.

https://psalm.dev/r/c1147fc79d

**Comment by danog** [comment]
`list{0?: string, 1: string}` is actually not a valid list type (so the error would be correct, but the type should've also been marked as `array`), and it shouldn't have been generated in the first place (a `list{'A'|'B', 'C'}` should've been generated instead).

I've already started work to fix this and a number of other issues, it's a bit tricky :)

**Comment by boesing** [comment]
Not sure if it is worth handling this.

Even if `array{0: string, 1: string}` would be interpreted as `list` that would be a flaw, because the array-key order is probably not really handled by psalm.

https://psalm.dev/r/2c3fa92ffa
https://3v4l.org/3FHbY#v8.1.13

**Comment by danog** [comment]
`array{0: string, 1: string}` is, correctly, _not_ interpreted as a list, so it's not an issue.

**Comment by danog** [comment]
Fixed!
