### ISSUE TITLE
 Regression in condition of `0|positive-int`

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#8944]
Hey there,

not quite sure if that has changed in the most recent versions of v5 or already on some version after 4.15.0:

https://psalm.dev/r/74ad76d080

Since `positive-int` was not deprecated in any way (at least not that I know), the code should still be valid, right?
But it does not work with `int<0,max>` either, so I guess something has changed regarding constant handling in conditions or sth. like that.

**Comment by danog** [comment]
The problem is caused by the `$foo->bar === self::ZERO` comparison, changing that to `$foo->bar === 0` fixes the issue.

Simplified: https://psalm.dev/r/743733a05f

**Comment by boesing** [comment]
Seems to be fixed.
https://psalm.dev/r/34ea83be03
