### ISSUE TITLE
Is there a Docker image available ? 

### ISSUE THREAD

**Issue by cavo789** [vimeo/psalm#8950]
Hi all

Is there an official docker image with a not too old,version of psalm.

I've found one but not updated since three years (https://hub.docker.com/r/phpqa/psalm).

Thanks.

**Comment by orklah** [comment]
Hi!

We have this: https://hub.docker.com/r/vimeo/psalm-github-actions

Here's a discussion we had about that: https://github.com/vimeo/psalm/discussions/6602#discussioncomment-2196704

**Comment by cavo789** [comment]
Oh ? I thought it was only for use as actions in github.

I wish to be able to run psalm on my Linux console with docker run.

Do you think I can use that image for this ? (In a second step idea is to use it in a GitLab CI pipeline, not github).

Thanks

**Comment by orklah** [comment]
Oh that may be true. I don't know docker very much TBH!

**Comment by cavo789** [comment]
> Oh that may be true. I don't know docker very much TBH!

No problem, I'll post a feedback here.

(using Docker is amazing, as a user you shouldn't install things neither configure them, just know how to call the application like, f.i., docker run --rm -it YOUR_DOCKER_IMG psalm --version, just crazy easy and always up-to-date)
