### ISSUE TITLE
Unclear MissingTemplateParam / false positive?

### ISSUE THREAD

**Issue by ThomasLandauer** [vimeo/psalm#8970]
I'm getting
> ERROR: MissingTemplateParam - src/Form/FooType.php:14:13 - App\Form\FooType has missing template params when extending Symfony\Component\Form\AbstractType, expecting 1 (see https://psalm.dev/182)
final class FooType extends AbstractType

The linked docs page says:
> Emitted when using the `@extends`/`@implements` annotation to extend a class without extending all its template params.

But neither my class nor the extended Symfony class (nor the interface it implements) has *any* annotation. No `@extends`, no `@implements`, no `@template` - nothing.

So I don't understand what psalm is complaining about here ;-)

I have:
vimeo/psalm 5.4.0
psalm/plugin-symfony v5.0.0 

I tried to reproduce on psalm.dev, but the error didn't show up.

**Comment by danog** [comment]
Actually, the Psalm stub for symfony __does__ define a template type, see https://github.com/psalm/psalm-plugin-symfony/blob/4.x/src/Stubs/common/Component/Form/AbstractType.stubphp, so this is correct.
