### ISSUE TITLE
xdebug_info triggers UndefinedFunction

### ISSUE THREAD

**Issue by gdejong** [vimeo/psalm#8977]
See https://xdebug.org/docs/all_functions#xdebug_info

https://psalm.dev/r/1a65c240f2

Another xdebug method like `xdebug_get_stack_depth` does not trigger an UndefinedFunction: https://psalm.dev/r/4646f18e42

**Comment by orklah** [comment]
We have xdebug_get_stack_depth signature in Callmap file but not xdebug_info: https://github.com/vimeo/psalm/tree/master/dictionaries

Up for adding it? We have an article on how those files work here: https://psalm.dev/docs/contributing/editing_callmaps/
