### ISSUE TITLE
Defining enum case with a class constant causes a crash

### ISSUE THREAD

**Issue by jack-worman** [vimeo/psalm#8978]
https://psalm.dev/r/224fdb8a5d

**Comment by jack-worman** [comment]
It seems to be because in `SimpleTypeInferer::infer()`:
```php
                if ($existing_class_constants === null
                    && $file_source instanceof StatementsAnalyzer
                ) {
                    try {
                        $foreign_class_constant = $codebase->classlikes->getClassConstantType(
                            $const_fq_class_name,
                            $stmt->name->name,
                            ReflectionProperty::IS_PRIVATE,
                            $file_source,
                        );

                        if ($foreign_class_constant) {
                            return $foreign_class_constant;
                        }

                        return null;
                    } catch (InvalidArgumentException | CircularReferenceException $e) {
                        return null;
                    }
                }
            }
```

`$file_source instanceof StatementsAnalyzer` returns false.

**Comment by weirdan** [comment]
> $file_source instanceof StatementsAnalyzer returns false.

That's because we're trying to infer values in the scanning phase. When that fails, we need to store `UnresolvedConstantComponent` instead and resolve it later in the analysis phase (when all classlikes are already loaded) rather than throwing an exception.

**Comment by DmytroPolavis** [comment]
Hey, any update on this? Having a similar issue, and what is more frustrating is that <ignoreFiles> directive does not work for a file with such error :(
