### ISSUE TITLE
Object shapes in assertions do not work anymore

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#8981]
Hey there,

I've recently upgrade psalm to v5 in another project where we use object shapes to determine properties from `json_decode` objects. So we have an assertion method which then should tell psalm that there are properties with specific types.

This does not properly seem to work, at least in my example here:
https://psalm.dev/r/eb1bed0bf9

Is that something which is related to psalm v5 or am I oversee something?

**Comment by danog** [comment]
While this is still technically a bug, I recommend using [valinor](https://valinor.cuyz.io/latest/) DTOs, instead.
