### ISSUE TITLE
Support wildcards in config for <projectFiles>

### ISSUE THREAD

**Issue by ryan7273** [vimeo/psalm#899]
It would be nice if the config file supported wildcards when describing which files to include/ignore. Maybe something along the lines of `<files name="*.class.php" />`.

**Comment by muglug** [comment]
This should work already - does it not?

**Comment by ryan7273** [comment]
Not using any method I've tried, though it is not covered in the documentation so I could just be doing it wrong.

**Comment by muglug** [comment]
Ahh ok, the wildcard only matches names of files in a given folder, not all possible files.

so `<files name="src/*.class.php" />` would match `src/foo.class.php`, `src/foo.bar.class.php`, but not `src/foo/bar.class.php`. I'll fix that

**Comment by ryan7273** [comment]
Got it. I'm getting the "Could not resolve config path to..." error because no files were found, which is caused by wildcards not being recursive. Makes perfect sense. Thank you (-:

**Comment by SignpostMarv** [comment]
@muglug what about `<files name="src/**/*.class.php" />` for deep folder checking to match the globbing syntax of other command line tools ?

**Comment by muglug** [comment]
Yeah actually that already works, so:

To match `*.class.php` in all folders, do
```xml
<!-- matches files ending in .class.php in src -->
<file name="src/*.class.php" /> 
<!-- matches files ending in .class.php in exactly one folder deep -->
<file name="**/*.class.php" /> 
<!-- matches files ending in .class.php in exactly two folders deep -->
<file name="**/**/*.class.php" />
```

**Comment by muglug** [comment]
I added a couple more tests just to confirm that the feature works as presented above: https://github.com/vimeo/psalm/commit/4fcef5c0d6ef07c576da414c43b6ac18f90df6bf
