### ISSUE TITLE
Config option to unseal arrays

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8992]
Given https://github.com/vimeo/psalm/issues/8744 as well as some other issues reported, as well as the incompatilibity with all (!) other tools (phpstorm inspections, phpstan, phpcs,...) I think there should be an option to disable/unseal all arrays via a config flag.

Given there are already 2 flags https://psalm.dev/docs/running_psalm/configuration/#sealallmethods and https://psalm.dev/docs/running_psalm/configuration/#sealallproperties I guess a 3rd sealAllArrays (with default true) wouldn't be too far fetched, would it?

**Comment by danog** [comment]
I don't feel like there's a need for this.
Arrays can already be marked as unsealed by using `array{}&array` syntax, which is already supported by phpstan.

The final objective of this change was move the entire static analysis ecosystem to the new semantics, which I hope will happen soon enough; in the meantime, existing tools already have support for unsealed syntax, so changing phpdocs is simple enough (even though really, even this is unnecessary, for example I have personally found no valid usecases for unsealed arrays in our codebase @ work).

**Comment by danog** [comment]
As I already said, Psalm does not forbid the use of unsealed arrays, and the `&array` unsealed syntax is fully supported by phpstan, phpcs&other tools using phpstan's docblock parsers.

`usort` is not a valid usecase for unsealed arrays, as Psalm is capable of automatically typing closures passed to usort and other functions, based on the type of the array type.

**Comment by orklah** [comment]
> Since `array{}&array` is supported everywhere, why does psalm need to introduce a redundant syntax with `, ...` ?

The former syntax makes no sense. If you have `array{'a': string}&array<int, int>` the resulting type should be `never`. This syntax is not only weird and non-sensical, it could actually be an obstacle for a future correct implementation of intersections between arrays...

We won't be adding a config to control the sealing of arrays. If libraries were to use that and users of those libraries weren't, it would create major misunderstanding that would never be solved. And once Psalm 6 comes and we get to deprecate the config, we will have this issue all over again.

**Comment by orklah** [comment]
yeah, but the `array{'a': string}&array` is short for `array{'a': string}&array<array-key, mixed>`. You can use `array{'a': string}&array<int, string>` and the current meaning is "an array shape with an offset 'a' of type string. Every other offset must be an int and returns a string"

The meaning and the syntax does not match. The plan is for the user to be able to do `array{'a': string, ...<int, string>}` that would have the same meaning but with a more consistent syntax
