### ISSUE TITLE
ImplementedReturnTypeMismatch for IteratorAggregate::getIterator()

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#901]
Consider we have this class we want to extend, [Symfony's Finder being a fine example:](https://github.com/symfony/finder/blob/master/Finder.php#L579)

```php
// A class from vendor/
class Foo implements \IteratorAggregate {
    
    /**
     * We cannot change this method's signature
     * @return ArrayIterator|Foo[]
     * (this is very convenient declaration IDE-wise, gives autocomplete on iteration)
     */
    public function getIterator()
    {
        return new ArrayIterator();
    }
}
```

```php
// Our class from src/
class Bar extends Foo // or extends \Symfony\Component\Finder\Finder
{
    public function getIterator()
    {
        $iterator = parent::getIterator();      
      
      	if (true) {
            $iterator = new NoRewindIterator($iterator);
        }
      
      	return $iterator;
    }
}
```

[Psalm gives the following error:](https://getpsalm.org/r/3db87a60d5)

> ERROR: PossiblyInvalidArgument - 28:45 - Argument 1 of __construct expects iterator, possibly different type array<mixed, string>|ArrayIterator provided

It is bogus because `IteratorAggregate::getIterator()` can't possibly return anything but an iterator. [This is guaranteed PHP-side.](https://3v4l.org/4tGJm)

> Fatal error: Uncaught Exception: Objects returned by Foo::getIterator() must be traversable or implement interface Iterator in /in/4tGJm:13

(Although the error message say one can return a traversable, but [it fails on an array](https://3v4l.org/4tGJm).)

**Comment by muglug** [comment]
You should be able to create a stub file with the code:

```php
class Foo implements \IteratorAggregate {
    /**
     * @return ArrayIterator<Foo>
     */
    public function getIterator() {}
}
```

and it'll override whatever's in `vendor`.

Psalm also has a config flag `allowPhpStormGenerics="true"`, but that only works for property docblocks and functions that have a hard `: SomeIterator` return type hint (as well as a `@return Iterator|Foo[]`)

**Comment by muglug** [comment]
Closing - let me know if this didn't solve the problem
