### ISSUE TITLE
Return type of array combine doesn't consider key casts

### ISSUE THREAD

**Issue by aszenz** [vimeo/psalm#9010]
When using `array_combine` with an array of decimal string keys, php casts them to int as noted [here](https://www.php.net/manual/en/language.types.array.php), psalm infers the type of array as `array<string, string>`, instead it should have been `array<int|string, string>`

See: https://psalm.dev/r/039eb314bd

**Comment by orklah** [comment]
ping @danog , it might be related to recent changes

**Comment by danog** [comment]
This actually works fine if the @var is removed, because the keys of a shaped array are stored as actual keys of a real runtime array, which yields the desired behavior: https://psalm.dev/r/9e1db27976

However, I really don't think there is a way to make this work for generic array<string> arrays without uselessly introducing a bunch of false positives.
Maybe with a non-numeric-string type though...

**Comment by aszenz** [comment]
> However, I really don't think there is a way to make this work for generic array<string> arrays without uselessly introducing a bunch of false positives.

I only created this issue because it caused a runtime exception for us, while I agree this will create false positives for many scenario's it can still be added a stricter config option.

**Comment by orklah** [comment]
Oh, I didn't get the issue. Unfortunately, this is a major PHP issue that we can't get around to fix without massively degrade type inference. It doesn't just apply to array_combine but to every key operation in PHP:
https://psalm.dev/r/356fa3860f
Each of these operations has the potential to return an int instead

PHPStan also follows this logic: https://phpstan.org/r/af50221d-8da1-4642-b385-504cd7ee72d1

It's always a hard choice but we have to stay consistent (we won't just change array_combine and not the others) and we can't just say that string offset can't exists on their own...

I really wish PHP would offer a better solution here

**Comment by aszenz** [comment]
We should at least document this decision in docs about arrays, I'll be happy to contribute it.

**Comment by orklah** [comment]
Please do, documentation is always good!
