### ISSUE TITLE
Unexpected NoValue issue for a generic trait method

### ISSUE THREAD

**Issue by nevmerzhitsky** [vimeo/psalm#9015]
Hello!

I faced a strange problem with a generic trait. I got a NoValue issue while the execution of the script produce the proper stdout:

https://psalm.dev/r/1c5cbb8f94

Psalm treats this version of the script without the issue:

https://psalm.dev/r/e95420474f

The only difference between the scripts is `\stdClass` instead of `static` return types, and so don't use of the `@return SM` annotation in `HasSyncModel::findSyncModel()`.

Is this my bad or a problem with the parsing of generic traits by the tool?

**Comment by orklah** [comment]
I think this must be a flaw in templates resolution with traits in Psalm

**Comment by klimick** [comment]
Issue `NoValue` is not appear anymore. Issue can be closed?

**Comment by nevmerzhitsky** [comment]
Thanks guys
