### ISSUE TITLE
Deprecation message breaks JSON output

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#9034]
https://github.com/psalm/codeception-psalm-module/actions/runs/3810538569/jobs/6482681536#step:10:283

```
Failed to parse output: Warning: "findUnusedCode" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
```

This has the potential to break tests for most of the plugins. The Codeception module used for testing redirects STDERR to STDOUT, so the JSON it then tries to read won't be valid.

/cc: @jack-worman

**Comment by weirdan** [comment]
@orklah please hold off doing the new release for now, until this is resolved one way or another.

**Comment by jack-worman** [comment]
I am looking into it.

**Comment by danog** [comment]
@jack-worman the PR you submitted is not the right solution

@weirdan Currently the warning is output to STDERR, which is where we also output other non-json output like the progress bar, this seems like a bug in that pipeline, instead

**Comment by weirdan** [comment]
> Currently the warning is output to STDERR, which is where we also output other non-json output like the progress bar,

Correct. But that is either out of the happy path or suppressed with `--no-progress`.

> it really shouldn't parse JSON from STDERR too

Well, it's either that or STDERR is completely lost (Codeception CLI module uses `exec()`). And the latter makes debugging a nightmare. So Codeception Psalm module redirects STDERR to STDOUT.

**Comment by jack-worman** [comment]
What is the status of this? I would like to have a new release, what can I do to help?
Perhaps, we can add a `--no-deprecation-messages` flag?

**Comment by danog** [comment]
What's needed here is a change to the codeception psalm plugin to avoid parsing output from stderr, or otherwise ignore deprecation warnings outputted to stdout.

**Comment by lptn** [comment]
>@orklah please hold off doing the new release for now, until this is resolved one way or another.

How about hiding this `findUnusedCode` deprecation message for the upcoming release? Psalm doesn't have releases for almost a month. Once we found a solution for the issue, we can start displaying this message

PS: On my setup this `Failed to parse output: Warning: "findUnusedCode" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.` message displayed twice (latest master branch)

**Comment by jack-worman** [comment]
I created https://github.com/psalm/codeception-psalm-module/pull/45 to hopefully solve the issue

**Comment by weirdan** [comment]
@orklah releases are no longer blocked.
