### ISSUE TITLE
Broken assert for array and list - DocblockTypeContradiction

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9037]
https://psalm.dev/r/ea9ecf75b9

As we see in line 20, psalm correctly infers that $foo can be type list<string> when checking with array_values

When using a custom assert function, it correctly asserts it, but reports a false positive `DocblockTypeContradiction` on the if condition in line 23

What actually happens here is, that it assumes that @psalm-assert type `array<string, string>` does not contain `list<string>` which is correct - however why does it report this as a DocblockTypeContradiction in the place where the function is called?

**How can I assert `if true => list<string>`, `if false => array<string, string>`?**

**Comment by orklah** [comment]
Current situation seems correct `@psalm-assert` means that if the function doesn't throw, you have the type `array<string, string>` but you also say that if the function returns true, you have a `list<string>`. Those two are contradiction and assertions are considered docblocks so there's a fail.

In theory, this should work: https://psalm.dev/r/06c99cf8ac but it doesn't

**Comment by orklah** [comment]
As far as I know, contradiction in assertions were always reported where the contradiction is processed, on the method call.
