### ISSUE TITLE
DateTimeImutable::modify() should return `static`

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#9042]
DateTime type issues strike back...

https://psalm.dev/r/09e238bf00

I expect `$foo2` to be of type `Subclass` and indeed, according to PHP it is:

https://3v4l.org/j9ZSo

I agree that the PHP manual [disagrees](https://www.php.net/manual/en/datetimeimmutable.modify.php), so that should probably be raised on the php internals list too, but seeing how big a BC break it would be for PHP to change this behavior, I assume that this is a doc bug, not a language issue.

**Comment by pilif** [comment]
if you agree that Psalm should probably represent what PHP currently does, I'll try to submit a PR to fix the return type, though I'm a bit reluctant to start working on this right now as there were so many DateTime related issues and PRs raised in the past which kind of scares me to work on those parts at this point 😛

**Comment by weirdan** [comment]
Actual behaviour is the ground truth, so PR is welcome.

**Comment by DaDeather** [comment]
Didn't this break up a few things?

If you now call the given snippet it causes a `ERROR: [UndefinedClass](https://psalm.dev/019) - 10:6 - Class or interface <empty string> does not exist` which is given on any method call after a modify being made.
