### ISSUE TITLE
Redis deprecated - enableExtensions doesn't work

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9050]
>Deprecation: Psalm stubs for ext-redis loaded using legacy way. Instead, please declare ext-redis as dependency in composer.json or use <enableExtensions> directive in Psalm config.

But when I add it, I get:
>Problem parsing psalm-dev-debug.xml:
  Error on line 15:
    Element '{https://getpsalm.org/schema/config}extension', attribute 'name': [facet 'enumeration'] The value 'redis' is not an element of the set {'decimal', 'dom', 'ds', 'geos', 'gmp', 'mongodb', 'mysqli', 'pdo', 'simplexml', 'soap', 'xdebug'}.
    
Psalm 5.4.0@62db5d4f6a7ae0a20f7cc5a4952d730272fc0863

**Comment by orklah** [comment]
Fixed here: https://github.com/vimeo/psalm/commit/903c00c6eb8ba7488ffb36878dffcddb0b3fad2b

Can't release yet until https://github.com/vimeo/psalm/issues/9034 is sorted out
