### ISSUE TITLE
STDERR is not marked as a resource, it's mixed

### ISSUE THREAD

**Issue by dkarlovi** [vimeo/psalm#906]
https://getpsalm.org/r/569aa18b21

http://php.net/manual/en/features.commandline.io-streams.php

**Comment by weirdan** [comment]
https://getpsalm.org/r/16794f2586  — it's `resource`

**Comment by dkarlovi** [comment]
Not here: https://travis-ci.com/dkarlovi/xezilaires/jobs/135739461#L611

**Comment by dkarlovi** [comment]
The latest release.

So it's fixed already, great! It would be great if you added some explanations how to set config on getpsalm.org directly next to the editor, that way I wouldn't even open this issue since I'd assume it was fixed.

 Closing, thanks very much.
