### ISSUE TITLE
Getting `InvalidDocblock` when using an `int-range` scalar type on class with namespace

### ISSUE THREAD

**Issue by ezequiel-compucorp** [vimeo/psalm#9069]
I'm trying to validate that the index of an array is a non-negative integer, which works fine in the example below:
https://psalm.dev/r/9113171040

However, I'm getting an `InvalidDocblock` error when using `non-negative-int` on a class with a namespace:
https://psalm.dev/r/21478194fc

```php
namespace App;

class Entity {
    /**
    * @psalm-var array<non-negative-int, string>
    */
    private $actions = [];
    
    public function __construct() {
        $this->actions[-1]= 'test'; // I would expect an `InvalidPropertyAssignmentValue` error here, but I get an `InvalidDocblock` instead
    }
}
```

Note: it works if add a backslash before: `\non-negative-int`
https://psalm.dev/r/33769b88c8

I'm assuming this is a bug, right?! Or is it the expected behavior?

**Comment by orklah** [comment]
This is a legit bug, those types should have been included in here: https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Type/TypeTokenizer.php#L30
