### ISSUE TITLE
UndefinedMethod on aliased trait method

### ISSUE THREAD

**Issue by mxr576** [vimeo/psalm#907]
Hi,

I had to suppress the UndefinedMethod warning here, because Psalm reported traitGetEntities as not defined.

https://github.com/mxr576/apigee-client-php/blob/ebd3d1366a70ef2ac009ef9a3ca44bc3cd259300/src/Api/Management/Controller/DeveloperController.php#L85

**Comment by muglug** [comment]
I think this is buggy behaviour: https://getpsalm.org/r/6d0f3ed3eb but, on the other hand, that code doesn't work here: https://3v4l.org/A4Uor

Does PHP run your code?

**Comment by mxr576** [comment]
@muglug your example code is incorrect, of course your code is not compiling still in PHP, but in my case my code is working it - confirmed by tests - because the parameter list of the method is the same as in the trait and I am not trying to inherit the same method from multiple traits.

https://3v4l.org/O9HOL

**Comment by muglug** [comment]
@mxr576 sorry, that was very dumb of me. I'll investigate further with a local clone

**Comment by mxr576** [comment]
@muglug any news about this issue? Could you reproduce it? Do you need any input from me?

**Comment by muglug** [comment]
You're using a pretty old version (0.3.89) released over six months ago.

The issue goes away when you update Psalm to 1.x.
