### ISSUE TITLE
Getting `InvalidDocblock` when using the `non-negative-int` scalar type on a class with namespace

### ISSUE THREAD

**Issue by eopnetto** [vimeo/psalm#9070]
I'm trying to validate that the index of an array is a non-negative integer, which works fine in the example below:
https://psalm.dev/r/9113171040

However, I'm getting an `InvalidDocblock` error when using `non-negative-int` on a class with a namespace:
https://psalm.dev/r/21478194fc

```php
namespace App;

class Entity {
    /**
    * @psalm-var array<non-negative-int, string>
    */
    private $actions = [];
    
    public function __construct() {
        $this->actions[-1]= 'test'; // I would expect an `InvalidPropertyAssignmentValue` error here, but I get an `InvalidDocblock` instead
    }
}
```

Note: it works if add a backslash before: `\non-negative-int`
https://psalm.dev/r/33769b88c8

I'm assuming this is a bug, right?! Or is it the expected behavior?

**Comment by orklah** [comment]
I answered here:
https://github.com/vimeo/psalm/issues/9069#issuecomment-1374305274

There's a few keywords missing, are you up for a PR? :)
