### ISSUE TITLE
restrictReturnTypes and literal strings

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9071]
https://psalm.dev/r/251e6fb4a4

I think it's better to just set it to non-empty-string in case of literal string return instead of having people put the literal string in the return type when it's even hyphenated with ... in the error message already.

**Comment by orklah** [comment]
Psalm tries to infer the most precise type for the variable and use it to check everything it has to.

Either you don't enable the restrictReturnTypes config and you keep the type you have or you enable it and Psalm will give you the type it has. There's no "in between acceptable return type" notion and I won't be the one to introduce it.
