### ISSUE TITLE
ReflectionClass::newInstanceArgs() accepts associative arrays

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#9077]
Since PHP 8, `ReflectionClass::newInstanceArgs()` accepts an associative array of parameter names.

This code works (https://3v4l.org/L0kj4):

```php
class X {
    public function __construct(
        string $a,
        string $b,
    ) {
        echo "\$a = $a\n";
        echo "\$b = $b\n";
    }
}

$r = new ReflectionClass(X::class);
$r->newInstanceArgs([
    'b' => 1,
    'a' => 2,
]);
```

But Psalm fails with:

> ERROR: [InvalidArgument](https://psalm.dev/004) - 14:21 - Argument 1 of ReflectionClass::newInstanceArgs expects array<int, mixed>, but array{a: 2, b: 1} provided

https://psalm.dev/r/835445aea1

**Comment by BenMorel** [comment]
I tried to fix it, but I fail to understand the hierarchy of CallMaps that leads Psalm to fail on this example on PHP 8:

- `CallMap.php` has a type that should work:
    ```php
    'ReflectionClass::newInstanceArgs' => ['object', 'args='=>'array<array-key, mixed>'],
    'ReflectionObject::newInstanceArgs' => ['object', 'args='=>'array'],
    ```
- `CallMap_historical.php` has the old (i.e. pre- PHP 8) type:
    ```php
    'ReflectionClass::newInstanceArgs' => ['object', 'args='=>'list<mixed>'],
    'ReflectionObject::newInstanceArgs' => ['object', 'args='=>'array'],
    ```
- `CallMap_80_delta.php` has both the old and the new types correct:
    ```php
    'ReflectionClass::newInstanceArgs' => [
      'old' => ['object', 'args='=>'list<mixed>'],
      'new' => ['object', 'args='=>'array<array-key, mixed>'],
    ],
    ```

---

Even though `newInstanceArgs()` accepts arrays with out-of-order `int` keys, I think a sane validation would be:

- PHP 7: `list<mixed>`
- PHP 8: `list<mixed>|array<string, mixed>`

**Comment by orklah** [comment]
@BenMorel new stubs were introduced for Reflection classes: https://github.com/vimeo/psalm/blob/master/stubs/Reflection.phpstub

They take precedence over the callmaps, your fix should belong here
