### ISSUE TITLE
Be able to check array keys of a non-sealed array and make it sealed

### ISSUE THREAD

**Issue by ciaranmcnulty** [vimeo/psalm#9086]
https://psalm.dev/r/9d63736bbf

this is my specific use case but there may be something more general in there?

**Comment by danog** [comment]
Given that psalm does not enforce the order of values in a string-keyed array, it makes sense that the assertion does not work.
Try count instead: https://psalm.dev/r/9875ae316f

**Comment by ciaranmcnulty** [comment]
Psalm doesn't enforce the order but in this case my code DOES enforce the order

Therefore after the assertion psalm should know the keys of the array exactly

**Comment by ciaranmcnulty** [comment]
ordered-array might be a nice thing but it's out of scope IMO, I just meant this could be inferred to be true:

```
/**
 * @return list<array{bar: mixed, foo: mixed}> 
 */
function (array $a, array $b) {
    assert(array_keys($a) == ['foo', 'bar'];
    assert(array_keys($b) == ['bar', 'foo'];
    
    return [$a, $b];
}
