### ISSUE TITLE
InvalidArgumentException with symfony uid component

### ISSUE THREAD

**Issue by bitgandtter** [vimeo/psalm#9091]
Uncaught Exception: InvalidArgumentException Could not get class storage for symfony\component\uid\uuid. Not sure why or what its causing it

**Comment by orklah** [comment]
Can you try running it with --debug? Also, which version of Psalm and Uuid are you using?

**Comment by bitgandtter** [comment]
for some reason running it with --debug fix the issue. not sure if some cache, some weird but now it works

**Comment by orklah** [comment]
can you replace --cache by --threads=1?

**Comment by xterr** [comment]
I can confirm that passing `--threads=1` solves the problem
