### ISSUE TITLE
@psalm-assert-if-true does not work as per the docs

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#9093]
This example from the [docs](https://psalm.dev/docs/annotating_code/adding_assertions/#asserting-return-values-of-methods):

```php
<?php
class Result {
    /**
     * @var ?Exception
     */
    private $exception;

    /**
     * @psalm-assert-if-true Exception $this->exception
     * @psalm-assert-if-true Exception $this->getException()
     */
    public function hasException(): bool {
        return $this->exception !== null;
    }

    public function getException(): ?Exception {
        return $this->exception;
    }

    public function foo(): void {
        if( $this->hasException() ) {
            // Psalm now knows that $this->exception is an instance of Exception
            echo $this->exception->getMessage();
        }
    }
}

$result = new Result;

if( $result->hasException() ) {
    // Psalm now knows that $result->getException() will return an instance of Exception
    echo $result->getException()->getMessage();
}
```

Fails on the latest Psalm version:

> ERROR: [PossiblyNullReference](https://psalm.dev/083) - 32:35 - Cannot call method getMessage on possibly null value

https://psalm.dev/r/66ce8ba63c

**Comment by orklah** [comment]
It does if you also read the line below the example :D
https://psalm.dev/r/3cbab84b31

If you see a way to improve the docs here, it'd be welcome, you're not the first (or the second) to make the error :p

**Comment by BenMorel** [comment]
Oops, really sorry about this :flushed: The docs are more than OK, I just didn't read far enough.
