### ISSUE TITLE
[Bug] Psalm pretends uninitialized variables don't exist, always emits RedundantPropertyInitializationCheck

### ISSUE THREAD

**Issue by dkarlovi** [vimeo/psalm#9100]
https://psalm.dev/r/0d099ba533

Even in ctor it says it's redundant (which is technically true there, but because it's always true, not always false):

https://psalm.dev/r/33761671b1

**Comment by orklah** [comment]
Docs on this issue summarize what Psalm does pretty well I think: https://psalm.dev/docs/running_psalm/issues/RedundantPropertyInitializationCheck/

For a longer version, see this issue: https://github.com/vimeo/psalm/issues/7608

**Comment by dkarlovi** [comment]
@orklah we discussed this is Symfony Slack, I'm guessing you're referring to [this explanation](https://github.com/vimeo/psalm/issues/7608#issuecomment-1033056442). I'll answer here to avoid polluting the IMO unrelated readonly issue.

> Psalm can't see in advance the order in which you'll call your methods and won't ever be able to guarantee that your property is initialized if it's in a random method. 

That doesn't matter here, no? Assuming Psalm marks properties for which it would emit `PropertyNotSetInConstructor` as "not initialized",*any interaction* with it would be considered as unsafe if it doesn't have an init check.

Basically:

```php
class C
{
    private array $a;
    
    public function f1(): void
    {
        // not redundant
        if (!isset($this->a)) {
            $this->a = [rand()];
        }
        // safe
        $this->a[] = rand();
    }
    
    public function f2(): void
    {
        // unsafe
        $this->a[] = rand();
    }

    public function f3(): void
    {
        $this->a = [rand()];
        
        // redundant
        if (!isset($this->a)) {
            $this->a = [rand()];
        }
    }
}
```

The general goal would be to actually make `RedundantPropertyInitializationCheck` valuable by not emitting it for everything.

> there are code, like yours, that relies on having uninitialized properties at one point after the constructor.

**Any** code with lazy (on demand) properties will emit this, the pattern where you do something like

```php
function getFoo(): Foo
{
    if (!$this->foo) {
        $this->foo = heavyFooFactoryWhichYouDontAlwaysWantToRunSinceFooIsNotAlwaysNeeded();
    }
    return $this->foo;
}
```

That's not exactly an uncommon pattern.

> they go against the core assumption Psalm makes

Right, we're discussing that very assumption.

**Comment by orklah** [comment]
In your first snippet, you mark 

```
public function f2(): void
    {
        // unsafe
        $this->a[] = rand();
    }
```

It's a pretty big issue though, because f2 will be frequently used and is perfectly fine for most code that have always initialized properties. Worse, this is for the redundant isset, but if you assume any property can be uninitialized, you basically have to check every usage of the property

This goes back to my explanation on the other issue. There are 3 possibilities:
- Psalm doesn't make any assumption nor it can make any check
- Psalm makes the assumption that properties are initialized and will mark any redundant check and missing initialization
- Psalm makes the assumption that any properties can be uninitialized and will mark as unsafe any unguarded property usage

Any of these 3 will bother some people, it's a tradeoff we must make (or at least for now, I'm not willing to introduce some kind of config to control which class has which behavior). I think the current tradeoff seems the most common, don't you think?

**Comment by dkarlovi** [comment]
@orklah 

> because f2 will be frequently used and is perfectly fine for most code that have always initialized properties

In that case Psalm will know it's initialized and will not mark this as unsafe, though?

The idea here is just to make `RedundantPropertyInitializationCheck` a bit more useful: if Psalm's not sure the property is initialized, it doesn't emit it.

> if you assume any property can be uninitialized, you basically have to check every usage of the property

You don't assume *any* property is unitialized, you know which are not since you emit `PropertyNotSetInConstructor`, no? Those for which that is emitted are marked as "maybe unint" and you don't emit `RedundantPropertyInitializationCheck` for them.

My suggestion here is not some huge sweeping changes (IMO):
1. mark properties for which you've emitted `PropertyNotSetInConstructor` (even if suppressed) as "maybe uninit"
2. if a property is "maybe uninit", don't emit `RedundantPropertyInitializationCheck` wherever you now would

This shouldn't change any of the other checks nor require fundamental changes how Psalm sees uninit props, IIUC.

**Comment by orklah** [comment]
That would require storing two state for properties (we currently store none), definitely initialized and possibly unitialized. When a possibly unitialized property is checked we would not emit a RedundantPropertyInitialization, when it is used, the logic would be to emit a new PossiblyUninitializedPropertyUsage or something like that.

That would probably make some noise for some projects and I'm not sure it would be super helpful for a lot of people, but I'd be willing to merge a PR like that under a new config

**Comment by dkarlovi** [comment]
> That would require storing two state for properties (we currently store none), definitely initialized and possibly unitialized. 

You can store just one state, possibly unitialized. This can then be checked before emitting `RedundantPropertyInitializationCheck`, all other checks can keep assuming properties are initialized.
