### ISSUE TITLE
Unexpected behaviour with __call() and intersected types

### ISSUE THREAD

**Issue by ndench** [vimeo/psalm#912]
I'm writing a unit test that uses mock objects, so I have variables with intersected types:

```php
/** @var Magic|MockObject */
private $foo;
```

However, the `Magic` class defines `__call()`, so whenever I call a method on `$foo` that is defined in `MockObject` (ie. `expects()`), psalm thinks I'm calling the magic `__call()` method and complains that I'm passing the wrong parameters.

Note that this problem goes away if I reorder the intersected variable:

```php
/** @var MockObject|Magic */
private $foo;
```

So I assume that means psalm tries to match a method on the first declared type, and will only check the second if there is no match, but in this case, `__call()` matches everything.
My expectation would be that psalm would check all declared types before falling back to a magic method, the same way that PHP does.

You can see a [getpsalm.org example here](https://getpsalm.org/r/d2c8352566).

**Comment by weirdan** [comment]
> so I have variables with intersected types:
> `/** @var Magic|MockObject */`

That's union type. Intersection type would be spelled as `Magic&MockObject` (note the ampersand where you used pipe). That aside, your example does actually demonstrate some unexpected behavior, as order of union type member shouldn't really matter.

**Comment by muglug** [comment]
Thanks, @weirdan is right that you want an intersection type there, but definitely a bug either way

**Comment by muglug** [comment]
This was fixed last week in https://github.com/vimeo/psalm/commit/37be70a46560f2c920ce2a6f05a4ba34a3486e8b, didn't realise it was the exact same issue (sorry)
