### ISSUE TITLE
Improve contrast documentation for readability

### ISSUE THREAD

**Issue by imme-emosol** [vimeo/psalm#9128]
My browser is set to use different background-color & color.

Psalm's documentation seems to set a foreground-/text-color but not a background-color.

An example of what my browser shows:
![image](https://user-images.githubusercontent.com/487989/212964704-69cd38a7-3710-4537-90e1-cf00826b51b9.png)

**Comment by imme-emosol** [comment]
Screenshot is after scrolling up from https://psalm.dev/docs/running_psalm/configuration/#projectfiles .

**Comment by weirdan** [comment]
`psalm.dev` sources are available at https://github.com/psalm/psalm.dev

I believe it can be fixed in https://github.com/psalm/psalm.dev/blob/master/assets/sass/mkdocs_material_extra.scss, feel free to submit a PR to that repo.

**Comment by imme-emosol** [comment]
Okay, thanks.

**Comment by imme-emosol** [comment]
It is actually in https://github.com/squidfunk/mkdocs-material/blob/fbfb66258802d0bd64020d951e401976fcc55179/src/assets/stylesheets/main/_typeset.scss#L47 .
