### ISSUE TITLE
No option to specify 'pure' or 'immutable' for callback arguments

### ISSUE THREAD

**Issue by bitwise-operators** [vimeo/psalm#9132]
Take the following example:
https://psalm.dev/r/355b85ceb8

Psalm throws an `ImpureFunctionCall` on the `array_reduce` call because `$callback` is not specified as immutable or pure.

However, the current callable syntax doesn't have any way to do so, meaning this function will require a `@psalm-suppress ImpureFunctionCall`.

Even specifying the callback using an existing pure function will give the error (see [this example](https://psalm.dev/r/84e95e30f8) ), as the pure-ness is not enforced in the class method.

I don't really have a good suggestion on how to fix this. The [original discussion](https://github.com/phpDocumentor/phpDocumentor/issues/1712) on how to type-hint callables in docblocks had several alternative styles that would allow for more information on the callable, but implementing a completely different syntax just for this seems over the top.

Maybe the simplest solution would be to add a new pseudo type `pure-callable`. Developers would probably need to use `@psalm-param` when using it, but since I suspect this isn't exactly a common issue, I think that's acceptable.

**Comment by danog** [comment]
`pure-callable` and `pure-Closure` are already implemented: https://psalm.dev/r/dea1c375b5

**Comment by bitwise-operators** [comment]
That's awesome, thanks!

I've created a [PR](https://github.com/vimeo/psalm/pull/9141) to add it to de docs.
