### ISSUE TITLE
Docs: Tiny issue to be fixed

### ISSUE THREAD

**Issue by TheKhanj** [vimeo/psalm#9137]
In [file](https://github.com/vimeo/psalm/blob/396e7fcc827f2132ca27917526edb22792c5821f/docs/annotating_code/supported_annotations.md) on line 573, there seems to be an issue in the docs... IDK, I might be wrong though.

**Comment by weirdan** [comment]
What issue?

**Comment by TheKhanj** [comment]
In the php example code, shouldn't be any `@no-named-arguments`? And why the function is indented? I couldn't understand what it's trying to say! I thought it was a mistake in docs :thinking:  or maybe I'm wrong, and if that's the case, pardon me :pray:

**Comment by orklah** [comment]
@TheKhanj The way it's phrased it seems to imply "behavior will change if you put the annotation on a code that currently looks like that" so I'm no shocked the annotation is not already there, but if it confused you, we can as well change it for something clearer :)

Feel free to submit a PR :) I'll close here in the meantime

**Comment by TheKhanj** [comment]
@orklah Thanks for your consideration :). I will probably contribute to the project, but the most interesting part for me to contribute is it's language server. The project is awesome :+1: It is making my life so much easier as a Php developer. If only the language server was more mature it would have been great! I could have dropped using Intelephense which is "Freemium" cause I do believe in free and open-source software :). You are doing a great job keep doing it ❤️👍

**Comment by orklah** [comment]
Thanks! If you want to work on LSP, don't hesitate to tag @tm1000, he knows it pretty well and could probably help with advices :)

**Comment by TheKhanj** [comment]
I'm not that professional, but I'll try my best to contribute as much as I can and will be in touch with @tm1000  :)
