### ISSUE TITLE
Psalm doesnt respect @method __toString() and complains instance cannot be cast to string

### ISSUE THREAD

**Issue by michnovka** [vimeo/psalm#9143]
I came across this issue whilst implementing symfony validation in accordance to their docs ( https://symfony.com/doc/current/validation.html#using-the-validator-service )

The interface has `__toString()` mentioned via `@method` phpdoc, but psalm acts as if it did not exist.

https://psalm.dev/r/f830e4b03e

**Comment by staabm** [comment]
I think the problem is the wrong @var 

See https://psalm.dev/r/030d9d55a4

**Comment by michnovka** [comment]
The `@var` was a shortcut. This is whats creating the issue - sometimes an interface is the return value of a function.

https://psalm.dev/r/ebdd13b543

**Comment by staabm** [comment]
Thanks for clarifying

**Comment by orklah** [comment]
FYI, extending Stringable or using a concrete method is handled:
https://psalm.dev/r/68708c011e
https://psalm.dev/r/c92851ac7d

The issue should be fixed in this condition:
https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php#L600

Up for a PR?

**Comment by michnovka** [comment]
@orklah I dont get it, the code checks for whether method __toString exists:

https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php#L613

What function is used to check if the method exists only as a `@method` declaration in PHPDoc?

**Comment by orklah** [comment]
You're right, I missed that. As far as I know methodExists should work already. I removed the help wanted tag because it's not as easy as I thought but feel free to give it a go if you find something wrong

**Comment by michnovka** [comment]
Hi, any update on this?

**Comment by michnovka** [comment]
I belie this is fixed, thanks!
