### ISSUE TITLE
strtr - Too few arguments for method strtr - expecting 3 but saw 2

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#915]
> Too few arguments for method strtr - expecting 3 but saw 2

This issue was fixed before:
https://github.com/vimeo/psalm/issues/831

Unfortunately, I cannot reproduce the problem online...
https://getpsalm.org/r/3fcf383db0

I'm on Psalm 2.0.9.

Any clue what might be going on here?

**Comment by muglug** [comment]
What are the types of the args you're passing? Does explicitly casting them help?

**Comment by iluuu1994** [comment]
For whatever reason, suddenly the error message is different:

> Argument 2 of strtr expects string, array{%from_date%:mixed, %to_date%:mixed} provided

I have not opened the project since 10 days ago. I can see in `git` that the code has not changed. No `composer update`. Someone please explain that 😆

Explicitly casting the values in the array results in a very similar error message:

> Argument 2 of strtr expects string, array{%from_date%:string, %to_date%:string} provided

**Comment by muglug** [comment]
And what if you cast the first arg?

**Comment by iluuu1994** [comment]
That actually fixes the issue! I cannot for the life of me reproduce this issue on getpsalm.org:
https://getpsalm.org/r/a07c5ba9a1

Maybe it has to do something with my config. There's currently no way to add a config to the online version of psalm? That could make it easier to reproduce issues.

**Comment by muglug** [comment]
Thanks!

**Comment by iluuu1994** [comment]
Cool, thanks man!
