### ISSUE TITLE
Class or interface tidy does not exist

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#916]
Psalm 2.0.9

I get these all over the place. Not reproducible online...
I can also see the corresponding entries in **CallMap.php** and **PropertyMap.php**.

```php
$tidyHtml = tidy_parse_string('Dirty string');
$tidyHtml->cleanRepair();
```

With other words, Psalm can see that `tidy_parse_string` returns a `\tidy` object but cannot find the type itself.

Any idea what causes this?

**Comment by muglug** [comment]
Hmmm is `pear/tidy` installed on your PHP instance? I can't install straightforwardly from `pecl`

**Comment by iluuu1994** [comment]
No, I thought I didn't need it because of the function map. Is that assumption false?

**Comment by muglug** [comment]
Yeah, you still should need it (though you can [stub out the class](https://github.com/JetBrains/phpstorm-stubs/blob/master/tidy/tidy.php) if necessary). The reason you can't reproduce on getpsalm.org is because `tidy` is installed there.

**Comment by iluuu1994** [comment]
Oh, I see. My bad then.
