### ISSUE TITLE
Feature: suggest if a function can have "pure" annotation added

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9195]
Would be great if psalm could give an error/suggestion if a function is pure, so we can add pure annotation easily

**Comment by orklah** [comment]
psalter has a MissingPureAnnotation issue that will add the annotation where it can be added

**Comment by orklah** [comment]
We have a few tests that pass on that kind of code so it seems weird: https://github.com/vimeo/psalm/blob/1986c8b4a8018b1819bc4b83b0f7e69c2c936792/tests/FileManipulation/PureAnnotationAdditionTest.php#L26

Maybe some bug or some config issue?
