### ISSUE TITLE
Cyclic require_once usage prevent inclusion of files in the baseline

### ISSUE THREAD

**Issue by mindriven** [vimeo/psalm#9197]
When generating baseline, groups of files that have cycling require_once to reference one-another are not included in the baseline.
It happens in simple cases like f1<-->f2 as well as in more complex cases f1-->f2-->f3-->f1,

I this expected behavior?
I only found this old issue, that seems to be describing something similar.
https://github.com/vimeo/psalm/issues/169

**Comment by weirdan** [comment]
Can you provide a minimal reproducer in a separate repo?

**Comment by mindriven** [comment]
I was finally able to devote some time nailing it down, unfortunately I am not successful so far. I have the repository where the issue still occurs, in pretty stripped-down version, but I still can not share it due to IP protection.
I attempted to create another repository, with all factors that I think can pay into the problem present. For now I am stuck, because I can not get over psalm not accepting my definition of global variable (which I can not exclude plays a role here, and is working in the original problem repository).
Can I kindly ask you to take a look and help me get unstuck? Maybe it's something obvious that I am missing...
https://github.com/mindriven/vscode-psalm-testing/commit/b00aeddd93c43d8e809eb71d8b4f028bb38ebeec 

Terminal output:
``` bash
>vendor/bin/psalm --set-baseline=baseline.xml
Warning: "findUnusedBaselineEntry" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Target PHP version: 8.1 (inferred from current PHP version) Enabled extensions: .
Scanning files...
Uncaught RuntimeException: PHP Error: Undefined array key "BASE_PATH" in /home/kamil/vscode-psalm-testing/etc/autoloader.php:3 for command with CLI args "vendor/bin/psalm --set-baseline=baseline.xml" in /home/kamil/vscode-psalm-testing/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:75
Stack trace:
#0 /home/kamil/vscode-psalm-testing/etc/autoloader.php(3): Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}()
#1 /home/kamil/vscode-psalm-testing/vendor/vimeo/psalm/src/Psalm/Config.php(2661): require('...')
#2 /home/kamil/vscode-psalm-testing/vendor/vimeo/psalm/src/Psalm/Internal/IncludeCollector.php(35): Psalm\Config->requireAutoloader()
#3 /home/kamil/vscode-psalm-testing/vendor/vimeo/psalm/src/Psalm/Config.php(2410): Psalm\Internal\IncludeCollector->runAndCollect()
#4 /home/kamil/vscode-psalm-testing/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(388): Psalm\Config->visitComposerAutoloadFiles()
#5 /home/kamil/vscode-psalm-testing/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(615): Psalm\Internal\Analyzer\ProjectAnalyzer->visitAutoloadFiles()
#6 /home/kamil/vscode-psalm-testing/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(369): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#7 /home/kamil/vscode-psalm-testing/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run()
#8 /home/kamil/vscode-psalm-testing/vendor/bin/psalm(120): include('...')
#9 {main}
(Psalm 5.6.0@e784128902dfe01d489c4123d69918a9f3c1eac5 crashed due to an uncaught Throwable)
```

**Comment by orklah** [comment]
Your link is 404 it seems

Note that the error is emitted in your own autoloader apparently so it should get fixed easily

**Comment by mindriven** [comment]
please excuse me @orklah, I just made the repository public, you should be able to open the link now.

**Comment by weirdan** [comment]
```patch
diff --git a/etc/autoloader.php b/etc/autoloader.php
index e1b1a65..22d861f 100644
--- a/etc/autoloader.php
+++ b/etc/autoloader.php
@@ -1,3 +1,3 @@
 <?php
-
+$_SERVER['BASE_PATH'] = dirname(__DIR__);
 defined('PATH_CLASSES') || define('PATH_CLASSES', $_SERVER["BASE_PATH"] . '/src/');
```
This fixes the issue with autoloader, but I can't reproduce the issue in that repo.

**Comment by mindriven** [comment]
thanks @weirdan , it does, and at the same time it elliminates one of the factors that I thought may be paying into the observed issue. In another repo, declaration of global _SERVER in psalm.xml is working fine... any idea why is it not working here?

**Comment by weirdan** [comment]
Declaring globals in `psalm.xml` only affects the analysis part. It does not preclude PHP from issuing notices (that are converted to exceptions) when running autoload.

**Comment by mindriven** [comment]
ahh, after your last comment I think I understood what's going on, thanks, shame on me for not finding it on my own.

Anyway, I think I'm out of ideas of nailing this one down, especially I can no longer assume it's a Psalm issue. This is why: all my attempts so far, where I was able to reproduce the "error", were done in a devcontainer. Today, because I lacked better idea I attempted to generate the baseline file from my machine directly and it worked as expected.

The issue persists in the container, but now I have a workaround for generating the baseline.. and no idea why it does not work in the container.

**Comment by mindriven** [comment]
btw, spending some more time with the problem I compared outputs from devcontainer and my Ubuntu WSL

devcontainer:
``` bash
Warning: "findUnusedBaselineEntry" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Target PHP version: 8.1 (inferred from current PHP version) Enabled extensions: .
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  60 / 371 (16%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 120 / 371 (32%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 180 / 371 (48%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 240 / 371 (64%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 300 / 371 (80%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 360 / 371 (97%)
░░░░░░░░░░░
Writing error baseline to file...
Baseline saved to psalm-baseline.xml.

------------------------------
                              
       No errors found!       
                              
------------------------------
33733 other issues found.
You can display them with --show-info=true
------------------------------
Psalm can automatically fix 971 of these issues.
Run Psalm again with 
--alter --issues=MissingReturnType,InvalidReturnType,InvalidFalsableReturnType,InvalidNullableReturnType,MissingParamType --dry-run
to see what it can fix.
------------------------------

Checks took 29.24 seconds and used 923.272MB of memory
Psalm was able to infer types for 71.0740% of the codebase
```


Ubuntu WSL:
``` bash
Warning: "findUnusedBaselineEntry" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Target PHP version: 8.1 (inferred from current PHP version) Enabled extensions: .
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  60 / 371 (16%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 120 / 371 (32%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 180 / 371 (48%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 240 / 371 (64%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 300 / 371 (80%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 360 / 371 (97%)
░░░░░░░░░░░
Writing error baseline to file...
Baseline saved to psalm-baseline.xml.

------------------------------
                              
       No errors found!       
                              
------------------------------
41453 other issues found.
You can display them with --show-info=true
------------------------------
Psalm can automatically fix 2556 of these issues.
Run Psalm again with 
--alter --issues=MissingReturnType,InvalidFalsableReturnType,InvalidNullableReturnType,InvalidReturnType,MissingParamType --dry-run
to see what it can fix.
------------------------------

Checks took 127.48 seconds and used 1,232.496MB of memory
Psalm was able to infer types for 70.2644% of the codebase
```

devcontainer took around 1/4th of time needed to actually do the job right, and used some less memory. @weirdan I do not know what to make out of it, if you have any idea how to narrow down the issue, I would be happy to stick in few more hours under your guidance.

**Comment by orklah** [comment]
Maybe make sure to wipe cache from both env

**Comment by mindriven** [comment]
Inspired by the documentation (https://psalm.dev/docs/running_psalm/configuration/#cachedirectory) in devcontainer I configured ```XDG_CACHE_HOME``` to point to tmpfs-mounted directory, so there is basically no cache between container restarts (which also may explain the speed difference). On WSL I didn't clear the cache (althouth I just checked, it's in default ```$HOME/.cache/psalm```), as psalm behavior there seems to be correct (except possible quirk I've mentioned here https://github.com/vimeo/psalm/issues/9180#issuecomment-1427039986).
