### ISSUE TITLE
Generic argument on union types requires exactly one concrete type

### ISSUE THREAD

**Issue by scapital** [vimeo/psalm#9211]
Take a look at this example 
https://psalm.dev/r/b406bf1240

Both IntError and StrError are valid types for unsetError,
why "ERROR: [InvalidArgument](https://psalm.dev/004)" is happened?

**Comment by weirdan** [comment]
This one is interesting. Note that `@template-covariant` makes the issue go away: https://psalm.dev/r/be54722b29

**Comment by scapital** [comment]
Thanks!
