### ISSUE TITLE
psalm type inference for arrays is too strict

### ISSUE THREAD

**Issue by max-matiukhin** [vimeo/psalm#922]
It is more question, then a bug report.
Here is an example of my code
https://getpsalm.org/r/6814c13703

Is it intended behaviour?
It seems too strict. Technically psalm is correct, it's type is array{0:string, 1:string, 2:string}
But it is not what I meant. Is it possible to switch this strictness off and use my more general type?

**Comment by weirdan** [comment]
Sure: https://getpsalm.org/r/8e1763596a

You just don't need curlies here, they are for ["shapes"](https://github.com/vimeo/psalm/blob/master/docs/supported_annotations.md#object-like-arrays). So `array{int:string}` means literally array with key named "int", having a string type, so only `return [ "int" => "some string" ];` (with, optionally, some more different keys) would ever satisfy it. 

You want `array<int,string>` here (note the angle brackets).

**Comment by max-matiukhin** [comment]
Feel so ashamed :) Thanks for explanation
