### ISSUE TITLE
Psalm cannot get type array of multidimensional array with isset

### ISSUE THREAD

**Issue by kamil-tekiela** [vimeo/psalm#9222]
In the following example, Psalm should know that the key exists and the variable is not mixed. 

[Cannot access array value on mixed variable](https://psalm.dev/r/b8fa907c7a)

**Comment by orklah** [comment]
Well, technically `$dispatchData[0]['GET']` could very well be an `ArrayAccess` object. Worse, it could be that the object is not immutable and we can't actually be sure that calling the offset `\` will return the same result the second time. There's just too few information in this snippet to infer anything for sure
