### ISSUE TITLE
`@property` annotation ignored for one field only

### ISSUE THREAD

**Issue by alpipego** [vimeo/psalm#9224]
I can't figure this one out: https://psalm.dev/r/9263ad77f3 (shorter version https://psalm.dev/r/a7e4c279fe)

The `InaccessibleProperty` issue is only ever reported for the `$pre` variable, but I can't tell how it's different from the other fields in the class. I guess this is more of a question than a bug report.

**Comment by weirdan** [comment]
Just drop the semicolon after `$pre`: https://psalm.dev/r/25979aad87
![image](https://user-images.githubusercontent.com/57403/216902104-48b4f4cd-8d86-423b-a96c-4b4ffc4071d3.png)

**Comment by alpipego** [comment]
> Just drop the semicolon after `$pre`: https://psalm.dev/r/25979aad87

Oh damn. Thank you for the solution. I looked at this code for so long and couldn't find the issue.
