### ISSUE TITLE
DOMElement::$attributes is declared not null, PHP documents otherwise

### ISSUE THREAD

**Issue by Jean85** [vimeo/psalm#9242]
Reproducer: https://psalm.dev/r/10d681a370

Event the stubs report that property as non-null: https://github.com/vimeo/psalm/blob/4eacb2f234867d34d8489f904c2445aecb9158d0/stubs/extensions/dom.phpstub#L752-L758

But PHP docs (and PHPStorm stubs) report the opposite: https://www.php.net/manual/en/class.domnode.php#domnode.props.attributes

> A [DOMNamedNodeMap](https://www.php.net/manual/en/class.domnamednodemap.php) containing the attributes of this node (if it is a [DOMElement](https://www.php.net/manual/en/class.domelement.php)) or null otherwise.

**Comment by weirdan** [comment]
>    A [DOMNamedNodeMap](https://www.php.net/manual/en/class.domnamednodemap.php) containing the attributes of this node (if it is a [DOMElement](https://www.php.net/manual/en/class.domelement.php)) or null otherwise.

This seems to match what we have in stubs now. `DOMNode::$attributes` is nullable, but `DOMElement::$attributes` is not. Why would you want to change that?

**Comment by orklah** [comment]
I would need some 3v4l link with some case when it does return null to confirm or not. It seems to have been done very deliberately in the stubs so we need to make sure before changing it

**Comment by Jean85** [comment]
Unfortunately, 3v4l doesn't have the extension loaded. 

Locally, it seems that you're right. So probably I should file the bug against the PHPStorm stubs, which are used by PHPStan (which triggered me to open this...)
