### ISSUE TITLE
Incorrect return value is not detected for methods with a template return type since 5.3

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#9245]
This code has an error on line 23 (should return int, not string).

https://psalm.dev/r/aa26301af0

Removing the `mixed` return type fixes the issue: https://psalm.dev/r/6bf5cdea8a.

Regression occurred in https://github.com/vimeo/psalm/pull/8926.

Commit https://github.com/vimeo/psalm/commit/da001c46cd740973b7bc2ed5abec0469203ae584 is the last one, when Psalm reports the problem (correct behavior).

**Comment by orklah** [comment]
@danog could you take a look please?
