### ISSUE TITLE
InvalidDocblock error for callable with nullables

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#926]
https://getpsalm.org/r/526a898f84

```php
<?php
  
/**
 * @param callable(?int $year, ?int $month):void $doStuff
 */
function render(callable $doStuff): void {
  $doStuff(1, 2);
}
```

> Psalm output (using commit 200ea70):
> 
> ERROR: InvalidDocblock - 4:4 - Invalid type 'int$year' in docblock for render

worked fine before

**Comment by weirdan** [comment]
I don't think you're supposed to put var names in there: https://github.com/vimeo/psalm/blob/master/docs/supported_annotations.md#callables-and-closures

Without them, everything seems to work fine: https://getpsalm.org/r/d5769f1f67

**Comment by ostrolucky** [comment]
ah, my bad
