### ISSUE TITLE
Incorrect process psalm-assert for list

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#9261]
`list<string>`
↓
assert `non-empty-string[]`
↓
`list{non-empty-string, ...<int<0, max>, string>}`, but expected `list<non-empty-string>`

https://psalm.dev/r/9ab5fe855a

**Comment by weirdan** [comment]
Workaround: https://psalm.dev/r/fbfb702330

**Comment by weirdan** [comment]
Works now: https://psalm.dev/r/9ab5fe855a
