### ISSUE TITLE
Replace github key token for travis

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#930]
Filing this as a separate issue so that it doesn't get forgotten.

https://github.com/vimeo/psalm/blob/c54534c640b27b4096c8b8daf886e24036c53d7d/.travis.yml#L82 - this still uses my encrypted key, so build *will* fail when you create a tag.

As documented in the initial pull request you need to provide your own encrypted token:
> api_key.secure entry needs to be replaced by github token with public_repo scope, encrypted with
> ```console
> $ travis encrypt -r vimeo/psalm --org # use --pro instead of --org if running from travis-ci.com
> ```

**Comment by muglug** [comment]
Thanks!
