### ISSUE TITLE
Using an interface as a template value should make the template covariant

### ISSUE THREAD

**Issue by Baptouuuu** [vimeo/psalm#9307]
Hi,

I have generic immutable collections having templates that can't be `@template-covariant` because the collections must work with primitive types.

The problem is that creating expecting a collection of an interface always end with an `InvalidArgument` error because using a collection of objects implementing the expected interface is not the interface itself (which doesn't make sense). [example](https://psalm.dev/r/75499c4b2a)

My suggestion is to consider a template always covariant if the template value is an interface. This solves the problem and can't cause any other problems (as far I can see) since the concrete value can't be an interface.

**Comment by weirdan** [comment]
> can't cause any other problems (as far I can see) since the concrete value can't be an interface.

Concrete value can be an interface (as far as Psalm concerned). E.g. 
```php
/** @param Collection<A> $c */
function addToACollection(Collection $c, A $item): void {
    $c->add($item);
}
```

**Comment by weirdan** [comment]
That would be possible for covariant type parameter: https://psalm.dev/r/0d22a5e1c9
This snippet also shows why it's unsound.

**Comment by weirdan** [comment]
To put it simply, the collection needs to be read-only for it to be able to have a covariant item type. Anything else would be unsound in one way or another.

**Comment by weirdan** [comment]
It's covered in this doc chapter in more details: https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance

**Comment by Baptouuuu** [comment]
It's indeed a detail I omitted but my collection (the real one not the example I gave) is immutable so I don't have the problem from your example. If I use `template-covariant` I can no longer use the collection for primitive types.

**Comment by weirdan** [comment]
> If I use `template-covariant` I can no longer use the collection for primitive types.

Can you reproduce it on psalm.dev?

**Comment by Baptouuuu** [comment]
It seems I can't, I would have sworn it raised an error.

Sorry for the noise
