### ISSUE TITLE
class_exists with a nested function

### ISSUE THREAD

**Issue by mzur** [vimeo/psalm#9317]
I'm aware of several open issues regarding the behavior with `class_exists` (https://github.com/vimeo/psalm/issues/5480, https://github.com/vimeo/psalm/issues/7980, https://github.com/vimeo/psalm/issues/6530). I think I found a new issue: https://psalm.dev/r/19cba2e4fb

This is just a minimal example of legitimate Laravel code that should or shouldn't execute a database query. Something like this:
```php
if (class_exists(GenerateThumbnailJob::class)) {
   Image::eachById(fn ($i) => GenerateThumbnailJob::dispatch($i));
}
```

I'm willing to look into this issue if someone can point me into the right direction.

**Comment by lptn** [comment]
@mzur 
What do you think, how Psalm should behave on analysing `GenerateThumbnailJob::dispatch($i));` if it couldn't find this class? I'm trying to find a solution, but without luck ATM.

**Comment by mzur** [comment]
My naive description of the desired behavior is: When there is an existence check e.g. with `if`, then no `UndefinedClass` error should be thrown for that class inside the whole context block of the `if`.

**Comment by lptn** [comment]
@mzur 
I see, but how about static method calls of this class? (and other method calls).

**Comment by mzur** [comment]
Could you please show an example what you mean?

**Comment by lptn** [comment]
```php
if (class_exists(GenerateThumbnailJob::class)) {
   Image::eachById(fn ($i) => GenerateThumbnailJob::dispatch($i)); // how to check return type of the dispatch() method?
}
```

I meant even if we can get rid of `UndefinedClass` issue, the next one will be `InvalidMethodCall` or `PossiblyInvalidMethodCall` or something like this, what will not improve DX a lot.

**Comment by mzur** [comment]
It also works like this: https://psalm.dev/r/c215c2ffc0

**Comment by mzur** [comment]
Wow, that was quick, thanks a lot!

**Comment by weirdan** [comment]
And easy as well. Fixing other linked issues wouldn't be as simple.
