### ISSUE TITLE
strpos() can return false

### ISSUE THREAD

**Issue by mevl** [vimeo/psalm#9319]
```
ERROR: TypeDoesNotContainType - src/CrontabBuilder/Parser.php:240:32 - int does not contain false (see https://psalm.dev/056)
        if (false === strpos($file, $this->doc_root)) {
```

https://www.php.net/manual/en/function.strpos.php
> Returns false if the needle was not found.

**Comment by orklah** [comment]
It seems there's an error in stubs: 
https://github.com/vimeo/psalm/blob/54cd52964253bdbf4a0d1a08a3698200c2fdb4e5/stubs/CoreGenericFunctions.phpstub#L632

The signature should be int|bool at the very least

**Comment by othercorey** [comment]
The callmaps is `int|false` so will change to that:

```
'strpos' => ['int|false', 'haystack'=>'string', 'needle'=>'string', 'offset='=>'int'],
```
