### ISSUE TITLE
--update-baseline exit codes

### ISSUE THREAD

**Issue by wickedOne** [vimeo/psalm#9330]
would it be an option to return differnt exit codes when the `--update-baseline` option actually updates a baseline compared to when it doesn't?

thinking of a ci build which forces the update of a baseline...

**Comment by weirdan** [comment]
As a quick workaround, `git diff -s --exit-code psalm-baseline.xml` will produce `1` if the file is changed and `0` if not. So something like this should work:

```bash
#!/bin/bash
vendor/bin/psalm --update-baseline
if git diff -s --exit-code psalm-baseline.xml ; then
   echo "No changes to the baseline"
else
   echo "Baseline updated"
fi
```

**Comment by weirdan** [comment]
But alternatively, you can enable [`findUnusedBaselineEntry`](https://psalm.dev/docs/running_psalm/configuration/#findunusedbaselineentry) in your `psalm.xml` and Psalm will produce exit code `2` when there either some errors in your codebase *or* baseline entries that do not longer suppress anything.

**Comment by wickedOne** [comment]
thnx @weirdan
