### ISSUE TITLE
Psalm 5.7 started complaining about mb_strlen checks on array elements

### ISSUE THREAD

**Issue by kamil-tekiela** [vimeo/psalm#9341]
It manifests as multiple different issues. Here's one example:
https://psalm.dev/r/897a70d45b

Asserting string length doesn't mean checking if the string is non-empty.

**Comment by weirdan** [comment]
It doesn't seem to happen on a plain variable though: https://psalm.dev/r/6178eba089

> Asserting string length doesn't mean checking if the string is non-empty.

It's the other way around. Asserting non-emptyness doesn't mean the string can't be less than three chars (as in your example).

**Comment by weirdan** [comment]
cc: @LeoVie

**Comment by weirdan** [comment]
It also doesn't happen with nested ifs: https://psalm.dev/r/6ad10cdab0
