### ISSUE TITLE
Cannot run psalm without a composer autoloader

### ISSUE THREAD

**Issue by ewingd** [vimeo/psalm#935]
I have psalm installed globally and wanted to run it on a single file that has no includes and doesn't need or use an autoloader.  I am attempting to create a minimum test case to reproduce an exception psalm is throwing on a larger project.

It refused to run with the message: 

Could not find any composer autoloaders in <project_dir>
Add a --root=[your/project/directory] flag to specify a particular project to run Psalm on.

```
$ tree
.
├── psalm.xml
└── src
    └── main.php


$ cat psalm.xml 
<?xml version="1.0"?>
<psalm>
    <projectFiles>
        <directory name="src" />
    </projectFiles>
</psalm>
```

**Comment by weirdan** [comment]
Well, docs say psalm requires composer (and its autoloader). It doesn't need to be functional though, so you can work around this with `composer init; composer install; psalm`

**Comment by muglug** [comment]
> Well, docs say psalm requires composer (and its autoloader)

Yeah, although I can see why you _might_ not want that. It _shouldn't_ need composer (e.g. when running from the phar or from another directory) and I'll try and get that working properly.

**Comment by sebastianbergmann** [comment]
I have this problem with Psalm 3.2.7:
```
$ ./tools/psalm --init
Failed to find a valid Composer ClassLoader in
```
Not even `--version` works:
```
$ ./tools/psalm --version
Failed to find a valid Composer ClassLoader in
```
However, `--help` works.

As soon as an autoloader generated using Composer exists in `vendor/autoload.php` it works:
```
$ composer init                                                   
  Welcome to the Composer config generator  

This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [sebastianbergmann/example]: 
Description []: 
Author [Sebastian Bergmann <sb@sebastian-bergmann.de>, n to skip]: 
Minimum Stability []: 
Package Type (e.g. library, project, metapackage, composer-plugin) []: 
License []: 

Define your dependencies.

Would you like to define your dependencies (require) interactively [yes]? 
Search for a package: 
Would you like to define your dev dependencies (require-dev) interactively [yes]? 
Search for a package: 

{
    "name": "sebastianbergmann/example",
    "authors": [
        {
            "name": "Sebastian Bergmann",
            "email": "sb@sebastian-bergmann.de"
        }
    ],
    "require": {}
}

Do you confirm generation [yes]? 
```
```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```
```
$ ./tools/psalm --version
Psalm 3.2.7.0@6e010d9db95275725e5ad6409c387eb173091f72
```

**Comment by muglug** [comment]
@sebastianbergmann what's `tools/psalm` - is it a symlink to Psalm in another directory? I've added a slightly better error message in 5003533, but still need more info.

**Comment by sebastianbergmann** [comment]
`tools/psalm` is `https://github.com/vimeo/psalm/releases/download/3.2.7/psalm.phar` (no symlink; installed using `phive install --copy`).

**Comment by muglug** [comment]
The original fix did not apply to the Phar, but I've just patched it to hopefully work more robustly.

**Comment by sebastianbergmann** [comment]
I am seeing this problem (or a problem that looks like it) again with Psalm 5.1.0: without a Composer-generated autoloader present, Psalm refuses to start.

**Comment by weirdan** [comment]
@sebastianbergmann does this only happen for `psalm.phar --init`?

**Comment by sebastianbergmann** [comment]
No, it is not limited to `--init`. A simple `mkdir vendor && touch vendor/autoload.php` works around this.

**Comment by weirdan** [comment]
@sebastianbergmann is there any way for me to reproduce it?

I tried, but everything seems to be working for me:

![image](https://user-images.githubusercontent.com/57403/205481705-a0711c78-d6d5-4482-8a07-931aa058365a.png)

**Comment by sebastianbergmann** [comment]
No, sorry, this is in an internal project. If/When I am able to reproduce it in a minimal and self-contained way then I will open a new ticket. Sorry for the noise!

**Comment by weirdan** [comment]
No problem. At the very least it led to error message improvement in #8827
