### ISSUE TITLE
Uncaught Throwable somewhere in ConcatAnalyzer.php

### ISSUE THREAD

**Issue by ciaranmcnulty** [vimeo/psalm#9355]
This line appears to be breaking Psalm for me:
`$jsons = glob(__DIR__ . '/../acceptance/**/*.json');`

I can't reproduce on psalm.dev but I was able to chop the class down to just that line in a method

I get:
```
Uncaught AssertionError: assert(count($result_type_parts) === $combinations) in /Users/ciaranmcnulty/Code/dockerfile/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php:181
Stack trace:
#0 /Users/ciaranmcnulty/Code/dockerfile/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php(181): assert(false, 'assert(count($r...')
#1 /Users/ciaranmcnulty/Code/dockerfile/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php(138): Psalm\Internal\Analyzer\Statements\Expression\BinaryOp\ConcatAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Scalar\MagicConst\Dir), Object(PhpParser\Node\Scalar\String_), Object(Psalm\Context), Object(Psalm\Type\Union))
```

This is with:
`Psalm dev-master@589fee7b224f4ccb7c878aa3781c38c3a7dbea0a`

**Comment by weirdan** [comment]
Fixed in #9351 
The fix is released in [5.7.2](https://github.com/vimeo/psalm/releases/tag/5.7.2).

**Comment by ciaranmcnulty** [comment]
@weirdan I've tried just now with `Psalm 5.7.2@9e0dd5ab59498aa3f531bd359bc93dac671c5938` and same error is occurring

**Comment by ciaranmcnulty** [comment]
Disabling opcache fixed it for me though

**Comment by weirdan** [comment]
@ciaranmcnulty can you post the error message you're getting on 5.7.2, including backtrace?

**Comment by ciaranmcnulty** [comment]
I can no longer reproduce now it's successfully run. I'll re-open if it reoccurs
