### ISSUE TITLE
Psalter --issues=UnusedVariable tries to fix PossiblyUndefinedVariable

### ISSUE THREAD

**Issue by edsrzf** [vimeo/psalm#9359]
If I start with this code: ([psalm.dev link](https://psalm.dev/r/7dad7e88bc))

```php
<?php

function foo(bool $b): void {
    if ($b) {
        $v = 'hi';
    }

    if ($b) {
        echo $v;
    }
}
```

it correctly flags `$v` as possibly undefined. If I run `psalter --issues=UnusedVariable`, it alters the file to:

```php
<?php

function foo(bool $b): void {
    if ($b) {
    }

    if ($b) {
        echo $v;
    }
}
```

This is pretty unexpected, as:

1. It's altered the code incorrectly. Now the variable is definitely undefined!
2. It's tried to fix a `PossiblyUndefinedVariable` issue, when I only told it to fix `UnusedVariable` issues.

**Comment by orklah** [comment]
What I can say with certitude is that removing this condition:https://github.com/vimeo/psalm/blob/fcf42840f38316e39e23171430f458437ea80dd9/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php#L918
stops Psalter from fixing the issue, so it's made here. However, this block only triggers on UnusedVariable.

I tried to find what's going on exactly but I couldn't.

What I could see is that Psalm will only try to emit the UnusedVariable when in Psalter mode. That means there's something wrongly triggering this issue and then Psalter tries to fix it on the go
