### ISSUE TITLE
Double key declaration on type alias array causes unrecognized type

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#9365]
https://psalm.dev/r/d101d739cc

I had a long list of type aliases, and updating to `5.7.x` caused an error where psalm doesn't recognized the type. Without an error on declaration of the type it was hard to find the issue (because it was working on previous version).

A simple improvement should be to throw an error when the doc-block is invalid for this issue on declaration.

**Comment by weirdan** [comment]
It appears type parser actually emits the error (https://psalm.dev/r/8ad7b70312) but it's swallowed somewhere.

**Comment by weirdan** [comment]
Works on classes and enums, but doesn't work on traits and interfaces: https://psalm.dev/r/909229edda
