### ISSUE TITLE
Type string for ... is always isset

### ISSUE THREAD

**Issue by kamil-tekiela** [vimeo/psalm#9379]
Psalm complains about an `isset` check on an uninitialized property. It should not. 

https://psalm.dev/r/d3c055654e

**Comment by weirdan** [comment]
If you fix `MissingConstructor` and then `PropertyNotSetInConstructor` it won't. Supporting uninitialized properties is not a design goal.

See https://github.com/vimeo/psalm/issues/7865#issuecomment-1098221020
