### ISSUE TITLE
Another preload issue

### ISSUE THREAD

**Issue by SCIF** [vimeo/psalm#9382]
I have preload script configured. As of 5.7+ Psalm versions the preloading is forced on analysis start, I've got next errors appeared:

```
ERROR: UndefinedClass - app/File.php:36:24 - Class, interface or enum named Psl\Type\TypeInterface does not exist (see https://psalm.dev/019)
            $country = Type\non_empty_string()->coerce($country);
```

By adding `return;` on top of my preload files, the behavior of Psalm becomes fine (no new issues).

**Comment by weirdan** [comment]
Can you provide a minimal reproducer in a separate repo?

**Comment by SCIF** [comment]
> Can you provide a minimal reproducer in a separate repo?

Yep, trying to do that right now.

**Comment by SCIF** [comment]
Managed to reproduce. Final docker grooming and will push soon.

**Comment by SCIF** [comment]
Hi guys, I managed to reproduce the issue finally: https://github.com/SCIF/repro9382

**Comment by weirdan** [comment]
Thanks, I've been able to reproduce using the linked repo.

**Comment by weirdan** [comment]
Ok, the quick fix would be to disable preload here: https://github.com/vimeo/psalm/blob/2315c98a73f18244b9818fbbc72d6f0c26b47894/src/Psalm/Internal/Fork/PsalmRestarter.php#L103-L106

That's, I think, the best we can do at the moment. @danog would you agree?

**Comment by danog** [comment]
Sure, adding a forced `opcache.preload=` config to the xdebug restarter (along with a config check) should fix the issue.
