### ISSUE TITLE
Null wrongly added as possible variable value

### ISSUE THREAD

**Issue by MoonE** [vimeo/psalm#9395]
Psalm adds null as a possible value to a variable that never gets assigned null.
After the comparison `$a`s value according to psalm is `-1|null`
```php
<?php

$a = -1;
if ($a !== null) {
}
echo $a;
```
Obviously the  if block serves no purpose here. However the same problem occurred in a more complex function where an `int` variable was compared to an `int|null` variable.

https://psalm.dev/r/1502d48747

**Comment by weirdan** [comment]
Unfortunately, the snippet you posted does not reproduce the issue you're describing.

**Comment by weirdan** [comment]
https://psalm.dev/r/27a443b1bf

**Comment by othercorey** [comment]
Is this the same behavior as https://github.com/vimeo/psalm/issues/9348?

**Comment by weirdan** [comment]
It certainly looks similar.

**Comment by weirdan** [comment]
I thought this was a recently introduced issue, but it's not. It was broken since at least 3.4.0
