### ISSUE TITLE
`never` assignment stops analysis

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#9402]
https://psalm.dev/r/b143a721a2

**Comment by weirdan** [comment]
When there's no assignment, the lines below are analyzed correctly.

**Comment by orklah** [comment]
Removing the false return here: https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php#L537 seems to solve that. Not sure why it was designed to stop here

**Comment by weirdan** [comment]
I kinda makes sense to stop analysis for the branch where we encounter NoValue, but not the whole file

**Comment by orklah** [comment]
Not sure we have enough control over analysis from Analyzers to do that. Returning false will stop analysis, returning anything else will continue as usual. Even return false are sometimes not respected, it's kind of a mess

**Comment by weirdan** [comment]
I'm also unsure how to write a test for this because adding `NoValue` to `ignored_issues` will make even the current code pass.

**Comment by orklah** [comment]
maybe add a suppression for an issue that only appears if the rest of the analysis continued? That way if the issue is no longer raised, Psalm should complain that the suppression is unused

**Comment by weirdan** [comment]
This appears to have been fixed already: https://psalm.dev/r/b143a721a2
