### ISSUE TITLE
Concat should never remove "non-empty-"/"non-falsy-" from string

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9411]
https://psalm.dev/r/0baa3234b5

When concatenating a non-empty/non-falsy string with something else that is unknown (constants), the type should not "fall back", since it's wrong. And instead keep the type it already has (e.g. non-falsy-string in my example)

**Comment by orklah** [comment]
It's handled here: https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php#L255

It should be a pretty simple change

**Comment by EgorBakulin** [comment]
> It's handled here:
> 
> https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php#L255
> 
> It should be a pretty simple change

The problem is more complex than it might seem.

https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php#L65

This variable is null for this snippets https://psalm.dev/r/f264a4732f https://psalm.dev/r/9ef452ff58

**Comment by orklah** [comment]
yeah, I guess it makes sense given FOO was not defined. Then https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php#L69 will return false, so adding an else and setting $result_type accordingly with the known other operand should still be easy

**Comment by EgorBakulin** [comment]
#9422 I created pool request with fixes. But I newer worked with gihub pool requests. And I don't know how to link pool request to this issue.
