### ISSUE TITLE
Strange behavior when assigning to list and class-string-map

### ISSUE THREAD

**Issue by ptomulik** [vimeo/psalm#9412]
False negative for list and false positive for class-string-map. I think these two problems are related:

https://psalm.dev/r/1abd6b7b03

I guess, also #4460 is related.

**Comment by ptomulik** [comment]
The false-positive ``ERROR: InvalidPropertyAssignmentValue - 29:9`` gone (fixed in #9415). The  bug that alters ``ListTest`` has still to be fixed.

**Comment by orklah** [comment]
Seems fixed :)
