### ISSUE TITLE
UndefinedPropertyFetch even if `#[\AllowDynamicProperties]` is specified

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#9421]
https://psalm.dev/r/10f4d65384

**Got:** `UndefinedPropertyFetch`.
**Expected:** no errors when `#[\AllowDynamicProperties]` is specified.

PHPStan yields no errors if `#[\AllowDynamicProperties]` is specified:
https://phpstan.org/r/3c01def8-a910-4d64-839b-9e63e135e269
If the attribute isn't present it yields Undefined Property too (and it's fine):
https://phpstan.org/r/48b21122-ebad-4b7c-8b9b-50d7b2b7120c

**Comment by ygottschalk** [comment]
Seems like that does the trick: https://psalm.dev/r/aed2c59767

**Comment by orklah** [comment]
Indeed, this setting existed before `#[\AllowDynamicProperties]`. It makes sense that Psalm should not emit an issue when the user explicitly stated that dynamic properties are allowed.

Something will need to be added here: https://github.com/vimeo/psalm/blob/d86fcf4a85bcf8a3b38a633fdf3d8303cb6c74b7/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php#L1151
We seem to have the ClassStorage on hand so we would just need to check that it has the AllowDynamicProperties in its own $attributes property
