### ISSUE TITLE
False positive LessSpecificReturnType for unsealed lists

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9426]
https://psalm.dev/r/a3fdd49bca

Similar to https://github.com/vimeo/psalm/issues/9416

**Comment by weirdan** [comment]
@orklah I don't think it's a bug. The returned type is basically a `non-empty-list<non-empty-string>|true`, and it's more specific than the declared one. And the snippet has 'Tighten return types' checkbox set.

**Comment by orklah** [comment]
You're right! I didn't expect the tighten setting to be set
