### ISSUE TITLE
String cannot be used as a class - triggered for enum

### ISSUE THREAD

**Issue by SpacePossum** [vimeo/psalm#9455]
Hi all and thanks for this great tool!

Run into a little thing with `enums` and `string`s
Minimal example:

```php
<?php

namespace App\Bar;

enum Foo: string
{
    case A = 'B';
}

$enum = 'App\Bar\Foo';

/** @var \BackedEnum $x */
$x = $enum::tryFrom('B');

echo $x->value;
```

https://psalm.dev/r/7fdff8e8eb

will tell `String cannot be used as a class` on line 13, however it works fine in PHP :)

this also happens for cases like `$someEnumString::cases()`

**Comment by weirdan** [comment]
This is by design and is not specific for enums. Use `Foo::class` instead: https://psalm.dev/r/9d6b42facf

**Comment by SpacePossum** [comment]
thanks for the fast reply :+1:   I'll refactor : )
