### ISSUE TITLE
TooManyArguments emitted unnecessarily when one of union has issue

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#946]
```php
class A {
  public function foo() : void {}
}
class B {
  public function foo(string $s) : void {}
}

/** @param A|B $a_or_b */
function takesAB($a_or_b) : void {
  $a_or_b->foo("hello");
}
```
Expected: no issue
Actual: Too many arguments for method `A::foo`: https://getpsalm.org/r/95b03e51e8

**Comment by weirdan** [comment]
> Expected: no issue
I guess I disagree. This is too few arguments for A::foo(), which is a ArgumentCountError in php 7.1+

**Comment by muglug** [comment]
> I guess I disagree. This is too few arguments for A::foo()

Why?

**Comment by weirdan** [comment]
Because I need more sleep I suppose :sleeping: . Ignore me.

**Comment by weirdan** [comment]
On the other hand, some internal classes do actually throw warnings on too many arguments (e.g. https://3v4l.org/9GrPP), so the issue emitted might actually be useful there.

**Comment by muglug** [comment]
> some internal classes do actually throw warnings on too many arguments

Hmm - OTOH it would be _super_ rare for that class to be in a union with another that doesn't.

**Comment by weirdan** [comment]
Yeah, agree, especially since php core library is mostly procedural at the moment.
