### ISSUE TITLE
Psalm not able to use psalm.phpExecutablePath setting in VS Code, uses default php instead

### ISSUE THREAD

**Issue by matlinski** [vimeo/psalm#9461]
Hello, I never write git issues so forgive me if it's not well structured.

I have a WSL set up in my windows and there are multiple project inside. Most need PHP 7.4 and that's how default php is configured. There is one project where I need to run php8.1. In that project there is no way to set the alternative binary path for psalm. I tried introducing the following changes to workspace.code-workspace:

```
{
   "settings": {
		"php.validate.executablePath": "/usr/bin/php8.1",
		"psalm.phpExecutablePath": "/usr/bin/php8.1"
   }
}
```

the first path solved the issue for default VS code validation, the second path was added automatically by from VS code Psalm extension GUI (see the screenshot).
![photo_2023-03-06_14-34-28](https://user-images.githubusercontent.com/50202894/223124494-b8740beb-734b-4f80-ae3f-42f423d3d028.jpg)

This should defitelly solve the problem but it didn't. Both VS code extension and composer extension are up to date.

**Comment by matlinski** [comment]
This is VS Codes Extension specific issue, I don't think I can reproduce it enywhere else.

**Comment by weirdan** [comment]
This looks like it needs to be reported to https://github.com/psalm/psalm-vscode-plugin/.
