### ISSUE TITLE
No error when openssl_encrypt/decrypt returns false

### ISSUE THREAD

**Issue by cv65kr** [vimeo/psalm#9469]
`openssl_encrypt` and `openssl_decrypt` can return false|string.

Psalm not raise error in this case https://psalm.dev/r/73ad04a62c

**Comment by weirdan** [comment]
You can set [`ignoreInternalFunctionFalseReturn`](https://psalm.dev/docs/running_psalm/configuration/#ignoreinternalfunctionfalsereturn) in your `psalm.xml` to `false` to enable this check.

**Comment by orklah** [comment]
We should definitely put that to false by default in PHP 6...

It probably made sense a few years ago not to bother people with too much false positive but I feel people kind of expect those now.

There's still the severity level of PossiblyFalse/PossiblyNull that will make the error not pop immediately anyway

**Comment by weirdan** [comment]
> We should definitely put that to false by default in Psalm 6...

It should probably depend on the target PHP version. Those `false`/`null` returns were mostly to signal invalid parameter types that are caught by Psalm anyway, thus the default of `false`. Many of them were converted to exceptions in PHP 8.0 (see https://wiki.php.net/rfc/consistent_type_errors), but it does not apply when we analyze the code targeting older PHP versions.
