### ISSUE TITLE
UnusedVariable false positive on if-elseif-else with exception

### ISSUE THREAD

**Issue by flaviovs** [vimeo/psalm#9478]
See https://psalm.dev/r/5b6314611b

The `throw` line seems to be the culprit. If you comment out the line, the warning goes away.

**Comment by mkroeders** [comment]
Line 10 or 14 overwrite the value, and the exception on line 12 stops the exectution. So the value of line 4 is not used.

When adding an usage of the variable, https://psalm.dev/r/27f81ae06f, the usused variable is removed.

So the error is actually correct

**Comment by flaviovs** [comment]
UPDATE: The `elseif` seems irrelevant. Here's a simplified version:

https://psalm.dev/r/183d056e1f

**Comment by flaviovs** [comment]
> When adding an usage of the variable, https://psalm.dev/r/27f81ae06f on line 9 added a echo, the variable is used so no warning.
> 
> So the warning is actually correct

@mkroeders I'm not following.

The variable is used on line 17 of my first example, because it is needed only after the `if`.

**Comment by mkroeders** [comment]
In the `if` branch you overwrite the `foo` variable to `bar`, so the null value is not used. In the `else` branch there is an exception throw so exception stops, so the `foo` assignment of `null` is not needed on line 4.

**Comment by mkroeders** [comment]
True you are using foo on line 17 in your elseif example, and on line 12 in the other example.

However the variable definition of line 4 is overrwitten with an value or there is an exception thrown so execution stops.

So foloowing the if else example.

line 4 assign null to foo
- if = true, then foo is overwriten with 'bar' and the echo will be 'bar'
- if = false, then an exception is thrown en execution stops.

So the assignment of line 4 is not needed, an can safely be removed

**Comment by flaviovs** [comment]
@mkroeders I appreciate your comments. I think I see what you mean.

So the issue then is more of an "unnecessary assignment" than an "unused variable" per se, because the variable indeed _is_ used. Is that correct?

Just curious, is there a way to suppress only those "unnecessary assignment" warnings globally while keeping the true unused variable warnings on?

The use case I'm trying to address is when the variable is defined before the conditional only as a way to declare its type so that psalm can catch errors down the road.

For example, in https://psalm.dev/r/9203cb3858 the assignment on line 9 is clearly an error, but it can only get caught if the expected variable type is known. Just removing the unnecessary assignment on line 4, and replacing the annotation with `/** @var string|null $foo */` indeed does the job, but it makes the code less explicit (it looks just like a comment someone forgot to remove).

**Comment by weirdan** [comment]
Psalm doesn't have a concept of variable types that would prevent incompatible types from being assigned: https://psalm.dev/r/c4a528ca95

> while keeping the true unused variable warnings on?

Can you provide an example? PHP doesn't allow you to declare a variable at all; an assignment of some sort always accompanies it, so what would the code with a truly unused variable look like?

**Comment by flaviovs** [comment]
> PHP doesn't allow you to declare a variable at all;

But Psalm does it, doesn't it?

I mean, `/** @var string|null $foo */` is a variable (+type) declaration. In fact, this is required for my use case (cf. above).

>  (...) an assignment of some sort always accompanies it

That's where this issue started.

> Psalm doesn't have a concept of variable types that would prevent incompatible types from being assigned: https://psalm.dev/r/c4a528ca95

Actually I'm surprised to know that Psalm doesn't do type check on assignments.

I mean, if one uses `/** @var string|null */`, for example, one is stating the type of the variable explicitly, and if some code try to assign anything other than a _string_ or _null_, then that code should be flagged, IMHO.

But maybe my C and Python habits are getting in the way, where the type declared by the programmer are enforced statically either by the compiler or the static analysis tool.

Thanks for pointing it out though.

> (...)so what would the code with a truly unused variable look like?

Pardon if I don't understand the question. By truly unused variable I mean a variable that is assigned but never accessed in the same scope. Perhaps something like this:

```php
<?php
function something(): void
{
    // (...hundreds of lines here...)
    $var = 'something';
    // (...hundreds of lines that never read or change $var here...)
}
```

("Hundreds of lines" added for dramatic effect :grin:)

**Comment by weirdan** [comment]
> I mean, `/** @var string|null $foo */` is a variable (+type) declaration

It may look like one, but it actually is not (as in 'Psalm doesn't do this'). Psalm interprets it as 'the value that variable `$foo` holds at this point has the type `string|null`'.

> By truly unused variable I mean a variable that is assigned but never accessed

So it's the value of the variable that's never used, right? Because the variable is undoubtedly used - it's being written in that very same assignment. :grin:

Focusing on values rather than variables allows us to flag unused assignments like in your original snippet, but also things like https://psalm.dev/r/255e185fe8 and https://psalm.dev/r/86a55985a5, so I see it as a more powerful concept.

Granted, `UnusedVariable` is a misnomer, but it is what it is and doesn't tend to cause much confusion. We should perhaps extend [the issue documentation](https://psalm.dev/docs/running_psalm/issues/UnusedVariable/) to clarify this. 

> and if some code try to assign anything other than a string or null, then that code should be flagged, IMHO.

PHP itself doesn't forbid it, and a lot of code in the wild assumes it's allowed. I believe attempting to change it would yield many false positives for little practical benefit.

**Comment by flaviovs** [comment]
> 
> 
> >     I mean, /** @var string|null $foo */ is a variable (+type) declaration
> 
> It may look like one, but it actually is not (as in 'Psalm doesn't do this'). Psalm interprets it as 'the value that variable $foo > holds at this point has the type string|null'.

I appreciate you comment. The above makes sense and help me to understand how the tool works. To me this issue can be closed.
