### ISSUE TITLE
InvalidArgument for inherited object

### ISSUE THREAD

**Issue by Venatrix-Vexx** [vimeo/psalm#9480]
I am not sure if this is just bug, or it can be resolved by different annotation, but i could not find anything helpful regardless this issue except suppressing this error.
https://psalm.dev/r/abb86cfc90

**Comment by ygottschalk** [comment]
Solution is to mark the template parameter as covariant:
https://psalm.dev/r/04cb6456a8

Read more here: https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance

**Comment by Venatrix-Vexx** [comment]
Thanks, this seems like a correct way to me and it is indeed working, only thing is, i can't change Collection interface annotation as it is part of the Symfony framework (same for ArrayCollection class) in my example. So i guess i will do more research on Symfony why is not annotated as covariant and how to work with collection and eventualy write a new issue on symfony github if i don't find anything bad with my code.
