### ISSUE TITLE
getopt does not return an array with list(s)

### ISSUE THREAD

**Issue by LauraTaylorUK** [vimeo/psalm#9482]
https://psalm.dev/r/a60cd22d32

getopt returns an array of strings, booleans or an array of strings or booleans. There are no lists within the returned array items.

the definition of the returned array by getopt seems wrong?

Thank you.

**Comment by weirdan** [comment]
> There are no lists within the returned array items.

Sure there are:
```console
$ php -r '$opts = getopt("", ["foo", "bar"]); var_dump($opts); var_dump("foo is list", array_is_list($opts["foo"])); var_dump("bar is list", array_is_list($opts["bar"]));' -- --foo=a --foo=b --bar --bar
array(2) {
  ["foo"]=>
  array(2) {
    [0]=>
    bool(false)
    [1]=>
    bool(false)
  }
  ["bar"]=>
  array(2) {
    [0]=>
    bool(false)
    [1]=>
    bool(false)
  }
}
string(11) "foo is list"
bool(true)
string(11) "bar is list"
bool(true)
```

**Comment by ygottschalk** [comment]
Example 3 on https://www.php.net/manual/en/function.getopt.php shows the list.

Test your parameter with `array_is_list($parameters['foo'])`, it will return true (when called like in your example)
