### ISSUE TITLE
Only first array item is used to validate list type

### ISSUE THREAD

**Issue by MoonE** [vimeo/psalm#9485]
`list` (not ok, no warning):
https://psalm.dev/r/00e15a381c

`array` (ok, warning generated)
https://psalm.dev/r/6206fb1d17

Psalm should warn in both cases.

**Comment by weirdan** [comment]
The key problem here is in `KeyedArrayComparator::isContainedBy()`; it ignores `$fallback_params` of the `$container_type_part`.

Another thing I'm not sure about is `list<false>` being represented as `list{false?,...<int<0,max>, false>}`. @danog is this expected?
