### ISSUE TITLE
Run on extensionless files

### ISSUE THREAD

**Issue by RinkAttendant6** [vimeo/psalm#950]
Is there a way to run Psalm on files without extensions (common for executable CLI scripts)? For example a file in the `bin` directory called `console`:

```php
#!/usr/bin/env php
<?php

declare(strict_types=1);

// rest of file here
```

I tried this in my psalm.xml file (only relevant parts shown):
```xml
<?xml version="1.0"?>
<psalm autoloader="config/config.php">
    <projectFiles>
        <directory name="bin" />
        <file name="bin/console" />
        <ignoreFiles>
            <directory name="node_modules" />
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
    <fileExtensions>
        <extension name=".php" />
        <extension name="" />
    </fileExtensions>
</psalm>
```

But it doesn't appear to check the file.

**Comment by weirdan** [comment]
> But it doesn't appear to check the file.

How do you know this?

Here's the output I get with latest dev-master with a config similar to yours:
```console
$ ./psalm
Scanning files...
Analyzing files...
PHP Notice:  Undefined index: extension in /home/weirdan/src/psalm/src/Psalm/Codebase/Analyzer.php on line 106

Notice: Undefined index: extension in /home/weirdan/src/psalm/src/Psalm/Codebase/Analyzer.php on line 106

ERROR: UndefinedClass - bin/console:3:17 - Class or interface B does not exist
class A extends B


ERROR: MissingFile - bin/console:7:1 - Cannot find file /home/weirdan/src/psalm/bin/src/psalm.php to include
require_once __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'psalm.php';


------------------------------
2 errors found
------------------------------

Checks took 0.07 seconds and used 20.466MB of memory
Psalm was able to infer types for 100.000% of analyzed code (1 file)
```
Looks like it's working just fine.

**Comment by muglug** [comment]
Psalm's not designed to work on extensionless files. I solve this with Psalm by making sure the Psalm runner has a single line of PHP: https://github.com/vimeo/psalm/blob/master/psalm

**Comment by weirdan** [comment]
> Psalm's not designed to work on extensionless files

But it does work, see above. If you tried with something like `./psalm ./psalm` though, that would fail, but only because psalm ignores its own binary.

**Comment by muglug** [comment]
> But it does work

🤷‍♂️  I guess?

**Comment by WDD-Marv** [comment]
> PHP Notice:  Undefined index: extension

I was wondering what that was about...

**Comment by flodnv** [comment]
Hi, I stumbled upon this issue when trying to figure out if Psalm can analyze a single file, at the root of the project directory (cwd), not inside a directory. 

I added all configs suggested above , so:
```
    <projectFiles>
        <file name="something.php" />
    </projectFiles>
    <fileExtensions>
        <extension name=".php" />
    </fileExtensions>
```

However, Psalm is still not seeing the obvious errors (that I purposefully introduced) in something.php... Is this something Psalm can do, or not? I'm unclear on this. 

Thanks in advance!

**Comment by weirdan** [comment]
I can't reproduce that notice anymore.

**Comment by muglug** [comment]
Ah right, due to https://github.com/vimeo/psalm/commit/d6a6e6a1

**Comment by flodnv** [comment]
@muglug it seems that adding `<directory name="/" />` to `<projectFiles>` did the trick!

**Comment by flodnv** [comment]
To clarify... that did the trick on version 2. We just updated to version 3 and now we have to use the full path on the machine, and I'm battling to understand why our `ignoreFiles` have stopped being ignored (they show errors in Psalm's output)... I'm sure it has got to be a config/path change issue.

**Comment by flodnv** [comment]
Here's the gist of my issue (on version 3.0.17, did not happen on version 2) @muglug , maybe you can provide me with some guidance.

1. I'm running Psalm from `/path/Project/`
2. For legacy reasons, a lot of our php files are doing `require_once PATH.'file.php'`, where `PATH` is `/symlinks/Project` which on the filesystem is a symlink to `/path/Project/`
3. This seems to cause Psalm to treat files in `/symlinks/Project` as different files/project than `/path/Project/`, which results in ignoreFiles showing up in the output, as well as a much longer Psalm run time (because not only it checks both paths for everything, but also it doesn't ignore anything in `/symlinks/Project`).

Perhaps you can explain what changed from version 2 to 3 in terms of looking at symlinks?

**Comment by weirdan** [comment]
Can't reproduce anymore.
