### ISSUE TITLE
Recognize globals from autoloader or allow defining them in the configuration

### ISSUE THREAD

**Issue by RinkAttendant6** [vimeo/psalm#951]
Psalm doesn't recognize variables defined in the global scope throughout the entire analysis. Ideally it should  recognize global variables in the file referenced by the `autoloader` property (or have an option to do so).

Alternatively, an option like ESLint's [`globals`](https://eslint.org/docs/user-guide/configuring#specifying-globals) configuration property would suffice (though I'd suggest a hashmap of var name to FQCN instead of var name to boolean, if this is the desired implementation).

**Comment by muglug** [comment]
Fixed by https://github.com/vimeo/psalm/pull/1430

**Comment by RinkAttendant6** [comment]
Nice, I guess the documentation hasn't been updated yet
