### ISSUE TITLE
"self" does not work correctly for extended classes

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9510]
https://psalm.dev/r/abcc0a0b02

I'd expect the trace to be Foo2, not Foo.

Is there any other way to achieve this instead of using "self"?

**Comment by weirdan** [comment]
No, that's how `self` is intended to work.

You probably want `static` instead: https://psalm.dev/r/cafc5ec4bb

`self` specifically refers to the class where it's used, and `static` - to the class (possibly a descendant) used during the call.

**Comment by weirdan** [comment]
Or you may event want `@return $this` if that's what you're actually returning.

**Comment by orklah** [comment]
yeah, returning $this will preserve any template value on the caller side, whereas static will not (because we can't be sure the instance returned is the same). This is mainly useful when using fluent interface on templated classes
