### ISSUE TITLE
`assert()` should not mark variables as used

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#9515]
https://psalm.dev/r/2bbda08bb8

This should result in `UnusedVariable` error for `$i`. Depending on PHP settings, asserts may be eliminated during compilation.

Handling of `@psalm-assert` should be unaffected by this potential change, as methods annotated with this annotation may still have side effects.

**Comment by orklah** [comment]
That would feel very weird to me. What is actionable for a user that would receive this error in this case?

**Comment by weirdan** [comment]
> What is actionable for a user that would receive this error in this case?

They can remove the variable or actually use it, the same as with any unused variables. You can't assume assert would ever be executed, so why would you keep a variable that is only used in the code that will never run (in production environment, anyway)?

**Comment by orklah** [comment]
Yeah but the variable is used in dev environment though. If you delete the variable, you can't do the assert anymore? I don't get it

**Comment by weirdan** [comment]
You'd delete the assert too.

**Comment by orklah** [comment]
But then you remove all asserts in your code? Might as well raise an issue on every assert?

**Comment by weirdan** [comment]
> But then you remove all asserts in your code?

Why?

```php
function f(): int {
   $i = 10;
   assert(is_int($i));
   return $i;
}
```
The above would still be valid, as `$i` is used as a return value. But
```php
function f(): int {
   $i = 10;
   assert(is_int($i)); 
   return -1;
}
```
would raise `UnusedVariable`.

**Comment by orklah** [comment]
oh ok, but what about

```
class Car{

  public function run(){
    $gasLevel = $this->getGasLevel();
    assert($gasLevel > 0.); // raise an error in dev if we somehow managed to run the car without gas to fail early
    ...
  }
}
```
or things like
```
class SensibleResource{

  public function run($kernel){
    $envLevel = $kernel->getEnvLevel();
    assert($envLevel === "PROD"); // this should never be used in development env
    ...
  }
}
```
or even
```
//this has no unused var
function scope(){
    assert($a && ($b || $c === true || $d = false));//very complex expression with no context
    return [$a, $b, $c, $d];
}

//this will raise an error because $meaningful_variable_name is considered unused
function scope(){
    $meaningful_variable_name = ($b || $c === true || $d = false); //extracted complexity and better meaning
    assert($a && $meaningful_variable_name );
    return [$a, $b, $c, $d];
}
```

I admit I don't use assertions a lot myself, but I don't think every assertion has to refer to a variable we will use later in the scope

**Comment by weirdan** [comment]
```php
class Car{

  public function run(){
    $gasLevel = $this->getGasLevel();
    assert($gasLevel > 0.); // raise an error in dev if we somehow managed to run the car without gas to fail early
    ...
  }
}
```
You'd be using this `$gasLevel` in that method, wouldn't you? Otherwise, you could do `assert($this->getGasLevel() > 0)` instead.

```php
class SensibleResource{

  public function run($kernel){
    $envLevel = $kernel->getEnvLevel();
    assert($envLevel === "PROD"); // this should never be used in development env
    ...
  }
}
```
Here you're shooting yourself in the foot. Assertions are not typically executed in a production environment, so your check does nothing specifically where you think it should protect you.


```php
//this has no unused var
function scope($a, $b, $c, $d){
    assert($a && ($b || $c === true || $d === false));//very complex expression with no context
    return [$a, $b, $c, $d];
}

//this will raise an error because $meaningful_variable_name is considered unused
function scope($a, $b, $c, $d){
    $meaningful_variable_name = ($b || $c === true || $d === false); //extracted complexity and better meaning
    assert($a && $meaningful_variable_name );
    return [$a, $b, $c, $d];
}
```

Now that's a compelling example.
