### ISSUE TITLE
psalm-flow annotation not working for class attributes

### ISSUE THREAD

**Issue by kokjoon97** [vimeo/psalm#9524]
When we have an object that has a member attribute tainted, passing the entire object through a function removes the taint even though the stub was annotated with @psalm-flow ($args) -> return

I reproduced using this snippet: https://psalm.dev/r/7a47778d23

How do we annotate such that the taint will be detected here?

**Comment by weirdan** [comment]
Hi @kokjoon97, have you found a workaround for your specific case? If you did, it would be great if you could share it here.
