### ISSUE TITLE
ParadoxicalCondition for no reason?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9552]
Simplified code snippet https://psalm.dev/r/268b76bdec

No idea why/where it asserts that $unit cannot be "lb"?
=> when I comment the "continue;" the error is gone
=> this is ONLY with "lb". When I put "lbs" or anything else the error is gone too

This error is new in v5 (checked with v4 and it's not there)

**Comment by weirdan** [comment]
>  => this is ONLY with "lb". When I put "lbs" or anything else the error is gone too

Looks like it happens with the value the last element of that array has. If I put `lbs` last, it starts happening with `lbs` but emits not issues with `lb`: https://psalm.dev/r/7ebfb98ceb
