### ISSUE TITLE
Use template in var docblock

### ISSUE THREAD

**Issue by Gashmob** [vimeo/psalm#9569]
https://psalm.dev/r/c00bcc38f0

In fact, when I'm using `getService` it knows that the function returns an object of same type as the class-string. But my CI fail because psalm found errors. How can I fix it ?

**Comment by orklah** [comment]
I'm not sure what you're trying to do, Psalm would expects something like that: https://psalm.dev/r/004641fcc0

Is this what you're trying to do?

**Comment by Gashmob** [comment]
It's not exactly what I'm trying to do. Because `$services` is a collection of several object of several types. So if I'm trying to add the class inside its collection, I got an error : https://psalm.dev/r/5505a26d8f.

The goal is to be able to do this :
```php
$manager->getService(Router::class);
$manager->getService(Firewall::class);
...
```

So I instantiate each class only one time and access to these objects in one place

**Comment by ygottschalk** [comment]
Hi, we have the utility type [`class-string-map`](https://psalm.dev/docs/annotating_code/type_syntax/utility_types/#class-string-mapt-as-foo-t) for that.

https://psalm.dev/r/d4dc73c5e3

**Comment by Gashmob** [comment]
Thanks @ygottschalk, it works!
