### ISSUE TITLE
@psalm-assert-if-true and $_SERVER

### ISSUE THREAD

**Issue by max-matiukhin** [vimeo/psalm#957]
Hi
Here is my code : https://getpsalm.org/r/08f1532075

it shows errors "Argument 1 of substr expects string, array<mixed, mixed> provided" on lines 13 and 16 which is expected.
But I expect to have the same error for the line 19. It seems psalm doesn't inference that $_SERVER['abc'] should be an array.

**Comment by muglug** [comment]
Thanks!
