### ISSUE TITLE
Annotations being ignored possibly related to Argument Unpacking

### ISSUE THREAD

**Issue by benplummer** [vimeo/psalm#9571]
https://psalm.dev/r/1802eb5599

I'm fairly new to using Psalm so I apologise if the Issue title isn't very explanatory.

I would have thought that the annotations I added in my example would have been sufficient to prevent the error given back.
Am I missing extra annotations or is there an elegant way around this?

**Comment by ygottschalk** [comment]
I do think that your annotations should be sufficient.
Although Psalm is right about the types: https://3v4l.org/kEgqI
The type of parameter `$events` is `array<int|string, Event>`. You could try and trick psalm (eg add `/** @var array<int, Event> $events */` L17) OR you could thank psalm and fix the code (`$this->events = [...$this->events, ...array_values($events)];`)

But I still think that the type annotation should have overruled the type of the parameter...

**Comment by weirdan** [comment]
Adding `@no-named-arguments` would simultaneously give you the argument type you need *and* make Psalm complain when the method is called with named arguments (that could result in the string offsets): https://psalm.dev/r/92e60ab1f8

**Comment by benplummer** [comment]
> I do think that your annotations should be sufficient. Although Psalm is right about the types: https://3v4l.org/kEgqI The type of parameter `$events` is `array<int|string, Event>`. You could try and trick psalm (eg add `/** @var array<int, Event> $events */` L17) OR you could thank psalm and fix the code (`$this->events = [...$this->events, ...array_values($events)];`)
> 
> But I still think that the type annotation should have overruled the type of the parameter...

Thanks for your help! Your example got me thinking and I actually think the `add` method should accept `int` or `string` keys but then use `array_values` to convert the keys to match the format of `$this->events` (as you mentioned).

It now looks like https://psalm.dev/r/a0d4d4eeca

**Comment by benplummer** [comment]
> Adding `@no-named-arguments` would simultaneously give you the argument type you need _and_ make Psalm complain when the method is called with named arguments (that could result in the string offsets): https://psalm.dev/r/92e60ab1f8

Thanks for the suggestion! I realised from @ygottschalk's reply that my code was partially at fault and have altered that so I think it's all good now.

I'm happy with the solution, so if everyone else is happy that Psalm is performing as it should here, this is can be closed.

Thanks again!

**Comment by fluffycondor** [comment]
I'm a little confused that warning in the initial snippet isn't an issue.
Considering https://psalm.dev/r/316e3b9eb5
$events is specified as `array<int, Event>`. Why passing a string key there doesn't yield any warning? Why it's traced as `array<array-key, Event>` if it has `@param array<int, Event> $events`?
