### ISSUE TITLE
UnhandledMatchCondition when case is not possible

### ISSUE THREAD

**Issue by mkroeders** [vimeo/psalm#9574]
When passing an enum to match when a one of the cases is earlier handled and so not possible to match it gives a `UnhandledMatchCondition`

https://psalm.dev/r/5a0388b258

**Comment by orklah** [comment]
I guess Psalm could try to exclude that particular enum value and list all other as a type in `$foo`. Not sure if $match will still be able to check for UnhandledMatchCondition then, maybe this will need improvements

**Comment by weirdan** [comment]
Seems to be fixed.
