### ISSUE TITLE
DeprecatedClass should apply to all properties/methods of the class

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9591]
https://psalm.dev/r/2a1919ec04

When a class has @deprecated, then all properties/methods of the class should be treated as if they are deprecated too.
Line 20/22 should give DeprecatedProperty/DeprecatedMethod error just like if the @deprecated is added explicitly for them (e.g. https://psalm.dev/r/c9d20f58ba)

**Comment by othercorey** [comment]
I wouldn't want this. I think a deprecation warning on class use covers everything. If you decide to suppress that until you replace the deprecated class, then you don't want to see a deprecation every place you use that class. It would flood your output.

However, if psalm doesn't throw a deprecation warning when using the class as a parameter (let's say from a package), then we'd need that.
