### ISSUE TITLE
[Enhancement] Report $deprecated arguments

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9592]
https://psalm.dev/r/e21667d6cd

When calling a function where:
- a param is named `$deprecated` or regex `$deprecated\w+`
- has a default value
- is the last param (or there are only other variables that meet the same conditions)

It should give a new error DeprecatedParam so we know that these args do not need to be passed to the function anymore/won't do anything, since they're deprecated.

Also when:
When calling a function where:
- a param is named `$deprecated` or regex `$deprecated\w+`
- has a default value
- is NOT the last param
- the passed value does NOT match the default value

It should give a new error DeprecatedParam that the passed param value won't be used, since it's deprecated. Instead pass the default value set in the function.

**Comment by weirdan** [comment]
I've never seen people do that. Could it be a rather obscure convention?

Also, it would cause false positives for parameters actually called `$deprecated`, e.g.

```php
class FunctionEntry {
    private bool $deprecated = false;
    public function setDeprecated(bool $deprecated = true) { $this->deprecated = $deprecated; }
}

function f(FunctionEntry $f): void {
    $f->setDeprecated(false);
}
```

You probably can implement this as a Psalm plugin.
