### ISSUE TITLE
Named objects should not be included in generic object for return types

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9602]
https://psalm.dev/r/b9d2729359

Would be great if the trace would be `Bar|object` instead of object only.
I understand where this is coming from (multiple array types with |), but for objects this shouldn't be too difficult to separate, especially since it already works when using named objects only (`Bar|Hello`)

**Comment by orklah** [comment]
What would be the point?

**Comment by ygottschalk** [comment]
Using `Bar|object` instead of `object` is like writing `0+42` instead of `42`.

If it is about documentation, my idea would be to use `@param object` for phpdoc and `@psalm-param Bar` for psalm.

**Comment by orklah** [comment]
yeah, I'm gonna close this. Feel free to follow @ygottschalk suggestion or document your types in other ways (you can create your own tags like `@future-param/@legacy-param` that Psalm won't try to read
