### ISSUE TITLE
issue with typehinting Throwable::getTrace() in foreach loop

### ISSUE THREAD

**Issue by WDD-Marv** [vimeo/psalm#961]
```php
<?php declare(strict_types = 1);

try {
  
} catch (Throwable $e) {
    /**
    * @var array{file:string, line:int}|array{class:string, function:string} $trace
    */
    foreach ($e->getTrace() as $trace) {
        if ( ! isset($trace['file'])) {
            echo ($trace['class'] . '::' . $trace['function']);
        } else {
            echo ($trace['file'] . ':' . $trace['line']);
        }
    }
    exit(1);
}
```

This issue affects both psalm 1.x  & [getpsalm.org](https://getpsalm.org/r/00b8c01e9a)

Is it related to reserved words ?

**Comment by muglug** [comment]
No, it's just about how Psalm combines types.

`array{file:string, line:int}|array{class:string, function:string}`

is simplified to

`array{file?:string, line?:int, class?:string, function?:string}`

i.e. all the fields are treated as optional.

**Comment by WDD-Marv** [comment]
Is there an option to disable such simplifications ?

**Comment by weirdan** [comment]
I think it would be better handled as [discriminated union](https://github.com/basarat/typescript-book/blob/master/docs/types/discriminated-unions.md), but Psalm doesn't currently support that either.

**Comment by WDD-Marv** [comment]
@weirdan something like this?

```php
<?php
/**
* @somespecialtag array{file:string, line:int} Foo
* @somespecialtag array{class:string, function:string} Bar
*/

try {
  
} catch (Throwable $e) {
    /**
    * @var Foo|Bar $trace
    */
    foreach ($e->getTrace() as $trace) {
        if ( ! isset($trace['file'])) {
            echo ($trace['class'] . '::' . $trace['function']);
        } else {
            echo ($trace['file'] . ':' . $trace['line']);
        }
    }
    exit(1);
}
```

**Comment by weirdan** [comment]
I was thinking about something like `array{kind:'line',...}|array{kind:'function', ...}` actually

**Comment by WDD-Marv** [comment]
@weirdan is the variadic a placeholder or an example? variadic in an explicitly type-hinted array seems like a neat way of saying "these things are here, but there might be others" (compared to `array{kind:'line'}|array{kind:'function'}` hinting *only* these things are here)

**Comment by weirdan** [comment]
> @weirdan is the variadic a placeholder or an example?

Example.

> variadic in an explicitly type-hinted array seems like a neat way of saying "these things are here, but there might be others" (compared to `array{kind:'line'}|array{kind:'function'}` hinting only these things are here)

Well, there's no "final shapes" in Psalm now. Meaning `["a" => 1, "b" => 2]` is accepted where `array{b:int}` is expected. This is contrary to what you seem to expect, but it makes sense when you think of shapes in terms of their "inheritance".

**Comment by WDD-Marv** [comment]
@muglug @weirdan is it worth [more explicitly defining the type within psalm](https://github.com/vimeo/psalm/blob/3e69a333c9683596ad4a4325e0039374516295a0/src/Psalm/CallMap.php#L12891) ?

**Comment by weirdan** [comment]
Wouldn't harm, I think, but I'm not if shape syntax is allowed in CallMap.
