### ISSUE TITLE
Psalm --init scan and avoid given directories

### ISSUE THREAD

**Issue by nmeri17** [vimeo/psalm#9613]
I suffered everything reported in https://github.com/vimeo/psalm/issues/245 

I understand that psalm needs to analyse the project before generating a config (cuz of the level) but that can't work for me cuz my project lacks a src directory and contains a stubs directory that should be avoided. So far, I can't find a cli option to skip that folder while generating the config

So, what I would want is a command that can be plugged into a composer script, for scanning a custom directory and skipping another one. Otherwise, I may copy one from another project and just skip the init process

I don't know what version of psalm I'm on. I used * because a more specific version doesn't match my dependencies constraint. But a look at the composer.json has php section with ^7.4 through ~8.2.

@psalm-github-bot no, I can't re-produce there, as it's beyond one file

**Comment by nmeri17** [comment]
Composer extra.branch-alias includes 5.x

**Comment by orklah** [comment]
--init can be followed by two arguments: the source directory (that will replace src) and the level you want to use (that should prevent Psalm to scanning the first time)

**Comment by nmeri17** [comment]
@orklah I tried the path option. I just tried the level option. Neither worked. It interprets version number as a directory. I must be doing something wrong

**Comment by nmeri17** [comment]
Nvm. I'll just use a default configuration schema
