### ISSUE TITLE
Solving array shape issues with objects

### ISSUE THREAD

**Issue by juacala** [vimeo/psalm#9621]
Array shapes are great. They allow you to use arrays like objects. Unfortunately, they lag behind objects in fully documenting them. 

1. It’s difficult to document elements within an array. See https://github.com/vimeo/psalm/issues/9611
2. If the shape gets reused, you can use psalm-type and psalm-import-type, but it’s not as easy to use as just referencing a namespaced class, and IDE support is less robust (no hints on properties and online doc display is lacking on all I’ve tested: vscode intelephense devsense and others)

What are thoughts on something like
`@param array(\path\to\class)`

Note: the only reason I chose () is so as not to collide with the already used [] <> {}

It seems like from a parsing perspective it should be relatively easy. It’s easy to read. It also seems like improving IDE support should be easy since it works exactly as objects except it uses array access (`$arr[‘prop’]`) rather than `$obj->prop`.

The one thing you can’t do is differentiate between “not there” vs null (e.g. did a fetch from a database table not include a column or is the column value null), since object properties are always there; the current array shape does differentiate via `{prop:?string}` vs `{prop?:string}`

One benefit is once one gets the static analyzer to pass, it should be easy to write a migration script to just use the class itself, which can have advantages over arrays. This is as long as no array specific functions are used. 

Also, doing some algebra seems like it would be easy to implement as well:
@param array((\class1 & \class2) | \class3)

If people think it’s a good idea, I think my company could put some resources toward its implementation.

**Comment by ygottschalk** [comment]
What does `@param array(\path\to\class)` mean, can you explain this a little bit further?

Where does that syntax differ to `@param array<\path\to\class>` or `@param list{\path\to\class}`.

I might have missed something, but I failed to find any info about what the proposal is about...

**Comment by juacala** [comment]
Hi @ygottschalk , I apologize for not making it more explicit:

The idea is to match to the shape of the object.

It's different from
```
@param array<\path\to\space\myArrayShape> $param1
@param list{\path\to\space\myArrayShape} $param2
```
which are arrays whose values are the objects.

The keys of the array in the proposed syntax would be the same as the properties of the objects.

Consider the following:
https://psalm.dev/r/0d2140bcb7
```
<?php
namespace path\to\space;

/**
 * Echoes array shape information.
 * @param array{myInt: int, optionalString?: string, nullableString: ?string, myFloat: float} $myArrayShape 
 * @return void 
 */
function echoInfo(array $myArrayShape): void
{
    $newVal = $myArrayShape['myFloat'] + $myArrayShape['myInt'];
    echo ($myArrayShape['optionalString']??'NO DESC: ')." has val ".$newVal;
}
```

with the proposed syntax, we could write:
https://psalm.dev/r/d80a2dfabe
```
<?php
namespace path\to\space;

class myArrayShape
{
    /**
     * Object that can simulate array shape behavior.
     * NOTES:
     * We can do a much better job to document the properties of the parameters.
     * Nesting of shapes would be straightforward as well, since you can just create objects for nested layers.
     * @param int $myInt Integer to get added to float
     * @param null|string $nullableString Nullable string.
     * @param string|null $optionalString Optional string; NOTE this is always present in object, but optionally
     *  present in array shape. This is the only thing I'm aware of this can't simulate in an array shape...
     *  Perhaps you can use the fact that it's optional in the arguments to signify this?
     * @param float $myFloat Float to get added to integer.
     * @return void 
     */
    public function __construct(
        public int $myInt,
        public string|null $nullableString,
        public float $myFloat,
        public string|null $optionalString=null
    ){}
}


/**
 * Using proposed array shape using object shape, echoes array shape information.
 * If the function were in a different file, this would still work, since namespaced
 * classes have fully qualified names.
 * @param array(\path\to\space\myArrayShape) $myArrayShape 
 * @return void 
 */
function echoArrayInfo(array $myArrayShape): void
{
    $newVal = $myArrayShape['myFloat'] + $myArrayShape['myInt'];
    echo ($myArrayShape['optionalString']??'NO DESC: ')." has val ".$newVal;
}

/**
 * Echoes array shape object version information. Potentially, we could migrate to this syntax once we get
 * things to pass, to do away with the array shape altogether.
 * @param \path\to\space\myArrayShape $myArrayShapeObj 
 * @return void 
 */
function echoObjectInfo(\path\to\space\myArrayShape $myArrayShapeObj): void
{
    $newVal = $myArrayShapeObj->myFloat + $myArrayShapeObj->myInt;
    echo ($myArrayShapeObj->optionalString??'NO DESC: ')." has val ".$newVal;
}
```

**Comment by ygottschalk** [comment]
Ok, now I see what this is about. Did you've had a look at [`properties-of`](https://psalm.dev/docs/annotating_code/type_syntax/utility_types/#properties-oft)? I think it is exactly what you are proposing.

If not, we could build up on that...

**Comment by juacala** [comment]
https://psalm.dev/r/29ab03cca7

I was not aware of it. 

That does appear to work. Thanks much!
