### ISSUE TITLE
Report division by 0 errors

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9631]
When dividing by a generic int, you will eventually get a division by 0 PHP error, therefore psalm should report that:
https://psalm.dev/r/7471721898

No error when validated:
https://psalm.dev/r/c7b184e056

**Comment by orklah** [comment]
I think it would be a pretty intrusive issue with very little real bug fixed. However, it's a veeery easy thing to do in a plugin so feel free to create one and publish it in case some other people are interested (every psalm plugin is listed here: https://psalm.dev/plugins thanks to the correct tag in composer file)
