### ISSUE TITLE
PossiblyNullPropertyFetch error received after testing for null on method

### ISSUE THREAD

**Issue by ramsey** [vimeo/psalm#9635]
After using a conditional to test whether a method returns a `null` value, Psalm reports an error when attempting to use properties or methods on the return value of the method via method chaining.

When I assign the method's return value to a variable and check for `null` on that variable, then Psalm does not report an error when attempting to use properties or methods on the variable.

This example illustrates the issue: https://psalm.dev/r/81e6ef8edd

**Comment by orklah** [comment]
Yeah, it's expected. Psalm does not know your method will always return the same result twice. For example:
https://psalm.dev/r/0ed30f7fc6

and here's the solution:
https://psalm.dev/r/4eb4553bd3

Flagging your class as immutable let Psalm know the property won't change (flagging the method as pure would also do it in theory but you can't access property unless the class is immutable anyway)
