### ISSUE TITLE
RiskyCast: non-numeric-string to int/float

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9636]
https://psalm.dev/r/66575ee8d3

Should perhaps give a RiskyCast error when typcasting non-numeric-strings to int/float

**Comment by orklah** [comment]
That's a good idea, I had the same 3 years ago but decided to make a plugin out of it: https://github.com/orklah/psalm-strict-numeric-cast

Those very specific issue are more suited in a plugin instead of in the core IMHO
