### ISSUE TITLE
Psalm doesn't work with const array when key is enum value

### ISSUE THREAD

**Issue by AndreyThompson** [vimeo/psalm#9644]
I have const array in class and I use enum's value as key.
Psalm is going crazy with "Constant TranscodingCreateRequestFactory::MAP is not defined"
https://psalm.dev/r/ed2358aa53

But if change array key to simple string - everything works
https://psalm.dev/r/992a7c1602

**Comment by orklah** [comment]
Indeed, Psalm seems to have failed silently here

**Comment by ygottschalk** [comment]
Issue is tracked here: #9373
PR with fix is here: #9393
