### ISSUE TITLE
InvalidReturnStatement and InvalidReturnType: declared and inferred type in error message are identical?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9645]
https://psalm.dev/r/7f484038c8

False positive as the declared/inferred types in the both error messages are identical.

A simple sanity check in the errors would fix this - if both the types in the error message are the same, then don't report an error.

**Comment by orklah** [comment]
This is on purpose (see https://psalm.dev/docs/running_psalm/issues/InvalidReturnType/). Also the 2 messages aren't even the same?
