### ISSUE TITLE
PossiblyNullReference when assigning by reference

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#9659]
https://psalm.dev/r/518323e48d

While the code is correct: https://3v4l.org/8lAs5

PHP uses a similar pattern elsewhere, I believe.

**Comment by sanmai** [comment]
Tweaked case: 
https://psalm.dev/r/0a5624eaa7

**Comment by orklah** [comment]
Please check @param-out to document the type of you parameter once the function has ended: https://psalm.dev/docs/annotating_code/supported_annotations/#param-out-psalm-param-out
