### ISSUE TITLE
`@psalm-assert` should assert type after passing all never-returning branches

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#9661]
https://psalm.dev/r/4150a3c1a7

 It's safe to assume the type from `@psalm-assert` for `$bar` after passing all never-returning branches.

**Expected**: no errors.
**Got**: LessSpecificReturnStatement and MoreSpecificReturnType.

**Comment by orklah** [comment]
the strlen check should let Psalm infer that $bar is non-empty. 

Aside from that, it's Psalm's job to check, not to assume you didn't make mistakes. It would be weird to automatically consider that the type is the correct one (and it would lead to a whole new set of issues to be emitted in case you want to force a bool to be a string through an assertion for example).

Your snippet is pretty weird too, why would you return $bar without changing it after asserting its type?
