### ISSUE TITLE
Different baseline depending on --debug

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#9668]
Hi,

I've updated our psalm baseline using `psalm --no-progress --set-baseline=psalm-baseline.xml --update-baseline --output-format=github --no-cache`

Then running the same command, but with `--debug` added, i get changes in the baseline file. E.g.:

```diff
-    <UndefinedDocblockClass>
-      <code><![CDATA[$this->tokenStorage->getToken()->getUser()]]></code>
-    </UndefinedDocblockClass>
```

I don't see how the --debug flag should impact the baseline, and was hoping to find any hints here.

**Comment by jack-worman** [comment]
`--debug` sets threads to 1.
My best guess is this is because some bug depending on the number of threads used.

**Comment by ro0NL** [comment]
@jack-worman thanks!

It seems CI (in my case Github Actions) is implicitly running `--threads=1` also!

Running with the same flag locally actually reveals the same errors as shown in CI

It has to be either cache related, or a psalm src bug

I'll run with `--threads=1` to overcome :sweat_smile:
