### ISSUE TITLE
InvalidReturnStatement and InvalidReturnType: declared and inferred type in error message are identical? v2

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9669]
https://psalm.dev/r/7f484038c8

False positive as the declared/inferred types are identical (the **bold** highlighted part below)

InvalidReturnStatement
>The inferred type 
'**array<string, array<string, string>|string>|string**'
does not match the declared return type 
'T:fn-foo::sanitize as **array<string, array<string, string>|string>|string**' 
for Foo::sanitize

Same issue here:

InvalidReturnType
>The declared return type 
'T:fn-foo::sanitize as **array<string, array<string, string>|string>|string**'
for Foo::sanitize is incorrect, got 
'**array<string, array<string, string>|string>|string**'

**Comment by orklah** [comment]
As I said, It's on purpose. One of the issue targets the type in the function declaration the other targets the statement.

One of the two is wrong but we can't tell which (it's either an error with a specific statement that returns something unexpected or an error in the type that is declared).

If you don't want to have both each time, just suppress one of those. You'll probably want to make the same thing with LessSpecificReturnStatement/MoreSpecificReturnType or MoreSpecificImplementedParamType/LessSpecificImplementedReturnType and probably others
