### ISSUE TITLE
Way to widen/narrow inference

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#9677]
Currently, Psalm aggressively narrows all inferred types:

https://psalm.dev/r/c97bc21c8e
```php
<?php

$a = 42; // inferred as 42
/** @psalm-trace $a */;

$b = [40, 41, 42]; // inferred as list{40, 41, 42}
/** @psalm-trace $b */;

$c = new ArrayObject(['str' => 42]); // inferred as ArrayObject<'str', 42>
/** @psalm-trace $c */;
```

It would be nice to be able to manage it somehow. For example:

```php
<?php

/** @widen */
$a = 42; // inferred as int
/** @psalm-trace $a */;

/** @widen */
$b = [40, 41, 42]; // inferred as non-empty-list<int>
/** @psalm-trace $b */;

/** @widen */
$c = new ArrayObject(['str' => 42]); // inferred as ArrayObject<non-empty-string, int>
/** @psalm-trace $c */;
```

Or class templates: 
https://psalm.dev/r/bacd1cb8e7
```php
<?php

/**
 * @template A widen
 */
final class Container
{
    /**
     * @param A $value
     */
    public function __construct(
        public readonly string $value,
    ) {}
}

// Currently infers as Container<42>
// but with the "widen" modifier it will be Container<int>
$container = new Container(42);
/** @psalm-trace $container */;
```

Or even with functions:
https://psalm.dev/r/ec18b1dd81
```php
<?php

/**
 * @template A widen
 * @param A $value
 * @return A
 */
function id(mixed $value): mixed
{
    return $value;
}

// Currently infers as 42
// but with the "widen" modifier it will be int
$value = id(42);
/** @psalm-trace $value */;
```

What do you think?
I could try to implement this.

**Comment by danog** [comment]
To be frank, I don't see any sane usecase for such a feature.

**Comment by klimick** [comment]
> To be frank, I don't see any sane usecase for such a feature.

What I want: https://psalm.dev/r/a8805000d4
What I do actually: https://psalm.dev/r/3ebeacd959

What I want: https://psalm.dev/r/a9500084ee
What I do actually: https://psalm.dev/r/a541f502a1

I often have to write dock blocks in places where this could have been avoided.

**Comment by klimick** [comment]
> While I see your issue in this case, personally I would simply use a single template parameter, because IMO there is no real use in specifying a separate template type just for the accumulator type, which in 99% of cases (including this one) is of the same overall type as the input type: ...

Reduce function should have 2 template parameters:
https://psalm.dev/r/ed4255646f

Input collection may have different type than accumulator type.
There is another name of `reduce` - `fold`.
i.e. fold all elements of type `A` to type `B`.

> This is outright the wrong way of doing it

You right. While a class is immutable.
What about mutable class?
https://psalm.dev/r/59a29420ef

**Comment by danog** [comment]
>Input collection may have different type than accumulator type.

Actually, I realized it's more of an issue of template inferring priority, if we change the order of the parameters the issue goes away: https://psalm.dev/r/b2060a1c62
Possibly, there should be some way to tell Psalm that the template type should not be inferred from the first parameter that uses it, but from some other parameter, if needed.

> What about mutable class?

Simple, https://psalm.dev/r/9d3da1bb35

**Comment by ygottschalk** [comment]
I'd suggest using all parameters to infer the template type..

**Comment by klimick** [comment]
> Simple: ...

I'm aware about `psalm-this-out`. This is unsound feature that can drastically lie:
https://psalm.dev/r/045bd9f203
This requires some additional work unknown to me to become safe.

> Perhaps simply inferring template types according to the order of the `@param` phpdocs using them is enough.

Currently, templated function params inferring left to right. It happens in the `ArgumentsAnalyzer`.
We cannot know type of rhs argument before that lhs argument will be analyzed.

**Comment by klimick** [comment]
I gonna close that ticket in favor: https://github.com/vimeo/psalm/issues/4564
Additional context here: https://github.com/vimeo/psalm/issues/9684
