### ISSUE TITLE
IIFE argument mixed type

### ISSUE THREAD

**Issue by sserbin** [vimeo/psalm#968]
Test case:
```php
$dates = [new DateTime];

(function (iterable $dates): Generator {
    foreach ($dates as $date) {
        strlen($date);
        yield $date;
    }
})($dates);

```

Expected: `$date` type is `DateTime`
Actual: `$date` is `mixed`

**Comment by sserbin** [comment]
Ah, yes, I just thought it should be inferred, but it's not in a regular function so I guess that's ok then.

**Comment by muglug** [comment]
You can add param types to closures like so:
https://getpsalm.org/r/ab7576d2ac

Psalm will validate those against whatever's passed into them
