### ISSUE TITLE
Broken magic properties

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#9692]
https://psalm.dev/r/5c15139bd5, caused by #9656, working on a fix...

**Comment by orklah** [comment]
are we sure that's what we want?

Intersecting an object with a `content` property and another object with a `__tempProperties` is pretty weird, no? Shouldn't that be a union?

**Comment by danog** [comment]
That's an internal detail, something our plugin uses to represent "temporary" properties that may be attached to an object (ugly, I know, will phase them out completely eventually).
The crux of the issue is that property fetches on an intersection of a shaped object and a named object are broken.
