### ISSUE TITLE
Writes to references of readonly properties not detected

### ISSUE THREAD

**Issue by jack-worman** [vimeo/psalm#9697]
https://psalm.dev/r/c663093cf6

**Comment by jack-worman** [comment]
Here is a simplified example: https://psalm.dev/r/eb2781fdef

**Comment by weirdan** [comment]
A sensible approach would be to entirely forbid obtaining references to read-only properties

**Comment by orklah** [comment]
There are cases where this could be legit though. Memory management would probably be one use case where you want to pass references around, even for reading
