### ISSUE TITLE
InaccessibleProperty triggered on readonly public property

### ISSUE THREAD

**Issue by abcapili** [vimeo/psalm#9722]
I've a class (builder) with the following. I believe it should not trigger the error `InaccessibleProperty`

![image](https://user-images.githubusercontent.com/60128786/235096648-bb9ec990-a984-4e3a-96cb-45bb2201fd59.png)

https://psalm.dev/r/e1f12de541

**Comment by orklah** [comment]
The error message is unclear.

Psalm is trying to protect you from https://3v4l.org/PL8MT

So it will prevent any write access on a readonly property except from __construct.

The setter you have is not safe but if that's the way you do things, you might want to suppress this issue
