### ISSUE TITLE
Incorrect PossiblyInvalidArgument behaviour: Argument 2 of Exception::__construct expects int, but possibly different type int|string provided

### ISSUE THREAD

**Issue by xepozz** [vimeo/psalm#9723]
https://psalm.dev/r/b568babcf4

Incorrect PossiblyInvalidArgument behaviour: 
`Argument 2 of Exception::__construct expects int, but possibly different type int|string provided`

If you look at https://www.php.net/manual/en/throwable.getcode.php you may see `int` return type for the `getCode` method.

**Comment by orklah** [comment]
PHP has an annoying edge case here. `PDOException` is a Throwable that will possibly return a string for getCode(), as noted in the doc link you posted:

> Returns the exception code as int in [Exception](https://www.php.net/manual/en/class.exception.php) but possibly as other type in [Exception](https://www.php.net/manual/en/class.exception.php) descendants (for example as string in [PDOException](https://www.php.net/manual/en/class.pdoexception.php)).

That means, there are Throwable that will return a string but Exception::__construct DO expect an int for the $code parameter.

The error Psalm raise is correct. If you don't expect to handle PDOException, you can just ignore it though
