### ISSUE TITLE
list{0?: T, 1?: T} should not be assignable to list<T>

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#9724]
https://psalm.dev/r/62ff8f964a

In that case `$var` should be inferred as `array{0?: T, 1?: T}`: https://psalm.dev/r/128be96ce7

**Comment by orklah** [comment]
I'm not sure I get what the issue is?

**Comment by klimick** [comment]
> I'm not sure I get what the issue is?

It took me about an hour to realize that everything is fine 🗿😶
