### ISSUE TITLE
Type check for union templated class using array goes wrong with value from function

### ISSUE THREAD

**Issue by provokateurin** [vimeo/psalm#9731]
https://psalm.dev/r/24f24ab764

This is a really odd edge case. It depends on many factors and I wasn't able to make it smaller.
It seems to need the following things to break:
- Union type of same templated class in return
- Template types have to be arrays
- Value has to come from a function

**Comment by orklah** [comment]
It seems to be a convoluted case of [covariance check](https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance).

First, Psalm translate `A<array{a: string}>|A<array{b: string}>` to `A<array{a?: string, b?: string}>`. We could argue it's a different shape but it's consistent with the way Psalm handles shapes.

Then, you return a `A<array{b:string}>` and Psalm finds it's a more precise template than `A<array{a?: string, b?: string}>` and don't allow that.

The solution is to make the template covariant: https://psalm.dev/r/f0b8d69e4e

**Comment by provokateurin** [comment]
I see, but I don't understand why it works with the plain value but not the value from the function, since they have the same type. To me this seems like a bug :thinking: .

**Comment by provokateurin** [comment]
Could you explain to me why it has to be covariant? I don't understand that part :/

**Comment by provokateurin** [comment]
That part I do understand, but I don't understand why it works with the direct string and not the returned string. They should lead to the same type for the return statement, right?

**Comment by orklah** [comment]
That part is related to https://github.com/vimeo/psalm/pull/9746 (and other linked issues)

Basically: when a template contains a literal, Psalm assumes that it's likely it was inferred from a `new Collection(['a'])` or something and allow breaking covariance check. 

The reason behind this is debatable, but it doesn't have much to do with your issue. Here you should just make your template covariant and it will allow you to return a more narrow template
