### ISSUE TITLE
Ignore mixed issues for return types of specific stubs

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9749]
I have a library where the @return are missing in about 50% of methods, however the library is getting improved and eventually should be fixed.

Adding @var comments (or asserting) for all these cases is a huge waste of time.

It would be amazing if there was an option to not report mixed issues on any variables that are the direct result of a function call to any of the functions in those stubs.

**Comment by orklah** [comment]
Not sure I understood, please provide an example.

Also, this seems like the situation for which baselining was introduced

**Comment by orklah** [comment]
This is waay too specific to consider adding
