### ISSUE TITLE
MixedInferredReturnType vs MixedReturnStatement 

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9751]
The examples in .md for both are pretty much identical
And they always occur together.

https://psalm.dev/r/6ea0c210bb

`MixedInferredReturnType` seems redundant to me, since it's already reported by `MixedReturnStatement` (which is better, as it reports every return statement)

**Comment by orklah** [comment]
Seems fair, I couldn't find an instance where those two aren't emitted for the same issue on the same place

**Comment by robchett** [comment]
I've always hated having to suppress that issue twice, so happy to open a PR https://github.com/vimeo/psalm/pull/9783

**Comment by weirdan** [comment]
Fixed in #9783
