### ISSUE TITLE
Fixing the failing test about mocking a final class on Windows

### ISSUE THREAD

**Issue by tscni** [vimeo/psalm#9755]
> 1) Psalm\Tests\IssueBufferTest::testFinishDoesNotCorruptInternalState
PHPUnit\Framework\MockObject\ClassIsFinalException: Class "Psalm\Codebase" is declared "final" and cannot be doubled

Fyi, I've identified the issue and created a PR on `nunomaduro/mock-final-classes` to fix it: https://github.com/nunomaduro/mock-final-classes/pull/4
Once merged and released, the issue should just resolve itself.

Basically luck just ran out and `IssueBufferTest` is now in the same test chunk as `InternalCallMapHandlerTest`.
ParaTest analyzes data providers before calling into PHPUnit, but `nunomaduro/mock-final-classes` currently only starts applying the final-bypass when the autoloader is called via a `phpunit` entrypoint.
Additionally, on Windows the OPcache is shared between processes. (Windows tests run with `opcache.enable_cli=1`)

So in this case `InternalCallMapHandlerTest::callMapEntryProvider()` loads `Codebase` into shared memory via `ProjectAnalyzer` and then the bypass code never has a chance to remove the `final` keyword when ParaTest / PHPUnit is actually running the tests.

**Comment by orklah** [comment]
That's awesome! I didn't have a clue how to proceed! Thanks!

**Comment by tscni** [comment]
This is now resolved :)

**Comment by orklah** [comment]
Awesome!
