### ISSUE TITLE
False positives: PossiblyFalseOperand and PossiblyFalsePropertyAssignmentValue raised when using date functions

### ISSUE THREAD

**Issue by Alkisum** [vimeo/psalm#9756]
It seems like `PossiblyFalseOperand` and `PossiblyFalsePropertyAssignmentValue` are raised when using [date](https://www.php.net/manual/en/function.date.php) and [gmdate](https://www.php.net/manual/en/function.gmdate.php) functions, as shown in this snippet: https://psalm.dev/r/b56da40fc6 .

The PHP documentation specifies that the return type of these 2 functions is `string`, so I wouldn't expect `false` to be returned.

**Comment by orklah** [comment]
Here's some cases where date/gmdate used to return false:
https://3v4l.org/PHCSS#v730

However, some notes:
- It used to happen on invalid inputs
- It doesn't happen on PHP8 (invalid input emits an exception)
- The invalid input is correctly raised by Psalm as an error

In these case, we're used to removing the false value for invalid input altogether, so yeah, this is indeed an enhancement

False value is added here: https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Provider/ReturnTypeProvider/DateReturnTypeProvider.php#L67

Care for a PR?
