### ISSUE TITLE
Getting an `InaccessibleProperty` even though the scope of a property is public

### ISSUE THREAD

**Issue by abcapili** [vimeo/psalm#9757]
https://psalm.dev/r/3c5f0f4091

Insights as to why this might be a bad practice is appreciated

**Comment by orklah** [comment]
You asked the same question last week. Answer has not changed: https://github.com/vimeo/psalm/issues/9722#issuecomment-1527854728

**Comment by abcapili** [comment]
@orklah, sorry about that... I didn't realize they were the same. But my argument is that this **error is confusing.** Obviously the property is **NOT "inaccessible" since it is public** but readonly. 

Regarding the error you described from https://3v4l.org/PL8MT, I believe it's a good error to get. That way everyone could understand that a public readonly property is sort of a "set once" property.

I hope you could reconsider reopening this issue.

**Comment by abcapili** [comment]
To add... With the introduction of `readonly` properties in PHP 8.x, it would totally reduce code size and effort since you won't need to add accessors to your VOs/DTOs.

Thanks.

**Comment by orklah** [comment]
I agree that the error message is confusing. If you would like to help, you can propose a PR to improve it!

It's emitted from https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/InstancePropertyAssignmentAnalyzer.php#L396
