### ISSUE TITLE
uncaught exception - Object-like type must be array

### ISSUE THREAD

**Issue by WDD-Marv** [vimeo/psalm#976]
https://getpsalm.org/r/b9e7302198

> Psalm runner output: 
>
> Internal Psalm error on line 317 - Object-like type must be array

```php
/**
* @return Generator{string, PDOStatement}
*/
function foo(string ...$s) : Generator {
    foreach ($s as $thing) {
      
      yield $thing => new PDOStatement();
    }
}

foreach(foo(['a', 'b', 'c']) as $thing => $things) {
  foreach ($things as $row) {
    
  }
}
```

**Comment by weirdan** [comment]
What did you expect in this case?

You probably need `Generator<string,PDOStatement>`. Curlies are for shapes, and they are indeed arrays only.

**Comment by WDD-Marv** [comment]
@weirdan thanks for the suitable syntax :)

it's mostly that uncaught exceptions & other non-parsed errors are impacted by psalm/getpsalm.org#3

**Comment by muglug** [comment]
Thanks!
