### ISSUE TITLE
Cannot determine the type of the object on the left hand side of this expression

### ISSUE THREAD

**Issue by 0x00A1FA** [vimeo/psalm#9791]
Hi,

See the following Laravel code below:

```php

    public function subteams()
    {
        return $this->belongsToMany(Subteam::class, SubteamUser::class)
            ->withPivot(['is_responsible', 'shift_start_time', 'shift_end_time'])
            ->withTimestamps()
            ->as('membership');
    }

    public function subteamsWhereIsResponsible()
    {
        return $this->subteams()->wherePivot('is_responsible', true);
    }

    public function subteamsWhereIsResponsibleWithRefinerySubsampleTestsInAnalysis()
    {
        return $this->subteamsWhereIsResponsible()->with('refinerySubsamplesInAnalysis');
    }
```

Why am I getting this error?

![image](https://github.com/vimeo/psalm/assets/110613761/5e29f241-c1c2-4dc9-9b81-3bbaaf740cb0)

I'd like to get rid of the error without any annotations. Is this possible?

Thank you!

**Comment by orklah** [comment]
You will have to tell Psalm what `subteams` returns. You could do this by adding the type in the method signature, adding some phpdoc or stubbing the method.

But if you're against adding phpdoc, you'll have a hard time using Psalm or any other static analysis tool. You can't put enough information in code alone right now in PHP
