### ISSUE TITLE
Use strict in_array in if condition to assert needle type

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#980]
```php
<?php
/** @param void ...$_p */
function type(...$_p): void {}

/** @var mixed */
$a = null;

type($a); // mixed, as expected

if (in_array($a, [1,2], true)) {
  type($a); // could be narrowed down to int with the if condition
}
```
**Expected**: `$a` is `int` in the `if` block
Note: `in_array` should only be considered type-asserting when third parameter is true.

**Comment by muglug** [comment]
Thanks, this was just a bug concerning the special case where the original var (`$a` above) is `mixed` before the conditional asserting literal types.
