### ISSUE TITLE
Several method_exists calls cause Psalm to exhaust memory

### ISSUE THREAD

**Issue by edsrzf** [vimeo/psalm#9808]
For whatever reason, six seems to be the magic number: https://psalm.dev/r/c92dc4976b

The error says:

```
PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 4294967304 bytes) in src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MissingMethodCallHandler.php on line 372
```

Looks like exponential memory growth?

**Comment by edsrzf** [comment]
I notice we end up with lots of duplicate strings inside the `existent_method_ids` property. If I add an `array_unique` call around the `array_merge` on the line where the error is, checking completes without running out of memory. Seems like we could also turn that property into a string-keyed array to have the same effect, although that requires a fair bit of additional refactoring and I'm not sure what implications there might be.

**Comment by orklah** [comment]
I wouldn't expect this to have major consequences so it may be worth a try. Otherwise, array_unique seems good too :)
