### ISSUE TITLE
sprintf return type inconsistent

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9819]
https://psalm.dev/r/439491af3d

There should be an error for `non-empty-string` in both cases, not only in the case with %d.

It seems there is some return type provider in psalm for this already, but I couldn't find it. @orklah could you point me to the file that has it?

**Comment by orklah** [comment]
It's handled by the conditional return here: https://github.com/vimeo/psalm/blob/bd0ba6ee957a1789cf5c5fe647893bfe3bda2425/stubs/CoreGenericFunctions.phpstub#L1282
