### ISSUE TITLE
UndefinedThisPropertyFetch cannot be suppressed

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#9821]
In my psalm.xml I have 

```xml
    <issueHandlers>
        <!-- ... -->
        <UndefinedThisPropertyFetch errorLevel="suppress" />
        <!-- ... -->
```

and yet, psalm 5.12 still reports these issues.

This issue happens since 5.10 and later.

**Comment by orklah** [comment]
I can't reproduce with this snippet ```<?php
class A {
    /**
     * @psalm-suppress MixedMethodCall
     */
    public function foo(object $a) : void {
        $a->bar("bat" . $this->baz);
    }
}
```

**Comment by pilif** [comment]
the reproducer is this:

https://psalm.dev/r/920f2c09cb

it's, however, fine with a `@psalm-suppress` at line 16. What doesn't work is the suppression through `psalm.xml`, but I don't see a way to do this on psalm.dev.

**Comment by orklah** [comment]
What you need to suppress is [UndefinedThisPropertyAssignment](https://psalm.dev/040) not UndefinedThisPropertyFetch

**Comment by weirdan** [comment]
Closing as stale.
