### ISSUE TITLE
PropertyNotSetInConstructor with abstract constructor

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9830]
https://psalm.dev/r/f0411b4fa2

An abstract constructor cannot contain any code, therefore reporting `PropertyNotSetInConstructor` on the class does not make sense (line 7)
Btw without the abstract constructor it works correctly (no false positive error): https://psalm.dev/r/39534b5051

**Comment by ygottschalk** [comment]
Consider this:
https://psalm.dev/r/0dec2365d4
I think the abstract constructor does set the property this way.

**Comment by orklah** [comment]
@kkmuffme 
> what is the suggested/easiest way to check if the constructor is abstract or not (aka get the MethodStorage for the construct function)? Then I'll quickly PR this.

Yeah, that's the easiest way
