### ISSUE TITLE
`@method` annotation is ignored for calls from the same class scope

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#984]
https://getpsalm.org/r/db41b5cdc1
```php
<?php
  /**
   * @method I[] work()
   */
  class I {
     function __call(string $method, array $args) { return [new I, new I]; }
     
     function zugzug(): void {
       strlen($this->work()); // mixed, but should be array
     }
  }

  $i = new I;
  strlen($i->work()); // array as expected
```
**Expected**: both `strlen`s should fail with 'expecting string, array given'
**Actual**: psalm infers array return type in second case only.

**Comment by muglug** [comment]
Similar to https://github.com/vimeo/psalm/issues/798, I misunderstood when magic methods were invoked
