### ISSUE TITLE
Using plugin entry point in non-dev library

### ISSUE THREAD

**Issue by romm** [vimeo/psalm#9847]
Following up https://github.com/CuyZ/Valinor/issues/379, I discovered that using:

```xml
<plugins>
    <pluginClass class="CuyZ\Valinor\QA\Psalm\ValinorPsalmPlugin"/>
</plugins>
```

…doesn't work because the class is not loaded; that makes sense because the library autoloads QA tools only in dev-mode, see https://github.com/CuyZ/Valinor/blob/861c3b9da7f5c762db11da2ba9bbfc1cbdeaace8/composer.json#L39-L44

I thought that changing the `<pluginClass …>` config with `<plugin filename="vendor/cuyz/valinor/qa/Psalm/ValinorPsalmPlugin.php"/>` would solve this, but in #3459 it was stated that "file based plugins don't get the `PluginEntryPointInterface` invoked".

A way to solve this is to add the entry below in the `composer.json` file, but I'd prefer another way where the user doesn't have to do this and just have to include the plugin in the `psalm.xml` file.

```json
"autoload-dev": {
    "files": [
        "vendor/cuyz/valinor/qa/Psalm/ValinorPsalmPlugin.php"
    ]
}
```

Would it be possible somehow to include `PluginEntryPointInterface` instances when using `<plugin filename="…">` syntax?

Or do you see any other easy way to do something similar?

Thank you, have a good day! ☀️

**Comment by orklah** [comment]
> doesn't work because the class is not loaded; that makes sense because the library autoloads QA tools only in dev-mode

Can you tell me more about that? Is the user of your library is in dev-mode himself? If so, it should be able to autoload, otherwise it should not have the need to run Psalm?

**Comment by romm** [comment]
Hi @orklah thanks for the answer.

Even in dev-mode, Composer wont load `autoload-dev` sections of dependencies, this is easily reproducible thanks to https://github.com/rubenrubiob/valinor-sample, just clone the repo and run :

```bash
composer install
vendor/bin/psalm
```

This leads to the following error: `Uncaught UnexpectedValueException: CuyZ\Valinor\QA\Psalm\ValinorPsalmPlugin is not a known class`.

**Comment by boesing** [comment]
dev autoloaders are meant to be used while developing the project where the dev autoloaders are needed. These are never published to upstream projects the same way as dev requirements.

If the plugin is meant to be used in upstream projects, why not pushing it into non-dev autoloader?
Thats basically how every plugin works:
https://github.com/psalm/psalm-plugin-phpunit/blob/ad948801b278091709304d4f01c37a21d073b2da/composer.json#L37
https://github.com/psalm/psalm-plugin-doctrine/blob/d77df7869e574dcd81908e3076297c155bb19166/composer.json#L62
https://github.com/boesing/psalm-plugin-stringf/blob/2c75446ad763ac217e065e16f06391d7c16483ee/composer.json#L30

**Comment by romm** [comment]
Hi @boesing thanks for taking time to investigate.

The issue is that `cuyz/valinor` does provide both a mapping API and a Psalm plugin in the same package, which is maybe not the best thing to do. If you see no other way to tell Psalm to include a given file, I guess I'll update the `autoload` section in `composer.json`.

@Maintainers you can close the issue if they think the problem cannot be solved with another way. 😉

**Comment by boesing** [comment]
You might also want to change package type to psalm-plugin. That will enable psalm to show your plugin when running `vendor/bin/psalm-plugin`. But no clue if that has drawbacks when not only a psalm plugin is provided.

**Comment by orklah** [comment]
Sorry, I don't think I'll be able to help much on that, I have no particular knowledge on composer arcane I fear :p

I'll close this but don't hesitate to still add to the discussion, it could be helpful if we have this kind of question in the future
