### ISSUE TITLE
Meta: disable bot snippets found

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9852]
Could we please disable the bot comments for `I found these snippets:` (the other message are fine)

They're useless and super annoying, as you can't turn off notifications/block the bot.
It's disturbing to the read flow of issues and PR comments and spams you with email notifications that will lead you to miss actual relevant comments by human users.

**Comment by orklah** [comment]
They're pretty great for archives though. Psalm.dev doesn't store the result of a snippet. Looking at older issues, it can help see what the issue looked like when it was created and compare it to the result now
