### ISSUE TITLE
LessSpecificReturnStatement not working for non-class

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9859]
https://psalm.dev/r/0e5651df79

Line 15 should have a `LessSpecificReturnStatement` error, line 23 too
It seems it only works for class cases?
(the opposite "MoreSpecificReturnStatement" works in all cases though)

**Comment by orklah** [comment]
I think [LessSpecificReturnStatement](https://psalm.dev/129) is less strict and allows coercion for scalars. Not sure why though

**Comment by ygottschalk** [comment]
Np you are welcome =D

**Comment by ygottschalk** [comment]
Np you are welcome =D
