### ISSUE TITLE
Remove MoreSpecificReturnType

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9860]
since it's already better handled by LessSpecificReturnStatement

Same as "Mixed" already done in https://github.com/vimeo/psalm/issues/9751

See bug though https://github.com/vimeo/psalm/issues/9859

**Comment by orklah** [comment]
In #9751, both issues were reported on the same line and always in pairs

You can have multiple LessSpecificReturnStatement for one method and it's at a different place than MoreSpecificReturnType :
https://psalm.dev/r/0a363432d8

That's on purpose
