### ISSUE TITLE
Inherit parameter types?

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#9864]
Hi,

See https://psalm.dev/r/742950aedf

I thought adding `@inheritdoc` could solve it, but it doesnt.

Regardless i was wondering if it should be inherited implicitly?

Also https://phpstan.org/r/565886f5-4ed3-40d9-9076-1d2502671da4 :fearful:

**Comment by orklah** [comment]
IIRC, this was by design. If you want to have another docblock, it should mention every variable. (otherwise you could have weird interactions between the signature type in the child method vs the docblock type in the parent method

**Comment by ro0NL** [comment]
> it should mention every variable

i find that boring and error prone :thinking: 

added them to the baseline :rocket:
