### ISSUE TITLE
False-positive `MoreSpecificReturnType` when assigning and narrowing type inside `if` condition itself

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#9871]
https://psalm.dev/r/ca137c5498

**Expected**: no errors.
**Got**: `LessSpecificReturnStatement`, `MoreSpecificReturnType`.

Probably related to #9870.

**Comment by fluffycondor** [comment]
A real-world example yielding `InvalidReturnStatement` and `InvalidReturnType` for the same reason:
https://psalm.dev/r/cc01f01a7a

**Comment by orklah** [comment]
this was fixed it seems, I'm not really sure what fixed it though

**Comment by fluffycondor** [comment]
> this was fixed it seems, I'm not really sure what fixed it though

The second example is still yielding errors: https://psalm.dev/r/cc01f01a7a

**Comment by orklah** [comment]
Psalm is right though, your $value is a string (because of line 17) so it can't be an positive-int in the end

**Comment by fluffycondor** [comment]
> your $value is a string (because of line 17)
But below there's `intval()` at the line 23 :)

**Comment by orklah** [comment]
Indeed, can you create a new issue for this please?

I think the cause is pretty different than the rest

**Comment by fluffycondor** [comment]
Done! #10013
