### ISSUE TITLE
SprintfReturnTypeProvider not working well with array unpacking

### ISSUE THREAD

**Issue by fancyweb** [vimeo/psalm#9873]
Hello, SprintfReturnTypeProvider crashes when sprintf is used with array unpacking because it considers there's one arg only, eg:
```php
$array = ['foo', 'bar', 'ccc'];
sprintf('%s %s %s', ...$array);
```

**Comment by fancyweb** [comment]
Some real code that show the bug: https://github.com/symfony/symfony/pull/50565/files

**Comment by fancyweb** [comment]
https://psalm.dev/r/260236cf5b

**Comment by mrVrAlex** [comment]
@orklah @kkmuffme PR not full resolved this issue, look this case: https://psalm.dev/r/308b6b4ae5
Should I open new bug issue? Or just re-open it?
