### ISSUE TITLE
Uncaught Psalm\Exception\CodeException: Error with core stub file docblocks: InvalidDocblock

### ISSUE THREAD

**Issue by DRoss66** [vimeo/psalm#9886]
This error started showing up last night during our Psalm scan and is causing a crash.  Are there any suggestions on how to move past this?  I'm relatively new to Psalm and PHP, so apologies if this is obvious.

`Scanning files...
Uncaught Psalm\Exception\CodeException: Error with core stub file docblocks: InvalidDocblock - ../../composer/vendor/vimeo/psalm/stubs/CoreGenericFunctions.phpstub:1737:1 - Template F has invalid as type - int-mask types must all be integer values in /composer/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php:571

Stack trace:
#0 /composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(230): Psalm\Internal\PhpVisitor\ReflectorVisitor->leaveNode()
#1 /composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#2 /composer/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(79): PhpParser\NodeTraverser->traverse()
#3 /composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(554): Psalm\Internal\Scanner\FileScanner->scan()
#4 /composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(782): Psalm\Internal\Codebase\Scanner->scanFile()
#5 /composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(428): Psalm\Internal\Codebase\Scanner->scanAPath()
#6 /composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(280): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#7 /composer/vendor/vimeo/psalm/src/Psalm/Codebase.php(505): Psalm\Internal\Codebase\Scanner->scanFiles()
#8 /composer/vendor/vimeo/psalm/src/Psalm/Config.php(2297): Psalm\Codebase->scanFiles()
#9 /composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(551): Psalm\Config->visitStubFiles()
#10 /composer/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(370): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#11 /composer/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run()
#12 /composer/vendor/bin/psalm(119): include('...')
#13 {main}
(Psalm dev-master@99a54fb7bbdf498c3f997[32]()3d977b50af6212 crashed due to an uncaught Throwable)
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Psalm`

**Comment by orklah** [comment]
uh, weird, someone made a similar feedback yesterday on slack.

Could you run with --debug-by-line and post here the few lines around where Psalm stops?

**Comment by DRoss66** [comment]
I am using Psalm Github Actions, so not sure how to run with the --debug-by-line in my yml file. I don't have command line access to run this.

**Comment by ygottschalk** [comment]
Is the repo open source? If so, a link would be helpful.
If not, can you provide a reproducer? A small repo containing a similar github actions yml and a bit of sample code to show the error.
If not, you can try to locate the psalm command in the .yml ([something like this](https://github.com/doctrine/orm/blob/2.15.x/.github/workflows/static-analysis.yml#L103)) and add --debug-by-line to that and post the (relevant parts of the) results.
Also some info about the system / github runner could be helpful. ubuntu / debian / ... / windows ... stuff like that

**Comment by ygottschalk** [comment]
@orklah I think it is because one of the `GLOB_*` constants is not defined, [this](https://github.com/vimeo/psalm/pull/9878/commits/a130e2f06ca03d58f6aed4ed38fe1c506cb01299#diff-483b988f07809c751ac53f905f9b4dc8b0093e9af15578ee3ac009b9dfe394b5R1720) will not work.
Can we stub those constants if they do not exist on the system?

@DRoss66 which php version?

**Comment by orklah** [comment]
yeah we can stub those

**Comment by DRoss66** [comment]
PHP Version 7.4.  thanks!
