### ISSUE TITLE
Incorrect return types for stubbed core functions depending on PHP version

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9888]
https://psalm.dev/r/7106f13383

in PHP 8 `vsprintf` will never return false, but in PHP 7 it will.
As discussed in https://github.com/vimeo/psalm/pull/9877#issuecomment-1583319344 the stubs will never fall back to the callmap - this makes declaring different return/param types between PHP versions impossible in psalm.

I suggest to change it to fall back from the stubs to the callmap if the param/return type is not declared in the stubs (but is in the callmap)

Also somehow related to https://github.com/vimeo/psalm/issues/9843 since atm no consistency checking happens in-between the different versions of the callmap and the stubs either

**Comment by ygottschalk** [comment]
I thought that we have the files `stubs/Php8X.phpstub` for that...

**Comment by orklah** [comment]
> I thought that we have the files stubs/Php8X.phpstub for that...

Yeah, that is a first option. We also have this:
https://github.com/vimeo/psalm/blob/bd0ba6ee957a1789cf5c5fe647893bfe3bda2425/stubs/CoreGenericFunctions.phpstub#L66

For anything that those two tools can't answer, TypeProviders are the go to.
