### ISSUE TITLE
Wrong TypeDoesNotContainNull determination

### ISSUE THREAD

**Issue by chriskapp** [vimeo/psalm#9894]
Hi, I have found also another case where Psalm thinks that in the example the `$existing` variable does not contain `null` s.

https://psalm.dev/r/74b5ec5ba5

But it could be `null` in case `$foo` is `1` and `$bar` is `null`. It looks like Psalm does not recognize the `elseif` and thinks that there is a standalone `if` which would indeed remove the `null` type.

Maybe this is also related to #7099

**Comment by chriskapp** [comment]
If the `elseif` block is moved into a separate `if` inside an `else` it works like expected s.
https://psalm.dev/r/d274855806

**Comment by theodorejb** [comment]
Is this issue still relevant? It looks like it was fixed.

**Comment by weirdan** [comment]
I believe this is fixed in #9922
