### ISSUE TITLE
Expected psalm suppression time?

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#9918]
Hi,

We're running psalm in GitHub actions.

On our develop branch we suppress any issue :grimacing: 

The command running is: `psalm --no-progress --output-format=github --set-baseline=psalm-baseline.xml --update-baseline`

Initially ~40 MB of cache was successfully restored.

The runtime takes about ~2m, for a commit that didnt do any code changes. It's actually about the same time a commit with few code changes takes.

Is this expected, or am i missing something?

**Comment by orklah** [comment]
Unfortunately, I have no answer to your main question. However, i can say that --set-baseline makes --update-baseline redundant (the first one recreate the baseline completely while the second one only adds new issues in the existing baseline). Maybe using only the one you need would change something?

**Comment by ro0NL** [comment]
unfortunately it doesnt make any difference, but removed --update-baseline either way 

the bottleneck is definitely --set-baseline, since without it but with the same cache i get instant errors after modifying a file

so we need 2m for some baseline file IO :thinking:

**Comment by ro0NL** [comment]
it seems the cache is just ignored/invalidated when using --set-baseline

looking at --debug output, i see a lot of `Getting+Analyzing` with --set-baseline, but mostly `Have populated` without it

**Comment by ro0NL** [comment]
im gonna assume things happen for some reason
