### ISSUE TITLE
Intersection of two iterables disregards type parameters of the second one

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#992]
https://getpsalm.org/r/16365a9e8c
```php
<?php
/** @var iterable<mixed,mixed>&iterable<mixed,int> */
$a = [];

foreach ($a as $elt) {}
```
Here's the effective type is (supposed to be) `iterable<mixed,int>`, however Psalm reports `$elt` as mixed (should be int). It's also interesting to consider other (generic) iterable types, such as `array<...>`, `Traversable<...>` and `IteratorAggregate<...>` and how they should be intersected with `iterable<...>`

**Comment by SignpostMarv** [comment]
`mixed` is effectively `scalar|array|object|resource|null`, where `scalar` is `string|int|float|bool`

wouldn't this be interpreted as `iterable<mixed, mixed|int>`, which is effectively just `iterable<mixed, mixed>` ?

**Comment by weirdan** [comment]
I can't reproduce this anymore, it's working as expected now: https://psalm.dev/r/384b282722

**Comment by weirdan** [comment]
Nope, it's just latter iterable taking precedence now: https://psalm.dev/r/ff82237126 , so bug is still there.

**Comment by muglug** [comment]
This is fixed
