### ISSUE TITLE
Hanging when using a big case statement of constants in a foreach $key => $value

### ISSUE THREAD

**Issue by jeremy-smith-maco** [vimeo/psalm#9926]
When looping over an array using `foreach ($array as $key => $value)` with a large case statement of constants it seems to hang for a long time. Might be something related to #6741 or maybe not but it was the closest issue I could find to this.

It works fine for scalar values like strings, break the number of cases up into smaller blocks and also works if you're looping over values using `foreach ($array as $value)` but not in this case. 

I have a reproduction case: https://psalm.dev/r/4d3d94a149

**Comment by orklah** [comment]
Reproducible without the foreach: https://psalm.dev/r/cbaddaa911

Switch resolution is a big performance hog in Psalm

**Comment by jeremy-smith-maco** [comment]
Thank you so much for your swift response and fix!
