### ISSUE TITLE
Issue with using interface that is extended with template variable.

### ISSUE THREAD

**Issue by vuryss** [vimeo/psalm#9928]
When method expects interface as parameter and you pass an entity implementing that interface, but extending a template there it breaks.

Example demonstrates it better than words: https://psalm.dev/r/b132421ed6

**Comment by orklah** [comment]
That's actually the same issue than the other one :)
https://psalm.dev/r/38af487f21

If you push the child type to `method`, then Psalm won't be able to check that you're not doing things that are forbidden to do with the child (the doc link I gave you explain that in details. It takes the example where you'd send a `Collection<Dog>` where a `Collection<Animal>` and then add a `Cat` in the `Collection<Animal>` (that is seen inside the method but is in fact a `Collection<Dog>`
