### ISSUE TITLE
Difference between `isset($neverNull)` and `isset(neverNull())`

### ISSUE THREAD

**Issue by arthur-olafsson** [vimeo/psalm#9949]
When calling `isset()` on something with a non-null type, the resulting type can only be true. Psalm infers this correctly if passed a variable, but not if it's an expression with a clear type:

https://psalm.dev/r/98dcaa0a87

**Comment by orklah** [comment]
isset() on anything that is not a variable will crash: https://3v4l.org/M5Nhc

So yeah, Psalm could catch this early and emit an `InvalidArgument`

If you want to try to get your hands in Psalm, it should be a pretty easy change!

You should get into this loop:
https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Analyzer/Statements/Expression/IssetAnalyzer.php#L21

And as soon as you encounter a statement that is invalid (in this case, a `FuncCall`), you emit the issue exactly like this: https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Analyzer/Statements/Expression/EmptyAnalyzer.php#L43
