### ISSUE TITLE
TaintedTextWithQuotes etc

### ISSUE THREAD

**Issue by semwai** [vimeo/psalm#9958]
Hi I am using psalm and --taint-analysis. But in the end, 90% of the warnings are TaintedTextWithQuotes and TaintedHtml. Is there any way in the config file to remove these Tainted?

I found something similar but it doesn't work

psalm.xml:
```
    <issueHandlers>
        <TaintedHtml>
            <errorLevel type="info"></errorLevel>
        </TaintedHtml>
        <TaintedTextWithQuotes>
            <errorLevel type="info"></errorLevel>
        </TaintedTextWithQuotes>
    </issueHandlers>
```

**Comment by orklah** [comment]
Try using 

```
 <issueHandlers>
        <TaintedHtml>
            <errorLevel type="suppress"/>
        </TaintedHtml>
        <TaintedTextWithQuotes>
            <errorLevel type="suppress"/>
        </TaintedTextWithQuotes>
    </issueHandlers>
```

It should work.

Note that TaintedHtml and TaintedTextWithQuotes are real security issues that you probably should check at some point
