### ISSUE TITLE
Psalm alter provides incorrect class FQDN 

### ISSUE THREAD

**Issue by andrei-dascalu** [vimeo/psalm#9966]
```php
namespace Abc\MyDomain;


class Whatever
{
    public function listStuff(): array
    {
          $list = [];
          for ($i=0; $i<10;$i++) {
                $list[]=new Abc\MyOtherDomain\OtherClass();
          }
    }
}
```

after running the psalm fixer, it adds the following annotation

```php
    /**
     * @psalm-return list<Abc\MyOtherDomain\OtherClass>
     */
    public function listStuff(): array
```

However, afterwards psalm checker still complains like:

```
ERROR: UndefinedDocblockClass - src\Abc\MyDomain\Whatever.php:20:22 - Docblock-defined class, interface or enum named Abc\MyDomain\Abc\MyOtherDomain\OtherClass does not exist (see https://psalm.dev/200)
     * @psalm-return list<Abc\MyOtherDomain\OtherClass>
```

I am not sure whether the problem resides with the fixer or with the analyzer. The fixer could add a leading \ on the namespace (adding it manually no longer results in the error) while the analyzer could read the FQDN specification as-is instead of appending it to the current namespace.

**Comment by andrei-dascalu** [comment]
Unfortunately I can't have 2 separate namespaces on psalm.dev it seems

**Comment by weirdan** [comment]
Not a bug. The original code indeed references `Abc\MyDomain\Abc\MyOtherDomain\OtherClass` (see https://3v4l.org/1TEbV). Thus the type Psalter added is also correct, and it's correctly resolved relative to the current namespace, resulting in `UnderfinedClass` (but you had this issue initially as well), and Psalter cannot fix `UndefinedClass` for you.
