### ISSUE TITLE
Add type detection for PDOStatement::fetchAll(PDO::FETCH_CLASS, SomeClass::class)

### ISSUE THREAD

**Issue by thbley** [vimeo/psalm#9974]
Example fetchAll: https://psalm.dev/r/a9b0c85b47

Add type detection for PDOStatement::fetchAll(PDO::FETCH_CLASS, SomeClass::class): SomeClass[]|false;

Currently PDOStatement::fetchAll() is currently defined as:
```
'PDOStatement::fetchAll' => ['array', 'mode='=>'int', '...args='=>'mixed'],
```
which infers to array<array-key, mixed> instead of array<array-key, SomeClass>

**Comment by orklah** [comment]
Thanks for the feedback!

Turns out we already do something similar for `fetch`: https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Provider/ReturnTypeProvider/PdoStatementReturnTypeProvider.php#L34

It should be pretty easy to adapt this to work with fetchAll too

**Comment by robchett** [comment]
Looks like this issue is resolved? There was quite a lot of discussion on the merge request, but it feels beyond the scope of the tags :)

**Comment by thbley** [comment]
Yes, is resolved.
