### ISSUE TITLE
Psalm crash on undefined function

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#9976]
Hi,

We got the following errror using global psalm/phar on PHP7.4:

```
Uncaught Error: Call to undefined function Symfony\Component\Security\Core\Exception\trigger_deprecation() in /app/vendor/symfony/security-core/Exception/UsernameNotFoundException.php:14
Stack trace:
#0 phar:///usr/local/etc/tools/vendor/psalm/phar/psalm.phar/.box/vendor/composer/ClassLoader.php(571): include()
```

Looking at `vendor/composer/autoload_files.php` i see:

```
'6e3fae29631ef280660b3cdad06f25a8' => $vendorDir . '/symfony/deprecation-contracts/function.php',
```

Adding the file to our project's autoload section explicitly solves it.

Then it complains `Function Symfony\Component\String\u does not exist`, which is also in `vendor/composer/autoload_files.php`:

```
'b6b991a57620e2fb6b2f66f03fe9ddc2' => $vendorDir . '/symfony/string/Resources/functions.php',
```

Adding that file to our composer.json solves it again. But this is weird no? Since the files were already autoloadable.

Looking again at `vendor/composer/autoload_files.php` both files are there twice now, for reasons i cannot explain.

```
'6e3fae29631ef280660b3cdad06f25a8' => $vendorDir . '/symfony/deprecation-contracts/function.php',
'b6b991a57620e2fb6b2f66f03fe9ddc2' => $vendorDir . '/symfony/string/Resources/functions.php',
'4d9e22ed7253dbc8b62c44d81f86902c' => $vendorDir . '/symfony/deprecation-contracts/function.php',
'f08f3e43426e0e9dd740c320839f8936' => $vendorDir . '/symfony/string/Resources/functions.php',
```

**Comment by ro0NL** [comment]
Adding `vendor/symfony/deprecation-contracts/function.php` to `<stubs>` does not work, it MUST be in root composer.json

it seems psalm snifs composer.json rather than actual autoload files or so

**Comment by weirdan** [comment]
> /app/vendor/symfony/security-core/Exception/UsernameNotFoundException.php

This file shouldn't have been included at all. I wonder what's causing it.

**Comment by ro0NL** [comment]
That's from our project :grinning: we require symfony/security, which triggers the function call: https://github.com/symfony/symfony/blob/a6e5b75ecdf1266ab019fbfd7042a5d6efab0c04/src/Symfony/Component/Security/Core/Exception/UsernameNotFoundException.php#L14

So psalm runs at `phar:///usr/local/etc/tools/vendor/psalm/phar`

Project runs at `/app/composer.json` (so im actually looking at `/app/vendor/composer/autoload_files.php`)

**Comment by weirdan** [comment]
> That's from our project

Still, Psalm generally only includes class files if there's something wrong with the autoloader.

**Comment by ro0NL** [comment]
Interesting, the error ONLY happens without cache.

Relevant stacktrace:

```
#1 phar:///usr/local/etc/tools/vendor/psalm/phar/psalm.phar/.box/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/app/vendor/com...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#3 [internal function]: spl_autoload_call('Symfony\\Compone...')
#4 phar:///usr/local/etc/tools/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(258): class_exists('Symfony\\Compone...')
```

i think it's either https://github.com/symfony/symfony/blob/a6e5b75ecdf1266ab019fbfd7042a5d6efab0c04/src/Symfony/Component/Security/Core/Exception/UserNotFoundException.php#L97 or https://github.com/symfony/symfony/blob/a6e5b75ecdf1266ab019fbfd7042a5d6efab0c04/src/Symfony/Component/Security/Core/Exception/UsernameNotFoundException.php#L16C14-L16C35

:sweat_smile:

**Comment by ro0NL** [comment]
It's a (global) PHAR issue. Local from source is OK.

**Comment by ro0NL** [comment]
Let's pretend php functions do not exists. Closing as such.

I created the issue for reference mostly, but feel free to dive in ofc.

**Comment by ro0NL** [comment]
specying the global autoloader solved the trigger_deprecation issue :pray: 

```
autoloader="/usr/local/etc/tools/vendor/autoload.php"
```

**Comment by BafS** [comment]
We have the same issue and adding `<file name="vendor/symfony/deprecation-contracts/function.php" />` to the stubs doesn't help either.

**Comment by BafS** [comment]
Can we re-open this issue or is it better to open a new one? For us it's currently a blocker to upgrade to the new Symfony version (6.4).

**Comment by GrahamCampbell** [comment]
I can replicate this issue, similarly, with another file:

```
Uncaught Error: Call to undefined function Symfony\Component\HttpKernel\Debug\trigger_deprecation() in /data/vendor/symfony/http-kernel/Debug/FileLinkFormatter.php:16
Stack trace:
#0 phar:///data/vendor/psalm/phar/psalm.phar/.box/vendor/composer/ClassLoader.php(571): include()
```

**Comment by ro0NL** [comment]
> or is it better to open a new one?

**Comment by BafS** [comment]
It's exactly the same issue thought, did you find a way to fix it? We should keep this one open instead of duplicating the efforts and history IMO

**Comment by ro0NL** [comment]
Sorry, i forgot to share!

```
require __DIR__.'/vendor/symfony/deprecation-contracts/function.php';
require __DIR__.'/vendor/symfony/string/Resources/functions.php';
```

in a custom `autoloader` worked for us.

Open issues without PR ETA puts the bookkeeping on my end. Eventually i manage my open lists of things.
