### ISSUE TITLE
InvalidReturnType when an instance of a class with the subtype of template

### ISSUE THREAD

**Issue by zoltanka** [vimeo/psalm#9979]
Hey Guys,

If a function is type-hinted to return `Foo<Baz>`, it cannot return a sub-type like: `Foo<Bar>` where `class Bar extends Baz`.

https://psalm.dev/r/441d54531e

Though, normaly - without template - it works.

https://psalm.dev/r/de293180aa

**Comment by orklah** [comment]
You need to declare your template covariant for that to be allowed: https://psalm.dev/r/4ad5f4b2d3

More explanations here: https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance
