### ISSUE TITLE
Psalm is unaware of `__PHP_Incomplete_Class`

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#9983]
In `unserialize` scope, you can end up with an object of `__PHP_Incomplete_Class`.
Using this in unit tests (i.e. to verify that unserialize will properly apply the `allowed_classes` option), psalm fails as the assertion for `assertIsInstanceOf` expects a `class-string`.

https://psalm.dev/r/79df259902
https://3v4l.org/Tcq2Y

**Comment by weirdan** [comment]
Just use `__PHP_Incomplete_Class::class`

**Comment by boesing** [comment]
Yah, that would work as a workaround but I wonder if its worth to add it as some kind of core class such as stdClass?

**Comment by weirdan** [comment]
I think you misinterpreted the error. It would appear with any class name specified as a string, be that `__PHP_Incomplete_Class`, `stdClass`, `Exception` or anything else (https://psalm.dev/r/79aa92492c). For Psalm, the only valid source of `class-string`s is `::class`.

**Comment by boesing** [comment]
Ah! Yes I did. Interesting, I was not aware of that. Was totally in the: "if class exists that would work the same way". I'll close here, thanks for the explanation.
